### ISSUE TITLE
[UX] Layout UI: All "Configure blocks" actions should warn of unsaved changes.

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5588] opened 2022-04-15 23:30 UTC
Follow-up to https://github.com/backdrop/backdrop-issues/issues/1936.

## Description of the bug

In the "Configure Blocks" tab of a layout, if we add a block, it puts up this warning:

<img width="1179" alt="warning" src="https://user-images.githubusercontent.com/29214084/163652215-fe7525b0-6b44-4276-9892-d87fb26665b8.png">

But moving blocks around doesn't create the same warning of unsaved changes, even though unsaved changes exist. For consistency, we should put up a warning for any action on this page that results in unsaved changes, so add the warning for moving blocks.

## Steps To Reproduce

To reproduce the behavior:

1. Go to any layout.
2. Add a custom block: observe the warning is put up. Save the layout.
3. Now move a block. No warning.

**Comment by docwilmot** [comment] 2022-04-16 21:36
Dupe of https://github.com/backdrop/backdrop-issues/issues/1622

**Closed by docwilmot** 2022-04-16 21:36 UTC
Labels: type - bug report, good first issue
