### ISSUE TITLE
[Accessibility] Menu toggle can be tabbed to with keyboard while hidden

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#3195] opened 2018-07-12 19:26 UTC
### Steps to reproduce (if reporting a bug)
Open page, tab past login link (on vanilla fresh backdrop install) before you reach the menu you'll hit the hidden checkbox. If you hit space while you're on it you can make the navigation shut and open.

### Actual behavior (if reporting a bug)
Shouldn't be available to tab to.

**Comment by klonos** [comment] 2018-07-12 22:24
@wesruv while at it, do you think that `.menu-toggle-button` should be getting a focus halo when the user has tabbed to the toggle?

**Comment by herbdool** [comment] 2018-07-13 13:50
@wesruv tested and didn't see any issues. The button was still visible on smaller screens and wasn't able to tab to the button anymore.

Just curious why it used position instead of display. Are there any side effects with this change?

**Comment by wesruv** [comment] 2018-07-13 16:56
@herbdool I'm pretty sure I'm responsible for position, I was overusing it for a while for accessibility things. Position can be used when you don't want it visible, but you want screen readers to pick it up, display: none is for 'it shouldn't exist right now', which is what we want. So really I chose the wrong chose on a multiple choice question.

@klonos I was thinking about that, that's less direct, but I'd be glad to follow up on that in a follow up issue. It's tricky because technically they're focusing on the checkbox, not the label element (which is the part you can see). So I have to think about that.

**Comment by quicksketch** [comment] 2018-07-21 22:03
Thanks @wesruv for this little update. The rational makes sense to me and I confirmed it in the sandbox that the invisible checkbox is no longer accessible on desktop (as it should be, because it doesn't do anything on desktop), but still works on mobile.

Merged https://github.com/backdrop/backdrop/pull/2241 into 1.x and 1.10.x.

**Closed by quicksketch** 2018-07-21 22:03 UTC
Labels: pr - needs review, type - bug report

**Comment by klonos** [comment] 2018-07-26 23:06
...just filed #3214 as a follow-up for the focus indication of the mobile menu toggle.
