### ISSUE TITLE
Backdrop.tableDrag.showWeight warning in console

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#4453] opened 2020-06-24 13:28 UTC
**Description of the bug**

In the console on a node edit page which includes tabledrag:

> `Cookie “Backdrop.tableDrag.showWeight” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite`

**Steps To Reproduce**

To reproduce the behavior:
1. Add a file field that allows multiple values to a content type
2. Begin creating content and upload a file
3. Check the console

**Comment by olafgrabienski** [comment] 2022-09-29 08:30
@laryn I just stumbled about this older issue, and I guess it's a duplicate of https://github.com/backdrop/backdrop-issues/issues/4718 which was fixed. What do you think?

**Comment by kiamlaluno** [comment] 2022-09-30 07:41
Given that both the issues report the same warning, I would say they are duplicates.

**Comment by indigoxela** [comment] 2022-09-30 07:46
Yes, it's a duplicate, and it has been fixed meanwhile, so we can close this issue.

**Closed by indigoxela** 2022-09-30 07:46 UTC
Labels: status - duplicate
