### ISSUE TITLE
[UX][D8]  Allow multiple file/image uploads

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1380] opened 2015-11-29 08:02 UTC
These two modules have been merged in D8 core:
https://www.drupal.org/project/multiupload_filefield_widget
https://www.drupal.org/project/multiupload_imagefield_widget

WP is using https://github.com/enyo/dropzone / https://www.dropzonejs.com. There's also a contrib module for D8: https://www.drupal.org/project/dropzonejs ...with the equivalent for D7 seeming to be https://www.drupal.org/project/dragndrop_upload

<img width="786" alt="screen shot 2018-07-20 at 8 15 08 am" src="https://user-images.githubusercontent.com/2423362/42977268-8b9bed34-8c09-11e8-90ce-f809fc1d7538.png">

<img width="751" alt="screen shot 2018-12-20 at 6 12 21 pm" src="https://user-images.githubusercontent.com/2423362/50296286-d9eda300-0482-11e9-9b2c-6085e6644e32.png">

...or we could use
https://www.drupal.org/project/file_resup. 

If we choose to go with the later, we need to be aware of this warning that's posted on [the project page in d.org](https://www.drupal.org/project/file_resup):

>If you intend to handle large files and use modules like [File (Field) Paths](https://www.drupal.org/project/filefield_paths) that move files after upload, you are strongly advised to [apply this patch](https://www.drupal.org/files/issues/fast_move-1377740-55-D7.patch) or you will lose all the benefit of File Resumable Upload's fast handling of large files.
See https://www.drupal.org/project/drupal/issues/2752783

Part of #378

**Comment by jdanthinne** [comment] 2015-12-20 21:22
For a few months, I've replaced those two modules by https://www.drupal.org/project/file_resup. Very efficient, drag and drop, resumable. Wouldn't it be a better option?

**Comment by klonos** [comment] 2015-12-21 08:48
Thanx @jdanthinne!! I gave it a quick spin and I have to say I was impressed. All these features out of the box and no 3rd party library.

I am changing the title of this issue to make it more general and in order to not dictate which solution we decide to go with regardless what was decided for D8. The intent after all is feature parity and not strict feature "compliance".

**Comment by jdanthinne** [comment] 2015-12-21 10:03
If everybody agrees on this module, I'd be happy to try the merge.

**Comment by klonos** [comment] 2015-12-21 14:29
I tried to locate the issue that introduced this feature in D8 core. The closest I could find is [Support Uploading Multiple Files for HTML5 Browsers via #multiple attribute [#625958]](https://www.drupal.org/node/625958). So, they seem to have implemented [```<input type="file" multiple>```](http://www.w3.org/TR/html-markup/input.file.html#input.file.attrs.multiple).

@quicksketch, your comment from that issue back in Nov, 2009:

> ...Unfortunately this will certainly require extensive changes on the processing side as well, especially taking into consideration things like limiting the number of uploads to a certain number or getting the progress bar working with multiple files being uploaded at once. I doubt that the PECL uploadprogress extension properly supports multiple uploads yet.

> Considering that nearly all of FileField has been moved into Drupal 7, and we're past code-freeze for new features/APIs in Drupal 7, I doubt this feature will ever be added to FileField in an official release. It might be helpful to develop this functionality as a experiment to see what is necessary for its implementation, but unfortunately we probably won't see this officially released in FileField, since this module will be discontinued in Drupal 7 anyway.

Would you say that Backdrop counts as an "unofficial" release? :smile:

**Comment by klonos** [comment] 2015-12-21 14:58
...I am going through that issue. There's a lot of technical/code aspects that are beyond me, but if I got things right, it seems that the initial decision to start off by merging Multiupload Filefield/Imagefield Widget was that they pretty much were the only solid solution available in contrib at the moment and that they were mostly a copy-n-hack version of ```file.module```. The [File Resumable Upload](https://www.drupal.org/project/file_resup) project seems to have come into existence a lot later in [Oct. 2014](https://www.drupal.org/commitlog/commit/71363/947e158b540c3b72c34bf478fa8acad23018a2c6). From an end user PoV, I find it more feature-complete and better looking out of the box, but that's a personal opinion and I understand that code is more important.

There were two aspects of the final goal for D8: a) support multiple uploads b) redesign the File Field UI. The second task was eventually split off in a separate issue: https://www.drupal.org/node/2113931 (I'll file a respective issue for Backdrop shortly)...

@quicksketch I see you a bit more active in that issue after April 2013 where you've done a review and some rerolls, so I imagine you have some insight. Looking forward for your input here.

**Comment by klonos** [comment] 2016-03-06 06:41
How awesome would it be if we could add multiple files here:

![backdrop-project_install_page-allow_multiple_file_uploads](https://cloud.githubusercontent.com/assets/2423362/13552728/ad9499dc-e3c2-11e5-9f45-247a6145bc38.png)

**Comment by jenlampton** [comment] 2017-08-08 19:34
Wow, I hadn't seen https://www.drupal.org/project/file_resup before, thanks for the recommendation @jdanthinne. 

The Drupal 8 approach would mean we would have two widgets, one for a single value, and one for multiple values. Is that a burden we want to put on our site-builders, making them remember to choose the correct one depending on their field settings? And making them remember to change the widget when they change the # of values for a field?

I'm tempted to go with this solution since it would "fix" the existing file and image widgets and would "just work" for people.  However, I wonder about this requirement:

> File Resumable Upload is a pure HTML5 solution and therefore will only work on modern browsers. It automatically degrades to the standard upload widget when unsupported.

Does anyone know exactly which browsers would be left behind if we chose to go this route?

**Comment by jenlampton** [comment] 2017-08-08 19:44
A few thoughts on integrating:
* Remove all the field settings. I would incorporate them instead, as follows:
** `Enable resumable upload`: always enabled
** `Maximum upload size`, Use existing Maximum upload size, remove description text mentioning PHP's maximum post and file upload sizes
** ` Start upload on files added`: always enabled (as this is the norm for Backdrop now anyway)

**Comment by jenlampton** [comment] 2017-08-17 20:20
Bumping to 1.9 so we can have a longer conversation about the suggested approach.

**Comment by olafgrabienski** [comment] 2017-08-25 16:05
> Does anyone know exactly which browsers would be left behind if we chose to go this route? Or which HTML properties we should look up to see?

I (only) guess it's the  `input multiple` attribute, see https://www.w3schools.com/tags/att_input_multiple.asp. Can someone confirm? If so, browser support seems to be very good (http://caniuse.com/#feat=forms), and there would be a reasonable fallback (standard upload widget for single files).

So maybe it's still possible to get multiple file upload in 1.8? Which would give the release a nice focus on file related improvements.

**Comment by jenlampton** [comment] 2017-08-25 19:51
> So maybe it's still possible to get multiple file upload in 1.8? 

I would be happy to can re-tag this issue for 1.8, but I'll need someone (else?) to start working on it asap if we want to get it in. There isn't any code here yet to review and we should really be in the test-and-revise phase for features that need to be committed in the next 2 weeks.

@jdanthinne you don't happen to have any time to spare for this issue, do you? I think we could use some more hands on deck. If you are still willing we would love your help :)

**Comment by laryn** [comment] 2017-08-25 20:07
@jenlampton Would this be a simple port of the module, included in core, or something integrated more deeply?

**Comment by jenlampton** [comment] 2017-08-25 20:18
I haven't looked at the module code recently, but IIRC it simply alters the file upload widget. If that's the case we'd put that same change directly into the file upload widget, instead of using a module to alter it.

**Comment by Graham-72** [comment] 2017-08-25 20:27
@olafgrabienski I have used the input multiple attribute in contrib module views_send and found that it can be used to upload multiple files provided they are in the same folder in Windows. One cannot select files from different folders as far as I can tell.

**Comment by olafgrabienski** [comment] 2017-08-28 15:49
> input multiple attribute (...) can be used to upload multiple files provided they are in the same folder in Windows. One cannot select files from different folders as far as I can tell.

Thanks for the information, that's an important point. I guess in most cases it's sufficient to upload multiple files from only one local folder, at least much better than only one file at a time. That said, are there other, common approaches where you can choose multiple files from different local folders?

**Comment by jenlampton** [comment] 2017-08-28 16:06
The method we are considering for core might!

**Comment by olafgrabienski** [comment] 2018-12-29 00:08
Looks like this issue is a duplicate of #440, isn't it? @docwilmot made a PR there.

**Comment by BWPanda** [comment] 2019-09-02 13:25
I used to use the two multiupload_* modules in D7, now I use https://backdropcms.org/project/html5_upload. That might be worth considering too.

**Comment by diannevolek** [comment] 2021-12-24 15:04
This is great, especially if it includes "Select Existing" on files (not just images), and then adds the files to the file manager for later replacement/renaming.

(See discussion under https://github.com/backdrop-contrib/filefield_sources/issues/15 - File Field Sources isn't adding files correctly to the file manager, and I expect IMCE will be the same.)

**Comment by quicksketch** [comment] 2022-03-15 04:00
That would be wonderful @BWPanda. Take a look at https://github.com/backdrop/backdrop-issues/issues/440 instead... there's already a mostly working PR over there. We should close this issue.

**Comment by BWPanda** [comment] 2022-03-15 06:16
Seems so.

**Closed by BWPanda** 2022-03-15 06:16 UTC
Labels: type - feature request, type - task, needs - more feedback

**Comment by quicksketch** [comment] 2022-03-15 07:07
I'll update the weekly agendas and survey, I think that's why this issue continues to receive so much attention.

**Comment by klonos** [comment] 2022-03-15 07:15
The scope of the 2 issues is different though. #440 is about implementing the "multiple" HTML5 attribute in file upload fields, whereas this here is a feature request to implement a "dropzone"-like upload method.

**Comment by quicksketch** [comment] 2022-03-16 20:55
@klonos All browser already support drag and drop uploads if you drag a file onto an upload field. If #440 is completed, then you'd also be able to drag multiple files onto a single upload field (also natively supported by browsers). Then this issue becomes one of just styling an upload field, if that's something we want.
