### ISSUE TITLE
autocomplete-enabled link field complains that '<front>' is not a valid URL...?

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4855] opened 2021-01-04 03:03 UTC
**Description of the bug**

Trying to create a link to the homepage from an autocomplete-enabled link field, I get an error about `<front>` not being a valid URL. I'm sure this used to work...

**Steps To Reproduce**

To reproduce the behavior:
1. Go to `/node/add/page`
2. Click on the Link icon in the Body field's editor toolbar
3. Enter 'home' in the Link Destination field
4. Click on the matching 'Home (Menu item: `<front>`)' entry
5. Enter a Link Text and Save

**Actual behavior**

Error displayed: "The URL <front> is not valid."

**Expected behavior**

Link successfully created to the homepage.

**Additional information**

![image](https://user-images.githubusercontent.com/2385329/103497458-b1804800-4e95-11eb-9cbf-f552fb411a76.png)

**Comment by olafgrabienski** [comment] 2021-01-11 13:30
Confirmed (on a test site, running Backdrop 1.17.4).

**Comment by indigoxela** [comment] 2021-01-21 16:20
I think, that's not actually a bug, but for sure it's a WTF.

The callback for that autocomplete field is  [function path_autocomplete()](https://github.com/backdrop/backdrop/blob/11619724ae5f80a1edaf957d367ce24c24aca4e4/core/modules/system/system.module#L4085)

It searches for nodes, files, user profiles, taxonomy terms, views pages, layouts and menu links. It does not consider Backdrop's special `<front>` placeholder.

**Comment by indigoxela** [comment] 2021-01-27 09:43
The actual culprit seems to be [function _filter_format_editor_link_url_validate()](https://github.com/backdrop/backdrop/blob/11619724ae5f80a1edaf957d367ce24c24aca4e4/core/modules/filter/filter.pages.inc#L495).

That function's used for both, image src and link href, which makes things a bit more complicated.

If we allow the `<front>` placeholder, we also have to make sure that it gets replaced in filtered content. Not sure yet, if allowing it is a good idea, though.

**Comment by jenlampton** [comment] 2021-01-27 21:21
I ran into a similar problem when entering the URL to translated content. Backdrop was telling me the path was invalid, both with and without the langcode. The only option I had was to edit the source code and type in the link myself. (or, use the `node/NID` path instead).  I'll make a separate issue for that...

**Comment by indigoxela** [comment] 2021-01-30 15:11
The problem with `<front>` should be fixed in #4630.

**Comment by BWPanda** [comment] 2021-01-31 22:49
> The problem with <front> should be fixed in #4630.

👍🏻

**Closed by BWPanda** 2021-01-31 22:49 UTC
Labels: status - duplicate
