### ISSUE TITLE
Views: boolean filters do not show values when Label is `On value`

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2129] opened 2016-09-03 20:18 UTC
If the boolean field setting for `Use field label instead of the "On value" as label` has been marked... When adding a filter to a view for a boolean field, no options are visible. 

Without `Use field label instead of the "On value" as label` the available options should be something like (listed in my order of preference):
- Checked / On / TRUE / 1
- Unchecked / Off / FALSE / 0

With `Use field label instead of the "On value" as label` the available options could be:
- [FIELD_LABEL}
- Unchecked

Steps to reproduce:
1) add a boolean field to a node type
2) Check the box for `Use field label instead of the "On value" as label` in field settings.
3) Create a view of nodes
4) Add a filter to the view for the boolean field you just added.
5) See missing options, as shown below:

![screen shot 2016-09-03 at 1 18 34 pm](https://cloud.githubusercontent.com/assets/397895/18227434/fcdfb43c-71d8-11e6-8d73-97e2c1b9bf69.png)

**Comment by jenlampton** [comment] 2016-09-16 02:57
no PR here, removing milestone.

**Comment by Dinornis** [comment] 2017-05-07 05:52
Closing as duplicate of https://github.com/backdrop/backdrop-issues/issues/1138.

**Closed** 2017-05-07 05:53 UTC
Labels: type - bug report

**Comment by klonos** [comment] 2017-05-07 08:49
@Dinornis 👍 once again.
