### ISSUE TITLE
Cannot remove blocks when switching layouts anymore

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4420] opened 2020-05-24 18:59 UTC
**Description of the bug**

The [documentation](https://api.backdropcms.org/api/backdrop/core%21modules%21layout%21includes%21layout.class.inc/function/Layout%3A%3AsetLayoutTemplate/1) for the `$region_mapping` parameter of `Layout::setLayoutTemplate()` says:

> An array of region names, each keyed by the old region name and the value of the new region name. If empty, all known regions will be copied from one to the other. **To discard the contents of a region, set the value to FALSE.**

However this doesn't always seem to be the case...

**Steps To Reproduce**

To reproduce the behavior:
1. On a new Backdrop site, install and enable the Devel module
1. Note the blocks/regions in the Default layout: `/admin/structure/layouts/manage/default`
1. Go to `/admin/devel/php` and run this code (it changes the layout for the Default layout to 'Boxton' and says to discard all blocks in the process):
   ```php
   $layout = layout_load('default', TRUE);
   $layout->setLayoutTemplate('boxton', array(
     'header' => FALSE,
     'top' => FALSE,
     'content' => FALSE,
     'footer' => FALSE,
   ));
   $layout->save();
   ```
1. Note the blocks/regions in the Default layout now: `/admin/structure/layouts/manage/default`

**Actual behavior**

Blocks are removed from all but the 'Content' region. Blocks from other regions moved to 'Content'.

**Expected behavior**

All regions empty, no blocks remaining.

**Comment by BWPanda** [comment] 2020-05-25 06:04
This bug seems to be the result of https://github.com/backdrop/backdrop-issues/issues/3762 where blocks were assigned to the default region instead of being removed altogether. That's all well and good if wanting to keep all blocks when changing layout templates (the default behaviour), but breaks when you do actually want to remove blocks...

**Comment by BWPanda** [comment] 2020-05-25 06:18
I think the issue is that `FALSE` is used both as a manual way to specify that a region should be emptied as well as to define a region that cannot be mapped. In both cases, blocks are assigned to the default region, whereas that should only happen in the latter case. This [PR](https://github.com/backdrop/backdrop/pull/3152) fixes this behaviour by assigning un-mapped regions an empty string (to differentiate from the value `FALSE`). Testing needed please!

**Comment by klonos** [comment] 2020-05-25 14:36
I have tested this in the PR sandbox, and it now seems to be working as expected when programmatically emptying regions 👍 ...I have also tested changing the layout template manually from the admin UI to a flexi one, that has no default regions -> all blocks were moved to a region of the new template, so the functionality of #3762 was not regressed.

**Closed** 2020-06-20 00:23 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2020-06-20 00:26
At first it sounded like the differentiation between an empty string and `FALSE` was going to be confusing from an API-standpoint. But reviewing the PR I see that the differentiation only matters within a single method and it's all internal. So this seems fine to me.

Thanks @klonos for testing and @BWPanda for fixing the problem! I've merged https://github.com/backdrop/backdrop/pull/3152 into 1.x and 1.16.x. Thanks!
