### ISSUE TITLE
Menu bar "Menu search" searchbox not aligned properly vertically in Bartik.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#707] opened 2015-02-12 03:22 UTC
Seven:

![menu_bar-menu_search_seven](https://cloud.githubusercontent.com/assets/2423362/6161271/973d84e6-b2c2-11e4-9f5b-a26de85c2012.png)

Bartik:

![menu_bar-menu_search_bartik](https://cloud.githubusercontent.com/assets/2423362/6161276/a063767a-b2c2-11e4-8992-a768af30037e.png)

**Comment by quicksketch** [comment] 2015-02-12 03:31
It looks the correct in both themes for me in Chrome and Firefox. Do you by chance have the font size adjusted? There's an issue for the font size causing the admin bar to look a little wonky at https://github.com/backdrop/backdrop-issues/issues/507.

**Comment by klonos** [comment] 2015-02-12 03:34
Just updated to 1.0.3. Confirming that the issue is still there.

@quicksketch nope, no font adjustment (I'm no fun of this sport). Also made sure it is the default size by pressing ctrl+0 just in case.

This is in latest x64 38.0a1 nightly of firefox. Giving it a go on Chrome now...

**Comment by klonos** [comment] 2015-02-12 03:43
It is a bit better on Chrome, but as you can see still a couple pixels off to the bottom in Bartik:

![admin_bar-menu_search_seven_chrome](https://cloud.githubusercontent.com/assets/2423362/6161473/8987815a-b2c5-11e4-84e8-b8d6c664016c.png)

![admin_bar-menu_search_bartik_chrome](https://cloud.githubusercontent.com/assets/2423362/6161475/8f618382-b2c5-11e4-8f69-0aeb5f812d9a.png)

**Comment by klonos** [comment] 2015-02-12 03:47
...same thing in IE11 (for posterity sake):

![admin_bar-menu_search_seven_ie11](https://cloud.githubusercontent.com/assets/2423362/6161512/149d51a2-b2c6-11e4-885b-984117c9347b.png)

![admin_bar-menu_search_bartik_ie11](https://cloud.githubusercontent.com/assets/2423362/6161518/1c5f71c2-b2c6-11e4-8c21-54507ff4cc57.png)

**Comment by BWPanda** [comment] 2015-02-13 04:43
Looks fine to me... I'm running Firefox 35.0.1 and Chrome 40.0.2214.111 on Linux Mint 17.1.

**Comment by klonos** [comment] 2015-02-13 12:47
I'm on Windows 8.1 x64.

**Comment by BWPanda** [comment] 2015-02-13 12:51
> I'm on Windows...

Ah well, there's your problem ;)

**Comment by klonos** [comment] 2015-02-13 12:53
:p

...would could have guessed when I posted the IE11 screenshots.

So, lets wait to see if anyone else running Windows can confirm this.

**Comment by Dinornis** [comment] 2017-05-02 23:44
Does this problem still exist with your configuration?

**Comment by BWPanda** [comment] 2020-08-17 06:31
Just checked again, and can't see any issues with Bartik. Closing as 'cannot reproduce'.

**Closed by BWPanda** 2020-08-17 06:31 UTC
Labels: status - cannot reproduce
