### ISSUE TITLE
Notice: Undefined index: file_field_file_table in file_view_file() (line 3441 of /app/core/modules/file/file.module).

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#5371] opened 2021-11-25 14:56 UTC
## Description of the bug

Getting this notice when viewing a file (e.g. pdf) via the entity url: (file/1 for example):

> Notice: Undefined index: file_field_file_table in file_view_file() (line 3441 of /app/core/modules/file/file.module).

## Steps To Reproduce

1. Upload a file at `admin/content/files`.
2. Change the file display to something other than "Download link" at `admin/structure/file-types/manage/document/file-display`.
2. View the uploaded file by clicking on the link in the Manage files list.
3. Check logs (or display error messages to screen).

The `$display` is odd which will show something like:

```
array (
  'formatter' => 'file_field_file_default',
  'settings' => 
  array (
    'file_field_file_download_link' => 
    array (
      'text' => 'Download [file:name]',
    ),
  ),
)
```

when anything other than download link is chosen. Perhaps they need to match.

# Additional info

First reported https://github.com/backdrop/backdrop-issues/issues/5370

**Comment by argiepiano** [comment] 2021-11-25 15:05
I'm following the steps and am unable to reproduce. I'm using a completely clean install of 1.20.2. 

I tried with file types "image" and "document". See attached screenshots.  

I suspect this may be more complex than it seems.

<img width="710" alt="Screen Shot 2021-11-25 at 8 02 34 AM" src="https://user-images.githubusercontent.com/9938978/143464500-dc6170ae-c3be-48ec-b229-e44d9e57383c.png">

<img width="485" alt="Screen Shot 2021-11-25 at 8 02 45 AM" src="https://user-images.githubusercontent.com/9938978/143464493-8b13b9e9-c9de-4f7a-9807-6c86e51a1e0d.png">
 
<img width="1191" alt="Screen Shot 2021-11-25 at 8 03 40 AM" src="https://user-images.githubusercontent.com/9938978/143464490-fb4c7813-2210-4e61-ba6d-8a8d3c4771ff.png">

**Comment by herbdool** [comment] 2021-11-25 15:12
@argiepiano I updated the steps. Need to change the file display from something other than Download link.

**Comment by argiepiano** [comment] 2021-11-25 15:17
@herbdool  confirming that I'm seeing this issue after following the corrected steps.

**Comment by herbdool** [comment] 2021-11-25 15:45
One option is to check that the settings exist for that formatter, or we could fix `file_display_form` to ensure the right formatter is saved for the settings.

**Comment by argiepiano** [comment] 2021-11-25 16:03
It seems to me that the easiest solution is to do an isset check. The only formatter that has any settings is `file_field_file_download_link`. The other three formatters for documents (for example) don't use any settings.

Something like this in line 3441

```php
      'settings' => isset($display['settings'][$formatter]) ? $display['settings'][$formatter] : array(),
```

**Comment by argiepiano** [comment] 2021-11-25 16:06
Say the word and I'll create a PR with this change...

**Comment by indigoxela** [comment] 2021-11-25 16:11
> Say the word ...

Which one? "Go for it" - that's three. Alohomora? :laughing: Yes, please, a PR with this change. It makes sense.

**Comment by herbdool** [comment] 2021-11-25 16:11
I think it'll be better to have the file formatter save better settings in `file_display_form_submit` *and* have an isset() check (for previous settings).

The display info formatters should match in what is saved in config.

Something like:

```
function file_display_form_submit($form, &$form_state) {
  $file_type = $form['#file_type'];
  $view_mode = $form['#view_mode'];
  $formatter = $form_state['values']['display']['formatter'];
  $settings = isset($form_state['values']['display']['settings'][$formatter]) ? $form_state['values']['display']['settings']: array($formatter => array());

  $display = array(
    'formatter' => $formatter,
    'settings' => $settings,
  );

  file_display_save($form['#file_type'], $form['#view_mode'], $display);
  backdrop_set_message(t('Your settings have been saved.'));
}
```

**Comment by indigoxela** [comment] 2021-11-25 16:13
> I think it'll be better to have the file formatter save better settings

@herbdool are you sure? The settings are in an array and have their proper array keys. Only if a formatter has no settings at all, the array key obviously does not exist. Hence the undefined index.

**Comment by herbdool** [comment] 2021-11-25 16:16
@indigoxela or at least save it with an empty array for settings, so we don't get this:

```
array (
  'formatter' => 'file_field_file_default',
  'settings' => 
  array (
    'file_field_file_download_link' => 
    array (
      'text' => 'Download [file:name]',
    ),
  ),
)
```

which is confusing.

So ideally something like this?:

```
array (
  'formatter' => 'file_field_file_default',
  'settings' => 
  array (
    ),
  ),
)
```

And would still need to check that the key exists, of course.

**Comment by argiepiano** [comment] 2021-11-25 16:23
@herbdool The reason you are getting the weird looking array with the `file_field_file_download_link` key is because, when PHP doesn't find the key it defaults the the first key it finds, resulting in `file_field_file_download_link`.

If you add the fix I proposed above you would get

```
array (
  'type' => 'file_field_file_url_plain',
  'settings' => 
  array (
  ),
)
```

which is correct

**Comment by argiepiano** [comment] 2021-11-25 16:25
Plus, @herbdool , if we go the route of specifying an empty array in settings, I would also suggest we add that empty array in the formatter_info definition in `file_field_formatter_info()`

**Comment by herbdool** [comment] 2021-11-25 16:32
The main thing, I think, is avoiding a config file like this `file_display.document.json` where the formatter and settings don't match:

```
{
    "_config_name": "file_display.document",
    "_module": "file",
    "type": "document",
    "default": {
        "formatter": "file_field_file_default",
        "settings": {
            "file_field_file_download_link": {
                "text": "Download this file [file:name]"
            }
        }
    },
    "preview": {
        "formatter": "file_field_file_download_link",
        "settings": {
            "file_field_file_download_link": {
                "text": "Download [file:name]"
            }
        }
    },
    "full": {
        "formatter": "file_field_file_table",
        "settings": {
            "file_field_file_download_link": {
                "text": "Download [file:name]"
            }
        }
    }
}
```

Whether it's best leave the settings blank or leave off the settings key altogether, I don't know.

**Comment by argiepiano** [comment] 2021-11-25 16:52
That makes sense to me @herbdool . I'll create a PR with both fixes, the one you propose for `file_display_form_submit()`, and the isset check for backward compatibility in `file_view_file()`

**Comment by herbdool** [comment] 2021-11-25 17:11
Thanks @argiepiano.

I adjusted your PR slightly (contrary to what I pasted above) so that what's saved matches what you put in file_view_file().

**Comment by klonos** [comment] 2021-11-25 18:33
I've tested with the steps to reproduce in the issue summary:
- on a demo sandbox -> confirmed the issue/error 👎🏼 
- on the PR sandbox -> no errors 👍🏼 

The code also looks good to me, so RTBC.

**Comment by klonos** [comment] 2021-11-25 18:36
> The code also looks good to me, so RTBC.

...actually there's a tiny coding standard issue (missing space before the `:` in the shorthand conditional).

**Comment by argiepiano** [comment] 2021-11-25 18:41
> ...actually there's a tiny coding standard issue (missing space before the : in the shorthand conditional).

Committed

**Comment by klonos** [comment] 2021-11-25 19:19
Thanks 🙏🏼 ...back to RTBC.

**Closed** 2021-12-03 22:02 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2021-12-03 22:03
Merged https://github.com/backdrop/backdrop/pull/3836 into 1.x and 1.20.x. Thanks @argiepiano, @herbdool, @klonos, and @indigoxela!
