### ISSUE TITLE
'Home' dropdown menu display lag

### ISSUE THREAD

**Issue by matthui** [backdrop/backdrop-issues#3694] opened 2019-04-20 23:11 UTC
**Description of the bug**
When logged in, the 'Home' and dropdown menu do not disappear when mousing over it and immediately switching to the another.  Both menus appear for about half a second.  

**Steps To Reproduce**
To reproduce the behavior:
1. Log in to a backdrop page.
2. Hover over the 'Home' dropdown menu.
3. Hover over the any other dropdown menu immediately after.
4. Hover over the 'Home' dropdown menu after mousing over any other dropdown immediately after.

**Actual behavior**
Screenshot of hovering over 'Home' directly after hovering over 'Content'
![Screenshot (29)](https://user-images.githubusercontent.com/44682827/56463118-ee836e80-6382-11e9-9058-7ae43cebf961.png)

Screenshot of hovering over 'Content' directly after hovering over 'Home'
![Screenshot (31)](https://user-images.githubusercontent.com/44682827/56463117-eb887e00-6382-11e9-8247-43cb9599e58b.png)

Screenshot of hovering over 'Home' directly after hovering over 'Admin bar'
![Screenshot (32)](https://user-images.githubusercontent.com/44682827/56463283-dcef9600-6385-11e9-8075-ca69b00839fa.png)

**Expected behavior**
This issue with the 'Home' dropdown menu does not occur for any combination of other dropdown menus, as the rest only show up one at a time.  

**Additional information**
This issue may occur because the 'Home' menu is an individual menu from all of the others

**Comment by BWPanda** [comment] 2019-04-23 16:09
Thanks for reporting this issue! However it’s actually already been reported in #466, so I'll close this issue as a duplicate of that one.

**Closed** 2019-04-23 16:09 UTC
Labels: status - duplicate
