### ISSUE TITLE
URL Handling: Clean URLs cannot be enabled.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#2488] opened 2017-01-22 06:44 UTC
I have just come across this admin page and was confused

![url settings](https://cloud.githubusercontent.com/assets/10559274/22180612/a6ece150-e06c-11e6-93d3-21cea0718f1e.png)

I see that:
1. The tick box for 'Enable clean URLs' has disappeared but its explanatory text remains.
2. 'Clean URLs cannot be enabled...' would be better shown as a warning.
3. The link 'online handbook' is to drupal.org

When clean URLs are enabled the display is easier to understand.
![url settings2](https://cloud.githubusercontent.com/assets/10559274/22180628/bbc9d550-e06d-11e6-9cfe-cdb54146e412.png)

---
PR by @hosef (fixes the path for the clean URL test page): https://github.com/backdrop/backdrop/pull/2380
Additional PR by @klonos (converts the "orphan" description to an info message and fixes paths in a couple of other places): https://github.com/backdrop/backdrop/pull/2381

**Comment by Graham-72** [comment] 2017-01-22 07:04
And now I am finding, in the second example, that even though it warns me that the clean URL test failed, clean URLs will work for this second site. I guess this is connected with a previous issue https://github.com/backdrop/backdrop-issues/issues/1573 'Detect whether mod_rewrite is enabled (in Apache installs) and throw a warning in the clean URLs page'.

**Comment by laryn** [comment] 2017-03-16 16:06
@Graham-72 
In my case, my host had a `.htaccess` file that seemed to have overwritten the default Backdrop file somehow. When I replaced it and cleared caches the Clean URLs admin screen began working as expected again. This may not be the issue in your case -- but I agree, these errors/warnings were very confusing.

**Comment by BWPanda** [comment] 2018-06-27 10:16
On a new site (hosted on a server with other Backdrop sites that have clean URLs enabled), I'm suddenly getting the issue shown in the first screenshot above.

As per https://www.drupal.org/node/15365#falsenegatives, I accessed that page via it's clean URL, and the checkbox appeared. I ticked it and now things are working properly again.

So there seems to be the same bug here that Drupal has: https://www.drupal.org/node/1178850

**Comment by hosef** [comment] 2018-11-12 20:17
I ran into this issue on one of my sites, and decided to look into it. Apparently, the path being used on the clean URLs page to run the test did not match the menu entry for it, so it would always fail, even when clean URLs were working just fine.

**Comment by hosef** [comment] 2018-11-13 16:49
I took a look at your PR, and it looks good. The code changes all look good, and the messages are definitely easier to notice and read as an info message.

**Comment by klonos** [comment] 2018-11-13 17:18
Thanks @hosef 👍

Note to @quicksketch @serundeputy: both PRs listed in the issue summary need to be merged; one is *additional* to the other - not alternative. Thanks.

**Comment by klonos** [comment] 2018-11-19 16:59
@herbdool I did think of that too (to not have the "online handbook" link in the help text point to the respective d.org page). My only problem currently is the same as the reason why we currently still have dozens of d.org links/mentions throughout our codebase: there is a lot of info and comments in d.org that go back for years + a lot of that documentation is not just a simple copy-paste, because we have have change many things in Backdrop (for the better 😄).

Having said that... yes, of course I can do that: https://backdropcms.org/user-guide/clean-urls 😉 

...it's a start; the d.org page is h-u-g-e and we need to break it down to sections (book pages) + in Backdrop we have pathauto enabled by default, so things will need to be rewritten. I do not have time for this right now, perhaps next weekend (unless someone else beats me to it). I have for now included only the first "intro" section, but our documentation pages allow specifying an "Original source" link, which I have provided already, linking to the original d.org documentation.

**Comment by klonos** [comment] 2018-11-19 17:03
...and I have updated the URL in the PR to point to our docs 😉

**Comment by gdvallance** [comment] 2018-11-19 21:07
I cannot for the life of me get clean URLs to enabled in a clean install of Backdrop, on an Ubuntu 16.04 server running Apache2 with other Drupal 7 and Drupal 8 sites *with* clean URLs enabled. Same applies to IONOS (aka 1&1 hosting).

I too get the screen as above. Moreover, if I manually make clean URLs they seem to work. Any tips for getting them to work, or should I wait till the next version? 

Happy to try and test the fix if folks give directions. I am fairly new to this kind of work.

Would like to do a little bit towards helping this fantastic project.

**Comment by klonos** [comment] 2018-11-20 00:59
Hello @gdvallance and welcome onboard 😄

...I am sorry that you are having this problem. We have been discussing getting a fresh 1.11.3 version out since we have now accumulated a nice set of fixes (including this old one here, which might fix your problem). You can be part of the discussions if you want to join our Gitter chat, or watch the next weekly dev meeting coming up this Thursday (you can find more info about these here: https://backdropcms.org/support/resources).

Please bear with us as we are trying to address as many of the D7 annoyances as possible, as fast as we can 😄

...having said all that, if the next bug fix release does not fix your issue, please comment back here, or ping us on Gitter. I think that I have detailed documentation buried somewhere on my old NAS about setting up Drupal clean URLs in Ubuntu (worked for me since 10.04 😉). This might help you.

**Comment by klonos** [comment] 2018-11-20 01:00
...oh, there might not be a meeting this Thursday though. Thanksgiving and all 😄

**Comment by gdvallance** [comment] 2018-11-20 21:04
Thanks @klonos . The welcome is appreciated. Happy to bear with you and to assist if I can. 

Look forward to the bug fix. The thing is, I have clean URLs working on *other* D7 & D8 instances on that server. They are all using the same Apache2 webserver so I *know* `mod_rewrite` is working etc., otherwise, these instances would not have clean URLs. Consequently, it should be something specific to Backdrop and therefore I have high hopes that the new version will solve the problem. 

What can I do for the project? My time and expertise are minimal but would like to help. 

I had not realised it was Thanksgiving being in the UK., and we don't celebrate it. I *should* have realised it was coming up because we now have Black Friday sales :-(.

Is there a timeframe for the 1.11.3 release? 

Thanks.

**Comment by klonos** [comment] 2018-11-20 23:34
> ...not all review/feedback have to be code-related

I forgot to mention that with each pull request here on GitHub we have an automated sandbox site created where people can actually test the change 😄 ...so look for issues that have the "has pull request" tag, then look for the link to the pull request (there's usually a link to it bellow the issues summary):

<img width="1010" alt="screen shot 2018-11-21 at 10 31 51 am" src="https://user-images.githubusercontent.com/2423362/48809446-c0b8e000-ed78-11e8-879e-db82168d42c9.png">

...then go to the pull request and scroll down to look for a comment by the backdrop-ci bot with a link to the test site and username/password:

<img width="1012" alt="screen shot 2018-11-21 at 10 33 32 am" src="https://user-images.githubusercontent.com/2423362/48809497-f78ef600-ed78-11e8-9596-381d8b6f85fc.png">

Then use those to log in to the site and test away! ...then report good and bad things back the issue. That's it.

**Comment by herbdool** [comment] 2018-12-05 19:36
Thank you @hosef, @klonos and @Graham-72! Merged https://github.com/backdrop/backdrop/pull/2380 and https://github.com/backdrop/backdrop/pull/2381 into 1.x and 1.11.x.

**Closed by herbdool** 2018-12-05 19:36 UTC
Labels: pr - reviewed & tested by the community, status - has pull request, type - bug report

**Comment by gdvallance** [comment] 2018-12-20 10:13
I can confirm that on updating to the latest version the problem was fixed for me. Thanks!

**Comment by klonos** [comment] 2018-12-26 03:55
Glad it worked for you too @gdvallance 😄 ...and thanks for taking the time to report back 👍
