### ISSUE TITLE
CKEditor – incorrect initial display of Insert link dialog

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#3404] opened 2018-12-04 06:11 UTC
The changes made in the Filter module filter.js file when adding the Image Library in 1.11.0 (issue #3134) have caused a problem in the initial display of the Insert link dialog. Both of the toggled displays are showing where one should be initially hidden. We have this

![image](https://user-images.githubusercontent.com/10559274/49422240-fc957180-f78a-11e8-8926-10006a1096dd.png)

The correct display (below) appears after toggling to ‘Upload a file and link to it’ and back.
![image](https://user-images.githubusercontent.com/10559274/49422279-323a5a80-f78b-11e8-93e1-300bc876fca1.png)

A small change to filter.js is required.
See PR by @Graham-72  /backdrop/backdrop/pull/2401
See PR by @Graham-72 & @opi https://github.com/backdrop/backdrop/pull/2421

**Comment by olafgrabienski** [comment] 2018-12-04 09:49
I can confirm the issue and I've had a look in the sandbox site of the PR, where the dialog is displayed correctly, great!

**Comment by klonos** [comment] 2018-12-05 12:05
Hmm wondering what I am doing wrong, but I cannot reproduce the problem. Can one of you guys provide steps tp reproduce please? Thanks

**Comment by Graham-72** [comment] 2018-12-05 14:44
@klonos as follows, using BD 1.11.2 and Chrome Browser in Windows 10, before using the PR in the sandbox so that filter.js is not updated

1. Create a line of text on a new test page, using CKEditor with file uploading enabled on admin page.
2. Select part of this line (highlight).
3. Select 'Link' icon in CKEditor.

This then reveals the pop-up dialog as in the first screenshot above.

**Comment by opi** [comment] 2018-12-13 21:45
Without this PR, a JS error is thrown:
```
TypeError: $srcField.val(...) is undefined - filter.js:279:62
```

While this PR fix the error, I'd like to add a check on `$srcField` at this line. Alow, @Graham-72 PR shows the "Upload a file and link to it" tab by default. My opinion is regular "Link value" should be the default.

Here is a PR with mentionned changes, with @Graham-72 contribution and authorship : https://github.com/backdrop/backdrop/pull/2421

**Comment by olafgrabienski** [comment] 2018-12-14 13:11
@opi Looks good in the sandbox. Initially, I saw two messages in the DBlog, but after I cleared the cache, they didn't come up again.

However, here are the messages for reference:

> Notice: Undefined index: scheme in filter_format_editor_link_form() (line 402 of /home/qa/github/backdrop/backdrop/pr/2421/core/modules/filter/filter.pages.inc).
> Notice: Undefined index: status in filter_format_editor_link_form() (line 410 of /home/qa/github/backdrop/backdrop/pr/2421/core/modules/filter/filter.pages.inc).

**Comment by Graham-72** [comment] 2018-12-14 17:30
@opi thanks for your modification. Looks good to me.

**Comment by jenlampton** [comment] 2018-12-20 22:06
Looks like there are several great reviews, so marking as RTBC.

**Comment by quicksketch** [comment] 2018-12-31 18:48
Thanks @opi and @Graham-72! Merged https://github.com/backdrop/backdrop/pull/2421 into 1.x and 1.11.x.

**Closed by quicksketch** 2018-12-31 18:48 UTC
Labels: status - has pull request, status - fixed

**Comment by klonos** [comment] 2019-01-01 08:12
Thanks for merging this 👍 ...it's been really bothering me while testing #3307
