### ISSUE TITLE
[UX][D8] Views "Add fields" modal: Split item title/category/description into separate columns, and streamline JS used 

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#6355] opened 2024-01-06 07:18 UTC
## Description of the bug

While working on Gin I noticed that the Views modal for selecting fields or filters could use some clean up. Here are some of the things I'd like to improve:
 - Each field is prefaced by the category, which makes it hard to read field names/labels at a glance. In Drupal 10 the category is in a completely separate column after the field label, ~but perhaps it would be enough to just put it after the field label? I'm curious if others agree that this is harder to read with the category inserted at the front.~ and the latest PR replicates that.
 - The script that shows which fields have been selected could be made a little less fragile. If a theme is overriding `theme_checkbox` it is very easy to break that (as Gin does) and it can be hardened with a minor tweak. Right now it looks for the label exactly following the checkbox, but (for example) Gin adds a span directly after the checkbox, so the "Selected: " interface is broken. ~Changing that to look for a sibling label instead of whatever happens to be directly following seems a little stronger.~ [Code from Drupal 10](https://git.drupalcode.org/project/drupal/-/blob/10.2.x/core/modules/views_ui/js/views-admin.js?ref_type=heads#L33-593) has been adapted to match the corresponding structural changes and is more robust.

## Steps To Reproduce

To reproduce the behavior:
1. Go to a View and click on "Add" in the "Fields" or "Filter criteria" section.
2. Scroll the list.

## Screenshot (before)
![CleanShot 2024-02-04 at 14 14 30@2x](https://github.com/backdrop/backdrop-issues/assets/871421/8bfa47f0-89b2-43cb-9458-cf50c8b4b323)

## Screenshot (after)
![CleanShot 2024-02-04 at 13 45 59@2x](https://github.com/backdrop/backdrop-issues/assets/871421/c51f3344-0c99-4155-9c40-2b8b6ee67810)

**Comment by kiamlaluno** [comment] 2024-01-06 09:39
I prefer the *category: field* order to *field: category* because it is easier to notice that *Content revision: Title* is not *Content: Title*.

**Comment by kiamlaluno** [comment] 2024-01-06 11:22
Leaving out that, in English and other left-to-right languages, the order would be `<generic category>: <specific category>` or `<phrase>: <explanation of the previous phrase>`, `<field>: <category>` could help if at least the the fields were ordered by `<field>` and `<field>: <category>` were used in the view page too.

With the PR, the fields list is not easier to read (for a left-to-right language) than the list as it shown now.

![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/db9097e6-8284-4eec-acd5-f8441625141d)

If the list showed *Title: Content* and *Title: Content revision* as consecutive items, at least I could notice there are more *Title* fields without reading the full list.

**Comment by laryn** [comment] 2024-01-06 18:07
I wonder if we can break these out separately instead of mashing them together. For reference, here's a screenshot of how D10 does it, using a table and individual `<td>`'s:
![CleanShot 2024-01-06 at 12 05 03@2x](https://github.com/backdrop/backdrop-issues/assets/871421/9c3cc84e-1c80-45c6-90d5-b5fc60289366)

**Comment by kiamlaluno** [comment] 2024-01-06 19:09
That is much better! There is no even the need to "parse" the text to look at the field name.

**Comment by laryn** [comment] 2024-01-09 04:01
This is a screenshot from my local (with Gin for Backdrop as the theme) with the latest changes to the PR:

![CleanShot 2024-01-08 at 21 31 16@2x](https://github.com/backdrop/backdrop-issues/assets/871421/9ff99d57-291c-4f1f-bd78-9e82dc82e7e9)

I reworked it to use a table and td separation, and largely copied a section of code from Drupal 10 to rework the search functionality to work in this new structure. 

@kiamlaluno (and @olafgrabienski -- I see that thumbs up), are you able to test this and post your feedback here?

**Comment by kiamlaluno** [comment] 2024-01-09 09:27
Using the default Backdrop theme, this is what I see.

![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/c9b6e025-173e-4dd8-a983-1295f589f6b1)

There are lines around the check-boxes which should not be there.

**Comment by olafgrabienski** [comment] 2024-01-09 09:48
I've applied the PR locally and I really like the general look and feel. See the screenshots below for a comparison in Seven. As mentioned by @kiamlaluno, I also see the lines around the check boxes in the Seven theme, btw.

There seems to be a regression with regards to the Search box. Without the PR, you could filter the Category by typing parts of the Category name into the search box. With the PR, this doesn't work anymore. If I didn't miss anything, the search box looks only for Title and Description now. (To test, put "Global" in the search box.)

---

**Screenshots ("Add field" dialog in Seven)**

(a) Without PR 4628:

![image](https://github.com/backdrop/backdrop-issues/assets/14188307/dfc81447-1f6d-4c45-995d-20e59f4b2eb5)

---

(b) With the PR:

![image](https://github.com/backdrop/backdrop-issues/assets/14188307/c9132fd2-96dc-44eb-afbb-bd67e563260c)

**Comment by laryn** [comment] 2024-01-09 14:56
Thanks @kiamlaluno and @olafgrabienski -- I've made a revision to the PR. It does change the display slightly for Seven, with fewer high contrast border lines, making it more in line with the way Seven displays the main admin content listing.

I've also added the ability to keyword filter on the group name.

## Seven
![CleanShot 2024-01-09 at 08 50 51@2x](https://github.com/backdrop/backdrop-issues/assets/871421/6fbcac43-3aff-4407-b1fb-4aedfa4947b0)

## Gin
![CleanShot 2024-01-09 at 08 53 49@2x](https://github.com/backdrop/backdrop-issues/assets/871421/ce8b0dca-9bd0-4151-97ef-53d2d0e8ba96)

**Comment by olafgrabienski** [comment] 2024-01-09 15:34
Thanks for the update, @laryn. The revised PR works for me:

- Checkboxes look good in Seven (and Gin).
- Search box works with Categories.

I've also had a look at the line with "Selected" fields. Looks good both in Seven and in Gin.

**Comment by kiamlaluno** [comment] 2024-01-09 17:17
It looks good to me too.

**Comment by laryn** [comment] 2024-01-09 17:50
Score one for automated testing which has revealed a breakage if you actually try to go further along from here... I'll have to come back to this one!

**Comment by laryn** [comment] 2024-02-04 14:37
@kiamlaluno @olafgrabienski Are you willing to review again?

**Comment by olafgrabienski** [comment] 2024-02-04 17:47
@laryn Sure! I've tested in the sandbox, and the PR looks good at first sight (see 1st screenshot below). But I've noticed an issue, not sure if new or if it existed before: If you don't filter the fields, the "Selected" line is somehow hidden (see 2nd screenshot). This doesn't happen with a fresh Backdrop demo.

**Screenshot 1:**

![image](https://github.com/backdrop/backdrop-issues/assets/14188307/c88faaa5-16bc-44b9-878f-a15325b9ad1a)

---

**Sceenshot 2:**

![image](https://github.com/backdrop/backdrop-issues/assets/14188307/c1cf5065-7fd6-4a00-90b6-ecd1eeb4d3d6)

**Comment by laryn** [comment] 2024-02-04 19:47
Thanks for testing again @olafgrabienski!

This is a fresh site with nothing selected:
![CleanShot 2024-02-04 at 13 43 53@2x](https://github.com/backdrop/backdrop-issues/assets/871421/4a9d434a-7f5d-474a-bacb-14594ce3bd3d)

With the current PR, with nothing selected:
![CleanShot 2024-02-04 at 13 45 59@2x](https://github.com/backdrop/backdrop-issues/assets/871421/c51f3344-0c99-4155-9c40-2b8b6ee67810)

In both cases, the "Selected" text does not show up when nothing is selected. Are you seeing something different?

**Comment by olafgrabienski** [comment] 2024-02-04 20:15
> In both cases, the "Selected" text does not show up when nothing is selected. Are you seeing something different?

No, in this case I see the same. I was referring to another situation but didn't make that clear (sorry): In my second screenshot I _had_ selected some fields (the same as in the first screenshot). The selected checkboxes are not visible, though, because their rows are further down in the not visible part of the dialog.

I'm adding a new screenshot with some visible selected checkboxes to make the issue more clear. Note also the highlighted region in the screenshot where you see a small fraction of "Selected" line:

![image](https://github.com/backdrop/backdrop-issues/assets/14188307/fc3fe14b-d180-4482-b800-3c8183433351)

**Comment by laryn** [comment] 2024-02-04 20:18
@olafgrabienski Is that on your local with manual patching, or in the Tugboat sandbox? Here's what I'm seeing in the sandbox:

![CleanShot 2024-02-04 at 14 17 31@2x](https://github.com/backdrop/backdrop-issues/assets/871421/b94646d4-c4a9-4928-a29e-a91b83e4eee0)

**Comment by olafgrabienski** [comment] 2024-02-04 20:20
> Is that on your local with manual patching, or in the Tugboat sandbox?

Also sandbox ... Maybe a browser question? I was testing with Chrome on Mac.

**Comment by laryn** [comment] 2024-02-04 20:21
Ah, that could be. I'll check with Chrome.

**Comment by olafgrabienski** [comment] 2024-02-04 20:24
Hm, testing with Firefox for me it looks similar to Chrome, but it gets better at a certain point when I reduce the height of the browser window.

**Comment by laryn** [comment] 2024-02-04 20:27
I'll try to test later on a larger screen.

**Comment by kiamlaluno** [comment] 2024-02-04 20:32
I checkes the PR preview on Firefox, on a computer running on SparkyLinux (based on the testing branch of Debian). On a 1920x1080 screen, I see the dialog box as expected.

#### Without selected fields

> ![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/adb5d880-4adc-40c7-96fb-88fff7752ab2)

#### With selected fields

> ![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/dd35b8d9-e1ed-4be8-831d-290e8c46b650)

**Comment by olafgrabienski** [comment] 2024-02-04 20:44
My screen is quite _small_ (MacBook Air M2, standard resolution 1470x956). In the browser's dev tools I see the actual height within the browser is 832px. When I reduce the actual height to 749px, the dialog becomes smaller, shows less rows for this reason and lets enough space for the "Selected" line. Screenshot comparison in Chrome:

**Actual size in browser window, 1470 x 832px:**

![image](https://github.com/backdrop/backdrop-issues/assets/14188307/5a3489db-ad43-47f7-b4bd-e4a3672960d7)

---

**Actual size in browser window, 1470 x 749px:**

![image](https://github.com/backdrop/backdrop-issues/assets/14188307/62469ba8-f302-4c9c-885a-1a3ab41f4df2)

**Comment by olafgrabienski** [comment] 2024-02-04 21:03
> If you don't filter the fields, the "Selected" line is somehow hidden. This doesn't happen with a fresh Backdrop demo.

I have to correct myself. Now I see the same issue in the fresh Backdrop demo site without the PR, so not introduced by this PR. When I had compared the PR with the demo site before, I didn't pay attention to the browser window height. Sorry that I didn't compare more thoroughly.

**Comment by laryn** [comment] 2024-02-04 21:05
@olafgrabienski I see the same thing -- care to split that off into a separate issue for separate discussion then?

**Comment by olafgrabienski** [comment] 2024-02-04 21:07
> split that off into a separate issue for separate discussion then?

Agreed! (I put it on my list.)

**Comment by kiamlaluno** [comment] 2024-02-04 21:40
I reduced the viewport on Firefox, and I noticed the same issue, when I use a 1470x750 screen. With a 1470x956 viewport, nothing changes respect a 1920x1080 viewport.

**Comment by klonos** [comment] 2024-02-05 00:45
Thanks @laryn 🙏🏼 ...I've done a quick review of the code and added a couple of suggestions in the PR thread.

**Comment by olafgrabienski** [comment] 2024-02-05 16:38
I've filed a separate issue re the visibility of the "Selected" line: #6395

**Comment by laryn** [comment] 2024-02-05 16:47
@klonos FYI, I moved it back to _Needs Code Review_ since I wasn't sure if you were done with your review.

**Comment by klonos** [comment] 2024-02-19 20:35
@laryn I recall not being able to finalize the review because of the extend of the changes in `views-admin.js`. Do you think that we could split the indentation fix for that file into a separate issue/PR in order to make this easier to review?

**Comment by laryn** [comment] 2024-02-19 22:17
I've attempted to remove whitespace/indentation fixes from this PR.

**Comment by laryn** [comment] 2024-04-19 21:28
@klonos Are you able to review this one again?

**Comment by klonos** [comment] 2024-04-24 04:55
Thanks @laryn 🙏🏼 ...I did another review, but only the PHP bits - I took a look at the JS changes, but I think that someone else with more JS expertise should review that.

**Comment by stpaultim** [comment] 2024-04-29 02:07
This one is marked "Works for me" but there are some changes requested. @klonos, does this one Need work?

**Comment by laryn** [comment] 2024-04-29 16:25
@klonos On this particular table (Views add field) the first column in not bolded in Drupal, but here's what it would look like:
![CleanShot 2024-04-29 at 11 23 49@2x](https://github.com/backdrop/backdrop-issues/assets/871421/aa5c3128-8298-4b21-b78e-efde7f517deb)

I could go either way on this one -- is this better?

**Comment by stpaultim** [comment] 2024-04-30 04:39
Wow. Making improvements to views. Yes.

I like it. 

Sandbox is not working. I installed it locally and tested it.

**Comment by laryn** [comment] 2024-04-30 11:36
I rebased so the sandbox should be working again. I’ll try to add bold to the titles this morning.

**Comment by stpaultim** [comment] 2024-05-07 03:19
@laryn As a core committer, do you think this is a task eligible for bugfix release, or is this an extensive enough change that it needs to wait for 1.29?

**Comment by klonos** [comment] 2024-05-08 08:28
@stpaultim this is a UX task. It does not introduce any new feature - it simply reorders/re-styles the rows of the same table. I say that it can go in the next bug fix release as a UX/UI improvement. Added milestone accordingly, and we can move if other feel strongly otherwise.

**Comment by klonos** [comment] 2024-05-08 08:34
...that's odd: did someone reset the admin password in the PR sandbox? 😅 ...the password indicated in the automated message by Tugboat doesn't work for me. I'll test locally.

**Comment by klonos** [comment] 2024-05-08 08:54
@laryn can we please wrap the text in the title column cells in `<label>` tags, and then also add the appropriate `for` attribute that points to the `id` of the respective checkbox? That will most likely eliminate the need for the whole `// Click on the title checks the box.` JS thing in the code (untested, but very likely IIRC how things work with labels).

**Comment by laryn** [comment] 2024-05-09 14:43
@klonos That sounds like a good idea. If you know of a better way than what I've done, I'm all ears.
https://github.com/backdrop/backdrop/pull/4628/commits/948447d2f31256d1513550df338d23f370b0a245

**Comment by klonos** [comment] 2024-05-09 18:27
@laryn this has been a long-time peeve of mine, and no, I don't have any better way - I wish that it was easier and that it all just worked automagically with tableselects, but it doesn't (this actually reminded me that this also happens in the "Enable modules" step of the Project Installer - I looked for an existing issue, but didn't find any).

Anyway, the PR works for me, but I would prefer that we used the standardized `backdrop_attributes()`/`backdrop_html_class()`/`backdrop_html_id()` and avoid crafting the various attributes "manually" with `preg_replace()`/`strtolower()`/`str_replace()`/etc. where possible. Other than that, I will leave the JS code review to someone else, as I said earlier in one of my previous comments, since I'm not as experienced as others.

**Comment by laryn** [comment] 2024-05-09 18:59
@klonos I had considered `backdrop_html_id()` but discarded the idea because it would make sure the ID was unique so it wouldn't match the checkbox ID -- but hadn't considered using `backdrop_html_class()` as a stand-in. It seems to work. (PR updated)

**Comment by klonos** [comment] 2024-05-09 22:10
> ... I had considered `backdrop_html_id()` but discarded the idea because it would make sure the ID was unique so it wouldn't match the checkbox ID


Hmm 🤔 ...are you sure about this @laryn? From what I can see, the checkboxes have the same `data-tableselect-id` attribute (👍🏼) but they have different `id` attributes, so it should be fine. The attribute that we use in the labels is `for`, and it doesn't hurt if these aren't unique - they just need to match the `id` attribute of the respective checkbox. If you have already tried and it doesn't work, then that's fine. I just left a comment in the PR to add something in the inline comment to explain things though.

**Comment by laryn** [comment] 2024-05-14 16:54
@klonos I've added the additional text you requested in the comment.

**Comment by klonos** [comment] 2024-05-14 20:55
Thanks @laryn 🙏🏼 ...I think that this is good to go 👍🏼 

I have thoughts, but these are more broad and touch on inconsistencies with the FAPI etc. - so not here - follow-ups.

**Comment by quicksketch** [comment] 2024-06-23 23:46
I resolved a merged conflict in the PR (we stopped using `$.trim()` thanks to #6149). This is sort of a big set of changes but seems as though it's had extensive testing from @klonos, @laryn, @kiamlaluno, @stpaultim, and @olafgrabienski.

**Closed** 2024-06-24 00:15 UTC
Labels: type - task, status - has pull request, pr - ready to be committed, pr - works for me

**Comment by quicksketch** [comment] 2024-06-24 00:17
I merged https://github.com/backdrop/backdrop/pull/4628 into 1.x and 1.28.x. Thank you everyone!

[bf8e45e](https://github.com/backdrop/backdrop/commit/bf8e45ed6946fcd7bd72f599d81173f433549d0a) by @laryn, @kiamlaluno, @klonos, @olafgrabienski, @stpaultim, and @docwilmot.
