### ISSUE TITLE
Fixed: selected file is lost when a form is submitted anonymously with an un-uploaded file that fails validation

### ISSUE THREAD

**Issue by MrHaroldA** [backdrop/backdrop-issues#1678] opened 2016-03-02 15:47 UTC
> Drupal 7.43 makes file upload component fail for anonymous user but appears to affect Drupal core. To reproduce using the Standard installation profile:
> 1. Allow anonymous users to create article nodes.
> 2. As an anonymous user, go to the node creation page. Leave the article title blank. Select a file for the Image field, but do not click "Upload".
> 3. Click "Save". There will be a validation error because the title was not filled out. If you scroll down to the Image field, you'll see that the file was uploaded.
> 4. Fill out the title and click "Save" again. The node will be saved, but the file you uploaded before will no longer be attached to it.

Drupal core: https://www.drupal.org/node/2678822 / https://git.drupalcode.org/project/drupal/commit/6b6bc1b
Webform: https://www.drupal.org/node/2675170

[Update by @herbdool: confirmed it is a bug. Before testing without this PR, either disable javascript in your browser or comment out the line `'js' => array($file_path . '/js/file.js'),` in `file_element_info()`.]

**Comment by jenlampton** [comment] 2019-09-11 21:53
It looks like this was resolved with the fix that we merged in https://github.com/backdrop/backdrop-issues/issues/2013

**Comment by herbdool** [comment] 2021-06-04 19:34
I have a feeling that this wasn't addressed. The code that's in the patch in https://www.drupal.org/project/drupal/issues/2678822 doesn't exist in Backdrop. And it was marked as NA in the related issue here.

**Comment by herbdool** [comment] 2021-06-04 20:33
Maybe this wasn't seen as an issue because files get uploaded automatically now? That seems to be the case. When I prevent the automatic uploading via ajax, I can repeat the steps above and get the same error.

The related Webform issue is also fixed by the Drupal patch (though the steps are different).

**Comment by herbdool** [comment] 2021-06-04 21:02
Here's the commit to Drupal core https://git.drupalcode.org/project/drupal/commit/6b6bc1b which I'll adapt for here.

**Comment by herbdool** [comment] 2021-06-04 21:23
I've created a PR. It's not ready for review yet since I need to look at the test again. The idea is that we can currently (without the PR) reveal the bug by commenting out the line 'js' => array($file_path . '/js/file.js'), in `file_element_info()`. This will prevent the automatic file uploading which is hiding this bug.

I just need to figure out how to replicate this in the test so that I can first confirm that the test fails before we create a fix.

**Comment by herbdool** [comment] 2021-07-21 16:11
I'm hoping to get some ideas from people on why the bug can be recreated manually but can't replicate in the automated tests.

1. Spin up a fresh site.
2. "Turn off" the automatic file upload by commenting out the line `'js' => array($file_path . '/js/file.js'),` in `file_element_info()` in `file.module`. We need to do this because the JS triggers the upload button and this bug only appears if the upload button is *not* triggered.
3. Change permissions so that anonymous user can create posts and can add images.
4. Attempt to save a post with *no* title and an image attached. Like this:
   ![anon-add-post](https://user-images.githubusercontent.com/1071483/126520187-18872dd1-ae90-4992-a815-f66b426a24ce.png)
5. You will see the error like the following image. Now fill in a title and save.
   ![anon-add-post2](https://user-images.githubusercontent.com/1071483/126520189-a8a91ee8-bc20-4e75-bf61-b3003fa17c18.png)
6. You should see the saved post but the image has *disappeared*. 
![anon-add-post3](https://user-images.githubusercontent.com/1071483/126520190-f05ef47c-a4f1-4340-aebe-a2f5cc045115.png)

You should be able to confirm the bug. The file should be saved even if Upload isn't triggered.

I haven't been able to replicate this bug in the automated tests. I've tried it with the JS still commented out and then added the new test in this PR to the *existing* codebase (not the whole PR). This part of the test should fail, but it's not:

```
    // Generate a file.
    $test_file = $this->getTestFile('text');

    // Submit the form but exclude the title field.
    $edit = array(
      'body[und][0][value]' => 'Test page',
      'body[und][0][format]' => 'filtered_html',
      'files[' . $field_name .'_und_0]' => backdrop_realpath($test_file->uri),
    );
    $this->backdropPost(NULL, $edit, t('Save'));
    $this->assertResponse(200);
    $t_args = array('@type' => $bundle_label, '%title' => $node_title);
    $this->assertNoText(strip_tags(t('@type %title has been created.', $t_args)), 'The node was created.');
    $this->assertText(t('!name field is required.', array('!name' => t('Title'))));

    // Submit the form again but this time with the missing title field. This
    // should still work.
    $edit = array(
      'title' => $node_title,
    );
    $this->backdropPost(NULL, $edit, t('Save'));

    // Confirm the final submission actually worked.
    $t_args = array('@type' => $bundle_label, '%title' => $node_title);
    $this->assertText(strip_tags(t('@type %title has been created.', $t_args)), 'The node was created.');
    $matches = array();
    if (preg_match('@node/(\d+)$@', $this->getUrl(), $matches)) {
      $nid = end($matches);
      $this->assertNotEqual($nid, 0, 'The node ID was extracted from the URL.');
      $node = node_load($nid);
      $this->assertNotEqual($node, NULL, 'The node was loaded successfully.');
      $this->assertEqual($node->{$field_name}[LANGUAGE_NONE][0]['filename'], $test_file->filename, 'The file was uploaded successfully.');
    }
```

**Comment by docwilmot** [comment] 2021-07-21 16:36
Have you checked if `$node->{$field_name}[LANGUAGE_NONE][0]['filename']` really is empty when you do this locally? Just to be sure its not just a display issue.

**Comment by herbdool** [comment] 2021-07-21 17:03
@docwilmot good point. I've checked the `$node` object and `field_image`
![Screenshot from 2021-07-21 13-02-17](https://user-images.githubusercontent.com/1071483/126529606-4ea3f730-f540-4c67-977c-f1b507bd322f.png)
 is indeed empty.

**Comment by docwilmot** [comment] 2021-07-22 16:43
I cannot figure this out, sorry.

**Comment by herbdool** [comment] 2021-07-22 16:58
@docwilmot thanks. Were you able to recreate the bug manually at least? Just want to know if I'm on the right track.

**Comment by docwilmot** [comment] 2021-07-22 18:55
Yes, I did. To reproduce: 
- grant anonymous permissions as you describe
- select an image in the image field
- submit the node form with any required field not completed. The form reloads with error
- attempt to save the form. If you didnt complete the required field, the form reloads, again with the expected validation error, but it loses the `fid` on the image field. If you did complete the required field it saves but the image field is empty.

So essentially the bug is that the image field loses its `fid` if you click save after a validation error. I find this happens even without commenting out the lines you recommended.

**Comment by herbdool** [comment] 2021-07-23 19:44
@docwilmot hm... odd I can't recreate the bug *unless* I comment out the JS line. I just tested on a fresh Tugboat sandbox. The only change I made before testing was to give anonymous permission to create posts.

**Comment by docwilmot** [comment] 2021-07-23 19:58
So this is looking like an environment issue then.
> I just tested on a fresh Tugboat sandbox

How do you get your own fresh Tugboat sandboxes??

**Comment by herbdool** [comment] 2021-07-23 19:59
@docwilmot https://backdropcms.org/demo

**Comment by docwilmot** [comment] 2021-07-23 20:13
Yeah but how do you update the code and "comment out the JS line" there?

**Comment by herbdool** [comment] 2021-07-23 20:24
Sorry I wasn't clear. I can't. In my Tugboat test I only tested the fresh install without making any code changes. I couldn't recreate the bug there. I could only recreate the bug locally where I *could* make a code change.

**Comment by herbdool** [comment] 2021-08-05 13:36
@docwilmot I realized there's an easier way to test the bug by disabling javascript temporarily.

**Comment by quicksketch** [comment] 2021-08-05 21:04
Super @herbdool! If this is reproduceable without JS, that means that the test you added in https://github.com/backdrop/backdrop/pull/3642 should cover the bug. So if we ran the test on a current Backdrop site without the fix it should fail.

**Comment by herbdool** [comment] 2021-08-05 21:08
@quicksketch I've tried to run the test on a site without the fix and it's not failing. I'm trying to figure what is going on differently in the test which doesn't seem to be replicating the same conditions.

**Comment by quicksketch** [comment] 2021-08-06 05:51
I think the test isn't doing the same steps that @docwilmot laid out. I reproduced the problem with JS disabled as he described, but the test isn't doing the same thing, it's just submitting the form with all fields filled out. I left a comment on the PR: https://github.com/backdrop/backdrop/pull/3642/files#r683964230

**Comment by herbdool** [comment] 2021-08-12 00:39
Finally, I've fixed the test in the PR and it's working properly:

1. I've run the automated test *before* applying the patch and it fails, as expected.
2. After applying the patch, the test passes.

**Closed** 2021-08-12 02:43 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2021-08-12 02:44
Super, code looks good and thank for updating that test to actually cover the issue being described!

I merged https://github.com/backdrop/backdrop/pull/3642 into 1.x and 1.19.x!

Unfortunately, I forgot to properly credit folks in the merge. :frowning_face: 

But I'll say it here: Thank you @MrHaroldA, @herbdool, and @docwilmot for your work on this issue!
