### ISSUE TITLE
Fixed: Remove MySQL 5.0 hacks.

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#6120] opened 2023-05-19 18:18 UTC
## Description of the bug

I happened to be running updates locally with xdebug on and kept getting (repeatedly) a bunch of triggers on various PDO exceptions such as:

`PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'language' in 'field list'`
and
`PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.languages' doesn't exist`

If I resumed in xdebug it would complete but it was hitting these many many times.

## Steps To Reproduce

To reproduce the behavior:
1. Install Backdrop locally and activate Xdebug with a breakpoint activated on exceptions 
2. Install an outdated module
3. Update the module and try to run database updates

## Additional information

I think I've tracked this down to the `fieldExists` and `tableExists` methods in `DatabaseSchema_mysql` (in `core/includes/database/mysql/schema.inc`) which have a hack included from ~14 years ago in MySQL 5.0. Instead of checking whether the table exists, it tries to select from the table to see if it fails (which was much quicker at the time than checking if the table or field existed). The bug itself was first reported in 2006:

 - https://bugs.mysql.com/bug.php?id=19588

If it possible to now remove these hacks we should! The original bug gives these STR:
```
mysql> use information_schema
Database changed
mysql> select count(*) from tables;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

If I try that locally it doesn't seem to be an issue anymore (though someone more familiar with versions of MySQL/MariaDB might have some further input here):
```
MariaDB [information_schema]> use information_schema
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [information_schema]> select count(*) from tables;
+----------+
| count(*) |
+----------+
|      159 |
+----------+
1 row in set (0.001 sec)
```

Here are the locations with the hacks:

 - https://github.com/backdrop/backdrop/blame/1.x/core/includes/database/mysql/schema.inc#L505-L520
 - https://github.com/backdrop/backdrop/blame/1.x/core/includes/database/mysql/schema.inc#L530-L545

**EDIT:**
Here's one more that can probably go:

 - https://github.com/backdrop/backdrop/blob/81601e9dfd9f04e8a7182193191cc7b491a7c862/core/includes/database/mysql/schema.inc#L501-L502

**Comment by laryn** [comment] 2023-05-19 19:24
It looks like this has been changed in modern Drupal, e.g.:

 - https://git.drupalcode.org/project/drupal/-/blob/11.x/core/lib/Drupal/Core/Database/Schema.php#L235-256

**Comment by laryn** [comment] 2023-05-19 19:39
Perhaps this is why it's still in here (Backdrop requirements):

> MySQL 5.0.15 or higher with PDO enabled

**Comment by indigoxela** [comment] 2023-05-20 14:03
> ... MySQL 5.0.15 or higher

Honestly, I doubt, anyone's still using MySQL 5.0.x. But... it's unclear when this bug has been fixed in MySQL - can't seem to find the information. Without that info, it's hard to decide.

The oldest version I've available for testing are MariaDB 10.1 and MySQL 5.7 – both aren't affected by this bug anymore.

**Comment by kiamlaluno** [comment] 2023-05-20 16:42
I tried on my site, which uses MySQL 5.6.51-cll-lve: `SELECT COUNT(*) FROM information_schema.tables;` shown the `COUNT(*)` value.

**Comment by klonos** [comment] 2023-05-21 11:21
As @indigoxela pointed out in [the related discussion in Zulip](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/.236120.20Remove.20mysql.20override.20hacks), our [telemetry](https://backdropcms.org/project/backdrop/telemetry) shows that nobody is using MySQL lower than v5.5, so we can drop this hack I believe. Issues like this one is why we have introduced the Telemetry module to begin with - so that we can have some hard data to back our decisions.

I think that lando allows spinning up instances with v5.0 (and actually [allows patch-level versions](https://docs.lando.dev/mysql/#patch-versions) too - although officially unsupported), by doing this:
```
services:
  myservice:
    type: mysql:5.0.15
```

I'll give that a go when I get a chance.

**Comment by laryn** [comment] 2023-05-21 13:11
Here's one more that can probably go:

 - https://github.com/backdrop/backdrop/blob/81601e9dfd9f04e8a7182193191cc7b491a7c862/core/includes/database/mysql/schema.inc#L501-L502

**Comment by indigoxela** [comment] 2023-05-21 15:32
> I'll give that a go when I get a chance.

@klonos sure, let's verify that, too.  :+1:  But I'd actually expect such an old version to still have the bug.

The question is: when has this bug been fixed? I found some reports in the net, that  MySQL 5.1 and eventually a MariaDB version (unclear which one) was also affected, but no evidence, when this has been fixed.

**Comment by kiamlaluno** [comment] 2023-05-22 11:07
One of the comments on https://bugs.mysql.com/bug.php?id=19588 is the following.

> [5 Dec 2007 13:40] Sergei Golubchik
> 
> pushed in 5.1.21

I take that means the issue has been fixed in MySQL 5.1.21.

**Comment by jenlampton** [comment] 2024-04-14 03:30
So this would increase our minimum version to 5.1.21?

**Comment by quicksketch** [comment] 2024-04-22 02:54
I think this is a duplicate of https://github.com/backdrop/backdrop-issues/issues/6450 (technically this one came first, but that one had the PR). This has been fixed in https://github.com/backdrop/backdrop/pull/4691.

@jenlampton We don't need to increase the minimum requirements because removing the MySQL 5.0 "hack" is actually still backwards-compatible; it's just a lot slower. By removing it, we're optimizing for current versions of MySQL while penalizing this ancient (EOL 2007) version, but it should still actually work.

**Closed by quicksketch** 2024-04-22 02:54 UTC
Labels: status - duplicate, status - has pull request, status - fixed

**Comment by klonos** [comment] 2024-04-22 04:51
FTR: follow-up here for the removal requested by @laryn: #6466
