### ISSUE TITLE
Core updates failing due to missing type in profile .info files 

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#3553] opened 2019-02-22 04:44 UTC
**Description of the bug**

When upgrading from 1.12.2 to 1.12.3 via the UI for a site, I got this error:

> UpdaterException: The info file (<em class="placeholder">temporary://update-extraction-4b1a88c8/backdrop/core/profiles/minimal/minimal.info</em>) does not define a 'type' attribute. in Updater::getProjectType() (line 199 of /home/EXAMPLE.com/www/htdocs/core/includes/updater.inc).

**Steps To Reproduce**
To reproduce the behavior:
1. Navigate to `/admin/reports/updates/settings`
2. Scroll down and enable the "Manual self-update"
3. Go to `admin/modules/update`
4. If there's a Backdrop core update available then check it and click "Download" button.
5. When the download finishes, you should be redirected to the "Ready to update" page. Click "Continue"

Note that this error isn't consistent at all. I attempted the update on two mostly identical sites. One worked fine and the other complained.

**Expected behavior**
Core updater should ignore profile .info files.

In this issue https://github.com/backdrop/backdrop-issues/issues/1294 we excluded .tests.info but for this we'd need to put more work into excluding.

-----------
PR by @herbdool (exclude .info files for profiles from updater): https://github.com/backdrop/backdrop/pull/2540
Alternative PR by @klonos (adds `type = profile` to core profiles): https://github.com/backdrop/backdrop/pull/2541

**Comment by olafgrabienski** [comment] 2019-02-25 21:29
I can confirm the issue, it happened on only one of several sites. Can't add any details, though.

**Comment by olafgrabienski** [comment] 2019-03-21 14:56
Running in this issue again. In DBlog, I get the same message as in the issue description twice, one referring to line 199 and the other referring to line 194 of `updater.inc`.

The download of the update seemed to work fine. The  error occured after it, when I clicked the button *Continue* on the page `admin/update/ready`.

**Comment by klonos** [comment] 2019-03-21 15:45
Wondering if instead of excluding/ignoring the .info files it would make sense to support `type = test` and `type = profile`.

**Comment by herbdool** [comment] 2019-03-21 19:36
Perhaps an easier change is to add `hidden = TRUE` to `core/profiles/standard/standard.info` (the other profiles have it). Unless that hides it from the installer, in which case we need a different approach.

**Comment by herbdool** [comment] 2019-03-21 20:50
This PR might do the trick https://github.com/backdrop/backdrop/pull/2540

**Comment by olafgrabienski** [comment] 2019-03-22 10:50
@herbdool Sure! The PR seems to do the trick: I've applied the code changes to the site in question, and the core update via the UI ran smoothly.

**Comment by herbdool** [comment] 2019-03-22 11:36
@olafgrabienski do you feel comfortable to mark it RTBC?

**Comment by olafgrabienski** [comment] 2019-03-22 11:53
> do you feel comfortable to mark it RTBC?

Done! (Needs review of the code, though.)

**Comment by klonos** [comment] 2019-03-22 20:13
@herbdool I have left a comment and code suggestion in the PR re supporting contrib/custom profiles within the `/profiles` folder. Although Backdrop core does not ship with such a folder (#3205), we do support it if users manually create it 😉

**Comment by herbdool** [comment] 2019-03-22 20:47
@klonos it wouldn't help in the case of just a webroot profiles folder, such as `profiles/super_special/super_special.info`. That's because it's looking through the folder just downloaded to tmp. So it would have to be this structure `profiles/super_special/profiles/another/another.info` or `modules/super_special/profiles/another/another.info` and I'm not sure if Backdrop even supports that structure.

**Comment by klonos** [comment] 2019-03-22 20:56
Hmm, not sure. I think @BWPanda (ping!) uses profiles, so he must have more experience in this.

**Comment by herbdool** [comment] 2019-03-22 23:18
Just thinking more, we also don't want to exclude these: `profiles/super_special/modules/another/another.info`.

**Comment by klonos** [comment] 2019-03-22 23:33
...which makes me think that #3613 might be a better/safer solution after all.

**Comment by klonos** [comment] 2019-03-23 00:01
I just tried to reproduce this with a 1.12.2 to 1.12.5 update, but could not. I know this does not mean that the problem is not there, because as mentioned in the issue summary, this is not consistently reproducible. Nevertheless, I would love to be able to reproduce it in order to test my theory re #3613.

**Comment by herbdool** [comment] 2019-03-23 02:36
@klonos dunno, requiring profiles to include a `type = profile` in their .info files seems like an elegant solution now. Considering there's no default profile directory outside of core currently and few people are using profiles, this might be a good solution. If they're having problems with updater they can already add `type = profile` (or `type = gobbledygook` for that matter) to fix it.

**Comment by klonos** [comment] 2019-03-23 17:35
Moved my PR from #3613 over to this issue, as an alternative as per @herbdool's suggestion.

**Comment by olafgrabienski** [comment] 2019-03-28 12:31
@klonos I wanted to test your alternative PR, but I guess it's not possible. (It doesn't make sense to apply the code changes to an outdated test installation, the changes have to be in the core version which gets downloaded by the installer.)

**Comment by herbdool** [comment] 2019-03-28 13:30
@olafgrabienski good point. I suspect that this is such a small, non-invasive change that we could make it RTBC and see what @quicksketch thinks. We can't make it any worse.

**Comment by jenlampton** [comment] 2019-03-28 20:37
Trying our fancy new tag.

**Comment by quicksketch** [comment] 2019-03-28 20:38
I also like the option for including `type` in profiles.

**Comment by herbdool** [comment] 2019-03-29 13:42
I added "ready to be committed" which I guess is similar to saying I did a code review? @klonos I don't think we can say "works for me" since we can't really test it without committing the code and releasing it first.

**Comment by klonos** [comment] 2019-03-31 16:42
> I don't think we can say "works for me" since we can't really test it without committing the code and releasing it first.

Indeed. I tried to reproduce this previously by following the steps mentioned in the issue summary, but I was not able to. @olafgrabienski also mentioned that this happened to one of his sites/installations, but not to the rest of them. So this is intermittent/random for some reason we have not identified yet I guess.

Anyway, the PR changes are pretty "harmless", and I do not see any possible way for the addition in the .info files to break other things.

**Comment by quicksketch** [comment] 2019-04-10 21:31
I merged @klonos's https://github.com/backdrop/backdrop/pull/2541 which adds `type` to profile .info files. I don't see the second PR as being necessary, but if there's a benefit to be had including it too, please just reopen this and we can do a follow-up commit.

Thanks @klonos, @herbdool, and @olafgrabienski for your work on this!

**Closed by quicksketch** 2019-04-10 21:31 UTC
Labels: pr - ready to be committed, status - has pull request, type - bug report
