### ISSUE TITLE
[UX] Provide a hamburger menu (or option) by default

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#2369] opened 2016-11-29 15:15 UTC
Is there a way to get the default menus to turn into a "☰ Menu" link that opens to the full menu, instead of the stacked version that is used by default? With any more than a few menu items it currently takes the whole screen on a phone and it would be nice to have it collapsed to start with.

Pulling a few of the responses from Gitter:

>@klonos : Yes, it is possible. Take a look here: http://www.smartmenus.org/docs#menu-toggle-button

> @herbdool : it'll take editing the tpl at least to get the hamburger to work since it's picky about where the toggle is in relation to the menu. ...
> I got the hamburger working. Use MYTHEME_menu_tree__main_menu() to inject the Smart menu html for the toggle button, then edit and add the css and js to your theme. You need to change #main-menu to .menu in the css, and make sure you have the right selector in the js.
```
function MYTHEME_menu_tree__main_menu($variables) {
  $return = '';
  if ($variables['depth'] == 0) {
    $return = '<!-- Mobile menu toggle button (hamburger/x icon) --><input id="main-menu-state" type="checkbox" /><label class="main-menu-btn" for="main-menu-state">  <span class="main-menu-btn-icon"></span> Toggle main menu visibility</label>';
  }
  $return .= '<ul ' . backdrop_attributes($variables['attributes']) . '>' . $variables['tree'] . '</ul>';
  return $return;
}
```
> it puts the hamburger below the logo which may or may not work for you. I haven't tested to see if it can work without needing to be a sibling of the menu. If so then the hamburger html could be put anywhere

> @klonos : I would absolutely love it if there was a simple way in the menu block settings allowing the user to select the hamburger as an alternative option for mobile (instead of the default responsive style we have now). I have come across some websites that use the hamburger as their default navigation regardless of screen size, so I believe that the best way to handle this would be if we also allowed it to be selected as an individual menu style option in menu block settings.

> @herbdool : The hamburger still uses the responsive menu that's there but just provides a toggle for it.

> @olafgrabienski : If you file that hamburger menu issue, I guess these are good reference points: #2107#issue-173965498 (we want a hamburger) and https://github.com/backdrop/backdrop-issues/issues/2107#issuecomment-246092072 (why isn't it there at that moment / how to implement it in future).

---
~~PR from @herbdool https://github.com/backdrop/backdrop/pull/1686~~
~~PR from @jenlampton https://github.com/backdrop/backdrop/pull/1708~~
~~PR from @njbooher https://github.com/backdrop/backdrop/pull/1714~~
PR from @jenlampton https://github.com/backdrop/backdrop/pull/1715

**Comment by olafgrabienski** [comment] 2016-11-29 22:14
Thanks for making the feature request. A hamburger menu was one of the designated features of issue #2107 (*Provide responsive drop-down menus out of the box*):

> Add necessary JS to turn the menu into a hamburger (and the word "Menu") when it runs out of room.

To get the responsive drop-down on time in the 1.5 release, it was committed without the hamburger menu. @quicksketch said then in https://github.com/backdrop/backdrop-issues/issues/2107#issuecomment-246092072:

> My thought is to have Basis implement a hamburger but exclude that from Bartik. Basis would likely do this through a combination of JS, theme_menu_tree(), and additional CSS.

Is there anybody who wants to make a PR based on @quicksketch's proposal and/or @herbdool's approach mentioned above?

**Comment by wesruv** [comment] 2016-11-29 22:18
I have some code for this that I implemented on another site, I'll try to get a PR together soon, playing catch up 😛

**Comment by laryn** [comment] 2016-12-07 16:12
@wesruv Was it similar to @herbdool's approach? If so, is it Basis-specific? If you are overwhelmed I may try to replicate this and submit. If you have it handy, obviously that's better for me. :)

**Comment by quicksketch** [comment] 2016-12-08 21:15
As this is a feature, not a bug, I'm moving this to 1.6.0.

**Comment by olafgrabienski** [comment] 2016-12-08 21:28
Yes, it's a feature, but it was one of the *designated* features of the "Provide responsive drop-down menus out of the box" issue, and in my opinion it's important to provide the missing feature, no matter if it's a feature request or a bug report.

**Comment by jenlampton** [comment] 2016-12-15 21:54
This was the first feature-request I had on my D7 module for smartmenus too [see this](https://www.drupal.org/node/2835539) and there is some recommended code at http://www.smartmenus.org/docs/#menu-toggle-button that makes it pretty easy.

**Comment by herbdool** [comment] 2016-12-22 19:25
I've taken the approach of adding a setting to the Basis theme. It'll only include the hamburger if the primary nav is present.

**Comment by jenlampton** [comment] 2016-12-22 19:40
> if the primary nav is present.

What does this mean? If a menu block is present? If the menu block is showing the 'Primary navigation' menu?

**Comment by herbdool** [comment] 2016-12-22 19:48
Out of the box Basis has a Primary Navigation block enabled. This provides an option for a hamburger on that menu alone. It's main_menu in the system.

**Comment by olafgrabienski** [comment] 2016-12-23 12:51
Thanks @herbdool for the PR. Tested it, works well!

I like that there is a setting but as theme setting, it seems a bit far away. Without knowing what it would mean technically, I'd prefer to have the setting in menu blocks.

I guess, we could need some more feedback, I'll tag the issue as such.

**Comment by jenlampton** [comment] 2016-12-23 17:15
My vote is for a block setting. That way it will work for all themes.

**Comment by laryn** [comment] 2016-12-23 17:20
I agree, a block setting seems best from a user standpoint. I don't know how much that complicates the PR or if it means a completely different approach.

**Comment by herbdool** [comment] 2016-12-23 19:48
Makes sense to me. It can be bundled with the Primary Navigation block which also has the option for the dropdown. I'll look into it.

**Comment by klonos** [comment] 2016-12-24 20:49
Yep, the menu block is where I'd expect a setting for that to exist. Perhaps as a "Render as a hamburger menu" checkbox shown via `#states` if "Dropdown menu" is selected as the menu style. When that checkbox is enabled, there would be another set of radio options:

( ) Always
( ) Below a specific breakpoint: [ field to set breakpoint (in px/em??) ]

**Comment by klonos** [comment] 2016-12-24 20:57
...btw, it would be great if we had https://www.drupal.org/project/breakpoints in core so that themes and modules (like the admin_bar.module) can use them.

**Comment by klonos** [comment] 2016-12-24 21:03
...actually not themes. In Backdrop layouts could use the breakpoints. Right?

**Comment by herbdool** [comment] 2016-12-26 21:32
I've updated my PR. That was a bit harder to figure out than I thought. I don't know if I've got a good approach but it seems to be the only way I've gotten it to work.

There's a checkbox when you configure the Primary Navigation only and it allows you to display the menu toggle. I've created a template `block--system--main-menu.tpl.php` where the button is added.

**Comment by herbdool** [comment] 2016-12-26 21:36
@klonos good suggestions re breakpoint, but I see those as new feature requests that can be added later.

**Comment by jenlampton** [comment] 2016-12-27 00:32
>  I've created a template block--system--main-menu.tpl.php where the button is added.

Hm, that doesn't sound right. The markup should be in the menu output itself, not in the output for the block around the menu.  Yes, this sounds tricky...  Hm...

**Comment by herbdool** [comment] 2016-12-27 00:41
Actually, it's in the same location as my first attempt: a sibling of the ul tag. I had attempted to try to use theme_menu_tree or override it but gave up. This was less intrusive.

**Comment by jenlampton** [comment] 2016-12-27 00:44
> I had attempted to try to use theme_menu_tree or override it but gave up. This was less intrusive.

Yeah, I think in contrib I might have chosen to use the block template too, but in core we need to do it the right way.  `theme_menu_tree` would be a good place, or maybe `theme_menu_tree__dropdpwn` would be better ;)

**Comment by herbdool** [comment] 2016-12-27 00:59
Funnily theme_menu_tree is only possible in Backdrop because Drupal 7 didn't pass the depth of the menu so someone couldn't just apply a wrapping to the outer only.

Anyway, I'm not clear on why using the block template is not right here. It's not doing anything weird and seems like it would have been the likely option in Drupal 7.

**Comment by jenlampton** [comment] 2016-12-27 01:03
> I'm not clear on why using the block template is not right here.

Because someone could override a block template (copied from core system.block.tpl.php, or otherwise) and end up 'breaking' the menu. Menu markup needs to appear when the menu is rendered. Block markup needs to appear when the block is rendered, etc.

**Comment by jenlampton** [comment] 2016-12-27 01:06
Or, what about adding a new theme function `theme_menu_dropdown` that adds the hamburger menu (or not) and then calls `theme_menu_tree`?

**Comment by herbdool** [comment] 2016-12-27 01:10
I'll need some walking through this.

The menu isn't rendered until it reaches that template. Until that point it's still a render array. 

And the previous attempt could also easily be overridden by someone putting a MYTHEME_menu_tree in their theme.

I think the menu toggle didn't quite fit in either perfectly. It's technically not part of the menu but it also has to be right next to it and only rendered if the menu block is rendered.

**Comment by herbdool** [comment] 2016-12-27 01:12
> Or, what about adding a new theme function theme_menu_dropdown that adds the hamburger menu (or not) and then calls theme_menu_tree?

Perhaps. It's possible though that someone wants the hamburger even if they're not using the dropdown.

**Comment by herbdool** [comment] 2016-12-27 01:18
Since that block template is just for the main menu someone would need to copy the same template and not a more general one in order to override it. (Pretty sure anyway)

**Comment by jenlampton** [comment] 2016-12-27 01:20
> It's possible though that someone wants the hamburger even if they're not using the dropdown.

Hm, okay. What if we added it via a new theme function? Something like `theme_menu_toggle()`?

We could add it in `system_menu_block_build` as  `#prefix` inside 
```
if ($config['style'] === 'dropdown') {
```

**Comment by jenlampton** [comment] 2016-12-27 01:38
> The menu isn't rendered until it reaches that template. 

Yeah, so I guess we should be altering the renderable instead.

> And the previous attempt could also easily be overridden by someone putting a MYTHEME_menu_tree in their theme.

Also a problem...

> Since that block template is just for the main menu someone would need to copy the same template and not a more general one in order to override it. (Pretty sure anyway)

Yeah, we're creating a lot of ways a theme developer could shoot themselves in the foot with this, we should try to avoid that situation as much as possible. Let's only override core templates if it's both sensible and necessary.

I've added a small commit in https://github.com/herbdool/backdrop/pull/1 that adds the menu via a new theme function (so people could get it without needing to render a menu) and attaches it to the rennder array via `#prefix`.  What do you think of something like that?

**Comment by herbdool** [comment] 2016-12-27 19:29
> With template files there can be any number of sources (block.tpl.php, block--system.tpl.php, block--system--main-menu.tpl.php, etc) so the more we override the more confusing it is for people to find the right source to copy.

Someone can't override a more specific tpl file with a more generic one. Perhaps I misunderstand your point, but I don't think that's an issue. Either way someone would need to know about the specific theme function or template file in order to "shoot themselves in the foot".

Your idea could work too. I tried it and added a theme function to the prefix. For some reason, it strips out the label tag, but not the input tag.

**Comment by wesruv** [comment] 2016-12-27 19:47
Sorry I'm behind on this issue. I wrote all of the CSS, JS and template code necessary to achieve this in the new backdropcms.org theme, should be fairly straightforward to port to core... there might be some styling that needs to be made more generic, and I need to do an accessibility check on it, but it's functioning well.

Here's the markup:
https://github.com/backdrop-ops/backdropcms.org/blob/301-new-theme-based-on-homepage-designs/www/themes/basis_borg/template.php#L34-L51

Here's the styles (with fancy pants animations):
https://github.com/backdrop-ops/backdropcms.org/blob/301-new-theme-based-on-homepage-designs/www/themes/basis_borg/css/component/burger-toggler.css

No JS required 😄 I'm using an 'form hack' to make this work with CSS only. I don't think that's "ideal", but I do think it is better than relying on JS to show a hidden navigation, and I think aria attributes can make sure that it makes sense for assistive tech.

**Comment by wesruv** [comment] 2016-12-27 19:51
Oh, and that's the same hack that smartmenu's recommends 😛

**Comment by herbdool** [comment] 2016-12-28 15:17
Fixed a small mistake (after going on a wild goose chase). It does output the html properly. I'll update the PR and then look into rolling in @wesruv's changes.

**Comment by herbdool** [comment] 2016-12-28 15:40
@wesruv @jenlampton to get it to work for any menu will require a bunch of changes to the css and js, plus likely css override in Basis so it looks nice with its defaults. How important is it that the hamburger work for any menu?

**Comment by wesruv** [comment] 2016-12-28 15:57
I think it should be functional with core and look slick in Basis. I think we can get something solid for 90% of the menus... probably?

I can take a crack at correcting the styles for core/Basis if the config/backend dev stuffs is done.

**Comment by herbdool** [comment] 2016-12-29 15:01
A user can add multiple menus to the same layout, even of the same one, so I've found that the solution in the css of using an input with an id connected to the label won't work unless this can be generated dynamically so each id/for pair is unique.

```
<input id="menu-toggle--state" type="checkbox" />
'<label class="menu-toggle--btn" for="menu-toggle--state">
```

**Comment by herbdool** [comment] 2016-12-29 16:38
There are a couple ways to solve it. Either add a hidden menu config which creates a unique hash for the toggle id, or do it in JS as smartmenu is doing to populate the data-smartmenus-id. Not sure which way would be considered better. The first approach avoids relying on JS.

**Comment by herbdool** [comment] 2016-12-29 22:00
I've updated the PR. It's closer to working for any menu. I added a hash to the toggle so each id is unique. I removed the JS and added the css from @wesruv.

The toggle is hidden when logged in with the css from @wesruv. I believe it's because the class .contextual-links-region is added for admin users and this class adds position: relative to the wrapper div for the menu.

It's still not graceful if there are multiple menus in the layout with the toggle enabled. Plus it seems to assume the menu will be at the top. We'd have to account for each variation.

**Comment by jenlampton** [comment] 2017-01-01 00:34
@wesruv sounds like the ball is in your court? Sounds like we're really close! :)

**Comment by jenlampton** [comment] 2017-01-02 20:00
I'm going to take a stab at this one since I just added/fixed a similar feature on https://www.drupal.org/project/smartmenus :)

**Comment by jenlampton** [comment] 2017-01-02 22:35
New PR is up at https://github.com/backdrop/backdrop/pull/1708

I did some reworking of the CSS provided by @wesruv because the selectors weren't inline with the way we do CSS in the rest of core. I also added back the JS effect for sliding the menu open/closed since I couldn't determine if the CSS solution (using VH) would work on all browsers, and the JS is a proven solution. ( I basically put it back to the recommended CSS from the smartmenus library, but we can iterate and improve after Jan 1st if necessary.) I also cleaned up the markup to be easier for devs to read, and some of the PHP too, since I was in there anyway.

This is ready for user-testing if we have any takers :)

**Comment by olafgrabienski** [comment] 2017-01-03 00:10
Had a quick look at the new PR: The hamburger button and the block setting (if to show the hamburger button on small screens) worked fine.

**Comment by herbdool** [comment] 2017-01-03 00:22
@jenlampton I've put some comments on the PR

**Comment by Dinornis** [comment] 2017-01-03 04:14
Which PR needs testing?
1808 does not work and 1712 runs the install.

**Comment by jenlampton** [comment] 2017-01-03 04:15
https://github.com/backdrop/backdrop/issues/1712 needs testing.

**Comment by quicksketch** [comment] 2017-01-03 04:41
I closed the previous PR as the sandbox functionality seemed broken. Latest PR is now at https://github.com/backdrop/backdrop/pull/1714.

Some feedback:

- I'm not a big fan of the random hashes getting assigned to the menu IDs. Could we just use `backdrop_html_id()` to ensure unique identifiers in the same way that Form API does?
- The word "Menu" seems to be invisible on mobile, for accessibility and explanation, I think it would be best if the default CSS included the display of this text:
  ![screenshot from 2017-01-02 20-37-21](https://cloud.githubusercontent.com/assets/100206/21600087/9c35671e-d12b-11e6-9fde-1054b317cd12.png)
- As a potential follow-up, it's very strange now with the "secondary" links being huge and the primary links stashed away in a hamburger, as you can see from the above screenshot. We need better styling in Basis for the header menu links after this change.

**Comment by jenlampton** [comment] 2017-01-03 04:54
> Could we just use backdrop_html_id() to ensure unique identifiers in the same way that Form API does?

Can you think of an example of that we can copy?

> The word "Menu" seems to be invisible on mobile

Hm, I missed that. I agree, we can get it back.

> As a potential follow-up...

Yes, let's work on that tomorrow :)

**Comment by jenlampton** [comment] 2017-01-03 05:13
okay, I think I got it:
```
      $id = backdrop_html_id('menu-toggle-state');
      $data['content']['#wrapper_attributes']['data-menu-toggle-id'] = $id;
      $data['content']['#prefix'] = theme('menu_toggle', array('enabled' => $config['toggle'], 'id' => $id, 'text' => t('Menu')));
```

**Closed** 2017-01-03 06:15 UTC
Labels: pr - needs review, type - feature request

**Comment by quicksketch** [comment] 2017-01-03 06:17
Yay, new `backdrop_html_id()` approach works great and saves us from those hashes ending up in the config files. I made a few last tweaks to the CSS and docblocks. Merged https://github.com/backdrop/backdrop/pull/1715 into 1.x for 1.6.0. Woot!
