### ISSUE TITLE
Temporary files directory: Not fully protected

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1085] opened 2015-08-03 11:23 UTC
![backdrop-site_status_page-temp_files_directory-not_fully_protected](https://cloud.githubusercontent.com/assets/2423362/9036944/b0c0f5bc-3a29-11e5-9dbc-affe6cf419da.png)

Couple of issues here:
- is it ok that we point to d.org?
- can't we auto-create the .htaccess file?

**Comment by klonos** [comment] 2015-08-03 11:57
I see what might have happened here...

![backdrop-temp_dir_settings](https://cloud.githubusercontent.com/assets/2423362/9037054/98c596e2-3a2a-11e5-9f63-84b513936d8a.png)

This is a fresh installation of both my local dev environment as well as the backdrop installation. The ```C:\www``` directory is NOT where my Backdrop installation resides - it is under ```C:\www\backdrop```. So why did Backdrop pick ```C:\www\temp``` as the temp directory instead of ```files\temp``` for example?

**Comment by klonos** [comment] 2015-08-03 12:04
...so I manually changed the temp dir to ```files\temp``` and saved config. This has successfully created the ```\temp`` dir under ```C:\www\backdrop\files``` along with a ```.htaccess``` file in it. The contents of the file are:

```
    # Deny all requests from Apache 2.4+.
    <IfModule mod_authz_core.c>
      Require all denied
    </IfModule>

    # Deny all requests from Apache 2.0-2.2.
    <IfModule !mod_authz_core.c>
      Deny from all
    </IfModule>
```

...but the error in the site status page still remains.

**Comment by serundeputy** [comment] 2015-08-03 12:10
there is a `PR` over here: https://github.com/backdrop/backdrop-issues/issues/1059 not merged in yet though.

**Comment by klonos** [comment] 2015-08-03 17:10
Thanx @serundeputy, but from what I can see in that PR, what it changes is **what** is written in .htaccess - not **where** it is written. In my case, the .htaccess file was placed in a ```temp``` directory **outside** Backdrop installation folder (one level up the directory structure).

Also, since the contents of the file were overwritten instead of appended, the PR only fixes new installations - it does not correct current installations. What should the full content of the .htaccess file be?

**Comment by quicksketch** [comment] 2015-08-03 21:21
The full contents of the file for temp and private file directories should be:

```
# Turn off all options we don't need.
Options None
Options +FollowSymLinks

# Set the catch-all handler to prevent scripts from being executed.
SetHandler Drupal_Security_Do_Not_Remove_See_SA_2006_006
<Files *>
  # Override the handler again if we're run later in the evaluation list.
  SetHandler Drupal_Security_Do_Not_Remove_See_SA_2013_003
</Files>

# If we know how to do it safely, disable the PHP engine entirely.
<IfModule mod_php5.c>
  php_flag engine off
</IfModule>

# Deny all requests from Apache 2.4+.
<IfModule mod_authz_core.c>
  Require all denied
</IfModule>

# Deny all requests from Apache 2.0-2.2.
<IfModule !mod_authz_core.c>
  Deny from all
</IfModule>

```

If these files are incorrect, they can be deleted and then the File settings can be resaved. I agree though, perhaps what we should try is an update hook that recreates these files without the manual step if you have a mangled .htaccess file. The slightly ironic part of all this however is that the `Deny from all` line actually *is* secure enough that no files could be served from temp or private. The .htaccess file is overly verbose.

**Comment by klonos** [comment] 2015-08-03 22:12
Fair enough. Any clues as to why the ```temp``` directory was created outside the installation folder?

**Comment by quicksketch** [comment] 2015-08-03 22:18
> Any clues as to why the temp directory was created outside the
installation folder?

Not sure about this one. I haven't been able reproduce this one. By
default, Backdrop will use PHP's setting for the temporary file location,
e.g. `ini_get('upload_tmp_dir');`.

**Comment by klonos** [comment] 2015-08-03 22:34
OK, my WAMP's ```upload_tmp_dir``` is indeed set to ```C:\www\temp``` so this whole thing does make sense now that I know this. But, here a question: so I have a single local environment on which I test multiple Drupal and Backdrop installations. If they all use the same temp dir (the one defined by ```upload_tmp_dir```), would that be a reason for potential conflicts? If so, is it a good idea to use the ```upload_tmp_dir``` or would it be better that a ```temp`` folder was created inside ```files``` instead?

**Comment by quicksketch** [comment] 2015-08-03 22:53
> or would it be better that `temp` folder was created inside `files` instead?

Backdrop/Drupal putting an .htaccess file inside of /tmp has always been a bit over-zealous. However, the default temp directory (usually `/tmp`) usually has special treatment by the OS. On most systems, this directory will be entirely emptied upon restart, making it self-cleaning in a way. Using the normal "files" directory for temporary files is taking on some responsibility for emptying this directory occasionally (though Backdrop does a pretty good job of cleaning up after itself).

So I think the best thing for us to do would just create a sub-directory under the default temp directory, e.g. a `/tmp/backdrop` directory upon installation. Though we'll need to check that the directory exists after restarts as well.

> I have a single local environment on which I test multiple Drupal and Backdrop installations. If they all use the same temp dir (the one defined by upload_tmp_dir), would that be a reason for potential conflicts?

Yes, you could be getting conflicts. Although at this point we actually check for the same string as Drupal does, so they should work with each other currently. There's no guarantee of that in the future however.

**Comment by klonos** [comment] 2015-08-03 23:04
> Though we'll need to check that the directory exists after restarts as well.

That yes, but also check that another Backdrop installation has not created and/or is not using that very same directory (remember multiple Backdrop installations?). That's why I suggested using ```files``` instead. Unless that directory was ```/tmp/backdrop-[unique_site_key]``` or something so that we make sure that each Backdrop installation has its own temp dir under ```/tmp```.

Makes sense?

PS: We could use the md5 from ```$config_directories``` as the ```-[unique_site_key]``` part ...or the ```$settings['hash_salt']```.

**Comment by klonos** [comment] 2015-08-03 23:06
...or simply create the ```temp``` dir under ```files```?

**Comment by quicksketch** [comment] 2015-08-03 23:45
I don't like creating a temp directory under files because it won't get cleaned up automatically. And considering .htaccess only works for Apache, but nginx configs are becoming more common, I wouldn't want to expose the temporary directory into a web-accessible location by default with only .htaccess to protect it.

Protections aren't even necessary on the temp directory *unless* it's web-accessible, so most of the time you get this warning, it's not even accurate. Maybe we should adjust how this whole .htaccess business works for the temporary directory and just skip it entirely unless its within the web root of the Backdrop installation?

**Comment by klonos** [comment] 2015-08-03 23:52
Once again, fair enough. All I care is that I need my site status pages clear of any warnings and all my various test installations not conflicting with each other. I do not care how this is implemented. I can help with testing anything new that you might decide to implement though. Just let me know.

**Comment by jenlampton** [comment] 2021-09-16 22:22
I created a follow-up issue here to solve the problem: https://github.com/backdrop/backdrop-issues/issues/5233

Is it okay to close this question since it has been answered?

**Closed by jenlampton** 2021-09-16 22:22 UTC
Labels: type - question

**Comment by klonos** [comment] 2021-09-17 00:21
Thanks for following up on this old ticket @jenlampton 🙏🏼 ...yes. fine to close 👍🏼
