### ISSUE TITLE
'Administer vocabularies and terms' permission required to view lists of terms

### ISSUE THREAD

**Issue by kelizoliva** [backdrop/backdrop-issues#4628] opened 2020-09-18 23:44 UTC
**Description of the bug**

Unless we grant the "Administer vocabularies and terms" to a role, which allows deleting any taxonomy terms, the user of this role can navigate directly to individual terms' edit pages if they know the URL, but they are shown an "Access denied" error when trying to view lists of the terms in the taxonomy vocabularies, so they can't actually view all the terms or add new terms.

A role should be able to have permission to view/edit terms but not add or delete, but without a way to list those term nodes, it is very challenging to manage that content for a role with those permissions. Since taxonomies are different from content types, they also cannot show up listed in the Administer Content view. 

Some (somewhat) related issues are #382 and #4225.

**Comment by herbdool** [comment] 2020-09-20 11:25
While I agree this is annoying it's not a bug. It's just a quirk of Drupal that still exists. I think this a duplicate of https://github.com/backdrop/backdrop-issues/issues/382 so let's focus on giving it there. Reopen if you disagree.

**Closed by herbdool** 2020-09-20 11:25 UTC
Labels: type - feature request
