### ISSUE TITLE
error message on 1.7.0 -> 1.7.1 update

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop/backdrop-issues#2746] opened 2017-06-22 07:00 UTC
I'm getting an error message when runing update.php after code update from 1.7.0 to 1.7.1:

```
Backdrop database update

Some of the pending updates cannot be applied because their dependencies were not met.
No pending updates.
```
I cannot see any error message in any report page and apparently everyhting works fine. Could this be just a bug?

**Comment by serundeputy** [comment] 2017-06-22 20:32
I can confirm this message on a Backdrop site I maintain, but can not replicate on `1.x`; must be something different about our sites.

Question is what is the cause?  Need steps to reproduce on `1.x` to troubleshoot.

**Comment by quicksketch** [comment] 2017-06-23 21:18
Thanks for filing this bug report.

Here's the chunk of code from update.php where this message is output:

```php
  // Find and label any incompatible updates.
  foreach (update_resolve_dependencies($starting_updates) as $function => $data) {
    if (!$data['allowed']) {
      $incompatible_updates_exist = TRUE;
      $incompatible_count++;
      $module_update_key = $data['module'] . '_updates';
      if (isset($form['start'][$module_update_key]['#items'][$data['number']])) {
        $text = $data['missing_dependencies'] ? 'This update will been skipped due to the following missing dependencies: <em>' . implode(', ', $data['missing_dependencies']) . '</em>' : "This update will be skipped due to an error in the module's code.";
        $form['start'][$module_update_key]['#items'][$data['number']] .= '<div class="warning">' . $text . '</div>';
      }
      // Move the module containing this update to the top of the list.
      $form['start'] = array($module_update_key => $form['start'][$module_update_key]) + $form['start'];
    }
  }

  // Warn the user if any updates were incompatible.
  if ($incompatible_updates_exist) {
    backdrop_set_message('Some of the pending updates cannot be applied because their dependencies were not met.', 'warning');
  }
```

So it looks like there *should* be a more complete explanation of what the problem was, but perhaps it's not being printed to the page?

Ultimately though, I think this problem occurs when a module includes a function `[module_name]_update_last_removed()` but that update has not yet been run. For example if that function returns a value like `7005`, but the module's `schema_version` in the database table is `7001`. Because the module needs to run updates 7002 through 7005 but those updates no longer exist in the code.

So my guess is there is a contrib module that may be causing a problem here. However there is also a core issue in that we're not giving the user enough information about the problem to address it.

**Comment by robertgarrigos** [comment] 2017-06-23 22:34
You are right @quicksketch . The problem is with tagadelic module. On the same function that you got that piece of code I used the dpm() to through some light on this:

```
$updates = update_get_update_list();
dpm($updates);
```

And got this:

```
Array ( [tagadelic] => Array ( [warning] => tagadelic module can not be updated. Its schema version is 1000. Updates up to and including 6100 have been removed in this release. In order to update tagadelic module, you will first need to upgrade to the last version in which these updates were available. ) )
```
The fact is that the script is using the result array ```$updates``` to determine what to do by checking whether ```$updates[module]['start']``` is not set or ```$updates[module]['pending']``` is not empty. In this case 'start' is not set, then ```$incompatible_updates_exist``` is set to TRUE and ```backdrop_message()``` get this error about pending updates. But that's all. There are other variables, like a ```$count```, which could be used to print out the error message which already comes with the $updates array, or ```$incompatible_count```, but then a button to update is being printed anyway on the page. So this function would need some kind of rewrite to print out this error message and stopping the process.

Something like this would do it:

```
/**
 * Form constructor for the list of available database module updates.
 */
function update_script_selection_form($form, &$form_state) {
  ...
  foreach ($updates as $module => $update) {
    if (!isset($update['start'])) {
      $form['start'][$module] = array(
        '#type' => 'item',
        '#title' => $module . ' module',
        '#markup'  => $update['warning'],
        '#prefix' => '<div class="messages warning">',
        '#suffix' => '</div>',
      );
      $incompatible_count++; //ADDED LINE
      $count++;  //ADDED LINE
      $incompatible_updates_exist = TRUE;
      continue;
   ...
    $form['actions'] = array('#type' => 'actions');
    if (($count - $incompatible_count) != 0) { //ADDED IF
      $form['actions']['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Apply pending updates',
        );
    }
    
  }
  return $form;
}
```
In my case I only had one incompatible module to update and no other pending update. That's why the button is hidden with the if clause here.

**Comment by klonos** [comment] 2017-06-23 22:49
@robertgarrigos I'm intrigued by this bug. Can you please post a list of all your installed contrib modules?

PS: I also noticed a typo in: "This update will been skipped..."

**Comment by klonos** [comment] 2017-06-23 22:50
Oh, you have already found the offending module 😄 ..never mind then.

**Comment by klonos** [comment] 2019-05-16 13:22
...I'm gonna go ahead and close this as outdated (plus it seems that it might be an issue with the specific contrib module). Please feel free to reopen if you still think that this is a valid core bug.

**Closed by klonos** 2019-05-16 13:22 UTC
