### ISSUE TITLE
Fatal error on home page when comment module uninstalled

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4904] opened 2021-01-25 05:15 UTC
**Description of the bug**

Uninstalling the comment module causes fatal errors.

```
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'base.comment_close_override' in 'field list': SELECT revision.`vid` AS `vid`, base.`uid` AS `uid`, revision.`title` AS `title`, revision.`log` AS `log`, revision.`status` AS `status`, revision.`comment` AS `comment`, revision.`promote` AS `promote`, revision.`sticky` AS `sticky`, base.`nid` AS `nid`, base.`type` AS `type`, base.`langcode` AS `langcode`, base.`created` AS `created`, base.`changed` AS `changed`, base.`scheduled` AS `scheduled`, base.`tnid` AS `tnid`, base.`translate` AS `translate`, base.`comment_close_override` AS `comment_close_override`, revision.`timestamp` AS `revision_timestamp`, revision.`uid` AS `revision_uid`, base.vid = revision.vid AS `is_active_revision` FROM {node} base INNER JOIN {node_revision} revision ON revision.vid = base.vid WHERE (`base`.`nid` IN (:db_condition_placeholder_0)) ; Array ( [:db_condition_placeholder_0] => 1 ) in DefaultEntityController->load() (line 301 of backdrop/core/modules/entity/entity.controller.inc).
```

**Steps To Reproduce**

To reproduce the behavior:
1. Install backdrop as usual
2. Uninstall comment module
3. Visit the home page
4. See the error above.

**Actual behavior**

Fatal error on the home page.

**Expected behavior**

Home page should display as usual.

**Additional information**

Add any other information that could help, such as:
- Backdrop CMS version: 1.18.0

**Comment by jenlampton** [comment] 2021-01-25 05:18
Interesting, enabling comment module prevented the fatal error. Disabling again, and uninstalling a second time fixed the problem.

**Comment by indigoxela** [comment] 2021-01-25 07:21
Confirmed.

I followed the steps from issue description and was able to reproduce it. Flushing the caches (via commandline) immediately fixed it. So... which cache do we have to flush on module uninstall, that isn't already flushed?

As an experiment I removed the "Promoted contend" view from the home layout before disabling and uninstalling the comment module and the error didn't appear.

**Comment by indigoxela** [comment] 2021-01-25 10:52
> which cache do we have to flush on module uninstall, that isn't already flushed?

The entity_info cache (table cache, prefix entity_info:).

A [PR](https://github.com/backdrop/backdrop/pull/3514) is available for testing and review.

To test it's not necessary to install a complete Backdrop, it's sufficient to uninstall the comment module.

- Visit the front (home) page and a node page
- Go to admin/modules/list and disable comment
- Go to admin/modules/uninstall and uninstall comment
- Go to the front page

Don't do anything else between these steps.

**Comment by klonos** [comment] 2021-01-25 15:28
Thanks @indigoxela 🙏 ...code change seems straight-forward, but I was wondering if it'd make sense (if possible) to clear only cache specific to comments, rather than all entities. For example, if comments were only enabled for a single specific content type out of all content types on a site, then wouldn't it make sense to clear cache only for that bundle?

**Comment by indigoxela** [comment] 2021-01-25 15:47
> I was wondering if it'd make sense (if possible) to clear only cache specific to comments, rather than all entities.

Not sure if it's possible to further reduce this. Actually only a few rows get removed from the cache db table.

Fun fact: I figured out, which cache to flush by removing row by row from the cache tables... (Of course I had to start fresh several times.) The "fixing" row was `entity_info:en`. BTW comments are entities, too.

**Comment by indigoxela** [comment] 2021-02-10 12:27
@jenlampton can you confirm that the PR fixes the problem? The change is small, but should be effective.

**Comment by jenlampton** [comment] 2021-02-13 05:48
Confirmed! The PR fixes the home page (both with and without uninstalling comment module) Thank you @indigoxela

**Comment by quicksketch** [comment] 2021-03-04 19:34
Thanks @indigoxela! The added code appears to be identical to what `entity_info_cache_clear()` does. Entity module already clears the entity info cache when modules are disabled (or should), see `entity_modules_disabled()` (which is a hook_modules_disabled()).

Rather than making a specific clearing of the entity cache by comment module, entity module should clear its own cache automatically when comment module (or any module providing an entity type) is uninstalled.

So I would suggest we:
A) Check if `entity_modules_disabled()` is getting called and if so, why that isn't sufficient already.
B) If clearing the cache on disable is not sufficient, add `hook_modules_uninstalled()` to Entity module and clear the entity info cache when modules are uninstalled.

**Comment by docwilmot** [comment] 2021-03-04 20:11
I suspect it will be B). That `comment_close_override` field on `Node` isnt deleted until uninstall.

**Comment by indigoxela** [comment] 2021-03-05 11:45
Some problems here.

A) as @docwilmot already stated, comment_close_override still exists when the comment module is *disabled*, so the hook in the entity module does run, but doesn't help.

B) If I run entity_info_cache_clear() in a (newly implemented) entity_modules_uninstalled() it doesn't work as expected, until I register it as shutdown function

So:
```
function entity_modules_uninstalled($modules) {
  entity_info_cache_clear();
}
```
Reproducibly brings back the fatal error,
only:
```
function entity_modules_uninstalled($modules) {
  backdrop_register_shutdown_function('entity_info_cache_clear');
}
```
fixes it.

If using backdrop_register_shutdown_function() in entity_modules_uninstalled() is desirable, please let me know.

**Comment by quicksketch** [comment] 2021-03-06 04:13
Perhaps I'm missing something. Using `hook_modules_uninstalled()` should result in the same order (or later order) of operation as putting the code in `comment_uninstall()`. Reading through `backdrop_uninstall_modules()`, here's the execution order:

```
  foreach ($module_list as $module) {
    // Uninstall the module.
    module_load_install($module);
    module_invoke($module, 'uninstall'); // <--- comment_uninstall() called (as in previous PR).
    config_uninstall_config($module);
    backdrop_uninstall_schema($module);

    watchdog('system', '%module module uninstalled.', array('%module' => $module), WATCHDOG_INFO);
    backdrop_set_installed_schema_version($module, SCHEMA_UNINSTALLED);
  }

  if (!empty($module_list)) {
    // Let other modules react.
    module_invoke_all('modules_uninstalled', $module_list); // <--- entity_modules_uninstalled() called (as in new approach).
  }
```

Why wouldn't `hook_modules_uninstalled()` work when `hook_uninstall()` does? I apologize for only posting my thoughts without testing it.

**Comment by indigoxela** [comment] 2021-03-06 12:09
> Why wouldn't hook_modules_uninstalled() work when hook_uninstall() does?

I can't answer **why** it doesn't work as expected, I just realized that it doesn't - reproducibly.

While it would, of course, be good to know the exact reason, IMO our primary goal should be to fix the fatal error.

**Comment by quicksketch** [comment] 2021-03-08 02:59
> our primary goal should be to fix the fatal error.

Yep. My desire to do it absolutely "right" is trumped by fixing a critical error.

I did some additional investigation and it seems as though Layout module's `hook_modules_disabled()` seems to somehow restore the entity info cache. That does seem to get us much closer to a better fix though.

Unless a better solution comes soon, I think we should just go with the approach of the current PR, though we can use the entity_info_cache_clear() function instead of manually truncating the cache. I posted a suggestion to the PR: https://github.com/backdrop/backdrop/pull/3514/files#r589142337

**Comment by docwilmot** [comment] 2021-03-08 04:55
Interestingly the current PR doesnt work for me either:
```
  backdrop_static_reset('entity_get_info');
  cache()->deletePrefix('entity_info:');
```
in `comment_uninstall()`, disable then uninstall Comment module. Visit contents or home or a node page: error.

**Comment by indigoxela** [comment] 2021-03-08 07:10
> Interestingly the current PR doesnt work for me either:

Any idea, why that happens? Can we have some info about your testing web setup? I suppose, it's not the sandbox - or is it?

**Comment by docwilmot** [comment] 2021-03-08 14:50
My setup is latest dev 1.19 on WAMP localhost windows with a bunch of contrib modules installed. I get the fatal error anyway. Flushing the menu cache or page and else cache restores the site. If I delete my contrib modules folder (I'm assuming then that no contrib hooks run), this doesn't help, still get the fatal. Mystery.

**Comment by indigoxela** [comment] 2021-03-08 14:57
Hm, OK, Windows, that's an unlikely real-hosting environment... :wink: 

However, @docwilmot your trouble seems to be another proof that the order of hooks as they run is too unpredictable and it seems crucial that entity_info_cache_clear() runs last. Please correct me if I'm wrong.

Can you try the code from one of my previous comments in the entity.module (didn't provide it as a PR yet):
```
function entity_modules_uninstalled($modules) {
  backdrop_register_shutdown_function('entity_info_cache_clear');
}
```
I'm curious if it works as a shutdown function of it that also fails for you.

**Comment by docwilmot** [comment] 2021-03-08 15:02
Yes, the error is fixed by this method.

**Comment by docwilmot** [comment] 2021-03-08 15:21
FWIW its the `  cache()->deletePrefix('entity_info:');` that needs to run on shutdown.
This causes the fatal still:
```
function entity_modules_uninstalled($modules) {
  cache()->deletePrefix('entity_info:');
  backdrop_register_shutdown_function('tempentity_info_cache_clear');
}
function tempentity_info_cache_clear() {
  backdrop_static_reset('entity_get_info');
}
```
whereas this works fine:
```
function entity_modules_uninstalled($modules) {
  backdrop_static_reset('entity_get_info');
  backdrop_register_shutdown_function('tempentity_info_cache_clear');
}
function tempentity_info_cache_clear() {
  cache()->deletePrefix('entity_info:');
}
```
Dont know if that helps

**Comment by indigoxela** [comment] 2021-03-08 15:59
Maybe I could (sort of) reproduce the problem with a dummy module:

My "foobar" module does only this:
```
<?php

function foobar_modules_uninstalled($modules) {
  sleep(1);
}
```
But that's enough to bring back the fatal error.
With the same dummy module enabled, but the shutdown function the error gets fixed. I'll update my PR accordingly.

**Comment by indigoxela** [comment] 2021-03-19 11:07
Is there consensus that the shutdown function approach is correct?

Testing and review is welcome. As the problem is a fatal one, getting the fix in seems important to me.

**Comment by klonos** [comment] 2021-04-05 09:09
Thanks @indigoxela. Code looks good to me, and it fixes the issue 👍🏼 

Unless a core committer beats me to it and merges this, I plan to bring this issue up during our next dev meeting.

**Closed** 2021-05-03 02:52 UTC
Labels: pr - ready to be committed, pr - works for me, status - has pull request, type - bug report

**Comment by quicksketch** [comment] 2021-05-03 02:54
Thanks @indigoxela and @klonos! The final PR looks great. I appreciate the moving into `entity.module` rather than this being `comment.module` specific. I merged https://github.com/backdrop/backdrop/pull/3514 into 1.x and 1.18.x. Thanks!
