### ISSUE TITLE
Manual module (upload) installation does not work

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1920] opened 2016-05-23 14:42 UTC
Upload a module, theme, or layout archive to install

Browse

INSTALL

"Please wait..."

... and nothing happens.

Chrome and Firefox.

**Comment by quicksketch** [comment] 2016-05-23 18:11
Thanks @bd0bd! I've confirmed this problem. It looks like it's only the module *upload* that is broken. You can still type the name of a module or install one from a URL.

It seems this is related to other pages in which the auto-uploader on File Managed fields is not working, and is likely a JS problem which isn't covered by the tests.

**Comment by quicksketch** [comment] 2016-05-27 20:35
I mentioned this issue on the weekly call meeting. @docwilmot now knows about it and he may be able to help.

**Comment by quicksketch** [comment] 2016-09-16 03:01
I took a look at this but I couldn't figure out why uploads aren't working on my first pass. It looks like the archives are being uploaded properly and everything, because if you upload an invalid archive it still unzips it and throws a validation error. The problem just seems to be in the redirection code. Project Browser isn't returning an AJAX command to redirect the page. The AJAX request itself is getting redirected via a 302 redirect, which just results in a JS error because the page doesn't get back the expected JSON response.

**Comment by quicksketch** [comment] 2016-09-16 03:02
Bumping this to the next version.

**Comment by quicksketch** [comment] 2016-10-07 02:43
I finally worked this one out. The problem was that `installer_authorize_run_install()` was not written with the ability to *not* redirect immediately. As we're doing this within an AJAX request, we need to return JSON instead of doing a 302 redirect. So by adding an additional parameter to `installer_authorize_run_install()` and then passing that forward to `batch_process()`, we can prevent the redirect from happening and return an AJAX command instead.

PR at https://github.com/backdrop/backdrop/pull/1606.

**Comment by quicksketch** [comment] 2016-10-07 19:59
Merged https://github.com/backdrop/backdrop/pull/1606 for 1.5.1

**Closed** 2016-10-07 19:59 UTC
Labels: pr - needs review, status - has pull request, type - bug report
