### ISSUE TITLE
SQL subquery not always properly bracketed

### ISSUE THREAD

**Issue by lugray** [backdrop/backdrop-issues#1071] opened 2015-07-27 15:05 UTC
This is ported from Drupal.

When $sub​_query is an instance of ​​SelectInterface the following code generates invalid SQL.
```php
<?php
​​$query->condition('t.somefield', $sub​_query)​;
?>
```
The following code however, generates valid, working SQL:
```php
<?php
​​$query->condition('t.somefield', $sub​_query, 'IN')​;
?>
```
The second example works because brackets are added around the sub-​query because it's understood that there are multiple values to test against​. If however, your sub-query ​is designed to return a single value, it would make more sense to use the first example (defaulting to an '=' operator), or you may even wish to use something like
```php
<?php
​$query->condition('t.somefield', $sub​_query, '<'​);​
?>
```
In which case brackets are not added around the sub-query resulting in the SQL syntax error. At the moment condition values only get bracketed based on the operator used. They also need to be bracketed regardless of operator when the condition value is an instance of ​SelectInterface​.

**Comment by quicksketch** [comment] 2015-07-27 15:13
Hi @lugray! Excellent. Could you provide the URL to the Drupal issue for reference? Normally we'll port everything from Drupal when the next release comes out, reapplying every patch if needed.

Overall though, everything makes sense to me. The PR at https://github.com/backdrop/backdrop/pull/1005 looks good. Are there any tests for this new functionality? It seems like an ideal candidate to have a test to prevent future regressions.

**Comment by lugray** [comment] 2015-07-27 15:16
Drupal Issue:  https://www.drupal.org/node/2540434

I agree, now that you mention it, that some new tests would be good.  Do you have any advise on where to implement those?  This is my first contribution (in both projects).

**Comment by quicksketch** [comment] 2015-07-27 15:27
>  Do you have any advise on where to implement those?

In Backdrop, you can find the database_test.test file inside of the SImpleTest module. Within that file, there is a DatabaseSelectSubqueryTestCase class. I would suggest just amending the existing testConditionSubquerySelect method in there to add an additional query and assert statements.

> This is my first contribution (in both projects).

Excellent! Welcome and we're thrilled to have you here. :smile:

**Comment by lugray** [comment] 2015-07-27 19:49
The additional query and assertion have been added as suggested.

**Comment by quicksketch** [comment] 2015-07-27 21:25
Excellent, looks good to me. Could you squash all the commits together into a single commit, with the commit message `Issue #1071: SQL subquery not always properly bracketed.` ? We like to include the issue number in the commit messages so that we can associate the changes in the future from a `git blame`.

**Comment by lugray** [comment] 2015-07-28 12:23
Done.  Thanks for walking me through the process.

**Comment by quicksketch** [comment] 2015-08-03 20:24
Hi @lugray, it looks like you've gotten some feedback from the Drupal community on this PR as well. I think that you've described a problem and provided a solution to it. The new issue at https://www.drupal.org/node/1267508 encompasses a slightly larger scope than the original problem. If you could reroll your PR based on Crell's good feedback here I think this would be great to include.

It looks like the latest code is https://www.drupal.org/node/1267508#comment-10168806, which used a protected method and returned by value instead of reference.

**Comment by lugray** [comment] 2015-08-04 13:05
The PR has now been updated to match the patch submitted to Drupal.

**Comment by quicksketch** [comment] 2015-08-04 22:19
Thanks @lugray! The PR at https://github.com/backdrop/backdrop/pull/1005 has been merged into 1.x and 1.1.x. You're officially a core contributor. :smile:

**Closed** 2015-08-04 22:36 UTC
Labels: type - bug report

**Comment by klonos** [comment] 2015-08-05 06:02
@lugray I'd like to also welcome you on-board Lisa (though not a coder or core contributor myself - just a old-time Drupal user and Backdrop enthusiast). Thank you for your time spent on Backdrop. I really appreciate it and we need all the help we can get to make this an awesome(r) CMS.
