### ISSUE TITLE
Fixed: Some tests throw stat failed exceptions.

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#5799] opened 2022-09-25 23:12 UTC
## Description of the bug

A number of tests throw errors saying "filesize(): stat failed for &lt;uri&gt;".  These warnings happen while the tests are cleaning up and the test files in question are being deleted.  Somehow, they get deleted before the call to `preSave()`.

There are a few options here.  One is to look at `$entity->status` or call `file_exists()` and set the filesize to `NULL` if there is nothing there.  Another is to @-prefix the `filesize()` call to silence errors and warnings.

The backtrace looks like:
```
preSave()(entity.controller.inc:759); 
save()(entity.class.inc:299); 
save()(file.inc:764); 
file_usage_delete()(file.field.inc:300); 
file_field_delete()(image.field.inc:347); 
image_field_delete()(field.attach.inc:178); 
_field_invoke()(field.attach.inc:1000); 
field_attach_delete()(entity.controller.inc:833); 
invokeHook()(node.entity.inc:604); 
invokeHook()(node.entity.inc:445); 
delete()(entity.module:615); 
entity_delete_multiple()(node.module:1071); 
node_delete_multiple()(views_query.test:132); 
setUp()(comment_views_handler_argument_user_uid.test:37); 
setUp()(backdrop_web_test_case.php:627); 
run()(run-tests.sh:600); 
simpletest_script_run_one_test()(run-tests.sh:113); 
```

## Steps To Reproduce

To reproduce the behavior:

1. Enable warnings in php.ini.
2. Run an affected tests, such as CommentViewsHandlerFilterUserUidTest 
 
## Actual behavior

Tests failures look like this:

```
---- Comment: Tests handler filter_comment_user_uid (CommentViewsHandlerFilterUserUidTest) ----


Status    Group      Filename          Line    Function                            
------------------------------------------------------------------------------------------------------------------------
Exception Warning    file.entity.inc   201     preSave()                                                               
    filesize(): stat failed for public://field/image/card1-layout_800.png
Exception Warning    file.entity.inc   203     preSave()                                                               
    filesize(): stat failed for public://field/image/card1-layout_800.png
Exception Warning    file.entity.inc   201     preSave()                                                               
    filesize(): stat failed for public://field/image/card2-card_799.png
Exception Warning    file.entity.inc   203     preSave()                                                               
    filesize(): stat failed for public://field/image/card2-card_799.png
Exception Warning    file.entity.inc   201     preSave()                                                               
    filesize(): stat failed for public://field/image/card3-organize_799.png
Exception Warning    file.entity.inc   203     preSave()                                                               
    filesize(): stat failed for public://field/image/card3-organize_799.png
```

## Expected behavior

Tests pass.

## Additional information

Add any other information that could help, such as:
- Backdrop 1.x backdrop/backdrop#bcfb8e9
- Nginx
- PHP 7.0 and 7.4
- Debian 9 and Debian 11.

**Comment by jlfranklin** [comment] 2022-09-26 16:34
I am no longer able to reproduce this with Backdrop or MySQL, only with other database backends using Silkscreen.

**Comment by indigoxela** [comment] 2022-09-27 06:59
> ... stat failed for public://

@jlfranklin This is one of our "random buddies". It may be that using another db backend might trigger it more often - which would give us a better chance to figure out, what happens.

Personally, I don't think we should just silence the error.

A weird little detail `card1-layout_800.png` - doesn't that mean that it was attempted 800 times to create that image?

The actual name would be `card1-layout.png`, the next attempt adds a number to the name... and so on.

**Comment by jlfranklin** [comment] 2022-09-27 13:40
> Personally, I don't think we should just silence the error.

I agree.

> This is one of our "random buddies". It may be that using another db backend might trigger it more often - which would give us a better chance to figure out, what happens.

Well, it is 100% reproducible when I test with Silkscreen and something else, like Sqlite.

> A weird little detail card1-layout_800.png - doesn't that mean that it was attempted 800 times to create that image?

Not sure.  The setup for the test installs the standard profile, which copies the card1-layout.png (and friends) to the public://field/image directory, yes, incrementing the number each time.  Across the entire test suite, it may very well install the profile 800 times.

**Comment by indigoxela** [comment] 2022-09-27 14:43
Interesting - I can reproduce the failure/exceptions locally on my dev. When running only that single test (CommentViewsHandlerFilterUserUidTest).

So I digged a bit, then stuffed function BackdropLocalStreamWrapper::getLocalPath() with debugs:

```
  protected function getLocalPath($uri = NULL) {
    debug($uri); // NULL
    if (!isset($uri)) {
      $uri = $this->uri;
    }
    debug($uri); // 'public://field/image/card1-layout_9.png'
    $path = $this->getDirectoryPath() . '/' . $this->getTarget($uri);
    debug($path); // 'files/simpletest/772326/field/image/card1-layout_9.png'
    $realpath = realpath($path);
    if (!$realpath) {
      // This file does not yet exist.
      $realpath = realpath(dirname($path)) . '/' . backdrop_basename($path);
    }
    debug($realpath); // 'files/simpletest/772326/field/image/card1-layout_9.png'
    $directory = realpath($this->getDirectoryPath());
    debug($directory); // '/var/www/crashburn/html/files/simpletest/772326'
    if (!$realpath || !$directory || strpos($realpath, $directory) !== 0) {
      return FALSE;
    }
    return $realpath;
  }
```
Extracting the real file path seems to work correctly, but in some cases file_stream_wrapper_get_instance_by_uri() seems to end up with FALSE.

Another finding - the numbers also increase here - they shouldn't IMO.
Funny - some card images get written to the actual (live) files directory instead of the random simpletest folder, so after some test runs I have quite a lot of card*_*.png in my actual file directory under /files/field/image. Could it be that the images - under some circumstances - get written to the wrong place and the stat fails as the file isn't where it's supposed to be?

**Comment by indigoxela** [comment] 2022-09-28 08:45
Some discussion in our Zulip chat - seems like the problem isn't reproducible with Apache/mod_php.

I'm running Apache/php-fpm and the problem is 100% reproducible with both, php7.4 and php8.1. So it might depend on the php SAPI in use.

**Comment by indigoxela** [comment] 2022-09-28 14:56
Crazy idea - the problem *some* environments seem to have, has to do with the card images, which ship with the "standard" profile. We could switch to the "testing" profile, which would fix the immediate issue and is an open task, anyway. The testing profile is the recommended one for tests.

**Comment by indigoxela** [comment] 2022-09-28 15:20
A [PR](https://github.com/backdrop/backdrop/pull/4219) is available for testing and review.

That way we might also get rid of another "random buddy" in our GHA test runs. :crossed_fingers:

**Comment by indigoxela** [comment] 2022-09-29 07:28
@jlfranklin are you able to test the PR?

**Comment by klonos** [comment] 2022-09-29 07:47
Code-wise this looks good to me 👍🏼 

>Well, it is 100% reproducible when I test with Silkscreen and something else, like Sqlite.

Leaving it to you then @jlfranklin to test and confirm that the tests don't fail with this change.

**Comment by indigoxela** [comment] 2022-10-05 14:41
@jlfranklin friendly reminder: are you available to test this PR? As you reported the problem, you're the ideal candidate for testing.

**Comment by hosef** [comment] 2022-10-20 16:40
@indigoxela I have been running into this on my local environment, and it appears to be related to the order in which the setup steps are run when not using the profile cache. Essentially, the install process is run before the public file directory is changed. 

This was not a problem before, but now that we are creating files as part of the default content in standard.install we have files going into the root files directory instead of the test prefixes file directory. Then, once the file directory is changed, it can no longer find the files. This does not happen when using the prefix cache because the file directories are built and saved ahead of the test running, so everything is already in the correct place.

**Comment by indigoxela** [comment] 2022-10-21 06:17
@hosef are you suggesting to keep the standard profile for the test, or should we combine both changes, or should we open an extra issue for one of these?

**Comment by hosef** [comment] 2022-10-21 06:51
Changing the profile from standard to testing would fix the issue, and it would probably make the test faster, but there are a bunch of other tests that have the same issue. If we fix it in the setup function, then it would be fixed for all of them.

We could commit both since in general I am in favor of moving tests to use the testing profile.

**Comment by indigoxela** [comment] 2022-10-21 06:58
Two PRs that do different things merged with the same issue seems a bit messy to me. I could open a new one for the test profile switch and we can proceed here with the more general solution.

@hosef what do you think?

**Comment by hosef** [comment] 2022-10-21 07:02
That sounds good to me.

**Comment by indigoxela** [comment] 2022-10-21 09:16
Works for me, tested locally on PHP 8.1. :+1: 

Without caching and without patch applied:

Comment: Tests handler filter_comment_user_uid (CommentViewsHandlerFilterUserUidTest) 15 passes, 0 fails, 3 exceptions, and 7 debug messages

With patch applied:

Comment: Tests handler filter_comment_user_uid (CommentViewsHandlerFilterUserUidTest) 15 passes, 0 fails, 0 exceptions, and 7 debug messages

Also verified by running that test via UI.

**Comment by jlfranklin** [comment] 2022-10-23 00:10
The patch in backdrop/backdrop#4238 works in my Silkscreen tests, too.  Thanks for the patch!

@indigoxela @hosef

**Comment by jenlampton** [comment] 2022-12-02 22:54
A nice simple solution, RTBC after code review.

**Closed** 2022-12-02 23:00 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2022-12-02 23:01
Thanks for the final review @jenlampton! I merged https://github.com/backdrop/backdrop/pull/4238 into 1.x and 1.23.x. Thanks @hosef, @jlfranklin, and @indigoxela!
