### ISSUE TITLE
Views: Incorrect filter group OR behavior, LEFT JOIN changed to INNER JOIN

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3415] opened 2018-12-09 19:04 UTC
This is the respective issue for https://www.drupal.org/project/drupal/issues/1766338

That issue with Views seems to have regressed between 3.3 (released Feb 2012) and 3.4 (Aug 2012). Given that Backdrop 1.0.0 was released in Jan 2015, we must have inherited it.

As a summary, this issue is causing views with a SQL query containing a logical structure as simple as the following to not work correctly:
```
  AND A, B
OR
  AND X, Y
```
Given such a basic structure, it's likely that a huge number of views are not working correctly.

There is [a comment](https://www.drupal.org/project/drupal/issues/1766338#comment-6424788) in the issue in d.org which is pointing to a specific commit (`994acb299405ff0651706c020cf5d4e6d689e8b3`), which seems to only include a class name change. So it seems that the commit was part of [issue 1494884](https://www.drupal.org/project/views/issues/1494884), which is currently in "needs work" status.

Steps to reproduce:

* to a content type with existing content: add a boolean field
* to a view for published content of that type: add the new field to the filter as OR - Is one of - 1
* Expected: No change on the result list
* Actual: No results

---

~PR by @klonos https://github.com/backdrop/backdrop/pull/2414~
~PR by @jenlampton https://github.com/backdrop/backdrop/pull/3100~
PR by @laryn https://github.com/backdrop/backdrop/pull/3702

**Comment by klonos** [comment] 2018-12-09 19:17
@jenlampton you seem to have rolled [a patch for this](https://www.drupal.org/project/drupal/issues/1766338#comment-11560273) back in Aug 2016, which you reported working still up until Views 7.x-3.18. I have rolled the same patch in a PR for Backdrop.

@mikemccaffrey you might wanna give it a go, since you mentioned this over in Gitter 😉

**Comment by herbdool** [comment] 2019-01-03 02:47
There's a newer but very similar patch https://www.drupal.org/project/drupal/issues/1766338#comment-12287268 which only changes it to LEFT if it's not using the grouped filters. I think that would be a less invasive change.

**Comment by jenlampton** [comment] 2019-01-15 20:41
This issue still needs more feedback, removing milestone, but adding milestone candidate tag.

**Comment by jenlampton** [comment] 2020-03-20 19:16
Filed an updated PR, and posted a new patch in the [drupal queue](https://www.drupal.org/project/views/issues/1428158#comment-13517090)

**Comment by jenlampton** [comment] 2020-09-04 02:49
Filed an updated PR and posted a new patch in the drupal queue again. 

The solution in the patch recommended by @herbdool is reported as not working on Drupal 7. I've rolled another patch more similar to the Drupal 8 approach (hard-coding an exception for the `taxonomy_index_tid` plugin) that might still fix the problem while still including the check for grouped filters.

**Comment by laryn** [comment] 2020-11-17 19:58
I just tested and the view I am troubleshooting was not solved by the latest PR. When I test the original patch from @klonos the issue is solved, however.

**Comment by laryn** [comment] 2020-12-01 23:05
Sandbox is broken - @jenlampton can you refresh it?

**Comment by jenlampton** [comment] 2021-02-25 18:21
I rebased and pushed a new PR...  checking to see if that worked!

**Comment by laryn** [comment] 2021-05-07 15:20
Sorry to report but @jenlampton PR still isn't working on the site that I keep getting hit with this on. I end up having to use @klonos patch to revert it to a LEFT join after each update in order for my view with an "OR" filter grouping to work.

**Comment by laryn** [comment] 2021-05-07 15:46
Here's some testing I've done in the sandbox. I set up a vocabulary to be used with Post content and a vocabulary to be used with Page content. I added a term from the respective types to the default Post/Page content. I set up a View with an "OR" filter group, that should pull any published Post content that has the Post tag, OR any published Page content that has the Page tag. Here are some screenshots of the results, including testing tweaks in the filters:

## **Using "Has taxonomy term" instead of the field name for that term reference (only 1 result instead of 2):**
![Screen Shot 2021-05-07 at 10 37 06 AM](https://user-images.githubusercontent.com/871421/117474789-eb835880-af20-11eb-90d3-6dd93ef403df.jpg)

## **Changing to field name for both term reference fields (no results):**
![Screen Shot 2021-05-07 at 10 38 03 AM](https://user-images.githubusercontent.com/871421/117474883-0786fa00-af21-11eb-8267-bf1cdb72a8b1.jpg)

## **Removing one of the terms from the filters (one result):**
![Screen Shot 2021-05-07 at 10 38 54 AM](https://user-images.githubusercontent.com/871421/117475005-2c7b6d00-af21-11eb-8e13-b178754439e4.jpg)

## **Removing both terms from filters so there is no taxonomy filtering (two results):**
![Screen Shot 2021-05-07 at 10 39 35 AM](https://user-images.githubusercontent.com/871421/117475157-5896ee00-af21-11eb-91b7-656ef1f26e65.jpg)

**Comment by klonos** [comment] 2021-08-30 19:34
Both PRs seem mostly the same to me, with @laryn's adding some defensive coding around `$plugin_id`.

@laryn do you mind adding steps to reproduce for your case as well?

**Comment by laryn** [comment] 2021-08-30 19:49
@klonos I think this is an accurate reproduction of the issue I kept running into:

 - https://github.com/backdrop/backdrop-issues/issues/3415#issuecomment-834550640

**Comment by indigoxela** [comment] 2021-09-06 07:17
I think, now I got it. It took me a while to get, where the views_many_to_one_helper strikes. :wink:

Yes, confirmed, it works with the patch applied. Otherwise the result is empty, even if there should be records, and I also confirmed the (correct) switch to left join in the query.

Although @laryn asked for code review in the chat, I'm setting the "works for me" label, because that has to be the first step.

Maybe @herbdool wants to do the additional code review?

**Comment by indigoxela** [comment] 2021-09-15 06:38
Time to fix this issue. :wink: 

I took a look at the related Drupal issues and comments, mostly because I wanted to find an explanation, why `'taxonomy_index_tid'` has to be hardcoded (and what's so special about terms, that they need extra care).
Their conclusion seems to be that they didn't want to let the "perfect be the enemy of the good". And I think, the same is true for us. :smirk: 

RTBC!

**Comment by klonos** [comment] 2021-09-15 10:53
> ...they didn't want to let the "perfect be the enemy of the good". And I think, the same is true for us.

I agree, as long as:
- we have inline comments that explain why we are doing things the way we are doing them
- we have a follow-up issue in place, to fix things properly

Combining the two points above and converting them to actionable tasks:
1. Create a follow-up issue
2. Add a `@todo` inline comment in the current PR

**Comment by indigoxela** [comment] 2021-09-15 11:07
Creating a follow-up makes sense to me. The bug is a nasty (and old!) one. Fixing the functionality shouldn't be blocked.

I'm not sure about the `@todo` comment. If we create a follow-up, we can easily refer to the line of code, for which we'd like to investigate better solutions.

**Comment by klonos** [comment] 2021-09-15 11:44
@indigoxela people looking in the issue queue for things to work on will be able to find the follow-up issue 👍🏼 ...when people look at the code though, it won't be immediately apparent to them why `taxonomy_index_tid` is being special-cased. Hence the need for an inline comment. If the inline comment also includes a link to the existing issue, people won't be creating duplicates.

**Comment by indigoxela** [comment] 2021-09-15 11:54
> ...when people look at the code though, it won't be immediately apparent to them ... If the inline comment also includes a link to the existing issue, people won't be creating duplicates.

Right, didn't think of that. :+1:

Should the link point to this issue here, where we add that part of code? Or should it point to the (newly created) follow-up issue?

@laryn are you able to add that comment today?

**Comment by klonos** [comment] 2021-09-15 12:05
> ... Or should it point to the (newly created) follow-up issue?

Yes, the new issue please.

**Comment by laryn** [comment] 2021-09-15 13:47
Thanks for setting that up @klonos -- I've committed your suggestions in the PR as well.

**Comment by jenlampton** [comment] 2021-09-17 21:56
This looks like it was closed, maybe accidentally? Looks like the commit was merged into @laryn's fork, but I don't see it in core (yet?). ReOpening for a second review, if nothing else :)

**Comment by laryn** [comment] 2021-09-17 22:14
Oops, definitely accidentally closed it. I was testing a separate fork in a separate org account and somehow merging this over there closed this here? I think we just need another person to code review this...

**Comment by jenlampton** [comment] 2021-09-17 22:32
> a separate fork in a separate org account and somehow merging this over there closed this here?

I also thought that was really weird.

**Comment by indigoxela** [comment] 2021-09-18 08:12
> This looks like it was closed, maybe accidentally?

Shoot...

> I think we just need another person to code review this...

There's no need for another review, I guess. The status "RTBC" is still valid.

**Closed** 2021-09-30 02:12 UTC
Labels: type - bug report, status - has pull request, pr - ready to be committed, pr - works for me

**Comment by quicksketch** [comment] 2021-09-30 02:15
Thanks @laryn, @indigoxela, @jenlampton and @klonos! I merged https://github.com/backdrop/backdrop/pull/3702 into 1.x and 1.20.x.
