### ISSUE TITLE
[UX] Display a reminder to uninstall modules after disabling them

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3911] opened 2019-07-01 23:20 UTC
After a module is disabled, we should redirect people to the uninstall page if that module ~~has an uninstall hook~~ needs to be uninstalled. If it does not need to be uninstalled, we can reload the modules list (as we do now).

In order to do this, we would need to test for the ability to uninstall specific modules, and set a `#redirect` on the form conditionally. 

I don't think this will be too hard, so adding the good first issue tag. If it turns out to be difficult we can remove it.

**Comment by klonos** [comment] 2019-07-02 04:18
I like this 👍 ...we could use a "Would you like to also uninstall" confirmation dialog, which presents any modules with uninstall hooks, along with checkboxes next to them. The submit buttons would be `Just disable` (default) and `Disable and uninstall`.

**Comment by jenlampton** [comment] 2019-07-02 19:08
Hm, that sounds like a lot more change than a simple form state redirect...  Can we do the baby steps first? :)

**Comment by docwilmot** [comment] 2019-07-03 17:21
Why modules with uninstall hooks? I dont get it.

**Comment by serundeputy** [comment] 2019-07-04 23:07
@docwilmot if they don't have an uninstall hook then `uninstalling` said module does not do anything.

**Comment by stpaultim** [comment] 2019-07-04 23:09
I think the idea is that once you have disabled a module, it is a good idea to also uninstall it, if there is an uninstall hook. This change would automatically redirect the user to the unistall page to encourage them to uninstall the module. 

But, it will only do this if an uninstall hooks is available. Otherwise, there is no point and it is not necessary.

**Comment by docwilmot** [comment] 2019-07-05 00:00
docwilmot @docwilmot 18:20
OK so just to clear this up in my mind we're saying ideally all modules that are disabled should ideally be uninstalled, but those with uninstall hooks should be prioritised, is that it?

Geoff St. Pierre @serundeputy 18:21
well should be is maybe strong; it could be that uninstalling will/would remove data; the user may or may not want that
we'd have to check some modules that make database tables and see what there uninstall hooks do ... to really know what we are talking about here

Tim Erickson @stpaultim 18:21
I think the point is that there is no need to redirect an module without an uninstall hook, because there is nothing to uninstall? Or?
For context (if helpful), it is my understanding that in Drupal 8 you can’t disable a module without uninstalling it.

docwilmot @docwilmot 18:23
@stpaultim true but the reason for that has nothing to do with uninstall hooks.

Tim Erickson @stpaultim 18:24
I understand that.

Geoff St. Pierre @serundeputy 18:24
that is true; but there may still be users who are temporarily disabling a module to stop code from firing, but do NOT want to delete the data from tables the module is in charge of

Tim Erickson @stpaultim 18:25
I think that the only reason that “uninstall hooks” are being discussed, because if you disable a module without an uninstall hook, there is no reason to redirect the user to the uninstall page.

docwilmot @docwilmot 18:25
@serundeputy exactly, so why are we redirecting people to uninstall? TBH I genuinely dont understand why we're doing this, and I am trying.

Geoff St. Pierre @serundeputy 18:26
yeah; i don't know either; we should tread carefully here and study what Jen is asking for and why; becuase we don't want to encourage users to destroy data that they are looking for later

Tim Erickson @stpaultim 18:28
I think that many users, like myself, diable a module permanently and never uninstall it. We don’t understand that if we don’t uninstall a module, we’re leaving unnecessary stuff in database.

I think the goal is to redirect to the uninstall page after disabling a module to ENCOURAGE (but not require) users to uninstall it. The user still has the option to ignore that step, but by redirecting the user there we are encouraging them to engage in this best practice.


Geoff St. Pierre @serundeputy 18:28
still need to make sure the consequences are clear to the user

Tim Erickson @stpaultim 18:28
I would agree.

Geoff St. Pierre @serundeputy 18:29
on drupal it says if a module does not provide an uninstall hook it will not show up on the uninstall page; in backdrop it does?
so that is a little confusing

docwilmot @docwilmot 18:29
D8?

Geoff St. Pierre @serundeputy 18:29
because presumably (although it allows you to uninstall it) it does not do anything
https://www.drupal.org/docs/7/modules/ubercart/howtos/how-do-i-uninstall-a-module

Tim Erickson @stpaultim 18:30
I have not checked. I’m assuming that a module without an uninstall hook is not displayed on the Backdrop uninstall page, which is why we dont’ want to redirect the user to that page, because it serves no purpose.

Geoff St. Pierre @serundeputy 18:31
it is; i tested with headless
so that may be a separate bug

Tim Erickson @stpaultim 18:31
Ahhh, then you have more info than me. I thought you were asking….
Yes, that sounds like it might be a bug.

docwilmot @docwilmot 18:37
I dont think its a bug, I think that page is wrong. Uninstall is about removing entry in the system table and cleanup, not just uninstall hooks.
Testing D7 now

Geoff St. Pierre @serundeputy 18:37
ahh;
that would make sense;

docwilmot @docwilmot 18:39
Dont even need to test. Toolbar module (which everyone disables) has an entry in Uninstall page; it doesnt even have an .install file

Geoff St. Pierre @serundeputy 18:39
sweet; thanks for digging on that!
@docwilmot ++
Dragon Bot @dragonbot 18:39
@docwilmot is on the rise! (Karma: 130)

Geoff St. Pierre @serundeputy 18:40
so if they are redirected to uninstall there is a confirmation about deleting data i think
we should check that too

docwilmot @docwilmot 18:42
All modules the confirmation page says the same: "The following modules will be completely uninstalled from your site, and all data from these modules will be lost!"

Geoff St. Pierre @serundeputy 18:43
cool;; so the question becomes is that a sufficient warning; seems fine to me
and also your point about if they have an install hook or not stands; even w/out the hook the best prac is disable and uninstall if they no longer need the module or its data

docwilmot @docwilmot 18:47
What may be cool is if we do the complete opposite: modules which don't have a database and dont have uninstall hooks, when you click disable, throw up a confirmation saying this module has no data storage, would you like to completely uninstall it.

Geoff St. Pierre @serundeputy 18:47
yes; agreed; that would be harder though

docwilmot @docwilmot 18:47
other modules it may be OK to just add a message saying you disabled but data is still there.

Geoff St. Pierre @serundeputy 18:47
but, i think you are right that it would be better

docwilmot @docwilmot 18:48
it may be annoying to D7 veterans testing stuff to be redirected when theyre just temporarily turning off a module.
but either case i think that issue needs more thinking

Geoff St. Pierre @serundeputy 18:49
maybe instead of redirect we could link to the uninstall page in the status message; with some language about uninstalling vs. disabling?

docwilmot @docwilmot 18:50
good thought

Geoff St. Pierre @serundeputy 18:50
copy and paste all this junk into the issue :)

**Comment by serundeputy** [comment] 2019-07-05 12:48
@arjunk2004 thanks for taking this issue on!  Looking good so far.

Seems there are a lot more choices/use cases here than originally anticipated; causing the scope of this to grow. I've left some feedback on the PR trying to delineate the use cases as I see them.  https://github.com/backdrop/backdrop/pull/2779#issuecomment-508747145

**Comment by jenlampton** [comment] 2019-07-05 18:14
> I think the point is that there is no need to redirect an module without an uninstall hook, because there is nothing to uninstall

Yes exactly this. 

> that is true; but there may still be users who are temporarily disabling a module to stop code from firing, but do NOT want to delete the data from tables the module is in charge of

Yes, this is why we will not force people to disable + uninstall like Drupal 8 does. 

But the use-case for not uninstalling is very low compared to the alternative. Most of the time people simply forget to uninstall (or don't even know that they need to uninstall) and adding this redirect will prevent both of those situations :) 

> I think that many users, like myself, disable a module permanently and never uninstall it. We don’t understand that if we don’t uninstall a module, we’re leaving unnecessary stuff in database.

yes, exactly :)

> on drupal it says if a module does not provide an uninstall hook it will not show up on the uninstall page; in backdrop it does?

No, it's exactly the same in Backdrop. This is why we need to do the detection before we do the redirect. No sense in redirecting people to a place where there's nothing to be done!

>  the best prac is disable and uninstall if they no longer need the module or its data

That's an interesting idea, we could train people to uninstall (even when that action does nothing) just to teach people. I'm not sure I love it, but it may be a good topic for another issue.

> throw up a confirmation saying this module has no data storage, would you like to completely uninstall it.

I don't like this idea, as there is nothing to do...  we'd need to make something up. But anyway, a discussion for another issue :)

> it may be annoying to D7 veterans testing stuff

This is a limited use-case, not our concern here. We could maybe add a setting in devel if necessary - but not a core concern.

> maybe instead of redirect we could link to the uninstall page in the status message; with some language about uninstalling vs. disabling?

This UX is not as good as a redirect, as it will still require an extra click for the majority of uses. The only improvement would be ton the training side of things, no UX improvement. 

> Seems there are a lot more choices/use cases here than originally anticipated; causing the scope of this to grow.

All we are talking about in **this issue** is adding a redirect. I saw a few ideas in here that could be good alternate or follow-up issues, but no changes in scope.

**Comment by serundeputy** [comment] 2019-07-06 01:02
>No, it's exactly the same in Backdrop as D7, you can use the syslog module as an example. When there are no uninstall hooks - there is no checkbox for that module on the uninstall page.

this is not true; if you enable syslog then disable it; then syslog shows up on the uninstall tab.  The reason is that when you uninstall a module Backdrop sets its `schema_version` to `-1` in the `system` table this is how Backdrop differentiates an uninstalled module from a disabled module.

>This is why we need to do the detection before we do the redirect. There's no sense in redirecting people to a place where there's nothing to be done :)

So, since all modules that were once enabled, then disabled, have actionable items and appear on the `/admin/modules/uninstall` page we'd want to redirect all users to the uninstall page if something was disabled.

**Comment by jenlampton** [comment] 2019-07-06 01:05
> this is not true; if you enable syslog then disable it; then syslog shows up on the uninstall tab.

Have you tested it?

**Comment by serundeputy** [comment] 2019-07-06 01:06
yes.

**Comment by serundeputy** [comment] 2019-07-06 01:07
>Syslog did not show up on the uninstall tab.

you have to enable syslog
then disable syslog
then it will show up in the uninstall tab

**Comment by jenlampton** [comment] 2019-07-06 01:08
...  testing again

**Comment by jenlampton** [comment] 2019-07-06 01:28
@serundeputy I tested again and this time syslog **did** show up on the uninstall page. I think this is definitely a bug. 

Here's a diff of the Drupal uninstall code vs the Backdrop uninstall code... The only significant change is the addition of `config_uninstall_config($module);`.  Digging into that now. 

I know we have (had?) a core bug where if your contirb module does not provide a hook_uninstall() the config it provides does not get deleted...  I wonder if this bug was introduced as part of a fix for that issue?

```
--- a/docroot/includes/install.inc
+++ b/docroot/includes/install.inc
@@ -771,16 +771,16 @@ function drupal_install_system() {
  * @see module_disable()
  * @see module_enable()
  */
-function drupal_uninstall_modules($module_list = array(), $uninstall_dependents = TRUE) {
+function backdrop_uninstall_modules($module_list = array(), $uninstall_dependents = TRUE) {
   if ($uninstall_dependents) {
     // Get all module data so we can find dependents and sort.
     $module_data = system_rebuild_module_data();
     // Create an associative array with weights as values.
     $module_list = array_flip(array_values($module_list));
 
-    $profile = drupal_get_profile();
+    $profile = backdrop_get_profile();
     foreach (array_keys($module_list) as $module) {
-      if (!isset($module_data[$module]) || drupal_get_installed_schema_version($module) == SCHEMA_UNINSTALLED) {
+      if (!isset($module_data[$module]) || backdrop_get_installed_schema_version($module) == SCHEMA_UNINSTALLED) {
         // This module doesn't exist or is already uninstalled. Skip it.
         unset($module_list[$module]);
         continue;
@@ -792,7 +792,7 @@ function drupal_uninstall_modules($module_list = array(), $uninstall_dependents
       // them automatically because uninstalling a module is a destructive
       // operation.
       foreach (array_keys($module_data[$module]->required_by) as $dependent) {
-        if (!isset($module_list[$dependent]) && drupal_get_installed_schema_version($dependent) != SCHEMA_UNINSTALLED && $dependent != $profile) {
+        if (!isset($module_list[$dependent]) && backdrop_get_installed_schema_version($dependent) != SCHEMA_UNINSTALLED && $dependent != $profile) {
           return FALSE;
         }
       }
@@ -807,10 +807,11 @@ function drupal_uninstall_modules($module_list = array(), $uninstall_dependents
     // Uninstall the module.
     module_load_install($module);
     module_invoke($module, 'uninstall');
-    drupal_uninstall_schema($module);
+    backdrop_uninstall_schema($module);
+    config_uninstall_config($module);
 
     watchdog('system', '%module module uninstalled.', array('%module' => $module), WATCHDOG_INFO);
-    drupal_set_installed_schema_version($module, SCHEMA_UNINSTALLED);
+    backdrop_set_installed_schema_version($module, SCHEMA_UNINSTALLED);
   }
 
   if (!empty($module_list)) {

```

**Comment by docwilmot** [comment] 2019-07-06 01:36
> I think this is definitely a bug.

This is not a bug, as we pasted from Gitter above. This is the same in D7. The point of uninstall is not just to run `hook_uninstall()` but to uninstall schemas, remove the entry from System, **and** run uninstall hooks

**Comment by jenlampton** [comment] 2019-07-06 01:53
I'm trying to find an example module that does not need to be uninstalled. Then we can see what the difference is between those that do and those that don't - but I'll post that info in the other issue.

**Comment by serundeputy** [comment] 2019-07-06 12:25
I agree with @docwilmot this is not a bug; uninstalling will always change the system table regardless of presence of uninstall hooks.

**Comment by BWPanda** [comment] 2020-08-16 01:37
*All* modules need to be uninstalled after disabling them (if they're no longer required); so we either leave things as they are, or redirect everyone, all the time, to the uninstall page after disabling a module.

However, sometimes you want to disable a module that has various sub-modules that depend on each other. So you first have to disable the sub-modules, then disable the main module. It'd be annoying to be redirected to the uninstall page each time, when you're not done disabling everything yet.

For that reason (and for consistency with D7), I do *not* support the idea of redirecting users to the uninstall page automatically.

However, I do see the need to remind people about uninstalling in general and making that easier to do, so I *do* support @klonos' suggestion of a new 'Disable & uninstall' button.

**Comment by jenlampton** [comment] 2022-07-26 19:18
I agree that getting redirected before you are done uninstalling would be a nuisance, I hadn't thought of that.

> However, I do see the need to remind people about uninstalling in general and making that easier to do, so I do support @klonos' suggestion of a new "Disable & uninstall' button.

Adding a "disable and uninstall" button might not make sense on the modules page. The only button we currently have is "Save configuration", and it works for both enabling and disabling modules, as well as doing both at the same time.

A "Disable & uninstall' button wont make any sense when people are only enabling modules, so we would need to add some JS to determine when an enabled module is marked as disabled, so that we can only reveal the button at that point. 

And, what would happen if you were both enabling and disabling modules at the same time? Would the "Disable and uninstall" button also enable the modules you wanted enabled? 

Instead of adding a redirect, what if we set a warning message on the modules page any time there are disabled modules that have not been uninstalled?

We could list all the disabled modules in the message, something like...  `Warning: The following modules have been disabled: Vaiable, Vaiable example. To safely remove these modules from your site, please uninstall them (linked).`

**Comment by kiamlaluno** [comment] 2022-08-10 09:56
A module could not implement `hook_uninstall()`, but implement `hook_schema()` or `hook_schema_0()`. The fact the first hook isn't implemented doesn't mean there isn't anything to be uninstalled; there could be database tables to be removed.
Even in the case a module doesn't implement those hooks too, there is still a difference between a disabled module and an uninstalled module: When a module is disabled, Backdrop still remembers the last update executed for that module; when a module is uninstalled, Backdrop doesn't remember the last update ran for that module. That's why the users should abe asked if they want to also uninstall the module, once they disable it.

**Comment by kiamlaluno** [comment] 2022-08-10 10:37
I didn't mention the case of a module that implements an entity, for which Backdrop creates the related database tables, or (in general) a module that implements `hook_modules_installed()` to create data in the database when a module is installed, which is then removed in `hook_modules_uninstalled()`.

**Comment by BWPanda** [comment] 2023-02-22 02:18
I agree with @jenlampton's comments re. a 'Disable & uninstall' button. So that only leaves the option to display a message then. Here's a PR that does that: https://github.com/backdrop/backdrop/pull/4351

![image](https://user-images.githubusercontent.com/2385329/220503743-c28cc9ba-88a9-4d9f-9af8-8de75f8100cf.png)

**Comment by olafgrabienski** [comment] 2023-02-22 07:49
I like the message approach. Also quickly tested in the PR sandbox with a contributed module, works for me!

**Comment by kiamlaluno** [comment] 2023-02-22 08:51
Rather than *If they are no longer required*, I would use *If you do not plan to re-enable them*.

**Comment by klonos** [comment] 2023-02-22 15:36
Thanks for picking this up again @BWPanda 🙏🏼 ...I think that we should take baby steps, and the PR you provided improves things, so let's get that in.

> ...sometimes you want to disable a module that has various sub-modules that depend on each other. So you first have to disable the sub-modules, then disable the main module. It'd be annoying to be redirected to the uninstall page each time, when you're not done disabling everything yet.

Perhaps things will improve further once we can disable/uninstall modules and their dependencies in a single go (#2532 / #541 etc.).

**Comment by klonos** [comment] 2023-02-22 15:43
...there are some nits to pick, such as:
- using `:` instead of a period before listing modules
- using `format_plural()` and only showing a list of modules if there are more than 1.
- whether to use a warning or a success message (or info?), since there was no problem with the disabling of the modules - just the "please uninstall them" bit may warrant a warning

But I won't block getting this in unless others also think that these trivial things need to be fixed.

**Comment by jenlampton** [comment] 2023-04-06 21:57
I did a quick code review and I think the PR looks great. I also agree there is room for improvement as per @klonos 's comment above, but I think getting this in as is will be a huge improvement over what we have now so I'm setting the RTBC label.

**Comment by klonos** [comment] 2023-04-07 01:19
Sorry, I don't think this is RTBC. For instance, here's what people will see when disabling a module:
![image](https://user-images.githubusercontent.com/2423362/230518265-a65fc8ab-4a66-477a-bba9-fdc948369783.png)

So OK, there's a success message, which means success 👍🏼  ...but there's also a warning, which means that something is wrong or needs my attention. The warning starts with information ("The following modules have been disabled."), but also suggests that I should uninstall the disabled modules. Having that second bit as a warning "compels" me to do it, but I need to be a seasoned Drupal/Backdrop user to know that that will also irreversibly remove any settings/configuration. So it just doesn't feel right to have that message as a warning.

I started playing with the PR on my local, and here's what I currently have (one or several modules disabled):
![image](https://user-images.githubusercontent.com/2423362/230520679-ca860115-209a-4eb8-a0d7-ddead361a15f.png)

![image](https://user-images.githubusercontent.com/2423362/230520543-49960087-b5a9-4e8d-b149-ec76ac07467c.png)

In this case (only disabled modules - didn't enable any), the first "The configuration options have been saved." message seems superfluous to me. I'd rather we specifically listed the modules being enabled/disabled, which would make this a better set of messages.

I also don't agree with the use of the word "please" (adds even more to the "urgency" to uninstall, which is not correct) - this should be worded more like a suggestion, which is why I've used the word "consider" instead (without any "please").

https://ux.stackexchange.com/questions/10853/should-an-interface-ever-say-please
https://ux.stackexchange.com/questions/25500/why-avoid-the-word-please-in-error-messages

If listing all the modules that have been enabled/disabled is not acceptable (too "wordy" messages), then I would like us to consider a simplified implementation like this instead (the second info message is only shown if modules have been uninstalled):
![image](https://user-images.githubusercontent.com/2423362/230521106-bb4faed3-ef1b-4136-a2cf-aec62bbf31f6.png)

**Comment by stpaultim** [comment] 2023-12-09 05:07
I recreated the PR by @BWPanda (Thanks for all his hard work that is still available to us).

I simply changed the status of the message from "warning" to "info" to see what folks think about this. 

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/79b1d64a-85f7-40ea-94ba-1a003942dcda)

This might be a little less important since we added help text to "uninstall" page. However, I think that this might still be a useful addition. https://github.com/backdrop/backdrop-issues/issues/6309

@klonos, @olafgrabienski, @jenlampton, @kiamlaluno

**Comment by olafgrabienski** [comment] 2023-12-09 11:02
I like the info message a lot more than the warning. As @klonos [suggested](https://github.com/backdrop/backdrop-issues/issues/3911#issuecomment-1499817220), let's also change the wording, to make it less urgent:

Current PR:
> If they are no longer required, please uninstall them.

Suggestion:
> If they are no longer required, consider uninstalling them.

**Comment by olafgrabienski** [comment] 2023-12-09 11:10
I've just had a look at the sandbox site of the PR. In my opinion, the message works very well together with the new help text on the "Uninstall" page.

**Comment by kiamlaluno** [comment] 2023-12-09 20:13
I rather prefer *If they are no longer required, consider uninstalling them.* like @olafgrabienski.  
IMO, it is not necessary to say *completely uninstalling them* as either a module is uninstalled, or it is still installed. (There are not *partially uninstalled modules* and *completely uninstalled modules*.)

**Comment by stpaultim** [comment] 2023-12-09 21:31
Points taken, changes made. 

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/39fa911d-774e-4f6b-b75e-b573d3b0ce2b)

I removed the list of modules because I agree it's not necessary, but I did like having it there. I can go either way, what do others think?

I also added this line "Uninstalling a module will permanently remove its settings and/or associated data." I would have felt strongly about adding this line, if we hadn't just added this line to the unintall modules page. 

Do we need it in both places? Should we leave it here and remove it from the uninstall page to shorten the message there (it was only committed a couple days ago, so it's not too late to refine that message before release). Or should we leave it in both places. 

I think it's important information, because it really makes clear the distinction between disable and uninstall. 

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/4b00cfe5-3c32-40be-995c-ea9815bb1664)

**Comment by bugfolder** [comment] 2023-12-09 21:50
> I removed the list of modules because I agree it's not necessary, but I did like having it there. I can go either way, what do others think?

When we enable modules on that page, we don't list all the modules that were enabled. For parallelism, I'd suggest we can do without listing the ones that we disabled.

(Conversely, if we really want to list the ones that were disabled—which I wouldn't object to—then we should probably list the ones that were enabled, again, for parallelism of action. It is kind of nice to see exactly what happened in the confirmation message, versus the generic "The options have been saved.")

**Comment by irinaz** [comment] 2023-12-09 23:05
> Points taken, changes made. PR Updated.
> 
> ![image](https://private-user-images.githubusercontent.com/3144571/289313190-39fa911d-774e-4f6b-b75e-b573d3b0ce2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNjI5NTEsIm5iZiI6MTcwMjE2MjY1MSwicGF0aCI6Ii8zMTQ0NTcxLzI4OTMxMzE5MC0zOWZhOTExZC03NzRlLTRmNmItYjc1ZS1iNTczZDNiMGNlMmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDlUMjI1NzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGY1ZjE5OWFmZmY2ZTExNDU4MDBlMjQ2MDkzOWM2NDRiY2YwM2JiOTViZWQwOTExNTk2MmE0ZWE0Y2I5OTAzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RYPcMiTpjfV-e5A8fWRKdBAn5nvv3ESeLp9xXUoD3Fs)
> 
> I removed the list of modules because I agree it's not necessary, but I did like having it there. I can go either way, what do others think?
> 
> I also added this line "Uninstalling a module will permanently remove its settings and/or associated data." I would have felt strongly about adding this line, if we hadn't just added this line to the unintall modules page.
> 
> Do we need it in both places? Should we leave it here and remove it from the uninstall page to shorten the message there (it was only committed a couple days ago, so it's not too late to refine that message before release). Or should we leave it in both places.
> 
> I think it's important information, because it really makes clear the distinction between disable and uninstall.
> 
> ![image](https://private-user-images.githubusercontent.com/3144571/289313321-4b00cfe5-3c32-40be-995c-ea9815bb1664.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNjI5NTEsIm5iZiI6MTcwMjE2MjY1MSwicGF0aCI6Ii8zMTQ0NTcxLzI4OTMxMzMyMS00YjAwY2ZlNS0zYzMyLTQwYmUtOTk1Yy1lYTk4MTViYjE2NjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDlUMjI1NzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjAwYzYxMTViM2U4YjA5YmFmZDhkYjY3NzI2OTA2OTBkMmYzZWY1ZWJkYmY4ZWI2M2Y2Yzk4YzVjYjBhYjFmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IiR571-9YUYwUnT-cNlb2of-EaXX6E_WplVHwsmvoms)
> 
> Atten: @irinaz

@stpaultim , this additional message makes perfect sense to me, thanks!

**Comment by klonos** [comment] 2023-12-10 05:11
> (Conversely, if we really want to list the ones that were disabled—which I wouldn't object to—then we should probably list the ones that were enabled, again, for parallelism of action. It is kind of nice to see exactly what happened in the confirmation message, versus the generic "The options have been saved.")

If we find that information useful, then we can keep the "options have been saved" message for now, and then add a list of things that have been enabled/disabled in a more/less toggle (separate issue - not here please).

Anyway, I like where this is at now 👍🏼 ...for me, this is RTBC as is.

**Comment by olafgrabienski** [comment] 2023-12-10 11:50
> I removed the list of modules because I agree it's not necessary, but I did like having it there.

I like to have the list of modules as well. When I tested the PR, I found it really helpful because it doesn't leave open questions. I guess, seeing the message without the list sometimes people would ask themselves: "Did I just disable a module, or is this just a general hint?"

> Conversely, if we really want to list the ones that were disabled—which I wouldn't object to—then we should probably list the ones that were enabled, again, for parallelism of action.

In my opinion, we wouldn't need to list enabled modules for parallelism of action (even I wouldn't object to list them anyway). The situation with disabled modules is different, as the recommendation to consider uninstalling them doesn't have a counterpart when enabling modules.

**Comment by klonos** [comment] 2023-12-10 12:02
>In my opinion, we wouldn't need to list enabled modules for parallelism of action (even I wouldn't object to list them anyway). 

I'm with @bugfolder on this. If we are to add a list of modules that have been disabled, then I would like us to also add a list of modules that have been enabled. If we are to add such a list, it would need to go in the "options have been saved" message. Having the list hidden in a more/less toggle is a personal preference (so that the messages aren't too lengthy).

**Comment by bugfolder** [comment] 2023-12-10 14:41
> Having the list hidden in a more/less toggle is a personal preference (so that the messages aren't too lengthy).

I'm warming further to adding the additional information, and agree that it should be a separate issue, and appropriate for a more/less toggle (#5090 needs work, poke poke).

**Comment by olafgrabienski** [comment] 2023-12-11 10:51
If I get it right, we don't want to display a list of disabled modules for the time being - fair enough. Let's however improve the text to make clear what happened. Also, I'd like to remove the warning about uninstalling at this place. Better keep it (only) on the "Uninstall" page.

New suggestion:

> Some modules have been disabled. If they are no longer required, consider uninstalling them.

**Comment by stpaultim** [comment] 2023-12-11 22:35
@olafgrabienski 

> Let's however improve the text to make clear what happened. Also, I'd like to remove the warning about uninstalling at this place. Better keep it (only) on the "Uninstall" page.

It's not clear to me if you saw the most recent version and are suggestions changes to this OR if you are still looking at the previous version. Here is the most recent version (changed made 2 days ago). 

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/42f87a3a-43b2-4b88-983c-6c3c6b46095f)

Your suggested text is fine, but I'm not sure if it's necessary after the last round of changes. If you prefer your text, I'm ok with that as well. 

I'm fine with the follow-up issue for creating a list, given that will address something new (listing modules enabled).

**Comment by klonos** [comment] 2023-12-11 23:33
I see what @olafgrabienski is saying re the "Uninstalling a module will..." bit. I'm fine with the plain, single sentence suggested in Olaf's last comment (with the "uninstalling them" bit being the link).

**Comment by stpaultim** [comment] 2023-12-11 23:47
> Uninstalling a module will permanently remove its settings and/or associated data.

My justification for this is as follows. I'm on this page and I've just disabled some modules. There is some text suggesting I MIGHT consider "uninstalling" these modules, but I have no idea what this means or why I would do it. It's disabled, why bother uninstalling. 

I might never find out the reason, if I am required to go to the page before I understand the reason for it. 

NOTE: I do not feel strongly about this and I did ask for feedback. Personally, I think it MIGHT be more important on this page than on the uninstall page itself. But, if there is any consensus one way or the other, I'm fine with it.

**Comment by olafgrabienski** [comment] 2023-12-12 07:58
@stpaultim Yes, my suggestions refer to the recent version.

> Your suggested text is fine, but I'm not sure if it's necessary after the last round of changes

Mentioning that modules have been disabled, is still important, in my opinion, and the suggestion got some 'thumbs up' reactions. I'd be happy if you could change the PR accordingly.

> Uninstalling a module will permanently remove its settings and/or associated data.

Regarding the need of that sentence you wrote:

> There is some text suggesting I MIGHT consider "uninstalling" these modules, but I have no idea what this means or why I would do it.

Well, we just mentioned the "why": `If they are no longer required, ...`

So, I don't think we need the sentence here, but that may be a personal preference, and I don't have strong feelings about it.

**Comment by stpaultim** [comment] 2023-12-12 09:11
@olafgrabienski Thanks for feedback. Changes  made.

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/d4bc209a-dbcb-480d-ad42-1a425470da71)

This is clean and simple. Your specific suggestion didn't sound quite right to me, but I'm not sure if this is better.

**Comment by olafgrabienski** [comment] 2023-12-12 09:30
> You have disabled some modules, if they are no longer required you might want to uninstall them.

@stpaultim Thank you very much, the changes look good to me. Only thing I'm not sure about (not being a native English speaker): Shouldn't there be a full stop between the sentences?

> You have disabled some **modules. If** they are no longer required you might want to uninstall them.

**Comment by kiamlaluno** [comment] 2023-12-12 12:19
*You have disabled some modules, if they are no longer required you might want to uninstall them.* is a comma-split sentence, which is usually suggested to be changed to *You have disabled some modules. If they are no longer required you might want to uninstall them.* A semicolon instead of the period would be fine too, but I gather that American English tends to prefer a period.

**Comment by stpaultim** [comment] 2023-12-12 20:55
Sandbox isn't working at the moment, but here is the latest change.

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/78392ab7-f10a-4b34-a297-2fc94f37991a)

**Comment by olafgrabienski** [comment] 2023-12-13 08:42
Thanks for the update, looks good to me! (Sandbox is working again, btw.)

**Comment by irinaz** [comment] 2023-12-13 18:13
Do you know when this will be include in core - in the next release? thanks you so much for all the work on this!

**Comment by stpaultim** [comment] 2023-12-13 19:25
@irinaz - In theory, this could go into the next bugfix release if there is one before the next minor release. However, my best guess is that we will probably not have a bugfix release before 1.27 (that is my guess, I've not asked anyone else). 

I think it's highly likely that this will show up in 1.27. However, until it gets committed there is still a chance that someone raises an issue that will delay it. 

As you likely know, 1.27 will be released on Jan 15th.

**Closed** 2023-12-19 22:21 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2023-12-19 22:23
I think we're going to see a 1.26.3 release soon, and this will be in it. I've merged https://github.com/backdrop/backdrop/pull/4600 into 1.x and 1.26.x. This is a nice little improvement and I know I'll appreciate this reminder; I forget to uninstall modules all the time.

I merged https://github.com/backdrop/backdrop/pull/4600 into 1.x and 1.26.x. This issue has been open a while with a lot of input, so I hope I got everyone! Thank you @stpaultim, @BWPanda, @olafgrabienski, @kiamlaluno, @klonos, @bugfolder, @jenlampton, @serundeputy, @docwilmot, @yorkshire-pudding, and @irinaz!
