### ISSUE TITLE
Change the "Invalidate search index" process to a batched "Rebuild search index"

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4182] opened 2019-10-31 19:12 UTC
I like the neatness of the first screenshot that @jenlampton proposed on #1321 (comment). 

![screen shot 2015-11-05 at 3 08 11 pm](https://cloud.githubusercontent.com/assets/397895/10984559/0f14ccc6-83cf-11e5-9665-5840b07b046a.png)

Placing the same warning message twice on the search settings form:

<img width="624" alt="Screen Shot 2019-10-31 at 10 13 54 PM" src="https://user-images.githubusercontent.com/56604405/67978698-bf9c5e00-fc2b-11e9-9d7a-d5caf73a68f1.png">

and then again on the confirm page:

 ![screen shot 2015-11-05 at 3 08 46 pm](https://cloud.githubusercontent.com/assets/397895/10984576/296cd168-83cf-11e5-80f6-29c13b1b7051.png)

looks really too excessive. 

I do understand the initial concern for some people who could press the button without realizing the consequences. However, in fact the consequences are not so scary, because (1) no data is lost anyway and then (2) those who pressed the button will see the warning on the confirm page anyway.

Making the button outstanding with the scary text in red color was sufficient enough, so if possible please remove the description text.

**Comment by quicksketch** [comment] 2020-04-27 02:48
I started taking a look at this and figured the best way to solve this problem is to _actually do what the user expects_, rather than explain why it doesn't work the way they want.

That is, it would be best if instead of invalidating the index and then making the user wait, we could just build it immediately with a batch job. So I propose something like this:

Get rid of the explanation message and downgrade the button to a normal secondary button:

![image](https://user-images.githubusercontent.com/100206/80329132-32ab1980-87f6-11ea-8875-527bcb511ba1.png)

Provide a form that allows users to rebuild the index in the way of their choosing:
![image](https://user-images.githubusercontent.com/100206/80329176-4f475180-87f6-11ea-8788-9aa19270e17b.png)

We don't currently provide users a way to delete the entire index, which may be desired after disabling certain search modules or changing which content types are enabled to reduce the search index size (but otherwise is not necessary).

We also don't provide any way to index missing items, other than uninventively telling the user to run cron repeatedly. We might provide a 3rd option, or maybe make an entirely separate form. I'm not sure which would be better.
![image](https://user-images.githubusercontent.com/100206/80329366-f1673980-87f6-11ea-9f52-8c75bbcc2f03.png)

**Comment by jenlampton** [comment] 2020-04-27 02:57
This is a huge improvement over what we have now!
 
I'm not sure about the label `Rebuild type`, especially after we add options in there that are normal indexing options an not rebuild options, but I love where this is headed :)

**Comment by klonos** [comment] 2020-04-27 08:28
I also like this better than what we currently have.

> I'm not sure about the label `Rebuild type`,

How about "Rebuild method" instead?

**Comment by klonos** [comment] 2020-04-27 08:28
...also, should we make batched re-indexing the default?

**Comment by quicksketch** [comment] 2022-09-25 04:44
Coming back to this after @argiepiano's great work on https://github.com/backdrop/backdrop-issues/issues/5777.

Reading my previous suggestions, I think they're too complicated and probably unnecessary. The question of "invalidate" vs. "wipe" (or flush) is very confusing, and if you're rebuilding the entire index immediately, it's basically irrelevant.

The rebuild in the background option is also rather esoteric. I think if the search index is empty, it's fine that cron try to finish building the index, or index new items as they are created. But if the user has found this page, they want the index to be built _now_.

I think the _only_ question we should ask is number of items per batch, which should save its value when submitting the form so that it is "remembered" on future search rebuilds. Maybe start with that and we can expand/add options later.

**Comment by argiepiano** [comment] 2022-09-26 00:33
@quicksketch I've given this a try.  PR https://github.com/backdrop/backdrop/pull/4213

The task is not trivial. The issue is that all indexing is handled by modules implementing `hook_update_index` (e.g. `node_update_index()`). Therefore there is no central way to reindex. The batch has to necessarily invoke the hooks, AND it has to calculate how many passes it will need to reindex the whole site.

This is what this PR does:
- Changes the button to "Rebuild search index"
- Wipes out the indexes if confirmed
- Calculates how many passes it will need to index the whole site. Important: you suggested using a "Number of items to index in each pass" element in the confirmation form. INSTEAD I decided to use the "Number of items to index during cron runs" defined  in `admin/config/search/settings`.  The reason for this is that `node_update_index()` hard-codes the use of that setting. So, adding a different setting for the batch would imply rewriting the hook implementation... not worth it
- Runs the process X number of times as calculated above to reindex the site
- After finished, reports the percentage of the site that has been indexed, just to assure that 100% is done

What it does not do:
- Cron tasks are not modified at all. So, cron runs will STILL reindex the site if needed. What this new option does is FORCING a manual reindex of the whole site in batches.

**Comment by argiepiano** [comment] 2022-09-26 00:36
To test:
- Create an empty vanilla Backdrop site
- Install Devel and Devel generate (which has some bugs, but it works OK for this purpose)
- Generate a gazillion nodes (150?  1500? Go for it!)
- Visit admin/config/search/settings
- Click "Rebuild search index" and confirm in the next screen
- Watch the batch process go through all the reindexing

Please test and review.

**Comment by argiepiano** [comment] 2022-09-26 00:42
The PR has affected some tests. No time tonight to check. Hopefully I'll get to this soon.

**Comment by argiepiano** [comment] 2022-09-26 02:19
I fixed the tests and adapted them to the new functionality,. They are now passing (except the ones for PHP 5.6, which fail for a different reason). 

Ready for testing and review.

**Comment by quicksketch** [comment] 2022-09-26 02:39
@argiepiano PHP 5.6 is failing but should work if you rebase against `1.x`. This was merged earlier today in https://github.com/backdrop/backdrop-issues/issues/5790.

I tested out this PR and it works great!

![Screenshot from 2022-09-25 19-00-32](https://user-images.githubusercontent.com/100206/192182169-5d0b7bd7-50fd-40b6-ba6c-7b75c18799d8.png)

![Screenshot from 2022-09-25 19-03-11](https://user-images.githubusercontent.com/100206/192182230-b5364f57-c278-4f66-991e-432f9009e668.png)

I agree that leaving the cron implementation in place is a good idea. It should continue to work as it does now, and it's needed to handle new content as it is created on the site.

In testing this, my site was already about 25% indexed when I started. I tried re-indexing the site and then intentionally crashed it by hitting the Back button on my browser. When I re-indexed the site again, it started from 0 and took the same amount of time, even though the site was now 60% indexed when I crashed it. On my site with about 3000 nodes, indexing the entire site took 10 minutes.

I know I suggested removing all the options above. But now I think I have yet another option that _would_ actually be valuable, which is something like:

```
Items to Index:
( ) Re-index entire site (3000 items)
( ) Index only remaining items (500 items)
```

This would be helpful for users who have their batch operation fail, whether due to hitting the back button, running out of memory, their computer falling asleep, etc. That way they could pick back up after they left off.

**Comment by argiepiano** [comment] 2022-09-26 02:45
Thanks @quicksketch 

I'm experiencing a problem that needs to be solved. When I create nodes with Devel generate, and then run the reindexing, the page at `admin/config/search/settings` says that 100% has been reindexed. HOWEVER, if I do any search for any of the Lorem Ipsum text, nothing is found.

The only way I've been able to find something is if:
1. I edit any node and save it
2. I run Cron right after (not reindexing)

So, there is something wrong with the batch process. Something is missing. I can't look at this tonight, but if you have any ideas, let me know.

**Comment by argiepiano** [comment] 2022-09-26 03:08
> When I create nodes with Devel generate, and then run the reindexing, the page at admin/config/search/settings says that 100% has been reindexed. HOWEVER, if I do any search for any of the Lorem Ipsum text, nothing is found.

OK, I discovered where the problem was. I need to be sure to set `backdrop_register_shutdown_function('search_update_totals');`  on EACH iteration of the batch. Otherwise the indexed items don't make it into the `search_total` table, and are not found.

I'll push that commit later, and will implement your other suggestion too.

**Comment by argiepiano** [comment] 2022-09-26 04:00
> But now I think I have yet another option that would actually be valuable, which is something like:

I added that to the latest commit. Also fixed the problem I mentioned above. Ready for more testing and review.

**Comment by argiepiano** [comment] 2022-09-26 04:01
By the way, even though I rebased the PR, PHP 5.6 is STILL failing. Not sure why.

**Comment by docwilmot** [comment] 2022-09-26 04:13
"ERROR: Module php5.6 does not exist!" in the test report.

**Comment by argiepiano** [comment] 2022-09-26 13:48
A couple more tweaks and all tests are passing (except 5.4)

**Comment by indigoxela** [comment] 2022-09-27 06:29
> ERROR: Module php5.6 does not exist!

Oh, garbage, now *they* fixed it, and our fix breaks things... :roll_eyes:

**Comment by quicksketch** [comment] 2022-10-14 01:18
We talked about this during today's dev meeting. @klonos indicated he had further suggestions, like moving this regeneration option out of the settings form and possibly making a status report item, but I think we might want to accept this as-is and iterate. This is a huge improvement and I'd hate to delay it when it's at a nice stopping point.

**Comment by argiepiano** [comment] 2022-10-14 02:50
> I think we might want to accept this as-is and iterate.

Agreed!

**Closed** 2022-10-21 23:35 UTC
Labels: type - feature request, status - has pull request, pr - ready to be committed, pr - works for me, milestone candidate - minor

**Comment by quicksketch** [comment] 2022-10-21 23:37
Merged https://github.com/backdrop/backdrop/pull/4213 into 1.x for 1.24.0!

Wow, thank you @argiepiano for this amazing contribution!

https://github.com/backdrop/backdrop/commit/3ba74da19c98449247457552c691de0dec2453ab by @argiepiano, @quicksketch, @indigoxela, @alanmels, @jenlampton, @klonos, and @docwilmot.
