### ISSUE TITLE
Node previews: wrong layout

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5018] opened 2021-03-22 20:38 UTC
**Description of the bug**

When previewing a new or edited node, the system is supposed to use the layout that will apply when the node is normally rendered. It's not currently doing that, typically using the default layout.

**Steps To Reproduce**

1. Create a new layout with path `node/%`.
2. Add a custom block to it with some distinctive content so you can tell when it's being applied.
3. Create a new node and select 'Preview'.

The previewed node will be displayed with the default layout, not the custom layout that you just set up.

**What's going on**

The code introduced in [PR 2290](https://github.com/backdrop/backdrop/pull/2290) (in response to [Issue 3062](https://github.com/backdrop/backdrop-issues/issues/3062)) in function `layout_get_layout_by_path()` no longer does what it's supposed to, because:

* The path for preview nodes is different from what is in the code
* the `$tempstore_id` that was being requested was not returning the proper value.

There's also a problem a bit further down in that function in the setting of context data. The path for a node preview (e.g., `node/page/preview/%`) has its context in a different position from the position of the placeholder in the relevant layout path (e.g., `node/%`), which needs to be accounted for when setting context based on information in the router item.

A PR that fixes this will be forthcoming shortly.

This seems like a situation that should have a test as part of the test suite, and I'm willing to take on adding that, too. A question on logistics though: should the test be added in the same PR as the fix, or should the test be in a separate PR? (Of course the test would fail without the fix.)

**Additional information**

- Backdrop CMS version 1.18

**Comment by indigoxela** [comment] 2021-03-23 06:46
Interesting finding... I never realized before, but can confirm that the preview does not use the same layout as the node when viewed.
The node form (node/X/edit) doesn't either, BTW.

Regarding functional tests: they should be combined in the same PR.

**Comment by klonos** [comment] 2021-03-23 08:13
> This seems like a situation that should have a test as part of the test suite, and I'm willing to take on adding that, too. A question on logistics though: should the test be added in the same PR as the fix, or should the test be in a separate PR? (Of course the test would fail without the fix.)

How our Drupal brethren are doing things (and I really like it), is that they first write the test that fails, then they add the commits that fix the problem (and confirm that the test now passes).

> The node form (node/X/edit) doesn't either, BTW.

That should be the default admin layout though. Right? ...which is affected by the "Use the administration theme when editing or creating content" under `admin/appearance`. If you disable this option, then the layout being used is the default layout. If you have configured a layout with `node/%` as context, then that won't be used - unless the context is changed to `node/%/edit`. This may be handled better in the future, once we have #1528 in place. See @quicksketch's comment in https://github.com/backdrop/backdrop-issues/issues/1528#issuecomment-417885171

> In https://github.com/backdrop/backdrop-issues/issues/3062, we've run into an issue that requires layouts have multiple paths. In this case, we want `node/%` and `node/%/preview` to always use the same layout. It's related to this request for sure, but perhaps slightly different in that this combination of paths would probably not be optional or user-specified. Simply if `node/%` were the path, `node/%/preview` would automatically be included in the path matching as well.

**Comment by indigoxela** [comment] 2021-03-23 08:40
@klonos many thanks for finding and linking the related issue(s). :bowing_woman: 

So... what is the correct label for this issue here? Is it really a bug, or is it "works as (adversely) designed", "feature request", "duplicate"?

@bugfolder what would be your approach to solve the problem with the node preview?

Regarding test driven development (sort of) by first adding the test, then adding the fix. In an ideal world we would do that, too. But in an ideal world, writing tests would be easier. :smile: I guess we're also happy, if a test gets added later on - even if that means that we have to check locally, if it does fail without the fix.

**Comment by klonos** [comment] 2021-03-23 08:54
Well, I think that the current situation is "works as designed", since layouts unfortunately only support a single path. That does not make the existing WTF go away though (that would be us saying "it's not a bug, it's a feature" 😅 ).

IMO, the "proper" way to fix this would be to get #1528 fixed, so that site builders can specify multiple paths for layouts, to account for situations such as these. In the meantime, there is an existing solution in contrib.

The only way I see this being fixed in a "quick and dirty" way would be to hard-code things, so that any layout with `node/%` should "automagically" also handle `node/%/preview` and `node/%/edit` (conditionally, if "Use the administration theme when editing or creating content" is disabled). But we'd be making many assumptions in that case (although admittedly they may be 80% use cases ...or more).

@bugfolder was that your plan more or less?

**Comment by bugfolder** [comment] 2021-03-23 16:43
@klonos, I don't think the current situation "works as designed" because the code that was introduced in [PR 2290](https://github.com/backdrop/backdrop/pull/2290) (and is present now) is designed to use the proper layout for preview pages. The comments in the code say it explicitly:

>  If the path is a node preview path, check if a custom layout exists for
>  nodes and use that instead.

The problem is that the current code doesn't accomplish that, in part because the path assumed in the current code isn't in the form that preview paths currently take. (Maybe they were different in the past?) The current code assumes

```
$preview_path = 'node/' . $type->type . '/preview'
```

The correct value should be

```
$preview_path = "node/preview/{$type->type}/%";
```

That's not the only thing needed; there's some additional changes needed to handle the context and where the context placeholder and variable lies in the path.

I have a branch that works properly (at least on my local development machine), and was ready to commit and PR, but wanted to get the feedback on whether I should include the test first. From @indigoxela's comment, I gather it would be OK to file the PR with the fix, then add the test as a follow-up PR. (I've only written one Backdrop test before, so I'll probably have a bit of a learning curve on that; it might take longer.)

The fix isn't any "quick-and-dirty"er than the original code that's there now (although judging from the comments in the code, apparently the author considered it all a bit Q&D).

Since @docwilmot was the original author, perhaps he could chime in (now or after the PR).

Last, getting back to the feature request of [#1528](https://github.com/backdrop/backdrop-issues/issues/1528), I recently took over as maintainer of [Layout Wildcard](https://github.com/backdrop-contrib/layout_wildcard) and brought it up to date with core 1.18 code. (It will need to be updated again after this fix.) That module currently allows alternative paths on a layout; I have some ideas for enhancements, which I'll lay out in an issue in that module's issue queue to get feedback before doing anything beyond bugfixes to the current state.

**Comment by indigoxela** [comment] 2021-03-23 16:53
@bugfolder I think it makes sense to provide your PR. Then it'll be much easier to figure out, whether the approach is the proper solution. Currently our discussion is way too theoretical. :smile:

If you need any help with writing tests (the first steps are the hardest), don't hesitate to ask in the chat.

**Comment by bugfolder** [comment] 2021-03-23 17:10
[PR 3574](https://github.com/backdrop/backdrop/pull/3574)

**Comment by klonos** [comment] 2021-03-23 18:11
> If the path is a node preview path, check if a custom layout exists for
> nodes and use that instead.

Fair enough @bugfolder, I hadn't noticed that bit.

I've tested the PR sandbox by creating a layout for the `node/%` path, and then confirmed that it is applied both when viewing nodes, as well as when previewing them 👍🏼

**Comment by klonos** [comment] 2021-03-23 18:21
...the code also looks good to me, but I'll leave it to someone else to mark RTBC, as I think we should get more 👀 on this change.

**Comment by klonos** [comment] 2021-03-23 18:23
> If you need any help with writing tests (the first steps are the hardest), don't hesitate to ask in the chat.

@indigoxela if you feel like it, perhaps file a PR against @bugfolder's PR, to add a test.

**Comment by bugfolder** [comment] 2021-03-23 23:36
[PR 3575](https://github.com/backdrop/backdrop/pull/3574) added, which contains just the tests.

**Comment by quicksketch** [comment] 2021-03-24 00:30
@bugfolder Thanks this looks great. Would it be possible for you to write an automated test for this situation? The code seems fine to me, as you say it was considered a bit quick and dirty at the time (still is).

**Comment by klonos** [comment] 2021-03-24 00:50
@quicksketch you must have missed the last comment by @bugfolder ...tests have been added in a separate PR here: https://github.com/backdrop/backdrop/pull/3574

**Comment by bugfolder** [comment] 2021-03-24 01:23
Sorry for the ambiguity. There's two separate PRs:
[PR 3574](https://github.com/backdrop/backdrop/pull/3574) contains the fix for the issue.
[PR 3575](https://github.com/backdrop/backdrop/pull/3575) contains the automated tests. The sandbox for this PR should show the tests failing (and it does), but after applying 3574, they should pass.

**Comment by indigoxela** [comment] 2021-03-24 06:39
@bugfolder thank you so much for providing these PRs. I do have one concern though, based on the existing comments in function layout_get_layout_by_path:

> This adds very specific code for node previews which too closely
> couples Node and Layout modules. This needs to be reverted in a future
> commit.

I think this is still the case. The Layout module provides logic, that should actually be done by the Node module. OK, both ship with core, both are required, so nothing breaks. But a new hook in layout_get_layout_by_path, that the Node module could implement might be a cleaner solution. I have to admit, I didn't look deeper into this yet, so I don't know how hard this would be. And the hook could be a follow-up issue, anyway.

I didn't look at the contrib module Layout Wildcards either, but if a hook existed in the Layout module, things *might* get easier for that one, too.

Note, I'm only brainstorming here, not opposing in any way to the current solution. :wink:

**Comment by klonos** [comment] 2021-03-24 11:23
> I didn't look at the contrib module Layout Wildcards either...

I had a look the other day. In the `layout_wildcard.module` file, it seems to be duplicating https://docs.backdropcms.org/api/backdrop/1/search/layout_route_handler, and then all the "magic" happens via a `'menu_route_handler'` property added to `system.core.json`, which decides if core `layout_route_handler()` will be used (if the module is disabled), or `layout_wildcard_route_handler()` instead.

**Comment by bugfolder** [comment] 2021-03-24 17:40
Layout Wildcard wants to override the output of `layout_get_path_layout_names()`, but since there's no hook in that function, Layout Wildcard needs to essentially duplicate each function in the call chain as follows:

`layout_wildcard_get_path_layout_names()` <— contains the actual changes
`layout_wildcard_load_multiple_by_path()` <— duplicate of `layout_load_multiple_by_path()`but calls LW function
`layout_wildcard_get_layout_by_path()` <— duplicate of `layout_get_layout_by_path()` but calls LW function
`layout_wildcard_route_handler()` <— duplicate of `layout_route_handler()` but calls LW function

The only one that _really_ needs alteration is `layout_wildcard_get_path_layout_names()`, but the only way to get access to it is to replace `layout_route_handler()` in the system core config with `layout_wildcard_route_handler()`.

So `layout_wildcard_load_multiple_by_path()` and `layout_wildcard_get_layout_by_path()` are essentially the same thing as the core routines `layout_load_multiple_by_path()` and `layout_get_layout_by_path()`, except for who they call and who they are called from.

We could eliminate some of that duplication by adding a hook at one of the intermediate levels.

And now getting back to core: that dovetails nicely with the goal of getting the node-specific code out of layout module. Since the node-specific stuff needs to happen in `layout_get_layout_by_path()` (both picking the right layout and setting the contexts), that would seem to be the best place to put the hook. For example:

`function hook_layout_by_path_alter(&$selected_layout, $path, $router_item)`

called at the end of `layout_get_layout_by_path()`, just before the return.

And then node module could use this hook to do the prevew-specific tinkering. And other client modules like Layout Wildcard could also use this hook to do their thang.

But we'd need to be careful about the caching. Currently in `layout_get_layout_by_path ()`, the cache key is `$router_item['path']`, which contains placeholders. Clients implementing that hook might want to do different things based on the actual value of the placeholder in the normal path, which would require a different caching strategy (which the client would then have to be responsible for).

**Comment by indigoxela** [comment] 2021-03-25 08:26
Many thanks for that analysis!

> function hook_layout_by_path_alter(&$selected_layout, $path, $router_item)
> called at the end of layout_get_layout_by_path(), just before the return.

I'm not sure yet, because that would also mean, that modules bypass the access checks - which seems a bad idea. And the fallback to default layouts should be done last.

> Clients implementing that hook might want to do different things based on the actual value of the placeholder in the normal path, which would require a different caching strategy

I don't get that yet, mind to explain a bit more?

**Comment by bugfolder** [comment] 2021-03-25 13:49
>>Clients implementing that hook might want to do different things based on the actual value of the placeholder in the normal path, which would require a different caching strategy

>I don't get that yet, mind to explain a bit more?

Sure. Consider the situation where a client module would want to use layout A if the node is a Post (say, `node/1`) and layout B if the node is a Page (`node/2`). In both cases, the system path is `node/%` (i.e., `$router_item['path']` = `'node/%'` in both cases). So since `layout_get_layout_by_path()` returns `$cache[$router_item['path']]`, it would return the same layout for both `node/1` and `node/2`, because the key to the cache is `node/%` for both.

Now, admittedly, here `$cache` is only a static cache, so this would only matter if there's some reason to get layouts for the two paths within the same page load, and I can't think of a scenario where that would happen; so maybe that's a non-issue.

If we look at what the node module would have to accomplish to handle preview via layout hooks, it needs to do two things:

1. Load the layout for the path `node/%`, rather than the path `"node/preview/{$type->type}/%"`. Instead of overriding `layout_get_layout_by_path ()`, that could also be done by overriding either `layout_load_multiple_by_path()` or `layout_get_path_layout_names`, deeper in the call chain. (Layout Wildcard module would love to see `hook_layout_names_alter()` invoked from within `layout_get_path_layout_names()`, because that would eliminate all the duplicated code.)

2. If there's a node preview, then set the context for position 1 from the tempstore node specified by the tempstore ID in position 4. This context-setting pretty much has to be accomplished within `layout_get_layout_by_path()`, because it has to happen _before_ the access checks. So a second hook would be needed: perhaps `hook_layout_contexts_alter()`.

Deeper in the call chain, though, I see that `layout_load_multiple_by_path()` uses persistent cache based on the system path value. So that cache would defeat any attempts at handling content-type-dependent layout choices accomplished by overriding a deeper function.

So, maybe two hooks, both invoked from within 'layout_get_layout_by_path()`:

* `hook_layout_multiple_by_path_alter(&$layouts, $path, $router_item)`, to modify the output of `layout_load_multiple_by_path(&$layout, $path, $router_item)`
* `hook_layout_contexts_alter()`, to modify the contexts for a specific layout.

By the way, this content-type-dependent layout is a real scenario (and is the reason that dragged me into the whole layout and Layout Wildcard forest). On a site I'm working on, we have a few content types that users can create and edit, and we want them to see the default theme (and layout) for all of the CRUD pages for those content types; whereas for other content types that are only admin-editable, we want users to see the admin theme (and layout) for the create/edit pages. In D7, that was handled easily by implementing `hook_admin_theme()`. In Backdrop, though, there's no equivalent of `hook_admin_layout()` for layouts.

**Comment by indigoxela** [comment] 2021-03-25 16:33
Hm, the use-case you describe is a bit special. Using different layouts by node type is possible with visibility conditions - that shouldn't be the problem. But using the same layout on the edit and preview pages is the tricky part.

Regarding the persistent cache I can't suggest anything, I have to admit, I'm really no expert for the Layout system. :smile: 

What would a Layout expert recommend @docwilmot ?

**Comment by bugfolder** [comment] 2021-03-25 18:27
I see that `layout_load_multiple_by_path()` is also called from `layout_page_callback()`, which also sets contexts. (Also two places in dashboard module that don't set contexts.) So it looks like invoking the postulated `hook_layout_contexts_alter()` would also be needed in `layout_page_callback()`.

**Comment by docwilmot** [comment] 2021-03-25 21:01
We considered this when building node previews. See https://github.com/backdrop/backdrop-issues/issues/3062#issuecomment-417858973. @quicksketch had some reasonable concerns: see https://github.com/backdrop/backdrop-issues/issues/1528#issuecomment-417885171. Essentially a hook invoking in the function that builds *every page* is a recipe for disaster if it messes up or if it is inefficient.

**Comment by bugfolder** [comment] 2021-03-25 21:07
Is the process of calling hooks inherently inefficient, or is the worry that a client module might implement the hook in an inefficient way?

**Comment by docwilmot** [comment] 2021-03-25 22:44
This isnt funny, but i'm looking at this preview/layout code in core and this could never work as is. How on earth did we not see this?

**Comment by bugfolder** [comment] 2021-03-27 18:23
I've read both[ #3062 (comment)](https://github.com/backdrop/backdrop-issues/issues/3062#issuecomment-417858973) and [#1528 (comment)](https://github.com/backdrop/backdrop-issues/issues/1528#issuecomment-417885171). I think the situation is a bit more complicated than described there to handle node previews. Recall that the relevant paths are:

* `node/%` for the original node;
* `node/%/edit/preview` for the node preview for node edit pages
* `node/<type>/preview/%` for the node preview for node add pages

So, if we were going to store the preview path as `$layout->alternative_path` (suggested [here](https://github.com/backdrop/backdrop-issues/issues/1528#issuecomment-417885171)), we'd have to store a value for every node type; and the code that sets the context for the layout will have to handle the context variable being in a different position in this alternative path, and that the context variable is interpreted differently: it's a `nid` for node pages, but is a `tempstore_id` for previews.

@docwilmot suggested in [ #3062 (comment)](https://github.com/backdrop/backdrop-issues/issues/3062#issuecomment-417858973):

> a new hook_layout_get_layout_by_path_alter(&$layouts, $router_item, $object), invoked in layout module's layout_get_layout_by_path() function, that allows other modules to modify the layouts that are loaded for a given path before the chosen layout is resolved.

How that works depends on on where it comes in `layout_get_layout_by_path()`. Since it's acting on `$layouts`, it would have to come either before or after the `for` loop that both sets context and checks access. If before, then it wouldn't include the special context-setting needed for node previews; if after, it would bypass access checks and so that burden would be on implementers.

Using the two hooks I suggested [in my comment above](https://github.com/backdrop/backdrop-issues/issues/5018#issuecomment-806781876) would allow `layout_get_layout_by_path()` to still perform access checks and default fallback, but would put the burden on hook implementers to implement both hooks to handle the situations they're addressing. That would be easy to do for the node module to handle previews—basically, moving the two chunks of special code from its current location in layout module into the corresponding relevant hook implementations in node module.

That still leaves the issue @quicksketch raised:

> It's an opportunity to completely tank the site performance, because finding a matching layout at a given path is tricky to optimize

If we added the two hooks I suggest and then moved the code from layout module into the hook implementations in node module, I don't think site performance would be tanked; the code would be pretty much the same as now, plus two new calls to `backdrop_alter()` (which, I presume, would not be overly burdensome, performance-wise?).

Of course, by creating those hooks, then contrib modules could also implement them, and could do so inefficiently. Perhaps that's the "opportunity to completely tank the site performance" that @quicksketch alludes to? If so, I think that could be at least somewhat mitigated by putting a stern warning in the hook API: "if you do this inefficiently, you'll tank your site's performance," or something like that.

And I point out that the same performance-tanking opportunity exists already; anyone could implement the same hack that Layout Wildcard uses, by replacing the menu handler with a duplicate of the call chain and then putting their own stuff in that duplicate. So we're not really preventing someone from tanking site performance if they want to go tinker with what layouts are used. But if we give them a nice set of hooks to do said tinkering, we can retain more control (checking access, falling back to defaults), and they'll have to write less code.

And then node module can handle its own layout tinkering for node previews.

So I would ask that folks take another look at this issue, and consider again adding one or more hooks called from within `layout_get_layout_by_path()`. Maybe the two hooks I suggest aren't the best way to do it, but it seems like some set of hooks would be a clean and performant solution.

**Comment by bugfolder** [comment] 2021-04-20 21:17
In order to keep some movement going on this issue, could I suggest the following:

* Accept [PR 3574](https://github.com/backdrop/backdrop/pull/3574), which fixes the code in the way it was (apparently) originally intended;
* Accept [PR 3575](https://github.com/backdrop/backdrop/pull/3575), which adds an automated test for this situation.

That will get node preview pages working now with the correct layout, which they currently aren't.

And then we can continue the discussion about what the best longer-term solution is, whether it's the single hook proposed by @docwilmot in [3062 (comment)](https://github.com/backdrop/backdrop-issues/issues/3062#issuecomment-417858973), the two hooks I proposed above in [this comment](https://github.com/backdrop/backdrop-issues/issues/5018#issuecomment-806781876), or something else. (Maybe bring up the longer-term solution in the weekly dev meeting?)

**Comment by jenlampton** [comment] 2021-04-22 21:28
The Code looks great (RTBC from me!) but can we combine both PRs into one, so it will be easier to test and merge?

**Comment by bugfolder** [comment] 2021-04-22 21:57
Outcome of 4/22 development meeting:
—I will merge tests (PR 3575) into 3574 (and incorporate @jenlampton's edits)
—Separately, I will proceed with long-term solution of adding hooks to layout module and moving node-specific code into node module implementation of the hooks.

**Comment by bugfolder** [comment] 2021-04-22 22:27
Tests from 3575 are now merged into 3574.

**Comment by jenlampton** [comment] 2021-04-23 03:41
The updated PR looks great. Thanks for the cleanup @bugfolder!

**Closed** 2021-04-24 21:04 UTC
Labels: milestone candidate - bug, pr - ready to be committed, pr - works for me, status - has pull request, type - bug report

**Comment by quicksketch** [comment] 2021-04-24 21:10
Thanks @bugfolder for your work on this!! And I appreciate you taking the time to attend and bring this up during the weekly meeting this past week.

Big thanks to @indigoxela, @docwilmot, and @klonos for the repeated rounds of feedback and reviews. By the time I looked at this all problems have been fixed. I merged https://github.com/backdrop/backdrop/pull/3574 into 1.x and 1.18.x.

I'd love to see a follow-up as @bugfolder described to untangle node and layout modules when dealing with previews. We might also be able to incorporate some (or all) of Layout Wildcard contrib module into core, as that has been a long standing limitation that has been frustrating to Backdrop site builders.

**Comment by bugfolder** [comment] 2021-04-24 21:17
I created a [new issue](https://github.com/backdrop/backdrop-issues/issues/5067) to address the "untangling". I've been working on this and should have something to review/throw rocks at soon.

The untangling and new hooks will definitely simplify Layout Wildcard. There remain some near-term bugs to fix (I'm working on those, too), and I have some longer-term ideas that I will lay out in its issue queue for feedback/comment, but I still need to improve my understanding of the overall Layout structure and philosophy; I'm not up to "grok" yet.
