### ISSUE TITLE
[UX][DX] Color Module Support is not inherited by child theme

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#3348] opened 2018-10-27 23:07 UTC
Not sure if this should be a thing, but I found it surprising.

So in a session at BADCamp, @sethlbrown made a child theme from Basis, then went to see if color support worked, and it didn't. It gave a weird error (that I can't remember) about Color module not being enabled... or some error that shouldn't have fired because it was incorrect about what the problem was.

Related to: https://github.com/backdrop/backdrop-issues/issues/3341

- - - - - - 

PR by @hosef = https://github.com/backdrop/backdrop/pull/2917

**Comment by sethlbrown** [comment] 2018-11-02 02:39
In addition, additional changes to the subtheme styles didn't load.

**Comment by hosef** [comment] 2018-11-03 18:41
![image](https://user-images.githubusercontent.com/1253691/47955882-b2d32480-df5b-11e8-8908-6c9e1ef28f08.png)
Is this the error that you were seeing?

If so, then what was probably happening is that it was copying the theme-settings.php from the base theme, but not copying anything to do with the color module.
Currently, if you want to support the color module in a child theme, you must copy the color folder and all files that the color module modifies from the base theme to the child theme which sort of defeats the purpose of having a base theme in the first place.

**Comment by jenlampton** [comment] 2019-01-15 20:43
This issue still needs more feedback, removing milestone, but adding milestone candidate tag.

**Comment by hosef** [comment] 2019-10-05 02:47
I believe that I have a working implementation in backdrop/backdrop#2917 that fixes most if not all use cases of color module support in themes that are based off of another theme.

**Comment by stpaultim** [comment] 2019-11-10 21:56
From discussion of PR attached to this issue:

> Primary changes include:
> 
> - Importing settings from the base theme
> - Get the list of css files from the theme info if it is not defined in the color settings
> - Getting a list of files from the base theme if the base theme does not support the color module
> - Changed the code that swaps out files on page load so it works with all of the sub arrays of the stylesheets array from the theme instead of just stylesheets[screen]
> - Allowed themes to disable color shifting by omitting the 'blend_target' from the color settings

@hosef - I'm a little confused by the second item. How does it get the list of css files from the theme .info file. Does it assume that it should be modifying all the css files in the theme? I assumed that the reason there was a list of css files in the colors.inc file was so that the themer could control which css files are effected. 

I was envisioning a (one possible) scenario in which the themer is putting all the css rules that they want effected by the color module into a single colors.css file so that they don't have to worry about unexpected effects on the rest of the css. If the color module is automatically grabbing a list of all css file from the themes .info file, won't it be more difficult for a themer to control which rules are effected and which are not?

**Comment by stpaultim** [comment] 2019-11-10 21:58
ALSO:

@hosef - Could you help me better understand what is happening with the "blend_target" value. I don't understand what that is doing?

**Comment by hosef** [comment] 2019-11-11 16:52
> Why does it get the list of css files from the theme .info file.

This should only happen if you don't give it a list of files in color.inc. If there is a list of files in color.inc, then it will retain the old behavior. I did this for 2 reasons.The first is to make it easier to add color support if you just want it to modify everything. The second is to make it possible to add color support to a base theme by using a sub theme, where it will get the list of files from the base theme's info file even though there is no color.inc file in the base theme.

> Could you help me better understand what is happening with the "blend_target" value.

That has a very long explanation, but essentially it is part of the PHP implementation of the way the GD library modifies images. I could give a more detailed explanation, but it will take a while to write it up and get decent examples of how it works. It is a holdover from when it was necessary to modify bitmap images to do things because browsers didn't have support for rounded corners, SVG, advanced font controls, blend modes, and other things that make CSS so powerful these days.

**Comment by stpaultim** [comment] 2019-11-11 20:22
@hosef - Thanks for these answers. 

> This should only happen if you don't give it a list of files in color.inc. If there is a list of files in color.inc, then it will retain the old behavior.

Seems reasonable. Thanks. 

> That has a very long explanation, but essentially it is part of the PHP implementation of the way the GD library modifies images.

Thanks. Would it be sufficient to say that unless one understands the impact of changing the "blend_target" that they should probably just leave the default and they will be fine?

I think it's better to provide instructions that say "if you don't understand this, it's probably fine to leave it as it is" rather than leave no explanation and have users wondering if they need to try and figure it out.

**Comment by hosef** [comment] 2019-11-12 22:21
Once this gets added, I would honestly recommend removing the blend target from your theme unless you know what it does and really want it to do that.

**Comment by stpaultim** [comment] 2019-11-17 04:01
@hosef - your PR makes changes to basis/theme-settings.php 

Won't most sub-themes of Basis have copied this file into their sub-theme?
And if so, won't that possibly break things for sites with existing sub-themes?

In theory, I would expect that you shouldn't copy this file. I know that I did recently, but that might have been to try and fix the problem that this PR is trying to fix.

**Comment by stpaultim** [comment] 2019-11-17 07:09
I understand now, that the initial problem was if you created a sub-theme without copying the color module support to your sub-theme, then color modules support was broken. 

I tested this by:

1) Set up a site locally and created a sub-theme. I did not include any color module files in the new sub-theme. Color support worked for Basis, but when I enabled the sub-theme, color module support was broken. 

2) I then applied the changes in this PR to Backdrop CMS and tried the same thing. This time, I was able to leverage the color module fully with the sub-theme available. 

I will mark this, works for me.

**Comment by herbdool** [comment] 2019-11-17 19:40
Here's how I tested:

I created a sub-theme by adding only a barebones .info file in my sub-theme. It only contains name, ref to parent theme, etc. The PR works!

I can confirm @stpaultim issue with using Tatsu with this PR (though I haven't tested Tatsu without this PR). I can "fix" Tatsu by commenting out the parent theme (@stpaultim you seem to have all the parent theme files in the sub-theme so seems to work just as well without being connected to the parent).

**Comment by hosef** [comment] 2020-01-16 21:34
I took a look at how Tatsu was interacting with my color module changes, and it looks like the code that was merging the settings from the base theme with the sub theme's settings was not working the way I expected when there were duplicate settings.

I have added a new commit to the PR that should fix the issue.

**Comment by herbdool** [comment] 2020-01-20 14:49
@hosef Your changes worked for me. I tested before and after applying PR, on both a barebones child theme and also Tatsu. The color functionality works in both cases.

I left a comment in the PR. Other than one question the code looks good.

**Comment by stpaultim** [comment] 2020-01-22 06:50
@herbdool - Is this RTBC?

**Comment by herbdool** [comment] 2020-01-23 02:53
Now it is

**Comment by quicksketch** [comment] 2020-04-15 21:08
Thanks, finally merged https://github.com/backdrop/backdrop/pull/2917 into 1.x and 1.15.x.

**Closed by quicksketch** 2020-04-15 21:08 UTC
Labels: status - has pull request, status - fixed
