### ISSUE TITLE
Re#736 - Drop Buttons

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#785] opened 2015-02-26 22:42 UTC
See master issue for instructions/guidelines for implementation: 
https://github.com/backdrop/backdrop-issues/issues/736

![style guide backdrop](https://cloud.githubusercontent.com/assets/5607236/6403643/b1ff2074-bdde-11e4-88b2-1b52430c829a.png)

This one might be a bit of a dooooozy since the drop-button styles are split between system module and the seven theme.  I'm not sure the division that's in core is very good (as to what is "theme" and what isn't). I think that came from ctools originally.  it might be good to just throw out that concept and start over with nice clean CSS in a single place.

**Comment by jenlampton** [comment] 2015-03-03 21:18
Implementation detail comment from @BWPanda in https://github.com/backdrop-ops/styleguide/issues/11
> Dropbutton arrow changes color between open & closed and looks slightly pixelated

**Comment by BWPanda** [comment] 2015-03-03 21:56
Here a visual example of what I see (blown up slightly):
![drow-button-arrows](https://cloud.githubusercontent.com/assets/2385329/6473237/41d71276-c24c-11e4-950a-2ecc09095180.jpg)

**Comment by jenlampton** [comment] 2015-04-19 03:20
@wesruv if you are still working on this please feel free to re-assign to yourself, I just un-assigned since it's been a whole month :)

**Comment by wesruv** [comment] 2015-04-20 02:27
@jenlampton I'm not, thanks for catching that!

**Comment by Graham-72** [comment] 2015-04-20 04:40
In PR 819 backdrop/backdrop/pull/819 I seem to have added a commit that I was expecting to become a separate PR. I will get these PRs right one day :worried: And the commit has failed Travis CI :worried: 

I found that the arrow worked better in Chrome than in Firefox, but is much improved if enlarged slightly. Also I capitalised the text to match the styleguide.

**Comment by Graham-72** [comment] 2015-04-21 14:22
I have spotted two problems that don't seem to show up on the styleguide page. 

1. The width of the column is not sufficient for the text in some circumstance e.g. see the operations column in admin/modules/list so I suggest style #system-modules td.operations on line 90 of system.admin.css should be width 125px or perhaps greater.

2. The admin page for editing layouts [admin/structure/layouts/manage/default] would seem to use a different set of class names for many drop buttons. Presumably we want these to be adjusted to the style guide?

Perhaps there are other variants in the admin pages?

**Comment by Graham-72** [comment] 2015-04-21 15:11
And on that admin page for editing layouts, the font size seems very large. Is this really what is intended by the styleguide?

**Comment by wesruv** [comment] 2015-04-22 03:22
@Graham-72 good points! In the future screenshots would be helpful, I'm a big fan of "[Awesome Screenshot](http://awesomescreenshot.com/)", which I believe is available for every major browser.

In general I really like that we're increasing the font-size, but as you're pointing out it's bringing up some issues in how some pages are styled/marked up.

Per 1: That's not ideal, @dariusgarza and @quicksketch, do we want to fix the layout or change the button text?
![not-enough-space-for-button-text-1-5x-new-style](https://cloud.githubusercontent.com/assets/5607236/7266754/d8748ef6-e87c-11e4-8d54-a9dd4a27b1d3.png)

Per Item 2:
We have a guideline to not change any markup for this release, my guess would be style both classes for now and we should capture where we have dropdown buttons that deviate from regular classes so we can fix them all, unless @quicksketch you want to update markup in this case?

Per the last comment, I like that we're making the font size larger, but this page probably needs some design love as a result. I could take a stab at fixing up the styling a bit so the page hierarchy works a little better?
![layout-edit-page-1-5x-new-style](https://cloud.githubusercontent.com/assets/5607236/7266775/31562dfe-e87d-11e4-90dc-07665fb013f9.png)

**Comment by quicksketch** [comment] 2015-04-22 03:33
> Per 1: That's not ideal, @dariusgarza and @quicksketch, do we want to fix the layout or change the button text? (and this screenshot is on a wide viewport...)

On the modules page, I think we could simply specify a minimum width for the "Operations" column. Drop buttons in particular have been tricky to style in the past. There's already an open issue for this at #370, they just don't work well in inline-block situations right now.

 > The admin page for editing layouts [admin/structure/layouts/manage/default] would seem to use a different set of class names for many drop buttons. Presumably we want these to be adjusted to the style guide?

In a situation as specific as the Layout administration, markup changes should be fine if they are necessary, especially if it means just adding missing classes. I just want to avoid any generic markup changes (e.g. modifying *all* dropbutton markup everywhere).

I'm loving seeing these styleguide issues move forward. Thanks @Graham-72 and @wesruv!

**Comment by wesruv** [comment] 2015-04-22 04:21
Assigning to @Graham-72 to prevent confusion

**Comment by Graham-72** [comment] 2015-04-22 14:30
I have created a new PR at backdrop/backdrop/pull/829

**Comment by Graham-72** [comment] 2015-04-22 17:19
Thanks @quicksketch for your tip about "Awesome Screenshot".

>On the modules page, I think we could simply specify a minimum width for the "Operations" column

I have given this a try and unfortunately it produces inconsistent results in the operations column, as here..
![modules - backdrop starter 2015-04-22 18-10-59](https://cloud.githubusercontent.com/assets/10559274/7280601/bfe580ee-e91b-11e4-8e55-be1a5567123c.png)

This is just a first look and I will try other possibilities.

**Comment by wesruv** [comment] 2015-04-23 02:00
*shakes fists in the sky* TAAAAABBBBLLLEEEESSS!!!

Best of luck, they're not always cooperative.

**Comment by klonos** [comment] 2015-04-25 02:56
I understand that the styleguide dictates using UPPERCASE for our buttons, but the dropbutton innovation came to existence in order to save us horizontal space. By using UPPERCASE we increase the width of the "Operations" column though. Regression?

Also, (just a heads-up because I have not actually checked the PR itself - just the [styleguide](https://backdrop-ops.github.io/styleguide/#dropbutton)) when hovering over the parts of the dropbutton that "intersect" with one or more of the rounded corners, the darker background has square corners and thus covers the blue rounded corner border:

Hovering over a menu item other than the first/top or the last/bottom (no corners chopped):
![dropbutton-no_corners_chopped](https://cloud.githubusercontent.com/assets/2423362/7331196/740a7126-eb4a-11e4-92f7-d18144bfba9f.png)

Hovering over the first/top item (top-left corner chopped):
![dropbutton-upper_left_corner_chopped](https://cloud.githubusercontent.com/assets/2423362/7331197/7c3835ae-eb4a-11e4-8c10-0f0b2853f06a.png)

Hovering over the last/bottom item (bottom-left corner chopped):
![dropbutton-lower_left_corner_chopped](https://cloud.githubusercontent.com/assets/2423362/7331198/84b62c18-eb4a-11e4-90cd-b2a62fb3a8c6.png)

Hovering over the right part with the arrow (both right corners chopped):
![dropbutton-both_right_corners_chopped](https://cloud.githubusercontent.com/assets/2423362/7331199/8a85aa4c-eb4a-11e4-91d1-003e1a50025a.png)

**Comment by Graham-72** [comment] 2015-04-25 04:49
> when hovering over the parts of the dropbutton that "intersect" with one or more of the rounded corners, the darker background has square corners and thus covers the blue rounded corner border:

Interesting. I am not seeing this in my test site with PR applied and I have checked in Firefox, Chrome, Safari and IE (all on PC), but maybe some other change is causing this.

**Comment by klonos** [comment] 2015-04-25 12:03
As I said...

> ...I have not actually checked the PR itself - just the [styleguide](https://backdrop-ops.github.io/styleguide/#dropbutton)

**Comment by Graham-72** [comment] 2015-04-26 14:44
I have added a note to https://github.com/backdrop/backdrop/pull/829 about the latest situation concerning the appearance of the drop buttons. 
My note says : 
>with the latest 1.x-new-style the problem with the appearance of the drop button arrows seems to have disappeared and we don't need my proposed changes to its size. But we do need to modify dropbuttons.css to make the color blue and to capitalize the letters. Also we need to change style.css to remove the background gradient. It then looks like this
![dropbuttondown](https://cloud.githubusercontent.com/assets/10559274/7337690/e45d7f5a-ec2a-11e4-8b1f-179a187afb2b.png)
![dropbuttonup](https://cloud.githubusercontent.com/assets/10559274/7337691/e4632504-ec2a-11e4-9fec-099c881565fd.png)

**Comment by quicksketch** [comment] 2015-04-27 18:45
I merged https://github.com/backdrop/backdrop/pull/852, which was simple enough and ready to just remove the background color.

**Comment by Graham-72** [comment] 2015-04-27 21:21
I have provided PRs https://github.com/backdrop/backdrop/pull/853 and https://github.com/backdrop/backdrop/pull/854 to set the minimum width of drop buttons where appropriate on system modules admin, layout list and layout edit forms.

**Comment by jenlampton** [comment] 2015-04-30 22:41
Thanks @Graham-72! 

Let's try to keep the number of PRs to a minimum - Nate's our bottleneck with reviewing all the PRs at the moment, and the less he has to review the better. I've closed your two most recent PRs as duplicates of https://github.com/backdrop/backdrop/pull/829, so let's continue working on that one until it's ready to be merged.

To update a PR: 
* Checkout the branch the PR was made from.  
* Make whatever changes you need to the code.
* Commit the changes with --amend to overwrite the previous commit (and if needed, commit message)
* Push the local branch up to your remote (use -f to overwrite the previous code in that branch)
* the PR should be updated right away
* feel free to add a comment stating that it's been changed.

**Comment by jenlampton** [comment] 2015-04-30 23:47
@klonos 

> I understand that the styleguide dictates using UPPERCASE for our buttons, but the dropbutton innovation came to existence in order to save us horizontal space. By using UPPERCASE we increase the width of the "Operations" column though. Regression?

I don't think it's a regression, I actually think it's a UX improvement.  On small devices really tiny links are hard to get at with fingers. Having a single button is certainly an space-saver over listing each action in a horizontal row, but also helps with the finger problem :)

**Comment by jenlampton** [comment] 2015-05-01 00:57
I'm going to take a stab at solving this and https://github.com/backdrop/backdrop-issues/issues/370 in the same PR - without changing markup it could be a bit of a pain.

**Comment by jenlampton** [comment] 2015-05-01 08:51
zomg.  what a headache!  I now have a deeper appreciation for all @Graham-72 was trying to accomplish in this issue :)  New PR over at https://github.com/backdrop/backdrop/pull/829

**Comment by quicksketch** [comment] 2015-05-08 00:34
Thanks! Merged in https://github.com/backdrop/backdrop/pull/864. Are there any remaining sub-issues here?

**Comment by quicksketch** [comment] 2015-05-08 21:55
Let's close this and make a new issue for any followups.

**Closed by quicksketch** 2015-05-08 21:55 UTC
