### ISSUE TITLE
Fixed grammar error in Views row class description text

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#5143] opened 2021-08-08 23:51 UTC
**Steps To Reproduce**

To reproduce the behavior:
1. Navigate to Structure -> Views (`admin/structure/views`)
2. Edit any view (click the "Configure" button)
3. Under the "Format" section, click "Settings"
4. In the pop-up that opens, scroll down to the "Row class" setting:
   ![image](https://user-images.githubusercontent.com/2423362/157045311-cb64bf28-c37a-474d-a5d0-9bf675b4c55f.png)
5. The description text under Row class" says:
   > The class to provide on each row. You may use field tokens from as per the "Replacement patterns" used in "Rewrite the output of this field" for all fields.

   The "as per" is unexpected.

## Expected behavior

The description should probably change to something like:
> "The class to provide on each row. You may use field tokens from the "Replacement patterns" used in "Rewrite the output of this field" for all fields.

**Comment by ayushi424** [comment] 2022-03-07 13:09
Hi, I am Ayushi, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you. Would also seek some guidance on working on it.

**Comment by klonos** [comment] 2022-03-07 13:44
Welcome to our community @ayushi424 👋🏼 

I have updated the steps to reproduce the problem in the issue summary to be more detailed. I hope it helps.

I'll follow up shortly with some further information...

**Comment by stpaultim** [comment] 2022-03-08 08:42
@ayushi424 - I see you created a PR. Thanks very much!!!!!

If you create a PR, it's good to make a note in the issue letting folks know that a PR is available to review. I'll change the labels for you.

**Comment by stpaultim** [comment] 2022-03-10 05:25
I've reviewed this PR. It is a small change to the help text, which is something I can say works for me and approve the code change. :-)

**Closed** 2022-03-10 05:38 UTC
Labels: status - fixed

**Comment by BWPanda** [comment] 2022-03-10 05:39
Thanks for the PR @ayushi424! And thanks to @docwilmot for spotting this. I've merged https://github.com/backdrop/backdrop/pull/3977 into 1.x and 1.21.x.

**Comment by stpaultim** [comment] 2022-03-10 06:01
@ayushi424 Congratulations on your first merged commit to Backdrop CMS. We hope that you will try another one.
