### ISSUE TITLE
CKEditor: Select image library is disabled

### ISSUE THREAD

**Issue by dyrer** [backdrop/backdrop-issues#3481] opened 2019-01-16 08:05 UTC
![bdlibrary](https://user-images.githubusercontent.com/379094/51234739-4a9ab900-1976-11e9-91d2-d7d39918e060.jpg)
Link Upload from library is disabled when open window to insert image(s)

To insert an image from library (in my installation)
I have to click upload and then Select Image from library is enabled
Is this correct?

I recommend if this the correct behavior both links (upload & from library) be enabled from the start

**
Backdrop CMS 1.12
PHP 7.1.x
Apache

----
PR by @opi https://github.com/backdrop/backdrop/pull/2484

**Comment by olafgrabienski** [comment] 2019-01-16 11:19
I've had a look at my Backdrop 1.11.3 installation, where the display of the add image dialog is correct and at a Backdrop 1.12.x-dev sandbox site, where the display is not correct. Here the screenshots in comparison:

**Backdrop 1.11.3** (correct: select a file to upload, or click "Select from library")
<img width="336" alt="screen-backdrop-add-image-dialog-a-correct" src="https://user-images.githubusercontent.com/14188307/51244823-54c4b380-1986-11e9-9778-228f56bc4227.png">

**Backdrop 1.12.dev** (not correct: no select file element, "Select from library" is no link)
<img width="336" alt="screen-backdrop-add-image-dialog-b-incorrect" src="https://user-images.githubusercontent.com/14188307/51244825-555d4a00-1986-11e9-98a0-1a8171be1357.png">

AFAIK, there were two CKEditor related changes regarding similar elements in 1.11.4. Maybe one of the fixes had side effects?

- #3384 fixed an error when adding a link to an image
- #3404 fixed "incorrect initial display of Insert link dialog" (even if about the link dialog, it sounds very similar)

**Comment by Graham-72** [comment] 2019-01-16 15:18
Yes, I think this is caused by one of the changes introduced in the fix for #3404.
Line 147 in filter.js is causing the problem and changing it back to `$(".form-item-attributes-href").css({ "display": "none"});` as in my initial PR seems to fix the problem.
@opi Maybe we need something more complicated to achieve the aim of making the Link Value the default - see https://github.com/backdrop/backdrop-issues/issues/3404#issuecomment-447131977

**Comment by klonos** [comment] 2019-01-16 15:23
Related or duplicate (?): #3482

**Comment by herbdool** [comment] 2019-01-19 07:05
@Graham-72 maybe look for class parent that is unique like `$(".editor-link-dialog .form-type-managed-file").css({ "display": "none"});` so it doesn't clash between the link and image dialogs.

**Comment by opi** [comment] 2019-01-19 13:12
I don't really know why, because this filter.js file looks like a mess, but the solution of @herbdool works.

**Comment by herbdool** [comment] 2019-01-19 13:31
@opi are you able to make a PR? It needs to work for both dialogues but I didn't spend too much time on it.

I noticed that both dialogues have similar CSS classes probably because link borrows from the image dialogue.

**Comment by opi** [comment] 2019-01-19 14:20
done https://github.com/backdrop/backdrop/pull/2484

**Comment by opi** [comment] 2019-01-19 15:16
Pr updated, and after some monkey testing it seems good. Need other tests please.

**Comment by olafgrabienski** [comment] 2019-01-19 15:53
I've tested the PR in the sandbox website:

- opened image dialog, looks good, like the 1.11.3 screenshot in https://github.com/backdrop/backdrop-issues/issues/3481#issuecomment-454744059
- uploaded an image, works fine and seems to fix also #3482 
- inserted the image and saved the page, still fine
- edited the page, inserted the same image as above from the library without any problem

So, looks really good. Not sure if we should test other elements of the dialog or even other dialogs.

**Comment by opi** [comment] 2019-01-19 15:57
@olafgrabienski thanks. Try to open image dialog, then link dialog, then image dialog, etc... This is the most problematic case I encounter

**Comment by herbdool** [comment] 2019-01-19 16:08
@opi I recall something about reusing the image dialog so this is probably the negative side effect.

**Comment by olafgrabienski** [comment] 2019-01-19 16:11
@opi Done (uploaded image, saved, linked the image, reopened image and link dialog), I've seen no problems so far. Would however be nice if another person could have another look at the sandbox site.

**Comment by herbdool** [comment] 2019-01-19 16:15
@olafgrabienski @opi I took a look too and looks much better. One thing @olafgrabienski, can you try upload a file via the link dialog too? I can't recall how it worked before. Uploading the file works though the dialog only shows the link text and css classes fields. Only when opening it again will it show the uploaded file as well.

**Comment by Graham-72** [comment] 2019-01-20 20:08
PR 2485 is my attempt at a fix that seems to work but still opens with the Upload Image dialog. Hopefully it makes it clearer that a URL may be entered directly as an alternative to choosing from the image library.

**Comment by opi** [comment] 2019-01-21 09:48
PR updated. From my tests, Link and Image modals work fine.

**Comment by klonos** [comment] 2019-01-21 12:01
Thanks @opi ...this fixes #3482 too 👍 

PR looks fine other than a tiny grammar nit in a code comment. Other than that, RTBC.

**Comment by klonos** [comment] 2019-01-21 12:06
...actually, while we are on this, can we add the max upload size, and allowed file extensions description in the upload field?

**Comment by opi** [comment] 2019-01-21 12:15
> can we add the max upload size, and allowed file extensions description in the upload field

Follow-up issues ? So we can merge this fix quickly

**Comment by opi** [comment] 2019-01-21 12:15
> PR looks fine other than a tiny grammar nit in a code comment. Other than that, RTBC.

Fixed.

**Comment by herbdool** [comment] 2019-01-21 12:17
Agreed. This is a bug fix that needs to get out soon so anything what should be in a new issue.

**Comment by quicksketch** [comment] 2019-02-08 21:00
Thanks @opi, @klonos, @herbdool, @olafgrabienski, @Graham-72, and @dyrer! Merged https://github.com/backdrop/backdrop/pull/2484 into 1.x and 1.12.x.

**Closed** 2019-02-08 21:01 UTC
Labels: status - fixed, status - has pull request, type - bug report
