### ISSUE TITLE
System info cache writing and registry rebuilding is broken without a full bootstrap

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#781] opened 2015-02-25 17:28 UTC
This is the same as https://www.drupal.org/node/534594 which is **critical**:

> Update 12 Aug 2013: The registry has been removed from Drupal 8 and is less critical. However it is still critical for D7.

> catch notes in comment [#130](https://drupal.org/node/534594#comment-6652764) that while we no longer write the info to the {system} table, some alters may affect what does get saved to config. The patch at [#134](https://drupal.org/node/534594#comment-7131326) needs review.

So, since Backdrop is D7 + D8 + !magic! does this apply to us?

While testing [Basic Cart](https://www.drupal.org/project/basic_cart) ([that is being ported to Backdrop](https://github.com/biolithic/backdrop_basic_cart)) I got hit by [#1044914: Fatal error: Call to undefined function views_include()](https://www.drupal.org/node/1044914) which is postponed on the D7 critical issue. While the patch is not committed to D7, I thought I'd file this here because we have views in core too + catch mentions saving in config issues.

**Comment by quicksketch** [comment] 2015-02-25 19:45
I don't think this applies to Backdrop. We removed/replaced the registry as well: #77. We now use hook_autoload_info() to declare classes (but unfortunately that hook isn't documented, see #712).

> I got hit by #1044914: Fatal error: Call to undefined function views_include() which is postponed on the D7 critical issue.

Could you elaborate on the problem? The referenced issue is a bit on the vague side. When are you trying to use `views_include()`?

**Comment by klonos** [comment] 2015-02-25 20:01
I was testing the Drupal version of Basic Cart. I now filed this issue against views: [Fatal error: Call to undefined function views_include() in sites/all/modules/views/includes/plugins.inc on line 9](https://www.drupal.org/node/2438227)

**Comment by quicksketch** [comment] 2015-02-26 00:57
I read through the steps for reproducing at https://www.drupal.org/node/2438227.

It looks like though this problem has the same symptom (`views_include()` not found), the source of the problems appears to be different. I think this may be a simple bug directly in Basic Cart, such as attempting to use that function outside of a function (like at the top of a file).

I also checked in on our own implementation of VBO and all calls to `views_include()` within our own code. It doesn't look like the way we're calling it would ever be in a situation where the function wouldn't already exist.

I'm going to close this as it doesn't look related to core. If there is some evidence otherwise, please reopen.

**Closed by quicksketch** 2015-02-26 00:57 UTC
