### ISSUE TITLE
config files installation should respect settings.php 

### ISSUE THREAD

**Issue by rroseselavy42** [backdrop/backdrop-issues#4139] opened 2019-10-15 22:17 UTC
**Description of the bug**
When config active and staging are set in  settings.php before running backdrop installation config directory files are generate in files/config_(random string)/active instead of folder specified in settings.php. 
**Steps To Reproduce**
To reproduce the behavior:
1. edit settings.php to set config active directory
2. install backdrop (used drush backdrop-site-install)

**Actual behavior**
config is added to files/config_ and site is broken due to lack of config. 
**Expected behavior**
expect that on running backdrop install that backdrop will generate in folder specified by settings.php

**Comment by indigoxela** [comment] 2019-11-04 09:21
Hi @rroseselavy42 thanks for taking the time to report here.

Anyway, I'd rather suspect this to be a _drush_ issue.
I tried to reproduce it (without drush). Downloaded a fresh backdrop, opened settings.php and set `$config_directories` to custom values, ran the installer via the webbrowser.

The setting was respected, the install ran smoothly.

You might want to consider the alternative [Backdrop Console](https://github.com/backdrop-contrib/b), which is specialized on Backdrop. There's another alternative: [Drop](https://github.com/backdrop-contrib/drop).

Please note: both command line tools are currently under heavy development.

**Comment by BWPanda** [comment] 2022-05-28 08:31
Closing as "cannot reproduce".

**Closed by BWPanda** 2022-05-28 08:31 UTC
Labels: type - bug report, status - cannot reproduce
