### ISSUE TITLE
In Layout, "ADD BLOCK" doesn't work for "Primary Navigation" sometimes.

### ISSUE THREAD

**Issue by vinviny** [backdrop/backdrop-issues#2727] opened 2017-06-06 08:08 UTC
## Describe your issue or idea
No response for some blocks, when I ADD BLOCK in the layout page.

### Steps to reproduce (if reporting a bug)
In the Layout screen, I deleted "Primary Navigation" block (for testing), and tried to add it back again. 

### Actual behavior (if reporting a bug)
However, whenever I click the link "Primary Navigation" in the selection window, nothing happens with no response. Some other blocks respond.

### Expected behavior (if reporting a bug)
When I click the link "Primary Navigation", more options will appear so that I can choose more options, and then, finally add the "Primary Navigation" block into my layout.

### Relevant version/system information (if applicable)
1.7 (the previous version was the same, which was my reason to update, but the problem continues)

**Comment by olafgrabienski** [comment] 2017-06-06 10:44
@vinviny Couldn't reproduce the issue. That's what I did on my Backdrop 1.6.3 test site:

- Removed *Primary navigation* from the Default Layout and saved the layout.
- Header > Add Block > Primary navigation
  - Block title type: None
  - Menu style: Dropdown menu
  - Maximum depth: Unlimited
  - Button "Add block"
- Saved the layout.

Hm, no idea at the moment. Are there maybe any special layout, block or menu related contrib modules on your website?

**Comment by vinviny** [comment] 2017-06-06 12:15
Thank you for your quick response. 
Yes, I meant exactly what you did. But if you didn't reproduce it, then I may invite you to log-in to my site as an administrator to check. Please let me know your email address via "vinviny(at)hotmail.com", so that I can give you temporal ID/PW with the URL.

**Comment by olafgrabienski** [comment] 2017-06-06 16:47
@vinviny Sent you a mail a couple of hours ago.

**Comment by olafgrabienski** [comment] 2017-06-07 10:54
@vinviny I had a look at your test site and could reproduce the issue there. Don't know the reason so far but I noticed two things which may help debugging. (That would be a task for people with more coding skills than mine.)

**(1)** When I cleared cache on `admin/structure/layouts/manage/default`, I got the following message:

```
Warning: include_once(EXAMPLE-PATH/test/layouts/hero/simmons_hero/simmons.php): failed to open stream: No such file or directory in _theme_process_registry() (line 574 of /home2/luasssmy/public_html/test/core/includes/theme.inc).
Warning: include_once(): Failed opening 'EXAMPLE-PATH/test/layouts/hero/simmons_hero/simmons.php' for inclusion (include_path='.:/usr/php/56/usr/lib64:/usr/php/56/usr/share/pear') in _theme_process_registry() (line 574 of /home2/luasssmy/public_html/test/core/includes/theme.inc).
```

In case the message is related to your issue: There are also former examples of the message on `admin/reports/dblog`.

**(2)** When I try to add the *Primary navigation* block to the Header (or to other regions), that doesn't work, and I see a *406 (Not Acceptable)* message in the *Console* tab of the Chrome Develeper Tools:

```
POST http://example.com/test/admin/structure/layouts/manage/default/add-block/editor/header/system%3Amain-menu 406 (Not Acceptable)
send @ jquery.js:4
ajax @ jquery.js:4
Backdrop.ajax.eventResponse @ ajax.js:317
(anonymous) @ ajax.js:245
dispatch @ jquery.js:3
r.handle @ jquery.js:3
```

While the same issue happens with some other menu-like system blocks (Account menu, Administration menu, and Breadcrumb), it does not happen with a custom menu.

I don't know if a 406 error is relevant, so I hope others can help.

**Comment by vinviny** [comment] 2017-06-07 12:28
Thank you for checking. 

Regarding this issue, I'm sure that the first item is not the reason because I had the same problem before the error message. The error occurred after some update.

At the moment, a workaround is to generate a new menu and use it instead of "Primary Navigation" menu.

**Comment by klonos** [comment] 2017-06-09 10:23
@vinviny was this a fresh installation of Backdrop that was upgraded? I don't understand what you mean by this:

> (the previous version was the same, which was my reason to update, but the problem continues)

**Comment by Retsell** [comment] 2019-04-04 15:20
I'm having this issue now. Was there ever any resolution other than the work-around of creating a new custom menu? I'm on 1.12.5, a new installation, but the funny thing is I have another existing site with the same version and all of the same modules enabled, where the problem doesn't occur.

**Comment by klonos** [comment] 2019-04-05 16:31
> ...the only difference between the two is that the one with the problem is running as a subdirectory rather than a home directory

We might be getting somewhere with this here. In @olafgrabienski's comment from back in 2017 above, I see that the site is also in a `/test` sub-directory: 

```
POST http://example.com/test/admin/structure/layouts/manage/default/add-block/editor/header/system%3Amain-menu
```

**Comment by klonos** [comment] 2019-04-05 16:41
@vinviny @Retsell can you please let us know what the `$base_url` is set to in your settings.php file?

**Comment by Retsell** [comment] 2019-04-05 17:05
Thanks for the help klonos!  In my case, $base_url was left unset.  To check, I just changed it to $base_url = 'http://www.mysite.org/backdrop';, flushed all caches, ran update.php, but it did not resolve the issue.

**Comment by klonos** [comment] 2019-04-05 17:12
@rickmanelius (or anyone else with experience configuring ddev) I am trying to install Backdrop via ddev in a subdirectory to test this, but I am getting 404s when trying to access `http://2727.ddev.local/test/backdrop`. What do I need to change in my ddev configuration to make things happen?

**Comment by klonos** [comment] 2019-04-05 17:15
Thanks for taking the time to report back and test things @Retsell 👍. I will try to reproduce this and see if I can figure out where the culprit might be. ...if I manage to get ddev to work with subdirectories that is 😅

**Comment by BWPanda** [comment] 2020-10-12 11:17
I'm tempted to close this as 'cannot reproduce', unless there are any objections...?

**Comment by stpaultim** [comment] 2020-10-12 20:42
It was not clear to me that anyone successfully tried to reproduce this after the discovery that it might be related to having Backdrop in a sub-directory. So, I tried to recreate it locally in a sub-directory and was NOT able to recreate it based upon the instructions left by @olafgrabienski

**Comment by BWPanda** [comment] 2020-10-12 20:55
Let's close then. If anyone can reliably reproduce this and provide steps to do so, we can re-open.

**Closed by BWPanda** 2020-10-12 20:55 UTC
Labels: help wanted, needs - more feedback, type - bug report
