### ISSUE TITLE
Entity reference fields referencing terms fail to update table `taxonomy_index` in some instances.

### ISSUE THREAD

**Issue by leeksoup** [backdrop/backdrop-issues#6082] opened 2023-04-26 22:10 UTC
[EDIT]

Updated description
--------------------

- An upgraded D7 site that contained Entity Reference fields referencing taxonomy terms lost its ability to maintain the `taxonomy_index` table for those fields
- The result was that the page `taxonomy/term/[tid]` returned blank pages, despite the fact that the nodes contained references to terms
- The field instance for those ER fields were missing a crucial setting, `$instance['settings']['behaviors']['taxonomy']['status'] = TRUE`. Which resulted in the `taxonomy_index` not being filled or updated
- We could not reproduce what caused this.
- The OP used a small module to rebuild the table (caveat: the module had a small bug that prevented the whole rebuilding - see last posts)

  
-----
[Original post]
## Description of the bug

I have a lot of nodes tagged with various taxonomy terms. But for some reason, they are not showing, and instead I am getting the error:

There is currently no content classified with this term.

I first posted about this issue over at the forums https://forum.backdropcms.org/forum/tagged-items-are-not-shown-under-taxonomytermid

## Steps Taken

1. I was advised to rebuild the taxonomy_index table by finding all the nodes and then running
```
taxonomy_delete_node_index($node); 
taxonomy_build_node_index($node);

```
to remove existing records and then rebuild them.

2. This emptied the taxonomy_index table. So it looks like taxonomy_delete_node_index($node) worked, but taxonomy_build_node_index($node) didn't.

3. I found the taxonomy_build_node_index($node) function definition and did some debugging and I think I found the problem. The taxonomy terms field info gives the module as "entityreference" rather than "taxonomy". Since the taxonomy_build_node_index function checks for the field's module to be "taxonomy" this causes it to fail silently for my fields.

## Expected behavior

The site was upgraded from D7 using the documented upgrade path. I expected the taxonomy term pages to continue to work. :)

## Additional information

Since the Entity Reference module was part of Backdrop core, @argiepiano  advised that this is likely a bug.

Add any other information that could help, such as:
- Backdrop CMS version: 1.24.2
- Web server and its version: Apache httpd 2.4.54
- PHP version: 7.4
- Database sever (MySQL or MariaDB?) and its version: MariaDB version 15.1 Distrib 10.5.18
- Operating System and its version: Fedora 35
- Browser(s) and their versions: Brave 1.50.125

**Comment by argiepiano** [comment] 2023-04-26 22:24
> The taxonomy terms field info gives the module as "entityreference" rather than "taxonomy".

This is strange. Where are you seeing that? By opening the config json file? I'm checking by creating new term reference fields, and the json file correctly shows `"module": "taxonomy",`

**Comment by argiepiano** [comment] 2023-04-26 22:30
Are you sure your D7 term reference field wasn't actually and entity reference field? I just tried an upgrade from D7 for a content type that contained a term reference field, and the field was ported correctly.

**Comment by leeksoup** [comment] 2023-04-26 22:34
I'm seeing it by using code borrowed from the taxonomy_build_node_index function.

```
$nid = 2294;
$node = node_load($nid);
foreach (field_info_instances('node', $node->type) as $instance) {
      $field_name = $instance['field_name'];
      $field = field_info_field($field_name);
      print_r ($field); // debug
}
```

It is possible it was an entity reference in D7 and I can check that. However, the taxonomy/term/xx should still work (and always has). I know that the taxonomy_index table was properly filled in D7 as well.

**Comment by leeksoup** [comment] 2023-04-26 22:38
Yes, you are correct. They are Entity Reference fields in D7, that reference the taxonomy vocabulary terms. 

So what does that mean for me? How can I get the taxonomy tables rebuilt for _taxonomy_ entity references?

**Comment by argiepiano** [comment] 2023-04-26 22:38
Can you check your Backdrop DB  the `field_data_YOUR_TERM_FIELD`? If this was ported as a term reference field, you'll see the last column should be `MY_FIELD_tid`. If this was ported originally as an entityreference field, the last column will be `MY_FIELD_target_id`.

**Comment by argiepiano** [comment] 2023-04-26 22:42
> So what does that mean for me? How can I get the taxonomy tables rebuilt for taxonomy entity references?

You can't. These are two different types of fields, stored in different ways. Entity reference fields in Backdrop (even when they reference terms) will not fill in the `taxonomy_index` table . 

You will need to find a way to emulate the behavior of term reference fields. You could create a View that shows all the nodes that reference a specific term referenced by the entity reference field in your node..

**Comment by leeksoup** [comment] 2023-04-26 22:47
Yup, taxonomy_vocabulary_1_target_id.

> You can't. These are two different types of fields, stored in different ways. Entity reference fields in Backdrop (even when they reference terms) will not fill in the taxonomy_index table .

Ugh. I had the impression that Entity Reference would continue to work the same way in Backdrop as it did in D7. Am I able to update the documentation on it to make this clear for future users?

I could probably write the code to transform the fields from entity ref to term ref, but I will try your suggestion of using Views instead first. If that works, then I guess I'm all set. Thanks.

**Comment by leeksoup** [comment] 2023-04-26 23:48
> You will need to find a way to emulate the behavior of term reference fields. You could create a View that shows all the nodes that reference a specific term referenced by the entity reference field in your node..

This isn't going to work because there is no generic "entity reference" option in Views filters as there is "taxonomy term." So I would have to add multiple contextual filters to cover multiple vocabularies, and that in turn would mean the URL would need have the tid in different places depending on which vocabulary the term resides in.... What a mess.

This is a showstopper for me, unless there is some more advanced Views functionality to handle this than I am aware of.

If Entity Reference has lost the functionality of building the taxonomy indexes, then Views needs to be able to handle the taxonomy entity refs in a similar way to taxonomy terms.

**Comment by argiepiano** [comment] 2023-04-27 00:33
>  I had the impression that Entity Reference would continue to work the same way in Backdrop as it did in D7.

I'm checking D7. In D7 when you add to a node an entity reference field refers to a term, the `taxonomy_index` table is actually not built. So, I don't think your assessment is correct. So, I'm just wondering if perhaps your D7 site was actually providing the functionality via a View?

**Comment by argiepiano** [comment] 2023-04-27 00:52
> This isn't going to work because there is no generic "entity reference" option in Views filters as there is "taxonomy term." 

I'm not sure exactly what you are looking for, but I'm able to reproduce the functionality of listing all nodes that have a term by doing this:

1. I created a view of nodes
2. I entered a Contextual Filter with the entity reference field

That's it (additionally I have the View change the title to include the name of the term):

<img width="1195" alt="Screen Shot 2023-04-26 at 6 51 06 PM" src="https://user-images.githubusercontent.com/9938978/234732403-5fffceca-8980-4058-b5fe-5e309be63aa8.png">

In the snapshot above, the url is:
`/nodes-with-term/3`

**Comment by argiepiano** [comment] 2023-04-27 01:03
If you wanted to move all data from the entity reference field into a term reference field, this is what I would do:

1. Add a term reference field to your nodes (your nodes already have that entity reference field)
2. Enable Entity Plus, so that you can use metadata wrappers
3. Create some code such as (assuming your entity ref field is called `field_entity_reference_term` and your new term reference field is called `field_term_reference`.

```php
$query = db_select('node');
$query->addField('node', 'nid');
$result = $query->execute()->fetchCol();
$nodes = node_load_multiple($result);
foreach ($nodes as $node) {
  $wrapper = entity_metadata_wrapper('node', $node);
  $wrapper->field_term_reference = $wrapper->field_entity_reference_term->raw();
  $wrapper->save();
}
```

So, the above will move the term id to the term reference field. After that, you can rebuild your `taxonomy_index` table the way I indicated in the Forum post.

**Comment by leeksoup** [comment] 2023-04-27 02:15
> I'm checking D7. In D7 when your content type has an entity reference field that refers to a term, the `taxonomy_index` table is actually not built. So, I don't think your assessment is correct. This is not how it worked in D7.

That is truly weird. The site has been running since early D6 days, but I updated it to D7 many years ago. It is of course likely that the setup was different originally. BUT the new nodes added since the D7 upgrade continue to have entries in the taxonomy index table. I know that I haven't done anything special to make that happen, and the Views continue to reference "taxonomy term ID (with depth)" which does not work on the Backdrop version of the site.

>So, I'm just wondering if perhaps your D7 site was actually providing the functionality via a View?

No, the taxonomy/term/id functionality in D7 site is from the taxonomy module. The optional View for Taxonomy term is disabled.

**Comment by leeksoup** [comment] 2023-04-27 02:19
> > This isn't going to work because there is no generic "entity reference" option in Views filters as there is "taxonomy term."
> 
> I'm not sure exactly what you are looking for, but I'm able to reproduce the functionality of listing all nodes that have a term by doing this: ...

I appreciate your taking the time to help me, but my nodes have multiple entity reference fields that reference different vocabularies, so this simple setup doesn't work. I need to be able to pull content nodes based on various combinations of terms from different vocabularies.

**Comment by leeksoup** [comment] 2023-04-27 02:29
> If you wanted to move all data from the entity reference field into a term reference field, this is what I would do: [...]

Thanks for this, @argiepiano ! I will have to look back and see why I changed them over to Entity reference fields in the first place. At one time there was a push to "unify" all the reference type fields into Entity Reference and stop using Term reference, Node reference, etc. but I don't recall if there was more to the decision than that.

**Comment by argiepiano** [comment] 2023-04-27 02:34
Sure, @leeksoup, and good luck with this. It seems like your setup is pretty complex - however, I still think this can be done with Views. There is nothing really special to the way D7 and Backdrop do the page found under `taxonomy/term/[tid]`. In fact D7 provided a (disabled) view that overrides that path with a View.

>  At one time there was a push to "unify" all the reference type fields into Entity Reference and stop using Term reference, Node reference, 

Yes, this is also being discussed in Backdrop.

**Comment by leeksoup** [comment] 2023-04-27 02:47
> well, there are some special things about taxonomy term views - one of those is the ability to use the "with depth" contextual filter to get nodes that use children or parents of the term

Yes, and I do use this feature, extensively.

Is an alternative to write my own code to build the taxonomy index table from the (taxonomy) entity reference fields? 

> > At one time there was a push to "unify" all the reference type fields into Entity Reference and stop using Term reference, Node reference,

> Yes, this is also being discussed in Backdrop.

Ah. Maybe I should try to find those discussions and put in my 2c worth. It would be seriously problematic for me, at least for this site, if the special features of taxonomy terms went away. Drupal has the most powerful such system that I'm familiar with, and losing these features would hamstring it.

**Comment by argiepiano** [comment] 2023-04-27 02:57
Well, it seems I was wrong - actually Entity References that reference terms DO populate `taxonomy_index`, both in 
Backdrop and D7

Both of them have this option in the Entity Reference configuration:

<img width="1225" alt="Screen Shot 2023-04-26 at 8 54 29 PM" src="https://user-images.githubusercontent.com/9938978/234748132-df57ef51-6c4c-4f5c-9f02-057c22a94b90.png">

I checked in both test sites D7 and Backdrop, and both show a populated `taxonomy_index`

So, your issues, @leeksoup, must be in a bug somewhere else.

**Comment by leeksoup** [comment] 2023-04-27 03:10
Woah, nice! No problem @argiepiano -- everyone makes mistakes sometimes. 

Can you please give me the path to that config option? I'm not seeing it at the field configuration under content type - manage fields. All I'm seeing is this:

![image](https://user-images.githubusercontent.com/25186767/234749727-2de2d2a6-2178-408f-ba65-f3f00cbabc2f.png)

**Comment by leeksoup** [comment] 2023-04-27 03:12
nvm! It was on the other tab. And the checkbox is already checked in both D7 and Backdrop:

![image](https://user-images.githubusercontent.com/25186767/234750111-6d397acb-7c2f-4fff-a61a-8489a568d45f.png)

**Comment by argiepiano** [comment] 2023-04-27 03:13
Yes, it's there and checked by default. I'm re-checking the upgrade process to see if that's where you lost of your data in `taxonomy_index`. I'll post again in a few minutes.

**Comment by leeksoup** [comment] 2023-04-27 03:20
No, it was there for a long while after my upgrade to Backdrop. It got lost within ~ the last month. And currently, it's refusing to update the `taxonomy_index` table when I either re-save a node or create a new node with entity references.

**Comment by argiepiano** [comment] 2023-04-27 03:22
I did a quick, simple test upgrading a D7 site with nodes that used Entity Reference to reference a term. The table `taxonomy_index` was upgraded correctly, and `taxonomy/term/[tid]` is working as expected. So, something else must have happened that made your site lose all those entries in `taxonomy_index`... 

If this is a bug, it'd be hard to fix without a reliable way to reproduce the problem. So at this point, I think the best way forward is to try to rebuild that `taxonomy_index`. 

I just saw your message: it's strange that even when you create new nodes, the site is not updating that table. I supposed you don't have a sanitized version of your db (i.e. without any private or personal info) and config files that I could try localy?

**Comment by leeksoup** [comment] 2023-04-27 03:24
> I supposed you don't have a sanitized version of your db (i.e. without any private or personal info) and config files that I could try localy?

Not really. It's pretty large, too, but I can try to take a look in the next day or two and see if I can put something together for you.

**Comment by argiepiano** [comment] 2023-04-27 03:28
And you said that `maintain_index_table` is TRUE in `taxonomy.settings.json`? And also that the nodes are published by default when you create them? The table is updated by `EntityReferenceBehaviorHandlerTaxonomyIndex::buildNodeIndex()` but only when the node is published and when maintain_index_table is true in the config folder.

**Comment by argiepiano** [comment] 2023-04-27 03:38
Question: was your D7 site multilingual?

**Comment by leeksoup** [comment] 2023-04-27 04:19
> And you said that `maintain_index_table` is TRUE in `taxonomy.settings.json`? 
Yes.

> And also that the nodes are published by default when you create them? 
Yes.

**Comment by leeksoup** [comment] 2023-04-27 04:27
> Question: was your D7 site multilingual?

No.

> In your config folder, find the instance json file for one of your entity reference fields that references terms [...] Check that status is set to true under taxonomy....

No. I think you've found the problem! The only setting in there is this:
```
    "settings": {
        "user_register_form": false
    },

```
I just checked all the similar fields and the same for them all. Yet within Backdrop UI, I can see that the box for "Taxonomy index" _is_ checked for all of them. So why isn't it in the config file?

**Comment by leeksoup** [comment] 2023-04-27 20:57
Found out the reason for taxonomy_index entries disappearing over time after upgrading to Backdrop. 

At the initial upgrade from D7, the taxonomy_index table was carried over into the Backdrop DB. But anytime a node was re-saved after that, the entries for that node in the taxonomy_index table were removed, presumably because of the config issue you uncovered.

**Comment by argiepiano** [comment] 2023-04-27 21:47
A few additional observations (I'll work out a PR tonight):
- When the field instance of the entity reference field is missing `$intance['settings']['behavior']['taxonomy']['status']`, the check box  for "Additional Behaviors | Taxonomy" STILL shows as checked in the Manage fields UI. This makes it impossible to realize that there is a problem
- Resaving the field configuration in Manage fields will effectively correct this missing property

So, @leeksoup, while we fix this bug, you may want to open the configuration UI for those fields, and click Save to fix the missing settings. That will assure that new nodes, and nodes that are edited and resaved, will populate `taxonomy_index`.

So, the tasks needed here involve:

1. Figuring out why this important setting of the field instance is not originally included (upon upgrade, but also when you first add an ER field that references a term to a node) and fixing this problem
2. Devising a way to fix your database with some custom code (perhaps within a hook_update_N()) in a way that other users experiencing this can use

**Comment by leeksoup** [comment] 2023-04-27 22:39
Great! Sounds like a plan.

If the `buildNodeIndex` function is called on node save, then task 2 could be accomplished by re-saving the config for all such fields, and then re-saving all the relevant node types (or even all the nodes). It would be nice not to have to re-save the nodes since the node data isn't actually going to be changed, but calling the function directly gave me an error: protected function.

**Comment by argiepiano** [comment] 2023-04-28 01:05
OK, so good news / bad news.

Bad news: 
- I'm unable to reproduce the bug. I've tried (1) adding taxonomy ER fields and (2) Upgrading a D7 site that used taxonomy ER fields. In both cases the field instance  does contain `$instance['settings']['behaviors']['taxonomy']['status']`. This makes it impossible to fix it, since I can't tell why this happened in your site.

Good news:
- I have confirmed that, if the ER field instance doesn't contain  `$instance['settings']['behaviors']['taxonomy']['status']`, then the `taxonomy_index` is not updated (we knew this, but I have double-checked).
- I have also confirmed that, if you resave the field configuration, these settings are correctly saved

I have put together a small module that runs a batch job to rebuild your `taxonomy_index` table. See attached
1. BACK UP YOUR SITE
2. For each of your content types that contain the ER fields referencing term, re-open the "configuration" ui for the field, and re-save. This will fix the missing settings
3. Manually confirm that the field instance settings are correctly saved by either inspecting the JSON files, or running in devel: `com(field_info_instance('node', 'FIELD_NAME', 'CONTENT_TYPE);`. This will output a structure. Look under settings > behaviors > taxonomy > status
4. Install the module attached 
5. Visit `/rebuild-taxonomy-index`, select the Content Type and submit

This will run a batch job that runs code borrowed from from `EntityReferenceBehaviorHandlerTaxonomyIndex::buildNodeIndex()`

After running this, manually inspect the DB by opening the `taxonomy_index` table.

I've tested this in my local, and seems to work fine. LMK what happens. 

[rebuild_taxonomy_index.zip](https://github.com/backdrop/backdrop-issues/files/11349002/rebuild_taxonomy_index.zip)

**Comment by leeksoup** [comment] 2023-04-28 04:39
Sorry for the bad news. Intermittent problems are such a pain!

Thanks for verifying those problems.

And thank you so much for building that module to fix my site! I backed up and followed your procedure. Sadly, the module doesn't actually get all the terms into the taxonomy index table. It looks like it's only saving ONE term per node, and most of my content has multiple taxonomy tags. I'll look at the code and see if I can figure it out. Or maybe running it multiple times will make the rest of the terms get added.

**Comment by leeksoup** [comment] 2023-04-28 06:24
OK, I found the bug. The `return TRUE` at line 164 is inside the `foreach` that adds the taxonomy index entries to the DB instead of outside it, so it returns after adding the first tid to the DB. Fixed my copy and retrying now.

**Closed** 2023-06-05 22:22 UTC
