### ISSUE TITLE
[UX] Make it easier to get the SRC attribute for an image field (in views)

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2616] opened 2017-04-04 02:22 UTC
Every so often, I want to get the path to an image in a view. Every time I'm reminded of how hard it is to generate the src attribute alone. I see two easy places we could expose the SRC:
* Provide an "Image URL" formatter, much like https://www.drupal.org/project/image_url_formatter, which has the added advantage of working outside of views
* In views "Replacement patterns" provide a psuedo-token for [field_whatever-src] just like we do for alt, title, width and height.

**Comment by BWPanda** [comment] 2019-05-08 07:15
I think we can close this as a duplicate of https://github.com/backdrop/backdrop-issues/issues/2921. Feel free to re-open if you disagree.

**Closed by BWPanda** 2019-05-08 07:15 UTC
Labels: status - duplicate
