### ISSUE TITLE
Numeric fields throw fatal error when left blank.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3873] opened 2019-06-18 03:06 UTC
**Steps To Reproduce**
1. Add an integer/decimal/float field to the a content type
2. Leave all field settings to default
3. Create a piece of content of the type used in step 1, leaving the number field blank -> Error 👎 

If the field was a...

- integer:
  ```
  SQLSTATE[HY000]: General error: 1366 Incorrect integer value: ''
  for column 'field_integer_value' at row 1
  ```

- decimal:
  ```
  SQLSTATE[HY000]: General error: 1366 Incorrect decimal value: ''
  for column 'field_decimal_value' at row 1
  ```

- float:
  ```
  SQLSTATE[01000]: Warning: 1265 Data truncated
  for column 'field_float_value' at row 1
  ```

---
# Original report

**Description of the bug**
I have added an multi-value integer (textfield) field to a content type. On the node/add form there are several (empty) fields displayed, like so:
<img width="1224" alt="Screen Shot 2019-06-17 at 8 04 28 PM" src="https://user-images.githubusercontent.com/397895/59650508-1f8dde80-913b-11e9-8507-3f867c759c2c.png">

If I leave one (or all) of these fields empty, I get a fatal error when I save the node. The visible error is `Error 
The website encountered an unexpected error. Please try again later.` but in the logs I can see the following:
```
EntityStorageException: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'field_integer_value' at row 1 in NodeStorageController->save() (line 487 of backdrop/core/modules/node/node.entity.inc).
```

**Steps To Reproduce**
To reproduce the behavior:
1. Add an integer field to the Post content type
2. Configure the field to have "Unlimited" values
3. Create a Post, leaving all Integer fields blank
4. Error

-----
PR https://github.com/backdrop/backdrop/pull/3007 by @indigoxela

**Comment by laryn** [comment] 2019-06-18 04:01
This also happened to me with a single value integer field (ie. skip step 2 above).

**Comment by jenlampton** [comment] 2019-06-20 07:31
Hm... Sounds like it may be an issue with field module not properly checking for empty/null values before saving then.

**Comment by herbdool** [comment] 2019-11-25 20:03
I got a slightly different fatal error message with Numeric (integer):

> SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'field_myfield_value' at row 1

Hopefully any PR here will fix this as well.

**Comment by herbdool** [comment] 2019-11-25 21:16
I made a PR: https://github.com/backdrop/backdrop/pull/3004.

The good: it throws a validation error before we get a fatal error.
Maybe bad: it throws a validation error when creating a field if the default is left blank. I would think ideally we should be able to leave the default blank but require a number when creating an entity.

**Comment by indigoxela** [comment] 2019-11-26 08:49
My finding so far is that the problem seems to be related to "empty string" vs. "null" in db table column.

If I change the empty string to an explicit NULL in function number_field_validate, in case the field value is empty, I can save empty values without problems.

```
    else {
      $item['value'] = NULL;// works!
    }
```
Could it be that mysql/mariadb handles numeric db columns in a different way compared to string columns (null/not null...)?

As D7 doesn't have the same problem while using the same db table schema, it might be worth some code comparison.

**Comment by herbdool** [comment] 2019-11-26 15:14
The D7 code doesn't look much different for the validate function https://git.drupalcode.org/project/drupal/blob/7.x/modules/field/modules/number/number.module.  Must be somewhere else.

**Comment by herbdool** [comment] 2019-11-26 18:13
My guess is this has something to do with moving to a HTML5 field. Seems like only difference from D7.

**Comment by indigoxela** [comment] 2019-11-27 10:33
As this bug makes number fields unusable to a certain degree, I've posted a PR with a _workaround_.
https://github.com/backdrop/backdrop/pull/3006

Please note: I wasn't able to discover the actual root cause. Something with the default value and/or the check for an empty field value seems fishy. No clue, where or how to solve it.

**Comment by laryn** [comment] 2019-11-27 13:38
[No answer here but related issue in D7 "Elements"](https://www.drupal.org/project/elements/issues/2398439): 

> When the user leaves a numberfield empty, the value of this field is an empty string. elements_validate_number() leaves it as it is. Maybe I am wrong, but I think it should make the value NULL. Or should the module developer take care of this?

**Comment by jenlampton** [comment] 2019-11-27 22:45
> I notice the D7 code includes a number_field_widget_validate function -- we don't seem to have that; do we need that?

We removed those since validation is handled by the browser for HTML5 elements. I don't think it would help in this case since we need the processing for empty values to happen after submission, and not before. I think @indigoxela is on the right in this PR track with returning early for number fields. Maybe all that is really needed is returning NULL here?

**Comment by indigoxela** [comment] 2019-11-28 07:49
@jenlampton I've updated my [PR](https://github.com/backdrop/backdrop/pull/3006) to reflect your comment.

Regarding returning `NULL` vs. `$value = ''` for number fields: The one thing I really don't get is, why empty field handling works for simple text and for email fields (value = '' results in not saving the field), but it doesn't work for number fields. Function number_field_is_empty correctly returns TRUE, but on node save it's still attempted to save the field. Which causes the exception.

Regarding the removed validation function: hmm... isn't it unsafe to solely rely on client validation?

**Comment by indigoxela** [comment] 2019-11-28 14:56
HA! Here's a significant difference between B and D7:

in file _field.default.inc_ Drupal filters out empty field values regardless of an entity, Backdrop only if an entity exists:

* https://git.drupalcode.org/project/drupal/blob/7.x/modules/field/field.default.inc#L89
* https://github.com/backdrop/backdrop/blob/97522cb79d148cd5993e52997a49ed7d99dcf70b/core/modules/field/field.default.inc#L94

This explains, why the problem only occurs at first node save!

The change reg filtering is relatively new, it came with https://github.com/backdrop/backdrop/pull/2377/files
The issue was https://github.com/backdrop/backdrop-issues/issues/3378

The question is now: how can we fix this regression without bringing back the problem solved by that commit.

@klonos mind to dig in?

**Comment by indigoxela** [comment] 2019-11-28 15:08
Another finding, somewhat unrelated (number field validation): the field (widget) _does_ have validation.
`'#element_validate' => array('form_validate_number')`
The function is provided by includes/form.inc
No need to worry about that. (Tested with a command line browser, that's unaware of html5 number fields.)

**Comment by herbdool** [comment] 2019-11-28 17:41
A dirty fix would be to only skip filtering out empty values if it's got an input format. If that can be done.

**Comment by indigoxela** [comment] 2019-11-29 07:08
> A dirty fix would be to only skip filtering out empty values if it's got an input format.

That's not necessarily that dirty.
If I get the suggestion right, we should revert the breaking change in field.default.inc and instead figure out a solution in function text_field_is_empty() - for instance return FALSE if an input format is set?

**Comment by indigoxela** [comment] 2019-11-29 12:57
Based on our findings and @herbdool's suggestion I've created a new pull request:
https://github.com/backdrop/backdrop/pull/3007

Regarding the failing test "Correct number of images (1) return 403 access denied" any hint is welcome. It passes on my local and passes with zenci with php70. Is this a random failure or really related to my PR?

This PR will need extensive testing with different types of fields an especially with text fields.

If this PR turns out to be the right approach, we need to figure out update handling. To my understanding existing field instance configs need to get updated to reflect the changed handling.

**Comment by herbdool** [comment] 2019-11-29 15:32
@indigoxela thanks! Your variation is even better than what I was thinking. I think we can rerun the tests to see if that helps the failing test - I would assume it's just random but you never know.

I tested with a bunch of fields and it seems to work well enough. I would imagine that since the original commit was recent that the previous behaviour still works well.

I'm not sure if field instance configs need updating, do they? If the defaults are blank this PR will work fine and if they're set they aren't affected.

**Comment by indigoxela** [comment] 2019-11-29 16:28
> we can rerun the tests to see if that helps the failing test

OK, another test with the other php version failing, that one's for sure unrelated. :wink: 

> I'm not sure if field instance configs need updating...

I think we should at least take care of number fields. The previous change has been merged in April. Does anyone know, when this change has been released?
All number field settings created (or updated) in that time span are affected by a fatal error on first node save, when value is empty. The code change alone won't fix that, as the previous setting is still active.

Are there other opinions?

The string field types simply save empty values, but mysql doesn't choke on that.

**Comment by herbdool** [comment] 2019-11-29 16:58
I assumed that saving the node was impossible with that fatal error and thus no empty number fields saved.

**Comment by herbdool** [comment] 2019-11-29 17:15
I looked at my local site where I attempted to save empty values to blank integer fields and failed. Nothing gets saved to db. And if I attempt to change a value in the db so it's and empty string and then edit the node I get the fatal db error in my mysql editor so I guess I can't recreate the issue.

I think it unlikely that people will have bad data.

**Comment by laryn** [comment] 2019-12-03 21:07
There's a "Works for me" on a separate thread:
https://github.com/backdrop-contrib/fivestar/issues/13#issuecomment-561149544

**Comment by quicksketch** [comment] 2019-12-05 23:09
https://github.com/backdrop/backdrop/pull/3007 looks great. Nice job @indigoxela!

However, this issue points to a clear deficiency in our tests that number fields cannot be saved prior to this fix. We need a test that covers creating a number field and then saving it, with and without a value.

**Comment by indigoxela** [comment] 2019-12-06 13:41
> We need a test that covers creating a number field...

Sure, we should ... But I have no clue, how to test for that.

The existing field tests work with test_entity and test_bundle (simple stub entities). I've spent quite some time now to figure out, how to reproduce the Exception in a TestCase when this PR patch is not applied. No chance so far. I'd be glad if someone takes over.

While digging, I came across an [interesting TODO comment](https://github.com/backdrop/backdrop/blob/9d73493ba92c6e5e049e61cc424fbb9b0a09e5a7/core/modules/field/modules/field_sql_storage/tests/field_sql_storage.test#L111)
That's somewhat related to our current problem.

**Comment by indigoxela** [comment] 2019-12-06 13:47
My opinion is that this bug fix should go into the next release, regardless of an existing test. It's important to fix the Exception problem. A test could be a follow-up issue, if no one manages to create one until then.

**Comment by herbdool** [comment] 2019-12-06 14:40
@indigoxela @quicksketch I tried to create a failing test too. No luck! It happily accepts a blank string. I also tried setting it to NULL and get `FAIL: Failed to set field tlyynmqi[und][0][value] to` in my test. Not sure if that's creating the error or not.

@indigoxela can you post a PR of your test so we can see how you created it?

**Comment by indigoxela** [comment] 2019-12-06 14:47
@herbdool It's not worth a commit...

I played with this and some variants:
```
    // Submit an empty value to make sure, the entity gets saved without exception.
    $this->backdropGet('test-entity/add/test-bundle');
    $edit = array(
      "{$this->field['field_name']}[$langcode][0][value]" => '',
    );
    $this->backdropPost(NULL, $edit, t('Save'));
    preg_match('|test-entity/manage/(\d+)/edit|', $this->url, $match);
    $id = $match[1];
    $this->assertRaw(t('test_entity @id has been created.', array('@id' => $id)), 'Entity with empty value was created');
```
Then I tried my luck with field_test_create_entity() or field_attach_insert()... no luck.
Maybe things work as expected, if we do it in a more realistic way (backdropCreateContentType, field_create_field, field_create_instance, create a user, log in that user...) Not sure.

**Comment by herbdool** [comment] 2019-12-06 14:53
@indigoxela I also got this to pass:

```
  /**
   * Test blank number fields.
   */
  function testBlankNumberFields() {
    $this->backdropLogin($this->web_user);

    // Add an integer field to the page content type.
    $label = $this->randomName();
    $field_name = backdrop_strtolower($label);
    $edit = array(
      'fields[_add_new_field][label]'=> $label,
      'fields[_add_new_field][field_name]' => $field_name,
      'fields[_add_new_field][type]' => 'number_integer',
      'fields[_add_new_field][widget_type]' => 'number',
    );
    $this->backdropPost('admin/structure/types/manage/page/fields', $edit, t('Save'));

    // Create post with summary but empty body.
    $edit = array(
      "title" => $this->randomName(),
      "field_{$field_name}[und][0][value]" => '',
    );
    $this->backdropPost('node/add/page', $edit, t('Save'));
    $node = $this->backdropGetNodeByTitle($edit['title']);
    //debug($node, 'node');

    $this->assertIdentical($node->{"field_$field_name"}, array(), 'Page with a blank number field has been submitted.');
  }
```

It seems like it might be more realistic, but still can't get it to fail.

**Comment by docwilmot** [comment] 2019-12-06 15:27
> It seems like it might be more realistic, but still can't get it to fail.

Just curious: what would be the expected "fail" here, if the PR is meant to fix the fact that empty values fail?

**Comment by herbdool** [comment] 2019-12-06 15:31
@docwilmot there is something wrong with the testing structure. The sample tests above should fail but they are actually passing. Note that is when testing with the current Backdrop release, i.e. *not* with the PR that fixes the fatal error.

**Comment by indigoxela** [comment] 2019-12-06 15:35
@docwilmot it should throw an exception like it does in "real life".
Something like:
`$this->assertNoText('Exception', "No database exception")`
...should fail.
`$this->assertRaw(t('test_entity @id has been created.', array('@id' => $id)),...`
...should fail.

We can't seem to produce the db exception in our test cases. That the entity/node get's created regardless of the field problem is ok - that also happens in real life. But the test shouldn't indicate success.

**Comment by docwilmot** [comment] 2019-12-06 16:12
> Note that is when testing with the current Backdrop release

Ah got it. Strange. Does it fail also when not specifying an empty string? 
```
    $edit = array(
      "title" => $this->randomName(),
    );
```

**Comment by docwilmot** [comment] 2019-12-09 03:52
Had a long look at this, and I'm wondering if there is a problem with our field data filtering generally. Try this if you could please: In a D7 site add a couple field types to a node type, then create a node of that type with all the fields blank, and check your DB. I'm seeing that D7 does not save any data to the `field_data_field_whatever` tables but backdrop does; Backdrop save blank data. I'm thinking the reason why a blank number field causes the error here is because its the only one that requires a non-string data type. 

If this is the case, we probably need to be fixing that rather than just making number fields behave.

Cant explain why Simpletest passes. Maybe Simpletest tables use string fields?

**Comment by indigoxela** [comment] 2019-12-09 07:11
>  Backdrop save blank data

Yep, that's exactly what my PR addresses. In https://github.com/backdrop/backdrop/commit/c0cd5a3852ce39bd1fafa9e9463e4687e395faf9 an "if" clause has been added, which skips filtering when there's no `$entity` - which applies not only when a default setting is saved, but also when a new node is saved ($entity hasn't been created yet, so it's empty).

The PR reverts this general filter skip and only saves blank data for text fields, if there's a _format_ set. So the filter format is retained for both, default setting and individual node fields. That's what the previous change tried to address, but in a too general way.

**Comment by indigoxela** [comment] 2019-12-09 12:56
I'm not getting any closer than this: https://github.com/backdrop/backdrop/pull/3007/commits/23d282eb1690d8a0521e57b4c17759999f450031

At least I'm able to check for the `$config` (it's the array with released Backdrop code and NULL after my PR is applied (and it also was before the previous change back in April)).

For completeness, if anyone want's to experiment with it - this is the code I didn't commit because it never returns anything but friendly "200 OK".
```
    $node_user = $this->backdropCreateUser(array('bypass node access'));
    $this->backdropLogin($node_user);
    // Save the same empty value in a node entity.
    $this->backdropGet("node/add/{$bundle}");
    $this->backdropPost(NULL, $edit, t('Save'));
    $this->assertResponse(200, 'Post to create new node with empty number value returned 200 OK');
```

**Comment by indigoxela** [comment] 2019-12-09 14:19
Wow, I was that close already with my previous commit. Re-reading my own code I realized that node needs a title, of course.
Finally I can reproduce the exception in my test case. (I've never been so happy to see an exception.)

**Comment by herbdool** [comment] 2019-12-09 20:16
This looks great now. Thanks @indigoxela! It's got a test for testing empty values in number fields. Without the fix it fails as expected and the test passes with the fix.

**Comment by quicksketch** [comment] 2019-12-30 21:08
Thanks everyone for the collaboration to get this issue fixed! I've merged https://github.com/backdrop/backdrop/pull/3007 into 1.x and 1.14.x.

**Closed** 2019-12-30 21:07 UTC
Labels: milestone candidate - bug, pr - ready to be committed, pr - works for me, status - has pull request, type - bug report

**Comment by klonos** [comment] 2020-01-12 23:15
...a bit late to the party, but thanks @indigoxela 👍 

...and FTR, I have tested this, and we have not regressed #3378, so 👍 again 🙂
