### ISSUE TITLE
[UX] CKEditor: Allow to browse and enter links of local paths (content, users etc.).

### ISSUE THREAD

**Issue by jdanthinne** [backdrop/backdrop-issues#1206] opened 2015-09-16 08:40 UTC
Wouldn't it be nice to have an option to choose an internal page/content/view/whatever when using Link in the CKEditor (see the CKEditor Link, or LinkIt modules)?

---
PR by @docwilmot: https://github.com/backdrop/backdrop/pull/1779

**Comment by quicksketch** [comment] 2015-09-16 19:21
Yes, absolutely. I think this is a good feature request. The LinkIt module looks pretty interesting and is something we could do fairly easily. Let's brainstorm some ideas about how we would like this to work.

The Image and Link dialogs in CKEditor are serving up native Backdrop forms, which means they are form_alterable and changeable just like any other form in Backdrop.

**Comment by klonos** [comment] 2015-09-16 20:28
...better title.

I'm positively certain that this was discussed while getting the rich text editor and link modules in core and we agreed that it was a feature to be added. We simply did not file an issue for it. Thanx for doing that @jdanthinne :+1:

**Comment by jdanthinne** [comment] 2015-09-19 06:03
And what would be awesome (and would get rid of IMCE) is the ability to select a file, either by implementing the same behavior as images (add an option to upload a file and link to it), or even selecting previously uploaded files (can add that as a third option for images as well: URL / Upload / Browse).

**Comment by docwilmot** [comment] 2017-02-03 05:37
PR to address this issue. I think the files links should be dealt with using the image browser plugin when it lands.

**Comment by olafgrabienski** [comment] 2017-02-03 10:26
Thanks for the PR! Had a first look at it and was surprised to see a lot of internal administrative links when I put in an external URL:

![screen-backdrop-pr-1779-add-link](https://cloud.githubusercontent.com/assets/14188307/22587383/c3f8833c-ea01-11e6-8009-9940e0d7629a.png)

Would that be more easy to handle technically when we have two inputs - one for internal and one for external links?

Even without the external link issue, I guess the amount of administrative links could distract editors when they just want to link to classical content (pages, posts). Are the link proposals supposed to get reduced based on permission?

**Comment by docwilmot** [comment] 2017-02-03 13:41
😄 a very silly mistake by me. Should be fixed.

**Comment by olafgrabienski** [comment] 2017-02-03 15:31
:-) Looks good now, thanks!

Another suggestion: Let's add some help text below the input, for example:

`Start typing to find content or paste a URL.`

**Comment by olafgrabienski** [comment] 2017-02-03 15:34
As the PR is a great usability improvement, I'd suggest to tag it for a upcoming release once it's RTBC.

**Comment by docwilmot** [comment] 2017-02-03 15:57
I've tagged for 1.7 and asked for a review as well.
But still not quite fixed though. I just realised that I should exclude admin Views from the search results; its unlikely anyone will be linking to those in content.

**Comment by Dinornis** [comment] 2017-02-08 17:26
Thanks for the PR @docwilmot, few thoughts:

* Change the title of the modal window to `Insert/edit link`
* Change text on button to `Add Link`
* Add text above the URL field something like _Enter the destination URL or title of content_
* I am concerned about all users being able to scan for site user names (IDs) without the admin being able to disable this.

**Comment by docwilmot** [comment] 2017-02-08 18:21
> Change the title of the modal window to Insert/edit link
Change text on button to Add Link

This modal and button already exists. I just added autocomplete to it. 

> Add text above the URL field something like Enter the destination URL or title of content

I agree this text could change

> I am concerned about all users being able to scan for site user names (IDs) without the admin being able to disable this.

The autocomplete query includes an access check.

**Comment by olafgrabienski** [comment] 2017-02-09 21:53
> Add text above the URL field something like "Enter the destination URL or title of content"

I like "Start typing to find content or paste a URL." (from the Drupal Linkit module) for the help text.

**Comment by olafgrabienski** [comment] 2017-02-09 22:26
> The autocomplete query includes an access check.

@docwilmot I just wanted to check this with a test user and created one with editorial permissions. When I try to add an internal link with that user, the autocomplete doesn't work for the normal published pages.

**Comment by quicksketch** [comment] 2017-04-10 03:12
The test sandbox works great. This seems to be a pretty useful improvement IMO, especially for small sites that have a limited amount of content. Larger sites I've seen have the usefulness of autocomplete limited by the number of posts that all have the same title. I left a fair amount of feedback in the PR: https://github.com/backdrop/backdrop/pull/1779

A few general questions we can ask here:

- Should we include Layouts in the list of autocompletes, just like Views?
- This supports Nodes, Users, Terms, and Views (thus far). How should we handle non-core entity types? Should we worry at all or work to iterate on that capability later?

>  Add text above the URL field something like "Enter the destination URL or title of content"

I think using an `#placeholder` would be appropriate here as well. Perhaps something like `e.g. About or /about`.

**Comment by olafgrabienski** [comment] 2017-04-10 07:51
> Larger sites I've seen have the usefulness of autocomplete limited by the number of posts that all have the same title.

The limitation could be mitigated by displaying additional information. See the Drupal [Linkit module](https://www.drupal.org/project/linkit) as an example which displays author and creation date by default:

![screen-drupal-8-linkit](https://cloud.githubusercontent.com/assets/14188307/24851113/c9ec990e-1dd2-11e7-9107-1f447e9ff59c.png)

Nice: it's possible to change the default "Suggestion metadata" using tokens:

![screen-drupal-8-linkit-configure-metadata](https://cloud.githubusercontent.com/assets/14188307/24851199/1da3c720-1dd3-11e7-8048-945b5620094c.png)

**Comment by olafgrabienski** [comment] 2017-04-10 07:57
@docwilmot Did you have a chance to have a look at access questions regarding the test user with just editorial permissions? See https://github.com/backdrop/backdrop-issues/issues/1206#issuecomment-278794728.

**Comment by docwilmot** [comment] 2017-04-10 16:59
@olafgrabienski I havent looked at that issue yet. Will check soon. You're suggesting that a user who has access to view unpublished nodes still doesnt see these nodes in the autocomplete?

Also I did look at Linkit for inspiration, but they use a custom autocomplete thing which would be a bit overkill for core.

**Comment by olafgrabienski** [comment] 2017-04-10 20:27
@docwilmot Don't know, let me try to explain better: I created a "Test editor" role on the sandbox site including related permissions (even "Bypass content access control" and "Administer content"), created a user account and provided it with editor role. Then I logged in as the editor user and tried to create an internal link in CKEditor. Typing in the names of the existing pages, the autocomplete doesn't show any suggestion. (But I'm able to type a path like `/test-page` manually and save the link.)

I guess there is an access issue which prevents the editor user to get autocomplete suggestions. Or did I miss to check a relevant permission for the editor role? Didn't find anything related in the permissions though.

Re Linkit, thanks for your feedback, I see! Can't judge the technical overkill aspects, and I'll be already happy to get the current link dialog changes in core. On the other hand, the editor is very important from the end user's perspective, so it might be worth to improve the link dialog even more; have to think about it and will perhaps open a separate issue.

**Comment by klonos** [comment] 2017-04-11 09:36
> - Should we worry at all or work to iterate on that capability later?

Would be good to get this in for 1.7.0. Follow-up issue would suffice 😉

**Comment by klonos** [comment] 2017-04-11 09:39
> The limitation could be mitigated by displaying additional information. See the Drupal [Linkit module](https://www.drupal.org/project/linkit) as an example which displays author and creation date by default:

I also like the metadata option (especially now that token is in core.)

**Comment by quicksketch** [comment] 2017-04-16 20:27
The PR looks good from a code-standpoint. We could take this further as far as expanding it's capabilities (e.g. additional styling, tokens, and support for other types of entities). However it's a great start. I'm marking this RTBC; if we have any concerns, please move back to needs work/review.

**Comment by docwilmot** [comment] 2017-04-16 23:15
Great!
Re styling, I had filed https://github.com/backdrop/backdrop-issues/issues/2517 earlier. I think we should fix that before committing this; I think that is a bug with the auto complete dropdown. 
Re other entities, I don't think a genetic solution that includes any and every entity label here would be wise. We'd probably need to provide a hook.

**Comment by olafgrabienski** [comment] 2017-04-17 12:30
@quicksketch @docwilmot I'm not sure if the PR should already be tagged as RTBC. As mentioned in https://github.com/backdrop/backdrop-issues/issues/1206#issuecomment-278794728 and https://github.com/backdrop/backdrop-issues/issues/1206#issuecomment-293068688, I have the impression that there is an access issue with the dropdown when not logged in as a admin user. Looking forward to get feedback on it!

@klonos - maybe you wanna try to reproduce? https://github.com/backdrop/backdrop-issues/issues/1206#issuecomment-293068688

**Comment by docwilmot** [comment] 2017-04-17 12:46
@olafgrabienski this was addressed and fixed. There was a faulty permission string.

**Comment by olafgrabienski** [comment] 2017-04-17 13:07
@docwilmot Oh, hadn't noticed it! Tested it again, all fine now, thanks a lot for addressing and fixing the issue!

**Comment by bd0bd** [comment] 2017-04-18 19:10
Dear people, why nobody answer my dear post here?:
https://github.com/backdrop/backdrop-issues/issues/2613

**Comment by docwilmot** [comment] 2017-04-18 19:19
For me often it is because you write cryptic posts with insufficient information.

**Comment by bd0bd** [comment] 2017-04-19 05:57
I am sorry. I will try to do it in better way.

**Comment by olafgrabienski** [comment] 2017-04-20 15:21
> Re styling, I had filed #2517 earlier. I think we should fix that before committing this; I think that is a bug with the auto complete dropdown.

@docwilmot I guess I'm not able to fix #2517! I just saw that there hasn't been any activitiy for a long time. I'd like to use the local links browser anyway, do you think we really have to wait?

**Comment by quicksketch** [comment] 2017-04-20 20:02
I do think we should fix the styling before merging this, so I'm marking this postponed until https://github.com/backdrop/backdrop-issues/issues/2517 is completed. We should always have the latest code be shippable, and bringing that styling issue to the forefront would be unacceptable (IMO).

**Comment by jenlampton** [comment] 2017-04-21 18:47
I took a stab at https://github.com/backdrop/backdrop-issues/issues/2517 to fix the styling and have that about wrapped up. (There's one bit left I need some jQuery help with.)

**Comment by quicksketch** [comment] 2017-04-23 01:01
Sorry we found a few more issues here, so bumping back down.

While working on #2517 we found that Layouts seems to match every possible string. The "home" layout is always shown for example.

Also, perhaps we should limit the display of the list to 10 items max in all situations? Right now it limits it to 10 *each* of content, terms, users, and layouts. Once we have more than 10 items, we should skip further queries for efficiency and trim the list down to 10 before delivering back to the browser.

**Comment by docwilmot** [comment] 2017-04-23 14:18
Oops and sorry. Fixed.
Also added a description and placeholder on the autocomplete textfield.
And added an `alter()` hook for modules to add to the autocomplete list. At least other entities can inject their titles into the list where appropriate.

**Comment by serundeputy** [comment] 2017-04-23 14:41
This looks great and works great!
Thanks @docwilmot 

The only thing I don't like is the placeholder text in the URL:

```php
'#placeholder' => t('/my-path or Some Text'),
```
![screen shot 2017-04-23 at 10 39 19 am](https://cloud.githubusercontent.com/assets/6763671/25314412/48e2f382-2811-11e7-8635-02f82b9b8083.png)

I find it to be repetitive of the description text.  That beings said I don't want to hold these two issues up over it either.  I'm fine with merging as is or taking it out, but let's not bikeshed over it :)

**Comment by docwilmot** [comment] 2017-04-23 14:43
Agreed that its redundant. I actually removed it and then added it back before pushing. Removing again.

**Comment by docwilmot** [comment] 2017-04-23 14:46
Its gone.

**Comment by serundeputy** [comment] 2017-04-23 14:49
Thanks! Great work!
Marking as RTBC.  I'll work on merging #1206 and #2517.

**Closed** 2017-04-23 15:04 UTC
Labels: pr - reviewed & tested by the community, status - has pull request, status - postponed, type - feature request

**Comment by serundeputy** [comment] 2017-04-23 15:06
Great wokr everyone!
This is merged into `1.x` and will ship with `1.7`. 💯

**Comment by quicksketch** [comment] 2017-04-23 18:30
Yay, awesome! Thanks @docwilmot and @serundeputy for taking this to the finish! Many thanks to @olafgrabienski, @Dinornis, and @klonos for the feedback and reviews!
