### ISSUE TITLE
Layout wildcard paths dont load entity contexts properly

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#5145] opened 2021-08-10 00:20 UTC
Related to https://github.com/backdrop/backdrop-issues/issues/5065.

1. Go to Add layout. Pick any name and template.
2. Set the path to foobar/%.
3. Set the context type to Node.
4. Click "Create Layout."
5. Click "Configure Layout" tab.
6. Click "Add visibility condition"
7. Select visibility condition of "Node: Type".
8. Select a node type, e.g., "Page".
9. Click "Add visibility condition".
10. Click "Save Layout".
11. This produces a form error: "The condition 'Type is <em class="placeholder">Page</em>' does not have the required contexts at this path. Remove the condition to save the layout."

This is because the context is determined by the path but `layout_context_required_by_path()` doesnt handle that situation.

That form error really shouldnt happen I think. If you define a path and tell Layout that the wildcard represents an entity ID, then layouts should provide the entity context, I think. So I'm thinking that in `layout.admin.inc` function `layout_settings_form_validate()` we could add any wildcard entities like:
```
  $contexts = layout_context_required_by_path($path);
  foreach ($contexts as $context) {
    $context_plugins[] = $context->plugin;
  }
  // Add any plugin from a wildcard path.
  // E.g. if you selected Node context from the dropdown, for your custom path foo/% 
  // then $dropdown_plugin_choice would be 'node'.
  $context_plugins[] = $dropdown_plugin_choice;
```

Not sure if my logic is sound here (not the code, thats pseudocode still). @quicksketch any thoughts?

**Comment by quicksketch** [comment] 2021-08-10 01:02
@docwilmot I think you're right. We should leave `layout_context_required_by_path()` as it is, since it's used to identify special built-in paths like `node/%`. And `layout_context_required_by_path()` shouldn't be used as the validation (or perhaps should be used in addition the validation you describe).

**Comment by jayelless** [comment] 2021-08-22 05:44
@docwilmot This issue is a duplicate of [#5082](https://github.com/backdrop/backdrop-issues/issues/5082). I had a working solution for fixing the issue, but your suggestion above has allowed me to improve my solution.  A pull request for the improved solution has now been created against issue #5082.  Closing this one in response.

**Closed by jayelless** 2021-08-22 05:44 UTC
Labels: type - bug report
