### ISSUE TITLE
Notice: ob_end_flush(): failed to delete and flush buffer. No buffer to delete or flush in backdrop_page_footer()

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5594] opened 2022-04-25 09:59 UTC
## Description of the bug

This shows up recently in Tugboat demos, but is also reproducible elsewhere - depending on ini settings.

```
Notice: ob_end_flush(): failed to delete and flush buffer. No buffer to delete or flush in backdrop_page_footer() (line 3183 of /var/lib/tugboat/core/includes/common.inc).
```

## Steps To Reproduce

1. Set php output_buffering to `0` or `Off` (reload services as needed)
2. Visit any page

Warnings about ob_end_flush() once for every page call.

## Additional information

This affects the latest dev of Backdrop core. Not the stable release.
It seems to get caused by the changes to ob_end_flush(); when raising the minimum required PHP version in https://github.com/backdrop/backdrop/pull/3922/files

<s>Adding the error control character back in function backdrop_page_footer() silences the nagging - but does it fix the actual problem?</s>

I'm not sure how common it is to turn output_buffering off in php.

This issue is sort of a follow up to #3992

**Comment by indigoxela** [comment] 2022-04-25 11:22
Looking at the removed comment with a slightly fresher mind: 
```
      // End the request and send the response to the browser. This call has
      // error suppression on it as some PHP versions may require it (PHP 5.3)
      // but other PHP versions throw a warning (PHP 5.5).
```

> has error suppression on it as some PHP versions may require it (PHP 5.3)
> but other PHP versions throw a warning (PHP 5.5).

This ob_end_flush() *exists* here because old PHP needed it.
Newer PHP still throw warnings.

So the fix here seems to **remove** ob_end_flush(), as it's now obsolete, anyway. - Did I read that correctly?

A quick check with ob_get_length() in function backdrop_page_footer() shows that this buffer is always empty when buffering is turned on. Also note: I see no corresponding ob_start(). So, this flushing seems safe to remove.

**Comment by indigoxela** [comment] 2022-04-25 11:30
Some lines above ob_get_clean() is called, which explains the empty buffer here.

A [PR](https://github.com/backdrop/backdrop/pull/4051) is available for review - there's not much to test. Maybe verify, that the nagging is gone.

**Comment by olafgrabienski** [comment] 2022-04-25 13:13
> not much to test. Maybe verify, that the nagging is gone

Confirmed, the nagging disappeared in the PR's sandbox site (in contrast to older PRs where it is still there).

**Comment by quicksketch** [comment] 2022-04-27 00:58
> Also note: I see no corresponding ob_start(). So, this flushing seems safe to remove.

Backdrop starts the output buffer in `_backdrop_bootstrap_page_header()` and closes it in `backdrop_page_footer()`.

There's similar code in `_backdrop_bootstrap_page_cache()`, where both `ob_start()` and `ob_flush()` are used to deliver cached responses.

In the case of a cached page, we're not using `ob_get_clean()`. So `_backdrop_bootstrap_page_cache()` should remain as it is using `ob_end_flush()`. I believe @indigoxela is correct that we _don't_ need it in `backdrop_page_footer()`, because we've already emptied the output buffer using `ob_get_clean()`.

All that is to say, I think https://github.com/backdrop/backdrop/pull/4051 is the correct approach.

**Comment by quicksketch** [comment] 2022-05-01 00:29
I merged https://github.com/backdrop/backdrop/pull/4051 into 1.x for 1.22.0. Thanks @indigoxela!

**Closed** 2022-05-01 00:28 UTC
Labels: type - bug report, status - has pull request, pr - needs code review, pr - works for me
