### ISSUE TITLE
Fields with multiple values get two values by default

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4126] opened 2019-10-12 14:02 UTC
While working on #3520, I've noticed that the screenshots from back in Feb 2019 showed only a single value for multi-value fields:

![screen shot 2019-02-01 at 4 08 13 pm](https://user-images.githubusercontent.com/1234634/52156505-61f7c880-263d-11e9-9df1-a99e0c8ad329.png)

Something must have changed between then and now, because now all multi-value fields get 2 values by default:

![Screen Shot 2019-10-13 at 1 12 33 am](https://user-images.githubusercontent.com/2423362/66702740-a738d200-ed56-11e9-967e-270cef6fe49f.png)

Unless this was intentional, this is a bug.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2933

**Comment by hosef** [comment] 2020-03-07 23:07
@klonos I tried to review this, however when I tested on my local environment it only showed me one field by default for a field with unlimited values.
I think this may have been fixed in another issue since this one was created. Could you see if you can still reproduce the behavior?

**Comment by BWPanda** [comment] 2020-08-10 02:41
I also can't reproduce this. Closing as 'cannot reproduce', but feel free to re-open @klonos with updated STR if necessary.

**Closed by BWPanda** 2020-08-10 02:41 UTC
Labels: milestone candidate - bug, pr - needs code review, pr - needs testing, status - has pull request, type - bug report
