### ISSUE TITLE
Add the complete file path to the manage file form.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4175] opened 2019-10-30 20:11 UTC
When I'm managing my files, I really want to know the file name (not the human-readable label we already show in the form, but the actual name of the document on disk). I also sometimes wonder where that file is stored, because I'd like to test it directly in my browser. We don't reveal any of this information to the user, and it seems both are a valuable part of managing files.

I'd like to propose the following improvements to the Manage File form:
* ~Change the label of the "File name" element to indicate this is a label~
* Change the vertical tab heading for "Destination" to "File location"
* Display the complete file path in the "File location" vertical tab. 
* The filepath field should be read-only and not allow changes

Screenshot:
<img width="1208" alt="Screen Shot 2019-10-30 at 1 55 35 PM" src="https://user-images.githubusercontent.com/397895/67898142-fe8fbe00-fb1c-11e9-9870-c0b995c6b46c.png">

~I went with "File link text" in the screenshot (and first PR) but am open to recommendations on what to call the human-friendly name for a file~

~I went with `Description` as the label for that field, since that is what we are calling the same thing in other interfaces. See https://github.com/backdrop/backdrop-issues/issues/4178 for better text to use there.~

---
PR: https://github.com/backdrop/backdrop/pull/2960

---

Translation updates:
* "Destination" replaced with "File location"

**Comment by laryn** [comment] 2019-10-30 20:21
Is what you refer to as "File link text" the same thing as what is called "Description" elsewhere in the UI?

![Screen Shot 2019-10-30 at 3 20 54 PM](https://user-images.githubusercontent.com/871421/67895662-e32ab000-fb28-11e9-8330-462c4594ccba.jpg)

**Comment by jenlampton** [comment] 2019-10-30 20:24
Yes, according to that description text. But I think "Description" is an even worse label for it!

**Comment by jenlampton** [comment] 2019-10-30 20:25
@laryn where did you find that UI? I just added a file field to a node and it's not there...

**Comment by laryn** [comment] 2019-10-30 20:35
I suppose using what is already used elsewhere makes sense here, and then opening a separate issue to suggest that we change that descriptor throughout, if it's no good?

Separately, this thread is related:
https://github.com/backdrop/backdrop-issues/issues/3904

**Comment by jenlampton** [comment] 2019-10-30 20:44
> I suppose using what is already used elsewhere makes sense here, and then opening a separate issue to suggest that we change that descriptor throughout, if it's no good?

Yep, good idea. Will use Description here now, and I'll add the description text I like too :)

**Comment by klonos** [comment] 2019-10-30 21:54
Thanks @jenlampton 👍 ...I wouldn't mind holding off until we've made a decision in #4178 and got this all in one go ...I think we'll reach a decision soon 😉

**Comment by klonos** [comment] 2019-10-30 22:24
...I've left comments in the PR. I love this ❤️ ...just minor tweaks implementation-wise; is all.

**Comment by klonos** [comment] 2019-12-07 16:06
Hey @jenlampton ...I wanted to git this a go, but the PR sandbox doesn't seem to work, and there seem to be conflicts (after merging of #4178 I guess). Can you please resolve the conflict, and make sure that the sandbox works? ...if not, then perhaps try closing the PR and reopening it 🙂 

![It Crowd - Try turning it off and on again](https://user-images.githubusercontent.com/2423362/70377345-a643ab80-1967-11ea-9ec3-536d63da5d52.gif)

**Comment by herbdool** [comment] 2021-12-30 18:28
I think this looks good. I resolved the conficts on the PR. And reviewed/tested.

**Comment by laryn** [comment] 2022-01-13 18:25
Did this one get closed without merging as well @jenlampton 
https://github.com/backdrop/backdrop/pull/2960

**Comment by quicksketch** [comment] 2022-01-15 01:56
Yeah, @jenlampton I think you need to re-push this branch? Also I think there's a missing check_plain(): https://github.com/backdrop/backdrop/pull/2960#discussion_r785254206

**Comment by jenlampton** [comment] 2022-01-15 02:30
huh. I wonder what happened to all my branches? Anyway - I added the `check_plain()` and pushed my branch back up.

**Comment by klonos** [comment] 2022-01-15 11:22
Some feedback:
- I'm not sure if the addition of the read-only field for "Filename" provides any actual value 🤔  (we already display that as part of the page title).
- Since the filename cannot be edited, perhaps we could follow the same UI pattern as the machine name, and display it similarly next to the description field?
- Should the "File URL" be linkified?

**Comment by klonos** [comment] 2022-01-15 11:32
> - Since the filename cannot be edited, perhaps we could follow the same UI pattern as the machine name, and display it similarly next to the description field?

Never mind ...just found out that we have a similar UI pattern for the language configuration form:

![image](https://user-images.githubusercontent.com/2423362/149620237-7e5ccca9-85e3-4b23-9ee8-b67abe4fe502.png)

**Comment by quicksketch** [comment] 2022-01-27 06:10
@jenlampton Sorry! I think there's one more place that needs a `check_plain()`: https://github.com/backdrop/backdrop/pull/2960/files#r793279222

**Comment by jenlampton** [comment] 2022-03-24 02:01
I've merged your suggested change @quicksketch, this is back to RTBC.

**Comment by quicksketch** [comment] 2022-04-23 23:41
There's an accidental revert of some terminology in the PR: https://github.com/backdrop/backdrop/pull/2960#pullrequestreview-951134213

> Should the "File URL" be linkified?

I agree with this, seems weird to display a URL but not have it be clickable. However, that introduces a new UX problem where clicking the link may make any in-progress changes get lost. We could adjust the selector for the `Backdrop.behaviors.filePreviewLinks` behavior though to work both here and on file upload elements (where it's used currently).

**Comment by quicksketch** [comment] 2022-04-24 00:06
I filed a PR against @jenlampton's PR at https://github.com/jenlampton/backdrop/pull/15 that makes the URL clickable and reverts the terminology regressions. https://github.com/jenlampton/backdrop/pull/15

**Comment by stpaultim** [comment] 2023-12-26 22:02
I'm trying to help some old PR's reach the finish line. To get a sandbox this one needed to be rebased. I simply created a new PR that is up to date with current code base. https://github.com/backdrop/backdrop/pull/4619

We can work with mine or @jenlampton can replace her own with mine. 

This is what this page looked like before.

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/ca28437b-a626-4855-83fb-f0d512a26893)

This is what it looks like after PR.

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/87a9651e-3cd4-48d0-ab0c-88db6bee9b32)

Needs testing and code review.

**Comment by stpaultim** [comment] 2023-12-26 22:09
There is one test failure right now that looks like it is probably legit, I'm not sure I understand what is going on there. Can anyone help me with that?

**Comment by olafgrabienski** [comment] 2023-12-27 18:39
@stpaultim I've tested the new PR with a PDF file, and it looks good to me: The vertical tab looks like in your screenshot, the File URL is clickable and opens in a new small window.

**Comment by quicksketch** [comment] 2024-01-12 23:35
The changed code looks great, thanks @herbdool for coming in and fixing the use of `.on()` in the JavaScript.

There's a legit failing test across all versions of PHP:

```
Status    Group      Filename          Line    Function                            
------------------------------------------------------------------------------------------------------------------------
Fail      Other      file.test         1390    testNodeDisplay()                                                       
    Default formatter displaying correctly on full node view.
```

Looks like it just needs to be updated for the new markup created by this PR.

**Comment by herbdool** [comment] 2024-01-16 19:57
I fixed `file.test` and put it back to RTBC since the test was the only thing holding back.

**Closed** 2024-01-16 22:30 UTC
Labels: status - has pull request, status - fixed, needs - translation update

**Comment by quicksketch** [comment] 2024-01-16 22:33
Thanks @herbdool! I merged https://github.com/backdrop/backdrop/pull/4619 into 1.x and this is the first issue in the new 1.27.x branch to be fixed. Thanks @jenlampton, @stpaultim, @laryn, @olafgrabienski, and @klonos!
