### ISSUE TITLE
No hook exists to extract the complete list of messages on a page

### ISSUE THREAD

**Issue by alexhass** [backdrop/backdrop-issues#615] opened 2015-01-18 16:48 UTC
What is an alternative to attach something to the page now? I always used hook_page_alter() in Google Analytics and cannot find any alternative.

What is the very very latest hook that is available that allows backdrop_add_js() ? hook_preprocess_page() was too early in Drupal. backdrop_get_messages() does not give me the messages in hook_preprocess_page().

**Comment by quicksketch** [comment] 2015-01-18 23:43
Hi @yamlfd!

> What is the very very latest hook that is available that allows backdrop_add_js() ? hook_preprocess_page() was too early in Drupal.

In Backdrop, page.tpl.php renders much later than it did in Drupal 7. In D7, the *last* template was html.tpl.php. But because of the new Layout system, we no longer needed `page.tpl.php` at all. We then renamed `html.tpl.php` *back* to `page.tpl.php`, like it was in Drupal 6.

So in short, hook_preprocess_page() should be the last hook available before the page itself is rendered. It's later in Backdrop than it is in Drupal 7.

In that hook, you can tack on a string to the $page_bottom variable, or if adding JS, you can use drupal_add_js() with the scope of "footer".

**Comment by yamlfd** [comment] 2015-01-19 07:28
Thanks for info. Than we have here a bug. We need page_alter back. The problem is that the messages are not available in preprocess hook. This hook is not really late enough. I know you removed this hook, but this was a fault thereby.

**Comment by quicksketch** [comment] 2015-01-19 07:39
Why not just call `backdrop_get_messages()` directly to get the list of messages?

We can't add `hook_page_alter()` back, because the page renderable itself no longer exists. The entire page layout is controlled by Layout module now. Even if we added something back at the Layout layer, `hook_page_preprocess()` is called *after* the layout has been rendered. It's literally the last thing that happens before `page.tpl.php` is printed, so you're not going to find anything later.

**Comment by quicksketch** [comment] 2015-01-19 07:49
Oh, I just realized a different problem. I think `hook_preprocess_page()` is actually too *late*, rather than too early. In Backdrop, `hook_preprocess_page()` is literally the very last hook to be called before the page is rendered. However, the messages queue has already been cleared by the time it is called, because the layout is responsible for printing messages.

So if you want a list of all messages prior to the page rendering, you may need to get them during `hook_preprocess_layout()`, which happens just before the messages are rendered. After the layout is rendered, the entire thing is passed to the page template to be rendered.

It's different than Drupal 7, but generally speaking the way things map is as this:

- html.tpl.php is now page.tpl.php
- page.tpl.php is now layout--[suggestion-name].tpl.php

So if you want a list of messages prior to their rendering, use `hook_preprocess_layout()` and store the list using `backdrop_get_messages()` (or `backdrop_set_message()`).

**Comment by yamlfd** [comment] 2015-01-19 08:38
hook_preprocess_layout() only gives me an empty array.

print_r(backdrop_get_messages(NULL, FALSE));

**Comment by quicksketch** [comment] 2015-01-19 09:09
It looks like messages are emptied out in `template_preprocess_layout()`, which makes `hook_preprocess_layout()` too late to get the messages. So you're right, that hook is too late currently.

This is a bug, because it makes it pretty much impossible to get the list of messages on a page before they're printed out. To solve this problem in a fashion similar to other approaches in Backdrop, we'd move the call to `theme('status_messages')` into the layout.tpl.php file, so it's absolutely last.

Unfortunately, to do that we'll need to break the compatibility of the layout template files. Perhaps since we're so early, the damage would be minimal, but it sets a bad precedent.

As it stands now, the only work-around I can think of is looking in the `$variables['messages']` string for a list of messages in `hook_preprocess_layout()`. It's a string, so it's going to be pretty inconvenient to try and parse messages out of there, but for now I think that's the only approach available.

**Comment by yamlfd** [comment] 2015-01-19 12:55
Is there any good reason why you emptied the messages that early? Are we not able to keep them until all finishes?

Parsing html sounds not like an option to me. One feature less for now... Waiting for the fix I think.

I'd really like to use the very latest hook... That means I use hook_page_alter() and all messages need to be available there.

**Comment by quicksketch** [comment] 2015-01-19 19:58
> Is there any good reason why you emptied the messages that early? Are we not able to keep them until all finishes?

The messages empty out automatically when you call `theme('status_messages')`, so by printing the messages out, they get emptied. The intention is to print them out at the last moment, but Layout module is doing it too early, hence causing this problem.

> Parsing html sounds not like an option to me. One feature less for now... Waiting for the fix I think.

That's fair enough, we'll try to figure out the solution quickly.

**Comment by quicksketch** [comment] 2015-01-20 00:17
I filed a PR at https://github.com/backdrop/backdrop/pull/702 that should help this. We can't reintroduce `hook_page_alter()` because the page renderable itself no longer exists. This change should make `hook_prepreprocess_layout()` work for contributed modules because all messages will be retrieved *after* all other contributed modules have run, rather than getting the messages first. This will also allow other modules to use `backdrop_set_message()` or `backdrop_set_title()` in `hook_preprocess_layout()` and have it function correctly.

**Comment by quicksketch** [comment] 2015-01-20 02:26
Merged in https://github.com/backdrop/backdrop/issues/702. This will be in the 1.0.1 release tomorrow.

**Closed** 2015-01-20 02:26 UTC
