### ISSUE TITLE
Window scrolls when opening fieldset in a dialog

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3743] opened 2019-05-02 02:53 UTC
**Description of the bug**

When expanding/collapsing a fieldset within a modal dialog, the "Update block" button for the dialog can move outside of the visible window.

Also, when expanding/collapsing a fieldset within a modal dialog, the underlying page scrolls as the size of the dialog changes. (see gif below)

Resizing the window "fixes" the issue temporarily. GIF of the problem in action:

![Peek 2019-05-01 19-54](https://user-images.githubusercontent.com/100206/57054689-1314fb80-6c4b-11e9-9484-59b5dd8ea871.gif)

**Steps To Reproduce**
To reproduce the behavior:
1. Configure a block in the Layout UI
2. Open the "Styles" and set to "Dynamic" to make tall dialog.
3. Collapse "Styles" fieldset.
4. Scroll to top of window in the background.
5. Expand the "Styles" fieldset".

**Actual behavior**
The background of the window scrolls downward.

**Expected behavior**
The window scrolling should stay where it was when the dialog was opened.

**Additional information**
This is a different problem than the Views UI specific issue with dialogs at https://github.com/backdrop/backdrop-issues/issues/2426

---

PR https://github.com/backdrop/backdrop/pull/2639

**Comment by jenlampton** [comment] 2019-05-02 03:07
I hadn't noticed the scrolling, but on my computer `Worse, if the fieldset makes the dialog taller, the "Save" button for the dialog can move outside of the visible window.` happens ALL THE TIME. Does this PR fix that problem too?

**Comment by quicksketch** [comment] 2019-05-02 04:03
Yes, that problem is fixed as well. Fieldsets now trigger a window resize event, which re-centers/sizes the dialog after opening it.

**Comment by klonos** [comment] 2019-05-02 04:15
...wondering if this could be related: #2426

**Comment by klonos** [comment] 2019-05-02 04:20
I have tested this on the PR sandbox, and what happens now is that soon as a dialog opens, scrolling of the background is locked (also scrollbar removed). So there is no way to scroll the background any longer while a dialog is open.

Tested on latest Chrome on Mac, in case that matters.

**Comment by klonos** [comment] 2019-05-03 20:26
Something I have noticed in other PR sandboxes, is that when expanding the "More link options" fieldset (introduced in #1777) on the "Insert link" dialog, then the "Relationship (rel)" field is hidden below the viewport, and there is no way to scroll to it, or to click the "Save" button; unless you collapse the fieldset, in order to bring everything back into view:

<img width="534" alt="Screen Shot 2019-05-04 at 6 22 35 am" src="https://user-images.githubusercontent.com/2423362/57163752-66e33880-6e35-11e9-9ba8-66225f082952.png">

Can we please refresh the PR sandbox @quicksketch? ...that way, we'll be able to test if the PR is addressing issue like that as well.

**Comment by laryn** [comment] 2019-05-03 20:32
I see it too when checking the box to make it reusable and sometimes can't click save without making it not reusable.

**Comment by klonos** [comment] 2019-05-03 20:38
...and had I read @quicksketch's comment in https://github.com/backdrop/backdrop-issues/issues/1777#issuecomment-488531826, I wouldn't have mentioned the above 😅 ...still, a sandbox reresh would allow people to test things 😉

**Comment by klonos** [comment] 2019-05-10 21:18
The PR seems to have been closed by @jenlampton a few days back, with the intention to reopen it I imagine, but has remained closed (only the PR author can re-open I think). @quicksketch ??

**Comment by quicksketch** [comment] 2019-05-12 03:01
Thanks for the heads-up @klonos, I've reopened it.

**Comment by quicksketch** [comment] 2019-05-12 03:03
> I have tested this on the PR sandbox, and what happens now is that soon as a dialog opens, scrolling of the background is locked (also scrollbar removed). So there is no way to scroll the background any longer while a dialog is open. Not sure if that was the intended solution.

Yes, that's also a side-effect of the implementation. That's the best I could find to prevent this problem. Although I don't think the rest of the page is useful when the dialog covers everything up already.

**Comment by jenlampton** [comment] 2019-05-15 22:14
Bumping to 1.13.0 at @quicksketch 's request.

**Comment by klonos** [comment] 2019-05-15 22:18
I have just tested the PR sandbox, and the issue is fixed in the "Insert link" dialog 👍

**Closed** 2019-05-15 22:21 UTC
Labels: pr - needs code review, pr - works for me, status - has pull request, type - bug report

**Comment by quicksketch** [comment] 2019-05-15 22:22
Thanks @klonos and @jenlampton! This applies to 1.12.x as well, even though the problem is not as noticeable there. Merged https://github.com/backdrop/backdrop/pull/2639 into 1.x and 1.12.x.
