### ISSUE TITLE
Allow all valid characters (like underscores) in CSS classes in Views.

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#3428] opened 2018-12-13 14:18 UTC
Follow-up to https://github.com/backdrop/backdrop-issues/issues/3365

As @quicksketch mentioned:

> anywhere the user explicitly types in a class name we should allow all valid characters, using the same approach you included in your PR of passing in an empty array for the second parameter. Anywhere we have "automatic" class names (such as when we pass in the node type) should stick with the current behavior because otherwise class names are going to change all over the place where we pass in machine names.

...where "passing in an empty array for the second parameter" refers to using `backdrop_clean_css_identifier($class, array()`.

---
~PR: https://github.com/backdrop/backdrop/pull/2429~ (Merged and then reverted)
original PR again: https://github.com/backdrop/backdrop/pull/2446 
new PR: https://github.com/backdrop/backdrop/pull/2442

**Comment by stpaultim** [comment] 2018-12-14 04:56
Views is the obvious example of where we still need to make this change. In testing the previous PR (https://github.com/backdrop/backdrop-issues/issues/3365), I tested views and verified that it's still a problem there.

**Comment by quicksketch** [comment] 2018-12-31 19:56
I merged https://github.com/backdrop/backdrop/pull/2429, but then found a regression, so I reverted it again. Sorry about that! We'll need to make a new pull request.

The problem with the current PR is that Views first does token replacements (specialized Views tokens, like field value replacements) prior to any additional classes. So for example you might have a `[node_type]` token as a class name. If the node type was `blog_post`, previously would have had the class `blog-post` created. Now after this PR it will be `blog_post` with an underscore. The token replaced version should still have underscores converted, while the human-provided one should allow all valid characters.

**Comment by klonos** [comment] 2019-01-01 08:07
@jenlampton do you think perhaps add a helper function and use that instead of repeating the same bit of code again and again? We could be slightly more verbose in the helper function docblock to explain things (what @quicksketch explains in his previous comment).

**Comment by docwilmot** [comment] 2019-01-01 17:16
I'm missing the point sorry. Assuming *before* this PR a user had entered:
- `[node_type]` which resolved to `my_page`, we're saying change that to `my-page`, whereas,
- if they had typed in `my_page` dont change it?

Why? I think if we're going to allow all characters we should just do it, because either of those scenarios above will break something.

**Comment by jenlampton** [comment] 2019-01-01 18:31
> @jenlampton do you think perhaps add a helper function and use that instead of repeating the same bit of code again and again?

I was thinking that too...  will give it a go.

> I'm missing the point sorry [...] Why? [...] either of those scenarios above will break something.

True. @quicksketch will need to clarify what he was thinking here, but here's I was thinking when I agreed: 

When someone uses a token, they are after a class they can use, but they don't really care what comes out. When they type in something specific, they want exactly what they typed in to come out.

In terms of breaking existing sites, if someone had typed in something specific and it didn't come out how they wanted - they would have noticed, and might have changed what they put in. However, when using a token, they had no choice to change what went in.

I'm actually with @docwilmot on this one. The DX is much better with a single behavior. I  also think the likelihood of us breaking something is fairly low here, since these views replacements are not even listed as possible options for CSS selectors in the UI.

**Comment by herbdool** [comment] 2019-01-01 18:55
The current PR which was merged is not BC. Currently on a site the token gets converted to have a dash and that part needs to stay that way.

**Comment by jenlampton** [comment] 2019-01-01 19:03
@herbdool the new PR is not BC either. Currently on a site the manually entered class also gets converted to have a dash. Why does one part needs to stay that way, but the other doesn't?

**Comment by herbdool** [comment] 2019-01-01 19:06
@jenlampton see the very top comment. Yes, it breaks compatibility but it's manually entered by people. I agree with differentiating between automatic and manual.

**Comment by jenlampton** [comment] 2019-01-01 19:18
okay, so the answer to my question "Why does one part need to stay that way, but the other doesn't?" is...

> because otherwise class names are going to change all over the place where we pass in machine names.

I'm going to take a stab at the class-cleaning helper function @klonos recommended, for DX and sanity :)

**Comment by jenlampton** [comment] 2019-01-01 19:55
Okay - helper function added to PR: https://github.com/backdrop/backdrop/pull/2442 ready for another review.

**Comment by quicksketch** [comment] 2019-01-02 00:15
The current PR behaves a bit strangely. Now if a token is used, manual strings are not converted. For example if I entered a class of `node-type__[node_type] my-special-class__foo`, the resulting class would be `node-type--blog-post my-special-class--foo`. But if I typed in just `my-special-class__foo`, then the string would come out unmodified.

What we want here is for anything that was typed in to remain exactly as the user entered it. Any underscores that are present within tokens should be converted to hyphens to match the previous behavior.

**Comment by jenlampton** [comment] 2019-01-02 00:36
> The current PR behaves a bit strangely. Now if a token is used, manual strings are not converted.

It splits by class. I was testing by adding the two classes blog_post and [type]. In that case blog_post is not converted but [type] becomes blog-post. 

> For example if I entered a class of `node-type__[node_type] my-special-class__foo`, the resulting class would be `node-type--blog-post my-special-class--foo`. 

Actually, it would be `node-type--blog-post my-special-class__foo` since each class is tested individually.

> But if I typed in just my-special-class__foo, then the string would come out unmodified.

Yeah...  I thought that's what you wanted?

**Comment by herbdool** [comment] 2019-01-02 22:20
I tested final product. Looks good

**Closed** 2019-01-04 05:58 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2019-01-04 05:59
Looks great, thanks @herbdool for the great fix! I expanded the inline code comments slightly and merged https://github.com/backdrop/backdrop/pull/2442 into 1.x for 1.12.0. Thanks!
