### ISSUE TITLE
Configuration management throws errors if staging is empty

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#269] opened 2014-07-19 12:20 UTC
First off: thanks. I'm impressed with all the work you've done! I've been keeping tabs on Backdrop and we might use it for non-profit clients who don't have the budget to upgrade to Drupal 8.

I did a fresh install from the 1.x.zip file and I've been trying out the config management. I see a bug after importing staged config (I copied over the json files from active and made a small change in a views files).

```
Warning: array_map(): Argument #2 should be an array in ConfigFileStorage->listAll() (line 929 of /var/www/vhosts/backdrop.dev/httpdocs/core/includes/config.inc).
Warning: array_merge(): Argument #2 is not an array in config_get_statuses() (line 467 of /var/www/vhosts/backdrop.dev/httpdocs/core/modules/config/includes/config.admin.inc).
Warning: array_unique() expects parameter 1 to be array, null given in config_get_statuses() (line 467 of /var/www/vhosts/backdrop.dev/httpdocs/core/modules/config/includes/config.admin.inc).
Warning: array_fill(): Number of elements must be positive in config_get_statuses() (line 468 of /var/www/vhosts/backdrop.dev/httpdocs/core/modules/config/includes/config.admin.inc).
Warning: array_combine() expects parameter 1 to be array, null given in config_get_statuses() (line 468 of /var/www/vhosts/backdrop.dev/httpdocs/core/modules/config/includes/config.admin.inc).
Warning: ksort() expects parameter 1 to be array, null given in config_get_statuses() (line 497 of /var/www/vhosts/backdrop.dev/httpdocs/core/modules/config/includes/config.admin.inc).
Warning: array_filter() expects parameter 1 to be array, null given in config_sync_form() (line 12 of /var/www/vhosts/backdrop.dev/httpdocs/core/modules/config/includes/config.admin.inc).
Warning: array_map(): Argument #2 should be an array in ConfigFileStorage->listAll() (line 929 of /var/www/vhosts/backdrop.dev/httpdocs/core/includes/config.inc).
Warning: Invalid argument supplied for foreach() in config_get_modified_times() (line 510 of /var/www/vhosts/backdrop.dev/httpdocs/core/modules/config/includes/config.admin.inc).
```

I think it might be because the config files are removed from staging after the import. If I copy the config files from active into staging the errors go away.

**Comment by quicksketch** [comment] 2015-01-20 04:58
I haven't been able to reproduce this in testing. Since this was filed we added fairly comprehensive testing of config management, so I'm guessing this may have been solved back then. In any case, doing a full or partial import of configuration in the 1.0.0 version doesn't seem to display any problems. I'm going to close this one as it seems resolved, but please open again if the problem still happens. Thanks!

**Closed by quicksketch** 2015-01-20 04:58 UTC

**Comment by jenlampton** [comment] 2020-12-25 19:49
@herbdool I think I just stumbled across your first issue? How fitting that you just provided the option not to delete files from the staging directory in https://github.com/backdrop/backdrop-issues/issues/4447

**Comment by herbdool** [comment] 2020-12-26 18:34
Ha, you might be right @jenlampton! Has it really been six years already?
