### ISSUE TITLE
Label discrepancy on Login and Password pages

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#5653] opened 2022-06-16 10:13 UTC
## Description of the bug

Go to `/user/login` page to see `Username or email` label for the username field, switch to `user/password` page to see `Username or e-mail address` label for the same field.

## Expected behavior

Let's bring the label for this field to consistency for two pages.

**Comment by indigoxela** [comment] 2022-06-16 11:29
Nice little consistency fix! Many thanks @alanmels.

But there's one more place to fix: in user/user.admin.inc, that's the form on /admin/config/people/login. It still uses "Username or email address" (no hyphen).

**Comment by alanmels** [comment] 2022-06-16 17:22
Thanks for noticing another instance, made the change to https://github.com/alanmels/backdrop/blob/patch-13/core/modules/user/user.admin.inc

**Comment by indigoxela** [comment] 2022-06-17 06:45
Great, many thanks... but now, when I look at the admin form...

![email-hyphen](https://user-images.githubusercontent.com/842066/174240965-8462b869-c92d-4565-b0a9-77207d357a14.png)

There's e-mail and Email (no hyphen) pretty close to each other. For real consistency we probably need to fix that, too. @alanmels what do you think?

**Comment by indigoxela** [comment] 2022-06-17 12:04
Big oops, this overlaps - is actually partly contradictory - to an existing issue:

https://github.com/backdrop/backdrop-issues/issues/4521

Sorry, I wasn't aware of that older issue.

**Comment by BWPanda** [comment] 2022-06-17 12:15
Yep, this is a duplicate of https://github.com/backdrop/backdrop-issues/issues/4521, which has a PR that updates various spelling of 'email' in 46 different files in core.

**Closed by BWPanda** 2022-06-17 12:15 UTC
Labels: type - bug report, status - duplicate, status - has pull request

**Comment by indigoxela** [comment] 2022-06-17 12:40
> Yep, this is a duplicate

Not 100%, though, because @alanmels tries to unify the string "Username or **email address**" in various places. It's not directly about the spelling of "email".

**Comment by BWPanda** [comment] 2022-06-17 13:06
True, but if we keep this issue separate, whichever one doesn't get merged first will need to be updated. I think best to include this change in the other issue.

**Comment by BWPanda** [comment] 2022-06-22 00:32
I've updated the PR in https://github.com/backdrop/backdrop-issues/issues/4521 with these changes now, so please review there if you can.
