### ISSUE TITLE
Fixed PHP Notice for sites with content translation and admin language switcher.

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6104] opened 2023-05-03 18:59 UTC
## Description of the bug

After upgrading to 1.25.0-preview, a Notice is thrown: `Notice: Undefined index: href in admin_bar_locale_links() (line 490 of /Users/XXX/Sites/localhost/bdentity/core/modules/admin_bar/admin_bar.module)`   when all of these conditions are true:
- Version 1.25.0-preview, which includes the administrative Language Switcher (#5983)
- Site is multilingual with at least one other language installed, besides English (default)
- Content translation is enabled
- Multilingual support is enable for a Content Type, AND "Enabled, with translation" is selected for it

## Steps To Reproduce
1. Install Backdrop version 1.25.0-preview or later
2. Enable locale, language and content translation
3. In Structure > Content Type > Page, enable Multilingual Support for "Page" and select "Enabled, with translation"
4. Create a page and select English. Do not create a translation of that page into the second language
5. Save it

When you view, or try to edit that page, you'll get the Notice. NOTE: because this bug happens at the end of the page request process after the rendering processing has happened, you have to load the offending page twice to show the notice you got the first time. 

## Actual behavior
Notice is thrown, and the admin Language Switcher has an incomplete URL for the translated page (e.g. only `example.com/es` without a page path) .

## Expected behavior
Notice should not be thrown, and Language Switcher should work.

## Additional information

- Backdrop CMS version: 1.25.0-preview
- Web server and its version:
- PHP version: 7.4

------

PR https://github.com/backdrop/backdrop/pull/4433

**Comment by argiepiano** [comment] 2023-05-03 21:22
One more detail: once a page has been translated through the UI (when "Enabled, with translation" is selected for that content type), the notice goes away. It happens only for content that doesn't have a translation into the other language.

A possible solution is to check if the language link returned by `language_negotiation_get_switch_links()` has an `href` property. If not, we should not render the admin bar language switcher.

**Comment by argiepiano** [comment] 2023-05-06 14:07
PR https://github.com/backdrop/backdrop/pull/4433 provided for testing and review.

@herbdool, pinging you since you worked on the language switcher. This is what's happening:

- A call to `hook_language_switch_links_alter()` CAN return an empty href. This is the case with `translation_language_switch_links_alter()`. This happens when there is currently no translation of a node into the other languages. 

So, this PR checks that href is set. If not, it skips creating the link, thus avoiding the notice.

The second issue is NOT solved by this pr. In cases when a node doesn't have a translation, you still see the admin language switcher, but the link is incomplete, as in `example.com/es` with no path. Fixing that will require additional work.  The current approach to the admin language switcher uses `hook_admin_bar_replacements()` to work around the admin bar cache. Well, the current code in that hook replaces the children under the currently language in the switcher, even if the language paths are incomplete.

So, the incomplete link leads to the home page in the other language. Ideally, the switcher would be hidden for any language with incomplete paths. @herbdool I welcome your thoughts on this.

**Comment by herbdool** [comment] 2023-05-06 15:18
Thanks @argiepiano. I'm wondering if we should replicate the behaviour of the other switcher by adding a span instead of a link with just the language name.

**Comment by argiepiano** [comment] 2023-05-06 15:20
> Thanks @argiepiano. I'm wondering if we should replicate the behaviour of the other switcher by adding a span instead of a link with just the language name.

That sounds like a good solution. I can try expanding the PR later today.

**Comment by argiepiano** [comment] 2023-05-06 18:13
> I'm wondering if we should replicate the behaviour of the other switcher by adding a span instead of a link with just the language name.

I've been looking into this. The issue is that `theme_admin_bar_links()` expects either the element to have an `href`, or ir it's missing, to have children. If there is no `href` and no children, then the element is not rendered. So, it'd be tricky to render this as a `span`  without necessarily modifying   `theme_admin_bar_links()`, which may mess up other things... 

I could spend more time thinking of other ways, but perhaps @herbdool you have a better idea?

**Comment by argiepiano** [comment] 2023-05-07 00:49
I was able to modify the code to insert a `<span>` instead of `<a>` when there is no `href` provided by `language_negotiation_get_switch_links()`. I also added the suffix "(unavailable)" to the language.

@herbdool, this follows your recommendation. Can you please take a look and test?

**Comment by herbdool** [comment] 2023-05-07 02:16
Tested and confirmed the code looks good.

**Comment by laryn** [comment] 2023-05-15 21:02
Changed milestone since it specifies "1.25.0-preview" in the issue.

**Comment by quicksketch** [comment] 2023-05-15 21:13
Thanks @argiepiano and @herbdool! I merged https://github.com/backdrop/backdrop/pull/4433 into 1.x for 1.25.0.

**Closed** 2023-05-15 21:12 UTC
Labels: status - has pull request, status - fixed
