### ISSUE TITLE
Status Report should flag duplicate module installs

### ISSUE THREAD

**Issue by cellear** [backdrop/backdrop-issues#5464] opened 2022-01-18 21:17 UTC
## Description of the need

Modules can be installed in the root of the modules folder or in a subfolder.  This makes it possible to install multiple copies of the same module onto one Backdrop system.  Backdrop will choose one of these modules to make live, but it's (at best) not clear which one it has chosen, and a user can easily become confused, thinking a different module is loaded than the one that really is.

## Proposed solution

A test can be added to the status report which would alert the administrators that duplicate modules are installed.

## Alternatives that have been considered

Another option would be to allow duplicate modules to appear multiple times on the modules page.

## Additional information

Add any other information or screenshots that would help.

## Draft of feature description for Press Release (1 paragraph at most)

The Status Report now flags duplicate modules.

**Comment by bugfolder** [comment] 2022-01-18 21:31
Interesting, just saw that `system_requirements()` in file `system.install`already includes some checks for specific duplicate modules, so this should fit right in.

**Comment by klonos** [comment] 2022-01-18 22:02
Noting that part of this is "by design". For example, if someone wants to override a core module, they can copy that module from the `/core` folder into their `/modules` or `/modules/custom` or `/modules/contrib` folder, and "hack away". How things work in that situation is that the "custom" module take precedence over the core one.

Having said that, I understand the potential problem reported here, and I think that we should try to address it, so that people don't shoot themselves on the foot ...or if they do, then we provide them an easy way to know what's going on.

**Comment by cellear** [comment] 2022-01-18 22:05
I think it doesn't hurt to at least let site administrators know when one module is being overridden by another.  It strikes me as a big ask to assume site admins _know_ which one is taking precedence -- especially since it's based on a path that isn't (as far as I know) displayed in the user interface.

**Comment by bugfolder** [comment] 2022-01-18 22:05
Not just beginners can shoot themselves in the foot this way. My draft PR flags this situation in core:

![dup](https://user-images.githubusercontent.com/29214084/150026061-7949e607-af97-45e7-8429-26e02cab2fcd.jpg)

Is it a mistake to have both?

At any rate, your comment that duplicating a core module and "hacking away" is accepted suggests that instead of making this situation a REQUIREMENT_ERROR (as in the example above) it should only be REQUIREMENT_WARNING.

**Comment by bugfolder** [comment] 2022-01-18 22:09
Also sounds like it would be worthwhile to show which module is currently winning out (e.g., by emboldening the winner in the list).

**Comment by klonos** [comment] 2022-01-18 22:28
> At any rate, your comment that duplicating a core module and "hacking away" is accepted suggests that instead of making this situation a REQUIREMENT_ERROR (as in the example above) it should only be REQUIREMENT_WARNING.

Yup, I'd say waring, since that might be intentional. Something along the lines of "Hey, we've noticed this with your site. If you've done it on purpose, then cary on".

I would like something like that shown in the modules listing page as well (similarly to how we flag incompatible modules). If the 2 (or multiple) instances of the same module don't have the same number, it might be a good idea to indicate that, so that the person that will try to fix things picks the right version to remove.

**Comment by klonos** [comment] 2022-01-18 22:30
...perhaps it would also be a good idea to log something in dblog, just in case that having duplicate modules blows the site and troubleshooting can only happen by viewing the logs.

**Comment by bugfolder** [comment] 2022-01-19 02:45
`system_requirements()` already contains explicit checks for "duplicates" of 5 modules:

* ckeditor
* email
* link
* date
* redirect

So, for example, if you have another module `redirect` somewhere in the installation, you'll see a warning like this on the status page:

![before](https://user-images.githubusercontent.com/29214084/150053511-43c613c4-a623-45b9-9673-bd6f7963a9f8.jpg)

There's a couple of issues with this text. For one thing, it claims that the module is a "duplicate" even if it's not actually a duplicate module, but just has the same name. The language in the warning could also be cleaned up a bit. Since this issue is about flagging "duplicate" (or at least, same-named) modules, I'd say that cleaning up the existing code is part of this issue, so the PR I'll submit will address both: overrides of those 5 modules (existing checks), and in general, duplicate module names wherever they are (new checks).

**Comment by bugfolder** [comment] 2022-01-19 02:54
PR submitted. To fully test this, you'll need to build a local site and drop some duplicate modules into the hierarchy, although since it appears that Backdrop Core already contains two different versions of the `cron_queue_test` module, you can actually see that error in the Tugboat build. (Another bugfix issue about that will shortly follow.)

Meanwhile, here's an example of what it looks like with some intentional multiple-same-name modules, so folks can comment on the language and/or formatting.

![after](https://user-images.githubusercontent.com/29214084/150055050-31c15c5c-1ca8-46ad-96fc-dd16d404faa9.jpg)


Note new wording changes on the Redirect entry.

I'll point out one intentional difference between what's displayed for Redirect and for the general module command: the file path for the existing checks prepends BACKDROP_ROOT to the path (blacked out in the image). I left that off the "Modules" warnings for comparison. I do think we should do both the same way, but I think it's unnecessary and just adds more cluttered text for the user to parse. But I solicit further input.

**Comment by bugfolder** [comment] 2022-01-19 15:18
After further thought, I'm thinking that the explicit checks for the 5 core modules and the general check for multiply-named modules should be consolidated so that they're all formatted the same way; but still adding the additional informational text that's specific to the 5 core modules if they're overridden. So putting this back to "needs work" while I work on that.

> I would like something like that shown in the modules listing page as well (similarly to how we flag incompatible modules). If the 2 (or multiple) instances of the same module don't have the same version number, it might be a good idea to indicate that, so that the person that will try to fix things picks the right version to remove.

And also on this. Although I'd suggest that since there's already a ton of information on the modules listing page, perhaps it would be sufficient there to just add something like "Warning: multiple versions of this module detected. See the Status Report for details," and then put all the details like the specific paths (and versions, that's a nice touch) in the status report entries.

> perhaps it would also be a good idea to log something in dblog, just in case that having duplicate modules blows the site and troubleshooting can only happen by viewing the logs.

**Comment by bugfolder** [comment] 2022-01-20 00:43
I've made further changes in the PR.

On the module listing page, we flag multiples with warnings at the top of the page but send them to the status report page for details, since (a) the module listing page is already quite long and busy, and (b) the module listing page won't show any hidden modules that have multiple versions anyhow.

![modules](https://user-images.githubusercontent.com/29214084/150239724-2aeea224-7c69-4f73-81a9-b1b48e2082dd.jpg)

On the status report page, I've consolidated the explicit checks for the 5 core modules with the general identification of multiple-version-modules (but keeping the extra wording for those 5 modules), and have streamlined the wording a bit. Here's what that looks like with a bunch of extra module copies added.

![status_report](https://user-images.githubusercontent.com/29214084/150239829-4c072b80-3cf2-421a-a7f8-2dd8822d6f71.jpg)

Note that the status report flags the duplicate of `cron_queue_test`, which is hidden, and therefore does not show up on the module listing page.

And on the question of posting something in watchdog in case the site is totally hosed: if the site is well and truly hosed, then it's unlikely that a person could even get to the runtime status report evaluation, so I didn't include that.

**Comment by klonos** [comment] 2022-01-20 00:53
@bugfolder I'd suggest the following:
- have a single "Multiple/duplicate modules" entry on the status page, and then list all duplicate modules in a bullet list format in the details. The descriptions for the "special" modules merged into core can still be different (and point to the respective change record).
- I like the warning on the modules listing page 👍🏼  ...but I think that it should be a single message, with a list of duplicates. lIke (rough example - haven't though of exact wording etc):
  ```
  Multiple/duplicate modules detected:
  - module1
  - module2
  - ...
  See the status page for details."
  ```
- (follow-up) perhaps we should consider refactoring the array returned by `backdrop_merged_modules()` to include descriptions and/or links to change records of modules added in core 🤔

**Comment by docwilmot** [comment] 2022-01-20 01:47
Does this also nag when youve got different copies in mulitsite?

**Comment by bugfolder** [comment] 2022-01-20 01:50
On the status page, previously, each duplicated module had its own row, labeled with the module name (so I followed that pattern). I thought this was reasonable, because having duplicates is (apparently) relatively rare, so it's unlikely to have more than one appear; and if multiple modules do have duplication, it doesn't seem so bad to have multiple rows that puts the information into nice chunks, since there's a fair amount of information presented for each duplication, rather than a single doubly nested list (first level, modules; second level, paths for each module). Keep in mind that the examples I showed are intentionally pathological, to show lthe variety of possibilities on one screen.

On the modules listing page, there's a stronger case for having a single warning, since we're striving for brevity there, so I'll make that change.

> perhaps we should consider refactoring the array returned by `backdrop_merged_modules()` to include descriptions and/or links to change records of modules added in core

Just out of curiosity, where would this additional information be used? I only see 3 calls to that function, and it's not clear how or where the additional information could be made use of.

**Comment by bugfolder** [comment] 2022-01-20 01:51
> Does this also nag when youve got different copies in mulitsite?

Good question. Dunno—I've never set up a multisite. (Anyone out there got a test setup that could check this?)

**Comment by bugfolder** [comment] 2022-01-20 02:06
Here's the new version of the module listing page (with, as before, a pathologically large number of multiple-version modules).

![module_listing](https://user-images.githubusercontent.com/29214084/150251964-ffa8a323-25d5-48da-b0d2-d7f8ed94a6fb.jpg)

**Comment by indigoxela** [comment] 2022-01-20 15:54
> Anyone out there got a test setup that could check this?

I do have one around and can test soon. (I don't actually think, multisites would cause false positives, but you never really know until you test.)

**Comment by indigoxela** [comment] 2022-01-25 11:39
Now for the multisite test: works like a charm. :+1:

I juggled with the "Foobar" module. No problems if the module is in the individual site module folder. The warning only pops up when there actually are duplicates, like one copy in the common /modules directory and one in the /sites/THE-SITE/modules/ directory.
All warnings are correct, no false positives. And showing the "winning" one is a good idea, too.
I also tested with a Redirect contrib download. That warning is also correct.

![multisite-multi-module](https://user-images.githubusercontent.com/842066/150970271-ea7ebc21-93d0-4060-88d8-da95c913b36c.png)

**Comment by indigoxela** [comment] 2022-01-25 11:47
I'd like to note, though, that previously there's been no warning if the same module is in the common _and_ the individual module directory. But I think, that was a bug, actually. Correct me if I'm wrong. @BWPanda also uses multisite setups, if I recall correctly.

**Comment by BWPanda** [comment] 2022-01-26 23:56
I do use a multisite setup on my server. Not really willing to test PR there though 🙂 Here's a Lando file I posted a while ago for testing multisite setups, maybe it still works... https://github.com/backdrop/backdrop-issues/issues/4151#issue-510510820

**Comment by BWPanda** [comment] 2022-01-27 00:17
I setup a test multisite Lando install and tested the PR there. Works as @indigoxela already stated:

![image](https://user-images.githubusercontent.com/2385329/151268262-427559f0-b62a-4be5-91ec-bf7bafd28c32.png)

> previously there's been no warning if the same module is in the common and the individual module directory. But I think, that was a bug, actually. Correct me if I'm wrong.

I don't think it's a bug. It's a feature to be able to have common modules in the root `/modules` directory, then specific ones (even overriding the common ones) in the site-specific directory. We've never considered notifying the user of duplicate modules before, so this is a nice new feature, not a bug fix (for multisites anyway).

**Comment by docwilmot** [comment] 2022-01-27 00:26
> I don't think it's a bug. It's a feature to be able to have common modules in the root /modules directory, then specific ones (even overriding the common ones) in the site-specific directory. We've never considered notifying the user of duplicate modules before, so this is a nice new feature, not a bug fix (for multisites anyway).

Right, this is why I asked re multisite: this PR makes this a bug now, so your status icon would be flashing unnecessarily for a wanted feature. Do we want that?

**Comment by bugfolder** [comment] 2022-01-27 00:44
Right now, they're warnings, not errors (so no flashing status report). But seeing a warning on both the Modules page and possible warnings on the status page could get old quickly. Should this check be disable-able for multisite?

**Comment by BWPanda** [comment] 2022-01-27 01:01
Yeah, maybe add an ignore if one module's in the root dir, and one's in the sites/* directory...?

**Comment by docwilmot** [comment] 2022-01-27 01:23
I hadnt realised we were putting a warning at the top of the modules page. I wouldn't suggest not to throw a warning there in any situation, multisite or not, that just seems a bit too intrusive. Just a message on the status report should do (and maybe on module listing itself) IMO.

**Comment by quicksketch** [comment] 2022-01-27 06:40
I love this idea! And identifying which module is active is great. Should the displayed list be reversed so that the "winning" module is at the top of the list?

I agree with @docwilmot that reporting duplicate modules on the modules page might be aggressive. It's possible to be intentionally overridding. Lots of modules also post messages on the modules page (especially after enabling a module for the first time), I think we should avoid more messages unless they're absolutely necessary.

**Comment by bugfolder** [comment] 2022-01-27 15:38
> Should the displayed list be reversed so that the "winning" module is at the top of the list?

The algorithm that the system uses is "the last module found wins," so the current listing order somewhat reflects what's actually going on. But I guess users don't need to know that.

> reporting duplicate modules on the modules page might be aggressive

OK, will remove it.

Any thoughts about whether we should provide the ability to disable this warning on the status report page? There's a psychological desire to see the status report page "all green", and multisite users might think "I know what I'm doing, stop warning me about this."

**Comment by BWPanda** [comment] 2022-01-27 17:16
Since duplication *can* be a feature, maybe provide a setting to toggle this whole thing on or off. So then users can disable checking if they don't want it.

**Comment by indigoxela** [comment] 2022-01-28 07:31
> ... provide the ability to disable this warning on the status report page? ... and multisite users might think "I know what I'm doing, stop warning me about this."

Good point. We provide several overrides via the settings.php file. That warning might be a candidate for it.

> Since duplication can be a feature...

@BWPanda that's interesting. Personally I never used it that way, but I'm using multisite only in few projects.

**Comment by klonos** [comment] 2022-01-28 22:59
> We provide several overrides via the settings.php file. That warning might be a candidate for it.

I agree with that ^^ ...but these warnings should be on by default, since multisite installations are not 80% use case (we have metrics to validate that now 😉 )

**Comment by bugfolder** [comment] 2022-01-28 22:59
PR updated:

* Module listing page warning is removed.
* The order of multiple versions as presented on the status report is reversed, so that the winner comes first, rather than last.
* The "extra" description text for core modules has been consolidated into a single message (with varying parameters for module name, path, and relevant change notice).
* Introduced `$settings['multiple_module_version_warnings']` in `settings.php` where people can disable these warnings from the status report page. Default is that warnings are on.

**Comment by klonos** [comment] 2022-01-28 23:00
> Default is that warnings are on.

👍🏼 🙂

**Comment by BWPanda** [comment] 2022-01-28 23:17
> `$settings['multiple_module_version_warnings']`

I'd personally prefer something a bit shorter, like: `$settings['duplicate_modules_warning']`...

**Comment by bugfolder** [comment] 2022-01-28 23:23
> I'd personally prefer something a bit shorter, like: `$settings['duplicate_modules_warning']`...

I've tried to avoid using "duplicate" because the warnings happen even if the modules aren't duplicates (and that's probably a pretty common situation). The problems arise when the modules aren't duplicates, but are different versions.

**Comment by klonos** [comment] 2022-01-28 23:33
> I'd personally prefer something a bit shorter...

I've also left some suggestions on the PR around the settings.php bit. I'd rather the setting was as self-explanatory as possible (using the verb "disable" as a prefix), and that it is ready to be commented out and have warnings be disabled. ...plus a few other things around too long sentences etc. Feel free to tweak/adapt.

**Comment by bugfolder** [comment] 2022-01-29 02:08
The description changes were great, those are incorporated. I was less enamored of changing to "disable..." because it led to a double-negative in the evaluation ("if not disabled...."), so I left the settings variable definition the way it was. Hope that's OK.

**Comment by klonos** [comment] 2022-01-29 05:56
Thanks @bugfolder 🙏🏼 

> I was less enamored of changing to "disable..."...

I still like using "disable" better (or "suppress"), as that's what people will be doing. The default behavior for most cases will be to show these warnings, and the setting in settings.php will be providing a way to override that. If we leave it as is, it makes it seem more like a feature that people will be leaving enabled. I guess it also depends on how you see it.

I see what you are saying re the double negative, but that would be in the php code, whereas I was going for straight-forwardness and a self-explanatory setting name in settings.php, which is more likely to be read by non-coders.

Anyway, I'll let others chime in re that, but if we leave things as it is now, then I'd still like use to have a verb as a prefix to the setting name. Like `show_multiple_modules_warnings`.

**Comment by bugfolder** [comment] 2022-01-29 15:22
An overnight sleep always helps realize things. I realized an advantage to doing it the way you did with "uncomment this line to disable" is that existing sites, once upgraded,would throw the warning if there's a duplicate module squirrelled away somewhere, whereas what I've got now will only take effect on new sites (assuming existing sites don't carefully go through their settings.php file to check for additions).

**Comment by bugfolder** [comment] 2022-01-30 00:27
`'disable_multiple_module_warnings'` it is. PR updated.

**Comment by indigoxela** [comment] 2022-01-30 10:20
Another round of testing, single-site and multisite, again juggling with the "foobar" dummy module.

- No more warning on the module listing page. :+1:
- Still a warning on the status page :+1: 
- Then I uncommented the line in settings.php - warning gone :+1:

**Comment by jenlampton** [comment] 2022-02-03 23:33
This looks fantastic!  I've reviewed the PR and all looks good to me. I especially like the setting to disable the warning, but I'll personally be glad to have it :) Nice work everyone!

**Comment by quicksketch** [comment] 2022-02-09 22:53
Great work folks! I've merged https://github.com/backdrop/backdrop/pull/3910 into 1.x for 1.22.0.

**Closed** 2022-02-09 22:53 UTC
Labels: type - feature request, status - has pull request, pr - ready to be committed, pr - works for me, needs - translation update
