### ISSUE TITLE
[UX] Remove left-over help text on Maximum image size field

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2062] opened 2016-08-15 07:08 UTC
The description text for the Max image size field reads:

```
The maximum allowed image size expressed as WIDTHxHEIGHT (e.g. 640x480). Leave blank for no restriction. If a larger image is uploaded, it will be resized to reflect the given width and height. Resizing images on upload will cause the loss of EXIF data in the image.
```

We should remove the first part (`The maximum allowed image size expressed as WIDTHxHEIGHT (e.g. 640x480).`) because now that we have pretty integer fields that part of the explanation is nolonger necessary.

**Comment by Graham-72** [comment] 2016-12-20 05:54
But I still need the reminder that it is WIDTH x HEIGHT and not HEIGHT x WIDTH!

**Comment by jenlampton** [comment] 2017-10-19 21:49
Good point @Graham-72. Maybe that should be part of the label (and not hidden in the description?)

**Comment by Graham-72** [comment] 2017-10-20 04:47
Yes please. 👍

**Comment by BWPanda** [comment] 2020-10-12 11:48
I think the explanation in the description is fine. I don't think adding 'width x height' to the field label is a good idea.

Any objections to closing this then?

**Comment by stpaultim** [comment] 2020-10-12 18:04
I think the current text is ok as well, but it does leave room for improvement. I don't feel strongly about this, but if someone were so inclined to write a Pull Request I think it would be an improvement. 

I'm adding a screen shot to help folks looking at this issue for the first time. This applies to the maximum image size on the field configuration page (at least, that's what I think it applies to - the text may have changed slightly already). 

![Views___PR_3364_backdrop_backdrop_testing_site_](https://user-images.githubusercontent.com/3144571/95777203-54586a00-0c8b-11eb-9613-9a0c1453cdd2.png)

**Comment by stpaultim** [comment] 2022-03-12 07:39
As part of a OpenForce2022 I did a PR demo and we created a PR for this issue. 

Please, take a look and give us feedback.

**Comment by BWPanda** [comment] 2022-03-12 10:23
FTR, here's what it looks like with the above PR:

![image](https://user-images.githubusercontent.com/2385329/158014267-c233be58-1c8f-40de-849d-b6d618d39549.png)

**Comment by BWPanda** [comment] 2022-03-12 10:31
I'd personally prefer something like this instead:

![image](https://user-images.githubusercontent.com/2385329/158014449-82a1cc8d-02d4-449b-9b7f-4e2b960d5a1f.png)

And here's a PR that does just that: https://github.com/backdrop/backdrop/pull/3983
- Removes 'width/height' text from description
- Adds placeholder text instead
- Reduces width of number fields to look more natural

**Comment by stpaultim** [comment] 2022-03-12 21:15
@BWPanda - excellent improvement. I closed my PR in favor of yours and tested it. I will mark it "Works for Me."

**Comment by argiepiano** [comment] 2022-03-12 21:29
I do have a question about the latest PR by @BWPanda. When values are input into the fields, you don't know which field is for width and which for height. It may not too be problematic, but I think it's helpful to know at a glance.

**Comment by indigoxela** [comment] 2022-03-20 14:20
> When values are input into the fields, you don't know which field is for width and which for height. 

Yes, that's the culprit with placeholders. With existing values they're pretty worthless. TBH adding back (width x height) also seems better to me.

![width-or-height](https://user-images.githubusercontent.com/842066/159166938-c4b10eba-d550-4581-ac71-20dce72c0f63.png)

Another tiny thing: the "size" attribute is [not officially supported](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) for number input. It only works in some browsers, but not in all. I know that, because I ran into that myself. :wink:

**Comment by bugfolder** [comment] 2023-09-17 19:31
We have two PRs, both of which have (I think) been tested successfully, but provide different approaches:

* https://github.com/backdrop/backdrop/pull/3982, which uses explicit "width × height"
* https://github.com/backdrop/backdrop/pull/3983, which uses placeholders

@argiepiano, @indigoxela, and I prefer explicit. @BWPanda and @stpaultim prefer placeholders. Maybe we could get a little more input to move toward consensus (or at least, a clear majority?).

**Comment by olafgrabienski** [comment] 2023-09-17 19:56
I prefer the label with "width x height". (And in @BWPanda's screenshot I like the reduced width of number fields.)

**Comment by jenlampton** [comment] 2023-09-21 21:58
I also prefer explicitly stating it in the description, but can we also add placeholders? :) Best of both worlds?

**Comment by bugfolder** [comment] 2023-09-21 23:01
YAPR (Yet Another Pull Request) https://github.com/backdrop/backdrop/pull/4523. In response to the above, and discussion at the 2023-09-21 dev meeting. Points made there:

* Placeholders are nice to have, but are not accessible for all, so it's still nice to have the order spelled out in the description text.
* We don't need an entire sentence for "widht x height," so we can still streamline the wording.

Here's the result of the new PR, first, as the form initially comes up:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/b64c86d2-8e8e-46ce-bf1d-1e859363e7fb)

And then what it looks like with data already filled in (e.g., editing a field):

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/8f4130a5-f115-4074-b2d9-40a5288e44b1)

**Comment by quicksketch** [comment] 2023-09-22 22:15
Thanks @bugfolder! This is essentially @BWPanda's PR but with some description text rewording. Looks good! I left an item of feedback, that `#size` does not have any effect on number fields. It outputs the attribute, but it doesn't affect the display in the browser as far as I know. See https://github.com/backdrop/backdrop-issues/issues/6137, where we actually removed `#size` from various number fields.

**Comment by bugfolder** [comment] 2023-09-22 22:28
> This is essentially @BWPanda's PR but with some description text rewording.

Yes. Thanks for the `#size` note, I confirmed that it doesn't affect what the browser shows (at least in Mac Safari) and accepted those changes.

**Closed** 2023-11-21 21:16 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2023-11-21 21:18
I gave https://github.com/backdrop/backdrop/pull/4523 a final review and it looks and works great. Thanks @bugfolder for pushing this to the finish! Lots of folks to thank for this little improvement. https://github.com/backdrop/backdrop/commit/909f50d6b047f52ca65d2ecef0cab2fbecd74a07 by @bugfolder, @BWPanda, @indigoxela, @olafgrabienski, @jenlampton, @Graham-72, @stpaultim, @argiepiano, and @quicksketch.

Merged into 1.x and 1.26.x.
