### ISSUE TITLE
Unable to self-update to 1.13 on Pantheon: PHP fatal error

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3793] opened 2019-05-17 18:43 UTC
I tried to manually update my Pantheon site to Backdrop 1.13 today, but I failed because a test info file was missing the 'type' line. The error message follows:

```
UpdaterException: The info file (<em class="placeholder">temporary://update-extraction-51611763/backdrop/core/profiles/testing/modules/backdrop_system_listing_incompatible_test/backdrop_system_listing_incompatible_test.info</em>) does not define a 'type' attribute. in Updater::getProjectType() (line 199 of /srv/bindings/0a90d90e90ac41b4b6ff18f06dfbefe8/code/core/includes/updater.inc).
```

My previous version of Backdrop was 1.12.6

---

PR https://github.com/backdrop/backdrop/pull/2686

**Comment by quicksketch** [comment] 2019-05-17 20:23
Looks like that module is indeed just missing it's `type = module` line. I'll file a PR.

**Comment by quicksketch** [comment] 2019-05-17 21:37
Doing a grep I found 4 additional files that are still missing a `type = ` line in the .info file. Update the PR.

```
grep -L "type" --include "*.info" --exclude "*.tests.info" . --recursive 
```

**Comment by klonos** [comment] 2019-05-19 21:54
...got the same error. I guess we cannot auto-update until 1.13.1, where this is fixed 😞

**Comment by herbdool** [comment] 2019-05-28 13:02
@klonos your new issue is a duplicate of this one

**Comment by quicksketch** [comment] 2019-05-30 01:09
Thanks folks for the confirmation and review! I've merged https://github.com/backdrop/backdrop/pull/2686 into 1.x and 1.13.x.

**Closed** 2019-05-30 01:08 UTC
Labels: pr - ready to be committed, status - has pull request, type - bug report
