### ISSUE TITLE
[CMI] Add config translation

### ISSUE THREAD

**Issue by jdanthinne** [backdrop/backdrop-issues#704] opened 2015-02-11 11:10 UTC
## Things to test with configuration translation

- Site name/slogan (`/admin/config/system/site-information`)
- User account emails (`/admin/config/people/emails`)
- Field labels
- ???

## Original issue summary

Is there any plans for config translations? I'm currently porting my Custom Search module which adds configurable fields to search blocks, and due to the fact that some of them are labels, I was using the i18n_strings module to make them translatable, but I don't think i18n will be easy to port.
I've always dreamed that the Form API could contain a "#translatable" option for each field :-)

-----
~~PR: https://github.com/backdrop/backdrop/pull/2044 by @serendeputy~~
PR: https://github.com/backdrop/backdrop/pull/2397 by @herbdool

**Comment by quicksketch** [comment] 2015-02-11 22:37
Hi @jdanthinne! Yes, but probably only in Backdrop 2.x. Config translation is a big undertaking, but one that we can handle eventually.

Right now our config system is really efficient because it's so simple. It doesn't require any outside systems, such as a database connection, module info, or any language settings at all. I'd like to keep the storage mechanism as simple as possible, but we can use more elaborate mechanisms to translate config *after* it's been loaded.

I'm thinking something along these lines as a general approach:

- Load a config as we do normally.
- If that config file contains any translated strings, explicitly call `config_translate($config)` on the config object.
- This invokes `hook_config_info()`, which can be amended to include keys of items that need to be translated.
- `config_translate()` translates all strings within that config file.
- Call $config->get() normally.

We might also do something similar where instead of making a separate function, we could add a method and specifically call `$config->translate()` instead of `$config->get()`... that might be a more efficient approach as we would only need to translate one item at a time. But even if we did that, we'd still need the list of translated keys in hook_config_info() so that we can extract the list of strings that need to be translated by default.

**Comment by jdanthinne** [comment] 2015-02-12 06:55
That sounds good to me... Like a good plan.
But what would you advice to do now? Doing some t(config_get('module.settings', 'label')) is very ugly and has never been recommended...
Here in Europe, multilingual sites are everywhere.

**Comment by quicksketch** [comment] 2015-02-12 07:32
>  But what would you advice to do now? Doing some t(config_get('module.settings', 'label')) is very ugly and has never been recommended...

Yeah, it's never been recommended but it's the way that field labels and content type names have been translated for the entire Drupal 7 cycle. Although we didn't add new solutions for translating these things while adding config management, we did maintain the existing approach of running through t(), so it should behave the same was as Drupal 7. At least for the 1.x cycle, we'll likely be dependent on some kind of equivalent of the i18n project.

**Comment by jdanthinne** [comment] 2015-02-12 08:31
Allright, let's be nasty for now then. Thanks.

**Comment by quicksketch** [comment] 2015-02-12 20:31
I've updated the issue title to make this into the main thread for tracking config translation.

**Comment by klonos** [comment] 2016-03-05 21:17
> Yes, but probably only in Backdrop 2.x.

**Comment by quicksketch** [comment] 2017-06-01 20:12
I've been brainstorming on this recently and I think it may be possible for us to do this in both a simple and backwards-compatible manner.

Instead of making an entirely new 3rd translation system (in addition to Locale and Content Translation), if we build config translation on top of Locale module's `t()`. Using basically the same approach as I described previously, we'd add methods or functions to the config system to translate individual values or the entire config file, it's just that inside of these functions, we'd still be using t(). The only reason you're not supposed to use t() on variables is because the potx module can't find strings that are variables. So if we teach potx how to pull strings out of config files, then that limitation goes away.

In implementation, what this may look like is something like this:

Currently we do things like this (roughly):

```
$node_type_name = config('node.type.foo')->get('name');
$translated_name = t($node_type_name);
```

Afterwards we may do this:

```
$translated_name = config('node.type.foo')->getTranslated('name');
```

Where getTranslated() simply calls `t()` internally.

`potx` module then identifies the strings to be translated by using `hook_config_info()` to identify translatable strings. Or possibly we could store translatable keys directly in the config files themselves, in a special key similar to `_config_cache` and `_config_name`.

**Comment by klonos** [comment] 2017-06-02 20:35
Any reason why we should introduce `->getTranslated()` instead of just `->get()` (and adapt that to call `t()`)? Why not default to always getting the translated value?

**Comment by quicksketch** [comment] 2017-06-08 20:04
> Why not default to always getting the translated value?

Hm, possibly. I think my desire there would be to have `->get()` and `->set()` remain straight-forward and "non-magical". The automatic translation could result in odd behavior. Take the example: a config's 'foo' value contained the value "example", while browsing the site in French.

```php
$value = $config->get('foo'); // Would retrieve not "example" but "exemple"
$config->set('foo', $value); // Now the 'foo' value has been accidentally changed. It should remain "example", but has been changed to "exemple"
```

Keeping `->get()` retrieving the "actual value" and not the translated one would prevent these sort of mistakes. And if we modified ->get(), we'd need to introduce something that *didn't translate*, like `->getUntranslated()`, which I would find much less natural.

**Comment by herbdool** [comment] 2017-06-08 23:38
I guess we should hold off on porting parts of i18n until this is in core. It seems that this approach might mostly avoid the need to also port Variable module.

**Comment by klonos** [comment] 2017-06-09 09:07
>> Why not default to always getting the translated value?
>Hm, possibly....

I guess what I meant to say is that if we want Backdrop to be truly multilingual, we should make it so that *everything* is a translation of something. Even if that means that anything non-translated is actually the English translation of the thing. Does that make sense?

**Comment by klonos** [comment] 2017-06-09 09:08
...having said that, I really do not know if my suggestion makes sense in the context of CMI.

**Comment by jenlampton** [comment] 2017-08-11 00:50
As per the meeting today, bumping this to 1.9.

**Comment by jenlampton** [comment] 2017-12-11 21:24
Blocks are config. We are going to need a config translation system to translate anything else that's in config, so whatever we use for that can be used for blocks too. As a temporary work-around `t()` will do the trick, but we will probably need something better long-term.

**Comment by olafgrabienski** [comment] 2017-12-12 11:48
@jenlampton Thanks for your feedback! Re "config translation system" have you seen @serundeputy's first ideas how to translate a custom block over in https://github.com/Backdrop4Good/backdrop4good.org/issues/39#issuecomment-350821955? Maybe this approach is extendable for configuration translation.

**Comment by serundeputy** [comment] 2017-12-12 23:39
PR: https://github.com/backdrop/backdrop/pull/2044
Adds `getTranslated()` function to the `Config` class in `config.inc`.  This allows for the `t()` wrapping and makes it possible to do something like this:

```php
  $myConfig = config('block.custom.bear_block')
    ->getTranslated(
      'body.value',
      array(
        'making the text' => 'oui text.'
      ),
      array()
    );
  print_r($myConfig);
```
I'm confused about where and how we would use `hook_config_info()` to make `potx` aware of of the blocks/config to translate, but maybe we can itterate on this PR?

**Comment by herbdool** [comment] 2017-12-13 00:29
@serundeputy looks like a good start. How would this work with more than two languages?

**Comment by quicksketch** [comment] 2017-12-14 22:03
> I'm confused about where and how we would use hook_config_info() to make potx aware of of the blocks/config to translate, but maybe we can iterate on this PR?

Yeah, I'm also not 100% sure on this. Using hook_config_info() means that we would need to have a way to map which keys need to be translated. That works great for simple config files (like `system.core.json`) but would be complicate for dynamic config files (like `views.view.[*].json` or `layout.layout.[*].json`) where the keys are determined by user configuration.

I think possibly we might instead make this a more explicit process where we explicitly set which keys are translatable using something like this `$config->setTranslatable('key.name.here')`. For a module like Views, it would need to go through the configuration and mark which keys need to be translated before calling `$config->save()`. Something like this:

```php
$config = config('views.view.' . $this->name);
$translated_keys = $view->getTranslatedKeys(); // Difficult part is getting this list.
foreach ($translated_keys as $key) {
  $config->setTranslatable($key, TRUE);
}
$config->save();
```

For a simple config file like `system.core.json`, it would look like this:

```php
$config = config('system.core');
$config->setTranslatable('anonymous', TRUE);
$config->setTranslatable('site_name', TRUE);
$config->setTranslatable('site_slogan', TRUE);
$config->save();
```

Obviously we could optimize this a bit and make that take an array of keys rather than doing each one manually.

In the config file itself, you'd end up with something like this:
```
{
    "_config_name": "system.core",
    "_config_static": true,
    "_config_translatables": [
        "anonymous",
        "site_name",
        "site_slogan",
    ],
    // Rest of config file values.
}
```

**Comment by jenlampton** [comment] 2018-01-15 22:27
Great work on this so far everyone!  Bumping to 1.10 milestone

**Comment by jenlampton** [comment] 2018-04-26 20:27
Since there's been no progress on this since before the 1.9 release, I'm going to bump to 1.11. I think it's still an important improvement, so I'm not going to remove the milestone entirely, as is [our usual process](https://backdropcms.org/releases#timeline).

**Comment by herbdool** [comment] 2018-10-24 22:46
I'm trying to imagine how this would work for custom strings added to the database, or say, someone adding them to a custom module. For example, someone in the forum wants to localize registration emails (https://forum.backdropcms.org/forum/how-localize-registration-emails). In D7 you had to install Variables and i18n and then add the translations to settings.php. How can @quicksketch suggested approach help with this?

I'm keen to help with moving this forward where I can.

**Comment by herbdool** [comment] 2018-11-23 20:10
In my playing around with this I realized that using a `$config->getTranslated()` in the code cannot be done in form fields. It can only be used where the value can't be resaved, lest we resave the translated text as the new source. So it does seem to work, though it's a bit awkward for setting forms where people need to know they need to go to the locale form to search for the text.

Perhaps this can be improved by adding more contexts for when they're saved. Though this doesn't need to be included in this PR.

**Comment by herbdool** [comment] 2018-11-24 01:46
I've been trying it out on this page `admin/config/people/emails`. In this case, the translated string only appears in the emails and not anywhere in the interface (that is, because we don't want to display the translated string in the form field as noted above). So it seems that the custom user interface translation can't pick them up. So we have to display the translation somewhere, so I thought one option is to show the uneditable translation below the field. Then it's up to the admin to switch to the language in the interface for it to display.

**Comment by herbdool** [comment] 2018-11-29 20:55
I've posted a PR with my experiment. I think any final PR will be smaller but I wanted to see how it would work. It allows the user email templates and role label to be translated. For the email templates I had to print them to the screen so locale would find them.

**Comment by herbdool** [comment] 2018-12-04 03:37
To help with visualizing, here's what it looks like when viewing the Account emails admin screen (in Spanish at `es/admin/config/people/emails`):

![screenshot from 2018-12-03 22-13-22](https://user-images.githubusercontent.com/1071483/49416668-d2bb5b00-f748-11e8-8591-351bda6a12a4.png)

The translation is in a fieldset below each set of fields. If one visits the admin screen in the language interface to which one wishes to translate then they'll show up in a search in the User Interface screen:

![screenshot from 2018-12-03 22-18-09](https://user-images.githubusercontent.com/1071483/49416875-89b7d680-f749-11e8-9a84-9a41148a6e06.png)

**Comment by quicksketch** [comment] 2018-12-06 20:48
This is off to a great start! The PR at https://github.com/backdrop/backdrop/pull/2397 is pretty much exactly what I had in mind for interacting with `$config->getTranslated()`. I'm not sure about including translation information directly on each form (like the user registration emails), perhaps we could just link over to the Locale UI?

Also as you noticed, the option to translate a value in Locale module doesn't happen until the first time it is passed through `t()`. Locale module lazy-creates strings that need translation as they are passed through `t()`.

What we'll need on top of the current work is Locale module to react to config being pulled in, or have something that reads through all config files and finds all `_config_translatable` keys and trigger adding a locale entry for every key.

**Comment by herbdool** [comment] 2018-12-07 04:56
I agree that it's not ideal. A link to the Locale UI would be okay, but even better if it went right to the translation item there, if possible.

I like the idea of reacting to config being saved or imported so Locale gets updated whenever config changes.

**Comment by herbdool** [comment] 2018-12-26 15:18
I've updated the PR with Nate's suggestion. Using the config hooks when config is added or updated it will look for translatable config strings, and then run them through locale(). It also checks all config files when locale module is enabled. I haven't tested yet.

**Comment by herbdool** [comment] 2018-12-27 15:53
I've tested both enabling locale and update config and both work.

If my PR becomes the official one for this issue then I can clean it up so it covers just the basics. Then in separate PRs we can update the config files, etc.

**Comment by olafgrabienski** [comment] 2018-12-27 22:58
@herbdool I'm very interested but I'm on vacation, and I guess I won't have enough time here. But if you can provide steps to test, I'll *try* to have a look.

**Comment by herbdool** [comment] 2018-12-29 21:01
Thanks Olaf! I'll try to post steps here asap.

**Comment by herbdool** [comment] 2018-12-30 04:47
The patch will expose the config to translation but only if a particular config variable is set as "translatable". Here are the steps to test if a config string will show up in the locale UI. I'll write steps for testing the user registration emails.

1. To the `user.mail.json` file, after `_config_name` add:

```
     "_config_translatables": [
        "cancel_confirm_body",
        "cancel_confirm_subject",
        "password_reset_body",
        "password_reset_subject",
        "register_admin_created_body",
        "register_admin_created_subject",
        "register_no_approval_required_body",
        "register_no_approval_required_subject",
        "register_pending_approval_body",
        "register_pending_approval_subject",
        "status_activated_body",
        "status_activated_subject",
        "status_blocked_body",
        "status_blocked_subject",
        "status_canceled_body",
        "status_canceled_subject"
    ],
```
Easiest is to use the UI to re-import this file with the added change.

2. Enable locale.
3. Run update.php
4. Go to user mail admin page (`/admin/config/people/emails`) and choose a random string to search for. It can be just a fragment of a string. Copy it.
5. Go to the locale translation page `/admin/config/regional/translate` and search for that string.

The string should appear even without adding a language. And it doesn't require loading a page with that string for it to appear.

When enabling locale it will add all translatables in all the config files. But it should also add them when updating or adding a config file. So you could also test by adding a new, fake variable to the `_config_translatables` array and also adding it to the main part of the config file with a random string. Then reimport that file via the config UI. And then search for that config string in the translation page. It should appear.

That should be all the testing necessary for this PR I think.

**Comment by herbdool** [comment] 2018-12-30 19:56
Thanks Olaf. I think Gregory had already imported the config file, which is why it was there. You confirmed that the translatable string was present in the translation UI so that's good.

The line breaks are preserved in the db, this PR doesn't mess with that part.

This PR doesn't address the actual translation being used for the emails. That will come in the next PRs.

I think this is RTBC for the expected functionality. Are you okay if we mark it as such?

**Comment by olafgrabienski** [comment] 2018-12-30 20:43
I see! Yes, I'm okay with RTBC.

**Comment by klonos** [comment] 2018-12-31 02:13
Hey @herbdool, thanks for working on this 👍

Here's what I have done to test things:

1. Applied PR https://github.com/backdrop/backdrop/pull/2397 on my local (Backdrop installation in English)
2. Enabled locale.module (which also required language.module to be enabled).
3. Added another 2 languages (Greek and Italian), but left English as default.
4. I have left the detection method (`/admin/config/regional/language/detection`) as URL-based.
5. I have left the default path prefix for Italian (`/it`) and English (no prefix), but for Greek changed it from the default `/el` to `/gr`.
6. I have manually updated `system.core.json` to include `site_name` and `site_slogan` in a new `_config_translatables` section, right after `_config_name`. Here's how the first lines of that file look:

```json
{
    "_config_name": "system.core",
    "_config_translatables": [
        "site_name",
        "site_slogan"
    ],
    "_config_static": true,
...
```

7. I navigated to `/admin/config/regional/translate/translate`, and I searched for "name" -> "Site name" came up as the first result.
8. I then edited the "Site name" string, and have added translations for the Greek and the Italian version.
9. After saving the translations, I got redirected back to the list of strings 👍

...at this point, I have noticed that below the "Site name" string, there was some help text/description saying `/el/admin/config/system/site-information`. Not sure why the `/el` prefix was added there 👎 (as well as to the description of the other translatable strings), because a) I have changed that prefix to `/gr` for Greek, and b) I was doing all this from the English version of the site (no prefix in my URL). I am not sure what the purpose of this text is. Is it to be used as a link to navigate to the page where the string is mentioned? If so, then shouldn't all languages be listed (why was the `/el` prefix specifically added)? ...but then again, this is not very practical, as in a site with many languages this will end up being overwhelming. Anyway, moving on...

10. I head to `/admin/config/system/site-information`, and manually switch to Greek (`/gr/admin/config/system/site-information`), and then to Italian (`/it/admin/config/system/site-information`). The labels of the site name and slogan fields are rendered in their respective translated language 👍.
11. I edit the values of the actual fields while switched to the Italian version of the URL, and save 👍 ...I then switch to Greek in order to translate -> I see the Italian versions of the strings 👎 (was expecting English) ...without doing any editing, I switch to English -> strings in Italian 👎

...so although translation of the field labels works 👍, it seems that I cannot save the respective language of the actual values of the fields 👎 (as I expected). OK, lets try via the "User interface translation" page (although this does not make sense to me)...

11. I change the site name and slogan field values to "my English site name" and "my English slogan", and save them. I head over to `/admin/config/regional/translate` and search for "name", then for "slogan", then for "my English". The values do not come up so that I can translate them 👎

> This PR doesn't address the actual translation being used for the emails. That will come in the next PRs.

Fair enough, but my testing has resulted in finding that the actual field values are not translated/translatable.

**Comment by klonos** [comment] 2018-12-31 02:34
...OK so after some troubleshooting, it turned out that I needed to disable and uninstall locale.module, then reinstall it. After that, certain things started working:

- I could find the "my English site name" and "my English slogan" strings, and was able to translate them successfully via `/admin/config/regional/translate` 👍

- The help text below the translated strings **for the field values** was `/admin/modules/list/confirm` 👎 ...for the field labels, it was `/gr/admin/config/system/site-information` 👎 ...still don't know what that text is about/for ???

- The field labels in `/admin/config/system/site-information` would get updated as I switched language 👍 ...but the field values would not 👎 

- Heading to the home page and switching languages, would also render the English versions of the site name and slogan, no matter what language I switched to 👎

**Comment by klonos** [comment] 2018-12-31 02:36
...oh, sorry @herbdool, I just noticed your comment after posting mine. Sure, then it all makes sense then I guess.

> it turned out that I needed to disable and uninstall locale.module, then reinstall it. After that, certain things started working

^^ we should make sure that this also works without having to do anything special other than update the config files.

**Comment by klonos** [comment] 2018-12-31 02:37
...my testing will not go to waste. We can use the reports to create separate follow-up issues.

**Comment by quicksketch** [comment] 2018-12-31 05:34
> The help text below the translated strings for the field values was /admin/modules/list/confirm -1 ...for the field labels, it was /gr/admin/config/system/site-information -1 ...still don't know what that text is about/for ???

Seems to be that `locale.module` remembers the path at which the translated string was first seen, then provides a path to that location? Perhaps that's so that you can try and find if a string is used on that page. However... not very useful for something like `site_name` which is literally on every page. If we can find a way to suppress this behavior when strings are translated through config, that would be preferable.  Most config strings will probably be shown in lots of places (e.g. field labels and descriptions, view names, block titles, etc)

> The field labels in /admin/config/system/site-information would get updated as I switched language +1 ...but the field values would not -1

In all cases the current behavior is to show the default site language as the default value, regardless of the interface language. So no matter what language you are viewing the site in, the strings in the UI should always be the same (in the default language). We'd discussed briefly about options for translating being made more visible (e.g. linking over the locale UI or potentially providing a dedicated form for config strings), but yes, that's a follow-up after this one.

**Comment by herbdool** [comment] 2018-12-31 13:02
I updated the PR. Since the change was minor: docblock change plus a small change in $context being passed to locale(), I add a screenshot of result here and marked as RTBC.

![screenshot from 2018-12-31 08-01-02](https://user-images.githubusercontent.com/1071483/50560808-69d8eb80-0cd2-11e9-8285-6c2f901ee3c2.png)

**Comment by herbdool** [comment] 2018-12-31 13:15
Looks like the path shown below the string is stored in the db as the location which is populated by `request_uri()`. According to the schema location is: 'Backdrop path in case of online discovered translations or file path in case of imported strings.' We could improve this in a follow-up as well?

**Comment by herbdool** [comment] 2018-12-31 15:39
Follow up for location: https://github.com/backdrop/backdrop-issues/issues/3451

**Comment by quicksketch** [comment] 2018-12-31 19:14
Looks great @herbdool. One last question: Should we set `$options['context']` when calling `t()` inside of `getTranslated()`?

I believe that would allow the same string to be translated in different ways. For example the same word might have different meanings in different config files. However, reading through the code of the `locale()` I can't see how that is supposed to work. So perhaps omitting `$context` in the call to `locale()` is fine for now. Thoughts?

**Comment by herbdool** [comment] 2018-12-31 19:30
I think you're right. We need to set context in getTranslated. I can update this.

In locale it checks context when looking up the cache I think.

**Comment by herbdool** [comment] 2018-12-31 19:33
Or I think it's optional already for getTranslated to accept context and pass it on to t(). But might save some trouble by setting a default unless it's overridden in the call.

**Comment by herbdool** [comment] 2018-12-31 19:47
@quicksketch I've set a default context in getTranslated(). It only gets set if context is already empty.

**Comment by quicksketch** [comment] 2018-12-31 20:20
Looks good, I adjusted it slightly in https://github.com/backdrop/backdrop/pull/2397/commits/06beaac2765ed2cb6726d6f224207c843139ca22 so that `$options['context'] = NULL` can be explicitly set, in the event that someone ever wanted to specifically use the generic context instead of the config-file one.

**Comment by quicksketch** [comment] 2018-12-31 20:42
Merged https://github.com/backdrop/backdrop/pull/2397 into 1.x for 1.12.0. Thanks SO MUCH @herbdool for making this happen! Big thanks also to @serundeputy, @olafgrabienski, @klonos, and @jdanthinne for reviewing, testing, and making suggestions.

We only have a start here, APIs-only, but we can start adding all the config strings to files from here! And it opens up the way for https://github.com/backdrop-contrib/potx module to start extracting strings from config files based on the code base, which in turn will make translations from localize.backdropcms.org more complete than they ever have been. Great!

**Closed by quicksketch** 2018-12-31 20:42 UTC
Labels: status - has pull request, status - fixed

**Comment by herbdool** [comment] 2019-01-01 12:56
Here's a follow-up for adding config translatables https://github.com/backdrop/backdrop-issues/issues/3455

**Comment by herbdool** [comment] 2019-02-02 16:11
@sthomen might be good to read this comment on why it's not automatic https://github.com/backdrop/backdrop-issues/issues/704#issuecomment-307212144

**Comment by sthomen** [comment] 2019-02-02 16:47
@herbdool But that would not be the case, the context of the $config variable there would be the same, so you would be setting the _french_ value. The only real problem is a mismatch between get and set.

**Comment by herbdool** [comment] 2019-02-03 00:13
@sthomen since this is a really long thread it might not be clear that we merged in a PR for this already. So for better or worse we're working on this particular approach. You can see in the main PR how there's a getTranslated method for config now. And in a follow-up https://github.com/backdrop/backdrop-issues/issues/3455 you can see how it'll work in practice.

I'm not sure if I understand your questions/ideas but the config is "aware" of the language. The getTranslated method is because we don't want to have locale run for all config->get calls.

**Comment by herbdool** [comment] 2019-02-03 14:51
Hi @sthomen, rather than respond to your ideas, though they sound interesting, I will ask you to create a new issue and put your ideas there, with a link to this one. This issue is already closed and the PR is already merged. What you are proposing requires a completely different approach and also requires reverting this PR.

**Comment by herbdool** [comment] 2019-02-04 18:39
I've added a new issue https://github.com/backdrop/backdrop-issues/issues/3522. Please post all replies there rather than this closed issue.
