### ISSUE TITLE
Installer shows installing the Standard "module" (should be "profile" instead).

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2372] opened 2016-12-01 21:36 UTC
You can only catch this on really slow installations as it is the very last thing before the installer moves on to the next step:

![backdrop-installer-standard_module_instead_of_profile](https://cloud.githubusercontent.com/assets/2423362/20813626/68d69c1e-b86a-11e6-8200-8fa2ea8651e0.png)

**Comment by stpaultim** [comment] 2021-01-04 05:13
Closing this as duplicate of https://github.com/backdrop/backdrop-issues/issues/2015

**Closed by stpaultim** 2021-01-04 05:13 UTC
Labels: type - bug report
