### ISSUE TITLE
Fixed: Forms `user_register_form` and `user_pass` hard-code the page title.

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5731] opened 2022-08-18 23:03 UTC
## Description of the bug

Forms `user_register_form` and `user_pass` hard-code the page title by using `backdrop_set_title()`. This messes up the "real" page title when these forms are used  as blocks in a Layout (with the contrib [Form Block](https://backdropcms.org/project/formblock)), or when adding the forms programmatically to a page in a custom module. 

(Clarification: the issue is a core problem, not one produced by Form Block).

## Steps To Reproduce

1. Install Form Block
2. Add the User Registration Form in a sidebar of the Default Layout 
3. Visit a node display (be sure you are logged out) and see the title of the node page being changed to "Create new account"
<img width="1196" alt="Screen Shot 2022-08-18 at 5 02 04 PM" src="https://user-images.githubusercontent.com/9938978/185509900-f91cdd18-d983-43c0-a247-5ad3a24a1fa6.png">

## Actual behavior
The page title is force-changed by the block to "Create a new account"

## Expected behavior
The page title should still be the node's title.

## Additional information

The [line where the title is set](https://github.com/backdrop/backdrop/blob/8ce893d89106993c37ada5339355c9ead03bb8e8/core/modules/user/user.module#L3109) within the form function by using  `backdrop_set_title()` did not exist in Drupal 7.  This ws added 5 years ago as part of:

- https://github.com/backdrop/backdrop-issues/issues/260
and also as a reaction to:
- https://github.com/backdrop/backdrop-issues/issues/728
 
The advantage of using `backdrop_set_title()` in the forms is that it creates a more meaningful title for the user password and user register forms. Before `backdrop_set_title()` was added, Backdrop would produce the default page title of the parent item ("User account"),  since the paths for both `user/register` and `user/password`  are `MENU_LOCAL_TASK`.  

But the disadvantage of using `backdrop_set_title()` in the form is that it forces a specific page title onto other pages that contain the form as a block. This was [first reported in the forum](https://forum.backdropcms.org/forum/node-page-title-changes-create-new-account-when-user-reg-block-displayed). 

I really can't think of a way that preserves the nice form titles, and at the same time respects the page title where the form is present. 
 
Add any other information that could help, such as:
- Backdrop CMS version: 1.22.2

**Comment by indigoxela** [comment] 2022-08-19 06:51
Confirmed - not a problem in D7, but reproducible with user_register_form and user_pass in B.

Tricky... I couldn't think of any workaround the contrib module (or custom code) could do to restore the original page title in this case.

In core some checks could be done, for example "what's the current path" or "what's the current page title" and only fire backdrop_set_title() when appropriate.

Other thoughts?

**Comment by argiepiano** [comment] 2022-08-19 12:35
> In core some checks could be done, for example "what's the current path" or "what's the current page title" and only fire backdrop_set_title() when appropriate.

Yes. I think checking the path is the way to go. I'll try to provide a PR (busy time with school starting this week)

**Comment by klonos** [comment] 2022-08-20 14:40
> Yes. I think checking the path is the way to go.

Also agree 👍🏼 ...reading through the issue description, all that came to mind was "We should then be adding the titles via `backdrop_set_title()` conditionally."

**Comment by argiepiano** [comment] 2022-08-27 01:31
Revisiting this issue to try to find a more thorough solution. A bit of background:

- By design, both in Drupal 7 and Backdrop, `MENU_LOCAL_TASK` menu items always display the page title of the parent item. In Drupal 7 visiting `user/register` displays the title of the `user` menu item ("User account"), while the title of the local task ("Create new account") is displayed in the tab below the title. I want to emphasize that this is by design, and all `MENU_LOCAL_TASK` both in Drupal and Backdrop work like this, except in these two forms. See snapshot from D7

<img width="485" alt="Screen Shot 2022-08-26 at 7 12 46 PM" src="https://user-images.githubusercontent.com/9938978/187008587-5f4b14b5-f052-429d-9b6f-503f6b612b7d.png">

- Five years ago, it was decided that not having the local task title as the page title was confusing (I personally disagree with this). This is why these two forms got `backdrop_set_title()` to force the page to have the local task title (again, I disagree with this)

<img width="519" alt="Screen Shot 2022-08-26 at 7 26 13 PM" src="https://user-images.githubusercontent.com/9938978/187008965-bb8bbbb6-7fe2-4c09-8e1b-0a6e584f3079.png">


- As seen in this issue, this creates a problem when using these forms as blocks, or when you programmatically use them on a different page. The result is that the local task title (wrongly) becomes the title of the page

To me, the placement of  `backdrop_set_title()` within the form function was the wrong way to accomplish the title change.

So, as I see it, there are three options to fix this:
1. As suggested above, we could wrap the `backdrop_set_title()` with an if statement that checks whether we are seeing the form page, or we are on a different path. While simple, to me this seems like patching a hack with another hack
2. Create  full password and registration forms as separate blocks (in core, or as part of the contrib `Form Block`). This is what core does for the Log in form: this form is provided separately as a page callback (see `user_login()`), AND, separately as a block (see `user_block_view()` and  `user_login_block()`)
3. We could create "wrapper" page callbacks for `user/register` and `user/password`  that sets the title and then returns the form; AND remove the `backdrop_set_title()` from the form function. This way, forms `user_pass()` and `user_register_form()` will not have the problematic title setting themselves, but that will be moved to the wrapper callback.

I personally am leaning toward number 3 above. I'll provide a PR for this in a few minutes, and will appreciate your thoughts.

**Comment by argiepiano** [comment] 2022-08-27 02:26
PR https://github.com/backdrop/backdrop/pull/4182

This PR implements option 3 in my comment above: creates wrapper callback functions for user password and user registration forms. These wrapper functions take care of setting the page title. It removes `backdrop_set_title()` from the actual form functions.

**Comment by indigoxela** [comment] 2022-08-27 09:23
The wrapper (page) callback seems reasonable to me. :+1: 

Agreed, compared to that just using an if statement in the form function seems like a workaround.

**Comment by nattywebdev** [comment] 2022-08-30 14:06
I can confirm that PR https://github.com/backdrop/backdrop/pull/4182 works in my dev environment and fixes the issue I originally experienced.
Thanks to @argiepiano for a speedy response.

**Comment by argiepiano** [comment] 2022-09-01 15:29
The latest push addresses @docwilmot comment in the PR. Ready for code review. Can someone please add a milestone?

**Comment by indigoxela** [comment] 2022-09-02 06:37
> The latest push addresses @docwilmot comment in the PR...

Hm, but is `@since 1.23.0` correct? It's marked as "milestone candidate bug", which means that it will also go to 1.22.3, right?
Why is that `@since` actually necessary? @docwilmot?

**Comment by argiepiano** [comment] 2022-09-02 14:02
> which means that it will also go to 1.22.3, right?

That makes sense. I was following @docwilmot suggestion. I also wondered why this `@since` is needed. The PR adds an intermediary step, but it doesn't really change any API, and the uri for those forms hasn't really changed. Still, more documentation is better than less I guess.

**Comment by argiepiano** [comment] 2022-09-02 14:05
PR now refers to 1.22.3 instead of 1.23.0.

**Comment by argiepiano** [comment] 2022-09-16 22:40
This has a PR and a WFM. It needs code review. Anyone available to do that?

**Comment by indigoxela** [comment] 2022-09-19 07:08
That `@since 1.22.3` needs an update.

But still my question @docwilmot - why is that `@since` necessary?

**Comment by argiepiano** [comment] 2022-09-19 12:44
I have update the  `@since` label to 1.23.1.

**Comment by argiepiano** [comment] 2022-09-19 12:55
Strange test failures in PHP 5.6 - Could not set up web server. Probably unrelated?

**Comment by indigoxela** [comment] 2022-09-19 13:09
> Strange test failures in PHP 5.6... Probably unrelated?

Completely unrelated - odd webserver setup problem. Can you "turn it off and on again" to see, if it's gone?

**Comment by argiepiano** [comment] 2022-09-19 13:48
Retried: same failures. Something is wrong with the tests?

**Comment by indigoxela** [comment] 2022-09-19 13:55
> Retried: same failures.

[Issue](https://github.com/backdrop/backdrop-issues/issues/5790) opened for further investigation. The problem seems completely unrelated to our testing suite - it's rather in the action (setup).

**Comment by indigoxela** [comment] 2022-09-19 14:50
@argiepiano setup problem fixed in the other issue - but it's probably a blocker for this and all other PRs.

**Comment by kiamlaluno** [comment] 2022-09-19 21:43
Isn't `@since` used for the functions that are public API? I thought hook implementations should not considered public API.

**Comment by jenlampton** [comment] 2022-12-02 22:22
> Isn't @since used for functions that are public API? I thought hook implementations and page callbacks should not be considered public API.

I see where you're coming from, but in this case I think the `@since` is helpful here, even though strictly not necessary.

@argiepiano As I was reading through this issue, I thought to myself "oh jeez, we really need dedicated page callbacks and not just the forms..." and then I looked at the PR and saw exactly that solution :) Thank you  for finding + fixing this issue!  I expect there may be other places in core where we are doing the same thing, so I'm going to do a little look-see and will make a follow-up issue if that's the case.

**Comment by quicksketch** [comment] 2022-12-02 22:31
I agree that adding a `@since` here might be helpful for users/modules that are modifying the user login/reset pages. PR looks good to me too.

**Closed** 2022-12-02 22:41 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2022-12-02 22:43
https://github.com/backdrop/backdrop/pull/4182 has been merged into 1.x and 1.23.x. Thanks @argiepiano, @indigoxela, @klonos, @kiamlaluno, and @jenlampton!
