### ISSUE TITLE
[UX][DX] Change the weight field in the taxonomy term form to a number field

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3592] opened 2019-03-17 02:56 UTC
This is currently a text field, so we also need a `is_numeric()` check in `taxonomy_form_term_validate()` to make sure there is no wrong input.

If this was a proper number field, then the user could use their keyboard up/down key to change, and there would also be no need for the check in the form validation function. Less code/complexity++ 😄

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2535

**Comment by klonos** [comment] 2019-03-17 03:04
...we also have a `'#type' => 'weight'` field, but not sure if taxonomy terms are allowed to have negative weights.

**Comment by herbdool** [comment] 2019-03-26 13:10
This looks okay to me. It seems to limit it to the number of terms. So with 4 terms it goes from minus to plus four.

**Comment by klonos** [comment] 2019-03-26 14:11
>It seems to limit it to the number of terms. So with 4 terms it goes from minus to plus four.

Sorry, what? I don't understand this, but it sounds like something that we should fix.

@jenlampton is of the opinion that we should change this to `'#type' => 'weight'`, but as I said in #3593:

> Sure. The only reason I may sound skeptical about using fields of type #weight is because they are limiting to a specific min/max value. Number fields are easy to use with the mouse scroll when focused (no additional clicks).
>
>Having said that, I'm glad to switch the PR to #weight, but I need to know what to use for the #delta value for it?

What do you think @herbdool? ...others?

**Comment by herbdool** [comment] 2019-03-26 20:56
@klonos seems like by design to me. It also works that way without this PR.

I don't know if I even tested this in the right place. It's not clear from the description.

**Comment by klonos** [comment] 2019-03-28 06:56
OK, so changing `weight` fields to `number` fields, with min/max values instead of `#delta` (if that's required) seems like something we'll attempt in #3626.

Adding milestone tag for 1.12.6

**Comment by quicksketch** [comment] 2019-04-09 21:21
The scope of https://github.com/backdrop/backdrop/pull/2535 is limited and does exactly one thing (changing textfield to number) and doesn't get into the general weight field problems of #3626. I've merged the PR into 1.x and 1.12.x. Thanks @klonos and @herbdool!

**Closed by quicksketch** 2019-04-09 21:21 UTC
Labels: status - has pull request, status - fixed
