### ISSUE TITLE
Upgrade to 1.5.0 throws PHP notice

### ISSUE THREAD

**Issue by rstamm** [backdrop/backdrop-issues#2244] opened 2016-09-29 18:58 UTC
`Notice: Undefined variable: footer in include() (line 31 of /var/www/backdrop/backdrop1p/core/themes/seven/templates/maintenance-page.tpl.php).
`

![backdrop-upgrade-throws-php-notice](https://cloud.githubusercontent.com/assets/6431849/18967916/42418920-8687-11e6-87cf-03e2ee9a94cd.png)

**Comment by dyrer** [comment] 2016-10-02 23:18
There is a change on 1.5 version, how maintenance pages are handled.
https://api.backdropcms.org/node/44499

**Comment by klonos** [comment] 2016-10-03 08:17
I think that this is a duplicate of #2187

**Closed by klonos** 2016-10-03 08:17 UTC
Labels: type - bug report
