### ISSUE TITLE
Remove entity_create_stub_entity() in favor of entity_create()

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#4181] opened 2019-10-31 15:48 UTC
In https://github.com/backdrop/backdrop-issues/issues/1475 I propose to add forward revision capability to core. The corresponding issue in D7 listed [Remove stub entities, replace entity_create_stub_entity()](https://www.drupal.org/project/drupal/issues/1551140) as a blocker, subsequently fixed. This issue is to decide if this needs to follow the D7 path.

`entity_create_stub_entity()` is called only in four places: 3 times in Field tests and also in `EntityFieldQuery::finishQuery()` and just creates a `stdClass()` Object to initialize a stub entity, which was fine when all D7 Entities were not classed, but now in Backdrop all Entities are classed Objects.

The original resolution to stub entities when D7 started classing entities was to just change  `entity_create_stub_entity()` 
```
function entity_create_stub_entity($entity_type, $ids) {
- $entity = new stdClass();
...
-  return $entity;
+ return isset($info['entity class']) ? entity_create($entity_type, $values) : (object) $values;
}
```

But ultimately the patch committed just before forward revisions was committed was not that "simple" fix but [this one](https://www.drupal.org/files/stub-entity-concept-removed-1551140-38.patch) which removes stub entities completely. 

This issue is to track which route would be best for Backdrop. 

Would appreciate some advice from @quicksketch on how he feels we should move forward as this as noted above is a blocker.

---
PR by @docwilmot https://github.com/backdrop/backdrop/pull/2966

**Comment by docwilmot** [comment] 2019-11-01 21:02
Decided to go ahead and remove `entity_create_stub_entity()` after all. There was an available alternative for `EntityFieldQuery::finishQuery()` and there was already a Test Entity we could use in tests, so since this function is not used anywhere, it seems more sensible to remove it from core. This PR updates it to a real Entity.

Apart from tests there should be no need for a stub entity in Backdrop anyway, since all our Entities are classed; one could simply use `entity_create()`.

Only question is whether any contrib might perhaps be using this function.

**Comment by docwilmot** [comment] 2019-11-03 16:55
Googling `entity_create_stub_entity()` does find contrib uses for this function, which suggests that introducing this in core may break things. I attempted a PR https://github.com/backdrop/backdrop/pull/2967 which tried to instead fix the function, but ended up becoming more and more like the first PR, since we really shouldnt be using the function for anything we have in core anyway. So compromise: remove all usages of the function, but keep and deprecate it.

**Comment by klonos** [comment] 2019-11-03 17:02
> So compromise: remove all usages of the function, but keep and deprecate it.

Not very knowledgeable on the specific matter, but that sounds reasonable @docwilmot 👍

**Comment by herbdool** [comment] 2019-11-07 17:40
I agree with deprecating it. Is there a message that can be shown in logs when modules use it?

I haven't tested it but automated tests are passing.

**Comment by quicksketch** [comment] 2019-11-08 19:00
Looks good to me too.

>  Is there a message that can be shown in logs when modules use it?

Yes, one more change before committing, we should add a `watchdog_deprecated_function()` call:
https://github.com/backdrop/backdrop/pull/2966/files#r344316790

**Comment by quicksketch** [comment] 2019-11-08 22:07
Merged https://github.com/backdrop/backdrop/pull/2966 into 1.x for 1.15.0. We need a change record for this deprecated notice, so I'm leaving this open.

**Comment by quicksketch** [comment] 2019-11-08 22:08
Per the `@deprecated` docblock added in the PR, this looks like it will only go into 1.15.0, unless there's some driving reason to cherry-pick it back into 1.14.x as well.

**Comment by klonos** [comment] 2019-11-09 08:18
@quicksketch this is a blocker for #1475 ...and we currently have not milestoned that yet. The only thing that should mandate cherry-picking this into 1.14.x is if we decide to do the forward revisions thing during that cycle.

**Comment by docwilmot** [comment] 2019-11-11 19:36
merged

**Comment by quicksketch** [comment] 2019-11-14 21:04
From the scope of #1475, I don't think there's any way that could be done in 1.14.x, that's a major change in functionality. Leaving this in 1.15.x only seems appropriate, unless we have other reasons to backport it.

**Comment by klonos** [comment] 2019-11-18 01:13
We'll need a change record for this, so leaving open.

**Comment by jenlampton** [comment] 2019-11-19 21:12
I just ran into [problems with a contrib module](https://github.com/backdrop-contrib/multifield/issues/32#issuecomment-555684528) that is calling this function. In Backdrop every entity needs to have an `id()` method. If a stub entity is a `stdClass` it won't have that method, and anything else in core that expects that all entities will, things might break.

I think what we could do to fix this is avoid returning a `stdClass` object. If we were to provide a `StubEntity` instead, that had all the neessary properties, things could work as they did in Drupal 7.

Without a deprecated notice, I'm not really sure what contrib should do instead of using this function. Do we really want every contrib module to create their own stub entity class for this purpose? I could do that in this contrib project, but I wouldn't want a site with dozens of modules to have dozens of identical classes that are all used for the same purpose -- especially if the only reason they are doing so is to make up for a feature that we'd removed from core.

I'm going to file an alternate PR that un-deprecates this function and adds a StubEntity class, for consideration.

**Comment by docwilmot** [comment] 2019-11-19 21:36
That PR fixed stub entities so that they are supposed to be real Entities. See https://github.com/backdrop/backdrop/pull/2966/files#diff-74b1d8aac0e538965127e1fdce97dc37R367.

**Comment by jenlampton** [comment] 2019-11-19 21:39
> That PR fixed stub entities so that they are supposed to be real Entities

I was looking at the api site, where the final return line is this:

```php
return isset($info['entity class']) ? entity_create($entity_type, $values) : (object) $values;
```

The problem is the `(object) $values;` part.

**Comment by jenlampton** [comment] 2019-11-20 20:41
Well, It turns out I was running into two separate problems with `stdClass` objects, one was caused by the old `entity_create_stub_entity()` (but was fixed with this PR) and the other was a completely separate psuedo-entity created by my module.  

> Apart from tests there should be no need for a stub entity in Backdrop anyway, since all our Entities are classed; one could simply use `entity_create()`.

Should i try replacing `entity_create_stub_entity()` with `entity_create()` in contrib to see if it will work the same way?

**Comment by docwilmot** [comment] 2019-11-22 03:19
`entity_create_stub_entity($entity_type, $ids)`, note it requires an entity type, and so its essentially creating just a minimal version of an actual entity, not just a generic stub. So in the past, when we allowed entities to be `stdClass` this would work fine because you could pass that stub through all the entity hooks and it would behave appropriately, but now, core will complain loudly because our entities *have* to extend `Entity`. 

But to make a minimal entity is essentially what `entity_create()` does. So I'd say yes to your last question.

**Comment by jenlampton** [comment] 2019-11-22 05:53
> note it requires an entity type, and so its essentially creating just a minimal version of an actual entity, not just a generic stub

In the multifield module it used a made-up entity type and got back a `stdClass` object that it could use for it's purposes, as well as using `Node` when it needed a node stub. 

For the former, I've created a generic stub entity class in the Multifield module. I'm not sure how much that will be necessary in contrib, but I'd hate to see a lot of contrib projects need to create the same exact generic stub entity class. I'm not sure how we can tell if that will happen though, until all the contrib projects try to update.

**Comment by jenlampton** [comment] 2020-01-02 04:40
Change notice: https://api.backdropcms.org/change-records/entity_create_stub_entity-removed-from-core

**Closed** 2020-01-02 05:02 UTC
Labels: status - has pull request, status - fixed
