### ISSUE TITLE
Add Views handler for term aliased path

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#5338] opened 2021-10-29 20:03 UTC
**Description of the bug**

When using a view with fields for a content type, one option is "Path" which provides the aliased path to the content. This option is missing for Taxonomy Terms.

**Workarounds**

It is possible to build the internal URL using the term ID and adding `taxonomy/term/` in front of it, but it's better to be able to access the aliased path.

**Comment by laryn** [comment] 2021-10-29 20:09
I forgot I ported this one:

 - https://github.com/backdrop-contrib/views_term_path

**Comment by herbdool** [comment] 2021-11-18 17:24
I did a code review and tested. Works great!

**Comment by laryn** [comment] 2021-12-02 12:32
I just realized we have no milestone here -- and maybe need to do something to absorb the contrib module? What's your take on that @herbdool -- the classes don't actually clash since I kept the ported module as is, but followed the pattern of the node path for this core PR. The module uses `views_term_path_handler_field_path` and core uses `views_handler_field_term_path`. Even the Views tokens are different: `term_path` vs. `path`. 

Do we just leave this as is and I make a note in the README for contrib?

**Comment by herbdool** [comment] 2021-12-02 14:59
I just tested and the two can co-exist so that might be okay. There are just 10 installs of the contrib version. I was wondering what happened if I disabled the contrib module and it gave a Broken handler.

Maybe making a note of it in README is enough.

Just thinking that I'm going to change this to task - it's a small thing but it's not a bug per se.

**Comment by quicksketch** [comment] 2021-12-03 23:02
Thanks @laryn. I think making this backwards-compatible if we fully absorbed the contrib module would be a challenge. With so few installs and the non-conflicting approach, I think just noting the availability of this feature in the contrib README sounds good.

**Comment by quicksketch** [comment] 2021-12-03 23:03
I merged https://github.com/backdrop/backdrop/pull/3811 into 1.x and 1.20.x. Thanks @laryn, @herbdool, and @klonos!

**Closed** 2021-12-03 23:02 UTC
Labels: status - has pull request, status - fixed
