### ISSUE TITLE
Add descriptions for user roles.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5748] opened 2022-08-27 21:00 UTC
This is the same as https://www.drupal.org/project/drupal/issues/256287:

> It would be useful to be able to document on the site why a certain role exists.

The feature is currently provided by the contrib module https://github.com/backdrop-contrib/role_help (that module also allows for a separate help text field that is shown to the user, but I don't think that this should be provided by core).

---

Advocate: @quicksketch

---

Minor release update:
- [x] Add a conclusion suitable for blog post + release notes
- [x] Add Documentation label if the feature needs to be documented (or needs docs to be updated)
- [x] N/A Add Needs change record label if the the issue contains an API change.
- [x] Add Needs translation label if the the issue contains string translations.

---

String translations:
* `Summary of this role's purpose, shown on the role listing page and when assigning this role on user account forms.`
* `Backdrop core now provides most of the functionality of Role Help module. See the <a href="!url">change record for more information</a>.`

---

## conclusion suitable for blog post

Backdrop now includes the ability to add descriptions for user roles.  This will help administrators understand the differences between roles and assign them appropriately.

**Comment by quicksketch** [comment] 2022-12-06 20:27
I'd like to advocate for this (hopefully very simple) feature for 1.24.0.

**Comment by stpaultim** [comment] 2022-12-08 21:20
I think that this would be a very nice new feature in core!

**Comment by quicksketch** [comment] 2022-12-09 07:23
Initial PR for review: https://github.com/backdrop/backdrop/pull/4271

In particular, reviewing the default role descriptions assigned to anonymous, authenticated, and administrator would be helpful. Here's what I have in the PR:

* anonymous: `Special role assigned to any site visitor that has not signed into the site.`
* authenticated: `Special role assigned to all users who have signed into the site. Permissions assigned to this role are given to all other roles except the anonymous role.`
* administrator: `This role receives all permissions on the site.`

The display of the description I modeled on the content type descriptions, with an additional column on the role listing page:

![image](https://user-images.githubusercontent.com/100206/206647121-1e964d8f-38c0-4b53-a6c0-3e2614ea382d.png)

I also added the description to the `title` attribute of the Permissions page, which makes it show up on hover:

![image](https://user-images.githubusercontent.com/100206/206647268-3468a2e7-5a32-49d2-8fde-d27c1796f376.png)

This PR still needs test coverage for the new description value.

I briefly read over https://github.com/backdrop-contrib/role_help and I'm not sure if it makes sense to provide an upgrade path from that contrib module. I'd be curious to hear what @bugfolder might say regarding adding this to core and what path he would recommend for the contrib module.

**Comment by olafgrabienski** [comment] 2022-12-09 09:50
This is a great idea! I've had a quick look at the default descriptions which look good to me.

I'd suggest to also add a description for the Editor role, something like:
`This role is by default configured to give sufficient permissions to content editors.`

**Comment by bugfolder** [comment] 2022-12-10 02:55
>  I'd be curious to hear what @bugfolder might say regarding adding this to core 

I'd support adding the functionality to core, but there should be a graceful path for users of the contrib module.

> and what path he would recommend for the contrib module.

I will look into this deeper in several days when I'm back from travel; not in a position right now to look at the code. Note that `role_help` is a D7 module, so we'll need to gracefully accommodate users upgrading from D7, as well as users of the B module.

**Comment by indigoxela** [comment] 2022-12-15 14:42
All checks on all PHP version failed. I don't think we ever had that before. :wink:

All failing checks are user-related. So I'm guessing, this needs more work. `Undefined index: #description`

**Comment by bugfolder** [comment] 2022-12-16 02:59
I've done a little tinkering with and without the Role Help (`role_help`) module after applying this patch. The good news is that they more or less peacefully coexist (no smoke or flames). Role Help stores its extra info (`summary` and `description`) in a new db table (`role_help`), while this patch stores its new info (`description`) in config.

(In retrospect, since most role info moved into config, the module upgrade from D7 probably should have replaced the db table with config fields. Maybe a future version of the module could copy the description data from the table into config and then remove the table.)

Role Help actually has you enter two bits of new information: a `description`, which is longer and used for admin purposes (this is basically equivalent to the new `description` config field), and then a `summary`, which is shown on the user edit page. There is no equivalent of the `summary` in this new patch. I would like to suggest that we add this; if users can see their roles on their account edit page, it's informative to give them some clue about what those role names mean. See comparison screen shots below.

In what follows, anything prefixed by `[RH]` is a help field from the Role Help module. No-prefix description is what you get with this module.

So first, let's compare the admin Roles listing. First, this module:

![roles_patch](https://user-images.githubusercontent.com/29214084/208010039-5ac0c9e6-e465-4927-b9e6-b32d8205cc8e.jpg)

Next, with Role help enabled:

![roles_rh](https://user-images.githubusercontent.com/29214084/208010088-9cc4fbdb-6426-4aec-98f5-3302959ce137.jpg)

With RH enabled, it takes over the display of the roles, using its own information.

Now, the configuration page for a role. First, this patch (for the anonymous role):

![configure_patch](https://user-images.githubusercontent.com/29214084/208010314-91d1c3ed-6096-4cf3-8471-86b3a7d4fc21.jpg)

Next, configure page with RH enabled.

![configure_rh](https://user-images.githubusercontent.com/29214084/208010464-3d83c2bf-d9a1-4e2c-a2e7-c7c85f200974.jpg)

We see both fields, those from this patch, and those from RH. Saving does save all of the information.

The last thing to compare is what one sees on the user edit page. Since RH has a summary field, we see that here with RH enabled:

![user_rh](https://user-images.githubusercontent.com/29214084/208010749-5f75d782-863d-4897-8474-a59ed76a5793.jpg)

With RH disabled, we just see the role names, no summaries:

![user_patch](https://user-images.githubusercontent.com/29214084/208011016-ae0630cd-ebdc-4934-b909-6cd47d8de40f.jpg)

I think the summary information is useful to provide to users, and so would like to suggest that a `summary` field be added to this PR.

At that point, the PR would offer pretty much everything that RH offers. (RH also offers a separate admin page listing the roles, but that's not really needed since the description already appears on the admin role page under this PR.) So we could provide a more graceful path for users  by copying the data from the `role_help` table into config via an update hook.

Alternatively, since there's only a handful of users of Role Help, we could also just add an update hook to that module that copies the data from the table into config and then disables the module (or suggests that the admin disable it), since it would no longer be needed. Then core would not need to include any Role Help-specific update code. But we (I) would probably need to have the updated version of Role Help module ready when 1.24.0 comes out so that both could be updated together.

**Comment by quicksketch** [comment] 2022-12-16 22:03
Thanks @bugfolder for this audit! Role Help's descriptions on the fields are a little confusing to me, since it says both fields are shown when editing a user's profile. Which one is actually used?

**Comment by bugfolder** [comment] 2022-12-16 22:40
Yeah, I noticed (with the benefit of fresh eyes, not having looked at it in a long time!) that the description wasn't clear.

Checking again, the `summary` is listed on BOTH the user edit page and on the Roles listing page. The longer `description` field (which is field `help` in the role_help table) shows up on the RH-specific listing of roles (a separate page, not the core Roles page) and on the RH-specific Roles tab of the user account.

So I was a bit confused above! (Hey, I only ported the module, didn't design it). Since RH is using the same `summary` information on both the user edit page and the admin Roles page, the longer `description`/`help` field is only used on the pages that are RH-specific (and I'm not advocating adding those new pages to core); so I guess we could go with a single field after all.

Although, I would just toss out for consideration whether it would be be useful to have separate description text on the user edit page and the admin page. The text shown to the user could be briefer and more function-oriented, while the admin information might be lengthier and more helpful to a site architect. For example, for the user:

Editor — this role allows you to create new stories on the site.

For the admin:

Editor — give this role to anyone who creates stories. It will allow them to post any HTML without further moderation.

But that's just a thought, not a strongly urging.

**Comment by kiamlaluno** [comment] 2022-12-17 08:49
I think that the admin page could have a different description, as that page is for users who assign roles to users. There should be information useful for them to give the correct role, for example information useful to understand the difference between two roles that could seems closer than they are.

**Comment by klonos** [comment] 2022-12-21 15:48
I'm also in favor of allowing for both a long description (for use in the roles listing page) and a short description (for when people are assigning roles to user accounts). We have a similar paradigm with blocks actually, where we provide an "Admin label" and an "Admin description":

<img src="https://user-images.githubusercontent.com/2423362/208944541-019097dd-cd9d-4cee-b1ef-4558d5fe3874.png" width=50%>

I think that calling these "admin description" and "help text" would make sense.

If the UI seems overwhelming, then I'd suggest that we consider either a collapsed fieldset that holds these fields, or follow the checkbox paradigm that Views UI uses in `admin/structure/views/add`:
<img src="https://user-images.githubusercontent.com/2423362/208945075-7a79875a-62b1-4eb4-ac92-87fb913aaeac.png" width=25%>
<img src="https://user-images.githubusercontent.com/2423362/208945356-d9f677a8-f8c1-4bdb-b901-57df7c5b5c06.png" width=40%>

PS: we are using the same (but reverse) checkbox paradigm in `admin/config/system/site-information` for the "Use the logo supplied by the active theme" and "Use the shortcut icon supplied by the active theme" options too.

**Comment by bugfolder** [comment] 2022-12-23 00:15
Follow-up to today's Dev discussion of how to handle migration from `role_help` module. One of the things we discussed was potentially having Backdrop Core copy the information from the `role_help` table into the new core field(s). That could be problematic for those migrating from D7, because of the changes in role handling (no more `rid`, now use `role`). The `role_help` module takes care of that conversion durings its `hook_update_1000()` call. So it might be cleaner to leave the copying of `role_help` data into the (new) core fields to another `role_help` update hook that can be guaranteed to run after the conversion of the `role_help` table.

So, for D7 upgraders, they would install the (new) Role Help module into their Backdrop site, then run updates as usual, which would move all their Role Help descriptions into the new core Backdrop fields.

For existing Backdrop sites, they would update their Role Help module to the new version, whose update would copy the fields from the `role_help` table into the new core field(s).

And for those who updated their Backdrop site but not the Role Help module, they would still see extra fields on the role edit page (both core and Role Help), but it wouldn't create any harm (beyond possible confusion).

**Comment by quicksketch** [comment] 2022-12-29 03:32
I updated my PR at https://github.com/backdrop/backdrop/pull/4271

* Fixed PHP notices
* Added test coverage
* Split the single `description` into `admin_description` (Admin description) and `description` (Help text). Which matches terminology in other places like Layout, Views, and Field module.
* Added upgrade path if `role_help` module is installed. Copies the `summary` value into _both_ description and admin_description to preserve the current behavior of Role Help.
* The "help" property of Role Help module that previously showed a dedicated page is _not_ included. If Role Help wants to continue providing that page in a new version, that might be a good use for the module, but I think the 90% use-case here is getting the shorter descriptions displayed (which core now does).

I wrote a draft of a changelog as well that we can link to from the update hook: https://docs.backdropcms.org/change-records/user-roles-now-have-descriptions-role-help-module-in-core (logged-in account required since it is unpublished).

**Comment by klonos** [comment] 2022-12-29 06:06
Thanks @quicksketch ...code looks good, but the linter is complaining about a few things still.

> If the UI seems overwhelming, ...

That is not the case with the role create/edit forms, since they previously only held the role name field (and possibly the machine name field if people edited it manually). With the two description fields added, it still feels fine.

Adding the descriptions in the role names in the headers of the permission tables is a nice touch, although kinda "hidden feature" if you don't know it's there. We could style these with a dotted underline as a sort of "hover over me" hint perhaps, but can be a follow up.

**Comment by bugfolder** [comment] 2022-12-29 15:22
Added a follow-up issue in Role Help module: https://github.com/backdrop-contrib/role_help/issues/3.

**Comment by quicksketch** [comment] 2022-12-29 21:33
Discussed in dev meeting: We need to accomodate for non-upgraded Drupal 7 role names like 0 and 1 instead of anonymous and authenticated.

**Comment by quicksketch** [comment] 2022-12-30 01:14
PR updated to account for numeric role IDs "1" (anonymous) and "2" (authenticated) if present in the `role_help` database table.

I think all remaining PHPCS warnings are unrelated to this issue (unmodified lines by this PR).

**Comment by bugfolder** [comment] 2022-12-31 02:54
Applied the PR patch to a site that had Role Help installed with many roles defined.

* Update proceeded fine, with the "Backdrop core now provides most of the functionality of Role Help module..." warning message shown at the end of update.
* Roles listing at admin/config/people/roles still shows the Roles Help data and format (as expected).
* Disabled Role Help module.
* Roles listing at admin/config/people/roles now shows the new format, and is still showing the short descriptions that had been in the Role Help module.
* Selected "Configure" for a role. Both the short and admin descriptions show the same information, which was the short description from the Role Help module.

Summary: it's doing what it's supposed to do.Testing-wise, WFM, LGTM.

**Comment by bugfolder** [comment] 2022-12-31 03:10
Also did an update on an ordinary site without Role Help. The four standard roles all got their descriptions on the Roles listing. On the user edit page, I don't see descriptions for the roles. Wasn't that part of the intended behavior?

**Comment by quicksketch** [comment] 2022-12-31 05:29
> I don't see descriptions for the roles. Wasn't that part of the intended behavior?

The current implementation only adds admin-descriptions, not descriptions on the user account form. Only users moving from role_help maintain the current user account form descriptions. Both approaches keep things as similar as possible to the current implementation, though we definitely could add user account form descriptions for new sites; I just didn't know exactly how people would want to use these public descriptions.

**Comment by klonos** [comment] 2022-12-31 08:26
Yeah, while testing the PR sandbox and trying to see that from a new user's point of view, I kinda expected at the very least a short description for the "odd" there-but-locked authenticated role. 

<img src="https://user-images.githubusercontent.com/2423362/210130342-a0bf7403-21b1-41fe-a80a-24b0b3268753.png" width=35%>

On freshly-installed sites, the editor and admin roles are kinda self-explanatory, but can we add a description for "Authenticated" at the very least? ...something along the lines of:
> Automatically assigned to everyone that logs into the site.

I believe that the word "automatically" in the help text would do a good job explaining why the role is there, but cannot be removed.

Other than that, I'd be happy to RTBC this, especially after @bugfolder's testing 🙏🏼

**Comment by quicksketch** [comment] 2023-01-01 00:38
Here are the descriptions I came up with:

* Automatically assigned role to all accounts.
* Permission to create and edit content.
* All permissions, including the ability to assign roles.

![image](https://user-images.githubusercontent.com/100206/210158260-38fc71f3-1740-4703-81e7-0006c0ce1bef.png)

This iteration I changed it to add the descriptions even on upgrades, so existing sites with these roles will now receive descriptions.

**Comment by jenlampton** [comment] 2023-01-03 01:09
Saying that the admin role receives "all permissions" makes me nervous, since that does not actually describe the admin role, it describes the "Administrator role" setting.

I think it would make sense to append something to the description for whichever role has this setting, but we shouldn't use it for a default value. As soon as I change the "Administrator role" setting so that my "developer" role gets all the permissions, this description becomes incorrect, and is likely to cause confusion and frustration down the road. 

If we changed it just a tiny bit to something like `Elevated permissions, including the ability to assign roles.` that would make me feel a lot better. I'll post some alternatives for consideration.

Since the short versions are intended for editors who don't need to know about the "Administrator role" setting, I have moved the "elevated permissions" bit to the longer Admin description.

Short versions:
* Anonymous: `Automatically assigned.` 
* Authenticated: `Automatically assigned to all accounts.`
* Editor: `Permission to create and edit content.`
* Administrator: `Permission to manage the website structure and configuration.`

Long versions: 
* Anonymous: `Special role assigned to any visitor that is not logged into the site.`
* Authenticated: `Special role assigned to all accounts. Permissions assigned to this role are given to all other roles except the anonymous role.`
* Editor: `Role that can edit most content on the site, but cannot modify site configuration.`
* Administrator: `Role that receives elevated permissions, including site configuration and the ability to assign roles.`

**Comment by quicksketch** [comment] 2023-01-03 01:40
The new descriptions seem fine, but one thing that is unclear is whether an Administrator can edit content. From the descriptions, it might seem as though Administrators can only manage configuration and not modify content.

> Saying that the admin role receives "all permissions" makes me nervous, since that does not actually describe the admin role, it describes the "Administrator role" setting.

I don't think the potential for discrepancy between the admin role setting and the Administrator account is much of a problem. Descriptions throughout Backdrop can become incorrect if you modify other configuration, like the descriptions on default content types and views.

For what it's worth, the update hook matches on the admin role setting, not on the role named "administrator". So if an existing site has a different setting (such as a "Developer" role), that role that will receive the current description of "all permissions".

**Comment by klonos** [comment] 2023-01-03 01:42
Counter suggestion for the short descriptions:
- Editor: Can create and edit content.
- Admin: Can configure the site, including managing permissions and assigning roles.

**Comment by jenlampton** [comment] 2023-01-03 01:55
I like those too :)

**Comment by jenlampton** [comment] 2023-01-03 02:10
> Admin: Can configure the site, including managing permissions and assigning roles.

On second thought, Admin's don't usually manage permissions, but they do almost always assign roles. 

Adding "managing permissions" may be another example of not describing the role itself, but instead, describing the permissions that are assigned to that role *at install time*.

Keep in mind that people who are changing things on the permission matrix are not going to come back and edit the role descriptions. We should try to build something that's going to remain useful, and if we add things that are likely to be inaccurate, that could actually end up being a real pain point for people.

**Comment by jenlampton** [comment] 2023-01-03 02:12
> On second thought

On third thought, we don't need to get the text exactly right tonight. Small string changes like this could get in after code freeze!

**Comment by quicksketch** [comment] 2023-01-03 02:30
I incorporated combined suggestions for the role descriptions:

* Authenticated: Automatically assigned to all accounts.
* Editor: Can create and edit content.
* Administrator: Can manage content and configuration, including the ability to assign roles.

![image](https://user-images.githubusercontent.com/100206/210293035-4d864573-8b29-4a4c-bdd8-cc4f714bbd48.png)

I left admin descriptions as-is.

**Comment by klonos** [comment] 2023-01-03 02:31
Yeah, lets jus go with that as "good enough for now", and iterate (if needed) before final release as @jenlampton said 👍🏼

**Comment by quicksketch** [comment] 2023-01-03 03:10
I merged https://github.com/backdrop/backdrop/pull/4271 into 1.x for 1.24.0. Thanks everyone for your feedback and reviews!

**Closed** 2023-01-03 03:09 UTC
Labels: status - has pull request, status - fixed, needs - documentation, needs - translation update

**Comment by jenlampton** [comment] 2023-01-12 21:38
> I incorporated combined suggestions for the role descriptions:

I think you actually applied that text to the help, not the descriptions. I found a problem with the description and filed a follow-up issue: https://github.com/backdrop/backdrop-issues/issues/5930
