### ISSUE TITLE
Fix Views > Random sort

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1909] opened 2016-05-20 05:58 UTC
![firefox_screenshot_2016-05-20t05-57-39 434z](https://cloud.githubusercontent.com/assets/2385329/15418567/9a3a4294-1ea3-11e6-9062-9511978028bc.png)
What are they going to change...?

Suggest removing this checkbox from Global: Random views sort criteria.

---
PR by @BWPanda: https://github.com/backdrop/backdrop/pull/2396

**Comment by BWPanda** [comment] 2016-05-20 06:01
![firefox_screenshot_2016-05-20t06-00-31 648z](https://cloud.githubusercontent.com/assets/2385329/15418639/046a08de-1ea4-11e6-9f31-045284bb68d1.png)
While we're at it, let's remove the '(asc)' label which makes no sense.

**Comment by BWPanda** [comment] 2018-11-28 20:08
Made a simple PR that fixes this.

**Comment by klonos** [comment] 2018-11-28 23:40
Checking the "Expose" option in D7 does actually expose this as a drop-down menu, but "Random" is the only option it offers:

![screen shot 2018-11-29 at 10 35 46 am](https://user-images.githubusercontent.com/2423362/49189513-c9399800-f3c2-11e8-8e17-bc9e9aa776a8.png)

In Backdrop, checking the "Exposed" option does noting. In fact, if you click the sort to configure it again, you will see that the checkbox is unticked. So yeah, all kinds of weirdness here. Good catch @BWPanda 👍

**Comment by klonos** [comment] 2018-11-28 23:55
The PR is looking good @BWPanda 😉 ...I have reviewed and approved it, but also left a small comment for consideration.

Another thing to consider is to perhaps skip the settings dialog for this sort entirely. Here's what the user gets now:

![screen shot 2018-11-29 at 10 45 50 am](https://user-images.githubusercontent.com/2423362/49189984-92fd1800-f3c4-11e8-9e75-c5a8dea25d05.png)

...and when the "more" fieldset is expanded:

![screen shot 2018-11-29 at 10 45 57 am](https://user-images.githubusercontent.com/2423362/49189994-a14b3400-f3c4-11e8-9379-d41d3862a1d9.png)

I cannot think of any reason why someone would want to add the randomize sort more than once, so not sure how useful the admin label is. I would even go as far as to suggest to not show this as an option if it has already been added once:

![screen shot 2018-11-29 at 10 53 21 am](https://user-images.githubusercontent.com/2423362/49190108-16b70480-f3c5-11e8-921d-824285ff2d33.png)

...but please feel free to ignore me and consider this RTBC if these are either to much trouble to implement, or simply do not make sense 😄

**Comment by BWPanda** [comment] 2018-11-30 06:09
@klonos I've updated the PR as per your suggestion.

As for hiding the settings form, I don't think so as some people might be used to specifying a custom admin title for their fields, sorts, etc. (even if they only add it once) and this would prevent that.

As for preventing adding the same sort twice, I don't think other sorts are prevented from being added more than once, even though to me it seems just as ridiculous to, say, add 'Sort by title (asc)' twice...

**Comment by klonos** [comment] 2018-11-30 12:08
Thanks @BWPanda. The PR still looks OK. I have a minor concern about the coding standards re the single-line functions, but I see that this is how it is implemented in other handler files (https://github.com/backdrop/backdrop/blob/1.x/core/modules/views/handlers/views_handler_sort.inc#L237 for example). I'll let another person review and make the final decision, but other than that, it is RTBC form me.

PS: perhaps I'll file a separate issue to deal with not allowing sorts to be added multiple times.

**Comment by stpaultim** [comment] 2018-11-30 21:36
I just ended up here because none of the "exposed" sort options I tried were working. I went ahead and applied this patch (PR) to an existing site (v. 1.12) and tested it for what it is intended.

I tested and after applying the patch, the option to expose a random sort goes away. I did not test this any further than that. I hope that is helpful.

**Comment by klonos** [comment] 2018-11-30 22:12
I have thought about this a bit more, and I think that an exposed filter for random sorting might make sense if it was a checkbox. That way, the exposed functionality for the random sorting would become an on/off thing (either randomise the sorting, or not). Perhaps we should implement it as such instead of removing it completely. What do you think @BWPanda?

>As for preventing adding the same sort twice, I don't think other sorts are prevented from being added more than once, even though to me it seems just as ridiculous to, say, add 'Sort by title (asc)' twice...

I have filed #3401 as a follow-up to address that issue, and have also filed a PR for it.

**Comment by klonos** [comment] 2018-11-30 22:13
Thanks for bringing #1324 @stpaultim ...I will take a look 👀

**Comment by BWPanda** [comment] 2018-12-01 19:44
@klonos I can see your point, however making it so that an exposed sort can be turned off isn't something that we currently do anywhere (well, since I can test Backdrop's exposed sorts, I tested Drupal 7's). If we wanted to do that for the global random sort, I'd suggest doing it for others too. Maybe a separate issue for that?

**Comment by klonos** [comment] 2018-12-02 11:55
@BWPanda you must have missed my comment above ^^ 😄

> I have filed #3401 as a follow-up to address that issue, and have also filed a PR for it.

**Comment by jenlampton** [comment] 2018-12-06 20:57
What happens if you expose multiple sorts, like title + random. Can you switch between sort by title and sort by random? I'd like to be sure we don't loose that functionality with this change :)

**Comment by jenlampton** [comment] 2018-12-13 03:57
Perhaps a duplicate of https://github.com/backdrop/backdrop-issues/issues/1324?

**Closed** 2019-02-08 23:12 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2019-02-08 23:13
Looks great, thanks @BWPanda, @klonos, and @stpaultim! Merged https://github.com/backdrop/backdrop/pull/2396 into 1.x and 1.12.x.
