### ISSUE TITLE
[UX] Remove the "Delete" links for content types from admin bar

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#577] opened 2015-01-15 08:50 UTC
It worries me that the top item in the child drop-down for content types is "Delete".  This puts undue importance on that link.

On further investigation, there isn't even a menu link for Delete. Let's remove these.

**Comment by klonos** [comment] 2015-01-15 20:22
It might be a bit risky to have it as a top level action, I agree, but then again we do have a confirmation step before the actual deletion takes place and some people might find it handy.

We can consider either of these two things:

- Move it as a child item under "Edit". This would be consistent with the workflow of selecting the "Edit" operation from the content types list page and then the "Delete content type" button available in that form. 

- Move it as the last item in that list so it is consistent with the order of the operations drop button available for each content type in the content types list page.

Any of these solutions would reduce the "importance" of the link as it is now. One "hides" it a bit further down the rabbit hole and the other places it last on the list of available actions.

**Comment by jenlampton** [comment] 2015-01-16 05:44
I just think it's odd because no other "buttons" get a link in admin_bar. Delete also seems a dangerous one to start with.

**Comment by klonos** [comment] 2015-01-16 13:27
> ...no other "buttons" get a link in admin_bar.

We do have at least the "Structure" -> "Menus" -> [menu_name] -> "Delete menu" + other buttons as menu links.

Fair enough about the complexity concern. Though I personally prefer complexity (I actually see it as ) over having to click through forms and having to wait for the pages to load.

**Comment by jenlampton** [comment] 2015-01-17 05:29
Hm.  I think I'd like to remove all the "Delete" links :)

**Comment by CaffeinatedJim** [comment] 2015-03-22 19:02
I tried this issue, but this is harder than a "novice issue".  Removing Novice label. =)

**Comment by quicksketch** [comment] 2015-03-22 21:34
When I looked at this earlier:

- admin_bar_tree() builds the list of links, which calls `hook_admin_bar_map()`
- `node_admin_bar_map()` is invoked in the hooks list, which returns the content types path.
- `admin_bar_tree_dynamic()` then expands the path out to include all sub-links, including the delete links.

I think we might be able to fix this problem by excluding menu links of a particular type, for example excluding all MENU_CALLBACK items, but when I tried to just alter the SQL query, I started getting a bunch of PHP notices from admin bar.

**Comment by quicksketch** [comment] 2015-03-24 04:37
It looks like this works, but breaks the breadcrumbs (as indicated in the Travis tests). I'm not sure if this is going to be an easy fix or not, but I don't think MENU_CALLBACK items normally work with breadcrumbs. We might take the approach of applying this patch but filing another issue. Thoughts?

**Comment by serundeputy** [comment] 2015-03-24 22:37
either way is fine with me, but I'd lean towards merging and opening a fresh issue.
~Geoff

**Comment by quicksketch** [comment] 2015-03-24 22:42
In that case, could you file a new issue. Then update the PR to comment out the current test that's failing and link to the new issue with a `// @todo ` code comment above the commented-out test?

**Comment by serundeputy** [comment] 2015-03-24 22:43
of course.  will do.

**Comment by serundeputy** [comment] 2015-03-24 23:38
opened: https://github.com/backdrop/backdrop-issues/issues/825
added comment and `@ todo`
`rebased`

**Comment by quicksketch** [comment] 2015-03-31 02:20
Hi @serundeputy! While I was testing this out I reviewed the new issue you created at https://github.com/backdrop/backdrop-issues/issues/825 (thanks for doing that).

I was thinking about the way this all worked and realized there may be a much simpler way of handling this that requires almost no changes and doesn't break the breadcrumbs in the first place.

From the new issue (copy/pasted here):

---

In `menu.inc`, we have the `MENU_VISIBLE_IN_BREADCRUMB` bit flag, which is separate from `MENU_VISIBLE_IN_TREE`. The normal item is just a combination of the two flags:

```
define('MENU_NORMAL_ITEM', MENU_VISIBLE_IN_TREE | MENU_VISIBLE_IN_BREADCRUMB);
```

---

So it looks like the solution that would work here (and works in my testing) is that we simply should modify the `$items['admin/structure/types/manage/%node_type/delete']` menu item to be a `'type' => MENU_VISIBLE_IN_BREADCRUMB`. This is exactly what we want, an item that is in the breadcrumb but not in the visible menu. Could you try that out and see if it works correctly for you as well?

**Comment by serundeputy** [comment] 2015-03-31 02:45
passes;
rerolled;
rebased;
repushed;
![screen shot 2015-03-30 at 10 41 42 pm](https://cloud.githubusercontent.com/assets/6763671/6911407/5790f9a0-d72e-11e4-99af-1f4a47c120b2.png)
I still don't know where the actual 'breadcrumbs' are visible .... haha :)

**Comment by serundeputy** [comment] 2015-03-31 02:53
ahhhhhgggggh;
left the `@todo` in there;
i'll take that out, rebase and repush.

**Comment by quicksketch** [comment] 2015-03-31 03:54
>  I still don't know where the actual 'breadcrumbs' are visible .... haha :)

They're in the "Breadcrumb" block, which is in the admin layout by default, but it's possible to remove it.

![breadcrumb](https://cloud.githubusercontent.com/assets/100206/6912044/bb2158bc-d71e-11e4-8241-d1d48008131c.png)

Yay, also I think the entire change to ` core/modules/admin_bar/admin_bar.inc` is now unnecessary (it may have been before as well). The *only* change that is required is setting the 'type' to MENU_VISIBLE_IN_TREE.

**Comment by serundeputy** [comment] 2015-03-31 04:02
`MENU_VISIBLE_IN_TREE` or `MENU_VISIBLE_IN_BREADCRUMB`? The latter I think.

I can take out the `admin_bar.inc` changes and test.

**Comment by quicksketch** [comment] 2015-03-31 04:04
Oh, hahah, yes the opposite of what I said. :no_mouth:

**Comment by serundeputy** [comment] 2015-03-31 04:15
thanks; I'll fix that up tomorrow;  

those breadcrumbs visible the whole time were they not?

**Comment by quicksketch** [comment] 2015-03-31 04:40
> those breadcrumbs visible the whole time were they not?

They disappeared when we changed the type to MENU_CALLBACK, which is what caused the test failure.

Thanks!

**Comment by serundeputy** [comment] 2015-04-01 00:25
removed `admin_bar.inc changes`.
set `MENU_VISIBLE_IN_BREADCRUMB` in `node.module`
travis testing.

**Comment by quicksketch** [comment] 2015-04-01 02:44
Hooray, looks like we have a winner in https://github.com/backdrop/backdrop/pull/790. :smile:

**Comment by serundeputy** [comment] 2015-04-04 02:42
I tagged for 1.0.6 milestone.  Remove if I've misstepped.

**Comment by quicksketch** [comment] 2015-04-04 23:29
> I tagged for 1.0.6 milestone. Remove if I've misstepped.

I think that's fine. This isn't exactly a "bugfix" but it's also not a feature. Keeping our updates synced between versions will make management easier.

**Comment by quicksketch** [comment] 2015-04-04 23:32
Merged in https://github.com/backdrop/backdrop/pull/790. Thanks @serundeputy!

**Comment by klonos** [comment] 2015-04-05 09:21
Confirmed fixed. Works just fine. Thanx!

**Closed by klonos** 2015-04-05 09:21 UTC
Labels: status - has pull request, type - task
