### ISSUE TITLE
Flexbox grid not working in IE 11 and earlier

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#1973] opened 2016-06-13 15:51 UTC
As far as I can tell when testing with a browser testing service and using Bartik on Backdrop 1.4.2, the farthest right column always drops below in IE 11 and earlier. I've tested it with different default layouts--2 and 3 column layouts--and with different resolutions and they all have the same issue in IE.

Is there way to force them to use the float layout as well?

**Comment by jenlampton** [comment] 2016-06-17 00:17
I believe this is a duplicate of https://github.com/backdrop/backdrop-issues/issues/1961.  They were using the float layout, but the class names didn't match. Can you test the patch over there and let us know if it solves the problem for you?

**Comment by jenlampton** [comment] 2016-06-21 07:04
Well, this is going to be confusing, but the code that needs to be changed/updated is over in the PR for https://github.com/backdrop/backdrop-issues/issues/1962 so that's where I'm going to attempt to fix it. Sorry for the back-and fourth.

**Closed by jenlampton** 2016-06-21 07:04 UTC
Labels: status - duplicate
