### ISSUE TITLE
Remove the "Ensure the current toolkit supports the effect." comment from image_effect_definitions()

### ISSUE THREAD

**Issue by kiamlaluno** [backdrop/backdrop-issues#5720] opened 2022-08-12 11:45 UTC
[`image_effect_definitions()`](https://github.com/backdrop/backdrop/blob/1.x/core/modules/image/image.module#L1182) contains the following code.

```php
// Ensure the current toolkit supports the effect.
$effect['module'] = $module;
$effect['name'] = $name;
$effect['data'] = isset($effect['data']) ? $effect['data'] : array();
$effects[$name] = $effect;
```
The comment doesn't describe what the code is doing and it should be removed. 

Eventually, the comment should be *Make sure module, name, and data are set.* but that is probably not necessary, as that's clear from the code, except in the case we want to remember why those lines have been added.

**Comment by kiamlaluno** [comment] 2022-08-12 18:31
One of the tests for the PR fails, for PHP 8.1, but it's not related to this change. It's an exception for *is_dir(): Unable to find the wrapper "public"*.

**Comment by indigoxela** [comment] 2022-08-13 09:30
Many thanks for providing a PR :+1:

Honestly, I've no clue, either, what that comment line could have ever been good for. It just causes confusion. Removing it makes sense.

Re the failing (random) test: that looks like a temporary problem inside the workflow runner (?) - hard to debug.
If you're in doubt, whether a failing test is random or caused by a code change (which is obviously not the case here), re-running could make sense. That can be triggered by closing and re-opening a PR.

**Closed** 2022-09-14 13:27 UTC
Labels: type - task, status - has pull request, good first issue, pr - ready to be committed, milestone candidate - bug
