### ISSUE TITLE
[DX] Exclude .tests.info files from requiring a "type =" line.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1294] opened 2015-10-03 04:41 UTC
These are not modules or themes or layouts. The "right" way to do it would be to perhaps require a `type = test` line, but I say we make this optional and instead rely on the fact that these live within `/test` subdirectories.

This came up in https://github.com/backdrop-contrib/honeypot/issues/6 and elsewhere where modules would not be installed because we check and validate .info files in _every_ subdir inside a project. Lets ease DX and improve UX.

Steps to reproduce:
1)
2) 
3)

Backdrop version 1.2.2

----------
PR: https://github.com/backdrop/backdrop/pull/2491

**Comment by quicksketch** [comment] 2015-10-20 03:09
Rather than ignoring test directories, I'd recommend just stopping at the first .info file found, as suggested in https://github.com/backdrop-contrib/honeypot/issues/6#issuecomment-149414901. It will accomplish the same thing in hopefully a slightly more robust approach.

**Comment by quicksketch** [comment] 2015-10-20 03:10
Oh, that other issue is in Honeypot's queue, not core. Reopening to fix this here.

**Comment by pifbits** [comment] 2016-03-24 15:06
I'm still having the issue honeypot. Manually install via cmd/file manager works tho. it's also happening with mimemail, civicrm, and a few others.  I'm just testing config modules for now.  I'm not even at the point of dropping tables and re-importing a db-copy from the d7 production site yet.

**Comment by jenlampton** [comment] 2017-09-07 20:01
There are often test modules included in test directories, and those do need the `type = module` line to work correctly. The files that are causing problems are the ones named `*.tests.info` so can't we just stop the checker from checking those specific files?  I'm going to attempt a PR, I'll see how hard that is.

**Comment by jenlampton** [comment] 2017-09-07 22:19
I'm unable to reproduce this problem on backdrop 1.7.0 or above. Can someone confirm that it's still an issue?

**Comment by herbdool** [comment] 2017-09-08 16:40
I can't reproduce either using honeypot.

**Comment by klonos** [comment] 2018-06-29 14:50
This has now become an issue with #3105 which we are aiming to get in for the upcoming 1.11

**Comment by jenlampton** [comment] 2018-09-03 20:36
@klonos how is this more urgent because of https://github.com/backdrop/backdrop-issues/issues/3105? (no PR yet so removing milestone. We can add it back if it turns out we do really need it for core updates)

**Comment by jenlampton** [comment] 2019-01-15 20:49
Setting milestone because this is now highly important.

**Comment by herbdool** [comment] 2019-01-28 20:36
I added a PR to exclude .tests.info in the Updater class. The function was already smart enough to first try to fetch the .info that matches the directory name, and, if that didn't work, it would take the first .info file in the list. That seemed to exclude tests.info in my testing, but this PR will make sure.

I haven't been able to recreate the issue so perhaps someone else can test.

**Comment by quicksketch** [comment] 2019-02-08 22:43
That PR looks good to me @herbdool. I made a minor change to include the period in the substr() check, per @opi's comment that we shouldn't match on a string like `footests.info`.

**Comment by quicksketch** [comment] 2019-02-09 00:28
I've merged https://github.com/backdrop/backdrop/pull/2491 into 1.x and 1.12.x. Thanks for the fix @herbdool and review from @opi!

**Closed by quicksketch** 2019-02-09 00:28 UTC
Labels: pr - needs review, status - has pull request, type - bug report

**Comment by klonos** [comment] 2019-05-27 18:42
Follow-up: #3821
