### ISSUE TITLE
PHP 8.1: Deprecated function: `preg_replace()`: Passing null to parameter #3 in `system_requirements()`

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5925] opened 2023-01-12 01:07 UTC
## Description of the bug
When a custom module depends on another custom module that doesn't have a version number, PHP 8.1 throws

`Deprecated function: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in system_requirements() (line 472 of...`

This is only encountered when updating the site. 

## Steps To Reproduce

To reproduce you need two custom modules without versions, where one depends on another. Both should be enabled. Then visit `core/update.php` and see the notice.

## Actual behavior

Deprecation notice is shown.

## Expected behavior

No deprecation notice.

## Additional information

This is similar to https://github.com/backdrop/backdrop/pull/4232 (fixed), but is happening in a different place.
Backdrop 1.23.1
PHP 8.1

**Comment by argiepiano** [comment] 2023-01-12 04:27
Here are a couple of empty custom modules, module_a and module_b. module_b depends on module_a. 

Enable both and then visit `core/update`. Be sure you have PHP 8.1
[modulesab.zip](https://github.com/backdrop/backdrop-issues/files/10398186/modulesab.zip)

**Comment by argiepiano** [comment] 2023-01-12 05:05
PR https://github.com/backdrop/backdrop/pull/4306 submitted. 

This is a simple fix. The result of the fix is that $version remains an empty string when the required module has no version, which is exactly what happens with PHP 7.4, when `preg_replace()` accepted an empty 3rd argument.

**Comment by klonos** [comment] 2023-01-12 12:45
Thanks @argiepiano 🙏🏼 ...code looks good, but I can't test on the PR sandboxes, since they are running on php 7.2 (see #5926), so I'll have to test this on my local instead. Bear with me.

**Comment by klonos** [comment] 2023-01-12 13:32
...OK, tested this on my local with php 8.1.14 and was able to reproduce. I then patched my local and confirmed that the PR fixes the issue, so WFM 👍🏼

**Comment by quicksketch** [comment] 2023-01-15 03:21
Merged https://github.com/backdrop/backdrop/pull/4306 into 1.x and 1.23.x. Thanks @argiepiano and @klonos!

**Closed** 2023-01-15 03:21 UTC
Labels: status - has pull request, status - fixed
