### ISSUE TITLE
Follow up: Polish admin bar display, now that it's using SVG

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#6488] opened 2024-04-29 08:10 UTC
## Description of the task

As of  #364, Backdrop's admin bar now uses inline SVG, sized by em. :rocket: 
This is a follow-up to discuss and possibly fix the design / UX aspects (like margin).

Currently there seems to be some wasted space between the menu items, which will have impact on display on narrower screens.
And the admin bar's slightly higher, too, which may affect custom themes (for example, if they have a fixed menu bar).

For comparison:

![wasted-space](https://github.com/backdrop/backdrop-issues/assets/842066/3e1b11bd-90aa-4cbe-b127-53e56cc96070)

**Comment by klonos** [comment] 2024-05-02 07:45
Rehashing what I said in #6495 (which I'll be closing as a duplicate of this issue here shortly)...

With #364, the admin bar icons have increased size, which is good for UX (larger area to interact with is better on touch-enabled devices), however there is now too much left/right padding as well (`1.5em` and `1em` respectively). That causes the the following:
- icons appear too far from each other visually (this is just aesthetics and subjective opinion)
- increase of mouse "travel time" when moving horizontally across the admin bar
- decrease of the width that causes reaching the breakpoint that switches the admin to mobile version

Some screenshots for visual:
- Before:
  ![image](https://github.com/backdrop/backdrop-issues/assets/2423362/6f0c8ee3-4fdd-4548-81f7-58bd16fb6672)
- Now (`1.5em` left and `1em` right padding):
  ![image](https://github.com/backdrop/backdrop-issues/assets/2423362/a2008021-fff3-4581-9c51-2c5875c6b58f)
- Proposed (`1em` and `.5em`):
  ![image](https://github.com/backdrop/backdrop-issues/assets/2423362/4ad0aefe-2772-4087-b53a-6965f62959d0)

Perhaps we should decrease the padding even further(?)

**Comment by indigoxela** [comment] 2024-05-02 10:28
@klonos I'd suggest to start with a pull request. It's always easier to decide, if people can look at something "real" on their devices with their familiar screen resolution (in the sandbox). :wink:

**Comment by klonos** [comment] 2024-05-02 22:07
@argiepiano this is the issue you are looking for 🙂

**Comment by indigoxela** [comment] 2024-05-03 05:57
Here we go, a [PR](https://github.com/backdrop/backdrop/pull/4728) is available for testing and review.

It reduces the width of menu items. Although it's still wider than the old one, it's more compact now.

It also reduces the height of the admin bar to fit the previous height, to reduce the impact on existing themes, custom or contrib, that use a fixed navigation bar on their own ([Scenery](https://backdropcms.org/project/scenery), for example).

**Comment by klonos** [comment] 2024-05-03 11:36
@indigoxela I wanted to quickly say that I like it 👍🏼 ...I'll return with more useful feedback.

**Comment by klonos** [comment] 2024-05-03 11:39
...here's a quick thought though: could we add be adding the height of the admin bar dynamically into a `data-*` attribute, in a way that would allow themes to also dynamically adjust their offsets as the admin bar height increases/decreases? (follow-up - just a thought that I wanted to document somewhere quickly)

**Comment by indigoxela** [comment] 2024-05-03 11:59
> ... could we be adding the height of the admin bar dynamically into a data-* attribute...

Did you mean a CSS variable? (Instead of data attrib) That might be helpful for theming. No idea, if that's feasible. We could explore it in a follow-up.

**Comment by argiepiano** [comment] 2024-05-03 12:33
I like it! Thanks @indigoxela! I'll let subthemers and UI experts opine. To me, it looks good ;)

**Comment by quicksketch** [comment] 2024-05-04 04:00
> in a way that would allow themes to also dynamically adjust their offsets as the admin bar height increases/decreases? (follow-up - just a thought that I wanted to document somewhere quickly)

Themes already don't need to do anything to adjust the admin bar height. The body margin (or border actually) is adjusted by admin_bar.css. The only thing they need to _not_ do is override the provided border:

```
.admin-bar body {
  border-top: 2.25em solid #2D2D2D !important;
}
```

That said, we could use set a variable to let themes know how tall the admin_bar is.

I sort of liked the larger admin bar height but I can accept this compromise that we retained the larger font size while keeping the height the same.

**Comment by klonos** [comment] 2024-05-04 04:05
> That said, we could use set a variable to let themes know how tall the admin_bar is.

Yes. That.

**Comment by indigoxela** [comment] 2024-05-04 04:37
> Themes already don't need to do anything to adjust the admin bar height.

@quicksketch not the height, that's right, but if themes (or modules) place something (also positioned) right under the admin bar, they do have to consider the actual admin bar height for that. That affects one of my contrib themes and may affect custom themes, too. That's why I reduced the height, so the impact of the change is less likely to cause visual glitches.

**Comment by quicksketch** [comment] 2024-05-04 05:17
@indigoxela Would using a CSS property help to avoid this problem in the future maybe? I filed a PR against yours to see if that would be a good idea: https://github.com/indigoxela/backdrop/pull/6

The icon system is entirely dependent on CSS properties, so maybe we should lean into them and expose things like this that would be particularly helpful for themes and modules. Both `var()` and `calc()` are "baseline" CSS capabilities of all browsers at this point (fully supported since 2017) according to caniuse.com.

**Comment by indigoxela** [comment] 2024-05-04 05:26
> Would using a CSS property help to avoid this problem in the future maybe?

It might. :thinking: What I particularly like about your suggestion (PR) is, that we switch from a "magic number" to a named var. Good for themers, but also good for our future selfs. :wink: Will play with it locally.

**Comment by indigoxela** [comment] 2024-05-06 12:56
Based on the suggestion by @quicksketch we're now using the property `--admin-bar-height` to make it easier for themes to use this like: `top: var(--admin-bar-height);` to automatically get the right value for positioning something right below the admin bar.
Visually, there's absolutely no change, just an easier access to the height and no more need to remember the px value, or updates, if the value changes.

Thoughts?

**Comment by indigoxela** [comment] 2024-05-07 15:07
> My previous comment was premature. Further testing the --admin-bar-height and increasing it does not adjust the whole admin bar display

@izmeez  Sorry, but it's not supposed to do that. Why are you assuming, it would? It's a value, that's supposed to be informational only. Not to adjust it.

And as adjusting via single var isn't actually in the scope of this issue here - should I revert this change? It seems to be confusing.

**Comment by olafgrabienski** [comment] 2024-05-08 11:26
I've applied the PR on a test site. It works really good for me in getting a lot of important space in the admin bar back.

For comparison I'm listing how wide a screen must be to display the different admin bar modes. Tested with English interface and with all components (search bar, language switcher, etc.) enabled:

**Full menu** (depends on username length)

- 1.28 pre: 1786px
- with PR: 1559px

**Normal menu + More tasks**

- 1.28 pre: 1238px
- with PR: 1086px

**Hamburger menu + More tasks**

- 1.28 pre: below 1238px
- with PR: below 1086px

**Comment by indigoxela** [comment] 2024-05-08 12:33
@olafgrabienski many thanks for also testing, and for review. I added the leading zeroes.

**Comment by indigoxela** [comment] 2024-05-08 14:09
> This comment is clearly beyond the scope...

:joy: oh, really? :wink: 

Via settings.php, via admin UI, leave it to contrib... a lot to discuss, which should better be done in a different issue. At least, that's what I'd suggest.

**Comment by quicksketch** [comment] 2024-05-09 04:10
Code-wise and visually this looks good to me. IMO it's a little tight but multiple people have said that the admin bar collapsing earlier for them is not desirable. It's a good compromise to keep the font size at 12px but tighten up the spacing.

**Comment by indigoxela** [comment] 2024-05-09 05:42
> IMO it's a little tight...

Yes, it's a compromise to avoid the "premature hamburgerization" :wink: of the menus in the admin bar. Design-wise the initial change looked very good (nice distinction between items), but... :shrug: 

@quicksketch I commited your requested comment change.

**Closed** 2024-05-09 17:27 UTC
Labels: type - task, status - has pull request, design, status - fixed

**Comment by quicksketch** [comment] 2024-05-09 17:29
Thanks @indigoxela! I merged https://github.com/backdrop/backdrop/pull/4728 into 1.x for 1.28.0. We can revise again if we have the will for further adjustment. Thank you @herbdool, @olafgrabienski, @izmeez, and @klonos for your feedback and review!
