### ISSUE TITLE
Layout no sidebar doesnt expand contents to fit page

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#596] opened 2015-01-16 23:40 UTC
The two column and two column flipped layouts maintain the 70/30 width between main and sidebar region even when there is no sidebar content.

**Comment by quicksketch** [comment] 2015-01-17 00:24
Hi @docwilmot! This was actually intentional functionality; a layout stays the same even if there isn't any content in that region. The 3/3/4 layout *does* still have the collapsible behavior, but it was to provide compatibility with Drupal 7's Bartik layout. 

Let's start a discussion around which behavior is most desirable: collapsible regions or static ones.

**Comment by jenlampton** [comment] 2015-01-17 04:05
The intention was to have the layouts stay the same on all pages. If you have a page with no sidebar, that's really a different layout. (works as designed - so closing)

If you want to have a region expand to fill the space you have a few options: 
1) In your theme you can add whatever css is necessary to your custom style sheet to restore the auto-expand behavior of Drupal past.
2) Override that layout stylesheet entirely by adding one with the same name in your theme.
2) Create a new similar layout that's fluid instead of fixed (or whatever you want to call it)

**Closed by jenlampton** 2015-01-17 04:05 UTC
Labels: status - has pull request

**Comment by docwilmot** [comment] 2015-01-17 11:42
I disagree but I guess this is final.

**Comment by klonos** [comment] 2015-01-17 18:34
FTR, I disagree too.

**Comment by jenlampton** [comment] 2015-01-18 04:36
This magic-sidebar behavior became standard in Drupal because we had only one layout for the whole site, so it needed to adjust because our layouts would be so broken otherwise. When we have the ability to select different layouts for different pages (either with Drupal + panels, or with Backdrop) we don't need the magic-sidebar trick anymore. 

The trick is problematic because there was no way you could have a page with an empty sidebar, even when you needed one.  

Let's take the use-case of a blog site that puts ads in the sidebar, and say you have one blog post that has no advertisers. It creates a very strange user experience to have the layout jump from with-sidebar to without-sidebar on this one post.

It's also important to keep in mind that usability decreases when lines of text get too long.  Reading a line with 75-100 characters is what's comfortable for the eye (on the web anyway, print still claims 75chars or less),  But if a line of text goes from the left-side of a desktop monitor to the right these days, it can be pushing upwards of 200 characters. That's just too long!

So, in the interest of creating better websites as well removing Drupal-specific tricks, we decided this magic-sidebar of Drupal past needed to go.

However, If enough people want the magic-sidebar, there's no reason we can't add one (or two?) new layouts that have them in the future!  (Disagreement noted ;)

**Comment by klonos** [comment] 2015-01-18 05:16
Fair enough Jen. Thanx for taking the time to explain things.

**Comment by docwilmot** [comment] 2015-01-18 12:53
Not so sure. I imagine that folks will expect this behaviour (since theyre coming from Drupal mostly. I thought it was a bug, hence the PR.

> The trick is problematic because there was no way you could have a page with an empty sidebar, even when you needed one.

This works:
```
.layout--two-column-flipped.layout-no-sidebar .l-content {
margin-left: 30%;
width: 70%;
}
```
On the other hand, the current design may be preferable to some, plus the line length advantage you mention. Perhaps as a compromise we could add the preprocess so the no-sidebar class still appears, but dont change the CSS. Then in the README a note that suggests how to make the sidebar magical again.
