### ISSUE TITLE
[A11Y] Label for managed_file applied to the wrong HTML element.

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5968] opened 2023-02-09 04:15 UTC
## Description of the bug

The label for managed_file Form API elements is applied to the wrapping `<div>` rather than to the `<input>` element.  In the image below, notice that the label `for` attribute points at `edit-image-example-image-fid`, which is the ID of the `div`, instead of pointing at `edit-image-example-image-fid-upload`, which is the ID of the `input` element

<img width="903" alt="Screen Shot 2023-02-08 at 9 03 01 PM" src="https://user-images.githubusercontent.com/9938978/217715038-1d6ccf1e-46b6-44e6-8a0c-9aa6088667ae.png">

## Steps To Reproduce
You can reproduce with any Form API `managed_file` element. For example:

1. Install the module `examples` (https://backdropcms.org/project/examples)
2. Enable `image_example`
3. Visit `/image_example/styles`
4. Open the browser console and inspect the Image upload widget (which is a Form API `managed_file` element).

## Actual behavior
The label `for` attributes points at the ID of the `div`

## Expected behavior

The label `for` attribute should point at the `input` element ID, not the wrapper `div`, as per this [Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#labelable) (scroll to "labelable").

## Additional information

This is related to the D7 issue https://www.drupal.org/node/2594955. The main bug fixed in that issue (duplicate ID) has already been  fixed in Backdrop. But a related bug, which that issue fixed in D7, was the label `for` attribute. That particular fix never made it into Backdrop.

The solution used in D7 was to create a new theme property `#label_for` in `theme_form_element_label()`. This new property is used in D7's `file_managed_file_process()` to pass the correct ID for the `label`.

A similar solution would work in Backdrop.

**Comment by argiepiano** [comment] 2023-02-09 04:21
I believe this also has implications for accessibility, so it could be labeled [A11Y].

**Comment by argiepiano** [comment] 2023-02-09 04:55
PR https://github.com/backdrop/backdrop/pull/4331

Coding standard error `/bin/sh: 1: phpcs: not found`. This is the second time I see this in two separate PRs in the last 24 hours.

**Comment by argiepiano** [comment] 2023-02-10 13:40
Hi @klonos.

> any specific reason why you have not mimicked more closely the respective change in

I had explained this in the "Additional information" section above, but perhaps it's not clear there. The main part of the Drupal issue and fix was to take care of a bug that doesn't exist in Backdrop  (duplicated HTML ID). That was fixed in B some time ago, before the D7 fix. I cherry-picked the part that had not been cross-ported (the part that pertains to the label `for` attribute). 

So, most of the code of the D7 fix is not needed - also B's function there has diverted from D7's in pretty substantial ways.

All of the above is why I marked this D7 issue as NA in the task list #5770, but made a note "see #5968") to call attention to the fact that this is related.

**Comment by bugfolder** [comment] 2023-09-18 21:07
Tested. Installed the Image Example module, viewed `image-example/styles` page, confirmed the error described above.

Applied the diff, re-inspected that page; confirmed that the label has the proper `for` attribute:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/6a7d357b-6f17-48f3-9a45-7205fe940cc7)

There are PHPCS coding standards errors, but they don't relate to code in this PR. Functional tests all passed.

Code reviewed, LGTM.

**Comment by laryn** [comment] 2023-10-06 11:43
Thanks @argiepiano for catching and fixing, and @bugfolder and @klonos for reviewing in various capacities! Merged in `1.x` and `1.26.x`.

**Comment by klonos** [comment] 2023-10-06 17:49
Sorry to reopen this, but from the screenshot above provided by @bugfolder I see a discrepancy in the `for` attribute vs the id attribute of the input element. `for` has a value of `edit-image-example-image-fid-upload` vs. the input element `id`, which is `edit-image-example-image-fid-upload--2`. These two attributes need to have matching values.

**Comment by klonos** [comment] 2023-10-06 19:19
Follow-up PR that works for me here: https://github.com/backdrop/backdrop/pull/4536

**Comment by laryn** [comment] 2023-10-06 20:26
Good catch @klonos -- looks like a good fix. Tugboat failed and unfortunately I can't set up locally right now but the code looks good.

**Comment by klonos** [comment] 2023-10-06 20:32
Yup, saw that now. Restarting it and will update here when it's ready for testing.

**Comment by klonos** [comment] 2023-10-06 20:47
...sorry this is taking longer than expected. cspell keept complaining about things. Test are running now. Should be good to go in about 12min.

**Comment by klonos** [comment] 2023-10-06 20:59
Ready 😉

**Comment by argiepiano** [comment] 2023-10-06 23:05
@klonos, thanks for spotting that problem and providing an alternative PR. 

Both the old and new PR have an issue we did not anticipate. Once you choose your file, the `input` element is removed, and the label therefore points at an inexistent element. So, this is a complicated problem to fix, and probably why the original `for` was pointing at the `div` rather than at the `input`. 

I'm not sure what a good solution might be. There is no ideal solution here.

<img width="515" alt="Screen Shot 2023-10-06 at 5 04 29 PM" src="https://github.com/backdrop/backdrop-issues/assets/9938978/0f85ad9a-6f66-4186-a106-a00efaf895d8">

**Comment by klonos** [comment] 2023-10-07 02:52
Good catch @argiepiano 👍🏼 ...if this is not achievable in php, perhaps we could use the same JS that updates the field when a file is uploaded to remove the `for` attribute (and re-add it if the file is removed).

**Comment by klonos** [comment] 2023-10-07 03:54
...for reference, in Drupal (10.1 at the time of writing this) they are using a fieldset (`<details>`) element to wrap the entire field:
![image](https://github.com/backdrop/backdrop-issues/assets/2423362/f4877f85-e79f-4eb4-8f54-8961c6affdba)

Here's the HTML while no image has been uploaded (without the wrapping `<details>` and reduced to only most of the things that matter in this case):
```html
<div class="js-form-item form-item js-form-type-managed-file form-type--managed-file js-form-item-field-image-0 form-item--field-image-0">
  <label for="edit-field-image-0-upload" id="edit-field-image-0--label" class="form-item__label">Add a new file</label>

  <div class="image-widget js-form-managed-file form-managed-file form-managed-file--image is-single has-upload no-value no-meta">
    <div class="form-managed-file__main">
      <input accept="image/*" data-drupal-selector="edit-field-image-0-upload" type="file" id="edit-field-image-0-upload" name="files[field_image_0]" size="22" class="js-form-file form-file form-element form-element--type-file form-element--api-file" data-once="fileValidate auto-file-upload"><input class="js-hide upload-button button js-form-submit form-submit" data-drupal-selector="edit-field-image-0-upload-button" formnovalidate="formnovalidate" type="submit" id="edit-field-image-0-upload-button" name="field_image_0_upload_button" value="Upload" data-once="drupal-ajax">
    </div>

    <input data-drupal-selector="edit-field-image-0-fids" type="hidden" name="field_image[0][fids]">
  </div>
  <div id="edit-field-image-0--description" class="form-item__description">
    DESCRIPTION/HELP TEXT.
  </div>
</div>
```

Here's after a file has been uploaded:
![image](https://github.com/backdrop/backdrop-issues/assets/2423362/03a60334-6932-4d54-a1b0-3b4c6c49fb79)

```html
<div class="js-form-item form-item js-form-type-managed-file form-type--managed-file js-form-item-field-image-0 form-item--field-image-0 form-item--no-label">
  <label for="edit-field-image-0-upload--UJ56gZAsCM8" id="edit-field-image-0--PK68HupcRQ0--label" class="form-item__label visually-hidden">Image</label>

  <div class="image-widget js-form-managed-file form-managed-file form-managed-file--image is-single no-upload has-value has-meta">

    <div class="form-managed-file__main">
      <span data-drupal-selector="edit-field-image-0-file-1-filename" class="file file--mime-image-jpeg file--image">
        <a href="/sites/default/files/2023-10/fingers-fighting.jpeg" type="image/jpeg">fingers-fighting.jpeg</a>
        <span class="file__size">(40.6 KB)</span>
      </span>

      <input ... REMOVE BUTTON ...>
    </div>

    <div class="form-managed-file__meta-wrapper">
      <div class="form-managed-file__meta">

        <div class="form-managed-file__image-preview image-preview">
          <div class="image-preview__img-wrapper">
            <img data-drupal-selector="edit-field-image-0-preview" src="/sites/default/files/.../fingers-fighting.jpeg?itok=VgyWWkIl" width="100" height="66" alt="" loading="lazy" class="image-style-thumbnail">
          </div>
        </div>
  
        <div class="form-managed-file__meta-items">
          <div class="js-form-item form-item js-form-type-textfield form-type--textfield js-form-item-field-image-0-alt form-item--field-image-0-alt">
            <label for="edit-field-image-0-alt--Ld02_RaR36g" class="form-item__label js-form-required form-required">Alternative text</label>
            <input data-drupal-selector="edit-field-image-0-alt" aria-describedby="edit-field-image-0-alt--Ld02_RaR36g--description" type="text" id="edit-field-image-0-alt--Ld02_RaR36g" name="field_image[0][alt]" value="" size="60" maxlength="512" class="form-text required form-element form-element--type-text form-element--api-textfield" required="required" aria-required="true">

            <div id="edit-field-image-0-alt--Ld02_RaR36g--description" class="form-item__description">
              DESCRIPTION/HELP TEXT.
            </div>
          </div>
        </div>

      </div>
    </div>

    <input data-drupal-selector="edit-field-image-0-fids" type="hidden" name="field_image[0][fids]" value="1">
  </div>
</div>
```

**Comment by klonos** [comment] 2023-10-07 09:36
...I was doing some research on this, and have found [#1734716: File field form label has incorrect id in @for attribute](https://www.drupal.org/project/drupal/issues/1734716), which then lead me to discover that most of the changes in @argiepiano's and my PR are already included with what went into D7 as part of [#1734716: [D7] Duplicate HTML IDs are created for file_managed_file fields](https://www.drupal.org/project/drupal/issues/1734716](https://www.drupal.org/project/drupal/issues/2594955)) with [this commit](https://git.drupalcode.org/project/drupal/-/commit/d07ae5d). So this makes this issue part of ??? as well (in the sense that won't need to backport these changes).

There's a tiny bit of that D7 commit that doesn't apply to us: the addition of `file_validate_extensions` as a JS setting via `$element['upload']['#attached']['js']` for validation purposes. We are already taking care of that via a `data-*` attribute and the changes that went into 1.4.0 core with #869 and https://github.com/backdrop/backdrop/commit/03a70011d68776632a48ea75c8ae44101dc40818.

All the above to say that we're also bring things into parity with D7 at the same time, and that the solution we are going with is what our Drupal brethren have also reviewed/tested as the most appropriate at the time.

**Comment by herbdool** [comment] 2024-01-16 22:20
The follow-up PR should have been on a follow-up issue to help this from getting confusing. I was first thinking there were two competing PRs on one issue. Now the second PR has some conflicts so should be needs-work.

**Comment by herbdool** [comment] 2024-05-03 16:26
I moved the second PR to this follow-up issue: https://github.com/backdrop/backdrop-issues/issues/6505

**Closed by herbdool** 2024-05-03 16:26 UTC
Labels: type - bug report, status - has pull request, pr - needs work, milestone candidate - bug

**Comment by klonos** [comment] 2024-05-03 23:40
...I've moved all my comments + some of other people's comments over to #6505.
