### ISSUE TITLE
[UX][D8] Add support for more link attributes in rich-text editor (id, rel, target, title)

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1777] opened 2016-04-02 22:45 UTC
While upgrading CKEditor to 4.5.5+, please add a decent link plugin.
I ported [D8 Editor Advanced link](https://www.drupal.org/project/editor_advanced_link), but it's only part of [ckeditor_addon](https://github.com/backdrop-contrib/ckeditor_addon) (it needs an updated backdropimage plugin, and of course a CKEditor library >= 4.5.5)
The anchor functionality is apparently lost again, although it can be restored with an id attribute to a link (just need a concrete text to apply the link to);
Additionally, it provides lightbox facility…
Real world screenshots : 
![capture d ecran 2016-04-03 a 00 15 26](https://cloud.githubusercontent.com/assets/15943462/14229477/279fdd40-f935-11e5-850c-3139473ed00a.jpg)
![capture d ecran 2016-04-03 a 00 13 34](https://cloud.githubusercontent.com/assets/15943462/14229478/2cbf2da8-f935-11e5-91b1-f6610b9058b9.jpg)

---
~PR by @klonos: https://github.com/backdrop/backdrop/pull/2444~
Rerolled PR by @jenlampton: https://github.com/backdrop/backdrop/pull/2638

**Comment by quicksketch** [comment] 2016-04-03 00:38
> While upgrading CKEditor to 4.5.5+, please add a decent link plugin.

We'll do these things one at a time rather than all at once in a mega issue. The upgrading issue would be first if we can get *just* the upgrade handled without bundling it with anything else in #1560.

**Comment by klonos** [comment] 2016-04-03 00:42
:+1:

**Comment by quicksketch** [comment] 2016-04-03 00:42
As for this feature itself, I'd be interested to hear from others about how extensive we should make the link dialog. This should be entirely possible through a contrib module today (without replacing CKEditor) by form_alter'ing the link dialog that we have already. Any form elements that are put into that form will automatically be applied as attributes on the anchor tag.

Here's the current (very spartan) dialog for reference:
![selection_098](https://cloud.githubusercontent.com/assets/100206/14229960/41896b94-f8fa-11e5-877c-79f3f4ce27f3.png)

**Comment by quicksketch** [comment] 2016-04-03 00:46
> As for this feature itself, I'd be interested to hear from others about how extensive we should make the link dialog.

And of course if wanted we can make things options in the text format configuration, as we do with image uploading. So you could choose what features the link dialog should have when the link button is enabled. Here's what happens when you drag in the image button for example:

![2016-04-02 17 45 02 338](https://cloud.githubusercontent.com/assets/100206/14229967/bb07a15c-f8fa-11e5-9eb8-fcb27e86cf70.gif)

**Comment by klonos** [comment] 2016-04-03 04:02
:+1: for having the options upon drag to toolbar (so that admins can limit things that they don;t want editors to be messing with), but we can always add an "Advanced settings" fieldset on our "spartan" link modal and add any additional options there + collapse it by default. That way we do not bloat the default dialog.

**Comment by gifad** [comment] 2016-04-03 12:24
@quicksketch 
> We'll do these things one at a time

Unfortunately, you can't : the backdrop plugin, the ckeditor image2 widget, and ckeditor core API are imbricated at a very low level — you can't interchange any component 4.4 <> 4.5

To make it worse, links have no material existence on the editor screen, so they must be handled, at first instance, by the object they apply to.

To make it worse, the link may be inside the object, if the image is captioned or centered, or outside if it's not…

That's the only reason why I launched a separate ckeditor_addon project !

FWIW, the cke 4.5 version of drupalimage/plugin.js was fixed by Piotrek Koszuliński himself, no one at acquia could do it !

**Comment by jenlampton** [comment] 2016-09-08 08:29
There as been no activity on this issue since last release.  Since next release is in one week, I'm bumping this to 1.x-future. 

I have added this feature to the MEAT issue for rich-text editor tasks, and those could in theory get fixed at any time. That should mitigate the decrease in urgency that will happen by removing the 1.5 milestone from this issue.

**Comment by klonos** [comment] 2016-09-08 12:24
> I have added this feature to the **MEAT** issue for rich-text editor tasks, ...

😄

**Comment by olafgrabienski** [comment] 2017-04-20 15:27
Related: #1206 - [UX] CKEditor: Allow to browse and enter links of local paths (content, users etc.)

**Comment by BWPanda** [comment] 2017-09-08 04:04
> This should be entirely possible through a contrib module today (without replacing CKEditor) by form_alter'ing the link dialog that we have already. Any form elements that are put into that form will automatically be applied as attributes on the anchor tag.

@quicksketch I started trying to work on this for my own site (and the maybe a contrib module), but immediately realised that I don't think I can do what I want...

To make this as flexible as possible (some people want to add a class, others a rel attribute, and others need to create their own attributes (see my newly-created [Featherlight](https://github.com/backdrop-contrib/featherlight) module), I thought to make a single textfield where you could add whatever attributes you want.

Something in the form of: `[attribute_key_a]=[attribute_value_a.1],[attribute_value_a.2] [attribute_key_b]=[attribute_value_b.1]`.
So then people could enter the following: `class=my-class,another-class rel=gallery data-featherlight=image`

But apparently the way this works is that form keys are automatically added as attribute keys and form values are added as attribute values. Is that correct? If so, how can I/we override this behaviour to do something like the above? This would save creating separate textfields for every possible attribute we want to add...

**Comment by BWPanda** [comment] 2017-09-08 04:57
@quicksketch Ignore that. I've played a bit more and, based on [your post here](https://github.com/backdrop/backdrop-issues/issues/1580#issuecomment-176977479) I worked out that I should be able to do what I want.

**Comment by BWPanda** [comment] 2017-09-11 06:36
I have written some code (as a part of a site-specific module on my sandbox site) that allows users to add arbitrary attributes to a link via Backdrop's editor. However, one problem I am having is that you can't seem to add boolean attributes (e.g. `data-featherlight`) as they get removed somewhere...
Any ideas how/why boolean attributes get removed?

Here's my code: https://gist.github.com/BWPanda/cbd9bd9d43eb16a8a046004f289e02c5

**Comment by bradbulger** [comment] 2018-11-26 21:01
I'm finding that even if I add an ability to add an id attribute to tags, I can't create links to it because #idstring gets converted to /base/path#idstring. I'm not sure where this problem should go? There are lots of CKEditor and link issues...

**Comment by klonos** [comment] 2018-11-26 21:49
Sorry @bradbulger, I don't quite get what you are trying to achieve and what does not work. Can you please provide detailed steps to reproduce the problem?

**Comment by bradbulger** [comment] 2018-11-26 22:39
Should I make a new issue for it, then? I just wasn't sure if that would be the right thing to do. I have assigned an ID attribute to an element in the HTML, and I am trying to use the CKEditor link button to create an anchor link to it - like `<a href="#top">go to the top</a>`. The editor link widget saves that href value as "/base/path#top".

**Comment by klonos** [comment] 2018-11-26 23:07
Yep, sounds like a bug, while this issue here is a feature request. I'd file a separate issue.

**Comment by olafgrabienski** [comment] 2018-11-27 10:10
There is a related open issue about internal anchor links via the link module: #1308. It isn't about CKEditor and there's another result if you try to use such links. However, maybe URL validation and/or encoding in CKEditor are partially based on URL validation of the link module.

**Comment by bradbulger** [comment] 2018-11-27 16:06
I haven't dug into the code yet. I expect that it's treating it like an
alias so it's part of that autocomplete system. There may be shared code
between the two issues as you say.

**Comment by klonos** [comment] 2019-01-01 10:04
With #3307 merged, I thought to give this a quick go, so draft PR up for review: https://github.com/backdrop/backdrop/pull/2444

I have moved all options inside a collapsed by default "Advanced options" fieldset, leaving only link target and link text exposed by default:

<img width="515" alt="screen shot 2019-01-01 at 11 19 13 am" src="https://user-images.githubusercontent.com/2423362/50571887-55bde880-0dbd-11e9-9bb2-f4bcafccfc36.png">

<img width="410" alt="screen shot 2019-01-01 at 12 02 34 pm" src="https://user-images.githubusercontent.com/2423362/50571891-65d5c800-0dbd-11e9-9137-ae9f9cec7f96.png">

**Comment by klonos** [comment] 2019-01-01 10:07
...everything works fine as is, but we could improve things like add validation for things like ensuring that a single word is added as ID, plus perhaps run that through `backdrop_clean_css_identifier()` same as we already do for the CSS classes value.

**Comment by quicksketch** [comment] 2019-01-02 00:05
Looks like previously we had "Link value" to contain the `href` property. Afterwards now it's "Link target". I think we should avoid the word "Target" because that's a different HTML property (the "Open in new window" checkbox sets `target="_blank"`. "Link href" would be the most accurate label, but I'm inclined to leave it as-is with "Link value".

Also, any idea why the margin between the "Link value" label and the autocomplete field has more spacing than other fields?

**Comment by jenlampton** [comment] 2019-01-02 00:17
> Also, any idea why the margin between the "Link value" label and the autocomplete field has more spacing than other fields?

```
.form-item label.editor-image-toggle {
  display: inline-block !important;
  padding-bottom: 10px;
}
```

**Comment by klonos** [comment] 2019-01-04 00:38
@quicksketch fair point about "target", and also about "href" being the most technically-accurate but at the same time not the most user-friendly.

The reason why I have changed the existing "value" was because it was not a link value per se if a path was entered in that field instead of an actual, absolute URL (internal or external). I have now done some further research on the net and have found the following definitions/descriptions for "href":

https://www.w3schools.com/tags/att_a_href.asp
> The href attribute specifies the link's destination ...The href attribute specifies the URL of the page the link goes to.

https://www.pcmag.com/encyclopedia/term/44472/href
> The HTML code used to create a link to another page.

I have considered "Link to" as a label for the field, but have personally turned it down. I think that "Link destination" fits the bill for user-friendliness, so I have gone with that in the PR.

@jenlampton thank you for all the excellent recommendations re labels and help text. I have updated the PR.

As for the label `padding-bottom`, making the modal wider reveals the reason. It is to make sure that the label is vertically aligned with the autocomplete when inline:

<img width="634" alt="screen shot 2019-01-04 at 2 17 01 am" src="https://user-images.githubusercontent.com/2423362/50668370-414d3c00-0fc7-11e9-951f-39e4c84401f8.png">

...which by the way makes me think that we should make that dialog wider anyway when on desktop. Do it here, or separate issue?

**Comment by jenlampton** [comment] 2019-01-04 00:41
> As for the label padding-bottom, making the modal wider reveals the reason. It is to make sure that the label is vertically aligned with the autocomplete when inline:

Can we treat *Link text* the same way? 

> we should make that dialog wider anyway when on desktop. Do it here, or separate issue?

If it's easy, here, but IIRC changing modal size is not easy.

**Comment by olafgrabienski** [comment] 2019-01-04 11:15
@klonos I like "Link destination". Are there other questions to which you want more feedback?

**Comment by jenlampton** [comment] 2019-05-01 23:18
I've added a few comments on the PR. 

I don't like the description text on the `Link destination` field. It currently reads:
`Enter a link to an external page or a known internal path. Alternatively, start typing to get suggestions for paths of existing content.` This language feels cumbersome and hard to understand. 

How about something more like this?

`Enter an external URL (example: <em>http://backdropcms.org</em>), the relative path to another page on this site (example: <em>/about</em>), or just start typing to see a list of suggestions.`

**Comment by quicksketch** [comment] 2019-05-02 01:44
In the current PR, I'm seeing unnecessary empty attributes saved when no fields are filled in, for example:
```
<a href="/about" id="" rel="" title="">About Us</a>
```

We need to `unset()` these properties if they're empty in the submit handler.

**Comment by quicksketch** [comment] 2019-05-02 01:48
Also expanding the More options for the link dialog makes it impossible to click the Save button because it scrolls off the window, but that's an existing problem that is surfaced by having a short dialog suddenly become taller than the current window.

**Comment by quicksketch** [comment] 2019-05-02 02:09
Updated PR with a submit handler to remove empty attributes.

**Comment by quicksketch** [comment] 2019-05-02 03:01
I filed a new issue for problems with fieldsets within modals at https://github.com/backdrop/backdrop-issues/issues/3743

**Comment by jenlampton** [comment] 2019-05-02 03:25
I've tested the PR, and everything is working great! 
<img width="732" alt="Screen Shot 2019-05-01 at 8 25 02 PM" src="https://user-images.githubusercontent.com/397895/57055276-4194d580-6c4f-11e9-84b3-e4dd347873ff.png">

**Comment by jenlampton** [comment] 2019-05-02 03:32
I'm checking https://github.com/backdrop/backdrop-issues/issues/2072 to see if I can find out why the `data-editor-image-toggle` attribute was added.

**Comment by jenlampton** [comment] 2019-05-02 03:46
Pushed a minor update to the PR which will upset the CSS again, but maybe also put back the mystery thing that I've never understood that might be important :)

**Closed** 2019-05-02 04:05 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2019-05-02 04:07
https://github.com/backdrop/backdrop/pull/2638 looks all good to me. I've merged it into 1.x for 1.13.0. Note we'll need to fix https://github.com/backdrop/backdrop-issues/issues/3743 before release because the fieldset/modal problem is _very_ noticeable with this new feature.
