### ISSUE TITLE
[UX] Clarify layouts terminology

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#998] opened 2015-06-12 19:54 UTC
@klonos this may be one for you.

Just rounding off adding layouts to update module. We should now have the ability to install layouts through the UI, which is great. But I am struck by the blurred lines between:
- a Layout package and a layout path
- clicking "Edit > Settings" on a layout, so that you can change the layout assigned to that layout.
- the concept of installing a layout vs adding a layout

![layout](https://cloud.githubusercontent.com/assets/1042283/8138666/7c592f00-1112-11e5-8a24-02cd7cfba73e.PNG)

This may be understandable to us, but it is not clear enough. How can this be fixed?

**Comment by quicksketch** [comment] 2015-06-12 21:37
Oo, yikes. Well perhaps after we get project browser completed, we'd be able to say "Find new layouts"? Not sure that'd help much.

We've overloaded the term "layout" for sure. It's both the name of a template/CSS collection and the name of a path that has a layout added to it.

**Comment by klonos** [comment] 2015-06-13 14:42
> Oo, yikes.

Double-yikes! Hmm... this needs a lot of though, but of the top of my head I was thinking to perhaps introduce the concept of layout templates (the actual downloadable that contains the ```layout--*.tpl.php```) and layout configurations (where the user needs to select a template to be used with).

That's how far I went ...and I'm not happy with what I've come up with.

**Comment by klonos** [comment] 2015-06-13 14:44
...as for the install/add, would it be better if it was install (a template)/create (a config) instead?

**Comment by quicksketch** [comment] 2015-06-15 21:11
I like that idea. Maybe:

- Add layout
- Install new template

? Still a bit confusing terminology-wise.

**Comment by klonos** [comment] 2015-06-16 14:26
> Still a bit confusing terminology-wise.

Yeah, I know.

**Comment by docwilmot** [comment] 2015-06-21 13:04
This is a lot deeper than I thought, the 'layout' terminology is all mingled in core code. I did this to get info on the layout page:
```
function theme_layout_info($variables) {
  $layout = $variables['layout'];
  $info = layout_get_layout_info($layout->name);
```

Happy I was, but no!! The 'layout' in `$variables['layout']` is the layout path stuff, not the layout package! and `layout_get_layout_info()` only works on said package things. So its actually:

```
function theme_layout_info($variables) {
  $layout = $variables['layout'];
  $info = layout_get_layout_info($layout->layout);
```

@quicksketch if we were to change the package concept's name in core to `layout_template`, and someone went through and disambiguated core, would this equate to an API change?

**Comment by klonos** [comment] 2015-06-21 22:15
I say do it now -even if it constitutes an API change-, before we have too many contrib modules that rely on or extend layouts.

**Comment by quicksketch** [comment] 2015-06-23 02:05
I'm not sure about the API change. If we can limit this to variable names within forms and (mostly) administrative theme functions, I think that limited change is fine. I don't think we should change any return values from API functions, but it doesn't seem that those are the primary focus here.

**Comment by docwilmot** [comment] 2015-06-23 04:11
So now to go through each of 3305 mentions of 'layout' to decide which is which.

**Comment by klonos** [comment] 2015-06-23 14:21
> So now to go through each of 3305 mentions of 'layout' to decide which is which.

:cold_sweat:

**Comment by docwilmot** [comment] 2015-06-25 23:11
First pass, probably a bit more than @quicksketch will accept midcycle, but:

- Changed `layout_get_layout_info($layout_name = NULL)` to `function layout_get_layout_template_info($template_name = NULL)`.
Provided a compatibility compromise function: 
```
function layout_get_layout_info($layout_name = NULL) {
  return layout_get_layout_template_info($layout_name);
}
```
- Converted all instances of the word 'layout' referring to a template to 'layout_template'. 
- Did the same in the default and admin default configs, changing the `layout` key to `layout_template`. Provided an upgrade function in `layout.install` to swap these:
```
/**
 * Changes the layout template key in layout config files from 'layout'
 * to 'layout_template'.
 */
function layout_update_1000() {
  $layouts= config_get_names_with_prefix('layout');
  foreach ($layouts as $layout_name) {
    $config = config($layout_name);
    $configs = $config->get();
    if (isset($configs['layout'])) {
      $configs['layout_template'] = $configs['layout'];
      unset($configs['layout']);
    }
  $config->setData($configs);
  $config->save();
  }
}
```
- fixed tests, with the exception of upgrade.test which complains `No pending updates at the end of the update process.` on line 210, which I havent figured out yet.

This is the raw version of course.

**Comment by docwilmot** [comment] 2015-06-25 23:49
Incidentally, the nature of this change means that if you upgrade, you will get errors immediately until you run updates. 

There will be a mismatch between the existing config which will still have a "layout" key, and the new code, which will be using the new key.  I can't figure a way to avoid this. 

Which is probably a good reason to do this sooner rather than later.

**Comment by jenlampton** [comment] 2015-07-02 18:32
I think having errors before running the update is fine, that's bound to happen.  As long as people can navigate to the update screen with no issue, that is ;)

Also +1 on this issue.  Nice work!

**Comment by sutibun** [comment] 2015-09-23 19:33
First, I still don't fully understand Layouts but some ideas came up. May or may not have relevance here but felt like jotting them down somewhere relevant before I forget.

Having said that, I remembered in design there being a term called "[Composition][comp]"

> Composition is the placement or arrangement of **visual elements or ingredients** in a work of art, as distinct from the subject of a work. It can also be thought of as the **organization of the elements** of art according to the principles of art. ... The term composition means 'putting together,' and can apply to any work of art, from music to writing to photography, that is arranged or put together using conscious thought.

Also, [talked about here][compo]
> "As generally understood, good composition means the grouping of the different parts of a picture in a kind of geometrical arrangement of lines and spaces

Seems similar to Layouts.

Anyway, here are names that came up and throwing out there if it helps with the ambiguity

- canvas
- layout
- composition builder
- grid system (not [exactly a grid][grid])
- arranger

[comp]: https://en.wikipedia.org/wiki/Composition_(visual_arts)
[grid]: http://markboulton.co.uk/journal/five-simple-steps-to-designing-grid-systems-part-1
[compo]: http://www.drawinghowtodraw.com/drawing-lessons/art-design-principles/articles/theories-of-pictorial-art-compositions.html

**Comment by docwilmot** [comment] 2015-09-28 03:45
Just finished working on more Layout stuff and thought I should make a plea that we get this done ASAP! I am fearful that leaving this in much longer will get us into the same problem with longstanding Drupalisms/Backdropisms like "node" and "taxonomy" which are too entrenched to easily fix. Already it is going to be difficult. Please lets deal with this!

For those who are not familiar with this issue, it is a problem with the word "Layout":

Backdrop users can create Layouts, which are essentially an arrangement of blocks at a given path. These layouts can use different templates to arrange the blocks. So you can create several Layouts each with different blocks but with the same template (example the popular two-column template) or use differnet templates. 

Unfortunately though, in Backdrop these templates are also called... "Layouts"!

So the default admin "Layout" uses the one-column "Layout". 

Hence also the unfortunate situation in the image above of "Install Layout" (meaning upload a new 'template') and "Add Layout" (meaning create a new block arrangement at a given path) both being found on the admin/layouts page. This mixing of terms is what this issue aims to correct.

**Comment by quicksketch** [comment] 2015-09-28 04:58
Hey @docwilmot I looked at this a while back, but if I recall correctly, the only change here is renaming a layout .tpl.php with .info file to be called a "layout template". Is that right? Then current references to "layout" mean "a configuration of a layout". Is that right? Or are we renaming both things?

**Comment by sutibun** [comment] 2015-09-28 06:51
> Backdrop users can create Layouts, which are essentially an arrangement of blocks at a given path. These layouts can use different templates to arrange the blocks. So you can create several Layouts each with different blocks but with the same template (example the popular two-column template) or use differnet templates.
> ...
> Hence also the unfortunate situation in the image above of "Install Layout" (meaning upload a new 'template') and "Add Layout" (meaning create a new block arrangement at a given path) both being found on the admin/layouts page. This mixing of terms is what this issue aims to correct.

I *think* I sort of get it. Let me see if I can explain it in my own way and tell me if I am wrong. First, look at my crude drawing... specifically the last row. Row 3.

![bundle bag](https://cloud.githubusercontent.com/assets/14132746/10128313/53826732-6576-11e5-9493-621f708bb211.png)

## Now let's start with a story. (stick with me)

Let's say you are done visiting Africa and will return home soon. However, you want to take with you rare birds and smuggle them out. So, you select 3 tiny birds and place them in a large bag filled with other stuff. Inside the plane, you plan to place this bag in the overhead space above your own seat row.

You worry though the birds will get crushed inside the bag so you first lay the birds inside small cages. With the bird safely inside, you place the cages inside the bag. Come moving day, your birds safely fly home with you in the plane.

## Using the story as an anology


### Add layout
> "Add Layout" (meaning create a new block arrangement at a given path)

When we say "Add Layout", you mean we must

1. select the blocks we want to work with (blocks = the birds we want)
2. define the path they'll be found together. (given path = where we'll put them => the container bag)

So, "add layout" is about selecting what blocks/birds we'll work with and where we'll stuff them (i.e bag)

### Install layout
> These layouts can use different templates to arrange the blocks...
> 
> "Install Layout" (meaning upload a new 'template') 

Whereas an "Installed Layout" is the predefined template where we'll place and organize the blocks. i.e. the cages where we'll lay out the birds in so they're safe


### Putting it all together

So, the way the Bd Layout system works is

1. "Add layout": Select the birds you want and the bag you plan to carry them in (select the blocks to work with and define the path they'll be at)
2. "Install layout": Find cages that'll house the birds and keep them from being crushed (the predefined template that'll help you organize your blocks)
3. Thus, The birds/blocks will be housed in a cage/template located in the bag/path 

Assuming I understand this correctly, here is how I propose we differentiate the word layout.

- "Add layout" becomes **"Create a Bundle"** = Selecting the birds/blocks and defining bag/path (bundling blocks in a given path)
- "Install layout" remains the same or **Install Layout template** = cage/template where you'll lay out the birds/blocks (this is what designers think of)

Now, looking at row 1, we gather blog-related blocks and place them in path "/blog". This defines the bundle called "blog".

However, we'll first need to arrange the blocks in the layout template called "two columns" before we place them in the bag.

In Row 2, although the bundle "About" has different blocks and a different path (/about) or bag, we can still use the same template to organize them.

I hope my understanding isn't way off... and my explanation confusing.

**Comment by jenlampton** [comment] 2015-09-28 07:20
You have encountered one of the hardest problems in Drupal/Backdrop. We are running out of abstract nouns!

> Create a Bundle

Unfortunately, the word 'bundle' already has another meaning in Drupal/Backdrop. A bundle is a collection of fields attached to a specific entity type. A 'page' is a bundle, as is a 'post'. 

> Install Layout template

Unfortunately, the word 'template' already has another meaning in Drupal/Backdrop. Templates (also known as template files) are files that you use to control the combination of HTML markup and variables representing your content, or other output. A front-end developers tool. 

This issue touches on a few different problems:

1) what to call the thing you upload to your server? a `Layout`
We have decided on three project types: Modules / Themes / Layouts. I don't think we're going to get away from this one. Just as you can upload one module, but enable three modules (from that one module you uploaded) we are going to have a conflict here, but **I think it's alright as-is.**

2) What to call the thing you build: a `Layout`
It's really a page (or category of pages) that has a specific layout, menu item, etc. But unfortunately, the word also 'Page' already has lots of other meanings in Drupal/Backdrop. I could be convinced that we should call this a 'layout display' or something, since we are configuring how things should be displayed.

3) What to call the shape of the thing you build: a `Layout`
The good thing about this interface is that we can see previews of all the different layouts here. We have some visual context as to what we're choosing, so the label is less important. We are technically selecting a template since what we choose here will dictate the .tpl.php file that's being used. **I vote yes to changing this to be a `Layout Template`**

**Comment by docwilmot** [comment] 2015-09-28 12:50
@quicksketch I think @jenlampton got it spot on. Essentially we are changing this in all `layout.layout.x` files:
```
{
    "_config_name": "layout.layout.default",
    ...
    "layout": "two_column",
```
to this:
```
{
    "_config_name": "layout.layout.default",
    ...
    "layout_template": "two_column",
```

And all the necessary code changes required to support that switch.

The PR also changes user facing labels where necessary to make the interface less ambiguous, like altering "Install layout" to "Install layout template".

We're not changing the path-based Layout concept, nor changing the project/package name  (although for completeness I'd love to, but its too late now).

I'd love to get the go-ahead to freshen up that PR, and have you guys stick a 1.3.0 label on it.

**Comment by jenlampton** [comment] 2016-01-12 22:45
Hm, I think I just created a related (if not dupliate?) issue over at https://github.com/backdrop/backdrop-issues/issues/1513.  That one was specifically or the 2.x change of the `Layout` module name to `Layouts` though.

@docwilmot we need to be careful changing user facing labels, because `Install layout template` is not what we mean at all.  That action installs a **set** of layout templates, not a single template. I think we should call the projects "Layout sets" to differentiate them from `Layout templates` since there can be one or many templates in a set.

**Comment by docwilmot** [comment] 2016-01-12 23:04
I don't think that's necessarily right @jenlampton. Currently three layouts are listed, two of which are "sets", the other a single layout. As you've noted previously, we don't yet know how contrib layouts are going to work out. If we call them "sets" but people keep making single ones, we'll have even more confusion. Modules for example are usually single but can be groups. But we call them modules even when they're groups.

**Comment by jenlampton** [comment] 2016-01-15 07:21
I think we are having terminology / communication problems again. :) 

I was explaining that `layout sets' are the things you download and install.  A good example would be the `radix_layouts` project. That is a layout set. It's the thing you use the `Install layout` link for.  That will download files from GitHub and save them into your `/layotus` directory.

That thing is completely different from the thing you use the `Add layout` link for. That link will give you a UI where you place blocks. We should not be using the same word for both those things, especially when the links are right next to each other on the same page.

The impression I get from the `Install layout` link is that it will load a config file, since I think the layout you Install is the same as the layout you Add.

**Comment by docwilmot** [comment] 2016-02-06 13:04
Tagging this 1.4.0 simply to get it back on the radar. When it was first suggested, the recommendation was to do it ASAP before Layouts become well entrenched. We may be past that. So someone should decide: do we do this? If not tag 2.0 please.

**Comment by klonos** [comment] 2016-02-06 23:55
This thing is hitting me more and more each time I try to figure out a solution or report an issue about the Layout UI. We need to solve this ASAP as @docwilmot suggests. The more we wait, the more the terminology will be sitting-in in people's heads and the harder it will be to sort it afterwards. Lets consider this a major UX bug and sort it in the next bug-fix release please - not in 1.4.0.

**Comment by klonos** [comment] 2016-02-07 00:32
...I was thinking about possible alternatives for the *layout templates* (the things that we see and have screenshot/icons for). The best I could come up with was "wireframes" or "scaffolds" (I thought "frameworks" too, but that is reserved for other things in coding land).

https://www.google.com/search?q=define+scaffold

> ...
> 1. a raised wooden platform used formerly for the public execution of criminals.
> ...

Hmm :confused: :scream: :fearful: :cold_sweat:

...but http://dictionary.reference.com/browse/scaffold

> ...
> a temporary structure for holding workers and materials during the erection, repair, or decoration of a building.
>...

That sounds much better :relieved: 

https://www.google.com/search?q=define+wireframe

>...
>an image or set of images which displays the functional elements of a website or page, typically used for planning a site's structure and functionality.
>...

That sounds like a really good match! Which lead me to a few other words...

1. "matrix":

https://www.google.com/search?q=define+matrix

> ...
>a mold in which something, such as a record or printing type, is cast or shaped.
>...

http://dictionary.reference.com/browse/matrix

>...
>something that constitutes the place or point from which something else originates, takes form, or develops
>...

2. "blueprint":

> a design plan or other technical drawing.

>A blueprint is a guide for making something — it's a design or pattern that can be followed. Want to build the best tree house ever? Draw up a blueprint and follow the design carefully. The literal meaning of a blueprint is a paper — which is blue — with plans for a building printed on it.

Other notable mentions include "stage", "frame", "skeleton", "grid", "prototype" and "design"

**Comment by klonos** [comment] 2016-02-07 00:43
...I think I like the definitions of *blueprint* more than the rest, but *layout blueprint* is not as "rhymy" as *layout design* for example and it also has the word "blue" in it (we use gray for the layout thumbnails we ship with core and Radix is purple - silly OCD kicking in).

**Comment by docwilmot** [comment] 2016-02-07 01:04
As @jenlampton tried to point out previously, there are three layout things:

- the Layouts which are essentially the arrangement of blocks at a path
- the layout packages, which are the equivalent of modules, with an info file and a tpl.php etc. 
- and the layout templates, the tpl.php files. 

We call all three "layouts". The first can stay, but we need to decide about the others.

**Comment by klonos** [comment] 2016-02-07 06:32
Well, the way I see it, there are 4 layout things:

4. the *layout template* .tpl.php **files**
3. the *layout designs* (or *blueprints*): a single .info file and a tpl.php etc. This is what we ask the user to select **in the Layout UI** after choosing a name. They are what is behind **each individual** thumbnail.
2. the *layout packages* are a set of *layout designs* that people can download and install from the Project Browser or directly from bd.org or GitHub. They come packaged in a .zip file and **they are projects** like modules or themes. Think Radix.
1. A *Layout* is the thing we configure in the Layout UI. It has a configurable name (as well as a machine name),  a *layout design*, a path and optionally visibility conditions.

So in case it was not clear (because I was wrongly using the *layout template* terminology to refer to them), I was talking about the individual *layout designs*. The things with the thumbnail.

**Comment by klonos** [comment] 2016-02-07 06:38
...so this for example:

![backdrop-layout_form_validation-everything_a_field](https://cloud.githubusercontent.com/assets/2423362/12871183/1338cc6c-cdc1-11e5-85e3-3b638f86514b.png)

Becomes:

![backdrop-layout_form_validation-layout_design](https://cloud.githubusercontent.com/assets/2423362/12871193/8efb519e-cdc1-11e5-92cb-a4bfbba40da1.png)

**Comment by klonos** [comment] 2016-02-07 06:41
...still wavering between "layout design" and "layout blueprint" though :confused:

**Comment by jenlampton** [comment] 2016-03-11 06:37
> 1) the layout template .tpl.php files

I like `layout template`: for this, since it's consistent with other template files.

> 2) the layout designs (or blueprints): a single .info file and a tpl.php etc. They are what is behind each individual thumbnail.

I think design might be confusing, since there are no design files or resources in here. I don't like the word blueprint, but I like the idea behind it! I googled synonyms for "blueprint" and found "pattern". What about `layout pattern`?

> 3) the layout packages are a set of layout designs that people can download and install from the Project Browser or directly from bd.org or GitHub.

I like `layout package` as well as `module package` and `theme package` and I think we should update all the `Insall X` links to be `Install X package` for consistency.  :+1: 

> 4) A Layout is the thing we configure in the Layout UI. 

I think we all agree we should keep calling this thing a `Layout`

Also, I agree we should get this done quickly...  as soon as we can decide what to call #2 :)  All these suggestions are better than just "layout", btw, so if we want to go wtih design or blueprint, still an improvement!

**Comment by klonos** [comment] 2016-03-11 07:13
https://www.google.com/search?q=define+pattern

>1. a repeated decorative design.

Yeah, I like *blueprint*, *design* and *pattern* the same (which is not much).

Anyone else with a better alternative so we can wrap this up soon??

**Comment by klonos** [comment] 2016-03-11 07:15
...throwing *outline* in the table.

https://www.google.com/search?q=define+outline

> 1. a line or set of lines enclosing or indicating the shape of an object in a sketch or diagram.
> 2. a general description or plan showing the essential features of something but not the detail.

**Comment by klonos** [comment] 2016-03-11 07:16
...https://www.google.com/search?q=define+sketch

>a rough or unfinished drawing or painting, often made to assist in making a more finished picture

**Comment by klonos** [comment] 2016-03-11 07:18
Also thought of *skeleton* and *chassis* but the first one hmm :skull: and the second is more for :car:

**Comment by klonos** [comment] 2016-03-11 07:20
...*mould*??

https://www.google.com/search?q=define+mould

> a hollow container used to give shape to molten or hot liquid material when it cools and hardens.

**Comment by klonos** [comment] 2016-03-11 07:27
Run out of ideas.

**Comment by Graham-72** [comment] 2016-03-11 07:28
formation?

**Comment by docwilmot** [comment] 2016-03-11 13:35
Suggestion overload!

I personally think we should stick to just two concepts though: Layout and Template. I think if youre browsing/installing number 2 and 3 in https://github.com/backdrop/backdrop-issues/issues/998#issuecomment-180962218, its only because youre looking for something with a new *template* in it. 

We could debate what you call the thing you wrap the loaf of bread in, but in the end, you're just looking for bread! I think for the end user, she'll be looking simply for a *template* that arranges the Layout in a particular way. Let's not cloud the interface terminology with sets and mould and whatnot. 

In either case for the purpose of this PR/issue, the code changes will be mostly just to differentiate between `xx_layout_` and `xx_layout_template_` in the Backdrop code. There are a very few user facing labels where we can debate, but not much. So it seems we're set for `template` and can go ahead with that.

**Comment by quicksketch** [comment] 2016-03-26 01:39
I took a look at the new PR in https://github.com/backdrop/backdrop/issues/1307. It looks great! Change is limited to specific situations that are unlikely to be used in contrib, and in the situation where it is likely to break, a wrapper function marked as `@deprecated` is in its place. There are a few minor items, but to me the PR looks great. I'll need to do another pass, but I wanted to give my +1 to these changes.

**Comment by klonos** [comment] 2016-03-26 07:43
> We could debate what you call the thing you wrap the loaf of bread in, but in the end, you're just looking for bread! I think for the end user, she'll be looking simply for a template that arranges the Layout in a particular way. Let's not cloud the interface terminology with sets and mould and whatnot.

I understand what you're saying, but we will have two different things that are referred to by the same term: the design templates of the layouts and and the .tpl.php files. This is not likely to cause UI confusion because I cannot think of any place in the UI currently where we expose both the design templates and the .tpl.php files, but this will eventually be causing documentation confusion for sure.

**Comment by Graham-72** [comment] 2016-03-26 16:49
I struggle through this jungle by trying to avoid talking about any sort of template other than a template file ending in .tpl.php. A few months ago a potential client was quizzing me about how all this worked, partly because I was stressing the flexibility of Backdrop to meet all sorts of layout requirements. He was far from impressed by the confusing terminology, or perhaps my attempt at using it, and I didn't get the business! Clear terminology is important and if we have to use agreed pairs of words please let's do it.

**Comment by bd0bd** [comment] 2016-03-26 16:59
>Clear terminology is important

More than important. Super important, it is a key element.

**Comment by docwilmot** [comment] 2016-03-26 17:08
Agreed. In this PR though, all the changes actually turned out to be referencing the tpl stuff, fortunately, except the one link to "install a layout template". And I'm thinking that would be the most appropriate label for that one, since that's what the user would be interested in installing. 

Unless there are better ideas.

**Comment by klonos** [comment] 2016-03-26 23:36
> Unless there are better ideas.

We should pick one of the proposed words for the UI-screenshot-thingy. *Design*, *blueprint*, *pattern*, ...*[something]*, but **NOT** *template* because that is a "reserved" word for the .tpl.php files.

I know this is a bit frustrating. It is similar to not being able to use the word *features* because of the possibility to be confused with https://www.drupal.org/project/features

...still we need to decide. Soon.

**Comment by klonos** [comment] 2016-03-26 23:42
This might help... Consider the documentation or UI help text use cases and try to fill i the blanks with the best/first word that comes to your mind:

**UI help text**: *In order to create a Layout, you need to select a name, a _________, and a path. You can also specify visibility conditions.*

**Layout dev and themers' documentation**: *In order to create layout ________ that will be available for users to select through the Layout UI, you need to create a layout template. Layout templates are files with a .tpl.php extension.*

**Comment by klonos** [comment] 2016-03-26 23:52
How about *grid*:

> a network of lines that cross each other to form a series of squares or rectangles.

The only bad thing about this word is that is sounds awfully the same as "greed" (especially when pronounced by a non-native English speaker) and using "a grid" in a sentence might sound like "agreed".

**Comment by klonos** [comment] 2016-03-26 23:59
...the first encounter I personally had with the word "grid" was the [960 Grid System](http://960.gs/). Older versions of their website looked like this:

![960grid-12col](https://cloud.githubusercontent.com/assets/2423362/14063022/931efdc4-f40a-11e5-9af2-a1380f489d0e.jpg)

See the resemblance with our screenshot-thingies? I believe that this would make sense to front-end designers and people that used these ready-made systems as starting templates for their websites. What do you think?

**Comment by gifad** [comment] 2016-03-27 00:13
> Design, blueprint, pattern, ...[something], but NOT template

In French, template is often translated (for end users) into _canevas_, which google translates into _canvas, groundwork_;
On the other hand, my (developper) text editor uses _stationery_…

**Comment by klonos** [comment] 2016-03-27 00:57
Yes, our monkey friend [in a previous comment](https://github.com/backdrop/backdrop-issues/issues/998#issuecomment-142705964) I mentioned "canvas". I don't mind it. It's just that the [definitions on the web](https://www.google.com/search?q=define+canvas) refer to paint/painting-related things mostly.

> A basis for creative work.

> (computer graphics) A region on which graphics can be rendered.

I specifically liked the metaphor/allegory of this particular definition though:

>a specially prepared piece of cloth on which a picture can be painted by an artist

..."specially prepared piece of cloth" as in the "special" .tpl.php files that a theme/layout dev prepares and the "artist" being the website builder in our case that doesn't care about how the the .tpl.php file was created - only wants to use the canvas :wink: 

Wikipedia says the word is of Greek origin, from the word "cannabis" ...which could explain why artists are so creative. They use part of the plant to make the canvas fabric and part of it for "recreation" :laughing: 

Anyways, *Layout canvas* sounds good to me.

**Comment by gifad** [comment] 2016-03-27 09:56
Yes, we agree to like the creative aspect of _canvas_ — in french, it's preferred to _framework_ for very serious tasks, like business plan, when the innovative aspect is to be featured —.
Now the issue is that configuration is at the opposite connoted to obscure administrative tasks, so _Configure canvas_ seems a bit odd; _Edit canvas_ would shine, though…

**Comment by klonos** [comment] 2016-03-27 16:56
@gifad, the word "canvas" is a proposal for the screenshot representation of the layout template in th Layout edit UI. So if it is accepted, it will be used to describe that. So it won't be *configure* or *edit* canvas - it will be more like *select a layout canvas*.

...now that I read that phrase, I don't like the sound of it though. I like "layout design" or "layout grid" or the "layout pattern" that @jenlampton suggested a while ago better.

Lets consider this documentation example that someone would use to describe the whole thing to users (could be a section of an article in some blog, a chapter in a book or an email sent to a customer in order to explain things)...

> Themers create layout *templates* and put them together in layout *packages* that are made available through contrib. Site builders can download such a layout *package* in a .zip format, install it either by uploading and extracting it directly on their web server or through the Project Browser or through the manual project installation UI of their website. Then, in order to add a layout, site builders use the Layout UI. They select a Layout name, a layout _______, a path and optionally set visibility conditions.

So, votes please in order to decide on this. What would fill better the blank?:

- layout canvas
- layout pattern
- layout grid
- layout design

**Comment by gifad** [comment] 2016-03-27 17:40
In this context, I'd vote for _layout pattern_, without hesitation…

**Comment by Graham-72** [comment] 2016-03-27 17:47
I vote for layout pattern. Thank you for this clear presentation of its use in context.

**Comment by bd0bd** [comment] 2016-03-27 18:24
My English is not enough good but it seems to me **layout pattern**  is best variant.

**Comment by docwilmot** [comment] 2016-03-27 18:39
I still say **template** fits best. It is clearly the most familiar as @bd0bd agrees, and it is in fact *the thing* that you are installing, regardless of what we end up calling its wrapper/package.

**Comment by docwilmot** [comment] 2016-03-27 18:42
Can @jenlampton or @quicksketch put in a final word, lest we bike-shed any further?

**Comment by bd0bd** [comment] 2016-03-27 18:44
Single word **template** seems the best variant. Without word **layout**.

**Comment by quicksketch** [comment] 2016-03-27 19:07
I'm also in support of *template*. To me it's the main item that is being installed/used. In the case of something like Radix, it includes ~20 templates and only one common CSS file. So when I'm choosing a layout option, what I'm doing is selecting the matching template.

It used to be that "module" literally meant a .module file, alone with no other files at all. It wasn't until CSS and JS became common that the .module was grouped into a directory. Then eventually .info files were added as well. Even though a module now includes lots of files, the "main" thing is still the .module file. This seems similar, the main thing you're installing is a template, but it also has a .info file and an (optional but very likely) CSS file.

> Then, in order to add a layout, site builders use the Layout UI. They select a Layout name, a layout _______, a path and optionally set visibility conditions.

"template" or "template from the installed package" works for me.

**Comment by gifad** [comment] 2016-03-27 19:45
@ last three speakers : this issue is about user's language.
As a french speaker, I understand _template_ just because of my 50+ years background in computer science.
But it's a computer word, not an english word !
Conversely, I can immediately translate _layout pattern_, despite my very low level in english.

So 80% of core developpers will vote for template, but I've read nearby that this is 0,05% of users...

**Comment by bd0bd** [comment] 2016-03-27 20:02
>So 80% of core developpers will vote for template

Sorry, I will disagree :smile:
**Template** is a common and familiar word understandable for most users who make websites, even for newbies

**Comment by gifad** [comment] 2016-03-27 20:31
Sorry, I will disagree too :smile:
"most users who make websites" understand template as a sample file, to be used as a starting point of the final file they will create.
drupal, backdrop, and other CMS has derived this meaning into : sample html fragment(s) that the CMS will fill with variables to produce the actual page.

**Comment by Graham-72** [comment] 2016-03-27 21:10
I am not sure whether it is helpful or confusing to see how Wordpress uses the term Template - see https://codex.wordpress.org/Templates . Though I know that if you search for a template you will be offered Themes - synonymous in common sloppy usage IMHO.

**Comment by Graham-72** [comment] 2016-03-27 21:36
Another perhaps unhelpful comparison is that in the UK if one sets out to make a garment, you buy a 'pattern' which is a set of 'templates' for cutting out the required components. Similarly, a traditional metal fabrication might involve templates, but now of course CAD files. But we must of course go with modern usage. If the general feeling is that we should call the set of template files a Template I can live with that, but will try always to refer to one of those tpl.php items of code as a 'Template File' for clarity.

**Comment by jenlampton** [comment] 2016-03-27 21:59
It sounds like we are agreeing on `Layout` and `Layout package` (as well as `Module package` and `Theme package`) so I have created https://github.com/backdrop/backdrop-issues/issues/1757

The sticky part seems to be "Layout template"...

> We should pick one of the proposed words for the UI-screenshot-thingy... but NOT `template` because that is a "reserved" word for the .tpl.php files.

I disagree with this. The UI here is simply asking which .tpl.php file will be used. In this case we just happen to also be giving them a Name to refer to that template file, and a Screenshot to help them make that decision (and yes, these things all happen to be controlled through the .info file). In this case, I think using the word "template" is helpful, because not only will the word "template" be useful in this context, but it will help people understand that they are actually selecting a .tpl.php file to be used.

**Comment by gifad** [comment] 2016-03-27 22:46
Just for fun, I just downloaded panels.fr.po, and, guess what, they translated Layout into the same word as Display !!!
I'm playing/working with Backdrop for 5 or 6 months now, and I have yet absolutely no idea of just how to name "Layout".

For now, if I'm asked "What is Layouts ?", my answer is : "it's the new name for Blocks".

The fact that block layout is visible with no need of clicking "preview" is seen as a very minor advantage.
The fact that layout configuration is not saved when you change theme is seen as a major regression.

Sorry for disturbing your conversation, but your teminology discussion is very _`local`_ :smirk:

**Comment by klonos** [comment] 2016-03-28 04:36
I think I am convinced that going with *template* is the right way to go after all. The screenshot thingies are just the visual representations of .tpl.php files in the Layout UI that help people select the actual layout template file that renders the whole layout and its various regions. If anything we can call them template screenshots. In fact, IIRC the initial versions of the Layout UI were using a radio list of template names before we replaced these with the respective screenshots for better UX. So there you go: first we used template names, now we use template screenshots. Point is both were UI elements that were/are used to point to or represent the respective template files in the filesystem.

@jenlampton has explained things nicely, @docwilmot sorry if you were trying to explain the same thing when you said "We could debate what you call the thing you wrap the loaf of bread in, but in the end, you're just looking for bread!" - I guess I got lost in translation and the use of metaphors at some point.

Lets go with *template* and be done with it.

**Comment by bd0bd** [comment] 2016-03-28 12:37
Yes, **Template**.
Wordpress and many other users are familiar with this.
I think even for Drupal users this word would be clear.

**Comment by biolithic** [comment] 2016-03-28 13:57
Let's use this in a sentence:
(not saying this is the correct way, it's just what has manifest by the
community so far)

Senjo is layout package of a single layout template for content pages that
relies on/provides to the theme the Bootstrap grid.  Each layout template
in this group provides different sized regions to place your blocks into on
a specific page.

2 Columns Flex is layout package of a group of layout templates for content
pages that relies on/provides to the theme the Bartik grid.  Each layout
template in this group provides different sized regions to place your
blocks into on a specific page.

Radix is layout package of a group of layout templates for content
pages that relies on/provides to the theme the Bootstrap grid.  Each layout
template in this group provides different sized regions to place your
blocks into on a specific page.

Juiced Up is layout package of a group of layout templates for front
pages/splash pages that relies on/provides to the theme the Juiced grid.
Each layout template in this group provides different sized regions to
place your blocks into on a specific page.

Foundation Html Templates is layout package of a group of layout
templates for content pages that relies on/provides to the theme the Zurb
grid.  Each layout template in this group provides different sized regions
to place your blocks into on a specific page.


The layout template chosen is the highest level of visual page structure
for that page.  If you are using Views (as blocks) to provide your page
content, you may choose a Views plugin to provide a micro-layout for that
specific region inside your layout.  For example, a block that takes up 33%
of a larger 100% is 33% page width, but a block that takes up 33% of 50% of
the page is 16.5% of the total page width.

https://github.com/backdrop-contrib/views_slideshow
- It may not be necessary to have a layout or theme that provides a
slideshow.  You can use any layout template and theme and insert the Views
Slideshow into the region you want, if you desire this method.

https://github.com/backdrop-contrib/salvattore
- It may not be necessary to have a layout or theme that provides a
"responsive Pinterest card style grid system".  You can use any layout
template and theme and insert the Views Salvattore block into the region
you want to achieve this look, if you desire this method.

https://github.com/backdrop-contrib/views_bootstrap
- It may not be necessary to have a layout or theme that provides a
"responsive Bootstrap style grid system".  You can use any layout template
and theme and insert the Views Bootstrap block into the region you want to
achieve this look, if you desire this method.

https://github.com/backdrop-contrib/flexviews
- It may not be necessary to have a layout or theme that provides a
"responsive CSS flexbox grid system".  You can use any layout template and
theme and insert the FlexViews block into the region you want to achieve
this look, if you desire this method.

If you are making a news website with a card-style design (header at the
top, 3 equal size content boxes as the news stories underneath) you can
implement this in Backdrop with:

- A layout template from a layout package mentioned above, core Views
plugin, Bartik theme
or
- Core Layout, contrib Views plugin mentioned above, Bartik theme
or
- Core Layout, core Views plugin, custom theme writing your own CSS (using
PageTheme module)


Is it clearer?  Or harder to understand?  What is the way forward?

**Comment by mikemccaffrey** [comment] 2016-03-29 08:45
Wow, this thread is up to 68 comments? Seems like we might have a deeper
issue here than just terminology. Have we perhaps over-abstracted this
system to the point where the different parts have become vague and hard to
clearly explain?

**Comment by Graham-72** [comment] 2016-03-29 08:50
We forked from something that was hard to explain and have made it harder to explain but easier to use! I'm thinking in particular of my efforts to use Panels which were successful but I have to think very hard when I go back to modify the site that uses them.

**Comment by biolithic** [comment] 2016-03-29 11:42
I think layouts are easier to use, I was just trying to summarize this
thread in a real-life form.

**Comment by jenlampton** [comment] 2016-03-29 18:53
I also gave the PR a review, and it looks fantastic. Great work @docwilmot !!!

I'm recommending we exclude the text change for the install link so we can do modules & themes too - at the same time (perhaps in conjunction with the addition of project browser?) 
See https://github.com/backdrop/backdrop-issues/issues/1757
See https://github.com/backdrop/backdrop-issues/issues/1399

**Comment by jenlampton** [comment] 2016-05-15 04:47
This one looks great to me.

**Comment by quicksketch** [comment] 2016-05-15 19:59
Thank you thank you thank you @jenlampton for reviewing! I'll give this another look. I was worried this wouldn't make it. The PR needs to increment the update hook number in system.install, but I can handle that in the merge.

**Comment by quicksketch** [comment] 2016-05-15 20:29
I filed a new PR to adjust for more recent changes, removing a few more calls to the deprecated function `layout_get_layout_info()`. I also added a backwards-compatibility check to `Layout::__construct()` so that legacy config files will be convert `layout` to `layout_template`. This keeps sites from completely exploding upon upgrading to 1.4.0 prior to running update.php.

**Closed** 2016-05-15 21:34 UTC
Labels: status - has pull request, needs - change record

**Comment by quicksketch** [comment] 2016-05-15 21:36
I've merged https://github.com/backdrop/backdrop/pull/1382 for 1.4.0. We need a change record for this change. Thanks @docwilmot for your leadership and persistence on this issue! I'm relieved to have a small bit of sanity added to our terminology in Layout module. :tada:
