### ISSUE TITLE
Update docblock for `node_load_multiple()` to explain use of `FALSE`as parameter 1.

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6000] opened 2023-02-26 21:59 UTC
This is a follow-up #5437 (which won't be fixed). 

Currently, the doc block for `node_load_multiple()` doesn't explain that using FALSE as the first parameter will retrieve all nodes in the site. The default value for parameter 1 (an empty array) will actually return NULL, which seems counter-intuitive, but apparently can't be fixed in version 1. This isn't explained either.

**Comment by argiepiano** [comment] 2023-02-26 22:07
PR https://github.com/backdrop/backdrop/pull/4367 ready for review (no testing needed, as this is documentation).

**Comment by kiamlaluno** [comment] 2023-02-27 08:10
Is not this a duplicate of #5889?

**Comment by BWPanda** [comment] 2023-02-27 09:27
@kiamlaluno Looks like it. @argiepiano Closing as a duplicate of https://github.com/backdrop/backdrop-issues/issues/5889

**Closed by BWPanda** 2023-02-27 09:27 UTC
Labels: status - duplicate

**Comment by argiepiano** [comment] 2023-02-27 13:44
> Is not this a duplicate of https://github.com/backdrop/backdrop-issues/issues/5889?

Oops. Didn't see that. Thanks
