### ISSUE TITLE
Safari 9.x pushes down the last column in flexbox based layouts instead of positioning them side-by-side.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1985] opened 2016-06-23 06:15 UTC
Thanks for Backdrop 1.4.3 but I still have a layout problem when using Safari on a Mac (version 9.1.1)

When using the Geary layout the third column is below rather than alongside the first and second.

When using the Moscone Flipped layout the sidebar is below rather than alongside the main content.

This happens for both Bartik and Basis themes.

Interestingly, with Safari on my PC (an older version of Safari - 5.1.7) the layout is fine. And, of course, both Firefox and Chrome are fine.

**Comment by Graham-72** [comment] 2016-06-23 07:21
Another problem I have just seen, this time with the Boxton layout in Safari. The Footer is being displayed across the middle of the Main region, so consequently I have had to remove the Powered by Backdrop CMS message from the site. (This was also happening before release 1.4.3.)

**Comment by wesruv** [comment] 2016-06-27 15:28
I'll try to take a look at this soon.

**Comment by quicksketch** [comment] 2016-06-30 20:00
> Interestingly, with Safari on my PC (an older version of Safari - 5.1.7) the layout is fine. And, of course, both Firefox and Chrome are fine. 

Yeah when the float fallback is used Safari is fine. Firefox and Chrome work with the flexbox layout with no problem. Safari seems to be a bit weird with it's flexbox implementation.

I've tagged this for 1.4.4. As soon as we get this fixed we should make a new release. A significant problem in our layouts is a critical problem.

**Comment by jenlampton** [comment] 2016-07-01 02:15
Interesting, it looks like Safari can't calculate width correctly with flex. I'm looking at the simmons layout, and it appears that 50% + 25% + 25% > 100%.

**Comment by jenlampton** [comment] 2016-07-01 06:39
Well, it isn't pretty, but this is the only thing I could come up with. Reducing the `flex-basis` value for these grid classes fixes all core layouts in Safari 9.  It will also decrease the size of those columns in all other browsers that support flexbox, so it's not ideal, but things are really broken for Safari users today and I think "less than ideal" for most users is better than "utterly broken" for Safari and IOS users.

Long term, @quicksketch recommended we add our own fix via javascript: we should create an element off-screen of a known width, do the things we know cause measuring-problems in Safari 9, and measure the element again. If we find the numbers differ, only *then* do we reduce the size of the columns (thus, only affecting Safari 9 users).

**Comment by jenlampton** [comment] 2016-07-01 20:40
@Graham-72 would you be willing to test this PR on your site?

**Comment by Graham-72** [comment] 2016-07-01 20:44
@jenlampton yes, gladly. Hopefully I will be able to test it in a few hours time.

**Comment by jenlampton** [comment] 2016-07-01 20:46
Fantastic, thank you :)

**Comment by jenlampton** [comment] 2016-07-01 21:00
Also, for anyone needing to test layouts, I made these. Tarball attached for easy use @wesruv (inspired by @biolithic )

[layout-test.tar.gz](https://github.com/backdrop/backdrop-issues/files/344174/layout-test.tar.gz)

http://jenlampton.com/boxton
http://jenlampton.com/geary
http://jenlampton.com/harris
http://jenlampton.com/moscone
http://jenlampton.com/moscone_flipped
http://jenlampton.com/rolph
http://jenlampton.com/simmons
http://jenlampton.com/sutro
http://jenlampton.com/taylor
http://jenlampton.com/taylor_flipped

**Comment by wesruv** [comment] 2016-07-02 01:51
From what I could tell, Safari correctly calculated widths, in that the sum
of the rendered pixel widths for columns added up to the skinny of space
available... but for some reason it knocked one column to the next line,
even though it should fit.

I tried the flex basis fix, it seemed to cause other problems in Safari
when I mixed and matched different classes, much less other browsers.
That's why I opted for Safari going to the float fallbacks.

It's possible my testing environment for Safari was giving bad results and
that flex basis will fix it, we should make sure to test any fix for this
Safari thoroughly.

Also worth mentioning that Safari was reporting back wrong values for some
flex box styles when I dug into this more. That's why I got a bit pickier
about the feature test.

I would feel _most_ comfortable with float layouts in Safari. I don't trust
that this will be fixed soon, or that there aren't more bugs; they're not
transparent about what features and bugs they're working on, and their dev
cycle is suuuuper long compared to every other browser :/

**Comment by jenlampton** [comment] 2016-07-02 02:03
I like that idea too. Right now Safari 9 is not using the float fallback since it detects that flexbox is supported. Is there another JS sniff we can do to find out if it's safari 9 so we can add the float fallback here too?

**Comment by wesruv** [comment] 2016-07-02 02:14
Even with my latest pr? I thought I had it...

**Comment by jenlampton** [comment] 2016-07-02 02:25
I think we merged your latest PR. So, probably not?

**Comment by Graham-72** [comment] 2016-07-02 04:48
> would you be willing to test this PR on your site?

Yes, it is working fine thanks. :+1: 

All I need now is a fix for the serious 'disappearing images' problem #1373 - it's a showstopper for me.

**Comment by wesruv** [comment] 2016-07-02 23:45
Blargggg, I was testing Safari 8 apparently.

Safari 9 is passing our stricter flex box tests with flying colors, but still has the wonderful bug. I double checked and Safari is calculating column widths properly, but for some stupid reason clears the last column :angry: 

I made a PR that sniffs for the Safari browser and forces it to fail the flex box test, which will trigger the float fall back. Tested to make sure Chrome still gets flex layouts, and it does.

Not happy with 'browser sniffing' as a solution, but I'm not sure what else to do :disappointed: 
https://github.com/backdrop/backdrop/pull/1456

**Comment by wesruv** [comment] 2016-07-02 23:56
In doing more research, I stumbled on this:
https://github.com/philipwalton/flexbugs

Will probably be helpful, haven't read through all of it (yet)

**Comment by jenlampton** [comment] 2016-07-03 04:10
Yes, I also posted that in [this comment](https://github.com/backdrop/backdrop-issues/issues/1985#issuecomment-229837848), above :)

**Comment by wesruv** [comment] 2016-07-04 20:41
Hah! It appears I will never get better at reading.

**Comment by quicksketch** [comment] 2016-07-22 20:29
> For whatever reason, adding a content property in the :before (but not :after it seems) causes Safari to miscalculate the wrapping of flex items.

Hm, well now I can't see a reason why we are adding a `:before` property in the first place. Clearfix tricks only need the `:after` property to fix floating issues (https://css-tricks.com/snippets/css/clear-fix/) So perhaps the only thing needed here is to delete the `:before` statement entirely, then Safari starts working properly with the flexgrid. We also seem to have a lot of redundancy in the definitions of `.row` and `.container`. I'll file a PR cleaning up the clearfixing that should fix Safari 9.

**Comment by quicksketch** [comment] 2016-07-22 20:34
PR at https://github.com/backdrop/backdrop/issues/1467 that seems to fix flexbox entirely on Safari and should maintain clearfix as expected.

**Comment by jenlampton** [comment] 2016-07-28 23:45
I have a site that is using Bootstrap, and bootstrap was adding the same clearfixing that was breaking with flexbox in Safari 9.11.  After fixing Bootstrap, the fix in the recommended patch worked for me too!

While digging around in the bootstrap code I did find this note about why that was added: 

```
// 1. The space content is one way to avoid an Opera bug when the
//    contenteditable attribute is included anywhere else in the document.
//    Otherwise it causes space to appear at the top and bottom of elements
//    that are clearfixed.
```

Do we care about the use case of Opera + Contenteditable? Do we care about it more than everyone running Safari 9.11?

**Comment by quicksketch** [comment] 2016-07-28 23:49
> What about the use case of Opera + Contenteditable? I personally care about that use-case less than everyone on modern versions of Safari (so RTBC from me) but it might still be worth worrying about in a follow-up issue.

Yeah, each Opera and Contenteditable are less-common situations. Seems like something that should be reported upstream to bootstrap, I'm sure they'd reach the same conclusion.

**Comment by quicksketch** [comment] 2016-07-29 01:15
Bootstrap already had this bug reported once (but closed), I've posted a comment to the original issue at https://github.com/twbs/bootstrap/issues/18306. Let's make a new issue if that one doesn't get reopened by the administrators.

**Comment by jenlampton** [comment] 2016-07-29 01:17
Thanks.  @wesruv would you be willing to keep an eye on that Bootstrap upstream issue?

**Comment by quicksketch** [comment] 2016-07-29 01:19
I've merged https://github.com/backdrop/backdrop/pull/1467 for 1.4.4.

**Comment by wesruv** [comment] 2016-08-05 01:31
So I'm still able to trigger this bug at ~1400px wide, but not at ~900px.

This is through Browser Sync, Safari 8 on Yosemite.

I setup a theme called Bare that is just an info file (no CSS) to make sure this wasn't somehow theme CSS related.

Here's a video, I actually found out it was working ~900px while recording, so enjoy the stammering and smash cut!
https://goo.gl/QIwy0q

**Comment by wesruv** [comment] 2016-08-05 01:32
I'm out of brain power for the evening, might try to take a crack at this later :stuck_out_tongue:

**Comment by quicksketch** [comment] 2016-08-05 22:05
> Here's a video, I actually found out it was working ~900px while recording, so enjoy the stammering and smash cut! https://goo.gl/QIwy0q

Lol, I love the finishing thought in that video. "I hate you webkit." while cool as a cucumber.

I'll have to try this out again. I think in my testing I was only looking at Safari 9, not 8, so I'll have to take another look. :stuck_out_tongue:

**Comment by quicksketch** [comment] 2016-08-06 00:16
Okay I tried this out and found a different problem (I think). It looks like with no styling at all (e.g. running the Stark theme), the tabs, breadcrumb, and content are piling on top of each other when at desktop size (as seen in Wes's video). It does *not* seem to be an issue with Safari however, this happens in all browsers. 

With the default tab styling, the tabs are floated but the wrapper itself is not clearfixed, so you have this issue:

![selection_160](https://cloud.githubusercontent.com/assets/100206/17453386/22a9c3e8-5b30-11e6-8b50-41629c09967b.png)

Adding `clearfix` class to the tabs wrapper seems to work, or we could manually add the clearfix CSS in `system.theme.css` for the default tab styling.

**Comment by quicksketch** [comment] 2016-08-06 04:47
Hey @wesruv, could you try out this PR and see if it helps the desktop-size breakpoint? https://github.com/backdrop/backdrop/pull/1472

As I mentioned in the last comment, this isn't a fix for flexbox or Safari so much as a fix for our layouts in general in regards to the tabs. I think it would fix what I saw in your video (or at least help).

**Comment by quicksketch** [comment] 2016-08-15 02:16
I merged in https://github.com/backdrop/backdrop/pull/1472 because it fixed a somewhat obvious problem with the tabs floating when using a theme with no CSS (falling back to the system-only CSS).

I'd still love to have another confirmation/review of this problem. I don't think we'll hold up the release of 1.4.4 for this at this point, as we've definitely improved the situation but perhaps not 100% solved it. I'll leave this open to get another review or work on this further if needed. Please close if it looks like we've got it now.

**Comment by jenlampton** [comment] 2016-08-15 02:19
> I don't think we'll hold up the release of 1.4.4 for this at this point

👍  good move! :)

**Comment by Graham-72** [comment] 2016-08-16 14:42
> anyone needing to test layouts

@jenlampton I have found there is a problem at the moment with http://jenlampton.com/moscone on an iPad. Are you aware of this? Not being an iPad owner I haven't yet been able to check the other layouts.

**Comment by jenlampton** [comment] 2016-08-16 21:41
Yes, this is the "sidebar disappears" problem that we have fixed in 1.4.4.

**Comment by Graham-72** [comment] 2016-08-17 05:37
But it wasn't working in Chrome on the iPad either, which got me worried.

**Comment by jenlampton** [comment] 2016-08-17 06:11
I still think we should be testing the "fixed" layouts and not the ones we know are broken. If I get some time I'll throw the new code up on jenlampton.com and we can play with that. :)

**Comment by Graham-72** [comment] 2016-08-17 06:28
> throw the new code up on jenlampton.com

That would be very helpful, maybe once 1.4.4 is available.

**Comment by quicksketch** [comment] 2016-08-19 00:57
> But it wasn't working in Chrome on the iPad either, which got me worried.

Wes pointed out during the [Backdrop meeting today](https://www.youtube.com/watch?v=Y42L16pwgYY) that on iOS Chrome (and even Firefox) use the same webkit rendering engine as Safari. Apple doesn't allow other rendering engines, so all browsers use the Safari engine. As such you'd see the same result regardless of browser on iOS.

[1.4.4 has been released](https://github.com/backdrop/backdrop/releases/tag/1.4.4), I'll be pushing out Pantheon updates shortly. Perhaps you'll be able to try it out? We're leaving this issue open until it can be confirmed/denied that the Safari problem has been fixed. We've fixed some things to be sure, but it's not clear if we're all seeing the same problems.

**Comment by jenlampton** [comment] 2016-08-19 04:42
Well, all the layouts look pretty good to me, but we may have a bug in taylor flipped that I didn't notice before. https://www.jenlampton.com/taylor_flipped

**Comment by quicksketch** [comment] 2016-08-19 04:47
> Well, all the layouts look pretty good to me, but we may have a bug in taylor flipped that I didn't notice before.

Yikes... make a new issue? Not related to Safari.

**Comment by jenlampton** [comment] 2016-08-19 04:48
Here's the new issue https://github.com/backdrop/backdrop-issues/issues/2078

**Comment by quicksketch** [comment] 2016-09-01 04:59
Please reopen if there is still an issue here (or open a new one). It seems that we've got this handled.

**Closed by quicksketch** 2016-09-01 04:59 UTC
Labels: audience - design, pr - needs review, status - has pull request, type - bug report
