### ISSUE TITLE
Default URL pattern for nodes not saved

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1915] opened 2016-05-21 04:04 UTC
Steps to reproduce:
1. Create a new content type
2. Fill out the form, including customising the 'Default URL pattern' under the 'URL pattern' vertical tab
3. Save the new content type
4. Visit /admin/config/search/path/patterns or re-edit the content type to view the URL pattern for the new content type
5. It hasn't changed from the default

I believe this is because it's saved before the content type's name is saved, as the 'path.settings.json' file has saved the new URL pattern under `node__pattern` (notice double underscore and missing content type name).

**Comment by Dinornis** [comment] 2017-01-07 20:02
@BWPanda I was unable to reproduce this in 1.5.2, looks like this has been fixed, can you please confirm.

**Comment by BWPanda** [comment] 2017-01-19 00:01
I can confirm that this does indeed seem to be fixed now!

**Closed by BWPanda** 2017-01-19 00:01 UTC
