### ISSUE TITLE
Fixed: Administrator Role form saves wrong value on sites with numeric role machine name

### ISSUE THREAD

**Issue by jromine** [backdrop/backdrop-issues#5528] opened 2022-03-03 05:13 UTC
## Description of the bug

Upgrading a Drupal 7 site creates roles where the machine name is a number, like "3". This breaks the code that generates the Administrator Role form element in user_admin_roles() form. Specifically the call to array_unshift() renumbers numeric keys of the $roles array.  The select element generated is:
```
<select id="edit-user-admin-role" name="user_admin_role" class="form-select">
<option value="0">disabled</option>
<option value="1" selected="selected">Administrator</option>
</select>
```
The option value for the "Administrator" choice should be "3".

Note that this will also happen if you create a role with a numeric name, such as "7".

## Steps To Reproduce

To reproduce the behavior:
1. Upgrade a Drupal 7 site with an Administrator Role set
2. Visit Administration > Configuration > User accounts > Roles
3. Notice that the Administrator Role appears to be 'disabled'
4. Change the Administrator Role to your D7 admin role, and Save.

## Actual behavior

user_admin_role configuration setting is set to 1

## Expected behavior

user_admin_role configuration setting should be the array key for "Administrator" role, i.e., "3".

**Comment by BWPanda** [comment] 2022-03-03 05:19
> Upgrading a Drupal 7 site creates roles where the machine name is a number, like "3".

I don't think this is correct. I think the situation is that in D7, roles have an ID (as opposed to a machine name), and perhaps Backdrop isn't properly converting those IDs to machine names... It's not that we're creating roles with numerical IDs.

**Comment by argiepiano** [comment] 2022-03-03 05:20
Thank you @jromine ! I think we should consider assigning a proper machine name to the Administrator (and other roles) upon upgrade from D7. There are several places where the roles array is used, and I can imagine it would have similar problems, with numerical keys

I'm wondering what the rationale behind not assigning proper machine names in user_update_1007() . That's where the role table is made into config files. The update assigns machine names to authenticated and anonymous, but fails to do so for any other role. I guess the issue is that you have to convert the human name into a machine name, and they wanted to avoid that? The result is that the D7 numerical role ID ended up being used as machine names...

argiepiano: They clearly knew what they were doing in that update

    $role_data = array(
      'name' => $row->rid,
      'label' => backdrop_ucfirst($row->name),
      'weight' => $row->weight,
    );

**Comment by BWPanda** [comment] 2022-03-03 05:25
I guess with numerical IDs in Drupal it's technically possible to have, e.g.:
```
3 => 'Administrator',
4 => 'Editor',
5 => 'Administrator',
```
Since the numerical IDs are different, the two 'Administrator' roles are different. But in Backdrop if we try to convert them to machine names, they'll have the same machine name and cause all sorts of problems...

Just a guess.

**Comment by jromine** [comment] 2022-03-03 05:33
The same bug happens if you create a new role with a name like "7".

**Comment by jromine** [comment] 2022-03-03 05:33
PR submitted https://github.com/backdrop/backdrop/pull/3971

**Comment by argiepiano** [comment] 2022-03-03 05:34
> I guess with numerical IDs in Drupal it's technically possible to have, e.g.:
> 
> ```
> 3 => 'Administrator',
> 4 => 'Editor',
> 5 => 'Administrator',
> ```
> 
> Since the numerical IDs are different, the two 'Administrator' roles are different. But in Backdrop if we try to convert them to machine names, they'll have the same machine name and cause all sorts of problems...
> 
> Just a guess.

Not quite. D7 doesn't allow you to use the same name for two roles, despite the fact that it stores them keyed by numerical Role ID

**Comment by BWPanda** [comment] 2022-03-03 05:37
Ok, good to know.

**Comment by argiepiano** [comment] 2022-03-03 05:37
So it would have been straightforward to use D7's name and use it as machine name in Backdrop... Now the question is: do we create a new user_update_N() to take care of converting those numerical machine names into proper machine names, or do we just focus on the issue that @jromine reported here (with a partial fix that focuses on the select box he refers to)?

**Comment by jromine** [comment] 2022-03-03 05:38
I am curious now if the upgrade process correctly assigned my "Administrator" (machine name: 3) role as the user_admin_role for the site. I will need to re-test an upgrade to see.

**Comment by argiepiano** [comment] 2022-03-03 05:38
> I am curious now if the upgrade process correctly assigned my "Administrator" (machine name: 3) role as the user_admin_role for the site. I will need to re-test an upgrade to see.

Yes, it did. I checked that. It gets messed up (to "1") when you submit that form with the select box

**Comment by jromine** [comment] 2022-03-03 05:40
@argiepiano one less thing to fix after an upgrade. Just don't look at the config page. 😉

**Comment by laryn** [comment] 2022-03-03 05:54
*Maybe* the RID was saved instead of converting to a proper machine name in case contrib modules needed it later in their upgrade process? That's a guess.

**Comment by indigoxela** [comment] 2022-03-03 07:00
> Maybe the RID was saved instead of converting to a proper machine name

That's exactly what happens, and I think it's by design.

In system_update_1025() two roles (anonymous and authenticated) get a "machine name" assigned, but additional roles (including admin) keep their numeric keys.

That's in https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/system.install#L2385 I guess.

So after an upgrade from D7, roles other than anonymous and authenticated still have numeric keys and the setting for "The role that will be automatically assigned new permissions..." will not get a value.

Maybe by intention, maybe unavoidable, maybe a bug.

**Comment by indigoxela** [comment] 2022-03-03 07:47
@jromine nice catch! Right, array_unshift() does a bad job here because of the renumbering. No problem for native Backdrop sites, but problematic for migrated ones.

The code looks good. :+1:

A small suggestion: you prepended a "Fix for:" to the issue link in your PR comment, but it should be `Fixes `, to let Github do some magic, like back-linking the PR here and closing the issue, when the code gets merged.

**Comment by indigoxela** [comment] 2022-03-03 07:50
Another suggestion: there seems to be a (random?) test failure of LayoutUpgradePathTest.

@jromine can you close the PR, wait a minute, then reopen it, so tests can run again?

**Comment by argiepiano** [comment] 2022-03-03 13:24
@jromine did you post a PR? I don't see it.

**Closed** 2022-03-13 06:58 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2022-03-13 06:59
Thanks folks for the discussion and fix. I think you landed on the correct reasoning why upgraded roles keep using the numeric ID instead of trying to automate a new machine name. The role ID is used all over the place for assigning permission (such as in views, block visibility, etc) and continuing to use the numeric ID makes it so that those places don't also need to be remapped. I also had concerns about trying to transliterate non-English role labels into machine names. Since it's not possible to (easily) change a role machine name, keeping the less than ideal number was better than creating a non-sense machine name with transliteration that couldn't be changed later.

In any case, the PR at https://github.com/backdrop/backdrop/pull/3971 looks great and solves the immediate problem. Thanks @jromine, @argiepiano, @BWPanda, @indigoxela, and @laryn!
