### ISSUE TITLE
Add Dragon Help module

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#4680] opened 2020-10-03 23:19 UTC
@stpaultim reports in #4675, that at a recent Open Source Day, a couple participants were confused about what the "Site name" should have in it.

Under each field, the `#description` field can be used to show a short help text, but often times a full explanation cannot be done in a sentence or two.  On the set-up page alone, it would take more text than is reasonable explaining how the site name is used in the page title (visible on the browser's tab) and in emails from the site.  And the next form element, the "primary user account," already has text explaining what characters are allowed in a username, leaving no space to explain the special privileges it carries as UID 1.

**Proposed solution**

An [info circle](https://fontawesome.com/icons/info-circle) that opens a pop-up when the user either hovers over it or clicks it can provide a longer, more detailed explanation of the field and how Backdrop uses it.  To make it more user friendly, the Backdrop mascot Drop can appear in the pop-up giving the explanation with dragon-themed examples.

Once the site is set-up, the admin pages can benefit from such "dragon help."  As this may be a lot of extra code with long blocks of HTML, providing a way to put it in a separate file, loaded only when "dragon help" is enabled, would be better DX.  It would be easier for developers trying to work on the forms, as that much HTML will take up a lot of editor screen real estate, and for developers working on the help text itself who would like it to be well formatted in their editors.

One possibility is to add a "dragon_help" folder to modules, with files named after the forms.  For example, `core/modules/system/dragon_help/system_site_information_settings.dh.inc` would have the Dragon Help for the form at `admin/config/system/site-information`.  A "Dragon Help" module can use `hook_form_alter`to add the circle-info icons, wire them to some JS to trigger the help pop-ups, and include the AJAX callback handler to fill in the pop-ups.

**Alternatives that have been considered**

An info circle or "help" link that opens a page on backdropcms.org with a longer explanation.

**Comment by stpaultim** [comment] 2020-10-04 03:52
I like the intent of this feature request. I love any idea that provides more contextual support for Backdrop CMS users/editors/developers. 

My concerns/questions are:

1) Have there been attempts to do something like this before in the Drupal world (and why did they fail)? Specifically, I'm thinking about the help module. How is this similar and how is it different? I have the feeling that the help module in Drupal was not successful (is that correct)?
https://www.drupal.org/docs/8/core/modules/help/help-module-overview

2) This feels like an attempt to deal with this problem systematically (which should be a good thing), but is that too big a project for us to deal with - as opposed to dealing with items one by one? Meaning, can the "Dragon help" module be implemented slowly and be successful, or would it require that we provide a whole bunch of these help queues all at once?

I'm not trying to derail this idea. Just trying to anticipate problems and make sure that if we invest time in this, we avoid previous mistakes.

**Comment by jlfranklin** [comment] 2020-10-04 05:10
>  Have there been attempts to do something like this before in the Drupal world (and why did they fail)?

No idea.  It is true that documenting any project is a lot of work, even for a modest sized project like Backdrop, and a documentation effort is largely what this is.  Finding someone who is willing to lead the effort would be one of the keys to success, IMHO.  (No, that's not me.)

> This feels like an attempt to deal with this problem systematically.  [Can] the "Dragon help" module be implemented slowly and be successful, or would it require that we provide a whole bunch of these help cues all at once?

The module itself as described above is a framework to put the help elements in place and contains no help text items at all.  The help text itself can be added one form or even one field at a time. I think the nature of the project will tend towards adding in batches, but there's no technical reason it has to work that way.

**Comment by stpaultim** [comment] 2020-10-11 20:32
@jlfranklin - I just found this issue which seems to be suggesting a very similar thing. Maybe this issue is a duplicate of that one? What do you think?

https://github.com/backdrop/backdrop-issues/issues/3707

**Comment by jenlampton** [comment] 2020-10-22 20:20
Also related: https://github.com/backdrop/backdrop-issues/issues/1414

**Comment by jlfranklin** [comment] 2020-10-23 18:01
All three of these are very similar.  I think we should close two of them as dups and use the third to track the feature.  Unless one of the issues has much richer information and/or more discussion in it, I'd default to keeping the oldest and closing the newer two.

**Comment by stpaultim** [comment] 2020-10-23 18:39
Well, let's start by closing this one. I'm still not sure which of the other two to keep. I'll update one or the other and include some notes from this one.

**Closed by stpaultim** 2020-10-23 18:39 UTC
