### ISSUE TITLE
Impossible to save new layout

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1255] opened 2015-09-25 07:31 UTC
Have crated a new layout and after inserting blocks in it can not save it:

![untitled-1](https://cloud.githubusercontent.com/assets/13515302/10095150/509355e8-6370-11e5-9c49-86473c5716b2.gif)

**Comment by quicksketch** [comment] 2015-09-25 16:54
Did you add the "Main page content" block more than once within the layout? As the message says, if that block is added more than once, it won't let you save the layout.

**Comment by bd0bd** [comment] 2015-09-26 17:17
No, I did not try to add it second time.
The layout has had no  "Main page content" block and after my try to add it I got this warning :)

**Comment by quicksketch** [comment] 2015-09-28 22:00
>  The layout has had no "Main page content" block and after my try to add it I got this warning :)

I tried to make a layout without a main page content block, then add it again, but I couldn't get this problem to reoccur. Would it be possible to reproduce the problem with a set of step-by-step instructions?

**Comment by bd0bd** [comment] 2015-10-01 14:49
>
Would it be possible to reproduce the problem with a set of step-by-step instructions?

Sorry, I do not remember how it happened but it happened and I was very surprised.
I have deleted this layout and then created a new one again - everything was ok at this case.

I apologize for the delay in answering - I have been much overloaded with my site and needed to rest, to abstracting from GitHub and other social media.

**Comment by klonos** [comment] 2015-10-01 14:55
Glad the issue was sorted after all @bd0bd ...I 'm closing this issue for now since we cannot reproduce it, but feel free to reopen it should this happen again.

**Closed by klonos** 2015-10-01 14:55 UTC

**Comment by quicksketch** [comment] 2015-10-01 23:17
Thanks @bd0bd. Again all the feedback is very appreciated. Please reopen if you can make it happen again.
