### ISSUE TITLE
Basis feature branch: Recoverable fatal error: Argument 1 passed to node_page_title() must be an instance of Node, string given in node_page_title() (line 1815 of node.module).

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2177] opened 2016-09-14 09:51 UTC
...just downloaded a copy of the 1.x-basis branch to give it a spin. Installed over the latest 1.x (removed old core folder, replaced with the 1.x-basis core folder), run update.php, flushed caches, generated a few menu items for the primary navigation (using the already installed Devel module), tied to visit the home page:

Error
The website encountered an unexpected error. Please try again later.

Error message
Recoverable fatal error: Argument 1 passed to node_page_title() must be an instance of Node, string given in node_page_title() (line 1815 of C:\www\core\modules\node\node.module).

**Comment by klonos** [comment] 2016-09-14 09:54
I can visit the admin backend, but when I navigate to the home page, this error comes up.

**Comment by quicksketch** [comment] 2016-09-15 03:15
Hm, did you generate the menu items with Devel? Could you try deleting them and making the menu items manually? I haven't encountered this making links on new or existing sites. I'll try using Devel and see what happens.

**Comment by jenlampton** [comment] 2016-09-15 18:19
I've done several fresh installs of Backdrop without running into this error.  I'm going to try an upgrade of an existing site and see if I can reproduce that way.

**Comment by jenlampton** [comment] 2016-09-15 18:44
No issues with updating an existing site to 1.x-basis branch by copying in the core directory and running update.php. I used drush to run update.php, I'm going to try to do it via the UI and see if that ends up differently.

**Comment by jenlampton** [comment] 2016-09-15 18:48
Manual update also went smoothly with the exception of [this error](https://github.com/backdrop/backdrop-issues/issues/2187) which I don't think is related.  I'm going to mark this as postponed for now.  @klonos please grab the latest 1.x-basis and try again, it could be that things have improved since you opened this issue and now.

**Comment by klonos** [comment] 2016-09-16 00:44
> ...by copying in the core directory and running update.php.

Quick update: this was a local that has been through a series of updates that happened the same way from 1.4.0 (or could be from some 1.3.x). Could be random, but as I said, it was a local test site. Not a biggie. I'll have more time to look into it during the weekend.

**Comment by klonos** [comment] 2016-09-16 00:46
...I guess I'll just drop 1.5.0 on top of it and see if things are fixed 😉

**Comment by quicksketch** [comment] 2016-09-16 01:31
Cool, thanks for the update @klonos. I'll close this out to take it out of the 1.5.0 list. Reopen if it proves necessary.

**Closed by quicksketch** 2016-09-16 01:31 UTC
Labels: status - postponed, type - bug report
