### ISSUE TITLE
Fatal error: Call to undefined function views_fetch_fields() in <...>/core/modules/date/views/date_views_fields.inc on line 27

### ISSUE THREAD

**Issue by john-haus** [backdrop/backdrop-issues#3871] opened 2019-06-17 15:13 UTC
**Description of the bug**
I'm working on a site for a film festival that will show past winners by year.  I've made the view using a contextual filter for the year which works as expected. 
![view-1](https://user-images.githubusercontent.com/272771/59615071-88e40200-90e7-11e9-95e8-eea91d8bc814.jpg)
However, I if I wait a while (not sure how long yet), and try to access the view using a logged out browser (anonymous user), I receive the fatal error. 
![fatal-error](https://user-images.githubusercontent.com/272771/59615282-db252300-90e7-11e9-8f70-ad3a05d2863a.jpg)

Now, if I then go to the views admin and run the query there, it works as expected and the anonymous user can see the page (no error).
![no-error](https://user-images.githubusercontent.com/272771/59615549-4cfd6c80-90e8-11e9-97be-3745c4931a36.jpg)

Tracing the function, I see it resides in /core/modules/views_ui/views_ui.admin.inc - so my question becomes could this be linked to access to the this file?  Once the view works my guess is it's working until the cache expires or something along these lines, but I need someone significantly smarter than be to figure this out!

Thanks for any help you all can give.

---
PR by @laryn: https://github.com/backdrop/backdrop/pull/2741

**Comment by klonos** [comment] 2019-06-17 17:14
Hey @padprint ...since the error points to `date_views_fields.inc`, I guess that you must be right that it must be related to the date field used in the contextual filter. In order to help you though, we'd need steps to reproduce this on a vanilla Backdrop installation. You could try the following:

1. clone the view.
2. remove things from it, till you have a minimal version of it, where the problem is reproducible
3. export that view and attach a .txt file with it here (or provide a link to a code gist)

**Comment by laryn** [comment] 2019-06-17 18:38
@padprint I don't know that it's related, but what does that "Award Weight" Multifield look like?

**Comment by padprint** [comment] 2019-06-17 18:38
Hey @klonos, here's paired down test view that shows the same issue.  
[test_view.txt](https://github.com/backdrop/backdrop-issues/files/3298363/test_view.txt)

I've also noticed that I can force the error to occur simply by flushing the cache on the site, this immediately results in the fatal error.

thanks a lot for having a look!

**Comment by padprint** [comment] 2019-06-17 18:42
@laryn 

The Award Weight is a multi field consisting of a name (text) field, a detail (text) field, a select list from 1 to 20 to assign a weight to the award and a boolean to determined whether the film won an award or not.  In my simplified version i've  removed it from the equation…i think :)

**Comment by laryn** [comment] 2019-06-17 18:57
@padprint Can you remove it from the Sort Criteria area as well and test again?

**Comment by padprint** [comment] 2019-06-17 19:03
@laryn I've removed the sort, and have the same results.  Once I use the admin ui to test, it works fine, as does the page.  if i then flush the cache and retry the page, I get the undefined function.

**Comment by padprint** [comment] 2019-06-17 19:23
I was able to test against a demo i spun up:

https://master-dtlxgdrkfzki37vm8lazlfiht7twcmxe.tugboat.qa/test/2005. 

While you don't get the PHP debug, the mechanics work the same.. use the Admin UI and the page works until the cache expires.  This used only a base install with no modules.

If it helps, I can install a vanilla site, make the content type and the view, and upload a mysqldump.

**Comment by laryn** [comment] 2019-06-17 19:46
Verified on my local. STR:

 - add a date field to a content type (in my case I followed the example of only allowing the year, with no month,day,time)
 - create a view with a page display, e.g. **test/%**
 - add a contextual filter of this date field
 - try to visit **test/2019**

Watchdog shows: 

> Error: Call to undefined function views_fetch_fields() in _date_views_fields() (line 27 of /path/core/modules/date/views/date_views_fields.inc).

**Comment by laryn** [comment] 2019-06-17 19:58
I'm not saying this is necessarily correct (will need eyes from a core committer), but I made a PR that seems to solve it. @padprint Can you test?

https://github.com/backdrop/backdrop/pull/2741/files

**Comment by padprint** [comment] 2019-06-17 20:07
yessir, on first look that seems to fix it!

**Comment by klonos** [comment] 2019-06-18 02:43
[[Change notice] Move views_fetch_fields into an autoloadable class](https://www.drupal.org/project/views/issues/1962234) came up during my initial research/investigation. This issue has been inactive since 2013, then recently moved to D8 core views queue, and then back to Views 7.x; now closed as outdated. Thought I'd mention this.

**Comment by quicksketch** [comment] 2019-08-04 19:18
Initially looking at this, my impression is that we shouldn't be moving the function to a new file. However, this function is currently in `views_ui.admin.inc`, part of Views UI module. Since that module could potentially be turned off entirely, that would mean that views that contain Date fields wouldn't work if you turned off Views UI. That seems unacceptable.

So I think this solution is a good one. @klonos, what do you think? This may impact our efforts to maintain 1-to-1 correlation with Drupal 7 Views. If D7 has solved this, we should do it the same way. But from the looks of that issue, they might not be planning on changing it.

**Comment by klonos** [comment] 2019-08-04 19:43
I agree with the reasoning to move the `views_fetch_fields()` function to a "safer" place.

If I recall correctly, during various core and contrib crossports, I have come across quite a few cases where things have been moved around. I do not find it much of a trouble personally (things get tricky only in cases where we have completely removed things); it sometimes does take slightly more time to find where things should go, but no biggie. All good by me 👍

**Comment by quicksketch** [comment] 2019-08-07 17:21
Super, merged https://github.com/backdrop/backdrop/pull/2741 into 1.x and 1.13.x. Thanks @padprint for your patience and reporting this issue! And thanks @laryn for providing the fix.

**Closed by quicksketch** 2019-08-07 17:21 UTC
Labels: status - has pull request, status - fixed
