### ISSUE TITLE
How to manage D7 to Backdrop upgrades which store role RID in tables?

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#2842] opened 2017-09-09 11:47 UTC
## Describe your issue or idea
This came up in https://github.com/backdrop-contrib/ubercart/issues/121 so I thought I'd post here for reference, and in case anyone can suggest an alternative solution:

When we upgrade to Backdrop, we lose the connection between numeric `rid` and the new backdrop role names during the upgrade. If then a D7 module stores numeric `rid`s in a table, then how would you match these `rid`s to the Backdrop role names?

### Steps to reproduce (if reporting a bug)
A D7 site has some custom roles. In the roles table, `rid` => `role_name` is the following:
```
2 => apple
3 => plum
etc
```

On upgrade, all reference to `rid` is lost and Backdrop creates role configs using the `role_name`, like `user.role.apple.json`.

A module in D7 though which deals with roles (like Ubercart which grants roles) stores references to role in its own tables as numeric `rid`s such as `rid => 2`. When this module is converting to Backdrop, there is no record now of what `"2"` was.

So how do we upgrade this module without losing data? 

I proposed that it would require running a script on the D7 module before the upgrade to save the `role_name` to the module's tables.

Or maybe Backdrop core should save a reference to `original_rid` on upgrade?

**Comment by klonos** [comment] 2017-09-13 23:15
> Or maybe Backdrop core should save a reference to `original_rid` on upgrade?

I think that this option would be best.

**Comment by herbdool** [comment] 2017-09-14 00:19
Something like original_rid is the most robust since someone might not have the contrib module there during the upgrade.

**Comment by jenlampton** [comment] 2017-09-14 01:14
> When we upgrade to Backdrop, we lose the connection between numeric rid and the new backdrop role names during the upgrade. If then a D7 module stores numeric rids in a table, then how would you match these rids to the Backdrop role names?

There's already a solution for this in core. You can order the updates so that your contrib module updates are run before the core role table has been deleted. Every core system has two updates, the one where things are converted, and then another one where the things are deleted, specifically so contrib has a chance to get between those two actions. 

I'll see if I can find an example of a contrib module that does this, but the hook to use is `hook_update_dependencies()`

**Comment by herbdool** [comment] 2017-09-14 02:03
@jenlampton that only works if the module is there when doing the update. If someone adds the module after doing the core update then they miss that step.

**Comment by jenlampton** [comment] 2017-09-14 03:22
@herbdool That's Correct. But if they aren't upgrading from a Drupal 7 it won't be an issue. If they are doing an upgrade from Drupal 7, they should follow the upgrade instructions so things will work like they are supposed to :)

**Comment by herbdool** [comment] 2017-09-14 04:35
@jenlampton in my experience with D6 to D7 upgrades you can't rely on it working smoothly all at once with all modules. I've had problems with Rules, Webform. Especially CiviCRM isn't usually upgraded at the same time and it actually has modules which rely on the rid.

**Comment by jenlampton** [comment] 2017-09-14 04:38
@herbdool I'm not sure we should build contingencies into core for the use-case of "if people aren't doing things correctly". That's a very slippery slope.

**Comment by laryn** [comment] 2017-09-14 05:04
@jenlampton Just spitballing here, but what if a certain module isn't ported yet when someone upgrades to Backdrop, but then is later ported? They're just out of luck?

**Comment by jenlampton** [comment] 2017-09-14 05:18
@laryn It would depend on the module. If it's something like webform or ubercart that depends on RIDs, VIDs, or anything else that core's stopped using in the transition to config, then yes.

It's generally a bad idea to keep old data floating around without the module that created it, just because that module was the only tool that knew how to handle that data safely (including how to delete it properly).

However, if the developer for the site is aware of the risks then there may be ways around it. For example: keep a copy of the old D7 database. Uninstall the module completely (on Backdrop) until it's been ported, then install fresh.  Run the update as intended on the old Drupal 7 db, and then **this part may be dangerous** import any database tables or config from the correctly-updated site.

What modules do with their data can vary greatly. Some just add variables/config, which is not a huge risk even to have lying around without the module. Some add database tables, which is more risky, but still can be managed. Some, however, alter existing database tables (like the node table) and if a module like that is lost or upgraded separately from the code that manages the main table, you could be in big trouble.

**Comment by serundeputy** [comment] 2017-09-14 12:06
I think we could either:

* keep the `roles` table around in Backdrop for the `1.x` cycle and deprecate in `2.x` so that modules that rely on it will have it.

* Add the `rid` reference to the config files with an `rid` key:

`user.role.anonymous.json` might look like this:
```json
{
    "_config_name": "user.role.anonymous",
    "name": "anonymous",
    "label": "Anonymous",
    "rid": 0,
    "weight": "0",
    "permissions": [
        "access content",
        "access comments",
        "use text format filtered_html"
    ]
}
```

* the run script to prepare Drupal site for Backdrop upgrade would work too.  I guess we could start a list of known modules that need the `roles` table.  Have the script:
  * on backdrop upgrade check for those modules
  * create a temp store of the `roles` table data
  * perform the Backdrop upgrade as normal
  * backfill the temp store `roles` to the modules table, say `module_with_role_mapping_roles`

Those are the ways I can see forward.  I think I prefer the second option adding `rid` key to the config file.

**Comment by serundeputy** [comment] 2017-09-14 12:11
sounds to me that @jenlampton is saying option three as an update hook in the module in question, in this case `ubercart`.

**Comment by docwilmot** [comment] 2017-09-14 13:56
Thx all, I wasnt aware of `hook_update_dependencies()`. I suspect that would work for the majority of contrib. 

@herbdool as far as I know, update hooks run on disabled modules; is there a reason why you would need to completely remove the module package while upgrading rather than keeping it there but disabled? 

For my currrent use-case with UC though, and to account for those occasions when the module *is* absent during the core upgrade, I'm thinking the following plan:
- use `hook_update_dependencies()` to add a `role_name` column to any table with an `rid`; make it run before Backdrop drops role table
- in another `hook_update_N()`, for those tables check if a `role_name` column exists, make the `rid` column `varchar` and swap the `role_name` in there
- if the `role_name` column is missing, then we probably in the situation as @herbdool warns about, and then we proceed as in my alternate suggestion here https://github.com/backdrop-contrib/ubercart/issues/121#issuecomment-328585393

The problem with going the `hook_update_dependencies()` route alone, is that if a person is building a complex site and decides to do it incrementally as @herbdool suggests, they may be well down the road of porting and fixing modules and themes and etc before they finally decide to re-introduce the affected module and then realise that their functionality is broken, in which case there would be little option but to re-upgrade and lose progress or fiddle with the database, etc. I think the option to match and switch roles would be good to have.

@serundeputy I think your final point suggestion would be unnecessary if using `hook_update_dependencies()`. My idea for a script was to run it on the Drupal site, to add the roles column there.

**Comment by jenlampton** [comment] 2017-09-14 17:45
@docwilmot for your second bullet, you could simply drop the `rid` column instead of duplicating data across the two columns. 

> if a person is building a complex site and decides to do it incrementally

Upgrading a site incrementally is not supported - for exactly this reason. Any contrib module may need to run it's updates between two of core's updates. 

If we teach people that it's okay to do things incrementally for some projects (but not for all) we're going to be creating unsafe habits in our users. Doing this to our users is dangerous. We're going to be setting them up for failure somewhere down the road.

Most people won't know the difference between which projects can be updated separately and which can't, and they certainly won't check for this hook before removing a module (or not adding it in the first place). All modules should be there when upgrading - because that is how Backdrop (and Drupal) works. 

For your third bullet @docwilmot, It would make more sense to set a message to the user telling them what might have gone wrong, and instead teach them how to do things correctly. :)

@serundeputy we can't do any of the recommended approaches in core for supporting RID (or VID or anything else that has already been removed) because these things have already been removed from core. All Backdrop sites today do not have them, so there is no way we can write an upgrade path to get them back.

However, there is a workable contrib solution: A separate contrib module could be added during the upgrade process (hopefully one that depends on bad judgement). The module could implement `hook_update_dependencies()` to create config files that contain the mappings between things that were deleted from core, and the new values. For example: mapping vocabulary to vid, or role name to rid.

This would also serve the purpose of training users that this is the wrong way to do things (because the module depends on bad judgement) and maybe developers too, because if they need their module to depend on a module that  depends on bad judgement, they are also not doing things correctly.

**Comment by docwilmot** [comment] 2017-09-14 18:39
> for your second bullet, you could simply drop the rid column instead of duplicating data across the two columns.

I would drop the `role` column after the swap. Dropping `rid` would require changing `rid` to `role` in dbase queries. Which in retrospect is not a bad idea, but more work for me.

Re the rest of your post, I agree with everything. The only reason I'm supposing to support the bad practice is on the assumption that this is a common thing to do. If you (and everyone else) believe this is not the case, then I agree, we should modify step three to a warning. 

> However, there is a workable contrib solution

I think this would be redundant. My initial proposal was in case a person *did not know*; but using such a module would imply that you actually know that youre doing an unnecessary thing. You should just disable and leave the module files in there and let Backdrop do its thing.

**Comment by jenlampton** [comment] 2017-09-14 18:45
> I would drop the role column after the swap. Dropping rid would require changing rid to role in dbase queries. 

Having a `rid` column when there's not an ID in there is not great DX. Best case scenario, that change would happen the same time as the rid was replaced with role name. Definitely more work, but a find/replace on rid would also help find all places in the module that need to be updated. Maybe a good idea anyway?  :)

> using such a module would imply that you actually know that you're doing an unnecessary thing

True. But something like that might still be a possible solution for something like CiviCRM that is mostly separate from the CMS anyway.

> The only reason I'm supposing to support the bad practice is on the assumption that this is a common thing to do.

If it's a common thing that people are making dangerous mistakes - maybe that's even more reason to help train them not to? :)

**Comment by herbdool** [comment] 2017-09-14 19:31
I've rarely done a Drupal 6 to 7 upgrade all at once. According to the docs doing the upgrade in steps--first core then contrib--is actually recommended as one option: https://www.drupal.org/docs/7/upgrade-to-drupal-7/upgrading-contributed-modules-and-themes-from-drupal-6-to-drupal-7

> First perform the core upgrade as described in the UPGRADE.txt file. Then you can update and re-enable your non-core modules

As far as I can tell, `hook_update_dependencies()` allows an update to run *after* another update, but don't see any way to have it run *before* a particular update such as before a table is removed. Am I missing something? How do you specify how to get it to run *before* a different update? This hook doesn't look like it'll do the job.

https://drupal.stackexchange.com/questions/58044/when-running-db-updates-in-what-order-are-module-update-hooks-called
https://api.drupal.org/api/drupal/modules!system!system.api.php/function/hook_update_dependencies/7.x

**Comment by jenlampton** [comment] 2017-09-16 04:41
> According to the docs...

Yeah, that's the problem with Drupal's documentation. It's often out of date. [hook_udpate_dependancies](https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_update_dependencies/7.x) was only added in Drupal 7. Those docs likely predate it, and were probably never updated.

> As far as I can tell, hook_update_dependencies() allows an update to run after another update, but don't see any way to have it run before a particular update such as before a table is removed. Am I missing something? How do you specify how to get it to run before a different update? This hook doesn't look like it'll do the job.

It can do both. This is the hook Drupal 7 and Backdrop both use to solve this exact problem. It's been doing the job for 7+ years now ;)  Let me see if I can find an example module so you can see how it's used, that might clear things up.

**Comment by jenlampton** [comment] 2017-09-16 04:45
here are some examples of use:

* [Project module](https://github.com/backdrop-contrib/project/blob/1.x-1.x/project.install)
* [Similar module](https://github.com/backdrop-contrib/similar/blob/1.x-2.x/similar.install)
* [Tablefield module](https://github.com/backdrop-contrib/tablefield/blob/1.x-2.x/tablefield.install)
* [Taxonomy menu module](https://github.com/backdrop-contrib/taxonomy_menu/blob/1.x-1.x/taxonomy_menu.install)

**Comment by herbdool** [comment] 2017-09-16 05:48
Thanks for the explanation. I now see that the Drupal API explains it in the code example. Though it does have a warning that in the "before" direction it should only be used rarely:

```
 // Indicate that the mymodule_update_7001() function provided by this module
  // must run before the yet_another_module_update_7004() function provided by
  // the 'yet_another_module' module. (Note that declaring dependencies in this
  // direction should be done only in rare situations, since it can lead to the
  // following problem: If a site has already run the yet_another_module
  // module's database updates before it updates its codebase to pick up the
  // newest mymodule code, then the dependency declared here will be ignored.)
  $dependencies['yet_another_module'][7004] = array(
    'mymodule' => 7001,
  );
```

**Comment by jenlampton** [comment] 2017-09-16 05:59
Yes, that's accurate. If this is better than our docs in Backdrop, we should update ours to match!

**Comment by jenlampton** [comment] 2017-09-16 06:00
From https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_update_dependencies/1

```php
function hook_update_dependencies() {
  // Indicate that the mymodule_update_1000() function provided by this module
  // must run after the another_module_update_1002() function provided by the
  // 'another_module' module.
  $dependencies['mymodule'][1000] = array(
    'another_module' => 1002,
  );
  // Indicate that the mymodule_update_1001() function provided by this module
  // must run before the yet_another_module_update_1004() function provided by
  // the 'yet_another_module' module. (Note that declaring dependencies in this
  // direction should be done only in rare situations, since it can lead to the
  // following problem: If a site has already run the yet_another_module
  // module's database updates before it updates its codebase to pick up the
  // newest mymodule code, then the dependency declared here will be ignored.)
  $dependencies['yet_another_module'][1004] = array(
    'mymodule' => 1001,
  );
  return $dependencies;
}
```

**Comment by klonos** [comment] 2017-09-17 15:20
Although I do not 100% understand the technicalities behind this, I understand your concern about doing things properly and not endorsing things that will be creating "bad habits" @jenlampton. All that seems right from a veteran dev point of view. Now, from an end user and newbie point of view, I think that Backdrop should allow life to be made easier. That's the whole point of using it instead of D8 after all, right?

I think that keeping a reference "backup" of `rid` to role name would be a really good solution here. Not sure if we should be storing these within individual `user.role.*.json` files as @serundeputy suggested though (although I personally would not mind that either). Perhaps create a separate `rid.2.role.name.mappings.json` file (and respective json files for VID, TID etc where needed) during D7 to Backdrop upgrade. This way, the "redundant" data will be out of the way of those that want "clean" .json files, yet still available for those that might need to refer to them.

Bottom line is that reading this post from start to bottom as an "outsider", I get this:

- Huston, I have a problem
- It's not a (Backdrop) problem, you haven't done things properly.
- OK, I should have done things "properly", but please don't punish me for that. Any way to have my old data/site settings back?
- Tough luck buddy!

...wouldn't it be much better if we told people something along the lines of "You shouldn't have done things that way... BUT we care for you, so here's where you can find a backup of the mappings that we have created for you during the D7 to Backdrop upgrade."

Site builders could then perhaps set up a local with their old D7 db, (re)run the upgrade and just grab those *.mappings.json files (instead of having to mess with the DB), then drop them on their prod site, where the newly-ported contrib modules can make use of them for their installation/migration without having to care too much about having to know how to use `hook_update_dependencies()` (or that it even exists).

New Backdrop sites that are upgraded from D7 would benefit from this straight away (since these mapping backups would be created for them), while old D7-to-Backdrop sites that have problems with contrib modules that have been ported at a later stage will be able to recover with very minimal effort (provided they have kept a backup of their old D7 db).

Doesn't that sound better?

**Comment by jenlampton** [comment] 2017-09-17 16:49
It is not possible to add rid information into backdrop 1.x for any site
already upgraded to 1.x.

Adding it for some sites (but not all) creates an even more dangerous
situation, because now not only are we teaching users to do things wrong,
but we're also teaching developers to do things wrong by allowing them
access to data that will not always be there for all sites, and should
never be used.

There is already a safe solution to this question in core, and it has been
around since 7.x.

Adding a rid or similar is absolutely not something we should consider for
core as it would create a terrible experience for both users and developers
as peoples sites will start breaking. it will introduce numerous bugs where
there was no problem before.

As mentioned above, this can be done  in contrib, so if people want to
jeopardize the stability of their own sites by adding it, that is fine.
let's add the contrib-candidate tag and close this issue.

**Comment by docwilmot** [comment] 2017-09-17 18:21
As I noted  above a contrib solution wouldnt make sense. Even if developers who port modules take all precautions, and avoid the bad habits, and use `hook_update_dependencies()`, end users who update their sites who dont know that there is the chance of losing data, who follow the established Drupal advice of upgrading core first, will still be in trouble. Those people, if they had not known about this issue, would also not know about that contrib module. And its those persons whom @klonos is referring to with the "tough luck buddy" consolation.

Also, it seems that a few of the experienced persons here already update in stages, so it seems likely that it might be in fact a common occurrence to do so. Especially if this has been the recommended way to do it all along. We havent had this pop up yet though, maybe because we havent had any modules which would require this? Now that Ubercart and CiviCRM are ready, maybe its time?

I dont think its "dangerous" to do this. Adding it would be for all sites from a minor version onwards. Already upgraded sites would of course not need it. We are considering this for a minority of sites which may need it, those with Civi and UC (and maybe others) installed. It would be a node on a `json` file which no module would access after upgrade. I see no danger.

But as @klonos says I do see an opportunity to avoid a painful negative first impression.

And finally, I think if the majority of the people chiming in here are in favor of this, we may need some more consensus rather than closing the issue.

**Comment by jenlampton** [comment] 2017-09-17 19:33
Rather than continuing to talk about the approach mentioned  here -- it is
not only solving a problem that doesn't exist, teaching users its okay to
do things dangerously, providing bad data to developers, and teaching
developers its okay to do things dangerously, and is not possible for any
site that has already been upgraded -- why don't we look into the root
cause of this problem, and fix that instead?

The problem is that people are trying to update core without contrib. This
will likely result in a site that is not fully or properly upgraded.
Modules like taxonomy menu need to be present during the core update to be
upgraded to backdrop. If not, they will be broken site after upgrade. This
will cause a poor experience for people coming to Backdrop too, as people
may blame backdrop for their own information about update process being 7+
years out of date.

The problem is that the system allows this to be done -- with no kind of
warning whatsoever -- so people would of course think it's a safe thing to
do, when it's really not.

Why don't we add a requirements check for the modules being present, and if
they are not there, prevent updates from being run?

We could handle this in the exact same way as we do for update_free_access,
where a developer would have the ability to bypass this requirement, if
they wanted, by setting a variable In settings.php.

This way not only do we teach people the safe way to upgrade, but if a
developer wants to do things in a different order, they still can, but
they'll at least be aware of the risks first.

**Comment by jenlampton** [comment] 2017-09-17 20:24
Here's a better idea...

Rather than blocking anyone from updating their site unless every contrib module is present (which seems like overkill) what if we simply fixed `hook_update_dependencies()` so it could throw an error only IF there was a contrib module that had a dependancy that wasn't met?

Right now in the docs it says ...
```
If a site has already run the yet_another_module module's database updates before it updates its codebase to pick up the newest mymodule code, then the dependency declared here will be ignored.
```
How about rather than skipping the updates (this is the part that causes broken sites) what if it threw an error to the user telling them which module had which dependency. For example, for taxonomy_menu, it would say something like 'Taxonomy menu module needs to run it's updates before Taxonomy module. Please ensure the both these modules are present at time of update`.

**Comment by docwilmot** [comment] 2017-09-17 20:31
> Why don't we add a requirements check for the modules being present, and if they are not there, prevent updates from being run?

So we check if there are tables in the database which are not defined by a `hook_schema`? If this is a solid check, then that should work. I agree with the overkill comment; a warning step in the updates wizard saying some files are absent would be enough on Backdrop's part, the user can do what he likes thereafter.

> what if it threw an error to the user telling them which module had which dependency

That would not work. If `taxonomy_menu` files were present during the upgrade, `hook_update_dependencies()` would do its job; but if the files are absent, then youve missed the boat. When you do return the files and run updates, its too late, as Taxonomy has already upgraded.

**Comment by jenlampton** [comment] 2017-09-17 20:36
> That would not work. If taxonomy_menu files were present during the upgrade, hook_update_dependencies() would do its job; but if the files are absent, then you've missed the boat. When you do return the files and run updates, its too late, as Taxonomy has already upgraded

Yes, but at least when you did try to run the updates for taxonomy_menu later, it would tell you why you can't update it properly, with a nice little message telling you how to fix the problem. Right now it acts like everything's fine (no errors) when your site is likely broken.

**Comment by docwilmot** [comment] 2017-09-17 21:01
Great, seems a more appropriate approach.
Incidentally, it would be `status = anything` since `hook_update_dependencies()` would be able to do its work even on disabled modules. Any project the installer finds in the system table which isnt found in the file system should trigger a warning. It would be up to the user to check if this module has a `hook_update_dependencies()` implementation or any other condition which would cause problems if the files were absent.

**Comment by jenlampton** [comment] 2017-09-17 21:02
> Incidentally, it would be status = anything

yes, good point!

**Comment by jenlampton** [comment] 2017-09-17 21:23
@klonos Thank you for your recommendations. I've created two issues (as you can see above). I love love LOVE the idea of automatically creating a backup. However, since we won't know exactly what needs to be backed up, I recommend we make a backup of the whole site. And why stop at major version upgrades? We should do this every time we run update.php :) And -- why haven't we been doing this all along?!? Great idea! https://github.com/backdrop/backdrop-issues/issues/2854

Also -- I am against this idea in principle -- but since there are lots of people who seem to be in favor of it, I have created another issue about keeping a backup of some of the old D7 values that contrib may need during update. Since these values should only be needed during an update (and not on the site afterward) the best place for them to be would be in the database and not in config. Let's get some more feedback on that particular idea, here: https://github.com/backdrop/backdrop-issues/issues/2855

**Comment by docwilmot** [comment] 2017-09-27 09:46
Turns out this whole issue is unnecessary. Just realized that on upgrade, backdrop names the new config files by the RID, so a role with `RID = 3` actually gets a config file name `user.role.3` and the `name` key in the config file is actually `name: 3`. So no data loss after all. 

Closing. Sorry for all the noise.

**Closed** 2017-09-27 09:47 UTC
Labels: type - question

**Comment by BWPanda** [comment] 2019-11-11 20:01
Just updated the first post with @docwilmot's final comment to help others, and I've also just discovered that the output of `user_roles()` on a migrated D7 site is, for example:

```php
array(
  'anonymous' => 'Anonymous',
  'authenticated' => 'Authenticated',
  3 => 'Administrator',
);
```

**Comment by klonos** [comment] 2020-07-08 20:45
> ...I have created another issue about keeping a separate copy of some of the old D7 values that contrib may need during update.

FTR: This came up in Zulip, so I've updated https://api.backdropcms.org/change-records/converted-user-roles-to-cmi to include an "Upgrading from Drupal 7" section, with the findings by @BWPanda and @docwilmot 😉
