### ISSUE TITLE
Regression on Windows: Backdrop 1.26.0 release GUI install module Error: File Transfer failed

### ISSUE THREAD

**Issue by izmeez** [backdrop/backdrop-issues#6226] opened 2023-09-16 03:20 UTC
## Description of the bug

After installing upgrade to Backdrop 1.26.0 from 1.25.1 used the GUI interface to install a new module. This failed with Error.

```
Error installing Porter Stemmer. Error installing / updating. Error: File Transfer failed, reason: .../backdrop-demo/modules is outside of the .../backdrop-demo
```

## Steps To Reproduce

To reproduce the behavior:
1. Go to 'admin/modules/install'
2. Search for module to install.
3. Click on 'Add to installation queue'
4. Click on 'Install' in right sidebar
5. Proceed to install.
6. See Report of error.

## Actual behavior

Error.
```
Error installing Metatag. Error installing / updating. Error: File Transfer failed, reason: .../backdrop-demo/modules is outside of the .../backdrop-demo
```

## Expected behavior

Normally, and previously with Backdrop 1.25.1 the installation would proceed without issue.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.26.0
- Web server and its version: XAMPP Apache 2.4.56
- PHP version: 8.1.17
- Database sever (MySQL or MariaDB?) and its version: 10.4.28-MariaDB
- Operating System and its version: Windows 10
- Browser(s) and their versions: Firefox

**Comment by argiepiano** [comment] 2023-09-16 04:57
I'm testing this in my local installation of Backdrop, and cannot reproduce the error. Modules are installing normally in 1.26.0.  Using PHP 8.1.13

**Comment by argiepiano** [comment] 2023-09-16 05:04
Let's try som debugging to see what's going on. Can you enable Devel and add the following lines to `FileTransfer::checkPath()`? 

This is what that method would look like:
```php
  protected final function checkPath($path) {
    $full_jail = $this->chroot . $this->jail;
    $full_path = backdrop_realpath(substr($this->chroot . $path, 0, strlen($full_jail)));
    $full_path = $this->fixRemotePath($full_path, FALSE);
    if ($full_jail !== $full_path) {dpm($full_jail, 'full jail');dpm($full_path, 'full path');
      throw new FileTransferException('@directory is outside of the @jail', NULL, array('@directory' => $path, '@jail' => $this->jail));
    }
  }
```

Then post the results here.

**Comment by quicksketch** [comment] 2023-09-16 05:46
Just a guess here, but it's possible when we scoped the properties of the `FileTransfer` class as `protected`, it made it so that those values could not be read outside of that class ([see these lines of PR 4445](https://github.com/backdrop/backdrop/pull/4445/files#diff-c4acf33f76932beb676bd6f51fb7f39ad4a2e872c6ca31bafbccc37e607e75e2R19-R28)).

But if that were the case it wouldn't matter what version of PHP or the infrastructure you were on, it would probably fail regardless.

**Comment by argiepiano** [comment] 2023-09-16 13:36
My bad. This is being thrown in class `Updater::install()`, not `FileTransfer`.  More later.

**Comment by argiepiano** [comment] 2023-09-16 17:07
@quicksketch you are partially right.  @izmeez and I spent one hour on PM trying different things, until we found it.

- 1.25.2 and 1.26.0 introduced an initialization of `protected $chroot;`
- The problem with initializing this property, is that the magic method `FileTransfer::__get('chroot')` never gets called, since `chroot` already has been initialized with NULL above. 
- This causes `FileTransfer::setChroot()` to never get called
- Because setChroot is not called, the property `FileTransfer::jail` is never "fixed", meaning that **(on Windows servers)** it ends up looking like `X:\platforms\backdrop-demo` instead of looking like `platforms/backdrop-demo`
- This causes the comparison in `FileTransfer::checkPath()` to tail, thus the error

NB: this only happens on Windows environments.

So, the proposed solution is:
1. Run `fixRemotePath` on `__construct()`
2. Initialize  `chroot` ALSO in `__construct()` by calling `$this->setChroot` there instead of in `__get()`
3. Remove all the `__get()` stuff that initializes chroot

Since I don't have a Windows environment to test these fixes, I won't submit a PR. Who has Windows and XAMPP who may check on these? @indigoxela?

**Comment by argiepiano** [comment] 2023-09-16 17:47
I'm looking at the way this class is defined in Drupal 10. So, they never declare `FileTransfer::chroot`. Instead they have a property called  ``FileTransfer::chrootPath`, which gets set in `::__set()`.  Because `::chroot` is never declared (it's still a dynamic property), `__set()` gets call.

But guess what? Their approach will probably throw a deprecation notice in PHP 8.2, since `chroot` is still dynamic.

**Comment by argiepiano** [comment] 2023-09-17 01:26
Thanks @izmeez. PR provided, ready for review and testing.

Rationale: since the declaration of the property `chroot` is at the root of the problem, I removed it. Since this class uses `__set()` it will not show a "dynamic property" deprecation notice in PHP 8.2, as per the document linked in my previous comment.

This is by far the simplest solution. Since `chroot` is not declared, the class will invoke `__set()`, which will in turn run all the necessary processing/cleaning of `FileTransfer::jail`.

**Comment by argiepiano** [comment] 2023-09-17 02:31
@izmeez, the previous version of the PR triggered automatic errors in PHP 8.2. 

I have expanded the approach using Drupal 10's `FileTransfer` as a model. In that system, `FileTransfer` uses a new, declared property ,`chrootPath`, that acts as a proxy of `chroot`, which is not declared. This hybrid approach assures that `__get()` gets called whenever the methods try to access the value of `$this->chroot` in `FileTransfer::checkPath()`, which invokes the appropriate methods to clean up and fix the `jail` property. 

Can you please test this version on Windows?

**Comment by argiepiano** [comment] 2023-09-17 02:45
Oh boy. The changes created issues for several tests related to Update UI and installation tests. Obviously more work needed. I can't do more work tonight. If anyone wants to take over, be my guest.

**Comment by argiepiano** [comment] 2023-09-17 03:40
Some progress. The PHP 8.2 and 7.4 errors are gone with the latest PR (except for our "old friend" random failing testUninstallLocale). However, the changes are creating problems for testProjectBrowserInstallPage in php 5.6, most likely because the PR is using approaches not allowed in 5.6. Will check tomorrow.

**Comment by argiepiano** [comment] 2023-09-17 04:04
OK, all tests are passing now. The issue with 5.6 was some disallowed type hinting.  PR is now ready for testing and review.

**Comment by indigoxela** [comment] 2023-09-17 06:22
This is weird. I can't reproduce the problem.

Which step am I missing? What I did:

- Upgrade to 1.26, ran db update
- Go to /admin/modules/install, picked a random one
- Installed and enabled without any problems

Backdrop: 1.26.0
PHP: 8.1.23
Webserver: Apache
OS: Linux

**Comment by quicksketch** [comment] 2023-09-17 09:38
@indigoxela This problem exists on Windows only as far as we know, something to do with the conversion from `C:\` (or similar) paths to Unix-style `/` paths.

**Comment by argiepiano** [comment] 2023-09-17 13:55
Right, only Windows installations. According to Telemetry, this could be as high as 3% of all Backdrop installations. Those installs won't be able to download or update modules until this is fixed.

**Comment by muranod** [comment] 2023-09-21 19:25
Worked perfectly - just copied over the raw files. Appreciate the speedy fix! - Dan

**Comment by quicksketch** [comment] 2023-09-22 02:56
Thanks for testing this @muranod and @izmeez. I'd love to get this in shortly and we can include it in a 1.26.1 release.

I reviewed the PR and it looks great! I'm generally not a fan of the magic methods `__get()`, `__set()`, etc. as I think using them can make logic very difficult to follow when they're getting called at unexpected times (hence the "magic"). But we were already using `__get()` and this only adds the matching `__set()`, `__isset()` and `__unset()`. Seems like a good solution to a difficult problem of supporting a very broad range of PHP versions.

The PR also includes a wonderful collection of documentation updates and clarifications. Great job @argiepiano!

There are a few very minor complaints in the PR. @argiepiano Could you take a look?

**Comment by argiepiano** [comment] 2023-09-22 03:20
Thanks @quicksketch. Requested changes have been committed.

**Closed** 2023-09-22 04:07 UTC
Labels: status - fixed

**Comment by quicksketch** [comment] 2023-09-22 04:13
Excellent, thank you so much @argiepiano for getting to the root of this difficult problem! Thanks @izmeez for your report and working back and forth to determine what environment caused the differences.

https://github.com/backdrop/backdrop/commit/1982f486c2d40c570851059a6f63c14dabf41011 by @argiepiano, @izmeez, @quicksketch, @indigoxela, and @muranod.

Thanks and welcome @muranod to the Backdrop community! I added you to our triage group so that you can now add issue labels and edit issue summaries.

**Comment by muranod** [comment] 2023-10-10 13:00
Thanks, @quicksketch  Thanks for the updates and fixes.  Sorry I've been so distracted on the design phase of my local site and haven't checked back in a while. I'm not a developer, but have been using drupal since v7 came out. Now converting over to Backdrop and YAY - no more Composer and all that other stuff.  - Dan
