### ISSUE TITLE
[UX][D7] Add a 'User account: compare' visibility rule

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4029] opened 2019-09-11 23:36 UTC
**Description of the need**
In Drupal 7 / Panels you could choose to show or hide a content pane based on whether a `User context` was equal to the `logged in User context`. This panels access plugin allowed you to create a 'my own dashboard' separately from `the global dashboard`, or to show people their `own` blocks, without showing that block to anybody else. 

Now that we have a dashboard in core, I suspect more and more people are going to notie that this feature is missing from Backdrop.

**Proposed solution**
We should copy the User: compare visibility rule and turn it into a Visibility condition for the Backdrop block/layout system.

**Steps To Test**

To reproduce the behavior:
1. Apply the patch from https://github.com/backdrop/backdrop-issues/issues/4029 (or test in the sandbox)
2. Create a layout at the path `user/%` -- confirm `User` context is automatically added.
3. Scenario 1: Place a block I can only see on my own page
  a) Place a custom block (text: `my own page`)
  b) Add a visibility condition `User: Compare`
  c) Select **First User** Logged in user account
  d) Select **Second user** User account from path (position 2)
  e) Select **Grant access if the two are** The same user account
  f) Save
4. Scenario 2: Place a block I can only see on someone else's page
  a) Place a custom block (text: `someone else's page`)
  b) Add a visibility condition `User: Compare`
  c) Select **First User** Logged in user account
  d) Select **Second user** User account from path (position 2)
  e) Select **Grant access if the two are** Different user accounts
  f) Save
5. Save the layout.
6. Visit your own user profile -- see your own block
7. Visit someone else's user profile -- see the other block

---

**Please do not merge this until https://github.com/backdrop/backdrop-issues/issues/4594 has been merged**

---
PR by @jenlampton: https://github.com/backdrop/backdrop/pull/2869

**Comment by jenlampton** [comment] 2019-09-12 01:00
I took a stab at [a PR](https://github.com/backdrop/backdrop/pull/2869) but I'm having some trouble getting the contexts in the `summary()` method. 

I checked both `LayoutAccess` class and `LayoutHandler` class but couldn't find where contexts were loaded. I know they work, because I have access to them in the `checkAccess()` method.

One thing I noticed is that in the docs for the `summary()` method, a parameter of `$contexts` is defined, but never passed in. I tried adding `$contexts` as a perameter, in the base class, my class, and both, and nothing I did got contexts working in summaries. 

help appreciated :)

**Comment by klonos** [comment] 2019-09-12 01:13
> This feature us missing from Backdrop.

Sorry, how is this different to adding a visibility rule based on UID?

**Comment by jenlampton** [comment] 2019-09-12 01:14
This compares 2 different user's IDs, rather than comparing a single user ID to a fixed number.

**Comment by stpaultim** [comment] 2020-03-13 06:08
I believe that this user is looking for this functionality:
https://forum.backdropcms.org/forum/block-visibility

**Comment by stpaultim** [comment] 2020-03-13 06:12
The sandbox appears to be broken. I'm getting an install screen.

**Comment by jenlampton** [comment] 2020-04-28 01:03
@klonos I couldn't find the `dpm()` so I expect I must have removed it previously. @stpaultim I have rebased and updated the pr, seeing if that fixes the sandbox.

**Comment by jenlampton** [comment] 2020-04-28 01:09
The Sandbox is back in action :)
https://github.com/backdrop/backdrop/pull/2869#issuecomment-620315449

**Comment by docwilmot** [comment] 2020-04-28 16:35
I must say though, I think this is not likely popular functionality and would do well in contrib for the <80% who'd want it.

**Comment by klonos** [comment] 2020-04-28 18:15
I find it useful in core 😅 

I have left a couple of comments/questions in the PR, but the main issue I see is that if the layout context is set to anything but `user/%`, you get this:

![Screen Shot 2020-04-28 at 9 12 55 pm](https://user-images.githubusercontent.com/2423362/80522316-0f6aa080-8995-11ea-953c-a0500eabb611.png)

...as opposed to also having the two user select elements:

![Screen Shot 2020-04-28 at 9 10 48 pm](https://user-images.githubusercontent.com/2423362/80522465-49d43d80-8995-11ea-94db-189483e782fc.png)

**Comment by klonos** [comment] 2020-04-28 18:19
...also curious why the dropdown labels are "User" and "Second user" while in code there's:

```php
    'required contexts labels' => array(
      'user1' => t('First user'),
      'user2' => t('Second user'),
    ),
```

**Comment by jenlampton** [comment] 2020-09-02 23:00
> I think this is not likely popular functionality and would do well in contrib for the <80% who'd want it.

It's a fairly common use-case to make sure that people can only see their own content on their own profile page. This was an access plugin in ctools that we overlooked. It's not so much a new feature request as a correction of a previous oversight :)

> also curious why the dropdown labels in the PR sandbox are "User" and "Second user"

This should be fixed in the latest PR.

> the main issue I see is that if the layout context is set to anything but user/%, you get this:

This looks like a problem in layouts. Visibility conditions seem to be available even when required contexts are missing. See https://github.com/backdrop/backdrop-issues/issues/4594 for that bug. Will try to fix there.

**Comment by klonos** [comment] 2020-11-25 13:53
The (Zen) PR sandbox is broken @jenlampton. Care to close/reopen please, so we can get a pair of fresh sandboxes?

**Comment by jenlampton** [comment] 2020-12-24 21:39
I rebased and pushed the branch, tugboat sandbox is rebuilding now.

**Comment by klonos** [comment] 2020-12-25 18:43
> I rebased and pushed the branch, tugboat sandbox is rebuilding now.

Thanks @jenlampton 🙏 

>> the main issue I see is that if the layout context is set to anything but user/%, you get this:
>
>This looks like a problem in layouts. Visibility conditions seem to be available even when required contexts are missing. See #4594 for that bug. Will try to fix there.

Fair enough 👍 ...I'm happy so long as we have a follow-up to address this in the future.

I've left a couple of suggestions in the PR, but more importantly, I'm noticing many inconsistencies between using "user" or "user account" (for both user-facing text, as well as variables/functions etc.). We should pick one and stick with it.

**Comment by klonos** [comment] 2020-12-25 18:45
> So, the access check here is working, but the Admin UI is currently busted. Help appreciated :)

Is that still an issue @jenlampton? ...and is the "help wanted" label still valid for this issue?

**Comment by jenlampton** [comment] 2021-05-26 00:48
> Is that still an issue @jenlampton? ...and is the "help wanted" label still valid for this issue?

I have rebased the PR, added a little more language cleanup (`User` becomes `User account`), and tested again. I don't think any issues remain other than the one we'll tackle in  #4594

**Comment by stpaultim** [comment] 2021-08-22 09:09
I just tested this PR and I think that the use case described in this issue makes sense and could be fairly common. However, the UI is complicated and bit confusing for me. It seems to suggest that there are more options than there seem to be. Maybe, I'm missing something. 

It says that you are able to compare two users. This is stated in a generic way as if to imply that you can compare ANY two users. But, the only users that seem to be available are:

1) Currently logged in user
2) User in path

It seems like I'm asked to complete three fields to make a single binary choice. Either:

A) Only show this block to the user in the profile path.
    OR
B) Show this user to everyone except the user in the profile path.

Can't we reduce the options to a single choice?

```
Make this block visible if:
* Current user is same as user in path
* Current user is different from user in path
```
Visibility Condition = `User: Current` or `User: Compare with current`

Maybe I'm missing some deeper functionality?

**Comment by jenlampton** [comment] 2021-08-22 19:41
> Maybe I'm missing some deeper functionality or options?

In short, yes, there's more functionality than you can see in the user-interface.

What you are seeing in your testing are the two user contexts that are made available by core alone. But in contrib, any number of additional user contexts could be made available, and this feature supports comparing any two.

I think it is possible to add an "author from node" context by using the layout relationships in core...  and in that case you could get a 3rd user to compare.

> Also, I assumed that this condition is ONLY supposed to be available in the user context. But [...]

This is a different core bug and happens for all contexts (required contexts are not actually "required") I think that issue linked from above in this issue.

**Comment by stpaultim** [comment] 2021-08-22 20:07
> In short, yes, there's more functionality than you can see in the user-interface without additional configuration or contributed modules (like friendlist or user_relationships)

I would probably not object to putting this into core. But, I'm having a hard time imagining a UI that most users are doing to understand. However, this has been a problem for me with most of the layout + context issues. 

I can see where this might be considered good for core as a building block for contrib modules. But, it's difficult for me to imaging this right now. For me to provide any additional useful advice, I think I would need to be able to see more than the one use case in action. I don't know if that would mean adding something more to the core PR or creating a simple custom/contrib module that helps demonstrate how to use this?

**Comment by jenlampton** [comment] 2021-08-23 21:42
> I can see where this might be considered good for core as a building block for contrib modules ...

That's not quite the reasoning. This was considered a feature that's "good for core" because the one use-case you can see is an 80% use-case. It just also happens to support an infinite number of other 1% use-cases :)

That said, I'm sure the interface could use some cleanup. I'll see if I can use the new "Author from node" layout relationship to create another 80% use-case that you can test on core alone. Maybe that will help us figure out how make everything more intuitive?

**Comment by stpaultim** [comment] 2021-11-05 02:36
@jenlampton - Chatting about this today with @hosef and @klonos and @klonos suggested just hiding the complex part in an advanced dropdown. Something like the very rough screenshot below. 

Could we have the simple version visible and then hide the part in the red underneath an "Advanced" drowndown?

Maybe @klonos can provide a better mock-up.

![current-user](https://user-images.githubusercontent.com/3144571/140448753-83064b1b-c067-4786-a8b3-0132652042a8.png)

**Comment by klonos** [comment] 2021-11-05 10:33
> I have rebased the PR, added a little more language cleanup (`User` becomes `User account`)

I don't see that fixed @jenlampton:
![image](https://user-images.githubusercontent.com/2423362/140497395-232937f0-4170-4f67-90c8-17a72b1beaaf.png)

Perhaps forgot to push your changes?

**Comment by klonos** [comment] 2021-11-05 11:05
Re what @stpaultim said above, I was thinking either provide 3 options in the form like so:
<img width=50% src="https://user-images.githubusercontent.com/2423362/140500264-469d49e2-0610-4b58-9b5e-c5841ae433bd.png">

So we provide the 2 most common conditions as "presets", but also provide a 3rd option, which reveals more controls in the form, for advanced/complex scenarios.

The alternative could be to provide 2 separate visibility conditions:
![image](https://user-images.githubusercontent.com/2423362/140500877-d12a0ee7-44f6-4418-b1dc-b20571feef49.png)

- The "simple" option would only have the 2 commonly-used options.
- The advanced option would have the form as is now (with "fist user account" / "second user account")

Whichever of the two alternatives is easier to implement really.

**Comment by jenlampton** [comment] 2022-06-08 03:03
I rebased the PR since it has been a while since I've worked on it, but it looks like all the "forgotten" changes have been made.  I suspect that has something to do with you @klonos, so thank you :)

Re the UI suggestions: I don't think we can change this form that drastically. We still need to know which user account should be used for user1 and which to use for user2 (even though the person filling out the form may not care) and those questions aren't optional (they aren't specifically added by this PR - if we have required contexts, they are added automatically).

Rather than throwing them out entirely, can we set better default values, maybe? What if we assumed the first user was always the logged in user, and then hid that question. Then the second question could be formed around comparing that one to the logged in user, something like this...

<img width="603" alt="Screen Shot 2022-06-07 at 8 01 52 PM" src="https://user-images.githubusercontent.com/397895/172522467-4c89400c-e319-46cb-86b8-07048f3f2726.png">

In this case, we can also assume that "the logged-in user account" will never be a valid value for `user2`, so we can remove it from the list of options. This would mean, most of the time, the only/default value would already be selected leaving nothing up to chance. 

On the overview page, the text could look something like this:

<img width="1166" alt="Screen Shot 2022-06-07 at 7 57 54 PM" src="https://user-images.githubusercontent.com/397895/172522016-7c24da61-baa1-46eb-b267-979e2ee9ab74.png">

**Comment by jenlampton** [comment] 2023-04-06 21:58
Adding help wanted label since this still needs testing and code review :)

**Comment by klonos** [comment] 2023-04-07 00:08
> What if we assumed the first user was always the logged in user, and then hid that question. Then the second question could be formed around comparing that one to the logged in user, something like this...

Yeah, I like that 👍🏼

**Comment by klonos** [comment] 2023-04-07 00:11
...the PR linked to this issue has php5 failures @jenlampton and the PR sandbox and CI logs have expired. Can you please rebase and let us know when this is ready for review/testing? Thanks 🙏🏼

**Comment by stpaultim** [comment] 2023-04-14 05:29
I started creating a layout with a user compare visibility rule. It says "Display this block if the above user account is" even though it's a condition for a layout, not a block.

![image](https://user-images.githubusercontent.com/3144571/231949344-e6113dca-34bf-4821-a989-c09f6939b285.png)

**Comment by quicksketch** [comment] 2023-04-28 05:12
I merged the prerequisite issue at https://github.com/backdrop/backdrop-issues/issues/4594. It'd be great to see this in 1.25.0.

**Comment by quicksketch** [comment] 2023-05-01 01:12
A note about the radio options shown in the screenshot above: I think we should avoid this kind of sentence-splitting across labels because it may cause difficulties in translation. How about:

```
Visibility:
(*) Show if user accounts match
( ) Hide if user accounts match
```

Perhaps it's because I'm more technical, but I also don't see a problem with including the select list options for both user accounts, but perhaps remove "Currently logged in user" from the second list of options so it defaults to the most common configuration.

**Comment by stpaultim** [comment] 2023-05-01 03:21
@jenlampton - It seems the text I noted above applies to both layouts and blocks. Rather than customizing the text for each context, I created a PR against your PR that removes the words "this block." 

This changes the text to "Display if the above user acount is" - which I think works fine in both contexts.

**Comment by quicksketch** [comment] 2023-05-02 05:04
I made an alternative PR with a stab at the UI in https://github.com/backdrop/backdrop/pull/4426. Fundamentally it's still the same.

![image](https://user-images.githubusercontent.com/100206/235583159-9a0a4e31-0feb-41da-925b-7a41d69b2505.png)

- Both user context fields are shown with labels First User Account and Second User Account
- But duplicate options are removed from each field, so in the most common use case, there is only one option in each field.
- The wording on the equality check is changed.

Regardless of the UI, this probably won't make it in 1.25.0 since we don't yet have test coverage.

**Comment by stpaultim** [comment] 2023-05-11 00:48
@quicksketch Trying to test your PR. I don't think it's working in the sandbox. 

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/510f68c8-1661-47d9-ac9b-cc71fcb9630a)

I did the following. 

1) Created a layout with user/% context
2) Tried to create a custom block using visibility rule "user compare" and I'm not seeing the necessary options. 

Using PR 4426 sandbox

**Comment by quicksketch** [comment] 2023-09-04 20:41
I added test coverage to https://github.com/backdrop/backdrop/pull/4426 and rebuilt the sandbox. In my local testing, I wasn't seeing the problem @stpaultim described above. This should be ready for testing again.

**Comment by jenlampton** [comment] 2023-09-18 20:20
I still think this new interface is more confusing than the previous one because of both selects. What if we just fixed the language for the "Comparison mode" so that it more like the previous example?

Nate's suggestion:
<img width="598" alt="Screenshot 2023-09-18 at 1 15 54 PM" src="https://github.com/backdrop/backdrop-issues/assets/397895/efec6e72-d817-4e6c-ac29-6fee94d3cbcc">

New suggestion:
<img width="599" alt="Screenshot 2023-09-18 at 1 19 23 PM" src="https://github.com/backdrop/backdrop-issues/assets/397895/4f3dfce8-ac6f-4058-b2c8-7786f99510a2">

**Comment by quicksketch** [comment] 2023-11-24 21:15
I like the suggestion @jenlampton made above. That seems like a good way to avoid the translation issues.

**Comment by quicksketch** [comment] 2023-11-25 00:53
I closed my PR and pushed a clean-up commit to @jenlampton's PR at https://github.com/backdrop/backdrop/pull/4426. This looks ready for review again.

**Comment by argiepiano** [comment] 2023-11-25 01:35
I found a way to create a fatal error with this. I'll post details in a minute.

**Comment by argiepiano** [comment] 2023-11-25 01:40
Hi @quicksketch. I've tested  as follows and found an error: `TypeError: Unsupported operand types: string + int in UserCompareLayoutAccess->summary() (line 30 of /var/lib/tugboat/core/modules/layout/plugins/access/user_compare_layout_access.inc).` This resulted in a Fatal error (BTW, I did this in the sandbox, and the layout I created can't be accessed  anymore after this fatal)


 This is what I did. I'm aware there are other ways to create this condition, but I wanted to see if the new access plugin would also work with a User specified in an added context, rather than the one provided by the path. This is all in the sandbox, so you can log in and check this there:

1. Created user `someone`
2. Overrid `user/%`
3. Manually added "User account" as context, and added user ID 2 (which I had created previously, username: someone)
4. Added a Custom block with the following Visibility:
  a. User account: compare
  b. "User account to compare to the logged-in user account:" I chose User account: 2 (someone). NOTE: I did not pick the user in position 2
  c. "Comparison: Display if this account is the logged-in user account" 
  d. Click "Add". The modal stays there and does not close
5. Checked "Recent log messages" and I see this

<img width="1235" alt="Screen Shot 2023-11-24 at 6 39 26 PM" src="https://github.com/backdrop/backdrop-issues/assets/9938978/6d12c057-e9ea-4881-b6b4-2ff00197f53a">

I manually closed the modal and saved the Layout. Got the fatal:

<img width="880" alt="Screen Shot 2023-11-24 at 6 40 12 PM" src="https://github.com/backdrop/backdrop-issues/assets/9938978/020e78d5-60f8-4586-97c2-c900a3d6ecf2">

**Comment by argiepiano** [comment] 2023-11-25 03:31
I think the issue is that this new access plugin (specifically, the summary method) assumes that one will always pick "User account from path", but of course, there are other types of user context that need to be taken into account, since they are available in the dropdown under "User account to compare to the logged-in user account"

**Comment by stpaultim** [comment] 2023-11-27 06:07
I think I'm good with the current (most recent) approach, assuming we can solve the problem identified by @argiepiano.

**Comment by stpaultim** [comment] 2023-12-01 05:23
This was discussed at todays dev meeting. @quicksketch believes that the issue is pretty easy to fix.

**Comment by jenlampton** [comment] 2023-12-14 22:02
I have revered the problematic commit and rebased off the latest 1.x. Sandbox is rebuilding now.

**Comment by argiepiano** [comment] 2023-12-15 15:24
Thanks, @jenlampton. I've tested and WFM. I left a comment in the PR.

**Comment by quicksketch** [comment] 2023-12-15 22:19
Thanks @argiepiano. I re-added some non-breaking suggestions again as well, such as fixes to `t()` calls and reverting a few accidental function renames (`assertNULL()` should remain `assertNull()`). This needs another review and manual testing again.

**Comment by argiepiano** [comment] 2023-12-15 22:54
Tested and reviewed. LGTM.

**Closed** 2023-12-15 23:12 UTC
Labels: type - feature request, status - has pull request, pr - ready to be committed, pr - works for me

**Comment by quicksketch** [comment] 2023-12-15 23:13
Fantastic. I'm going to merge this before we find anything else. :sweat_smile: 

Merged https://github.com/backdrop/backdrop/pull/2869 into 1.x for 1.27.0. Yay, what a long journey for this small feature. Thanks @jenlampton, @docwilmot, @stpaultim, @argiepiano, @klonos, and @olafgrabienski!

**Comment by stpaultim** [comment] 2023-12-15 23:34
It took a while, but we got it!

**Comment by jenlampton** [comment] 2024-01-16 02:38
The FIRST site I updated to 1.27.0 is one that needed this patch! (coincidentally!)
