### ISSUE TITLE
Invalid option 2 in filters element

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#6228] opened 2023-09-17 05:53 UTC
## Description of the bug

Impossible to create new filter groups in Views.

## Steps To Reproduce

To reproduce the behavior:
1. Go to any views, for example `/admin/structure/views/view/node_admin_content/configure/page`
2. In _FILTER CRITERIA_ section drop down and select _AND/OR, REARRANGE_ option.

![Screenshot 2023-09-17 at 12 48 16 AM](https://github.com/backdrop/backdrop-issues/assets/56604405/cdfec322-4eec-4e86-b88a-ee5f5a759858)

4. Click on _+ Create new filter group_ and try to create any second filter group with any options.
5. Apply and then Save the View.
6. Nothing happens as the new filter group doesn't work.
7. Now go to `Recent log messages` page on `admin/reports/dblog` and see the error:

![Screenshot 2023-09-17 at 12 52 54 AM](https://github.com/backdrop/backdrop-issues/assets/56604405/ae9e8009-084d-4993-b5f6-bf76a6a85148)

**Comment by argiepiano** [comment] 2023-09-17 14:03
I'm no able to reproduce. See screen capture. I'm using Backdrop 1.26.0 and Chrome. It may help to know what you are using.

![screencapture5](https://github.com/backdrop/backdrop-issues/assets/9938978/81ea6046-07b3-4578-9894-959933fe1278)

**Comment by alanmels** [comment] 2023-09-17 20:10
@argiepiano, thanks for responding on this. I've made sure to replicate this on a completely fresh setup. Could it be the difference in PHP version? What's yours?
```

alan@myho-web:/var/www/html/docroot$ php -v
PHP 8.1.22 (cli) (built: Aug 29 2023 10:48:28) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.22, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.22, Copyright (c), by Zend Technologies
alan@myho-web:/var/www/html/docroot$ 
```

**Comment by klonos** [comment] 2023-11-12 10:41
Sorry for taking this long to reply here.

I was able to replicate this on a demo sandbox (which uses php 8.1.24). These were the steps:
1. Edit `admin/structure/views/view/file_admin`
2. Added 2 new filter criteria: `File: Mime type =` and `File: Path =` quickly accepting all default options for them, which resulted in this:
   ![image](https://github.com/backdrop/backdrop-issues/assets/2423362/ec8e2035-860c-413d-9b05-d5bb1bc27b91)
3. I clicked on "+ Create new filter group", and I dragged the 2 new filter criteria in that group (what you select as operator does not make any difference - I have tried many variations). That is what I have before I click on the "Apply (all displays)" button: 
   ![image](https://github.com/backdrop/backdrop-issues/assets/2423362/f412483c-02f0-4d20-9812-20e2d328a01c)
4. Saved the changes, and then opened the "Rearrange filter criteria" dialog again. Everything was reverted back to a single group.
   ![image](https://github.com/backdrop/backdrop-issues/assets/2423362/649a6477-6633-450e-8cf1-a1b09ae80ca4)
5. No matter how many times I tried, it always revers to the single group.

Looking at the log, I confirmed that the error was logged as many times as I attempted to create and save an additional group:
![image](https://github.com/backdrop/backdrop-issues/assets/2423362/0048b75c-842f-46f3-a124-66a54bcf6bfc)

**Comment by argiepiano** [comment] 2023-11-12 14:07
So glad to see you replicated this! I tried so many times. I'll see if I can spot what's going on.

**Comment by kiamlaluno** [comment] 2023-11-12 14:45
I was able to reproduce the issue too, even for a different view. I added two filter criteria and then rearranged them, like @klonos did.

**Comment by kiamlaluno** [comment] 2023-11-12 14:51
I will try also on PHP 7.3, just to be sure it is not an issue with PHP 8.

**Comment by kiamlaluno** [comment] 2023-11-12 15:05
Apparently, it happens only with PHP 8. I tried with PHP 7.3, and I was able to create and keep two filter groups.

![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/9971da7a-017f-4998-8c3d-f0072ab57cae)

In my case, I used Backdrop 1.26.1.

**Comment by argiepiano** [comment] 2023-11-15 00:08
I have found the [corresponding issue](https://www.drupal.org/project/views/issues/3348800) in D7. [Comment 13](https://www.drupal.org/project/views/issues/3348800#comment-15217878) explains what's happening. The form cache is erroneously cleared because of the way comparisons with 0 work in PHP 8.1 ('foo' != 0  is TRUE in 8.1, is FALSE in 7.4, meaning that the form cache is cleared and the groups that have been cached are lost).

The solution in D7 is to get rid completely of the 3 lines of code that start in [line 2932](https://github.com/backdrop/backdrop/blob/83b7bbac314a302e858cff482283073f73bcda1c/core/modules/views_ui/views_ui.admin.inc#L2932). Although this may seem a bit extreme, it was tested and merged in D7, so I'll submit a PR that does the same thing here.

**Comment by argiepiano** [comment] 2023-11-15 00:15
PR https://github.com/backdrop/backdrop/pull/4568 ready for testing and review

BTW; Tugboat did work for this PR.

**Comment by argiepiano** [comment] 2023-11-15 23:40
@alanmels, would you be able to test this fix?

**Comment by alanmels** [comment] 2023-11-15 23:51
> @alanmels, would you be able to test this fix?

Yay, works like a charm! IMHO RTBC!

**Comment by argiepiano** [comment] 2023-11-16 00:04
Great! Can you update the labels?

**Comment by quicksketch** [comment] 2023-11-24 23:02
Thanks @argiepiano, @alanmels, @kiamlaluno, and @klonos! I merged https://github.com/backdrop/backdrop/pull/4568 into 1.x and 1.26.x.

**Closed** 2023-11-24 23:01 UTC
Labels: status - has pull request, status - fixed
