### ISSUE TITLE
[UX] Rename the user roles to be more intuitive & inviting

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1581] opened 2016-01-28 20:59 UTC
Here's what we have now:

```
Anonymous
Authenticated
Administrator
```

Suggestions?

Anonymous => Visitor
Authenticated =>  ??
Administrator => Developer

This is a spin-off from https://github.com/backdrop/backdrop-issues/issues/1285

**Comment by docwilmot** [comment] 2016-01-28 22:07
Guest
Registered
Administrator

**Comment by mikemccaffrey** [comment] 2016-01-28 23:11
This might be one of those cases where the current implementation is not ideal, but changing things is not worth the cost of breaking with drupal conventions, especially since we would not only be changing a label, but also the underlying machine names of roles that are already present on existing backdrop sites.

Perhaps kick this to 2.x, when we can be more bold with changing things?

**Comment by klonos** [comment] 2016-01-29 02:56
>Guest
>Registered
>Administrator

:+1: 

> Perhaps kick this to 2.x, when we can be more bold with changing things?

:+1:

**Comment by jenlampton** [comment] 2016-08-20 04:09
>Guest
>Registered
>Administrator

👍 

> Perhaps kick this to 2.x, when we can be more bold with changing things?

Iunno, user roles are the kind of thing that would be easy to change for new sites even if there was no upgrade path for old ones. Does the user roles/permissions config file have machine names or ID/UIDs? Maybe it's still possible in 1.x!

**Comment by BWPanda** [comment] 2019-05-15 19:46
Even though this issue is older, I'm going to mark is as a duplicate of https://github.com/backdrop/backdrop-issues/issues/3509 since that one has more recent discussion and links to similar Drupal issues/discussions.

**Closed by BWPanda** 2019-05-15 19:46 UTC
Labels: status - duplicate
