### ISSUE TITLE
[UX] Allow menus to be reordered

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2664] opened 2017-05-01 18:20 UTC
I often want my menus to appear in a specific order on admin/structure/menu, usually with the Main Menu on the top, and Administration (Management) on the bottom. 

<img width="1206" alt="screen shot 2017-05-01 at 11 19 54 am" src="https://cloud.githubusercontent.com/assets/397895/25589104/2327d5ae-2e60-11e7-84ae-99531d3ad0b4.png">

It seems that since our menu info is saved in config now it might be easy to add a `weight` to each one, and update the UI to allow the menu order to be drag-and-dropped as desired.

**Comment by BWPanda** [comment] 2018-08-23 12:19
Will mark this as a duplicate of https://github.com/backdrop/backdrop-issues/issues/3003 (even though this issue's older, there's more discussion in the other queue).

**Closed by BWPanda** 2018-08-23 12:19 UTC
Labels: type - feature request

**Comment by jenlampton** [comment] 2018-08-23 17:51
well, at least I agree with myself :) Someday I'll figure out how to get the GitHub search to work for me!

**Comment by klonos** [comment] 2018-10-21 06:18
@jenlampton: https://github.com/sindresorhus/refined-github works beautifully for me 😉:

![screen shot 2018-10-21 at 5 17 16 pm](https://user-images.githubusercontent.com/2423362/47263838-4caad280-d555-11e8-8ba6-673f69d34610.png)
