### ISSUE TITLE
Home page layout storage state "Overridden" on install

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2251] opened 2016-09-30 06:30 UTC
When you install a new backdrop site, the home page layout think's it's overridden instead of default.

The config file in the standard profile has the storage state as 4, or `LAYOUT_STORAGE_DEFAULT`, but for some reason when this file is copied to active, it changes to 2 or `LAYOUT_STORAGE_OVERRIDE` even if the files are identical. What could cause this?

**Comment by quicksketch** [comment] 2016-10-06 22:23
This is a side-effect of #2165, where we set the hero block text to `"Welcome to @site_name!"`. Because the site name in the hero block is a customization of the homepage layout, it's no longer in the "default" state. If you were to revert the layout, you'd actually get the string `"Welcome to Backdrop CMS!"`.

So while a bit unexpected, overridden is indeed the right state. We could "force" it to be in the default state by loading the config and manually modifying the storage property, but that seems pretty hacky. The layout is currently modified in `standard_form_install_configure_submit()` in `standard.profile`, if we decide to do anything about this issue.

**Comment by quicksketch** [comment] 2016-10-06 22:25
I re-categorized this as a question, as technically it is correct. We can label it as a UX bug however, if we think it is something that needs to be changed.

**Comment by jenlampton** [comment] 2016-10-06 23:56
It's definitely weird from a UX perspective. Let's leave the "needs feedback" label and see if it strikes anyone else as odd enough to merritt change.

**Comment by BWPanda** [comment] 2020-11-17 06:23
Doesn't look like anyone else thinks this needs changing. Closing as 'works as designed'.

**Closed by BWPanda** 2020-11-17 06:23 UTC
Labels: status - works as designed
