### ISSUE TITLE
Don't show image minimum dimension help text if min restriction isn't set

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4221] opened 2019-11-21 14:20 UTC
**Description of the bug**
In image field the help text for minimum dimension restriction shows even if there isn't a limit set.

**Steps To Reproduce**

1. Set a dimension limit for "max" but none for "min" on a node image field
2. Open a node form of that type

**Actual behavior**
The help text for minimum dimension shows, without number of course.

![screenshot-image-field-help](https://user-images.githubusercontent.com/842066/69346027-6647ad80-0c72-11ea-9a9c-573abea73089.png)

**Expected behavior**
If there's no limit set, the help text shouldn't appear.

**Additional information**

- Backdrop CMS version: latest dev

**Comment by indigoxela** [comment] 2019-11-21 14:33
Here's a PR: https://github.com/backdrop/backdrop/pull/2998

Please test and review.

**Comment by olafgrabienski** [comment] 2019-11-25 21:56
Hey @indigoxela - nice catch, I can confirm the issue! (For curiosity: do you know if the issue exists also in D7?)

I've had a look at the sandbox site of the PR, and it works for me.

**Comment by indigoxela** [comment] 2019-11-26 07:39
@olafgrabienski regarding D7: it does this validation slightly different in file.field.inc, so it's not affected. But the help text of D7 is misleading in some cases, so to my opinion the way Backdrop does it (max and min independently from each other) is better anyway - apart from this small bug.

**Comment by klonos** [comment] 2019-11-29 10:16
Not sure if we want to address this here, but there is no validation for when min > max. So you end up with this:

<img width="394" alt="Screen Shot 2019-11-29 at 9 16 02 pm" src="https://user-images.githubusercontent.com/2423362/69861930-80763100-12ed-11ea-813c-f39916cb9f6b.png">

**Comment by klonos** [comment] 2019-11-29 10:18
...also, is it only me, or does it feel more natural to have the "larger than" message come after the "at least" one?

**Comment by indigoxela** [comment] 2019-11-29 10:32
@klonos That's a good catch. The check `max < min` seems to be missing for the field widget settings form.

That's actually not a job for function theme_file_upload_help but rather for file_field_instance_settings_form.
Mind to file a bug report regarding settings form validation?

**Comment by klonos** [comment] 2019-12-01 11:57
> Mind to file a bug report regarding settings form validation?

Done: #4227

**Comment by klonos** [comment] 2019-12-01 11:59
...what about this though?:

> ...also, is it only me, or does it feel more natural to have the "larger than" message come after the "at least" one?

**Comment by indigoxela** [comment] 2019-12-01 13:17
> does it feel more natural to have the "larger than" message come after the "at least" one

Never thought about that, but now as you brought it up - somewhat yes. It _does_ feel a little more natural to have it the other way round (min help text, then max help text).

**Comment by indigoxela** [comment] 2019-12-02 14:21
Based on @klonos' suggestion I've switched the help texts to let the min help appear before the max help, which seems more natural.

**Comment by BWPanda** [comment] 2019-12-05 04:24
The PR removes the broken `min != max` conditions, but I think they should be fixed rather than removed. E.g. add a condition if `min == max` that says images must be exactly x wide and x high...

**Comment by indigoxela** [comment] 2019-12-05 07:16
> The PR removes the broken min != max conditions

Yes, that's by intention. While the check makes sense in D7, it doesn't in Backdrop.
If you compare the D7 code at https://git.drupalcode.org/project/drupal/blob/7.x/modules/file/file.field.inc#L940
you'll see that D7 does that kind of check to put out text like:

- Images must be exactly...
- Images must be between...

Which is misleading.
Backdrop handles min and max independently from each other, which puts out better text.
Bigger images are downscaled regardless of a min value - also in D7 btw.

**Comment by BWPanda** [comment] 2019-12-05 07:26
Ok, I kind of see what you mean.

![image](https://user-images.githubusercontent.com/2385329/70213030-1e7c5800-1741-11ea-955f-4fef9e2b818a.png)

Does seem to make sense I guess...

Unless we were to say something like this instead:
> Images must be at least 500x500 pixels (larger images will be scaled down to this).

**Comment by quicksketch** [comment] 2019-12-05 20:32
Seems like the current PR is an improvement. Maybe we merge that one in and make combining the two messages into a follow-up?

**Comment by quicksketch** [comment] 2019-12-12 18:32
I've merged https://github.com/backdrop/backdrop/pull/2998 into 1.x and 1.14.x. Thanks everyone!

**Closed** 2019-12-12 18:31 UTC
Labels: pr - ready to be committed, pr - works for me, status - has pull request, type - bug report
