### ISSUE TITLE
[UX] Fix RTL admin_bar style

### ISSUE THREAD

**Issue by shabibalm** [backdrop/backdrop-issues#3405] opened 2018-12-04 10:30 UTC
fix admin bar with rtl
befor

![admin-bar-backdrop](https://user-images.githubusercontent.com/45591694/49435213-266c8980-f7c7-11e8-9e65-bcc17d864f47.gif)

after

![fix-admin-bar-rtl-backdrop](https://user-images.githubusercontent.com/45591694/49435885-b5c66c80-f7c8-11e8-95cb-84259aaa72e3.gif)

change line 186 admin_bar.css
`[dir="rtl"] #admin-bar .dropdown li li.expandable ul {
  margin-left: 160px;
  margin-right: 0;
}`
to 
`[dir="rtl"] #admin-bar .dropdown li li.expandable ul {
  margin-right: 160px;
  margin-left: 0;
}`

thanks team backdrop
---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2403 (credits to @shabibalm)

**Comment by klonos** [comment] 2018-12-05 11:57
Thank you @shabibalm for taking the time to report this, and to also propose a fix 👍 

I have filed a PR for it, and have tested in the sandbox, and confirmed that it fixes things. Can someone else please also take a look and RTBC? Thanks

**Comment by klonos** [comment] 2018-12-05 11:59
PS: there are so many other places we need to fix for RTL. I'll file a meta.

**Comment by shabibalm** [comment] 2018-12-05 16:43
I'm working now for translate backdrop to arabic and fix rtl

**Comment by klonos** [comment] 2018-12-05 21:17
Thank you @shabibalm 👍 ...since you seem to be new in our community (I could be wrong about that), let me point out a few things that you can do in order to participate and contribute more as your time/energy allows:

- you can join our Gitter channel: https://gitter.im/backdrop/backdrop-issues ...you will find that if you post there about an issue and ask for people to provide feedback and/or test things, we are pretty responsive 😄

- if you are a developer and knowledgeable with all things around GitHub and pull requests, you will also be pleasantly surprised to see that when we file a pull request with a fix for a bug, or a new feature, there is a sandbox/test site created, which includes the fix or feature. So even if coding and pull requests is not your thing, when someone else creates a pull request, you can test their code in that demo/sandbox site. In this ticket for example, you will see that I have filed a PR with your code suggestions for the fix to this bug. Look in the issue summary at the top ^^ and you will find a link that I have added to that PR. If you follow that link, you will see a series of comments. Look for the comment with a link to a site, a username, and a password:

  <img width="789" alt="screen shot 2018-12-06 at 8 06 20 am" src="https://user-images.githubusercontent.com/2423362/49544603-559e0a80-f92f-11e8-8fb8-6147d70d0a56.png">

  ...you can use that to test if the code changes in the PR fix the problem, then head back to the issue here and provide feedback. You can for example report possible problems that you noticed, or add a comment saying that the issue is RTBC (= **R**eviewed and **T**ested **B**y the **C**ommunity).

  Marking issues as RTBC helps draw the attention of our core committers, who will check the code, and apply the fix for the next version of Backdrop.

Please take a look at https://backdropcms.org/support/resources for other way to contribute and participate, like perhaps joining our weekly developers meeting tomorrow (which despite its name is not only for developers).

It is really great to have you onboard, and thank you for your time 😄

**Comment by shabibalm** [comment] 2018-12-11 19:39
thank you @klonos i'm here new but i like backdrop cms
thanks for information

**Comment by jenlampton** [comment] 2019-01-13 01:49
I can confirm the PR fixes the issues, thanks @shabibalm for the solution!

**Comment by quicksketch** [comment] 2019-01-14 03:48
Thanks @shabibalm, @klonos, and @jenlampton! Merged https://github.com/backdrop/backdrop/pull/2403 into 1.x and 1.11.x!

**Closed by quicksketch** 2019-01-14 03:48 UTC
Labels: pr - reviewed & tested by the community, status - has pull request, type - bug report
