### ISSUE TITLE
[UX] Date field: Current date (time) is calculated differently in Default date and description

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#2903] opened 2017-11-03 12:17 UTC
When I choose the option "Default date: Now" in the settings of a date field, the current date (and time, depending of the field settings), is displayed correctly on the node edit form. In contrast, the date / time value in the field description is not always correct: At a certain time of the day the values differ by 12 hours.

### Steps to reproduce

Update: The issue seems to occur only between noon and 1pm, so be sure to reproduce it by that time of the day.

- Create a date field in a content type.
  - Set the field to collect Year, Month, Day, Hour and Minute.
  - Choose *Text field* as the *Widget Type*.
- Add a new item of the content type in question.
- Have a look at the date field.

### Actual behavior

While the value in the Date field text widget is correct, the one in the description isn't. It differs by 12 hours. Here's an example:

- Date field text widget:
  - `2017-11-03T12:22`
- Description:
  - `Format: 2017-11-04T00:22`

NB: If the date field doesn't collect hours and minutes, the visible values may not differ at all, or they differ by one day. Example (screenshot):

![screen-backdrop-date-field-default-vs-description](https://user-images.githubusercontent.com/14188307/32373223-871b3234-c098-11e7-899f-73f6bfa114bd.png)

### Expected behavior

Both dates are displayed correctly, without any difference.

### Relevant version/system information

- Backdrop 1.8.0
- Default and user's time zone: `Europe/Berlin: +100`

---

**@Graham-72: "PR #2038** by provides a fix for this. I think it is a usability issue rather than a bug, but to the user it looks like a bug."

**Comment by Graham-72** [comment] 2017-11-03 15:41
@olafgrabienski I am not able to reproduce this. Does it happen at any hour of the day or just in hour 0 or 12 ? Which type of date field are you using - e.g. UNIX, ISO ?

**Comment by olafgrabienski** [comment] 2017-11-03 16:05
@Graham-72 Thanks for checking the issue! I'm using the the 'normal' Date field, not UNIX nor ISO.

At the moment I can't reproduce the issue either. It happened however (on two different sites) between noon and 1pm. In the example above the current time was 12:22 pm.

I'll add the information about the specific time when the issue occurs in the *Steps to reproduce* section of the issue description.

**Comment by Graham-72** [comment] 2017-11-04 12:23
@olafgrabienski I can reproduce the problem now that it it 12.16 here. Clearly there is a bug in the code. Well spotted!
![screenshot-2017-11-4 create plain page backdrop starter](https://user-images.githubusercontent.com/10559274/32405301-be4d6660-c15a-11e7-8e4f-958300f6b1ae.png)

**Comment by Graham-72** [comment] 2017-11-05 16:00
This would seem to be caused by code in function date_example_date() in date.module which is a copy of the same function in the D7 Date module, in date_api\date_api.module.

Its intention would seem to be to deal with differences between the 24 hour and 12 hour clocks but it does not seem to be doing this correctly. Perhaps it would be better to omit this piece of code:
```
if (date_format($now, 'H') == date_format($now, 'h')) {
    date_modify($now, '+12 hours');
  }
```

**Comment by olafgrabienski** [comment] 2017-11-06 23:16
@Graham-72 Interesting! I found a similar Drupal issue about month examples: https://www.drupal.org/node/2261251.

From the Drupal issue I understood that the goal of the code is to "disambiguate date examples" in certain cases. Not sure if it's good to remove the code then. Maybe add another `if` statement to exclude the time range from noon to 1pm instead?

**Comment by Graham-72** [comment] 2017-11-11 08:01
@olafgrabienski thanks for the link to the Drupal issue which explains the purpose of the code. I see that it is there to avoid any ambiguity about the example shown, changing all am times to pm, also changing the 11th day of the 11th month to be the 12th day, as it is doing today
![screenshot-2017-11-11 create plain page backdrop starter](https://user-images.githubusercontent.com/10559274/32687472-04feadbc-c6b5-11e7-8b68-1708d8d0029e.png)

So it would seem that this is not a bug since the code is working as intended. However, I think it can be confusing to the user when the hour is changed by 12 hours or the day is changed by 1. As a user I think something odd is happening and something must be wrong.

I think it would be better to use a fixed date and time for the example, choosing one that is unambiguous in all date formats, and I suggest 23.59 on 31st December of any year will achieve this.
![screenshot-2017-11-11 create plain page backdrop starter 1](https://user-images.githubusercontent.com/10559274/32687529-37023ed6-c6b6-11e7-91b8-70c741bea5a0.png)

What do you think? Shall I submit a PR?

**Comment by olafgrabienski** [comment] 2017-11-11 17:33
> I think it would be better to use a fixed date and time for the example, choosing one that is unambiguous in all date formats, and I suggest 23.59 on 31st December of any year will achieve this.

Yes, that's an excellent idea! (To make more clear that the date is ficticious, I'd choose another year example, for instance `2099`.)

A PR would be good, if it isn't too much work at this moment. I guess we could need in any case more feedback regarding the suggestion, and maybe it's easier to get it with a working PR.

**Comment by olafgrabienski** [comment] 2017-11-14 17:48
PR looks good, see screenshot as an example:

![screen-backdrop-pr-2038-date-format-example](https://user-images.githubusercontent.com/14188307/32795563-5c0960de-c96c-11e7-8c8e-a13713801140.png)

RTBC in my opinion.

**Comment by quicksketch** [comment] 2017-12-15 01:59
Thanks, great suggestion! I wasn't sure about the year "2099", but then I realized that helps clarify month and day versus year. I think it's a great improvement and the +12 hours thing was definitely weird. Merged in https://github.com/backdrop/backdrop/pull/2038 into 1.x and 1.8.x. Thanks @olafgrabienski and @Graham-72!

**Closed by quicksketch** 2017-12-15 01:59 UTC
Labels: pr - reviewed & tested by the community, status - has pull request, type - bug report
