### ISSUE TITLE
`type = module` missing from .info files in modules of the "Testing" core profile.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3821] opened 2019-05-27 18:34 UTC
This was reported by @simone960 in https://forum.backdropcms.org/forum/failed-perform-manual-self-update

> I tried to update my backdrop 1.12.6 to 1.13.1 from the backend but I encountered error recorded in the log message:
> 
> ```
> LOCATION: https://  mydomain/admin/update/ready
> 
> MESSAGE: UpdaterException: The info file
> (<em class="placeholder">temporary://update-extraction-7a226124/backdrop/core/profiles/testing/modules/backdrop_system_listing_compatible_test/backdrop_system_listing_compatible_test.info</em>)
> does not define a 'type' attribute. in Updater::getProjectType()
> (line 199 of /mydomain/core/includes/updater.inc).
> ```
> 
> Any idea how to resolve this ?

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2705

**Comment by klonos** [comment] 2019-05-27 18:40
...in #3553 we solve the same issue with .info files of core profiles by making sure that they all include a `type = profile` line.

In #1294, we are excluding `*.tests.info` files from the requirement to include a `type = ` line, but the specific error is caused because the file in question is a `*_test.info` file instead (so not caught by the logic).

We should do either one of the following:

a) rename all `.info` files for tests, to make sure that they follow the same `*.tests.info` convention
b) include `*_test.info` in the logic that excludes test `.info` files
c) require all `.info` files (including tests) to have a `type = something` line (this would practically revert #1294)

**Comment by klonos** [comment] 2019-05-27 18:48
...from #1294:

@klonos:
> These are not modules or themes or layouts. The "right" way to do it would be to perhaps require a `type = test` line, but I say we make this optional and instead rely on the fact that these live within `/test` subdirectories.

@quicksketch:
> Rather than ignoring test directories, I'd recommend just stopping at the first .info file found, as suggested in https://github.com/backdrop-contrib/honeypot/issues/6#issuecomment-149414901. It will accomplish the same thing in hopefully a slightly more robust approach.

In this specific use case, there was no `/test` or `/tests` directory, and the .info file was not following any specific convention. Perhaps it is time to reconsider the `type = test` approach?

**Comment by docwilmot** [comment] 2019-05-27 20:38
Actually the Updater logic is fine, this is just an edge case we missed. Some tests have a dummy module (and usually we name them `whatever_test`, with a corresponding `whatever_test.info`, but could be named anything, they're normal modules, just only used for a specific test.) 

But normally they would be inside a `tests` directory:
```
whatever.info
whatever.module
tests
--whatever.tests.info
--whatever.test
--whatever_test            <---- dummy module
----whatever_test.info
----whatever_test.module
```
So the Updater logic would check inside the `tests` folder, find a `test.info` file, and skip everything inside that folder including the dummy module. 

This dummy module, `backdrop_system_listing_compatible_test` just happens not to live in a tests folder. 

```
testing.profile
whatever.info
modules
--backdrop_system_listing_compatible_test.info
--backdrop_system_listing_compatible_test.module
```

It needs a `type=module` in other words.

**Comment by klonos** [comment] 2019-05-27 20:48
> ...they're normal modules, just only used for a specific test.) ...It needs a `type=module` in other words.

You are absolutely right @docwilmot 👍

**Comment by herbdool** [comment] 2019-05-29 11:57
This is a duplicate of https://github.com/backdrop/backdrop-issues/issues/3793. We should close this one.

**Closed** 2019-05-29 11:59 UTC
Labels: pr - needs code review, pr - needs testing, status - has pull request, type - bug report
