### ISSUE TITLE
Dashboard module conflicts with Block Reference Module

### ISSUE THREAD

**Issue by redstagmedia** [backdrop/backdrop-issues#3966] opened 2019-08-06 06:09 UTC
When attempting to view a node type containing a block reference field (with a value), I am getting the following error:

"Error: Call to a member function hasContexts() on null in dashboard_preprocess_block() (line 218..."

dashboard_preprocess_block function in dashboard.module @line 217 to 218 is:

```
$layout = $variables['layout'];
if ($layout->hasContexts(array('dashboard'))) {
```
The problem with this appears to be that a block called through a block ref field may not have a layout assigned.  This will result in $layout being Null, which causes the error.

Having a null check at the beginning of the if statement @line 218 solves this issue:

```
if (!is_null($layout) && $layout->hasContexts(array('dashboard'))) {
```

---

PR by @olafgrabienski: https://github.com/backdrop/backdrop/pull/2839

**Comment by klonos** [comment] 2019-08-06 07:44
Thanks for taking the time to register a GitHub account and report this @redstagmedia 👍

...I will try to reproduce this soon as I get a chance, and also test your proposed solution. If it all checks out, I'll file a pull request for it (unless either you or someone else beats me to it 🙂).

**Comment by klonos** [comment] 2019-08-06 15:44
@redstagmedia I have tried to reproduce this but was not able to. Can you please provide step by step instructions? Thanks.

**Comment by olafgrabienski** [comment] 2019-08-06 19:13
Just yesterday I ran into the same issue: After enabling the *Dashboard* for a site which makes use of [Block reference](https://backdropcms.org/project/blockreference), I got the "unexpected error" message on some pages, and in the log I found the `Call to a member function hasContexts() on null in dashboard_preprocess_block()` message mentioned above. After disabling the Dashboard, everything was fine again.

@klonos - I think I can reproduce the issue but I'm short of time and will need some time to write up the exact steps.

**Comment by redstagmedia** [comment] 2019-08-06 19:34
@klonos 
Assuming you have a typical install with Dashboard enabled, here are the steps as I've encountered them:

1. Install Block Reference module
2. Add Block Reference field to a node type (I chose to limit it to only views blocks)
3. Create a node of that node type and select a value for the block ref field (when I leave it blank I get a completely different type of error that should be a completely different issue.)
4. Once saved, you won't be able to view the node assuming that the block ref field is set to show in the default node display.

**Comment by olafgrabienski** [comment] 2019-08-15 13:14
> Assuming you have a typical install with Dashboard enabled, here are the steps (...)

@redstagmedia The steps described by you meet exactly the configuration of my site which was running in the same error. As you mentioned, making the following change in line 218 of `core/modules/dashboard/dashboard.module`, solves the issue:

```
-  if ($layout->hasContexts(array('dashboard'))) {
+  if (!is_null($layout) && $layout->hasContexts(array('dashboard'))) {
```

Are you up to make a PR?

**Comment by olafgrabienski** [comment] 2019-08-15 13:21
> when I leave [the block ref field] blank I get a completely different type of error that should be a completely different issue.

I get also a different message when I leave the Block Reference field empty:

`Notice: Trying to get property 'langcode' of non-object in locale_language_url_rewrite_url() (line 434 of /(...)/core/includes/locale.inc).`

(It's still possible to visit the page in this case.)

@redstagmedia Do you get the same message?

**Comment by olafgrabienski** [comment] 2019-09-02 11:47
> If it all checks out, I'll file a pull request for it (unless either you or someone else beats me to it 🙂).

@klonos, I've created a PR at https://github.com/backdrop/backdrop/pull/2839. Are you up to test and/or review it?

> making the following change in line 218 of core/modules/dashboard/dashboard.module, solves the issue

`dashboard.module` has changed in the meantime, the fix is in line 225 now.

Note: The PR fixes the *error* but not the *notice* mentioned in https://github.com/backdrop/backdrop-issues/issues/3966#issuecomment-521638343.

**Comment by olafgrabienski** [comment] 2019-09-09 22:02
I've changed the PR according to a suggestion by @herbdool. Instead of

`!is_null($layout)`

it uses

`is_a($layout, 'Layout')`.

The PR works for on my test site, and this time it fixes not only the error mentioned in the issue description but also the *notice* mentioned in https://github.com/backdrop/backdrop-issues/issues/3966#issuecomment-521638343.

@klonos or @redstagmedia - want to confirm if the fix works for you?

**Comment by herbdool** [comment] 2019-09-10 14:37
@olafgrabienski it works for me. (I found unrelated bugs in block reference and put issues in that project's queue).

I've requested one addition in a similar function to be consistent in ensuring that the variable is actually an object of the Layout class.

**Comment by olafgrabienski** [comment] 2019-09-10 20:57
@herbdool Thanks a lot! I've added the fix to the other function as well.

**Comment by quicksketch** [comment] 2019-09-16 02:34
Thanks! Merged https://github.com/backdrop/backdrop/pull/2839 into 1.x and 1.13.x.

**Closed** 2019-09-16 02:33 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2019-09-16 02:35
Extra thanks to @redstagmedia for reporting this issue! Welcome to Backdrop!
