### ISSUE TITLE
[UX] Add timestamp to date displayed in DBlog

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3753] opened 2019-05-03 23:57 UTC
I would like to include the time, as well as the date, in the 'Date' column of the dblog. 

<img width="1208" alt="Screen Shot 2019-05-03 at 4 53 13 PM" src="https://user-images.githubusercontent.com/397895/57170753-efc18c00-6dc3-11e9-939f-ac68a7f4cf41.png">

When something goes wrong on your site, its helpful to be able to check the date and the time of the problem, and then the date and time in the logs. If there's no time in the log, that's not so nice. 

If you have adjusted your date formats so that 'short' no longer includes a time, then you end up in a pickle when reviewing the dblog.

I think this might be one place where it would be better not to use a configurable date format.

**Steps to reproduce:**

1) go to Date and time formats (admin/config/regional/date-time)
2) remove the time from short and save
3) visit your error log (http://backdrop.local/admin/reports/dblog)

Problem:

* no timestamps

Expectation

* system logs not affected by front-end facing date format configuration

---
PR: https://github.com/backdrop/backdrop/pull/2645

**Comment by jenlampton** [comment] 2019-05-07 19:31
> but my problem is that this hardcodes the date used in the dblog ... but it may be limiting now.

It doesn't hard code the date. Only the **date format**. Dates are still accurate. 

Removing this customization will prevent people form shooting themselves in the foot, by taking the nailgun out of their hand. Limiting and safe is better than flexible where the flexibility is completely unnecessary. 

> How about we introduce a new date format called dblog and use that one for the dblog instead?

We don't need a date format for everything, it will just clutter the UI and confuse people. 

Can you explain your objection to providing people with a sensible date format? If the problem is which format, let's fix that. But let's not give people tools they don't need :)

**Comment by findlabnet** [comment] 2019-05-08 06:47
>Removing this customization will prevent people from shooting themselves in the foot

Seems like too powerful decision - you shouldn't set your preferable date format at system level without option to change it.
For example, this is my preferred short date format, widely used outside of USA:

![dblog](https://user-images.githubusercontent.com/11479969/57354694-d712f680-7174-11e9-8a88-701cbb253bea.png)
 
So, hard code for only one specific format of date can (and will) create new UX problem.

**Comment by jenlampton** [comment] 2019-05-08 07:11
> For example, this is my preferred short date format

Everyone will still have the ability to set a short date format. 

It's only this date -- the one that is used in the dblog -- that I want to lock down. We need to guarantee that people can't accidentally remove the day, time, or even year -- as is commonly done with the short date format. For most dates it's not important whether they include all the parts but **this  particular date** is different.

I really like the `2019-05-07` date format too. The problem with using all numbers, though, is that some people struggle with month vs day. `2019-05-07` could be either May or July. If we set it to something like `2019-May-07` that might be more universal.  I'm also fine with using 24-hour time here if that would be less confusing. 

let me give the PR a re-roll.

**Comment by jenlampton** [comment] 2019-05-08 07:21
I've pushed an updated PR with a new custom date using `Y-M-d g:ia`:

<img width="1328" alt="Screen Shot 2019-05-08 at 12 18 08 AM" src="https://user-images.githubusercontent.com/397895/57357095-00a53100-7127-11e9-9181-ffd240ec9a1f.png">

Please let me know if you have other recommendations that might be improvements! (24 hour time?)

**Comment by findlabnet** [comment] 2019-05-08 07:31
24-hour time more clean to me, in my location am/pm format is not in use.
Second thing I personally dislike - two lines of text in any table cell, just so ugly for me.

**Comment by jenlampton** [comment] 2019-05-08 07:38
> 24-hour time more clean to me,

I've updated the PR with 24 hour time. I like this better too! `Y-M-d h:i`

<img width="1325" alt="Screen Shot 2019-05-08 at 12 34 28 AM" src="https://user-images.githubusercontent.com/397895/57357966-24697680-7129-11e9-97d1-079630849180.png">

> Second thing I personally dislike - two lines of text in any table cell

That might have to do with the width of the errors in my log.

**Comment by findlabnet** [comment] 2019-05-08 07:54
Two lines in the cell also caused by "(not verified)" label, see https://github.com/backdrop/backdrop-issues/issues/3390 about this tail.
In my customization this is just removed as proposed and horizontal padding for this cell changed from 20px to 15px, as result I have more accurate seems table. 
This page (dblog) is my tool for work and I love comfortable and beautiful tools.
About variable in settings.php - for me is good if any customization available.

**Comment by jenlampton** [comment] 2019-05-08 08:07
> About variable in settings.php - for me is good if any customization available.

@klonos is that enough of a customization to make you happy too?

**Comment by klonos** [comment] 2019-05-08 09:52
> The problem with using all numbers, though, is that some people struggle with month vs day ...

> 24-hour time more clean to me, in my location am/pm format is not in use.

That is precisely the reason why we'd be creating a UX issue by hard-coding the date in a specific format ...that plus if more people had visibility on this issue here, I'm sure we'd have lots more bike-shading 😅. For example, I'm also a big fan of 24hr format, but Aussies don't seem to like it (they call it "military" format).

Anyway, something customisable via settings.php is better than hard-coding things, which would force people to hack core (and kittens to die 😅).

Having said that, I am still not entirely convinced why an additional date format would be confusing or add clutter. We already allow people to add date formats via the admin UI, and I personally do not revisit that admin page once I have configured things once.

Ideally, the dblog listing would be a view. That would allow admins to customise the date format of that column at will, via the admin UI. If not that, then I'd prefer an additional date format. If not that, then I'd settle for settings.php ...although as a constituent of site-builders that never touch code unless they have to, I would frown.

If everyone else is happy with settings.php, then can we at least call it something that is less dblog-specific, so that we can reuse it in elsewhere in the admin UI in the future? Something like `system_date_format` or `admin_date_format`?

PS: the PR is RTBC if we decide that a settings.php option is the best way to go.

**Comment by findlabnet** [comment] 2019-05-08 11:08
> Ideally, the dblog listing would be a view.

How you see this view items? 
Should we have some specific entity type, instance of which will be created for each dblog event instead of simple DB record? 
Seems like slightly overloaded solution.

**Comment by jenlampton** [comment] 2019-05-08 17:33
I agree a view here is overkill, but that could be done in contrib.

@klonos the whole point of this issue is that this one, single, date needs
to be treated differently than all the others.

We should not use this setting for anything else, anywhere, or we are
likely to get into the same mess a date format caused: someone customizes
it for the other thing and inadvertantly interferes with the thing they
need to use in an emergency.

The name of the setting is super specific to indicate that this setting is
for one thing, and one thing only.

Another option would be to come up with a way to make a date format hidden,
and then add a hidden one into config. That might make it easier for
non-coders, but it would also be encouraging people to edit config files
directly, which I don't really want to condone...

**Comment by herbdool** [comment] 2019-05-11 04:25
RTBC.

I didn't like it at first, and I was about to do some bikeshedding but decided that this is a simple, elegant solution. And 97% of people are never going to change this.

**Comment by findlabnet** [comment] 2019-05-12 05:06
Sorry for late reaction, but hours format should be fixed
from `$dblog_date_format = settings_get('dblog_date_format', 'Y-M-d h:i');` - 12-hour format of an hour with leading zeros
to `$dblog_date_format = settings_get('dblog_date_format', 'Y-M-d H:i');` - 24-hour format of an hour with leading zeros
Commented in PR too.

**Comment by jenlampton** [comment] 2019-05-12 22:32
Thanks @findlabnet  for catching that, and thanks @herbdool  for fixing it in the PR. I was discussuing this with @quicksketch over dinner the other night, and he asked if we had any other settings form for database logging that we might use for this purpose, rahter than leaving it to a setting in `settings.php`. Then I remembered we had `admin/config/development/logging`. 

So, I've pushed a commit that adds seconds, and another that replaces the settings.php setting with a UI setting, like so: 
<img width="1463" alt="Screen Shot 2019-05-12 at 3 32 07 PM" src="https://user-images.githubusercontent.com/397895/57588571-19b53580-74cb-11e9-8f7a-51faae018541.png">

**Comment by herbdool** [comment] 2019-05-12 23:19
RTBC!

**Comment by klonos** [comment] 2019-05-15 11:55
>The name of the setting is super specific to indicate that this setting is
for one thing, and one thing only.

Fair enough.

> ...Then I remembered we had `admin/config/development/logging`. ...I've also pushed another commit that replaces the settings.php setting with a UI setting ...I think that @klonos will like this better because it doesn't require touching code ...Also, it's config, so deployable!

I do love it ❤️ ...and envious that I did not think of that 🙂 👍

**Comment by quicksketch** [comment] 2019-05-15 21:49
The PR at https://github.com/backdrop/backdrop/pull/2645 looks good. I'm not sure about the default date format myself, but we could change that later. The functionality improvement is definitely worthwhile.

We do need an update hook though. Which should pull from the "short" format and set the default value to match so upgrading sites should get identical functionality to how their site was before the change.

**Comment by jenlampton** [comment] 2019-05-15 22:33
Update hook added.

**Comment by klonos** [comment] 2019-05-15 23:03
I've left a tiny change suggestion in the PR; otherwise looks RTBC 👍

**Comment by jenlampton** [comment] 2019-05-15 23:07
merged your suggestion! ty :)

**Comment by quicksketch** [comment] 2019-05-16 00:13
I meant to include this in 1.13.0, oh well. Looking good and we can include it in 1.13.1.

**Comment by quicksketch** [comment] 2019-05-17 20:42
Merged https://github.com/backdrop/backdrop/pull/2645 into 1.x and 1.13.x for 1.13.1.

**Closed** 2019-05-17 20:41 UTC
Labels: good first issue, pr - ready to be committed, pr - works for me, status - has pull request, type - bug report
