### ISSUE TITLE
Using Views to override a node

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3228] opened 2018-08-02 08:49 UTC
It's kind of embarrassing to post this as I pride myself on my knowledge of Views and using relationships, contextual filters, etc. But I can't figure it out or find examples online...

So when I'm viewing a node (e.g. `/node/15`, or its alias `/post/my-blog-post`) I want that page to actually be a view (so I can manipulate the fields, etc. using Views instead of tweaking a template file). I can accomplish this easily by creating a view with the path `node/%` and setting a NID contextual filter that gets its default value from the content ID in the URL, however the problem is when I only want this view affecting a certain content type. Regardless of setting a filter criteria of Content Type = Post, anytime I view a node of a different content type on my site I get a 'Page not found' error.

Is there a way to restrict a view from affecting other content types? If so, how (what am I missing)?

**Comment by olafgrabienski** [comment] 2018-08-02 16:09
Only guessing: maybe because of the Layout system? I'm wondering e.g. if this Views page and the (usually required) "Main page content" block play well together. Do you see any Layout related (or other) messages in DBlog?

Apart from that: what about another approach? Remove the node fields via "Manage display" from the node (type) display, build the view as a block display, and put the block in a node type specific Layout.

**Comment by laryn** [comment] 2018-08-02 16:18
It might be best to set this up as a Layout with the `node/%` path and a visibility condition for the content type in question. Then you don't have to create a Views page at all, just the blocks that you place on this custom layout.

**Comment by laryn** [comment] 2018-08-02 16:20
(Also, once this is answered, it may be worth transcribing to the forum)

**Comment by docwilmot** [comment] 2018-08-02 17:40
@BWPanda Im not sure thats possible. Once you provide a path in Views it takes over the menu routing for that path. So you cant have some pages with that same path providing a View and others not. Maybe though you could create a separate Views display with different filter criteria, that just provides the full view mode instead of fields?

**Comment by BWPanda** [comment] 2018-08-02 18:13
Thanks guys!

@docwilmot Your suggestion sounded so perfect that I tried it immediately (and wondered why I didn't think of it myself). Unfortunately it doesn't seem to work. Even putting the display with content type != post as the first view's 'no results behaviour' doesn't work... Sad.

But I've since tried this in Drupal and had the same issue there, so it's not specific to Backdrop. That made me wonder why I seem to recall doing this before, but I think maybe I'm confusing Views with Ctool's Page Manager/Panels. So I think @olafgrabienski and @laryn are right in that I should be overriding 'node/%' with Layouts instead of Views. Will try that instead.

**Comment by docwilmot** [comment] 2018-08-02 18:43
Did you try a separate view or one view with two page displays? Not that I think it would work but curious.

**Comment by BWPanda** [comment] 2018-08-02 18:53
@docwilmot One view with two displays.

@laryn That's awesome! I had no idea that you could add fields directly to a layout! You can't do it to the default layout, so it must be activated by either the 'node/%' path or (more likely) the content type visibility setting. Nice! :grinning:

**Comment by laryn** [comment] 2018-08-02 19:25
@BWPanda Yes, the "context" path (`node/%`) can provide additional fields to the Layout, which is pretty awesome.

**Comment by jlfranklin** [comment] 2018-08-03 03:28
IIRC, D7 had views that "attached" to node pages, receiving the node's NID as a contextual parameter.  The attached Views acted more like blocks, but it let you attach, for example, a list of related blog posts based on the taxonomy terms of the current post.  

It would feel like a bit of a hack to me, but you could set the node's display to show no field at all and attach a view.

**Comment by BWPanda** [comment] 2018-08-03 05:52
@klonos :grin:

**Comment by BWPanda** [comment] 2018-08-03 07:37
So using Layouts to override `node/%` for just one content type (using a visibility filter) seems to have done the trick. However now I seem to have lost the local task tabs (view, edit, etc.). They're still setup in the Layout, just not displaying when I view nodes of that content type...

**Comment by klonos** [comment] 2018-08-03 21:31
@BWPanda I tried to reproduce the problem you are describing, but I could not. Here's what I have done:

- added a new layout with its path set to `node/%`
- removed the main content block
- added the "Page tabs (local tasks)" block and the body field block in the content region
- visited a few existing nodes while logged in as admin

The local task tabs were always rendered for me. Can you please provide steps to reproduce in a vanilla installation?

**Comment by klonos** [comment] 2018-08-03 21:33
...I have also tried moving the blocks to a region other than the "CONTENT" region. Still no problems.

**Comment by BWPanda** [comment] 2018-08-07 17:04
@klonos I'm getting some notices in my logs:

- Notice: Undefined variable: messages in include() (line 30 of /[SNIP]/core/modules/system/templates/page-components.tpl.php).

So it might be related to that... Will investigate further.

**Comment by BWPanda** [comment] 2018-08-07 18:47
@klonos Ok, so this is the weirdest thing ever... I'd love to know if it happens to you too.

Do the steps you mentioned above and, after the last step (confirming that existing nodes still display as expected), go back to the layout and remove the 'Powered by Backdrop' block. Then check the nodes again...

**Comment by klonos** [comment] 2018-08-07 21:06
Indeed, removing the "Powered by Backdrop" block makes the local tabs disappear. Hmm.

**Comment by BWPanda** [comment] 2018-08-08 02:28
So weird right? Also, it's not just the local tabs, but page title, messages, etc. Any page component it seems: https://api.backdropcms.org/api/backdrop/core%21modules%21system%21templates%21page-components.tpl.php/1

**Comment by klonos** [comment] 2018-08-08 16:47
Weird indeed. Care to file a bug report @BWPanda?

**Comment by BWPanda** [comment] 2018-08-08 19:02
Sure, done: https://github.com/backdrop/backdrop-issues/issues/3247

**Comment by BWPanda** [comment] 2018-08-08 19:04
Going to close this now. Original question answered, and bug report filed for the discovered issue.

**Closed by BWPanda** 2018-08-08 19:04 UTC
