### ISSUE TITLE
#states does not properly hide title and description of checkboxes element

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#711] opened 2015-02-13 02:00 UTC
I have the following form element:
```
$form['services']['enabled'] = array(
        '#type' => 'checkboxes',
        '#title' => t('Icons'),
        '#options' => $sorted_options,
        '#default_value' => (isset($settings['enabled'])) ? $settings['enabled'] : $defaults,
        '#description' => t('Please select the icons you would like displayed in this block.'),
        '#states' => array(
          'visible' => array(
            ':input[name="block_settings[services][display]"]' => array('value' => 'manual'),
          ),
        ),
      );
```

When the display target element is toggled, the checkboxes correctly appear and disappear, but the element title and description are always visible. It looks like the `display:none` is being added to the wrong div.

**Comment by bt-eric** [comment] 2015-03-21 14:21
For the visibility state, states.js looks for the nearest .form-item, .form-submit, or .form-wrapper element and applies the appropriate display style to it. For issue #197, the theme_checkboxes and theme_radios functions were removed in previous commits in favor of theme_container. This introduced a form-wrapper div around the form item value but not the form item label (there's no label in a container). This pull request modifies theme_container to not add the form-wrapper class if $element['#type'] exists and does not equal container.

**Comment by quicksketch** [comment] 2015-03-22 20:56
Thanks @bt-eric for researching this one and finding the root cause. I'm not sure about the solution proposed. Perhaps we could use different attribute besides `#type` on the element to determine if the class should be added.

Would something like this work?

```php
if (empty($element['#attributes']['class'])) {
  $element['#attributes']['class'][] = 'form-wrapper';
} 
```

Then if checkboxes or radios add a different class, they won't end up with the `form-wrapper` class as well.

**Comment by quicksketch** [comment] 2015-03-22 20:56
Let's try to fix this for the next bugfix release.

**Comment by bt-eric** [comment] 2015-03-28 03:59
I agree the check for an existing class is a better approach, and it works well. The pull request has been updated.

**Comment by quicksketch** [comment] 2015-03-30 01:51
Sweet. Thanks! I'll try giving this a manual go and see if it fixes the configuration display issues in Views, where this problem is most apparent.

**Comment by quicksketch** [comment] 2015-03-30 17:36
Confirmed this solves the problem in Views as well. It was apparent when using the "Content type" as an exposed filter, the list of content types to expose was a set of checkboxes whose title would never go away. This fixes the problem and the title is now hidden when the checkboxes are hidden. Nice one!

Merged this in as a squashed commit https://github.com/backdrop/backdrop/commit/c499829a2aad6a100ae6f3ebcd1b06b5e9c60b2d into 1.x and 1.0.x. Thanks @bt-eric!

**Closed by quicksketch** 2015-03-30 17:36 UTC
Labels: pr - needs review, status - has pull request, type - bug report
