### ISSUE TITLE
Issue with Backdrop modals causing the main body to jump up to the top

### ISSUE THREAD

**Issue by kelizoliva** [backdrop/backdrop-issues#4627] opened 2020-09-18 23:33 UTC
**Description of the bug**

We have experienced this with Layout block modals, as well as Node image selection modals. After the modal opens, the content in the background scrolls up to the top of the page, l which is rather disorienting after closing the modal and not being at the point in the page you were at when opening the modal.

**Steps To Reproduce**

To reproduce the behavior:
1. Go to any layout block management page and scroll down to a block below the fold.
2. Click on 'Configure' for a block.
3. See the content behind the modal scroll to the top.

**Expected behavior**

The background should stay locked in the position it was in before the modal was opened.

I do not think there is any other information that would be helpful here. This is not browser or OS specific. There are no errors coming up in the console, so without digging around in the code I am suspecting that this may be operating as written in the js. But it is very disorienting and undesirable behavior.

**Comment by BWPanda** [comment] 2020-09-19 04:03
Thanks for reporting this @kelizoliva, however I'm going to close this as a duplicate of https://github.com/backdrop/backdrop-issues/issues/4342.

**Closed by BWPanda** 2020-09-19 04:03 UTC
Labels: status - duplicate
