### ISSUE TITLE
User name views autocomplete filter always shows the same description

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6170] opened 2023-07-14 13:33 UTC
## Description of the bug

Even if the description for the user name exposed filter is left blank, the following is shown:

<img width="1192" alt="Screen Shot 2023-07-14 at 7 30 06 AM" src="https://github.com/backdrop/backdrop-issues/assets/9938978/615fea24-db4b-4840-8e61-a6f0a416cef0">

This makes it impossible to customize the description for this filter, plus it causes quite a bit of alignment problems in Seven if the other filters don't contain descriptions.

There is a [D7 issue](https://www.drupal.org/project/views/issues/1700194) for this.

## Steps To Reproduce
1. Create a user View
2. Add a user name exposed filter, leave the description blank
3. Add another exposed filter without a description
4. Visit the view 

## Actual behavior

The description for the user name is shown. 

## Expected behavior

If left blank no description should be shown. And if the description is customized, that customization should be shown verbatim. 

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.25.0

----
PR https://github.com/backdrop/backdrop/pull/4473

**Comment by argiepiano** [comment] 2023-07-14 13:40
PR https://github.com/backdrop/backdrop/pull/4473

**Comment by argiepiano** [comment] 2023-07-14 14:51
@olafgrabienski thanks for the response. That view uses a different handler, one that doesn't provide auto complete. It's an acceptable alternative to this bug.

**Comment by olafgrabienski** [comment] 2023-07-14 15:03
> That view uses a different handler, one that doesn't provide auto complete.

Ah, got it! Tried again with autocomplete, and yes, issue confirmed.

**Comment by indigoxela** [comment] 2023-07-15 12:33
It makes sense to me, that this field description (help text) gets handled like other ones, when exposed. The other fields allow to set a custom text or leave empty.

I verified the behavior, then applied the patch and verified that only my custom description is visible (empty if not set). So the field aligns with others, when exposed.
The help text is still there in the views admin form, when configuring the field, of course.

Works for me. :+1:

**Comment by bugfolder** [comment] 2023-09-18 17:21
Code reviewed. LGTM.

**Comment by quicksketch** [comment] 2023-09-22 03:07
Thanks @argiepiano, @indigoxela, @olafgrabienski, and @bugfolder! I've merged https://github.com/backdrop/backdrop/pull/4473 into 1.x and 1.26.x.

**Closed** 2023-09-22 03:07 UTC
Labels: type - bug report, status - has pull request, pr - ready to be committed, pr - works for me
