### ISSUE TITLE
[UX] Add contextual link for editing the currently-used layout

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#3946] opened 2019-07-24 03:24 UTC
**Description of the need**
As I am working on a page, I frequently find myself clicking on a "configure block" contextual link and then closing the block configuration to get to the layout itself. I can get directly to a node, view, or block by using contextual links, but I can not get to the layout directly. 

I think that this would be a nice improvement. 

If a site editor was ever confused about which layout was being used for a page (is that likely), they could use this to find the right layout. 

**Proposed solution**
Add a contextual menu in the upper right hand corner of every page that takes the site editor to the layout that is being used for that page. 

I'm usually looking for the "Manage Blocks" tab as opposed to the "Configure Layout" tab, so that would be my preference. 

@jenlampton said something similar here: https://github.com/backdrop/backdrop-issues/issues/1725#issuecomment-298144809
> There is one feature from Panels (Drupal 7) that we are missing in Backdrop that might serve the same goal, in a slightly less dangerous way: A contextual link on the layout itself.

**Comment by laryn** [comment] 2019-08-02 18:34
Related: https://github.com/backdrop/backdrop-issues/issues/2626

**Comment by BWPanda** [comment] 2019-11-20 13:30
I was just about to post a suggestion for something like this too, because I do the same 'trick'! :smile: 

My only additional suggestion would be instead of a 'cog' contextual link (which may be hard to see/get to in the top-right corner of the page) have a link in the admin menu, probably under the Home icon... But maybe this is already covered in the https://github.com/backdrop/backdrop-issues/issues/2626 issue (haven't looked yet).

**Comment by bugfolder** [comment] 2021-10-09 18:47
Closing this issue as a duplicate of #2626 (where work is ongoing). Based on [decisions taken at 9/30 design meeting](https://github.com/backdrop/backdrop-issues/issues/2626#issuecomment-931743014):

* Near-term needs can be met by the [Layout Contextual Links contrib module](https://backdropcms.org/projects/layout_contextual_links)
* Further eventual integration into core will be addressed by [Issue #2626, [UX] Add a contextual menu for quick access to editing things like the layout, theme, etc. of the current page](https://github.com/backdrop/backdrop-issues/issues/2626).

**Closed by bugfolder** 2021-10-09 18:47 UTC
Labels: type - feature request
