### ISSUE TITLE
Comments on a Views' Full Content display of a node appear above the content.

### ISSUE THREAD

**Issue by muranod** [backdrop/backdrop-issues#6282] opened 2023-11-04 15:25 UTC
## Description of the bug

If I set a view to display full content, with comments, the comments appear above the article with no way to rearrange them.

## Steps To Reproduce

1. Create a node and add a comment
2. Create a view to display the "full content" of a node 
3. In Format, click "Full content" and select "Display comments"
4. Visit the View page

## Actual behavior

The comments are shown above the content of the node. There is no way to rearrange this in the UI.

## Expected behavior

The comments and comment form should be shown below the content.

## Additional information

- Backdrop CMS version: 1.26.1
- Web server and its version: Apache/2.4.56 (Win64) OpenSSL/1.1.1t PHP/8.0.28
- PHP version:  8.20.28
- Database sever (MySQL or MariaDB?) and its version:  MySQL, MariaDB, or equivalent version 10.4.28-MariaDB
- Operating System and its version: Windows 11 current, 
- Browser(s) and their versions:  Firefox / Chrome / Edge current

**Comment by argiepiano** [comment] 2023-11-04 15:34
@muranod I've edited your OP to focus only on one problem (the fact that comments are shown above the content in the View). 

I've reproduced this issue. Also, checked D7: comments there are shown correctly, below the content.

**Comment by argiepiano** [comment] 2023-11-04 17:19
I've found the source of this behavior by comparing to the D7 code. 

Normally in Backdrop, `node.tpl.php` receives the comments in a separate variable, `$comments`.  In D7, the comments are inside `$content['comments']`.  The problem is that Backdrop's `node_row_node_view_preprocess_node()` (a preprocessing function only used by Views), STILL puts the comments inside `$content['comments']`. This results in the comments being rendered together with the rest of the content inside  `$content` (other fields, and the node links).

The solution seems pretty straightforward. Modify `node_row_node_view_preprocess_node()` to place the comments build array inside a separate variable, as in `$variables['comments']` instead of `$variables['content']['comments']` as it does right now. Haven't tested this yet, but I will.

**Comment by argiepiano** [comment] 2023-11-04 18:08
PR https://github.com/backdrop/backdrop/pull/4557. @muranod, can you please test?

**Comment by argiepiano** [comment] 2023-11-04 18:18
Test failures seem random and unrelated.

**Comment by muranod** [comment] 2023-11-04 19:31
@argieplano Willing to try, but I believe it's beyond my skill level.  Is this the correct file:  views_plugin_row_node_view.inc  ?
& would it then go into the theme folder as one would do with a modified page template file?

**Comment by argiepiano** [comment] 2023-11-04 20:50
@muranod, do you have access to the command line (e.g. Terminal in Mac, or ssh access on your hosting server)? If so, this is how you can patch Backdrop to test the PR.

1. Visit the PR URL: https://github.com/backdrop/backdrop/pull/4557
2. Add '.diff' at the end of the URL: https://github.com/backdrop/backdrop/pull/4557.diff
3. This will display the diff file. Save that from your browser onto your computer
4. (Another way to obtain the diff file from the command line is to do `wget https://github.com/backdrop/backdrop/pull/4557.diff` from the root of your Backdrop installation)
5. If you used 3 instead of 4, move the file you saved into the root of your B installation
6. In your command line, be sure you are at the root of your installation. Then run `patch -p1 <NAME_OF_THE_DIFF_FILE`  (insert the name of the diff file you saved above)

That's it. That will automatically make the changes you need to test. Then open your site in your browser and try to reproduce the problem (in this case, create a View of Full content, and check that the comments are printed below the rest of the node content).

Whn you are done, you can revert the patching by running patch -p1 -R <NAME_OF_THE_DIFF_FILE`

**Comment by muranod** [comment] 2023-11-04 22:43
@argiepiano I'm embarrassed to say I had a hard time getting the patch to apply before learning more about it - (I didn't realize the a single < had meaning). 

It worked perfectly!

Thanks for your patience.

**Comment by argiepiano** [comment] 2023-11-04 22:53
Oh sorry - I should have mentioned that "<" was important. 

If the patch works for you, can you please mark this as "tested" and "works for me" - pick those tags on top, where it says "Labels" in this issue post.

**Comment by muranod** [comment] 2023-11-04 22:59
No worries. I should have realized that. 

Took care of the labels. Thanks again.

**Comment by argiepiano** [comment] 2023-11-04 23:03
@muranod, we should not close the issue until the PR is approved and merged. Reopening.

**Comment by bugfolder** [comment] 2023-11-09 21:55
Code reviewed. LGTM.

**Closed** 2023-11-13 21:23 UTC
Labels: type - bug report, status - has pull request, pr - ready to be committed, pr - works for me
