### ISSUE TITLE
Comment titles should be removed from presentation and from database if not used

### ISSUE THREAD

**Issue by cptX** [backdrop/backdrop-issues#4967] opened 2021-02-25 08:20 UTC
**Description of the need**
Hi, I prefer the comments to have no title. Other cms have no comment title at all (eg Wordpress) not in edit and not in presentation. Personally I cannot think of any reason a comment should have a title.

Also, I would suggest comments to have no title for the following reasons:
1. Title looks ugly (in my eyes) when the comment is just a line. You see a line as a title and exactly the same line underneath. So you see the same line twice. How clever and nice is this?
2. Having the same line twice is bad for SEO
3. Database is filled with useless and redundant information (why should we store an autogenerated title?)
4. We confuse people when asking for a comment title. We just add complexity and difficulty to comment posting.
4. We add extra complexity to the admins that want to remove them from presentation. Tpl file should be modified plus css... etc.

I'm aware that there is an option to autogenerate comment titles during comment posting but this is inadequate
![image](https://user-images.githubusercontent.com/9040042/109122058-b99b8c00-7750-11eb-99de-8be22bcc5c4e.png)

**Proposed solution**
Ideally the system should allow having or not having comment titles at all. By this I mean that the checkbox shown in the screenshot above should not only hide the title field from comment editing but also hide it from presentation too and also eliminate autogeneration title and storing it to the database in order to save space!
In order to not break backward compatibility, the title field could remain but we could just keep it empty when storing a comment instead of autogenerating the title. Even better we could have an option to save an autogenerated title to the database or leave it empty.

UPDATE: Unfortunately I discovered this issue here after posting mine https://github.com/backdrop/backdrop-issues/issues/4569
And also found that there is this module to hide the title https://backdropcms.org/project/comment_hide_subject but this should be moved to the core.

So what is my issue here proposing differently than previous suggestions?: Not storing the title in the database if not necessary.
If you think this could have a point to reduce database size and complexity we can discuss further.

**Comment by alanmels** [comment] 2021-02-25 22:44
See also #4413 and #4569

**Comment by BWPanda** [comment] 2022-06-16 10:58
I'm going to close this as a duplicate of  https://github.com/backdrop/backdrop-issues/issues/4569 since there is much more discussion happening there.

**Closed by BWPanda** 2022-06-16 10:58 UTC
Labels: status - duplicate
