### ISSUE TITLE
[UX] Generate warning/error message when embedding an iframe into a layout area that is too small

### ISSUE THREAD

**Issue by ColumbiaBlooms** [backdrop/backdrop-issues#2612] opened 2017-04-03 12:45 UTC
When embedding the Google Calendar iframe into the body of an article content type not all the buttons are functional unless the body is in a one column section of the layout or in a layout with only one column. 

Please explain why Backdrop behaves in this manner.

This may apply to all iframes ...

**Comment by olafgrabienski** [comment] 2017-04-03 13:38
@ColumbiaBlooms To reproduce the issue, can you provide the iFrame code and tell which theme you use and if it happens in other themes as well?

**Comment by ColumbiaBlooms** [comment] 2017-04-03 23:01
`<p><iframe frameborder="0" height="700" scrolling="no" src="https://calendar.google.com/calendar/embed?showTz=0&amp;height=1200&amp;wkst=1&amp;bgcolor=%2333cc00&amp;src=sj4l0jipgcndgd0v2j9irag10o%40group.calendar.google.com&amp;color=%23875509&amp;ctz=America%2FChicago" style="border-width:0" width="900"></iframe></p>`

I'm using the basicolor theme. This also happens in the basis and Summer Fun themes. Please let me know if you need more information.

**Comment by olafgrabienski** [comment] 2017-04-04 16:42
That's very interesting: I tested the code with two Backdrop sites and a Drupal 7 site, all more or less vanilla installations and with the Full HTML format untouched. The iFrame was there but without content!

To reproduce the issue, I simplified the iframe code a bit ...

`<iframe height="600" src="MY-URL" width="100%"></iframe>`

... and got still no iframed content.

As a next step, I tried a local path ...

<iframe height="600" src="/contact" width="100%"></iframe>

... and that worked fine.

Finally I tried different external URLs:

```
google.com:
<iframe height="600" src="http://www.google.com" width="100%"></iframe>
example.com:
<iframe height="600" src="http://www.example.com" width="100%"></iframe>
backdropcms.org:
<iframe height="600" src="https://backdropcms.org" width="100%"></iframe>
```

The Google site didn't showed up in the iframe, but the others did. Seems that there ain't no general problem with Backdrop and iframes but with some external URLs. I guess some site owners or webhosters or applications try to block iframes. Didn't hear of it before, searched for it and found for instance http://stackoverflow.com/questions/8284217/iframe-and-external-website.

Has anybody experienced similar issues?

**Comment by ColumbiaBlooms** [comment] 2017-04-05 12:27
Looks like we have two issues here. 

1. The Google Calendar buttons on the right are not functional unless one is using a one-column layout, thus the title of this issue.

2. For some URLs in the iFrame nothing is displayed on the page at all.

Maybe there's a single solution to both problems?

**Comment by olafgrabienski** [comment] 2017-04-05 15:03
> Maybe there's a single solution to both problems?

Don't know, but at the moment I can't reproduce the original issue because on my test sites the calendar doesn't show up at all, neither in a two-column nor in a one-column layout!

That's why I tested iframes more generally, with the results described above. Would be nice if some other person could try to reproduce the original issue (two vs. one column).

@ColumbiaBlooms Does the calendar still show up in your environment on a one column layout? Do I maybe need an API key or something to see the calendar?

**Comment by Graham-72** [comment] 2017-04-05 15:36
@ColumbiaBlooms I'm having a look at this (after a short break away) and cannot reproduce this problem, but I am wondering how you were placing your calendar iframe in the side column. Having checked that your calendar iframe still works as main content, I have changed my default layout (using Basis) to be 'Sutro' which has 50:50 columns. I created a custom block containing your calendar iframe and then through layouts added this block in the 'half first' then 'half second' regions of Sutro, and its tabs work in either, in fact both if the custom block is placed in both.

Please explain how you are placing your calendar iframe on a page i.e. how you are using layouts in this situation. I will then try to reproduce the problem on my test site.

**Comment by ColumbiaBlooms** [comment] 2017-04-05 23:44
I created a layout called Google Calendar using the Boxton layout. Path is set to article/calendar. There are no visibility conditions set. In the content section of the layout is an existing content block set to Displays content of node ID: 525. I'm not sure how this Displays content got set, but it works. In the list of all layouts the Google Calendar layout is at the top. I didn't notice this before, but the right side of the "agenda" button and the drop down arrow to the right of agenda does not work. I guess I forgot to check this earlier. Sorry about that.

This is weird ... Now I can't seem to make it not work! Except for the right side of the agenda button and the drop down arrow button not working all seems OK. I'll have to find a previous backup when it didn't work. I thought by changing the template to Moscone (that's what my home page uses) that the problem I was having would be recreated, but no luck. I'll post again when I find a backup of my site with the original problem.

At this point I'm wondering if I'm going crazy or maybe all this has something to do with the size of my browser window and/or using F12. Or maybe it's just Gremlins!

**Comment by klonos** [comment] 2017-04-06 00:33
>Or maybe it's just Gremlins!

I tend to blame them all the time 😄 ...not all of them though; Gizmo was nice.

**Comment by Graham-72** [comment] 2017-04-06 06:01
@ColumbiaBlooms the down arrow to the right of 'agenda' reveals the name of the calendar so that if the viewer is entitled to view more than one they can select one here. When I view your calendar iFrame on my test page the arrow does not work but I get this warning in the calendar header
![test page 2 oliverhosting](https://cloud.githubusercontent.com/assets/10559274/24739858/08972eca-1a96-11e7-925d-06d181935edc.png)

When looking at a calendar to which I do have access permission the down arrow shows the name
![calendar deben rowing club](https://cloud.githubusercontent.com/assets/10559274/24739900/41b7facc-1a96-11e7-975d-e5fd20c34ad1.png)

**Comment by olafgrabienski** [comment] 2017-04-06 12:20
@ColumbiaBlooms Strange: I'm even not able to see the calendar in the browser when I put the code from https://github.com/backdrop/backdrop-issues/issues/2612#issuecomment-291303326 in a local static HTML file. Is the calendar still there and public?

I tested the issue however with an own calendar which works, no matter if in a 1 column or in a 2-columns layout.

I had one issue though using the Basic theme: the height of the iframe is not respected, I guess because of `height: auto;` in the following rule in `base.css`:

```
iframe, img {
    height: auto;
    max-width: 100%;
}
```

**Comment by Graham-72** [comment] 2017-04-06 13:03
@olafgrabienski Yes, please see issue raised for Basicolor https://github.com/backdrop-contrib/basicolor/issues/8, though it seems it should really be an issue for Basis in core.

**Comment by ColumbiaBlooms** [comment] 2017-04-06 13:05
@Graham-72 Thanks for the explanation of the down arrow on the right.

@olafgrabienski My calendar is still there. Maybe Gremlins have attacked you as well ... ! 

Yes, height: auto; in base.css causes the calendar to be squashed. I added this `iframe {
height: 500px;
max-width: 1500px;
}`
at the bottom of styles.css in basicolor (the theme I'm using). I need to make a sub-theme instead, but have not had the time to get to it. 

@Graham-72 Regarding your previous post ... I restored a backup and the problem of all right side buttons has returned. It must be something in the layout that causes this. In this restored backup I have a new layout called Node layout that's listed just after Home Page in the layouts list. It's path is Node/% and the template is Sutro. There are no visibility conditions set. Hopefully you can recreate this on your machine. If you need more information please let me know.

**Comment by Graham-72** [comment] 2017-04-06 13:57
@ColumbiaBlooms if you look at the 'Manage Blocks' page for your layout 'Node layout' (using Sutro) is there anything other than 'Main page content' showing in the 'Content' region? I presume not. Also, is there anything in either of the regions 'Half first' and 'Half second'. I need to know this to be sure to set my test exactly as yours is set.

**Comment by ColumbiaBlooms** [comment] 2017-04-06 15:39
@Graham-72 Yes. There is other stuff in the Content region. I've attached an image of the manage blocks page. This is stuff that was migrated from my D7 site that I've not yet implemented in the Backdrop version of my site. As you can see from the attached image there is stuff in the Half first & Half second sections. I'm not sure where the stuff in these two sections came from. (I get myself so spread out working on more than one thing at a time that I sometimes forget how or why I did something! I guess this happens because I'm so old!!)

![screencapture-localhost-8080-bd-admin-structure-layouts-manage-node-1491492866383](https://cloud.githubusercontent.com/assets/12977583/24762683/b1a89cc4-1ab4-11e7-9771-8f4637bee65c.png)

**Comment by Graham-72** [comment] 2017-04-06 16:39
@ColumbiaBlooms did you create this 'Node layout' especially for your calendar? I think it might be best if you were to try a dedicated layout just for your calendar page and remove all the other custom blocks, so that initially you only have the calendar set to appear i.e on the 'configure layout' page for this new layout you set the path to be node/N where N is the nid of your calendar node. From your settings it looks as though the body is set to appear in 'Half first' which is a bit odd. If on the 'manage blocks' page you select 'add block' for the 'content' region you might be given the opportunity to add 'Main page content' into the content region. Maybe your site has inherited some strange settings in the upgrade from Drupal.

**Comment by olafgrabienski** [comment] 2017-04-06 21:09
@Graham-72 New core issue regarding the iframe height: #2622

**Comment by ColumbiaBlooms** [comment] 2017-04-06 21:54
@Graham-72 Thanks so much for you comments and help and to @olafgrabienski for creating a new core issue for iframe height.

I actually cleaned things up quite a bit in the current version of my site. I did just as you recommended. I created a layout just for the calendar. It works fine. The image I posted is from an earlier version of my site before I knew what I now know.

Thanks, again, to everyone on the team for doing such a wonderful job of support!

**Comment by ColumbiaBlooms** [comment] 2017-04-06 21:55
So ... back to the title of this issue. Where are we with generating a warning message of some sort when a novice like me embeds an iframe that behaves not as expected?

**Comment by Graham-72** [comment] 2017-04-07 06:39
@ColumbiaBlooms I'm glad to have been of some help and it's good that you brought this iframe height issue to our attention. However, I am not sure about the need for this warning message. From my testing it looks to me as though an iframe will be displayed even if the width is less than intended. Most of the Google Calendar is responsive, shrinking to fit the space available, with the exception of that line of controls and tabs which is getting cropped at smaller widths. I think maybe with your work on layout you have resolved the problem that caused you to create this issue?

**Comment by ColumbiaBlooms** [comment] 2017-04-07 13:50
I think I'm still a bit confused about how layouts & blocks work. In my layout for Google Calendar (see image below) I have a content section with no blocks. How does the iframe find its way into the content section? What's happening here?


![screencapture-localhost-8080-bd-admin-structure-layouts-manage-google_calendar-1491572212823](https://cloud.githubusercontent.com/assets/12977583/24802561/0a99cfc4-1b6e-11e7-9ea7-b0aca654282a.png)

**Comment by Graham-72** [comment] 2017-04-07 15:25
@ColumbiaBlooms yes this is a difficult one and there does not seem to be a way of seeing exactly which layout is in action for a page, even by inspecting the code. From what you can see here there is no evidence that this is the layout being used for your calendar, except perhaps for the (article/calendar) in the heading, but that might be a statement of intention rather than what is actually happening.
When things are working normally one would see the words 'Main page content' appear in a region, normally 'Content' but that is not happening here.
Two possibilities occur to me:
1. By inspecting the code around your iframe you will see from the classes assigned to the divs where your iframe is located in the layout, though the class names do not necessarily tie in closely with region names, so one needs to work out how the layout is translated into classes.
2. You might temporarily assign an existing custom block to one of the regions in that layout and see whether it then appears alongside/above/below your calendar. If it does, then the layout is doing what is intended.
If you can find a better way I shall be very glad to hear it.

**Comment by ColumbiaBlooms** [comment] 2017-04-08 12:20
@Graham-72 Thanks so much for the debugging tip. I discovered that my new layout is ignore. The one that's used for my calendar is Default Layout. In its Content section there is "Main page content". When I go to my Calendar Layout to add this block to the Content section "Main page content" does not appear in the drop down list of available blocks. 

Is Main page content some kind of special block that's used only in the Default Layout? What block should I choose to mimic Main page content on my calendar layout?

BTW, what does the "Storage State" column in the layouts list mean? I see custom, overridden, and "default (module provided).

**Comment by Graham-72** [comment] 2017-04-08 14:34
@ColumbiaBlooms I think the reason that no 'Main page content' is showing as an option for your Calendar Layout must be that you do not yet have the right Visibility Condition set for this layout.

Please look at your admin page structure/layouts/list layouts. Hopefully in the column headed 'Paths and Layouts' you can see your 'Calendar Layout' listed. Does this have an entry in the column headed 'Visibility Conditions'? It might be something like 'Current path is "node/N"' where N is the node ID of your Calendar page (or post). [I usually find out the NID of a page from the URL that appears for its edit link.]

If it does not yet have this Visibility Condition you must set it by going to the 'Configure Layout' page - use the drop-down selector in the RH column headed 'Operations'.
On the Configure Layout page towards the bottom first make sure that the entry for Path is node/%, then below that you will see 'Visibility Conditions', here you select 'Add visibility condition' and on the form that appears select the option 'Node: NID' for the visibility condition. Then enter the NID for your calendar.
Having done all this and saved these settings, the layout system will no longer display your Calendar using the Default Layout but will use your special Calendar Layout.

I am sure there are other ways to set this up, I am just describing the one I use, sometimes with several values in the visibility conditions so that a custom layout is used for several nodes.

The 'Storage State' column on the layouts page tells something about the origin of each layout. This might be 'Custom', 'Default', 'Overridden' or 'Default (Module provided)'. 'Overridden' seems to mean that it is a modified version now used as the Default.

Please feel free to ask any more questions.

**Comment by ColumbiaBlooms** [comment] 2017-04-09 22:24
@Graham-72 Thanks so much. I think I'm finally beginning to understand how this works ...

I updated the Google Calendar layout per your instructions and it worked! I created a new layout called General Node with the Moscone Flipped template, but without Visibility Conditions. (I want most of my pages to have text on the left and an image on the right.)

I did some testing of the calendar layout. I changed the template to Rolph. I expected the iframe to be squished somehow or the buttons on the right not to work, but the buttons work and the calendar looks OK. I don't quite understand why it works like this. I thought the point of this exercise was to make a special layout for Google Calendar so that all the buttons work. Is this behavior due to this code 
`iframe {
height: 500px;
max-width: 1500px;
}`

at the bottom of C:\xampp\htdocs\BD\themes\basicolor\css\styles.css?

**Comment by Graham-72** [comment] 2017-04-10 15:01
@ColumbiaBlooms it seems you are making good progress with this. I think the problem with the buttons was caused by something wrong with the initial layout you were using, which was the reason for suggesting you create a new layout specifically for your calendar page. 

Now you have this working I am not surprised to hear that other options work, though I don't know why you were experiencing problems with the buttons, maybe a clash of style settings. It was clearly a problem having Basis set the iframe height as auto, and not just with the Google Calendar iframe. The situation is probably made more complicated because Basis uses Flexbox (and I'm very glad that it does.)

**Comment by ColumbiaBlooms** [comment] 2017-04-11 14:34
Thanks to everyone for helping me understand what's going on and for solving this problem!

**Closed** 2017-04-11 14:40 UTC
Labels: status - needs feedback
