### ISSUE TITLE
[D8][A11Y] ALT attributes should be enabled by default on new fields and have an option to set ALT as required

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3006] opened 2018-03-21 16:29 UTC
## Describe your issue or idea

I want to make ALT tags on images required. There is [a module](https://www.drupal.org/project/eim) I could port but I think this should probably be in core and active as a default for new image fields. Side note: I also see that [D8 has this in core](https://www.drupal.org/project/drupal/issues/2303765):

![screen shot 2018-06-22 at 9 36 02 am](https://user-images.githubusercontent.com/2423362/41750502-b7bcf9e6-75ff-11e8-8537-80e911889eac.png)

From that D8 issue:

> Alternative attribute text is required for images to ensure a site meets WCAG accessibility guidelines. When adding an image field to a content type, the alt text field is currently optional meaning Drupal sites often fail accessibility audits until alt text is added to images.

> Note: This issue does not relate to images added via CKeditor. It relates to changing the default setting on the image field to require the alt attribute.

**Comment by laryn** [comment] 2018-03-21 16:41
I think I will port the module for now but hopefully long-term this gets in core.

**Comment by jenlampton** [comment] 2018-03-26 20:14
I've been thinking the same thing recently. ALT tags should at the very least, be enabled by default. Making them required might be going a bit too far in terms of generating end-user-frustration, but it would help to create a more accessible internet!

**Comment by laryn** [comment] 2018-03-26 20:49
I don't think we'd set this retroactively on existing fields, so it would just be when adding a new field. Do you think it goes to far to set 'required' on new fields (with the option to uncheck during field creation/edit if they really want to)?

**Comment by jenlampton** [comment] 2018-03-26 22:03
I don't know how to measure frustrated-more-sighted-users vs happy-less-sighted-users. :/

**Comment by olafgrabienski** [comment] 2018-03-27 09:04
> set 'required' on new fields (with the option to uncheck during field creation/edit) ...

Just perfect, in my opinion: It's a reasonable default, with the freedom to decide otherwise.

**Comment by findlabnet** [comment] 2018-03-27 10:19
I think tag should be enabled by default, but not as required field. If this field left blank - show message to author (when saving) and add to HTML `alt=""` as if the image is only for decoration.

**Comment by jenlampton** [comment] 2018-03-27 17:55
What if we made it enabled by default in 1.10, and required by default in 1.11. to ease people into using it?

**Comment by BWPanda** [comment] 2018-04-21 16:40
As long as I can disable the required function, I'm happy.

**Comment by findlabnet** [comment] 2018-04-21 16:53
> But would that make the system too verbose?

We can just add to field description note about such behavior - if field left blank, tag with empty value will be added to HTML.

**Comment by olafgrabienski** [comment] 2018-04-22 14:51
> We could add a yellow warning message on save (...) recommending that ALT text be added to images.

In my opinion, a yellow warning is too strong. Persons may have reasons to not use the ALT text, and when they see always a warning then, it will be perceived as an unsolicited advice. I'd prefer @findlabnet's idea of a good field description and adding `alt=""` if the ALT text is empty.

**Comment by klonos** [comment] 2018-06-22 01:33
> Making them (alt tags/text) required might be going a bit too far in terms of generating end-user-frustration, but it would help to create a more accessible internet!

I agree with this, but not with the "might" bit; it will **certainly** add frustration.

>> set 'required' on new fields (with the option to uncheck during field creation/edit) ...
>
>Just perfect, in my opinion: It's a reasonable default, with the freedom to decide otherwise.
...
>As long as I can disable the required function, I'm happy.

I second that as a compromise. But would rather we were less "strict" or at least explain why to users. So I think:

a) We should be offering a way to require alt (and title) and I would prefer if that was in core.
b) The default should be to **not** required.
c) We should be offering the required option on a per-field basis, but also per-editor/format if possible (to compliment the new work done over in #3134)

>>show message to author (when saving)
>
>We could add a yellow warning message on save, along with the green info message `This post has been saved`, recommending that ALT text be added to images. But would that make the system too verbose?

I sorta agree with this, BUT my thought process is this: If we make the alt text required, we'll be having whythehelldoIhaveto kind of frustration; while if we (only) show a message **after** the content is saved, we'll have ohmanwhydidntyousaythatwhenIwascreatingthebloodything frustration. Either that (in the cases where the users do re-edit to add the alt text), or ohwellyoushouldhavesaidsomethingbefore-Icouldntcareless-cantbebotherednow reactions. That's why I think it would be best if we (perhaps **additionally** to adding the warning when no alt text has been added):

d) *endorse* instead of *enforce*... as I said on Gitter, I was thinking some bold/red help text under the alt field along the lines of "This is optional, but please be considerate of people not able to see images and provide some descriptive text here."

**Comment by jenlampton** [comment] 2018-06-22 02:37
I like all these suggestions :)

**Comment by jlfranklin** [comment] 2018-07-15 12:36
I think it is fine to leave it disabled by default.  We can create a module that enables several accessiblity best practices, and turning alt tags on by default would be hook_form_alter() #1.

**Comment by herbdool** [comment] 2021-06-01 19:11
I've got a PR https://github.com/backdrop/backdrop/pull/3640. It still needs some changes but it works for image fields and for uploading images in the editor.

- [ ] automated tests
- [ ] ensure it works with Insert module? (eim module does but I simplified it)
- [ ] add update hook to ensure no undefined variables with new settings

**Comment by herbdool** [comment] 2021-06-01 19:22
My simplified version does work with Insert. Maybe not the same way EIM does it, but I think it makes sense. It still allows an Insert to insert an image into the editor if the alt isn't filled in yet, but I think that's a better job for Insert (or EIM) to solve.

**Comment by herbdool** [comment] 2021-06-01 19:50
One issue I noticed is the image dialog in the editor can't handle a field being required:

![Screenshot from 2021-06-01 15-46-42](https://user-images.githubusercontent.com/1071483/120381783-e1bafe00-c2f0-11eb-8bfe-08c6d3be9aa4.png)

**Comment by herbdool** [comment] 2021-06-01 21:04
The image dialog might be a more general issue. I couldn't get anything else in the image dialog to trigger an error so couldn't confirm but I suspect that it doesn't handle any form errors well.

**Comment by herbdool** [comment] 2021-06-01 21:06
Okay got it trigger a different error. As suspected it gets messed up with any error in the dialog.

![Screenshot from 2021-06-01 17-06-04](https://user-images.githubusercontent.com/1071483/120390478-be498080-c2fb-11eb-868f-393ea61d0d43.png)

**Comment by jenlampton** [comment] 2021-06-02 00:45
> the image dialog in the editor can't handle a field being required:

I can't tell from the screenshots what the problem is in the modal. It looks like the required fields are properly failing validation when empty?

**Comment by herbdool** [comment] 2021-06-02 04:58
@jenlampton the set of tabs is showing up twice

**Comment by indigoxela** [comment] 2021-06-02 06:12
I can confirm the double tabs when the error is triggered in the dialog, so this still needs some work.
Besides that the PR seems to be working fine.

**Comment by herbdool** [comment] 2021-06-02 11:35
@indigoxela I actually think that bug should be a separate issue. See my screenshot above where I triggered the bug with any error message. So this PR didn't create the bug per se.

**Comment by indigoxela** [comment] 2021-06-02 11:53
> I actually think that bug should be a separate issue. See my screenshot above where I triggered the bug with any error message. So this PR didn't create the bug per se.

If that were the case, I'd be fine with that, too. - But I can't reproduce it on a clean install. Whatever I do to trigger an error (wrong file type upload, non-existent or empty url, ...) - no tab duplication caused by form errors.

I can only reproduce it in the sandbox. So, to my understanding, this *is* a newly introduced problem.

**Comment by indigoxela** [comment] 2021-06-02 11:56
UPDATE: wait, now I found a way to trigger errors, that actually duplicates the tabs. Back to needs code review. :smile:

**Comment by herbdool** [comment] 2021-06-02 14:27
@indigoxela thanks for creating the new issue.

What I gathered from reviewing the comments above was that on *new* fields make ALT attributes enabled by default and make required an option (though some preferred required be enabled when first creating new fields).

**Comment by indigoxela** [comment] 2021-06-02 14:34
> What I gathered from reviewing the comments above was that on new fields make ALT attributes enabled by default and make required an option

Maybe you want to update the issue title, to make that clearer? (I thought the new title fits, but maybe it's still misleading.)

**Comment by olafgrabienski** [comment] 2021-06-03 12:00
For reference, this is the new help text for the "*Alt* field required" option:

> Requiring alternative text is strongly encouraged to improve accessibility for all users.

I agree with the direction but it doesn't cover the rare cases where an alt attribute doesn't improve accessibility at all (e.g. decorative images). What about something like this?

> More often than not, requiring alternative text is strongly encouraged to improve accessibility for all users.

**Comment by olafgrabienski** [comment] 2021-06-03 12:03
> I lean a bit to also enabling the alt_field_required on new fields, but I'll see what others think.

Hm, several people above already said they didn't want "alt" required by default. Do you have new thoughts about this question?

**Comment by herbdool** [comment] 2021-06-03 14:24
@olafgrabienski thanks. I hadn't thought about decorative images. Just reading up on it here: https://webaim.org/techniques/alttext. Your sentence helps, though I'm wondering: would help to be more specific or is that too much information?

**Comment by herbdool** [comment] 2021-06-11 19:21
@olafgrabienski maybe the wording is fine. I was just editing an image field in Drupal 9 And it looks like:

![Screenshot from 2021-06-11 15-18-23](https://user-images.githubusercontent.com/1071483/121738575-5f88c180-cac8-11eb-8fc2-1b8a93aadc44.png)

I noticed the description for the Title field. It actually recommends *not* enabling it for screen readers. Plus Drupal 8/9 makes the "Alt field required" option enabled by default.

**Comment by olafgrabienski** [comment] 2021-06-14 09:40
> maybe the wording is fine

Okay! For me it's hard to say, as I'm not a native English speaker, but if nobody objects ...

Re "Alt field required" in Drupal 8/9, that was already mentioned in the issue description, so shouldn't change anything in my opinion.

Regarding the Title field description, are you considering to drop the option to make title fields required or do you suggest to change the text for Backdrop?

**Comment by herbdool** [comment] 2021-06-18 18:51
@olafgrabienski I was wondering if we add a similar description for Title: "The title attribute is used as a tooltip when the mouse hovers over the image. Enabling this field is not recommended as it can cause problems with screen readers."

**Comment by klonos** [comment] 2021-06-19 17:46
@herbdool yes please 👍🏼 ...although please also add a comma there: `... not recommended, as it can ...`.

**Comment by olafgrabienski** [comment] 2021-06-20 15:04
@herbdool Thanks for the feedback! I'm sort of undecided about the title field (non-)recommendation because I don't know much about the question, but the warning seems to be right for must use-cases, so I'd be fine with it.

**Comment by herbdool** [comment] 2021-08-12 14:16
I finally made the small change to the title attribute description. @klonos or @olafgrabienski wish to test and RTBC?

**Comment by jenlampton** [comment] 2021-08-12 17:12
The PR looks great, I left two comments on the PR that can be addressed in follow ups if necessary.

**Comment by olafgrabienski** [comment] 2021-08-13 07:37
@herbdool Sure, tested in the PR sandbox, works for me!

**Comment by olafgrabienski** [comment] 2021-08-13 07:39
RTBCed as well, based on [Jen's comment](https://github.com/backdrop/backdrop-issues/issues/3006#issuecomment-897815438).

**Comment by BWPanda** [comment] 2021-09-15 11:57
Removing the RTBC label as @jenlampton left a review of the PR with suggestions that haven't been addressed yet. She mentioned a possible follow-up issue, but why go to the trouble if they can be addressed now...?

**Comment by klonos** [comment] 2021-09-15 12:18
Both suggestions are tiny fixes, and the core committer that reviews could add them before they merge. Having said that, @herbdool are you around to implement the changes?

**Comment by BWPanda** [comment] 2021-09-15 12:27
I've never quite understood how to easily make small changes before merging a PR... Could someone please enlighten me? I normally just press the 'Squash and merge' button in GitHub.

**Comment by klonos** [comment] 2021-09-15 14:39
@BWPanda I thought that people with write access to the backdrop/backdrop repo can merge code suggestions (added as comments in the PR either by others, or by the person about to merge). I've converted @jenlampton's comments into code suggestion comments. Can you see if there's a "merge" button in each one of them @BWPanda?

**Comment by laryn** [comment] 2021-09-15 14:44
I think @klonos suggestion will work, or I discovered recently that core committers can actually push commits to the branch/PR of the forked repo (if the "allow changes..." box was checked when submitting the PR, I think) -- but that's from the command line, not in the GUI.

**Comment by klonos** [comment] 2021-09-15 14:54
> if the "allow changes..." box was checked when submitting the PR, I think

Right. That could be the case. Not sure if that's the default or not, but I always leave that checkbox ticked in my PRs.

**Comment by jenlampton** [comment] 2021-09-15 20:06
oops, I merged @klonos's suggested changes into the PR thinking it was mine for some reason, and I don't see an un-merge option :( I'll see myself out...

**Comment by laryn** [comment] 2023-01-25 22:16
Adding back RTBC because it looks like the suggestions were incorporated, and also adding a milestone.

**Comment by klonos** [comment] 2023-01-26 02:56
@laryn I've left a comment in the PR re using a float (`.1`) for `#weight` in a couple of places. Not sure if that was intentional or not, but if it was, then can someone please explain?

Also, since the last commit in the PR was from back in September 2021, @herbdool can we please rebase to have it run through PHPCS and PHP8 tests? (and to get the PR sandbox going for a final round of testing/review as well).

In the meantime, I'll set this up on my local and test there.

PS (and note to self): There have been some nice suggestions in this thread over the course of the years. We should file follow-up issues.

**Comment by keiserjb** [comment] 2023-01-27 16:08
I'm seeing a major difference between the contrib EIM module and the PR.

When using EIM I see that the field is required.
![image](https://user-images.githubusercontent.com/41843284/215133399-2ffb7b74-ab15-4ae2-bc1b-82ed4eb918b4.png)

When using the patch I get a different message.  Normally this isn't a problem but if I have an image field that allows multiple uploads I cannot add another image until the first one is saved.
![image](https://user-images.githubusercontent.com/41843284/215133901-a57b2409-a6e3-4276-89eb-11971da64c79.png)

**Comment by jenlampton** [comment] 2023-04-11 17:11
I just did a quick code review and I found only one instance of "users" in the help text that needs to be removed. 👍 

While reading the new help text it occurred to me: Using the title attribute on images is NOT recommended, and will actually make accessibility on sites worse. So why are we adding the ability for people to make their sites less accessible in a fix that's supposed to make sites more accessible?  It also seems like that's something that 80% of Backdrop sites will not want, and so that feature would fail the "should this go in core?" test on two counts.

I do know why we are including it: because it's the same mechanism to do so as for the alt field (and probably also because Drupal did it). The more important question is **should we** include that in core? I think the answer is "no".

**Comment by herbdool** [comment] 2023-04-12 03:59
The PR is ready again. It only has the ALT field required option, since we want to discourage people relying on title attribute for accessibility.

**Comment by keiserjb** [comment] 2023-04-20 18:33
I agree with only making the alt text required.  I'm using the pr on a production site.

**Comment by klonos** [comment] 2023-04-25 01:30
@herbdool I've left a comment in the PR re removing a final instance of "users" in the description text + to add `#indentation` to the dependent checkbox. Otherwise this LGTM 👍🏼

**Comment by herbdool** [comment] 2023-04-25 13:24
@klonos please review

**Comment by klonos** [comment] 2023-04-27 10:58
Thank you @herbdool ...LGTM 👍🏼

**Comment by quicksketch** [comment] 2023-05-01 02:48
This looks great! I posted a review with some suggestions, and we have a conflict with 1.x at the moment. https://github.com/backdrop/backdrop/pull/3640#pullrequestreview-1407299315

Very nice implementation! We should be able to get this into 1.25.0 for sure.

**Comment by herbdool** [comment] 2023-05-01 03:18
@quicksketch I'm happy to make changes but I won't be able to work on it tonight or tomorrow. Catching a flight tomorrow.

**Comment by klonos** [comment] 2023-05-01 16:53
I've started a draft PR based off of @herbdool's here: https://github.com/backdrop/backdrop/pull/4422

I've rebased, and started implementing the suggestions from the feedback from @quicksketch, but need to take a break for about 1hr or so. Hoping to get this in for 1.25.0.

**Comment by quicksketch** [comment] 2023-05-01 20:35
@klonos One test failed but it's just because the string changed from "The Alt field is required" to "The Alternative text field is required". I committed directly to the PR and we'll see if tests pass.

I'm a little sad to see the `#indentation` line commented out, but hopefully we'll fix that before release in https://github.com/backdrop/backdrop-issues/issues/6090. I wasn't actually seeing the problem in the first place.

**Comment by klonos** [comment] 2023-05-01 20:45
> ... I wasn't actually seeing the problem in the first place.

Yeah, it must have been something that we've merged into 1.x that regressed that. We have a couple of weeks ahead of us to fix things before the final release 😉

**Closed** 2023-05-01 21:08 UTC
Labels: type - feature request, status - has pull request, pr - needs code review, pr - works for me, needs - translation update

**Comment by quicksketch** [comment] 2023-05-01 21:10
All tests are passing now! I have merged https://github.com/backdrop/backdrop/pull/4422 into 1.x for 1.25.0. Long list of credits on this one! Thanks to @herbdool, @klonos, @laryn, @indigoxela,  @olafgrabienski, @jenlampton, @findlabnet, @BWPanda, @keiserjb, and @jlfranklin for your work making this happen!

**Comment by keiserjb** [comment] 2023-05-01 21:33
Thank you for getting this done.
