### ISSUE TITLE
"Add Existing Content" block doesn't respect the "Show author and date information" checkbox.

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#2536] opened 2017-02-13 17:38 UTC
Toggling the "Show author and date information" option does nothing from what I can see.

In Backdrop 1.6.0

----
~~PR: https://github.com/backdrop/backdrop/pull/2047~~
PR by @herbdool https://github.com/backdrop/backdrop/pull/2684

**Comment by Al-Rozhkov** [comment] 2017-05-02 09:46
I can confirm this bug. When I watch variables in hook_preprocess_node, `display_submitted` is not overwritten and `block` flag is set to false.

**Comment by olafgrabienski** [comment] 2017-12-13 12:05
I confirm the bug as well, it's still active in Backdrop 1.8.0.

As Rabbit Hole is being ported to fix [Add a system of page-less nodes](https://github.com/backdrop/backdrop-issues/issues/100) in contrib, there are new use cases for "Add existing content" blocks, and this bug will concern more sites in the future. @Al-Rozhkov are you still/again up to have look at the issue?

**Comment by Al-Rozhkov** [comment] 2017-12-13 21:14
Unfortunately I don't have time to work on this. Anybody can pick this up.

**Comment by serundeputy** [comment] 2017-12-14 00:40
Added PR to check for NodeBlock in `node_view()` and then check `display_submitted` from the block form.

Website: http://2047.backdrop.backdrop.qa.backdropcms.org
Username: admin
Password: Lci5EopL

**Comment by herbdool** [comment] 2017-12-14 01:50
@serundeputy works!

**Comment by serundeputy** [comment] 2017-12-14 20:10
Updated PR fixing test failures.

**Comment by quicksketch** [comment] 2017-12-21 20:45
The PR looks like it would work but it's mixing the data model (the `$node` object) with the display information (by setting `$node->display_submitted`). It shouldn't matter where the node is being rendered, the `$node` object should always just contain the node data. Instead we should be passing a variable to `theme('node')`, or in our case because this is a renderable, as `$content['#display_submitted'] = TRUE;`

We're already doing this, but it looks like this value might be getting wiped out in `template_preprocess_node()`. Could you take another look at this @serundeputy?

**Comment by herbdool** [comment] 2019-05-16 17:38
The issue was that it was assuming the node was using a view_mode == "block" when actually the user can set it to anything. I've come up with a small PR https://github.com/backdrop/backdrop/pull/2684. Maybe @olafgrabienski you feel like testing? Thanks!

**Comment by olafgrabienski** [comment] 2019-05-17 09:35
@herbdool Thanks for the new PR! It's working in the sandbox site, test page: http://2684.backdrop.backdrop.qa.backdropcms.org/about.

**Comment by herbdool** [comment] 2019-05-17 13:21
PR approved by @serundeputy

**Comment by quicksketch** [comment] 2019-05-23 18:21
Looks great! Nice and simple. Merged https://github.com/backdrop/backdrop/pull/2684 into 1.x and 1.13.x.

**Closed by quicksketch** 2019-05-23 18:21 UTC
Labels: status - has pull request, status - fixed
