### ISSUE TITLE
Add admin title / description for pre-made blocks such as hero or menu for layout UI

### ISSUE THREAD

**Issue by Egarbeil** [backdrop/backdrop-issues#4325] opened 2020-03-01 15:50 UTC
There is no admin title for non-custom blocks when adding to a layout, so there can be multiple blocks with the same name in the layout UI and no easy way to distinguish between them.

Example:  Hero blocks showing at the top in different sections of the site (limited by visibility).  If there are 4 blocks for 4 sections of the site, there is no way to distinguish between the blocks if block title is not used.  Let's say the user want to make a change to one of the hero blocks, they have no way to easily distinguish which block to make the change.  This creates frustration for the user.

In the case where I discovered the issue,  it was for a school site with 8 different departments.  Each department wanted to have and be able to update their own header (hero) block.  They needed to be able to determine easily which block was theirs.

**Comment by indigoxela** [comment] 2020-03-02 08:10
@Egarbeil many thanks for creating this issue. That was something that also came to my mind from time to time. Especially when there are multiple blocks of same type in a region, which have visibility conditions.

In this case an admin label would be very helpful. Like "Block description" in D7.

Maybe someone of the core team knows, why blocks in Backdrop don't have an admin label. Were there objections?

**Comment by BWPanda** [comment] 2020-08-21 03:46
Closing as duplicate of the more general https://github.com/backdrop/backdrop-issues/issues/4558

**Closed by BWPanda** 2020-08-21 03:46 UTC
Labels: needs - more feedback, type - feature request
