### ISSUE TITLE
Admin Bar CSS has incorrect height

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#1845] opened 2016-05-08 20:35 UTC
![image](https://cloud.githubusercontent.com/assets/5607236/15100257/e6473e2a-153a-11e6-9239-43d54d18d837.png)

Currently the stylesheet thinks it's 33px

**Comment by wesruv** [comment] 2016-05-08 20:37
PR Here: https://github.com/backdrop/backdrop/pull/1363

**Comment by dboulet** [comment] 2016-05-08 21:49
It should be 33px in height. Maybe the theme you are using is inadvertently affecting the admin bar height?

![screen shot 2016-05-08 at 4 45 42 pm](https://cloud.githubusercontent.com/assets/208615/15100629/aeecedce-153c-11e6-9a97-d7b688631d8b.png)

**Comment by klonos** [comment] 2016-05-08 22:57
For me (firefox x64 nightlies) the `#admin-bar-wrapper` div consistently shows at 33,4px. The only rule that is applied directly to it from admin_bar.css is `overflow: hidden;` and then these are inherited from the `#admin-bar` div:

```
    font: normal 11px "Lucida Grande", Verdana, sans-serif;
    text-align: left;
    line-height: 1;
```

There is no `top` rule unless you inspect the `#admin-bar` div (also rendered at 33.4px) and that is set to 0.

**Comment by wesruv** [comment] 2016-05-09 23:56
Blarg! I'll have to look into it. Thanks for the feedback

**Comment by BWPanda** [comment] 2020-08-11 05:19
Closing as cannot reproduce.

**Closed by BWPanda** 2020-08-11 05:19 UTC
Labels: status - has pull request, status - cannot reproduce
