### ISSUE TITLE
[UX] Make sure the columns in the modules page have equal width between categories.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#501] opened 2014-12-22 21:23 UTC
It would be "easier" on our eyes while scrolling this long list...

![modules_page-not_equal_widths-narrow](https://cloud.githubusercontent.com/assets/2423362/5531187/e6b24084-8a7c-11e4-88fa-fb9654604d52.png)
![modules_page-not_equal_widths-wide](https://cloud.githubusercontent.com/assets/2423362/5531188/e6d373a8-8a7c-11e4-889e-212f3d7777ad.png)

**Comment by jenlampton** [comment] 2015-01-02 03:09
I love these recommendations. :) To make the enabled column narrower, how would you feel about having modules be "off" and "on" instead of "enabled" and "disabled" ?

**Comment by klonos** [comment] 2015-01-04 05:29
I personally do not mind on/off instead of enabled/disable, but what actually makes the "Enabled" column as wide as it is is its title/heading. Changing the "Enabled" heading to something like "on/off" saves us a couple of characters, but would not make that much of a difference. If we choose to go that way, I prefer "Status" as a heading. It makes more sense to me.

**Comment by klonos** [comment] 2015-01-04 05:40
...on second thought, would it make any sense to remove the "Enabled" column altogether and replace the "on/off" checkboxes with a "enable/disable" AJAX operation?

That would save us the whole width since for disabled modules the checkbox would be moved as a "enable" operation button in the already existing "Operations" column. For enabled modules, the "disable" operation would be "merged" with the drop-button as with any other module that has multiple operations available ("configure", "permissions").

**Comment by quicksketch** [comment] 2015-01-04 06:31
> ...on second thought, would it make any sense to remove the "Enabled" column altogether and replace the "on/off" checkboxes with a "enable/disable" AJAX operation?

I think this may have a negative user experience impact. Every module enable/disable requires a full cache flush. On many sites I work on, enabling a module may take 10-20 seconds. If you need to turn on 6 modules, that's going to be a frustrating experience waiting for each AJAX request to finish before you can enable the next module.

> Changing the "Enabled" heading to something like "on/off" saves us a couple of characters, but would not make that much of a difference.

Good point here. Unless we renamed the column header to just "On", it wouldn't save hardly any space, and "On" just isn't an adequate descriptor.

**Comment by klonos** [comment] 2015-01-04 07:05
Fair enough about the long time and thus bad UX to enable/disable using AJAX. I was just brainstorming.

How about if the "enable"/"disable" operations simply "stacked" modules for the respective action + it invoked a "dirty" flag? Then we could use the same mechanism that prompts the user to save before changes take effect like we do in views. As an added visual indication/effect we could have disabled modules name/version/description be grayed out and enabled ones be normal.

So, hitting the "enable" button on disabled/grayed out modules would:

- [UI] "light up" the module font
- [UI] turn the "enable" button text to "disable"
- [back end] queue the module for enabling
- [back end] set a "dirty" flag for the modules page
- [UI] fire a "All changes are stored temporarily. Click Save to make your changes permanent." message

...and similarly hitting the "disable" action for enabled modules would:

- [UI] "dim" the module font
- [UI] turn the "disable" button text to "enable"
- [back end] queue the module for disabling
- [back end] set a "dirty" flag for the modules page
- [UI] fire a "All changes are stored temporarily. Click Save to make your changes permanent." message

This way, the user can keep on enabling and/or disabling modules and things happen only when they hit the "save" button.

**Comment by klonos** [comment] 2015-01-04 07:10
..anyways, my previous comment might be the means to and end, but is totally off-topic here. If you think that what I propose might improve UX, we could move that to its own issue. For now, the whole idea is to figure out if we could remove the "Enabled" column in order to save horizontal space before trying to align column so that they have equal widths throughout the page.

**Comment by BWPanda** [comment] 2015-01-04 07:34
Here's another idea: make the Modules page the same as other admin pages (e.g. admin/content) - the checkboxes column doesn't have a label, they're just for selecting items to apply an action to. In this case, the enabled/disabled status of a module could be based on the color of the table row (green for enabled, red or grey for disabled, etc.) and you simply check the boxes you want to enable then apply the 'Enable' action (bulk operation). You could go one step further and add an 'Uninstall' action so that you could uninstall disabled modules from the one page (rather than going to a separate tab - disabled modules would have to be colored differently to uninstalled modules). You could even add a 'Disable & Uninstall' action to do both in one go. Here's what it might look like:

![modules](https://cloud.githubusercontent.com/assets/2385329/5605164/44a3035a-9440-11e4-8847-42904201a0a9.jpg)

Otherwise, I don't really see a problem with the width of the 'Enabled' column (but then I only ever view the admin pages on my widescreen desktop). The solution is to change the auto-column-width functionality to make that column (and the 'Operations' column) a fixed-width instead of a variable-width.

**Comment by klonos** [comment] 2015-01-04 07:49
++ for no label!!

...not sure about bulk operations as a drop-down + "execute" button though. Lets take the discussion to #541

**Comment by klonos** [comment] 2015-01-04 08:00
...I copied everyone's relevant comments over at the other issue and removed my own from here to keep this issue short and focused on simply making sure we have equal widths for the columns. Feel free to remove your comments if you like.

**Comment by jenlampton** [comment] 2015-01-05 10:22
+++ for no label.  The checkbox is self-evident.
I think all the other columns can be handled with some CSS width to keep them in line (except for the description column, that one should be allowed to stretch for responsiveness)

Anyone up for a quick PR for this?

**Comment by BWPanda** [comment] 2015-01-05 12:11
Here's an initial PR that removes the 'Enabled' header and sets all columns except 'Description' to a fixed-width. Problem is that it doesn't work that well on smaller screens (e.g. at a screen width of 760px the 'Name' column should probably be narrower...). Suggestions welcome.

**Comment by klonos** [comment] 2015-01-05 18:06
We need to make sure that the same meaningful/descriptive classes present in the ```td``` tags in this table are applied to the ```th``` tags as well (don't forget the ```th``` tags for ```table .sticky-header```).

Saying this because after applying the changes, while the css and the widths set were applied to the core modules fieldset/group, they weren't applied to the views fieldset/group.

**Comment by docwilmot** [comment] 2015-01-05 18:57
Wouldnt percentage widths be better than pixel width in this case?

**Comment by klonos** [comment] 2015-01-06 00:46
In #473 we ended up using flexbox. Couldn't we do the same here to achieve some dynamic widths? I mean if you consider the table a horizontal flexbox, then...

- the checkbox column is always specific width ```flex-grow``` value of ```1``` and sticky to the left
- the operations column is also specific width and sticky to the right and we can figure out a reasonable ```flex-grow``` number for it (using the checkbox as a "basis")
- the module name and description columns could be set to ```flex-grow: stretch``` with a min/max width percentage.

Does that make sense?

**Comment by quicksketch** [comment] 2015-01-06 02:10
I'm not sure if flexbox will work here. Flexbox has the ability specify a max *and* min, as opposed to tables which normally only support a static percentage. The problem is that we need each of the category tables to all have the same percentage all the time. I think flexbox will still have the same problem with different tables being different widths based on the content in the other cells, no different than tables do already. If our only problem is that the table looks funny at smaller sizes, then we should just use a media query to add different width values at different screen sizes.

**Comment by BWPanda** [comment] 2015-01-06 05:01
> ...they weren't applied to the views fieldset/group.

I can't reproduce this.
The CSS (as per the PR) applies to *all* fieldsets (as all fieldsets are within `<form id="system-modules">...</form>` and have the same `<td>` classes). As for `<th>`, they get the same width as it's not possible for a `<th>` to have a different width to a `<td>` in the same column (as far as I know).

> Wouldnt percentage widths be better than pixel width in this case?

I don't think so, especially since the checkboxes and operations columns shouldn't be variable-width.

**Comment by BWPanda** [comment] 2015-01-06 05:23
Added a media-query to fix width on smaller screens.

**Comment by klonos** [comment] 2015-01-06 08:48
> I can't reproduce this.

Could it be failure to clear caches on my part or a browser-specific issue? I'm not sure. Testing this again...

**Comment by klonos** [comment] 2015-01-06 09:19
...and after even taking fancy screenshots to prove my point and that what I said I'm seeing is actually true, I noticed that (because I manually applied the changes) I had set the ```#system-modules td.operations``` to a **min**-width of 105px. Stupid me.

**Comment by quicksketch** [comment] 2015-01-14 07:55
Fixed in https://github.com/backdrop/backdrop/pull/638. Thanks!

**Closed by quicksketch** 2015-01-14 07:55 UTC
Labels: status - has pull request

**Comment by klonos** [comment] 2015-01-15 00:03
Looks great!!
