### ISSUE TITLE
[UX] upload an inserted image automatically

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1199] opened 2015-09-16 03:57 UTC
If you add an image in the rich-text editor but forget to hit the `Upload` button, closing the dialog does not insert the image.  Let's automatically upload the image, just like we do for fields.

**Comment by quicksketch** [comment] 2016-02-23 08:26
> Let's automatically upload the image, just like we do for fields.

The easiest way to solve this is in the same manner as Drupal 8, in which the problem isn't actually fixed, but it is greatly obscured to the point that it's irrelevant. In D8, files auto-upload upon selection, whether on file fields or in the dialog for uploading an image. This auto-upload saves the user from needing to click the "Upload" button, and in turn hides the fact that images are not uploaded upon saving the dialog.

Implementing this is fairly trivial. If we take that approach, it shouldn't be much work at all.

**Comment by gifad** [comment] 2016-02-23 09:56
FWIW, https://github.com/backdrop/backdrop/pull/1226 implements a backdropuploadimage plugin, which allows image upload without any dialog, 0 click, just drag and drop.
It just requires CKEditor 4.5.5 (for its uploadwidget)

**Comment by quicksketch** [comment] 2016-02-23 21:14
> FWIW, backdrop/backdrop#1226 implements a backdropuploadimage plugin, which allows image upload without any dialog, 0 click, just drag and drop.

That's awesome. I'd love to get that into 1.4.0. I left some feedback on moving forward on that issue in https://github.com/backdrop/backdrop-issues/issues/1560#issuecomment-187852552.

We'll still want to fix this dialog in any case, we'll still want to have a button for uploading an image as it's more discoverable than drag-and-drop, plus not all systems have that option anyway (iOS, Android).

I'll file a PR to fix the dialog by auto-uploading.

**Comment by quicksketch** [comment] 2016-02-23 21:55
Merged in https://github.com/backdrop/backdrop/issues/1275 for 1.3.3.

**Closed** 2016-02-23 21:54 UTC

**Comment by klonos** [comment] 2016-02-25 06:19
This is great! Thanx. Can I shamelessly promote the related #869??
