### ISSUE TITLE
Bulk Operations UX

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2294] opened 2016-10-21 17:59 UTC
@mikemccaffrey brought up a good point, we have a dropdown and a giant execute button on our content listing pages even when you don't have any content selected.

I like that you can see that there are bulk operations that you can do, but that execute button is awfully enticing.

In Google's Material design, a bar appears across the top of the page after you've selected content. See Google Photos UI:
No content selected:
![image](https://cloud.githubusercontent.com/assets/5607236/19607252/8c2c52a2-9796-11e6-89da-47fbd0b79201.png)

Content Selected:
![image](https://cloud.githubusercontent.com/assets/5607236/19607268/a4c59350-9796-11e6-863b-5aeaa3a3f9bd.png)

**Comment by klonos** [comment] 2019-06-01 18:39
This is a duplicate of #2440

**Closed by klonos** 2019-06-01 18:39 UTC
Labels: status - duplicate
