### ISSUE TITLE
Views: "Rescan template files" is broken

### ISSUE THREAD

**Issue by deaddred** [backdrop/backdrop-issues#3734] opened 2019-04-30 20:17 UTC
Backdrop 1.12.6 
PHP 7.2.17
Apache
Firefox 66.0.3 (64-bit)

Select a View to edit
In the View edit page under "Other", click the "Theme Information" link
When the window pops up, click the "Rescan Template Files" button.
After that you are taken to `admin/structure/views/ajax/display/listings/page/analyze-theme`

The results:

![image](https://user-images.githubusercontent.com/2423362/56996961-8e45c580-6be9-11e9-8b95-0513d7247d06.png)

**Comment by laryn** [comment] 2019-04-30 20:37
Confirm this happens on a sandbox site as well.

**Comment by klonos** [comment] 2019-04-30 23:37
Recent change made to that bit of the UI: #1265

**Comment by klonos** [comment] 2019-05-01 00:57
...I don't see how the changes in that issue could have broken this. The button is calling `views_ui_config_item_form_rescan()`, which only seems to be rebuilding the theme and the form. Could we have broken this earlier?

**Comment by klonos** [comment] 2019-05-01 01:00
...yep, just tested this on the PR sandbox in https://github.com/backdrop/backdrop/pull/1684 (Backdrop 1.5.x-dev), and that is broken there too. So this is definitely not related to the changes in #1265.

**Comment by indigoxela** [comment] 2019-06-06 05:10
Just realized the same bug here and it must have been there for quite a while.
I checked some older releases. The problem exists at least since 1.12.2 (didn't test older versions though).

Clicking on "change theme" or "rescan template files" outputs plain json instead of ctools overlay content.
Drupal 7 doesn't show this behavior.

**Comment by indigoxela** [comment] 2019-06-06 10:15
Tried to dig a bit deeper...

It seems to me, the json content itself should be ok. The problem is, that instead of rendering it inside a modal, it's provided as-is, without any wrappers (on the same url as the view edit page).

The other dialogs on views edit page work fine. Only "Theme: Information" (analyze-theme) seems broken. The main difference I can see is, that analyze-theme is the only one with submit buttons _inside the modal_, which require a form rebuild without removing (reloading?) the views edit page on submit.

No clue, how to solve this, I'm really no ajax guru.

**Comment by alanmels** [comment] 2020-01-19 20:08
Unfortunately, we I am having the same issue on Backdrop 1.5.

**Comment by Graham-72** [comment] 2020-01-19 21:39
` the only one with submit buttons inside the modal`

This reminds me of the problem I experienced when trying to work on #3297 and needed @quicksketch to provide a solution. Maybe the solution is now somewhere there or maybe we need @quicksketch to take a quick look at this one?

**Comment by alanmels** [comment] 2020-01-19 22:07
> ...I don't see how the changes in that issue could have broken this. The button is calling `views_ui_config_item_form_rescan()`, which only seems to be rebuilding the theme and the form. Could we have broken this earlier?

I am afraid the issue was always there. I've just tested backdrop-1.0.0 and the same error, but with less output popped up.

**Comment by indigoxela** [comment] 2020-01-21 10:15
After revisiting this issue again, I thought it's worth to read the docs... and gave it a try...
and feel somewhat stupid now that I see, what was actually only needed to fix the render issue.
(One of those developer moments... :wink: )

Please test and review.

**Comment by Graham-72** [comment] 2020-01-21 14:23
This fix works for me, thanks.

**Comment by alanmels** [comment] 2020-01-21 17:41
@indigoxela, You are my hero as you managed to tackle this long going issue! Works great and ready to be committed. Thank you very much!

**Comment by indigoxela** [comment] 2020-02-13 14:42
To get some progress, it would be helpful if someone who successfully tested the PR changed the label from "needs testing" to "works for me".

Then someone else (can't be me) could set a proper milestone and someone (can't be me either) could do a code review. :wink:

**Comment by herbdool** [comment] 2020-06-07 12:54
Code looks good to me

**Closed** 2020-06-11 19:14 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2020-06-11 19:17
Thanks @indigoxela for the fix! I love simple ones. Thanks @deaddred for filing the excellent issue. And thanks everyone for the reviews and confirmations!
