### ISSUE TITLE
Token display format is not configurable (and date token creates very long paths)

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop/backdrop-issues#1425] opened 2015-12-16 22:12 UTC
I've created a date field, and want to include the start date of an event in its url alias pattern:
events/[node:field_event_date]-[node:title]

However, when the path is generated, it uses the complete start and end dates and times, like:
http://test-datera.pantheon.io/events/2015-12-18-220000-2015-12-18-230000-second-website-demo

I don't remember having trouble adding the simple start date when doing this in D7. How are we handling things differently, now that we've moved the token module to Backdrop core?

---

~PR by @docwilmot: https://github.com/backdrop/backdrop/pull/2476~
PR by @docwilmot: https://github.com/backdrop/backdrop/pull/3101

**Comment by quicksketch** [comment] 2015-12-17 01:34
Hiya @mikemccaffrey! I think there may be an issue with the token handling. Right now date (and all other fields) have their tokens generated by the `field_tokens()` function (an implementation of `hook_tokens()`.

When generating tokens, it mostly comes down to this one line:
```
        $field_output = field_view_field($entity_type, $entity, $field_name, 'token', $langcode);
```

This means that we're rendering the "token" display mode of the field. However, I think our problem is that there isn't a place to configure the token display mode, so you're stuck with the default. I'll need to look further into this, but it definitely looks like a bug.

**Comment by mikemccaffrey** [comment] 2015-12-17 21:14
> This means that we're rendering the "token" display mode of the field. 

Okay, that makes a lot of sense. Can we just add a token display mode to the content type Manage Display tab? That is still not a terribly intuitive place to look for configuring the tokens, but at least it would let us edit them for the time being.

Out of curiosity, has anyone proposed using configurable tokens by adding additional arguments within the brackets? Then we could enter something like [node:field_event_date:start_date:short] to just display the short version of the start date.

**Comment by quicksketch** [comment] 2015-12-18 03:29
> Can we just add a token display mode to the content type Manage Display tab?

Yes, I think that's the best thing to do for starters.

> Then we could enter something like [node:field_event_date:start_date:short] to just display the short version of the start date.

I was also a little surprised to find that wasn't working. I think this functionality should also exist by default. It works for `[node:created]` e.g. `[node:created:short]`, but not for date fields. Looks like something that didn't make it in the port somehow.

So both solutions should be implemented/fixed. The `token` display mode will provide the default when no specific format is requested, and the extended token should let users select a particular date style whenever needed.

**Comment by quicksketch** [comment] 2015-12-18 03:30
I'm labelling this a bug since it should have come over in the Date port. Without it, upgraded sites are going to be using broken tokens.

**Comment by olafgrabienski** [comment] 2019-01-04 13:45
I've just discovered this bug report, long time after adding my feature request #2652 which I've closed as a duplicate now. It seems that everyone involved in the various issues agrees that Backdrop should offer better date tokens, so I'm adding the milestone 1.11.4. (I've also added the new "status - milestone candidate" even if I don't really understand if it's adequate here.)

**Comment by docwilmot** [comment] 2019-01-13 14:31
Had a look at this. It seems Token never had field support. See https://www.drupal.org/node/691078 which is still at `needs work`.
Pushed an early PR that adds a Token view mode to all entities and an early start to add field Tokens based on the patch in that D.org issue. Needs work.

**Comment by quinnanya** [comment] 2019-01-14 04:32
@docwilmot If I'm understanding right, though, later on in that Drupal issue they tell people not to post patches there anymore, but to one of the other issues: https://www.drupal.org/project/token/issues/691078?page=1#comment-4879702. "#1252714: Easily allow a 'token' view mode to override token display settings", one of those other issues which was fixed, was what I'm familiar with and what I was trying to emulate here.

**Comment by docwilmot** [comment] 2019-01-14 04:43
@quinnanya yes, the token view mode was done, but not field support. We could do them separately as well but its not going to get in to 1.12 anyway, so I parked it for now.

**Comment by quinnanya** [comment] 2019-01-14 04:48
@docwilmot Apologies for being dense, but what does "field support" refer to? I'm having trouble figuring out from that issue what this is supposed to do that the D7 token module doesn't do. There were definitely tokens available for field values, and the entity_token module also let you pull in field values from pointed to via a node/user reference fields. (Not urgent, given upcoming 1.12 release priorities, but just curious.)

**Comment by docwilmot** [comment] 2019-01-14 14:14
@quinnanya I'm the one being dense here. Yes youre right.

**Comment by jenlampton** [comment] 2019-02-08 21:24
I just ran into this on a D7 site, and setting the date format for a token is still nearly impossible. Core provides support for `[node:created]` and  `[node:updated]` but date fields have never worked correctly. The current recommended solution for D7 is to use the `entity_tokens` module, which will crash your browser, so then also add the `token_tewak` module to un-do that damage. 

The token format for dates using the above approach is something like `[node:field_date:0:custom:Y-m-d]`, or [node:field_date:1:custom:Y-m-d] if it's a multi-value date field. I didn't see anyone using tokens for end date in the issues I read, but we could add a separate token for that, something like [node:field_date-end:1:custom:Y-m-d].

I'd prefer to avoid using a display mode for tokens. Can't we make this work without it? Most date formats assume 'medium' unless otherwise specified, I think we should do the same here.

**Comment by jenlampton** [comment] 2019-02-08 21:25
Oh also, release is today so bumping milestone. But yes please on this issue :)

**Comment by olafgrabienski** [comment] 2019-02-12 09:42
I'd also be happy if we make this work without the need of a display mode for tokens.

**Comment by herbdool** [comment] 2019-02-13 03:06
From what I understand the token display mode basically works and the PR just sets a default like in D7 (maybe I'm wrong I haven't checked).

I'm testing @docwilmot's PR to see how far it works now, but trying to think of a usecase for the issue (other than a View).

**Comment by quinnanya** [comment] 2019-02-13 03:09
@herbdool For use cases, this comes up for me with pathauto and automatic nodetitles as well as views.

**Comment by jenlampton** [comment] 2019-02-13 03:54
I have a use-case of meetings that repeat every month. I'd like the meeting
date in the URL so each one is unique, without -0, -1, etc tacked on to the
end of the meeting name.

This is still not possible in D7 @herbdool, see previous comment about
that.

**Comment by herbdool** [comment] 2019-02-13 05:21
So @docwilmot's PR worked for me and helps make visible what was already working. I think we should make this UI change so other people can benefit and don't need to know the secret about creating a display mode called token. Maybe this could be a separate PR from the rest.

**Comment by olafgrabienski** [comment] 2019-02-13 09:48
It worked for me as well (on the sandbox site):

- Somebody had already created a date field for the post content type.
- The URL alias pattern was also already configured to contain the date field (`post/[node:field_date]/[node:title]`).
- On the *Manage Display* page, there was the *Token* display. On this display, I configured the date format to show the the `HTML Date (2099-12-31) format`.
- Result, as expected, was a post with a path like `post/2019-03-31/test-html-date`.

I've also a use case for this, and I'm happy that it works with the PR!

However, in my opinion, the above is a hard to guess workaround. Isn't it possible (or is it too difficult) to add the missing tokens directly to the token browser? Here's a list of tokens possible with the `created` date:

```
[node:created]
[node:created:long]
[node:created:medium]
[node:created:short]
[node:created:custom:?]
[node:created:since]
[node:created:raw]
```

The same should work with date fields, in my opinion. IIRC, @jenlampton expressed it similar in https://github.com/backdrop/backdrop-issues/issues/1425#issuecomment-461951877. Actually, there is already the respective issue #2652, but I closed it a month ago as a duplicate of *this* one when it wasn't clear that a PR would take the token display approach. Now I'm asking me: should I reopen #2652?

**Comment by herbdool** [comment] 2019-02-13 14:10
I can imagine we have both in separate PRs. The display mode is an easy win since the functionality is already there.

**Comment by jenlampton** [comment] 2019-02-13 17:44
I still think the display mode is a poor user experience, and not a good
candidate for putting into core.

It introduces a second, more confusing way to handle dates, when we already
have a good solution for date tokens in core.

The right solution here is to make what works for created / updated work
for date fields too, and add those to the token browser.

**Comment by olafgrabienski** [comment] 2019-02-28 12:23
> The right solution here is to make what works for created / updated work for date fields too, and add those to the token browser.

@jenlampton I agree. As we have a quite working PR with the other approach, are you up to make an alternative PR?

**Comment by jenlampton** [comment] 2019-02-28 16:53
Yes, but I have a project deadline of March 1st, so it will need to wait
till after that :)

**Comment by olafgrabienski** [comment] 2019-04-16 08:29
For reference - the question for custom date tokens came recently up in the Backdrop forum:

https://forum.backdropcms.org/forum/using-date-token-path-alias-patterns

**Comment by docwilmot** [comment] 2019-08-25 04:13
Going over Milestone issues, noting the discussions here. This PR works and replaces missing functionality (fixes token view modes). It just coincidentally also provides a long-winded way to handle the problem in this issue. So even if it isn't *the best* way to fix this issue, it still stands on its own as a bug fix for missing functionality, and I think we should commit it meanwhile. 

Can I get a RTBC please?

**Comment by klonos** [comment] 2019-08-25 11:36
I agree that we should get this in, but with 1.14.0, should we change the milestone to that?

I have left comments about 2 tiny nits in the PR though @docwilmot (one of them is to simply update `@since` in the function docblock).

**Comment by herbdool** [comment] 2019-09-05 19:25
@quicksketch I've added a test.

It checks for tokens like `[node:field_test_date]` and `[node:field_text]`. But I don't know if the PR is supposed to also allow the `[node:field_test_date:short]`. @docwilmot do you have an answer for that?

**Comment by docwilmot** [comment] 2020-03-19 22:44
> It checks for tokens like [node:field_test_date] and [node:field_text]. But I don't know if the PR is supposed to also allow the [node:field_test_date:short]. @docwilmot do you have an answer for that?

I'm guessing this may need to be dealt with in Date module. Lets just agree that this PR provides a token view mode, and thats it, and get it in core. Then we can work on any missing functionality. Reasonable?

**Comment by herbdool** [comment] 2020-03-20 18:04
@docwilmot yes, that's reasonable.

Automated tests look good now. I will try test it at some point soon unless someone gets to it first.

**Comment by olafgrabienski** [comment] 2020-03-20 22:34
Tested the PR again in the sandbox -- similar to https://github.com/backdrop/backdrop-issues/issues/1425#issuecomment-463131316 --, and it still works: I was able to configure post URL alias patterns with different date formats (HTML date, Short date), great!

**Comment by docwilmot** [comment] 2020-03-23 14:41
This needs work. The `field.tokens.inc` code is unnecessary and bogus too.

**Comment by docwilmot** [comment] 2020-03-24 03:41
New PR, dropping the bogus code, and incorporating token view mode directly into `entity_get_info()` instead of an alter function. Otherwise same code,

**Comment by docwilmot** [comment] 2020-03-24 03:48
@olafgrabienski care for one more review? Tests green.

**Comment by olafgrabienski** [comment] 2020-03-24 21:13
> care for one more review?

Sure, can't make it today but hopefully soon.

**Comment by olafgrabienski** [comment] 2020-03-26 09:31
@docwilmot I've tested the sandbox site of the new PR. Works good like before: Was still able to configure *Post* URL alias patterns with different date formats (HTML date, Short date) via a custom Date field on the Tokens display mode, and the alias reflects the configuration, e.g.:

- post/2020-03-26/test-post-i-with-html-date-format
- post/03262020-1200am/test-post-ii-with-short-date-format

Only issue: I've seen a "Theme hook not found" message in DBlog - no idea if related but just in case: http://3101.backdrop.backdrop.qa.backdropcms.org/admin/reports/event/40

**Comment by docwilmot** [comment] 2020-03-30 16:36
@olafgrabienski thanks. I went through the process of creating a token view mode, a URL alias, adding a field and creating a node and found that the "Theme hook not found" is an unrelated bug.

**Comment by olafgrabienski** [comment] 2020-03-30 20:39
For reference, the "Theme hook not found" issue: #4357

**Comment by docwilmot** [comment] 2020-04-16 14:51
Can we get an RTBC?

**Comment by herbdool** [comment] 2020-04-16 15:41
Much simpler than last PR. Looks good.

**Comment by quicksketch** [comment] 2020-04-16 19:11
Looks good. The functionality is great and we have tests :tada: 

I have a question on the code, is Entity module providing the `token` display mode redundant with Node, Comment, Taxonomy, and User all doing it separately? https://github.com/backdrop/backdrop/pull/3101/files#r409787612

**Comment by quicksketch** [comment] 2020-04-17 15:39
That seems fine. Could you set `custom settings` to `FALSE` in the generic implementation so it's the same in all places? Looks like that just disables the Token display mode by default.

**Comment by quicksketch** [comment] 2020-04-23 19:20
Moving to needs work, on that one-liner change. ^^

**Comment by jenlampton** [comment] 2020-04-26 22:24
Code review looks great, RTBC.

**Closed** 2020-05-11 03:08 UTC
Labels: pr - ready to be committed, pr - works for me, status - has pull request, type - bug report

**Comment by quicksketch** [comment] 2020-05-11 03:09
Merged https://github.com/backdrop/backdrop/pull/3101 into 1.x and 1.15.x. Thanks everybody!
