### ISSUE TITLE
Scheduled content gets accidentally published by users without "Administer content" permission

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#3731] opened 2019-04-29 16:03 UTC
**Description of the bug**
When Backdrop users without the `Administer content` permission edit a content item which is "Scheduled for later" (and thus unpublished), the node gets published accidentally when it is saved.

**Steps To Reproduce**

**(1)** As a user **with** the `Administer content` permission:
  Add a post, fill in a title, write some content, go to the tab *Publishing options*, enable the option "Schedule for later", choose a date and time in the future, and save the post.
**(2)** As a user **without** the `Administer content` permission (but with, amongst others, `View any unpublished content` and `Post: Edit any content`):
  Edit the post, change e.g. some *Body* text, and save the post.

**Actual behavior:**
The post is published immediately.

**Expected behavior:**
The post remains unpublished until the scheduled date and time.

---

**(3)** Alternatively, after step (1) don't do step (2). Instead -- again as a test user *without* the `Administer content` permission, but *with* the permission `Override Post published option` provided by the [Override Node Options](https://github.com/backdrop-contrib/override_node_options) module:
  Edit the post, and have a look at the *Publishing options* tab.

**Actual behavior:**
The option "Published" is selected, the "Schedule for later" isn't.
  (You don't see these options in step (2) due to restricted permissions, but I guess there happens the same.)

**Expected behaviour:**
The option "Schedule for later" is enabled.

(Note: When you switch from "Published" to "Schedule for later" as this user, you're not able to choose a date and time.)

---

**Screenshots**

A post created by an administrative user:

![screen-backdrop-scheduled-tabs-admin](https://user-images.githubusercontent.com/14188307/56908370-774a8a80-6aa6-11e9-921b-361259fc8256.png)

The same edit form, visited by an editor without the `Administer content` permission (but with `Override Post published option`:

![screen-backdrop-scheduled-tabs-editor-2-override-node-option](https://user-images.githubusercontent.com/14188307/56908371-774a8a80-6aa6-11e9-997e-3e3936a17843.png)

**Additional information**
- Backdrop CMS 1.12.6

---------------
~~PR https://github.com/backdrop/backdrop/pull/2648~~
PR: https://github.com/backdrop/backdrop/pull/2683

**Comment by herbdool** [comment] 2019-04-30 14:48
I can confirm this bug on a clean site.

**Comment by herbdool** [comment] 2019-04-30 19:46
The issue is this section https://github.com/backdrop/backdrop/blob/5a461671f91e7ea08d4e2f90d3f456b50ba45ca6/core/modules/node/node.pages.inc#L351

it's setting a default for the user if they don't have access to scheduling content but it assumes it's new content instead of editing content that might already have something scheduled. So we need to allow it to keep the current scheduled settings if they exist.

**Comment by olafgrabienski** [comment] 2019-04-30 21:00
Thanks for the confirmation, @herbdool! (I‘d encountered the issue on a production site.)

**Comment by olafgrabienski** [comment] 2019-05-02 13:48
> So we need to allow it to keep the current scheduled settings if they exist.

@herbdool Thanks also for the hint to `nodes.pages.inc`. I've tried to just add the condition `empty($node->nid)` to line 351:

```
elseif (empty($node->nid) && ($form['options']['status']['#default_value'] == NODE_SCHEDULED)) {
    $form['options']['status']['#default_value'] = NODE_PUBLISHED;
  }
```

This way, the status doesn't change to "published", when the user without 'administer nodes' permission edits an existing scheduled node. However, the same user isn't able to save the node then because the scheduled date is missing (message: "You have to specify a valid date.").

Unfortunately, I don't know how to keep the scheduled date, do you have an idea?

**Comment by olafgrabienski** [comment] 2019-05-03 08:24
Not sure if related, but sounds similar: #3744

**Comment by herbdool** [comment] 2019-05-08 19:59
@olafgrabienski I think part of it is related. I've created a PR for you to check.

**Comment by olafgrabienski** [comment] 2019-05-08 21:31
@herbdool That's great news, will test the PR, first thing tomorrow!

**Comment by olafgrabienski** [comment] 2019-05-09 09:03
@herbdool Thanks for the PR! I've tested it on a local site, and it works partially for me:

As a user without the `Administer content` permission, I edited and saved a content item which was already "Scheduled for later", and the node didn't get published accidentally.

Regarding the approach of the PR: Is it good to remove the permission check `user_access('administer nodes')` completely? This way, a user without the `Administer content` permission (and also without `Override Post published option`) is able to *change* an existing scheduled date. In my opinion, this kind of user should only be able to (see and) save a scheduling date which was defined before by a user with the respective permission.

I saw also that a user without `Administer content` is able to choose a scheduled date for a node which had formerly been saved as draft, which shouldn't be possible. (The scheduled state is not saved in this case, without any message, the node remains a draft.)

**Comment by herbdool** [comment] 2019-05-09 14:48
> I saw also that a user without Administer content is able to choose a scheduled date for a node which had formerly been saved as draft, which shouldn't be possible.

@olafgrabienski can you be more specific? In my testing a user without `Administer content` can't see the scheduled date field. I assume that since the parent fieldset already has access restrictions https://github.com/backdrop/backdrop/blob/6298ccbfa938211994e9500537e2e293928c19d9/core/modules/node/node.pages.inc#L297 that this will prevent them from seeing it. The same goes for the status field.

If you have contrib modules can you disable them and test this again? Or test it in the sandbox site?

**Comment by olafgrabienski** [comment] 2019-05-09 19:55
> If you have contrib modules can you disable them and test this again? Or test it in the sandbox site?

Good idea!

**Comment by olafgrabienski** [comment] 2019-05-09 21:36
Interesting: I've tested the PR in the sandbox, and indeed, there as a user without `Administer content` I do not see the scheduled date field, which is the expected behavior.

I then revisited my test site and set the node related permissions of the editor role to be the same like the sandbox site. As a result, the editor was still able to see and change the scheduled date. The site had the *Override Node Options* module enabled, but none of its permissions was set. I however suspected the module to be the issue, so I disabled it, and finally the editor didn't see the scheduled date anymore.

So there seems to be a problem with *Override Node Options*. I guess it's in different ways not yet adapted to the scheduling feature in core, see e.g. https://github.com/backdrop-contrib/override_node_options/issues/7 (which is about the current situation, without the PR discussed here).

**Comment by olafgrabienski** [comment] 2019-05-09 21:42
@herbdool: the PR works for me, see last comment. I've adapted the issue tags respectively.

(Will report the information from the last comment in the *Override Node Options* issue.)

**Comment by herbdool** [comment] 2019-05-11 00:53
@laryn want to do code review?

**Comment by laryn** [comment] 2019-05-11 21:14
@herbdool Looks good on my phone, haven't been able to do any testing.

**Comment by herbdool** [comment] 2019-05-11 21:18
@laryn, @olafgrabienski already tested so I guess this is good to marked as RTBC.

**Comment by quicksketch** [comment] 2019-05-15 22:38
PR looks good but I had some comments on syntax: https://github.com/backdrop/backdrop/pull/2648#pullrequestreview-238104581

**Comment by jenlampton** [comment] 2019-05-15 23:16
Syntax fixed, new PR pushed, PR tested, and RTBC!

**Closed** 2019-05-15 23:16 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2019-05-15 23:17
Thanks! And @herbdool got in another review also. Merged https://github.com/backdrop/backdrop/pull/2683 into 1.x and 1.12.x.

Thanks @herbdool, @olafgrabienski, @jenlampton, and @laryn!
