### ISSUE TITLE
Support, Layout: How to have a Front page ruled by the role?

### ISSUE THREAD

**Issue by vtad** [backdrop/backdrop-issues#660] opened 2015-01-30 11:41 UTC
I want to have a 2 column front page for anonymous users, and a 1 column for authenticated users,
but defining a layout with a role condition generates the message:
"The condition 'User has the role Anonymous' does not have the required contexts at this path. Remove the condition to save the layout."

**Comment by quicksketch** [comment] 2015-01-31 02:23
Hi @vtad! It sounds like you've done everything correctly, you may have found a bug in the context checking. The context for "User" should always be available because the global user object is always in scope. I'll take a look and see if I can reproduce it.

**Comment by quicksketch** [comment] 2015-02-07 04:33
I confirmed this problem. User validations are currently not allowed unless on a path that already includes another user context. I filed a PR at https://github.com/backdrop/backdrop/pull/731 to resolve this issue.

**Comment by quicksketch** [comment] 2015-02-07 21:44
This has now been fixed in https://github.com/backdrop/backdrop/pull/731. Thanks @vtad! A 1.0.2 release will be out early next week.

**Closed** 2015-02-07 21:44 UTC
Labels: status - has pull request
