### ISSUE TITLE
Config Exception Errors illegible, have a whole lot of escaped content...

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2484] opened 2017-01-21 17:32 UTC
It looks like this:
![image](https://cloud.githubusercontent.com/assets/5607236/22176338/d309f9b8-dfd5-11e6-9490-2378ff310a52.png)

<em class="placeholder">ConfigStorageReadException</em>: The configuration file "user.role.administrator" is not properly formatted JSON.

Contents:
&lt;pre&gt;{
    &amp;quot;_config_name&amp;quot;: &amp;quot;user.role.administrator&amp;quot;,
    &amp;quot;name&amp;quot;: &amp;quot;administrator&amp;quot;,
    &amp;quot;label&amp;quot;: &amp;quot;Administrator&amp;quot;,
    &amp;quot;weight&amp;quot;: 2,
    &amp;quot;permissions&amp;quot;: [
        &amp;quot;administer blocks&amp;quot;,
        &amp;quot;administer comments&amp;quot;,
        &amp;quot;access comments&amp;quot;,
        &amp;quot;post comments&amp;quot;,
        &amp;quot;skip comment approval&amp;quot;,
        &amp;quot;edit own comments&amp;quot;,
        &amp;quot;synchronize configuration&amp;quot;,
        &amp;quot;administer fields&amp;quot;,
        &amp;quot;administer filters&amp;quot;,
        &amp;quot;upload editor images&amp;quot;,
        &amp;quot;use text format filtered_html&amp;quot;,
        &amp;quot;use text format full_html&amp;quot;,
        &amp;quot;administer image styles&amp;quot;,
        &amp;quot;use installer browser&amp;quot;,
        &amp;quot;administer menu&amp;quot;,
        &amp;quot;bypass node access&amp;quot;,
        &amp;quot;administer content types&amp;quot;,
        &amp;quot;administer nodes&amp;quot;,
        &amp;quot;access content overview&amp;quot;,
        &amp;quot;access content&amp;quot;,
        &amp;quot;view own unpublished content&amp;quot;,
        &amp;quot;view any unpublished content&amp;quot;,
        &amp;quot;view revisions&amp;quot;,
        &amp;quot;revert revisions&amp;quot;,
        &amp;quot;delete revisions&amp;quot;,
        &amp;quot;create page content&amp;quot;,
        &amp;quot;edit own page content&amp;quot;,
        &amp;quot;edit any page content&amp;quot;,
        &amp;quot;delete own page content&amp;quot;,
        &amp;quot;delete any page content&amp;quot;,
        &amp;quot;create post content&amp;quot;,
        &amp;quot;edit own post content&amp;quot;,
        &amp;quot;edit any post content&amp;quot;,
        &amp;quot;delete own post content&amp;quot;,
        &amp;quot;delete any post content&amp;quot;,
        &amp;quot;administer url aliases&amp;quot;,
        &amp;quot;create url aliases&amp;quot;,
        &amp;quot;administer path patterns&amp;quot;,
        &amp;quot;notify of path changes&amp;quot;,
        &amp;quot;administer redirects&amp;quot;,
        &amp;quot;administer search&amp;quot;,
        &amp;quot;search content&amp;quot;,
        &amp;quot;use advanced search&amp;quot;,
        &amp;quot;administer modules&amp;quot;,
        &amp;quot;administer site configuration&amp;quot;,
        &amp;quot;administer themes&amp;quot;,
        &amp;quot;administer software updates&amp;quot;,
        &amp;quot;access administration pages&amp;quot;,
        &amp;quot;access site in maintenance mode&amp;quot;,
        &amp;quot;view the administration theme&amp;quot;,
        &amp;quot;access site reports&amp;quot;,
        &amp;quot;block IP addresses&amp;quot;,
        &amp;quot;administer taxonomy&amp;quot;,
        &amp;quot;edit terms in tags&amp;quot;,
        &amp;quot;delete terms in tags&amp;quot;,
        &amp;quot;administer permissions&amp;quot;,
        &amp;quot;administer users&amp;quot;,
        &amp;quot;administer account settings&amp;quot;,
        &amp;quot;access user profiles&amp;quot;,
        &amp;quot;change own username&amp;quot;,
        &amp;quot;cancel account&amp;quot;,
        &amp;quot;select account cancellation method&amp;quot;,
        &amp;quot;administer views&amp;quot;,
        &amp;quot;access all views&amp;quot;,
        &amp;quot;access contextual links&amp;quot;,
        &amp;quot;administer layouts&amp;quot;,
        &amp;quot;access administration bar&amp;quot;,
        &amp;quot;flush caches&amp;quot;,
        &amp;quot;create artist content&amp;quot;,
        &amp;quot;edit own artist content&amp;quot;,
        &amp;quot;edit any artist content&amp;quot;,
        &amp;quot;delete own artist content&amp;quot;,
        &amp;quot;delete any artist content&amp;quot;,
        &amp;quot;create exhibit content&amp;quot;,
        &amp;quot;edit own exhibit content&amp;quot;,
        &amp;quot;edit any exhibit content&amp;quot;,
        &amp;quot;delete own exhibit content&amp;quot;,
        &amp;quot;delete any exhibit content&amp;quot;,
        &amp;quot;create gallery_image content&amp;quot;,
        &amp;quot;edit own gallery_image content&amp;quot;,
        &amp;quot;edit any gallery_image content&amp;quot;,
        &amp;quot;delete own gallery_image content&amp;quot;,
        &amp;quot;delete any gallery_image content&amp;quot;,
        &amp;quot;create membership content&amp;quot;,
        &amp;quot;edit own membership content&amp;quot;,
        &amp;quot;edit any membership content&amp;quot;,
        &amp;quot;delete own membership content&amp;quot;,
        &amp;quot;delete any membership content&amp;quot;,
       &lt;/pre&gt;
 in <em class="placeholder">ConfigFileStorage-&gt;read()</em> (line <em class="placeholder">900</em> of <em class="placeholder">/srv/bindings/854e8a38da80443d9cdd489d657dd088/code/core/includes/config.inc</em>).

**Comment by wesruv** [comment] 2017-01-21 17:35
If you copy that same code into github, you get this, looks like the `<pre>` got escaped?

ConfigStorageReadException: The configuration file "user.role.administrator" is not properly formatted JSON. Contents: <pre>{ &quot;_config_name&quot;: &quot;user.role.administrator&quot;, &quot;name&quot;: &quot;administrator&quot;, &quot;label&quot;: &quot;Administrator&quot;, &quot;weight&quot;: 2, &quot;permissions&quot;: [ &quot;administer blocks&quot;, &quot;administer comments&quot;, &quot;access comments&quot;, &quot;post comments&quot;, &quot;skip comment approval&quot;, &quot;edit own comments&quot;, &quot;synchronize configuration&quot;, &quot;administer fields&quot;, &quot;administer filters&quot;, &quot;upload editor images&quot;, &quot;use text format filtered_html&quot;, &quot;use text format full_html&quot;, &quot;administer image styles&quot;, &quot;use installer browser&quot;, &quot;administer menu&quot;, &quot;bypass node access&quot;, &quot;administer content types&quot;, &quot;administer nodes&quot;, &quot;access content overview&quot;, &quot;access content&quot;, &quot;view own unpublished content&quot;, &quot;view any unpublished content&quot;, &quot;view revisions&quot;, &quot;revert revisions&quot;, &quot;delete revisions&quot;, &quot;create page content&quot;, &quot;edit own page content&quot;, &quot;edit any page content&quot;, &quot;delete own page content&quot;, &quot;delete any page content&quot;, &quot;create post content&quot;, &quot;edit own post content&quot;, &quot;edit any post content&quot;, &quot;delete own post content&quot;, &quot;delete any post content&quot;, &quot;administer url aliases&quot;, &quot;create url aliases&quot;, &quot;administer path patterns&quot;, &quot;notify of path changes&quot;, &quot;administer redirects&quot;, &quot;administer search&quot;, &quot;search content&quot;, &quot;use advanced search&quot;, &quot;administer modules&quot;, &quot;administer site configuration&quot;, &quot;administer themes&quot;, &quot;administer software updates&quot;, &quot;access administration pages&quot;, &quot;access site in maintenance mode&quot;, &quot;view the administration theme&quot;, &quot;access site reports&quot;, &quot;block IP addresses&quot;, &quot;administer taxonomy&quot;, &quot;edit terms in tags&quot;, &quot;delete terms in tags&quot;, &quot;administer permissions&quot;, &quot;administer users&quot;, &quot;administer account settings&quot;, &quot;access user profiles&quot;, &quot;change own username&quot;, &quot;cancel account&quot;, &quot;select account cancellation method&quot;, &quot;administer views&quot;, &quot;access all views&quot;, &quot;access contextual links&quot;, &quot;administer layouts&quot;, &quot;access administration bar&quot;, &quot;flush caches&quot;, &quot;create artist content&quot;, &quot;edit own artist content&quot;, &quot;edit any artist content&quot;, &quot;delete own artist content&quot;, &quot;delete any artist content&quot;, &quot;create exhibit content&quot;, &quot;edit own exhibit content&quot;, &quot;edit any exhibit content&quot;, &quot;delete own exhibit content&quot;, &quot;delete any exhibit content&quot;, &quot;create gallery_image content&quot;, &quot;edit own gallery_image content&quot;, &quot;edit any gallery_image content&quot;, &quot;delete own gallery_image content&quot;, &quot;delete any gallery_image content&quot;, &quot;create membership content&quot;, &quot;edit own membership content&quot;, &quot;edit any membership content&quot;, &quot;delete own membership content&quot;, &quot;delete any membership content&quot;, </pre> in ConfigFileStorage->read() (line 900 of /srv/bindings/854e8a38da80443d9cdd489d657dd088/code/core/includes/config.inc).

**Comment by klonos** [comment] 2017-01-21 20:03
I think I've seen some random test failures with the "is not properly formatted JSON" message. Checking the contents of the reported .json files with a couple of online JSON validators showed everything green, so I don't know what's going on.

**Comment by indigoxela** [comment] 2021-01-24 11:32
This issue is quite old and it seems that only one person was affected since 2017.

As there aren't any steps to reproduce, I'm closing this one. Feel free to re-open, if there's any new information about how to reproduce the problem.

**Closed by indigoxela** 2021-01-24 11:32 UTC
Labels: status - cannot reproduce
