### ISSUE TITLE
[UX] Pathauto follow-up: duplicate path pattern settings on entity-type forms

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#899] opened 2015-05-02 08:16 UTC
This has been a long-time pet peeve of mine.  Steps to create a new content type on an existing site:
1) node/types - add a type
2) user/permissions - configure permissions
3) pathauto/settings - set up aliases
etc, etc for redirect, metatag, whatevs.

Can we *please* put the settings for these things in a convenient location - like, oh, I dunno, the node type page!!! Yes - Drupal users expect to find a list of all path patterns in the same palace.  Fine, leave them there too.  The user should always be right - wherever you expect to find the thing. PUT THE THING.

</rant>

So, here's the actual follow up issue: 
1) Add automatic path pattern config to node/type form
2) Add automatic path pattern config to term/vocab form
3) Add automatic path pattern config to user/settings form

Also related: https://github.com/backdrop/backdrop-issues/issues/900

**Comment by klonos** [comment] 2015-05-02 09:30
Yes please! If not a vtab, then perhaps a new "Manage Permissions" local menu?

**Comment by serundeputy** [comment] 2015-05-29 02:56
@jenlampton is this the right idea:
https://github.com/backdrop/backdrop/pull/917

if so I keep at it; if not guidance. :smile:

**Comment by serundeputy** [comment] 2015-05-29 13:10
when i woke up i thought maybe a screenshot is worth a 100 words;
Add content type:
`/admin/structure/types/add`
![screen shot 2015-05-29 at 8 27 00 am](https://cloud.githubusercontent.com/assets/6763671/7882687/126a1896-05de-11e5-8b3d-1764f63dc3ce.png)

Add content of that type:
![screen shot 2015-05-29 at 8 31 12 am](https://cloud.githubusercontent.com/assets/6763671/7882710/637e2bd2-05de-11e5-96ab-ae7beb8c44a3.png)

after using form on add content type:
`/admin/config/search/path/patterns`
![screen shot 2015-05-29 at 8 43 02 am](https://cloud.githubusercontent.com/assets/6763671/7883154/3e4d1324-05e2-11e5-809a-7b3add1b2d1a.png)


so i'm thinking: 
  * add token browser to form
  * some help text maybe:

    ````
     Path patterns automatically alias new content based on wildcards called "tokens". For example the URL "node/10" might be automatically aliased to "blog/my-first-post" using the pattern "blog/[node:title]".
    ```
  * some help text on the vertical tab

thoughts?

**Comment by klonos** [comment] 2015-05-29 16:02
Usually help text is intended for first-time users/new-comers and I think that these user groups should never be exposed to the words "node" or "token" if possible. Now with token/pathauto in core, I see Backdrop being "smart" enough so that no ```/node/*``` path is *ever* exposed to the general public. Of course ```/node``` will still be there, but "behind the scene".

So, for the help text (if any at all), I'd go simply with something like ```Path patterns automatically create meaningful URL paths for your content based on wildcards. For example, using the pattern "blog/[node:title]" will result in a URL path of "blog/my-first-post"```

I intentionally made my comment about the help text before actually commending on the work done because I just wanted to say that this idea and implementation is plain awesome!!!

**Comment by serundeputy** [comment] 2015-05-30 00:34
updated PR; 
Issue #899: Adding token browser and vertical tab description to configure path alias on content type add/edit forms.

![screen shot 2015-05-29 at 8 31 52 pm](https://cloud.githubusercontent.com/assets/6763671/7894897/e8fd8f60-0641-11e5-98f5-5d666cccdac8.png)

**Comment by serundeputy** [comment] 2015-06-22 23:48
I began work on this and then realized it was assigned to @jenlampton so you can have it Jen if my work is useful then take it; otherwise discard it.

If you don't want it; I'm stuck on how this would work for `taxonomy` terms and `users` as there add forms do work the same way as adding content types.  Anyone have ideas?

Sorry for hijacking your issue @jenlampton :crying_cat_face:

**Comment by quicksketch** [comment] 2015-06-22 23:57
I don't think @jenlampton will mind. :smile_cat: 

> I'm stuck on how this would work for taxonomy terms and users as there add forms do work the same way as adding content types. Anyone have ideas?

I think it would be acceptable, even ideal, if path patterns were shown on *both* the content type forms and the current path patterns page. So perhaps just leave the path patterns page completely the same and add the path pattern to the content type forms. We do similar duplication of settings when dealing with UIs that are completely separated, such as permissions for text formats. We don't make the user go to the permissions page when setting up a new text format; they can set the permissions right in the text format form.

@jenlampton opened a similar issue for settings permissions on node types in the same way: https://github.com/backdrop/backdrop-issues/issues/900

**Comment by serundeputy** [comment] 2015-06-23 00:05
>> I'm stuck on how this would work for taxonomy terms and users as there add forms do work the same way as adding content types. Anyone have ideas?

  * oops; I meant *don't work in the same way :dragon_face: 

So, should I put a vertical tab on this form: `/admin/structure/taxonomy/add` ?  or a fieldset?
Similarly here: `/admin/people/create` ?

~Geoff

**Comment by serundeputy** [comment] 2015-09-19 20:38
Updated `PR`

Adding Automatic URL Alias for taxonomy terms.
---
If the default pattern is not populated on `admin/config/search/path/patterns` page.
Then there is no Check box for `Generate automatic URL alias` when adding a new term even if the path pattern is set for that vocabulary.


Adding Automatic URL Alias for users.
---
I added the fieldset to manage the URL aliases for users on the `/admin/people/create` page, It saves the new pattern, but does not apply it to the current user you are creating.  It also does not have the `Generate automatic alias` check box in the fieldset.

 - [x] Administer URL Alias path patterns from add content type
 - [ ] Administer URL Alias path patterns  from add vocabulary
    * this works if the default vocabulary path pattern is set.
 - [ ] Administer URL Alias path patterns from /admin/people/create
    * you can add a new / change user path pattern
    * does not apply to the current user or allow for `Generate automatic alias`

**Comment by jenlampton** [comment] 2015-09-28 07:58
yes, yes yes. Thank you @serundeputy :+1: 

I personally think there should be vertical tabs on those pages.  Once you have a full-featured site with redirects, aliases, and who-knows-what-else there is a lot of stuff on those pages you wish were tucked inside vertical tabs.

However, adding vertical tabs to pages that don't have them yet may be a bit trixy.

**Comment by klonos** [comment] 2015-09-29 01:52
> If the default pattern is not populated on ```admin/config/search/path/patterns``` page.
> Then there is no Check box for "Generate automatic URL alias" when adding a new term even if the path pattern is set for that vocabulary.

I would prefer to show features to users rather than hide them. How I would like to see this work is that instead of hiding the checkbox, we instead replace it with a "Paths can be automatically generated, but there is no automatic pattern set for this term" ...or something like that + a connect-the-dots link (taking the user to the patterns admin page or opening a modal where only the specific pattern can be set). Does that make sense?

**Comment by serundeputy** [comment] 2015-09-29 22:14
>>If the default pattern is not populated on admin/config/search/path/patterns page.
Then there is no Check box for "Generate automatic URL alias" when adding a new term even if the path pattern is set for that vocabulary.

I'm not suggesting this is the way it ought to be; I'm stating this is the current state of affairs.  I believe if a specific pattern is populated that it should show the check box for automatic alias since that is more specific than the default.  Sorry that was not clear.

The check box's are the TODO list.

**Comment by sutibun** [comment] 2015-10-24 21:39
Late to the party but....

> This has been a long-time pet peeve of mine. Steps to create a new content type on an existing site:
> 1) node/types - add a type
> 2) user/permissions - configure permissions
> 3) pathauto/settings - set up aliases
> etc, etc for redirect, metatag, whatevs.

Yes, please.

> I think it would be acceptable, even ideal, if path patterns were shown on both the content type forms and the current path patterns page

And, yes, please.

**Comment by serundeputy** [comment] 2015-10-26 22:49
updated: https://github.com/backdrop/backdrop/pull/917

this gets the path patters form working on `admin/structure/taxonomy/add`

~Geoff

**Comment by serundeputy** [comment] 2015-10-27 22:36
I think this does it; path pattern settings on the following forms:

 - [x] admin/structure/types/add
 - [x] admin/structure/taxonomy/add
 - [x] admin/config/people/settings

This adds the path pattern forms and saving to the respective forms, but for the taxonomy term paths to work we need the additional fix from #1290 (https://github.com/backdrop/backdrop/pull/1108).

Ready for user/code review @jenlampton @quicksketch 

~Geoff

**Comment by quicksketch** [comment] 2015-10-28 22:54
Great thanks @serundeputy!

**Comment by jenlampton** [comment] 2015-11-05 20:52
Yes, yes yes.  Wow, this looks fantastic!  So far with all my testing things are working as expected. Not sure where the test failures are coming from, but after we get those cleaned up this should be good to go. :) HOORAY !!!

**Comment by serundeputy** [comment] 2015-12-03 21:53
Here is a patch link if you would like to test this and report back your findings:
https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/1108.patch

**Comment by quicksketch** [comment] 2015-12-05 05:57
This patch adds great functionality! :+1: It also works with saving new patterns and the patterns themselves are uses as expected.

Though I found a bunch of issues while testing it. :(

- Saving a vocabulary now throws a PHP notice.
![selection_006](https://cloud.githubusercontent.com/assets/100206/11606258/f5303076-9acf-11e5-9b7f-8086f7f50569.png)
- The default patterns don't seem to be respected when editing a content type/vocabulary or the user account settings. In all 3 cases the default pattern and the pattern I saw on these pages was incorrect.
  - Content types (a Post in this case):
![selection_001](https://cloud.githubusercontent.com/assets/100206/11606260/0ee94674-9ad0-11e5-8b21-6c6d18a7867b.png)
![selection_003](https://cloud.githubusercontent.com/assets/100206/11606262/167bb2e6-9ad0-11e5-82c6-ecef7531c342.png)
  - Taxonomy (Tags in this case). This one was weird because there *should* be a default pattern here (based on the global default pattern), but the pattern used was just the vocabulary name without the term name. Additionally the description text on here is incorrect, calling the vocabulary a "content type". 
![selection_004](https://cloud.githubusercontent.com/assets/100206/11606267/22dbfec4-9ad0-11e5-942a-62c3d5949a96.png)
![selection_005](https://cloud.githubusercontent.com/assets/100206/11606269/285fb93a-9ad0-11e5-8123-46af1ed6f1d3.png)
  - User accounts
![selection_007](https://cloud.githubusercontent.com/assets/100206/11606270/3768deca-9ad0-11e5-8507-d135dd465571.png)
- As noted in the User Accounts screenshot, I also didn't think that the path settings belongs in this list of emails. For now I think we should separate path settings out into its own fieldset (as it is on a Vocabulary) and consider merging peripheral user account settings (e.g. Admin role) into a vertical tab set with path settings later.

I also found the description texts to be lacking. A description of just "The default path for this content type" doesn't tell me what this does. I'd prefer something like: "When new content of this type is created, it will used this pattern by default when generating URL paths." for content and "When new terms within this vocabulary are created, they will use this pattern by default when generating URL paths." for vocabularies/terms.

Lastly, we also need tests for all this new functionality. We should ensure that saving values on the patterns page updates vocabulary/content type/user forms and vice-versa.

**Comment by serundeputy** [comment] 2015-12-19 00:21
> The default patterns don't seem to be respected when editing a content type/vocabulary or the user account settings. In all 3 cases the default pattern and the pattern I saw on these pages was incorrect.

I think this part is because of #1290 

All the other stuff I agree with.
TODO:
 - [ ]  separate path settings out into its own fieldset (as it is on a Vocabulary)
 - [ ] default path for users should be `accounts/[user:name]` 
 - [ ] get rid of the PHP notices when saving taxonomy paths 
 - [ ] Additionally the description text on here is incorrect, calling the vocabulary a "content type". fix it.
 - [ ] Update description text for terms 
    * "When new terms within this vocabulary are created, they will use this pattern by default when generating URL paths."

 - [ ] Update description text for content
    * "When new content of this type is created, it will use this pattern by default when generating URL paths."

**Comment by serundeputy** [comment] 2015-12-19 19:09
Latest PR:
* allows node type edit form to display the currently set path in the Path Settings form.
  * before adding this all backdrop tests were passing; I think I've got a handle on how to resolve what this introduced though prolly not today

* blocker is how to write new tests ... same type of tests that are on path patterns form? @quicksketch if you have any advise on how to go about this that would be great!

**Comment by jenlampton** [comment] 2016-01-08 19:24
Woohoo!  #1290 got in so this is un-stuck again, yes?

**Comment by jenlampton** [comment] 2016-01-08 20:38
Feedback from the patch:

1) We need to clean up the UI for setting patterns. "Path settings" is not at all clear as to what should go in that box. The description text "The default path for this content type." also does not clarify matters at all.  Nothing in there about a pattern or a token or an explanation of what this box will do.

2) The default values need to pull from `path.settings` config file for ***new*** nodes types, vocabs, and on the user form. We will likely need to form-alter these forms to put in the default values for specific node types, vocabularies (and user types?) to pull and display accurate values.

 Before:
![screen shot 2016-01-08 at 11 31 40 am](https://cloud.githubusercontent.com/assets/397895/12207467/9736f09e-b5fb-11e5-82dc-a1cb29619c8c.png)
After: 
![screen shot 2016-01-08 at 11 45 58 am](https://cloud.githubusercontent.com/assets/397895/12207780/75d5318e-b5fd-11e5-90d7-325070e68c22.png)

3) A little cleanup on the javascript for the vertical tabs.  When empty: `No URL pattern set` When provided: `blog/[node:title]`
![screen shot 2016-01-08 at 11 52 51 am](https://cloud.githubusercontent.com/assets/397895/12207933/635cfbc6-b5fe-11e5-98e6-9fa8b0778155.png)

4) On the node and term pages, the fieldset is labeled `URL path settings` which I think makes sense to people. We should use that same label on the node-type and term-vocab configure pages (currently it's just `Path settings`).

5) The default value for terms is set to `[term:vocabulary:name]` which isn't a valid token. I have removed this for now (see my comment above about defaults) but we should add it back - just for Tags, as `[term:vocabulary]/[term:name]` instead.

6) User e-mails and path settings should not be grouped together in vertical tabs.  In fact, why the heck are emails on this page anyway?  (see # about that) For now let's move the Path settings out of the vertical tabs, and place them above the emails for now.

There are a few tiny code-nit notes on the current PR, but  I'm filing a PR with these changes, we'll see how that goes :)

**Comment by jenlampton** [comment] 2016-01-08 22:38
woot woot, we have passing tests people :)  Anyone want to give this a review?

**Comment by jenlampton** [comment] 2016-01-08 22:43
Also related: https://github.com/backdrop/backdrop-issues/issues/1250

**Comment by docwilmot** [comment] 2016-01-08 23:23
Checked working:
- path fieldsets appear on node/vocab/user pages as expected
- changes to these fieldsets are reflected on the `admin/config/search/path/patterns` page
- path patterns added on those pages work as exected
- changes to the `admin/config/search/path/patterns` page are reflected on the node and user pages

Not working:
- changes to the `admin/config/search/path/patterns` page are **not** reflected on the vocab config pages. the default `[term:vocabulary]/[term:name]` always shows.

**Comment by serundeputy** [comment] 2016-01-08 23:25
testing: https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/1180.patch
against `1.x`

- [x] Added node-type no default pattern set; expected behaviour no path setting in the `Default URL pattern` js shows `No URL pattern set` in the vertical tab.

- [x] Added node-type with default pattern set; expected behaviour path setting in `Default URL pattern` is picked up and displayed in text box. js shows default path in the vertical tab.

- [x] Added node of new content types from above; expected behaviour path that was set on the node type form is applied to saved node.

- [ ] Added a vocabulary and set a default path for it, but upon creating a term in said vocabulary the path is not applied; the path pattern is not saved; when you edit the vocabulary again you see the pattern is set back to default vocabulary, but on the path patterns page the saved path is there???

**Comment by jenlampton** [comment] 2016-01-09 01:55
Thanks for the detailed reviews guys! :)

> changes to the admin/config/search/path/patterns page are not reflected on the vocab config pages. the default [term:vocabulary]/[term:name] always shows.

> Added a vocabulary and set a default path for it, but upon creating a term in said vocabulary the path is not applied; the path pattern is not saved; when you edit the vocabulary again you see the pattern is set back to default vocabulary, but on the path patterns page the saved path is there???

These sound like the same problem, will look into it!

**Comment by jenlampton** [comment] 2016-01-09 07:08
Okay, I got the taxonomy issue sorted, but think we should add new tests (so that would have been caught!).

**Comment by jenlampton** [comment] 2016-01-09 09:16
Now with tests :) Can I get confirmation that I fixed that taxonomy glitch?.  If so we may be RTBC!

**Comment by klonos** [comment] 2016-01-09 14:06
...found some other issues and have some ideas about how things can be done better, but do not want to side-track this, so I'm filing separate issues. If you think they should be tackled here in a single go, then feel free to update the PR and close the other issues.

**Comment by serundeputy** [comment] 2016-01-09 14:07
https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/1180.patch this patch is now working for me;

thanks @jenlampton++ 

In particular the setting the taxonomy paths for specific vocabulary on the vocab add page and through the path patterns page.

**Comment by quicksketch** [comment] 2016-01-10 00:20
Overall, looks great.

I found only two issues:

- Path module is optional. As such, we need to wrap anything that reads/writes from `path.settings` in a `if (module_exists('path'))` check.
- There seems to be a bug in TaxonomyTerm class, as I noted here: https://github.com/backdrop/backdrop/pull/1180/files#r49269860. We should fix this rather than making an exception for taxonomy term entities.

**Comment by jenlampton** [comment] 2016-01-10 00:32
Ah, right. I suppose all those settings should also disappear if path module is disabled... will do.

**Comment by jenlampton** [comment] 2016-01-10 02:24
Okay, just pushed a rewrite of the patch with all the new settings areas being form-altered into node, term and user forms by the path module. Let's see if it still passes tests :)

**Comment by quicksketch** [comment] 2016-01-11 01:21
Close! One fail:

```
Status    Group      Filename          Line Function                            
--------------------------------------------------------------------------------
Fail      Browser    path_pattern.test  692 PathPatternFunctionalTestCase->test
    URL pattern set with user account config appears on path config page.
```

**Comment by jenlampton** [comment] 2016-01-14 23:33
@quicksketch that's a random fail. Passes tests locally.

**Comment by quicksketch** [comment] 2016-01-15 06:29
Thanks @serundeputy and @jenlampton! Merged the PR from https://github.com/backdrop/backdrop/pull/1180 in manually at https://github.com/backdrop/backdrop/commit/bb82360794dd85555dc579fb04484f14a341972a. This will be in 1.3.0. Thanks!!

**Closed by quicksketch** 2016-01-15 06:29 UTC
Labels: status - has pull request, type - feature request
