### ISSUE TITLE
Use design changes from Status Report redesign in the Available Updates page

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#2591] opened 2017-03-21 14:10 UTC
There is discussion about updating the design of the Status Report: https://github.com/backdrop/backdrop-issues/issues/485

It would be good for consistency to also use the updated design style on the Available Updates page, since it has many similarities.

Here's the new status report: 
<img width="1429" alt="screen shot 2017-04-22 at 9 22 45 pm" src="https://cloud.githubusercontent.com/assets/397895/25310751/df5e5ace-27a1-11e7-876a-fb73d2a914c4.png">

---

PR: https://github.com/backdrop/backdrop/pull/1836

**Comment by jenlampton** [comment] 2017-04-23 02:08
On it :)

**Comment by jenlampton** [comment] 2017-04-23 06:08
How about something like this?

Desktop:
<img width="1341" alt="screen shot 2017-04-22 at 11 07 49 pm" src="https://cloud.githubusercontent.com/assets/397895/25311248/92731420-27b0-11e7-8444-d49ffe529886.png">

Tablet:
<img width="697" alt="screen shot 2017-04-22 at 11 07 38 pm" src="https://cloud.githubusercontent.com/assets/397895/25311251/9958c140-27b0-11e7-92f1-1f757b933ebb.png">

Mobile:
<img width="448" alt="screen shot 2017-04-22 at 11 07 24 pm" src="https://cloud.githubusercontent.com/assets/397895/25311252/9e11be6c-27b0-11e7-8a79-a3155d22299c.png">

**Comment by jenlampton** [comment] 2017-04-23 07:00
I'm having a hard time keeping these changes separate from those in https://github.com/backdrop/backdrop-issues/issues/2591 so I'm going to include these in a separate commit on te PR at https://github.com/backdrop/backdrop/pull/1836

**Comment by olafgrabienski** [comment] 2017-04-23 14:54
Nice! Two suggestions for the mobile design:

- "Check manually" button: Remove the left margin, and add some top margin.
- Update information: Don't alternate the alignment between left and right. Put all the information on the left, it looks less busy on narrow screens. See screenshots:

320px, e.g. iPhone 5:
![screen-backdrop-pr-1836-mobile-320px](https://cloud.githubusercontent.com/assets/14188307/25314437/14c4c930-2844-11e7-9a5e-515a360d5a4f.png)

On 380px and above, the bottom links have room to float, if we want to finetune:
![screen-backdrop-pr-1836-mobile-380px](https://cloud.githubusercontent.com/assets/14188307/25314436/14c48c4a-2844-11e7-88cc-5b4435bcf01b.png)

**Comment by jenlampton** [comment] 2017-04-23 18:56
Yes, that's much better, thank you :) Fixing now.

**Comment by jenlampton** [comment] 2017-04-23 19:03
Desktop: 
<img width="992" alt="screen shot 2017-04-23 at 12 01 50 pm" src="https://cloud.githubusercontent.com/assets/397895/25316476/b8478e62-281c-11e7-8562-531f0b118446.png">

Tablet: 


Mobile:
<img width="389" alt="screen shot 2017-04-23 at 12 01 25 pm" src="https://cloud.githubusercontent.com/assets/397895/25316480/c8f3df90-281c-11e7-841f-3e649abd25ad.png">

**Comment by olafgrabienski** [comment] 2017-04-23 21:56
> I'm not going to make this one [380px] change ... for not a lot of gain.

I agree!

> Everything else looks fantastic

:-) Everything ... but one small thing. On mobile screens the version status rises at the top of the page, see screenshot of the PR taken with an iPhone:

![screen-backdrop-pr-1836-iphone5](https://cloud.githubusercontent.com/assets/14188307/25317805/6d0eb06a-2880-11e7-9cc5-040d202ca9a0.png)

**Comment by quicksketch** [comment] 2017-04-27 02:07
Thank you so much @olafgrabienski for the feedback! I'm moving this to needs work to address that lingering item.

**Comment by jenlampton** [comment] 2017-04-27 04:20
Hm. I'm unable to reproduce this problem. I've added a `position: relative;` in what I believe is the relevant place, but I'll need someone to test again for me :) @olafgrabienski ?

**Comment by olafgrabienski** [comment] 2017-04-27 08:36
@jenlampton Having a quick look with Chrome dev tools device toolbar, the issue is still there. Hm, not sure if I'm looking at the correct PR. This one: [485 status report](https://github.com/backdrop/backdrop/pull/1836), correct?

**Comment by jenlampton** [comment] 2017-04-27 21:04
Yes, that's the correct PR. Update status changes should be the 2nd commit. I'll try to get a new sandbox.

**Comment by jenlampton** [comment] 2017-04-27 22:33
I'm seeing this on chrome (latest sandbox) with the latest PR: 
<img width="394" alt="screen shot 2017-04-27 at 3 32 37 pm" src="https://cloud.githubusercontent.com/assets/397895/25507068/ce9f23a6-2b5e-11e7-8943-cf67e514bd63.png">

**Comment by Dinornis** [comment] 2017-04-28 01:32
Also looks fine in OSX Firefox responsive mode.
The new reports look great, thanks everyone.

**Comment by olafgrabienski** [comment] 2017-04-28 09:05
@jenlampton Had a look again, the version status is positioned correct now, great!

Saw another small issue on 320px which is the iPhone 5 and iPhone SE width: The string "Last checked (...) ago" is two lines, and the end is on the same line with the button:

![screen-backdrop-pr-1836-mobile-320px-ago-vs-button](https://cloud.githubusercontent.com/assets/14188307/25521870/7eee99b0-2c01-11e7-8868-29580d411899.png)

The issue happens only up to 326px or so. We could apply some but not too much `margin-left` on `.checked .button`. Or change the font-size of `.checked .update' to 15px.

**Comment by Dinornis** [comment] 2017-04-28 23:23
Another possible solution could be to lower the current 25px horizontal padding for the button to perhaps 10px?
By the way, the button reflows correctly in OSX Firefox and Safari even with the string "Last checked (...) ago" is rendered in two lines.

**Comment by quicksketch** [comment] 2017-04-30 00:55
> The string "Last checked (...) ago" is rendered in two lines in some cases, dependent on the number of characters.

I pushed an update that just always adds a margin in all cases. We can't really tell with the button will wrap because that date string can get pretty long.

I also reworked the the absolute positioning of the project name and version, as if a project had a long name, it would overflow over the top of the version.

![image](https://cloud.githubusercontent.com/assets/100206/25560303/03bdf4de-2d05-11e7-9d07-ad332643b278.png)

**Comment by Dinornis** [comment] 2017-04-30 03:16
Looks good in Responsive design mode in FireFox & Safari on OSX. Not sure how reliable this is as  I was not able to replicate the button problem shown in @olafgrabienski screenshot with these tools.

**Comment by jenlampton** [comment] 2017-04-30 04:52
@Dinornis that's because @quicksketch fixed that problem, if you are looking for it and don't see it - his fix likely solved it :)

**Closed** 2017-04-30 05:33 UTC
Labels: audience - design, pr - needs review, status - has pull request, type - task

**Comment by quicksketch** [comment] 2017-04-30 05:37
I've merged https://github.com/backdrop/backdrop/pull/1836 into 1.x for 1.7.0. Thanks everyone for the many reviews and updates on this issue!
