### ISSUE TITLE
[UX] Help message on `node/add` is incorrect, and shown to those without sufficient permissions.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6349] opened 2023-12-29 23:09 UTC
When visiting `node/add` as an anonymous viewer without access to create any content, I am presented with a help message intended for an administrator:
* `You have not created any content types yet. Go to the [content type creation page] to add a new content type.`

On a fresh install, content types have been created, so the first part of the message is wrong. I also do not have access to the content type creation page, so the second part of the message should not be presented to me at all.

Proposed changes:
1) Change the wording of the first sentence to work for all scenarios, perhaps something like `No content types are available for creation.`
2) Only show the second sentence containing the link to the "content type creation page" if the user seeing the message has permission to go there.

**Comment by kiamlaluno** [comment] 2023-12-30 09:43
I checked a preview site for an existing PR. After I logged in, and removed the only existing post, I see the following, on the front page.

![Screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/ccdc90cd-5cca-46f0-9986-579dff151e0e)

That is what I see also as anonymous user too. (I flushed the cache and accessed to the preview site from a private window.)

I take the issue is about the front page, since (out of the box) /node/add would not be accessible to anonymous users. As admin, /node/add just shows a list of available content types.

**Comment by kiamlaluno** [comment] 2023-12-30 10:30
For the /node/add page, this is what I see (even when I do not remove the existing post) as anonymous user.

> ![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/200881c2-fccd-4d46-90bd-3a6203947e42)

The front page as anonymous user, when I do not remove the existing post, do not show any *You have not created any content types yet.* text.

![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/bf8bc16f-4688-4e69-b4a7-badb05bfe456)

**Comment by kiamlaluno** [comment] 2023-12-30 11:14
I checked the code currently committed for the page callback used for /node ([`node_page_default()`](https://github.com/backdrop/backdrop/blob/19dc618f14b47c80d5734e781d4fb89f4d9d3fcc/core/modules/node/node.module#L2355)). I do not see any line adding the *Go to the [content type creation page] to add a new content type.* sentence.

```php
  // Check for custom <front> page
  $front = config_get('system.core', 'site_frontpage');
  if ($front != 'node') {
    backdrop_goto('<front>', array(), '301');
  }
  else {
    $site_config = config('system.core');
    $select = db_select('node', 'n')
      ->fields('n', array('nid', 'sticky', 'created'))
      ->condition('n.promote', 1)
      ->condition('n.status', 1)
      ->orderBy('n.sticky', 'DESC')
      ->orderBy('n.created', 'DESC')
      ->extend('PagerDefault')
      ->limit($site_config->get('default_nodes_main'))
      ->addTag('node_access');

    $nids = $select->execute()->fetchCol();

    if (!empty($nids)) {
      $nodes = node_load_multiple($nids);
      $build = node_view_multiple($nodes);

      // 'rss.xml' is a path, not a file, registered in node_menu().
      backdrop_add_feed('rss.xml', $site_config->getTranslated('site_name') . ' ' . t('RSS'));
      $build['pager'] = array(
        '#theme' => 'pager',
        '#weight' => 5,
      );
      backdrop_set_title('');
    }
    else {
      backdrop_set_title(t('Welcome to @site-name', array('@site-name' => $site_config->getTranslated('site_name'))), PASS_THROUGH);

      $default_message = '<p>' . t('No content has been promoted yet.') . '</p>';
      $default_links = array();
      if (_node_add_access()) {
        $default_links[] = l(t('Add content'), 'node/add');
      }
      if (!empty($default_links)) {
        $default_message .= theme('item_list', array('items' => $default_links));
      }

      $build['default_message'] = array(
        '#markup' => $default_message,
        '#prefix' => '<div id="first-time">',
        '#suffix' => '</div>',
      );
    }
    return $build;
  }
```

It shows an *Add content* link, but only when the user account has the permission to create any content type. (See [`_node_add_access()`](https://github.com/backdrop/backdrop/blob/19dc618f14b47c80d5734e781d4fb89f4d9d3fcc/core/modules/node/node.module#L1641C10-L1641C27)).

**Comment by kiamlaluno** [comment] 2023-12-30 11:20
I thought it was a view showing what reported in the issue summary, but I cannot see any frontpage view in /admin/structure/views, nor could I see anything that explicitly show that sentence in /admin/structure/layouts/manage/home.

**Comment by kiamlaluno** [comment] 2023-12-31 11:40
I found what shows the message I see: It is the *Promoted content* view, which use the following settings, for the global area.

![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/ee77d6a2-2bf4-4a0f-b586-bbd70cd558a6)

That view is used by the *Home page* layout.

![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/560be88d-2882-4f65-9861-ee59c4d45a22)

Anyway, that would explain why on the previous sites there is no link to create new content, even for admin user, which is exactly the opposite of what this issue reports.

**Comment by argiepiano** [comment] 2023-12-31 13:29
I can't reproduce the problem reported in the OP.

**Comment by stpaultim** [comment] 2024-01-13 08:02
Also unable to recreate the reported problem.

**Comment by stpaultim** [comment] 2024-03-25 01:13
@jenlampton It seems that 4 people have failed to reproduce this issue. Can you still reproduce it?

**Comment by olafgrabienski** [comment] 2024-09-11 09:32
I'd suggest to close this issue with `status - cannot reproduce`. Any objections?

**Comment by olafgrabienski** [comment] 2024-09-18 12:54
Closing the issue. @jenlampton, feel free to reopen.

**Closed by olafgrabienski** 2024-09-18 12:54 UTC
Labels: type - bug report, status - cannot reproduce
