### ISSUE TITLE
Front page disappear after update to 1.22

### ISSUE THREAD

**Issue by Egmund** [backdrop/backdrop-issues#5629] opened 2022-05-16 18:04 UTC
## Description of the bug

All blocks on front page was de-activated by the update. Update at the website. The .htaccess was updated/edited. The cache was flushed etc. etc. 

## Steps To Reproduce

Use 'layout-node' for a 'custom' front page (overriding standard templates).
Update to 1.22

## Actual behavior

The content of front page does not show. Bu in 'edit' mode all is there.

## Expected behavior

I of course expected the content to show.

## Additional information

The 'problem' was solved by re-activate the blocks. But that should not be needed! 
At least a warning about this should be included in upgrage instructions.

**Comment by indigoxela** [comment] 2022-05-17 06:55
Hi @Egmund,

this sounds severe, but I can't reproduce it.

What I tried:

- Install a fresh 1.21.4
- Set the home page to a node (node/3, newly created), default layout
- Add custom block to that layout, with visibility condition for home page
- Updated to 1.22, ran database updates
- Everything as expected, nothing changed, no blocks deactivated

Can you please provide more details about your setup? Especially about this "Use 'layout-node' for a 'custom' front page". What exactly did you set on your custom home page layout?

**Comment by stpaultim** [comment] 2022-05-17 07:06
We added the ability to "disable" blocks with this release. While, the update should not have disabled anyones blocks automatically, this seems like the logical connection. 

@Egmund - is that what happened. Did you find your blocks disabled after the update?

**Comment by Egmund** [comment] 2022-05-17 07:20
You forgot that I installed and use the module 'layout-node' for the front: layout-node/velkommen-til-havredal-zendo. I think that is the problem. But it might not be a big problem - just chocking to see no front  page after update. With 'layout node' you should be able to recreate.

**Comment by Egmund** [comment] 2022-05-17 07:26
@stpaultim Yes, blocks disabled. But fortunately only on this domain. I suspect the bug might be in 'layout node', which is (still) beta.

**Comment by indigoxela** [comment] 2022-05-17 07:39
> You forgot that I installed and use the module 'layout-node'

@Egmund no, I didn't "forget" that, it just wasn't clear to me that "layout-node" is a module. If that's the culprit, it might make sense to open an issue in their issue queue.

Or maybe @docwilmot has some thoughts or an explanation, as he ported the module (and is our Layout specialist, anyway).

**Comment by argiepiano** [comment] 2022-05-17 19:56
I have been able to reproduce this issue.

1. Started with Backdrop 1.21.4
2. I installed the Layout Nodes module
3. I create a Layout Node node and placed 3 existing nodes in each of their regions (see image)
4.  I updated to 1.22.0
5. Visited the home page, and the blocks containing the three existing nodes have been automatically disabled (see image)

This obviously has to do with the new ability to disable blocks. It'd be important to check if this is an uncommon interaction with Layout Nodes, OR if this has negative effects beyond Layout Nodes with existing "normal" Layouts.
<img width="1221" alt="Screen Shot 2022-05-17 at 1 52 03 PM" src="https://user-images.githubusercontent.com/9938978/168898985-d0184f08-aea1-4ae5-ba96-41fc807363d6.png">
<img width="1229" alt="Screen Shot 2022-05-17 at 1 56 24 PM" src="https://user-images.githubusercontent.com/9938978/168898994-4d81485a-018a-4595-9d6c-4e897fd782f1.png">

**Comment by argiepiano** [comment] 2022-05-17 20:06
Additional testing with the "normal" Home layout, placing existing content there and then updating - no problems. So it seems to be an issue/interaction between Layout Nodes and the new "block disable" feature.

**Comment by argiepiano** [comment] 2022-05-17 20:46
I've dug a bit into this issue. The problem lies with Layout Nodes, not with core. The issue is that Layout Nodes doesn't instantiate Block classes when rendering the blocks in the node layout - and therefore skips the important new code in `Block::_construct` that sets the block's new key `status` to 1 if `status` is not set. 

I'm closing  this now, as the best place to address this problem is within Layout Nodes.

**Closed by argiepiano** 2022-05-17 20:46 UTC
Labels: type - bug report
