### ISSUE TITLE
Dashboard: Consolidate the "Create content" and "Content overview" blocks

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4704] opened 2020-10-14 14:44 UTC
![image](https://user-images.githubusercontent.com/2423362/96005273-f7a0af00-0e44-11eb-8c03-19e4e58a2e5c.png)

Any reason to have a separate "Create content" block, when its links can be placed next to each content type in the "Content overview" block?

I would like us to make this a single block, and have it be more consistent with these other Dashboard blocks:

![image](https://user-images.githubusercontent.com/2423362/96005357-08e9bb80-0e45-11eb-94c3-a760af3e1772.png)

**Comment by olafgrabienski** [comment] 2020-10-14 14:52
Duplicate of https://github.com/backdrop/backdrop-issues/issues/3944?

**Comment by klonos** [comment] 2020-10-14 15:08
Related, but not duplicate @olafgrabienski ...over in #3944 @stpaultim is proposing to add the "add" content links in the content _type_ management block (which I don't think is ideal, and may in fact end up being confusing).

I'll whip up something quickly, and we can then compare the two solutions in their respective sandboxes. We can then make better-informed decisions I think.

**Comment by klonos** [comment] 2020-10-14 15:28
> ...The types of content items are only listed for information.

**Closed** 2020-10-14 15:29 UTC
Labels: status - duplicate, type - task

**Comment by klonos** [comment] 2020-10-14 19:48
I started working on #3944 and have changed my mind again re it being a duplicate of this issue 😅 

What I am proposing here is to merge the 2 blocks into a single one, whereas that other issue is about improving the "Create content" block, so that its content is being rendered as a table + to include separate "add" and "manage links".

I will still keep this ticket here closed though, as merging these 2 blocks may not be possible. You see, out of the box we have something like this:

![image](https://user-images.githubusercontent.com/2423362/96037453-8970e200-0e6e-11eb-9268-d3dbf51c72fb.png)

...but once we fix #3943, the "Content overview" block has the potential to show counts of approved and unapproved comments. So it could look like so:

![image](https://user-images.githubusercontent.com/2423362/96037770-ec627900-0e6e-11eb-8d91-86f114bb8c7b.png)

I'm not sure how we could fit all that information in a single block, and still have it look good. Here's what I have on my local:

![image](https://user-images.githubusercontent.com/2423362/96038003-36e3f580-0e6f-11eb-9215-968b490e694f.png)

...if I were to fit another column there for comments, then things would get pretty crumbed up 🤔

**Comment by stpaultim** [comment] 2020-10-14 20:19
@klonos - That final proposal looks like it's pretty much the same as my recommendation (https://github.com/backdrop/backdrop-issues/issues/3944), but with different text (which I am not wedded to). 

Here is screen shot of mine:

![Dashboard_Module__Show_link_to_manage_existing_nodes_of_specific_content_type_·_Issue__3944_·_backdrop_backdrop-issues-](https://user-images.githubusercontent.com/3144571/96040557-206a7980-0e30-11eb-87a1-c41a268690e8.png)

I assume that the "count" column links to a view of existing nodes of that content type (just like my "manage" does). If so, that how is your block any different from mine, other than the text?

You can easily test my version with the [Dashboard Plus module](https://backdropcms.org/project/dashboard_plus)
