### ISSUE TITLE
Deprecated function: Creation of dynamic property PDOException on PHP 8.x

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop/backdrop-issues#6140] opened 2023-06-09 04:05 UTC
## Description of the bug

Error when installing on PHP 8.x:

```
Deprecated function: Creation of dynamic property PDOException::$query_string is deprecated in DatabaseConnection->query() (line 743 of /backdrop/core/includes/database/database.inc).
Deprecated function: Creation of dynamic property PDOException::$args is deprecated in DatabaseConnection->query() (line 745 of /backdrop/core/includes/database/database.inc).
```

## Steps To Reproduce

Install on PHP 8.x. Error shows on site configuration window.

## Additional information

Found the same bug (solved) on Drupal 7: https://www.drupal.org/project/drupal/issues/3304883

**Comment by robertgarrigos** [comment] 2023-06-09 04:45
PR https://github.com/robertgarrigos/backdrop/pull/4 ready to review.

**Comment by klonos** [comment] 2023-06-09 06:01
Hey @robertgarrigos 👋🏼 ...this has already been discussed in the PR for #5927 here: https://github.com/backdrop/backdrop/pull/4445/files#r1210208091

Since the fix will be included in that PR, I think that we should close this issue and PR here as dupllicate.

Ping @indigoxela

**Comment by indigoxela** [comment] 2023-06-09 06:11
@robertgarrigos this is a clear duplicate of #5927, so your testing and feedback is welcome in that issue. Closing this one here.

**Closed by indigoxela** 2023-06-09 06:11 UTC
Labels: type - bug report

**Comment by robertgarrigos** [comment] 2023-06-09 13:49
Sorry, I have been looking for a previous issue. No prob.
