### ISSUE TITLE
wrong link to updates available after update to 1.19.0

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop/backdrop-issues#5099] opened 2021-05-19 05:30 UTC
**Description of the bug**

The first "updates available" link in status page, after applying update 1.19.0, is wrong. It goes to admin/config/system/updates, instead of admin/modules/update

The second link, within the text, is ok.

**Comment by indigoxela** [comment] 2021-05-19 06:30
That's not a bug, it's a feature. :smirk:  All those update pages have been unified, so now there's only one page for doing updates for all types.

See [this issue](https://github.com/backdrop/backdrop-issues/issues/2714) for details.

TLDR it was considered confusing, that there are so many different pages that do exactly the same thing. And even more confusing, that it was, for example, possible to update core from the theme update page.

**Comment by robertgarrigos** [comment] 2021-05-19 10:32
mmm the problem is that there are two different links for the same destination and text "updates available" in the same place (the title and inside the text. This is confusing.

**Comment by klonos** [comment] 2021-05-19 10:44
Perhaps we needed an update hook with #2714 to clear caches 🤔

**Comment by indigoxela** [comment] 2021-05-19 12:44
Strange, I updated several times now, and never had a problem with stalled content / links. But maybe because I did it via admin UI.

@robertgarrigos what are your usual steps to update (core or modules)?

**Comment by robertgarrigos** [comment] 2021-05-20 07:47
These have been my steps to updating backdrop, again, in my lando environment:

1. created a new backdrop install with v. 1.18.0
2. installed an outdated contrib module (backup_migrate v. 1.x-1.0.16)
3. updated core only
4. got this message (ok):
![Status_report___backdrop_lndo_site](https://user-images.githubusercontent.com/105581/118938132-9a2a8e80-b94e-11eb-8143-b64b194ee5d0.jpg)
5. Tried the first link (updates available - wrong page):
![System___backdrop_lndo_site](https://user-images.githubusercontent.com/105581/118938285-c6460f80-b94e-11eb-889c-291495e92b44.jpg)
6. Tried to clear cache - a few times (I didn't try this with my production site, could this be a lando problem??):
![Error___backdrop_lndo_site](https://user-images.githubusercontent.com/105581/118938376-de1d9380-b94e-11eb-863a-f431e47b195e.jpg)
7. updated backup_migrate
8. Tried the first link again (wrong page):
![System___backdrop_lndo_site](https://user-images.githubusercontent.com/105581/118938285-c6460f80-b94e-11eb-889c-291495e92b44.jpg)
9. Tried to clear cache (ok):
![System_updates___backdrop_lndo_site](https://user-images.githubusercontent.com/105581/118938752-440a1b00-b94f-11eb-9d2f-50827913e312.jpg)

I realize now that those two links in the status page when there are updates available were already pointing to different places. So, yes, it was confusing, and it's still confusing.

About the cache problem... no idea.

**Comment by indigoxela** [comment] 2021-05-20 08:35
These two links on the status page are supposed to point to different pages, the first one to /admin/config/system/updates - to run updates (but only if the updater and installer module are turned on), the second one to the update listing on /admin/reports/updates.

Looking at your second screenshot I realized that there's no item "System updates", so I suppose you have module Project Installer turned off on your site. Can you confirm that? Weird, because if I turn off these modules off, my status page doesn't show the link.

The error regarding Backup and Migrate has its own issues, so that's unrelated here.

The bug here seems to be that the link also gets shown, although the modules that provide that functionality are *not* enabled, or something else is weird with your site. Can you also check the file permissions on your filesystem, please?
Which modules are enabled?

**Comment by robertgarrigos** [comment] 2021-05-20 11:04
Thanks @indigoxela this was just a fresh install with lando of an outdated backdrop with backup and migrate. Project Installer was as default, which I don't know whether it is on or off. I guess we can close this issue, then.

**Comment by indigoxela** [comment] 2021-05-20 11:38
@robertgarrigos ... wait, not so fast. :smirk: You took the time to open an issue, so I'd really like to figure out it there's a bug or not.

To be honest, I never used lando and can't tell, how it installs Backdrop. If doing a regular install, the updater module is turned on - but then the path to the update page exists, and it also shows up as an item on /admin/config/system. (path has been /admin/modules/update (and several other pages) prior to 1.19)

You can easily check, if the modules I mentioned are enabled on the module listing page /admin/modules/list:

- Project Installer, which requires
- Update Manager

If it's not that, it still could be that something went wrong because the incompatible Backup and Migrate version broke the core update, and a database or config update didn't run properly. Updating from 1.18.0 to 1.19.0 requires update.php to be run.
(Note: we have an extra core issue for the BaM conflict)

If you see no problem (anymore) and everything works for you now, feel free to close this issue. :slightly_smiling_face:

**Comment by robertgarrigos** [comment] 2021-05-20 15:28
Lando just installs backdrop as you would do it in any other server, but locally and easier ;-). Project Installer and Update Manager are indeed on.

I've done a new update, from v. 1.18.2, without an outdated Backup and Migrate, and went as expected, well. No message of updates available, of course, but, I couldn't get admin/config/system/updates. It needed to clear the cache. Then yes, you can get that page.

So, that error with database on clearing cache should be related to Backup and Migrate. I tried another update process with another outdated module (metatag) and didn't have this error.

Finally, this bug is, then about this:

1.- Once updated, from 1.18.2, backdrop links and update available notice to admin/config/system/updates which is not available until you clear the cache. Provably the update process should do it for you.
2.- You say: "All those update pages have been unified, so now there's only one page for doing updates for all types." What is the unification? These two links: 
![Status_report___backdrop_lndo_site](https://user-images.githubusercontent.com/105581/118938132-9a2a8e80-b94e-11eb-8143-b64b194ee5d0.jpg)
are still pointing to two different pages. Or you are talking about something else?

**Comment by klonos** [comment] 2021-05-20 18:31
Hey @robertgarrigos 👋🏼 

- the first link is provided by this code: https://github.com/backdrop/backdrop/blob/1.x/core/modules/update/update.install#L159 (`$updates_path = 'admin/config/system/updates';` if the Project Installer module is enabled - otherwise it points to `$updates_path = 'admin/reports/updates';`)
- the second link is provided by this code in the Update Manager module: https://github.com/backdrop/backdrop/blob/1.x/core/modules/update/update.module#L559 (`'@available_updates' => url('admin/reports/updates', array('language' => $language))`)

- `admin/reports/updates` is the usual "Available updates" page
- `admin/config/system/updates` is the new unified "System updates" page

I hope that this is clear now.

**Comment by indigoxela** [comment] 2021-05-21 06:37
> Once updated, from 1.18.2, backdrop links and update available notice, if you have other outdated contrib modules, to admin/config/system/updates which is not available until you clear the cache. Provably the update process should do it for you.

If doing an update via UI, caches do get cleared. At least, that has worked for me several times.

If doing an update via filesystem (or ftp), which means to simply replace the files (core or contrib), caches do not get flushed automatically. Admins have to do that manually. I don't think, there's a possible fix for that. Backdrop does not "observe" the file system for changes - and couldn't.

Why flushing caches is important in this case: several paths got removed, another one has been added (admin/config/system/updates). Under the hood hook_menu() does the job - which is cached for performance reasons. Without flushing caches, the changes don't apply.

@robertgarrigos is my impression that you replaced files in the filesystem and directly went to the status page (without flushing caches) correct? In that case it's not astounding that the new path didn't work yet on your site. The status page always gets assembled by request, but the system path for the update link (hook_menu) isn't available until you flush caches.

**Comment by robertgarrigos** [comment] 2021-05-21 07:46
@indigoxela Yes, I update by replacing core files. Understood. Thanks for your time and explanations.

**Closed** 2021-05-21 07:47 UTC
Labels: type - bug report
