### ISSUE TITLE
DateThemeTestCase fails at certain times of day

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4180] opened 2019-10-31 15:03 UTC
This is somewhat a follow-up of https://github.com/backdrop/backdrop-issues/issues/3794

Turned out, that there's still a situation, when the test fails at a certain time of day.

I messed it, I fix it. (And hope that this test finally stops haunting me.)

---

PR by @indigoxela: https://github.com/backdrop/backdrop/pull/2963 (merged)
Follow-up PR by @klonos: https://github.com/backdrop/backdrop/pull/3003

**Comment by indigoxela** [comment] 2019-10-31 16:02
For the records - this is the test this issue is about:
`Start and end date on same day with timezone, with remaining days renders correctly. date_themes.test:137`

**Comment by herbdool** [comment] 2019-11-02 12:44
I seem to recall this test got a tweak recently (or maybe it was a similar one) but looks like it wasn't enough. I also noticed this error a couple times.

I think this looks good.

**Comment by quicksketch** [comment] 2019-11-06 18:48
Thanks @indigoxela and @herbdool! I've also seen the occasional date failures even after the last fixes, so it's worth merging this to see if we can fix those last intermittent issues. I really appreciate your continued attention to fix this @indigoxela!

Merged https://github.com/backdrop/backdrop/pull/2963 into 1.x and 1.14.x.

**Comment by klonos** [comment] 2019-11-24 03:40
I am still getting a lot of these myself, and see it PRs filed by others. Let's please keep it open; I'll have a go at it.

**Comment by klonos** [comment] 2019-11-24 05:05
...gotcha you little @#$!!!

This is a series of `dpm()s`:

```php
America/New_York
current hour => 0
current hour < 1
time start => Sat, 30 Nov 2019 22:03:06 -0500f2019-11-30T22:03:06-05:002822
time   end => Sat, 30 Nov 2019 23:03:06 -0500f2019-11-30T23:03:06-05:002822
expected => <span class="date-display-single">30.11.2019 - <span class="date-display-range"><span class="date-display-start">22:03</span> to <span class="date-display-end">23:03 America/New_York</span></span> </span><div class="date-display-remaining"><span class="date-display-remaining">To event remaining 7 days</span></div>
output   => <span class="date-display-single">30.11.2019 - <span class="date-display-range"><span class="date-display-start">22:03</span> to <span class="date-display-end">23:03 America/New_York</span></span> </span><div class="date-display-remaining"><span class="date-display-remaining">To event remaining 6 days</span></div>
```

Notice that it is "To event remaining 7 days" vs "To event remaining 6 days"? ...so it seems that the hour is rounded up ...which means that 23h becomes 00h ...which is next day.

Working on a fix...

**Comment by klonos** [comment] 2019-11-24 07:33
...so this entire thing we've added with the PR that got merged is not needed at all (and does not fix the problem):

```php
    elseif ($currentHour < 1) {
      // Make sure it's really 7 days.
      $dateTimeStart->modify('- 2 hours');
    }
```

If `$currentHour` is less than 1, it means 0h. So further down, when we set the end time to +1hr, it will still be within the same day/date (which is what we're after in this test):

`$dateTimeEnd->modify('+ 1 hour');`

OTOH, this is needed:

```php
    if ($currentHour > 22) {
      // Make sure start and end are the same day.
      $dateTimeStart->modify('- 1 hour');
    }
```

...because if the start time is 23h, when we add +1hr to the end date, that will be on the next day (which is why the test was failing before we fixed that).

**Comment by klonos** [comment] 2019-11-24 08:17
Here's a PR up for review: https://github.com/backdrop/backdrop/pull/3003

- When calculating remaining days, use `date_diff()->days` (available in PHP 5 >= 5.3.0, PHP 7), which also accounts for leap years. Manually calculating the diff, and then using `floor()` was returning +1/-1 day depending on time being close to midnight.
- Fixed strings like "To event remaining 1 day" which don't make sense.
- Switched the format for `$currentHour` to `G` instead of `H` (no leading zeros)
- Switched the start date offset to `'+ 1 week'` instead of `7 * 24` hours - we could make it `'+ 7 days'` if preferable; let me know.

**Comment by klonos** [comment] 2019-11-24 08:27
...ironically, the tests failed with another random failure 😅:

`fail Correct number of images (1) return 403 access denied. image.test:1792`

**Comment by indigoxela** [comment] 2019-11-24 12:47
@klonos my PR already fixed that. It has been merged 18 days ago. Please make sure, that you have that in your dev: https://github.com/backdrop/backdrop/commit/376f740d290ebe0ae521adac4cbda2e2a89b6f83

**Comment by indigoxela** [comment] 2019-11-24 13:38
@klonos I like your changes in theme_date_display_combination(). It's a lot smarter to use an up to date way to calculate the diff (in a php5+ way). This gets the date module another step forward.
And improving the wording is always good.
But that should actually go to another (new) issue.

Your PR reverts my previous fix. That will bring the "6 vs. 7" days problem back.

Looking at one of your recent PRs, I see:
`This branch is 4 commits ahead, 349 commits behind backdrop:1.x.`

Your branches lag behind! If you also have testing trouble with branches that are up to date with core, re-opening this issue is correct. Otherwise ... :wink: guess what...

**Comment by klonos** [comment] 2019-11-24 15:26
> But that should actually go to another (new) issue.

`Start and end date on same day with timezone, with remaining days renders correctly. date_themes.test:137`

@indigoxela this issue is about fixing that random failure ^^ ...your PR was merged into 1.x, and it was meant to fix this, **but it has not**.

I have seen it happen to my PRs, as well as PR by other people ...which are against 1.x ...which includes the fix.

>Your PR reverts my previous fix...

Yes it does - intentionally...

> ...That will bring the "6 vs. 7" days problem back.

No it won't 🙂 ...the change in your PR has nothing to do with the actual problem that was causing this ...which is the way `$remaining_days` was being (mis)calculated in `theme_date_display_combination()` (using `floor()` etc.).

> Your branches lag behind!

Yup, I know 😓  ...but that has nothing to do with the random failures. My entire fork is behind, that's why you see that notice. This does not cause any trouble with my local or my PRs though, because on my local I use the latest  https://github.com/backdrop/backdrop 1.x (so that I don't need to constantly be pulling and resolving conflicts, and keeping my fork in sync with `backdrop/backdrop`). Here's what I do to achieve that:

```
git clone https://github.com/backdrop/backdrop docroot
cd docroot
git remote add klonos https://github.com/klonos/backdrop
git checkout issue-1234
dev dev dev...
git add ...
git commit ...
git push -u klonos issue-1234
```

...I have found that this way to work fine all these years. I always work off of latest 1.x from `backdrop/backdrop`, make changes there, and then push the branch on my fork. So you see, nothing "outdated" ends up on my local or in my PRs.

**Comment by indigoxela** [comment] 2019-11-25 08:32
@klonos let's give your approach a try. (I can't mark comments as resolved on your PRs, but my latest comment should indicate my approval.)

**Comment by klonos** [comment] 2019-11-25 10:49
Thanks @indigoxela 👍 ...I have tested my approach pretty thoroughly I like to believe. I have simulated different timezones, so to achieve `$currentHour` being 00, 23, as well as any other not-close to midnight hour. I am pretty confident about it actually.

**Comment by indigoxela** [comment] 2019-12-11 07:43
@klonos As testing the test is a bit hard because of it's random failures, I concentrated on testing your changes in date.theme.inc.

Your PR has one glitch, that doesn't appear without the patch:

If a date is on the same day, but some hours back, the "remaining" text appears, although it shouldn't.

"Less then 1 day remaining to event." (But the field date is several hours in the past)

Maybe you need two date_diff? Check if the date isn't already in the past (check time), then get the remaining days?

**Comment by klonos** [comment] 2019-12-11 20:44
> If a date is on the same day, but some hours back, the "remaining" text appears, although it shouldn't.

Oh yes, I have not thought of that @indigoxela, nor tested for it. If I understand this correctly though, you are referring to the use case of an event that has happened already; in which case, the problem is with the logic in `date.theme.inc` - not with the test fixes. So we need to do the following:

- Account for this use case in `date.theme.inc`, and have the text being shown to users reflect that (something like "Event date/time has passed").
- Either create a new test case for this use case, or update the logic in the current test to account for it too.

TBH, this sounds like a different issue to what we are trying to solve here, and in fact must be a pre-existing one (without your PR or mine for that matter). This issue here though was/is to fix the random test failures, so separate issue perhaps?

**Comment by indigoxela** [comment] 2019-12-12 07:40
> This issue here though was/is to fix the random test failures, so separate issue perhaps?

I think, you catched something. You seem to be right, that my previous PR for the test didn't cover all cases. I see at least another test fail in one of your recent PR (which has the previous "fix" already).

As this test is related to exactly that part of theme code, I think we can handle both here, theme code and related test code.
Calculating the diff in a more modern way (via DateTime object) is a good idea.

> something like "Event date/time has passed"...

That would rather be a new feature, as up until now nothing is shown if the date has passed. The display settings help text says "Show remaining days" - I'm not sure if users would expect an "Event has passed" text.

**Comment by indigoxela** [comment] 2019-12-13 12:45
I tried to figure out, what is wrong with the test... It's the "+ 1 week" offset, that should be relative to the _default (local) timezone_, not `$tz`.

So we should create the offset first, apply the timezone afterwards. Here's a snippet:
```
$default_tz = date_default_timezone();
// Make sure it's seven days from local timezone.
$dateTimeStart = new DateTime('+ 1 week', new DateTimeZone($default_tz));
$dateTimeStart->setTimezone(new DateTimeZone($tz));
$currentHour = $dateTimeStart->format('G');
```
@klonos What do you think?

**Comment by klonos** [comment] 2019-12-18 21:00
Hey @indigoxela 👋 ...sorry for the late responce here.

So I still think that the potential issue with the "remaining" text should be a separate, follow-up PR. The default timezone thing though could be handled here.

To be clear, I see no flaw with the actual implementation in the PR. Here's why:

- `$dateTimeStart` is created based on `$tz`
- `$currentHour` is set based on `$dateTimeStart` (which is based on `$tz`)
- `$dateTimeEnd` is a clone of `$dateTimeStart` (which is based on `$tz`)

...so basically, all variables are set based on the same timezone variable (`$tz`), which is OK, because all offsets work off of those dates. So all good 👍 

Having said that, I am not sure why we are using `$tz = 'Europe/Moscow';` specifically for the tests in the first place; so your suggestion to use `date_default_timezone()` makes sense. I will update the PR to use that instead. Thanks 👍

**Comment by klonos** [comment] 2019-12-18 21:21
I've updated the PR to use `date_default_timezone()`, with https://github.com/backdrop/backdrop/pull/3003/commits/9075d4564990752b590aba2344c3359fd7e09ea1

**Comment by indigoxela** [comment] 2019-12-27 11:57
@klonos many thanks for your update.

The date_diff() thing still seems to be pending (same day, but already in past...). Maybe you can dig into this after Christmas holidays. I'll stay tuned.

**Comment by quicksketch** [comment] 2019-12-27 18:40
I merged https://github.com/backdrop/backdrop/pull/3003 as we seem to be in agreement that it's worth trying. The code there is along the right lines, and I think we agree that using `date_diff()` is going to get us a better result that doing integer math on timestamps.

During this past weekly meeting @klonos recapped this again, stating that he managed to reproduce the current failures locally by adjusting his machine's clock. And testing before and after his adjustments, the problem seems to be fixed. As we're seeing this failure a lot still on PRs, I'm hoping this merge will reduce the number of failures we get from the automated testing.

If there is still more adjustment to be done (even if it means reverting something), please create another PR. I'm closing this for now but reopen if needed. Thanks @indigoxela and @klonos for continuing to look into this!

**Closed by quicksketch** 2019-12-27 18:40 UTC
Labels: pr - needs code review, pr - needs work, status - has pull request, type - bug report

**Comment by klonos** [comment] 2019-12-27 20:16
Thanks @quicksketch 👍 ...follow-up here: #4248
