### ISSUE TITLE
Fixed: Symlink to document root causing several update and install issues

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3008] opened 2018-03-27 22:34 UTC
## Describe your issue or idea
When attempting to update on_the_web module using the updater at admin/modules/update, my update succeeded on my local site, but failed on my live site, with the following error:
`File Transfer failed, reason: path/to/www/modules/contrib/on_the_web is outside of the path/to/docroot`. 

That error is incorrect, as on this server `www` is a symbolic link to `docroot`. 

I suspect there's something about this symlink that's causing the problem. Noting the issue here incase anyone else is experiencing something similar.

---

Besides module updates, this problem also affects:

- core updates
- theme updates
- layout updates
- module/theme/layout installs via URL (via dialog "Manual installation")

---

~PR by @bradbulger: https://github.com/backdrop/backdrop/pull/3690 (this wider change has its own issue now)~
~PR by @indigoxela: in same function, but simpler https://github.com/backdrop/backdrop/pull/3706 (outdated)~
PR by @indigoxela: fixes it in the updater, not in file transfer: https://github.com/backdrop/backdrop/pull/3708

**Comment by bradbulger** [comment] 2018-12-04 17:44
I have a similar problem in, I think. I'm running the site at https://localhost/mydirectory/. Apache looks in /var/www/html for localhost directories. /var/www/html/mydirectory is a symlink to /home/www/mydirectory for reasons.

I changed FileTransfer's checkPath function to run everything through backdrop_realpath() before comparisons and that stopped the problem. I'm hoping that means I'll be able to move modules/contrib and modules/custom back up above the docroot and use symlinks for them, which was my original problem (I thought).

**Comment by klonos** [comment] 2019-08-26 18:17
Thanks for taking the time to confirm this @padprint 👍

**Comment by bradbulger** [comment] 2019-10-17 21:15
I believe I have a fix for this but I want to test it under more circumstances. I can't figure out what kind of configuration would result in the FileTransfer object having a value for its "chroot" property. If anyone has thoughts about how to create an installation so that it would be set to something, that would be helpful.

**Comment by olafgrabienski** [comment] 2020-03-25 22:59
Referencing a related forum post: https://forum.backdropcms.org/forum/error-update-modules-1and1

**Comment by olafgrabienski** [comment] 2020-11-23 12:34
I've tested [the PR](https://github.com/backdrop/backdrop/pull/3406) on a site hosted by Strato, and it fixes the problem for me. Here's what I did:

1. Made sure I had a site with an outdated module.
2. Went to `admin/modules/update`, hit the checkbox of the module, let Backdrop download the update, and tried to continue.

Result: Backdrop stopped with a file transfer error.

After applying the PR to my site and repeated the steps mentioned above, the update went just fine.

@bradbulger Do you need more details about the directory structure of the site to evaluate the fix further?

**Comment by bradbulger** [comment] 2020-11-23 20:00
Is the website document root a symlink to another location? That's how our sites are set up.

**Comment by olafgrabienski** [comment] 2020-11-24 15:11
> Is the website document root a symlink to another location?

I'm not sure. It's a shared hosting, and I don't know how they organize the directories. Do you see if it's a symlink thing reading the following message?

`/home/strato/http/premium/rid/81/23/SOME-LONG-ID/htdocs/backdrop-dev/modules/backup_migrate is outside of the /mnt/web214/c3/23/SOME-LONG-ID/htdocs/backdrop-dev`

As I said, your PR fixes the issue for me. Not sure if and how to test further.

**Comment by bradbulger** [comment] 2020-11-24 20:23
That looks like it's the case, yes - two paths to the same location.

**Comment by olafgrabienski** [comment] 2020-12-18 16:11
@jenlampton Are you maybe up to have a look at the code of the PR? And/or label the issue with a milestone for the next bugfix release? (I've added the milestone candidate label.)

**Comment by indigoxela** [comment] 2020-12-19 10:00
I finally found the time to test this locally:

1. Moved the web directory and set a symlink to the DocumentRoot (made sure the site still works)
2. Installed an outdated version of a module via UI - that worked fine BTW
3. Went to to admin/reports/updates - the available update shows up
4. Tried to run the updater - failure on core/authorize.php (see screenshot below)
5. Applied the [patch](https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/3406.patch)
6. Back to admin/reports/updates - the available update shows up
7. Tried to run the updater again, no failure this time, got a success message
8. Back to admin/reports/updates - the available update *still* shows up :confused: 
9. Repeated step 7 and 8, same result...
10. Flushed "Update data"
11. Repeated step 7 and 8, same result, the update still hasn't been done, the module version was still old

Odd.
I exported database table "cache_update" to figure out what's going on there... I suspect, the update cache is the culprit here.

OK, another testing approach:

1. Uninstalled that module
2. Flushed all caches
3. Installed that module again
4. Ran cron, available update shows up
5. Ran update again, got success message
6. Back to admin/reports/updates - the available update still shows up
7. Verified a final time that the module *has not* been updated (checked the module's info file)
8. Nothing in dblog, no errors

Can anyone confirm this behavior? Note: it *might* be unrelated, but I'd like to verify that the PR not only makes the error go away, but also gets the update working.
Funny enough, that *installing* modules works without any problem without this patch.

This error **got fixed**, though:
![update-failed](https://user-images.githubusercontent.com/842066/102686640-3e19dd80-41e9-11eb-8562-60d8c6c24b74.png)

**Comment by indigoxela** [comment] 2020-12-19 10:36
Yet another approach

1. I manually downloaded an outdated version of a theme
2. Then I enabled the "Also check for updates of disabled modules, themes, and layouts" setting and ran cron
3. Ran the update
4. Verified that the disabled theme has been updated :+1:

I need to dig a little deeper, but I'm already (almost) convinced, that the odd behavior described in my previous comment is totally unrelated to this PR.

**Comment by olafgrabienski** [comment] 2020-12-20 13:01
@indigoxela Thanks for testing the PR!

After having tested with the other approach, do you think the initial behavior of not updating is indeed unrelated?

**Comment by indigoxela** [comment] 2020-12-20 13:59
> After having tested with the other approach, do you think the initial behavior of not updating is indeed unrelated?

Yes, unrelated. It has been caused by some sort of update caching, although I don't fully understand, why.

Regarding the PR code:

@bradbulger that's a lot of code to solve a single problem (de-referencing a symlink, if I get it right?).

What baffled me when trying to test the PR was, that *installing* new projects works without any problems, only the updater fails. Could that mean that the base problem is somewhere else (authorize.inc?) and the solution is already there - somewhere in the installer code?

I admit, I'm not familiar with that part of Backdrop and probably can't do code review here.

**Comment by indigoxela** [comment] 2020-12-20 14:58
Maybe interesting in this context is an [older issue](https://github.com/backdrop/backdrop-issues/issues/1297), which caused BACKDROP_ROOT in authorize.php to be switched from  `getcwd()` - which resolves symlinks to `dirname(dirname($_SERVER['SCRIPT_FILENAME'])))` - which doesn't.

**Comment by bradbulger** [comment] 2020-12-21 17:52
That's mostly debugging code - as I said, I don't feel I was able to test all possible circumstances. This was my local patch that we are using on my site. It could be trimmed down considerably. If there is some deeper or more fundamental problem, whoever finds it would be welcome to fix it.

**Comment by jenlampton** [comment] 2021-01-14 22:13
I think the new error handling looks great, the PR is RTBC from me. Let's get some core committer eyes on it to see what they think.

**Comment by quicksketch** [comment] 2021-01-16 00:25
I'm going to have spend a little time reviewing this PR. I don't think I should hurry it into today's release.

**Comment by BWPanda** [comment] 2021-01-23 09:45
I tried looking into this issue, but after an hour or so I had to give up as it's beyond my comprehension sadly. I can tell you though that the PR as it currently stands will very likely not be merged as-is. By the author's own admission it's "mostly debugging code". So I'm going to mark this as 'needs work' and assign it to @quicksketch who said he'll take a look at it.

**Comment by BWPanda** [comment] 2021-01-23 09:48
If it helps, I was able to reproduce the problem my creating a directory called `symlink`, putting the following Lando config file in it, downloading Backdrop into a `backdrop` sub-directory, then creating a symlink `www` pointing to `backdrop`:

```yaml
name: symlink
recipe: backdrop
config:
  webroot: www
  database: mariadb
```

![image](https://user-images.githubusercontent.com/2385329/105575011-59fe3980-5dbc-11eb-8b28-bca2c66aafe2.png)

**Comment by klonos** [comment] 2021-01-24 09:47
Thanks @BWPanda 🙏 ...that'll help me test/troubleshoot this. In fact, I might as well change all my local sandboxes to have that setup, so to catch any existing/future issues.

**Comment by bradbulger** [comment] 2021-07-28 01:04
I'm not sure what the status of this is, but one thing I found looking at it today is that apparently none of the logging modules are enabled when this FileTransfer method runs? The watchdog() function itself runs but there are no modules implementing the hook.

Switching to error_log() instead, I've found several issues in the changes I made. I will try to sort that out.

**Comment by bradbulger** [comment] 2021-07-29 19:18
I rewrote the change and removed the debugging code. The issue seemed to be that checkPath() gets called on paths that may or may not exist, so a simple realpath call will fail. I added code to back up the path until it gets to an existing directory if the initial path does not exist. If the result has a common root with the realpath of the jail, it passes, otherwise it throws the exception.

Probably it would be good to test this on Windows - I think the way realpath() works there puts some limits on what's possible.

Do I need to close the old pull request and make a new one?

**Comment by indigoxela** [comment] 2021-07-30 06:40
> Do I need to close the old pull request and make a new one?

Hm, you already closed it? It's actually your decision, if you want to continue working on the same PR or start a fresh one.

**Comment by bradbulger** [comment] 2021-07-30 07:23
I think it automatically closed? Because I removed the previous commits, so
there was a time when it was identical to current 1.x.

If it works as it is, might as well leave it. I'm not totally clear on the
process. Whatever you need me to do.

**Comment by olafgrabienski** [comment] 2021-07-30 07:42
> If it works as it is, might as well leave it.

I guess, having a PR is necessary:

*All development on Backdrop core happens on Github by pull requests.*
  https://docs.backdropcms.org/documentation/contribute-to-backdrop-core

**Comment by olafgrabienski** [comment] 2021-08-03 21:41
Oh, I only saw now that https://github.com/backdrop/backdrop/pull/3406 has been reopened a few days ago!

I've applied the PR to a test site which usually can't be updated via the Backdrop user interface – same steps and hosting as mentioned in https://github.com/backdrop/backdrop-issues/issues/3008#issuecomment-732135007 and below. With the PR, updating both core and modules work without any issue. That's great news!

So, still works for me. Is somebody up to make a code review of the current PR?

**Comment by bradbulger** [comment] 2021-08-04 17:18
yeah, the PR is open. the automated tests are failing, but there seems to be some system problem involved there. the tests work fine in the Tugboat build.

**Comment by indigoxela** [comment] 2021-08-05 05:42
> the automated tests are failing, but there seems to be some system problem involved there

Unfortunately our Zen.CI setup puts developer patience to the test (sometimes even more than the actual code, it seems...).

**Comment by bradbulger** [comment] 2021-08-13 03:02
I tried running on the base 1.x code with Clean URLs turned off, without any symlinks involved, and I was able to install updates for Webform and for core Backdrop. I get 20 failures from Installer UI - aka Installer (module) - tests. I get 2 failures with Clean URLs enabled again, so I don't know about that. Out of scope.

Running with my change applied, I see the same results.

**Comment by bradbulger** [comment] 2021-08-14 01:22
Comment from @quicksketch on the PR: "Symlinking individual directories is indeed broken by these changes."

Is that a separate issue? I don't know how people will think about that. If you have the core code in one place, and link directories like '/modules/' to somewhere entirely separate, the current idea of the "jail" can't handle that, can it?

**Comment by indigoxela** [comment] 2021-08-14 07:09
Great! We get progress here. But there's a problem with the PR: instead of rebasing it in the latest core changes, the CKEditor update shows up as a part of the PR - I don't think it should.

**Comment by bradbulger** [comment] 2021-08-15 19:20
Is there a way to do that other than closing that PR and starting from a new branch?

**Comment by indigoxela** [comment] 2021-08-16 05:57
> Is there a way to do that other than closing that PR and starting from a new branch?

Hm, I don't think so, at least no easy way.

**Comment by bradbulger** [comment] 2021-08-16 17:14
I'll do that, but before I push it up and start a new PR, do we need to think about symlinks inside the document root, that link to paths entirely outside of it? I'm now wondering if we have a test case where failure is the correct result of the test.

**Comment by quicksketch** [comment] 2021-08-17 22:13
> Is there a way to do that other than closing that PR and starting from a new branch?

You can `git rebase 1.x` and then `git push origin HEAD -f` to force push the rebased version into your PR.

> we need to think about symlinks inside the document root, that link to paths entirely outside of it? I'm now wondering if we have a test case where failure is the correct result of the test.

I think ideally we'd keep the current behavior in addition to the new behavior, where either the destination directory is a symlink or the entire web root is a symlink. Both should work.

**Comment by bradbulger** [comment] 2021-08-18 19:22
I rebuilt the original branch and opened a new PR. I confirmed that on the Tugboat site, the Installer tests work, and I was able to download & install a copy of Devel using the UI. We'll see how the automated tests go.

**Comment by indigoxela** [comment] 2021-08-19 06:22
> We'll see how the automated tests go.

W00t! Passing. :smiley:

**Comment by bradbulger** [comment] 2021-08-19 19:59
I have been walking through this some more. Say the actual no-links path to the root - the directory containing index.php, BACKDROP_ROOT - is /var/www/backdrop/. The apparent path being checked is /var/www/backdrop/modules/contrib/devel. /var/www/backdrop/modules is a link to /var/www/modules. Should that pass or fail?

**Comment by bradbulger** [comment] 2021-08-20 06:31
the root of the problem, so to speak, is that jail is a realpath, but the paths being checked are usually (maybe always?) webserver paths.

In the current 1.x setup, it's taking the first length-of-jail characters from the given path, and only then running it through realpath. so if there's a symlink on the way to the docroot, that will fail. if any symlinks in the given path are below the docroot, they're ignored, and so it passes, even though strictly speaking the ultimate destination is outside of the jail. that's also why paths that don't exist yet can pass - it's only looking at the length-of-jail part of the path.

i have a version of my changes - not yet committed - that will keep walking up the given path - from /a/b/c/d to /a/b/c to /a/b etc. - and running realpath on that to compare to the jail. that will pass both docroot symlinks and lower symllinks. so if your files are like:

/www/symroot -> /www/mycode/backdrop
/www/modules
/www/mycode/backdrop/index.php
/www/mycode/backdrop/modules -> /www/modules

and the path being checked is /www/symroot/modules/contrib/devel
the realpath of that is /www/modules/contrib/devel, so that fails
so it will walk up that path until it gets to /www/symroot, which realpath resolves to /www/mycode/backdrop, which is the jail. so it will pass.

that seem like a desirable result to me but i lean towards "let me do whatever i want" as a rule, so.

**Comment by indigoxela** [comment] 2021-08-20 07:00
After all this forward and back, I wonder, why we never questioned the root cause of the problem.
Drupal 7 doesn't suffer from this bug.

The change that seemed to have broken everything was: https://github.com/backdrop/backdrop/commit/4a9c9a68270345f71a44a4146cee23dbca8905a3 from 2016.

What breaks if we revert that and switch back to `getcwd()`? There doesn't seem to be a related issue to that commit, so I'm not sure about the reason for this change. @quicksketch do you happen to remember?

**Comment by indigoxela** [comment] 2021-08-20 07:03
If I read the comments in that commit correctly, the change was made for some developy stuff (Zen.CI sandbox setup).

So in fact it broke a lot of real-world stuff (hosting providers using symlinks) to fix a sandbox? :stuck_out_tongue_winking_eye: 
(Yes, I tend to ask heretic questions from time to time.)

**Comment by olafgrabienski** [comment] 2021-08-20 07:49
> Drupal 7 doesn't suffer from this bug

Good point! On the other hand, there is a current approach to fix the issue. I don't have the technical expertise to discuss if a rollback is a better option, but at least I found the corresponding issue for the change in question (it was mentioned in the docblock): https://github.com/backdrop/backdrop-issues/issues/1297

**Comment by indigoxela** [comment] 2021-08-20 08:03
> at least I found the corresponding issue for the change in question

Nice catch, I should learn to read more carefully. :+1: 

> On the other hand, there is a current approach to fix the issue.

Unfortunately with a lot of forward and back, though.

@bradbulger have you ever considered the use of `is_link()` or `readlink()`?

**Comment by bradbulger** [comment] 2021-08-20 18:27
> Drupal 7 doesn't suffer from this bug.
I didn't even realize it had a UI for doing updates. In Drupal 7, at least, the path given to checkPath has already had the docroot part converted to a realpath. In the above scenario, checkPath is given /www/mycode/backdrop/modules/contrib/devel. So everything is fine.

When Backdrop installs a module, the path that gets checked looks like that as well. It's only when it updates a module that the path is the webserver path - /www/symroot/modules/contrib/devel.

[Wrong DRUPAL_ROOT with non-standard code structure](https://www.drupal.org/project/drupal/issues/1792310) is a somewhat related issue that's been going for the usual years upon years. 

BACKDROP_ROOT is already getcwd() from index.php. That's what I meant when I said that jail is already a realpath. If the jail was also based on $_SERVER[SCRIPT_FILENAME] it would eliminate these issues, because then you would be doing an apples to apples comparison. But I imagine that's a big step to solve a small problem. 

I apologize for the back & forth, I am trying to understand the intention of the function. What scenarios are we trying to prevent, and which ones do we want to allow?

> @bradbulger have you ever considered the use of is_link() or readlink()?
As a replacement for backdrop_realpath()? I don't get what you have in mind.

**Comment by bradbulger** [comment] 2021-08-20 19:53
I noticed that run-tests.sh was doing this:

`define('BACKDROP_ROOT', realpath(dirname(dirname(dirname($_SERVER['SCRIPT_FILENAME'])))));`

I tried that approach, of running realpath on the value being set, in all the places that BACKDROP_ROOT gets defined. So far everything seems OK.

**Comment by indigoxela** [comment] 2021-08-21 07:42
@bradbulger I wonder what the status of your PR (and this issue) currently is. Are you still elaborating your approach or are you working on something completely different? Or did you settle on your approach and your PR is ready for testing and review?

And a general question: what are we supposed to test? Sure, docroot symlink and module update. But is there something additional, we have to keep an eye on?

@quicksketch is there something you recommend to check when doing local testing?

**Comment by bradbulger** [comment] 2021-08-22 04:53
I have code that will work in the existing system and allow all the cases I outlined above - the docroot being a symlink as well as directories under the docroot being symlinks.

I haven't committed it yet because of the discussion of changing the value of BACKDROP_ROOT instead. I don't know if people would prefer to do that instead.

**Comment by indigoxela** [comment] 2021-08-22 10:54
> I have code that will work in the existing system and allow all the cases I outlined above
> ... I haven't committed it yet 

Please commit. :+1:  Discussions are easier, if we're looking at a concrete implementation.

I'd like to get this bug fixed, because several people are waiting for it. Currently updates simply do not work at all in many hosting environments (docroot = symlink), which is really bad for Backdrop in general.

And many thanks for your patience and perseverance. :wink:

**Comment by bradbulger** [comment] 2021-08-24 22:53
I am trying to test changes out with a ddev installation and getting very peculiar results. There is no error, it downloads the zip file of the module update, unpacks it into a directory in /tmp, and then whatever update.php I think? is supposed to do, doesn't happen. No kind of error or problem or warning, but the original module files never change. I've opened up file permissions wide, doesn't matter. I haven't traced my way to the part of the code where it is supposed to change what is in the real module directory - if anybody can point to that, I can maybe see what is going on.

I think this might just be an artifact of ddev somehow, but it still seems not great that it can happen.

**Comment by indigoxela** [comment] 2021-08-25 05:57
@bradbulger I'm assuming, you're trying to test your most recent changes - the ones you didn't commit yet? This makes it hard for us to also test and provide feedback. :wink:

**Comment by bradbulger** [comment] 2021-08-25 16:34
I thought so, but no, I'm seeing the same problem on a vanilla 1.x installation, that is set up as describe in the PR comments, where all the files in the document root are links into a backdrop/ directory except files/ and settings.php, as described by @quicksketch in [this comment](https://github.com/backdrop/backdrop/pull/3682#issuecomment-898087178).

**Comment by bradbulger** [comment] 2021-08-25 16:48
I can recreate this on the tugboat linked to the current PR. I am doing the update without going into maintenance mode. Try to update Backup and Migrate. Everything proceeds without error, but the update does not really happen.

**Comment by bradbulger** [comment] 2021-08-25 16:59
Ha. I tried creating a sandbox from the link on the main backdropcms.org page, and module updates fail because "File Transfer failed, reason: /var/www/html/modules/devel is outside of the /var/lib/tugboat/backdrop".

**Comment by bradbulger** [comment] 2021-08-28 01:08
What about @quicksketch's changes to core/misc/zen-ci/init_test.sh, btw?

**Comment by indigoxela** [comment] 2021-08-28 09:08
> What about @quicksketch's changes to core/misc/zen-ci/init_test.sh, btw?

Hm, good question. We're currently trying to switch from Zen.CI to Github Actions, so any effort in that direction may be futile. :thinking:

**Comment by indigoxela** [comment] 2021-08-28 11:55
Maybe it's necessary to better explain my current concerns with the changes in FileTransfer class:

Abstract class FileTransfer is used for all sorts of - ehm - file transfers, SSH, FTP...
And there's the API (hook_filetransfer_info, hook_filetransfer_info_alter), which makes it hard for me to understand, where these changes strike and might break something.

That checkPath is a _protected final_ doesn't make it easier for us, because the possible places to fix something are limited.

The way I currently understand things - checkPath isn't actually meant to get fed with paths containing unresolved symlinks (correct me if I'm wrong). At least at the time this class was written, all paths already were real file system paths - note: that's an assumption. I'm unclear, where of if stream wrappers play a role here.

The FileTransfer classes so far don't care about BACKDROP_ROOT in any way, it's the updater module that feeds in paths still containing symlinks. And that's the root cause for the problem this issue tries to fix - failing updates.

Call me coward :fearful:, but currently I'm leaning towards the workaround-ish change in the Updater classes ([PR 3708](https://github.com/backdrop/backdrop/pull/3708)), as this gives me confidence, that we don't accidentally break something else - something we might not be aware yet.

But if there are good arguments, why the change *has* to be in checkPath, I'm all ears.

**Comment by bradbulger** [comment] 2021-08-28 17:13
Why keep the symlink in the definition of BACKDROP_ROOT in the first place?

I think it would be OK to separate the problems, and open a separate ticket
about checkPath().

**Comment by indigoxela** [comment] 2021-08-30 06:07
> Why keep the symlink in the definition of BACKDROP_ROOT in the first place?

In Issue #1297 it was discovered that it's impossible to install Backdrop when the "core" directory is outside the docroot. I'm not sure, why this was important, but since then (2016) it works that way and changing back from `dirname(dirname($_SERVER['SCRIPT_FILENAME']))` to `getcwd()` would break that.

> I think it would be OK to separate the problems, and open a separate ticket about checkPath().

Yeah, that problem seems to need a little more (and thorough) discussion, while the module update problem should (and could) get fixed quickly - even if that means we settle on the workaround for now. @bradbulger what do you think, shall we switch to https://github.com/backdrop/backdrop/pull/3708 here and open a new issue for your PR and checkPath()?

**Comment by bradbulger** [comment] 2021-08-30 15:46
I understand about #1297. I'm suggesting that you can use realpath() around the dirname(...) result.

But in any case, yes, I'll open a new issue about checkPath() and close the PR on this ticket.

**Comment by olafgrabienski** [comment] 2021-08-30 20:31
I'm not sure about the current status. Is there consensus that PR 3708 is the way to go? And would it then make sense to test it manually in my shared hosting, or is it already sufficiently tested according to https://github.com/backdrop/backdrop-issues/issues/3008#issuecomment-907349358?

**Comment by indigoxela** [comment] 2021-08-31 05:51
@olafgrabienski sorry about the confusion. Yes, https://github.com/backdrop/backdrop/pull/3708 is the one to test here.

Testing in real (and different) environments is totally welcome - there can never be too much testing. :+1:

**Comment by olafgrabienski** [comment] 2021-09-01 08:49
Let's see: After applying https://github.com/backdrop/backdrop/pull/3708 in my shared hosting environment, I was able to update modules using the UI 👍 , but *not* Backdrop core.

After changing also line 17 of system.updater.inc, I *was* able to update core.

`- return BACKDROP_ROOT;`
`+ return realpath(BACKDROP_ROOT);`

Not sure if this is reasonable, though.

However interesting that updating core fails in my environment. Brad mentioned in https://github.com/backdrop/backdrop-issues/issues/3008#issuecomment-907349358 it worked with the same PR. Maybe my environment is different? In case it helps, I get an error message like the following when trying to update core:

File Transfer failed, reason:
`/kunden/homepages/some-id/another-id/htdocs/backdrop` is outside of the
`/homepages/some-id/another-id/htdocs/backdrop`

**Comment by olafgrabienski** [comment] 2021-09-01 08:52
Side note: In my environment https://github.com/backdrop/backdrop/pull/3708 fixes also the manual module installation using a URL.

**Comment by indigoxela** [comment] 2021-09-01 09:00
> I was able to update modules using the UI , but not Backdrop core.

Many thanks for testing! :+1: Yes, the change in line 17 seems reasonable. Will do some more checks locally, to make sure it also works when "core" itself is a symlink - to prevent possible side effects (#1297 again).

> ...3708 fixes also the manual module installation using a URL.

Another nice catch, many thanks for the hint. Will also check installation using URL.

**Comment by indigoxela** [comment] 2021-09-01 09:37
Confirmed, `realpath(BACKDROP_ROOT)` in class CoreUpdater fixes broken core updates, when the docroot is a symlink.

I verified that there are no side-effects, when "core" itself is a symlink with following setup:

- The docroot is a real directory
- Core is outdated (1.19.2), patch applied
- Move "core" outside and created the symlink: `ln -s ../core/ core`
- Flush all caches
- Update core via UI - it works
- Also check the actual files in file system - everything as expected

And, yes, installing from URL does indeed work now. I wasn't aware that this is also broken since 2016 with docroot symlinks.

Tests are "passing" - besides the usual internal server error and one of our "random buddies". :roll_eyes:

**Comment by bradbulger** [comment] 2021-09-01 15:52
I never tried to update core because I assumed that the update would erase my patch halfway through. IF you got it working, that's good.

**Comment by indigoxela** [comment] 2021-09-02 07:01
> I never tried to update core because I assumed that the update would erase my patch halfway through.

After the update all patches are gone, of course, but the update itself is working fine. (All these tests should obviously never be done on a production site.)

**Comment by indigoxela** [comment] 2021-09-07 07:35
Rebased. Some random test failures, but still ready for review.

**Closed** 2021-09-15 17:25 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2021-09-15 17:28
Yay, looks like we're all agreeing that https://github.com/backdrop/backdrop/pull/3708 is a simple and safe fix. Although I think more comprehensive symlink handling would be good, this fixes the problem that everyone is experiencing specifically with Installer and Update modules.

I've merged https://github.com/backdrop/backdrop/pull/3708 into 1.x and 1.19.x. Huge thanks especially to @bradbulger and @indigoxela for their patience on this and working together to arrive at a solution. Kudos to @olafgrabienski, @padprint, @BWPanda, @jenlampton, and @klonos for their help validating and testing solutions!
