### ISSUE TITLE
Remove the code initializing $variables from l() and change the code to directly use the function arguments

### ISSUE THREAD

**Issue by kiamlaluno** [backdrop/backdrop-issues#5996] opened 2023-02-25 10:06 UTC
[`l()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/l/1) contains the following code.

```php
  // Build a variables array to keep the structure of the alter consistent with
  // theme_link().
  $variables = array(
    'text' => $text,
    'path' => $path,
    'options' => $options,
  );
```

Since `l()` does not call `theme_link()` (it is `theme_link()` that calls `l()`), using `$variables` instead of the function arguments does not make much sense.

That code should be removed and any reference to that variable should be replaced with a reference to the correct parameter.

**Comment by klonos** [comment] 2023-02-25 17:20
Thanks @kiamlaluno 🙏🏼 ...the code changes seem reasonable to me, and tests are green.

I'm not sure why this hasn't caused any issues before, but I'd like some @backdrop/core-committers 👀 on the PR (preferably @quicksketch, since he's the one that introduced the specific changes way back when, when https://www.drupal.org/project/drupal/issues/1922454 was backported to Backdrop with https://github.com/backdrop/backdrop/commit/c45d57d462252498268260b329ba94d4fe72d6f9)

**Comment by klonos** [comment] 2023-02-25 17:22
...BTW @kiamlaluno, how did you happen to come across this? Did you have any error or notice any specific thing not working as expected? If so, do you have any steps to reproduce?

**Comment by kiamlaluno** [comment] 2023-02-25 18:36
> I'm not sure why this hasn't caused any issues

It is just a matter of using another variable (`$variables`, containing an array) instead of the arguments passed to the function. It should not cause issues, as long as `$variables` is changed and it is always used. (It would cause issues when the content of `$variables` is changed but then the function arguments are directly used, for example for calling a function.)

> how did you happen to come across this?

I just read the function code to understand another issue and I noticed that.

> Did you have any error or notice any specific thing not working as expected? 

No, I did not. It is just a matter of initializing and using a new variable instead of using the variables already available to the function.

**Comment by kiamlaluno** [comment] 2023-02-25 19:09
Using the *Blame* tab on Github, I found the code has been changed in commit [c45d57d462252498268260b329ba94d4fe72d6f9](https://github.com/backdrop/backdrop/commit/c45d57d462252498268260b329ba94d4fe72d6f9) whose commit message is the following.

>  Issue #10: Resolving last problem with Tablesort headers by backporting Drupal #1922454, removing theme calls from the l() function.

I found [#ㅤ10](https://github.com/backdrop/backdrop-issues/issues/10), but it seems an unrelated issue.

**Comment by kiamlaluno** [comment] 2023-02-25 19:25
At least I found the issue [#ㅤ1922454](https://www.drupal.org/node/1922454) on drupal.org: *Gut l(), fix theme('link'), have a working framework for consistently generated links inside and outside of Twig*. The [last patch added there](https://www.drupal.org/files/1922454-118.patch) contains the same code change done in Backdrop.

**Comment by klonos** [comment] 2023-02-25 19:52
Yeah, so the question is: do we remove `$variables`, or do we add a `hook_link_alter()` invocation in `l()` (in which case using `$variables` would make sense)?

**Comment by kiamlaluno** [comment] 2023-02-25 20:04
Since the code that was calling a theme function to render the link has been removed (to improve performance), I would rather not invoke an alter hook in `l()`.

**Comment by kiamlaluno** [comment] 2023-02-25 20:14
That would probably make more sense, for Backdrop.  
In Drupal, it is `l()` that calls `theme_link()`, while in Backdrop it is `theme_link()` that calls `l()`. `theme_link()` itself is described as *a wrapper around [`l()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/l/1) to allow for more flexible link themeing*. It makes more sense to keep `theme_link()` more flexible also by letting it invoke `hook_link_alter()` too.

**Comment by klonos** [comment] 2023-02-26 07:46
Sounds reasonable, but I'll let our @backdrop/core-committers chime in.

**Comment by herbdool** [comment] 2023-02-28 16:51
This seems like a small, reasonable change contained within this function. Though it's called everywhere so we'd need to make extra sure things still work.

**Comment by quicksketch** [comment] 2023-03-15 03:26
What a strange set of changes that were made back then. I agree with this simplification and matching to what Drupal 7 did, no need to make things unnecessarily complicated. I would think that test coverage would ensure 100% compatibility already, but I'd like to have another set of eyes to triple-check.

**Comment by quicksketch** [comment] 2023-03-15 04:41
I don't think any further changes are needed on this PR based on my read-through, but I'm moving this down into needs review/testing just to get one more round of reviewing on it.

**Comment by kiamlaluno** [comment] 2023-03-15 09:30
I synchronized the fork with backdrop/backdrop, since it was behind of 28 commits.

**Comment by argiepiano** [comment] 2023-03-16 22:36
Reviewed and tested. LGTM!

**Closed** 2023-03-25 23:11 UTC
Labels: type - task, status - has pull request, pr - ready to be committed, pr - works for me

**Comment by quicksketch** [comment] 2023-03-25 23:14
Thanks @argiepiano! I merged https://github.com/backdrop/backdrop/pull/4361 into 1.x and 1.24.x. Thanks @kiamlaluno for undertaking this cleanup!
