### ISSUE TITLE
How to upgrade to Backdrop from Drupal 7

### ISSUE THREAD

**Issue by cellear** [backdrop/backdrop-issues#683] opened 2015-02-03 22:36 UTC
I tried to follow the upgrade instructions here:
https://backdropcms.org/upgrade

I followed steps 1 and 2, and exported a fairly small, stripped down Drupal 7 site DB. Steps 3 and 4 currently say this:

> Step 3: Upgrade your Drupal site to Backdrop CMS
> @todo Document
> Step 4: Restore your Backdrop site to glory
> @todo Document

So...does converting from D7 work yet, or is it still a to-do item (that needs some documentation -- which I'm willing to write, if I get it to work!)

To sum up what I tried (maybe this isn't what's missing from step 3!) 
1. Copied my existing Drupal site (in this case, lukemccormick.com) to a local setup.
2. Drupal's UPGRADE.txt awkwardly tells you to delete all the files except the contents of your sites folder.  This is just to get you the existing database and your settings.php file, right?
3. Drupal wants you to run /update.php.  In Backdrop, this is now core/update.php.  Running (mylocalhost)/core/update.php I get this:

> Error
> Error message
> PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lmdotcombd.cache_bootstrap' doesn't exist: DELETE FROM {cache_bootstrap} WHERE (cid = :db_condition_placeholder_0) ; Array ( [:db_condition_placeholder_0] => hook_info ) in module_implements_reset() (line 763 of /Users/luke/Sites/00_MAMP/lmcom-backdrop/core/includes/module.inc).

I apologize if I'm doing something brain-dead -- I've never had much luck with Drupal's upgrade system, so it's been a long time since I've actually tried it!

(I asked this question on our Subreddit, but so far I'm still looking for guidance:
http://www.reddit.com/r/backdrop/comments/2ue27o/upgrading_to_backdrop_from_drupal_7/)

**Comment by quicksketch** [comment] 2015-02-03 23:51
Hi Luke! Well, I suppose it's time to try this out, eh? I actually upgraded api.backdropcms.org through the update.php script just 2 weeks ago, so I'm fairly sure it's working.

What I think is happening here is that Backdrop isn't yet pointing itself at the D7 database, since the "cache_bootstrap" table can't be found. That's a table that should already exist in your D7 site.

So what I think you need to do is open up Backdrop's `settings.php` file and change the `$database` variable to point at your D7 database. Then visit `/core/update.php` again and see if it gets any further. Thanks!

**Comment by cellear** [comment] 2015-02-04 01:19
> What I think is happening here is that Backdrop isn't yet pointing itself at the D7 database, since the "cache_bootstrap" table can't be found. That's a table that should already exist in your D7 site.

Hmm...I might have deleted that table, trying to reduce the size of my database.  (My vanity site got hacked by spammers, so I tried to clean it out...perhaps not as skillfully as I thought.)

Let me try it again with an unmodified DB, it sounds like that's a good candidate for what went awry

**Comment by cellear** [comment] 2015-02-04 01:58
Success!  The root to my problem turned out to be that I hadn't sufficiently updated Drupal to get it to within range that Backdrop would upgrade it.  It apparently needed me to get system module up to 7079.

I now have my vanity site running in Backdrop!  Locally, and I need to redo the theme, but still -- I'm excited.

I can follow through on my promise to update that upgrading documention now.

Thanks, @quicksketch!

**Comment by quicksketch** [comment] 2015-02-04 03:13
Yay, success. Thanks @cellear.

**Comment by BWPanda** [comment] 2015-02-10 09:15
I'm also starting to try upgrading a copy of www.panda.id.au to Backdrop and am having issues...

I have followed [these steps](https://backdropcms.org/upgrade#from-drupal) (updated D7 website, made a full backup, disabled all non-core modules (with the exception of modules that provide fields - these can't be disabled as long as the fields exist), uninstalled unnecessary modules & changed theme to Bartik). I then made another, Backdrop-specific full backup and re-instated the previous backup (so my website can still run while I test upgrading a copy of it).

I downloaded v1.0.1 of Backdrop onto my server and extracted my Backdrop-specific backup into the 'sites' directory (I use multisite, and only backed up the 'panda.id.au' directory (complete with modules, themes, DB, etc.) from D7). I copy 'settings.php' from Backdrop core into my site-specific directory and add my database credentials (I've also created a new database and populated it with my Backdrop-specific backup). After setting up Apache, etc. I try to access `http://new.panda.id.au/core/update.php` but keep getting redirected to `http://new.panda.id.au/core/install.php`.

The only thing I've changed in the default 'settings.php' is the new DB credentials - I haven't updated the salt hash or config directories as I figure they should be updated automatically.

What have I missed/done wrong?

**Comment by BWPanda** [comment] 2015-02-10 09:17
Oh, I forgot to mention that I also patched Backdrop v1.0.1 with [this patch](https://github.com/backdrop/backdrop/pull/717.patch).

**Comment by serundeputy** [comment] 2015-02-10 22:03
@BWPanda I did have to update my settings.php file to point to the new config:
http://serundrop.staffordtavern.com/backdrop-cmi

see bottom of post.

~Geoff

**Comment by BWPanda** [comment] 2015-02-10 22:14
@serundeputy I guess I thought that Backdrop should create the config directories automatically, since they likely need a .htaccess file to prevent unauthorised access. If I add them to settings.php manually, there's no way Backdrop would know to add them itself would there?

**Comment by quicksketch** [comment] 2015-02-10 22:23
> I guess I thought that Backdrop should create the config directories automatically

Backdrop should be creating the config directories automatically if you're upgrading from Drupal 7. Perhaps this is a multisite upgrade issue. The patch we made that @BWPanda applied was for multisite *installation* rather than upgrade (https://github.com/backdrop/backdrop-issues/issues/666) (though it probably affects both). We may have an issue with upgrades yet.

> since they likely need a .htaccess file to prevent unauthorised access. If I add them to settings.php manually, there's no way Backdrop would know to add them itself would there?

Backdrop doesn't add an .htaccess file at all to the config directories, instead the "private" nature of them is hidden by generating a random hash for the config directory name. The safest way to set up a site is to host these files entire outside of the web root. Although now that you mention it, providing an .htaccess file for a safety backup sounds like a good idea.

**Comment by BWPanda** [comment] 2015-02-10 22:32
> The safest way to set up a site is to host these files entire outside of the web root. Although now that you mention it, providing an .htaccess file for a safety backup sounds like a good idea.

That's the same suggestion Drupal has for the 'private' file system (outside the web root). But I've always found it easier to have the 'private' dir inside the normal 'files' dir (as is the default) and rely on .htaccess denying access.

Since you mentioned that Backdrop doesn't do this automatically (add .htaccess to config dir), I'd highly recommend adding this.

**Comment by serundeputy** [comment] 2015-02-10 23:46
@BWPanda @quicksketch but you are not running core/install.php on the server right.
you ran that on your local, and then on the server you are hitting core/update.php

so that is not going to create the config dirs you have to rsync them and then point your settings.php file at them

**Comment by BWPanda** [comment] 2015-02-11 00:17
> but you are not running core/install.php on the server right.
you ran that on your local, and then on the server you are hitting core/update.php

@serundeputy I'm not running 'install.php' at all (shouldn't have to with upgrading existing site), and I don't have local vs. server; just a server where I do development plus host live sites.

I cannot even make it to 'update.php' as it keeps redirecting to 'install.php' - still looking for an answer to that...

**Comment by serundeputy** [comment] 2015-02-11 00:31
@BWPanda so that behavior sounds like backdrop is not detecting the DB at all and therefore redirecting to 'install.php'

make sure the:
```
$database = 'mysql://user:pass@localhost/database_name';
$database_prefix = '';
```
have the correct DB Creds

make sure the user specified in the `$database` string has read/write access to the DB specified in the same string.  If the user doesn't have those creds, grant them and flush privileges.

Make sure there are not two or more `$database` strings overwriting your creds with either empty or invalid creds.

**Comment by BWPanda** [comment] 2015-02-11 01:04
Ok, I fixed the redirection problem: I left the 'settings.php' in the root directory (so backdrop was seeing that instead of the one in my site-specific directory). After renaming it to default.settings.php I can now access update.php without being redirected.

**Comment by BWPanda** [comment] 2015-02-11 01:06
Sorry, scrap that. I'm still getting redirected to install.php but an now seeing this messages instead of the install page:

> Additional uncaught exception thrown while handling exception.

> Original
ConfigException: The configuration directory type &quot;active&quot; does not exist. in config_get_config_directory() (line 131 of /var/www/backdrop/core/includes/config.inc).

> Additional
ConfigException: The configuration directory type &quot;active&quot; does not exist. in config_get_config_directory() (line 131 of /var/www/backdrop/core/includes/config.inc).

**Comment by BWPanda** [comment] 2015-02-11 01:07
Marking as a bug report as the multi-site feature certainly seems to be having issues.

**Comment by BWPanda** [comment] 2015-02-12 09:14
Ok, I started afresh and noted the following:

- If using a multisite installation, you have to setup `sites.php` properly (see https://github.com/backdrop/backdrop-issues/issues/708#issuecomment-74022969); no need to rename/delete `settings.php`
- I was seeing some errors that stopped me accessing the site but figured they'd be fixed once I ran update.php (had to set `$settings['update_free_access'] = TRUE;` to access update.php without being logged in)

I was able to run update.php, but halfway through applying the updates it errored out and says:
>  Fatal error: Call to undefined function entity_info_cache_clear() in /var/www/backdrop1/core/includes/common.inc on line 7949

**Comment by BWPanda** [comment] 2015-02-12 09:34
Hmm, `entity_info_cache_clear()` is [clearly an existing function](https://api.backdropcms.org/api/backdrop/core!modules!entity!entity.module/function/entity_info_cache_clear/1), which makes me think this is a namespace issue with the disabled 'entity' module I'm bringing over from Drupal...

**Comment by quicksketch** [comment] 2015-02-12 20:27
> which makes me think this is a namespace issue with the disabled 'entity' module I'm bringing over from Drupal...

That's possible. Updates are run even for disabled modules, though since the Drupal module shouldn't include a `backdrop = 1.x` line in its info file, I don't think it would get picked up... but I'm not totally sure about that. In any case, that module should definitely be removed from the installation, since there's no way it's going to work well with the entity.module that is included in core.

**Comment by jenlampton** [comment] 2015-02-12 22:07
Removing the bug report tag until we're sure we've found a bug. It sounds like upgrading a multi-site will need some thorough documentation though.  @BWPanda let us know if you have removed entity API module from your contrib directory. 

I often remove everything from the contrib directory and see if core upgrades okay on it's own. Then you can throw in contrib modules one at a time and upgrade them each individually. That helps find which one (or ones) causes problems.

**Comment by BWPanda** [comment] 2015-02-12 23:31
Thanks @jenlampton. I've now tried the migration again with all disabled modules moved out of the 'modules' directory. Updating works nicely, except at the very end it lists a bunch of notices:

> Notice: Use of undefined constant COMMENT_NODE_OPEN - assumed 'COMMENT_NODE_OPEN' in comment_update_1001() (line 316 of /[BACKDROP]/core/modules/comment/comment.install).

(Various 'Use of undefined constant' notices all to do with 'comment.install')

> Notice: Undefined index: module in _field_info_prepare_instance_widget() (line 416 of /var/www/backdrop1/core/modules/field/field.info.inc).

(Various 'Undefined index' notices all to do with 'field.info.inc')

**Comment by quicksketch** [comment] 2015-02-13 02:42
Thanks @BWPanda! We may have a few bugs here. I think those comment exceptions may happen when the comment module needs to be upgraded but is disabled during the update.php process. We may need to manually load comment.module at the start of that update. Not sure about the cause of the second set of notices.

**Comment by jenlampton** [comment] 2015-09-28 00:29
I updated the documentation at https://backdropcms.org/upgrade-from-drupal today.

**Comment by jenlampton** [comment] 2015-09-28 00:30
(please reopen if there needs to be updates!) :)

**Closed by jenlampton** 2015-09-28 00:29 UTC
