### ISSUE TITLE
Transliteration doesn't respect site default language

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#2637] opened 2017-04-12 15:26 UTC
In German, certain characters are supposed to be transliterated language-specific. Example: The letter `ä` should be transliterated to `a` for English but to `ae` for German. Backdrop doesn't deliver the language-specific transliterations unless you add *Multilingual support* to a content type and select the relevant language on the content items.

**Steps to reproduce:**

- Enable Language and Locale modules.
- *Don't* enable Content Translation module.
- Add Language: German
- Make German default.
- Disable the Detection Method "URL" to make sure that the default language is used in any case.
- Enable "Transliterate prior to creating URL aliases" (`admin/config/urls/path/patterns/settings`)
- Enable "Reduce URL alias characters to letters and numbers".
- *Don't* enable Multilingual Support for Posts.
- Add a Post with Title: Ärger im Büro

Resulting URL alias: `posts/arger-im-buro`

Expected alias: `posts/aerger-im-buero`

---

Current PR by @indigoxela: https://github.com/backdrop/backdrop/pull/3176 (transliterate neutral paths in current lang, like D7)

---

Outdated PRs:

<strike>PR by @olafgrabienski: https://github.com/backdrop/backdrop/pull/1849</strike> (outdated)
<strike>PR by @quicksketch: https://github.com/backdrop/backdrop/pull/1850</strike> (outdated, conflicts)
<strike>PR by @indigoxela: https://github.com/backdrop/backdrop/pull/3175</strike> (set node langcode, closed in favor of different approach)

---

**Original issue description:**

On a Backdrop 1.6.3 site which uses German as default language, transliteration for URL aliases and files are enabled and work generally, but they do not respect language-specific variations by default.

Certain characters are supposed to be transliterated language-specific. Example:

- **ä** => **a** (English)
- **ä** => **ae** (German)

At the moment, Backdrop doesn't deliver language-specific transliterations of URL aliases, unless you add Multilingual support to a content type and select the relevant language on the content items.

(Note: For localized sites which use only one language there's usually no need to add multilingual support to content types, and it's not an acceptable workaround to do so.)

At the top of `core/includes/transliteration.inc` I see the following comment which makes me think that Backdrop should use the site's default language for language-specific transliterations:

```
 * @param $source_langcode
 *   Optional ISO 639 language code that denotes the language of the input and
 *   is used to apply language-specific variations. If the source language is
 *   not known at the time of transliteration, it is recommended to set this
 *   argument to the site default language to produce consistent results.
 *   Otherwise the current display language will be used.
```

Unfortunately I don't have the skills to check `$source_langcode` in the code itself. Could someone have a look at it and give feedback how it's supposed to work and/or why it doesn't?

**Comment by olafgrabienski** [comment] 2017-04-12 15:32
Related issue, regarding taxonomy terms: #1995

**Comment by olafgrabienski** [comment] 2017-04-26 20:14
Reminder: Have a look at English as well. There's no `en.php` in `core/includes/transliteration`.

**Comment by serundeputy** [comment] 2017-04-26 22:31
@olafgrabienski I've assigned this to you feel free to un-assign if you don't have the time or whatever.

----
NOTES:

@olafgrabienski and I did some prelim research on this; here is the rough draft code we have so far:

```php
  $site_langcode = config_get('system.core', 'language_default');
  if (!empty($site_langcode)) {
    $langcode = $site_langcode;
  }
  elseif (!empty($options['language']->langcode)) {
    $langcode = $options['language']->langcode;
  }
  elseif (!empty($options['langcode'])) {
    $langcode = $options['langcode'];
  }
```

This works in the case described in the OP, but we need to assure it works in multi-language scenarios as well.  Like if the site has English, French and German and certain nodes should work in certain languages etc.

**Comment by olafgrabienski** [comment] 2017-04-28 16:32
@serundeputy I made a PR with your suggestion, putting the code just below `$langcode = LANGUAGE_NONE;` (line 161; not sure if it's exactly the correct place).

After configuring Localization for the sandbox site, the change fixes the issue with German transliteration if German is set *as site default language*. That's great! But as assumed, transliteration doesn't work anymore for content of other languages, when the respective language is choosen *on the single node* (for content types with enabled "Multilingual support"). So, for the time being the situation is contrary to the original issue description:

From the issue description:
> Backdrop doesn't deliver language-specific transliterations of URL aliases, **unless** you add Multilingual support to a content type and select the relevant language on the content items.

Current situation:
Backdrop doesn't deliver language-specific transliterations of URL aliases, **when** you add Multilingual support to a content type and select the relevant language on the content items. (It does however deliver the expected result for the site's default language which wasn't the case before.)

**Comment by olafgrabienski** [comment] 2017-04-28 16:40
Writing up the steps to configure the sandbox and to test the PR, just in case we have to start over:

## Configure Localization

admin/modules
- Enable Language and Locale

admin/config/regional/language
- Add Language: German
- Add Language: Spanish
- Make German default

admin/config/regional/language/detection
- Disable the Detection Method "URL" to make sure that the default site language is used in any case.

admin/config/urls/path/patterns/settings
- Enable "Transliterate prior to creating URL aliases"
- Enable "Reduce URL alias characters to letters and numbers"

## Add Content

node/add/post
- Title: Ärger im Büro ist schließlich immer möglich
- Resulting URL alias:
  - posts/aerger-im-buero-ist-schliesslich-immer-moeglich (ok)

## Change post type settings

admin/structure/types/manage/post/configure
- Publishing settings: Enable Multilingual support

## Edit content

node/3/edit
- Language: Spanish
  - Resulting URL alias: node/3 (strange but let's have a look at it later)
  - Expected result: posts/arger-im-buro-ist-schliesslich-immer-moglich
- Language: German
  - Resulting alias: posts/aerger-im-buero-ist-schliesslich-immer-moeglich (ok)
- Language: English
  - Resulting alias: posts/aerger-im-buero-ist-schliesslich-immer-moeglich (not ok)
- Language: Spanish (again)
  - Resulting alias: posts/aerger-im-buero-ist-schliesslich-immer-moeglich (not ok)

admin/config/regional/language
- Make English default

node/3/edit
- Language: none
  - Resulting alias: posts/arger-im-buro-ist-schliesslich-immer-moglich (ok)
- Language: German
  - Resulting alias: posts/arger-im-buro-ist-schliesslich-immer-moglich (not ok)

**Comment by olafgrabienski** [comment] 2017-04-28 16:51
So, as a next step, we have to look at these conditionals:

```
$site_langcode = config_get('system.core', 'language_default');
  if (!empty($site_langcode)) {
    $langcode = $site_langcode;
  }
  elseif (!empty($options['language']->langcode)) {
    $langcode = $options['language']->langcode;
  }
  elseif (!empty($options['langcode'])) {
    $langcode = $options['langcode'];
  }
````
The goal is to let it work as following: To transliterate a URL alias, look first if there is a language setting on the node. If yes, use the node language. If not, use the site's default language.

Any idea?

**Comment by Dinornis** [comment] 2017-04-28 20:39
Hi Olaf, please forgive my ignorance on this topic.
Why certain characters are supposed to be transliterated language-specific?

Shouldn't the german sentence: _Ärger im Büro ist schließlich immer möglich_ be always transliterated as _aerger-im-buero-ist-schliesslich-immer-moeglich_ in all languages? Changing the diphthongs from **ae** to **a**, **ue** to **u** etc. changes the meaning of the title.

**Comment by olafgrabienski** [comment] 2017-04-28 22:48
@Dinornis Thanks for your question. I'm not expert, but I know that in English you can transliterate German *Umlauts* without the `e`. "Müller" can become "Mueller" or "Muller", and so on. Another example: there is the `ö` which is a German *Umlaut* and a Swedish letter at the same time. While the German `ö` can be transliterated to `oe`, the Swedish letter cannot. So, it's complicated.

Apart from that, I guess my testing examples were misleading. I should have created different posts with different titles for the different examples to make it more clear. In my opinion, the question is however not how a *German* title is transliterated in *different other* languages. This can't be the question because the content / the node is not aware of the language you're typing in the title field. Can't explain it better at the moment, hoping to find time in a couple of days.

**Comment by quicksketch** [comment] 2017-04-29 01:39
I looked at the PR and reproduced the problem at hand. Thanks @olafgrabienski for the great instructions.

I found it is possible to get Transliteration working as expected on content, but it's dependent upon the *Content Translation* module:

- Enable transliteration of URLs at `/admin/config/urls/path/patterns/settings`
- Enable Content Translation module.
- Enable Multilingual Support (Enabled) under "Publishing settings" at `/admin/structure/types/manage/post`
- Create a Post and select "German" as the language
- Set title to "Post In German Chär"
- Resulting URL is `/de/posts/post-german-chaer` (as expected, `chaer` rather than `char`)

This works because the Node now has a `langcode` of `de` in the `node` table. If no language is specified, Backdrop assigns content the language `und` (No language or Undefined). The alias is then based off the language of the content.

Overall, this presents problems for single-language, non-English sites. They shouldn't need to turn on the Content Translation module if all their content is only in a single language.

So I think the correct fix is to make it so that if Language module is enabled and a default language is set, that language should be used when creating content.

**Comment by quicksketch** [comment] 2017-04-29 01:54
I filed a PR at https://github.com/backdrop/backdrop/pull/1850 that changes the default language used by nodes, both with or without Content Translation module. The default of new content is now the site language if another language has been added, or the site language is changed from English.

I think this fixes the primary problem, but the solution may be incomplete. What about other types of entities? Do we need an upgrade path for this (if that's even possible)?

**Comment by olafgrabienski** [comment] 2017-04-29 22:02
@quicksketch Thanks for your PR! I like the approach to use the site's default language as node language. (It may even solve other issues with the language undefined which I remember only vaguely from D7.)

I've had also a quick look at the PR sandbox, configured it to use transliteration, added some languages, made one default and created some nodes to test it. Works as expected, great!

I tested also what happens to transliteration when you enable Multilingual support (Content translation module is not required to do so, btw) and change the language of a node, which dependent of the languages in question should result in a different URL alias. Looking at the browser address bar, in some cases the URL alias doesn't seem to reflect the changed language. But when you edit the node again and have a look at the vertical tab "URL settings", the correctly changed alias is visible. So, the changed URL alias is there, but it's not used in display mode. Strange!

Example:

- Danish as site's default language
- Created a post. Result: correct URL alias with Danish transliteration
- Enabled Multilingual support for posts.
- Edited the node, and changed the language to German.
- Browser address bar:
`posts/oeresund...` (not ok, still the danish transliteration)
- Node edit form > URL settings:
`posts/oresund...` (ok, not danish)

Can someone try to reproduce the issue?

Finally: I can't estimate the questions regarding other entities or an upgrade path. Reminds me though that we have also transliteration for files. I try to have look at it next week.

If we can't cover other entities with @quicksketch's PR , should we try to improve the first PR which may be less node specific?

**Comment by olafgrabienski** [comment] 2017-05-11 13:41
Just another idea as I had never issues with transliteration for URL aliases in Drupal. Should we have a look at the implementation in Drupal's Transliteration and/or Pathauto modules?

**Comment by olafgrabienski** [comment] 2017-05-15 21:51
> So I think the correct fix is to make it so that if Language module is enabled and a default language is set, that language should be used when creating content. (quicksketch)

> I like the approach to use the site's default language as node language. (olaf)

Hm, I still like the approach but I'm not sure if it's the correct way for a bugfix. As reported in https://github.com/backdrop/backdrop-issues/issues/2637#issuecomment-298197258, the PR of @quicksketch works for single-language, non-English sites, but it *remains unclear if it works on multilingual sites* (Feedback welcome). Additionally, there are open questions, e.g. how to handle other entities.

As mentioned in https://github.com/backdrop/backdrop-issues/issues/2637#issuecomment-298045242, 'my' PR works also for single-language, non-English sites, and it *does not work on multilingual sites*. Apparently even worse. I think however that it could be the right direction for a bugfix, if we just want to make sure transliteration works as it used to work in Drupal (and the Transliteration module).

Comparing the respective files in Backdrop (`core/includes/transliteration.inc`) and Drupal's transliteration module (`transliteration/transliteration.inc`), I see a lot of code which handles language related questions, and I've the impression there are some more than formal Backdrop/Drupal differences. Unfortunately, I don't understand the code differences well enough for debugging. @quicksketch and/or @serundeputy : Wanna have a look at them to find what's going wrong in Backdrop?

**Comment by jenlampton** [comment] 2019-01-15 20:41
This issue still needs more feedback, removing milestone, but adding milestone candidate tag.

**Comment by indigoxela** [comment] 2019-09-02 12:53
@olafgrabienski again a good multilingual catch!

After verifying that it works fine in Drupal 7, I tried to figure out the differences to Backdrop, but as pathauto is a contrib module in D7 and the same functionality is in Backdrop core, this didn't help much.

In D7 it is possible to have language neutral nodes, which can have several language specific aliases.
In Backdrop this is currently impossible.

Regarding the two PR. I think, none of those really fixes the base problem.

- https://github.com/backdrop/backdrop/pull/1850 forces a language to be set per node
- https://github.com/backdrop/backdrop/pull/1849 overrides the existing alias

Both prevent multiple language aware aliases for language neutral nodes.

I think, the problem should/could get fixed in core/modules/path.module, probably in:

- function path_form_element
- function path_entity_insert
- function path_entity_update

...and possibly more functions.

I'm not sure, if I find the time to create a PR in near future. I'm hoping for someone else to dig into this. To my understanding this needs a bigger change in path module.

**Comment by olafgrabienski** [comment] 2019-09-17 09:32
> D7 seems to force the site language then.

Thanks for chiming in, @indigoxela! Do you think Backdrop should also force the site language, and if so, any idea how?

I'm very interested to get a fix here. Have to patch many sites, hardcoding the language to `de`.

**Comment by indigoxela** [comment] 2019-09-17 10:02
> Do you think Backdrop should also force the site language

I think, for a site with only one language (no matter, which one), it might make sense.
Language neutral content - to my understanding - only makes sense on multilingual sites (for content mostly containing images or videos, for instance).

I hope for someone else to provide a PR. Unfortunately @quicksketch's PR is outdated. I think, forcing a language was the intention of it.

**Comment by indigoxela** [comment] 2020-06-27 09:36
Another [PR](https://github.com/backdrop/backdrop/pull/3175) with a slightly different approach (still needs work as FieldTokenTestCase is failing).

The idea behind it: only set node langcode to site default language if there's only _one_ active language. Otherwise we might be making wrong assumptions.

I took a look at how D7 transliteration module does it: it takes `global $language` as a base - the current page language - that would be another approach.

**Comment by klonos** [comment] 2020-06-27 14:12
I have only taken a quick look at the 3 PRs, but I noticed that both @indigoxela and @quicksketch are addressing the issue within the Node module (which would solve this only for content/nodes), whereas @olafgrabienski was doing within the Path module. @olafgrabienski's approach seems like a more generic path forward, as it would cover transliteration for taxonomy paths, user paths etc.

**Comment by indigoxela** [comment] 2020-06-27 15:28
> @indigoxela and @quicksketch are addressing the issue within the Node module (which would solve this only for content/nodes)

Yep, that's one of the disadvantages.

>  @olafgrabienski was doing things within the Path module.

Considering both, node and path module, came to my mind as a better solution.

1. Set node langcode to language_default if only one language is active
2. Create path alias based on current language (global $language) if there's more than one language, but node translation isn't available (like [D7 transliteration does](https://git.drupalcode.org/project/transliteration/-/blob/7.x-3.x/transliteration.inc#L181))

Or choose one of these approaches (node vs. path) - I don't feel like I'm the one to decide this.

**Comment by olafgrabienski** [comment] 2020-06-27 20:56
@indigoxela Thanks for your PR! It works for me if German is the default and if it's also the *only* language, i.e. English has to be disabled: A title like "Über uns" gets the expected URL alias `ueber-uns`.

> The idea behind it: only set node langcode to site default language if there's only one active language.

Initially the PR didn't seem to work (alias `uber-uns`), because I forgot to disable English. I guess, many people don't mind to disable English when they run a single-language, non-English site. (At least so far, I didn't do so on any of my sites.) How would we let people know that they have to disable English to get correct URL aliases? And why is it necessary in the first place? You wrote, "otherwise we might be making wrong assumptions". Not sure but I'd say if multilingual support isn't enabled for a certain content type, it's fine to take the default language right away even if other languages are enabled for the site.

**Comment by olafgrabienski** [comment] 2020-06-27 21:09
As described in https://github.com/backdrop/backdrop-issues/issues/2637#issuecomment-298197258, I tested again what happens when you enable Multilingual support for a content type and change the language of a node. This should result in a different URL alias dependent of the language, e.g. `uber-uns` for Danish instead of `ueber-uns` for German. Strangely, the alias in the browser address bar doesn't reflect the changed language. But when I edited the node again and had a look at the "URL settings" tab, the expected alias was visible. So, the changed URL alias is known to Backdrop, but it's not in the address bar. (Not sure if that is a completely separate issue.)

**Comment by olafgrabienski** [comment] 2020-06-27 21:40
Regarding the different approaches (node vs. path module), I'm not able to judge the technical aspects. An entity-agnostic approach seems however more straightforward to me:

Assumption: Translation (or multilingual support) for an entity or a content type isn't available. (If available, handle as usual, based on the node / entity language.)

- If there's really only one site language, create aliases based on that language.
- Otherwise, create aliases based on the current or the default language. (Should be the same most of the time.)

Did I miss something?

**Comment by indigoxela** [comment] 2020-06-28 08:15
@olafgrabienski Yes, the current approach (node langcode) has disadvantages leading to WTF moments.

1. The node langcode is only set _once_ - on node creation
2. We're setting a value the users do not have access to via form elements (no language selection form item)
3. People won't know what to do to get the proper transliteration

Fixing it in the path module seems like a cleaner approach.

Here's another [PR](https://github.com/backdrop/backdrop/pull/3176) (it's getting crowded here... :wink: ) which handles path transliteration the same way the D7 module does it.

**Comment by klonos** [comment] 2020-06-28 08:25
To make it "less crowded", I would close the 2 PRs that attempt to provide a solution specific to nodes, and keep any PRs that solve this in a generic way, in the Path module.

**Comment by indigoxela** [comment] 2020-06-28 08:43
> To make it "less crowded", I would close the 2 PRs that attempt to provide a solution specific to nodes

My current favorite is the latest PR (fix in path module), but other people might want to compare the approaches.
On the other hand "less crowded" might make it easier for people to decide.

**Comment by olafgrabienski** [comment] 2020-06-28 09:33
@indigoxela Thanks for the new PR! I've tested in the sandbox: works great and applies even to other entities as taxonomy terms, for instance. To implement it as Drupal *Transliteration* is also good for people coming from D7, so I'm all for this approach.

**Comment by indigoxela** [comment] 2020-06-28 10:00
@olafgrabienski many thanks for testing. You might want to close your three year old PR then?

**Comment by olafgrabienski** [comment] 2020-06-28 10:14
> You might want to close your three year old PR then?

Sure, done!

**Comment by quicksketch** [comment] 2020-07-02 19:47
The approach suggested by @olafgrabienski and @indigoxela sounds good to me. I looked at the latest PR at https://github.com/backdrop/backdrop/pull/3176 and it makes me a little uneasy that the current _interface language_ determines the _path language_. But only if the content being created is language-neutral.

The primary concern here seems to be on non-English sites that have a single language. Instead of using the current interface language, could we pull from the site default language instead, as @olafgrabienski did in https://github.com/backdrop/backdrop/pull/1849? But instead of being the first choice, it'd be the fallback, as @indigoxela did in the latest PR.

Suggestion posted to the current PR: https://github.com/backdrop/backdrop/pull/3176/files#r449232041

In any case, we should add test coverage in `PathPatternLocaleTestCase` to cover this new fallback approach.

**Comment by indigoxela** [comment] 2020-07-03 08:13
> it makes me a little uneasy that the current interface language determines the path language

I understand your concerns, but still believe that "interface language" is the best approach. It has proven to work reliably in D7 Transliteration module for many years.

> In any case, we should add test coverage

Yes, absolutely.

**Comment by indigoxela** [comment] 2020-08-14 14:48
Tadaaa, we have functional tests.

**Comment by olafgrabienski** [comment] 2020-08-17 08:14
> we have functional tests.

Great! The updated PR is still working for me.

Regarding the different approaches (default language vs. interface language) it sounds reasonable to take the one which works fine in D7 and the Transliteration module.

**Comment by stpaultim** [comment] 2020-08-25 17:44
I added this to the "[Help wanted](https://backdropcms.org/news/help-wanted-finalizing-backdrop-cms-1170)" blog post as requested by @olafgrabienski. Can anyone provide a quick summary of where this issue is at and which Pull Requests are still being looked at or have we settled on one. It might be helpful to update the original post to clarify this. The PR listed in the original post is not consistent with the one linked in the right column.

**Comment by olafgrabienski** [comment] 2020-08-25 21:24
@stpaultim You're right, https://github.com/backdrop/backdrop/pull/3176 is the correct PR. I've however updated the issue description to clarify the topic of the issue and which is the current PR.

**Comment by quicksketch** [comment] 2020-09-10 19:55
I think the approach in the latest PR is fine. I read over https://github.com/backdrop/backdrop/pull/3176 and the one thing I think is missing is that we have test coverage specifically for German now, but it's not clear how that transliteration is different than the English one. Could we save the same node title in both languages and then validate the differences between them?

**Comment by indigoxela** [comment] 2020-09-11 07:16
> Could we save the same node title in both languages and then validate the differences between them?

I enhanced the test as requested: two nodes, (almost) same title, different default languages - different path aliases.

**Comment by indigoxela** [comment] 2020-09-22 08:11
Friendly reminder: I updated the PR (test) as requested, so it's ready for another review.

**Comment by klonos** [comment] 2020-10-31 18:03
Thanks @indigoxela and sorry for taking that long to re-review. This is RTBC now 👍

**Comment by klonos** [comment] 2020-10-31 18:10
...just to be sure, I've also re-tested in the fresh PR sandbox, following the steps from the issue summary. Everything still WFM 👍

**Comment by herbdool** [comment] 2020-10-31 19:05
Code and test looks good to me.

**Closed** 2020-11-06 10:38 UTC
Labels: pr - ready to be committed, pr - works for me, status - has pull request, type - bug report

**Comment by BWPanda** [comment] 2020-11-06 10:56
Thanks @indigoxela, @quicksketch, @klonos, @olafgrabienski, @serundeputy & @herbdool! I've merged https://github.com/backdrop/backdrop/pull/3176 into 1.x and 1.17.x.
