### ISSUE TITLE
[UX] Create Wizard or Quick Link to Create a custom layout for a specific content type

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#6434] opened 2024-03-24 19:26 UTC
## Description of the need

Field blocks are one of the most powerful and useful features that are very hard to find or discover in Backdrop CMS. Over the years I have enjoyed watching the expressions of joy on the face of site architect's as I show them this feature, while growing increasingly frustrated that almost no one (including myself) finds it on their own or through documentation. 

In modern Drupal, with the new layout buider installed a site architect is able to enable layouts, click manage layout for that content type and they are presented with a customizable layout that already has visible field blocks for all of their fields. It's quite easy to discover and use this ability to drag and drop fields from one region to another within the core UI.

I think that we can simulate this experience in Backrop CMS and make field blocks a much easier feature to find and use.

## Proposed solution

I haven't decided on what I think is the best workflow for this yet. But, I'll share this idea to get the discussion going and I welcome ideas for how to improve on this. 

1) Add a "Create Custom Layout" option to the drop down for each content type on the Content Type page. 

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/fd606d8a-8009-4bf2-80ec-e465f958a5c8)

Clicking on this link, would take person to a preconfigured layout that looks something like this:

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/fbbd66b3-f73c-450e-ba25-51c2cf60e36b)

This would already be completed and saved but could be edited:

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/a4f7bab4-55d0-41a2-b20c-75d78e754c53)

## Alternatives that have been considered

I have not yet considered many alternatives. I am sure there are more complicated and far reaching solutions to this problem, but I see this solution as a step in that direction. Since this PR does not really add or change any functionality in Backdrop CMS, it just brings an important feature closer to the surface where folks will be much more likely to find and use it on their own.

Is there a Drupal or Backdrop contributed module that accomplishes this?

The Layout System is quite different in modern Drupal, but there is a workflow very similar to this built into Layout Builder.

## Additional information

In Modern Drupal, one would accomplish the same thing on the Manage Display page for a content type:
![image](https://github.com/backdrop/backdrop-issues/assets/3144571/962dfdb2-4df6-4da9-a236-68460f293281)

Clicking on the Manage Layout option in DRUPAL takes one to this page with field blocks that one can easily reorder or drag and drop into other sections/regions.

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/677928f7-9ceb-43d7-ba2e-37e595a88e12)

## Concerns

I'd want to make sure that we're not confusing this feature with existing features to manage the display of content types.

## Draft of feature description for Press Release (1 paragraph at most)

Backdrop CMS now includes an easy to use wizard that makes it much easier to use the existing layout system to create custom layouts for content types and along the way helps new site architects find hidden features and better understand the layout system.

**Comment by stpaultim** [comment] 2024-03-24 19:38
I'm not sure how to create a PR to do this. But, I THINK that this should be a relatively easy PR to create for those with better programming skills than I have.

Any feedback on the difficulty level for this feature and or suggestions on how to get started with a PR? Maybe help with some pseudo code?

**Comment by stpaultim** [comment] 2024-03-29 06:09
We talked about this issue in the DEV meeting today. Here is a link to the exact spot in the discussion: https://www.youtube.com/live/h7FkJEQpT1E?si=21jYMtZ4FbTLPKe_&t=32m16s

This will come up again at Backdrop LIVE.
https://events.backdropcms.org/discussions/backdrop-live-april-2024/what-can-we-learn-from-modern-drupal-layout-system

**Comment by docwilmot** [comment] 2024-04-02 15:58
This sounded like a good idea. Had a look last night. Will have a PR to demo this evening.

**Comment by stpaultim** [comment] 2024-04-03 01:34
@wilmoth shillingford ***@***.***> That would be wonderful!
Looking forward to testing it.

**Comment by docwilmot** [comment] 2024-04-03 04:27
POC PR up now. 
- Adds a "Manage layouts" tab to all entity bundle configuration pages (page nodes: `admin/structure/types/manage/page/layouts`, user: `admin/config/people/manage/layouts`, taxonomy)
- That page shows all layouts overriding that entity type's display (eg `node/%`, `user/%`, `taxonomy/term/%`), and any layouts overriding the bundle type e.g layout with a `page` content type visibility condition.
- Allows adding a new layout with visibility conditions set automatically
- New layouts have all that bundle's field block in the content region automatically

Not fully tested, YMMV!

**Comment by stpaultim** [comment] 2024-04-03 06:26
@docwilmot - It's very exciting to see progress on this. Not sure if your ready for feedback, but I'll give some easy and obvious feedback and ask a few questions.

1) Layout page for all content types is full of these errors.

```
Deprecated function: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in layout_context_required_by_path() (line 2131 of /var/lib/tugboat/core/modules/layout/layout.module).
Deprecated function: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in layout_context_required_by_path() (line 2138 of /var/lib/tugboat/core/modules/layout/layout.module).
```

2) All the field blocks are currently showing up in the footer. I think that they should be in whatever region the "content" block was. 

3) Currently, the content block remains on the new layout. I would assume we should remove this block, since the field blocks would replace it. I don't think we need the "content" block on these new layouts.

4) In your PR, each entity type or content type has it's own layout page that shows layouts for that content type. I had not imagined this. I guess, I don't expect that content types are likely to have more than one layout and it seems excessive to have an entire page to list one layout. Is this an interim step in developing this feature or are you imagining that this layout page for each content type is useful?

I think, I'll leave my comments here for now, since I assume this PR is still in progress and may still be changing. 

But, I love where this is going!

**Comment by hosef** [comment] 2024-04-03 18:32
I like the idea, but I am not sure about having all the field blocks in there by default. Usually I just want the default content block and then 1-3 fields moved to other regions.

**Comment by stpaultim** [comment] 2024-04-03 18:38
@hosef - For me, the most important part of this is to provide easy access to field blocks. If they are not all visible, then how do you decide which ones to make visible? And if the content block is visible, then some data is duplicated, unless you also change the display settings.

Any specific proposals for how you think this could work better?

**Comment by herbdool** [comment] 2024-04-03 19:16
Looks like an awesome feature.

Maybe there's a way to provide an option of using the default content block or add field blocks. The wizard is useful for both approaches (those who just want an easy way to configure the context and visibility; and those who want a more complex layout) so it would be good to figure this out.

**Comment by docwilmot** [comment] 2024-04-04 01:12
>Layout page for all content types is full of these errors.

Should be fixed
> All the field blocks are currently showing up in the footer. 

Fixed
> Currently, the content block remains on the new layout. I would assume we should remove this block. 

Done. Wasn't sure this would be preferred, please see @hosef's comment.
> In your PR, each entity type or content type has it's own layout page that shows layouts for that content type. I had not imagined this. I guess, I don't expect that content types are likely to have more than one layout and it seems excessive to have an entire page to list one layout. Is this an interim step in developing this feature or are you imagining that this layout page for each content type is useful?

This seemed the more logical way to do it for me. I suppose a single layout page per entity instead of per bundle may make more sense though, so I'm open to other ideas.
> I like the idea, but I am not sure about having all the field blocks in there by default. Usually I just want the default content block and then 1-3 fields moved to other regions.

This is reasonable, but then if we're hoping this feature will make field blocks more visible, how could we do that? Pick a random field block and enable it in a random region? Open to suggestions

**Comment by stpaultim** [comment] 2024-04-04 01:17
I would not want to loose the auto placement of field blocks, I think it's an important part of this feature. But, @hosef has made a good point that some content types have a lot of fields and there is still value to having to this feature, even if you don't need field blocks. 

So, I think the option (suggested by @herbdool) to either keep the default content block or replace them with field blocks could be nice. BUT, I don't know if it's necessary. I'm anxious to hear what others think. My view of this feature is changing slightly as I see it develop. 

I think it was @hosef that suggested today, that the UI could provide a list of all available field blocks and let the site admin choose which ones to expose. That sounds cool to me, but I don't want to stall progress if that is difficult to accomplish. Maybe that is a follow-up improvement?

I don't know if @docwilmot is ready for additional feedback, but I noticed a fresh update to PR and gave it a peek. It's much better already. 

1) Most of the errors are gone. There is still one error showing up, but I'm guessing he is aware of that and working on it. 

`Warning: Undefined variable $rows in layout_entity_admin_form() (line 73 of /var/lib/tugboat/core/modules/layout/layout.entity.admin.inc).`

2) Field blocks are now placed in content region by default instead of the content block. Good work on that.

I'm relucant to test this too hard yet, until we get other feedback on the progress made so far.

**Comment by stpaultim** [comment] 2024-04-04 01:26
I'm trying to test this, but @docwilmot is making changes so fast, that he is breaking my test environment (I love it). 

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/e13fcc74-c110-4ad8-acd9-81adfb80cfc7)

OK, I couldn't resist. 

1) Maybe a little text here that says something to the effect: "Layouts used for this entity type." I would prefer "content type", but that would not always be accurate when used with other entity types. 

2) Instead, maybe it says here "No layouts have yet been created for this entity type."

Just looking for some words to reinforce that the layouts on this page are ONLY for one entity type and that this is not a list of all layouts.

**Comment by docwilmot** [comment] 2024-04-04 02:38
I think the normal layout block add page should be the definitive place to do layout stuff. I think we should consider this PR to just be making a shortcut to lead to that location. I think some good help text on the entity layout page, and a message after layout creation explaining what happened, maybe even a link back to the entity layout page?

Not sure. Usually this is when @jenlampton and @klonos come in right?

**Comment by hosef** [comment] 2024-04-04 15:21
I think that if they start in the content types section, they should end up back there after going through the wizard. I can see new users getting confused by ending up somewhere else when setting up a new content type.

**Comment by hosef** [comment] 2024-04-04 15:25
Also, in relation to the field blocks:
I have worked on sites in the past that had hundreds of fields, and the idea of having to delete all the field blocks when I just want to use a display mode for most of them and a small number of field blocks sounds like a nightmare.

I think Herb's idea of providing an option of which thing to do would be the best option.

**Comment by klonos** [comment] 2024-04-04 18:17
Thanks @stpaultim for bringing this issue here to my attention. I have not read the whole thread yet, but it seems to be a duplicate of #2894 ...right?

**Comment by stpaultim** [comment] 2024-04-04 19:08
After taking a moment to look at #2894, I would agree that this one is a duplicate. However, given that we have a PR here, I think it might be best to keep this one moving and potentially close that one, if we make progress.

**Comment by olafgrabienski** [comment] 2024-04-05 07:15
> The most common use-case is that people will only have one or two field blocks, and all other fields are shown via by the display mode. Placing all the field blocks will create a lot of work for people to remove them.

Agreed, the 'one-or-two-field-blocks' use case is probably very common. However, it's not _so_ much work to remove multiple blocks from a layout (hit "Remove" for every block, and save the layout). That said, I also like the suggestion to provide the option to choose the use-case option.

A possible alternative: place all the field blocks in a disabled state. This way, people see at first sight which blocks are available and can enable only those useful for them.

**Comment by docwilmot** [comment] 2024-04-05 15:00
> (What we talked about in the meting was... ) In both cases the result of clicking the action link should land someone on the "Mange blocks" interface, skipping the "Add new layout" form entirely, but assuming sensible defaults (like copying the default layout + layout template).

I considered this but I dont think it is the most logical way to approach it. The user would end up with a layout with the wrong template each time (if the default template really was already sensible, the user wouldnt need a different layout for node pages), and have to go through several clicks to re-configure and save a new template each time, instead of selecting their preferred template up front.

**Comment by docwilmot** [comment] 2024-04-05 15:12
> I like the idea, but I am not sure about having all the field blocks in there by default. Usually I just want the default content block and then 1-3 fields moved to other regions.

I've added a switch for choosing either field blocks or main content block. 
> If a layout already exists for node/%, that one should appear in the list of layouts also. 

This already happens. The UI doesnt yet indicate the difference between the two though, since its mostly a cut and paste of the core layout list so far. Will add details.
> Recommendations for link text the weekly meeting were: Create a layout for all content and Create a layout for [Page] content

This is good. Note FYI, this PR adds layout pages for all entities, not jsut nodes, ICYMI.

**Comment by jenlampton** [comment] 2024-04-05 16:35
>  this PR adds layout pages for all entities

I saw this in the demo, but forgot to mention it: these aren't `Layout pages`, these are all `Layout overrides` since they use an existing path, we should be careful not to confuse people by using the wrong terminology :)

**Comment by jenlampton** [comment] 2024-04-05 16:59
I've copied all the comments and the new issue desctiption over to https://github.com/backdrop/backdrop-issues/issues/2894. Closing.

**Closed by jenlampton** 2024-04-05 16:59 UTC
Labels: type - feature request
