### ISSUE TITLE
[UX] Node Form: Authored on field Broken

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1370] opened 2015-11-26 05:19 UTC
Datepicker date selection for "Authored on" and probably elsewhere results in the date format "mm/dd/YY" should be "YY-mm-dd" to be consistent and not regionally specific.

---
Issue summary from comment below:
- The `Authored on` field date format is `YYYY-MM-DD and the time zone offset from UTC`.
- The Datepicker inserts only a date in the `mm/dd/Y` format and there is no time field.
- When the user selects a date through the popup the original value gets replaced with the selected date and the user has no way of entering time.
- The `Authored on` field excepts only numbers although characters `-`, `:` and `+` are necessary to enter the correct date & time.

---

PR https://github.com/backdrop/backdrop/pull/2171

**Comment by klonos** [comment] 2015-11-26 13:56
There are quite a few tricky underlying issues here, like...

- the default formats picked for date under ```admin/config/regional/date-time``` should be set according to the selected region during installation and be updated if these change under ```admin/config/regional/settings```.
- each language should have a default date format.
- If a second language is added (and the content type is set to multilingual with translation), then the node being created should respect the current language and it's respective date format in both edit and view modes.

I vaguely remember filing issues for issues like these in d.org, but don't have the energy to locate and link to them right now. Point is the issue is deeper than what it seems.

**Comment by laryn** [comment] 2016-11-10 03:35
Just noticed this myself and it took me a minute to figure out why it wasn't letting me type dashes into the text field (I wasn't using the popup picker because the date was a few years old and I thought typing would be quicker).

<img width="584" alt="screen shot 2016-11-09 at 8 34 55 pm" src="https://cloud.githubusercontent.com/assets/871421/20163722/4c22a7e6-a6c4-11e6-8025-4e1c1d3f03b3.png">

**Comment by jackaponte** [comment] 2017-04-06 01:08
Glad I checked here; I was stumped as to why I couldn't type dashes into the "Authored on" field and am concerned my site's end users will be similarly stumped!

**Comment by laryn** [comment] 2017-04-06 14:11
@klonos @jackaponte Is there any reason not to change this label format as a stop-gap measure, until we can adjust the deeper settings that @klonos refers to above? Right now it's a pretty big failure in terms of user instruction.

**Comment by Dinornis** [comment] 2017-05-03 21:19
May I change the title to: **[UX] Node Form: Authored on field Broken** or something like that?

Here is a summary of the problems:

- The `Authored on` field date format is `YYYY-MM-DD and the time zone offset from UTC`.
- The Datepicker inserts only a date in the `mm/dd/Y` format and there is no time field.
- When the user selects a date through the popup the original value gets replaced with the selected date and the user has no way of entering time.
- The `Authored on` field excepts only numbers although characters `-`, `:` and `+` are necessary to enter the correct date & time.

**Comment by olafgrabienski** [comment] 2017-05-04 10:08
@Dinornis In my opinion yes, please! Would be good to update the issue summary above then. As far as I know and as the issue seems to be a bug, you could also set the milestone to the next bugfix release.

**Comment by Dinornis** [comment] 2017-05-04 17:22
Will there even be a 1.6.4 since 1.7.0 is due mid May?

**Comment by serundeputy** [comment] 2017-05-06 22:43
@Dinornis `1.6.4` will be released on the same day as `1.7.0` as the last `1.6.x` release.

**Comment by klonos** [comment] 2017-05-07 09:25
It is also safe to assume that @chrisherberte will not be working on the issue, so removing from the assignee field.

**Comment by Graham-72** [comment] 2017-10-19 05:00
Perhaps it is inappropriate to be using jquery datepicker on this 'Authored on' field?

**Comment by quicksketch** [comment] 2018-05-04 04:56
Thanks @laryn for cross-referencing this with https://github.com/backdrop/backdrop-issues/issues/3073.

I have filed a PR that fixes this issue at https://github.com/backdrop/backdrop/pull/2171. It switches this field to use a `date_popup` element, like the Scheduled date, but only if Date module is available. If Date module is not available, it goes back to being a textfield, though now without the jQuery Datepicker. Since nearly all Backdrop sites have Date enabled, they will all get the much nicer and consistent UI for date elements.

**Comment by quicksketch** [comment] 2018-05-11 05:38
I've merged https://github.com/backdrop/backdrop/pull/2171 into 1.x for 1.10 to resolve https://github.com/backdrop/backdrop/pull/2171, and as a side-effect, this issue is fixed as well. The new Authored on field now looks like this:

![image](https://user-images.githubusercontent.com/100206/39908383-bcae755c-54a2-11e8-9cc8-c5973e9a12a0.png)

Or with a value:

![image](https://user-images.githubusercontent.com/100206/39908401-cee56dc0-54a2-11e8-9664-edc744857e87.png)

Timezone is now always in the user's current timezone.

**Closed** 2018-05-11 05:39 UTC
Labels: status - has pull request, status - fixed
