### ISSUE TITLE
Move "flush caches" permission from admin_bar to system module

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3844] opened 2019-06-02 11:42 UTC
As per the discussion in #3617 I think we should have a new permission for viewing any messages related to caches being cleared/flushed. These aren't something most users would care, or even know, about, so I think being able to show them more specifically (e.g. just Administrators by default) would be good.

---
PR by @BWPanda: https://github.com/backdrop/backdrop/issues/2723

**Comment by klonos** [comment] 2019-06-02 15:32
@BWPanda should we close this in favor of #1062?

This is a more generic problem with all/most messages, rather specific to "cache cleared" messages. Besides, we already have a "Flush caches" permission (`flush caches`), and I think that if a user has that permission, then they should also be able to see these messages (in other words why add to the already huge list of permissions, when we can reuse `flush caches`?).

**Comment by BWPanda** [comment] 2019-06-02 16:17
I never actually went into Backdrop to see what permissions were already available :blush:

Yes, I think using the 'flush caches' permission would be fine.

**Comment by klonos** [comment] 2019-06-02 17:52
Good. I have used that permission to conditionally show the message in the PR for #3617 😉 

Let's close this as a dupe of #1062 then.

**Comment by BWPanda** [comment] 2019-06-02 18:00
@klonos I don't see how this is a duplicate... From what I understand, that issue is about making message text alterable, whereas this issue is now about updating core to wrap any 'caches cleared' messages in a permissions check... Unless I'm mistaken?

**Comment by klonos** [comment] 2019-06-03 09:49
....sorry @BWPanda, I closed the ticket because I have not noticed the renaming of the issue.

**Comment by BWPanda** [comment] 2019-06-03 10:50
@klonos  Hmm, I don't think using the existing `Flush caches` permission will work after all. It's part of the Administration bar module, which can be disabled. I think we need to find an existing permission that's from a non-disableable module, or else add a new permission for this purpose...

**Comment by BWPanda** [comment] 2019-06-03 12:29
There are only 3 places in core where I can see a `backdrop_set_message()` that mentions `cache`:

- `/admin/config/development/performance`
- `/admin/structure/views/settings/advanced`
- Admin bar

I the first two cases it makes sense that any user with access to that page should see the message. In the last case it uses the aforementioned `flush caches` permission.

So I think this is a non-issue, except for https://github.com/backdrop/backdrop-issues/issues/3617 which I'll post additional comments there. Closing then.

**Comment by BWPanda** [comment] 2019-06-03 17:51
Re-opening this issue based on @jenlampton's suggestion in https://github.com/backdrop/backdrop-issues/issues/3617#issuecomment-498346114 to "move the flush caches permission to system module."

Proposal now is to move that permission to System so it's always available, then wrap all instances of flush caches with that permission (both accessing the links/buttons and viewing the subsequent messages).

**Comment by klonos** [comment] 2019-06-03 18:04
>Proposal now is to move that permission to System so it's always available

I like this; especially now that we've got https://github.com/backdrop-contrib/navbar ported. I only recently filed https://github.com/backdrop-contrib/navbar/issues/35, which is a request to add "clear caches" (among other things) to Navbar. With admin_bar module being suppressed by Navbar, there might have been errors when attempting to clear caches. Having the permission live inside system.module (which is always on) will prevent that. Big 👍from me, and thanks @jenlampton for the idea.

**Comment by BWPanda** [comment] 2019-06-03 18:17
Made a [PR](https://github.com/backdrop/backdrop/pull/2723) that:

- Moves the `flush caches` permission from Admin Bar to System
- Wraps all 'clear caches' buttons/links with a `user_access()` check of that permission:
    - Core performance page
    - Views' advanced settings
    - Admin bar 'flush caches' link (this was already done actually)

**Comment by klonos** [comment] 2019-06-03 18:42
RTBC :+1: ...thanks @BWPanda

**Comment by serundeputy** [comment] 2019-06-23 15:59
I'm not sure about this.  I'm having trouble understanding what situation the user would not have permission to flush cache, but are shown the message?

The `/admin/config/development/performance` page is already protected by the `administer site configuration` permission. Which means we'll be checking additional permissions, more checks, more code, more slow.

I defer to @quicksketch

**Comment by BWPanda** [comment] 2019-06-23 16:09
> I'm having trouble understanding what situation the user would not have permission to flush cache, but are shown the message?

On the Appearance page I believe. Caches are cleared on saving that form and a message shown, though the average user wouldn't know what on earth it means.

**Comment by quicksketch** [comment] 2019-06-27 19:22
Overall I think this seems pretty good. Centralizing that permission instead of having it in Admin Bar makes sense to me.

> On the Appearance page I believe. Caches are cleared on saving that form and a message shown, though the average user wouldn't know what on earth it means.

In the PR, is this problem resolved? I didn't see any changes to the display of caching messages on the appearance form. Or perhaps we can/should remove any information about caches being cleared on saving the appearance page anyway.

**Comment by BWPanda** [comment] 2019-06-27 20:06
@quicksketch This PR makes it possible for https://github.com/backdrop/backdrop-issues/issues/3617 to wrap the display of the caching message in the appropriate permission (without relying on Admin Bar).

**Comment by klonos** [comment] 2019-06-29 06:44
Yup, what @BWPanda said @quicksketch 🙂

**Comment by quicksketch** [comment] 2019-07-13 18:07
Looks good. I can't see any compatibility issues so I've merged https://github.com/backdrop/backdrop/pull/2723 into 1.x and 1.13.x. Thanks @BWPanda and @klonos!

**Closed** 2019-07-13 18:06 UTC
Labels: status - has pull request, status - fixed
