### ISSUE TITLE
Date: Popup does not handle the S (English ordinal suffix for the day of the month) properly.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2688] opened 2017-05-14 02:25 UTC
### Steps to reproduce

In b.org, the medium date format field is set to `F jS, Y`. Here's what happens when entering a date in a field using the date popup:

![date-s](https://cloud.githubusercontent.com/assets/2423362/26030749/63c31080-389f-11e7-974b-f94ec82070a6.gif)

### Actual behavior

Notice how the "S" is added to the date field after clicking on a specific date. After saving, the date is all wrong (2 instead of 28 in this case) and also noticed that the year might "jump" (2017 instead of 2017). If before saving the node, you edit the date field to manually remove the "S", the date is saved properly.

### Expected behavior

That "S" should not be added to the date field and date should be saved properly.

**Comment by Dinornis** [comment] 2017-05-14 22:41
Thanks for reporting this. I just reproduced it on BD 1.7.x-dev

**Comment by jenlampton** [comment] 2017-05-15 23:14
Can you explain what the bug here is? Is the default date format wrong? Or is there something about the pop-up calendar that doesn't work?

**Comment by klonos** [comment] 2017-05-16 11:11
> Notice how the "S" is added to the date field after clicking on a specific date.

Say that you click on the 17th of May 2017 using the date popup. The field value should be "May 17th, 2017". It is "May 17**S**, 2017" instead.

**Comment by klonos** [comment] 2017-05-16 11:19
Turns out to be a known issue with the date module since the D6 days: https://www.drupal.org/node/751696

...no fix though 😞

**Comment by klonos** [comment] 2017-05-16 11:20
...from the d.org issue:

>Any ideas? Again, the exact same date format configuration works correctly on my dev site. Same version of jQuery on both machines. The staging server is running php version 5.2.6 and the dev site is running 4.4.8 which is the only difference I can find, but I can't understand why 4.4.8 would work and 5.2.6 wouldn't.

Hmm.

**Comment by daggerhart** [comment] 2017-05-16 11:50
jQuery UI's datepicker [does not allow for day-suffixes](http://api.jqueryui.com/datepicker/#utility-formatDate). 

This PR just adds capital-S to the `_date_popup_datepicker_format_replacements()` array, replacing it with nothing (effectively removing it). This will prevent the form from saving the date incorrectly.

What remains is a much-smaller UX issue that may go unnoticed by most people:

1. When the field first loads, it will display the date with the suffix: `May 17th 2017` 
![pre-edit](https://cloud.githubusercontent.com/assets/1205329/26104533/46790e30-3a0c-11e7-9597-3b3419228b9f.png)

1. If you change the field, the suffix will not be display in the field value: `May 17, 2017` 
![post-edit](https://cloud.githubusercontent.com/assets/1205329/26104538/4f17bf3c-3a0c-11e7-9fbb-da3492a8f2f5.png)


But at least the data is saved correctly.

**Comment by klonos** [comment] 2017-05-16 11:53
@daggerhart I have to ask... are you a ninja? 😄 👏

**Comment by klonos** [comment] 2017-05-16 11:58
...just one minor thing: please do not add "- solved" in your PRs' titles. It makes it show up in the release log and it's inconsistent with the rest of the entries.

**Comment by klonos** [comment] 2017-05-16 11:59
...perhaps we should provide a patch (or at least some clues) for our Drupal brethren in that old d.org issue.

**Comment by daggerhart** [comment] 2017-05-16 12:03
@klonos ahh, thanks for mentioning that (about -solved). Apparently I misread this portion of the [submitting prs page](https://backdropcms.org/develop/pull-requests). 

--- 
![submitting-prs](https://cloud.githubusercontent.com/assets/1205329/26104879/c3241a5a-3a0d-11e7-906a-ab5f9f648415.png)
---

I originally understood it as ` Example: Issue #xxx: "Description of the problem" solved.` ¯\\_(ツ)_/¯ - will correct going forward

Re: Drupal - I'll see if the fix is as straight forward as this, and give them a heads up if so.

**Comment by klonos** [comment] 2017-05-16 12:12
Yeah, in the meantime I tried finding the proper place to report this in the jQuery queue so that it can hopefully be fixed upstream at some point. There is no reported bug or feature request about this (no wonder why it's not been fixed for years). [Their instructions on how to report issues](https://contribute.jquery.org/bug-reports/) say to include a minimal/reduced code jsFiddle plus what seems a billion other things (no wonder why nobody has reported it 😄 ). Fair enough, but bad timing because although I strive to make good bug reports in order to make things easy for the devs, I do not have much time lately.

**Comment by daggerhart** [comment] 2017-05-16 12:37
Submitted a patch to Drupal 7 date module. It was a bit different because they have an additional layer of validation that happens when the date field is saving, and an additional function for listing date_popup_formats().

**Comment by klonos** [comment] 2017-05-16 13:53
I think that there might be a way to fully fix this (including the UX issue of keeping the ordinal suffix after selecting a date), but my dev skills are not strong enough. Perhaps @quicksketch (which is our JS ninja) can help here...

So, the way I understand this is that:
1. (php) function `_date_popup_format_to_popup()` receives a single parameter which is the date format as specified for the date field in a php manner.
2. (php) `_date_popup_format_to_popup()` calls the `_date_popup_datepicker_format_replacements()` helper function that converts the php-formated date format into datepicker-formated format (using an array of pairs).
3. (js) magic happens in the form so that the date that the user picks from the date popup is converted to the format from step 2 above.

Your PR @daggerhart makes it so that in step 2 if there's any `S` in the php format, it gets removed when converting to datepicker format (because there is no equivalent). How about we instead replace it with a literal text. So instead of `'S' => '',` we have something like `'S' => "'date_ordinal_suffix'",`. This can then be replaced with the proper st/nd/rd/th string after datepicker has done its magic, but before the value is passed in the form field.

Does this make any sense?

**Comment by klonos** [comment] 2017-05-16 13:57
I have a feeling that `S` is not the only php date character we are going to have this issue with. Will need to test some more once I make time in my life.

There's quite a few places on the netz that talk about the same thing:

https://stackoverflow.com/questions/16702398/convert-a-php-date-format-to-a-jqueryui-datepicker-date-format
https://stackoverflow.com/questions/8199204/adding-st-nd-rd-th-to-jquery-datepicker

**Comment by klonos** [comment] 2017-05-16 14:04
> There is no reported bug or feature request about this

I was wrong. A little bit more searching revealed this old ticket from 6 years ago https://bugs.jqueryui.com/ticket/7228 , but:

>This is out of scope for the datepicker widget. We're in the process of changing datepicker to rely on Globalize which pulls data from CLDR. You'd need to handle this yourself.

**Comment by klonos** [comment] 2017-05-16 14:08
...and of course there's people that have forked their own version of jQuery datepicker that does support ordinals: https://github.com/agschwender/jquery.formatDateTime

> The plugin supports the following formatting combinations:
> ...
> S  - ordinal suffix for the previous unit
>...

Perhaps we should use a fork then. ...I mean since we are a fork of Drupal ourselves and keeping D7 alive was "out of scope" for d.org and all 😛

**Comment by quicksketch** [comment] 2017-09-03 03:18
> This is out of scope for the datepicker widget. We're in the process of changing datepicker to rely on Globalize which pulls data from CLDR. You'd need to handle this yourself.

It's worth noting that this switch has been completed and will be in jQuery UI 1.13: http://wiki.jqueryui.com/w/page/12138038/Roadmap and https://github.com/globalizejs/globalize/issues/128, though I can't tell from the discussion if this would solve the ordinal suffix problem.

For now though, I think @daggerhart's great suggestion is both simple and effectively saves a large bug. Let's get this merged and reconsider when we do the 1.13 upgrade (which seems like it may affect a lot of things).

**Closed** 2017-09-03 04:30 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2017-09-03 04:31
I've merged https://github.com/backdrop/backdrop/pull/1896 into 1.x and 1.7.x. Thanks @daggerhart for this great find!
