### ISSUE TITLE
Add entity_view() into core

### ISSUE THREAD

**Issue by sentaidigital** [backdrop/backdrop-issues#1739] opened 2016-03-24 00:33 UTC
[entity_view()](http://www.drupalcontrib.org/api/drupal/contributions!entity!entity.module/function/entity_view/7) was in the D7 entity.module, D8 moved it to entity.inc.

----------
PR https://github.com/backdrop/backdrop/pull/3848 by @herbdool

**Comment by mikemccaffrey** [comment] 2016-10-21 23:13
In order to do this, we are going to need to add a view function into the entityInterface class:
https://api.backdropcms.org/api/backdrop/core%21modules%21entity%21entity.class.inc/interface/EntityInterface/1

And then we are going to need to implement that function in all core entity type. In most cases, it will just involve calling an existing [ENTITY_TYPE]_view().

**Comment by docwilmot** [comment] 2016-10-22 00:25
All for this, needed a `view()` for some module recently, and had to copy a `build_content()` instead. Looked into doing a core PR but seemed a bit too much at the time. Happy to help where able though.

**Comment by indigoxela** [comment] 2019-03-15 14:11
Is anyone actually working on this? Or has it been deprecated?

**Comment by docwilmot** [comment] 2019-03-15 14:28
Nobody's working on this. Feel free to start.

**Comment by jenlampton** [comment] 2021-07-09 22:23
As we talked about today at BackdropLIVE, this is the last remaining core issue preventing [Reference](https://github.com/backdrop-contrib/reference) from moving into core. See https://github.com/backdrop/backdrop-issues/issues/1301 for more details .

**Comment by indigoxela** [comment] 2021-11-22 07:36
This issue here is a blocker for both, Reference and Entity Reference - is that correct?

Can someone describe what's necessary here and why there hasn't been any progress in years? What's so tricky about entity_view()?

**Comment by jenlampton** [comment] 2021-11-22 08:21
@indigoxela  I haven't looked at the code for this in ages, but I think the problem we ran into was with files. Files do not have a `file/FID` page callback, instead, the file itself is shown. This didn't match the pattern `entity_view()` expected, so it needs to be added as an exception somehow.

**Comment by herbdool** [comment] 2021-11-24 03:04
I don't think it'll be all that tricky. I've been playing around with this and seems doable. There are some variations between the entities but an entity's method can override the parent class's method.

**Comment by herbdool** [comment] 2021-12-03 15:16
PR is here https://github.com/backdrop/backdrop/pull/3848

**Comment by herbdool** [comment] 2021-12-03 15:24
Needs a bit of work to ensure what's passed to the controller are instances of `EntityInterface`, or allow `NULL`: that should help with some failing tests.

**Comment by herbdool** [comment] 2021-12-03 17:59
And may want to ensure it won't interfere with modules that may continue to use `entity_plus`, such as Paragraphs.

**Comment by herbdool** [comment] 2021-12-03 18:29
@laryn I noticed https://github.com/backdrop-contrib/paragraphs/blob/769e1db92419cfee145a80ee1e573c0f5a14cd00/ParagraphsItemEntity.inc#L570 which is calling a `view` method but it's not in core yet and it doesn't check that it's using `EntityPlusControllerInterface`. Maybe have it like https://github.com/backdrop-contrib/entity_plus/blob/489b908ea54ebefc1ce966971c6af09c5e51a0c6/entity_plus.module#L371.

Not sure what would happen otherwise, if/when we add this to core and if the parameters are different.

**Comment by laryn** [comment] 2021-12-03 18:40
Thanks @herbdool -- I just transcribed that comment into the Paragraphs issue queue so I don't lose it. Not sure when I can look at it. I appreciate it!

**Comment by herbdool** [comment] 2021-12-07 17:28
All tests passing now.

**Comment by argiepiano** [comment] 2021-12-07 17:38
> And may want to ensure it won't interfere with modules that may continue to use `entity_plus`, such as Paragraphs.

@herbdool thank you for all this work! As you said I think we need to take a close look to be sure that modules that are using `entity_plus` don't break. Entity Plus extends the core controller, but if I'm correct, it will override the methods buildContent and view that you are providing in these PRs. Still, worth taking a closer look and tweaking EntityPlusController if needed.

If you discover any issues, please create an issue in the Entity Plus issue queue.

**Comment by argiepiano** [comment] 2021-12-09 05:51
@herbdool , I've found some conflicts with Entity Plus with the arguments of the new `buildContent` and `view` methods you've added to `EntityControllerInterface`.  The problem is that `EntityPlusControllerInterface` extends `EntityControllerInterface`, and if the methods don't contain the same arguments, you get a PHP Fatal error.

To summarize the conflicts:
- `buildContent` takes 4 arguments in the new EntityControllerInterface, as opposed to 3 in EntityPlusControllerInterface. The 4th argument is the array `context`. The method documentation doesn't really explain what `context` is.
-  `view` takes 4 arguments in both (there is no Fatal error), BUT the 4th argument is an array in the  `EntityControllerInterface`  (no documentation of  that variable), and a boolean ($page) in EntityPlusControllerInterface, which determines whether the entity will be rendered with or without titles
- And, more serious, the first argument of view in EntityPlusControllerInterface is an array of entities, while view in EntityControllerInterface is a single entity

See below for the declarations of these methods.

I'm thinking that solving the buildContent is not difficult - I can just add the fourth argument ($context array) to the next release. $context is initialized as an empty array in the declaration anyway.

But solving the issues with `view` will take some careful thinking. I haven't looked at the controllers provided in core for node, etc, but they probably follow the same argument pattern you used for these new methods. At the same time, every module that depends on Entity Plus and extends EntityPlusController uses the pattern defined in Entity Plus (with an array of entities as the first argument, and a boolean as the 4th).

Should we discuss a bit before you merge these?    


**The new `EntityControllerInterface`:**
```php
public function buildContent(EntityInterface $entity, $view_mode = 'full', $langcode = NULL, $context = array());
```
and
```php
public function view(EntityInterface $entity, $view_mode = 'full', $langcode = NULL, $context = array());
```
----
**Compared to `EntityPlusControllerInterface`  (which extends `EntityControllerInterface`):**
```php
public function buildContent(EntityInterface $entity, $view_mode = 'full', $langcode = NULL);
```
and
```php
public function view($entities, $view_mode = 'full', $langcode = NULL, $page = NULL);
```

**Comment by argiepiano** [comment] 2021-12-09 13:40
Continuing the conversation about the serious conflict with Entity Plus I reported above, some additional thoughts:
- Changing the arguments in those methods in Entity Plus is not a good option in my view. I can see someone who has, for example, Paragraphs installed, who updates core and not Entity Plus, and all their sites suddenly get WSOD
- To me, the most sensible course of action is to modify the PRs provided by @herbdool in this issue, and adjust the new view and buildContent methods (and also the new overridden versions in all core entity controllers like NodeStorageController)  to follow the pattern of Entity Plus

We are coming to adding these methods after a many years of developers depending on Entity Plus when porting stuff from D7. The contrib Entity API (which is the parent of Entity Plus) was huge in the Drupal. Something to consider carefully.

**Comment by argiepiano** [comment] 2021-12-09 16:28
> Either way if the `nid` is stored in Comment, we dont need to pass the node separately do we? Just load it from the `nid` in the `buildContent()` and `view()` methods?

@docwilmot I was going to suggest that (access the node through the `nid` property) as a way to do away with the $context variable. That would solve that conflict.

The other issue, the fact that the `view` method takes an array of entity objects as its first argument, would be more straightforward to solve in the PR provided here, since `entity_view` is being added from scratch and there are no backward compatibility issues.

**Comment by argiepiano** [comment] 2021-12-22 23:06
Tested the latest PR with core and custom entities. Works for me.

**Comment by indigoxela** [comment] 2021-12-23 09:51
This all looks great! Thank you @herbdool for providing the PR and @argiepiano for your thorough review.

Automated tests have already been requested. Any chance, @herbdool, to add them soon?

And also, several times a follow-up has been suggested in the PR comments. Does a follow-up already exist or should we create one now? It's mostly about cleanup tasks like type declarations.

Finally, maybe @laryn you also want to take a look? I think, you have a much deeper understanding of paragraphs and should be able to identify anything that could be problematic for contrib.

**Comment by indigoxela** [comment] 2021-12-23 10:41
Almost forgot: do we already have a draft for the change record?

**Comment by argiepiano** [comment] 2021-12-23 13:53
@laryn I did some testing with Entity Plus and Paragraphs - mostly to be sure there were no collisions with the new `view` and `buildContent` methods. No issues there (an old collision I noticed a couple weeks ago was resolved).

 Paragraphs extends Entity Plus' `EntityPlus` and `EntityPlusController` classes, and therefore doesn't touch the new methods and functions that @herbdool created. However I did try the new `entity_view()` function manually and it worked as expected.

**Comment by laryn** [comment] 2021-12-23 20:05
I am out of the office and away from the keyboard (mostly) for a little while here but I defer to @argiepiano's testing on this!

**Comment by argiepiano** [comment] 2021-12-25 19:29
This is RTBC for me! 👍🏽  Thanks for all the work @herbdool and @docwilmot

**Comment by quicksketch** [comment] 2021-12-27 07:20
I read through the PR, wow! This is a big chunk of refactoring and work. Thanks folks for putting this together!

Overall I think this looks great! It strikes the right balance between abstracting what we need and not getting carried away. Most of the changes are just copy/pasting things into a class from the old `*_view()` functions we have.

One concern here: In all entity controller classes, we've now added `buildContent()` and `view()` methods. But the name of these classes in all cases indicates it only deals with storage (including methods like as create(), save(), delete(), etc). Now it deals with non-storage (buildContent() and view()) operations too.

For example we've added `FileStorageController->buildContent()`. The `FileStorageController` class has the following class hierarchy:

* `FileStorageController` extends
* `EntityDatabaseStorageController` extends
* `DefaultEntityController` implements
* `EntityStorageControllerInterface` extends
* `EntityControllerInterface`

I actually think adding `buildContent()` and `view()` is okay, because Backdrop officially only supports MySQL (or compatible derivatives), and not alternative storage mechanisms. I don't think [Silkscreen](https://www.silkscreencms.org/) (an extensible Backdrop fork) even supports alternative entity storages (such as Mongo), but I could be wrong (please chime in @jlfranklin). So I think as a follow-up to this we should attempt to fix the naming discrepancies and _remove_ the word "Storage" from all the controllers, and consolidate storage and non-storage classes/interfaces together.

That would mean:

* `EntityDatabaseStorageController` would merge with `DefaultEntityController`
* `EntityStorageControllerInterface` would merge with `EntityControllerInterface`
* All entity controller classes such as `FileStorageController` would be renamed to simply `FileController`, or possibly `FileEntityController`.

These changes could be made backwards-compatible by maintaining the old class names, but having them extend the new names and have an otherwise empty content (no methods or properties).

Alternatively we could separate storage controllers from display controllers. For example introduce `FileDisplayController` in addition to `FileStorageController`, and put the new methods in that. However, that would mean changing the returned classes of `hook_entity_info()`, which right now only designates a single `controller class` key -- we'd need to change that to `display class` and `storage class`.

I think that consolidating storage and non-storage controllers into fewer classes is more inline with Backdrop's simplicity (the 80% rule) philosophy. It's was very rare to replace storage classes in Drupal and we've officially removed support in Backdrop anyway. Consolidating those classes would be a continuation of the path we've started.

But all of that might be a separate/follow-up issue. However, I want to make sure that we're okay (or not) with putting non-storage methods into storage-only classes, and have a plan for how to fix this problem we're creating in the future (basically acknowledging this is creating technical debt).

Again, great work on this PR and I think it looks great! We just need to figure out what we'll do to have this class hierarchy make sense.

**Comment by herbdool** [comment] 2021-12-28 05:46
I agree about renaming the classes to be just `FileController`, etc. I didn't really know where else to put the methods initially but settled on this because it extended the same controller as in entity_plus. I noticed Drupal 8/9 divides display and storage controllers, but it does seem unnecessary for Backdrop.

**Comment by klonos** [comment] 2021-12-28 08:51
I've read through this thread + the thread in the PR. There's many things I don't understand, but I appreciate the time/effort everyone has put in this, So thank you @herbdool @indigoxela @docwilmot @argiepiano and @quicksketch 🙏🏼

**Comment by argiepiano** [comment] 2021-12-28 15:20
I too agree about the renaming, but we also want to be careful about this, as Entity Plus (which is one of the most installed modules in Backdrop) implements `EntityControllerInterface` and extends `DefaultEntityController`. If the idea is to "merge down" `EntityDatabaseStorageController`into `DefaultEntityController` and `EntityStorageControllerInterface` into `EntityControllerInterface` then there shouldn't be any issues as long we respect the method definitions overridden by Entity Plus.  Thanks @quicksketch and @klonos for taking the time to read this long conversation!

**Comment by argiepiano** [comment] 2021-12-29 05:02
Given the issues I outlined in the PR (see comments https://github.com/backdrop/backdrop/pull/3848#issuecomment-1002299809 , https://github.com/backdrop/backdrop/pull/3848#issuecomment-1002391674 and https://github.com/backdrop/backdrop/pull/3848#issuecomment-1002395534) I believe we need more testing and possibly some tweaking. I'm removing the tag "RTBC" I added 3 days ago (before `Entity:buildContent()` was added).

**Comment by quicksketch** [comment] 2021-12-30 02:15
> If the idea is to "merge down" EntityDatabaseStorageControllerinto DefaultEntityController and EntityStorageControllerInterface into EntityControllerInterface then there shouldn't be any issues as long we respect the method definitions overridden by Entity Plus

Yes that's the idea. All the code from the storage controllers would be merged into the lower class/interface. The storage class and interface would still exist but they would just be empty, while still extending the same parent they have now.

Sounds like there's no big concern with that plan as of yet, which is great and I think we can keep working on the current approach.

**Comment by argiepiano** [comment] 2021-12-30 05:50
After the latest commit to the PR, code review and further testing I feel this is RTBC now.

**Comment by quicksketch** [comment] 2021-12-31 02:04
The last changes look good to me on the return value of `buildContent()`. I think that's more expected anyway rather than returning `NULL`. I have merged https://github.com/backdrop/backdrop/pull/3848!

Huge thanks to @herbdool for carrying the torch here, with the huge help and collaboration from @argiepiano, @docwilmot, and @indigoxela! @jlfranklin and @mikemccaffrey get props for filing the original issue and helping organize our original plan for getting entity reference into core.

Great work folks!

We still need a change record for this. Although it's entirely additive, the additions appear to provide some better alternatives for contrib that were either duplicating similar functionality or working around the previous limitations.

**Comment by quicksketch** [comment] 2021-12-31 02:47
I drafted an initial change record at https://docs.backdropcms.org/change-records/generic-entity-view-and-build-content-added could any copy editors review and suggest changes? It might also be good to get real-world examples from contrib that might be impacted, I generalized the before and after code samples.

**Comment by quicksketch** [comment] 2021-12-31 03:08
I filed a small follow-up PR at https://github.com/backdrop/backdrop/pull/3880. Usually I'll directly added `@since` lines when I do the merge but there are a few other docblock changes that wouldn't hurt getting a review. @herbdool or @argiepiano could you check if we should add any other inline documentation changes?

**Comment by argiepiano** [comment] 2021-12-31 15:35
> I drafted an initial change record at https://docs.backdropcms.org/change-records/generic-entity-view-and-build-content-added could any copy editors review and suggest changes? It might also be good to get real-world examples from contrib that might be impacted, I generalized the before and after code samples.

@quicksketch this looks good to me. My only suggestion is to add

```php
case ('file'):
 $output = file_view($entity);
```

 in the "Before Backdrop 1.21.0" switch cases, just for completeness.

**Comment by quicksketch** [comment] 2022-01-02 01:57
Thanks @argiepiano! I added that suggestion to the change record examples.

**Closed** 2022-01-02 01:59 UTC
Labels: type - task, status - has pull request, status - fixed
