### ISSUE TITLE
1.6.0 regression: Layouts: Header block: Site info checkboxes not saved after hitting the "Update block" button.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2473] opened 2017-01-16 04:01 UTC
From my testing, this only happens with this specific block and only for these specific settings within it (logo, name, slogan). The rest of the block settings seem to be saved fine. Seems to be caused by the move of these settings inside a fieldset in https://github.com/backdrop/backdrop/pull/1723

PS: this effects only the ability to show/hide the logo/name/slogan. There respective settings under `admin/config/system/site-information` are saved properly and also properly rendered in the header section.

---
~PR by @klonos: https://github.com/backdrop/backdrop/pull/1756~
Replaced with PR by @jenlampton at https://github.com/backdrop/backdrop/pull/1778 (Edit Dinornis)

**Comment by klonos** [comment] 2017-01-16 04:37
...back to needs work. Although the PR works in saving the layout, a lot of things stop working or break because the logo/name/slogan are now saved nested 1 level deeper within a `components:` property in the .json file...

Before:

```json
"block_settings": {
    "menu": "user-menu",
    "logo": 1,
    "site_name": 1,
    "site_slogan": 1
},
```

After:

```json
...
"block_settings": {
    "menu": "user-menu",
    "components": {
        "logo": 1,
        "site_name": 0,
        "site_slogan": 1
    }
},
...
```

**Comment by herbdool** [comment] 2017-01-16 14:15
@klonos I can confirm this. Can you update it to mention this is the Header block?

**Comment by jlfranklin** [comment] 2017-01-18 22:40
Likely the same issue as #2478.

**Comment by jenlampton** [comment] 2017-02-03 01:30
I've pushed a new PR that saves the settings without the troublesome 'component', similar to how they were saved before. This should do the trick.

**Comment by klonos** [comment] 2017-02-03 12:36
Code looks good and the PR sandbox works 👍

We should probably add a test that checks whether these settings are saved to make sure that this does not regress again.

**Comment by Dinornis** [comment] 2017-02-03 19:16
Seems to be working as expected.
Also ran Block, Layout, Render and Theme tests using the `/admin/config/development/testing/` (hope that's okay) no fails or exceptions.

**Comment by klonos** [comment] 2017-02-03 19:46
Thanx for testing and reporting back @Dinornis. Must be my local then, but I see that on various browsers. Could be the non-clena URLs too.

**Comment by quicksketch** [comment] 2017-02-10 00:23
I looked at this and it does fix the problem. We could have made this a shorter fix by simply adding a `#parents` line to the `$form['components']` element like this:

```php
  $form['components'] = array(
    '#type' => 'fieldset',
    '#title' => t('Site information'),
    '#description' => t('Show or hide various components of your site header. To change the values of these components, visit the !site_info page.',
      array('!site_info' => l(t('Site information'), 'admin/config/system/site-information'))),
    '#parents' => array('block_settings'),
  );
```

But even though it's shorter, it's mysterious to most people why this would solve the problem (Layout puts the entire custom block form inside an invisible element called "block settings"). So instead I think @jenlampton's PR is just fine. I made a minor change to unset() the entire "components" value though, previously it was left saved into config as an empty array.

**Comment by quicksketch** [comment] 2017-02-10 01:45
Merged https://github.com/backdrop/backdrop/pull/1778 for 1.6.1.

**Closed** 2017-02-10 01:44 UTC
Labels: pr - reviewed & tested by the community, status - has pull request, type - bug report
