### ISSUE TITLE
[UX] Date format tokens for date field missing 

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2069] opened 2016-08-16 21:21 UTC
**Description of the need**

We can customize the format of the `[node:created]` and `[node:updated]` tokens, by adding `custom` followed by the date format, like so: `[node:created:custom:Y-m-d]`.  But adding `custom` and a date format to date field tokens is not allowed. 

As a user, once I have learned how to customize date tokens, it feels like a bug that it does not work on date fields. This should be included in core.

The last comment by @docwilmot below mentions that we could tackle this problem separately from the token view modes (which is done now), but it seems that we never got back to the tokens.

This is a new issue to help is get that done :)

**Proposed solution**

Allow the `custom` modifier on date field tokens, to match `[node:created]` and `[node:updated]`.

The token format for dates could be something like `[node:field_date:0:custom:Y-m-d]`, or `[node:field_date:1:custom:Y-m-d]` if it's a multi-value date field. For end-date tokens, something like `[node:field_date-end:1:custom:Y-m-d]`.

**Alternatives that have been considered**

Many people have reported this issue before, but it seems that even though other solutions have been added, but the original issue has not been addressed yet. Re-opening this issue to see if we can add to the core tokens.

* [Token display format is not configurable (and date token creates very long paths)](https://github.com/backdrop/backdrop-issues/issues/1425#issuecomment-461951877) by @mikemccaffrey - solved by adding a token view mode
* [Add missing tokens for date fields](https://github.com/backdrop/backdrop-issues/issues/2652) by @olafgrabienski - closed as duplicate of #1425 above
* [THIS ISSUE: Date format tokens for date field missing](https://github.com/backdrop/backdrop-issues/issues/2069) by @jenlampton - Originally closed in 2017 as a duplicate of #2652 above -- reopening now in 2020.

> I was also a little surprised to find that wasn't working. I think this functionality should also exist by default. It works for [node:created] e.g. [node:created:short], but not for date fields. Looks like something that didn't make it in the port somehow. -- by @quicksketch 

> the token view mode was done [in Drupal 7] but not field support. We could do them separately as well but its not going to get in to 1.12 anyway, so I parked it for now. -- by @docwilmot

**Comment by klonos** [comment] 2017-05-13 11:29
Let's close this as a duplicate of #2652 as the other issue has a more detailed description.

**Comment by jenlampton** [comment] 2020-09-03 17:38
I'm re-opening this issue since we didn't manage to get the token support in previous issues. I've updated the description to include recommended solutions, and links to previous issues where this has been discussed.

**Comment by indigoxela** [comment] 2020-12-14 09:16
FTR: the entity_token module ships with these tokens:

![date-field-tokens](https://user-images.githubusercontent.com/842066/102062661-53f85e80-3df5-11eb-9bd2-4dc7053ec4d1.png)

**Comment by olafgrabienski** [comment] 2020-12-14 10:17
> the entity_token module ships with these tokens

Thanks, @indigoxela . Is this for information, or are you against integration of the date format tokens in core?

If the latter: I had the impression that many people (including me) expect core to do the job. For that discussion see also the related issues mentioned in the description of this thread.

Re Entity Tokens, personally I'd like to not install this module plus dependencies (https://github.com/backdrop-contrib/entity_token/issues/3) just for date tokens. While usually I don't miss other tokens, I miss formattable date tokens on many of my sites.

**Comment by indigoxela** [comment] 2020-12-14 10:19
> Is this for information, or are you against integration of the date format tokens in core?

Purely for information. If we add it to core, we have to take care of migration steps.

**Comment by argiepiano** [comment] 2021-12-02 05:25
I can help getting the core tokens for date fields to work as described above. 

I started maintaining the contrib module entity_token recently and have looked in detail into tokens. I am doing a pretty full rewrite of entity_token (Backdrop has more robust token support in core than D7, and the contrib entity_token is not as needed in Backdrop as it was in D7). I was planning on adding some of this to entity_token, but can definitely help bring this to core. I'll work on this over the weekend.

**Comment by argiepiano** [comment] 2021-12-04 00:57
I have created a first PR that adds chained tokens for date fields. Please read the explanation there.

PR: https://github.com/backdrop/backdrop/pull/3849

**Comment by olafgrabienski** [comment] 2021-12-05 15:10
Thanks for the PR, @argiepiano ! I'm looking forward to test it but will need some time.

Btw, the PR's sandbox website isn't working for me at the moment ("Oops! Something went wrong..."), hopefully a temporary issue.

**Comment by olafgrabienski** [comment] 2021-12-06 12:29
Tested in the sandbox (which is working again). Looks good to me!

I've followed the steps in the [PR description](https://github.com/backdrop/backdrop/pull/3849#issue-1071076281) and didn't have any issues. Devel shows the correct values for the tokens.

I've also used a custom date token for a URL alias pattern (my main use case), and it works like a charm. Example:

- `posts/[node:field_date:date:custom:Y-m-d]/[node:title]` =>
  `posts/2021-12-31/test-event-with-date-field`

**Comment by olafgrabienski** [comment] 2021-12-06 12:33
Marked as `works for me`. Do we want another pair of eyes for more advanced use cases?

**Comment by argiepiano** [comment] 2021-12-06 15:36
Thanks @olafgrabienski . If anyone else could test that'd be great, but this addition is unlikely to break anything (these chained tokens did not exist, and if the fail they simply return an unfulfilled $original).

What we do need is to create/expand the automated token tests to tests for these. That will take me some time... unless someone else wants to give try that.

**Comment by indigoxela** [comment] 2021-12-11 12:54
> If anyone else could test that'd be great

Sure, just tested it. Works great! I tested with the multi value field and a token like `article/[node:field_date_multiple:1:custom:Y-m]/[node:title]` ("1" is the delta, so the second date in that field.)

One question regarding token browser (really only a question):

On /admin/structure/types/manage/article (the node type setting, vertical tabs) this node type's date fields appear top level, which is great.
On /admin/config/urls/path/patterns (the url patterns admin page) a plain "Date fields" without available tokens appears. I guess, that's inevitable - or is it possible to suppress the output if there's no tokens? The tokens do appear below "Content" with "Content url alias patterns" on that page. Possibly that's out of scope of this issue.

![token-browser](https://user-images.githubusercontent.com/842066/145677022-4f7bbabb-637f-4f97-ab7c-0b7cfb9a5419.png)

**Comment by argiepiano** [comment] 2021-12-11 15:21
> I guess, that's inevitable - or is it possible to suppress the output if there's no tokens? The tokens do appear below "Content" with "Content url alias patterns" on that page. Possibly that's out of scope of this issue.

@indigoxela , the token type "Date fields" is a helper type that acts as a bridge between the field token fulfillment (provided in field.tokens.inc)  and the date token fulfillment (provided by system.tokens.inc).

After working in depth with tokens for a few weeks I have come to realize that the tokens and tokens types defined in `hook_token_info` are used mostly for the UI display, and it's "decoupled" from the actual token fulfillment provided by `hook_tokens`.  Therefore it is possible to hide that empty "Date fields" token type by simply not declaring it in `hook_token_info`. Even when not declared, that helper token type can still be used in the token fulfillment logic. 

You still will find all the field date tokens in the UI inside the "Content" and other trees.  

I'll make that change in the next couple of days and you can test again, @indigoxela ?

**Comment by indigoxela** [comment] 2021-12-12 11:44
> I'll make that change in the next couple of days and you can test again

@argiepiano sure, go ahead and let me know, when there's something to test.

**Comment by argiepiano** [comment] 2021-12-13 04:35
@indigoxela I've made the change that hides the empty "Date field" token type from the list of tokens. Functionality remains the same - the adjustment only affects the UI. If you'd like to test, that'd be peachy.

**Comment by indigoxela** [comment] 2021-12-13 08:20
> If you'd like to test, that'd be peachy.

I just did, and it works pretty well, the empty entry on /admin/config/urls/path/patterns is gone, the tokens are still available below "Content", the tokens on the individual node type form are still there. :+1:

I've left some suggestions re coding standards, otherwise the code looks good.

**Comment by indigoxela** [comment] 2021-12-13 08:55
Oh, I almost forgot to mention one finding re the empty "Date fields": that happened because you had a typo in your date_token_info():

You had `'needs-date' => 'date-field',` but it should have been `'needs-data' => 'date-field',` - "needs-dat**a**". It seems to work without that $info['types']['date-field'] parent definition, though.

**Comment by argiepiano** [comment] 2021-12-13 13:41
> You had `'needs-date' => 'date-field',` but it should have been `'needs-data' => 'date-field',` - "needs-dat**a**". It seems to work without that $info['types']['date-field'] parent definition, though.

Good catch, @indigoxela ! Still, that fix would have assure that any defined tokens with type 'date-field' would have been shown under Date field. Since there are no defined tokens for that type, it would still be shown empty. It's a helper type that's there to provide a bridge between the field tokens (which are always grouped under a type name that coincides with the entity name they are attached to), and the 'date-field-value' type, which is used to fulfilled date tokens 'date' (i.e. starting date) and 'end-date'.

**Comment by indigoxela** [comment] 2021-12-13 14:23
I just learned a new word: "pettifogging" - I guess, that's what I am with some more tiny standard fix requests. See my comments on your PR. :grinning:

**Comment by indigoxela** [comment] 2021-12-14 07:35
Time to set a milestone here, as we're super close to finalizing.

**Comment by indigoxela** [comment] 2021-12-14 07:47
Re extending the [token tests](https://github.com/backdrop/backdrop/blob/1.x/core/modules/simpletest/tests/token.test)...

I'm not sure what makes sense here. Maybe similar to TokenNodeTestCase? Add a content type with date fields (which variants?), set field values, post, check for the alias?

Maybe simplified? A function saveEntityAlias() exists - that possibly makes the test easier and more lightweight.

**Comment by argiepiano** [comment] 2021-12-17 04:12
I have added a test for chained date fields. I believe this completes the task. Please check the code.

**Comment by indigoxela** [comment] 2021-12-17 07:34
> I have added a test for chained date fields.

Great, we have tests!

@argiepiano there are some pending comments on your PR, small things like punctuation.

**Comment by argiepiano** [comment] 2021-12-17 13:48
> @argiepiano there are some pending comments on your PR, small things like punctuation.

@indigoxela I resolved and committed all your punctuation comments a few days ago. Am I missing something? Please clarify.

Will you want this feature to be added to the 1.21.0? What's the next step to make this happen?

**Comment by indigoxela** [comment] 2021-12-17 13:54
> I resolved and committed all your punctuation comments a few days ago. Am I missing something?

@argiepiano  Seems like you missed two of them: https://github.com/backdrop/backdrop/pull/3849/files (Yes, I do feel a bit silly being so picky with punctuation. :wink:)

And there's a general suggestion (optional) re using both, isset and empty, when using empty already covers the task.

Next steps: This issue already has a milestone set, so after being marked as RTBC, a core committer will do final review and merge it into the next minor, which comes out in January.

**Comment by argiepiano** [comment] 2021-12-17 14:10
@indigoxela no problem, but I need help here. I'm just not seeing those two pending comments in the PR. When I open the PR I see a bunch of resolved comments, things I fixed a couple of days ago. Can you please point me in the right direction? Like give me a file name and line number? 

Also, regarding isset, again, I'm not seeing a comment for that in the PR. There are several issets there. Can you please point out the file and line? 

Thank you for your patience!

**Comment by indigoxela** [comment] 2021-12-17 14:22
> I'm not seeing a comment for that in the PR.

That's really odd... :thinking: Wonder, what could be causing this.

In file core/modules/date/date.tokens.inc, line 86:
```
if (isset($data[$type]) && !empty($data[$type]) && is_a($data[$type], 'Entity')) {
```
The isset seems redundant, as !empty() also checks that it exists.

And the two missing fullstops in the same file are in line 118 and 125.

> Thank you for your patience!

Thank YOU for your patience. :wink:

**Comment by argiepiano** [comment] 2021-12-17 14:30
@indigoxela , great! I'm not sure why I'm still not seeing those 3 comments, but I've fixed those two periods and the redundant isset.  Let me know if you see anything else.

**Comment by indigoxela** [comment] 2021-12-17 14:46
Funny, you don't see the comments, and I can't "resolve" them... might be a Github (permission) thing.

Anyway, let's not get confused by infrastructure quirks, RTBC!

**Comment by quicksketch** [comment] 2021-12-19 19:38
I tested this to check that end-dates show in the Token UI and they do!

![image](https://user-images.githubusercontent.com/100206/146688413-89669e65-3de1-4086-aa65-a556b9722a7f.png)

The tokens supported are a lot more extensive than those shown in the UI, like multiple field support, but that UI quirk exists for all multivalue fields.

This looks and works great! Amazing work @argiepiano, @indigoxela, and @olafgrabienski!

**Closed** 2021-12-19 19:42 UTC
Labels: type - feature request, pr - ready to be committed, pr - works for me

**Comment by quicksketch** [comment] 2021-12-19 19:43
I've merged https://github.com/backdrop/backdrop/pull/3849 into 1.x for 1.21.0. Great work @argiepiano, @indigoxela, and @olafgrabienski!
