### ISSUE TITLE
Uncomment tests for Views Filters containing operator 'is none of'

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4092] opened 2019-09-26 20:34 UTC
This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/3614 so we remember to uncomment two tests after all the views cross-ports are in.

**Comment by BWPanda** [comment] 2019-11-07 14:27
Duplicate of https://github.com/backdrop/backdrop-issues/issues/4049

**Closed by BWPanda** 2019-11-07 14:27 UTC
Labels: status - duplicate
