### ISSUE TITLE
Fix full-bleed for hero image in Basis

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2190] opened 2016-09-15 19:58 UTC
follow-up to https://github.com/backdrop/backdrop-issues/issues/1361 reported by @klonos 

From @wesruv:

> The issue I'm trying to wrap my head around is how to pop out of the layout without causing a bugs/horizontal scrollbars.

From @jenlampton

> I think bootstrap has a way to do this, something like `.jumbotron`. 

From @wesruv:

> Full width backgrounds are possible (like the header bg color), but they need to be done on the region, not the block.

From @quicksketch:

> True, yeah no attributes/classes on regions. We've been fighting that but it may be a losing battle. I think the solution you've applied that works with what we have is a great start, even if it's not exactly what we wanted.

From @docwilmot:

> Thats sad that we can't do this with current core. I am going to push a contrib version of all the core layouts with the .container div inside the region divs

From @jenlampton:

> But basis is a theme. Override 10 core layout files, replace .container
> with .container-fluid. Problem solved?

From @docwilmot:

> [...] Having to override every layout [...]  just to get a hero goes against my principle that it should just be doable from the UI. see [more](https://github.com/backdrop/backdrop-issues/issues/1361#issuecomment-247056177)

From @wesruv:

> I vote we work on making [settings for regions], and then we can have this feature in a nice sane way.  [...] there are probably other solutions, but this late in the game, and for core especially, I think we go with what we have.

From @jenlampton:

> Settings for regions still isn't an majority use case imo, and not a good candidate for core. If we're doing it only because we have a `.container` class in the wrong place, it would be better to fix that root problem than add an edge-casey feature. see [more](https://github.com/backdrop/backdrop-issues/issues/1361#issuecomment-247111245)

From @klonos:

> I also say go with what we currently have and consider full width hero (or any region) in a separate issue. If we title that issue "No full-bleed in Basis", then we can consider it a bug (or known issue) of the initial mockup and target that issue for the 1.5.x cycle. If this is considered a feature ("Allow setting the hero block to be full width"), then we target it for 1.6.0 instead.

Other things we may want to fix with this issue:
- [ ] excess margin above hero
- [ ] excess margin around messages
## Lots of options for PRs, all work with varying degrees of cleanliness.

~~PR from @jenlampton at https://github.com/backdrop/backdrop/pull/1596 - Template overrides for all layouts~~
PR by @jenlampton: https://github.com/backdrop/backdrop/pull/1593 - template for front page only
PR by @jenlampton: https://github.com/backdrop/backdrop/pull/1598 - CSS only fix.
PR by @quicksketch: https://github.com/backdrop/backdrop/pull/1621 - Preprocess hero block variables
PR by @wesruv: https://github.com/backdrop/backdrop/pull/1656 [using `ellipsis`]
PR by @serundeputy: https://github.com/backdrop/backdrop/pull/1675/files [using `breakword`]

**Comment by wesruv** [comment] 2016-09-15 21:40
Confirmed that this needs to be punted.

At some point the decision was made to add `l-wrapper` with a `container` class which wrapped all of our content area regions (top, content, etc). So we can't make full width blocks without introducing some nasty bugs. (see https://github.com/backdrop/backdrop-issues/issues/1361#issuecomment-246860734)

I'm thinking this could be configuration in layouts instead of hard coded in the TPL. We could add the ability to make certain rows fluid or fixed, and default an entire layout to either fluid or fixed widths.

Currently they're all fixed.

Another option is we could make a special template with a full width Top or Hero region.

**Comment by quicksketch** [comment] 2016-09-16 06:05
Let's consolidate https://github.com/backdrop/backdrop-issues/issues/2191 with this issue. We have an issue with margins around the hero. Right now they aren't bothersome because we lost the full bleed from the mockup. I think if we add the full bleed, we should also eliminate the margin above the hero.

**Comment by wesruv** [comment] 2016-09-16 15:52
I tried to fix the issue from #2191 yesterday, but couldn't do it with pure CSS. I think some template.php logic in preprocess layout should do the trick.

Check to see if there are status messages
Check to see if first block in top region is hero
If so, add a class that removes the margin from the header region.

**Comment by jenlampton** [comment] 2016-09-30 01:52
I just recently built a theme that had a full-bleed on the breadcrumbs (in the `top` region). I had to figure out how to support a single full-bleed region in my theme where the rest of the regions was not full-bleed, and it wasn't hard to do starting with the core layout template markup.

![screen shot 2016-09-29 at 6 38 34 pm](https://cloud.githubusercontent.com/assets/397895/18978007/0394995a-8674-11e6-8b7f-57d57f199417.png)

What I did was this:
* in every template file (yes, all 10) move the top region outside the fixed-width container, between `<div class="l-wrapper">` and `<div class="l-wrapper-inner container container-fluid">`
* on breadcrumbs, add an inner div with class `container` to center the content on the bleed.

In basis, we could do the same thing.
* in every template file (yes, all 10) move the top region outside the fixed-width container, between `<div class="l-wrapper">` and `<div class="l-wrapper-inner container container-fluid">`
* on the hero, add an **inner** div with class `container` to center the content
* on the breadcrumbs, add an **outer** div with class `container` to center the content

**Comment by quicksketch** [comment] 2016-09-30 02:28
I'd like to get feedback from others on the current PR overridding all 10 layout template files. I get that it's a relatively easy thing to copy/paste template files when making themes, but overriding all 10 layouts in core's default theme seems unclean to me. I'm also a little sad to see a hero block template after we did the work to avoid that initially. As before, that template will only work if using the "Default" block style, switching to "Dynamic" would break the theming.

**Comment by jenlampton** [comment] 2016-09-30 02:56
> I'm also a little sad to see a hero block template after we did the work to avoid that initially. 

Oh yea, I forgot about that. :(

>  I'd like to get feedback from others on the current PR overridding all 10 layout template files

Me too, especially from @wesruv. 

Here's my take on it: If we expect all contrib themes to do this in order to "support" all the layouts in core, I don't see why it's unclean to do it in a core theme. We are supposed to be providing a good example that contrib can follow, and this would show them the way. Providing two sets of templates also covers the two most popular use-cases for needing some-but-not-all things to be full-bleed: 
1) only header/footer are full-bled (done cleanly in core layout templates)
2) other parts of the page are also full-bleed (done via template overrides in basis)

**Comment by docwilmot** [comment] 2016-09-30 04:08
No we cant do this. Provide a core feature and override it completely in the same core? No. 
Either we fix layout templates or we come up with a JS solution, or we leave it to contrib (https://github.com/backdrop-contrib/hero).

**Comment by jenlampton** [comment] 2016-09-30 05:10
> Provide a core feature and override [the HTML] completely in the same core? No. 

Themes are there to change the HTML comes out of modules. Core themes shouldn't be any different. It's not "the same core" necessarily, it's layout (module) and basis (theme).

> Either we fix layout templates...

There's nothing wrong with the current layout templates, they just don't match the design we chose for the basis theme. There are plenty of other designs in the world that have the "hero" be the same width as the rest of the content. We just chose to put one that doesn't in core (granted, because it's more modern, and we *do* want to be more modern!) :)

> ...or we come up with a JS solution, or we leave it to contrib 

There are other solutions, too! 

I like @wesruv's [idea](https://github.com/backdrop/backdrop/pull/1593#pullrequestreview-2264029) about adding another theme-hook-suggestion for `front`. That would reduce the template-overrides from 10 to 1. The downside to this approach is that if anyone chose a different layout template for their home page, the hero wouldn't be full-bleed anymore.

There's also probably also a CSS-only solution, too. What if we changed all the `.container` classes to remove the fixed-width? Then we could add back a fixed-width only where we wanted it. It's not a very bootstrappy solution, but might work.

**Comment by jenlampton** [comment] 2016-09-30 05:33
I just pushed an updated PR that adds a theme hook suggestion for only the front page layout, and overrides only that one single template. See https://github.com/backdrop/backdrop/pull/1593

**Comment by jenlampton** [comment] 2016-09-30 06:06
I just pushed another PR (just to see if it was possible - it is!) with a CSS-only approach: https://github.com/backdrop/backdrop/pull/1598

**Comment by klonos** [comment] 2016-09-30 06:10
I do understand all the talk and arguments around this subject and I do not particularly like one idea/solution better than another. All I care about as an end user is that I want an easy way to achieve the end goal which is that I would like to be able to make certain layout regions full-width without mush effort. If possible, I would like that to be a configuration setting either on the block or the region(s). The easier solution so far (without having to touch code) is to install @docwilmot's https://github.com/backdrop-contrib/hero.

...my 2c

**Comment by jenlampton** [comment] 2016-09-30 07:17
> If possible, I would like that to be a configuration setting either on the block or the region(s).

There is no way to customize a region yet. If someone makes a contrib project for region-settings, however, that could be one way to get that setting. :)

A block-setting for full bleed is possible using classes. If you are using a bootstrap4-based theme, for example, then adding the classes `jumbotron` and `jumbotron-fluid` may achieve what you are after, provided there is not a fixed-width on a parent container. Unfortunately, all the layouts in core currently put a fixed-width on the parent containers. In order to get around that, those layout templates would either need to have been overridden in your bootstrap4-based theme (similar to in my first PR), or you would need a whole new set of layout templates to work with (like `hero`).

**Comment by docwilmot** [comment] 2016-09-30 15:47
> what about adding a new 'hero' region to all templates that is full-bleed?

This should be doable without affecting existing sites. Essentially same thing done in contrib.

**Comment by jenlampton** [comment] 2016-09-30 19:53
We can't change the markup in core. Even if we can add a region and change
nothing else, the API change is questionavle. But we can't change classes
or add div's anywhere as people have already styled the markup that's
there, and copied the previous templates to themes (that wouldn't get the
new regions) etc.

**Comment by docwilmot** [comment] 2016-09-30 20:07
JQuery or contrib or 2.0 then.

**Comment by olafgrabienski** [comment] 2016-10-03 20:57
> The issue I'm trying to wrap my head around is how to pop out of the layout without causing a bugs/horizontal scrollbars.

@wesruv - I guess, your first approach to pop out of the layout (but causing horizontal scrollbars) was CSS only, right? I googled the question getting two promising pages:

- https://coderwall.com/p/hkgamw/creating-full-width-100-container-inside-fixed-width-container
- https://css-tricks.com/full-browser-width-bars

Seems that `html, body { overflow-x: hidden; }` could do the trick. Not tested personally yet, though. What do you think about it?

**Comment by quicksketch** [comment] 2016-10-19 04:46
> I guess, your first approach to pop out of the layout (but causing horizontal scrollbars) was CSS only, right?

I tried this myself and found it worked okay. Firefox on my desktop always shows the vertical scrollbar, so I ended up with a horizontal bar caused by 100vw. However, adding `overflow: hidden` indeed solves the problem. I put it on the `.layout` wrapper and got the desired result.

However, then I had a problem where the text was all the way against the left end of the page. To fix this, I wrapped the title and block content in an additional wrapper in `hook_preprocess_block()`. This gets the desired result:

Before:

![screenshot from 2016-10-18 21-43-01](https://cloud.githubusercontent.com/assets/100206/19505951/e84e924c-957b-11e6-8032-f36aa357cfd8.png)

After:

![screenshot from 2016-10-18 21-42-26](https://cloud.githubusercontent.com/assets/100206/19505948/e40aad88-957b-11e6-95e0-ea3b37ef5674.png)

Overall this is low-impact. No new templates and it would work with all layouts. The downside though is it's not very clean and other themes would need to do something similar to get the same effect (though they would need to do that with the template-overriding approach as well).

PR could use review at https://github.com/backdrop/backdrop/pull/1621

**Comment by olafgrabienski** [comment] 2016-10-19 21:24
> I wrapped the title and block content in an additional wrapper in hook_preprocess_block().

Nice!

> in core, (...) we can't change classes or add div's anywhere

I'm not sure if the cited verdict in https://github.com/backdrop/backdrop-issues/issues/2190#issuecomment-250836973, which refers to the idea of adding an entire hero *region*, should apply to the very 'small' and specific additional hero block wrapper which probably won't interfere with existing customizations. I'd say, in this case, we could still consider to change core, instead of letting themes do the wrapper job, can't we?

**Comment by klonos** [comment] 2016-10-21 10:20
In the upcoming DrupalSouth presentation, I would like to dazzle everybody with the new Basis theme and the drop-down menus out of the box, but the fact that we do not have a full-bleed hero block out of the box spoils things. Is there any chance we can reconsider this, re-target for 1.5.2 AND release 1.5.2 before the 27th (next week)? ...or am I asking too much 😄 ...seriously though.

**Comment by klonos** [comment] 2016-10-21 11:24
...couple of things as feedback for @quicksketch's PR:

1. The home layout has a "Breadcrumb" block in it but no actual breadcrumb rendered on the home page. Should we just remove that block from that layout then? Separate issue?

2. For layouts that include full-bleed hero blocks, should we be rendering the site messages *below* the hero block? It just doesn't look right to me (also separate issue?):

![backdrop-basis-messages_above_full-bleed_hero_block_dont_look_good](https://cloud.githubusercontent.com/assets/2423362/19596941/0dfe69f0-97dd-11e6-9477-8ca05b3c319d.png)

**Comment by wesruv** [comment] 2016-12-01 22:08
I think this PR is ready to go: https://github.com/backdrop/backdrop/pull/1656

**Comment by wesruv** [comment] 2016-12-01 22:15
That's a version of Jen's homepage template with a few modifications and it puts the hero in the top region by default.

**Comment by jenlampton** [comment] 2016-12-01 23:14
I just tested the PR and it looks great to me. I'm marking as RTBC but would love another set of eyes on it as well!

**Comment by serundeputy** [comment] 2016-12-03 00:22
This looks great to me RTBC.

I pulled it down and gave a long site name and did not get horizontal scrollbars as reported here: https://github.com/backdrop/backdrop/pull/1656#issuecomment-264341715  

I was testing with chrome inspector for iPhone5, 6, and Galaxy S5.  @docwilmot what device were you using?

@wesruv can you see if you can reproduce the horizontal scroll issue?

here is iphone5 logged out with chrome inspector:
<img width="334" alt="screen shot 2016-12-02 at 7 20 57 pm" src="https://cloud.githubusercontent.com/assets/6763671/20854782/a5adb582-b8c4-11e6-9dda-4b3d14396f41.png">

**Comment by docwilmot** [comment] 2016-12-03 00:37
Try "whealkadelliosauruses" 😄

**Comment by serundeputy** [comment] 2016-12-03 00:56
yep; 

<img width="326" alt="screen shot 2016-12-02 at 7 49 30 pm" src="https://cloud.githubusercontent.com/assets/6763671/20855219/1d0bf162-b8c9-11e6-8f71-d17f3325eaa7.png">

@wesruv can we get some css magic here; something like `break-word: overflow-wrap` or something?


![breakword](https://cloud.githubusercontent.com/assets/6763671/20855249/6af0e248-b8c9-11e6-8095-bb8fe7ac9447.png)

**Comment by klonos** [comment] 2016-12-06 00:31
> @wesruv can we get some css magic here; something like `break-word: overflow-wrap` or something?

👍

**Comment by klonos** [comment] 2016-12-06 00:53
I just gave the PS sandbox a spin too an I could not break it 😄 ...other than the horizontal scrollbar with long site names that is.

> For layouts that include full-bleed hero blocks, should we be rendering the site messages below the hero block? It just doesn't look right to me as it is now between the header and the hero (also separate issue?):

@wesruv you 🔨 it!!:

![backdrop-issue2190-pr1656-nav_menu_goes_mobile_too_soon](https://cloud.githubusercontent.com/assets/2423362/20908487/5ec4f350-bba9-11e6-9d5f-89ffc5a27a53.png)

...only thing I see wrong now is that our nav menu goes mobile a bit too soon: #2380

**Comment by quicksketch** [comment] 2016-12-09 01:50
Merged https://github.com/backdrop/backdrop/issues/1656 into 1.x and 1.5.x for 1.5.3. Thanks everyone!

**Comment by docwilmot** [comment] 2016-12-15 21:12
this was merged but the overflow fix wasnt yet added

**Comment by jenlampton** [comment] 2016-12-16 00:22
Is there a new PR for the overflow problem? Marking this as NW so it doesn't get overlooked.

**Comment by wesruv** [comment] 2016-12-16 00:46
@docwilmot @jenlampton overflow fix?

**Comment by jenlampton** [comment] 2016-12-16 01:08
[this](https://github.com/backdrop/backdrop-issues/issues/2190#issuecomment-264597859)

**Comment by serundeputy** [comment] 2016-12-16 01:08
@wesruv https://github.com/backdrop/backdrop-issues/issues/2190#issuecomment-264601664

**Comment by wesruv** [comment] 2016-12-16 15:51
Ahh... we can address that for modern browsers, I'll cook up a fix soon.

Ideally people update their hero styles if they have really long words in it.

**Comment by wesruv** [comment] 2016-12-16 17:29
Here's what I can offer with some fancy pants CSS:
![image](https://cloud.githubusercontent.com/assets/5607236/21271952/2c085bfc-c38b-11e6-865f-51f9e16e8348.png)

I think it's the best we can do given we can't accommodate all content ever, and this is a subtheming or content issue.

PR Here: https://github.com/backdrop/backdrop/pull/1672

**Comment by wesruv** [comment] 2016-12-16 17:34
http://1672.backdrop.backdrop.qa.backdropcms.org/

**Comment by olafgrabienski** [comment] 2016-12-16 19:45
The new PR works for me (Chrome Dev tools, Device toolbar). While its approach is to add `text-overflow: ellipsis;`, @serundeputy in https://github.com/backdrop/backdrop-issues/issues/2190#issuecomment-264601664 had suggested to add `overflow-wrap: break-word;`, which seems to work as well. In my opinion, both of the approaches are fine. Does anybody prefer one of them?

**Comment by jenlampton** [comment] 2016-12-16 19:46
The only problem with the ellipsis is that people can't see the rest of the text in the hero.  With break word it's ugly, but they can at least read it all.  Question: I thought ellipsis wasn't supported on all browsers?

**Comment by olafgrabienski** [comment] 2016-12-16 19:59
> I thought ellipsis wasn't supported on all browsers?

Looks actually good, see http://caniuse.com/#feat=text-overflow.

**Comment by jenlampton** [comment] 2016-12-16 20:11
IE 11 only.

**Comment by docwilmot** [comment] 2016-12-16 20:11
> The only problem with the ellipsis is that people can't see the rest of the text in the hero

Thats a problem. I think break-word is the better option.

**Comment by olafgrabienski** [comment] 2016-12-16 20:14
If you click "Show all", you see that IE supported it as of version 6. (I read somewhere, they invented it.)

**Comment by jenlampton** [comment] 2016-12-16 20:15
hah! :)

**Comment by klonos** [comment] 2016-12-17 03:26
> The only problem with the ellipsis is that people can't see the rest of the text in the hero. With break word it's ugly, but they can at least read it all.

Yeah, I think that `overflow-wrap: break-word;` would be a better option here.

**Comment by serundeputy** [comment] 2016-12-18 18:32
This is an alternative to `ellipsis` it adds `overflow-wrap: break-word;` to `header-site-name-wrapper` in core/themes/basis/css/component/header.css and to `+.block-hero .block-title,` in core/themes/basis/css/component/hero.css

PR: https://github.com/backdrop/backdrop/pull/1675/files

**Comment by olafgrabienski** [comment] 2016-12-20 10:15
On the test site of the PR I noticed, that on wide screens with for instance 1920px the image of the hero block doesn't cover the full width anymore, see screenshot below.

![screen-backdrop-hero-block-background](https://cloud.githubusercontent.com/assets/14188307/21346507/f21350c4-c6a4-11e6-837d-dfd45b80904b.png)

This might not be related to this PR, but I wanted to ask if I remember correctly, that some time ago the default image covered the full width. If yes, I'd post a separate issue.

(Note to myself: compare `.block-hero-no-image` in `core/themes/basis/css/component/hero.css` and `core/themes/basis/css/skin.css`.)

**Comment by wesruv** [comment] 2016-12-20 16:09
I had no idea `break-word` existed, sorry I had missed your suggestion earlier @olafgrabienski 

I agree that break-word is much better!

@olafgrabienski I have a ticket for that issue: https://github.com/backdrop/backdrop-issues/issues/2249

**Comment by olafgrabienski** [comment] 2016-12-20 16:18
Thanks @wesruv , I'll look at the other issue.

Btw break-word had been suggested by @serundeputy ++

**Comment by quicksketch** [comment] 2016-12-22 20:02
Excellent, I've merged the follow-up by @serundeputy at https://github.com/backdrop/backdrop/pull/1675. Thanks!

**Closed by quicksketch** 2016-12-22 20:02 UTC
Labels: pr - needs review, status - has pull request, type - bug report
