### ISSUE TITLE
Flexbox grid system negatively affecting float fallback rendering on Safari and IE

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1962] opened 2016-06-10 00:16 UTC
My use case is a three-column footer.  Below are screenshots on how it should look (and this works on FF and Chrome)

Phone (xs)
![phone](https://cloud.githubusercontent.com/assets/397895/15949282/2cb1801c-2e5b-11e6-990e-1f855099ff4c.png)

Tablet (sm)
![tablet](https://cloud.githubusercontent.com/assets/397895/15949450/76597516-2e5c-11e6-9ee4-79b9d5d19baf.png)

Desktop (md and up)
![desktop](https://cloud.githubusercontent.com/assets/397895/15949322/5d86a33e-2e5b-11e6-87b5-50594a42a0d5.png)

I've tried using the `push-` and `pull-` classes as follows:
```
<footer class="l-footer"  role="footer">
  <div class="l-footer-inner container container-fluid">
    <div class="row">
      <div class="col-md-4 col-md-push-4">...</div>
      <div class="col-sm-6 col-md-4 col-md-pull-4">...</div>
      <div class="col-sm-6 col-md-4">...</div>
    </div><!-- /.row -->
  </div><!-- /.container -->
</footer>
```
I've also tried using the flexbox ORDER classes, like this:
```
<footer class="l-footer"  role="footer">
  <div class="l-footer-inner container container-fluid">
    <div class="row">
      <div class="col-md-4">...</div>
      <div class="col-sm-6 col-md-4 col-md-first">...</div>
      <div class="col-sm-6 col-md-4 col-md-last">...</div>
    </div><!-- /.row -->
  </div><!-- /.container -->
</footer>
```

For desktop neither of the above work on IE or safari. The result is the same: 
![safari](https://cloud.githubusercontent.com/assets/397895/15949484/bc797910-2e5c-11e6-9a91-0b6864956220.png)

**Comment by jenlampton** [comment] 2016-06-10 00:24
For anyone else suffering from this problem on safari, my hack was to set `-webkit-flex-wrap` to  `nowrap` for the media query where the line of columns was wrapping unexpectedly.
```
@media all and (min-width: $screen-md-min) {
  .l-footer {
    .row {
      -webkit-flex-wrap: nowrap;
    }
  }
}
```

**Comment by klonos** [comment] 2016-06-10 20:39
Thanx for sharing the fix @jenlampton

**Comment by wesruv** [comment] 2016-06-11 21:24
This is matching up with what I was seeing in my codepen: http://codepen.io/wesruv/pen/pbJWQw?editors=1100 in the latest Safari.

I don't think there's a good way around it, this seems to be a Safari bug. I'm thinking we force Safari to use the float bootstrap CSS.

I would prefer `no-wrap` as the default. It is safest, but I think Bootstrap chose to stick with the behavior it has traditionally had and they defaulted to wrap. I'm going to see about detecting browsers that are using `-webkit-flex` and have them load the fallback CSS.

**Comment by jenlampton** [comment] 2016-06-11 21:30
Sounds like a good plan.

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by wesruv** [comment] 2016-06-11 21:31
Should mention I did find other mentions of this issue, people were able to address it in certain scenarios:
http://stackoverflow.com/questions/29986668/flex-wrap-not-working-as-expected-in-safari

But I wasn't able to get it working consistently with all of the possible variations that might occur with a Bootstrap style layout.

**Comment by wesruv** [comment] 2016-06-11 22:08
That was pretty straight forward, Safari was reporting the flex-wrap, but was reporting the wrong value, which is weird. Made the feature test stricter. Works great in Chrome, and IE, Safari is now getting the `grid-float.css` stylesheet

**Comment by jenlampton** [comment] 2016-06-12 04:22
Well, the markup with the classes `col-md-first` and `col-md-last` is still not working in Safari. Are those classes even in the float-fallback stylesheet?

**Comment by jenlampton** [comment] 2016-06-12 04:50
Is there a way to detect Safari and remove the flexbox stylesheet?

**Comment by wesruv** [comment] 2016-06-12 18:53
@jenlampton we shouldn't need to remove the flexbox stylesheet, it should be overriding everything.

... actually we might need to add `display: block` to the row and some other things. I'll take a closer look at this.

**Comment by wesruv** [comment] 2016-06-12 19:45
I hadn't even noticed those order classes, interesting. 

Those classes do not work in the float stylesheet at all, there isn't anything we can map that functionality to in a float grid :disappointed: 

Everything after line `.col-xs-first` (around line 1400 of grid-flexbox.css) is unsupportable in a float grid. I'm going to unset those in the float stylesheet so they don't cause any unexpected woe.

**Comment by wesruv** [comment] 2016-06-12 20:03
@jenlampton give the update a shot, I think this should behave much better:
https://github.com/backdrop/backdrop/pull/1442

**Comment by jenlampton** [comment] 2016-06-16 21:05
I'm still not getting the float fallback in Safari.

**Comment by jenlampton** [comment] 2016-06-16 21:14
I'm pushing this fix to my live site and will have my client test on her versions of both Safari and IE, but it looks good to me.

**Comment by jenlampton** [comment] 2016-06-21 07:03
As noticed over in https://github.com/backdrop/backdrop-issues/issues/1973, to un-do the flexbox magic, `-ms-flex-wrap: unset;` is not correct (at least, according to https://msdn.microsoft.com/en-us/library/hh673531(v=vs.85).aspx). Instead we need `-ms-flex-wrap: none;`.

**Comment by quicksketch** [comment] 2016-06-22 05:07
So the problem is that IE10 doesn't support the `unset` property at all, which is a special property that would work on all rules (http://caniuse.com/#feat=css-unset-value). So instead of just using `unset`, we need to set each different `-ms-flex*` rule back to its default property. This includes `-ms-flex-wrap` but also several other rules. I left comments on the current PR.

**Comment by quicksketch** [comment] 2016-06-30 19:58
We merged in https://github.com/backdrop/backdrop/pull/1447, which fixed IE9/10/11 but still didn't fix Safari. Let's continue this issue over in https://github.com/backdrop/backdrop-issues/issues/1985.

**Closed by quicksketch** 2016-06-30 19:58 UTC
Labels: pr - needs work, status - has pull request, type - bug report

**Comment by wesruv** [comment] 2016-07-02 23:48
Eesh, IE not supporting unset is quite annoying :/
