### ISSUE TITLE
URL for update.php generated with language prefix returns 404 error

### ISSUE THREAD

**Issue by findlabnet** [backdrop/backdrop-issues#5169] opened 2021-08-22 18:47 UTC
**Description of the bug**

1. There are two languages available on the site.
2. English is enabled, but not set as default language, only for admin use.
3. URL language detection is configured to use the "en" prefix for English and no prefix for another (default) language.

The update link from admin side is built as domain.name/**en**/core/update.php, so the result is a 404 error.

**Expected behavior**

No error.

**Additional information**

- Backdrop CMS version: 1.19.3
- Web server and its version: Apache
- Operating System and its version: GNU/Linux
- Browser(s) and their versions: any.

**Comment by indigoxela** [comment] 2021-08-23 05:52
@findlabnet I think this is a duplicate of https://github.com/backdrop/backdrop-issues/issues/5092
There's a PR ready for testing and review.

**Closed by indigoxela** 2021-08-23 05:52 UTC
Labels: type - bug report
