### ISSUE TITLE
Custom CSS positioning of search box makes it unusable (Bartik theme)

### ISSUE THREAD

**Issue by vstemen** [backdrop/backdrop-issues#3278] opened 2018-09-05 19:15 UTC
Hi.

Using the Bartik theme, if I place a search block in the <b>HEADER</b> region above the primary navigation, and float the block right, it's dead.  Clicking in the search field or on the magnifying glass does nothing and hovering over it does not change my pointer shape indicating it is any kind of link.

I float to the right in the header using

<pre>
  .contextual-links-region.block.block-search-form {
      float: right;
      }
</pre>

If I move it below the primary navigation menu or move the navigation menu out of the header region, it goes back to working.

It's also dead if I place it in the <b>TOP</b> region.  If I move it down to the <b>BOTTOM</b> region, it is alive again.

I am running Backdrop 1.10.1 and have tested on Firefox, Waterfox, and Chrome.

**Comment by jenlampton** [comment] 2018-09-20 22:30
Hi @vstemen and thanks for the feedback.

The problem is that you are floating the search block into the same part of the page that is occupied by the contextual link for the header block. In order for both to work, you will likely need to change the size or location of this contextual link with CSS, or remove it entirely. 

I've removed this contextual link myself, many times, by overriding the block template for the header (`block--system--header.tpl.php`), and removing the title_prefix and title_suffix. 

In the Backdrop core queue we don't support making custom code changes to the Bartik theme (like floating the search box to the right) so I have labeled this issue as a question. Since I have answered it I will now close this issue - but if you have further questions about how to customize themes like Bartik, feel free to ask either here, or in the forum.

**Closed by jenlampton** 2018-09-20 22:30 UTC
