### ISSUE TITLE
Entity Reference autocomplete needs a JSON delivery callback

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#6486] opened 2024-04-28 22:08 UTC
## Description of the bug

I stumbled across this while looking at something else, but it looks like the autocomplete menu items for Entity Reference need to have json delivery callbacks added, so the layout system doesn't insert a bunch of HTML at the end of the JSON result:

![image](https://github.com/backdrop/backdrop-issues/assets/871421/028bee14-f816-4e71-bf8b-267bfe5c6b7e)

**Comment by laryn** [comment] 2024-04-28 22:13
To test:

1. Add an entity reference autocomplete field labeled "Post Reference" to the "Page" content type, which allows you to add references to "Post" content type.
2. Visit `/index.php?q=entityreference/autocomplete/single/field_post_reference/node/page/NULL/first` and look at the result

**Comment by quicksketch** [comment] 2024-04-29 02:43
Thanks @laryn! In my testing I was able to reproduce the problem as you described, but it looks like this doesn't affect the functionality of Entity Reference module. When requested by an AJAX request, the content returned is proper JSON. But when visiting the autocomplete callback page directly outside of an AJAX request, you get the HTML appended to the JSON. This is still a good change; HTML shouldn't get appended to JSON ever, but at least it's not an issue affecting the everyday functionality of Entity Reference.

**Comment by quicksketch** [comment] 2024-04-29 02:44
Merged https://github.com/backdrop/backdrop/pull/4718 into 1.x and 1.27.x. Thanks @laryn!

**Closed** 2024-04-29 02:43 UTC
Labels: type - bug report, status - has pull request, pr - ready to be committed, pr - works for me
