### ISSUE TITLE
[UX] FIX RTL Formatting options in Seven

### ISSUE THREAD

**Issue by shabibalm** [backdrop/backdrop-issues#3431] opened 2018-12-15 17:34 UTC
![formatting-options-1](https://user-images.githubusercontent.com/45591694/50045744-8279bc80-00a9-11e9-9f06-14ecf25a95a2.gif)

first edit core/modules/system/css/system.theme.css

change
```
.js[dir="rtl"] fieldset.collapsed .fieldset-title {
  background-image: url(../../../misc/menu-collapsed-rtl.png);
  background-position: 98% 50%;
}
```
to
```
.js[dir="rtl"] fieldset.collapsed .fieldset-title {

    background-image: url(../../../misc/menu-collapsed-rtl.png);
    background-position: 100% 50%;
    background-repeat: no-repeat;

}
```

now edit core/themes/seven/css/style.css
add new 
```
.js[dir="rtl"] fieldset.collapsed .fieldset-legend a::before {
	right: 0;
	top: .75em;
	border: .32em solid transparent;
	border-right-color: black;
}
```
and
```
.js[dir="rtl"] fieldset.collapsible .fieldset-legend a::before {
    right: 0;
}
```
![formatting-options](https://user-images.githubusercontent.com/45591694/50045709-c1f3d900-00a8-11e9-84bd-b4a2c9e68feb.gif)

---
PR by @jenlampton: https://github.com/backdrop/backdrop/pull/2474

**Comment by jenlampton** [comment] 2019-01-13 02:10
I've created a PR for this issue at https://github.com/backdrop/backdrop/pull/2474, would someone please test and confirm?

**Comment by findlabnet** [comment] 2019-01-13 10:56
This PR should include already approved fixes from another RTL-related issues to be tested properly.

**Comment by findlabnet** [comment] 2019-01-19 09:02
Today I've tested on local environment RTL-related issues:
1) https://github.com/backdrop/backdrop-issues/issues/3423
2) https://github.com/backdrop/backdrop-issues/issues/3424
3) https://github.com/backdrop/backdrop-issues/issues/3431

4)https://github.com/backdrop/backdrop-issues/issues/2396 also is resolved via 
https://github.com/backdrop/backdrop-issues/issues/3431

Tested on core 1.12.1, not dev.

**For all of issues above I can confirm corrected state.**

We need summarised PR, not per issue.
So I can provide 3 patch files (with .txt extension requested by GitHub) to resolve all 4 issues:

[style.css.patch.txt](https://github.com/backdrop/backdrop-issues/files/2775364/style.css.patch.txt)
[system.theme.css.patch.txt](https://github.com/backdrop/backdrop-issues/files/2775366/system.theme.css.patch.txt)
[vertical-tabs.css.patch.txt](https://github.com/backdrop/backdrop-issues/files/2775367/vertical-tabs.css.patch.txt)

**Comment by klonos** [comment] 2019-01-19 09:41
@findlabnet sorry, I disagree. We should be avoiding huge PRs that address multiple issues. I have closed #2396 as a duplicate of this one here.

**Comment by findlabnet** [comment] 2019-01-19 09:50
27 changed lines in 3 css files is something huge?
OK, up to you.

**Comment by klonos** [comment] 2019-01-19 09:53
I have noticed that adding a RTL language and setting that as the default does not switch the UI to RTL. It does not seem to be a problem with the PR code (I could be wrong though). In any case, @jenlampton can you please refresh the PR sandbox?

@findlabnet you are right that the PR is not huge in this case, but I was talking in general. Besides amount of lines changed, there is also the matter of scope creep. If something goes wrong and we need to revert, we will need to revert all the fixes; whereas with smaller, isolated fixes, we can revert them individually should there be need to do that.

**Comment by findlabnet** [comment] 2019-01-19 10:05
@klonos I not about talking in general. 
Those specific changes are related and complement each other. I've add line or two myself without existing issue. 
As result we can have something more suitable for RTL backend.

**Comment by klonos** [comment] 2019-01-26 23:37
Code looks good, and it works. RTBC 👍

**Comment by quicksketch** [comment] 2019-02-08 21:29
There seem to be a number of small issues in the PR: https://github.com/backdrop/backdrop/pull/2474#pullrequestreview-201791961

**Comment by klonos** [comment] 2019-02-08 21:56
@quicksketch moving this back to RTBC (unless you have any more concerns re the code)...

Before:

<img width="731" alt="screen shot 2019-02-09 at 8 54 28 am" src="https://user-images.githubusercontent.com/2423362/52508342-72650000-2c48-11e9-95ce-f0a983cf94d0.png">

After:

<img width="720" alt="screen shot 2019-02-09 at 8 54 39 am" src="https://user-images.githubusercontent.com/2423362/52508345-7abd3b00-2c48-11e9-9471-48cf090c695c.png">

**Comment by quicksketch** [comment] 2019-02-08 22:20
Thanks everyone. Merged https://github.com/backdrop/backdrop/pull/2474 into 1.x and 1.12.x!

**Closed** 2019-02-08 22:19 UTC
Labels: pr - reviewed & tested by the community, status - has pull request, type - bug report
