### ISSUE TITLE
inline-images disappear after a while

### ISSUE THREAD

**Issue by vtad** [backdrop/backdrop-issues#1385] opened 2015-11-30 14:34 UTC
After 1 day the directory is empty. I loaded one image with the Editor.

Backdrop 1.2.2

**Comment by Graham-72** [comment] 2015-11-30 14:44
I have been having a similar  - see #1373 . In my case it has been only when the image is the sole content of a custom block. All my other images in inline-images are fine. I think we need to add this to the meta for CKEditor #1087

**Comment by quicksketch** [comment] 2016-02-24 02:44
Yeah probably a duplicate of https://github.com/backdrop/backdrop-issues/issues/1373. Thanks @Graham-72.

**Closed by quicksketch** 2016-02-24 02:44 UTC
Labels: status - duplicate
