### ISSUE TITLE
Allow webp extension for hero block image upload (if supported)

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4937] opened 2021-02-04 07:52 UTC
**Description of the bug**

This popped up [in the forum](https://forum.backdropcms.org/forum/webp). Webp support is in core since 1.17.5.
However, the list of allowed extensions in hero blocks is currently hardcoded and doesn't consider the latest change.

https://github.com/backdrop/backdrop/blob/ac819913fdb7aadcec9c7579fd33920327526792/core/modules/layout/includes/block.hero.inc#L56

**Proposed solution**

Either add webp to that hardcoded list (only if supported, of course), or provide a core function for "allowed image extensions", which modules can re-use.

**Comment by MikheevDesign** [comment] 2021-02-05 09:11
Sub

**Comment by klonos** [comment] 2021-02-05 09:17
Hey @indigoxela 👋 ...thanks for providing a PR for this, but it seems to be duplicating the code of the `system_image_supported_extensions_alter()` function.

>...or provide a core function for "allowed image extensions", which modules can re-use.

Yes, that please ^^

**Comment by indigoxela** [comment] 2021-02-05 09:30
> ...or provide a core function for "allowed image extensions", which modules can re-use.

To be honest, I looked at the existing code, but wasn't able to find an appropriate place for a generic "allowed_image_extensions_default" function. Any hint is welcome.

**Comment by klonos** [comment] 2021-02-05 09:40
Well, it would have to be a component that is always loaded (like the System module), or somewhere like `core/includes`. Some places to consider:

- `core/includes/common.inc` ("Common functions that many Backdrop modules will need to reference.")
- `core/includes/file.inc` ("API for handling file uploads and server file management.")
- `core/includes/utility.inc` (not 100% sure about this)
- `core/modules/file/file.api.php`
- `core/modules/file/file.field.inc`
- `core/modules/file/file.file.inc`

**Comment by philsward** [comment] 2021-02-05 09:47
Originally I thought "let it be customized", then I thought "it needs to be locked to image extensions, so hard code it".

Guess I'm on the fence. An admin might like to limit the image extensions for content editors, so there's that.

Has anyone complained about it being hard coded other than not allowing webp? If not, it might be easiest to add that extensionnand wait to see if anyone brings up the ability to edit them.

Editing or limiting the extensions could also live in contrib.

Food for thought.

**Comment by indigoxela** [comment] 2021-02-05 09:48
Hm. At first sight core/includes/file.inc looked promising, but if such a function gets put there, it'll require a complete rewrite of the current way hook_image_supported_extensions_alter() is implemented. That's a big API change IMO.

**Comment by indigoxela** [comment] 2021-02-05 13:56
@klonos I tried several ways to use a generic (re-usable) function, but it's not possible without breaking changes.

Explanation:

Hero blocks ship with the layout module, which has no dependency on the image module, that's why the upload field in hero blocks is a simple file field, not an image field (with image library support).

The hook used by the system module to add _webp_ to the list of supported extensions ships with the _image_ module - hook_image_supported_extensions_alter(). Using that hook would require to move it out of the image module, which would in turn require renaming it. That's an API change I wouldn't want to do just to prevent a little code duplication.

So my conclusion is: a little code duplication doesn't hurt as much as a breaking API change. :wink:

**Comment by klonos** [comment] 2021-02-05 15:51
> So my conclusion is: a little code duplication doesn't hurt as much as a breaking API change. 😉

Agreed. I'll review/test this soon as I get a chance. Thanks @indigoxela 👍

**Comment by indigoxela** [comment] 2021-02-20 11:59
@MikheevDesign are you willing to test? It should be easy, as every pull request ships with a sandbox:

- Website: https://pr3527-qsuae6jlw3fqrgbsohnisgcntdf5xxil.tugboat.qa/
- Username: admin
- Password: cd0c66198907

Just log in, do your testing, and report your findings here in this thread. We really appreciate testing of all kinds. :smiley:

**Comment by laryn** [comment] 2021-03-12 18:49
Can we expand this issue to include `webp` extension on new image fields by default?

**Comment by indigoxela** [comment] 2021-03-13 10:40
> Can we expand this issue to include webp extension on new image fields by default?

I'm not sure if this is the right issue for that. The hero image is a pretty special thing, not related to "normal" image fields created via UI.

**Comment by MikheevDesign** [comment] 2021-03-14 07:05
> @MikheevDesign are you willing to test? It should be easy, as every pull request ships with a sandbox:
> 
> * Website: https://pr3527-qsuae6jlw3fqrgbsohnisgcntdf5xxil.tugboat.qa/
> * Username: admin
> * Password: cd0c66198907
> 
> Just log in, do your testing, and report your findings here in this thread. We really appreciate testing of all kinds.

Sorry, didn't understand the purpose of testing, because webp is still not available for hero

**Comment by indigoxela** [comment] 2021-03-14 07:13
@MikheevDesign sorry, that was my fault, I forgot that the php/gd version in sandboxes do not support webp.

You'd actually have to test locally. Make sure that your gd version supports webp on /admin/reports/status/php. If so, then webp should be available out of the box in hero blocks.

Let us know, if you need any guidance regarding local setup for testing.

**Comment by MikheevDesign** [comment] 2021-03-14 07:23
> @MikheevDesign извините, это моя вина, я забыл, что версия php / gd в песочницах не поддерживает webp.
> 
> На самом деле вам придется тестировать локально. Убедитесь, что ваша версия gd поддерживает webp в / admin / reports / status / php. Если это так, то webp должен быть доступен прямо из коробки в блоках героев.
> 
> Сообщите нам, если вам понадобятся какие-либо указания относительно локальной настройки для тестирования.

Thanks for the quick response, I will soon solve the problem with hosting and test it on a working host and write about my results here

**Comment by laryn** [comment] 2021-03-14 13:33
> > Can we expand this issue to include webp extension on new image fields by default?
> 
> I'm not sure if this is the right issue for that. The hero image is a pretty special thing, not related to "normal" image fields created via UI.

I guess I was referring to the conversation about taking this one level higher with a generic "allowed_image_extensions_default" function -- which would also be useful in the case I raised. In any case, I've opened https://github.com/backdrop/backdrop-issues/issues/4998

**Comment by yorkshire-pudding** [comment] 2023-01-18 11:21
@indigoxela - thank you for this.  I've tested, reviewed the code and updated labels.  Hopefully as this is a task, we can get it in the next bug fix release.

**Comment by kiamlaluno** [comment] 2023-01-18 14:17
This happens also for user pictures: Despite the GD library used by the server handles WebP images, I cannot use that image type because the allowed extensions do not include .webp.

**Comment by yorkshire-pudding** [comment] 2023-01-18 14:27
@kiamlaluno - probably worth a separate issue but linked to this; it might use a similar approach but will be in a different location.

**Comment by kiamlaluno** [comment] 2023-01-18 14:34
@yorkshire-pudding I have already created it. I was just saying that hard-coded extensions are used on different form elements.

**Comment by yorkshire-pudding** [comment] 2023-01-18 14:41
I see that now - https://github.com/backdrop/backdrop-issues/issues/5859

**Comment by kiamlaluno** [comment] 2023-01-18 17:29
I forgot about that issue. See also #5917.

**Comment by klonos** [comment] 2023-01-18 22:49
@yorkshire-pudding the PR introduces yet another place where we are hardcoding extensions, so we need to do better than that.

@indigoxela I was thinking something like a generic `backdrop_allowed_image_extensions()` function, which has an array of extensions, and invokes a hook to allow contrib/custom modules to alter the extensions in that array. The check for support of webp should live in that function or in a hook in the image module I guess. Then use that function in `BlockHero::form()`.

Based on the above + on the fact that the PR is rather old now and needs a rebase, setting this to NW.

**Comment by indigoxela** [comment] 2023-01-19 07:33
> I was thinking something like a generic backdrop_allowed_image_extensions()

Agreed, it's about time to find a more generic approach and replace these hardcoded checks. :+1:

**Comment by jenlampton** [comment] 2023-01-19 22:03
Can we expand this issue (and update the PR) to include the new function `backdrop_allowed_image_extensions()`? 

I don't like explicitly adding webp in this one instance, and only when the image toolkit is gd. People could be using imagemagick with webP support, and this solution wouldn't work for them. 

If we add the new function `backdrop_allowed_image_extensions()` function, we should make sure the resulting list of extensions is alterable, so that the imagemagick module can add webP if/when it is supported.

**Comment by jenlampton** [comment] 2023-01-19 22:20
I'm expanding this issue to cover all image form elements, since I think it is possible to add an image type upload validator directly to the form API element, so it gets called for every image upload.

**Comment by jenlampton** [comment] 2023-01-19 22:36
I have created https://github.com/backdrop/backdrop-issues/issues/5946 - it might make more sense to be adding `backdrop_allowed_image_extensions()` over there.

**Comment by yorkshire-pudding** [comment] 2023-01-20 08:21
That makes sense, then this ticket can hook into the new global elements.

**Comment by herbdool** [comment] 2023-02-22 20:34
I disagree. This can't be tied to a new form element. A generic function is needed that can be loaded without the image module because it has to work for file elements as well. We can't switch all of them to use a new form element, at least not in 1.x. And there's contrib too. I think we want to allow webp or other extensions even if using the file element.

I think we'll need to somehow make another `system_image_supported_extensions_alter` and put it in file.inc. Maybe that old hook can be a "wrapper" for the new one?

**Comment by herbdool** [comment] 2023-02-22 20:44
Thinking more about it: we can just keep that hook as it is, and have it's invocation call the new function suggested `backdrop_supported_image_extensions()`. Though I changed it to "supported" and not "allowed" since what's allowed can still be restricted per field. Webp might be supported but maybe you don't want it allowed for a field.

**Comment by herbdool** [comment] 2023-02-26 16:15
I've got a PR https://github.com/backdrop/backdrop/pull/4366 that could use some feedback. It might not be the best approach but I think it's getting there. It reduces duplication, is backwards-compatible and doesn't require the image module to be enabled.

**Comment by kiamlaluno** [comment] 2023-02-26 16:36
Image toolkits return the images they support with `image_<toolkit>_get_info()`, which is not invoked in the PR.

**Comment by kiamlaluno** [comment] 2023-02-27 09:34
To expand my previous comment: The image toolkit is the Backdrop part that should load and save the images uploaded in form elements. The fact WEBP images are not allowed in some form elements is not caused by the image toolkit that is rejecting the image, but it is caused by a validation handler that checks the file extension, which is not even able to handle images. In fact, it allows extensions that are not usually used for images, like _txt_, _doc_, _xls_, _pdf_, or _ppt_ (just to list some of those extensions).

What is really causing the "issue" is that there is not an *image* form element that can be used to upload an image; we are using a form element that accept any file, as @jenlampton said in a previous comment.

**Comment by herbdool** [comment] 2023-02-27 15:10
@kiamlaluno `image_gd_get_info()` is used and adapted in this PR, and so is the validation handler. We can't use it directly to provide a list of supported extensions because it requires an image object and we need a way to not just validate but also display what extensions are supported. That's why I took the approach in my PR.

Creating an image form element is a worthy effort, but it's not going to be backwards-compatible. This should work for contrib/custom modules as well. And will also need to support Webform file form elements, which rely on core's file form element.

So... I don't think it's perfect but I think this is the direction this needs to go.

**Comment by kiamlaluno** [comment] 2023-02-27 15:48
Would the code still work if the site enables another image toolkit?  
The code is hard-coding the allowed extensions, but that code is simply moved in `image_get_supported_extensions()`. To work with every image toolkit, it should invoke `image_<toolkit>_get_info()`.

**Comment by herbdool** [comment] 2023-02-27 16:38
A variation of this would be to create a new function like `image_<toolkit>_supported_extensions()` and have the hook implementation call that. But that would also require yet another new function to call that since the current functions like that use `image_toolkit_invoke('some_action', $image)` and we don't want the image. So using the hook was the easiest at this point. But I'm happy to adapt the PR to whatever makes it clearer (and still backwards-compatible).

**Comment by herbdool** [comment] 2023-02-27 18:35
Thank you too @kiamlaluno. I've changed `image_get_supported_extensions` so it now calls `image_TOOLKIT_supported_extensions`. So now it's clearer that a toolkit needs to implement that. And I simplified my adaptation of `image_gd_get_info` so it calls `image_type_to_extension()` but then ensures that the extension is one of the (currently) supported extensions for Backdrop's use of GD.

**Comment by herbdool** [comment] 2023-02-28 03:00
@kiamlaluno it's ready for another test/review. Tests are passing. There is one test under PHP 5.6 that is passing for me locally (with PHP 5.6) but not here. Perhaps there's something weird about the PHP build here, but would be good to have a second person run the tests locally to compare.

**Comment by kiamlaluno** [comment] 2023-03-08 13:42
The failing test is [`ImageFieldValidateTestCase::testTypeSupport()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21image%21tests%21image.test/function/ImageFieldValidateTestCase%3A%3AtestTypeSupport/1). It seems it is hard-coding the allowed image type and expecting only two image types (jpeg and webp). Since it creates a field that allows just those two image types, its failure seems correct.

**Comment by kiamlaluno** [comment] 2023-04-04 15:50
Should not the error message lists all the extensions allowed for that file, independently from which image extensions are allowed from the image toolkit?

**Comment by herbdool** [comment] 2023-04-10 20:27
@kiamlaluno thanks for letting me know. I added that small change to this PR since it would be good to see if all tests pass now. If your PR gets merged first I can update this PR again.

By the way, I also added `$this->assertFalse($webp_supported, 'WebP image type is not supported for this PHP build.');` and `$this->assertTrue($webp_supported, 'WebP image type is supported for this PHP build.');` so we can tell for sure if our tests were set up properly.

**Comment by herbdool** [comment] 2023-04-10 22:56
Finally, all tests pass.

**Comment by stpaultim** [comment] 2023-04-11 06:06
Seems like the next step is for someone to test the PR and if it's working, to mark "Works for Me."

**Comment by herbdool** [comment] 2023-04-11 11:36
I'm not sure if our build of Tugboat supports webp. I can't get it to work there. I'll test my own stuff locally to compare.

**Comment by indigoxela** [comment] 2023-04-11 11:41
> I'm not sure if our build of Tugboat supports webp

It doesn't (oddly compiled version of GD). IIRC that was one thing we struggled with, when introducing webp. The GitHub runners do, though.

The only thing we can reliably test with the Tugboat builds is, that the messages are correct when webp isn't supported. :grin:

**Comment by herbdool** [comment] 2023-04-11 13:30
> It doesn't (oddly compiled version of GD).

Thanks @indigoxela, that helps. I thought I had done something wrong.

I tested again on my local and it seems to be working well enough. It should work for existing sites with hero blocks and with CKEditor. Any custom fields will need to be edited and have webp added to the list of supported extensions. We want it that way since site builders may have reasons for restricting it.

So you can test these scenarios:

- hero block image
- CKEditor image upload
- existing image fields (should not have it unless added manually)
- new image fields (should have it when created)

**Comment by indigoxela** [comment] 2023-04-11 14:36
> Now I'm wondering if we should put a hook in this PR to support image types like SVG

Oh, the SVG discussion again? :smirk: That seems like a topic for a new issue.

I'm happy with the current approach - streamline image extension handling and (finally) allow webp for hero images and from within the editor. :grinning:

Contrib modules can also benefit from function `image_gd_supported_extensions()`. BTW do we need an `@since` for that function? Not sure.

**Comment by herbdool** [comment] 2023-04-11 14:40
We might need `@since`. Once we have a good sense which release it'll merged into then we can add that.

Yes, we can leave SVG for another issue. We already have an alter hook in `image_field_widget_form()` that can be used for that. And could an alter hook in `image_get_supported_extensions()` later. So I agree it doesn't need to be done now.

**Comment by indigoxela** [comment] 2023-04-11 14:55
> do you feel comfortable doing the code review too?

I took a look and left a comment. But another pair of eyes would be great, too.

**Comment by kiamlaluno** [comment] 2023-04-11 15:55
As a new image toolkit "hook" is implemented, that should be documented too. I would leave that for a follow-up issue, though.

**Comment by klonos** [comment] 2023-04-12 07:02
Code looks really good to me too @herbdool 👍🏼 ...thanks for all the cleanup/consistency/improvements 🙏🏼 

I left a suggestion in a comment in the PR - otherwise this is RTBC.

**Comment by quicksketch** [comment] 2023-05-01 00:08
I gave this a code review and it looks fantastic. I love the removal of `system_image_supported_extensions_alter()`, providing a generic supported formats function, and then moving WebP support to the GD toolkit. Very nice clean-up of our API. And it accomplishes the originally stated goal beautifully. I added a `@since 1.25.0` line to the docblock of the new `image_get_supported_extensions()`.

Very nice work @herbdool! Big thanks to @indigoxela and @klonos for the code reviews. And thanks @kiamlaluno, @jenlampton, @yorkshire-pudding, and @MikheevDesign for feedback and testing!

**Comment by quicksketch** [comment] 2023-05-01 00:17
Merged https://github.com/backdrop/backdrop/pull/4366 into 1.x for 1.25.0. Great work everyone!

**Closed** 2023-05-01 00:16 UTC
Labels: type - task, status - has pull request, pr - ready to be committed, needs - documentation, pr - works for me

**Comment by quicksketch** [comment] 2023-05-01 00:31
Oh, I missed that this adds a new toolkit callback... I think we might want a fallback for backwards compatibility so that the ImageMagick module continues working without requiring changes (though they'll want to include the new callback to also support webp). I'll make follow-up PR.

**Comment by quicksketch** [comment] 2023-05-01 00:50
Change record published here: https://docs.backdropcms.org/change-records/image-toolkits-should-provide-image_toolkit_supported_extensions-callback

I filed a follow-up at https://github.com/backdrop/backdrop-issues/issues/6092
