### ISSUE TITLE
Fixed: Wrong display of some float values in Views.

### ISSUE THREAD

**Issue by AlexHoebart-ICPDR** [backdrop/backdrop-issues#6412] opened 2024-03-01 11:00 UTC
## Description of the bug

The views_handler_field_math uses code copied from views_handler_field_numeric (this is even mentioned in a comment)
That code snippet has a bug due to limitations of PHP and float values: it produces wrong results for certain values.

## Steps To Reproduce

Create any type of View with a display format using Fields.
Add a Global:Math Expression field and enter a decimal value in the Expression input field, e.g. 67.93 (the behaviour is only visible with certain values such as this example).
Don't check the Round checkbox.
Preview or display the View.
Instead of 67.93, the output will be 67.93000000000001

There is another bug:
Use any number between 0 and -1, e.g. -0.5.
Instead of -0.5, the output will be 0.5.

## Additional information

This bug was partly fixed in Drupal7 for numeric fields in issue [#662692](https://www.drupal.org/project/views/issues/662692) only, but not applied to the same code used for Math expressions.
There was another fix in Drupal8 for numeric fields in issue [#1952926](https://www.drupal.org/project/drupal/issues/1952926#comment-12082454) which fixes both issues described above.

I'm aiming at providing a port of the bugfix as in Drupal8 for both numeric and math fields.

**Comment by AlexHoebart-ICPDR** [comment] 2024-03-01 12:01
PR is ready to be reviewed/tested - some automatic tests fail, but I don't think they are related

I should have mentioned that the bug is not easy to see for numeric fields, as the Number Field does not use the views_handler_field_numeric. That handler is only used with some integer values in the core modules. However, I have ported a module using that handler directly and then the bug is surfacing. 

That's why I added the examples based on the Math field which can be easily reproduced - but the bug is in both handlers.

**Comment by AlexHoebart-ICPDR** [comment] 2024-03-01 15:24
I have ported views_database_connector to Backdrop (and maybe will publish it later) and use it to display measurement data from another database, that's why I noticed the issue.

**Comment by indigoxela** [comment] 2024-03-06 08:34
@AlexHoebart-ICPDR many thanks for this cross-port. :pray: 

I can confirm the described problem and can also confirm, that the PR fixes it. :+1: 

A tiny formal thing (trailing white space), and the PR's good to go.

One thing, maybe out of scope / asked too much: the D commit contained a functional test and I wonder, if we should port that over, too. So we don't run into the same problem again. I'm aware, that our testing framework really differs, so it might be quite some effort to create a similar test based on Simpletest.

**Comment by AlexHoebart-ICPDR** [comment] 2024-03-06 20:45
> A tiny formal thing (trailing white space), and the PR's good to go.

Thanks, I fixed it.

> One thing, maybe out of scope / asked too much: the D commit contained a functional test and I wonder, if we should port that over, too. So we don't run into the same problem again. I'm aware, that our testing framework really differs, so it might be quite some effort to create a similar test based on Simpletest.

I don't know how to do that, unfortunately. I'm fine with manual tests.

**Comment by indigoxela** [comment] 2024-03-07 05:42
@AlexHoebart-ICPDR many thanks for the white space fix, this PR's now ready to merge.

FTR, Github acts a bit weird currently, it's not able to display errors (not caused by anything on our side, it's their infra). The full output's still available via "raw log". So I could confirm, that the failing tests are our usual false negatives (we have an issue for that, unrelated here).

Re functional tests. No problem, I suspected, that this is asked too much, anyway. I can add functional tests in a follow-up.

**Comment by indigoxela** [comment] 2024-03-07 09:44
I've added a second PR with the functional test only, so the tests fail as expected. They only pass if the fix of the first PR is applied.

GHA still acts (fails to display error details via nodejs). To see the actual output, use "View raw logs" from the dropdown on the top right (gear icon) of the Simpletest batch run.

Failing related test output (as expected):
```
Expected rendered output to be -1234.01, got -1234.0099999999999909
Expected rendered output to be -0.5, got 0.5
Expected rendered output to be 17.0029, got 17.0029000000000003
Expected rendered output to be 67.93, got 67.93000000000001
```

As I now contributed to the PR, someone else has to mark this as RTBC (and set the milestone).
@bugfolder you showed some interest in this topic, are you willing to do an additional review?

**Comment by bugfolder** [comment] 2024-03-11 22:46
Tested patch with a view containing Global:math expressions.

Before:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/896fa322-d544-4f53-8335-4832fd55d99f)

After:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/0a2e58b1-63d5-42fd-8938-a3b2aa405050)

**Comment by bugfolder** [comment] 2024-03-11 22:52
Applied both PRs and ran Views Handlers Field:Math and Views Handlers Field:Numeric tests in Simpletest. All tests passed.

Code reviewed: LGTM.

RTBC.

**Comment by quicksketch** [comment] 2024-03-13 18:29
Thanks folks! @indigoxela I merged your PR at https://github.com/backdrop/backdrop/pull/4665 into @AlexHoebart-ICPDR's PR at https://github.com/backdrop/backdrop/pull/4663, so all the changes can be in a single PR. If that still passes tests then we'll be ready to merge.

**Closed** 2024-03-13 18:41 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2024-03-13 18:42
Thanks @AlexHoebart-ICPDR, @indigoxela, and @bugfolder! The PR looks great with the added tests. I merged https://github.com/backdrop/backdrop/pull/4663 into 1.x and 1.27.x. Thanks to all of you for collaborating on this!
