### ISSUE TITLE
Fixed: Undefined property `originalLanguageDefault` in simpletest.

### ISSUE THREAD

**Issue by bradbulger** [backdrop/backdrop-issues#4679] opened 2020-10-02 21:56 UTC
In backdrop_web_test_case_cache.php, the tearDown() function of BackdropWebTestCaseCache refers to an originalLanguageDefault property. That property is not defined.

It's a little murky. It was originally added to BackdropWebTestCase by the fix to #1835. Then in issue #2776, a fix to the Drupal issue [1823504](https://www.drupal.org/project/drupal/issues/1823504) was applied, and that ended up removing the property. I think maybe only because it had moved? Or something else inadvertent.

This matters because I wonder if the proper fix is to restore some of the changes from #1835.

You can see this by running SimpleTestBrokenSetUp ("Broken SimpleTest method") and displaying errors and/or checking the error log.

**How to reproduce**

1. Enable Simpletest module
2. Make sure, test caching is on (admin/config/development/testing/settings)
3. If you ran tests before, clean test environment (admin/config/development/testing)
4. Run a test via UI, for instance "Language list configuration"
5. Visit admin/reports/dblog

**Actual result**

There are three dblog entries with:
`Notice: Undefined property: BackdropWebTestCaseCache::$originalLanguageDefault in BackdropWebTestCaseCache->tearDown() (line 160 of .../core/modules/simpletest/backdrop_web_test_case_cache.php).`

**Comment by indigoxela** [comment] 2020-10-06 07:36
Drupal 7 defines it as such: `$this->originalLanguageDefault = variable_get('language_default');`

In Backdrop this variable can get accessed with `config_get('system.core', 'language_default');` or `language_default()`.

**Comment by indigoxela** [comment] 2020-10-06 10:38
Here's a [PR](https://github.com/backdrop/backdrop/pull/3357) which sets originalLanguageDefault in function prepareEnvironment().

**Comment by bradbulger** [comment] 2020-10-06 15:44
Is the code that is using this doing something that makes sense now? Isn't $GLOBALS['conf'] a Drupal thing - old style variable_set()?

The original code was checking the config

`     $this->originalLanguageDefault = config_get('system.core', 'language_default');`

and then restoring that value if there was one, but it wasn't restoring it to the config. I don't know if test code like this

`foreach ($languages as $key => $value) {
  // Set the default language.
  // Get the system config.
      $core_config = config('system.core');
      $core_config->set('language_default', $key);
  $core_config->save();`

is affecting the actual config files of the installation, and so needs a config_set() to put it back? (Sorry, I can't figure out how to make that code look like a block.)

**Comment by indigoxela** [comment] 2020-10-07 06:34
> Is the code that is using this doing something that makes sense now?

Yes, I think so. The purpose of originalLanguageDefault is _not_ to fiddle with the actual config files, but to restore the global in $conf back to the original in function tearDown, in case it has been changed. (Backdrop and Drupal 7 globals are mostly the same.)

[language_default()](https://api.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/language_default/1) does the same as config_get('system.core', 'language_default'), but with a static cache and a fallback.

**Comment by bradbulger** [comment] 2020-10-07 15:33
That's what I'm saying, though. For one, there is no global $conf. That's Drupal variables. For another, the original code that created this line was only setting it if it had found a value in the system.core config. It returned it to the status quo.

Are the config changes made in tests affecting the actual config of the site? Or only the copies? If it's not changing the real system.core config, then isn't the simplest thing to remove this altogether?

**Comment by indigoxela** [comment] 2020-10-08 06:31
>  there is no global $conf

There it is: https://api.backdropcms.org/api/backdrop/core%21authorize.php/global/conf/1

See also: https://github.com/backdrop/backdrop/blob/5aba056ecbcaa20db3292fc70c0556fa1a178044/core/includes/bootstrap.inc#L569

See also: https://github.com/backdrop/backdrop/blob/5aba056ecbcaa20db3292fc70c0556fa1a178044/core/includes/bootstrap.inc#L1106

See also: https://api.backdropcms.org/api/backdrop/core%21includes%21drupal.inc/group/drupal_compatibility/1

> If it's not changing the real system.core config...

Simpletest does not change any _real_ config files. The global $conf is available in all scopes throughout a script, which is probably the reason, why it's reset after running tests.

**Comment by bradbulger** [comment] 2020-10-08 16:14
I think it ends up "restoring" values that weren't there to begin with, and it would be fine to remove these lines altogether.

Otherwise, I think it's simpler to just add
`$this->originalLanguageDefault = config_get('system.core', 'language_default');`
to setUp().

**Comment by klonos** [comment] 2021-09-06 19:26
@indigoxela if the simple one-liner fixes this problem here, then I would like us to get it in, to get another thing out of the way. Can you please rebase your PR?

**Comment by klonos** [comment] 2021-09-06 19:56
I have tried the STR from the issue summary:
- in a recent Backdrop demo sandbox -> reproduces the 3 notices in the log 👍🏼 
- in the PR sandbox -> throws 2 same exceptions: `EXCEPTION: copy(files/simpletest/579166/config_active/.htaccess) [function.copy]: failed to open stream: Permission denied` (will test again, once the PR has been rebased)
- on a recently-cloned 1.x + the PR changes merged in -> fixes the issue 👍🏼 (no exceptions - no notices in the log)

I'm tentatively marking this as WFM, pending rebase in order to mark it RTBC.

**Comment by indigoxela** [comment] 2021-09-07 06:24
> I'm tentatively marking this as WFM, pending rebase in order to mark it RTBC.

Rebased, and test are ... "passing".

**Comment by herbdool** [comment] 2021-09-07 12:41
I've read all the comments and I didn't feel there was consensus on the fix. I'm not clear on any implications. It looks like an easy fix but it's confusing how the different things were added and removed around this.

@bradbulger and @indigoxela do you think you'd come to agreement on the fix here?

**Comment by indigoxela** [comment] 2021-09-07 12:59
@herbdool regarding the previous comments here - yes, we came to agreement to open a new issue for the wider change and discussions regarding how [checkPath is supposed to work](https://github.com/backdrop/backdrop-issues/issues/5190) - to not further block this important bugfix.

**Comment by herbdool** [comment] 2021-09-07 13:02
@indigoxela sorry I'm still a bit confused. This issue is about originalLanguageDefault but you linked to checkPath.

**Comment by indigoxela** [comment] 2021-09-07 13:09
> sorry I'm still a bit confused...

You are absolutely right, another example of "read before you post" - sorry about the confusion. (Same person, different issue.)

If you have concerns, you maybe better ask @bradbulger - I just provided the bugfix. It they think, this requires further discussion, then maybe I'll just close my PR to make space for alternate approaches.

**Comment by herbdool** [comment] 2021-09-07 13:13
@indigoxela please keep your PR open. It might be the best one here but it wasn't clear to me based on your discussion above. I investigated a bit @bradbulger's concerns too but nothing conclusive.

**Comment by klonos** [comment] 2021-09-07 17:05
I've retested the PR sandbox after the rebase, and everything worked flawlessly this time. RTBC from me 👍🏼 

I understand that @herbdool still has concerns, and expecting @bradbulger to chime in, so adding the "needs more feedback" label too.

**Comment by herbdool** [comment] 2021-09-08 05:40
@indigoxela would using `language_default()` be a problem since it uses a cached version? I noticed other variables are just calling the config files directly. I haven't been able to look closely enough yet myself.

**Comment by indigoxela** [comment] 2021-09-08 05:50
FWIW, this is the D7 code. D7 doesn't have that bug.

https://git.drupalcode.org/project/drupal/-/blob/7.x/modules/simpletest/drupal_web_test_case.php#L1419

> would using language_default() be a problem 

The PR is using language_default() in function prepareEnvironment(). If anyone sees a problem with my approach - please clarify.

**Comment by indigoxela** [comment] 2021-09-10 07:21
Does this issue still need "more feedback"?

@herbdool I really appreciate your thorough consideration of opinions. But the last comment of @bradbulger was almost a year ago, which could mean that they lost interest in this issue, anyway.

How long are we supposed to wait for feedback?
Especially as it's a simple one-liner fix that has equivalent code in D7.

**Comment by herbdool** [comment] 2021-09-10 20:54
@indigoxela if @bradbulger doesn't respond soon, I'll take a look. Hopefully on the weekend. I haven't been at my own computer for a couple weeks.

In my reading above and seeing that it involved caching somehow, I couldn't understand if language_default() was a better option than `$this->originalLanguageDefault = config_get('system.core', 'language_default');` (as @bradbulger suggested). Or would the caching not be a problem here?

**Comment by herbdool** [comment] 2021-09-13 03:03
@klonos I don't think we can have both "needs feedback" and "ready to be committed" at the same time. It wasn't ready because I had questions about the approach.

I've finally had time to look a bit closer. So I realized that `language_default()` is just using a static variable and not the regular cache (I misread a comment above). And it's not the same as in D7. So maybe using it won't have any side effects in the tests.

**Comment by bradbulger** [comment] 2021-09-14 15:16
sorry i have been away. i haven't dug into this in a while, the PR seems fine.

**Comment by quicksketch** [comment] 2021-09-15 20:26
I think we should revisit the `BackdropWebTestCaseCache::tearDown()` method. Like @bradbulger points out, we're not using the global `$conf` variable for most things in Backdrop. We're certainly not using it for `file_public_path` and `language_default`.

If we don't have a need for `originalLanguageDefault` (we haven't been using it so far), I think we should just leave it out.

I'm pretty sure restoring the files directory and the language default is already handled in `refreshVariables()`, when `backdrop_static_reset('config')` is called.

**Comment by herbdool** [comment] 2021-11-16 18:22
I've got a PR removing `originalLanguageDefault`. It sounds like we can safely remove `file_public_path` too so I added that to the PR.

**Comment by indigoxela** [comment] 2021-11-17 07:12
> It sounds like we can safely remove file_public_path

Strange, there's a test failure in CommentApprovalTest with php 7.4:
```
filemtime(): stat failed for modules/ddd_installer_test/ddd_installer_test.info
```
Could this be related to that change?

**Comment by indigoxela** [comment] 2021-11-17 11:06
I did a quick local check, running only that test on php 7.4. It passes locally, so probably the failure is unrelated.

@herbdool can you please close and reopen the PR to verify (or, if you have permission, just re-run the workflow)?

That test used to be one of the [random failures](https://github.com/backdrop/backdrop-issues/issues/2248), but got fixed years ago.

**Comment by herbdool** [comment] 2021-11-17 11:55
@indigoxela thanks, I didn't know I had permissions to rerun the tests. I've just done so.

**Comment by herbdool** [comment] 2021-11-17 16:17
@indigoxela looks like it was just a random failure

**Comment by bugfolder** [comment] 2021-12-24 22:29
Tested per original instructions: worked to suppress the dblog entries. WFM.

Code reviewed. Looks good.

RTBC.

**Closed** 2022-01-04 23:30 UTC
Labels: status - fixed

**Comment by quicksketch** [comment] 2022-01-04 23:32
Thanks! I merged https://github.com/backdrop/backdrop/pull/3825 into 1.x and 1.20.x.

Props to @herbdool, @bradbulger, @indigoxela, @klonos, and @bugfolder for their work on this issue!
