### ISSUE TITLE
Add a helper function to load a single entity

### ISSUE THREAD

**Issue by rszrama** [backdrop/backdrop-issues#968] opened 2015-06-05 03:27 UTC
entity_load() is fine and dandy as a multiple loader, though I prefer the name entity_load_multiple(), and in D7 we just got in the habit of making single loader functions for all of the entity types we defined (e.g. commerce_order_load(), commerce_product_load(), etc.). Since changing entity_load() to be a single loader is a breaking API change, I believe an additional entity_load_single() function should be added to make it easier to load a single entity and avoid the need for every module defining new entity types to create loaders.

**Comment by rszrama** [comment] 2015-06-05 03:34
Note that entity_load_unchanged() already only loads a single entity from the database. This really leads me to believe entity_load() should be turned into a single loader and the current entity_load() should become entity_load_multiple(). What's the semantic versioning requirement for such a change to happen? Would it be possible in a 1.2.0 release or is that significantly breaking to require a 2.0.0?

**Comment by quicksketch** [comment] 2015-06-05 03:44
Wow Hi @rszrama! A pleasure to see you in our nick of the woods.

> D7 we just got in the habit of making single loader functions for all of the entity types we defined (e.g. commerce_order_load(), commerce_product_load(), etc.).

+1000

Here's our current function for reference: https://api.backdropcms.org/api/backdrop/core!modules!entity!entity.module/function/entity_load/1

Couldn't we add entity_load_multiple() (to be consistent with other multi-loaders) that just called entity_load()? Or do the opposite and move all code from entity_load() to entity_load_multiple() and have entity_load() check if the second argument is an array, if not then assume a single loader?

**Comment by rszrama** [comment] 2015-06-05 03:47
Yeah, I think I'd just move the entity_load() code to entity_load_multiple(), and I didn't think about the idea of preserving backwards compatibility and just checking the second argument for a single integer vs. an array. This whole idea of thinking about backwards compatibility will take some getting used to... ; )

I'm happy to revise my pull request to do that! Been playing a little after hours here, figure I can offer up a few pull requests as a wedding present. : D

**Comment by quicksketch** [comment] 2015-06-05 03:49
Maybe something like this? It's possible there's a cleaner yet solution here.

```php
function entity_load($entity_type, $entity_id) {
  if (!is_array($entity_id)) {
    return entity_load_multiple($entity_type, array($entity_id));
  }
  // Backwards compatibility with entity_load() as a multiple loader.
  else {
    call_user_func_array('entity_load_multiple', func_get_args());
  }
}
```

**Comment by quicksketch** [comment] 2015-06-05 03:51
Note the downside of this approach is that older versions of Backdrop would throw an error if a newer module assumed this single-loader functionality. But the module could just specify that it requires a newer version of Backdrop core and that wouldn't be unusual. Not dissimilar to when the locking mechanism was added in D7 and contrib started using it a short while later.

**Comment by rszrama** [comment] 2015-06-05 03:51
Yeah, something like that, though we'd have to accommodate that funky FALSE option for the $ids parameter in the current entity_load() (man, that's a monstrosity... really needs an entity_load_all()). And how defensive are you trying to be here? As you work on other bits of core, are you doing things like checking to ensure a non-array, non-FALSE value for this parameter is an integer?

**Comment by quicksketch** [comment] 2015-06-05 03:54
Groan. I totally forgot about the FALSE value for that parameter. Why in the world would you want to load *all* entities (or at least have a shortcut to do so)? This should still be possible to wrap, just another if statement.

> are you doing things like checking to ensure a non-array, non-FALSE value for this parameter is an integer?

No, we haven't gone so far as to ensure integer only values for the entity ID at this point. I think that means that we should check for the types that are explicit: FALSE and array(), then assume all other types are a single loader (int, float, string).

**Comment by rszrama** [comment] 2015-06-05 03:55
Cool, I'll get on it.

Also, I may have missed how to cross-reference pull requests and issues (as with #969; think I expected it to somehow read my mind). Lemme know if I'm screwing something up here. : )

**Comment by quicksketch** [comment] 2015-06-05 03:57
Because our PRs are in a separate repository (a mess I know), just paste in the full URL to the issue when cross-referencing. GitHub will shorten it down on display and cross-link for us.

**Comment by jenlampton** [comment] 2015-06-05 04:42
:+1:

**Comment by rszrama** [comment] 2015-06-05 14:40
Burn! Test fails, will check 'em out later.

**Comment by quicksketch** [comment] 2015-06-06 17:51
Close! It looks like the current failure is caused by attempting to load a non-existent entity ID, since we're trying to call `reset()` on a FALSE returned value.

**Comment by rszrama** [comment] 2015-06-06 18:00
Ahh, poo. I thought I tested that, but it must've just been an empty array. : P

**Comment by rszrama** [comment] 2015-06-10 14:07
Ok, as best as I can tell, the issue wasn't actually the reset() call, as the load function returns an empty array if no matching entities are found. What really got me here was the fact that the comments for the $id function lied by omission. :stuck_out_tongue_closed_eyes: 

It isn't _just_ FALSE that can be passed as a value for $id, it's also NULL when paired with a $conditions array. These failing tests are calling entity_load_multiple() with a NULL $id and some condition that loads a subset of all entities of the given type.

I incorrectly diagnosed this in an amended commit I just made, but I'm amending it once again now.

**Comment by rszrama** [comment] 2015-06-10 14:30
Ok, got the updated patch in. Honestly, it feels dirty to be referencing and accommodating a parameter that's been marked as deprecated, but to follow this all the way down the rabbit hole, you'd need to update all the related *_load_multiple() functions to stop using it. Really a separate issue imo.

(This also raises the strategy question... what does a deprecated parameter actually mean? In Commerce we deprecate a function or parameter and remove it two minor versions later. Is there any meaning here beyond, "You really shouldn't be using this, but it's hangin' around for a while anyways."?)

**Comment by quicksketch** [comment] 2015-06-12 22:24
Thanks @rszrama for your work on this! Increasing the consistency of our APIs is a very worthy goal. I know personally I've run into this exact issue a few times myself. It's great to see it fixed. Merged into 1.x and this will be in the 1.2.0 release.

**Closed by quicksketch** 2015-06-12 22:24 UTC

**Comment by rszrama** [comment] 2015-06-13 03:26
Gangsta. I've been playing around with entity definitions in Backdrop for toots and giggles. I'll hope to keep it up and address some of the other issues I've been finding / referencing in these issues. : )

**Comment by quicksketch** [comment] 2015-06-13 05:22
Yay, thanks @rszrama! :grinning:
