### ISSUE TITLE
[UX] Modules that do not need to be uninstalled are appearing on the Uninstall page after being disabled

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3915] opened 2019-07-06 01:33 UTC
**Description of the bug**
We recently noticed that all modules -- regardless of whether they need to be uninstalled or not -- are appearing on the uninstall page after being disabled. 

**Steps To Reproduce**
To reproduce the behavior:
1. Go to 'admin/modules'
2. Check the box for 'syslog'
3. Save the modules page.
4. UnCheck the box for 'syslog'
5. Save the modules page again.
6. Go to `admin/modules/uninstall`

**Actual behavior**
Syslog appears on `admin/modules/uninstall`

**Expected behavior**
Syslog should not appear on `admin/modules/uninstall`

**Additional information**
This was first brought to our attention in https://github.com/backdrop/backdrop-issues/issues/3911. 

There was some discussion over there about adding this behavior as a "feature" to train people that all modules need to be uninstalled...  but there is resistance to that addition as it would be a UX regression from Drupal 7.

Unfortunately, it looks like we already have the regression. This issue is an attempt to rectify that.

**Comment by jenlampton** [comment] 2019-07-06 01:34
Here's a diff of the Drupal uninstall code vs the Backdrop uninstall code... 

The only significant change is the addition of `config_uninstall_config($module);`.  

I know we have (had?) a core bug where if your contirb module does not provide an Implementation of `hook_uninstall()` the config files it provides do not get deleted...  I wonder if this bug was introduced as part of a fix for that issue?

```
--- a/docroot/includes/install.inc
+++ b/docroot/includes/install.inc
@@ -771,16 +771,16 @@ function drupal_install_system() {
  * @see module_disable()
  * @see module_enable()
  */
-function drupal_uninstall_modules($module_list = array(), $uninstall_dependents = TRUE) {
+function backdrop_uninstall_modules($module_list = array(), $uninstall_dependents = TRUE) {
   if ($uninstall_dependents) {
     // Get all module data so we can find dependents and sort.
     $module_data = system_rebuild_module_data();
     // Create an associative array with weights as values.
     $module_list = array_flip(array_values($module_list));
 
-    $profile = drupal_get_profile();
+    $profile = backdrop_get_profile();
     foreach (array_keys($module_list) as $module) {
-      if (!isset($module_data[$module]) || drupal_get_installed_schema_version($module) == SCHEMA_UNINSTALLED) {
+      if (!isset($module_data[$module]) || backdrop_get_installed_schema_version($module) == SCHEMA_UNINSTALLED) {
         // This module doesn't exist or is already uninstalled. Skip it.
         unset($module_list[$module]);
         continue;
@@ -792,7 +792,7 @@ function drupal_uninstall_modules($module_list = array(), $uninstall_dependents
       // them automatically because uninstalling a module is a destructive
       // operation.
       foreach (array_keys($module_data[$module]->required_by) as $dependent) {
-        if (!isset($module_list[$dependent]) && drupal_get_installed_schema_version($dependent) != SCHEMA_UNINSTALLED && $dependent != $profile) {
+        if (!isset($module_list[$dependent]) && backdrop_get_installed_schema_version($dependent) != SCHEMA_UNINSTALLED && $dependent != $profile) {
           return FALSE;
         }
       }
@@ -807,10 +807,11 @@ function drupal_uninstall_modules($module_list = array(), $uninstall_dependents
     // Uninstall the module.
     module_load_install($module);
     module_invoke($module, 'uninstall');
-    drupal_uninstall_schema($module);
+    backdrop_uninstall_schema($module);
+    config_uninstall_config($module);
 
     watchdog('system', '%module module uninstalled.', array('%module' => $module), WATCHDOG_INFO);
-    drupal_set_installed_schema_version($module, SCHEMA_UNINSTALLED);
+    backdrop_set_installed_schema_version($module, SCHEMA_UNINSTALLED);
   }
 
   if (!empty($module_list)) {

```

**Comment by jenlampton** [comment] 2019-07-06 01:41
Hm, `config_uninstall_config()` has been unchanged since 2014. 

And anyway, Syslog does not implement `hook_config_info()` - so as much as I was hoping that fixing that bug caused this one I think we may still have both of them.

**Comment by jenlampton** [comment] 2019-07-06 01:48
I think this might have been a recent change to Drupal 7 that was cross-ported to Backdrop? I'm now also seeing syslog appear on the Drupal 7 uninstall page. Oh hangon, syslog has an uninstall hook in Drupal 7 ...  bad example.

**Comment by klonos** [comment] 2019-07-06 12:32
I was under the same impression as you @jenlampton; that only modules that declared uninstall hooks would show up in `admin/modules/uninstall`. It seems that we must have been wrong all this time 🤔

**Comment by jenlampton** [comment] 2019-07-09 00:25
Maybe that was a Drupal 6 thing? Jeez we're getting old!

**Comment by BWPanda** [comment] 2020-08-16 03:00
> It seems that we must have been wrong all this time

Yes, in D7 and Backdrop, *all* modules need to be uninstalled. This is because all modules have, at the very least, an entry in the `system` table. So that needs to be removed when a module's no longer required, hence the 'Uninstall' process.

Here's a list of the different states a module can be in:
- **Installed/Enabled**: The module is enabled and usable on the site. There are entries (and maybe tables) in the DB, and possibly config in the filesystem.
- **Disabled (previously installed)**: The module is not usable, but still has entries (and maybe tables) in the DB, and possibly config in the filesystem.
- **Uninstalled/Disabled (never installed)**: The module is not usable and has no entries or tables in the database, and no config in the filesystem.

Therefore, to go from 'Installed' to 'Disabled' and then just deleting the module from the `modules` directory (i.e. skipping the 'Uninstall' process), you leave at least once reference in the DB, and possibly whole tables and config files.

I'd say this issue should be closed as 'works as designed'.

**Comment by indigoxela** [comment] 2021-01-24 11:21
I don't think that this is a bug anyway. @BWPanda already explained, why all modules need to get "uninstalled".

Closing this as "works as designed". Feel free to re-open, if you still think, there's something to do.

**Closed by indigoxela** 2021-01-24 11:21 UTC
Labels: status - works as designed
