### ISSUE TITLE
Root 'files' directory still used in multi-site setup

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#1853] opened 2016-05-12 13:30 UTC
I'm getting this error on my status page, and yet my 'files' directory is writable by both my user account and the web server:
`drwxrws--- 3 panda www-data  4096 May 12 16:22 files`
The same is true of all the directories inside it.

What am I missing/doing wrong?

----
PR by @jlfranklin https://github.com/backdrop/backdrop/pull/1724

**Comment by serundeputy** [comment] 2016-05-12 14:28
> drwxrws--- 3 panda www-data 4096 May 12 16:22 files

what is that `s`?

Try `sudo chown -R panda:www-data files` and `sudo chmod -R 770 files`

also I like this script Script based on guidelines given above: Script based on guidelines given above

~Geoff

**Comment by BWPanda** [comment] 2016-05-12 22:41
> what is that `s`?
It's a 'setgid' flag. It means that new files or directories created in 'files' will be given the 'www-data' group, as opposed to 'panda'. See here for more info: https://en.wikipedia.org/wiki/Setuid#setuid_and_setgid_on_directories

Tried your suggestions, but they didn't work unfortunately, still get error on status page (even after clearing caches). Also tried removing the 'setgid' flag, but that didn't change anything either.

I think there was a link to the script missing from your comment @serundeputy...

**Comment by BWPanda** [comment] 2016-05-12 22:46
Ok, so on a hunch, I checked the 'files' directory in the root directory (I'm using a multisite setup with a files directory in the site-specific directory under 'sites', so didn't think about that before). It was indeed not writable and when I made it so, it worked and the error went away.

So the question now becomes, how and why is the root 'files' directory still used in a multisite setup? And should that be the case, or is that a bug?

When I look at the contents of the different files directories, I see the following in my site-specific files directory:
config_.../

And the following in the root files directory:
pictures/
README.md
styles/

Shouldn't those directories (pictures/ and styles/) be in the site-specific files directory instead?

**Comment by klonos** [comment] 2016-05-13 01:37
> ...or is that a bug? ...Shouldn't those directories (pictures/ and styles/) be in the site-specific files directory instead?

I see this as a bug. I too feel like there should be site-specific files directories.

**Comment by serundeputy** [comment] 2016-05-13 01:44
missing link: https://www.drupal.org/node/244924 see the `Script based on guidelines given above` section.

~Geoff

**Comment by BWPanda** [comment] 2016-05-13 04:24
Thanks @serundeputy, I have a script that changes my permissions automatically based on that page. It was after running this script that I noticed this problem (so I've subsequently added a section that also changes the permissions for the root 'files' directory as well as site-specific ones).

**Comment by quicksketch** [comment] 2016-05-13 21:09
I also agree this is a bug. Backdrop should default to putting the files directory in the same directory as `conf_path()`. By default this is the root directory of Backdrop, but if you have set up `sites.php` then the files directory should match where `settings.php` is.

**Comment by BWPanda** [comment] 2016-05-21 03:26
Argh! I just got bitten by this bug. In upgrading Backdrop I just copied over the /sites directory and then wondered where all my images went...

**Comment by BWPanda** [comment] 2016-09-28 06:56
I hope this can be fixed soon, as I just setup my 2nd Backdrop site using the same codebase (multisite setup), so now two different websites are sharing the same files directory... Not sure how I'll separate them when this is fixed.

**Comment by jlfranklin** [comment] 2017-01-07 00:25
@BWPanda, I'm running into the same issue: installing a bunch of sites in a multi-site setup, and need a sane way to do it.

The PR works if you copy the `settings.php` file to the `sites/mysite.com` directory _and_ set the `$database` string before installing.  If you don't, then the site fails to install the modules in the profile and leaves you with a half-installed site.

**Comment by quicksketch** [comment] 2017-02-10 01:13
Thanks @jlfranklin! PR at https://github.com/backdrop/backdrop/pull/1724 looks like a great start, though sounds like this needs a bit more work before its ready.

**Comment by jenlampton** [comment] 2017-02-13 03:37
Pushing this to the 1.6.2 milestone since the PR needs work and we are releasing 1.6.1 tonight.

**Comment by docwilmot** [comment] 2017-04-21 13:28
This bug is a significant regression and needs to be fixed.

**Comment by jenlampton** [comment] 2017-04-21 18:52
Agreed.

**Comment by docwilmot** [comment] 2017-04-21 22:19
I looked at the PR and I dont quite get the point, and unfortunately dont have the time to figure it out before 1.7.0.

**Comment by jlfranklin** [comment] 2017-04-23 16:26
That `if` was supposed to be an `elseif`.  The half-installed site error does not happen with `elseif`.

My own testing consisted of:

* directory present with pre-configured settings.php
* directory present with default settings.php file
* directory present and emtpy
* directory not present

The first three pass.  The fourth successfully installs Backdrop, but uses the default `$BACKDROP_ROOT/settings.php` and `$BACKDROP_ROOT/files`.  This is a bug in `find_conf_path()`, which we can fix in a separate issue.

Code is pushed up, tests are running now.

**Comment by quicksketch** [comment] 2017-04-24 00:31
All tests passed and this looks good. I should have been able to see that was just a simple "elseif" to fix everything. Thanks @jlfranklin for revisiting this and fixing that issue.

Merged https://github.com/backdrop/backdrop/pull/1724 into 1.x and 1.6.x. Thanks @jlfranklin and @docwilmot!

**Closed** 2017-04-25 14:34 UTC
Labels: status - fixed, status - has pull request, type - bug report

**Comment by quicksketch** [comment] 2017-05-12 20:03
This PR caused a regression it seems. See https://github.com/backdrop/backdrop-issues/issues/2683.
