### ISSUE TITLE
[UX] Modal popups jump to the top of the page when opened

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4342] opened 2020-03-14 12:20 UTC
**Description of the bug**
When you open a modal popup (e.g. the Image Library browser), the page behind the modal jumps up to the top of the page and, when you close the modal, you have to scroll back down to where you were previously. This is very frustrating.

**Steps To Reproduce**
To reproduce the behavior:
1. On a new sandbox site, edit the 'Your first post' node: `/node/1/edit`
2. Scroll down to the Image field and click 'Select existing file'
3. Note the page behind has jumped back to the top
4. Close the modal popup and groan in frustration as you scroll back down to the image field

Screencast:
![Peek 2020-03-14 14-18](https://user-images.githubusercontent.com/2385329/76681726-bd490800-65fe-11ea-9eba-421bad6e53e6.gif)

**Comment by laryn** [comment] 2020-03-14 13:11
Not by a computer to test but is this because the focus is on the title field?

**Comment by BWPanda** [comment] 2020-03-14 13:26
@laryn Hmm, yes and no...

No, in that if I focus a field below the modal trigger (e.g. Authoring Info), when the modal opens the page behind still jumps to the top.

But yes, in that when I then close the modal, it jumps back down to the focused Authoring Info field.

Interesting...

**Comment by klonos** [comment] 2020-09-19 06:29
You can reproduce this in our forum, in threads where there are several/enough comments that scroll the page down:

- find a thread with many comments
- scroll to the last comment
- start adding a new comment
- try to insert a link via the button in the CKEditor toolbar -> page jumps to the top 👎 

...now you need to scroll down to your comment, to continue editing it, or hit the "save" button 👎

**Comment by indigoxela** [comment] 2021-09-24 07:26
This is a really annoying bug, especially with longer node forms or comment threads.
I can't fix it, but I could advocate. Is anyone able to work on this bug?

**Comment by laryn** [comment] 2021-09-24 14:37
I also am not certain how to approach it but advocating is a good idea to get it on the agenda and discussed :+1:

**Comment by stpaultim** [comment] 2021-09-29 19:58
I also find this frustrating. I thought I was told once that this was expected behavior, which has prevented me from whining too loudly. But, every time it happens I am frustrated and can't believe that this is the best option available.

**Comment by laryn** [comment] 2021-09-30 02:41
@indigoxela and @stpaultim I made a PR based on [this Stack Exchange comment from Nimish Goel](https://stackoverflow.com/a/50086408/4122575).

**Comment by indigoxela** [comment] 2021-09-30 05:59
@laryn wow, I can't belief it - such a simple fix! You're my hero!

**Comment by findlabnet** [comment] 2021-09-30 06:26
Maybe I'm doing something wrong, but now the page jumps **after** inserting (when closing the modal window).

**Comment by indigoxela** [comment] 2021-09-30 06:37
> but now the page jumps after inserting image...

Odd, I can't reproduce that, it works fine here with FF for both, links and images. Which browser are you using?

**Comment by findlabnet** [comment] 2021-09-30 06:44
Google Chrome Version 94.0.4606.61 (Official Build) (64-bit)
Debian/GNU Linux 10.10

**Comment by indigoxela** [comment] 2021-09-30 07:33
> reproducible in any Chromium-based browser (for me).

Hm. Not reproducible in Chromium 93.0.4577.82 (also Linux). Tested in the Tugboat sandbox.

**Comment by olafgrabienski** [comment] 2021-09-30 08:48
> now the page jumps after inserting image (when closing the modal window)

Confirmed for Chrome version 94.0.4606.61 on Mac OS 10.15.7.

**Comment by olafgrabienski** [comment] 2021-09-30 09:04
> page jumps after inserting image

Hm, I was even able to reproduce it in Firefox, at least kind of.

- Edited a post (noted the focus in the Title field)
- Scrolled down to the image field
- Hit "Select existing file"
- Chose an image, and clicked "Insert

Result: image was inserted, page jumped back *nearly* to the top, focus was back in the "Title" field

**Comment by indigoxela** [comment] 2021-09-30 09:13
> Result: image was inserted, page jumped back nearly to the top, focus was back in the "Title" field

Ah, the autofocus on the node title field - IMO a different issue (bad UX!), unrelated here.
I can reproduce it in FF, but only if the title field had focus before opening the dialog.

If you make sure that there is **no** focus on the title field, before opening the dialog - does the problem persist on Chrome(ium) 94.0?

**Comment by olafgrabienski** [comment] 2021-09-30 09:32
> If you make sure that there is no focus on the title field, before opening the dialog - does the problem persist on Chrome(ium) 94.0?

Oh, I see! In this case, it does not persist, so it was indeed the autofocus.

**Comment by laryn** [comment] 2021-09-30 12:59
Probably a separate issue, but since focus could be in a title (or other) field without it having been autofocused, should we be giving that type of link/button (in this case the "Select existing file" button) focus manually when clicked?

**Comment by indigoxela** [comment] 2021-09-30 13:12
> Probably a separate issue, but since focus could be in a title (or other) field without it having been autofocused, should we be giving that type of link/button (in this case the "Select existing file" button) focus manually when clicked?

I agree, this should be a different / new issue.

**Comment by klonos** [comment] 2021-10-01 14:49
> I agree, this should be a different / new issue.

I second that 👍🏼 ...thanks for creating #5266 @laryn 🙏🏼 

The PR for this is RTBC 👍🏼

**Comment by indigoxela** [comment] 2021-10-14 05:50
> ... html.dialog-auto-resize CSS to position: static

This also seems to work, but as "static" is the default, anyway, you could as well skip it. Only removing the `position: fixed` already should do the trick. BTW, if you also remove the `overflow: hidden`, the side-jump because of the scrollbar would also get fixed.

**Comment by laryn** [comment] 2021-10-14 20:34
@indigoxela I actually ended up chopping out the whole `html.dialog-auto-resize` section completely. It seems to work fine -- do we know if that was doing anything helpful anywhere?

**Comment by indigoxela** [comment] 2021-10-15 06:18
> I actually ended up chopping out the whole html.dialog-auto-resize section completely. It seems to work fine -- do we know if that was doing anything helpful anywhere?

The locking has been introduced in #3743 - I confirmed that the "jump" is back when editing custom blocks. So, unless we find a better solution, the "overflow: hidden" is needed - although that causes a slight side-jump.

**Comment by laryn** [comment] 2021-10-15 13:03
I'm making myself cross-eyed on this one. How does the current version look to you? (The one strange thing I can't figure out is the "Add block" in the header region of a layout only -- before any scrolling -- jumps down for me but any other "Add block" works as expected).

**Comment by indigoxela** [comment] 2021-10-15 13:31
Unfortunately the `overflow: hidden` alone also doesn't do the trick. That doesn't fix the second jump (when expanding the fieldset inside the dialog).

**Comment by indigoxela** [comment] 2021-10-15 13:45
Seems like two "jumpers" compete here: the dialog and the fieldset.

`position: inherit` brings me closest to a solution, but does not fix the jump caused by the expanding fieldset - maybe we can't solve it at all without revisiting animated fieldsets? They're also a bit "jumpy" outside dialogs.

**Comment by stpaultim** [comment] 2021-11-27 04:19
Seems pretty clear from recent discussions that this should not have "Works for me" on it right now. @indigoxela as the primary tester, please change it back if I'm wrong.

**Comment by indigoxela** [comment] 2021-11-30 11:36
Still not giving up here. :grin: This jumping just annoyed me again.

What we figured out so far: The problem, which caused that previous commit - which lead to the jump-to-top regression was actually caused by Backdrop.collapseScrollIntoView().

So the previous "fix", which forced position: fixed, top: 0 (the reason for the current jump to top) should get reverted - it caused more trouble than it fixed.  #3743

The actual reason for the down-jump, which was attempted to get fixed by positioning is the fieldset expand and that the [collapse.js](https://github.com/backdrop/backdrop/blob/b2690394c575ffe659186a6a818dba93da418f6e/core/misc/collapse.js#L45) script tries to re-position. 

Our options:

- get rid of that ScrollIntoView anti-feature completely - it also causes distracting jumps when outside dialogs (I'm aware, it may be hard to find consensus re that)
- do not run that ScrollIntoView, when _inside a dialog_

Feedback is welcome! Please let's fix that jumping once and for all.

**Comment by yorkshire-pudding** [comment] 2021-11-30 12:28
I've just checked out the default behaviour in a few areas.  I can't say I've actually noticed it before so didn't bug me too much.  Is more annoying on content creation than layout.
I'm not sure what is meant by the issues that are described above so don't know how to test these.  Point me in the right direction and I'll give it a go so I can give more feedback.

**Comment by indigoxela** [comment] 2021-11-30 12:34
There's nothing to test yet, as the current PR is outdated (causes another problem).

The request for feedback is about "can we get rid of ScrollIntoView"? At least inside dialogs. Before I create a PR. :wink:

**Comment by indigoxela** [comment] 2021-11-30 13:07
Now there *is* a [PR](https://github.com/backdrop/backdrop/pull/3839) for testing and review. It's less radical, as it only prevents collapseScrollIntoView when the fieldset is inside a dialog.

How to test:

- Go to /admin/structure/layouts/manage/default
- **important** scroll to the middle of the page
- Open one of the "Configure" dialogs
- Open one of the included fieldsets, close, open, close
- The page underneath may not jump up or down
- The dialog itself may not jump left/right a bit

- Go to /node/add/post
- Open the Link dialog
- Expand the fieldset inside
- ... same as above, there should not be any jumping of the page underneath

- Pick any fieldset outside dialog, like /admin/appearance/settings/basis
- Collapse some fieldsets
- Scroll down a bit, so one of the collapsed fieldsets would be outside the viewport, when expanded
- Expand it
- The fieldset contents should jump into view (anti-feature IMO, but somebody else may like it)

**Comment by docwilmot** [comment] 2021-11-30 13:28
This is great. Works well. If we could add some animation to the "anti-feature" it would be even better.

**Comment by indigoxela** [comment] 2021-11-30 14:00
> If we could add some animation to the "anti-feature" it would be even better.

Do you think, if the scrolling was smoother, I'd like it more? :grinning:

Well, there's now a native [scrollIntoView](https://caniuse.com/scrollintoview), but support for the "smooth" parameter isn't very good.

**Comment by findlabnet** [comment] 2021-11-30 14:43
Works as described.

**Comment by docwilmot** [comment] 2021-11-30 15:17
Actually I looked at the current behaviour and there isnt really a noticable difference with this PR. I think the "anti-feature" is a feature.

In either case this PR solves the current problem for me. WFM.

**Comment by indigoxela** [comment] 2021-11-30 15:25
Many thanks for testing. :+1: 

> I think the "anti-feature" is a feature.

Maybe you want to open an issue for the animation smoothness? Eventually other people also think that it's time to overhaul the fieldset animation (including jump into view). That whole collapse.js appears a bit dated.

**Comment by yorkshire-pudding** [comment] 2021-11-30 16:20
This all looks good - meets what you expect from your description and also from what users would expect.

**Closed** 2021-12-03 23:26 UTC
Labels: type - bug report, status - has pull request, pr - ready to be committed, pr - works for me

**Comment by quicksketch** [comment] 2021-12-03 23:28
Merged https://github.com/backdrop/backdrop/pull/3839 into 1.x and 1.20.x. This is so great to get fixed!

Big crew on this one, thank you to @indigoxela, @laryn, @BWPanda, @docwilmot, @findlabnet, @olafgrabienski, @yorkshire-pudding, @klonos, and @stpaultim!
