### ISSUE TITLE
Layout->getContexts() error when on Account Settings page

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4598] opened 2020-09-03 16:56 UTC
**Description of the bug**

Get this error:

> Warning: Invalid argument supplied for foreach() in Layout->getContexts() (line 773 of /app/core/modules/layout/includes/layout.class.inc).

**Steps To Reproduce**

To reproduce the behavior:
1. Go to `Account > Settings`

Using 1.17.0-preview. This might be related to merging of adding ability for multiple contexts on a layout.

**Comment by herbdool** [comment] 2020-09-03 17:09
@docwilmot do you want to try tackle this? Not sure if you can replicate or not.

**Comment by indigoxela** [comment] 2020-09-04 06:24
@herbdool I can't reproduce it on a 1.17.0-preview install. Not on admin/config/people/settings and this php warning doesn't appear in dblog, although I clicked through backdrop quite a lot.

Could we get some details about your default administrative layout? Or whatever layout is set for the page(s) this warning appears on your site.

**Comment by quicksketch** [comment] 2020-09-10 19:41
This sounds like the same fix suggested in https://github.com/backdrop/backdrop-issues/issues/4604 might help here.

**Comment by jenlampton** [comment] 2020-09-10 20:01
Where is the account settings page? Is it `admin/config/people/settings` or `Administration` > `Configuration` > `User accounts`?

If so, I am not seeing any errors on this page after running updates with the patch from in #4604.  I'm tempted to mark this as dupe?

**Comment by quicksketch** [comment] 2020-09-14 21:07
If this isn't fixed by the now merged #4604 then let's reopen, but it seems as though its the same problem.

**Closed by quicksketch** 2020-09-14 21:07 UTC
Labels: status - duplicate
