### ISSUE TITLE
Some setting files not being deleted after deleting a content type

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop/backdrop-issues#5860] opened 2022-11-14 11:12 UTC
## Description of the bug

After deleting a test content type, some settings files are still present on config/active directory.

## Steps To Reproduce

1. Create a new content type named 'test' and clic on 'save and add fields'
2. Just don't add any field, but go to config tab and delete the content
3. confirm deletion

## Actual behaviour

The following settings files are still present on config/active:
* field.instance.comment.comment_node_test.comment_body.json
* field.instance.node.test.body.json

## Expected behaviour

I would say those files shouldn't be there. Am I wrong?

## Additional information

Backdrop v. 1.23.0

**Comment by indigoxela** [comment] 2022-11-14 11:16
@robertgarrigos this is mostly a duplicate of #5469.

As for the body field config: you still might have body field content for field.instance.node.test.body in the database.

**Comment by robertgarrigos** [comment] 2022-11-14 14:15
thanks, @indigoxela. I did look for it before posting mine....

> As for the body field config: you still might have body field content for field.instance.node.test.body in the database.

Actually, I don't.

**Comment by indigoxela** [comment] 2022-11-14 14:48
Interesting... I'm pretty sure, you didn't run cron in the meantime, because when I run cron, that node body field json file gets removed.

- For the field.instance.comment.comment_node_test.comment_body.json we already have an issue
- The field.instance.node.test.body.json thing gets fixed by a cron run

**Comment by robertgarrigos** [comment] 2022-11-14 16:55
No, I didn't run cron. ok. Thanks.

**Comment by laryn** [comment] 2024-02-16 18:53
> No, I didn't run cron. ok. Thanks.

Closing, assuming the cron run solved this. (Reopen if I'm wrong.)

**Closed by laryn** 2024-02-16 18:53 UTC
