### ISSUE TITLE
Flexible layouts: "Row" label/indicator rendered in the frontend

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#5343] opened 2021-11-05 04:08 UTC
**Description of the bug**

If you create a NEW flexible layout using the DEV branch (with the new UI improvements to the flexible layouts UI) you will see some unexpected "Row" labels on the page (see below).

**Steps To Reproduce**

To reproduce the behavior:
1. Spin up a new site with the current DEV branch
2. Create a new flexible layout template (just use default)
3. Change the home page to use your new template (leave blocks where they land)
4. View the home page

**Actual behavior**

![image](https://user-images.githubusercontent.com/3144571/140456690-826034a3-8db4-4b8c-a188-3d351a670f52.png)

**Expected behavior**

I don't expect to see these "row" labels

**Additional information**

I wonder if this was "debug" code that didn't get removed?

I think this is caused by a recent commit that has not yet been released. 
https://github.com/backdrop/backdrop/commit/981d52604da163ac6e93e0f58fa6cf6dd051f933

https://github.com/backdrop/backdrop-issues/issues/5149

**Comment by klonos** [comment] 2021-11-05 05:15
Thanks for catching that @stpaultim ...I think I know what's wrong.

**Comment by klonos** [comment] 2021-11-05 06:20
PR up for review: https://github.com/backdrop/backdrop/pull/3815

There are some indentation issues in that file, but I'll fix those in a separate commit.

**Comment by klonos** [comment] 2021-11-05 06:29
> There are some indentation issues in that file, but I'll fix those in a separate commit.

- commit with the actual fix + minimal indentation fixes: [`c912ce1` (#3815)](https://github.com/backdrop/backdrop/pull/3815/commits/c912ce1dafa61955a2d5ffdfaddd5396c97f2b2d)
- commit with further indentation fixes: [`36d0d25` (#3815)](https://github.com/backdrop/backdrop/pull/3815/commits/36d0d251cfd42bf56864a47e14e62ecf2439cf78)

**Comment by stpaultim** [comment] 2021-11-05 07:13
I can confirm that the problem is fixed. Works for me.

**Comment by indigoxela** [comment] 2021-11-05 07:18
:grinning: same here, works for me, but there might be a slight regression.

Previously the "Headings" were bold, but they're not anymore, so the contrast in the template edit form is worse.

Before:

![bold-text](https://user-images.githubusercontent.com/842066/140472776-c5bf0337-c59c-4862-9532-301579cf0803.png)

Now, with this PR:

![no-more-bold](https://user-images.githubusercontent.com/842066/140472801-3d2519ab-460d-4b09-9dd6-8d2b2c17fbf6.png)

Is this by intention?

**Comment by indigoxela** [comment] 2021-11-05 07:21
Ah, sorry, my fault, I compared apples with pears... :smile: No change in the "boldness" of text, the contrast is as bad as before - maybe an A11Y follow-up for the template edit form?

**Comment by stpaultim** [comment] 2021-11-05 07:39
> No change in the "boldness" of text, the contrast is as bad as before - maybe an A11Y follow-up for the template edit form?

I agree that this might be worth revisiting, once the current changes are merged.

**Comment by klonos** [comment] 2021-11-19 20:58
Just a reminder that the actual fix is this simple commit: [`c912ce1` (#3815)](https://github.com/backdrop/backdrop/pull/3815/commits/c912ce1dafa61955a2d5ffdfaddd5396c97f2b2d) ...the rest of it is fixing indentation.

**Comment by argiepiano** [comment] 2021-11-19 22:54
Applying the patch (https://github.com/backdrop/backdrop/pull/3815/commits/c912ce1dafa61955a2d5ffdfaddd5396c97f2b2d) fixed the issue for me. Thanks

**Comment by herbdool** [comment] 2021-11-20 05:50
I've checked the code.

This seems to be a recent pattern where some UI tweaks are causing other things to break. Perhaps we should be more comprehensive with our testing given that this sort of stuff doesn't have automated tests.

**Comment by stpaultim** [comment] 2021-11-20 07:56
What's worse is that this bug was identified and a fix provided prior to this last release, but because the fix was not RTBC, no one noticed. In the future, if we catch a bug in a the dev branch before it's released, we should have a way to flag that issue to prevent the bug from being released - or to quickly roll back the commit before it gets released.

**Comment by stpaultim** [comment] 2021-11-20 08:06
Someone is also talking about this in the forum. https://forum.backdropcms.org/forum/update-1202-bug-flexible-layout

@quicksketch - Does this bug warrant a quick fix or how do we deal with this?

**Comment by indigoxela** [comment] 2021-11-20 13:26
One easy thing we could do is to add a link to this issue in the release notes: https://github.com/backdrop/backdrop/releases

Maybe we can prevent one or two WTF moments with a "known issues" hint.

**Comment by indigoxela** [comment] 2021-11-20 13:32
This bug only affects sites if:

- flexible layout templates are in use
- no custom template file exists (overriding the default)

What should we recommend as a workaround? Probably not everyone has shell access and/or the ability to apply patches.

Maybe we should link to a download of the [previous version](https://raw.githubusercontent.com/backdrop/backdrop/2a719a4d1f5ce20c47092c8fbf6ccf1cf81f15fa/core/modules/layout/templates/layout--flexible.tpl.php)?

**Comment by herbdool** [comment] 2021-11-20 14:00
Maybe we need a regression flag. Or "dev regression" flag to identify something just merged that broke something.

**Comment by klonos** [comment] 2021-11-20 23:19
> if we catch a bug in a the dev branch before it's released, we should have a way to flag that issue to prevent the bug from being released

Or if we have an easy fix such as this ready, then flag the fix as a release blocker for that release?

**Comment by jenlampton** [comment] 2021-11-21 01:58
> What's worse is that this bug was identified and a fix provided prior to this last release, but because the fix was not RTBC, no one noticed.

I don't think another issue label would help in this case, since core committers check only the RTBC label. Perhaps what we need to do is @-mention the core committers via @backdrop/core-committers  so that they know there's something that either needs to be revered or fixed before release.

**Comment by albanycomputers** [comment] 2021-11-22 13:49
> What should we recommend as a workaround? Probably not everyone has shell access and/or the ability to apply patches.

Just came across this bug on a site...  and I don't know how to apply patches... well, I have done a few in the past, but that was many a year ago...

I'll just download and edit the file and take out the offending line, then upload it to the client's side.

**Comment by indigoxela** [comment] 2021-11-22 13:52
In case, someone can't apply patches, it also works to upload the [previous version of that file](https://raw.githubusercontent.com/backdrop/backdrop/2a719a4d1f5ce20c47092c8fbf6ccf1cf81f15fa/core/modules/layout/templates/layout--flexible.tpl.php), for instance using FTP.

**Comment by argiepiano** [comment] 2021-11-22 14:25
> Just came across this bug on a site... and I don't know how to apply patches... well, I have done a few in the past, but that was many a year ago...
> 
> I'll just download and edit the file and take out the offending line, then upload it to the client's side.

> In case, someone can't apply patches, it also works to upload the previous version of that file, for instance using FTP.

Also [check out the accepted answer here](https://forum.backdropcms.org/forum/update-1202-bug-flexible-layout)

**Comment by albanycomputers** [comment] 2021-11-22 15:21
As a quick fix before I found the offending line in the template and removed it, I added this to my themes CSS

.layout-editor-block-title {
    display: none;
}

**Comment by docwilmot** [comment] 2021-11-27 02:14
@backdrop/core-committers ping again. This is a serious bug.

**Closed** 2021-11-27 11:34 UTC
Labels: type - bug report, status - has pull request, pr - ready to be committed, pr - works for me

**Comment by BWPanda** [comment] 2021-11-27 11:35
Thanks to @klonos for the PR and @stpaultim, @argiepiano & @herbdool for testing/reviewing. I've merged https://github.com/backdrop/backdrop/pull/3815 into 1.x and 1.20.x.
