### ISSUE TITLE
Remove the RSS feed icon from the home page.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2183] opened 2016-09-15 06:52 UTC
It's not really an 80% use-case to have one there anymore, and it makes Backdrop seem dated.

**Comment by quicksketch** [comment] 2016-09-16 01:17
Hm, I thought we had manually placed the Syndicate block on this page, but this feed icon is actually coming from Views, in `class views_plugin_style_rss`:

```
      if (empty($this->view->feed_icon)) {
        $this->view->feed_icon = '';
      }

      $this->view->feed_icon .= theme('feed_icon', array('url' => $url, 'title' => $title));
      backdrop_add_html_head_link(array(
        'rel' => 'alternate',
        'type' => 'application/rss+xml',
        'title' => $title,
        'href' => $url
      ));
```

I actually think Views is providing a helpful attempt here. It makes sense if you had explicitly configured a block to have an RSS feed you would want that icon there. I don't think Views was intended to do exactly what we're making it do here.

So my take on this: We should add a setting to Views to let you control if you want to include the icon on the attached display or not. But this is going to be a more involved process than simply disabling a block or deleting the code out of Views. So I'm going to move this to 1.6.0.

**Comment by quicksketch** [comment] 2016-09-16 01:29
PR filed at https://github.com/backdrop/backdrop/pull/1570.

**Comment by quicksketch** [comment] 2016-09-16 01:55
Merged https://github.com/backdrop/backdrop/pull/1570 that adds this new setting, leaves it on by default, but disables it for our homepage view.

**Closed** 2016-09-16 01:54 UTC
Labels: pr - needs review, status - has pull request, type - feature request
