### ISSUE TITLE
Admin menu doesn't use URL aliases, but other menus do

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#6040] opened 2023-03-27 18:47 UTC
## Description of the bug

If you create a Page node with a URL alias, then add it to the Administration menu, the destination link uses the normal path, i.e., `http://mysite/node/NNN`, rather than the URL alias. The normal path shows if you hover over the menu item, and if you click on the link, the normal path shows in the browser bar.

This is different from other menus. For example, if you add the same Page node to the Primary navigation menu, the alias path shows up when you hover and when you follow the link, the browser shows the alias path as well.

The admin bar menu should behave the same as other menus; it should use the alias.

## Steps To Reproduce

To reproduce the behavior:

1. Create a page node, say, "User accounts page", with some content.
2. Give it a custom URL alias, say, `admin/people/user-accounts-page`, and save.
3. Add a link to this page to the Administration menu, say, at Administration > User accounts > User accounts page.
4. Also add a link to this page to the Primary navigation menu, say, at [menu root] > User accounts page.

Hover over both links in the menu and observe the URL, and/or visit the page via either link.

## Actual behavior

Hovering over the admin menu link shows this:

![image](https://user-images.githubusercontent.com/29214084/228037470-945c718d-e0cc-40e8-be87-7040d712fbc1.jpeg)

Hovering over the primary navigation link shows this:

![image](https://user-images.githubusercontent.com/29214084/228037547-ae55787c-1923-4dd7-adb2-d5b1f22ea7bf.jpeg)

## Expected behavior

Both links should show the URL alias for the link.

**Comment by argiepiano** [comment] 2023-03-28 05:14
This has been inherited from Drupal 7's `admin_menu` module. Links for the admin bar are created using `l` with the option `'alias' => TRUE`, which (counterintuitively) means that `l` will not attempt to find an alias for the href.

The creation of the admin bar links is done in [line 492](https://github.com/backdrop/backdrop/blob/1.x/core/modules/admin_bar/admin_bar.inc#L492)  of `admin_bar_links_menu()`. That line sets `alias` to TRUE to omit alias lookups.

I've tried unsuccessfully to find out why the admin bar purposely avoids alias lookups. There must be a reason for this... perhaps because the admin menu bar automatically builds the tree hierarchy based on the paths themselves, as opposed to the main menu, where the hierarchy is built manually when you create the menu link. Therefore, omitting the alias allows the hierarchy to be built based on the real path.

**Comment by bugfolder** [comment] 2023-03-28 19:10
> perhaps because the admin menu bar automatically builds the tree hierarchy based on the paths themselves...

Isn't the tree-like aspect of the hierarchy established by the menu itself? And then the order within the tree is set by the combination of the `weight` assigned in `admin_bar_links_menu()`, and then the sorting by weight and title done in `theme_admin_bar_links()`.

So I realize that by overriding `theme_admin_bar_links()` in the theme, I could go in and remove all those `'alias' => TRUE` settings, then call `theme_admin_bar_links()` on the modified array. But since `admin_bar` has its own configuration page, it would seem like a nice thing to add a checkbox, "Use URL aliases if available", so that the omission of aliases would be conditional. (Just commenting out that line seems to have the desired behavior with no observed ill side effects.)

**Comment by argiepiano** [comment] 2023-03-29 05:21
That sounds like a good plan to me. In the D7 module, they solved this by changing the href. See:
https://git.drupalcode.org/project/admin_menu/-/commit/67a9e419f4e25b779bf87bc877fb3d6031341b1d

And the [issue](https://www.drupal.org/project/admin_menu/issues/1742844).

**Comment by klonos** [comment] 2023-04-02 00:16
I believe that the reason for this is that to this day pathauto remains in contrib for Drupal. I think that since we have included pathauto in Backdrop core, we don't really need an option for this. If there are pathauto paths generated, then these should be used instead of the "internal" ones.

**Comment by bugfolder** [comment] 2023-04-09 23:49
> I think that since we have included pathauto in Backdrop core, we don't really need an option for this. If there are pathauto paths generated, then these should be used instead of the "internal" ones.

Agreed. That make the PR simple: just omit the "Omit...".

**Comment by klonos** [comment] 2023-11-25 14:59
I have tested this in the PR sandbox vs a demo sandbox. I have confirmed the issue in the demo, and that it is fixed in the PR sandbox 👍🏼 ...code change is straight-forward as well 👍🏼

**Closed** 2023-12-01 19:12 UTC
Labels: type - bug report, status - has pull request, pr - ready to be committed, pr - works for me
