### ISSUE TITLE
Permissions summary in node type page works only with Seven theme.

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1756] opened 2016-03-27 21:43 UTC
With any theme other than seven, the summary states erroneously: No permissions set.

This is caused by the checked permissions count is base on a query : `$(context).find('input:checked:visible')` and the pane is hidden at the time node.type.js is attached.

Seven eventually fixes this bug in the process of making vtabs responsive, which includes a `display: block;`, which makes the DOM thinking the checkbox is visible…

The issue may be fixed in two ways : 
- 1. Copy and invoke Seven's script.js and vertical-tabs.css in your favorite theme;
  Bonus, the vertical tabs will respond nicely to narrow screens; but you probably will need a little adjustment of font sizes;
  for bartik, and similar themes, I use

```
@media (min-width: 750px) {
  .vertical-tab-link .fieldset-legend,
  .vertical-tab-link strong {
    font-size: 1.0834em;
  }
}
.vertical-tab-link .summary {
  font-size: 0.9583em;
}
```

or (easier from the backdrop POV)
- 2. Patch `core/modules/node/js/node.type.js` line #65 as : 

```
       // Find all checked boxes and save the column number.
-      $(context).find('input:checked:visible').each(function () {
+      $(context).find('input:checked.real-checkbox').each(function () {
         $cell = $(this).closest('td');
```

yes, all this is to exclude from the checked boxes count some so-called `dummy-checkbox` which are here apparently for voice readers…

**Comment by BWPanda** [comment] 2020-08-11 03:26
Cannot reproduce this. Permissions summary seems to work fine with Basis, for example. Likely this was fixed in the 4 years since the OP.

**Closed by BWPanda** 2020-08-11 03:26 UTC
Labels: status - cannot reproduce
