### ISSUE TITLE
Regression in 1.22.0-preview for views-related tests

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5615] opened 2022-05-06 15:00 UTC
## Description of the bug

1.22.0-preview introduced a regression that breaks some tests for Views. All tests that override `ViewsSqlTest:setUp()` are currently failing. 

Version 1.22-0-preview added an argument to ViewsSqlTest::setUp. This creates a problem with all other classes that override ViewsSqlTest:setUp and have not been changed.

There are over 10 classes that have this problem, including `CommentViewsHandlerArgumentUserUidTest`, `UserViewsArgumentValidate`, `ViewsHandlerSortDateTest `, etc.

The tests fail in my local, and produce fatal errors in GHA (see for example [this](https://github.com/backdrop/backdrop/runs/6313809761?check_suite_focus=true)).

## Steps To Reproduce

Create an installation using 1.22.0-preview, enable `simpletest` and run, for example, the test `UserViewsArgumentValidate`.

## Actual behavior

Fatal errors

## Expected behavior

Tests should run normally.

PHP: 7.4

**Comment by indigoxela** [comment] 2022-05-06 15:02
> All tests that extend ViewsSqlTest:setUp() are currently failing.

Nice catch! I was about to search / open an issue for that. :laughing:

**Comment by argiepiano** [comment] 2022-05-06 15:04
@indigoxela I can provide a PR for this, unless you've already started working on this. Let me know

**Comment by indigoxela** [comment] 2022-05-06 15:12
> I can provide a PR for this...

Yes, please do, I have to run now, anyway.

**Comment by indigoxela** [comment] 2022-05-07 09:14
@argiepiano as it's a regression - wouldn't it be cleaner to just revert the breaking change in class ViewsSqlTest? Does anyone know, why this setUp has been changed?

And also: ViewsPluginStyleMappingTest is still trowing an exception:
```
PHP Fatal error:  Declaration of ViewsPluginStyleMappingTest::setUp() must be compatible with ViewsSqlTest::setUp(array $modules = []) in ...core/modules/views/tests/styles/views_plugin_style_mapping.test on line 14
```
But that seems to be the last remainder, the other one's now work.

**Comment by indigoxela** [comment] 2022-05-07 09:15
Note: 1.22.0 is the wrong milestone, but 1.22.1 doesn't exist, yet.

**Comment by argiepiano** [comment] 2022-05-07 12:26
Thanks @indigoxela. I'll check that last test. 

Maybe "Regression" was the wrong title? This problem was created, I believe, because, when the Cards feature was merged, ViewsSqlTest:setUp() was changed to allow children classes to be able to enable additional modules for testing by passing arguments to it.  The old  ViewsSqlTest:setUp() did not allow for arguments. This is a common change that has been applied to other test classes. The problem here is that whoever committed this change forgot to check children classes that extend setUp()

See the ["blame" for this change, line 127](https://github.com/backdrop/backdrop/blame/1.x/core/modules/views/tests/views_query.test). It was changed 12 days ago.

It would be wrong to revert this commit, as it's needed for other tests. It's easier to change the tests that were not brought up to date.

**Comment by argiepiano** [comment] 2022-05-07 12:28
> Note: 1.22.0 is the wrong milestone, but 1.22.1 doesn't exist, yet.

Hmm... but 1.22.0 has not yet been release, right? I don't want to wait until 1.22.1 for this to be merged. We need this merged very soon - or else many tests for unrelated PRs will keep failing.

**Comment by argiepiano** [comment] 2022-05-07 12:51
@indigoxela, I've made that fix. As far as I can tell all tests are now passing (I didn't catch the one you caught because it failed silently). Can you please take a look now? (side note: Tugboat instance creation failed)

**Comment by indigoxela** [comment] 2022-05-07 13:02
> It would be wrong to revert this commit, as it's needed for other tests

Ah, that's the reason for that change. Sure, in this case it has to stay.

And, yes, of course it can still go into 1.22.0 :laughing: And it's a bugfix that should (and can) go in any time.

(So, there you see, I'm personally done with 1.22.0 and step forward to the next release already.)

**Comment by indigoxela** [comment] 2022-05-07 13:20
Great work, all tests passing now!

I'm taking the liberty to directly jump to RTBC, nothing to (manually) test, anyway.

**Comment by herbdool** [comment] 2022-05-07 21:18
This looks good to go now. Unless someone else gets to it first I'll be able to merge it on Monday.

**Comment by argiepiano** [comment] 2022-05-09 12:22
Thank you @herbdool. I'm looking forward to this being merged today so that we can continue working on the other issues whose tests are failing because of this issue.

**Comment by herbdool** [comment] 2022-05-09 18:48
Merged into 1.x. Thank you @argiepiano and @indigoxela.

**Closed** 2022-05-09 18:47 UTC
Labels: type - bug report, status - has pull request, pr - ready to be committed
