### ISSUE TITLE
Manual installation of projects does not check for "type = x" like Project Installer does.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2008] opened 2016-07-06 10:39 UTC
See https://github.com/backdrop-contrib/forum/issues/3

Manually downloading and installing (extracting its contents under `/modules/forum` manually and enabling it via `/admin/modules`) the Forum module from https://github.com/backdrop-contrib/forum/releases/tag/1.x-1.0.0 installs the module just fine without any errors.

Any other method using the Project Installer (`/admin/modules/install` and `/admin/installer/manual`) fails with "The info file (temporary://update-extraction-[hash]/forum/forum.info) does not define a 'type' attribute."

**Comment by klonos** [comment] 2016-07-06 10:48
...not sure if we should fix this (??). Technically, this causes no problem. It in fact offers a workaround for people to "manually" install any module that does not define `type =` in its .info file. The actual problem here is perhaps that the packaging script did not pick this up (but that issue belongs in `backdrop-ops/backdropcms.org/issues` with "github-automation" tag).

**Comment by serundeputy** [comment] 2016-07-07 23:43
I would vote against `fixing` this and would argue that it is not a bug, but expected behaviour.  The `type = x` was added to help Project Browser and BackdropCMS.org and not any technical requirement of Backdrop CMS itself.

So, it is good to help those things, but we should not create problems for backdrop core because of the help this provides.

my 2¢;

**Comment by klonos** [comment] 2016-07-08 06:14
Yes, agreed. Although...

The underlying issue here is that if there is something wrong and the packaging script does not fail (it should if there is no `type =` line in the .info file), then the project node gets created in backdropcms.org and so the project is listed in the Project Browser but it *will* fail to install via the admin UI.

The other issue there is that the generic "Failed to install [number] project(s)" message is of no help to the end user in that case.

Also, people trying to help in the issue queues that try to install manually, will think that the issue report is not legit because for them it does install and thus they are unable to reproduce the issue. That's what happened in https://github.com/backdrop-contrib/forum/issues/3 and I was only able to get to the bottom of this because I know a couple of things more about how the GitHub packaging, the Project Installer and the manual installation all work. People will not be able to figure this out if they are not long-time Drupal/Backdrop users.

**Comment by serundeputy** [comment] 2016-08-08 22:50
It still seems silly to me to create more problems for end users who are installing manually or through drush just to help developers troubleshoot.

The onus is supposed to be on the developers not the end users.  That is the Backdrop way.

**Comment by klonos** [comment] 2016-08-09 01:21
Fair enough, how about we fix the packager not picking up the luck of `type = x` in the .info files (new issue over at https://github.com/backdrop-ops/backdropcms.org/issues)? We should generate an error.txt file like we used to do at some point for other issues with the packaging process. This does not affect the end users - it is for project maintainers' eyes only.

**Comment by BWPanda** [comment] 2019-11-07 17:11
Going to close this in favour of an issue in the other issue queue if still relevant.

**Closed by BWPanda** 2019-11-07 17:11 UTC
Labels: type - question
