### ISSUE TITLE
Remove documentation on variables that don't actually exist

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4828] opened 2020-12-24 00:51 UTC
We don't have variables for `language`, `head`, `css`, `styles`, or `scripts` in the page template, yet these are still in the docs.
https://api.backdropcms.org/api/backdrop/core%21modules%21system%21templates%21page.tpl.php/1

**Comment by jenlampton** [comment] 2020-12-24 01:07
I also added docs for `$html_attributes` and `$body_attributes` in this PR.

**Comment by klonos** [comment] 2020-12-24 09:41
Wonder how these ended up there in the first place? ...did we inherit them from Drupal? ...and if so, have we removed them intentionally? ...and if so, then are there change records for these changes?

Are you sure re `language` @jenlampton? ...have you tested with language modules enabled?

**Comment by klonos** [comment] 2020-12-24 11:12
...looks like `$language->langcode` and `$language->dir` have now been moved to `$html_attributes['lang']` and `$html_attributes['dir']` respectively:

![image](https://user-images.githubusercontent.com/2423362/103079945-89633000-45dd-11eb-8e22-d4598b626cff.png)

Also, how about documenting the other variables (especially the `$user` object)?

**Comment by jenlampton** [comment] 2020-12-24 23:42
> ...did we inherit them from Drupal?

Yes :)

> ...and if so, have we removed them intentionally?

Yes :)

> ...and if so, then are there change records for these changes?

It is now! https://api.backdropcms.org/change-records/htmltplphp-removed

> Also, how about documenting the other variables (especially the $user object)?

The variables that are included for every template are documented separately.

**Comment by klonos** [comment] 2020-12-26 01:36
Thanks for taking the time to explain things @jenlampton 🙏 

My main point then is this:

> looks like `$language->langcode` and `$language->dir` have now been moved to `$html_attributes['lang']` and `$html_attributes['dir']` respectively

Should we at the very least document (either as a docblock in `page.tpl.php `, or in https://api.backdropcms.org/converting-themes) how people that used to use `$language->langcode` or `$language->dir` can get these values now?

**Comment by jenlampton** [comment] 2020-12-27 07:37
I thought it was clear already from the code example. If you think more
docs are necessary, please add them :)

**Comment by BWPanda** [comment] 2023-02-14 00:06
Closing this as a duplicate of https://github.com/backdrop/backdrop-issues/issues/1981 - that includes a similar PR that seems to include everything from here.

**Closed by BWPanda** 2023-02-14 00:06 UTC
Labels: status - has pull request, type - documentation, milestone candidate - bug, pr - needs code review
