### ISSUE TITLE
No thumbnails in library

### ISSUE THREAD

**Issue by dyrer** [backdrop/backdrop-issues#3386] opened 2018-11-16 08:57 UTC
### In library media there are empty thumbnails just the filenames

---
PR by @Graham-72 : /backdrop/backdrop/pull/2408

**Comment by dyrer** [comment] 2018-11-16 08:57
![nothumbs](https://user-images.githubusercontent.com/379094/48611199-9ed8eb00-e97d-11e8-8ae0-5d850439ee7f.jpg)

**Comment by klonos** [comment] 2018-11-16 18:04
Hey partida! 👋 😄...if you navigate to Reports >> Status report, what does it say for "GD library rotate and desaturate effects" and "PHP extensions" I think that if `gd` is not listed in the extensions, then that might be your issue:

<img width="1004" alt="screen shot 2018-11-17 at 5 03 15 am" src="https://user-images.githubusercontent.com/2423362/48638980-401b7c00-ea26-11e8-8325-1e069911ad11.png">

**Comment by dyrer** [comment] 2018-11-16 19:46
Hi Greg, No gd is enabled.

**Comment by klonos** [comment] 2018-11-17 06:08
Hmmm. Seems that we'll need to fire up a setup using openlitespeed to troubleshoot this further. Sorry patrida, but I don't have time for this right now.

Both Backdrop and Drupal do not officially support openlitespeed as it seems:

https://backdropcms.org/requirements
https://www.drupal.org/docs/7/system-requirements/web-server
https://www.drupal.org/docs/8/system-requirements/web-server

...and I have found quite a few issues already reported in d.org:

https://www.drupal.org/project/drupal/issues/1176508
https://www.drupal.org/forum/support/post-installation/2015-01-21/htaccess-problem-in-litespeed-not-working

@dyrer if you are still interested in pursuing this, these might be of help (noting them here for my own benefit too, for future reference):

https://websiteforstudents.com/install-drupal-on-ubuntu-16-04-lts-with-openlitespeed-mariadb-and-php-7-1-support/

https://openlitespeed.org/mediawiki/index.php/Help:Install:Drupal (although that one goes back to D6)

**Comment by dyrer** [comment] 2018-11-17 07:10
https://forum.backdropcms.org/forum/no-thumbnails-library
Another guy in forums reports the same problem

**Comment by klonos** [comment] 2018-11-17 12:54
Thanks for pointing that forum topic out @dyrer 👍

...some people there report that thumbnail conversion works with apache and nginx but not with LiteSpeed and Lighttpd, but at the time of writing there is also one person reporting the issue with nginx.

Others mention noticing that thumbnails aren't being generated when uploading via CKEditor, but are being generated when uploaded as an image field on a content type. I have tested this on my local with Apache (Mac OS 10.13.6 host - Ubuntu 16.04 VM, Apache 2.4.33, php 7.1.24), but I could not reproduce it, as both methods resulted in properly-generated thumbnails.

**Note for people reporting the problem** here in the future, please also report your server and its version, and also php version being used. Might also help to indicate if you are noticing the problem on shared hosting or VPS, or your local + what is the operating system and its version.

**Comment by Graham-72** [comment] 2018-11-19 17:17
@dyrer in your admin list of views can you see the view 'Image Library'? If you select 'configure' for this view and then 'update preview' are you seeing any thumbnails in the preview on this admin page?

I am just wondering at what stage Backdrop is losing the correct href for the images.

**Comment by korontari** [comment] 2018-12-05 13:39
I also do not see thumbnails in library. When I select 'Image Library' view, thumbnails are broken there as well.

I use shared hosting. My server: 
Apache/2.2.33-dev (Unix) mod_ssl/2.2.33-dev OpenSSL/1.0.1e-fips Phusion_Passenger/5.1.12 PHP/7.2.11 mod_wsgi/4.5.2 Python/2.7.5
GD library: bundled (2.1.0 compatible).

**Comment by Graham-72** [comment] 2018-12-05 14:29
@korontari thank you for trying the 'Image Library' view. Please can you now look at the files on your server to see whether Backdrop has created the thumbnail image files which you should see in the folder `/files/styles/thumbnail/public`

If the thumbnail files are there we must have a problem with Views referencing them properly.

**Comment by korontari** [comment] 2018-12-05 15:08
I found that there are no /thumbnails directory in /files/styles.

Here are a few observations that might be important for the issue:
1. I have changed "Public files system path" to a custom one (files_public in my case).
2. In that custom directory (/files_public/styles ) I found several folders corresponding to Image Styles I have defined and used earlier. There is also /thumbnail folder that seem to be related to default(module-provided) style  but it contains only 3 thumbnails out of dozens images that I have uploaded there.
3. I noticed that all of the images were uploaded into image fields contained in my custom defined content types. Those fields had been assigned custom Image Styles in their default displays and module-provided thumbnails(100x100) in their teaser displays.
4. Of all the images there were only 3 displayed as teasers on my site and those images thumbnails where the only present in /files_public/styles/thumbnail/public.

Thank you and I hope this is helpful.

**Comment by Graham-72** [comment] 2018-12-06 07:31
@korontari thank you, yes that is helpful. It seems that if the public file system path is changed from the default value 'files', Views is not generating the correct file path for the thumbnails. This is at the setting for the field 'File: Path (thumbnail)' 'Use full URL instead of file storage URI'. I will have a look at the code and see if I can provide a fix.

**Comment by korontari** [comment] 2018-12-15 21:52
No, I have only latin characters in the path.

**Comment by Graham-72** [comment] 2018-12-16 08:09
@klonos I have responded to your comment in the PR and done a test which would seem to indicate that the proposed fix is OK with multi-byte characters.

**Comment by klonos** [comment] 2018-12-16 12:48
Thanks @Graham-72 👍 

@korontari, @dyrer do you guys have the time to test the fix and confirm if it fixes the problem for you?

**Comment by korontari** [comment] 2018-12-18 17:01
I probably could try a quick test but I don't know how to apply a fix - I am not a coder. May be you could explain me how to do this?

**Comment by jenlampton** [comment] 2018-12-22 06:41
@korontari Let's see if these instructions will work:

1) Download a patch version of the PR from
https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/2408.patch
(I got this URL by adding .patch onto the end of the PR link above)

2) Save this file into into the Backdrop site root, right next to index.php
3) Navigate into the Backdrop site root via command line
4) from the Backdrop site root type `patch -p1 < 2408.patch`
5) if there are no errors, try the image library again to see if the problem is fixed

**Comment by jenlampton** [comment] 2018-12-25 01:30
@korontari Congratulations on applying your first patch :) And best of all -- it worked for you!

**Comment by Chas-Davis** [comment] 2018-12-28 16:16
I also had the same issue. The patch worked for me as well although no shell access with my host so manual editing. Good thing that .patch file is plain text.

**Comment by klonos** [comment] 2018-12-28 22:41
Thanks for testing this @Chas-Davis, and for taking the time to report back 👍

**Comment by quicksketch** [comment] 2018-12-31 05:56
I left a comment on the PR about using `backdrop_substr()` instead of `substr()`. If we can use that instead, that would be preferable.

**Comment by quicksketch** [comment] 2019-01-16 07:39
@Graham-72 made a last edit and I think he's right that the current code is fine, and easier than rewriting to use `backdrop_strpos()` just because it's there. This didn't make it into 1.11.4 but it will be in 1.12.1. Thanks @Graham-72, @dyrer, @klonos, @korontari, @jenlampton, and @Chas-Davis!

**Comment by dyrer** [comment] 2019-06-26 19:30
I am still having problems with thumbnails, https://www.screencast.com/t/aZbSuwO0DUA
The correct thumbnails uploaded from default image field and the corrupted from the image file manager.
Here is also my status report
https://www.screencast.com/t/VMlD2Kv4le8

**Comment by jenlampton** [comment] 2019-06-26 20:49
Re-opening this issue until we can sort out @dyrer 's problem.

**Comment by Graham-72** [comment] 2019-06-27 14:07
@dyrer if you look in the admin listing of files (Manage files) can you see the missing images listed there, e.g. an entry for `dangerous.jpg`? If so, when you hover on the filename in this listing, what link is it showing? Is it linking to a file of exactly the same name and does the link work from there? [I am trying to understand what might be happening in your system].

**Comment by dyrer** [comment] 2019-06-27 14:31
With inspect I have links like this /files/styles/thumbnail/public/inline-images/hestiacp_term.jpg but there are any directories in /files/styles/
here also my /files/ structure
https://www.screencast.com/t/oRWWunhlyqzL

**Comment by Graham-72** [comment] 2019-06-27 15:12
In a previous screencast https://www.screencast.com/t/aZbSuwO0DUA there were three images showing and four not showing.

The images that are showing I expect would have links like `....../files_public/styles/thumbnail/public/inline-images/filename.jpg`

Presumably there is a styles folder within your inline-images folder?

Where in your site are the four missing image files - the ones that do not have images appearing in the library in your screencast image? Does 'Manage files' help you find this? I would like to know whether your system has created a styles folder within that folder.

**Comment by Graham-72** [comment] 2019-06-27 15:14
For example, where in your system is the file dangerous.jpg? I mean, which folder is it in?

**Comment by dyrer** [comment] 2019-06-27 15:38
yes this was from a test server with [hestiaCP ](http://hestiacp.com), is deleted now
The last one is with my main web configuration with [runcloud.io](runcloud.io) and this mainly I care about.
runcloud.io disables also by default these extensions
`getmyuid,passthru,leak,listen,diskfreespace,tmpfile,link,ignore_user_abort,shell_exec,dl,set_time_limit,exec,system,highlight_file,source,show_source,fpassthru,virtual,posix_ctermid,posix_getcwd,posix_getegid,posix_geteuid,posix_getgid,posix_getgrgid,posix_getgrnam,posix_getgroups,posix_getlogin,posix_getpgid,posix_getpgrp,posix_getpid,posix,_getppid,posix_getpwuid,posix_getrlimit,posix_getsid,posix_getuid,posix_isatty,posix_kill,posix_mkfifo,posix_setegid,posix_seteuid,posix_setgid,posix_setpgid,posix_setsid,posix_setuid,posix_times,posix_ttyname,posix_uname,proc_open,proc_close,proc_nice,proc_terminate,escapeshellcmd,ini_alter,popen,pcntl_exec,socket_accept,socket_bind,socket_clear_error,socket_close,socket_connect,symlink,posix_geteuid,ini_alter,socket_listen,socket_create_listen,socket_read,socket_create_pair,stream_socket_server`

**Comment by Graham-72** [comment] 2019-06-27 18:49
As I understand it runcloud.io provides a Server Management Panel on top of an underlying web server. I am unable to set up a test installation and so cannot find out what exactly you are experiencing. Sorry I cannot help you more.

**Comment by korontari** [comment] 2019-10-31 10:11
I have similar issue with thumbnails in library - some of them are just missing. All links point to standard location: /files/styles/thumbnails/public. It looks like not all thumbnail images where generated.

Status report:
![rep](https://user-images.githubusercontent.com/44873997/67938037-c604e880-fbdf-11e9-9ce5-d966a4ba7600.jpg)

**Comment by Graham-72** [comment] 2019-10-31 21:28
@korontari please can you check whether the original image file still exists in /files/public? The only times I have experienced this behaviour is when a temporary image file has been deleted by housekeeping.

**Comment by korontari** [comment] 2019-11-01 17:07
@Graham-72 I have checked and found the following:
1. Some missing thumbnails appeared since I wrote about the bug. :smiley:  I have another BD installation where I saw a missing thumbnail but it also appeared today when I checked it before writing this. 
2. All original images exist, but the thumbnail for some doesn't.
3. The image that has a missing thumbnail was uploaded twice. The second instance of it has got a '_0' suffix in filename on server. Thumbnail is missing for the first image instance (without a suffix). Both file instances can be viewed and edited in 'Content->Manage files' under the same name.
![image](https://user-images.githubusercontent.com/44873997/68041464-afdf5100-fce1-11e9-96aa-cf706e228a56.png)

**Comment by Graham-72** [comment] 2019-11-02 08:00
@korontari thank you for the extra information. I am thinking that there must be some sort of timing race that is showing up on your server. I think that the image library function is calculating the URL of where the thumbnail file will be and sending this to the browser before the server has stored the thumbnail in this location. I am not experiencing this problem on my server.

On a test site I have created a situation where the same image is uploaded three times, twice via  CKeditor into the body and once as the image file in a post. This results in it appearing three times in the image library, as seen here
![image](https://user-images.githubusercontent.com/10559274/68067749-bdc5be00-fd43-11e9-9d3c-405556f6fb9e.png)
As you can see each of the three identical thumbnails has the same name though in fact they are three separate files as can be seen by inspecting the code, which is
` <div class="image-library-choose-file">
<img class="image-library-image" src="http://xxxxxxx/files/styles/thumbnail/public/field/image/P1020377.jpg" data-file-url="http://xxxxxxx/files/field/image/P1020377.jpg" data-fid="37">    
<p class="image-library-filename">P1020377.jpg</p>    
</div>
<div class="image-library-choose-file">
<img class="image-library-image" src="http://xxxxxxx/files/styles/thumbnail/public/inline-images/P1020377.jpg" data-file-url="http://xxxxxxx/files/inline-images/P1020377.jpg" data-fid="43">    
<p class="image-library-filename">P1020377.jpg</p>    
</div>
<div class="image-library-choose-file">
<img class="image-library-image" src="http://xxxxxxx/files/styles/thumbnail/public/inline-images/P1020377_0.jpg" data-file-url="http://xxxxxxx/files/inline-images/P1020377_0.jpg" data-fid="44">     
<p class="image-library-filename">P1020377.jpg</p>   
 </div>
`

In my opinion it is unfortunate that for 'image-library-filename' we are using the human-readable name and not the actual file name. (Backdrop adds a suffix _0, _1 etc when a file with an identical name is uploaded into the same folder). This is a wider issue, raised by @jenlampton in issue #4175.

On an established site where a site editor has, for good reasons, uploaded the same image multiple times, I am finding it difficult with our existing admin capabilities to find out all that I need to know about these different files, hence would welcome some extra help - issues #3904 and #4175 .

**Comment by Graham-72** [comment] 2019-11-02 08:05
Apologies, I have not been able to post my code into github. Github is trying to render it, not just show it as text, maybe because I copied from Word. I will try and find another way of showing it.

**Comment by korontari** [comment] 2019-11-09 15:45
@Graham-72 , thank you for the in depth explanation. The last time I looked into the  image library all thumbnails where in place. So it really seems like a timing related issue in my case. I do agree that filename should be an actual filename. I have left a more detailed feedback here: #3904.

**Comment by jenlampton** [comment] 2020-01-15 23:59
We don't have  PR here to solve the latest problem yet, so adjusting tags and milestones.

**Comment by dyrer** [comment] 2020-02-08 09:59
All that time I've made a lot of test with other control panels and configuration for example, aaPane (nginx)l, gridepane(nginx), cyberpanel(openlitespeed) and thumbnails same problem. With VestaCP, HestiaCP (apache with nginx proxy), ploi.io (nginx) are working so I believe is something with server configuration not permissions.

**Comment by klonos** [comment] 2022-03-19 04:44
Yup, I now have an actual site hosted on LiteSpeed, and I can confirm that there is no issues with generating thumbnails on the image library dialog.

@dyrer are you still having this issue?

**Comment by dyrer** [comment] 2022-03-19 06:31
Yes, with Runcloud.io and working great with hestiaCP. Runcloud is with openlitespeed and hestiaCP nginx with Apache.
@klonos Your host is using Openlitespeed or Litespeed?

**Comment by jenlampton** [comment] 2023-09-05 00:49
Since the PR for this issue has been merged, I'm going to close this issue as fixed. If anyone is still having this problem, feel free to re-open this issue or create a newer one.

**Closed by jenlampton** 2023-09-05 00:49 UTC
Labels: type - bug report, status - fixed

**Comment by bennybobw** [comment] 2025-02-27 20:49
I think this issue needs to get re-opened. We have a site that uses the s3fs module and because `views_handler_field_file_uri`  uses custom code to try to get the image style rather than the image module's `image_style_url` function, all the thumbnails in the image library are broken. Pull request incoming.

**Comment by bennybobw** [comment] 2025-02-27 20:49
I don't have perms to re-open the issue, so I'm going to make a new issue and refer to this one.

**Comment by bennybobw** [comment] 2025-02-27 21:05
Issue #6860

**Comment by quicksketch** [comment] 2025-02-28 03:49
Thanks @bennybobw. For the future, I've added you to the Triage team so you can open, close, and label issues.
