### ISSUE TITLE
"Filter processing order" woes

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#2357] opened 2016-11-25 03:46 UTC
One thing I ALWAYS struggle with is knowing what order the filters should be in for my text formats to work correctly. To make sure they are correct, you have to basically check the readme for each module that provides a text format filter and follow its instructions to arrange them correctly (and of course they can't know what other filter you have enabled, so it's always a guessing game).

Is there no way that we can hide and automate the whole filter processing order process? Something like an extra hook or two that modules implement to say where their filter should be listed in the ordering?

I'm thinking that if every possible core and contributed filter was enabled, there would be at least one ordering system that made sure they all worked correctly. It's either a matter of documenting that somewhere, or better yet making it happen automatically somehow.

Not many answers or suggestions from me as to how to do this I'm afraid, but opening this for further discussion hopefully.

**Comment by jenlampton** [comment] 2016-11-26 22:54
> Is there no way that we can hide and automate the whole filter processing order process?

IIRC we did try to burry the ordering deeper than it was in Drupal. Each filter should be setting a default weight which should be correct, it's very rare that they need to be changed at all. Once they have been changed, all hell usually breaks loose, and it is really really hard to get them back in the right order. 

The problem is that  there are an infinite number of possibilities of filters and their combinations, so it's hard to automate this. The best we can do is let each set its own default.

Would it help if we added a "reset to defaults" button to help people once they do manage to get them out of whack? I bet we could do that, at least.

**Comment by klonos** [comment] 2016-11-27 00:53
> The problem is that there are an infinite number of possibilities of filters and their combinations, so it's hard to automate this. The best we can do is let each set its own default.

We could have it so that each module that defines a filter can specify a `must-go-before` and `must-go-after` array of values that are updated accordingly based on any known issues with other filters. Once we have such a mechanism in place, we can automate the order based on some logic instead of arbitrary filter weights.

**Comment by klonos** [comment] 2016-11-27 00:57
...we can have these be "strict" `must-go-before/after` or lose `suggested-before/after` and also have them define a way that places them *immediately* before/after, perhaps `chain-before` and `chain-after`.

**Comment by jenlampton** [comment] 2016-11-27 01:26
and what happens when two modules both stay they need to go after the another? This is getting messy...

**Comment by jenlampton** [comment] 2016-11-27 01:32
A thought: Maybe we should look at this specific use-case a little closer and try to figure out what's going on specifically, before we brainstorm generic solutions. @BWPanda which filter were you having trouble with initially, when you started changing the filter weights?

It could be that we have different classes of filters that should always be grouped together or something...  let's dig in a little deeper.

**Comment by BWPanda** [comment] 2016-11-27 22:02
The reason for my comment was from my experience with Drupal. I wasn't aware that Backdrop had changed this somewhat already. If that is indeed the case, then maybe a good idea would be to simply put the filter ordering table in a closed-by-default fieldset with a description at the top stating that changing the weights should only be done if you know what you're doing and isn't otherwise necessary. Also, I like the idea of a 'reset to defaults' button :+1:

**Comment by BWPanda** [comment] 2022-01-25 20:39
Going to close this now as there's no indication that there's actually an issue here. If/when we discover a situation where filters don't work OOTB and need to be rearranged first, we can re-open.

**Closed by BWPanda** 2022-01-25 20:39 UTC
Labels: needs - more feedback

**Comment by klonos** [comment] 2022-01-28 10:01
Related: #1033
