### ISSUE TITLE
Mysql 8 Support on Backdrop CMS

### ISSUE THREAD

**Issue by domaingood** [backdrop/backdrop-issues#4539] opened 2020-08-13 20:30 UTC
Problem/Motivation
MySQL 8 has been release and includes performance enhancements. It would be nice to integrate those enhancements with Backdrop CMS.

Proposed resolution
Test a variety of Backdrop CMS distributions running with MySQL 8 and fix bugs as they appear.

Remaining tasks
Add support
User interface changes
Note during the site install that MySQL 8 is supported.

Error Message
Failed to connect to your database server. The server reports the following message: : Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER'.

Is the database server running on localhost?
Is tuhin.info the correct database name?
Are the username and password correct?
For more help with configuring your database server, see the Installation Instructions page.

**Comment by stpaultim** [comment] 2020-08-13 20:34
Is this a duplicate of: https://github.com/backdrop/backdrop-issues/issues/4238

**Comment by klonos** [comment] 2020-08-14 00:24
Yes it is 🙂

**Closed by klonos** 2020-08-14 00:24 UTC
Labels: status - duplicate
