### ISSUE TITLE
[WP][UX] Remove "tabs" from log-in, register, and password reset pages.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3309] opened 2018-10-11 19:40 UTC
A follow-up to https://github.com/backdrop/backdrop-issues/issues/3108

I'd really like to redesign the log-in page to remove the "tabs" entirely. The visual "tabs" are a strange way to navigate these three pages. Plus, they really give away that a site is Drupal/Backdrop.

I almost always remove these tabs in my custom themes, and replace them with a markup element in the form containing links to those pages instead. I'd love to see us do that by default for all Backdrop sites.

**Comment by laryn** [comment] 2018-10-11 19:47
I like that idea.

**Comment by olafgrabienski** [comment] 2018-10-11 19:50
Yes, good idea! @jenlampton can you provide a screenshot of one of your custom themes?

**Comment by docwilmot** [comment] 2018-10-11 20:16
:+1:  to this idea.
would like to see @jenlampton's solution as well.

**Comment by findlabnet** [comment] 2018-10-12 05:36
Would like to see new solution for help to decision. 
Right now these tabs just prepare an user for what he/she will see everywhere after log in.

**Comment by klonos** [comment] 2018-10-12 06:57
I think that @jenlampton means something like this:

<img width="567" alt="screen shot 2018-10-12 at 5 38 18 pm" src="https://user-images.githubusercontent.com/2423362/46852880-3495cd80-ce48-11e8-8dcd-1a96e93fb937.png">

...instead of this:

<img width="546" alt="screen shot 2018-10-12 at 5 38 33 pm" src="https://user-images.githubusercontent.com/2423362/46852892-42e3e980-ce48-11e8-93c4-7303f927fe95.png">

...to which I say 👍

**Comment by jenlampton** [comment] 2018-10-12 20:41
Yes, exactly @klonos. Here's a Drupal 7 site with the tabs hidden (https://www.dogstardaily.com/user)
<img width="659" alt="screen shot 2018-10-11 at 5 58 45 pm" src="https://user-images.githubusercontent.com/397895/46841891-52e3c680-cd7f-11e8-8541-f4e9c459d9ee.png">

**Comment by olafgrabienski** [comment] 2018-10-12 20:55
@jenlampton I like the example! Thing to consider: being on one of the other pages (Forgot PW, Create Account), there is no link (back) to the login page nor to the (other) other page. In the Backdrop implementation we should continue to provide these links.

**Comment by jenlampton** [comment] 2018-10-12 21:12
@olafgrabienski That's a good point. I'd like to see the links below those forms too (like in this example) rather than rendered as "tabs".

**Comment by klonos** [comment] 2018-10-12 22:31
@jenlampton ...are we talking about implementing this on the Basis theme level?

**Comment by jenlampton** [comment] 2018-10-12 23:28
I was thinking about at the menu level, changing these items so they are not "menu local tasks" (and therefore would not be rendered as tabs)

**Comment by klonos** [comment] 2018-10-13 10:31
Hmm, wouldn't that break existing themes though? Whereas if we did it on the theme level, I think it'd have less impact. Just saying.

**Comment by klonos** [comment] 2018-10-13 20:47
...may I add that if we do decide to do this on the theme level, perhaps it'd be worth to file a follow-up ticket to do it on the menu level, but set the target for that ticket to 2.0 where API changes are acceptable.

**Comment by jenlampton** [comment] 2018-10-17 20:37
> Hmm, wouldn't that break existing themes though?

No, it wouldn't break any themes. If a theme had thought to style the tabs on the user/login page specially (and most don't), then there might be some excess code in a theme that would become unnecessary with this change.

> Whereas if we did it on the theme level, I think it'd have less impact.

Yes, that's very true. If we made this change on the theme level, hardly any sites would benefit at all. Another good reason to do it at the menu level ;)

**Comment by jenlampton** [comment] 2018-10-17 20:39
From @kreynen in https://github.com/backdrop/backdrop-issues/issues/3108#issuecomment-430746240

> It is much easier to alter away a menu in a module than it is to figure out if we need to remove markup from a theme.

**Comment by kreynen** [comment] 2018-10-17 22:54
With LDAP, you can run sites in "mixed mode" meaning that user can login via LDAP or a local account.  In that use case, you'd want to be able to create accounts and reset passwords. I'm not sure if either of the SAML projects support mixed mode, but Github SSO does. The only local account on our sites is uid 1.  All other users are invited to join the site using https://www.drupal.org/project/user_external_invite.  An account is created when they authenticate using LDAP or SAML, but to reset their password they'd need to go to https://cuidm.colorado.edu/pwreset/password_reset.html and reset their password for all CU systems.

**Comment by sbgraphicdesign** [comment] 2019-03-01 18:16
There's a Drupal module which improves the login experience and does what the OP asks:

https://www.drupal.org/project/betterlogin

I tried a straight conversion to Backdrop (by replacing the text "drupal" with "backdrop") which didn't work.

It's possible to use a custom layout and blocks (with some custom html) to replicate the Better Login module, but if someone could port the module then that would be much easier!

**Comment by oadaeh** [comment] 2019-03-02 15:33
@sbgraphicdesign did you make those changes manually, or did you use [Coder Upgrade](https://backdropcms.org/project/coder_upgrade)? If not the later, maybe give it a shot and see if the module "magically" works after that.

**Comment by jenlampton** [comment] 2019-03-02 23:22
@sbgraphicdesign can you post your code (in any state) to a Github repo? I'd love to get it working and use it on my sites, instead of my usual custom shenanigans.

**Comment by sbgraphicdesign** [comment] 2019-03-04 21:09
> @sbgraphicdesign did you make those changes manually, or did you use [Coder Upgrade](https://backdropcms.org/project/coder_upgrade)? If not the later, maybe give it a shot and see if the module "magically" works after that.

Hi, sorry I should have been clearer, that's what I did in D7. I couldn't make the Better Login module work for Backdrop, so I've gone another route, using a custom layout, displays and a ported module. I'm nearly there, just having some issues overriding the Login, Register, Password & Password Reset pages.

@jenlampton I'm going to add a repo with all my templates and CSS shortly so keep an eye out for that. Might need some helping refining things somewhat, but to get you started here's a module I've ported over from D7 to help with placeholders in forms: https://github.com/sbgraphicdesign/form_placeholder

**Comment by klonos** [comment] 2019-03-05 00:14
> I couldn't make the Better Login module work for Backdrop, so I've gone another route, using a custom layout

Actually, this is not such a bad idea. We could ship core with a "Login page" layout that would be disabled by default for existing sites (so that we don't end up breaking any custom theming they might already have in place), but be enabled on fresh installations.

If we shipped this new layout with nothing but a login block, then we'd be able to achieve a "separate" full-screen login page (no header/footer/menu), and thus provide a similar login experience as the one Wordpress/Joomla have. If people do not like that, they could simply disable that layout and get back to the good-ol' login page we currently have in place.

**Comment by jenlampton** [comment] 2019-03-05 00:15
mind. blown.

**Comment by sbgraphicdesign** [comment] 2019-03-05 12:18
Okay, here's my repo of what I've done to get a custom login. I hope this will be of use to someone!

Get it here: https://github.com/sbgraphicdesign/Backdrop-Custom-Login-Pages

I've created a login layout which offers two regions, the header, with which to place the site logo, and the main content area where everything else goes.

The layout includes a css file which is adapted from my own with some of the more esoteric elements removed. I've tried to use the core theme's styles, but of course these pages pick up your theme's css as well, so feel free to adapt as necessary. This stylesheet uses Fontawesome for the icons on the input fields.

Links to the Register, Password and Reset pages are hard coded in the footer and display according to the path. These replace the usual Tabs navigation.

My approach uses 4 separate displays, based on a path visibility condition. I was rather hoping to be able to use one single display, however this cannot be achieved in the UI (can it?). The only issue I have with my approach is with the Password Reset page path condition. In my tests '/user/reset/%/%' worked but depends entirely on what url the system spits out, and whether there are two arguments in that url. I'd imagine this could be better handled programmatically.

Lastly there's a ported D7 module for Form Placeholders which does away with the need for labels above the input fields. Just looks neater imho. 

The Read Me file contains full setup and config info.

Get it here: https://github.com/sbgraphicdesign/Backdrop-Custom-Login-Pages

Would be great to have a login layout in core by default. I know a lot of us don't always consider these small elements of websites but I think this sort of attention to detail matters, and does make a difference to (my) clients experience when using their websites.

And for those old-timey 'Drupallers' who prefer the olde ways (lol), it's their choice to use it or not

**Comment by jenlampton** [comment] 2019-05-01 20:52
No PR here yet and it's feature freeze day, so bumping milestone. (Since there is still somewhat recent activity, I'm not pulling milestone entirely...)

**Comment by klonos** [comment] 2019-05-20 23:49
So, how does everyone feel about implementing this as a separate layout (disabled for existing sites - enabled for new installations)?

**Comment by BWPanda** [comment] 2019-10-16 18:28
@klonos I like it! Very Backdrop-y :wink:

**Comment by jenlampton** [comment] 2019-10-16 20:40
I don't know. Approximately 0 of my backdrop sites have a layout for the log-in page. I'm not even sure there's a valid use case for this, and it's definitely not up to the 80% mark. I don't think we should fix UX bugs by adding features nobody needs?

**Comment by klonos** [comment] 2020-07-16 01:49
Should we close this in favor of #4410?

>So, how does everyone feel about implementing this as a separate layout (disabled for existing sites - enabled for new installations)?

^^ I've brought this up in that other issue 😉

**Comment by jenlampton** [comment] 2020-07-16 16:33
Let's leave this open. A new layout won't remove the tabs, so that's not
related, but the theme change there could be repurposed here to work for
all themes.

**Comment by BWPanda** [comment] 2022-06-24 11:48
Here's a PR: https://github.com/backdrop/backdrop/pull/4103

![login](https://user-images.githubusercontent.com/2385329/175528345-4fab9c25-8f1f-4cea-8758-1e54c38f1273.png)

![password](https://user-images.githubusercontent.com/2385329/175528362-a5dfda8a-ed8a-4291-8969-8febeee2513f.png)

It:
- Changes the menu items from local tasks (tabs) to normal menu items
- Adds 'reset' and 'register' links to the login form
- Adds 'login' link to the reset form
- Doesn't add anything to the register form since that already has a Cancel link that seems to take you to the login form anyway
- Removes the custom Login link from the User Account menu

That last point is due to the fact that now that the links are normal menu items, they're added to the menu automatically. So there were duplicate login links.
But the issue is that the new links are added as children of the My Account link, whereas the Log Out link isn't (presumably because it's a menu callback).
![image](https://user-images.githubusercontent.com/2385329/175528266-09b90d15-a1f9-41ff-9711-e5343c930eec.png)
Not sure how to fix that. Assistance welcome.

**Comment by BWPanda** [comment] 2022-06-24 11:50
And if you have user registrations enabled:

![image](https://user-images.githubusercontent.com/2385329/175528666-426a7e19-4057-4d5a-92e5-6c7dc48115ed.png)

**Comment by indigoxela** [comment] 2022-06-24 13:57
I have no clear example, but what worries me a bit is the possible impact for contrib module that provide alternative login methods (like SAML or LDAP).

We should check in advance, if this change (to a different type in hook_menu) can have side effects for these modules.

**Comment by kiamlaluno** [comment] 2024-01-23 21:36
If the impact for contributed modules would be "negative," this could eventually done in Backdrop 2.x.  
I agree that, in this case, a link to reset the password makes more sense than a separate tag, although I can understand that, with a tab, there is still a link users click. (The difference is how that link is rendered.)

**Comment by klonos** [comment] 2024-05-13 20:06
Just throwing this out there as well: https://www.drupal.org/project/gin_login is a "companion" module for the new Drupal core admin theme Claro, as well as for the Gin admin theme which is getting fast adoption in the community. It changes the login screen to this:

![image](https://github.com/backdrop/backdrop-issues/assets/2423362/f878453c-6ad0-4b18-bfc9-0dfaa2d92ac4)

I believe that the images to the right are randomized/rotated, but we don't have to do anything like that - the simplified login form with links instead of tabs is the point which is relevant to this issue here.

**Comment by docwilmot** [comment] 2024-05-13 22:02
Could this be a setting? Then we could implement easily in 1.x. Like "Use consolidated login page" or such.

**Comment by klonos** [comment] 2024-05-13 22:42
I had a similar thought @docwilmot 👍🏼 ...I was thinking a bit more broadly though (having #4167 in mind etc.), but the gist of my thought was more or less the same. I was specifically considering if there was a way to do the following:
- new sites get the new type of login form
- old sites get the old style
- figure out if there's a way for existing contrib/custom themes do declare (in)compatibility with the new style of the login form.

**Comment by docwilmot** [comment] 2024-05-14 01:21
This is a start, copied from @bwpanda's PR. Got guests just as I pushed this so explanations later.

**Comment by herbdool** [comment] 2024-05-14 03:35
I think we could just make the change. I haven't seen anyone provide actual examples of where it'll break themes or ldap modules. I took a look at https://github.com/backdrop-contrib/ldap_sso/blob/1.x-2.x/ldap_sso.module and I think it would fine.

Let's do it for 1.29.0!

**Comment by klonos** [comment] 2024-05-14 06:13
Thanks @docwilmot 🙏🏼 ...you beat me to it 🙂 

This is looking promising 👍🏼 (the login link missing aside and all)

Perhaps we could add a setting for all themes, make the default be turned off, and then in 2.x we could switch to this being the only option for everyone (without any UI setting).

Eventually, I would like us to make the login a proper "pageless" page, without a header, navigation menu, breadcrumb etc. ...I think that we had an issue for that, but can't find it now to link to.

**Comment by docwilmot** [comment] 2024-05-18 15:41
Updated PR:

- [ ] Fixed missing login link in Account menu
- [ ] Added UI for changing to no tabs (now under `admin/config/people/login`)
- [ ] Added option to suppress layout on the login page
- [ ] Page title missing on the suppressed page (title usually provided by layout)
- [ ] Messages missing for same page (same reason)
- [ ] Suppress layout on password reset and new account page?
- [ ] Fix tests

**Comment by klonos** [comment] 2024-05-18 23:47
Thanks @docwilmot 🙏🏼 ...I realize it's still WIP, but it is looking awesome! ...well, it's actually looking rather "plain" at the moment, but perhaps it'll be different with the "Log in" title added back.

I think that caches should be cleared in the submit handler when the settings we are adding as part of this feature change. As it is now, you need to manually clear caches, otherwise what is configured appears to "not work" (those that are used to clearing caches in Drupal/Backdrop for everything will figure that out, but we should try to make this work seamlessly ...and clearing specific caches instead of everything if possible).

We can also consider the following:
- Adding the site/Backdrop logo (which can serve as a "home" link as well, since we are removing the breadcrumb)
- Add an option in `admin/appearance` to allow using the admin theme in the login form.
- Style the form to be inside some frame. If Seven is used as the theme, then we can use the same styling as the pages used in the installer and update.php (which I personally also like for the fact that it has the little folded corner to hint that this is Backdrop).

All these can be separate follow-ups, but mentioning them here in case we want to deliver a more complete thing as part of this feature here.

**Comment by docwilmot** [comment] 2024-05-19 01:35
Made it less plain 🙂 
> what is configured appears to "not work" 

Could you please give STR for this? I'm not getting anything needing cache clearing
> Add an option in admin/appearance to allow using the admin theme 

We by default don't use admin theme for anonymous though, which is everyone before login.
> same styling as the pages used in the installer and update.php 

Did consider this, but thought should get some opinions on how the page should look first. We can see how other opinions go?

**Comment by klonos** [comment] 2024-05-19 04:30
>Made it less plain 🙂

It is less plain indeed 😅 ...thanks for adding the page title in 👍🏼 🙏🏼 

> Could you please give STR for this? I'm not getting anything needing cache clearing

Pretty simply actually:
1. Logged in as an admin, switch from no tabs to using tabs in `admin/config/people/login` and save.
2. Launch the site as anonymous in a different browser or private browser window -> visit the login page -> page still shows no tabs 👎🏼 
3. Back to the session as admin clear caches.
4. Back to the anon session -> refresh -> tabs are no back (but they should be available w/o having to clear caches and refresh the page)

> We by default don't use admin theme for anonymous though ...

That's right 👍🏼 ...I've filed #6560 to explore this further and avoid derailing this issue here.

> Did consider this, but thought should get some opinions on how the page should look first. We can see how other opinions go?

Absolutely! ...just wanted to be the first to express my opinion 😅

**Comment by herbdool** [comment] 2024-05-19 10:41
The scope seems to keep expanding but we'll see where this goes. It mostly looks okay but some issues so far. 

- Doesn't look good on mobile. The width isn't responsive.
- I still don't see a title for the login page. 
- If I choose to display tabs and hide regions, it doesn't seem to work. I'm not sure why someone would want that combo.
- It's a bit jarring to have a plain view for the login but then goes back to regular regions for the request password and register pages. 
- There should be a link on the register page back to login too.

@klonos  there's already an old issue about using the admin theme for the login page. I can't recall what number.

**Comment by klonos** [comment] 2024-05-19 11:10
> I still don't see a title for the login page.

This is from the PR sandbox:
<img width="652" alt="image" src="https://github.com/backdrop/backdrop-issues/assets/2423362/76731f90-cd18-4d93-a118-9acc4fdbb224">

> ...there's already an old issue about using the admin theme for the login page. I can't recall what number.

You are right @herbdool ...I thought that it was the same as this request here, but it is not: #4410

**Comment by herbdool** [comment] 2024-05-19 11:20
Right. I was thinking of a logo or something. It could use something to indicate the website. Or leave that up to the site builder? Can blocks still be added to main region?

**Comment by klonos** [comment] 2024-05-19 12:07
> I was thinking of a logo or something. It could use something to indicate the website.

Yes 👍🏼 ...I also requested that:

> - Adding the site/Backdrop logo (which can serve as a "home" link as well, since we are removing the breadcrumb)

> Can blocks still be added to main region?

It was possible before (tested by adding a custom block with some test text in the default layout), but doesn't work now when the `Hide layout regions` setting is enabled. Disabling that setting and clearing caches renders any block previously added. I guess that this qualifies as a regression, so @docwilmot can we please make it so that that setting only suppresses blocks that aren't in the same region as the `main content` block? ...or at least the region that is defined as `default region` in the .info file of the layout template being used?

**Comment by docwilmot** [comment] 2024-05-19 17:16
> The scope seems to keep expanding but we'll see where this goes.

I didn't think it's expanded that much; the only new thing is removing layout regions, which seemed like a natural expansion of the initial scope, but I could roll that back if its too much.

**Comment by docwilmot** [comment] 2024-05-23 03:07
> I guess that this qualifies as a regression, so @docwilmot can we please make it so that that setting only suppresses blocks ...

The code we're using here literally does not use the Layout system at all. It would render the form, thats all. Blocks, layouts, regions, none of those exist if suppressing layouts. 

What youre asking here is to only display the region the main content block is in. If we don't supply a custom layout for the login/register pages, then I dont know of any way to prevent other regions from displaying, while allowing whichever region the main content block is in to continue to display currently. 
> If I choose to display tabs and hide regions, it doesn't seem to work. I'm not sure why someone would want that combo.

If added `states` to the login page settings, and description to make it clear you can only suppress layouts if not using tabs. Which is true because tabs are a function of the layout template.
> It's a bit jarring to have a plain view for the login but then goes back to regular regions for the request password and register pages.
There should be a link on the register page back to login too.

Both added
> Launch the site as anonymous in a different browser or private browser window -> visit the login page -> page still shows no tabs 👎🏼

Thanks, confirmed, will fix, once I figure which cache to clear 🙁

**Comment by herbdool** [comment] 2024-05-23 03:32
Thanks @docwilmot.

I checked again. How come it seems like the regions are surpressed even if that setting is disabled?

**Comment by docwilmot** [comment] 2024-05-23 13:12
> I checked again. How come it seems like the regions are surpressed even if that setting is disabled?

Caches?
I'm actually having a hard time figuring this out. The settings only stick if you either save the user settings form twice, or flush caches after saving. I've tried adding an additional submit function to the user settings form and running all sorts of cache clearing scenarios, and none seem to work. Stumped, hopefully temporarily.

**Comment by herbdool** [comment] 2024-05-23 17:57
Actually it's a bit odder than that. It doesn't happen consistently. Sometimes it works, sometimes not. And I've been clearing the cache each time.

**Comment by herbdool** [comment] 2024-05-23 18:21
I think even with regions suppressed it should still load the `grid-*.css` files (and `grid-fallback.js`) and the user login form should be wrapped in `container`, `row` and `col-md-*` so that it still follows the same approach as theming the rest of the site. And we should include some css for Basis as well if this PR is merged.

I'm not convinced yet of this approach to simplifying the login (aside from removing the tabs). I know there's another issue that got bogged down when trying to create layouts for the login pages - a problem with getting the context for /user/login, etc I think? But if this issue gets bogged down, then I may lean towards splitting the "Hide layout regions" part to a separate issue and merging them separately. I have reservations. But for now let's see where the discussion carries us.

**Comment by docwilmot** [comment] 2024-05-24 01:43
I think the caching issues should be sorted now.
> I'm not convinced yet of this approach to simplifying the login

To simplify the login page (apart from removing the tabs):
1. ship with 3 layouts for the `user/**` paths; no header or nav or sidebars, just a content region. This would ideally need a new template that more suits the styles of the sample simple login pages above. The advantage is you can add blocks to it. Disadvantage its harder for themes to modify.
2. add code to Layout for suppressing the other regions on the `user/**` paths. May be slightly confusing in case someone actually wants sidebars etc. Somehow doesnt seem palatable to me, though I have no obvious reasons.
3. suppress the layout and add a template to override if needed, as in this PR. Theme it consistently; all Backdrop sites have a similar login page, just like WP does. Themes can have customized login pages if they supply their own template. Disadvantage you cant add blocks, you'd have to use a template file. Not sure how many users would need login page blocks TBH.

I think suppressing the layout seems the cleanest method of doing this. I think I'll leave the code in, we've got 4 more months to ruminate over the options anyway.

> I think even with regions suppressed it should still load the grid-*.css files...etc

Agreed, this can be added if we finally include the suppress code.

**Comment by indigoxela** [comment] 2024-05-24 06:02
I know, I'm too late here, but all the time this issue went on (and the scope shifted) I asked myself: is this really an 80% use-case? Isn't that just a contrib candidate?
And if this completely bypasses the Layout system, it's no longer possible to add custom blocks to the page. Isn't that actually a regression?

**Comment by klonos** [comment] 2024-05-24 08:52
> ...and assume the "Test Test Test" string is just a temporary place holder.

That was me. Sorry. I was testing what happens if you try to add a custom text block to the various regions in the default layout ...turns out that you cannot add any block on any other region - just on the default region with the "main content" block ...or rather you can add it, blocks on the other regions, but they won't show up in the login pages.

> Thanks, confirmed, will fix, once I figure which cache to clear 🙁 ...I've tried adding an additional submit function to the user settings form and running all sorts of cache clearing scenarios, and none seem to work. Stumped, hopefully temporarily.

Thanks for working on that @docwilmot 🙏🏼 ...I believe that we are doing something similar with cache clearing when we switch themes under `admin/appearance`. Did you have a look at that?

> While trying to keep an eye on this issue to understand what the design is aiming to be I noticed this related issue: https://github.com/backdrop/backdrop-issues/issues/4410

Yup. I have mentioned it a few times in this thread already. I like to be cross-liking relevant issues that way 😉 (although I wish that GitHub allowed to do that in a more structured way, and show relevant issues in the sidebar, like it shows linked PRs etc.)

> ... I know there's another issue that got bogged down when trying to create layouts for the login pages - a problem with getting the context for /user/login, etc I think?

I suggested that in this issue here, [back in March 2019](https://github.com/backdrop/backdrop-issues/issues/3309#issuecomment-469480480) and then again [in May 2019](https://github.com/backdrop/backdrop-issues/issues/3309#issuecomment-494188963), but it was shot down and we never actually created any separate issue for it.

**Comment by klonos** [comment] 2024-05-24 10:42
@docwilmot I love this! Thank you for your time and effort on this.

Can we please use `0.25rem solid #bbbbbc` for the border in the login page? It is the same as the horizontal line used in the top-border of the footer in Basis (where Drop the dragon is sitting):
<img src="https://github.com/backdrop/backdrop-issues/assets/2423362/7dbbb63a-7c01-41d7-ac2f-9d4191ad9433" width=50%>
...I tried to find any other borders used in blocks etc. in Basis that we could mimic, but couldn't find anything else.

If I was to suggest further styling for the login pages in Basis, then it would be to consider wrapping the h1 site name in a div, and styling it similarly to the header in Basis:
<img width="50%" src="https://github.com/backdrop/backdrop-issues/assets/2423362/82eb50ef-054b-4a0b-88ed-21253bf0e9f1">

...we could add the same background pattern as the one used in the hero block:
<img width="50%" src="https://github.com/backdrop/backdrop-issues/assets/2423362/b62babc5-32eb-4537-9f22-813d6774e170">

...or make it plain black/white if people think it's "too much":
<img width="50%" src="https://github.com/backdrop/backdrop-issues/assets/2423362/7cbc5a2c-d2ed-4b9c-b9e0-498948490ceb">

In general, I am looking for more consistency with the Basis theme.

I have some ideas for the setting form/UI for this as well. Coming up in a separate comment...

**Comment by olafgrabienski** [comment] 2024-05-24 11:19
> And if this completely bypasses the Layout system, it's no longer possible to add custom blocks to the page. Isn't that actually a regression?

I was also skeptical if this is too much, but then I saw the "Hide layout regions" setting. If it's disabled, the layout seems to work as usual.

@docwilmot In the PR sandbox I saw the elements on the `user/register` page are too wide (full screen width).

**Comment by klonos** [comment] 2024-05-24 11:34
...this is what I had in mind for the settings UI:
![image](https://github.com/backdrop/backdrop-issues/assets/2423362/923a8d59-0461-4e49-85b7-4b4df815ebe8)

The wording in labels and help texts needs further thought/improvement, however the current "Use tabs" and "Hide regions" are too techie and don't sound like a new feature. They also do not explicitly convey what you get before/after.

**Comment by docwilmot** [comment] 2024-05-24 15:28
> Isn't that just a contrib candidate?

@indigoxela yes, it probably is. I added the code for the "simplified" login page to the code since there were several mentions/screenshots of similar styles before my PR, so I thought this was likely to be wanted. And *if* we do want this "simplified" login page in this PR, I explained [here](https://github.com/backdrop/backdrop-issues/issues/3309#issuecomment-2128334770) why suppressing the layout seems the way to do it. 

I am happy to strip that "simplified login page" code out and just leave the original scope of removing tabs if this is preferred.

As a matter of fact I think I'll do just that and open a separate issue for deciding re the "simplified" login pages.

**Comment by klonos** [comment] 2024-05-24 20:45
> ... There's also `user/reset/*` in core, and `system/tfa/*` with TFA which should have the same look and feel as the login workflow ...

The PR adds this code:

```php
if ($current_path == 'user/login' || $current_path == 'user/password' || $current_path == 'user/register') {
```

In the PR comments I suggested that we should define these paths in something similar to `path_is_admin()`? ...something like `path_is_login()`. Aso introduce `path_get_login_paths()` to match `path_get_admin_paths()`, as well as `hook_login_paths()`/`hook_login_paths_alter()` to match `hook_admin_paths()`/`hook_admin_paths_alter()`.


That should make it easier for custom/contrib to be able to hook into any logic we have around the theming of the login section.

**Comment by docwilmot** [comment] 2024-05-25 18:46
Back to basics.

**Comment by klonos** [comment] 2024-05-25 21:29
Thanks again @docwilmot 🙏🏼 (and for keeping the original PR 👍🏼 )

There's a typo in the word `passord` (missing w), which was carried across from the other PR.

I left a couple of suggestions in the new PR for the settings form introduced by this:
- convert the single checkbox with the rather lengthy help text that explains what happens when ticked vs. when unticked into a radio set with two distinct options instead.
- add only a small part of the help text (the bit that explains what these setting will affect) to the container fieldset.

Before/after screenshot:
![image](https://github.com/backdrop/backdrop-issues/assets/2423362/be426e90-c258-412c-9843-6364be686d59)

Lets also please move the entire fieldset higher up this form, right after the "User login" fieldset (the rest of the settings in the form are all about failed login attempts, and I am proposing to group them together and collapse them in #6567).

**Comment by bugfolder** [comment] 2024-05-25 22:29
> add only a small part of the help text (the bit that explains what these setting will affect) to the container fieldset.

[Wouldn't it be great if there were an easy way to add expandable additional help text?](https://github.com/backdrop/backdrop-issues/issues/5090)

**Comment by herbdool** [comment] 2024-05-26 02:38
@klonos suggestion for setting UI is an improvement.

Though I'm still of the mind that we probably don't need to make it optional. Just make the change for everyone. I don't think anyone has yet pointed out a module that relies on them being tabs. There's only been speculation.

**Comment by indigoxela** [comment] 2024-05-26 05:19
> Though I'm still of the mind that we probably don't need to make it optional. Just make the change for everyone.

While this would simplify the task here, I don't think we can do that, with regards to backwards compatibility.
We can't just change the way the login/password/register pages look like for existing sites, as that might lead to lots of irritation.

**Comment by indigoxela** [comment] 2024-05-26 05:57
Some testing in the sandbox...
Works like a charm, and I'm happy, that we're back to the initial scope.

One thing I tested, is to add a tab after login tabs via views (Path: /user/thetab), which displays, when tabs are enabled, but doesn't display at all, if not. I guess, that's how it's supposed to work, but made me think, what happens to modules, that add such a tab. Would that break, too?

**Comment by herbdool** [comment] 2024-05-27 17:00
Some minor code fixes. Tested and it works fine. I'm not worried about if something adds a tab to the login tabs. I have a hard time thinking of a case where I've seen that, or why there might be one. Plus it seems like people want to keep this as an option so someone can still go back to tabs if needed.

**Comment by stpaultim** [comment] 2024-06-06 21:30
The "Needs Work" label was added back in 2022. @herbdool removed and added it back about two weeks ago. We're not entirely sure if that was intentional. 

Is this PR ready for code review OR does it still "need work?"

**Comment by docwilmot** [comment] 2024-12-01 17:50
PR refreshed. Its a bit confusing between this issue to remove tabs and https://github.com/backdrop/backdrop-issues/issues/6570 which is to simplify the login page. I've refreshed both, but I don't remember which direction we were leaning towards, TBH.

**Comment by stpaultim** [comment] 2024-12-02 09:58
> Edit: also, can we get a milestone?

The process for adding an issue to the minor release milestone is to find an advocate. Do you want to advocate for this?
https://docs.backdropcms.org/documentation/adding-milestones-to-issues

**Comment by docwilmot** [comment] 2024-12-07 17:50
> Its a bit confusing between this issue to remove tabs and https://github.com/backdrop/backdrop-issues/issues/6570 which is to simplify the login page

FYI having revisited the code, https://github.com/backdrop/backdrop-issues/issues/6570 does what this PR does (adds a setting to remove tabs, or not), as well as simplifying the login page. So if we merge https://github.com/backdrop/backdrop-issues/issues/6570, this issue becomes moot, and can be closed.
> The process for adding an issue to the minor release milestone is to find an advocate. Do you want to advocate for this?

I'd prefer to advocate for the other issue, https://github.com/backdrop/backdrop-issues/issues/6570, but according to what I've just mentioned, seems I might as well advocate for both.

**Comment by quicksketch** [comment] 2024-12-27 00:49
This issue is superseded by https://github.com/backdrop/backdrop-issues/issues/6570. As that issue seems to be moving and very likely for 1.30.0, let's close this issue.

**Closed** 2024-12-27 00:49 UTC
Labels: type - feature request, status - has pull request, design, pr - needs work, pr - needs code review, pr - works for me, milestone candidate - minor
