### ISSUE TITLE
Fix extraneous gray stripe left over when removing Cards grid.

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#5599] opened 2022-04-27 11:39 UTC
## Description of the bug

When you remove the new Cards grid (introduced in #4903) from the Home page, a gray stripe remains.

## Steps To Reproduce

To reproduce the behavior:
1. Go to the Home page, and make sure there is the Card grid.
2. Remove the Card grid by disabling the block or the views display.
3. Return to the Home page.

## Actual behavior

There is a gray stripe below the hero block:

![backdrop-cards-remove-block](https://user-images.githubusercontent.com/14188307/165509768-6c56e09f-2c6a-4290-a7d2-93a4fcdbe1b6.png)

## Expected behavior

No gray stripe (this happens btw as expected, if you unpublish the Card content instead of removing the block):

![backdrop-cards-unpublish-content](https://user-images.githubusercontent.com/14188307/165509781-b0fcbab6-65c8-4913-b737-43b3b8cc55db.png)

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: Dev as of 27 april 2022

**Comment by indigoxela** [comment] 2022-04-27 11:51
Only in Basis, I guess...

Hm, that's probably caused by the messages block. @olafgrabienski do you always see the stripe, or only after messages appeared and you dismissed them?

**Comment by olafgrabienski** [comment] 2022-04-27 13:20
> that's probably caused by the messages block

Ha, indeed! The stripe is only visible after seeing and dismissing the message which tells me that the block has been removed. I guess, that's acceptable. What do others think?

**Comment by indigoxela** [comment] 2022-04-27 13:31
> The stripe disappears when I reload the page. I guess, that's acceptable. What do others think?

Acceptable - maybe. But it's a bit ugly.

**Comment by stpaultim** [comment] 2022-04-28 04:42
The stripe will come back anytime you clear the cache or anything that triggers a notification, because we moved the notifications into the "Top" region. 

Also, this new background color is going to appear anytime anyone adds something into the TOP region. I don't think we can do this. We will need to either remove the background color OR find a way for it to show up ONLY if the specific view is present. 

BEFORE:

![image](https://user-images.githubusercontent.com/3144571/165677898-054b4ee9-c53e-4c45-996c-334500dc69e9.png)

AFTER:

![image](https://user-images.githubusercontent.com/3144571/165677954-547bb94b-e2d8-4ef6-9197-a531f6aa743e.png)

**Comment by indigoxela** [comment] 2022-04-28 06:33
TBH, personally I find the background color for any block in that region is OK. Only the stripe after dismissing a message is a bit ugly. I see no easy way to fix that, though, because it's actually caused by the hero block margin.

An alternative could be to style the cards to get the background color - probably not optimal.

**Comment by indigoxela** [comment] 2022-04-28 07:04
I belief, we can fix this issue and #5604 at once.

1. Remove the container class from the block
2. Remove the problematic background color css
3. Add the container class to the view
4. Add the background color css very specific only to the block and only if in l-top

**Comment by olafgrabienski** [comment] 2022-04-28 08:54
@indigoxela I've simulated steps 1 to 4 with my browser's dev tools, works nicely! Are you up to file a PR?

**Comment by stpaultim** [comment] 2022-04-28 08:55
I will note, that I'm quite sure that this does not need to be complete by code freeze. We can still fix bugs until May 15th.

**Comment by indigoxela** [comment] 2022-04-28 09:07
> Are you up to file a PR?

Yes I am. Here it is: https://github.com/backdrop/backdrop/pull/4055
I'm curious if I did everything right.

**Comment by stpaultim** [comment] 2022-04-28 09:14
I added this to the 1.22 milestone even thought it's a bug fix, because it's fixing a bug introduced in 1.22.

**Comment by indigoxela** [comment] 2022-04-28 09:15
Now it works: https://github.com/backdrop/backdrop/pull/4055 (removed the right "container" this time :wink:)

Ready for testing and review.

**Comment by olafgrabienski** [comment] 2022-04-28 09:16
> that outer "container" is back.

I guess you removed the class from messages, not from the Cards grid.

**Comment by olafgrabienski** [comment] 2022-04-28 10:08
Many thanks for the PR, works for me!

**Comment by stpaultim** [comment] 2022-04-29 05:32
I think that this PR is simple enough for me to mark it RTBC. It all seems very straightforward.

**Comment by quicksketch** [comment] 2022-04-29 23:38
Thanks @indigoxela, @stpaultim, and @olafgrabienski! Merged https://github.com/backdrop/backdrop/pull/4055 into 1.x for 1.22.0.

**Closed** 2022-04-29 23:38 UTC
Labels: status - fixed
