### ISSUE TITLE
Regression in text filter format overview submit when disabled formats exist

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4419] opened 2020-05-24 10:36 UTC
**Description of the bug**

When at least one format is disabled and the filter format overview form gets submitted (changing the weight of a format), an additional _empty_ format gets created, causing several php notices and warnings.

**Steps To Reproduce**

To reproduce the behavior:
1. Add a format
2. Disable that format
3. Go to admin/config/content/formats, (reorder), submit

**Actual behavior**

```
    Notice: Undefined index: aaanotherformat in filter_admin_overview_submit() (line 114 of ...core/modules/filter/filter.admin.inc).
    Notice: Trying to get property 'weight' of non-object in filter_admin_overview_submit() (line 114 of ...core/modules/filter/filter.admin.inc).
    Warning: Creating default object from empty value in filter_admin_overview_submit() (line 116 of ...core/modules/filter/filter.admin.inc).
    Notice: Undefined property: stdClass::$name in filter_format_build_format() (line 293 of ...core/modules/filter/filter.module).
    Notice: Undefined property: stdClass::$format in filter_format_save() (line 362 of ...core/modules/filter/filter.module).
    Notice: Undefined property: stdClass::$format in filter_formats() (line 797 of ...core/modules/filter/filter.module).
    Notice: Undefined property: stdClass::$format in filter_formats() (line 808 of ...core/modules/filter/filter.module).
    Notice: Undefined property: stdClass::$format in filter_admin_overview() (line 61 of ...core/modules/filter/filter.admin.inc).
    Notice: Undefined property: stdClass::$format in filter_get_roles_by_format() (line 923 of ...core/modules/filter/filter.module).
```

You might have guessed: "aaanotherformat" is the name of the disabled one.

Additionally a new file gets created in config directory: `filter.format..json`
With this content:
```
{
    "_config_name": "filter.format.",
    "weight": "0",
    "name": "",
    "cache": true,
    "status": 1,
    "editor": null,
    "filters": []
}
```

**Additional information**

This popped up while I was trying to figure out a possible solution for another (unrelated) Issue but it's reproducible on a different install.

Both have php 7.2, one is the latest dev (git).

Deleting that additional broken filter config file and enabling the filter via UI and then deleting the newly created broken filter config again "solves" the problem. At least the notices go away and no additional config files get created (as long as there's no disabled format).

**Comment by indigoxela** [comment] 2020-05-24 12:07
Crazy, the fix is a one-liner...

The trick is to get the _same_ filter list in both, function filter_admin_overview() and function filter_admin_overview_submit(). If that's not the case, disabled ones create empty formats on submission as they exist in `$form_state['values']`.

To test the [PR](https://github.com/backdrop/backdrop/pull/3151) follow the instructions in the Issue description.

**Comment by herbdool** [comment] 2020-05-24 14:52
Tested and reviewed

**Comment by jenlampton** [comment] 2020-05-28 20:50
Is this a duplicate of https://github.com/backdrop/backdrop-issues/issues/4407?

**Comment by indigoxela** [comment] 2020-05-29 06:17
> Is this a duplicate of #4407?

No, it's unrelated. There's no solution yet for the other issue.

**Closed** 2020-06-04 20:00 UTC
Labels: pr - ready to be committed, pr - works for me, status - has pull request, type - bug report

**Comment by quicksketch** [comment] 2020-06-04 20:02
Thanks! Merged https://github.com/backdrop/backdrop/pull/3151 into 1.x and 1.16.x.
