### ISSUE TITLE
User error: "theme" is an invalid render array key in element_children()

### ISSUE THREAD

**Issue by findlabnet** [backdrop/backdrop-issues#3776] opened 2019-05-13 14:53 UTC
**Description of the bug**
PHP user error when disabling any enabled theme (5 records for each event):
`User error: "theme" is an invalid render array key in element_children() (line 7207 of /<document_root>/core/includes/common.inc)`

**Steps To Reproduce**
1. Go to 'admin/appearance'
2. Click on 'Disable' link of any enabled theme

**Additional information**
- Backdrop CMS version: 1.12.6 and later
- Seems like bug was added with changes in 'system' module due https://github.com/backdrop/backdrop/pull/2507

---
PR (credits to @findlabnet): https://github.com/backdrop/backdrop/pull/2719

**Comment by findlabnet** [comment] 2019-06-02 09:39
To prevent this bunch of errors we can pass theme name by using hidden field,
so in the file `core/modules/system/system.admin.inc`:

line 293:
instead of `$form['theme'] = $_REQUEST['theme'];`
should be `$form['theme'] = array('#type' => 'hidden', '#value' => $_REQUEST['theme']);`

line 305
instead of `$theme = $form_state['complete_form']['theme'];`
should be `$theme = $form_state['complete_form']['theme']["#value"];`

**Comment by klonos** [comment] 2019-06-02 10:57
Thanks @findlabnet 👍 ...I was able to reproduce this bug in 1.14.x-dev

I have filed a PR with your suggested fix: https://github.com/backdrop/backdrop/pull/2719 ...I have tested in the PR sandbox, and the problem is indeed fixed (plus tests a green) ...but I will leave someone else to RTBC this.

**Comment by findlabnet** [comment] 2019-06-02 11:02
Thanks @klonos I have tested in the PR sandbox too, commented PR.

**Comment by quicksketch** [comment] 2019-08-04 19:31
Thanks @klonos and @findlabnet (and @drupol who did a code review)! Merged https://github.com/backdrop/backdrop/pull/2719 into 1.x and 1.13.x.

**Closed by quicksketch** 2019-08-04 19:31 UTC
Labels: pr - needs code review, pr - works for me, status - has pull request, type - bug report
