### ISSUE TITLE
Deprecated function: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in mb_strlen() (line 479 of ../unicode.inc)

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#5890] opened 2022-12-17 20:59 UTC
## Description of the bug

In certain conditions the deprecated function error in subject is triggered. 

## Steps To Reproduce

Not clear how to reproduce this - I'll update if it comes up again - but the last time I caught this was a combination of a custom module being ported and Devel module. In particular, the error was caused by a call from `/var/www/html/docroot/modules/devel/devel.module line 1232`  which is the` krumo($object);` and the whole function is:

```
function krumo_ob($object) {
  ob_start();
  krumo($object);
  $output = ob_get_contents();
  ob_end_clean();
  return $output;
}
```

The [line](https://github.com/backdrop/backdrop/blob/c27cd94ff25f633d5a9903abf0085f6f1c0724f6/core/includes/unicode.inc#L479) in the subject is `return mb_strlen($text);` and the whole function is:

```
function backdrop_strlen($text) {
  global $multibyte;
  if ($multibyte == UNICODE_MULTIBYTE) {
    return mb_strlen($text);
  }
  else {
    // Do not count UTF-8 continuation bytes.
    return strlen(preg_replace("/[\x80-\xBF]/", '', $text));
  }
}
```

## Additional information

This kind of errors started to flow in with projects switching to PHP 8.1. I believe the same error was reported on https://www.drupal.org/project/feeds/issues/3266703 with the patch offered on https://www.drupal.org/files/issues/2022-02-26/core_unicode_deprecated.patch, but the issue itself being marked as duplicate of https://www.drupal.org/project/feeds/issues/3266704

Wanted to offer a PR using the null coalescing operator as suggested on https://stackoverflow.com/questions/71707325/migration-to-php-8-1-how-to-fix-deprecated-passing-null-to-parameter-error-r, but then because of potential comparability issues decided to hear from the community on what would be the best way of addressing this issue.

**Comment by alanmels** [comment] 2022-12-17 21:00
This article explains the issue in details: https://php.watch/versions/8.1/internal-func-non-nullable-null-deprecation

**Comment by kiamlaluno** [comment] 2022-12-17 21:21
The null coalescing operator isn't available on PHP 5.6. A fix that works on PHP 5.6 is casting the value passed to `mb_strlen()` to `string`, or checking that value isn't `NULL` before passing it to `mb_strlen()`.

**Comment by kiamlaluno** [comment] 2022-12-18 09:55
Also the third parameter for preg_replace() isn't nullable, which means that even `strlen(preg_replace("/[\x80-\xBF]/", '', NULL))` would throw an exception, on PHP 8.1. The following code would avoid that exception and casting `$string` in two different lines.

```php
function backdrop_strlen($text) {
  global $multibyte;
  if (!isset($text)) {
    return 0;
  }
  if ($multibyte == UNICODE_MULTIBYTE) {
    return mb_strlen($text);
  }
  else {
    // Do not count UTF-8 continuation bytes.
    return strlen(preg_replace("/[\x80-\xBF]/", '', $text));
  }
}
```

**Comment by alanmels** [comment] 2022-12-18 13:00
@kiamlaluno You did all the work, so why don't you also create a PR?

**Comment by klonos** [comment] 2022-12-21 15:06
Thanks @alanmels for reporting this, and for the initial investigation, and thank you @kiamlaluno for the solution and the PR. The PR seems simple and straight-forward to me, so I'm RTBC'ing this. I guess that whenever contrib or core needs to use `mb_strlen()` we should be using `backdrop_strlen()`, which with this fix will not be trowing deprecation warnings/errors in PHP 8.1+.

**Comment by klonos** [comment] 2022-12-21 15:11
...it seems that in core we are already using `backdrop_strlen()` everywhere except in https://github.com/backdrop/backdrop/blob/c27cd94ff25f633d5a9903abf0085f6f1c0724f6/core/includes/unicode.inc#LL107C21-L107C21

**Comment by kiamlaluno** [comment] 2022-12-21 16:12
@klonos Does that link point to `_unicode_check()`?

**Comment by quicksketch** [comment] 2023-01-09 00:25
@klonos Do you mean we're using it everywhere except for these lines in unicode.inc? This seems to be the section you referenced:

```
  // Check for mbstring extension
  if (!function_exists('mb_strlen')) {
    return array(UNICODE_SINGLEBYTE, $t('Operations on Unicode strings are emulated on a best-effort basis. Install the <a href="@url">PHP mbstring extension</a> for improved Unicode support.', array('@url' => 'http://www.php.net/mbstring')));
  }
```

Which definitely should continue to check for `mb_strlen` and leave as-is. It doesn't call it; it just confirms whether it exists.

**Comment by quicksketch** [comment] 2023-01-09 00:34
I'm not sure about the solution in the (PR https://github.com/backdrop/backdrop/pull/4285). From the description in the original report, this does not seem to affect core directly but rather only some contrib modules; which only occurs on PHP 8.1+. The referenced issues in Feeds module suggest this was fixed by the contrib modules in Drupal.

We could pursue the same solution Backdrop: contrib modules must always pass a string to `mb_strlen()` (NULL is not allowed). On the other hand, if we do decide to make the suggested change, then that implies that we should provide the same check for _all_ `mb_*` wrapper functions, including:

* `backdrop_strtoupper()`
* `backdrop_strtolower()`
* `backdrop_substr()`

Either way this probably needs more discussion.

**Comment by kiamlaluno** [comment] 2023-01-09 08:26
If Backdrop core code never passes `NULL` to `backdrop_strlen()`, I would at least change the documentation comment for `backdrop_strlen()` to hint its first argument to `string`. At least, developer's tools should warn them about passing `NULL` to a function that expects a string.

The only way to be sure that `backdrop_strlen()` always get a string would be to use the following code, which runs on PHP 7, not PHP 5.6.

```php
function backdrop_strlen(string $text) {
  global $multibyte;
  if ($multibyte == UNICODE_MULTIBYTE) {
    return mb_strlen($text);
  }
  else {
    // Do not count UTF-8 continuation bytes.
    return strlen(preg_replace("/[\x80-\xBF]/", '', $text));
  }
}
```

Since that isn't yet possible (without stopping to support PHP 5.6, which is indeed something we probably don't want), if the issue isn't from Backdrop core code, the only possibility is better documenting the function parameters.

**Comment by klonos** [comment] 2023-01-10 11:39
> Which definitely should continue to check for `mb_strlen` and leave as-is. It doesn't call it; it just confirms whether it exists.

You're right 👍🏼  ...of course. I simply did a search across our codebase - didn't check the actual code or the function calling it.

@kiamlaluno I don't see anything wrong with type hinting - as you say, at least people will get a useful error when trying to pass NULL or anything other than a string. Not sure what you mean "which runs on PHP 7, not PHP 5.6." though.

**Comment by kiamlaluno** [comment] 2023-01-10 12:16
@klonos That is referred to the following code, shown in my previous comment.

```php
function backdrop_strlen(string $text) {
  global $multibyte;
  if ($multibyte == UNICODE_MULTIBYTE) {
    return mb_strlen($text);
  }
  else {
    // Do not count UTF-8 continuation bytes.
    return strlen(preg_replace("/[\x80-\xBF]/", '', $text));
  }
}
```

Calling `backdrop_strlen("Random string")` with that definition would cause the following error, in PHP 5.6.

> Catchable fatal error: Argument 1 passed to backdrop_strlen() must be an instance of string, string given.

**Comment by klonos** [comment] 2023-01-10 15:07
> ...that definition would cause the following error, in PHP 5.6...

Huh! ...I didn't know that type hinting could cause errors in php 5.6 🤔

**Comment by indigoxela** [comment] 2023-01-10 15:19
@klonos type hinting in php5.x is OK for _array_ and _object_, but not for string. I think, that came with php 7, but am not really sure.

**Comment by indigoxela** [comment] 2023-01-10 16:10
> Yup, that's what I said

... after I got the email with original comment, which didn't contain that info. Nevermind. :smile:

**Comment by kiamlaluno** [comment] 2023-01-10 16:21
The coding standards are failing for /core/modules/system/view/views_handler_field_system_info.inc, which isn't a file my PR changed.

**Comment by klonos** [comment] 2023-01-10 19:55
@kiamlaluno yes, we are having some issues with PHPCS, which is the tool we use to check the code of our PRs. See #5848 and #5893 for example. So I wouldn't worry too much about these failures. You could try closing the PR, waiting for 1min or so, then reopen it. That will run the tests again, and might make these unrelated failures go away.

> ... that implies that we should provide the same check for all `mb_*` wrapper functions ...

@quicksketch does that mean that you would be open to including that code change if this issue here and the respective PR included the same fix for those other 3 functions?

**Comment by quicksketch** [comment] 2023-01-10 21:03
> @quicksketch does that mean that you would be open to including that code change if this issue here and the respective PR included the same fix for those other 3 functions?

Yes, but I'm still not sure that it would be better than fixing the calling code. PHP 8 has required a lot of checking for NULL values being passed to all kinds of functions, so even "fixing" a few places in core will probably still require modules to make other changes for PHP 8 compatibility. I'm inclined to say that as far as backwards-compatibility, Backdrop hasn't changed anything, but PHP did, and accounting for PHP changes is just a part of maintaining PHP-based software.

**Comment by klonos** [comment] 2023-01-10 22:21
Thanks for taking the time to reply @quicksketch ...I'm now reading your previous replies as "I'd rather we did nothing in core unless core is affected or causing these errors, and have contrib deal with these specific php8-related issues instead.". That's fair enough for me, and I've also filed #5920 which would allow us to simply type-hint things and be done with it (but that may take long to decide and make it happen).

In the meantime, while I understand the "ideally contrib should handle this" sentiment from a developer point of view, I would still like to point out that according to https://backdropcms.org/philosophy

> Backdrop values the needs of the contrib developer over the needs of the core developer.

So if we can make things easier for contrib, then we should.

**Comment by klonos** [comment] 2023-01-12 22:49
During this week's dev meeting, we have decided that we should do the following:
- add the same check in all 4 functions (`backdrop_strlen()`/`backdrop_strtoupper()`/`backdrop_strtolower()`/`backdrop_substr()`)
- explicitly check for `is_null()` instead of `!is_string()`
- add a `@todo: remove this in 2.x.` inline comment above each conditional check
- make sure that all `@param` in the docblocks are type-hinted

(if you wanna see the discussion about all that: https://youtu.be/vvzsOmfyIsA?t=1451 )

@kiamlaluno can you please update your PR accordingly? Thanks 🙏🏼

**Comment by kiamlaluno** [comment] 2023-01-13 08:26
@klonos I should have time in three hours, less or more.

**Comment by klonos** [comment] 2023-01-13 18:21
No worries @kiamlaluno 👍🏼 ...ust add a comment here once you've updated the PR.

Hoping to get this is with the upcoming 1.24.0 🤞🏼

**Comment by kiamlaluno** [comment] 2023-01-14 19:32
I changed the PR code.  
The failing test for the coding standards is not caused from code I changed, nor is it for the file I changed.

**Closed** 2023-01-15 01:48 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2023-01-15 01:49
I'm still not 100% on this but I think this is a good compromise. Provide compatibility for now and remove in 2.x. I merged https://github.com/backdrop/backdrop/pull/4285 into 1.x and 1.23.x. Thanks @kiamlaluno, @klonos, @alanmels, and @indigoxela!
