### ISSUE TITLE
[D8][UX] Replace the 'Add role' button with a '+ Add role' action link, and move the `Role name` form to its own page.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2742] opened 2017-06-17 13:32 UTC
## Describe your issue or idea

Throughout the rest of the UI we have changed everything to "+ Add xyz" links, but in the "Roles" page we use a different pattern.

### Steps to reproduce (if reporting a bug)

Navigate to `admin/config/people/roles`

### Actual behavior (if reporting a bug)

![image](https://user-images.githubusercontent.com/2423362/27253282-d157b990-53b4-11e7-85b0-a72549954d98.png)

### Expected behavior (if reporting a bug)

![image](https://user-images.githubusercontent.com/2423362/27253317-56b19c96-53b5-11e7-9c39-48299c454483.png)

**Comment by klonos** [comment] 2017-06-17 13:40
I realize that this is not the only part of the admin UI that we use this pattern. We use something very similar in the "Manage fields" page for content types for example:

![image](https://user-images.githubusercontent.com/2423362/27253334-b69a3956-53b5-11e7-8d5e-00e3af43ea16.png)

...only in that page the button that performs the add action is also the primary submit button for the entire form (also saves the order of fields). Anyways, we have plans to change that form to use a "+ Add field" button: https://github.com/backdrop/backdrop-issues/issues/779

**Comment by jenlampton** [comment] 2017-08-17 19:01
The action link is used when there's a larger form that needs to be filled out, mostly because it "won't fit" as a row in the table. For something like Roles, the only thing we need to add is a name, so it fits nicely. In this case I think adding the extra clicks to add a role name is a UX regression, though I do see your point about consistency. I'm on the fence about this change. (Adding needs feedback tag to get some more opinions)

**Comment by BWPanda** [comment] 2021-01-22 02:50
I support this idea. Especially since I just requested the same for the Manage Fields page: https://github.com/backdrop/backdrop-issues/issues/4898

**Comment by BWPanda** [comment] 2021-01-22 10:37
In preparation for doing this for the Manage Fields page, I thought I'd try a slightly easier one first 😄  So here's a PR: https://github.com/backdrop/backdrop/pull/3510

**Comment by BWPanda** [comment] 2021-01-22 10:38
Because of the significant UI changes involved here, I'd be happy to see this go into the next *minor* release, as opposed to a *bug fix* release. But see how others feel...

**Comment by BWPanda** [comment] 2021-01-22 10:41
Here's how it looks:

![image](https://user-images.githubusercontent.com/2385329/105480784-45f20380-5cfa-11eb-9a7d-f1ed8c05f230.png)

![image](https://user-images.githubusercontent.com/2385329/105480820-5609e300-5cfa-11eb-829e-987bfa90e6f3.png)

**Comment by docwilmot** [comment] 2021-01-22 15:25
This could work well as a dialog. But then it would be inconsistent with the rest of core again. 🤷

**Comment by klonos** [comment] 2021-01-22 19:33
I feel that this is another baby step towards consistency/standardization in the UI 👍  ...smaller incremental changes done sooner are better than bigger changes that take months/years to be done, I say.

I think that although not a new feature per se, still a substantial UI change, so better to get in with 1.19.0.

**Comment by klonos** [comment] 2021-01-22 19:42
...code looks good, and I like the clean-up. I've also tested this, and it works as expected when adding/editing roles. There are a few test failures though.

**Comment by BWPanda** [comment] 2021-01-22 20:07
@docwilmot I agree that there are probably better ways to do this UI-wise, but like @klonos said, let's make this consistent with the rest of core now, then later can implement dialogs everywhere as necessary.

**Comment by BWPanda** [comment] 2021-01-22 22:20
Also, I believe dialogs require the content of the dialog to be on its own URL...? So this issue is a good first step - moving the 'add' for to its own page.

**Comment by BWPanda** [comment] 2021-01-22 22:21
@klonos PR updated to (hopefully) fix tests.

**Comment by docwilmot** [comment] 2021-01-23 01:18
> Also, I believe dialogs require the content of the dialog to be on its own URL...? So this issue is a good first step - moving the 'add' for to its own page.

Yeah, that's what I meant: since its already on its own page, just a `use-ajax` class on the link would do it. So maybe a new issue after this to AJAXify all the buttons, if that makes sense.

**Comment by BWPanda** [comment] 2021-01-29 01:25
@docwilmot pointed out in the PR that:

> The page title doesnt seem to inherit this title still just says "Roles"

I looked briefly into this, but I'm not sure why it's happening... Any thoughts on how to fix?

**Comment by docwilmot** [comment] 2021-01-29 04:07
I suspect you'd need a `backdrop_set_title()`

**Comment by BWPanda** [comment] 2021-01-29 04:13
@docwilmot Will try that, thanks. Was more wondering why that happens here and not on, say, the Edit page... Maybe has to do with a menu normal item vs. a menu local action...?

**Comment by BWPanda** [comment] 2021-02-01 02:43
Updated PR to fix page title.

**Comment by klonos** [comment] 2021-02-01 20:23
The tests are all green now, the page title works as expected, and so do all the various user role actions (add/remove/rename). RTBC 👍

**Comment by klonos** [comment] 2021-02-01 20:24
...I was the one to add the milestone label, so someone else needs to add the actual milestone here.

**Comment by quicksketch** [comment] 2021-03-04 02:51
I think this is a fair change. And really minor in the grand scheme of things. It does set us up for using dialogs in the future if desired. I think we can all agree that the field UI isn't something we should be trying to preserve as a pattern.

I'll leave this open until the next time I do a review. Perhaps we can discuss during the [weekly call](https://backdropcms.org/news/meetings) tomorrow.

**Comment by quicksketch** [comment] 2021-03-13 00:18
I've merged https://github.com/backdrop/backdrop/pull/3510 into 1.x for 1.19.0. Thanks @BWPanda for the PR and @klonos and @docwilmot for your suggestions and testing!

**Closed** 2021-03-13 00:18 UTC
Labels: status - has pull request, status - fixed
