### ISSUE TITLE
Follow-up: Add icon to language switcher in admin bar

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#6503] opened 2024-05-03 10:52 UTC
## Description of the bug

Another little follow-up, this time relevant for sites with the **locale** module enabled (multilingual sites).

The language switcher needs an icon, too. Currently it's the default, which doesn't fit well.

This one:
![language-icon-missing](https://github.com/backdrop/backdrop-issues/assets/842066/0691fb3c-edf8-401a-8d0c-f3f9880c0c24)

Easy to fix, now that we have an API for icons. And loads of icons. :smile: 

## Additional information

- Backdrop CMS version: 1.28.x

**Comment by indigoxela** [comment] 2024-05-03 11:11
> And loads of icons...

Solution or problem... :speak_no_evil: 

I chose "translate-fill" for now, as it's relatively similar to the previous one, but the unfilled variant, or one of the globe icons could fit, too.

![translate-icon](https://github.com/backdrop/backdrop-issues/assets/842066/88a3cb5f-0880-4ad9-ac75-00900513dc47)

**Comment by klonos** [comment] 2024-05-03 11:44
That looks good to me 👍🏼 

For reference, this is what it used to look like:
![image](https://github.com/backdrop/backdrop-issues/assets/2423362/29a6dd23-82bc-4317-8460-550156c824a4)

**Comment by klonos** [comment] 2024-05-03 11:50
I tried to test in a demo site (1.27.1), and soon as I enabled the Language and Locale modules and added languages, the language switcher was automatically added (that's where I got the screenshot from in my previous comment). When I tried the same in the PR sandbox though, the language switched is not showing up 🤔

**Comment by klonos** [comment] 2024-05-03 11:51
...odd. It did show up after I disabled/removed/re-installed the modules 🤔

**Comment by klonos** [comment] 2024-05-03 11:54
...I tried to re-reproduce, but I can't 🤷🏼 

Anyway, this works as expected, and code looks good too, so RTBC 👍🏼

**Comment by quicksketch** [comment] 2024-05-04 03:15
I think there's a sanitization issue introduced by the PR: https://github.com/backdrop/backdrop/pull/4729#pullrequestreview-2039212088

**Comment by indigoxela** [comment] 2024-05-04 04:32
@quicksketch many thanks for spotting that problem (copy-paste without thinking...). :+1:  Fixed now.

**Comment by klonos** [comment] 2024-05-04 04:52
> ...soon as I enabled the Language and Locale modules and added languages, the language switcher was automatically added (that's where I got the screenshot from in my previous comment). When I tried the same in the PR sandbox though, the language switcher is not showing up 🤔

FTR: I've raise #6508 for that, since I can now reproduce it consistently.

**Comment by klonos** [comment] 2024-05-04 04:52
Back to RTBC 👍🏼

**Comment by quicksketch** [comment] 2024-05-04 05:04
Perfect, I wasn't sure if that was added for a reason. Thanks for verifying! I merged https://github.com/backdrop/backdrop/pull/4729 into 1.x for 1.28.0. Thanks @indigoxela and @klonos!

**Closed** 2024-05-04 05:04 UTC
Labels: type - task, status - has pull request, pr - ready to be committed, pr - works for me
