### ISSUE TITLE
Install and Update themes missing

### ISSUE THREAD

**Issue by dyrer** [backdrop/backdrop-issues#2025] opened 2016-07-20 19:54 UTC
I have upgraded Backdrop CMS from 1.3 to 1.4 and in appearance section Install and Update themes are missing.

**Comment by klonos** [comment] 2016-07-20 22:00
Hey @dyrer, couple of questions:

- is it just the tabs missing or the menu items in the admin bar too?
- what happens when you "manually" visit `/admin/appearance/install` and `/admin/appearance/update`?

...in order to see if I can reproduce this bug, can you please tell me if you remember the exact versions you upgraded from and to?

**Comment by klonos** [comment] 2016-07-20 22:28
...I think I know what the issue is here @dyrer ...you can head to your modules management page (`/admin/modules`) and enable the new Project Installer module that's available in core after version 1.4. That will bring back those tabs for you.

**Comment by dyrer** [comment] 2016-07-21 05:51
Thanks that was the problem.
Thank you very much

**Comment by serundeputy** [comment] 2016-07-23 00:28
Glad your all set @dyrer ; Thanks @klonos !

I'm closing this. Reopen if there is more needed or an action item.

~Geoff

**Closed by serundeputy** 2016-07-23 00:28 UTC
