### ISSUE TITLE
Error with Manual self-update in BD 1.12.0

### ISSUE THREAD

**Issue by amilenkov** [backdrop/backdrop-issues#3521] opened 2019-02-03 17:06 UTC
Today I tried to check the operation of Manual self-update of core. 

This can not be done with the current version 1.12.1 because there is no newer core. So I downloaded the 1.12.0 version and installed a new installation in a new hosting account and a new database. The system installs seamlessly and immediately detects a newer version of the core.

<There is a security update available for your version of Backdrop. To ensure the security of your server, you should update immediately! See the available updates page for more information. >

So I went to /admin/modules/update check Backdrop (Security update) and click DOWNLOAD THIS UPDAES.

And get this message:

    HTTP error 403 occurred when trying to fetch https://github.com/backdrop/backdrop/releases/download/1.12.1/backdrop.zip.
    Downloading updates failed:
        Failed to download backdrop from https://github.com/backdrop/backdrop/releases/download/1.12.1/backdrop.zip

**Steps To Reproduce**
To reproduce the behavior:
1. Install 1.12.0
2. Go to admin/reports/updates/settings ant setup  Manual self-update 
3. Go to /admin/modules/update and try to download 1.12.1

I cannot paste a screenshot possibly because I am using a browser incompatible with current version of GITHUB, so I paste a links to a screenshots before and after trying of core update.

https://milenkov.net/_files/Update_core_before.png
https://milenkov.net/_files/Update_core_after.png

**Comment by amilenkov** [comment] 2019-02-03 17:12
Update: 

In Temp directory of this Backdrop 1.12.0 installation there is new directory update-cache-b23dc071 but it is empty.

**Comment by laryn** [comment] 2019-02-04 15:23
@amilenkov Is this related to this bug? 
https://github.com/backdrop/backdrop-issues/issues/3488

If so, you may want to test the patch from that thread.

**Comment by amilenkov** [comment] 2019-02-04 16:13
Yes, I think it is related. Seems the same for me as far as I get the same error messages from the system. 

But I cannot help testing patches. My experiences are HTML, CSS, Photoshop and Adobe Illustrator, graphic design, content creating, not programing. 

I will wait for 1.12.2 and even more till this problem is solved. I have worked with Drupal since version 5 where no internal update system was available and can perfectly update core and modules via FTP upload. This works fine. 

And I understand that core updates is giant  and very difficult task and such problems are inevitable. I can help only with reporting when I see something works wrongly. 

And I will continue to do manual backups of DB and all non-core files before every update even after this problem is solved and updates become available without errors through administrative pages.

**Comment by laryn** [comment] 2019-02-04 16:18
Sounds good! 

I'll close this issue then as a duplicate of the other thread, which has a PR.

**Closed by laryn** 2019-02-04 16:18 UTC

**Comment by klonos** [comment] 2019-02-07 19:52
> But I cannot help testing patches. My experiences are HTML, CSS, Photoshop and Adobe Illustrator, graphic design, content creating, not programing.

We could use your help in issues like #3520 #3516 and #3499 @amilenkov 😉
