### ISSUE TITLE
Drop-down menu no longer displays all menu links, after adding checkbox to show all menu links for menu tree

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2886] opened 2017-10-19 18:51 UTC
## Describe your issue or idea

Drop-down menu no longer displays all menu links, after adding checkbox to show all menu links checkbox (for menu tree)

### Steps to reproduce (if reporting a bug)

* Upgrade to 1.8.0
* See broken menu

**Comment by laryn** [comment] 2017-10-19 19:41
Duplicate of https://github.com/backdrop/backdrop-issues/issues/2879?

**Comment by jenlampton** [comment] 2017-10-20 01:32
Yes.

**Comment by olafgrabienski** [comment] 2017-10-28 21:38
Closing (duplicate of #2879, see above).

**Closed by olafgrabienski** 2017-10-28 21:38 UTC
