### ISSUE TITLE
Warnings logged in dblog in php8 when running tests

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5355] opened 2021-11-14 13:52 UTC
This issue deserves a better summary and title, but wanted to quickly record this for now:

- location/referrer: `admin/config/development/testing`
  ```
  Warning: Undefined property: BackdropWebTestCaseCache::$originalLanguageDefault
  in BackdropWebTestCaseCache->tearDown()
  (line 160 of /core/modules/simpletest/backdrop_web_test_case_cache.php).
  ```

- location/referrer: `admin/config/development/testing`
  ```
  The file files/simpletest/simpletest_cache_minimal was not deleted because it does not exist.
  ```

In case it matters, I got both these errors 3 times each, when running dblog tests.

**Comment by indigoxela** [comment] 2021-11-15 07:19
@klonos this issue seems to be a duplicate of https://github.com/backdrop/backdrop-issues/issues/4679

**Closed** 2021-11-16 17:24 UTC
Labels: status - duplicate
