### ISSUE TITLE
Fixed: Views hooks are not invoked without a defined `path` in `hook_views_api()`.

### ISSUE THREAD

**Issue by AlexHoebart-ICPDR** [backdrop/backdrop-issues#5512] opened 2022-02-15 21:33 UTC
## Description of the bug

According to documentation of **hook_views_api**, the **path** parameter is **_optional_**, see https://docs.backdropcms.org/api/backdrop/core%21modules%21views%21views.api.php/function/hook_views_api/1

However, if it is not specified in the hook, it is not set at all and consequently the hook is not invoked as it should be.

## Steps To Reproduce

1. Define a **hook_views_data** as a function custom_module_views_data() in a module's custom_module.views.inc file.
2. Define a **hook_views_api** in a module's custom_module.module file, without giving a path:
```
function custom_module_views_api() {
   return array(
    'api' => 3,
  );
}
```
3. Check the return value of [views_module_include](https://docs.backdropcms.org/api/backdrop/core%21modules%21views%21views.module/function/views_module_include/1)('views', true);

## Actual behavior
The return value does not include a key for the hook_views_api defined in the custom module.
Subsequently, the function [views_include_handlers](https://docs.backdropcms.org/api/backdrop/core%21modules%21views%21views.module/function/views_include_handlers/1) called from [_views_fetch_data_build](https://docs.backdropcms.org/api/backdrop/core%21modules%21views%21includes%21cache.inc/function/_views_fetch_data_build/1)() does not load it and the hook is not invoked by [module_invoke_all](https://docs.backdropcms.org/api/backdrop/core%21includes%21module.inc/function/module_invoke_all/1)('[views_data](https://docs.backdropcms.org/api/backdrop/core%21modules%21views%21views.api.php/function/hook_views_data/1)').
The correctly defined hooks are not invoked by Views module.

## Expected behavior
The hooks defined in the custom module are invoked by Views module.
The return value of views_module_include('views', true) includes a key for the hook_views_api defined in the custom module.
This is the behavior in Drupal 7 and makes the path in hook_views_api optional, as documented (and used in Drupal contrib modules. Note: I just noticed this issue while trying to port a module)).

## Additional information
Backdrop version: 1.21.1 

This can be easily fixed by adding following (missing) code to function [views_get_module_apis](https://docs.backdropcms.org/api/backdrop/core%21modules%21views%21views.module/function/views_get_module_apis/1)() before or after "$api_info['module'] = $module;" (as in the original ctools_plugin_api_info function in Drupal 7)
```
        if (!isset($api_info['path'])) {
          $api_info['path'] = backdrop_get_path('module', $module);
        }
```

**Comment by indigoxela** [comment] 2022-02-16 08:38
Hi @AlexHoebart-ICPDR, I just verified the problem with a module I maintain (realname). Heck, how could we miss that?

Mind to file a pull request? Are you familiar with GitHub forks and pull requests, or do you need any guidance. If so, please let us know.

**Comment by AlexHoebart-ICPDR** [comment] 2022-02-16 10:07
I'm still in phase of finding out if Backdrop is usable for my projects. If it is, I will have to get more familiar with GitHub and will do the pull request. However, if you would like to get that fixed soon, I would appreciate if somebody could just add my snippet of code to the right place as indicated in my post.

**Comment by indigoxela** [comment] 2022-02-16 10:48
> I'm still in phase of finding out if Backdrop is usable for my projects.

@AlexHoebart-ICPDR  I'm confident, it is. :smiley:

> If it is, I will have to get more familiar with GitHub...

You'll get all the help you need.
To not put you under pressure in the evaluation phase, I'll take over the task here, no problem.

**Comment by indigoxela** [comment] 2022-02-16 11:13
A [PR](https://github.com/backdrop/backdrop/pull/3963) is available for testing and review.

I decided to put the fallback for the optional (as documented!) path into function views_module_include() instead. However, there's an open question based on the function comment:

```
@todo: Remove in favor of locating includes directly within core modules.
```
@quicksketch do you happen to remember, what the initial plan to handle file inclusion was? It doesn't only affect core modules, but also all contribs that implement [hook_views_api](https://docs.backdropcms.org/api/backdrop/core%21modules%21views%21views.api.php/function/hook_views_api/1)().

Currently we claim that the path is optional, but it isn't. And that's one of those traps for module ports, that we could catch in a BC way without much effort.

How to test:

- In the Tugboat sandbox install module realname (you can also configure it, but for the test that's not really necessary)
- Create a view of users (fields) and search for field "Realname: Real name"
- It should be available

Compare that to another sandbox without the patch - the field is not available.

**Comment by AlexHoebart-ICPDR** [comment] 2022-02-16 12:17
Thanks @indigoxela for taking this over and preparing the pull request. I can confirm that your, slightly different, approach also solves the issue in my use case.

I'm not sure about Backdrop, because of the small community and related sustainability (compared to Drupal 9) - I'm coming from Drupal 7 and I would have a lot of custom modules to be ported and probably would need to port some other contrib modules not yet in Backdrop. Backdrop claims to have an upgrade path from Drupal 7, but finding quickly such kind of issues makes me wonder how far that is true. (But ok, if I would have tried to solve similar issue while porting a module to Drupal 9, I guess I would have failed completely - I'm just a part-time developer)

**Comment by indigoxela** [comment] 2022-02-16 12:36
> because of the small community and related sustainability (compared to Drupal 9)

We hear that "small community" argument regularly - it's a hen-and-egg problem. One important note: the community is constantly growing. It may not be huge, but it's vibrant and welcoming.

Regarding sustainability: aren't more than seven years of constant work convincing enough? :wink:

The upgrade path is still work in progress. It needs people to report problems to be able to fix and improve. Sure, there's still "Luft nach oben" (you speak German?) - if you expected a one-button-hit-all-done solution, I'd understand that you're disappointed. But even now it's easy compared to other alternatives.

Sorry for digressing... Many thanks for testing. :+1:

**Comment by laryn** [comment] 2022-02-16 15:22
> I can confirm that your, slightly different, approach also solves the issue in my use case.

Setting to WFM based on @AlexHoebart-ICPDR report. Code looks good to me but I'll leave as needs code review since there's an open question:

> @quicksketch do you happen to remember, what the initial plan to handle file inclusion was? It doesn't only affect core modules, but also all contribs that implement [hook_views_api](https://docs.backdropcms.org/api/backdrop/core%21modules%21views%21views.api.php/function/hook_views_api/1)().

**Comment by klonos** [comment] 2022-02-16 15:51
> @quicksketch do you happen to remember, what the initial plan to handle file inclusion was?

I'll leave it to @quicksketch to actually respond, but looking at [the respective function in Views 7.x](https://api.drupal.org/api/views/views.module/function/views_module_include/7.x-3.x), I'm assuming that this `@todo` has to do with moving away from the CTools dependency in a more performant/appropriate way. Perhaps the current form of the function in Backdrop was a "quick 'n' dirty" solution to achieve that at the time, but @quicksketch had plans to improve things even further down the road (perhaps implementing the CTools respective functionality in the System module or something).

**Comment by AlexHoebart-ICPDR** [comment] 2022-03-22 08:04
Is there a reason, why this bug fix has been postponed several times? 
It's fixing a bug, nothing more, nothing less. 
It does not influence the mentioned todo about some possible future ways to handle this differently.

**Comment by indigoxela** [comment] 2022-03-22 08:23
> Is there a reason, why this bug fix has been postponed several times?

@AlexHoebart-ICPDR it's still pending code review. That's pretty often the bottleneck in our queue, sorry for that.

**Comment by laryn** [comment] 2022-03-22 12:34
@klonos  did you raise this in the dev meeting?

**Comment by bugfolder** [comment] 2022-04-02 14:27
It's now [on the agenda for the April 7 dev meeting](https://forum.backdropcms.org/comment/3941#comment-3941).

**Comment by BWPanda** [comment] 2022-04-02 21:06
Just saw this issue and it seemed familiar. Turns out it's a duplicate of one I posted back in 2018: https://github.com/backdrop/backdrop-issues/issues/3202 Guess no one found that one though...

Since there's more activity here I guess I'll close mine.

**Comment by indigoxela** [comment] 2022-04-03 11:22
> Turns out it's a duplicate of one I posted back in 2018

Oops, yes, I also wasn't aware of that one. Seems like "our" policy to keep issues open forever has reached its limits. At least, it doesn't seem realistic to me, that anyone searches a 2.3k+ queue for possible duplicates. :shrug:

**Comment by BWPanda** [comment] 2022-04-03 12:11
@indigoxela I agree that issues shouldn't stay open forever. I'm often going through the issue queue trying to find and close old/outdated ones. But I often get push back from others about this ☹️ 

Having said that, it doesn't require looking through all 2.3k+ issues to find duplicates. Searching for `hook_views_api path` for example find just 4 results, one of which is this one, and one of which was mine: https://github.com/backdrop/backdrop-issues/issues?q=is%3Aissue+hook_views_api+path

**Comment by indigoxela** [comment] 2022-05-01 11:46
Rebased, just in case someone's willing to review it.

**Comment by BWPanda** [comment] 2022-07-02 03:37
Code looks good to me.

**Closed** 2022-07-15 23:26 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2022-07-15 23:29
Thanks folks, and sorry for the delay in response despite the multiple `@` mentions. It looks to me that in my original porting of Views module to Backdrop, I overlooked this situation where "path" might be missing, since almost all of core uses a sub-directory for views handlers.

The fix looks great to me. Thanks for the confirmation and testing @BWPanda.

https://github.com/backdrop/backdrop/commit/c531bf44beeb8b6379f73b546c226d9792948792 by @indigoxela, @AlexHoebart-ICPDR, @klonos, @BWPanda, and @laryn.
