### ISSUE TITLE
[UX][UI] Move Image Title and Alt-Text Labels into Input field as HTML5 Placeholders

### ISSUE THREAD

**Issue by philsward** [backdrop/backdrop-issues#4957] opened 2021-02-19 21:26 UTC
**Description of the need**

Image title and alt text labels create too much overhead with images. Drupal 7 was never designed to be HTML5 ready, so things like adding placeholders within text fields, was never possible without contrib or custom code.

Moving the labels into the input field as placeholders, removes a lot of wasted space and creates a more narrow area to work with a large stack of images. It becomes difficult to re-order 10+ images because the container is "too tall" and difficult to work with.

**Proposed solution**

Long story short, move the "title" and "alt text" labels for images into the text field as HTML5 placeholders.

**Alternatives that have been considered**

Port form_placeholder and use it to override the image title and alt-text labels

**Additional information**

From
![image](https://user-images.githubusercontent.com/3436110/108563159-a0b15780-72c6-11eb-8c8f-28faf79b8457.png)

To
![image](https://user-images.githubusercontent.com/3436110/108563195-ae66dd00-72c6-11eb-9e71-d4f20e247400.png)

**Draft of feature description for Press Release (1 paragraph at most)**

Backdrop image Title and Alt-Text labels have been moved into the input fields as placeholders to make the edit image container smaller and easier to work with.

**Related Request**
https://github.com/backdrop/backdrop-issues/issues/4956

**Comment by olafgrabienski** [comment] 2021-02-19 21:49
Due to [usability issues](www.nngroup.com/articles/form-design-placeholders), placeholders shouldn't be a replacement for labels but an additional option.

Instead of replace the label with a placeholder, we could push the label in the form and design it as a 'floating label':

> In this pattern, labels are placed within the form field as placeholders until the field becomes active and the user moves the input focus into the field. At that point, the placeholder label moves to the top of the field. As a result, the floating label (also known as an adaptive placeholder) is always visible, either in the center of the form field, or above the text that the user entered. (Source: www.nngroup.com/articles/form-design-placeholders)

**Comment by philsward** [comment] 2021-02-20 01:36
I haven't looked, but are there aria designations that would resolve accessibility issues?

**Comment by indigoxela** [comment] 2021-02-20 06:45
I support using placeholders to visually de-clutter forms, but we still should consider accessibility. That's feasible by keeping the label but visually hiding it with css.

Example:
```
<label class="element-invisible" for="the-id">Label text</label>
<input type="foo" id="the-id" placeholder="Label text" />
```
Core provides everything needed for that, it's a matter of adapting the form items to use the attributes.

**Comment by jenlampton** [comment] 2021-02-21 00:18
Placeholders cannot be used in place of labels. Not only because of the accessibility issues, but also because of usability issues for sighed users too. Once a field already contains a value, there would be no indication of what that value is, or what the field is for. The only time it's acceptable to remove the label entirely is when there is no question what the field is being used for (for example: a search box.)

**Comment by jenlampton** [comment] 2021-02-21 00:28
I'm closing this issue as "works as designed" for now, but if others stumble across this later and want to weigh in, please feel free to re-open.

**Closed by jenlampton** 2021-02-21 00:28 UTC
Labels: contrib candidate, status - works as designed
