### ISSUE TITLE
Fixed: Files lose permanent status when in edited in CKEditor link dialog.

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#5843] opened 2022-10-26 16:29 UTC
## Description of the bug

With file uploads for a text format enabled, CKEditor can be used to upload files through the link dialog. Such files lose their permanent status, when the correspondent link is edited using the CKEditor link dialog.

## Steps To Reproduce

To reproduce the behavior:
1. Enable file uploads on `admin/config/content/formats/filtered_html`.
2. Add a Test post, insert a file link in the Body field, using the link dialog in CKEditor and its tab "Upload a file and link to it". Save the link dialog.
3. Check the Source code, it should be something like `<a data-file-id="4" href="/files/inline-files/dummy.pdf">`.
4. Save the node.
5. Check `admin/content/files`. The Status of the file should be `Permanent`, Use count should be `1`.
6. Edit the test post. Edit the link using the link dialog. Save the dialog. (It doesn't matter if you actually change something.)
7. Check the Source code: the `data-file-id` from step 3 is missing.
8. Save the node.
9. Check `admin/content/files`. Status of the file is `Temporary`, Use count is none.

## Actual behavior

On link edting, the `data-file-id` is removed.

## Expected behavior

The `data-file-id` should not be removed.

## Additional information

Add any other information that could help, such as:

- Tested in the Tugboat driven demo site.
- Not yet tested, but I suspect data loss, as temporary files get removed at a certain point.

**Comment by argiepiano** [comment] 2022-10-26 17:30
How do you upload a file using the ckeditor link tool? I can't do that. Only if I use the image tool

<img width="499" alt="Screen Shot 2022-10-26 at 11 30 20 AM" src="https://user-images.githubusercontent.com/9938978/198095812-4ff8c510-dc87-4a73-acdd-2e1f2198649f.png">

**Comment by argiepiano** [comment] 2022-10-27 01:25
I think this is what's happening:

When you upload a file in the link editor, CKEditor preserves the fid of the file by using a data attribute, `data-file-id`, inserted within the `a` tag of the newly created link in the body field.  Upon saving the node, the filter module parses the HTML of the text field and looks for `a` links that contain that particular `data` attribute. When it finds one, it makes the file permanent.

The problem is that, when you edit an existing link in an existing body field using ckeditor link dialog and save it again, that data attribute is lost. This is due to sone logic error in the dialog submit handler. So, when you save the node, the filter module treats that link as a "regular" link, rather than a link pointing at the fid of a managed file.

I haven't yet tried solutions... but perhaps someone can beat me to it.

**Comment by argiepiano** [comment] 2022-10-27 03:40
A bit more information about this, and questions:

When **editing an existing file link**, if you open the link dialog  AND THEN you click   "Upload a file and link to it" you will see the file. If you save AT THAT POINT (with "Upload..." open), then the dialog proceeds as expected and **the file does not lose the permanent status**.

<img width="518" alt="Screen Shot 2022-10-26 at 9 20 42 PM" src="https://user-images.githubusercontent.com/9938978/198184459-772c78cc-cca8-4ccd-9ff7-7576bbf1b7c9.png">


The problem described in this issue ONLY happens if you save the dialog when "Link destination" is selected. Then, the dialog thinks you are saving a regular link rather than a file (despite the fact that the link IS to a managed file). The dialog does not include the data attribute with the fid. Upon saving the node, `filter_entity_update()` thinks that the file link has been removed (since it can't find `data-file-id` in the body text. Therefore it marks the original file as temporary, slated for removal.  

<img width="525" alt="Screen Shot 2022-10-26 at 9 21 59 PM" src="https://user-images.githubusercontent.com/9938978/198184007-a7552cdc-3d4a-4fd5-9ce0-661aeadfb18b.png">

Possible solutions
---

So, this widget is confusing. It has TWO elements that should be mutually exclusive: a textfield to enter a link, and a file upload/source. But what if BOTH elements have values? Which should take precedence? I assume the file... meaning that when you save the dialog, the widget should ignore the filled link textfield, and instead use the fid in the file source field to re-construct the link in the ckeditor field. 

At the moment, this widget will basically use the element that is currently selected: if the link textfield is selected, then it will use that as a "normal" link in the ckeditor field (and therefore remove `data-file-id` from the `a` anchor, resulting in the hook_entity_update to think the file link has been removed, and the file will be marked as temporary). If the file source side is selected, it will use the fid to re-construct the link, and the make (again) the file permanent.

So, possible solutions may be (OR):

- Always give precedence to the file source element over the link textfield element. And also (with JS) activate the file source element automatically (right now, by default, the link textfield is selected). So, if you really want to use the link textfield, you must remove the file first,  OR
- Status quo: basically the element selected has priority, BUT use js to select the file source if this is a link to an uploaded managed file that contains `data-file-id`, OR
- Somehow manage to retain the `data-file-id`, but this is dangerous. Say you are editing the ckeditor field and want to link to something that's not a managed file. In that case, retaining the `data-file-id` is not appropriate and will lead to weird results

I'm leaning toward number 1 above. Thoughts?

**Comment by olafgrabienski** [comment] 2022-10-27 07:42
> At the moment, this widget will basically use the element that is currently selected: if the link textfield is selected, then it will use that as a "normal" link in the ckeditor field (and therefore remove `data-file-id` from the `a` anchor [...], and the file will be marked as temporary). If the file source side is selected, it will use the fid to re-construct the link, and the make (again) the file permanent.

Confirmed, great finding! Thank you very much for investigating so thoroughly.

Regarding the ideas for a solution, I'm tending to no. 1 but it also might be problematic to not prepopulate the link textfield which may suggest that there is no file. Also, the path to the file is actually an interesting information which would be removed by this approach. Idea: leave the prepopulated information but make it not editable and gray it out?

Or a new approach: just never let the dialog remove the `data-file-id`. (What's the purpose of removing it in the first place?)

**Comment by argiepiano** [comment] 2022-10-27 12:35
> Or a new approach: just never let the dialog remove the data-file-id. (What's the purpose of removing it in the first place?)

The removal happens because `data-file-id` is used only when you upload a file. Uploading a file makes it a managed file with a file id. If you manually type a  path to any file in the link textbox, Backdrop has no way to know that this links points to a managed file. Therefore, editing a link results in `data-file-id` not being preserved. 

It's very difficult for Backdrop to know that a URL link actually points at a managed file.

The "elephant in the room" here is the fact that this widget does not let you pick a managed file with a file browser. It only lets you either:

1. Type a path to a file or something else (Backdrop cannot know if this is the path to a managed file)
2. Upload a file (which makes it managed)
3. MISSING: picking a managed file with a file browser 

So a third option: add this functionality to the widget

**Comment by argiepiano** [comment] 2022-10-27 12:43
Adding:

What happens when `data-file-id` is removed: upon saving the node, the filter module compares the body field of original node to the one in the new node. Since it doesn't find `data-file-id` it assumes that the link doesn't point to a managed file anymore, and therefore marks that file (pointed in the original node with `data-file-id`) as temporary, slated for removal since it's not pointed to anymore.

**Comment by indigoxela** [comment] 2022-10-27 12:47
Hm... very tricky (also confirmed the problem). I'm not sure if we should make this widget even more confusing... :thinking: 

@argiepiano seems to be right - it's not easy (maybe impossible) for the dialog form submit to distinct managed and unmanaged files.

Two inputs for the same item make this widget a bit fragile.

**Comment by indigoxela** [comment] 2022-10-27 13:47
Here's a [PR](https://github.com/backdrop/backdrop/pull/4242) as a starting point.

It **is** possible to keep the fid, but that has a side effect - it's not possible anymore to change the value when editing. So maybe this makes the widget more confusing. Feedback is welcome.

**Comment by indigoxela** [comment] 2022-10-27 13:52
Some explanation:

Currently in filter_format_editor_link_form_submit there's an if/else. So if the href is set - which is the case when editing an existing link - the fid isn't considered.

If we still consider the fid (it's still there in the form_state values), we prevent people from overriding the href value directly. In fact, they still can override it, but their submission is discarded, as the fid wins. Definitely not ideal from a UX perspective, but prevents data loss by removing the permanent status.

Any smarter suggestions?

**Comment by indigoxela** [comment] 2022-10-27 14:27
Looking closer at the code - the problem is somewhere else: in function _filter_get_file_id(), where file_valid_uri() fails, because the href value isn't what the validation expected - a stream wrapper uri.

**Comment by indigoxela** [comment] 2022-10-27 14:37
Here we go, IMO we have to fix the problem in _filter_get_file_id(). We can _not_ use file_valid_uri() here, as that would only work with stream wrapper uris (like public://foo/bar...), not with a href value.

**Comment by argiepiano** [comment] 2022-10-28 00:47
This is brilliant, @indigoxela! I didn't realize that this module could actually look up the fid from the typed path.  So the fix was a lot simpler than I thought, and it was a bug with the code rather than a problem with the widget itself.

RTBC!

**Comment by argiepiano** [comment] 2022-10-28 00:49
I added the milestone bug label. If someone else could add the actual milestone version that'd be great

**Comment by klonos** [comment] 2022-10-28 07:20
Great teamwork here people! 👍🏼 ❤️ 

I've left a comment in the PR, since the proposed code changes are making assumptions re the file scheme being used. I believe that we should be checking which text format is being used, and then get the `editor_settings.file_upload.scheme` setting from the appropriate `filter.format.*.json` file.

PS: does this happen with uploaded images too? ...because there's a separate `editor_settings.image_upload.scheme` setting for that in each text format config file.

**Comment by olafgrabienski** [comment] 2022-10-28 08:05
> does this happen with uploaded images too?

If you refer to the image dialog, I don't think so. (Tried only quickly on one of my test sites.)

**Comment by indigoxela** [comment] 2022-10-28 08:35
> Great teamwork ...

And ongoing. :wink: @klonos Many thanks for your hint re private files (how could I miss that). Fixed now.

**Comment by indigoxela** [comment] 2022-10-28 08:50
@klonos you may wonder, why I don't strictly check for the file system in use in that textformat. That's because the setting can change (happened while I tested), and the previously referenced file is still valid, so we shouldn't break that link on updates. Only newly uploaded files will go to the path that's now configured.

**Comment by olafgrabienski** [comment] 2022-10-28 10:58
Thanks for the updated PR, @indigoxela, it works for me! Tested in my local test site, both with public and with private files.

**Comment by argiepiano** [comment] 2022-10-28 13:59
There is one case in which the text input may not be working as expected (i.e. it doesn't recognize it's a managed file), but perhaps it's the expected behavior.

1. Manually upload a file (text file or anything else) using the Manage file ui
2. Visit the file page (your URL should be something like `example.com/file/39`  where 39 is the fid).
3. Copy the path to the file page as in `/file/39`  (no https or base url etc)
4. Create a node and use ckeditor to insert a link. Paste `/file/[FID]` there
5. Save

If you inspect the link with your browser's dev tool, you'll see it doesn't have a `data-file-fid`, and the usage counter for the file does not increase.

Now, I'm not sure if it should or not. The link is pointing at the file entity page, not to the file itself. There is no danger for it to be marked as temporary either, as it was uploaded through the File manage UI. So, perhaps this is working as expected, but I thought I add this here as a comment in case someone wonders.

**Comment by indigoxela** [comment] 2022-10-28 14:04
> Now, I'm not sure if it should or not.

Linking to a File entity page (file/fid) is not the same as linking to the file in the files directory. Links to entities don't have and don't need a data-file-id attribute - which exists to capture file usage. A File entity is no file (oh these naming rabbit holes :wink:)

**Comment by argiepiano** [comment] 2022-10-28 14:06
> Links to entities don't have and don't need a data-file-id attribute - which exists to capture file usage

Yeah, that's what I was thinking...

**Comment by klonos** [comment] 2022-10-29 07:54
Thanks @indigoxela ...I have a few questions:
1. have you considered improving `file_valid_uri()` instead of adding these checks in `_filter_get_file_id()`?
2. what is the `system/files/` thing we are now hard-coding in the pattern that we are checking? ...where does it come from?
3. why are we only using `config_get('system.core', 'file_public_path')` and not also `config_get('system.core', 'file_private_path')` in the pattern?

**Comment by indigoxela** [comment] 2022-10-29 09:52
> have you considered improving file_valid_uri()

No, because file_valid_uri() is simply not meant to work with urls or paths, it strictly validates `public://` or `private://`. Wrong tool for the job.

> what is the system/files/ thing we are now hard-coding

That's the start of the url to a private file, see the [source](https://github.com/backdrop/backdrop/blob/1.x/core/includes/stream_wrappers.inc#L975)

> why are we only using config_get('system.core', 'file_public_path') and not also config_get('system.core', 'file_private_path') in the pattern?

Because:

1. The url is always `system/files/`
2. This path is irrelevant for this widget, as it's not accessible via web, anyway - we need the actual url in our widget, no file system paths

@klonos does that answer your questions?

**Comment by klonos** [comment] 2022-10-29 10:10
> @klonos does that answer your questions?

Yup, thanks 🙏🏼 ...can we please add some of these as inline comments? I'm sure that if I asked, others will also wonder in the future.

**Comment by indigoxela** [comment] 2022-10-29 10:16
> ... can we please add some of these as inline comments?

Happy to do so, but what seems most helpful to you? Mind to suggest something? Regex stuff is always a bit hard to document.

**Comment by klonos** [comment] 2022-10-29 10:19
> Mind to suggest something?

I will. In the meantime, I don't want to stop others from RTBC'ing this over some documentation/comments.

**Comment by klonos** [comment] 2022-10-29 20:37
...I've added a suggestion for an inline comment @indigoxela. Feel free to tweak as you see fit.

Since the suggestion is only adding an inline comment, I'm marking the code RTBC.

**Comment by indigoxela** [comment] 2022-10-30 09:07
@klonos great, many thanks! :pray: Suggestion committed.

**Comment by quicksketch** [comment] 2022-11-10 21:06
@indigoxela Do we have any idea what kind of effect this would have on managed files that use stream wrappers other than `public://` and `private://`? Although the only stream wrapper we have in contrib is https://github.com/backdrop-contrib/system_stream_wrapper (for which I don't think this issue is relevant), I think this would likely have problems with `s3://` or other read/write stream-wrappers. At the same time, this fixes a problem for 99% of all Backdrop sites, so maybe we should just leave a `@todo` in there if this doesn't work with other stream wrappers.

**Comment by indigoxela** [comment] 2022-11-11 07:26
> ... what kind of effect this would have on managed files that use stream wrappers other than public:// and private://?

That's an interesting point, but I wouldn't know how to test that. I never used s3 so far, so I don't even know what url it actually uses. In theory an external one, so very likely the file usage won't get recorded - but that's also the case currently.

I don't even know if file usage is ever recorded for external stream wrappers. Maybe @keiserjb has some info?

**Comment by keiserjb** [comment] 2022-11-11 16:13
@indigoxela yes, well the url for the uploaded files becomes the url of the s3 bucket.  I tested the PR first with public files and then with s3.  It's only on file but all seems to be good.

**Closed** 2022-11-26 18:10 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2022-11-26 18:11
Thanks folks! I have merged https://github.com/backdrop/backdrop/pull/4242 into 1.x and 1.23.x.
