### ISSUE TITLE
Unable to Filter Aliases on URL aliases page

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2836] opened 2017-09-04 21:33 UTC
## Describe your issue or idea

I'm not able to use the URL alias filter on the URL Aliases page for any URL containing a slash `/`.

### Steps to reproduce (if reporting a bug)

1) navigate to the Url aliases page
2) attempt to search for the alias `articles/purdue-university-visual-communications-design-computer-graphics-technology-programs-profile`

### Actual behavior (if reporting a bug)

* the search box fills with only the first part of the url: `articles`
* the path `articles/purdue-university-visual-communications-design-computer-graphics-technology-programs-profile` gets appended to the current page. In my case, the url I was on was changed to `http://www.example.com/admin/config/urls/path/list/articles/purdue-university-visual-communications-design-computer-graphics-technology-programs-profile`

**Comment by indigoxela** [comment] 2021-01-24 11:55
I can reproduce it.

It happens, because function [path_admin_filter_form_submit_filter](https://github.com/backdrop/backdrop/blob/0362219161a9b42275fdfbe54ae36d857c2af672/core/modules/path/path.admin.inc#L328) does it with a simple `$form_state['redirect']` and the value simply gets attached to the url. That seems pretty odd to me...

It could get fixed by using a proper $_GET param.

**Comment by indigoxela** [comment] 2021-01-25 15:33
My previous comment is likely off topic...

I did a quick check, how D7 handles that form - it has the same quirk.

Playing around with that form, I realized the problem: strings containing slashes don't work, as they seem to get interpreted as page arguments (?), hence reduced to the first arg... - I'm only guessing.

For instance, a search string like `posts/a/b/c/d/e` gets cut to `posts`.

I can fix the problem, but I don't know what's happening. :grin: 

A [PR](https://github.com/backdrop/backdrop/pull/3515) is available.

Hm, we don't have a label for "pr - needs enlightenment"... Can anyone help out with an explanation?

**Comment by klonos** [comment] 2021-01-25 15:41
Seems similar to #2833 @indigoxela ...only in that case it's `backdrop_goto_deprecated()` which seems to trip up on wildcard/placeholder (`%`) instead of forward slashes.

**Comment by klonos** [comment] 2021-01-25 15:48
I've tested this on a vanilla Backdrop demo sandbox:

- navigated to `/admin/config/urls/path`
- searched for "posts/your-first-post"
- the filter works, as the list of aliases gets filtered down to that single alias 👍 
- the filter gets appended to the URL, which becomes `/admin/config/urls/path/list/posts/your-forst-post` 👍 
- the search text in the "Filter aliases" textfield gets reduced to "posts" 👎 

I then tested on the PR sandbox. Everything works as expected 👍 (the "Filter aliases" textfield retains the full search text "posts/your-first-post")

**Comment by klonos** [comment] 2021-01-25 15:50
...now whether the implementation is the right way to do it or simply happens to work, I don't know. Same as @indigoxela, I'd like to understand more before I can tell.

**Comment by indigoxela** [comment] 2021-01-25 15:58
> Seems similar to #2833 ...

I wouldn't bet on that. The main problem in the other issue is with placeholder substitution - if I get it right.

The alias filter form doesn't have any placeholder (from hook_menu). The common things in both issues are: hook_menu and backdrop_go_to in use, but... the redirect via $form_state['redirect'] works correctly, it's just a function parameter that gets mangled.

> I'd like to understand more ...

Same here, that's why I set the imaginary "pr - needs enlightenment" label. :laughing:

**Comment by docwilmot** [comment] 2021-01-25 18:33
> Hm, we don't have a label for "pr - needs enlightenment"... Can anyone help out with an explanation?

Useless comment follows: 🤣 🤣

**Comment by jenlampton** [comment] 2021-01-25 18:47
> The alias filter form doesn't have any placeholder (from hook_menu).

Placeholders (%) are used when an item needs to be loaded when passed through as a parameter. Nodes get `node_load()`ed, users `user_load()`ed, etc. In any case where a "magic-loader" isn't needed, there won't be a placeholder in the menu system. In those cases the parameters are passed directly into the page as strings, usually through `page arguments`.  

If only a single argument is passed, for example, the one in position 1, then only the items **between the slashes** in that position get passed along. 

If menu route is `/admin/config/urls/path` and it the `page arguments` are `array(1)` and you try the path "/admin/config/urls/path/posts/a/b/c/d/e" then only the argument in the first position is passed through: "/admin/config/urls/path/**posts**/a/b/c/d/e".

For path, it doesn't look like `page arguments` is set:
```php
$items['admin/config/urls/path'] = array(
    'title' => 'URL aliases',
    'description' => "Change your site's URLs by setting up automatic URL alias patterns.",
    'page callback' => 'path_admin_overview',
    'access arguments' => array('administer url aliases'),
    'file' => 'path.admin.inc',
  );
  $items['admin/config/urls/path/list'] = array(
    'title' => 'List URL aliases',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
```

Maybe the default value is `array(1)`?

**Comment by jenlampton** [comment] 2021-01-25 18:58
The solution in the PR looks fine, though I agree switching to a proper `$_GET` param would be a cleaner solution. Would that cause any issues with backwards compatibility? (adding NW label for removal of the @todo)

**Comment by docwilmot** [comment] 2021-01-25 20:42
I think @indigoxela solution is probably the best. Plus remove the `$key =NULL` parameter. This function will only ever get passed a path string, right?

**Comment by jenlampton** [comment] 2021-01-26 02:43
> Plus remove the $key =NULL parameter. 

Ooh, I like this suggestion. 

My first thought was that this change wouldn't be backwards compatible, but any contrib that was relying on `$keys` wouldn't be working the way it is now anyway. 👍

**Comment by indigoxela** [comment] 2021-01-26 07:53
@jenlampton Many thanks for the enlightenment. :wink: 

The PR has been updated: the useless function parameter has been removed, and comments got updated. Ready for another review.

**Comment by klonos** [comment] 2021-01-26 08:56
RTBC 👍 ...I was the one to add the milestone label, so someone else needs to add the actual milestone.

**Comment by jenlampton** [comment] 2021-01-26 18:09
ooh! me!

**Closed** 2021-01-27 21:22 UTC
Labels: pr - ready to be committed, pr - works for me, status - has pull request, type - bug report

**Comment by quicksketch** [comment] 2021-01-27 21:32
I'm not a fan of the Backdrop menu system just taking any number of arbitrary arguments based on path, but we have a much bigger problem to change that behavior. This is a very low impact location, so I don't think we'd have trouble changing it in the future.

Thanks folks for the work on this one. I've merged https://github.com/backdrop/backdrop/pull/3515 into 1.x and 1.18.x.
