### ISSUE TITLE
The word "All" is repeated at the bottom of menu admin pages

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3123] opened 2018-05-16 05:36 UTC
## Describe your issue or idea

For every menu item, the word "All" appears at the bottom of the menu admin page, just above the `Save configuration` button. 

Examples below:
<img width="1191" alt="screen shot 2018-05-15 at 10 34 43 pm" src="https://user-images.githubusercontent.com/397895/40098418-35d8a858-5890-11e8-914f-4a462e9613a7.png">

<img width="1262" alt="screen shot 2018-05-15 at 10 35 26 pm" src="https://user-images.githubusercontent.com/397895/40098430-4cc7d124-5890-11e8-86df-3c9b34528b8a.png">

### Steps to reproduce (if reporting a bug)

* Upgrade to Backdrop 1.10
* visit any menu admin page

### Actual behavior (if reporting a bug)

* the word `All` appears above the `Save configuration` button. 

### Expected behavior (if reporting a bug)

* no strange text

### Relevant version/system information (if applicable)

* Starting at version 1.10.0

---

PR https://github.com/backdrop/backdrop/pull/2193

**Comment by quicksketch** [comment] 2018-05-16 05:42
This happens because we have added a language code column to the output, but the column is not shown if Locale module is not enabled. So the string "All" is printed out once per language below the table, since it can't render in the missing column.

**Comment by quicksketch** [comment] 2018-05-16 05:44
PR filed at https://github.com/backdrop/backdrop/pull/2193.

**Comment by jenlampton** [comment] 2018-05-16 05:53
I can confirm that the PR fixes the problem. Thanks!

**Comment by opi** [comment] 2018-05-17 12:04
confirmed too

**Comment by quicksketch** [comment] 2018-05-23 22:51
Thanks! Merged https://github.com/backdrop/backdrop/pull/2193 into 1.x and 1.10.x.

**Closed** 2018-05-23 22:50 UTC
Labels: status - has pull request, status - fixed
