### ISSUE TITLE
Layout context regression: Updating to 1.17.0 throws PHP fatal "Unsupported operand types" error

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4604] opened 2020-09-07 20:28 UTC
**Description of the bug**

I am attempting to update a site from backdrop 1.15.0 to 1.17.0-preview, and I get the following PHP fatals when running update.php

It appears as though core assumes `$this-contexts` and `$this->getContexts()` will always return an array. It does not check to see if the value is an array in many places. It immediately runs a `foreach()` on the result in some places, and in others does `$this->contexts += $contexts` assuming both are arrays. Neither of these will work if contexts is not an array. 

```
Error
Error message

    Warning: Invalid argument supplied for foreach() in Layout->getContexts() (line 773 of backdrop/core/modules/layout/includes/layout.class.inc).
    Warning: Invalid argument supplied for foreach() in LayoutMenuItem->resetContexts() (line 265 of backdrop/core/modules/layout/includes/layout_menu_item.class.inc).
    Error: Unsupported operand types in LayoutMenuItem->getContexts() (line 253 of backdrop/core/modules/layout/includes/layout_menu_item.class.inc).

Unsupported operand types

```

**Steps To Reproduce**

To reproduce the behavior:
1. Install backdrop 1.15.0, 1.15.1, or 1.16.3
2. Replace code with 1.17.0-preivew
3. Visit `/core/update.php` and run the updates using the UI
4. Update fails due to fatal error:

<img width="927" alt="Screen Shot 2020-09-10 at 4 32 10 PM" src="https://user-images.githubusercontent.com/397895/92824418-3c878080-f383-11ea-8d3d-35f8e6988bed.png">

**Actual behavior**

PHP fatal prevents updates from running. 

**Expected behavior**

Update as usual

**Additional information**

We made some changes to `core/modules/layout/includes/layout.class.inc` in https://github.com/backdrop/backdrop-issues/issues/3750 that may have accidentally removed [the code that handled the case when layout contexts are null](https://github.com/backdrop/backdrop/pull/3271/files#diff-f9a46040a1020182a9f049bb8c6864e8L760). 

I've provided a PR that adds this back.

---

Sites tested:
* Site A: 1.16.2 - PHP 7.2.19-0ubuntu0.19.04.1
* Site B: 1.15.0 - PHP 5.5.9-1ubuntu4.11
* Site E: 1.14.1 - PHP 5.4.45
* Site F: 1.16.2 - PHP 7.3
* Site J: 1.16.2 - PHP 7.3
* Site O: 1.15.1 - PHP 7.2.19-0ubuntu0.19.04.1

---

PR https://github.com/backdrop/backdrop/pull/3296

**Comment by indigoxela** [comment] 2020-09-08 08:59
I couldn't reproduce it (yet).

I installed a vanilla 1.15.0 (no contrib modules).

Then I tried updates to 1.17.0-preview in two ways.

**1) In two steps**

After installing the outdated version I immediately got notified that an update is available (1.16.2).
Then I went to admin/modules/update and ran the core update from UI.
Then I unzipped the preview release, extracted the core directory, removed the old 1.15 core directory, moved the new core in place and ran `updb`.

That went smoothly.

**2) In one step**

After installing 1.15.0 I replaced the outdated core directory with the one from 1.17.0-preview and ran the database update via UI (core/update.php).
All 13 available updates ran smoothly, no errors or problems at all.

**Additional info**
- php 7.2
- apache 2.4
- mariadb 10.3

@jenlampton can you give us some details about the site you saw the php fatal?

Whatever is/was the reason for the php fatal - it's nothing in core alone.
Either a contrib module or a configuration item seems to be the root cause.

**Comment by klonos** [comment] 2020-09-09 13:26
@jenlampton I've hit this as I was testing the PR in ???

I've left a comment in your PR re checking `!is_array()` instead of `is_null()`. Will try to test on my local next...

**Comment by klonos** [comment] 2020-09-09 13:51
I was able to reproduce this by doing the following:

1. Prepared my local, and pulled @jenlampton's PR:

```
git clone https://github.com/backdrop/backdrop docroot
cd docroot
git checkout -b issue-4604
git fetch origin pull/3296/head:issue-4604
```

2. git checkout origin/1.16.x core -> install Backdrop -> enable all errors under `admin/config/development/logging` -> visit the status report page -> all good 👍 

3. git checkout origin/1.x core -> refresh page -> 👎 -> clear caches -> refresh page -> still 👎 

![image](https://user-images.githubusercontent.com/2423362/92606613-cff57e80-f2bb-11ea-81c0-b42053dcdcfd.png)

4. git checkout core (this reverts core back to @jenlampton's PR changes) -> clear caches -> refresh page -> 👍 -> run pending db updates -> no errors 👍

**Comment by docwilmot** [comment] 2020-09-09 18:07
We did change the class to declare `private $contexts = array()` but somewhere perhaps upgraded sites are reading config files with `context = null or ''` set? I checked over and every mention of context in the code seems to be an array, so I'm suspecting config files. Not sure though.

**Comment by jenlampton** [comment] 2020-09-09 22:25
> We did change the class to declare private $contexts = array() but somewhere perhaps upgraded sites are reading config files with context = null or '' set? I checked over and every mention of context in the code seems to be an array, so I'm suspecting config files. Not sure though.

On my 1.15 site it was `NULL`, so I'm guessing it was never set in the first place.

@quicksketch suggested setting the value to an empty array in the constructors. Apparently defining the property as an array `private $contexts = array()` doesn't actually create a property on the class that's an empty array for new classes, but initializing it in the constructors did. 🤷

**Comment by jenlampton** [comment] 2020-09-09 23:32
I'm seeing this again on another site, this one was on 15.1 before upgrading to 17.0-preview. It's running on 7.2.19-0ubuntu0.19.04.1.

Even with the patch from this PR, I'm still getting these two errors, the first is fatal:

```
Error: Unsupported operand types in LayoutMenuItem->getContexts() (line 258 of backdrop/core/modules/layout/includes/layout_menu_item.class.inc).
Warning: Invalid argument supplied for foreach() in LayoutMenuItem->resetContexts() (line 276 of backdrop/core/modules/layout/includes/layout_menu_item.class.inc).
```

**Comment by jenlampton** [comment] 2020-09-09 23:43
I've pushed an update to the PR that adds an additional check for `NULL` contexts into `getContexts()` for the layout menu item class. That fixes both the remaining errors. I'm going to test this on a third site.

**Comment by indigoxela** [comment] 2020-09-10 06:29
Did anyone already figure out what's the actual root cause of the fatal? Sure, `$contexts` is not an array under certain circumstances, but what is necessary to reproduce it?

**Comment by indigoxela** [comment] 2020-09-10 08:19
Ha! Success. The problem occurs when core directory has already been replaced but the db updates did not yet run and one clicks around in the website.

The only thing I needed to do is adding the check to both constructors (layout.class.inc and layout_menu_item.class.inc):
```
    if (!is_array($this->contexts)) {
      $this->contexts = array();
    }
```

**Comment by laryn** [comment] 2020-09-10 13:40
I upgraded a dev site to 1.17 and saw this same thing, along with `Error: Call to a member function init() on null in view->init_localization` (not sure if that's different or related to this issue). I applied the PR from this thread and cleared caches with drush and the fatals went away...

**Comment by jenlampton** [comment] 2020-09-10 19:49
@laryn I don't think that error is related to this problem. Do you think it might have been the cache clear that fixed it? I did see those same errors on one site, but they went away after I did a cache clear, so I didn't pursue them further. 

> Just visiting status page and then run the db updates is not enough.

Updating is enough. On all 3 of my sites the fatal error appeared during the update process (I used update.php, not drush) and prevented the updates from running.

**Comment by indigoxela** [comment] 2020-09-11 08:32
I belief the PR is _almost_ ready.

@klonos requested a change and I support it: instead of `is_null()` check for `!is_array()` in all 4 places. Because anything that's _not_ an array will cause problems (NULL, empty string, string, integer, float), so it seems safer to use is_array().

**Comment by jenlampton** [comment] 2020-09-11 16:52
I merged the change, but then had second thoughts because I only wanted to
cover the case where contexts was not yet set. Overwriting an existing
value with an empty array seemed the wrong thing to do. If an existing
value were passed in that wasn't an array, that should be fixed where the
value was set, not overwritten here.

**Comment by indigoxela** [comment] 2020-09-12 13:04
> ...but then had second thoughts because I only wanted to
> cover the case where contexts was not yet set. Overwriting an existing
> value with an empty array seemed the wrong thing to do.

Only arrays are usable, anything else will cause problems, foreach() can handle arrays and only arrays. In other words: array or bust. :grin:

**Comment by jenlampton** [comment] 2020-09-12 19:35
Exactly. And if something is setting a non-array non-null value, it will
need to be fixed wherever it's coming crom -- not here.

**Comment by indigoxela** [comment] 2020-09-14 14:56
@klonos regarding the recent comments here - are you able to set the PR to RTBC? Or are there additional concerns?

**Comment by quicksketch** [comment] 2020-09-14 20:58
I wish we didn't need the checks in so many places, but I think unless we put them in all the locations covered by the PR, sites that upgrade may be unusable until the administrator visits update.php, because a cache clear may be needed. So I'm fine with it as is.

I don't think @klonos's recommendations to switch from `is_null()` to `!is_array()` are required, I think he was just suggesting that based on @indigoxela's [suggestion above](https://github.com/backdrop/backdrop-issues/issues/4604#issuecomment-690074641).

**Comment by quicksketch** [comment] 2020-09-14 21:05
I merged  https://github.com/backdrop/backdrop/pull/3296 into 1.x for 1.17.0. Thanks folks!

**Closed** 2020-09-14 21:05 UTC
Labels: status - has pull request, status - fixed
