### ISSUE TITLE
Layout template prints "main page content" block twice if you move the content block to another region

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3606] opened 2019-03-21 21:35 UTC
**Description of the bug**
In the default layout, when the main page content block is moved to a region other than the default region, the block is printed twice.

edit: The same thing happens with any layout, when you move the main page content block. The problem does not happen on a node/% layout, so it may be limited to the default layout.

**Steps To Reproduce**
To reproduce the behavior:
1. Configure the default layout
2. Switch the layout template to "Sutro"
3. Move the "main page content" block from the "content" region to the "half first" region
4. Save the layout
5. Visit the default post at node/2

**Actual behavior**
The main page content is rendered twice.

**Expected behavior**
The main page content should only be rendered once.

**Comment by stpaultim** [comment] 2019-10-08 04:47
This is still happening. @jenlampton - do you remember why you closed this issue?

It is not specific to any layout. You can test this leaving the default layout template as it is. This happened to me on a local site and I also tested it in a Tugboat demo site and confirmed it there.

As @jenlampton points out, the problem goes away if you create a node/% template.

**Comment by stpaultim** [comment] 2019-10-08 04:52
This issue: https://github.com/backdrop/backdrop-issues/issues/2660
Sutro layout duplicates "Main page content" block when used as the default layout

**Comment by stpaultim** [comment] 2019-10-08 05:05
OK, closing this now. It's a duplicate of:
https://github.com/backdrop/backdrop-issues/issues/2691

Which was a followup of https://github.com/backdrop/backdrop-issues/issues/2660

**Closed** 2019-10-08 05:05 UTC
Labels: status - duplicate
