### ISSUE TITLE
All themed views grids broken in 1.12.x

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3494] opened 2019-01-21 20:50 UTC
**Describe the bug**
After introducing the CSS grids fix for views grids in 1.12 all the grid views on my site are broken.

Before the upgrade to 1.12 the items in my grid were structured into rows and columns, so the render array looked like this:

<img width="599" alt="screen shot 2019-01-21 at 12 48 07 pm" src="https://user-images.githubusercontent.com/397895/51498339-f67b4480-1d7a-11e9-9fb3-07a902709bd0.png">

After the upgrade, the array has been flattened into a single list of items, removing the row / column structure that my theme depended on:

<img width="507" alt="screen shot 2019-01-21 at 12 49 00 pm" src="https://user-images.githubusercontent.com/397895/51498356-072bba80-1d7b-11e9-87f4-810c27793595.png">

The renderable structure should remain the same unless I have ticked the box in the views settings asking to have it changed.

**Steps To Reproduce**
1) Theme a grid view in 1.11.x
1) update to 1.12.x

**Actual behavior**
broken grids.

**Expected behavior**
not broken grids.

**Additional information**
Add any other information that could help, such as:
- Backdrop CMS version: 1.12

----
PR https://github.com/backdrop/backdrop/pull/2486

**Comment by jenlampton** [comment] 2019-01-21 21:05
Manually editing the view and checking the box for "Use HTML table (deprecated)" does not restore the previous render array structure. (I thought this was going to be updated for all existing sites? did we forget the update hook?)

**Comment by jenlampton** [comment] 2019-01-21 21:17
I have reverted this patch to get my site working again, since I made heavy use of grids.

**Comment by herbdool** [comment] 2019-01-22 14:00
My understanding of how we implemented it was that if the view style wasn't edited it would use deprecated tables and if it was edited would need to check it to keep it that way. Maybe that's not working.

**Comment by herbdool** [comment] 2019-01-22 14:51
I can confirm that old views will have flattened render arrays (I think it's defaulting to the new grid then). But if I then edit the view and turn on deprecated HTML tables then it goes back to the proper nested array. Looks like we need to tweak the logic a bit. Not sure if it requires an update hook, but that's an option too.

**Comment by herbdool** [comment] 2019-01-22 15:00
I suspect that in views.theme.inc $options will show deprecated_table as false even if it wasn't in the view config. In which case, that means we'd need to set deprecated_table in an update hook. Otherwise we don't know if it was intentional or not.

**Comment by jenlampton** [comment] 2019-01-22 17:12
Setting the deprecated table setting to TRUE didn't restore the nested
render array structure for me. I was froced to reverse the patch to get
that back.

**Comment by jenlampton** [comment] 2019-01-22 17:13
I'll get an export of one of my views and post it here.

**Comment by herbdool** [comment] 2019-01-22 21:51
@jenlampton can you try out https://github.com/backdrop/backdrop/pull/2486

**Comment by jenlampton** [comment] 2019-01-23 01:21
I tried it, and I still have a flattened array of values after the patch, even if I check the box for the deprecated table setting.

**Comment by herbdool** [comment] 2019-01-23 01:45
@jenlampton I think I fixed the issue in the update hook.

Can't test the update hook on the sandbox, but I did test manually toggling the deprecated table checkbox and it seems to work:  http://2486.backdrop.backdrop.qa.backdropcms.org/content-grid

**Comment by jenlampton** [comment] 2019-01-27 23:04
It didn't work for me on one site, but I'll try some others...

**Comment by jenlampton** [comment] 2019-02-01 09:40
This patch works for backdropcms.org.

**Comment by jenlampton** [comment] 2019-02-08 21:31
I've applied the patch and run it for my site that makes heavy use of views grids, it appears that this has fixed the issue. I'm not sure why manually editing / saving the view with this change didn't do the trick...  unless maybe I was editing the wrong view? Anyway - RTBC from me.

**Comment by quicksketch** [comment] 2019-02-08 22:06
Thanks folks! Merged https://github.com/backdrop/backdrop/pull/2486 into 1.x and 1.12.x.

**Closed** 2019-02-08 22:30 UTC
Labels: status - has pull request, status - fixed
