### ISSUE TITLE
The 'current_user' context in a Layout does not contain a User entity

### ISSUE THREAD

**Issue by MrHaroldA** [backdrop/backdrop-issues#2398] opened 2016-12-12 12:47 UTC
Currently, the 'current_user' context contains the global stdClass $user. This object does not contain any fields, and isn't a User entity, so calling $entity->bundle() fails with a fatal error instead of calling the parent \Entity::bundle.

```
Error: Call to undefined method stdClass::bundle() in FieldBlock->getContent() (line 73 of /home/harold/checkout/backdrop/core/modules/field/field.block.inc).
```

I'm not to familiar with the Layout-system, but I guess the data of a block should contain a fully loaded user, as you are probable trying to display field data in a block.

\Layout::getContexts
```
$this->contexts['current_user']->setData(user_load($GLOBALS['user']->uid));
```
-------
~~PR by @bradbulger: https://github.com/backdrop/backdrop/pull/3045~~
updated PR by @bradbulger: https://github.com/backdrop/backdrop/pull/3314

**Comment by MrHaroldA** [comment] 2016-12-14 09:00
Copied from the Gitter chat:

> In hindsight; shouldn't the global $user always contain a fully loaded User entity? I always found it quite strange that I needed to load the user to access it's properties.

> I think I ran into something similar, @MrHaroldA , when trying to use the anonymous user via $user. It turns out the anonymous user isn't a proper User entity, but something else entirely. There was an exchange about it with me and @quicksketch .... I forget it if was in a ticket or here in gitter. If you start to address the $user should contain a User (and yes, I think it should, too), you may need to find a solution to anonymous, too.

> From a developer's view it would be most welcome to always have a fully loaded User in $user, anonymous or logged in shouldn't matter. I also think it wouldn't be very hard to do so and it also won't break anything.

**Comment by bradbulger** [comment] 2020-01-22 18:13
This is not a feature request. The user fields are available as blocks in the layout, but using them causes a fatal error. That's a bug.

It seems reasonable to explicitly use the "load callback" function defined for User entities, since hook_layout_context_info() is set up to allow modules to alter that value.

**Comment by bradbulger** [comment] 2020-01-22 18:59
I added a pull request with changes to both load a complete user and to fail out of FieldBlock if the entity doesn't implement EntityInterface (and thus has a bundle() method, etc.).

https://github.com/backdrop/backdrop/pull/3045

**Comment by indigoxela** [comment] 2020-01-23 08:05
@bradbulger I seem to have trouble to reproduce. Could you provide the steps, please?

Maybe I misunderstood the bug description.
I added a custom block to a layout, set a visibility condition on "User account uid: 0" and it works fine.
The block shows for anonymous and doesn't for logged-in user. No error, nothing in dblog.
I've been testing with 1.15.x-dev.

What am I missing?

**Comment by bradbulger** [comment] 2020-01-23 16:23
Add a field to the user entity - like a Full Name field. Go to a layout and add a block - don't tie the layout to a particular user, otherwise it doesn't matter. Your new Full Name field will be available as a block. But when you add it and try to save, you get the fatal error about the missing bundle() method. Because the entity for the "current_user" context is set to $GLOBALS['user'], which is just a stdClass object.

**Comment by bradbulger** [comment] 2020-01-23 16:29
I should probably write a test to go with this? I'll see if I can figure that out based on what's there.

**Comment by indigoxela** [comment] 2020-01-24 07:32
Ah, now I got it!

I can confirm that the PR fixes it.

**Comment by bradbulger** [comment] 2020-01-24 19:04
I guess the question is, would the preferable fix be to put a complete entity into $GLOBALS['user']? I don't know who would have an opinion about that or what the pros/cons are.

**Comment by indigoxela** [comment] 2020-01-25 09:32
> ...to put a complete entity into $GLOBALS['user']

That's indeed a good question. I'd vote for it, but am of course not the one to decide.

**Comment by herbdool** [comment] 2020-06-07 17:15
I think it's good to go as is. Except still needs a test.

I don't think we want to load the whole object into the globals. I believe there's a reason it wasn't done in the first place. I don't recall exactly but probably having to do with keeping it efficient.

**Comment by bradbulger** [comment] 2020-09-18 16:24
I closed the old PR and create a new one rerolled on the current backdrop 1.x branch. I don't know how to create an automated test, unfortunately. I will see if I can figure it out.

**Comment by klonos** [comment] 2020-09-19 06:43
Thanks for picking this up again @bradbulger 🙏 ...can you please add the magic keyword "fixes" in the PR 1st comment, followed by a link to this issue? That will make it so that the PR is linked to this issue via the metadata sidebar on the right 😉

**Comment by klonos** [comment] 2020-09-19 06:49
...code looks good in general, but left some comments in the PR re coding standards.

**Comment by bradbulger** [comment] 2020-09-19 17:32
The standards aren't explicit about inline comments and IF ELSE blocks. The idea was to comment on the action being taken in one case vs the other. If both comments are outside of the conditional block, isn't that less clear?

**Comment by bradbulger** [comment] 2020-09-19 17:56
I have somehow connected this and/or the pull request to an unrelated issue :(

**Comment by bradbulger** [comment] 2020-10-06 21:37
I rebuilt the [PR](https://github.com/backdrop/backdrop/pull/3362) and added a test to add a custom field to user and check its availability as a field block in a new layout.

**Comment by herbdool** [comment] 2020-10-07 04:55
Thanks @bradbulger! I can hopefully look at it tomorrow.

**Comment by herbdool** [comment] 2020-10-07 16:39
@bradbulger I took a look and left a comment - we need to add to the test viewing the layout and ensuring the field is visible.

**Comment by bradbulger** [comment] 2020-10-07 16:54
I saw that, thanks. I'm giving it a shot.

**Comment by bradbulger** [comment] 2020-10-07 18:22
I added a test for putting a value into the new field and finding it displayed on the new layout, it's working for me. (There are multiple unrelated failures in the layout test due to other issues.)

**Comment by herbdool** [comment] 2020-10-11 14:10
Looks good now. Thanks @bradbulger

**Comment by stpaultim** [comment] 2020-10-11 16:50
This still has the tag, "needs - automated tests." Is this true or does the tag need to be updated/

**Comment by herbdool** [comment] 2020-10-12 16:13
Good catch

**Comment by quicksketch** [comment] 2020-10-17 22:24
This solution seems mostly good to me. It definitely fixes the bug where field blocks can't be pulled from the "current_user" context. The new tests look great.

In the current PR, this change makes it so that the current user entity is loaded on every page load (since Layouts are used on every page). Now that we have Entity Caching in core, this only results in two additional queries per page load (less than 0.10 ms on my local).

As for why `$GLOBALS['user']` doesn't contain the full entity, I don't really know either. As pointed out above though, the anonymous user object isn't at all the same as a logged-in user object. Anonymous users can't have fields or really any meta data assigned to them at all.

Overall, what I think I'd like to see is that we fully load the user object inside of `FieldBlock::getContent()`, rather than always loading the full user object all the time even if we don't need the fields in the layout. Any thoughts on that approach?

**Comment by bradbulger** [comment] 2020-10-18 01:36
I'm away from being able to look at my codebase. I wonder if that's too
deep, like if there would be other subsequent problems caused by not being
a User entity. If not, then sure.

**Comment by BWPanda** [comment] 2020-10-29 23:30
> Overall, what I think I'd like to see is that we fully load the user object inside of `FieldBlock::getContent()`, rather than always loading the full user object all the time even if we don't need the fields in the layout. Any thoughts on that approach?

I second that. If we can get a PR to that effect and it fixes the bug while not adding additional and unnecessary DB queries, I think that's the way forward here.

**Comment by stpaultim** [comment] 2021-01-03 01:06
I spent time today experimenting with contexts and relationships (to help me understand this issue: https://github.com/backdrop/backdrop-issues/issues/2134)

During my experiments, I realized that if I added a field to the user profile, this new profile field is immediately available to layouts, but that if I try to add this field to a layout it generates an error. 

This Pull Request seems to fix that problem, unfortunately I'm not able to comment on the request that "we fully load the user object inside of FieldBlock::getContent()."

This seems to be the blocker for getting this bug fixed.

**Comment by bradbulger** [comment] 2021-01-05 00:19
I moved the loading of a User object into FieldBlock::getContent(). I left the layout_current_user_context() function, it just loads $GLOBALS['user'] as the initial data.

**Comment by herbdool** [comment] 2021-01-05 19:54
@bradbulger looking close! I've added a couple suggestions and tested.

**Comment by herbdool** [comment] 2021-01-11 17:31
@bradbulger one more suggestion.

**Comment by bradbulger** [comment] 2021-01-11 19:09
Should I close that pull request and redo it as one commit?

**Comment by herbdool** [comment] 2021-01-11 19:15
@bradbulger don't worry about that. You can keep adding your commits to this. It will get squashed when merged.

I was just testing it again. There's one small thing which I thought would work but doesn't. I created a layout with user/% path and added a field as block with the context from the path.

![Screenshot from 2021-01-11 14-13-03](https://user-images.githubusercontent.com/1071483/104227286-27952980-5417-11eb-87fd-ed31c06f0d22.png)

As a logged in user I can see that field block. But when logged out, even if anonymous has permission to see the user profile, I cannot see the field block.

**Comment by bradbulger** [comment] 2021-01-11 19:17
the context is the currently logged in user. that you happen to be looking at some other user's page is irrelevant.

**Comment by bradbulger** [comment] 2021-01-11 19:18
So maybe "Field from the available user account content" is ambiguous or misleading?

**Comment by herbdool** [comment] 2021-01-11 20:01
I think you misunderstand me. I know the difference in setting the context to the "User from path" vs "current user". If the context is "User from path" *and* viewing the user profile, it should not matter *who* is viewing it (assuming they have access to the user profile). They should see that field on the user profile. But that isn't working if the user is not logged in.

**Comment by bradbulger** [comment] 2021-01-11 20:33
Ah, there is an option in the block configuration settings, I hadn't noticed. I added a block to the content area on the tugboat site for the pull request and it seems to be working
https://pr3479-fuvggjvag8gj4kchdrraanzfxfxtwosx.tugboat.qa/accounts/test

**Comment by bradbulger** [comment] 2021-01-11 20:35
That makes me think that "current_user" is misleading but that's probably not worth pursuing. Maybe a comment on the new layout_current_user_context() function?

**Comment by herbdool** [comment] 2021-01-11 20:46
Now that I look at it again, it's visible to anonymous. I probably forgot to clear the cache on tugboat (I usually leave caching disabled when I'm working). All good for now.

**Closed** 2021-01-16 00:33 UTC
Labels: pr - ready to be committed, pr - works for me, status - has pull request, type - bug report

**Comment by quicksketch** [comment] 2021-01-16 00:36
I have merged https://github.com/backdrop/backdrop/pull/3479 into 1.x and 1.17.x. Thanks @MrHaroldA for filing this issue; thanks @bradbulger, @indigoxela, @herbdool, @docwilmot, @BWPanda, @klonos, and @stpaultim for your work completing this solution!
