### ISSUE TITLE
[UX] Regression: Views dialogs are rendered partially off-screen and submit buttons are unreachable 

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6076] opened 2023-04-22 04:54 UTC
## Description of the bug

I think a recent update may have caused this, but views modals seem to be taking up more of my browser window than the whole "admin area" of the site, which seems a little weird for a modal (which is usually smaller) - but most importantly, 
**I can't use the modal because it's now pushed below the part of the screen I can see, so I can't reach the submit buttons on it to submit the modal form.**

<img width="1602" alt="Screenshot 2023-04-21 at 9 50 35 PM" src="https://user-images.githubusercontent.com/397895/233763290-23ab68dc-1d6a-43c5-bfd0-07df9dc37660.png">

## Steps To Reproduce

To reproduce the behavior:
1. Update to 1.24.1 (or newer)
2. Attempt to add a filter to the user/account admin listing

## Actual behavior

Unable to "reach" submit buttons.

## Expected behavior

It should be possible to use the modal. 

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.24.1 (or newer)

## Related issues

* https://github.com/backdrop/backdrop-issues/issues/6077

------

PR https://github.com/backdrop/backdrop/pull/4501

**Comment by argiepiano** [comment] 2023-04-22 14:02
I've noticed this in Chrome as well. Usually, when you scroll down you can "force" the modal to jump back to the right place and location. We found and fixed a [slightly similar issue](https://github.com/backdrop/backdrop-issues/issues/5835) with the image library modal. In that case it was due to the fact that the screen was painted before 
the needed css was loaded (through ajax). The solution implied using a setTimeOut.

Have you tried other browsers? Firefox did not present this, as I recall.

**Comment by olafgrabienski** [comment] 2023-04-24 07:37
> more detailed steps to reproduce, maybe the relation between views display size and browser window size?

Ha, just tested on the same demo site as above: After resizing the browser window from a height of about 840px to approx. 640px, I was able to reproduce the issue, both in Chrome and Firefox.

**Comment by argiepiano** [comment] 2023-08-18 03:30
Couple more observation: 
- If you click "ADD"  right after you open the view configuration UI (without doing ANY scrolling before clicking ADD), the modal will open correctly:

<img width="1332" alt="Screen Shot 2023-08-17 at 9 28 19 PM" src="https://github.com/backdrop/backdrop-issues/assets/9938978/84d1310e-4505-4f5d-ba78-b1fc84d542c0">


- If you first scroll down the UI, and then click "ADD", the modal will open incorrectly (half way through the screen)
- The more you scroll, the more screwed up the modal will be

<img width="1312" alt="Screen Shot 2023-08-17 at 9 30 07 PM" src="https://github.com/backdrop/backdrop-issues/assets/9938978/858fa18d-b43f-4d50-a6c7-653935ef3aa7">

**Comment by argiepiano** [comment] 2023-08-18 23:44
OK, this is what I found out: the problem with the dialog appearing half-way off screen is a jQuery UI Dialog bug, reported [here](https://bugs.jqueryui.com/ticket/8741). This was fixed in [version 1.13.2](https://github.com/jquery/jquery-ui/releases/tag/1.13.2), released in July last year. Unfortunately, Backdrop uses version 1.13.0. 

@inigoxela, you've worked updating Backdrop's jQuery UI in the past. What would be the best way to update the Dialog widget to 1.13.2 (the latest version)?  Or should we update the WHOLE jQuery UI library to that version? Please advise :)

**Comment by argiepiano** [comment] 2023-08-19 01:33
Well, no. That was not it. The fix is a simple change in the css. That change already exists in `jquery.ui.dialog.css`, but is overridden in Seven's `style.css`.  But, still, making that change in `style.css` doesn't fix the problem. It looks like, in Backdrop, the css `top` property for the dialog wrapper is recalculated and overridden inline somewhere. 

So, more digging and debugging needed 😞

**Comment by laryn** [comment] 2023-08-19 02:02
This one should be merged soon:
https://github.com/backdrop/backdrop-issues/issues/5705

I almost got to it yesterday but got sidetracked looking at the unrelated code formatting test failure.

**Comment by argiepiano** [comment] 2023-08-19 03:12
Thanks, @laryn. I patched BAckdrop with that PR, but it doesn't solve the problem of the OP here.

**Comment by argiepiano** [comment] 2023-08-19 04:32
OK now I have found it. The problem started when https://github.com/backdrop/backdrop-issues/issues/5835 was merged. Bear with me:

- One of the puzzling aspects of the bug was that the Layout dialogs worked fine, but Views did not, even if you open the dialog in similar contexts, that is, when you first open the modal after having scrolled down on the page: Views modal was off he screen, while Layouts were not
- Step debugging through Javascript showed that the problem does exist for a split second in Layouts too. But it gets corrected right away by a call to `resetPosition()` in `Backdrop.dialog.openDialog()`, which is triggered by the new code added in the PR above. That code waits for specific CSS `overflow: auto` to be loaded before calling `resetPosition()`
- The problem basically is that Layouts (as well as the Image dialog, which was fixed by that PR) use `overflow: auto`, which the Views dialog uses `overflow: hidden`
- Therefore, `resetPosition()` is never invoked when using Views dialogs. In fact, there is an **infinite JS loop** created by `setTimeout(waitForCss, 10);` (see [line](https://github.com/backdrop/backdrop/blob/0ac5151950728357985c4202f4bece1247381890/core/misc/dialog.js#L92)). That loop probably impacts JS performance in the browser.

So, a possible solution is to modify the [if statement in line 85](https://github.com/backdrop/backdrop/blob/0ac5151950728357985c4202f4bece1247381890/core/misc/dialog.js#L85) to also check for `hidden` (which is what Views dialogs use). 

I've done some testing with this, and it seems to solve the problem. It does not impact other dialogs, including the image dialog problem solved by that other PR.

Another possible solution is to get rid of the if statement, and create a single, longer setTimeout to assure the CSS has loaded. This would avoid the potential for infinite loops if overflow is neither auto, nor hidden for a specific dialog. 

I'll try with the first approach. PR coming.

**Comment by argiepiano** [comment] 2023-08-19 04:46
PR https://github.com/backdrop/backdrop/pull/4501

Let's get this SUPER annoying bug fixed!

**Comment by argiepiano** [comment] 2023-08-19 14:36
I was uneasy about the potential of infinite loops similar to the one seen in this issue, when overflow is neither hidden, nor auto. So, I added a safeguard to only allow `setTimeout` to reschedule the check for overflow up to 10 times (100 milliseconds), and after that just run `resetPositiion()` as a preventive measure.

An alternative way is to simply remove all those checks, and simply schedule the run of `resetPosition()`  100 milliseconds in the future, but I still think it's worth doing this check in 10 millisecond intervals. In my testing, only one reschedule is necessary, meaning that `resetPosition()` can be run pretty quickly after the page rendering.

**Comment by indigoxela** [comment] 2023-08-20 12:00
One of my pet peeves gets fixed! :tada: 

Works for me! Tested on Firefox ESR and Chromium, which are both affected. :+1:

**Comment by indigoxela** [comment] 2023-08-20 12:03
> I almost got to it yesterday but got sidetracked looking at the unrelated code formatting test failure.

@laryn FTR: These will get fixed soon, I've added a comment at the (unrelated) PR. :grinning:

**Comment by quicksketch** [comment] 2023-09-06 04:37
Code looks good to me too. I like the added check to prevent infinite loops. I tested it in latest Firefox and Chromium and saw no ill effects.

**Closed** 2023-09-06 04:39 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2023-09-06 04:40
Great work @argiepiano hunting this down. And thanks @jenlampton, @olafgrabienski, @laryn, and @indigoxela for testing and reporting your different situations. Great job triaging this tricky issue!
