### ISSUE TITLE
When editing in source mode (inside a dialogue window) changes are not saved unless you switch back out of source mode

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1259] opened 2015-09-26 19:55 UTC
**Issue Summary (UPDATED July 31, 2020):**

If you edit a text field inside of a dialogue block (is that the right term) using the source mode and do not turn the source mode off before saving, your changes are lost. 

It had been thought that this problem was specific to custom blocks, but during a recent dev meeting we speculated (and later confirmed) that the problem is related to dialogue windows and NOT custom blocks. The same behavior happens when editing a view header with CKEditor in source mode (which happens in a dialogue window). 

The problem does NOT exist when creating a custom block on the custom block page (which does not use a dialogue window). It does happen when adding a custom block in directly to the layout (which does happen in a dialogue window). 

**Steps to reproduce:**

- Download and install Backdrop CMS (happening as recent as 1.16.2)
- Create a custom block. (/admin/structure/block/add)
- Add a layout (/admin/structure/layouts/add)
- Add the custom block to the layout.
- Click the "Configure" button to the right of the custom block.
- In the "Block content" editor input, click the "Source" button.
- Edit the block content.
- Click "Update block"
- Click "Save layout"

**Proposed Solution**

Look at core/misc/dialog.ajax.js to see if we are using the correct JQuery handler/event or series of handlers/events to process this action. 

(SEE comments on July 31, 2020)

**Original Issue:**

If we try to change image URL (created before in our block) then it would not be saved if it is done in Source mode. You need to switch to normal mode after the change then it will be saved.

**Comment by sutibun** [comment] 2015-09-26 19:58
@bd0bd I'm totally useless here but I have a question. what software/app/plugin do you use to take screenshot and add the text + arrows?

**Comment by bd0bd** [comment] 2015-09-26 20:05
I make screenshot by pressing Print Screen button on my keyboard.
Then in Adobe Photoshop I paste it in, crop and add text with arrows.
Sure, Photoshop is not best solution for normal users but I am a little bit abnormal + I use it from around 1996.

**Comment by sutibun** [comment] 2015-09-26 20:13
@bd0bd ah kk. I thought you had something that does this quick. Don't have Photoshop in this computer and probably too much work for me. Thanks anyway.

**Comment by bd0bd** [comment] 2015-09-26 20:15
I understand you. Thank you!

**Comment by Graham-72** [comment] 2015-09-27 05:29
About screenshots : some weeks ago @quicksketch recommended Awesome Screenshot for this and it is a great help. It is available as an add-on for Firefox and Chrome, and perhaps others.

**Comment by quicksketch** [comment] 2015-09-27 17:32
Thanks @bd0bd for the issue report. This seems like it may be caused by CKEditor. We should look for a fix upstream and update our library if needed. We're running `4.4.7`, the newest version is `4.5.3`. Seems like an update is worth doing in any case.

**Comment by sutibun** [comment] 2015-09-28 02:15
@Graham-72 ooh, that's good. I'll be using it. Thanks.

**Comment by klonos** [comment] 2015-09-29 01:32
> We're running ```4.4.7```, the newest version is ```4.5.3```.

Do we have any specific policy/procedure of regularly updating our libraries or at least the "major" ones (currently jQuery and CKeditor fit this category I guess)? Shouldn't we establish a procedure to do that at least with minor releases (when releasing 1.2.0, 1.3.0 etc.)? That will ensure that we have the latest fixes in (although some might argue that also the latest bugs).

**Comment by BWPanda** [comment] 2016-11-14 22:39
I am having issues with this, but with any changes, not specifically just image URLs (I've updated the title accordingly).

If you edit a block (either through the normal WYSIWYG or in Source mode) and then *change to Source mode before saving*, the changes aren't saved and the block stays the same.

To replicate:

1. Add a custom block with some text and assign to a region.
2. Edit that block to change the text (e.g. add '2' to the end). Don't change to Source mode in CKEditor at all. Save. The block is updated.
3. Edit the block again to change the '2' to a '3'. Change to Source mode and save. The block is not updated (it still displays '2').

**Comment by laryn** [comment] 2016-11-14 23:05
Ditto to exactly what @BWPanda described, with the additional info that changing to source mode, editing, and then changing out of source mode before saving seems to work.

**Comment by laryn** [comment] 2017-05-03 18:08
Another update on this one -- I don't think it's a CKEditor upstream issue (as @quicksketch [suggested](https://github.com/backdrop/backdrop-issues/issues/1259#issuecomment-143579955)) because it seems to work when editing other fields. 

I just hit save on a taxonomy term description edit in source mode and then had a sinking feeling ("Oh no, I just lost all my edits again") but it actually saved the changes. It seems to just be custom blocks that have this issue?

**Comment by bd0bd** [comment] 2017-05-04 11:47
It does not save in Source mode.
Each time I need not to forget to switch back before saving any blocks.
Headache.

**Comment by laryn** [comment] 2017-05-04 18:09
@bd0bd Are you saying it doesn't work in source mode for taxonomy descriptions, either, or just for custom blocks, as I was suggesting?

**Comment by bd0bd** [comment] 2017-05-04 18:53
Any custom block when it is edited in Layouts.
Before pressing on UPDATE BLOCK blue button we need to switch to normal mode.

**Comment by olafgrabienski** [comment] 2017-11-06 14:17
In the last days I've worked quite a lot with custom blocks and experienced this very issue with unsaved block content. I confirm that content of custom blocks doesn't get updated if you switch to Source mode of the editor and don't switch back to the Wysiwig mode before saving the block.

As suggested by @laryn in https://github.com/backdrop/backdrop-issues/issues/1259#issuecomment-298990310, it think also it's an issue with custom blocks but not with other long text fields or CKEditor in general. When you edit for instance the body field of a content (node) item in Source mode without switching back to Wysiwyg the content gets however saved without any issue.

**Comment by olafgrabienski** [comment] 2017-11-06 14:20
Tagged with milestone 1.8.1.

**Comment by Radcliffe** [comment] 2018-12-08 21:54
This is still an issue for us. Confirmed on a fresh install of v1.11.2.

**Comment by klonos** [comment] 2018-12-09 13:18
...adding a milestone to help keep this within our radars for the next bug release.

**Comment by stpaultim** [comment] 2018-12-09 22:57
I just updated the issue summary to reflect that @serundeputy tested this issue against this pull request which did not solve the problem. backdrop/backdrop#2361

This seems to rule out CKEditor being the source of the problem.

**Comment by stpaultim** [comment] 2020-05-07 21:19
I ran into this again today and we discussed it VERY briefly before the dev meeting and in Zulip. 

I think I will try to advocate for this issue in coming weeks (after 1.16) to get some attention, because it's a huge annoyance and particularly difficult for new users who have not seen the problem before. Once you know it's there, it's easy to work around. 

Does anyone have any theories on what may be causing this?

**Comment by laryn** [comment] 2020-05-08 13:20
I tried to look at this again but came up empty. These seemed potentially relevant but didn't help me solve it:
 - [ckeditor getData() returning stale data (last change missing) in source mode](https://stackoverflow.com/questions/33261102/ckeditor-getdata-returning-stale-data-last-change-missing-in-source-mode?noredirect=1&lq=1)
 - [detecting changes with ckeditor](https://stackoverflow.com/questions/5230839/detecting-changes-with-ckeditor)

**Comment by olafgrabienski** [comment] 2020-05-10 22:08
Searching for `ckeditor does not save source mode` on the web, there are some interesting results like [CKeditor does not update text area in source mode](https://stackoverflow.com/questions/12071145/ckeditor-does-not-update-text-area-in-source-mode), but I've not the code skills to assess if they're helpful here.

Another idea: is it possible to implement a workaround (for the time being) where the editor is forced to switch out of source mode upon saving?

**Comment by stpaultim** [comment] 2020-05-13 02:15
I don't know if this issue is related. But, there is a width option for tables in CKEditor, but it doesn't seem to work. Changes don't seem to register.
https://github.com/backdrop/backdrop-issues/issues/1251

**Comment by jenlampton** [comment] 2020-07-23 20:52
Can we also test these and see if it's still a problem there?
* the ckeditor in the views "Global formatted text" field  (in a dialog - not a block)
* The add block from that's not in a dialog

**Comment by stpaultim** [comment] 2020-07-25 22:55
OK, great insights share in last dev meeting. I ran the tests that @jenlampton suggested and determined that in fact the problem is related to whether or not the change is made in a dialogue box. 

1) If I edit the header of a view using the source mode, the changes are not saved (this uses a dialogue window). 
2) If I edit a custom block using the custom block creation page (admin/structure/block - does not use a dialogue window) I can edit is source mode and save without problems. 

This bug is seems to be related to how we save content in a dialogue window and is NOT specific to custom blocks. This indicates that it is probably not a CKEditor issue, but a Backdrop CMS issue. I will update the issue summary.

**Comment by klonos** [comment] 2020-07-26 13:59
Glad to see getting to the bottom of this old bug 👍

**Comment by stpaultim** [comment] 2020-08-01 04:35
We talked about this in weekly dev meeting yesterday. I'm not sure I can fix this, but Nate provided some helpful (hopefully) advice to anyone interested in submitting a PR. 

Here is my attempt to summarize comments by @quicksketch taken from 15:00 minutes into recording of meeting (https://www.youtube.com/watch?v=C9uBdciSeSU):

- - - - - - - - - - 

When you save a dialogue in Backdrop CMS it also submits an AJAX request.  We have a javascript file "core/misc/dialog.ajax.js" that we use to process this action/request. 

When a user clicks the "submit" or "add block" button in the dialogue, we're using JQUERY to click on the actual submit button and we are probably using the wrong click handler or wrong sequence of handlers/events to manage this action. 

It might be that we're telling it to "mousedown" and we need to tell it to "mousedown" and "follow with click."

**Comment by klonos** [comment] 2020-08-01 05:22
> It might be that we're telling it to "mousedown" and we need to tell it to "mousedown" and "follow with click."

Unless I'm mistaken, we are already doing that: https://github.com/backdrop/backdrop/blob/1.x/core/misc/dialog.ajax.js#L62 🤷

**Comment by stpaultim** [comment] 2020-08-01 21:16
> Unless I'm mistaken, we are already doing that

I think that @quicksketch was providing a hypothetical example. I understand his point was to do something different from what we are currently doing.

**Comment by quicksketch** [comment] 2020-08-20 20:04
I'll volunteer to try and take a look at this problem.

**Comment by quicksketch** [comment] 2020-08-29 20:55
This problem was a weird one... it seems as though when Backdrop detaches behaviors from a part of a page (such as when closing the dialog), the textarea that has CKEditor applied to it must be in its original state. If it's been modified, CKEditor loses track of it.

Weirdly there's just a single parameter you can pass to CKEditor to tell it to look a little harder for the textarea, by passing `optimized = false` to `CKEDITOR.dom.element.get(element).getEditor();`. Then it finds the textarea just fine, and the value saves.

So this seems like a one-line fix with several lines of code comments. Testing and feedback appreciated: https://github.com/backdrop/backdrop/pull/3272

**Comment by stpaultim** [comment] 2020-08-29 22:22
Works for me. 

I tested this on custom blocks and in views and it now works as expected in both scenarios.

**Comment by olafgrabienski** [comment] 2020-08-29 23:29
Will check tomorrow.

**Comment by klonos** [comment] 2020-08-30 05:47
>this seems like a one-line fix

😌 ...thanks for figuring this one out @quicksketch 🎉 ...the inline comment may be a tad too technical, so how about adding a reference to the most obvious side-effect? Something like "for example, when the editor is on a dialog".

**Comment by olafgrabienski** [comment] 2020-08-30 14:42
> Can either of you double check my testing and confirm this works as expected?

@stpaultim Works for me as well in custom block and views dialogues.

Does anyone has ideas what to look at to check if the PR has unwanted side effects?

**Closed** 2020-08-30 21:48 UTC
Labels: pr - ready to be committed, pr - works for me, status - has pull request, type - bug report

**Comment by BWPanda** [comment] 2020-08-30 21:51
Thanks everyone for your help with reporting, confirming, fixing and testing this issue! Particularly to @quicksketch, @bd0bd, @laryn, @olafgrabienski, @Radcliffe, @stpaultim & @klonos.. I've merged https://github.com/backdrop/backdrop/pull/3272 into 1.x and 1.16.x.

**Comment by quicksketch** [comment] 2020-08-31 16:30
> Does anyone has ideas what to look at to check the PR for unwanted side effects?

CKEditor is the only thing affected, so places where it is used are the best additional places to check. In particular this affects when CKEditor is removed from the page but the value needs to be saved. I can't think of any other places where this occurs other than in dialogs.

**Comment by laryn** [comment] 2020-08-31 16:34
@quicksketch Any chance it could accidentally help with this one? https://github.com/backdrop/backdrop-issues/issues/3293

**Comment by olafgrabienski** [comment] 2020-08-31 20:30
> The only other place I can think where this happens besides dialogs is in multi-field situations like Paragraphs or Multifield.

Ha, I think I've found a similar situation: multiple long text fields. Steps to reproduce (without this PR):

- Change the settings of the Body field of your content type (e.g. Page) to allow unlimited values.
- Add a page, put some text in the Body field, format a phrase as bold text, and change CKEditor to source mode.
- Add another item of the Body field.

Result: The bold formatting in the first Body field is not saved (the bold phrase changed back to normal). In some cases, the text of the first Body text even disappears completely - wasn't able to reproduce this reliably, though. I also haven't checked so far if this PR changes anything.

Finally, I tested the steps using a newly added Long text field instead of the Body field but wasn't able to reproduce the behavior then.
