### ISSUE TITLE
Permissions shown on /admin/config/people/permissions/editor do not match the permissions shown on /admin/config/people/permissions for the same role

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6127] opened 2023-05-25 20:58 UTC
I checked my site after updating it to Backdrop 1.25. When I verified the permissions given to the *Editor* role (to understand what changed for that role), I noticed the *View published content* permission was not selected, on /admin/config/people/permissions/editor.

> ![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/1feb0982-9786-414e-aafb-0c4982fc7bac)

I then checked which roles had that permission, on /admin/config/people/permissions, and noticed this.

> ![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/2c72a471-9df3-4cd1-a295-aea21738bd9b)

That page tells me the *Editor* role has the permission to view published content, even though that permission is not shown as selected in the page for the *Editor* permissions.

**Comment by olafgrabienski** [comment] 2023-05-30 12:43
I can confirm the behavior (tested on a Tugboat demo site).

> I thought it would happen for every permission given to the _Authenticated_ role, but when I assigned the _View own unpublished content permission_ to the _Authenticated_ role, what I described in this issue did not happen.

There are however permissions where the same thing happens, e.g. _View comments_. And there are others where it does not happen, e.g. _Use the Filtered HTML text format_.

**Comment by kiamlaluno** [comment] 2023-06-24 15:48
@olafgrabienski That is… curious. Could that happen for permissions that role already had?

**Comment by olafgrabienski** [comment] 2023-06-26 13:37
> Could that happen for permissions that role already had?

Sounds reasonable, but I didn't check other / all permissions so far. (No time atm.)

**Comment by kiamlaluno** [comment] 2023-07-15 14:28
I would say it works as expected: /admin/config/people/permissions/editor shows the permissions explicitly assigned to the *Editor* role, while /admin/config/people/permissions makes evident that permissions given to the *Authenticated* role are also permissions for the *Editor* role, since the latter is a role given to people who logged in on a site (and therefore, they have been authenticated).

**Closed by kiamlaluno** 2023-07-15 14:28 UTC
Labels: status - works as designed
