### ISSUE TITLE
[UX] Add vertical tabs and permissions to vocabulary edit forms

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#38] opened 2013-09-10 06:17 UTC
We have design patterns for the node form that should also be extended to other entity forms.  For example, taxonomy terms can also have Paths and Menu items, so the same UI to add these things should be present in both places.

**Comment by jenlampton** [comment] 2016-01-15 06:30
I just pushed a PR that 1) adds vertical tabs on the vocabulary form and 2) adds the permissions matrix onto the vocabulary form, in that vertical tab set.  There is also some work in this PR that should help pave the way for https://github.com/backdrop/backdrop-issues/issues/382 as it will now be easier to add additional permissions per-vocabulary.

**Comment by jenlampton** [comment] 2016-01-15 06:43
Optimistically changing milestone?

**Comment by quicksketch** [comment] 2016-01-16 00:00
Per the feedback in https://github.com/backdrop/backdrop/pull/1209#issuecomment-172126929, looks like this added permissions to the form but isn't actually saving them. (Thanks @docwilmot)

**Comment by jenlampton** [comment] 2016-01-16 00:57
Updated submit handler, and rebased for latest 1.x

**Comment by quicksketch** [comment] 2016-01-16 01:03
When we added the permissions to the node type form, we added tests as well to check that they worked. We'll need tests here as well, obviously they would have failed if the permissions weren't getting saved from the vocabulary configure page.

**Comment by docwilmot** [comment] 2016-01-16 01:08
Saving confirmed working

**Comment by jenlampton** [comment] 2016-01-16 02:01
tests on the way!

**Comment by jenlampton** [comment] 2016-01-16 02:19
Pushed a new PR with tests (thanks @docwilmot I stole / modified them from the node tests)

**Comment by quicksketch** [comment] 2016-01-16 02:34
Fixed in https://github.com/backdrop/backdrop/pull/1209. Thanks @jenlampton for putting this together at the last second. And @docwilmot for providing most of the code that we swiped from the Content Type form. :wink:

This is the last item on the docket for 1.3.0.

**Closed by quicksketch** 2016-01-16 02:34 UTC
Labels: pr - needs review, status - has pull request

**Comment by docwilmot** [comment] 2016-01-16 02:41
> This is the last item on the docket for 1.3.0.

Woohoo! Well done to @quicksketch and @jenlampton and everyone else. It's been a marathon couple of weeks. Good work.

**Comment by quicksketch** [comment] 2016-01-16 08:27
I'm very happy with everything that finished for 1.3.0. I'll be making articles and hopefully a screencast this weekend so we can tell everyone all about it. :smile:
