### ISSUE TITLE
Inconsistent use of styles on Flexible Template Builder UI

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6325] opened 2023-12-06 23:02 UTC
## Description of the bug

The UI for building a Flexible Template has some unusual CSS patterns that are not consistent with the rest of core. This page should have similar design patterns to the Manage Blocks page. That said, the elements we are moving around are not blocks, so they should not match the pattern for blocks on the manage block page to avoid confusion.

<img width="1502" alt="Screenshot 2023-12-06 at 2 56 05 PM" src="https://github.com/backdrop/backdrop-issues/assets/397895/be20661e-f893-43f0-87e5-6c76bebbd8ed">

Some individual problems are noted below, but this page could probably use a a design review / refresh as a whole.
* Strange spacing between border and interior
* use of blue dotted line (unique to only this page)
* box shadow too large (should be `box-shadow: 2px 2px 0 0 #d0d0d0;` for consistency)
* combination of box-shadow and dotted line looks strange

**Comment by stpaultim** [comment] 2024-01-14 07:29
I took a stab at making some improvements here. Sure, we could always use a designer input, but is this good enough (with feedback) to move forward until we get a designer. (Actually, I did get input on most of the changes I made today from a designer at Twin Cities Drupal January sprint). 

Before:

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/c00411e8-5abe-4bd0-816c-5b2814471f42)

After:

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/24ba33df-0078-4250-b4da-86ed0073669e)

I welcome thoughts and ideas for improvement.

**Comment by yorkshire-pudding** [comment] 2024-01-18 08:29
@stpaultim - it is a definite improvement.  I don't have any suggestions for improvement and I would be happy with this.

**Comment by stpaultim** [comment] 2024-01-18 22:31
@yorkshire-pudding I put this on the agenda for the design/ux meeting next week. 

I'm open to suggestions for how to make this revision better OR we could work incrementally and make more changes later.

**Comment by yorkshire-pudding** [comment] 2024-01-18 22:32
> @yorkshire-pudding I put this on the agenda for the design/ux meeting next week. 
> 
> I'm open to suggestions for how to make this revision better OR we could work incrementally and make more changes later.

Unless there are concrete suggestions, I'm a strong fan of incremental improvement

**Comment by klonos** [comment] 2024-02-01 21:51
Some feedback from today's dev meeting:
1. looks good and is definitely an improvement 👍🏼 
2. the cursor should be a "vertical move" cursor (up/down) - while the current cursor is a "move cursor" (all directions, which is wrong for the flexible layouts UI, as the rows can only be moved up/down), and the PR changes it to a default "select text" cursor (which is a regression)
3. some attention in the left/right/up margins of the row headers (they should be removed, so that the row "attaches" to the border of the container)
4. The font size of the row header text is smaller than the respective used in the blocks layout - needs to be adjusted.

(I hope I captured everything)

**Comment by stpaultim** [comment] 2024-05-07 04:37
PR is about to get updated:

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/6c76f6a7-dedb-43ad-b476-965d857e71a2)

I changed the cursor to the one we were using before. I did not do an up/down cursor, because I did not see one in standard CSS and it seems we have not yet implemented #5152

**Comment by stpaultim** [comment] 2024-05-08 04:24
Incorporated feedback from @jenlampton . Thanks so much for taking a look. I appreciate it.

**Comment by klonos** [comment] 2024-05-08 07:58
@stpaultim #5152 is in order to change the drag icon (the one to the left of the row titles) to a .svg provided by the Phosphor icon set in core (point 3 in my previous comment in this thread), whereas what needs to be changed to up/down is the standard mouse cursor CSS property to be `cursor: row-resize;` (which is point 2 in my previous comment). See https://www.w3schools.com/cssref/pr_class_cursor.php and https://www.w3schools.com/cssref/playit.php?filename=playcss_cursor&preval=row-resize specifically.

One thing that has been mentioned before is the lack of sufficient contrast with the various shades of gray and white we use, but we have #1632 for that. What we could do here though is to add some border to the regions. If we go with the same dashed border as in the "Manage blocks" UI (`border: 1px dashed #CCC;` instead of the current `border: 1px solid white;`), then it would suffice and be consistent I believe.

Other than those issues, I think that this good to go. Thanks @stpaultim 🙏🏼

**Comment by klonos** [comment] 2024-05-08 08:05
>If we go with the same dashed border as in the "Manage blocks" UI ...

...actually, simply removing the following fixes that (I've added a comment in the PR):
```css
.l-flexible-row .layout-editor-region {

```

**Comment by stpaultim** [comment] 2024-05-08 22:58
> standard mouse cursor CSS property to be cursor: row-resize;

I looked for a standard cursor that did this and did not find this one on my own. Thanks for pointing this out. Change made, along with your other suggestions. 

Does anyone else have any thoughts on this PR?

**Comment by jenlampton** [comment] 2024-05-08 23:26
@klonos @stpaultim As soon as we get rid of the dotted lines on the regions, I think this is RTBC! 

The dotted lines mean "you can drop things here" and since we are dragging rows on this page (and not blocks) and since rows cannot be dropped into regions, the dots need to go. (This was discussed very early on, I think, you may have missed that part of the discssion @klonos.)

**Comment by jenlampton** [comment] 2024-05-08 23:38
We could be a little more consistent with the manage blocks interface if we made the main background gray, and provided a drop-zone for rows with a white background and gray dashed border.

Add the same styles on `#layout-flexible-edit-main` as are on `#layout-edit-main`. 
```
#layout-edit-main {
    padding: 20px 0 0;
    border-radius: 4px;
    background-color: #f7f7f7;
    border: 2px solid #EAEAEA;
}
```

Then also add these to `#layout-flexible-edit-main`
```
	padding: 15px 15px 0;
    margin: 0 15px;
    border: 1px dashed #ccc;
    background: #fff;
```

I'll make a PR against your PR @stpaultim

**Comment by jenlampton** [comment] 2024-05-09 00:13
@stpaultim I'm not sure I like this any better, so I provided an alternate PR where people can see what the page would look like with a drop-zone for rows: https://github.com/backdrop/backdrop/pull/4738

Here's the page with an additional drop-zone for rows added (more consistent with manage blocks)
![Jen-test-My-Backdrop-Site](https://github.com/backdrop/backdrop-issues/assets/397895/ea3e8cca-2381-401b-91ca-6b1c4293bbc6)

I think I prefer the current PR but without the drop-zone for blocks:
![Jen-test-My-Backdrop-Site-before](https://github.com/backdrop/backdrop-issues/assets/397895/6c01426b-455c-466e-9cc8-6f3ba87cdeaa)

**Comment by stpaultim** [comment] 2024-05-09 01:59
In terms of consistency, I think that there is enough of a difference between the manage blocks and flexible layouts page that consistency is at least somewhat in the eye of the beholder. It's not clear to me that either approach is objectively more consitent?

Having said that, I think I would vote for the second one. BUT, I'd be fine with either one. 

@Klonos asked me to put the dotted line around the regions to be more consistent with the manage blocks page. Then you removed it. I'm not sure why or if that was intentional. On the manage layouts page, regions have a dotted/dashed border. I had added that to my PR for consistency with flexible layout page, but your PR against my PR removed it again. Was that intentional?

@jenlampton

**Comment by stpaultim** [comment] 2024-05-09 02:06
At @jenlampton My last version had this dashed line (actually, the dashed line is inherited from existing css, I had overridden it with a solid line, but I removed the override in my last draft).
![image](https://github.com/backdrop/backdrop-issues/assets/3144571/c5b0be91-ddb8-44be-ab18-88664c9e1676)

The manage blocks page puts this around regions as well.
![image](https://github.com/backdrop/backdrop-issues/assets/3144571/de654eb7-00a9-4733-b744-0a1a6541e87c)

Your PR against my PR overrides that dashed line and makes it solid.

**Comment by klonos** [comment] 2024-05-09 05:34
> The dotted lines mean "you can drop things here" and since we are dragging rows on this page (and not blocks) and since rows cannot be dropped into regions, the dots need to go. (This was discussed very early on, I think, you may have missed that part of the discssion @klonos.)

Gotcha 👍🏼 ...makes sense. I didn't know that that was the convention, and yes, I missed the discussion about it. Sorry.

> Here's the page with an additional drop-zone for rows added ... @klonos would love your opinion here too :)

Yeah, I don't think that dropzones in the template UI makes sense in the way that region dropzones make sense in the blocks UI.

> @klonos asked me to put the dotted line around the regions to be more consistent with the manage blocks page. Then you removed it. I'm not sure why or if that was intentional. ...

Apologies for the confusion @stpaultim ...I did miss the previous discussions, and whay @jenlampton is describing makes sense. My thought process when I made the suggestion I made was more like this: I noticed that there is some rather serious contrast issue in the tones of white/gray we are using around the regions and their row container -> I then opened another tab with the blocks UI in order to compare and see why this issue was not as prominent to my eyes before -> then saw that the regions in the block UI have the dotted border, which made things a bit better -> then tested the same in my local with the template UI and it seemed like an improvement. Now that I know that there is a mental association with the dotted border as a dropzone, I realize that what Jen is saying makes sense. ...so if I'm not asking too much, can we then please try changing the dotted line to a solid one, but with the same gray color (`#ccc` I believe)? (instead of the solid white like you had it in your original PR, which made no difference anyway)

**Comment by klonos** [comment] 2024-05-09 05:36
> ...can we then please try changing the dotted line to a solid one ...

Never mind, I see that that's been done in the latest commits. Re-reviewing 👀

**Comment by stpaultim** [comment] 2024-05-09 05:48
So, I think my version of the PR has all the requested changes and the agreed upon version of the drop zone (or lack thereof). 

@klonos and @jenlampton - What next?

**Comment by klonos** [comment] 2024-05-09 08:12
@stpaultim I've filed a PR against your PR: https://github.com/stpaultim/backdrop/pull/7

Before you merge it, I'd like @jenlampton's and other people's 👀 on it please. See comments and screenshots in the PR summary.

**Comment by stpaultim** [comment] 2024-05-09 22:35
@klonos  I agree that the contrast is not great. I tried to keep my focus on consistency between the two pages and was reluctant to make this kind of improvement, for fear that scope creep (keeping two pages consistent, while making improvements) would bog down the issue. 

Having said that. Your scope creep is ONLY 1-2 lines of css and only effects one other file. I think this increase in scope is fine and I do think it makes the two pages easier to read or look at. So, I'm in favor of your change, if others are ok with it as well and as long as it does not open the door to a bunch of other new "improvement" issues.

Happy to file a follow-up issue to take the redesign even further at a later date.

**Comment by klonos** [comment] 2024-05-10 17:24
Adding the screenshots for the PR here, so that people can nay or yay in order to move this issue on:

...adds consistent `1px solid #cccccc;` in various places - see before([Tim's PR](https://github.com/backdrop/backdrop/pull/4633))/after([this PR](https://github.com/stpaultim/backdrop/pull/7)) side-by-side screenshots:
  - template UI:
    ![image](https://github.com/stpaultim/backdrop/assets/2423362/f24cf10d-a435-44a5-997d-14156952f2ae)
  - blocks UI:
    ![image](https://github.com/stpaultim/backdrop/assets/2423362/a224799c-bcd0-483d-8199-84cc6e75aa50)

**Comment by stpaultim** [comment] 2024-05-14 02:33
STATUS: I believe that @jenlampton has agreed that we should stick with my PR. She experimented with some changes, that we decided against. This is a pretty simple review that has been reviewed by both @klonos and @jenlampton and feedback has been incorproated. 

I think the only hold up on this is the decision on whether or not to include the border change that @klonos describes in the last comment. 

Any feedback on that border? (I like it)

I would argue that given that we're are talking subtle change to CSS for the admin theme, we could merge the improvements already included and futher interate later...

**Comment by klonos** [comment] 2024-05-14 05:20
@stpaultim I'm happy to merge this as is and follow-up on the a11y and border line issues 👍🏼

@jenlampton since you were the one that set the label of this issue to "needs work", I'll leave it up to you to make the call. If you like the results of the before/after in the screenshots in my previous comment here, then it would be as simple as @stpaultim merging my PR against his branch. If not, then we can leave it for a follow-up.

**Comment by stpaultim** [comment] 2024-05-17 05:26
@klonos, @jenlampton and I looked at this during the most recent dev meeting and agreed on the changes. Someone take a final look at it and mark it WFM!

Let's try to get this into bugfix release.

**Comment by klonos** [comment] 2024-05-17 11:27
@stpaultim my concerns about the same border added consistently around the draggable/droppable items in both UIs (rows in the flexible template UI, blocks in the layout UI) has been addressed in the current PR 👍🏼 ...I've left a small comment about a CSS formatting issue (missing zeros from decimal values).

I believe that @jenlampton suggested that we wrap all rows around a dashed line ...not to add it to each row individually - just add another wrapper around the area where they can be dropped. This is the screenshot Jen provided with the desired outcome:
![image](https://github.com/backdrop/backdrop-issues/assets/2423362/d6a809b2-e7a0-48f7-891a-7a5b9b9f0786)

I agree with that suggested change, however the screenshot above is leaving the "Add row" button out of that dotted frame, whereas the respective "Add block" button is inside each such frame in the Blocks UI:
<img width="386" alt="image" src="https://github.com/backdrop/backdrop-issues/assets/2423362/6594d071-5a5b-4fa7-960b-a430d9d971ff">

So the end result in the flexi template UI should ideally be:
- outer gray overall frame, with `#f7f7f7` background and a 2px solid border of `#eaeaea`
- inner white overall frame with a 1px dashed border of `#cccccc`
- the "Add row" button should be inside the white dashed frame
- I'm happy with the current style of the draggable/droppable rows and they seem to be consistent with the style of the draggable/droppable blocks in the Block UI 👍🏼 

Setting the status to "needs work" for the above.

**Comment by stpaultim** [comment] 2024-05-18 02:01
> I believe that @jenlampton suggested that we wrap all rows around a dashed line ...not to add it to each row individually - just add another wrapper around the area where they can be dropped.

@jenlampton suggested that and created a PR to do that, but then decided she preferred it without that extra layer. See (current PR was my PR without the extra drop-zone):

https://github.com/backdrop/backdrop-issues/issues/6325#issuecomment-2101698094
> I think I prefer the current PR but without the drop-zone for blocks

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/6aef2d38-1fd0-4134-9c28-fc9389208a0a)

I'm getting dizzy, going back and forth here. :-)

**Comment by stpaultim** [comment] 2024-07-29 23:10
I've removed the "Needs Work" label and am asking for both Testing and Review once again. 

This nice little change is very near to RTBC. I believe that the last concern by @klonos about the placement of dotted line has been discussed and resolved.

Does anyone else want to chime in on that?

**Comment by avpaderno** [comment] 2024-07-30 00:27
I was going to take a look, but the preview sites for both the PR expired.

**Comment by avpaderno** [comment] 2024-07-30 00:52
I just noticed a behavior: When I add a new row, the row is shown after the footer, but when I try to drag the new row to place it before the footer, the footer suddenly appears as last row.

**Comment by avpaderno** [comment] 2024-07-30 00:58
Furthermore, after I push the footer row to the bottom, and I click on *Save layout template*, when I click on the footer row, a row is still show after the footer row.

I always click on *Save layout template* after I add a new row and move back the footer row to the bottom.

**Comment by avpaderno** [comment] 2024-07-30 01:06
Even more "complex": I push the footer row to the bottom, I click on Save layout template. I click on the footer row to move it, and a row is shown after the footer row. I scroll the page up and down, I click again on the footer row to move it; this time two rows are shown after the footer row.

**Comment by stpaultim** [comment] 2024-07-30 03:18
@avpaderno - I'm confused. To start with, have you looked at the code? This PR makes some pretty basic CSS changes to things like background-color and line weight. So, I don't think this PR could be doing anything to effect the placement of regions. Are the behaviors you are noting specific to this PR or simply things that work differently in Backdrop CMS than you would expect?

> When I add a new row, the row is shown after the footer, but when I try to drag the new row to place it before the footer, the footer suddenly appears as last row.

Is this not the expected behavior? When you add a new row, it always go to the end of the layout and then you move it into place. There might be a better way for this to happen, but if so, that would be a new feature request. 

If there is a region below the footer region and I drag it above the footer, then I would expect the footer to be on the bottom. Right?

Is all of your testing in the sandbox site? Have you compared behavior in this PR to behavior in a normal Backdrop site? Maybe I am misunderstanding something. But, I am unable to create any unusual or unexpected behavior around the placement of regions in the sandbox for this PR.

**Comment by avpaderno** [comment] 2024-07-30 09:31
I apologize for the confusion: I tried the preview site for this PR and I commented on what I noticed. I did not mean it was caused by this PR.  

Surely, there is JavaScript code that handles the drag-and-drop. I could not say what causes the behavior, but it happens in the moment I try to drag a row. I would say it is caused by the used JavaScript code, which could also not correctly change the used CSS classes.

(It is not about what I expect. I guess that everybody would be confused when they try to move a row on the bottom, and that row suddenly appears on the bottom of all the rows.)

**Comment by avpaderno** [comment] 2024-07-30 09:44
I could reproduce it on https://pr4827-u4dgvncmnhsntqfqnubjrfn3j8qnxi7e.tugboatqa.com/admin/structure/layouts/settings/flexible-template/demo/configure too, and I noticed it happens even without dragging any row.

I will create an bug report about that.

**Comment by stpaultim** [comment] 2024-08-31 06:49
I believe that all the issues @avpaderno is referring to are now included in this bug report. 
https://github.com/backdrop/backdrop-issues/issues/6673

Could some take a look at the sandbox for this PR and give it a Works for Me (assuming that it works for you)?

We really should get this page cleaned up. I'm surprised every time I visit this page in that it looks a bit unfinished.

@avpaderno Do you think that this PR works and accomplishes what it set out to accomplish?

**Comment by avpaderno** [comment] 2024-08-31 19:47
@stpaultim For what I can see, the PR does what the issue summary suggests to do.

**Comment by stpaultim** [comment] 2024-09-02 20:15
@izmeez 

It's not clear to me that your seeing the same cursor/pointer as I am on this page. Here is a screenshot of my cursor. I believe that all we are doing is defining which type of cursor to use on this page, which we have set to `row-resize`. 

It's not clear to me if we currently have a unique icon for this cursor or if the browser is loading a default cursor suitable for `row-resize`.

Anyone?

![image](https://github.com/user-attachments/assets/622c3668-0155-4e61-b46a-391994586ef8)

Either way. I'm inclined to break that into a different issue, because it's not really specific to this page.

FYI - This issue can still get into 1.29 until the day of launch. So no rush on this issue. It's a design/UX change, not a new feature and it can get into any bugfix release as well.

**Comment by stpaultim** [comment] 2024-09-03 20:47
On my linux computer with both Chrome and Firefox, `ns-resize` and `row-resize` look the same.

Here is a resource that let's you both 'hover' over each to see the effect, but also comes with a picture of what they are expected to look like. There are a few discrepencies between what my computer shows and what it should look like. 

https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

I'm inclined to agree with @izmeez that `ns-resize` is a better option. I'm going to change the PR to reflect that. Looking for additional feedback.

**Comment by stpaultim** [comment] 2024-09-15 18:44
@izmeez The intention is to leave the PR as it currently is. If I understand correctly, you are in agreement that we should use the `ns-size` icon. This is the icon that I switched to back on Sept 3rd. 

It seems that you are now suggesting that we change the behavior or the area over which this icon is triggered. If I understand correctly, you would limit it to the title area. 

I have no problems with the change you are suggesting, however since this is a new request that was not addressed by anyone else in the earlier discussions and because I have not had time to think about whether or not this change would be consistent with other UI elements in Backdrop, I'm inclined to leave that as a follow-up issue. 

I do not want to jeopordize the merging of some changes which have been discussed in serveral meetings, by introducing a new change at this point in the cycle. If this PR does not get into 1.28.3, we can revist this.

**Comment by stpaultim** [comment] 2024-09-15 19:02
@izmeez - OK, it's a bit frustrating that I'm not able to recreate the problem visually with either Firefox or Chrome. However, I can see by inspecting elements that there were situations (as you described) in which it was using `row-resize` instead of `ns-resize`. I've made the change you suggested. 

Please, test to make sure this addresses your issue. Thanks for your patience.

If the change addresses your concerns. I think you should be able to mark this RTBC.

**Comment by stpaultim** [comment] 2024-09-15 19:16
@izmeez The tag is actually `pr - ready to be committed`

**Closed** 2024-09-16 05:28 UTC
Labels: type - bug report, status - has pull request, design, pr - ready to be committed, pr - works for me

**Comment by quicksketch** [comment] 2024-09-16 05:29
Thank you everyone! I merged https://github.com/backdrop/backdrop/pull/4633 into 1.x and 1.28.x.

https://github.com/backdrop/backdrop/commit/def4c49141aadabfbdbbd3d74e08e7516f651adf by @stpaultim, @jenlampton, @klonos, @izmeez, @avpaderno, and @yorkshire-pudding.
