### ISSUE TITLE
Include SmartMenus styles in Bartik for Primary navigation menu

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2361] opened 2016-11-26 18:47 UTC
The Bartik menu does not display properly when shown as a dropdown menu (the default).

To reproduce:

- Add nested menu items to the primary menu.
- Set the default theme to Bartik
- (Ensure the menu style is "Dropdown", the default)

---
~~PR by @klonos: https://github.com/backdrop/backdrop/pull/1671~~
PR by @klonos: https://github.com/backdrop/backdrop/pull/3487

**Comment by bd0bd** [comment] 2016-11-26 19:01
Chrome, Win 7

![menu_](https://cloud.githubusercontent.com/assets/13515302/20642586/ca326fe2-b423-11e6-8d04-914a08a931a4.png)

**Comment by klonos** [comment] 2016-11-26 19:46
I confirm this bug. It's not limited to Chrome. I see it in latest firefox too. I think that Bartik was not adapted to support the newly-added drop-down menus.

**Comment by olafgrabienski** [comment] 2016-11-27 10:11
> The Basis design is roughly broken too. CSS bugs.

@bd0bd Can you provide more information about what is broken in Basis?

**Comment by bd0bd** [comment] 2016-11-27 15:03
A lot is broken. Please test and look. It is difficult for me to explain in English. I am sorry, pls forgive me.
I mean in Android (Chrome) not Windows in PC.

**Comment by olafgrabienski** [comment] 2016-11-27 15:57
@bd0bd Can you provide a screenshot?

**Comment by klonos** [comment] 2016-12-11 15:53
@bd0bd, @olafgrabienski can you please give the PR a spin and verify that it fixes the "jumping" menus issue?

Before:

![backdrop-issue2361-jumping_menus](https://cloud.githubusercontent.com/assets/2423362/21081232/1cf59558-c016-11e6-9c80-a01360390c61.gif)

After:

![backdrop-issue2361-pr1671](https://cloud.githubusercontent.com/assets/2423362/21081237/283ebe12-c016-11e6-9398-bf6380c738b9.gif)

**Comment by olafgrabienski** [comment] 2016-12-11 22:53
Gave it a quick look in Chrome and Firefox on Mac OS X: When I hover over the "Home" menu item, "About" jumps to the right. (No screencast tool available at the moment.)

**Comment by klonos** [comment] 2016-12-12 03:42
Thanx @olafgrabienski. I see it. Will try to sort it out...

**Comment by klonos** [comment] 2016-12-12 03:55
Updated the PR to fix this issue:

![backdrop-issue2361-pr1671-right_padding](https://cloud.githubusercontent.com/assets/2423362/21087552/ffc4fef0-c07a-11e6-9813-09498dc62e97.gif)

Can you guys try to break it now? 😄

**Comment by klonos** [comment] 2016-12-12 06:34
...scratch that. Still not 100% fixed. I could not reproduce this on my local because I have all my 1st-level items with child items. Placing a single menu item (without any children) on the top level reproduces the issue. It's because of the arrow that does not exist on the "solo" 1st-level items. On to it...

**Comment by klonos** [comment] 2016-12-12 07:32
...had to fight with `/core/modules/system/css/menu-dropdown.theme.css`, but I think I got it this time 😉 

RTL is broken, but I'll fix that once I get a review on the current PR ...perhaps even on a separate PR. Once these are fixed, all there's left is to add hover and active trail colors (#2160).

**Comment by olafgrabienski** [comment] 2016-12-12 23:48
@klonos Actually not a review due to lack of time, but I can confirm that the issue mentioned in https://github.com/backdrop/backdrop-issues/issues/2361#issuecomment-266314708 is fixed now.

**Comment by quicksketch** [comment] 2017-01-08 21:24
Making progress here! The dropdown version now looks fine, but the padding is now broken when using a non-hierarchical version ("Top links only" option):

Looking good with dropdowns enabled:
![screenshot from 2017-01-08 13-23-08](https://cloud.githubusercontent.com/assets/100206/21753621/bd98a29e-d5a5-11e6-9513-c487777eb0d4.png)

But a lack of padding with top-links only:
![screenshot from 2017-01-08 13-23-01](https://cloud.githubusercontent.com/assets/100206/21753623/cbce3d42-d5a5-11e6-9be6-55e4c04d489b.png)

**Comment by serundeputy** [comment] 2017-01-15 23:27
Still in needs work; moving to `1.6.1`

**Comment by bd0bd** [comment] 2017-03-18 17:44
Almost 4 months left but the "bug" not fixed. In my mind this is not a bug, it is banal negligence.
![screenshot_2017-03-18-13-24-05 2](https://cloud.githubusercontent.com/assets/13515302/24074520/16d356f8-0c13-11e7-8762-85b96925b0ec.jpg)
![screenshot_2017-03-18-13-19-24 2](https://cloud.githubusercontent.com/assets/13515302/24074525/29d8c148-0c13-11e7-91a7-d2fe3730aa1a.jpg)

**Comment by bd0bd** [comment] 2017-03-18 17:49
Sorry, no time to place in appropriate place. Home page css issue.
Other pages are ok.

![screenshot_2017-03-18-20-45-42 2](https://cloud.githubusercontent.com/assets/13515302/24074553/9cfcdd94-0c13-11e7-8d83-f374e26ce3a3.jpg)

**Comment by klonos** [comment] 2017-03-19 12:22
> Almost 4 months left but the "bug" is not fixed. In my mind this is not a bug, it is banal negligence.

> Sorry, no time to place in appropriate place. Home page css issue.
> Other pages are ok.

@bd0bd sorry for can't helping but being mean, but I really like how you feel it's totally OK if you don't have time to file issues against the proper queue (it would probably take you what? ...30 seconds? ...maybe one minute?). On the other hand, it is totally "banal negligence" of us if we don't have time to fix all the issues. Just remember that the more time one of us wastes in moving issues in the proper queue, the less time we have to dedicate in fixing bugs. Thanx once again for helping, man. Here's the proper queue: https://github.com/backdrop-ops/backdropcms.org/issues/364

**Comment by mikemccaffrey** [comment] 2017-03-20 06:33
Hey @klonos, it is actually helpful that @bd0bd pointed the issue out here. The backdrop.org site is not using Basis, so that means that the problem is not at the theme layer, but the underlying layout layer.

**Comment by bd0bd** [comment] 2017-03-20 10:04
It is difficult to understand why you do not fix very simple bugs in the Bartik menu for months.
Very bad work you are doing  in this aspect. I would say you are doing nothing.

Menu. When we click (tap) any  item  then this item jumps up and the righ adjacentt  item twitches to the right.

Bad css coder you have. It is  a schoolchild level.

The Basis is defective. The Bartik is defective. How to work with your  Backdrop CMS if you do not care about your users! :'(

**Comment by olafgrabienski** [comment] 2017-03-20 10:43
@bd0bd I understand your frustration when an issue doesn't get fixed for a long time. When I read "bad css coder" and "schoolchild level" I get the impression that you know the solution to fix the issue. Why don't you suggest it?

**Comment by klonos** [comment] 2017-03-20 11:04
@mikemccaffrey, @olafgrabienski I am usually a very patient person. Perhaps it's because my girls are going back home and it'll be another 4 to 5 months till I see them again. So perhaps that makes me prone to easy irritation. I also understand that there might be language constrains, so I was understanding with "funny" choices of words and phrases a couple of times before. Well, unfortunately, this has proven to be a pattern with the specific person and I don't think that this should be acceptable behavior in general. I realize that as a PMC member I should be setting the example, sorry, but a man has their limits too.

**Comment by bd0bd** [comment] 2017-03-24 11:44
I would like to use Bartik because Basis is very defectively done and it is a shame for me to use such bad product for my clients. You do not respect your users - it is ok, it is your business - but I respect people who I am doing websites for.
But because of  the SmartMenus Bartik is also defective now for 4 months.

I was going ti deactivate the SmartMenus but can not see this option in the modules list.
Please, how to deactivate it?
All I need - good work of Bartik it was 1 year or 2 years ago.

Thank you!

**Comment by bd0bd** [comment] 2017-03-24 11:56
"When I read "bad css coder" and "schoolchild level" I get the impression that you know the solution to fix the issue. Why don't you suggest it?"

I can. Also I can sew pants, grow potatoes and cows and much more.
But I  do what I like more to do.

**Comment by olafgrabienski** [comment] 2017-03-24 12:01
> I was going to deactivate the SmartMenus but can not see this option in the modules list.
> Please, how to deactivate it?

Have a look at the configuration of the block "Primary navigation". Choose there the "Menu style" and/or disable the option "Display menu toggle button on small screens".

**Comment by bd0bd** [comment] 2017-03-24 14:15
Thank you very much! :+1: 

This is exactly  what I have been looking for in /admin/structure/menu/manage/main-menu/configure

**Comment by laryn** [comment] 2017-03-24 15:58
> I would like to use Bartik because Basis is very defectively done and it is a shame for me to use such a bad product for my dear and lovely clients. You do not respect your users - it is ok, it is your business - but I respect people who I am doing websites for.

@bd0bd My two cents: Try to show a little more respect to the people who are devoting so much time and energy to this project that you are using. Intentionally or not, your comments come across as very disrespectful and don't bring a good energy to finding a solution.

@olafgrabienski and @klonos Thank you for your tireless work and support!

**Comment by docwilmot** [comment] 2020-03-17 21:47
@klonos can we get this one fixed too? It looks like its close.

**Comment by BWPanda** [comment] 2021-01-04 09:55
I found a fix for the problem @quicksketch identified and left a note for @klonos in the PR.

**Comment by klonos** [comment] 2021-01-09 04:34
The PR hasn't been updated since 2016 (sorry). I'll rebase and check whether @BWPanda's suggestion fixes things.

**Comment by klonos** [comment] 2021-01-09 04:48
I've rebased my local, and it seems that things work as expected with both 1+ level menu items (randomly generated using devel_generate):

![image](https://user-images.githubusercontent.com/2423362/104083230-ad617b00-5245-11eb-8890-efb2aa53bd6e.png)

...as well as with only 1 level of items:

![image](https://user-images.githubusercontent.com/2423362/104083287-0b8e5e00-5246-11eb-8748-6f50acd55026.png)

In other words, I am not able to reproduce the problem @quicksketch reported 🤷 

I also went back to all comments in the thread, and tried to reproduce issues that others have reported over time. I confirmed that everything seems to be working as expected 👍 

Because in the meantime I've nuked my fork of the repo from which the original PR was filed, I could not update the existing PR, so I've filed a new one here (no code changes compared to the previous PR): https://github.com/backdrop/backdrop/pull/3487

**Comment by klonos** [comment] 2021-01-09 04:51
...the ZenCI sandbox is broken (I guess confused by the previous PR 🤷 ), but the Tugboat sandbox shows that only-top-level menu items have proper spacing:

![image](https://user-images.githubusercontent.com/2423362/104083430-1dbccc00-5247-11eb-8b09-23d5799fe006.png)

**Comment by klonos** [comment] 2021-01-09 05:11
@BWPanda I've tested your suggestion on my local, and it indeed seems to not be needed. I've included the same padding in the CCS I've added, so it already applies:

![css-change-not-required](https://user-images.githubusercontent.com/2423362/104083749-d2f08380-5249-11eb-9fc0-9d3fa146fd3a.gif)

**Comment by klonos** [comment] 2021-01-09 05:17
...meh 🤦 ...it's that `.js` selector. The key is to disable JS on the browser; I'm able to reproduce then. The drop-down selectors though only make sense when JS is enabled 🤔 ...I'll see what can be done to avoid CSS duplication there.

**Comment by klonos** [comment] 2021-01-09 05:33
OK, PR updated:

- I've included the `.l-header ul.menu a` selector from the previous block of CSS in the selectors with the changes I've introduced
- I've removed the `height`, `line-height`, and `padding` from the block of CSS that applied _exclusively_ to the `.l-header ul.menu a` selector, and these now apply to both `.l-header ul.menu a`, as well as all the `.js .menu-dropdown`* selectors.

I believe that I've addressed all points this time.

**Comment by indigoxela** [comment] 2021-01-09 09:41
> I believe that I've addressed all points this time.

I think so, too! I tested in the sandbox with all sorts of menu block settings, with Javascript in the browser turned on and off, with changed viewport sizes.
Everything works as expected, no jumping and the menu item padding is always consistent. Works for me.

**Comment by BWPanda** [comment] 2021-01-09 10:13
Works for me too! Tested all menu styles on my local with the patch applied and they all display consistently and without any of the issues described in the comments above. RTBC.

**Closed** 2021-01-12 00:08 UTC
Labels: status - has pull request, status - fixed

**Comment by BWPanda** [comment] 2021-01-12 00:09
Thanks @klonos, @bd0bd, @olafgrabienski, @Dinornis, @quicksketch & @indigoxela.! I have merged https://github.com/backdrop/backdrop/pull/3487 into 1.x and 1.17.x.

**Comment by BWPanda** [comment] 2021-01-14 04:15
Looks like the [Silkscreen](https://www.silkscreencms.org/) website uses Bartik and suffers from this bug, so I'm sure @jlfranklin will appreciate this fix 😃
