### ISSUE TITLE
Problem with updating Backdrop 1.8.0 to 1.9.2

### ISSUE THREAD

**Issue by amilenkov** [backdrop/backdrop-issues#3005] opened 2018-03-19 11:17 UTC
I am starting update of Backdrop 1.8.0 to 1.9.2. 
And get error message:

> Exception: The <em class="placeholder">../private/config/active</em> directory must be completely empty to proceed with installation. Empty this directory or specify a different directory in settings.php. in backdrop_install_config_directories() (line 729 of /home/hoscom/public_html/core/includes/install.inc).

I will return the site from backup to Backdrop 1.8.0 and I do not know how to make this update.

Apply screenshots. If further information is required, I will provide it.

Before update (the core has already been changed to 1.9.2):
![before-update](https://user-images.githubusercontent.com/14857883/37592526-9c3d1e4e-2b77-11e8-99ff-d201eb6bdd1f.png)

After starting update:
![update-error](https://user-images.githubusercontent.com/14857883/37592531-a2ff945a-2b77-11e8-8ede-6642106de605.png)

**Comment by olafgrabienski** [comment] 2018-03-19 11:29
Maybe a duplicate of #2538?

See https://github.com/backdrop/backdrop-issues/issues/2538#issuecomment-280931820:
> I had no staging folder in my config directory and it seems this is needed even if required to be empty. I'm not sure how I had lost it, but creating an empty staging folder has solved my problem.

**Comment by amilenkov** [comment] 2018-03-19 11:39
There was a file README.md in the staging folder and I deleted it. 
The staging folder is empty.
But I get the same error.

After I returned the site to Backdrop 1.8.0 I tried to at least update the Backup and migrate 1. x-1.0.12 module from an older version of this module. 

And again I get the same error:

Site returned to Backdrop 1.8.0:
![before-update-2](https://user-images.githubusercontent.com/14857883/37593481-cd3c9be8-2b7a-11e8-9069-20cfea4e38c2.png)

Error after trying update to Backup and migrate 1. x-1.0.12
![update-error-2](https://user-images.githubusercontent.com/14857883/37593525-f0802228-2b7a-11e8-9372-6326be2fcfab.png)

**Comment by amilenkov** [comment] 2018-03-19 12:47
I do not know what the above errors are due, I am not a programmer and I can not solve such problems.

But I managed to make an update from Backdrop 1.8.0 to 1.9.2 in another unconventional way and I share it because it can be useful for others who have the same problem.

Here's what I did:

I deleted completely the contents of the public_html directory of the site.
I deleted all the tables in the database on the site.
I installed a completely new blank site with Backdrop 1.9.2.
I deleted the database tables in database of the new site.
I imported in the database of the new site through phpMyAdmin tables from the last backup of the site done via phpMyAdmin in December 2017 for version 1.8.0.
I made a copy from the previous backup to the directory .. /private/config, where the active and staging folders are located with the configuration of the site:
I edited the settings. php file on the new site like this: 
```
$config_directories['active'] = '../private/config/active';
$config_directories['staging'] = '../private/config/staging';
```
In this way the site was rebuilt but in the installation of Backdrop 1.9.2
I entered the site as an administrator and and clicked Run updates.
The update completed without errors.

**Comment by olafgrabienski** [comment] 2018-03-19 13:01
Happy to see that you've been able to update the site this way! As you say, it was a quite unconventional way. Doing so shouldn't be necessary, and I hope we can figure out the reason for the issue. I'm however not able to reproduce the issue at the moment, so I'm going to close it for now.

For reference here are some links to related issues:

open
- #2507 
- #2263

closed
- #2538 
- #2262

**Closed by olafgrabienski** 2018-03-19 13:01 UTC

**Comment by amilenkov** [comment] 2018-03-19 13:10
Whether this might be the cause of the error:

This site was first installed on 15.10.2017 with Backdrop 1.8.0 via http domain. It hasn't been updated until today. 

Meanwhile, on 7.11.2017 I have converted the domain to work on HTTPS. For this purpose I added to the end of settings.php file:

```
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L] 
```

And so when I try to update today actually starts a new installation, not an update - the system does not see the existing site because of the new HTTPS domain?

**Comment by olafgrabienski** [comment] 2018-03-19 13:25
Not sure! I think Backdrop should recognize the HTTPS site. I've experienced however that Drupal (and, I guess, also Backdrop) treats http and https differently in some aspects. When you for instance login using HTTP and then navigate to a HTTPS url of the same site, you're no longer logged in.

**Comment by amilenkov** [comment] 2018-03-19 13:38
> When you for instance login using HTTP and then navigate to a HTTPS url of the same site, you're no longer logged in.

I thing this is due to the cookies - HTTP  and HTTPS  cookies are different as I have red. You will be logged out also if you delete your cookies in current browser session.

I have some other sites with backdrop that after creation were changed to https. Next days will try to update them after adding base url with https in settings.php. And will report there if this solves such problem.

**Comment by amilenkov** [comment] 2018-03-20 12:03
I just made an update to another site from Backdrop 1.7.1 to 1.92 and  before this update I changed the site's domain to be https. There were no problems with this update, so I conclude that changed https domain is not the cause for the above discussed error message about updating 1.8.0 to 1.9.2.
