### ISSUE TITLE
ViewsUpgradeTestCase may be (partly) obsolete

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5620] opened 2022-05-08 09:30 UTC
## Description of the bug

This popped up in an unrelated test-only bug fix:

```
module_enable(array('php'));
```
But that makes no sense, as this module doesn't even exist in Backdrop.

Looking at the test, it seems completely obsolete - it deals with views upgrade (or import?) - not sure which one.

Let's verify that it's really obsolete and remove that test, if that's the case. Otherwise update the code so the check is useful.

## Additional information

- Backdrop CMS version: latest dev
- Code: https://github.com/backdrop/backdrop/blob/1.x/core/modules/views/tests/views_upgrade.test

**Comment by argiepiano** [comment] 2022-05-08 14:07
The test is not obsolete but there are parts there that need modification. 

The 'moved to' functionality still exists in Backdrop's Views, and it's a very helpful one. It allows you to indicate changes in the definitions of the table, the handlers or the fields - for example, if suddenly you decides to change the name of the base table for an entity, the 'moved to' would allow you to tell Views about this change, so that older views that existed before that change won't break. 

So, most of the test checks that this functionality still works. BTW, the moved to key is currently used by several core modules, e.g. comment.

The parts that needed fixing:
- The test defines an "old" View that uses the wrong base_table (comments instead of comment) and the wrong body field (formerly a column in the comments table called comment, nowadays a separate Field API field called comment_body, stored in the table field_data_comment_body) among other things.

The problem is that this View (as far as I can tell) is never imported or used, and no replacement for it was created for the test. What we need is to create a config file with those wrong definitions and place it inside tests/views_test/config so that it gets imported when the views_test.module is enabled by ViewsSqlTest

- The second issue is that the module php is not really needed (and obviously it's not available anyway) once the above is done.

**Comment by argiepiano** [comment] 2022-05-09 03:01
A bit more digging. The view definition in method `viewUpgradeImport()` is not needed. That was part of an obsolete test that tested views imports (which now happen as config imports). 

I just submitted a PR: https://github.com/backdrop/backdrop/pull/4069

I expect several tests to fail since https://github.com/backdrop/backdrop/pull/4067 has not been merged yet, but ViewsUpdateCaseTest should pass - we'll see.

**Comment by indigoxela** [comment] 2022-05-09 06:59
@argiepiano many thanks for all your digging!

> ... ViewsUpdateCaseTest should pass

It does. :+1: Hopefully https://github.com/backdrop/backdrop/pull/4067 gets merged soon.

**Comment by indigoxela** [comment] 2022-05-10 05:51
@argiepiano many thanks for the cleanup and rebase. Everything's working as expected. RTBC :+1: 

I wasn't aware of the "moved to" functionality in Views. Pretty cool stuff.

**Comment by argiepiano** [comment] 2022-05-10 12:18
Thank you, @indigoxela! May I get a milestone number from someone please?

**Comment by BWPanda** [comment] 2022-05-14 11:47
I posted a question about some code in the PR (warning; might be a silly question).

**Comment by argiepiano** [comment] 2022-05-14 14:13
After @BWPanda comment on the PR I pushed a small change (getting rid of the setUp override, which is not needed). I put this back on "needs code review". Since this is a test, I did not add "needs testing" since GHA does that for us. 

@indigoxela or @BWPanda, it'd be great if you could do a code review of the small change and if you lie it put this back on RTBC.

**Comment by BWPanda** [comment] 2022-05-15 02:13
Looks good to me!

**Closed** 2022-05-15 23:08 UTC
Labels: type - bug report, status - has pull request, pr - ready to be committed

**Comment by BWPanda** [comment] 2022-05-15 23:12
Thanks @argiepiano and @indigoxela! I've merged https://github.com/backdrop/backdrop/pull/4069 into 1.x and 1.21.x.
