### ISSUE TITLE
Design review: contextual links

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#992] opened 2015-06-11 23:39 UTC
Is the current look / feel for the contextual administration links what we want?  If so please close this issue.
![screen shot 2015-06-11 at 5 37 47 pm](https://cloud.githubusercontent.com/assets/397895/8120802/b65f3f80-1060-11e5-9b97-65d29f355b21.png)

**Comment by docwilmot** [comment] 2015-06-12 03:10
good for me

**Comment by klonos** [comment] 2015-06-12 14:23
Yep. Don't mind it either.

**Comment by wesruv** [comment] 2016-04-01 22:36
There are a fair number of bugs with the positioning of these guys, I also find their hit area and font sizes to be inconsistent and a potential issue with touch.

The gear icon is fine, I think we could try a pencil, but that says 'edit' more than anything and sometimes the only option in this menu is 'configure'.

The positioning bug happens when elements overlap (usually due to floats or absolute positioning), or if an element has a strange width for some reason.

The solutions I see for the positioning bugs are:
* D8 chose to do some very fancy positioning JS for inline quick edit. This could be the most accurate, but would have to be fairly involved/a little heavy. I'm thinking it isn't worth the effort
* I'm thinking put contextual menus in the top left instead of the top right. 

I think the second option will fix most of the positioning issues, as the top left corner of elements tends to be much more reliable than the right side. It's the way HTML renders, and it tends to how we lay things out.

Downside is the gear will cover up what tends to be an important corner. BUT this is only for editors, and the gear is pretty small, so it's unlikely it'd cover up the entire it area of something.

It's also easy to implement, so there's that.

I've actually been messing with this in the 'new default theme', if you check out the latest you should see my updates to contextual.
https://github.com/backdrop-contrib/basis/

**Comment by klonos** [comment] 2018-07-05 10:46
> D8 chose to do some very fancy positioning JS for inline quick edit.

@wesruv do you happen to have a d.org issue for that handy?

> The gear icon is fine, I think we could try a pencil, ... I'm thinking put contextual menus in the top left instead of the top right.

Android uses 3 dots stacked on top of each other, and they are positioned at the top-right:

![image](https://user-images.githubusercontent.com/2423362/42319091-4d4bd952-8094-11e8-90a5-e5b0b3751cfa.png)

Although the market share of Android vs Apple here [in Australia is about 50/50](http://gs.statcounter.com/os-market-share/mobile/australia), it is [about 75/20 globally](http://gs.statcounter.com/os-market-share/mobile/worldwide). Not saying that Google knows best about everything, or that these numbers won't change ever, but it seems that close to 80% of people worldwide would expect things to look/work that way.

**Comment by BWPanda** [comment] 2020-10-12 20:56
Still working on this?

**Comment by wesruv** [comment] 2020-10-12 21:07
Nope

**Comment by BWPanda** [comment] 2021-07-19 12:14
> Is the current look / feel for the contextual administration links what we want? If so please close this issue.

> Still working on this?
> Nope

Going to close this issue then as 'works as designed'.

**Closed by BWPanda** 2021-07-19 12:14 UTC
Labels: design, type - feature request
