### ISSUE TITLE
Taxonomy terms do not display properly in theme Basis

### ISSUE THREAD

**Issue by metatop** [backdrop/backdrop-issues#4384] opened 2020-05-01 23:15 UTC
The categories do not appear horizontally, they appear vertically in theme Basis
![category-basis](https://user-images.githubusercontent.com/35878927/80848112-5addb280-8c12-11ea-860c-ced5c3684a6a.png)

**Comment by jenlampton** [comment] 2020-05-02 02:55
This is something I find very frustrating too, and it's a bug we have inherited from Drupal 7. 

If we could [get the Drupal-6 style sane display of taxonomy terms back in core](https://github.com/backdrop/backdrop-issues/issues/2674) we would resolve this long-standing bug.

**Comment by laryn** [comment] 2020-05-05 16:46
@metatop Until this gets fixed in core, you can use the contrib module to control display:
https://github.com/backdrop-contrib/textformatter

**Comment by metatop** [comment] 2020-05-17 20:36
Gracias

**Comment by klonos** [comment] 2020-05-18 19:29
Should this issue be closed as a duplicate of the existing #2674?

**Comment by BWPanda** [comment] 2022-05-30 01:47
Yes, since we're not fixing this in Basis but rather more generally, this becomes a duplicate of that existing issue.

**Closed by BWPanda** 2022-05-30 01:47 UTC
Labels: status - duplicate
