### ISSUE TITLE
Fix Admin bar collapse with jQuery 3 for certain settings and narrow windows.

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#6666] opened 2024-07-27 22:23 UTC
## Description of the bug

Normally with a narrow window (like a phone screen), the admin bar collapses into a single hamburgered drop-down menu. However, if the site is set to use jQuery 3 (which is now the default) and one turns off the extra items that usually appear to the right of the admin bar, then that collapse fails, and the admin bar wraps, thereby potentially covering up other stuff (depending on the theme).

## Steps To Reproduce

* On a plain Backdrop site, enable the Admin Bar module and log in as a user with sufficient privileges to see the admin bar.
* Go to admin/config/administration/admin-bar and turn off "Page links", "User counts", "Account links", and "Language switcher", like this:
  ![image](https://github.com/user-attachments/assets/56fd47ee-200c-4871-aafe-9abdf0e7a953)
* Go to admin/config/development/jquery (which would normally be set to jQuery 3), resize the window to 500px or less, and refresh the page. You will see something like this, with all admin menu menus visible and wrapping. (Note that the breadcrumb got covered up.)
  ![image](https://github.com/user-attachments/assets/1c611c6e-3fc3-4f18-b1bc-410e3c09eb47)
* Now select jQuery 1 and save. You'll see what you're supposed to see, which is this:
  ![image](https://github.com/user-attachments/assets/b991d290-73a5-4477-9435-4a760f2250fb)

## Additional information

This happens because of some code in `admin_bar.js`, specifically, the function defined as `var adjustItems`:

```
  var adjustItems = function () {
    // Expand the menu items to their full width to check their size.
    $menu.removeClass('dropdown').addClass('top-level');
    $extra.removeClass('dropdown').addClass('top-level');

    $adminBar.trigger('beforeResize');

    menuWidth = $menu.width();
    extraWidth = $extra.width();

    // Available width is anything except the menus that may be collapsed.
    availableWidth = $adminBar.width();
    $adminBar.children().children().not($menu).not($extra).each(function() {
      availableWidth -= $(this).width();
    });

    // Collapse the extra items first if needed.
    if (availableWidth - menuWidth - extraWidth < 20) {
      $extra.addClass('dropdown').removeClass('top-level');
      extraWidth = $extra.width();
      ...
```

When there are no extra items at the right , `$extra` is empty. In jQuery 1, `extraWidth` ends up as `null`, which typecasts to zero, so the expression `availableWidth - menuWidth - extraWidth` still evaluates as a number.

However, in jQuery 3, `$extraWidth` ends up undefined, which makes that mathematical expression a `NaN`, and so the conditional never evaluates to TRUE.

So the solution would appear to be to handle the case where `$extra` happens to be empty (in a way that works with both jQuery versions).

**Comment by klonos** [comment] 2024-07-28 04:46
Good find @bugfolder 👍🏼 ...thanks for the PR 🙏🏼 ...I confirmed the problem in a demo sandbox, then repeated the steps in the PR sandbox, and confirmed that the problem is fixed 👍🏼 

Looking at the code, and being me and liking to "kick the tires" when I can, I tried the following:
1. Renamed the default `admin` user to `veryveryverylongadminusername`.
2. Back to the admin bar configuration, I enabled all the "extras", and disabled the "Management menu" checkbox instead. NOTE!: this will remove the main admin bar menu, so you'll need to navigate using the breadcrumb thereafter.
3. Navigate to `/admin/config/development/jquery`, and switch to v3 if not already switched. Wrapping occurs and the extras section fails to collapse:
   <img width="499" alt="image" src="https://github.com/user-attachments/assets/3777f263-c9ec-4728-815e-b3fa80770ac1">

So, edge case, however it seems that we need to apply the same code logic to the `menuWidth` variable as well.

**Comment by bugfolder** [comment] 2024-07-28 11:58
That's a weird little corner (case) there, but definitely a corner! Thanks, addressed (also the  orphan debug variable).

**Comment by argiepiano** [comment] 2024-07-28 13:54
I have suggested a more idiomatic (and shorter) way to do this.

**Comment by bugfolder** [comment] 2024-07-28 14:56
Nice, I'll remember that trick. Change made (and verified that it works); ready for re-testing, re-review.

**Comment by bugfolder** [comment] 2024-07-28 14:58
I love the PHP null coalescence operator `??`; nice to see something like that in JS.

**Comment by argiepiano** [comment] 2024-07-28 15:05
LGTM!

**Comment by klonos** [comment] 2024-07-29 03:59
Thanks for the tip @argiepiano 🙏🏼 ...really sleek indeed! 👍🏼

**Comment by quicksketch** [comment] 2024-08-30 19:32
Thanks @bugfolder, @argiepiano, and @klonos! Merged https://github.com/backdrop/backdrop/pull/4838 into 1.x and 1.28.x

**Closed** 2024-08-30 19:31 UTC
Labels: status - has pull request, status - fixed
