### ISSUE TITLE
format_date() gives inconsistent result in tests if timezone not specified

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#723] opened 2015-02-17 03:54 UTC
Not sure what this is but in filter_example.module (part of [Examples for Developers](https://github.com/backdrop-contrib/examples)), there is a function that replaces a tag `<time />` with a time string:

```
function _filter_example_filter_time_process($text, $filter) {
  return str_replace('[filter-example-time]', '<em>' . format_date(time()) . '</em>', $text);
}
```

In the filter_example.test there is this code:

```
    $edit = array(
      "title" => $this->randomName(),
      "body[$langcode][0][value]" => 'What foo is it? it is <time />',
    );
    $result = $this->backdropPost('node/add/' . $content_type->type, $edit, t('Save'));
    $time = format_date(time());
    $this->assertRaw('What bar is it? it is <em>' . $time . '</em>');
```

The test posts a node with the `<time />` tag in the node body, which should then be the same as the $time variable in the test. 
It fails, because the test time is in a different timezone than the module time! If you add a node manually on the site, the time is different from the time genrated during the test. To make tests pass I had to change the format_date function to:
`format_date(time(), 'medium', '', 'Europe/London');` (the important bit being the specific timezone).
Any thought on this? Is this right?

**Comment by klonos** [comment] 2019-06-06 21:11
Could this be related to (or duplicate of) #3794 @docwilmot?

**Comment by indigoxela** [comment] 2019-06-07 04:43
> Could this be related to (or duplicate of) #3794

@klonos I don't think so. Function format_date() is defined in includes/common.inc and isn't part of the date module.

By default in format_date(), if the $timezone variable is null, it's either determined from $backdrop_static_fast['timezones'] or with date_default_timezone_get() or timezone_open().

@docwilmot what is the timezone defined in your testing servers' php.ini? And which timezone is set in your Backdrop regional settings?

**Comment by indigoxela** [comment] 2019-06-07 05:14
Gosh, now I realize that this is an ancient Issue... ;)

There wasn't much activity sine 2015, probably the problem is solved anyway.
@docwilmot Is this true?

**Comment by klonos** [comment] 2019-11-24 08:37
Wondering if the initial report is still an issue, and also if this should be moved to https://github.com/backdrop-contrib/examples/issues instead.

**Closed** 2020-04-29 18:01 UTC
Labels: needs - more feedback
