### ISSUE TITLE
[RTL] Fix placement of "gray box" for vertical tabs in Basis theme 

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4835] opened 2020-12-28 08:28 UTC
![image](https://user-images.githubusercontent.com/2423362/103200815-07357d00-48f7-11eb-9191-2bdf5b0cefb4.png)

**Steps To Reproduce**

To reproduce the behavior:
1. Enable the Language module.
2. Add a RTL language, such as Arabic or Hebrew.
3. Set the newly-added RTL language to be the default.
4. Switch the default admin theme to Basis (or toggle off the "Use the administration theme when editing or creating content" setting)
5. Try to add/edit any type of content.

**Comment by indigoxela** [comment] 2020-12-28 08:35
Another RTL glitch...

`.vertical-tabs::before` needs a `[dir="rtl"]` override.

**Comment by findlabnet** [comment] 2020-12-28 08:52
Cannot reproduce. Seems like you use old codebase (capital letters in the fieldset title?)

![rtl](https://user-images.githubusercontent.com/11479969/103202318-bc1d6900-48fa-11eb-843e-4db4732ab210.png)

**Comment by indigoxela** [comment] 2020-12-28 08:56
> Cannot reproduce. 

@findlabnet your screenshot shows Seven, but the bug is in Basis. Switch off "Use the administration theme when editing or creating content" to off, then you can reproduce.

**Comment by findlabnet** [comment] 2020-12-28 08:59
Sorry, my bad. Never used this approach.

**Comment by findlabnet** [comment] 2020-12-28 09:06
Additional grey "boxes" when editing.

![rtl2](https://user-images.githubusercontent.com/11479969/103202978-93966e80-48fc-11eb-8beb-6a273ad1c8d0.png)

**Comment by indigoxela** [comment] 2020-12-28 09:13
@findlabnet nice catch! While at it, we should also fix the help text border direction for RTL.

**Comment by klonos** [comment] 2020-12-28 09:33
>> Cannot reproduce.
>
> @findlabnet your screenshot shows Seven, but the bug is in Basis. Switch "Use the administration theme when editing or creating content" to off, then you can reproduce.

Sorry about that folks. I've updated the steps to reproduce in the issue summary 👍 

> ...we should also fix the help text border direction for RTL.

Or separate issue and separate PR, so that we can easily revert if we happen to introduce any regressions 😉

**Comment by indigoxela** [comment] 2020-12-28 13:00
A [PR](https://github.com/backdrop/backdrop/pull/3462) is available for testing and review.

My third commit might need some explanation:
I removed a rtl CSS rule, because _padding-top_ can't ever be relevant for LTR/RTL. And it broke vertical tabs on small screens with RTL languages, because it created a needless gap between them.

I know that CSS changes in core themes need to be treated with caution :fearful:, so I'm open for suggestions to separate things in smaller tasks.

**Comment by indigoxela** [comment] 2020-12-28 13:08
Hehe, already found a regression caused by my third commit, so I reverted it.

**Comment by indigoxela** [comment] 2021-03-19 10:58
Trying to revive this issue. It still needs testing and review.

@findlabnet and/or @klonos it would be cool, if you verify that the right-to-left issue is fixed in Basis (and set the issue label accordingly).

**Comment by findlabnet** [comment] 2021-03-19 11:35
@indigoxela I've implemented changes from your PR (2 CSS files) to my local and can confirm resolution of this issue. 
Thank you!

Out of scope for current issue: this form need some more love - borders width should be more consistent, isn't?

**Comment by indigoxela** [comment] 2021-03-19 11:40
@findlabnet many thanks for testing! :bowing_woman: 

> Out of scope for current issue: this form need some more love

So true, but let's do baby steps. Changes in core themes, and especially in Basis, tend to be difficult / problematic.

**Comment by klonos** [comment] 2021-03-19 18:09
Thanks @indigoxela 🙏🏼 ...I've tested the PR, and things work as expected. Code also looks good, but I've left a minor suggestion for consideration. Once I get a reply on that, this will be RTBC.

**Comment by indigoxela** [comment] 2021-03-20 11:30
> I've left a minor suggestion for consideration. Once I get a reply on that, this will be RTBC.

@klonos your suggestion has been committed. :+1:

**Comment by klonos** [comment] 2021-03-20 16:52
Thanks @indigoxela ...retested (just in case), and marking as RTBC 👍🏼

**Comment by quicksketch** [comment] 2021-03-24 00:51
Thanks @indigoxela, @findlabnet, and @klonos! I merged https://github.com/backdrop/backdrop/pull/3462 into 1.x and 1.18.x.

**Closed** 2021-03-24 00:50 UTC
Labels: status - has pull request, status - fixed
