### ISSUE TITLE
Backdrop code linting

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3896] opened 2019-06-28 10:48 UTC
In this week's development meeting, the lack of [linting](https://en.wikipedia.org/wiki/Lint_(software)) for Backdrop was [discussed](https://youtu.be/zUHbSeWYWYs?t=2218). I don't know/understand enough about the topic to try to summarise the discussion here, but wanted to at least get the ball rolling with this issue.

One idea that I took notice of was the suggestion to make it so that pull requests here on GitHub are automatically checked by the linter. Once we have something in place to prevent new code having coding standard issues, we can then look at bulk-fixing existing code.

So what will it take to get an automatic linter for PRs?

**Comment by drupol** [comment] 2019-06-28 10:57
Hi,

I started to do this project: [drupol/backdrop-conventions](https://packagist.org/packages/drupol/backdrop-conventions), maybe it would be something to evaluate ?

It's based on [Grumphp](https://github.com/phpro/grumphp).

**Comment by serundeputy** [comment] 2019-06-28 13:19
@BWPanda I think this is a dupe of https://github.com/backdrop/backdrop-issues/issues/3213

@drupol @BWPanda feel free to chime in on that issue.

**Closed by serundeputy** 2019-06-28 13:19 UTC
Labels: help wanted, needs - more feedback, type - feature request
