### ISSUE TITLE
Added: Distinguish layout-created/module-provided/missing-callback paths on the layout listing page.

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5077] opened 2021-05-04 01:05 UTC
This is a follow-on to https://github.com/backdrop/backdrop-issues/issues/4986, which noted that for pages that have both a module-defined page and a layout with the same path, the page callback that actually gets called depends on the chronological order of the module-enabling and layout-creation that happened in the past. In that issue, I question whether we should have that past-history dependence. In this issue, I accept that dependence, but propose some changes that will make it easier for users to figure out what is going on.

Specifically, I propose to add some formatting to the system paths shown in the first column on the layout listing page at admin/structure/layouts:

1. If the page will be rendered by a module, use the current formatting (bold) for the path.
2. If the page will be rendered by a layout, use bold+italic.
3. If the page won't be rendered at all because there is no menu router item for the page, use bold+red.

Currently, there is no way to tell which of these three situations applies, short of attempting to go to the page and seeing what renders (or 404s, for case 3), which can be more puzzling than illuminating. If you apply the PR below, it's a lot easier to distinguish the different scenarios in https://github.com/backdrop/backdrop-issues/issues/4986. With regard to the 5 scenarios in https://github.com/backdrop/backdrop-issues/issues/4986, you should see:

* Scenario 1: bold (module provides the page)
* Scenario 2: bold+italic (layout provides the page, hiding module page)
* Scenario 3: bold+italic (layout provides the page)
* Scenario 4: bold+red (no menu router item for page, so 404)
* Scenario 5: bold+italic (layout provides the page)

I might also suggest that on the configure layout page, after the user has typed in a path, the AJAX call displays whether that page will be layout-provided or is an existing module-provided page, but that behavior isn't part of the PR below.

-- 

PR by @jenlampton, @bugfolder https://github.com/backdrop/backdrop/pull/3652 separates layouts into two tables
PR by @bugfolder https://github.com/backdrop/backdrop/pull/3864 labels each layout in a single table

**Comment by bugfolder** [comment] 2021-06-25 20:33
In some discussion with @quicksketch, he suggested that as an alternative to the above, we could clarify whether the page for a given path is layout-provided or module-provided by noting (or highlighting) what's in the "Operations" column of the gray path row on the layout page. 

If it is layout-provided, then it will have a "MENU SETTINGS" button in that column. If it was provided by a module and then overridden by a layout, that column will be empty. To make it clearer that it is module-provided, we could put text like "(module-provided)" in that column.

Although...that column is labeled "Operations", and that additional information isn't exactly an operation.

There is an existing example of adding parenthetical information, which is the label for Default layouts, which is "Default layouts (used on all paths without a specific layout)". So perhaps another alternative would be that in the first column, if the path is module-provided, we add the text "(module-provided)" after the path (and not part of the link text if the path is hyperlinked).

**Comment by bugfolder** [comment] 2021-06-26 02:24
So, I added a second PR implementing the solution in the previous comment:
* Added a parenthetical to the "path" column
* Added some formatting so the parentheticals are distinguishable from the path itself
* Kept the red formatting when the menu router item is missing, also added a parenthetical.

Here's a screen shot showing examples. Path "foo" is missing its router item; path nodes/% is module-provided.
![after PR](https://user-images.githubusercontent.com/29214084/123499321-b9ba7400-d5ea-11eb-9628-34f3b5b97a6e.jpg)

**Comment by indigoxela** [comment] 2021-06-26 09:12
Personally, I'm in favor of the second approach (text instead of formatting). :+1: 

IMO formatting alone doesn't actually provide enough information about (possible) problems. Color is even more problematic - think of people with trouble to distinguish some colors (not so rare, actually). Especially red is difficult. And the red text on the darker grey will have less contrast than required, I suppose.

I need some guidance for the third scenario: "If the page won't be rendered at all because there is no menu router item for the page"
Does this only apply to module-provided paths? Or are there other scenarios? How to reproduce that?

**Comment by bugfolder** [comment] 2021-06-26 16:07
A quick way to reproduce the "no callback" scenario is:

1. Enable a module that creates a page at path "foo".
2. Create a layout for path "foo".
3. Disable the module.

It's true that this is not a corner case that one would ever create intentionally. However, for someone new to layouts who is trying things out, they could find themselves in this situation, not realizing that their past history of actions set up this scenario. And now, it's really confusing: "I have a layout for this exact page, but I get a 'page not found' error." So flagging it in some way helps let them know that something is wrong, it's "not just them."

**Comment by indigoxela** [comment] 2021-07-08 13:18
So I tested the path-not-available problem as proposed:

A mini-module with a path:
```
<?php

function testthing_menu() {
  $items['testthing'] = array(
    'page callback' => 'testthing_page',
    'access callback' => TRUE,
  );
  return $items;
}

function testthing_page() {
  return 'There is content!';
}
```
- enabled the module
- added a layout for that path
- disabled the module
- verified the 404
- saved the layout again - no more 404, but also no content
- deleted the layout

Then applied the changes

- enabled the module
- added a layout for that path
- disabled the module
- verified the 404
- went to layout overview page
- there was the "(no callback)" text in red

It might not be super helpful, until people go to the layout overview page, but at least then they get a hint, that something's wrong.

Re the color `#ff1100`: that's way too light on that gray background to comply with WAI, it should be darker, for instance `#c40d00`.

@bugfolder there are currently two PRs related to this issue - I assume you prefer the second approach? If so, you should close the obsolete one.

**Comment by bugfolder** [comment] 2021-07-08 19:16
Updated the color.

I'd left the old PR in place in case anyone wanted to compare the approach. Since the consensus seems to be #2 (add parenthetical text), I'll close the first PR.

**Comment by jenlampton** [comment] 2021-09-09 21:43
I agree that we need to do something to separate the layouts that create stand-alone pages from those that override existing pages, but I'm not sure adding the text "module-provided" does that.  After reading your description of the problems above, I understand what the text denotes, but when I tested the new interface in the sandbox (before reading the issue), I didn't see any improvement. 

I think there's a duplicate issue with another recommendeation. I'm going to go re read that issue too and see where it landed.

**Comment by bugfolder** [comment] 2021-09-09 22:34
So, looking through those issues:

* Having a big block of help text (as in https://github.com/backdrop/backdrop-issues/issues/4868#issuecomment-758759562) would be a big help.
* I don't think that separating paths with and without placeholders into two groups as advocated in https://github.com/backdrop/backdrop-issues/issues/4871 particularly helps clarity.
* What I think IS important is to make obvious the distinction between layout-provided paths and layout-overriding-existing paths (what I was striving for in this issue and PR). Perhaps "module-provided" isn't clear. How about "override"? 
* Nate had pointed out in a Zoom discussion of this issue that the distinction is implicitly conveyed by the presence/absence of the "Menu Settings" dropdown, but I doubt many users would figure that out. I know we're trying to convey a lot of information on this page, but I think this distinction is one of the important ones.

**Comment by jenlampton** [comment] 2021-09-10 03:44
> What I think IS important is to make obvious the distinction between layout-provided paths and layout-overriding-existing paths 

I 100% agree!

> Nate had pointed out in a Zoom discussion of this issue that the distinction is implicitly conveyed by the presence/absence of the "Menu Settings" dropdown.

Also, for the stand-alone pages the `Path` is linked to the stand-alone page, that won't happen for a layout with a placeholder in the path.

> Perhaps "module-provided" isn't clear. How about "override"?

I don't think either one of these phrases mean anything without more context. module-provided what? override what? There's not enough there for anyone who is not already familiar with layouts to know what these labels are describing. I think we would need a whole sentence to properly explain. 

Something we'd talked about (and I can't find where now) was grouping the items in the layout listing differently so that they didn't all end up in a single table. We have different types of things, why not list them separately rather than grouping them all in the same table?

As an example (not fully thought through yet) we could have one table that contained only the **Layout pages** (or, stand-alone layouts where the paths are provided by layout module). Every layout in this table would link to its own page, provide its own menu settings, etc.

Then, we could have another table for **Layout overrides** where a layout wraps around existing content (these are the layouts where the "Main page content" block is required, and the path often has a placeholder in it).

We also have two other kinds of layouts I often want to group separately, but I don't know where they should go.
1) Default layouts - these are the most important but appear at the bottom of the page because they are always the final "else" in the if...else operations.

2) Admin layouts -- these are the least important (least likely to ever be changed) yet Dashboard appears at the top of the list because it starts with `a`.

In a perfect world, I think I'd choose the order to be something like...

FRONT END
- Layout pages
- Layout overrides
- Layout default

ADMIN
- Layout pages
- Layout overrides
- Layout default

Or maybe we could do three tables instead...

DEFAULT LAYOUTS (these layouts will be used if no other layout below matches the visibility conditions)
- front-end
- admin

LAYOUT PAGES (these layouts will create their own stand-alone pages on the site)
- front-end 
- admin

LAYOUT OVERRIDES (these layouts will override existing pages on the site)
- front-end
- admin

**Comment by bugfolder** [comment] 2021-09-10 17:10
> I don't think either one of these phrases [module-provided, override] mean anything without more context...I think we would need a whole sentence to properly explain.

Agreed; that's why I think adding a big honkin' collapsible help text block (a la [#4868 comment](https://github.com/backdrop/backdrop-issues/issues/4868#issuecomment-758759562)) would be very useful; that's where such a sentence would go.

Layouts are one of the most confusing aspects of the D7->Backdrop. Making it easy for people to get some explanation right from the main Layouts page would be really helpful.

Now, for the proposed reorganization...

The distinction between "front-end" layouts and "admin" layouts seems a bit artificial and potentially difficult to implement, beginning with the question: what makes a Layout an "admin" layout? Certainly more than starting its path with "admin", since "node/%/edit" is (usually) an admin page. 

Perhaps a better definition of an "admin" Layout would be one for which the admin theme is used. But that would be hard to determine since [`hook_custom_theme()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_custom_theme/1) could conceivably return the admin theme for any given path.

And in some cases that would mean splitting up layouts that use the same path into different groups. For example, for content types that ordinary users can create, one might use a front-end theme and layout for `node/%/edit` to provide a consistent user experience, but for admin-only content types, use an admin theme and layout for `node/%/edit`. (This is the case on a D7 site I'm porting.)

So making that distinction seems like it could be difficult.

There's a bunch of information we ought to communicate on the main Layouts page for each Layout:

* **What path(s) does it apply to?** This is currently conveyed by grouping by path.
* **Is it a single page or does it apply to multiple pages?** This is conveyed by the presence/absence of "%" and, more noticeably, by whether the path is hyperlinked.
* **Is the path provided by the layout, or by some other module and overridden by the layout(s)?** This is what I was trying to convey (more clearly than the presence/absence of a "Menu settings" dropdown in the Operations column). And I think it's important enough that it belongs in the left column with the path.

If we're going to be doing any grouping, then it's worth asking what's the most important grouping criteria? Because of the importance of the role of the path, I think that path is indeed the most important criteria (so the current arrangement has that right). I don't think that Front-end vs Admin (or non-default vs default) is as important, grouping-wise. Also, each time we add a level of grouping, we consume additional vertical space for the headers and groupings, further expanding what can already be a pretty big, complex page.

> Then, we could have another table for **Layout overrides** where a layout wraps around existing content (these are the layouts where the "Main page content" block is required, and the path often has a placeholder in it).

"Layout overrides" can also override layout-provided pages, based on visibility conditions.

Also, the "main page content" block isn't required in the sense of "you can't create such a layout without a main content block." It's only required in the sense of "the page won't do what you probably wanted without a main content block." It's fairly easy when tinkering with layouts to (unintentionally) create an overriding layout in which the main content block is missing, or to create a non-override layout that has a superfluous main content block. People who know what they're doing won't encounter this; people who are new to Layouts and tinkering and trying things might well end up with either situation. (Perhaps that's a different issue than this one.)

I'd really like to see the distinction between layout-provided and overridden made even more prominent: somehow displayed on both the Configure Layout page (ajax-updated, based on what's in the Path field) and on the Manage Blocks page for the layout (so if it's an override layout and the Main Content Block is missing, there could be some sort of warning). Implementing either of those is a fair bit of work; but just displaying the distinction on the Layouts listing page seems like a good start.

So, I respectfully request reconsideration. (Or at least, further opinions.)

**Comment by jenlampton** [comment] 2021-09-10 22:18
> The distinction between "front-end" layouts and "admin" layouts seems a bit artificial and potentially difficult to implement, beginning with the question: what makes a Layout an "admin" layout? Certainly more than starting its path with "admin", since "node/%/edit" is (usually) an admin page.

This is technically very simple: any page that was defined in `hook_admin_paths()` is an admin page. These are the pages that will appear using the admin theme (if a user has access) and will render using the Default admin layout (assuming no other layout has been provided).

**Comment by jenlampton** [comment] 2021-09-10 22:27
> If we're going to be doing any grouping, then it's worth asking what's the most important grouping criteria? Because of the importance of the role of the path, I think that path is indeed the most important criteria (so the current arrangement has that right). 

I agree with this. I wasn't recommending that we change anything about the grouping by path. I just wanted to separate the most important distinction `Is the path provided by the layout, or by some other module and overridden by the layout(s)?` so that each set of items was in a separate table, perhaps with a heading (and maybe a sentence if we need more words) describing each. 

Maybe It's time to write some code -- I tried to alter the page in my inspector yesterday for a screenshot, but couldn't get anything looking decent.

> "Layout overrides" can also override layout-provided pages, based on visibility conditions.

Hm, that's not exactly what I meant by "Layout overrides" -- again problems with naming things. :/

> Also, the "main page content" block isn't required in the sense of "you can't create such a layout without a main content block." It's only required in the sense of "the page won't do what you probably wanted without a main content block." It's fairly easy when tinkering with layouts to (unintentionally) create an overriding layout in which the main content block is missing, or to create a non-override layout that has a superfluous main content block. People who know what they're doing won't encounter this; people who are new to Layouts and tinkering and trying things might well end up with either situation. (Perhaps that's a different issue than this one.)

yeah, a separate problem. This might be another good use of an un-deleteable block, but with a "hide me" option instead (like the page title: None)

**Comment by jenlampton** [comment] 2021-09-10 23:01
Okay, here's a first stab: 

<img width="1198" alt="Screen Shot 2021-09-09 at 8 26 18 PM" src="https://user-images.githubusercontent.com/397895/132926006-40c47b14-69e5-4e77-8133-1f53b67987a8.png">

**Comment by bugfolder** [comment] 2021-09-10 23:34
> Okay, here's a first stab...

That definitely accomplishes most of what I was after. (Note capitalization inconsistency in the screen shot.)

Having [the red error text if the path is missing](https://github.com/backdrop/backdrop-issues/issues/5077#issuecomment-868930205) would still be nice. (Again, not a situation one would encounter if one knows what one is doing, but it's reachable if one is turning things on and off while trying out Layouts and not knowing what one is doing. Not that I've ever done anything like that, of course.)

Incidentally, the scenario I described (where sometimes `node/%/edit` is admin and sometimes not, depending on the value plugged in for "%') would be difficult to encode using `hook_admin_paths()`.

**Comment by jenlampton** [comment] 2021-09-11 00:04
> Having the red error text if the path is missing would still be nice

We can add that :)

> Incidentally, the scenario I described (where sometimes node/%/edit is admin and sometimes not, depending on the value plugged in for "%') would be difficult to encode using hook_admin_paths().

This use-case is already accounted for in core, but the current PR doesn't separate admin paths from non-admin paths, so we could start with this for 1.20, and debate the admin separation later, if everyone thinks this is an improvement. 

We may still need a better name for "Layout overrides", and a language check on the 1-sentence description under each heading. (I'll see if I can fix the capitalization)

**Comment by jenlampton** [comment] 2021-09-11 00:27
ok, I made a change to the PR that added the warning text when a callback is missing, and tried to fix up the capitalization. It could use testing (especially for the missing path scenario).

**Comment by bugfolder** [comment] 2021-09-11 01:39
I like all aspects of the UX!

* The two sections are not too many divisions and makes the distinction clear and unambiguous.
* The titles and descriptions of each section are clear.
* I like preceding the path with "Path" (or "System path"), which makes it clearer that these words aren't a title, and it also highlights the hyperlinked paths nicely.

My only quibble arises if you do the following (doable on Tugboat demo site):

* Enable the Contact module (which creates a page at path "contact").
* Create a layout with path "contact".

The layout shows up under "Layout pages," but it should appear under "Layout overrides," since the layout is overriding the Contact page (and it does override properly).

Note that if at this point you disable the Contact module, then they layout shows up with the red "(missing callback)" path, which is good.

**Comment by jenlampton** [comment] 2021-09-11 04:02
> The layout shows up under "Layout pages," but it should appear under "Layout overrides," since the layout is overriding the Contact page (and it does override properly).

Ah right. I need to update the check for stand-alone vs overridden layouts. (I had hijacked a previous check in the code for the existence of `%` in the path for my "first stab" but have now replaced that with a check for the `layout_page_callback` callback.)

New PR up for testing :)

**Comment by indigoxela** [comment] 2021-09-11 08:00
Great progress here! Currently several layout related tests are failing, so these have to get updated to also reflect the changes in layout_list_page().

**Comment by bugfolder** [comment] 2021-09-11 15:51
LGTM (aside from tests). Sample screen shot in the PR.

**Comment by stpaultim** [comment] 2021-09-11 19:28
I've looked at this sandbox and this feels like it's a good step in the right direction. I believe that the changes are providing with me valuable information, but I'm still not quite sure what that new information is and/or how it applies to me. 

I've spend a while trying to come up with constructive ideas/suggestions to no avail. So, instead I'll just give you my reactions to the proposed changes and my questions - hopefully they will inspire useful ideas. NOTE: Some of my questions exist prior to these changes. 

1) I am having a hard time grasping our use of the word "override" here. I think that this problem has been acknowledged already by others. 

a - Are layout overrides layouts that override other layouts. No, I don't think that is what we are saying. 
b - Are layout overrides any layout that is not a stand alone layout in the top section. The top section seems to be for layouts that are specific to a path that they have defined themselves. But, then I see the "/contact" layout under Layout Overrides and I'm confused about how that is different from "/dashboard." /contact seems to fit this description I gave for the top section "layouts that are specific to a path that they have defined themselves."
c - Are layout overrides layouts that effect the appearance of pages that would exist even if this layout didn't exist. Is the difference, that the top section "Layout Pages" is for layouts that in a sense create a NEW page that never before existed (without this layout) and that the "Layout Overrides" is layouts that will apply and change the appearance of pages that already exist and would exist even if this layout didn't exist. 

NOTE: It took writing everything above for me to come to my current assumption which is that "C" is probably the right answer. 

2) The RED "Path: contact (missing callback)" tells me that something is wrong with this layout and it's broken. That is probably very helpful. However, I'm not quite sure what "missing callback" means, but then again that may not matter, because the important message is clear - something is broken and I will probably be able to solve the problem with or without understanding exactly what "Missing Callback" means. 

3) I'm still a little unsure about whether the order of the "Layout Overrides" tells me anything meaningful about the which layout will override which layout. I kinda of assume that the first applicable layout in that (Layout Overrides) list is the one that will be applied to a page. 

- - - - -

Would something like the following be helpful:

`Layout pages` `These layouts will create their own stand-alone pages on the site, pages that would not exist without this layout.`
`Layout overrides` `These layouts will override existing pages on the site.`

In hindsight, I believe that the difference between "stand-alone-pages" and "existing pages" wasn't quite clear (enough) to me. Something that helps clarify that would go a long way towards making this page more helpful to me.

**Comment by bugfolder** [comment] 2021-09-11 19:42
> It took writing everything above for me to come to my current assumption which is that "C" is probably the right answer.

Yup.

>  /contact seems to fit this description I gave for the top section "layouts that are specific to a path that they have defined themselves."

The Layout with path /contact was originally an override of the page provided by the Contact module with that path, so this layout started as a proper override. Disabling the Contact module removed that path from the menu router table. I _think_ the only way to get to this situation is to start with an other-module-provided path with the Layout overriding it, so it makes some sense to list the problematic layout in this section.

Or we could have another section titled "Broken Layouts", which would eliminate the need for the extra text (and which only appears if non-empty). I kinda like that; seems more direct.

Your comment provides really good support to the notion that "Layouts are hard to wrap our head around". The one-sentence descriptions are good reminders (or hints) of what the categories mean, but [having a more extended chunk o' collapsible help text](https://github.com/backdrop/backdrop-issues/issues/4868#issuecomment-758759562) would also be really nice.

**Comment by stpaultim** [comment] 2021-09-11 19:44
Thanks @bugfolder. 

What about the issue I mentioned about the "Default Layouts"? Would it make sense to distinguish them from "Layout Overrides"? Is it just me, or isn't that contradictory?

**Comment by bugfolder** [comment] 2021-09-11 20:04
Hmm, the default layouts seem to me like a special case of overrides, since they apply to existing pages, just like overrides. The difference is that they apply to a whole bunch of existing pages with varying paths, while other overrides only apply to a single page or family of pages (if there are placeholders).

(Just to muddy the waters, [Layout Wildcard](https://github.com/backdrop-contrib/layout_wildcard/tree/1.x-2.x) allows layouts to override multiple "alternative paths", making every non-default layout potentially able to act like an override.)

The functional underlying difference between "layout pages" and "layout overrides" (whatever we call them) is what gets called as the page callback: for the former, it's `layout_page_callback()`; for overrides, it's anything else. But that's probably not very useful in explaining to the average user.

**Comment by jenlampton** [comment] 2021-09-13 01:01
> Would it make sense to separate the Default layouts from the Layout Overrides. Should Default Layouts be a third section?

I also wondered that... I'll try it in a separate branch.

> That is probably very helpful. However, I'm not quite sure what "missing callback" means, but then again that may not matter, because the important message is clear - something is broken and I will probably be able to solve the problem with or without understanding exactly what "Missing Callback" means.

Yeah, I wondered about that. Do you feel the same about the blocks/views messages "Missing plugin" or "Broken or Missing handler"? Maybe we should revisit all of those and use some friendly messaging in the UI (with more technical messaging in the dblog) 

> I'm still a little unsure about whether the order of the "Layout Overrides" tells me anything meaningful about the which layout will override which layout. I kinda of assume that the first applicable layout in that (Layout Overrides) list is the one that will be applied to a page.

The order really only matters if you have multiple layouts at the same path (or system path). And in those cases, it does matter. (Hence the "reorder" button not otherwise visible)


> In hindsight, I believe that the difference between "stand-alone-pages" and "existing pages" wasn't quite clear (enough) to me. 

I like your suggestions!

> Or we could have another section titled "Broken Layouts", which would eliminate the need for the extra text (and which only appears if non-empty). I kinda like that; seems more direct.

I'll try it in a separate branch too :)

> The one-sentence descriptions are good reminders (or hints) of what the categories mean, but having a more extended chunk o' collapsible help text would also be really nice.

I agree. I don't think this issue is enough, we need both!

**Comment by stpaultim** [comment] 2021-09-13 05:06
>  I've pushed an update to the current PR with a little more text for each description:

I think this is a real improvement. There is more work to be done on this page, but I'm happy to make the improvements incrementally. 

> Yeah, I wondered about that. Do you feel the same about the blocks/views messages "Missing plugin" or "Broken or Missing handler"? Maybe we should revisit all of those and use some friendly messaging in the UI (with more technical messaging in the dblog)

As with "Missing Callback" I'm not quite sure what "Broken or Missing handler" means literally. However, in both cases the context of the message usually makes it pretty clear what to look for in terms of fixing it. That being said, I suspect that we could come up with better language that more users would understand.

**Comment by klonos** [comment] 2021-09-13 14:33
> I think this is a real improvement. There is more work to be done on this page, but I'm happy to make the improvements incrementally.

I also agree with that. Baby steps 😉

**Comment by bugfolder** [comment] 2021-09-13 16:01
Agreed.

**Comment by bugfolder** [comment] 2021-12-14 22:58
Partly because I've really like to see this happen, and partly because there's so many other things that need Jen-cycles that I'm reluctant to ask for some on this issues, I've made a new PR https://github.com/backdrop/backdrop/pull/3864 that (a) is mergeable, (b) passes all automated tests. Testing/code review requested!

**Comment by docwilmot** [comment] 2021-12-15 21:34
TBH I feel that splitting this into two table produces a bit too much visual clutter. I would prefer just a parenthesis after each path that says "overriden path" or "layout path" or such. Its already a busy table; to make it *two* busy tables doesnt seem worth the benefit to me.

**Comment by bugfolder** [comment] 2021-12-15 21:41
> TBH I feel that splitting this into two table produces a bit too much visual clutter. I would prefer just a parenthesis after each path that says "overriden path" or "layout path" or such.

Heh. That was [my original proposal (above)](https://github.com/backdrop/backdrop-issues/issues/5077#issuecomment-868930205).

**Comment by docwilmot** [comment] 2021-12-15 21:53
Yep that was what I was looking at. I'd prefer that.

**Comment by bugfolder** [comment] 2021-12-17 15:29
OK, I have taken the liberty of renaming the issue to focus on the problem being solved, rather than just one possible solution, and to help folks evaluate the two possibilities, I'll post screenshots of both below with some pros and cons. They'll be in two consecutive comments so that people can indicate their preference with thumbs-up on the one they like (if either).

**Comment by bugfolder** [comment] 2021-12-17 15:33
PR https://github.com/backdrop/backdrop/pull/3652: add text after the path if module-provided or missing callback.

Pros:

* Keeps the current wholly alphabetical ordering of paths on the page, just adds additional annotation.
* Page isn't any longer than it was before.

Cons:

* Layout-provided pages and module-provided pages are intermingled, so less clearly distinguished.

![3652 example](https://user-images.githubusercontent.com/29214084/146568860-42ab5b08-c5bc-4d08-bfe9-15b731ddfd5b.jpg)

**Comment by bugfolder** [comment] 2021-12-17 15:37
PR https://github.com/backdrop/backdrop/pull/3864: Group different types of layouts into different tables.

Pros:

* Layout-provided pages are clearly distinguished from module-provided pages

Cons:

* Page is overall longer, has more structure.
* 
![3864 example](https://user-images.githubusercontent.com/29214084/146569520-812b3bac-9ec5-449d-b13c-82e3a0a9b51e.jpg)

**Comment by stpaultim** [comment] 2021-12-21 03:16
In my opinion, the first option doesn't really help me at all. I don't get any new information from that table (with text), at least I don't get any new information that I understand. 

I do feel like the second option is providing me with new information that does make sense to me. 

Based upon my understanding of the problem that we are trying to solve, I prefer the second option. 

We have a number of different PR's out there right now that will make this page easier to understand. I'm confident that this one, along with the the one that provides a bunch of help text, will be very helpful.

**Comment by jenlampton** [comment] 2021-12-21 04:00
I also prefer the second, and I don't mind the page being longer since it will be easier to understand.

**Comment by yorkshire-pudding** [comment] 2022-01-13 20:57
I prefer the second (#3864)

**Comment by bugfolder** [comment] 2022-01-13 21:01
In the 2022-01-13 design meeting, we discussed this, and those present all preferred the second PR (3864) (as do I). So I will close the first PR so that we can proceed with testing and code review.

**Comment by Wylbur** [comment] 2022-01-13 21:03
After getting a demo of this at the Weekly UX meeting, I also prefer the presentation in the second pull request #3864.   So plus one for the separate sections.

**Comment by bugfolder** [comment] 2022-02-11 03:35
> On the confirm form. "Warning: the page at path mypage will no longer exist" or such. What you think?

I think that's good! PR updated.

**Comment by bugfolder** [comment] 2022-02-11 22:02
OK, here's where we're at. The majority view is in favor of using the two-tables approach, which is that in the current PR. And I've added a warning to the confirmation page if the layout being deleted is for a layout-created page AND is the last layout for that path. And I've rebased the PR on the current state of Backdrop core, and added some fixes for tests so that they're coming up green.

So, asking for folks to test and code-review!

Incidentally, one of the fixes for PHP 8.1 is suggestive of a separate core issue for `path_is_admin()`, but I'll open a separate issue for that.

**Comment by klonos** [comment] 2022-02-15 01:11
I really like where this is going! Thank you @bugfolder 🙏🏼 

> > On the confirm form. "Warning: the page at path mypage will no longer exist" or such. What you think?
>
> I think that's good! PR updated.

I would like us to do the following please:
- Provide another button in the confirmation form, that disables the layout instead of deleting it.
- Change the message to somethings like this: `Deleting this layout will permanently delete the page at /%path. This action cannot be undone. If you are unsure, then consider disabling the layout instead of deleting it.`
- Consider making the "destructive" bit of the text a warning message.
- See if we can use `confirm_form()` for all this, since that's the purpose of that function.

**Comment by jenlampton** [comment] 2022-02-15 02:49
@klonos Can you move your suggestions into follow-up issues if they are not directly applicable to the current PR? Disabling a layout might be considered a new feature, and may need additional tests added. This is just a UX cleanup task as it is now so I wouldn't want to block its progress :)

**Comment by bugfolder** [comment] 2022-02-15 17:46
> See if we can use `confirm_form()` for all this, since that's the purpose of that function.

The current code for `layout_delete_form()` suggests that we can:

```
function layout_delete_form($form, &$form_state, $layout) {
  $form_state['layout'] = $layout;
  ...
  return confirm_form($form, $question, 'admin/structure/layouts', $text, $button_text);
}
```

I'll echo @jenlamption's suggestion that we move the addition of the disable button to a follow-up issue, and will suggest that the change of warning message to suggest disabling also should happen there. 

And I'll add a further suggestion for that follow-up: that in addition to checking whether for layout-created pages this layout is the last layout for its path, we _also_ check whether this layout's page is any of the Home page or either Error page on `admin/config/system/site-information`, so that the user doesn't inadvertantly delete those important pages.

Rather than having two PRs (this one and the follow-up) that both tinker with `layout_delete_form()` (thereby almost certainly requiring some future merging/rebasing), I'm going to remove the added warning from this PR, to keep this one focused on the layout listing page, but will add that warning back in the PR that tackles the follow-up issue, https://github.com/backdrop/backdrop-issues/issues/5511.

**Comment by klonos** [comment] 2022-02-15 19:32
Thank you @bugfolder 🙏🏼 ...all that makes absolute sense of course.

**Comment by yorkshire-pudding** [comment] 2022-03-25 09:07
@bugfolder - is there any other feedback you need? Other than my [comment above](https://github.com/backdrop/backdrop-issues/issues/5077#issuecomment-1038917947) I think it is great.

**Comment by bugfolder** [comment] 2022-03-25 13:47
@yorkshire-pudding, I don't think more feedback is needed; just testing (hopefully ending in a "WFM" and removal of the "needs testing" label) and code review (hopefully ending in removal of the "needs code review" label and addition of the "RTBC" label).

**Comment by bugfolder** [comment] 2022-03-25 15:50
@yorkshire-pudding, to address your comment above:

> I found myself asking what other layout would be used if the defaults were not there?

Yeah, that's kind of vague. But the answer, I think, would also still be vague, even if more detailed:

> These layouts will override existing pages on the site. Without these layout overrides, these pages would use other layouts. Which layout gets used would depend on the visibility conditions of layouts whose paths match, or possibly one of the default layouts if no other layouts match."

Doesn't seem to me like that extra bit of information "pulls its weight" relative to the amount of space it adds to the page (particularly considering that the same information is given in the "How layouts work" details section at the top of the listing).

**Comment by jenlampton** [comment] 2022-04-21 20:28
> These layouts will override existing pages on the site. Without these layout overrides, these pages would use other layouts. Which layout gets used would depend on the visibility conditions of layouts whose paths match, or possibly one of the default layouts if no other layouts match."

These layouts will override existing pages on the site. Without them, these pages would use other layouts. Which one would depend on the path and visibility conditions. If no other layouts match, one of the default layouts will be used."

**Comment by bugfolder** [comment] 2022-04-21 21:20
Some discussion at today's meeting to add more to "How Layouts work". Moving to "PR needs work" for the moment.

**Comment by yorkshire-pudding** [comment] 2022-04-21 21:23
Give me a shout when you are ready for me to review

**Comment by bugfolder** [comment] 2022-04-22 01:38
I've updated "How Layouts Work" and the text below each section per our discussion today. Here's a screenshot for easy reading. @yorkshire-pudding (and others), please take a look. 

I noticed one small inconsistency. If we have two "layout pages" with the same path, they both appear in the "Layout pages" section, but technically, one of them is overriding the page created by the other. (See layouts "Home page 2" and "Home page" in the example below.) It's not clear that this scenario is worth still more words of explanation, but I'm certainly open to further suggestions.

![layouts](https://user-images.githubusercontent.com/29214084/164579532-3e0aa484-00a8-4abc-8040-7f495a6c9d74.jpg)

**Comment by yorkshire-pudding** [comment] 2022-04-22 07:21
@bugfolder - I think your existing description clearly explains this scenario.  It explains the order they are processed and that they can be re-ordered, so I don't think anything further is needed.

**Comment by yorkshire-pudding** [comment] 2022-04-22 08:12
@bugfolder - review added

**Comment by bugfolder** [comment] 2022-04-22 21:07
Thx, changes made! @yorkshire-pudding, please re-review & re-test (and, if it passes, add the "milestone - bug" label, since it's a "task").

**Comment by yorkshire-pudding** [comment] 2022-04-22 21:38
Re-reviewed and re-tested.  Breakpoint works and all works as expected. Thanks @bugfolder - will be a great improvement to the user experience for layouts

**Closed** 2022-04-23 22:18 UTC
Labels: status - has pull request, design, status - fixed

**Comment by quicksketch** [comment] 2022-04-23 22:21
Merged https://github.com/backdrop/backdrop/pull/3955 into 1.x and (as a UX improvement) into 1.21.x. Thanks everyone for the rounds of feedback and collaboration to make this happen!

https://github.com/backdrop/backdrop/commit/0965fa69f7c56b5b30b6a2605d1167875054019d by @bugfolder, @jenlampton, @yorkshire-pudding, @klonos, @indigoxela, @docwilmot, and @stpaultim.
