### ISSUE TITLE
Fix PHP Notice: Undefined index: form_build_id in ajax_get_form()

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#5041] opened 2021-04-15 23:44 UTC
**Steps To Reproduce**

To reproduce the behavior just go to http://backdrop.site/system/ajax and the log will show the following notice:

> Notice: Undefined index: form_build_id in ajax_get_form() (line 323 of /var/www/docroot/core/includes/ajax.inc).

and the warning:

> Invalid form POST data.

**Additional information**

Normally, the `system/ajax` page should not be accessed directly. Regardless, an additional check could help to avoid the above warning and notice.

**Comment by indigoxela** [comment] 2021-04-16 06:06
@alanmels Oh, this behavior annoys me for ages in Drupal (...Invalid form POST data)! Yes, let's fix it in Backdrop.

I'll try to test and review your PR soon (weekend is coming). :smile:

**Comment by klonos** [comment] 2021-04-16 14:53
Thanks @alanmels ...I confirmed this issue with both vanilla D7 and Backdrop. The issue is fixed in the PR sandbox 👍🏼 

Code-wise, this is a simple 1-line fix, but not sure if it is the proper way to fix this or not (don't know much about the internals of the AJAX system in Drupal/Backdrop), so I'll let someone else mark this RTBC.

PS: I tried to find any reports of this issue filed for Drupal core, and the only relevant one I could find was https://www.drupal.org/node/1833746. Is there any respective issue in d.org?

**Comment by alanmels** [comment] 2021-04-16 16:07
@klonos Besides https://www.drupal.org/node/1833746 that you've found there is another relevant discussion on https://drupal.stackexchange.com/questions/120787/error-undefined-index-form-build-id-in-ajax-get-form, however both are about some contributed modules' interaction with AJAX, whereas this case is purely about the `system/ajax` page accidentally accessed directly. As I said:

> Normally, the system/ajax page should not be accessed directly. Regardless, an additional check could help to avoid the above warning and notice.

**Comment by klonos** [comment] 2021-04-17 11:20
> ...accidentally accessed directly.

Yes, that's what surprised me actually. I was able to replicate the problem in vanilla D7, so it seems odd that it was never reported for core, and all discussions are around modules.

**Comment by indigoxela** [comment] 2021-04-17 12:26
To describe, why this annoys me for so long:

It seems to happen, that proxies (client side) or security tools try to call that path, but with invalid or missing data. This causes useless rows in dblog. There's simply no point in proceeding in that function, if it's already clear that there's only garbage or nothing to handle.

@alanmels I've left a suggestion in a comment on your PR. I can confirm that it also works for me. :+1:

**Comment by alanmels** [comment] 2021-04-17 15:06
Thanks, guys, for the updates! @indigoxela, I've replied to your comment on the PR, could you please review it again?

**Comment by indigoxela** [comment] 2021-04-25 08:47
@alanmels I let you decide to do additional validation. After some days, I assume you decided not to do that - which I'm totally fine with. My Github permissions aren't sufficient to close my comment on your PR as "resolved", so please do it yourself.

RTBC :+1:

**Comment by alanmels** [comment] 2021-04-25 16:30
> @alanmels After some days, I assume you decided not to do that.

@indigoxela Oh, no, I've been just too busy with other things. I've just made the change. Thanks for reviewing!

**Comment by quicksketch** [comment] 2021-05-04 00:45
Thanks folks! Merged https://github.com/backdrop/backdrop/pull/3587 into 1.x and 1.18.x.

**Closed** 2021-05-04 00:44 UTC
Labels: status - has pull request, status - fixed
