### ISSUE TITLE
Text filter configuration is not saved  v1.16.0

### ISSUE THREAD

**Issue by metatop** [backdrop/backdrop-issues#4400] opened 2020-05-17 22:19 UTC
**Description of the bug**

Text filter configuration is not saved from the v1.16.0

Test online and localhost

Video:
https://youtu.be/7Ipohsxs7jo

**Comment by indigoxela** [comment] 2020-05-18 11:44
Confirmed, some values from filter settings don't get saved.

Lost values: filter_url_length, filter_html_nofollow, filter_html_help

These worked fine in the previous version, but somehow broke, probably with https://github.com/backdrop/backdrop/commit/3489233cbc95869d1748c27f875bbca5e14d10f0

I tried to figure out, what the reason is, but am not sure.
Maybe it's related to the tempstore thing. When are the values from tempstore supposed to come back in? On form validation, or on submit?

**Comment by indigoxela** [comment] 2020-05-19 08:16
A [PR](https://github.com/backdrop/backdrop/pull/3144) is available for testing and review.

It's reordering the submit function a bit (order matters!), but the main thing is that it get's the filter settings back from tempstore.

One thing is missing: a Simpletest that actually catches the problem described in this issue. There are several tests, but none actually seems to cover the problem of values not being saved.

**Comment by indigoxela** [comment] 2020-05-19 09:26
Test for config value has been added.

**Comment by herbdool** [comment] 2020-05-19 11:18
I've looked at the code and it looks good to me. I have not tested.

**Comment by herbdool** [comment] 2020-05-19 11:30
Allowed HTML worked for me, but not URL length. I'm not sure why. Just tested in the sandbox.

**Comment by indigoxela** [comment] 2020-05-19 11:33
@herbdool can you describe your testing steps, please? I just tested successfully _filter_url_length_ in the sandbox.

**Comment by herbdool** [comment] 2020-05-19 11:38
It's perhaps because I first edited URL length, then the allowed HTML. I did not save the form in between. Perhaps that's what I did wrong. (That could be a new issue if we want to change that)

**Comment by indigoxela** [comment] 2020-05-19 11:47
> It's perhaps because I first edited URL length, then the allowed HTML

I can reproduce this.

1) Edit filter_url_length (click Update)
2) Add <audio> to allowed html (click Update)
3) Pull table into the editor active toolbar (save format)

And when I re-opened the Filtered HTML form I got:

1) filter_url_length was NOT set correctly
2) Both, the table tags and the audio tag were still in allowed html
3) The table icon was still in the active toolbar

So the tempstore approach still has some glitches. Any hint is welcome.

**Comment by indigoxela** [comment] 2020-05-19 15:29
Some progress here, but the PR still needs work.

I made an (uncommited) test to check consecutive filter setting form submits, which unfortunately still fails.
I'll fix that when I'm less hungry... :wink:

**Comment by quicksketch** [comment] 2020-05-20 02:47
Oh no, this is a biiig problem. We're going to be making a release _tomorrow_ for other reasons. It would be definitely preferable if we can get this fixed at the same time, rather than needing to make 2 releases.

**Comment by indigoxela** [comment] 2020-05-20 06:26
The new tests are also passing now (here on my dev). OK, a little under time pressure and Github/ZenCI fail to get a test box running, meh...

The new tests cover the consecutive form submit problem we discovered yesterday.

@quicksketch thanks for commenting, but... I suspect you mixed up setting and getting values when loading the form - unless I totally misunderstood something.

Maybe the two newly added tests better explain the changes I made.

**Comment by indigoxela** [comment] 2020-05-20 14:41
How to test:

In the sandbox open a text format, then try all sorts of combinations in random orders:

- Edit URL filter settings
- Edit allowed html settings, add/remove tags (also play with the checkboxes for help and nofollow)
- Drag and drop icons into the active editor toolbar

After clicking around save the format, reopen the form and check if all your settings were saved.

Adventurous testers can do this with javascript disabled in the browser.

**Comment by quicksketch** [comment] 2020-05-20 16:13
Thanks @indigoxela! I'm trying it out now. I posted another comment to the PR (https://github.com/backdrop/backdrop/pull/3144#discussion_r428135099). I don't understand how the new code works, but I'm pulling it down to test locally.

**Comment by quicksketch** [comment] 2020-05-20 17:22
Okay, I was having trouble understanding the PR because we have multiple systems updating `$form_state`. There's our manual tempstore_set() calls but then there's also the Form API cache that also uses tempstore.

I'm still not entirely sure how @indigoxela's PR works, but the test coverage shows that it works without AJAX and in testing the sandbox and locally, it seems to work with AJAX.

Longer term I think we might make this less confusing by using `$form_state['no_cache']` to suppress the Form API cache. That's what Views UI does when it uses tempstore. However, doing that would probably cause other things to fail, like the AJAX-loading of the editor settings.

So @indigoxela's changes seem like the best solution: where we get things working with minimal change, even though we're storing in-progress values in tempstore twice.

@indigoxela do you have any other concerns at this point?

**Comment by indigoxela** [comment] 2020-05-20 18:06
> do you have any other concerns at this point?

Not actually.
Funny that you also spent some time head scratching over my code - that's what happened to me with yours.

> Longer term I think we might make this less confusing

Absolutely.

If the merge happens today, let's open a follow-up issue right after closing this one. With this fix going out, we make sure people don't break their filter settings because they updated because of a "Wednesday release" (which usually should get done quicker than simple milestone updates).

But that part of code for sure deserves a closer look, overly complicated stuff is never the best choice.

**Closed** 2020-05-20 18:48 UTC
Labels: pr - ready to be committed, pr - works for me, status - has pull request, type - bug report

**Comment by quicksketch** [comment] 2020-05-20 18:51
I've merged https://github.com/backdrop/backdrop/pull/3144 into 1.x and 1.16.x for the 1.16.1 release. Thanks @indigoxela for fixing this critical issue!!

Thanks @metatop for reporting!! And thanks @klonos and @herbdool for facilitating and reviewing. :raised_hands:

**Comment by klonos** [comment] 2020-05-20 20:36
> If the merge happens today, let's open a follow-up issue right after closing this one.

@quicksketch @indigoxela follow-up created here: 4409
