### ISSUE TITLE
Contact module settings: Permissions do not stick for the Administrator role

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6063] opened 2023-04-17 14:49 UTC
## Description of the bug

It seems that the Contact module permission checkboxes for the Administrator role are always reset to ticked/enabled.

## Steps To Reproduce

To reproduce the behavior:
1. Enable the Contact module
2. Navigate to admin/structure/contact/settings -> by default, all permissions are ticked for the Administrator role
3. Enable some of the permissions for other roles, and disable some or all of the permissions for the Administrator role.
4. Save the form -> the permissions for the other roles are saved properly 👍🏼 however, all permissions for the Administrator role are reset to enabled 👎🏼 
5. Repeat steps 3 and 4 with different roles/permissions -> 

## Actual behavior

Every time the permissions for the Administrator role are being reset (enabled).

## Expected behavior

The permissions for the Administrator role should be saved properly.

## Additional information

I have tested the same with the permissions matrix available in the content type edit form, and the permissions there seem to be working as expected. So this issue seems to be limited to the permissions matrix in the Contact module permissions. We should check other permission matrices as well though, to make sure.

**Comment by jenlampton** [comment] 2023-04-17 21:24
Permissions issues are critical, so adding bug-fix milestone candidate label.

**Comment by klonos** [comment] 2023-04-20 17:05
Noting that we don't need this for 1.x if we merge #5031. I confirmed that cannot reproduce this issue in the sandbox of the PR for that issue 😉

**Comment by bugfolder** [comment] 2023-09-29 02:29
Although https://github.com/backdrop/backdrop-issues/issues/5031 is not yet merged, I just tested this with the 1.27.x-dev version (as of 2023-08-28), and I don't see the problematic behavior. If I just check the "Editor" permission and uncheck all "Administrator" permissions, then save, that is reproduced after saving.

Couldn't test this on the sandbox because Tugboat didn't build the sandbox when I closed and reopened the PR. But it appears that this issue has been fixed by other means.

Git blame tells me this was fixed by PR https://github.com/backdrop/backdrop/pull/4472 for issue https://github.com/backdrop/backdrop-issues/issues/6117, which has been merged into 1.26.1. (And it's exactly the same change in the PR.)

Closing the issue as no longer needed.

**Closed by bugfolder** 2023-09-29 02:29 UTC
Labels: status - duplicate, status - has pull request
