### ISSUE TITLE
[UX] Time picker in Date Pop-up calendar does not respect time format

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop/backdrop-issues#5703] opened 2022-08-02 10:36 UTC
## Description of the bug
~~Firstly,~~ an AM/PM is shown when time is set to use `G` for hour (i.e. 24 hour with no leading zeroes).  In #4064 @VasasA proposed a solution which works:
On
https://github.com/backdrop/backdrop/blob/8ce893d89106993c37ada5339355c9ead03bb8e8/core/modules/date/date.elements.inc#L1170

Change:

```php
      'show24Hours' => strpos($element['#date_format'], 'H') !== FALSE ? TRUE : FALSE,
```

to:

```php
'show24Hours' => (strpos($element['#date_format'], 'H') !== FALSE || strpos($element['#date_format'], 'G') !== FALSE) ? TRUE : FALSE,
```

but because the other issue in the ticket (dot after date) could not be solved, this has not been implemented.

~~Secondly, the tooltip has a time that doesn't respect the time format, e.g. 04:34PM and 05:34PM~~

~~I cannot work out where this is coming from.~~
Is Chrome autofill 

## Steps To Reproduce

To reproduce the behavior:
1. Add a date field to content type
2. Pick a date time format with G for time format
3. Create a content and click into the time field

## Actual behavior
Only 12 hour clock can be entered and PM is shown after
~~Tooltip shows in 12 hour format~~
![chrome_sDc44RExoW](https://user-images.githubusercontent.com/20357797/182354438-10411c65-626a-4da8-b46c-777e676d4e53.gif)

## Expected behavior
24 hour time can be entered
~~Tooltip respects the time format~~

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.22.2
- Web server and its version: litespeed
- Operating System and its version: n/a
- Browser(s) and their versions: Chrome 103

**Comment by yorkshire-pudding** [comment] 2022-08-02 10:43
I've added a [PR](https://github.com/backdrop/backdrop/pull/4153) that addresses the first part.  Credit for this should go to @VasasA .  However, I cannot work out how to fix the tooltip, if that is too hard, we should go ahead with the PR as it stands

**Comment by indigoxela** [comment] 2022-08-02 12:44
I've never seen a time tooltip on core date fields (with datepicker enabled). How do I have to setup the widget to get one?

**Comment by yorkshire-pudding** [comment] 2022-08-02 13:14
Did you find where it is? Does that mean its possible to disable it?

**Comment by indigoxela** [comment] 2022-08-02 13:47
> Did you find where it is?

No... reading the core code - it should be there OOTB, right? Never saw one. Also not on D7...

Please enlighten me! :bulb:

**Comment by yorkshire-pudding** [comment] 2022-08-02 13:49
I don't know. I'll try in a different browser

**Comment by indigoxela** [comment] 2022-08-02 13:57
I tried in FF and Chrome on Linux. The script is loaded, but I never saw any time popup (tooltip).

**Comment by yorkshire-pudding** [comment] 2022-08-02 14:00
Was a Chrome autofill.  It must have added whilst I was testing before I fixed the format.

**Comment by indigoxela** [comment] 2022-08-02 14:18
Nevertheless, `G` should still lead to a 24 hour format - which it currently doesn't (confirmed).

But... even with the patch applied, the format still has leading zeros. Probably because the datepicker widget is a bit opinionated when it comes to input formats.

**Comment by yorkshire-pudding** [comment] 2022-08-02 14:35
Yes, I couldn't find anywhere to change that, but it didn't bother me as much as not being able to enter 24 hour time.  If there is a simple way to force it to use the format, then great, but if not, in my opinion, it shouldn't stop the 24 hour fix going in.

**Comment by yorkshire-pudding** [comment] 2022-08-02 15:02
😄  all automated tests have passed ✔️

**Comment by indigoxela** [comment] 2022-08-03 07:27
Seems like we agree, that the 24-hour format problem should get fixed - no matter if the leading zeros are there or not.

It works for me. :+1:

**Comment by herbdool** [comment] 2022-08-05 11:50
Looks good to me!

**Comment by quicksketch** [comment] 2022-09-15 04:57
Merged into 1.x and 1.22.x. Thanks folks!

**Closed** 2022-09-15 04:56 UTC
Labels: type - bug report, pr - ready to be committed, pr - works for me
