### ISSUE TITLE
Random failure: Exception Notice: path.admin.inc, line 862, path_bulk_update_batch_finished()

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5201] opened 2021-09-06 11:26 UTC
Part of the #1478 meta.

I've seen this random failure only in php7.4 tests so far:

```
Comment: Comment interface (CommentInterfaceTest) 2427 passes, 2 fails, 0 exceptions, and 689 debug messages. [184.645s]

Test run duration: 7 min 33 sec

Detailed test results
---------------------
Fail      Other      comment.test       526 CommentInterfaceTest->testCommentNe

Fail      Other      comment.test       529 CommentInterfaceTest->testCommentNe

Exception Notice     path.admin.inc     862 path_bulk_update_batch_finished()  
---- Comment: Comment interface (CommentInterfaceTest) ----
```

```
Exception Notice     path.admin.inc     862 path_bulk_update_batch_finished()  
Status    Group      Filename          Line Function                            
--------------------------------------------------------------------------------
    Link with label 1 new comment not found.
    Array
    (
        [0] => SimpleXMLElement Object
            (
                [@attributes] => Array
                    (
                        [class] => node-readmore odd first
                    )
    
                [a] => Read more
            )
    
        [1] => SimpleXMLElement Object
            (
                [@attributes] => Array
                    (
                        [class] => comment-comments even
                    )
    
                [a] => 1 comment
            )
    
        [2] => SimpleXMLElement Object
            (
                [@attributes] => Array
                    (
                        [class] => comment-new-comments odd
                    )
    
                [a] => 1 new comment
            )
    
        [3] => SimpleXMLElement Object
            (
                [@attributes] => Array
                    (
                        [class] => comment-add even last
                    )
    
                [a] => Add comment
            )
    
    )
```

```
---- Path: Path pattern bulk updating (PathPatternBulkUpdateTestCase) ----


Status    Group      Filename          Line Function                            
--------------------------------------------------------------------------------
    Trying to access array offset on value of type bool
    Trying to access array offset on value of type bool

Error: Process completed with exit code 1.
```

Could be related to these random failures that happen from time to time:

```
Path: Path pattern bulk updating (PathPatternBulkUpdateTestCase):
"Generated 20 URL aliases." found path_pattern.test:929
"Generated 1 URL alias." found path_pattern.test:943
```

**Comment by indigoxela** [comment] 2021-09-06 11:55
Closing as duplicate of #5189 and #4862 - both failures already have their own issue.

**Closed by indigoxela** 2021-09-06 11:55 UTC
Labels: type - bug report
