### ISSUE TITLE
PHP Warning: Undefined array key "alt" in theme_icon()

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6760] opened 2024-11-23 03:56 UTC
## Description of the bug

When running on_the_web module I'm seeing a handful of PHP warnings, one for each icon:

```
Warning: Undefined array key "alt" in theme_icon() (line 327 of /var/www/html/docroot/core/includes/icon.inc).
```

Line 327 is as follows:
```php
if (isset($variables['alt']) {
```

The warning comes because in `hook_theme()` we are not specifying `alt` as an allowed value:
```php
  'icon' => array(
      'variables' => array(
        'name' => NULL,
        'path' => NULL,
        'attributes' => array('class' => array()),
        'wrapper_attributes' => array('class' => array()),
      ),
    ),
```
But when you call the `icon()` function to display an icon, we are passing the `alt` in as though it should were defined in hook_theme():
```php
    return theme('icon', array(
      'name' => $icon_name,
      'path' => $icon_path,
      'alt' => $options['alt'],
      'attributes' => $options['attributes'],
    ));
```

## Steps To Reproduce

To reproduce the behavior:
1. Write some code that calls `icon()` to render one of the new core icons:
```php
$svg_options = array(
    'alt' => 'alt-test',
    'attributes' => array('class' => array('test-class)),
  );
icon('envelope', $svg_options);
```
3. See the warning.

## Actual behavior

Warning

## Expected behavior

No warning

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.29.2
- Web server and its version:
- PHP version: 
- Database sever (MySQL or MariaDB?) and its version:
- Operating System and its version:
- Browser(s) and their versions:

**Comment by jenlampton** [comment] 2024-11-23 04:00
PR at https://github.com/backdrop/backdrop/pull/4910.

**Comment by bugfolder** [comment] 2024-12-25 00:50
I"m not seeing the warning when I try to reproduce with the (corrected) sample code (missing `'`):

```
$svg_options = array(
    'alt' => 'alt-test',
    'attributes' => array('class' => array('test-class')),
  );
icon('envelope', $svg_options);
```

Although the PR certainly looks correct/appropriate, is there a better code snippet to reproduce the warning?

**Comment by indigoxela** [comment] 2024-12-25 09:07
It took me a moment to understand the problem, but found a way to reproduce:

```
$options = array(
  'name' => 'circle',
  'path' => icon_get_path('circle'),
);

$foo = theme('icon', $options);

debug($foo);
```
This triggers warning. And I can confirm that applying the patch fixes that. :+1:

**Comment by avpaderno** [comment] 2024-12-25 09:09
The only way I could think that warning is thrown is when `theme('icon')` is called directly, not via `icon()`, and `$variable['alt']` has not been set. (As @indigoxela said in the comment I now see.)

Calling `icon()` would not cause that warning because it sets the `alt` key.

**Comment by avpaderno** [comment] 2024-12-25 09:22
I can confirm the change is correct too.

As a side note, the code that merges in the default values defined by a theme hook is in [`theme()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21theme.inc/function/theme/1).

```php
// Merge in argument defaults.
if (!empty($info['variables'])) {
  $variables += $info['variables'];
}
```

**Comment by quicksketch** [comment] 2024-12-26 08:10
I filed an [identical PR](https://github.com/backdrop/backdrop/pull/4945) for issue https://github.com/backdrop/backdrop-issues/issues/6784 (which is a duplicate). This is the correct fix. I've merged into 1.x and 1.29.x. Thanks @jenlampton, @bugfolder, @indigoxela, and @avpaderno!

**Closed** 2024-12-26 08:11 UTC
Labels: type - bug report, status - has pull request, pr - ready to be committed, pr - works for me
