### ISSUE TITLE
Installation error: "ParseError: syntax error, unexpected '=>'" when DB host is wrong

### ISSUE THREAD

**Issue by quinnanya** [backdrop/backdrop-issues#3342] opened 2018-10-26 01:38 UTC
I was trying my hand at installing Backdrop 1.11.2 on MAMP 5.1, and ran into the following error after putting in the database name, username, and password:

ParseError: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in backdrop_install_config_directories() (line 17 of /Applications/MAMP/htdocs/backdrop/settings.php).

At that point, everything is hosed if you try to restart the installation process by going back to /backdrop; you just get a 500 error.

Indeed, the settings.php file looks like this:
$database = 'mysql://backdrop:backdrop@127.0.0.1/backdrop';
$database_prefix = '';
  'default' => '',

I started over (deleted the backdrop directory and put in a fresh one), and in the installer, opened the "advanced options". I realized that the host automatically gets populated with 127.0.0.1, and I created the user under localhost. Once I changed the database host to localhost under "advanced options", I was able to install it successfully.

Would it be possible to at least put in a more friendly error message that the installation can recover from in cases like this? I don't know how often people need to change the host, but I wonder if it might be better as part of the main form, rather than under "advanced options" (though I appreciate wanting to keep the main form as minimal as possible).

Thanks!

**Comment by olafgrabienski** [comment] 2018-10-26 08:02
@quinnanya Thanks for reporting! I agree, a more friendly error message would be great. I guess we haven't been aware of the reason for the error message though, see #3223 where the same error was reported, but it difficult to reproduce so far. Looks like your report will help to reproduce the issue.

**Comment by klonos** [comment] 2018-10-26 08:21
@quinnanya I am closing this issue as a duplicate of #3223. Can you please copy-paste your report over to that issue?

Thanks

**Closed by klonos** 2018-10-26 08:21 UTC
Labels: status - duplicate
