### ISSUE TITLE
[UX] The Add Layout page title should be "Add layout"

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1918] opened 2016-05-23 04:56 UTC
It seems to be just "Layouts" now.

**Comment by klonos** [comment] 2016-06-28 19:55
Yep, confirmed. Funny, in https://github.com/backdrop/backdrop/blob/1.x/core/modules/layout/layout.module#L101 we have `'title' => 'Add layout',`. So it should work I guess. Unless it is the `'type' => MENU_LOCAL_ACTION,` that is causing this.

**Comment by klonos** [comment] 2016-06-28 20:00
Sure, changing `'type' => MENU_LOCAL_ACTION,` to `'type' => MENU_NORMAL_ITEM,` (+ clearing caches) works in having the right tile shown, but this way we loose the local actions/tabs from that page (List layouts / Install layouts / Update layouts / Settings).

**Comment by klonos** [comment] 2016-06-28 20:01
...my guess is that this is a more generic issue with `'type' => MENU_LOCAL_ACTION` and it must effect other pages too besides the add layout page.

**Comment by laryn** [comment] 2016-08-15 18:13
It looks like this is specifically programmed to behave this way:
https://github.com/backdrop/backdrop/blob/6ea4c7524296e547ef4181c686fa4b91bb7d39de/core/includes/menu.inc#L2643-L2674

"Local task" items use the page title of their parents. I looked at the block module (another `MENU_LOCAL_ACTION`) and it looks like the [page title is manually set](https://github.com/backdrop/backdrop/blob/230200112aff22cb2aee7cd9e1ce638a0cf60f64/core/modules/block/block.admin.inc#L78) instead of relying on the [title set in the form](https://github.com/backdrop/backdrop/blob/230200112aff22cb2aee7cd9e1ce638a0cf60f64/core/modules/block/block.module#L55).

**Comment by quicksketch** [comment] 2016-08-15 18:23
Hi @laryn, yes I think you're right. The title needs to be set via `backdrop_set_title()` within the form callback in order to affect what is shown on the page but not adversely affect the menu tree structure. Backdrop doesn't have any other way of separating what should be shown on the page vs. what should be shown in the menu structure (and in the action link in this case).

**Comment by laryn** [comment] 2016-09-07 17:41
@quicksketch, I'm still a newbie at submitting so I'm just checking -- anything else I need to do on this to move it forward?

**Comment by klonos** [comment] 2016-09-08 07:55
@quicksketch perhaps add @laryn to the backdrop group so he can add labels and assign himself issues etc?

**Comment by klonos** [comment] 2016-09-08 09:33
I am really annoyed by the way our current menu/breadcrumb/primary tab system works currently (and I think I already have an issue filed somewhere). This PR improves things, but still the issue needs to be addressed fundamentally.

So the **current situation** is for example:

**Administration** <-- admin bar menu
**[Home ](#)> [Administration](#)** <-- breadcrumb links
  **Appearance** <-- page title
    **LIST THEMES** <-- active primary tab

**Administration > Install themes** <-- admin bar menu
**[Home ](#)> [Administration](#) > [Appearance](#)** <-- breadcrumb links
  **Appearance** <-- page title
    **INSTALL THEMES** <-- active primary tab

**Administration > Update themes** <-- admin bar menu
**[Home ](#)> [Administration](#) > [Appearance](#)** <-- breadcrumb links
  **Update themes** <-- page title
    **UPDATE THEMES** <-- active primary tab

In general, in my head, as I see the header section, I mentally create a "You are here" path that consists of the breadcrumb links + the page title + the active primary tab label + the active secondary tab label (if there is one). So, with the current status, I don't like:

1. the inconsistency (or special-casing if you like) of the first/default primary tab when it's the active one (the "Appearance" part is not appended to the breadcrumb like the rest of the sibling pages).
2. the duplication of the "Appearance" page title and last breadcrumb link under the install themes page (but I do understand that the link is required in order to go one level up).
3. the duplication of page title and active primary tab under the update themes page.

**This PR** changes the current situation to this instead:

**Administration** <-- admin bar menu
**[Home ](#)> [Administration](#)** <-- breadcrumb links
  **Appearance** <-- page title
    **LIST THEMES** <-- active primary tab

**Administration > Install themes** <-- admin bar menu
**[Home ](#)> [Administration](#) > [Appearance](#)** <-- breadcrumb links
  **Install themes** <-- page title
    **INSTALL THEMES** <-- active primary tab

**Administration > Update themes** <-- admin bar menu
**[Home ](#)> [Administration](#) > [Appearance](#)** <-- breadcrumb links
  **Update themes** <-- page title
    **UPDATE THEMES** <-- active primary tab

The PR addresses only point 2 from the list of issues above. In other words, it improves certain things (that's why it gets a 👍 from me and should be committed), but still, if you look at the greater picture, the fundamental issue of inconsistency is not solved.

What I would like to see instead at some point is this:

**Administration** <-- admin bar menu
**[Home](url) > [Administration](url) > Appearance** <-- breadcrumb links
  **Themes** <-- header `<h1>` title
  **Appearance: List themes | Site Name**  <-- HTML page `<title>`
    **LIST THEMES** <-- active primary tab

**Administration > Install themes** <-- admin bar menu
**[Home ](#)> [Administration](#) > [Appearance](#)** <-- breadcrumb links
  **Themes** <-- header `<h1>` title
  **Appearance: Install themes | Site Name**  <-- HTML page `<title>`
    **INSTALL THEMES** <-- active primary tab

**Administration > Update themes** <-- admin bar menu
**[Home ](#)> [Administration](#) > [Appearance](#)** <-- breadcrumb links
  **Themes** <-- header `<h1>` title
  **Appearance: Update themes | Site Name**  <-- HTML page `<title>`
    **UPDATE THEMES** <-- active primary tab

1. The first/default page gets the parent "Appearance" part as the last part of the breadcrumb - but plain-text, not a link
2. **All** `<h1>` titles become the "semantic" parent (not necessarily menu item) of the primary tabs.
3. The HTML page `<title>` is rendered as concatenated menu labels from the admin bar trail (+ the site name appended). It is in order to solve the UX issue with similarly named browser tabs. The same more or less solution that @jenlampton implemented with the admin bar search results in https://github.com/backdrop/backdrop-issues/issues/948#issuecomment-168475301
4. Now the "mental" path in the header section has consistency:

```
Breadcrumb                         |  <h1>  | Primary tab label
Home > Administration > Appearance > Themes > List themes
Home > Administration > Appearance > Themes > Install themes
Home > Administration > Appearance > Themes > Update themes
```

**Comment by klonos** [comment] 2016-09-08 10:14
I believe that the PR improves the situation. I've tested the sandbox and things seem to work as advertised, So, RTBC form me.

I'll try to find the old issue for the general problem I rant about above. If I can't find it, I'll just move my comment to a new issue.

**Comment by jenlampton** [comment] 2016-09-08 19:04
@klonos can you put your [previous comment](https://github.com/backdrop/backdrop-issues/issues/1918#issuecomment-245544643) into an issue about the breadcrumb someplace?  That is a fantastic summary of the problem and we'll need that to fix the breadcrumb. (Also, FTR, the breadcrumb situation has also always frustrated me! - well ever since D5 when it mostly worked)

**Comment by klonos** [comment] 2016-09-12 02:11
@jenlampton done 😉

**Comment by serundeputy** [comment] 2016-09-16 00:18
Great work everyone!  Thanks @laryn for the PR.

Merged into `1.x` and `1.4.x` will ship with `1.4.5` and `1.5.0`!

thanks!

**Closed by serundeputy** 2016-09-16 00:18 UTC
Labels: status - fixed
