### ISSUE TITLE
Fixed: Do not require the attributes array for backdrop_add_css() -- follow up to 4981.

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5070] opened 2021-04-26 14:33 UTC
**Description of the bug**

Long story short: this popped up in the contrib issue queue of bootstrap_lite: https://github.com/backdrop-contrib/bootstrap_lite/issues/36

I don't think we wanted the attributes array to be required (https://github.com/backdrop/backdrop-issues/issues/4981).

**Actual behavior**

Fatal error with hook_css_alter if not set.

**Expected behavior**

No fatal error. And the attributes array should be optional IMO, so core should check if it's set and only then try to merge.

**Comment by herbdool** [comment] 2021-04-29 15:37
That function sets attributes to be an empty array by default so I assume it shouldn't be an issue. Maybe the hook needs to be fixed?

Do you have some simple steps to replicate this?

**Comment by bugfolder** [comment] 2021-04-29 22:05
Steps to reproduce: Add this implementation of `hook_css_alter()` to any module (crashing example adapted from Bootstrap Lite module):
```
function mymodule_css_alter(&$css) {
  $cdn = 'https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css';
  $css[$cdn] = array(
    'data' => $cdn,
    'type' => 'external',
    'every_page' => TRUE,
    'media' => 'all',
    'preprocess' => FALSE,
    'group' => CSS_THEME,
    'browsers' => array('IE' => TRUE, '!IE' => TRUE),
    'weight' => -2,
//    'attributes' => array(),
  );
}
```
Load any page, immediate crash. Uncomment the 'attributes' line and it works.

**Comment by indigoxela** [comment] 2021-04-30 07:21
I confirmed the same behavior in themes - with a really minimal subtheme of basis, which actually only consists of an info and a template.php file.

in template.php:
```
<?php
function minitheme_css_alter(&$css) {
  $cdn = 'https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css';
  $css[$cdn] = array(
    'data' => $cdn,
    'type' => 'external',
    'every_page' => TRUE,
    'media' => 'all',
    'preprocess' => FALSE,
  );
}
```
Result: WSOD on every page when this theme is enabled and the default one.

In dblog: Error: Unsupported operand types in backdrop_pre_render_styles() (line 3955 of .../core/includes/common.inc).

Then I applied [the patch](https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/3610.patch), which immediately brought the site back. Works for me. :+1:

**Comment by indigoxela** [comment] 2021-04-30 14:12
I see that @herbdool and @klonos already did a review. And so I did now – wrapping in `isset()` was actually what I had in mind. :+1: 

RTBC from my side.

**Comment by klonos** [comment] 2021-04-30 14:30
I've left a suggestion re text wrapping in the docblock, but otherwise still RTBC.

**Comment by klonos** [comment] 2021-04-30 14:31
> I've left a suggestion...

Which @bugfolder lightning-merged 😓

**Comment by herbdool** [comment] 2021-04-30 15:15
I still have niggling problem that I don't understand why the problem is happening and that this PR might be just papering over it.

I thought that `backdrop_css_defaults()` would have solved the issue by always ensuring that the attributes is set to at least an empty array. I can't figure out why the alter hook is messing that up. I was going to look into that but I haven't had a chance. But perhaps someone else can clarify before we can confirm this is ready to be committed.

**Comment by indigoxela** [comment] 2021-04-30 15:42
@herbdool probably because backdrop_css_defaults() get's called in backdrop_add_css(), but the problem occurs with hook_css_alter().

**Comment by herbdool** [comment] 2021-04-30 16:17
Sorry I still don't understand. I'll look up more later when I'm at a computer. But from what I can tell, `backdrop_get_css` calls `backdrop_add_css` and then triggers the alter hook. So I assume it should be setting the defaults before the hook is triggered.

**Comment by quicksketch** [comment] 2021-04-30 21:53
> So I assume it should be setting the defaults before the hook is triggered.

Yes, that's correct. What I think it happening is a module or theme is adding an _entirely new_ entry into the list of CSS files. So while defaults are set on all files in the list, if a module adds a new CSS file by manually specifying every possible key, it wouldn't have known to add `attributes` prior to this patch.

Now that we have `backdrop_css_defaults()`, any module that adds a CSS file in `hook_css_alter()` should probably populate its own defaults by tacking on `backdrop_css_defaults()` at the end, like this (amending @indigoxela's example):

```php
function minitheme_css_alter(&$css) {
  $cdn = 'https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css';
  $css[$cdn] = array(
    'data' => $cdn,
    'type' => 'external',
    'every_page' => TRUE,
    'media' => 'all',
    'preprocess' => FALSE,
  ) + backdrop_css_defaults();
}
```

But we should also add the check suggested in the PR at https://github.com/backdrop/backdrop/pull/3610, so that existing sites and modules won't strictly be required to do this.

**Comment by herbdool** [comment] 2021-04-30 23:43
Makes sense to me now, and I agree with the pr. I was assuming that the alter hook could only edit existing entries.

**Comment by klonos** [comment] 2021-04-30 23:44
> Now that we have `backdrop_css_defaults()`, any module that adds a CSS file in `hook_css_alter()` should probably populate its own defaults by tacking on `backdrop_css_defaults()` at the end...

It feels that this should be documented in https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/system.api.php#L416 and that code snippet provided as an example. No?

...having said that, shouldn't we be doing that whole adding of `backdrop_css_defaults()` for all implementations of `hook_css_alter()`, instead of expecting developers to know that they need to do it?

**Comment by indigoxela** [comment] 2021-05-01 05:29
Documenting things with a code snippet for sure makes sense - but only for new implementations of that hook. IMO we still should take care that existing implementations don't break. And as this currently results in WSOD it seems even more important to me.

I'm all for making attributes optional, and that core takes care of catching possible problems.

**Closed** 2021-05-02 01:02 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2021-05-02 01:04
I was thinking about if we should instead add the defaults, such as `$item += backdrop_css_defaults()` rather than doing several `isset()` checks. But I don't think it's better than the current solution. I've merged https://github.com/backdrop/backdrop/pull/3610 into 1.x for 1.19.0. Thanks @indigoxela for reporting the issue and thanks @bugfolder for the fix!

This feature is not in the 1.18.x branch so there's no need to pull it into 1.18.x.
