### ISSUE TITLE
CKEditor 5 adds extra line breaks within heading tags

### ISSUE THREAD

**Issue by marioawad** [backdrop/backdrop-issues#6371] opened 2024-01-16 18:32 UTC
## Description of the bug

CKEditor 5 is adding extra `<br>` tags within heading tags in the Basic text format.

Now you get `<h3>My Title<br /></h3>` instead of `<h3>My Title</h3>` for example.

This is the case on a fresh Backdrop 1.27.0 install and on previous versions of Backdrop updated to 1.27.0.

If you edit the Basic text format and disable the Convert line breaks into HTML filter this issue will be resolved but then you will no longer be able to add line breaks with shift+enter which is a feature many editors require.

## Steps To Reproduce

1. On a fresh Backdrop 1.27.0 install or on an upgraded one
2. Go to the About page for example, edit it, and add a heading, and save it

## Actual behavior

Check the generated page source to see the extra `<br>` tag in the heading.

## Expected behavior

Expected to get a clean heading tag with no line breaks inside.

## Additional information

- Backdrop CMS version: 1.27.0
- Web server: Apache 2.4.58
- PHP version: 8.1.27
- Database sever: MariaDB 10.6.12
- Operating system: Ubuntu 22.04 LTS
- Browsers: Firefox 121.0.1 and Brave 1.61.116 (Chromium: 120.0.6099.217)

**Comment by olafgrabienski** [comment] 2024-01-16 19:25
I had a very simular issue with the 1.27 preview release, but using the "Raw HTML" format with CKE5. When I added a Shift + Enter line break, two `<br>` elements were added. My workaround was to disable the Convert line breaks filter.

Now I had another look at the site in question and tried to reproduce the heading issue with the steps described above. Interestingly, I was not able to reproduce it, even after updating to 1.27.0. I was also no longer able to reproduce 'my' issue with two `<br>` elements.

Can you check if just saving the text format fixes the issue?

**Comment by olafgrabienski** [comment] 2024-01-16 21:03
Confirmed the issue on another test site (didn't look close enough before). The undesired result:

```
<h3>
  This is a heading<br>
</h3>
<p>
  This is text with a line break.<br><br>
  New line
</p>
```

**Comment by olafgrabienski** [comment] 2024-01-16 21:16
> Of course if you uncheck the Convert line breaks into HTML filter then the issue is fixed but now you can no longer add line breaks with shift+enter which is a feature many editors need in the Basic format.

Using a workaround, I'm able to add line breaks with Shift + Enter in the Basic format. To make it possible, I edited the text format and added `<br>` to the Filter "Limit allowed HTML tags".

**Comment by quicksketch** [comment] 2024-01-16 22:41
> Could updating the Basic format (disable Convert line breaks, add <br> to allowed HTML) even be the approach for a fix?

I think both disabling the newline filter and enabling `<br>` in Basic would be good solutions.

CKEditor 4 was compatible with the New Line filter, I thought CKEditor 5 was too. Since all existing Backdrop sites probably have that filter turned on (since it's on by default), we may need to find a way to make it compatible with CKEditor 5. Or we could consider disabling it as part of the CKEditor 4 to 5 upgrade path. In practice it does nothing with a rich text editor enabled. And CKEditor 5 is much more aggressive about forcing content to be wrapped in `<p>` tags.

**Comment by quicksketch** [comment] 2024-01-16 22:47
The extra `<br>` tag shows up on output, not within the editor:
![image](https://github.com/backdrop/backdrop-issues/assets/100206/9e057ea9-4f2d-482f-bcc1-b56ab08d73d3)

On themes like Basis, this doesn't seem to have any sort of visual impact. But this implies that it's a problem with the new line filter itself, rather than CKEditor 5. Looking at other text formats, it seems like creating content in CKEditor 5, then switching to the out of box "Raw HTML" filter produces the same extra `<br>` tag on output.

**Comment by quicksketch** [comment] 2024-01-17 00:32
I filed a PR at https://github.com/backdrop/backdrop/pull/4638 that should fix this, including test coverage.

It seems like there's a list of tags for which `<br />` should not get automatically added before the closing tag, including p, li, div, pre, etc. The PR simply adds h1-h6 to this list of tags. This code hasn't changed since 2006! And apparently this problem has existed the entire time with the autop filter, we just never formatted our code this way that made it obvious.

There's a broader list of block tags like blockquote, article, aside, details, etc, but adding those to the list of exceptions is not necessary because autop puts a `<p>` tag inside of each of those block elements. So the rule to not add an extra `<br />` is handled by the added `<p>` tag.

To test this manually:

- Create a new post.
- Set text format to `Raw HTML` (which out of the box has the autop filter enabled).
- Insert content such as:
```
<h3>
    Hello
</h3>
```
- Save the node.
- View the source of the page.
- Before this PR the output would become:
```
<h3>
    Hello<br />
</h3>
```
- After this PR, the h3 does not get the added `<br />`:
```
<h3>
    Hello
</h3>
```

With the `Basic` text format (which does not have `<br>` enabled out of the box), things seem to be working through a strange set of coincidences. The `<br>` tag gets stripped out, but then the autop filter adds one back in. We should still add `<br>` to the default tag list so that shift+enter is supported even when the autop filter is disabled.

**Comment by herbdool** [comment] 2024-01-17 00:54
Should we add `<br>` to the default tag list in the PR as well or a new issue? We might not need a new issue for that - it's a pretty minor change in `filter_filter_info()`.

I tested the above in the sandbox and it works. The one thing not mentioned was testing that it's *not* adding double `<br>` between `<p>` tags. I tested that too and it is working.

![2024-01-16 19 54 04 pr4638-gkfrzk4kr9lyxeqf7hyyzxklls7kouww tugboatqa com dd741b12c25b](https://github.com/backdrop/backdrop-issues/assets/1071483/ad45666a-05c2-44d1-a081-6873ee10fad0)

**Comment by herbdool** [comment] 2024-01-17 01:10
I was looking at the phpcs errors. It seems to have missed quite a few missing parameter types. I wonder why it reports back only some of them?

**Comment by quicksketch** [comment] 2024-01-17 02:00
> I was looking at the phpcs errors. It seems to have missed quite a few missing parameter types. I wonder why it reports back only some of them?

Weirdly the phpcs action only reports errors not only on changed lines but on _all lines last modified by the same user_. So since I last touched those lines, phpcs is flagging them (but not the thousands of other lines in filter.module). It's an imperfection in the phpcs action. See https://github.com/backdrop/backdrop-issues/issues/5848#issuecomment-1302938514

> Should we add `<br>` to the default tag list in the PR as well or a new issue? 

Yeah it's so simple I think maybe add it here? I guess for existing sites we can leave the existing text formats as-is, since they supposedly have been fine without the `<br>` tag up until now.

**Comment by quicksketch** [comment] 2024-01-17 02:06
@herbdool I added the `<br>` tag to the list of default tags allowed by filter module. Since the standard profile just inherits the default settings, no other changes seem to be necessary. Could you re-review?

> The one thing not mentioned was testing that it's not adding double `<br>` between `<p>` tags.

Thanks, yeah that functionality should be unchanged and work the same as before. The new automated test coverage covers that scenario because it seems like something that could easily be overlooked in the future.

**Comment by herbdool** [comment] 2024-01-17 03:44
Now with the added `<br>` and autop it's adding double `<br>` when trying to add a single. This is what I get when I test it in the sandbox with default settings.

![Screenshot_20240116-224046](https://github.com/backdrop/backdrop-issues/assets/1071483/169f8687-620f-4ca5-a7ab-b737d60ca0a2)

**Comment by quicksketch** [comment] 2024-01-17 08:41
Thanks @herbdool, nice catch. I think this is because CKEditor creates `<br>` (non-self-closing) tags, and the autop filter is only set up to handle `<br />` (self-closing) tags. By adding an extra rule at the top of the replacements that normalizes `<br>` to `<br />`, all the following rules work as desired and the extra duplicate `<br />` is not created by the filter.

I updated the PR and added more test coverage for this scenario of a `<br>` at the end of a line. In my testing it seems to work whether `<br>` or `<br />` tags are used at the end of a line.

I also separately discovered, whether by design or accident, that if you have two break tags in a row in the original content (before the filter is applied), the autop filter converts those two `<br>` tags into separate `<p>` tags. It's a weird behavior, but one that has been in place for a long time apparently.

**Comment by herbdool** [comment] 2024-01-17 11:39
@quicksketch all works now. RTBC 

@marioawad yes, that's a good solution for individual sites. For those, who don't change their settings, this PR will ensure they have a fix too.

**Comment by olafgrabienski** [comment] 2024-01-17 12:09
Wow, thanks for the quick fix!

> I guess for existing sites we can leave the existing text formats as-is, since they supposedly have been fine without the `<br>` tag up until now.

I'm not sure about this. With CKEditor 4, it wasn't necessary to add `<br>` to the allowed HTML tags, but isn't it necessary for Shift + Enter line breaks when people switch to CKE 5?

**Comment by quicksketch** [comment] 2024-01-17 18:38
@olafgrabienski It turns out both CKEditor 4 and 5 both work out-of-the-box currently with shift+return, even without `<br>` being added to the list of tags, because the autop filter adds the break on new lines (`\n` characters) in the source HTML. So we don't specifically need to enable the `<br>` tag. But I think you're right that enabling it as part of the CKEditor 5 upgrade might be a good idea.

Let's track that in a separate issue, as we might want to also add an update hook

**Comment by quicksketch** [comment] 2024-01-17 19:06
@olafgrabienski I filed a new issue at https://github.com/backdrop/backdrop-issues/issues/6373 to discuss updating existing sites with `<br>` tags.

**Closed** 2024-01-17 19:30 UTC
Labels: type - bug report, status - has pull request, pr - ready to be committed, pr - works for me

**Comment by quicksketch** [comment] 2024-01-17 19:33
I merged https://github.com/backdrop/backdrop/pull/4638 into 1.x and 1.27.x. Thanks @herbdool, @marioawad, and @olafgrabienski for your help in reviewing and testing! Extra thanks to @marioawad for finding and reporting the issue.

**Comment by olafgrabienski** [comment] 2024-01-17 21:02
> both CKEditor 4 and 5 both work out-of-the-box currently with shift+return, even without `<br>` being added to the list of tags

Hm, that's not what I see. On a site with applied PR and without `<br>` in the list, when I use shift+return in CKE 5, it _seems_ to work as the `<br>` is visible when I switch to source code. But when the node is saved, the tag gets removed from the rendered HTML.

As the PR here is already merged, let's try to handle the question in the follow-up.
