### ISSUE TITLE
Project Installer UI: Sub-modules that are hidden should not be shown

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#5054] opened 2021-04-21 19:58 UTC
**Description of the bug**

This bug can be seen when using the Project Installer UI to install Node Clone. The module contains a hidden sub-module:

![Screenshot from 2021-04-21 15-34-27](https://user-images.githubusercontent.com/1071483/115613191-1a12f980-a2ba-11eb-83f9-ca165324c5d1.png)

The hidden module should not be shown.

This might be a follow-up bug fix to https://github.com/backdrop/backdrop-issues/issues/2200.
Here's where we added the hidden sub-module to Node Clone https://github.com/backdrop-contrib/node_clone/issues/8.

**Comment by klonos** [comment] 2021-04-21 21:02
I confirm that enabling the module from the modules listing page (either manually downloaded, or if the "Enable modules" step in the Project Installer was skipped) does NOT redirect to any confirmation page about enabling any dependencies. That's expected though, since the Node Clone module listed in that page is the `clone.module` - NOT the "faux" `node_clone.module` which has the `dependencies[] = clone` line in its .info file.

Enabling the `node_clone` module using drush works seamlessly as well:

```
drush en node_clone -y
The following projects will be enabled: clone, node_clone.
    Do you want to enable the projects? (y/n): y

	Sucess: module clone enabled.


	Sucess: module node_clone enabled.
```

So we're good on those fronts 👍🏼

**Comment by laryn** [comment] 2021-04-21 21:26
Sidebar: Looks like there's a [spelling mistake in Backdrop's Drush](https://github.com/backdrop-contrib/backdrop-drush-extension/issues/242)

**Comment by klonos** [comment] 2021-04-21 21:31
> Sidebar: Looks like there's a spelling mistake in Backdrop's Drush

OMG! ...I literally see these lines each time I spin up my local, and I've never noticed it before. Shame on me.

**Comment by klonos** [comment] 2021-04-21 21:38
...so I've done some more testing, and the "culprit" in this situation seems to be this bit of logic: https://github.com/backdrop/backdrop/blob/1.x/core/modules/installer/installer.pages.inc#L662

The assumption there is that the main modules are **never** hidden, and submodules of these modules are always added to the list. In the case of the Node Clone module though `node_clone` is not the main module - only a helper ...but in both Drupal and Backdrop, the general assumption is that the main module is always the one that has the same name as the folder containing it 🤔

**Comment by klonos** [comment] 2021-04-21 22:57
This fixed it for me on my local: https://github.com/backdrop/backdrop/pull/3604

...there are some very trivial side-effects caused by the fact that the "main" module on that project is hidden, but not within scope to be fixed in Backdrop core. I'll file issues for these things in the contrib module issue queue.

**Comment by laryn** [comment] 2021-04-23 14:35
> Shame on me.

Hey now, this is a shame-free zone.

Tested on my local and it WFM.

![node-clone-install](https://user-images.githubusercontent.com/871421/115887083-34aeb500-a417-11eb-9bb5-b9805813c484.png)

**Comment by klonos** [comment] 2021-04-24 06:18
Yeah, as I also mention in the inline comment, what I've done is to add an extra check for the final list of options, to remove any hidden modules. It will mainly help in these rare situations, where the "main" module of a module package is to be hidden for whatever reason, and submodules installed instead.

**Comment by herbdool** [comment] 2021-12-02 16:06
This looks good to me.

**Closed** 2021-12-03 23:40 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2021-12-03 23:46
Thanks @herbdool for the RTBC! I merged https://github.com/backdrop/backdrop/pull/3604 into 1.x and 1.20.x. Thanks @klonos!
