### ISSUE TITLE
[UX] Fixed: Do not link an email address if the domain name does not contain a TLD.

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6448] opened 2024-04-09 09:18 UTC
This is the equivalent of https://www.drupal.org/project/drupal/issues/2016739 created for Drupal 7.

Text like SETI@home or working@home should not be converted to email links because they are not email addresses. To be converted to links, the domain part should contain at least a dot.

**Comment by indigoxela** [comment] 2024-04-10 13:15
@kiamlaluno many thanks for opening this issue and providing a PR. :pray: 

Yeah, the link filter's an ongoing topic. I can confirm, that this PR works as expected, the regex pattern's slightly better. At least things that can never be a mail address aren't converted anymore.

I tested with the "Raw HTML" format, to prevent CKE from already converting while typing. Works for me.

**Comment by herbdool** [comment] 2024-04-12 16:12
Given that this was fixed in D9 and the D7 patch matches this PR, I think it is RTBC.

**Closed** 2024-04-22 02:44 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2024-04-22 02:46
Thanks @kiamlaluno, @indigoxela, and @herbdool! I merged https://github.com/backdrop/backdrop/pull/4690 into 1.x and 1.27.x.
