### ISSUE TITLE
Basis theme: Contextual Link not showing up on Views page

### ISSUE THREAD

**Issue by simone960** [backdrop/backdrop-issues#2909] opened 2017-11-24 22:55 UTC
I have created a Views page with Views, but when I hover the title bar, I don't see the contextual link showing up. There's no wheel/gear icon. However, when I inspect element and I can see the contextual link is being triggered. I'm using the default backdrop's basic theme on backdrop 1.8.0. 

![contextual-link-not-showing](https://user-images.githubusercontent.com/7530286/33225146-4f3a40d2-d1c6-11e7-8ac6-be36eabe897c.png)

I eventually fixed it with css below but I need to draw your attention to see if such issue exist and need to be fixed in a better and proper way. 

```
.l-page-title{
  position: relative;
}
```

I reported this issue in Basis issue queue but realized this theme already part of core so should be reported here. If not please correct me. Thanks!

https://github.com/backdrop-contrib/basis_contrib/issues/57

**Comment by Graham-72** [comment] 2017-11-25 07:25
@simone960 on a views page I am seeing the gear-wheel icon in the top right corner of the page and this gives the link 'configure view'. I do not need to hover the title bar to make this icon appear.

**Comment by simone960** [comment] 2017-11-26 05:08
Em.. thanks for pointing out. Now I realized the gear-wheel icon is indeed in the top right corner but it is not visible as it is covered by the admin bar actually. If I inspect element and delete the admin bar, then I'm able to see the contextual link. But this is no good also since it is not visible. I tried to install a new copy of the latest 1.8.0 version but it's still the same issue. Perhaps you can try that out on a new installation with Basis theme and see if you experience that.

**Comment by Graham-72** [comment] 2017-11-26 07:41
@simone960 which layout template are you using?

**Comment by serundeputy** [comment] 2017-11-26 21:04
I think this issue is a dupe of https://github.com/backdrop/backdrop-issues/issues/2690

**Comment by simone960** [comment] 2017-11-27 00:09
@Graham-72, the default layout - "Moscone Flipped". To reproduce, just simply install a backdrop 1.8.0 and create a Views page. The gear-wheel icon is covered by the admin menu bar.

![contextual-link-views4](https://user-images.githubusercontent.com/7530286/33245980-633b605e-d363-11e7-961e-72c54c5fd1e1.png)

**Comment by Graham-72** [comment] 2017-11-27 09:52
Yes, I see the problem.

I think an answer might be to add to layout.css in Basis
```
.l-page-title .contextual-links-wrapper{
  top:35px;
}
```
which moves the relevant contextual links wrapper to be below the admin bar.

**Comment by serundeputy** [comment] 2017-11-27 13:41
closing as duplicate of #2690; I'll link this issue so people can see the comments if needed, but they are largely a reproduction of that conversation.

**Closed by serundeputy** 2017-11-27 13:41 UTC

**Comment by simone960** [comment] 2017-11-30 06:24
@Graham-72 Graham-72. Thanks for the trick. I can see the icon now. 

```
.l-page-title .contextual-links-wrapper{
  top:35px;
}
```

@serundeputy  Sure, thanks for closing. It's a dupe indeed. Better focus on one.
