### ISSUE TITLE
Allow server settings to be overridden

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4966] opened 2021-02-23 11:19 UTC
**UPDATE:** This issue started as a feature request to add the ability to override the server variable to Backdrop. However it was later pointed out that this variable can already be overridden by [adding some lines to `settings.php`](https://github.com/backdrop/backdrop-issues/issues/4966#issuecomment-786248854). This issue now serves as a reference to anyone needing to do this same thing in future.

---

**Description of the need**

If any settings are set via the `$_SERVER['BACKDROP_SETTINGS']` variable, they take precedence over settings in the `settings.php` file(s).

This feature is used, for example, by Lando, which [sets the database connection information](https://docs.lando.dev/config/backdrop.html#connecting-to-your-database) via that variable. This makes it easier for users in that they don't need to setup the DB connection info themselves. However this also means that there's no way to specify the DB connection info manually via `settings.php`, (e.g. for debugging, testing, etc.), since the `settings.php` values are **always overridden by the server variable**.

It's this hard-coded overriding that I'd like to make optional, so that users can choose which settings will be used for any given site.

**Proposed solution**

I recommend adding a new setting to `settings.php` which determines whether the `settings.php` values are overridden by the server or not.

**Alternatives that have been considered**

I've tried to [override Lando's default setup](https://github.com/lando/lando/issues/2727), but to no avail.

**Draft of feature description for Press Release (1 paragraph at most)**

Backdrop now allows you to disable the automatic overriding of `settings.php` values by the server.

**Comment by BWPanda** [comment] 2021-02-23 19:59
I am advocating for this issue.

**Comment by klonos** [comment] 2021-02-23 23:21
The code changes are simple and straight-forward (thanks for catching that missing space + that extraneous `$` in that variable too 👍 ).

I understand the need for this when looking at it from a local dev point of view, but are we this way providing a way for users to override/ignore settings that hosting providers may have set up? ...in other words, are we fixing an issue for a specific use case, but then also making things worse for another group of people?

**Comment by BWPanda** [comment] 2021-02-24 00:12
> are we fixing an issue for a specific use case, but then also making things worse for another group of people?

The only way this will "make things worse" for people, is if they specifially enable this setting (which is disabled by default), and then don't make the necessary changes to their `settings.php` file. People should only enable this if they know what they're doing.

**Comment by BWPanda** [comment] 2021-02-25 19:52
FTR, this is required to get the local dev environment working for `b`: https://github.com/backdrop-contrib/b/blob/baff5ea0307123948412b0bae3a05ebf56a7413d/.lando.yml#L14

**Comment by quicksketch** [comment] 2021-02-25 21:45
I'm curious if this code snipped at the bottom of settings.php would be sufficient to avoid adding this new option:

```
// Make our database settings take precedence over Lando server settings.
if (isset($_SERVER['BACKDROP_SETTINGS'])) {
  unset($_SERVER['BACKDROP_SETTINGS']);
}
```

Then the server-provided settings would not exist, and your settings.php database information would be used.

**Comment by BWPanda** [comment] 2021-02-26 01:38
Thanks @quicksketch! I can confirm that your suggestion works nicely.

In case anyone wants to test, here's an example Lando file:
```yaml
name: settings-test
recipe: backdrop
config:
  webroot: backdrop
  database: mariadb
services:
  appserver:
    build_as_root:
      - wget -q --show-progress https://github.com/backdrop/backdrop/archive/1.x.zip
      - unzip -q 1.x.zip && rm 1.x.zip
      - mv backdrop-1.x backdrop
      # - echo 'if (isset($_SERVER["BACKDROP_SETTINGS"])) unset($_SERVER["BACKDROP_SETTINGS"]);' >> backdrop/settings.php
```

1. Start the Lando instance (leaving the last line commented out)
2. Access the Backdrop site URL and proceed through the installer - note that the Database step is skipped (it uses Lando's DB connection info from the server variable)
3. Destroy the Lando instance and delete the `backdrop` directory
4. Uncomment the last line of the Lando file and save
5. Start the Lando instance again
6. Access the Backdrop site URL and proceed through the installer - note that the Database step is *not* skipped (it now uses the DB connection info from `settings.php`)

The reason I couldn't get this working previously was that I was trying to unset the variable from within the Lando file (through various commands). It's nice to know that there's a provider-agnostic way to do this via `settings.php` instead!

I'll close this issue and the associated PR now.

**Closed by BWPanda** 2021-02-26 01:38 UTC
Labels: status - has pull request, status - works as designed

**Comment by quicksketch** [comment] 2021-02-26 04:42
Yay, that's great! Thanks for the follow-up @BWPanda!
