### ISSUE TITLE
Taxonomy bulk delete/generate aliases doesn't work

### ISSUE THREAD

**Issue by sutibun** [backdrop/backdrop-issues#1290] opened 2015-10-02 05:44 UTC
1. I created a new taxonomy called "category"
2. Added a few terms to it. (e.g. cookies)
3. I then remembered that I should've defined the URL alias pattern for the category taxonomy at "admin/config/search/path/patterns". _Initially it was blank_ and I knew the URL for the terms I added at step 2 would follow the "Default path pattern" [term:vocabulary]/[term:name] As I checked, I was right. (e.g. /category/cookies)
   
   ![tax](https://cloud.githubusercontent.com/assets/14132746/10239888/1fd740fc-689a-11e5-8aff-cb68acd97826.png)
   
   What I wanted instead, for the category taxonomy only, is the URL alias pattern /[term:name] (e.g. /cookies) so I made the necessary change as seen in the image above.
4. With the category alias pattern now defined, I head over to the "Delete Aliases" page ("admin/config/search/path/bulk-delete") and check "Taxonomy term paths". As I understand it, this will delete the URLs for the terms I added in step 2. I then click the delete button.
   
   ![bulk-delete](https://cloud.githubusercontent.com/assets/14132746/10239882/07084ab2-689a-11e5-8562-9491a304a4d0.png)
5. Next, I go to the "Bulk Generate" page ("admin/config/search/path/bulk-update") As I understand it, I can create aliases for those earlier terms that no longer have aliases now using the new alias pattern defined in step 3. I click the bulk generate button.
   
   ![bulk-generate](https://cloud.githubusercontent.com/assets/14132746/10239881/070680a6-689a-11e5-94f2-11f4049c4303.png)
6. I head back to the taxonomy page for category (in my case, it's "admin/structure/taxonomy/category") and hover over each term but find they still retain the old URL pattern (e.g. /category/cookies as opposed to /cookies)
7. Figured I must've made a mistake in the Bulk delete+Bulk generate process. So I decide to update those old terms manually but later. I then go on to add new terms to the category taxonomy but find they don't follow the URL pattern defined in the "Patterns" page ("/admin/config/search/path/patterns") I double check the Patterns page and my custom pattern of "[term:name]" is right there.

**Either I did something wrong or**
- the Path patterns for Taxonomies doesn't work and only follows the default path pattern
- bulk delete + bulk generate aliases for taxonomy also doesn't work

**Comment by quicksketch** [comment] 2015-10-20 04:37
Thanks for the amazingly detailed report @sutibun!

> the Path patterns for Taxonomies doesn't work and only follows the default path pattern

I created a new term after setting up a new pattern and it worked as expected. So this is fine.

> bulk delete + bulk generate aliases for taxonomy also doesn't work

This seems to be the problem. Bulk deletion is broken for terms. After selecting terms on the bulk deletion page, the number of term aliases to be deleted doesn't change (it's 4 both before and after for me). Obviously after deleting all existing aliases, the number aliases that would deleted should be 0. I'll take a look into this.

**Comment by quicksketch** [comment] 2015-10-20 04:55
PR filed at https://github.com/backdrop/backdrop/pull/1107. After testing, I've confirmed that the workflow outlined now works as expected and the new aliases are created for the existing taxonomy terms.

**Comment by klonos** [comment] 2015-10-20 14:23
> I've confirmed that the workflow outlined now works as expected and the new aliases are created for the existing taxonomy terms.

I think that's what we have tests for. Should we add one for this scenario?

**Comment by quicksketch** [comment] 2015-10-20 23:35
> I think that's what we have tests for. Should we add one for this scenario?

Yes! I'll update it before committing. :smile:

**Comment by klonos** [comment] 2015-10-21 13:04
Yeah, I am still being a smart-pants not being able to put code where my mouth is. Just making sure it's on your todo list for this issue.

**Comment by sutibun** [comment] 2015-10-24 19:54
> > the Path patterns for Taxonomies doesn't work and only follows the default path pattern
> 
> I created a new term after setting up a new pattern and it worked as expected. So this is fine.

I am still having trouble with the taxonomy's URL.

Here is what I did:

1. I created a **new** taxonomy called "tagtest"
2. Unlike before, I then immediately went to the path pattern page at "admin/config/search/path/patterns" and set the path pattern for tagtest to "[term:name]" as shown below
    
    ![tag](https://cloud.githubusercontent.com/assets/14132746/10712343/06314f28-7a5e-11e5-840d-d0d5f378a83e.png)
3. Now, I went back to the taxonomy page and added a new term called "a".
4. Since I set the path pattern for the tagtest taxomony to "[term:name]", I expect the URL for term a to be "/a" But in fact, that's not what I get. I get "/tagtest/a" See below.
    
    ![a](https://cloud.githubusercontent.com/assets/14132746/10712367/9d6075c2-7a5e-11e5-8d1e-f110712c211c.png)
    
    Once again, the taxonomy is following the Default path pattern: "[term:vocabulary]/[term:name]". Not matter what changes I make to "Pattern for all tagtest paths", I keep getting the URL pattern "/tagtest/TERMNAME"

**Comment by serundeputy** [comment] 2015-10-25 18:22
This PR allows for term specific path patterns: https://github.com/backdrop/backdrop/pull/1108

But it made a lot of test failures on my local; we'll see what travis has to say.

**Comment by serundeputy** [comment] 2016-01-01 20:13
@quicksketch this has passed tests can we merge it into 1.2.x or 1.x as it is impeding/blocking #899 

thanks.

**Comment by jenlampton** [comment] 2016-01-01 22:40
I confirmed the bug is fixed with this PR, but it's still missing tests.

**Comment by serundeputy** [comment] 2016-01-02 15:17
* Downloaded this patch (https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/1158.patch) 
* Applied 1158.patch to `1.x`
* Set a pattern for the tags taxonomy
* Bulk generated 7 term paths
  * the paths were there on the listing tab `/admin/config/search/path`
* Did a bulk delete from `/admin/config/search/path/bulk-delete` 
  * checked `Taxonomy term paths`
* Clicked `DELETE ALL CHECKED ALIASES` button
* Returned to `/admin/config/search/path`
  * the paths were gone

I locally ran tests for `Path` and `Path API` all tests passed.

**Closed** 2016-01-04 02:24 UTC
Labels: status - has pull request

**Comment by quicksketch** [comment] 2016-01-04 02:25
THe PR at https://github.com/backdrop/backdrop/pull/1158 now includes tests. Nice job @jenlampton and @serundeputy!

Merged into 1.x and 1.2.x. This will be in 1.2.3.

**Comment by sutibun** [comment] 2016-01-17 04:52
Yay! \\(^\_^)/ It works. 

Can finally continue with my site building.
