### ISSUE TITLE
Italics are not working with our new admin theme font, OpenSans

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#878] opened 2015-04-19 03:08 UTC
Italics are not working with our new admin theme font, OpenSans.  In a previous issue, @wesruv said...

> Looks like that's also an issue with how the font was included with @font-face

This is a follow up from https://github.com/backdrop/backdrop-issues/issues/875

**Comment by wesruv** [comment] 2015-04-19 21:23
Nice, thanks!

**Comment by Graham-72** [comment] 2015-04-20 05:41
I can see that the italics problem is caused by seven.fonts.css linking to the Light font files when it means to link to the Italic font files. (Lines 17, 19, 20, 21, 22 of seven.fonts.css)

**Comment by Graham-72** [comment] 2015-04-20 13:44
I have added a commit to PR https://github.com/backdrop/backdrop/pull/819 that makes the necessary changes to file names in core/themes/seven/css/seven.fonts.css

**Comment by quicksketch** [comment] 2015-04-20 15:36
Hi @Graham-72! Thanks for your work on these issues. Could you make a separate branch per issue and file the pull requests individually? The fix for this issue looks great, but the other issues look like they need additional work. Separating them will let me merge the ones that are ready.

**Comment by Graham-72** [comment] 2015-04-21 06:42
Hi @quicksketch - I apologise for my struggles in using GitHub. I have now produced three separate pull requests at
https://github.com/Graham-72/backdrop/pull/1
https://github.com/Graham-72/backdrop/pull/2
https://github.com/Graham-72/backdrop/pull/3
and when doing the first of these the page invited me to merge pull request, so I did, which I guess was a mistake! Do you need a separate branch for the italics issue or is that done?

**Comment by wesruv** [comment] 2015-04-22 04:16
@Graham-72 I didn't see a PR for the italics so I added one in myself to make sure this gets fixed sooner rather than later.
https://github.com/backdrop/backdrop/pull/825

**Comment by quicksketch** [comment] 2015-04-22 05:08
Thanks guys! Thanks @wesruv for helping with the PRs. We're a little all over the place.

I've merged in https://github.com/backdrop/backdrop/pull/825. Thanks!

**Closed by quicksketch** 2015-04-22 05:08 UTC
Labels: status - has pull request
