### ISSUE TITLE
[ongoing] Backdrop in One-Click-Install collections

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#965] opened 2015-06-03 22:32 UTC
The typical Backdrop market would use those.
* [x] Fantastico https://netenberg.com/fantastico.php
* [x] Mojo https://www.mojomarketplace.com
* [x] OpensourceCMS https://www.opensourcecms.com
* [x] DockerHub https://hub.docker.com/_/backdrop/
* [ ] Installtron https://installatron.com | [open ticket #14776130](https://installatron.com/tickets?ticket=14776130&email=&new=yes)
* [x] Softaculous https://www.softaculous.com | [open ticket #167103](https://softaculous.deskuss.com/tickets.php?id=167103)
* [ ] bitnami https://bitnami.com | "application already submitted"
* [ ] SimplyTest.me https://simplytest.me
* [x] ~~SimpleScripts http://www.simplescripts.com~~ SimpleScripts is now the MOJO Marketplace

**Comment by quicksketch** [comment] 2015-06-04 04:29
Wow, I've never seen Mojo before. Although it makes me uneasy that you can apparently log into Mojo with your hosting account credentials (not sure how that works). This is a great idea in any case.

**Comment by docwilmot** [comment] 2015-06-08 04:12
Very popular with us amateurs. But this would increase exposure tremendously, Im sure.

**Comment by klonos** [comment] 2015-06-08 06:35
Mojo?? Link please?

**Comment by klonos** [comment] 2015-06-08 06:42
...btw, since [Drupal has an entry in wikipedia](https://en.wikipedia.org/wiki/Drupal), I registered a wikipedia account the other day. Thought it'd be nice to have an entry for Backdrop CMS (also linked to from the [Backdrop](https://en.wikipedia.org/wiki/Backdrop) disambiguation page and listed in the [List of content management frameworks](https://en.wikipedia.org/wiki/List_of_content_management_frameworks)). Got stuck because it did mention some legal stuff like being careful not to promote/advertise etc. Might be a thing that I'd better leave up to @quicksketch and/or @jenlampton instead.

**Comment by klonos** [comment] 2015-06-08 06:46
...other wikipedia articles where drupal is listed:

https://en.wikipedia.org/wiki/Comparison_of_web_application_frameworks
https://en.wikipedia.org/wiki/List_of_content_management_systems

**Comment by docwilmot** [comment] 2015-06-08 12:31
Decided to do a proper search and list instead. After reading this I have a sneaky suspicion that this. Type of thing is part of the reason that Wordpress is where it is. The concept of  "Easy One Click Install!" Is heavily promoted on web hosts. Here's the lists of one-click install vendors, who sell their services to webhosts:

http://www.mojomarketplace.com/scripts
http://www.simplescripts.com/ (merged with MOJO says the web)
https://www.netenberg.com/fantastico.php#fantastico-scripts.html
http://www.softaculous.com/softaculous/
http://installatron.com/apps?s=VXWJHa3AWmIAAGeNM10AAAAF
http://wiki.dreamhost.com/Available_One_Click_Installs - they have an in-house solution. No Drupal! Probably second largest webhost!

Who would do the submitting?

**Comment by quicksketch** [comment] 2015-06-08 20:17
> Who would do the submitting? 

I'm comfortable with any interested person taking this on. However, if there are any kind of credentials or receipts for submitting a project, it would be great to get that information sent to info@backdropcms.org so we can keep a record of it in the event that someone else needs to make updates to the package in the future.

If anyone needs a hand or access, I'm happy to assist them!

**Comment by jenlampton** [comment] 2015-12-03 20:48
I'd love to see movement on this as well. Great idea @docwilmot

**Comment by docwilmot** [comment] 2016-01-14 16:56
We're now officially on MOJO Marketplace scripts list. MOJO provides One-Click Installs to a **whole bunch** of large webhosts including:

- BlueHost
- HostMonster
- iPower

Making us a click away for curious installers. See https://www.mojomarketplace.com/scripts

We've also gotten commitment from Softaculous, and still awaiting others.

**Comment by docwilmot** [comment] 2016-01-14 17:00
Also listed on OpensourceCMS.com FWIW, though no demo yet. 
http://www.opensourcecms.com/scripts/details.php?scriptid=702&name=Backdrop%20CMS

**Comment by klonos** [comment] 2016-01-22 22:22
MOJO lists 1.2.2 (btw, they list all versions of Drupal, 6, 7 and 8) and OpensourceCMS.com 1.2.3

Anyway to keep these up to date? ...add a step to the release procedures perhaps @quicksketch ?

**Comment by docwilmot** [comment] 2016-04-22 14:32
We're now also on [Fantastico](https://www.netenberg.com/fantastico.php#fantastico-scripts.html). 

Softaculous and Installatron are still considering.

**Comment by LeeteqXV** [comment] 2016-06-14 01:49
Softaculous would be great for WHM/cPanel environments (VPS etc.).
And what about getting it supported by SimplyTest.me?

**Comment by jenlampton** [comment] 2016-06-14 04:07
@LeeteqXV all great ideas!  Would you be wiling to reach out to SimplyTest.me and samiandmike@starstream.net for us?

**Comment by klonos** [comment] 2016-06-14 04:45
When it comes to simplytest.me, there's https://www.drupal.org/project/simplytest so perhaps it'd be worth building our own testing site/server. I had previously filed #338 which was closed as a duplicate of https://github.com/backdrop-ops/backdropcms.org/issues/5 which in turn was closed and the simpletest.me part of it filed as a follow-up issue: https://github.com/backdrop-ops/backdropcms.org/issues/172

**Comment by LeeteqXV** [comment] 2016-06-14 09:07
good, I will reach out to SimplyTest.me first, as part of an already planned initiative, see if I can get BD along, which is highly relevant anyway

**Comment by LeeteqXV** [comment] 2016-11-09 15:22
Patrick_DE at SimplyTest.me says: "atm it only supports projects that are hosted on drupal.org - makefiles can be used to fetch deps from github though". I have pointed him towards the new http://CMX.content.cat distribution community for some perspective on the potential usefulness for his service long-term, as drupal.org/D8 is not catering for the same markets as BDC-based CMX distros with 300-500 modules will.

**Comment by LeeteqXV** [comment] 2016-11-09 15:23
Also pointed him to this issue thread here, in case he wants to chime in. Lets see. I have a Twitter dialog with him atm.

**Comment by patrickd-** [comment] 2016-11-10 23:13
Hey there!
I'm trying to wrap my head around what the actual requirements are to get Backdrop running on simplytest.me. (The following questions might be stupid, sorry)

So if I see it right, all backdrop projects are hosted on github?
That would mean that simplytest.me cannot only use update.drupal.org as source for existing projects but must have some possibility to add projects from github to it's registry.

What about dependencies / compatibility?
While it would be easy to select "Backdrop" as Drupal Core alternative..
How can additional modules be handled - are 7.x modules from drupal.org compatible?
If not Backdrop but a Backdrop project is selected - is Backdrop required as Drupal Core or could the current Drupal 7 core be used?
How well does drush work with Backdrop? drush dl probably won't work - but what about the other stuff?

I'm definitely interested in offering backdrop support on the service but I can't promise how far I'm able to go right now.

**Comment by jenlampton** [comment] 2016-11-10 23:47
Hi @patrickd- thanks for looking into this for us :)
Answers to your questions below...

> all backdrop projects are hosted on github?

yes, that's correct, they are all in the "Backdrop contrib" organization: https://github.com/backdrop-contrib

> That would mean that simplytest.me cannot only use update.drupal.org as source for existing projects

Did you try using Backdrop's update server instead of Drupal's? updates.backdropcms.org

> What about dependencies / compatibility?

should be exactly the same as Drupal.

> are 7.x modules from drupal.org compatible?

No, at the very least, they need to have a line in their .info file changed. It would be best to use those "officially" supported (via our update server)

> could the current Drupal 7 core be used [with a backdrop contrib project] ?

No, Backdrop does have API changes that mean a Backdrop module can't run on Drupal 7. (configuration management is the biggest difference)

> How well does drush work with Backdrop?

The most common drush commands are supported in backdrop. For example, `drush dl` will download projects from GitHub instead of drupal.org.

* Make sure you are running Drush 8 (not 7, not 9) 
* add the Backdrop Drush extension into your "commands" directory in Drush 8. 
See https://github.com/backdrop-contrib/drush

**Comment by LeeteqXV** [comment] 2016-11-11 00:43
Thanks @patrickd- for the fast positive approach.

Since we are talking testing here, and as @jenlampton says the least change for compatibility is only one (standard) extra line in the .info file of each project, I imagine that this is something that could be automated to let many more people give various unported modules (straight from drupal.org) a try with BD and report back which ones seem to work with just that info file change. That would be very practical and help move forward faster.

**Comment by jenlampton** [comment] 2016-11-11 00:48
Good point :)

**Comment by patrickd-** [comment] 2017-01-13 13:30
Quick question: Does backdrop also have a composer repository like drupal.org for d7 and d8?

**Comment by jenlampton** [comment] 2017-01-14 04:57
@patrickd- I'm not sure what you are asking. What's a composer repository? Backdrop does not use composer, but we do have a docker file if you are only interested in seeing the dependancies: https://hub.docker.com/_/backdrop/

**Comment by docwilmot** [comment] 2017-01-16 17:56
Hurray, although we were long part of MOJO, but Bluehost (which uses a modified MOJO) had excluded Backdrop, but now not anymore! Users can now install Backdrop on Bluehost with one click, and update core with one click too (I havent tested the update core bit myself, but it has always worked fine for Drupal, I'm assuming it works here).

**Comment by herbdool** [comment] 2017-03-03 09:39
@jenlampton I believe @patrickd- is referring to what is described https://www.drupal.org/docs/develop/using-composer/using-composer-to-manage-drupal-site-dependencies

It's a way of making composer aware of an ecosystem of packages that are outside of packagist, if I understand correctly.

**Comment by jenlampton** [comment] 2017-03-06 19:41
Oh! This is a fantastic idea. We should do this too :)  Volunteers?

**Comment by serundeputy** [comment] 2017-03-07 03:32
I've been composing things as of late in backdrop and have toyed with the idea of getting backdrop and modules on https://packagist.org/ but each time shied away from it as I did not know how the rest of the backdrop community felt about it, but I think it could open up some really great possibilities for backdrop.

> Oh! This is a fantastic idea. We should do this too :) Volunteers?

So, I guess I volunteer :)

**Comment by herbdool** [comment] 2017-03-11 23:52
@serundeputy I had assumed that the packages would need to be supplied from a separate URL and couldn't get on packagist unless the projects followed PSR standard. Drupal serves its projects from https://www.drupal.org/docs/develop/using-composer/using-packagesdrupalorg

**Comment by dustinleblanc** [comment] 2017-05-07 21:32
In order to list things on Packagist, you need a properly formatted composer.json. Given that Backdrop does not appear to currently use Composer, it might get weird to use Packagist.

**Comment by herbdool** [comment] 2017-05-11 13:09
Just FYI I came across this WordPress fork which uses composer https://github.com/johnpbloch/wordpress

I think Composer is required to be used on Platform.sh no?

**Comment by jenlampton** [comment] 2018-01-19 01:55
Adding this to our milestone so we remember to update one-click installers with each release.

**Comment by oadaeh** [comment] 2018-03-15 20:26
FYI, I reached out to the current maintainer of SimplyTest.me to find out about his interest in Backdrop, and he told me that basically he wasn't opposed to it, but he's rather busy and preoccupied with getting some major architectural improvements done for drupal.org.

He did tell me what we could expect and/or do to make Backdrop compatible with the future of SimplyTest.me:
> In the short term, we'll need similar drupal.org web service API endpoints that would  enable us to pull project/theme/distro/core information from a Backdrop-sponsored system. This would be a necessity for the user interface. This could expedite things once we get to a point we can work on it.

For more about his plans and the future of SimplyTest.me, see http://nerdstein.net/blog/simplytestme-roadmap-early-2018

**Comment by jenlampton** [comment] 2018-03-27 23:40
Thanks @oadaeh. 

> In the short term, we'll need similar drupal.org web service API endpoints that would enable us to pull project/theme/distro/core information from a Backdrop-sponsored system. 

It sounds like Adam didn't know that we already have those things ;) 

I'd like to repeat [@klonos's concern from above](https://github.com/backdrop/backdrop-issues/issues/965#issuecomment-174071623):

> MOJO lists 1.2.2 (btw, they list all versions of Drupal, 6, 7 and 8) and OpensourceCMS.com lists 1.2.3 Any way to keep these up to date?

Especially in light of security updates like tomorrow's, it would be good to get a handle on how these projects are being maintained. 

@docwilmot do we have any control over what they are doing? Are there public repos where we can submit a pull request for an updated version? Or is all the magic happenng behind closed doors where we can't help keep people up to date.

**Comment by oadaeh** [comment] 2018-03-28 13:59
I see 1.9.0 on this page: https://www.opensourcecms.com/backdropcms/ so it is closer.
MOJO is still far behind, being only at 1.4.2.

**Comment by jenlampton** [comment] 2018-04-30 17:35
I just contacted SimpleScripts Installtron bitnami and Softaculous asking how new products can be added. 

Fantastico is the only one that has a secure version of Backdrop, so I've also contacted opensourcecms.com and mojomarketplace asking how we can help them stay up to date.

**Comment by klonos** [comment] 2018-11-01 23:54
Just adding here FTR what we have discussed in today's outreach meeting re simplytest.me and the sponsors section where we could possibly add our logo:

![screen shot 2018-11-02 at 8 20 09 am](https://user-images.githubusercontent.com/2423362/47886368-b0a29480-de8d-11e8-82e1-1d4d92b775f9.png)

**Comment by stpaultim** [comment] 2020-10-24 21:14
Should this issue be in the BackdropCMS.org issue queue with the other outreach tasks? I just spend 5 minutes trying to find it in that repo. ;-) I don't think we can simply move issues to another queue, can we?

**Comment by jenlampton** [comment] 2020-10-24 22:42
No, we'd need to close this one and open one there (but I'm in favor of that!)

**Comment by domaingood** [comment] 2020-10-29 21:09
https://github.com/backdrop/backdrop-issues/issues/4722

**Comment by stpaultim** [comment] 2020-10-30 02:08
I don't think this is the right place for this issue. We tend to put marketing, outreach, and community issues in the backdropcms.org issue queue, so I'm moving this issue to: 
https://github.com/backdrop-ops/backdropcms.org/issues/721

**Closed by stpaultim** 2020-10-30 02:08 UTC
Labels: help wanted
