### ISSUE TITLE
header-site-name-wrapper div still rendered even if the site name is disabled from the header block settings.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2303] opened 2016-10-22 13:29 UTC
I discovered this while doing some manual tests for https://github.com/backdrop/backdrop-issues/issues/2287

![backdrop-issue2303-site_logo_div_rendered_even_if_disabled_from_the_header_block_settings](https://cloud.githubusercontent.com/assets/2423362/19619643/16a06442-98b8-11e6-9a72-345a5a5e4af3.png)

**Comment by klonos** [comment] 2016-10-22 13:30
...site slogan works as expected, but need to check if the same happens with the logo.

**Comment by klonos** [comment] 2016-10-22 13:33
...also need to check if this is Basis-specific or system-wide.

**Comment by olafgrabienski** [comment] 2016-11-11 09:13
I can't reproduce the issue in a test environment. See the HTML code below.

Site name **enabled:**

```
<div class="contextual-links-region block block-system-header">
  <div class="contextual-links-wrapper contextual-links-processed">(...)</div>
  <div class="block-content">
    <div class="header-identity-wrapper">
      <div class="header-site-name-wrapper">
        <a href="/" title="Home" class="header-site-name-link" rel="home"><strong>SITE NAME</strong></a>
      </div>
    </div>
  <nav class="header-menu"> (...) </nav>
  </div>
</div>
```

Site name **disabled** (no more header wrappers):

```
<div class="contextual-links-region block block-system-header">
  <div class="contextual-links-wrapper contextual-links-processed">(...)</div>
  <div class="block-content">
    <nav class="header-menu">(...)</nav>
  </div>
</div>
```

Did I miss something to reproduce the issue?

**Comment by serundeputy** [comment] 2017-01-14 23:39
Needs more info as issue can not be re-produced. De-milestoned for now; @klonos are there other steps that you can identify to reproduce the issue?

**Comment by klonos** [comment] 2017-01-16 03:16
>Did I miss something to reproduce the issue?

Were you testing on Basis @olafgrabienski?

**Comment by olafgrabienski** [comment] 2017-01-16 14:34
@klonos Yes, and I checked it again in one of the open PRs: no 'header-site-name-wrapper' div, see screenshot:

![screen-backdrop-header-code-without-sitename](https://cloud.githubusercontent.com/assets/14188307/21986782/0c047064-dc01-11e6-906d-24330981d90b.png)

**Comment by BWPanda** [comment] 2018-02-01 03:34
This issue could only be seen when using the Basis theme and when you had a slogan visible, but the logo and site name hidden.

PR fixes it.

**Comment by opi** [comment] 2018-02-01 20:03
Review OK. Can't change issue labels on my phone :/

**Comment by BWPanda** [comment] 2018-02-01 22:01
Thanks @opi. There you go!

**Comment by quicksketch** [comment] 2018-02-08 22:25
Excellent, thanks all! Merged https://github.com/backdrop/backdrop/pull/2087 into 1.x and 1.9.x.

**Closed** 2018-02-08 22:25 UTC
Labels: status - has pull request, status - fixed
