### ISSUE TITLE
Double-clicking "Save" when editing content causes an error

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2595] opened 2017-03-23 11:39 UTC
_The content on this page has either been modified by another user, or you have already submitted modifications using this form. As a result, your changes cannot be saved._

I make new changes and again:

_The content on this page has either been modified by another user, or you have already submitted modifications using this form. As a result, your changes cannot be saved._

Then I edit the page again and get it again:

_The content on this page has either been modified by another user, or you have already submitted modifications using this form. As a result, your changes cannot be saved._

Sure I know if I view the page and get back again to edit it then it will be everything ok. But this is somewhat abnormal situation :smile: 

---
~PR: https://github.com/backdrop/backdrop/pull/2562~
PR: https://github.com/backdrop/backdrop/pull/2595

**Comment by laryn** [comment] 2017-03-23 20:14
Can you reproduce? What causes it in the first place?

**Comment by bd0bd** [comment] 2017-03-23 23:35
I save page. Second time I edit it again and press Save button may be 2-3 times at once.

**Comment by laryn** [comment] 2017-03-25 11:30
Yes, I can reproduce as well if I double or triple click the "Save" button. 
One potential solution would be to deactivate the "Save" button when it is first clicked, perhaps?

**Comment by serundeputy** [comment] 2017-04-01 20:24
https://www.drupal.org/node/1705618

**Comment by laryn** [comment] 2017-11-10 16:55
I just had a user report strange double content on a site and I think it may be related to this bug (double clicking on Save on the initial content create form rather than the edit form saves twice without an error). 

The content had the exact same URL alias which made it take a little longer to realize that it was two separate content items rather than a problem with views.

**Comment by klonos** [comment] 2019-04-02 00:17
This has been implemented in D8 core and the respective patch for D7 is RTBC.

Many people seem to have been using in prod for a few years now. There have been some that report that the patch has not fixed the problem for them, but in most cases it seems that browser caches need to be cleared.

PR added that mimics the D7 RTBC patch.

**Comment by klonos** [comment] 2019-04-02 01:43
I have tested this on my local (without the patch):

- Double-clicking on "Save" when creating content -> same content saved twice 👎 
- Double-clicking "Save" when updating content -> "Content modified by another user" error 👎 

Then tested on the PR sandbox:

- Double-clicking on "Save" when creating content -> content only saved once 👍 
- Double-clicking "Save" when updating content -> no errors 👍

**Comment by quicksketch** [comment] 2019-04-13 21:47
PR looks pretty good. Simple JS-based prevention is proven and usually effective. I left a single comment on the PR: https://github.com/backdrop/backdrop/pull/2562/files#r275133582

**Comment by klonos** [comment] 2019-04-14 13:05
Hmm, sorry I missed that `variable_get()` there 😓 ...I did some research, and it turns out that we've missed things like #3669 and #3670 (which will make things harder for the upcoming https://www.drupal.org/project/drupal/issues/2594151 / #3671). I think that we should hold this off until 1.13, and get all these things ported to Backdrop for feature parity.

PS: it seems that a) Drupal contrib modules such as AdvAgg and others (?) have already started implementing this, and b) there is some performance gain, especially on mobile, so this counts as a feature regression too.

**Comment by daggerhart** [comment] 2019-04-20 20:49
I've updated the code and submitted a new PR that does not involve the `javascript_always_use_jquery` variable.

**Comment by herbdool** [comment] 2019-04-21 15:35
RTBC @daggerhart's PR https://github.com/backdrop/backdrop/pull/2595

**Comment by quicksketch** [comment] 2019-04-27 21:45
Yay! This functionality is great and something we've been wanting for years. It's a simple solution but one that will solve most problems.

If it's okay, I've merged this _only_ into 1.x, as there is a small chance for breakage and it's a useful thing to be able to call out in the 1.13.0 release as being a new useful feature.

Thanks @klonos, @daggerhart @bd0bd, @laryn, and @herbdool!

**Closed by quicksketch** 2019-04-27 21:45 UTC
Labels: status - has pull request, status - fixed

**Comment by klonos** [comment] 2019-04-27 22:27
Thanks everybody! ...follow-up to keep parity with D7 core: #3717 😉
