### ISSUE TITLE
Port and merge Date Popup Authored in core (feature parity with D8).

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1379] opened 2015-11-29 07:43 UTC
Another module that's merged in D8 core: https://www.drupal.org/project/date_popup_authored

Part of #378

**Comment by klonos** [comment] 2015-11-29 07:47
I think that we already covered this with porting Date and merging it in Backdrop core, because I already have a date popup in my "Authored on" field.

**Comment by Dinornis** [comment] 2017-05-03 20:11
Hi @klonos I am closing this issue as a duplicate of https://github.com/backdrop/backdrop-issues/issues/775.  I hope that is okay.

**Closed by Dinornis** 2017-05-03 20:11 UTC
Labels: status - duplicate
