### ISSUE TITLE
[UX] Make the default home page path required

### ISSUE THREAD

**Issue by quinnanya** [backdrop/backdrop-issues#3343] opened 2018-10-26 02:01 UTC
On `/admin/config/system/site-information`, the default front page field is pre-populated with `home`, which generates the a layout, containing a feed of promoted posts. But the instructions beneath that field say:

> Optionally, specify a relative URL to display as the front page. Leave blank to display the default content feed.

If you clear out `home` and leave it blank as per the instructions, the home page seems to be your user account (e.g. /user/1).

---

**Translation update**

Strings to be replaced:
* `Default home page` becomes `Path to use for the home page`

 - - - - - - -

PR by @BWPanda - backdrop/backdrop#2690

MOST RECENT PR - 01/02/22
PR by @BWPanda and @stpaultim https://github.com/backdrop/backdrop/pull/3891

**Comment by klonos** [comment] 2018-10-26 08:34
Thanks for taking the time to report this @quinnanya 👍 ...I was able to reproduce this, but unsure what the "default content feed" mentioned in the help text is, nor what we should be redirecting to.

@jenlampton ??

**Comment by laryn** [comment] 2018-10-26 17:13
Hi @quinnanya! Agreed, that is strange behavior and/or misleading instructional text. 

Just to add, if you are not logged in, the front page becomes the login form in the case that you blank out the front page field.

I would guess as a user that this should just keep 'home' in place in that field if someone blanks it out (or behave as if it were 'home' if blank).

**Comment by klonos** [comment] 2018-10-26 20:42
@laryn if we were to "lock" things to `home`, I would expect things to work like so:

- have a check in place for when the field is left blank, and in that case have it default to `home`
- have the help of the text field be:

>Optionally, specify a relative URL to display as the front page. If left blank the URL will default to `home`.

I am still unsure what the default behaviour should be though, and I cannot remember how this worked before.

**Comment by klonos** [comment] 2018-10-26 20:49
...it seems that as it is now, the `promoted` view is being used. The description of that view is:

>Provides a list of promoted content. Used by default on the front page.

If this view is disabled, the home page main content area is rendered blank. So I think that this should also be implemented:

- check if the `promoted` view is disabled `&&` if the home page path has not been set to something that exists. If that is the case, then throw a message in the front page. Something like:

> It seems that the default _Promoted content_ view that is used by default on the front page has been disabled, and at the same time no other valid URL has been specified to be used as the home page.

**Comment by klonos** [comment] 2018-10-26 20:53
...noting that if you set the home page to a path that is not valid, we throw this validation error when saving the form in `/admin/config/system/site-information`:

> The path 'xyz' is either invalid or you do not have access to it.

I have not checked the code to verify if `home` is set as a hard-coded exclusion, of if the validation considers paths provided by disabled views as still being valid.

Anyway, I think we might be getting somewhere here 😄

**Comment by klonos** [comment] 2018-10-26 22:53
...you are right @laryn. The `promoted` view does not offer a page, only a block and feed. The block is used in the `home` layout, and disabling the view renders the block broken:

<img width="594" alt="screen shot 2018-10-27 at 9 51 48 am" src="https://user-images.githubusercontent.com/2423362/47595854-23af9500-d9ce-11e8-91f5-6b75a44993ba.png">

**Comment by klonos** [comment] 2019-05-07 13:01
This is a serious UX bug, that should be fixed as soon as possible. I am adding the milestone candidate so that it does not slip under the radar again.

**Comment by jenlampton** [comment] 2019-05-07 21:19
> unsure what the "default content feed" mentioned in the help text is, nor what we should be redirecting to.

Back before we had he home page layout, the "default content feed" was /node, and that's what Backdrop used for the front page. 

Perhaps we should revert to this behavior, so if no value is entered in this form, we save 'node' in the config file.

**Comment by klonos** [comment] 2019-05-07 22:29
Seems that we need to account for situations where whatever page (as in single specific node), view (or rather page display of a view), or layout that have been set as home page get deleted/unpublished/disabled. Perhaps warn "this is being used as the home page" when attempting these actions on those things? Not entirely sure at this point; I need to test various use cases, but lets handle the originally reported use case first.

@jenlampton yes, separate issue for the promoted block.

**Comment by jenlampton** [comment] 2019-05-07 22:31
How about a separate issue for all the things mentioned in your last comment (promoted block being one of them) and a simple asap fix for this issue as noted above?

**Comment by klonos** [comment] 2019-05-07 22:31
Yep, that too 🙂

**Comment by jenlampton** [comment] 2019-05-15 21:58
no PR, so removing milestone.

**Comment by BWPanda** [comment] 2019-05-19 20:03
I've looked into this and, from what I can see, the default value of the 'Default front page' field was changed from `node` to `user` in an effort to [make the `node` module optional](https://www.drupal.org/project/drupal/issues/375397). Also, the adding of the `if` statement to the default value was done when [removing the `required` attribute](https://www.drupal.org/project/drupal/issues/806232#comment-3001998) of that field.

Since our `node` module is still required then I think it's fine to set 'node' as the default (as @jenlampton suggested). I also noticed a field below the 'Default front page' field ('Number of posts on front page') that's only displayed when the 'Default front page' is `node`. However this only happens on saving the form, so it's not obvious that it's there (unless you scroll back down after saving to notice it). I've changed this to use `#states` instead so that it appears straight away when 'Default front page' is blank (i.e. `node`).

Finally, I saw a few places where `config_get('system.core', [SOMETHING])` was used, even though `$site_config = config('system.core');` is defined at the top of the function. I've therefore changed these to `$site_config->get([SOMETHING])` instead.

PR: https://github.com/backdrop/backdrop/pull/2690

**Comment by BWPanda** [comment] 2019-05-19 20:09
From my understanding of https://backdropcms.org/user-guide/adding-milestones-issues I'm allowed to add the milestone. Correct me and remove it if I'm wrong.

**Comment by stpaultim** [comment] 2019-10-23 00:08
We just had a question in the forum that is very much related to this discussion. 
https://forum.backdropcms.org/forum/adding-menu-block-front-page

A user listed node/2 as their home page and then added a block to the home layout and was surprised that their block did not show up on node/2 (which is their home page). 

This is because if you set a custom home page path at admin/config/system/site-information - the page will now use whichever layout is specified for that page, NOT the home layout. There is nothing in the UI to make this clear. 

A confusing alternative, would be to go to the home layout and set a visibility condition to use the home layout on node/2, but if you do that - you don't get the content of node/2 because the home layout does not have a Main Page Content block and it is NOT possible to add one. 

I think that in this situation, most of us would use a existing content block in the home layout and this is probably the best solution in most cases. However, I think we should do something to help reduce the likelihood that users might waste time on either of these other very sensible alternatives, neither of which work as one would expect.

**Comment by stpaultim** [comment] 2019-10-23 03:19
Optionally, specify a relative URL to display as the front page. If left blank the URL will default to home. The front page will use whichever layout is currently associated with this path.

**Comment by stpaultim** [comment] 2019-10-23 04:20
@BWPanda - I hope I'm not stepping on toes. I wanted to see if I could simply submit a new PR based upon yours. It appears to have worked. We have leave both for now, since there is yet no agreement on my suggested change in help text.

**Comment by BWPanda** [comment] 2019-10-23 04:32
@stpaultim Not at all, that's why I removed my assignment :slight-smile:

**Comment by stpaultim** [comment] 2019-12-14 22:36
Hmm, can't get the sandbox to work.

**Comment by jenlampton** [comment] 2020-01-15 21:58
The sandbox is working now, but the PR still needs work. 

We are setting the default value for the home page setting to `node` in this PR, but the description text was changed to say `Optionally, specify a relative URL to display as the front page. If left blank the URL will default to home. The front page will use whichever layout is currently associated with this path.` These two things are in conflict with one another.

We may need a helper function to find and set the default value for home page. It should go something like this:

1. Check if there is a layout with the path `home` and set that as the default. 
2. If not, set the default to 'node`.

After that, the description text will need another update. Thoughts:
* we can remove the word optionally.
* A `relative URL` we call a `Path`

```
Specify a path to use for the home page. If left blank, the system will use a layout at the path '/home' if it exists. If not, the the default content feed at '/node' will be displayed.
```

**Comment by docwilmot** [comment] 2020-03-29 17:40
> Specify a path to use for the home page. If left blank, the system will use a layout at the path '/home' if it exists. If not, the the default content feed at '/node' will be displayed.

Bikeshedding: can we just skip the path business and say:
> Specify a path to use for the home page. If left blank, the system will display the home layout if it exists, or an unformatted list of content if it does not.

**Comment by indigoxela** [comment] 2020-12-24 14:01
I could verify this odd behavior (/user is the default site_frontpage if nothing's set).

Out of curiosity I checked, when this came in. It was Drupal Issue #375397: "Make Node module optional.", commit [b3cf0681](https://github.com/backdrop/backdrop/commit/b3cf0681406832ea677d21beb438624a746b1622)

This isn't something we need to consider in Backdrop, the Node module is and should be required. So the PR looks reasonable to me (set default value back to /node).

It's marked as "needs work" only for wording reasons.

Just to revive this stalled issue. :wink:

**Comment by klonos** [comment] 2020-12-25 04:07
> * we can remove the word optionally.

👍 

> * A `relative URL` we call a `Path`

also 👍 

> Specify a path to use for the home page. If left blank, the system will use a layout at the path '/home' if it exists. If not, the the default content feed at '/node' will be displayed.

Sound good 👍 ...my only suggestion would be to replace "content feed" with "content listing".

**Comment by klonos** [comment] 2020-12-25 04:20
...I just saw @docwilmot's suggestion, and I like it better:

> Specify a path to use for the home page. If left blank, the system will display the home layout if it exists, or an unformatted list of content if it does not.

**Comment by klonos** [comment] 2020-12-25 04:41
...turns out I had a sandbox on my local for this. Here's where I am so far:

![image](https://user-images.githubusercontent.com/2423362/103119435-faf1bb80-467b-11eb-9888-5381de2e7091.png)

I believe that providing the user with options is much better UX than having them read lengthy help text, which explains what they need to do manually. I might clean up that version on my local, and push it as a PR, to see what people think.

**Comment by indigoxela** [comment] 2020-12-25 11:19
@klonos Nice try to derail this issue... :laughing: 

No, seriously, do we really need a new/different UI here? The site frontpage setting doesn't change often, in many cases not at all.

The main reason for this issue is that several people (including me) found it odd that the default value is "user" when nothing's set. Setting the default back to "node" makes sense for Backdrop. I don't think anyone had trouble with the user interface for that value. Or is that the case?

@BWPanda I think, there's an inconsistency in your PR. When the value is empty, the number of posts can be set, but not if the value is "node".

A screenshot for comparison:

![home-page-set](https://user-images.githubusercontent.com/842066/103133428-aa458700-46aa-11eb-8e2e-c2e0295c9c74.png)

**Comment by klonos** [comment] 2020-12-26 02:03
> No, seriously, do we really need a new/different UI here?

Nope. That's simply how I leave notes/thought-trails to myself in various issues. Then, after the PR gets merged and the issue closed, I file new follow-up issues. Sorry, I didn't mean to derail nor imply that any UI change should happen as part of this issue here.

**Comment by BWPanda** [comment] 2020-12-27 01:26
> When the value is empty, the number of posts can be set, but not if the value is "node".

Fixed, and PR updated. Thanks @indigoxela!

**Comment by BWPanda** [comment] 2020-12-27 02:32
Ok, so I added the preferred new help text, however it wasn't accurate until I also added the new feature that @jenlampton suggested re. changing the blank homepage to be `home` if the Home layout exists, or `node` if not.

So the latest PR now does the following:
- If the frontpage setting is saved as empty and the 'Home' layout exists and is enabled, sets the homepage to `home`, otherwise sets it to `node`.
- Always displays the value of the frontpage setting field (even if it's `home` or `node`.
- Changes the help text for the frontpage setting to:
  > Specify a path to use for the home page. If left blank, the system will display the home layout if it exists (`home`), or a list of promoted content if it does not (`node`).
- Only displays the 'Number of posts on home page' setting if the frontpage setting is `node` (using States API).

https://github.com/backdrop/backdrop/pull/2690 ready for testing again.

@stpaultim I popose closing your PR in favour of my updated one so it's easier for testers/less confusion.

**Comment by indigoxela** [comment] 2020-12-27 08:57
> Only displays the 'Number of posts on home page' setting if the frontpage setting is node (using States API).

Doesn't that mean that the setting is inaccessible if the value is empty and the `home` layout is missing? (Which means that `node` would be the default.)

Personally, I don't like such complex _hidden_ logic (it's this or that (home or node), you'll never guess...).
It can be so incomprehensible for users. But I don't want to start an extra discussion for that.

**Comment by BWPanda** [comment] 2020-12-27 09:26
> Personally, I don't like such complex hidden logic...

Yes, that's why I made the frontpage setting field *show* the value after you save the form with a blank value (previously it would remain blank if the value == 'node'). Now, you can see what the value is, and at that point it will correctly show (or not) the dependent field (this is, BTW, the same as the current behaviour - that dependent field is only shown/hidden after saving the form).

**Comment by indigoxela** [comment] 2020-12-27 10:07
> Yes, that's why I made the frontpage setting field show the value after you save the form

Many thanks for your explanation. I did some testing in the sandbox:

- Went to admin/config/system/site-information
- Removed `home` and saved
- `home` was back after saving
- Set the value to `node` (set a value for displayed items) and saved
- Node and chosen item value was saved correctly
- Set the value to `home` and saved
- Went to admin/structure/layouts and disabled the "home" layout
- Went to / - 404 not found
- Went to admin/config/system/site-information `home` was still set
- Saved without changes - `home` was still set (although the layout is still disabled, frontpage is still 404)
- Removed that value (empty) and saved - value switched to `node`

Ehm... to be honest, I had some WTF moments. But I'm no UI specialist. :wink:

**Comment by BWPanda** [comment] 2020-12-27 10:12
Thanks for the testing @indigoxela. That all sounds like it works as designed.

The reason for the 404's is simply because if you set the homepage to something (e.g. `node/4`) and then delete that content (e.g. delete node with ID `4`), the homepage setting isn't going to automatically update to something else. You're natually going to get a 'page not found' error. If you were expecting something different, then I believe that'll be a separate issue/feature request...

**Comment by indigoxela** [comment] 2020-12-27 10:18
> That all sounds like it works as designed.

I didn't question that :grinning:, but is it really better UX?

My three main problems with that solution seem to be:

1. I don't think it's smart to hardcode something that can be disabled / deleted (like the "home" layout)
2. I find it weird to fill out form items a user has emptied (that's not how I'd personally deal with default values)
3. I find it weird that the form lets me save "impossible values" without nagging or any hint (page non-existent or inaccessible for visitors)

Again, I'm no UI expert, so these are only my personal concerns.

**Comment by indigoxela** [comment] 2020-12-27 10:27
A quick update regarding point 2 from my previous comment (can save disabled layout, unpublished node).

This message explains it actually (I deleted layout "foobar"). "The path 'foobar' is either invalid or you do not have access to it."

The validation function should not check if I (the admin) have access, but if visitors have access. That's nothing that has been introduced with this PR, so it could be ignored here (follow-up issue?).

**Comment by klonos** [comment] 2020-12-27 23:22
> But I'm no UI specialist. 😉

I ain't one either ...but here's how I'd expect things to work ideally, as an end user:

- If I try to delete the node, or view, or layout that's set as my home page, there should be a warning, to let me know that I'll be getting 404s until things are fixed (new home page specified in `admin/config/system/site-information`). I understand that this is a separate issue though.
- If I leave the home page field empty, and that is changed to something that works as a fallback "behind the scenes", then I'd expect the success message on the form submit to be letting me know that this has happened (in other words, that whole "Removed home and saved -> home was back after saving" is a UX WTF).

> follow-up issue?

Yes, expect one or more follow-ups if all things that I consider WTFs are not addressed as part of this issue here 😅

**Comment by stpaultim** [comment] 2020-12-27 23:42
[In this comment](https://github.com/backdrop/backdrop-issues/issues/3343#issuecomment-545207080) (and comments following) I suggested a change to the help text to help users understand that if they set a new path, the "home" layout may no longer be used.

While this is not directly related to the user vs node default (it is related to the title of this issue "sort out issues with setting the default home page"), we are changing the help text in this PR already and I think adding this line would be really helpful to users to understand what is happening.

`NOTE: The home page will use whichever layout is currently associated with this path.`

I think that it will be VERY easy for users to not understand that even if they have an active home layout, changing this value will also change which layout is being used. 

Do I need to open a new issue and submit a new PR for this or is there any chance of getting this added?

**Comment by stpaultim** [comment] 2020-12-28 00:00
> "Removed home and saved -> home was back after saving" is a UX WTF

Well this not be optimal, it is not clear to me that this is a major UX problem because:

1) What does a user expect to happen if they remove the default value for the home page and don't replace it. It seems to me that the most obvious result is that the default action would return (that's why it's the default). It doesn't really make any sense to me why someone would remove "home" and not replace it and expect anything different to happen. 

2) If a user does remove "home" and not replace it, we have help text that explicitly says what will happen `If left blank, the system will display the home layout if it exists (home)` and one can easily see that the path is 'home' again. 

None of this is to suggest that adding a status message that says something like "You have set your page to _______" is a problem. But, I'm not sure it's required for a reasonable UX.

**Comment by indigoxela** [comment] 2020-12-28 08:25
It seems to me, that this issue is currently a little too wide for an easy solution. My first impression (almost done) might have been wrong.

Maybe it helps to split it into several (sub-)tasks?

- Switch the default fallback from `user` back to `node` - which would actually need less than the current PR already has
- Improve form validation to check for anonymous instead of admin access to potential frontpage setting (follow-up?)
- Elaborate an easy to understand UI (same or another follow-up?)

**Comment by stpaultim** [comment] 2020-12-28 20:42
> Maybe it helps to split it into several (sub-)tasks?

In the interest of simplification, I've broken my related, but different, concern about the help text into it's own issue. I still think it would be great if that issue could be merged with this one, but if there are any objections or concerns, we now have a different issue for that. #4839 

I am fine with the core change in this PR as it is which is to use the "home" layout if available and if not, to use the "node" path.

**Comment by philsward** [comment] 2020-12-29 08:30
Question: how many here have used the default "page display" provided by Drupal/Backdrop?

With well over 50+ sites under my belt on Drupal, not a single one is left to "node" and I don't think the home page layout for BD should use this either.

Yes, I realize it's a placeholder, yes I realize it's supposedly "friendly" for new users, but it's only worthwhile for the very first time someone new installs Backdrop.

The home page should be ready to add/edit home page content out of the box.

It always bugged me that I had to go override the home page on EVERY Drupal install. It should be as simple as clicking edit, adding/changing content and saving.

By having the list of pages, it's actually more confusing to new people because they have to now learn how to get rid of it.

Ideally, the install profile should ask: "How do you want your homepage to look?" With one option showing the "old" way and the other option of a page that is ready for homepage content. Add telemetry to the mix and measure how many people use one over the other, then promote the winner down the road.

**Comment by indigoxela** [comment] 2020-12-29 08:33
@philsward we're currently trying to narrow down the purpose of this issue. It seems to me, your comment further enhances the scope. :wink: You know - the wider the scope the less likely is a solution.

**Comment by philsward** [comment] 2020-12-29 09:12
@indigoxela sometimes you have to take a step backwards to view the whole scope, so you can figure out what actually needs fixed.

My point is that the entire homepage experience is really confusing all the way around. By understanding how we address the overall UX problem of how the homepage is expected to work, we can better guide the user on how to change the default homepage path.

What I would like to see, is a homepage experience where very few people ever have to change that default system setting and they only need to because they have a very specific reason for changing it.

By approaching it from this angle, we can better inform someone about what happens if it does get changed.

This issue while very valid for the "blank" scenario, still doesn't fix the fact that the OOTB experience is extremely confusing, even for experienced Drupal users where every single one of them is expecting to have to go change it.

**Comment by indigoxela** [comment] 2020-12-29 09:37
@philsward I agree, the whole UX regarding setting site_frontpage has issues and needs some loving care.

But the initial scope of this issue (see issue description) is that the default value - if not set - is `user` instead of `node` (a change we inherited from early D8). That would be an easy fix.

Fixing the "whole scope" is a huge task and I expect lengthy discussions, which means that the simple default value task won't get fixed for a looong time. I hope I could explain my suggestion to use sub-tasks a bit better now. :wink: 

UX discussions tend to get out of hand and that might block the simple switch back to default `node` - like it is/was in D7.

**Comment by philsward** [comment] 2020-12-29 09:41
@indigoxela no worries. Just playing devil's advocate and making sure we aren't tackling low hanging fruit that might end up changing later due to larger discussions.

Blank = /node is probably fine for now. Not a fan of it for long term though.

**Comment by BWPanda** [comment] 2020-12-31 23:09
A few of us were discussing this after the dev meeting, and it was suggested that in Backdrop, unlike Drupal, you generally shouldn't need to change the homepage path on the System Information page. It should stay as `home` and you could/should instead tweak the Home layout to do what you want (display a specific node, add additonal blocks, show a view, etc.).

In that case, I propose moving the homepage field on the System Information page into a collapsed fieldset (maybe called 'Advanced Settings'?) that, when expanded, displays a warning *above* the homepage field pointing people to the Home layout and saying that editing this field changes how Backdrop works and therefore should only be done if you know what you're doing.

**Comment by stpaultim** [comment] 2021-01-04 00:05
This issue has a very ambiguous title which I think is blocking progress, because with this title the goals are not clear.

I've opened a META issue that addresses the broader issues surrounding the home page. I'm going to open another new issue with the suggestion that @BWPanda mentioned in his last comment AND change the name of this issue to reflect the goals of the attached PR. 

Changing the default front page from user to node.

**Comment by stpaultim** [comment] 2021-02-05 06:39
> "Removed home and saved -> home was back after saving" is a UX WTF

In an earlier comment, I suggested that this wasn't so bad. Relooking at PR, I agree that this is very confusing. The field is not required and it appears that the user can delete the home page path, but then it is automatically added back without explanation. This was confusing for me and I assumed the patch was broken until I reread the earlier discussion (and noticed my earlier comment). 

@indigoxela said:
> Switch the default fallback from user back to node - which would actually need less than the current PR already has

It seems to me that this earlier goal was a step in the right direction. This discussion has gone lots of new directions and MANY new issues have been opened. I'd be inclined to make the original small step forward and then proceed with another issue. 

Putting this on agenda for next weeks DEV meeting.

**Comment by herbdool** [comment] 2022-01-02 15:23
Looks like it needs more discussion.

**Comment by herbdool** [comment] 2022-01-02 15:42
Actually I changed my mind. This doesn't need more discussion. I agree with @stpaultim that this issue only needs a simple pr to change default from user to node. Everything else is for new issues.

**Comment by herbdool** [comment] 2022-01-02 15:45
@stpaultim if you make that simple PR I'll review.

**Comment by stpaultim** [comment] 2022-01-03 00:07
@herbdool (or anyone else) 

I consulted with @bugfolder and @klonos today on how to solve the very basic part of this issue and we decided the following PR might be a good first step. I've submitted a NEW PR based upon work by @BWPanda, but with a few changes. 

In our opinion, part of the problem was the default behavior for an empty field. We decided that by removing the option for an empty field, we solve most of the problems.

This PR does the following:

1) It simply makes that field required, which removes any confusion about the default behavior when it's left empty and removes the need for fixing help text. 

2) We added an update hook to explicitly set the default to "user" if it is blank on any existing sites, which should keep the current behavior on those sites.

**Comment by klonos** [comment] 2022-01-03 01:01
The PR works for me, and the code looks good, so RTBC.

There are things that could be done better here UX-wise, but I'll leave that for a follow-up issue.

**Comment by herbdool** [comment] 2022-01-03 03:40
@stpaultim better.

I found one small issue. It now only accepts the raw `node/NID` and not the alias if a node is used. Didn't it allow that before? I think you may need to add back in `form_set_value($form['front_page']['site_frontpage'], backdrop_get_normal_path($form_state['values']['site_frontpage']), $form_state);` but without the if/else.

**Comment by stpaultim** [comment] 2022-01-03 06:22
@herbdool - Thanks for adding to the 1.20.4 milestone. This means there is no rush on this issue for Jan 3rd. I'll try to fix the issue you mentioned within 1-2 days.

**Comment by klonos** [comment] 2022-01-03 09:22
Good call @herbdool 👍🏼 

While we're changing things @stpaultim, I don't think that the simplified help text provides any value any longer:

![image](https://user-images.githubusercontent.com/2423362/147915005-f7223541-ab14-49c0-8584-8322be26b5c3.png)

We could:
- remove the help text entirely (and perhaps change the label of the field to include the word "path": `Default home page path`)
- change it to something like `Start typing to receive a list of relevant paths to select from.`

**Comment by klonos** [comment] 2022-01-03 09:47
I've changed the issue title to reflect what we're doing here. The setting
- already defaults to `'node'` for new sites (see https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/config/system.core.json#L68)
- will be retained to `'user'` for existing sites if (possibly intentionally set to blank) (see https://github.com/backdrop/backdrop/pull/3891/files#diff-71ecd72989e99f3bd8c92afc37144a39d6c51af1463df2b5283548dc06467830R3228)

**Comment by olafgrabienski** [comment] 2022-01-03 09:48
> (...) perhaps change the label of the field to include the word "path": `Default home page path`

"Default home page path" is too ambiguous, in my opinion. At first sight, it sounds like: You have to to this path (e.g. `home`) to see your home page, which isn't true. The actual meaning ("this path is **used** for your home page") is lost.

**Comment by klonos** [comment] 2022-01-03 09:50
You do have a point @olafgrabienski 🤔 ...should we then remove the word "Default"?

**Comment by olafgrabienski** [comment] 2022-01-03 10:00
> should we then remove the word "Default"?

Hm, not sure. This would lead to 2 instances of just "Home page": one heading, one label. I'd suggest in any case to leave the help text as is, because it turned out it provides a value.

**Comment by klonos** [comment] 2022-01-03 10:07
Right. I see what you mean now. I still think that it does not provide value, and what I meant was that the help text is short enough to be conveyed by the field label. Perhaps something like this would make more sense then:

![image](https://user-images.githubusercontent.com/2423362/147918867-4f256e11-abdd-47ef-b1e9-3f51c0e5b1ec.png)

**Comment by klonos** [comment] 2022-01-03 10:29
...or we can leave the discussion re the help text to #4839. I like @stpaultim's suggestion there.

**Comment by docwilmot** [comment] 2022-01-03 14:57
I'm confused again, it seems. I thought we were defaulting to "home". If that field is now required, then why dont we default to "home" now instead for new sites?

**Comment by klonos** [comment] 2022-01-03 16:05
@docwilmot here's my understanding:
- On new installations, we have always been defaulting to 'node' for the front page (see https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/config/system.core.json#L68). This is not changed by @stpaultim's PR.
- If the setting was blanked in `/admin/config/system/site-information`, the user would previously be redirected to `/user`
- Although the previous behaviour may seem odd (that's what this issue is about fixing), it may still be intentionally set as such on existing sites. Since we don't want to go breaking these sites, the update hook in @stpaultim's PR changes the config to `/user`.

**Comment by klonos** [comment] 2022-01-03 16:09
>On new installations, we have always been defaulting to 'node' for the front page

...right 🤦🏼 ...the default setting in system.core.json may be set to `node`, but the standard installation profile overrides that and sets it to `home`: https://github.com/backdrop/backdrop/blob/1.x/core/profiles/standard/standard.install#L112

Sorry about any confusion caused.

**Comment by docwilmot** [comment] 2022-01-03 16:38
OK so the only this we're doing here is making the default required.

**Comment by klonos** [comment] 2022-01-03 18:42
> OK so the only this we're doing here is making the default required.

Yup, it seems to be that way 👍🏼  ...which results in not being able to leave the setting blank ...which in turn fixes the original bug described in this issue (redirecting to `/suer` if the home page setting was set to blank).

**Comment by stpaultim** [comment] 2022-01-07 02:11
@herbdool - I've made the change that you requested AND changed the label and description. 

The change to the description had been split into another issue, but since I needed to edit this anyway I thought this might be a time to add this change. 

If people prefer we can delete the description all together and deal with it later in #4839.

This is what it looks like right now:

![image](https://user-images.githubusercontent.com/3144571/148480041-128debde-227d-4603-b141-f29ac0d18455.png)

**Comment by jenlampton** [comment] 2022-01-07 02:54
I find it a little strange that we are asking for the "Path" for the home page, because the home page most commonly will not show a path at all. This seems counterintuitive... I wonder if we can ask this question differently...  

**starts brainstorm**  If we could ask "Which page should we use for the home page of this site?" or ...  "Which page should we display as the home page for this site?"  I think that might make more sense to people.  We could use the description text to explain that we need the path for the page. 

Can we try the label `Which page should be used for the home page?`
And the description `Please provide the Path to the preferred page`

(I don't like mentioning layout in the description here because it won't necessarily have anything to do with a layout, and I fear it might mislead people. Or, we could add something conditionally only when the home page is a layout...)

**Comment by stpaultim** [comment] 2022-01-07 03:39
> (I don't like mentioning layout in the description here because it won't necessarily have anything to do with a layout, and I fear it might mislead people. Or, we could add something conditionally only when the home page is a layout...)

Well, I disagree in the sense that most of the time that a user changes this setting they are effectively changing the layout on the home page, but most new users do not realize that. The ONLY page (by default) that uses the home layout is "Home" - so if you change this, you are pretty much guaranteed to also change which layout is used on home page. 

Or am I missing something?

**Comment by stpaultim** [comment] 2022-01-07 03:56
![image](https://user-images.githubusercontent.com/3144571/148489027-105884d1-9e54-47d9-be7f-38b06d5ac280.png)

**Comment by jenlampton** [comment] 2022-01-07 04:02
This setting has nothing to do with layouts, that's all. Just like this
setting has nothing to do with nodes, but people could set the value to a
node. (Same with views!)

I understand it's extra confusing  with layouts since there's a core layout
with the name "home page" but i don't think this is the place to explain
that.

People could also have a node called "home" and a view called "home" but we
don't disambiguate those here.

If this setting does not point to a layout, but the description mentions
layouts, that's going to be even more confusing.

**Comment by jenlampton** [comment] 2022-01-07 04:03
Conditionally adding something could be useful, though. And we can tell if
the home page is using the home layout! That might be when we add some text
like you'd suggested.

**Comment by stpaultim** [comment] 2022-01-07 04:40
> This setting has nothing to do with layouts, that's all.

I find this statement very confusing, when virtually every time that a user changes this setting, they WILL also be changing their home page layout. The only time that changing this setting does not change the layout, is if the user had already changed it once OR disabled their home page layout. 

To say that this setting has nothing to do with layouts is technically true, but practically very problematic (in my opinion). 

I think it important that users understand that changing this setting will most likely also change their home page layout (given the current Backdrop defaults). I'm certainly open to other suggestions on how to convey this message to them or to prevent that misunderstanding. 

This has come up in the forum on more than one occasion: 
https://forum.backdropcms.org/forum/adding-menu-block-front-page

**Comment by olafgrabienski** [comment] 2022-01-07 09:09
> Which page should be used for the home page?

This sounds misleading to me, as the default `home` isn't a page IIRC.

**Comment by stpaultim** [comment] 2022-01-07 09:19
> This sounds misleading to me, as the default home isn't a page IIRC

Do you have a suggestion? We are struggling for the right description.

**Comment by olafgrabienski** [comment] 2022-01-07 09:46
> Do you have a suggestion?

Unfortunately not at the moment, but wanted however mention what doesn't work in my opinion.

I'm also a bit confused whether renaming things happens here or in #4839 .

**Comment by docwilmot** [comment] 2022-01-07 12:24
I get @stpaultim point that people may assume that whatever page you choose as "home" will automatically use the home layout. If layouts could accept multiple paths that would be a perfect solution. But failing that, I agree that we should give a heads up to the user that their front page layout will change. So I like Tims version https://github.com/backdrop/backdrop-issues/issues/3343#issuecomment-1007083270.

**Comment by herbdool** [comment] 2022-01-07 15:03
@stpaultim I tested and the autocomplete and validation now work. All tests passing.

Seems like we're going down a rabbit hole again. What if the description change here is very minimal. Remove the parts of the sentence that don't make sense anymore and leave the rest for later:

> Specify a relative URL to display as the home page.

**Comment by herbdool** [comment] 2022-01-07 15:05
@olafgrabienski I think most people think of "page" as generic enough to encompass what's available here, regardless of how the page is built (standalone layout, content type, etc). Regardless I say debate it on the other issue.

**Comment by bugfolder** [comment] 2022-01-07 15:07
I actually find @BWPanda's suggestion https://github.com/backdrop/backdrop-issues/issues/3343#issuecomment-1007258469 to be the clearest. But maybe, because of the several possibilities of where that path could come from, and the significance of it and potential for confusion for new users, this would be another candidate for some expandable description, something like this ([_more_] is a toggle that reveals the stuff below it):

![home page](https://user-images.githubusercontent.com/29214084/148563029-3675ef48-c424-49b6-9a47-99b856ca72d7.jpg)

**Comment by herbdool** [comment] 2022-01-07 15:12
@bugfolder can you copy your comment over to https://github.com/backdrop/backdrop-issues/issues/4839? I say anything other than the bare minimum change to the description is out of scope for this issue.

**Comment by bugfolder** [comment] 2022-01-07 15:39
Done.

**Comment by stpaultim** [comment] 2022-01-07 20:37
> Seems like we're going down a rabbit hole again. What if the description change here is very minimal. Remove the parts of the sentence that don't make sense anymore and leave the rest for later:

Yes, I'm sorry. I thought I had done that last and pushed a simpler version, but I see now that my controversial suggestion was still in the PR. I've removed it and went with the simplest option (in my opinion) for now.

![image](https://user-images.githubusercontent.com/3144571/148604114-6066f7ce-a789-496d-a3cb-1dfcf33696e1.png)

I see the problems with this text, but in my own view none of the alternatives are really any better or have any consensus.

**Comment by jenlampton** [comment] 2022-01-07 20:40
Yeah, let's not change the text in this PR, and go discuss in a follow up
issue. Thanks for getting us back on track.

**Comment by stpaultim** [comment] 2022-01-07 20:43
@herbdool - How does this look?

**Comment by BWPanda** [comment] 2022-01-07 20:53
Looks good to me, but I'm not @herbdool...

**Comment by herbdool** [comment] 2022-01-07 20:56
Nice and simple.

**Comment by docwilmot** [comment] 2022-01-07 21:11
> but I'm not @herbdool...

Should someone file an issue to fix that? @klonos?

**Comment by klonos** [comment] 2022-01-07 21:48
That's not a bug - it's a feature @docwilmot 😝

**Closed** 2022-01-13 00:29 UTC
Labels: status - fixed, needs - translation update

**Comment by quicksketch** [comment] 2022-01-13 00:30
Merged https://github.com/backdrop/backdrop/pull/3891 into 1.x and 1.20.x.

Thanks to @stpaultim, @quinnanya, @klonos, @jenlampton, @indigoxela, @laryn, @docwilmot, @herbdool, @BWPanda, @philsward, @olafgrabienski, and @bugfolder (phew)!

What a list! If there are any follow-ups, please post a final comment with links.
