### ISSUE TITLE
Bartik's main menu sub-links look ugly

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#726] opened 2015-02-18 01:26 UTC
The sub-links in Bartik's main menu look ugly. They are styled as 'tabs' but appear under the top-level tabs:
![firefox_screenshot_2015-02-18t01-18-04 000z](https://cloud.githubusercontent.com/assets/2385329/6240865/aa9519d2-b768-11e4-9c08-bdbd55047115.png)
('Test 2' is a sub-menu item of 'Test')

I propose instead something like this:
![firefox_screenshot_2015-02-18t01-25-59 855z](https://cloud.githubusercontent.com/assets/2385329/6240915/5949e570-b769-11e4-8803-b01625bdd2d6.png)

Steps to reproduce:

- Set Bartik as the default theme
- Choose 'Rounded tabs' as the Main Menu Tab Style in the theme settings
- Edit the Default layout and set the Primary Navigation block to use 'Hierarchical tree' as the Menu Style
- Add a new menu item as a child of 'About' (e.g. `posts/your-first-post`)
- View the About page (`about`) to see the issue with the child menu item:

![image](https://user-images.githubusercontent.com/2385329/158261656-1934396c-0b3b-46be-b216-218452de2012.png)

**Comment by klonos** [comment] 2015-02-18 14:15
Good catch! That must be something we missed. Neither D7 nor D8 Bartik themes show 2nd level links.

**Comment by wesruv** [comment] 2016-04-01 22:48
... can we just say Bartik is too close to being deprecated and not put effort into this?

I think the problem is Bartik is ugly :stuck_out_tongue:

**Comment by serundeputy** [comment] 2016-04-02 00:06
oh; poor bartik; :sadpanda: indeed;  point taken though;

**Comment by bd0bd** [comment] 2016-04-02 00:28
I do not think Bartik is ugly.
Menu is ugly.

**Comment by klonos** [comment] 2016-04-02 08:46
>... can we just say Bartik is too close to being deprecated and not put effort into this?

#1457 is targeted for 1.4.0 and so is #1361 so if none is pushed further back, then my logical reaction is "yes, lets not", but...

>I think the problem is Bartik is ugly :stuck_out_tongue:

I think it's ok (ugl**ier** than the new Basis theme, but not necessarily ugly) + I use it in some simple sites and intranet apps built on Drupal/Backdrop. Some others use it too, so I think that we should put some effort to it. People moving from old D7 websites will then have minor things to change in their design after the upgrade + they will get the bonus of a "pimped-up" Bartik with a few extra features. This will be an extra reason for them to make the move. If we tell them that in order to get nice-looking menus they'll also have to switch theme and adapt it to match their current design/branding (more changes and thus more effort/cost required), then they are less likely to make the switch. Plus they more cost is against our philosophy.

My 2c.

**Comment by Graham-72** [comment] 2016-04-02 11:35
> I think that we should put some effort to it

I agree and am willing to contribute some effort, even if only a small contrib module. I use Bartik a lot, but with custom secondary menus and not those out of the box. Nevertheless I am very much looking forward to the new core theme coming soon as another design option.

**Comment by wesruv** [comment] 2016-04-02 20:06
Cool, I can take a crack at this since I did the tabs in seven it should be pretty easy to port over.

Just wanted to make sure it's worth the effort and those are some excellent reasons to follow up with it.

**Comment by bd0bd** [comment] 2016-04-02 23:00
Are you going to make it like the admin menu?
Would be cool.

**Comment by gifad** [comment] 2016-04-02 23:20
Making a responsive menu for narrow devices, _à la_ `adminimal_admin_menu` is easy, but I've not yet found a good design for a multi-level menu on tablet size, touch devices (no mouse), compatible with small laptops, trackpad driven — at least for a "classic" theme bartik like (multi-column, explicit header / footer…)
Example anyone ?

**Comment by Graham-72** [comment] 2016-04-03 05:13
> Cool, I can take a crack at this

:+1:  :+1:

**Comment by bd0bd** [comment] 2016-04-03 13:59
>Making a responsive menu for narrow devices

I mean only dropdown menu without responsiveness.
It would be cool.

**Comment by gifad** [comment] 2016-04-03 15:47
> only dropdown menu without responsiveness

just pick up the css files of [nice_menus](https://github.com/backdrop-contrib/nice_menus), and you've got a good starting point…

**Comment by bd0bd** [comment] 2016-04-03 16:02
No, this is not a problem.
I know CSS.
Also I use this module - this is the problem.
I mean dropdown menu  inegrated by default in the core so any people could make multilevel menu.

**Comment by mikemccaffrey** [comment] 2016-04-03 17:08
We definitely should fix how the second level tabs are rendering in Bartik, since that looks obviously broken. However, I'm thinking we should stick to something simple, like a row of links. We should move conservatively with this theme, since: 1) We are deprecating it as the default theme and shouldn't spend too much time improving it, and 2) it has been the default theme for quite a bit of time, so we don't want to break the styling of any backdrop sites that are already using it, or any drupal sites using it that want a simple upgrade to backdrop.

Make sense?

**Comment by bd0bd** [comment] 2016-04-03 18:03
@mikemccaffrey, I think it would be better to have **two**  modes - keep the current version and a possibility to switch to the new mode. In the Bartik theme settings or the menu block config  to have this mode switcher.

**Comment by wesruv** [comment] 2016-04-03 18:32
@mikemccaffrey I like where you're going @mikemccaffrey. If I added new functionality and it caused problems I'd rather not bury a bunch of time in it.

@bd0bd if there's a desire for a fancier/continuing improvement for bartik it could be forked in contrib-land? I think having 'modes' and managing two sets of code in one theme would be a bit of a pain and not very 'core appropriate'.

**Comment by docwilmot** [comment] 2016-04-03 18:43
> Making a responsive menu for narrow devices

See [[UX] Provide responsive drop-down menus out of the box](https://github.com/backdrop/backdrop-issues/issues/1457#issuecomment-174560739). Would be great to hear opinions on this.

**Comment by bd0bd** [comment] 2016-04-03 18:44
I think my offer is not bad. It is not something new or special solution, it is good practice within transition periods.  Yahoo mail box had the option to use old box design or switch to the new one. Sometimes when we make a new site old visitots can use the old version too.

**Comment by bd0bd** [comment] 2016-04-03 18:54
@docwilmot, this is what I mean https://cloud.githubusercontent.com/assets/1042283/12556490/1e7a151c-c354-11e5-9dbe-12e251b2898b.PNG

**Comment by klonos** [comment] 2016-04-04 02:36
@mikemccaffrey yes, we are deprecating it from being the *default* front-end theme that comes with core, but we are not *removing* it from core AFAIK. That's for the exact same reason: it has been in core, people are still using it (and my guess is that they will keep using for simple site designs) and we don't want to break their sites. I bet you, once we implement drop-down menus, people will expect them to work with it. If they see a row menu instead of drop-down, you'll see issues in the queue about it.

**Comment by jenlampton** [comment] 2017-08-17 19:24
I think we should leave this issue here since it's a good novice one for people who are CSS experts to tackle, but as Bartik is no-longer our front-end theme, it's definitely not high priority.

**Comment by BWPanda** [comment] 2022-01-27 02:56
It's been over 4 years since the last activity here. Any objections to just closing this issue?

Also, this no longer happens out-of-the-box. You have to first enable tabs in Bartik's settings to see this bug:
![image](https://user-images.githubusercontent.com/2385329/151283845-b985eeb7-a321-474a-a1a1-b9311e3b223b.png)

**Comment by BWPanda** [comment] 2022-02-28 12:48
Closing due to lack of interest/need.

**Comment by klonos** [comment] 2022-03-01 12:52
@BWPanda I don't think that we should be closing issues with confirmed bugs just because we have other priorities. This issue is also marked `good first issue`, so it might be fixed by a person that is looking to dip their toes into contributing to Backdrop.

I think that the only reasons bug reports should be closed should be:
- cannot reproduce the issue
- the issue has become obsolete/outdated because other changes have been merged in the meantime
- the component the issue has been raised for (in this case the Bartik theme) has been removed from core
- issue is fixed

**Comment by RakeshPotnuru** [comment] 2022-03-13 17:11
@BWPanda, @klonos 
I think this issue resolved
<img width="229" alt="image" src="https://user-images.githubusercontent.com/70439799/158070948-ba08a1c5-f63c-439e-9bf1-b910f3c7c7d3.png">

**Comment by stpaultim** [comment] 2022-03-13 21:09
@RakeshPotnuru - Your screen shot shows the menu on mobile. This issue is about the desktop view. 

However, I am also having trouble to recreate this issue. Here are the steps that I THOUGHT would recreate it. 

1) Spin up site and enable Bartik and make it the default theme. /admin/appearance
2) In the theme settings for Bartik, enable rounded tabs /admin/appearance/settings/bartik

**Comment by RakeshPotnuru** [comment] 2022-03-14 12:13
@stpaultim 
It's looking fine, I think it's fixed.
<img width="956" alt="image" src="https://user-images.githubusercontent.com/70439799/158169657-939baa72-aab4-4177-924b-9370796b6cfd.png">

**Comment by jenlampton** [comment] 2022-03-14 21:08
Thank you both for confirming, and for the screenshots!

**Comment by BWPanda** [comment] 2022-03-14 21:08
The issue still exists:

- Set Bartik as the default theme
- Choose 'Rounded tabs' as the Main Menu Tab Style in the theme settings
- Edit the Default layout and set the Primary Navigation block to use 'Hierarchical tree' as the Menu Style
- Add a new menu item as a child of 'About' (e.g. `posts/your-first-post`)
- View the About page (`about`) to see the issue with the child menu item:

![image](https://user-images.githubusercontent.com/2385329/158261656-1934396c-0b3b-46be-b216-218452de2012.png)

**Comment by jenlampton** [comment] 2022-03-14 21:10
restoring tags, thanks @BWPanda!

**Comment by stpaultim** [comment] 2022-03-16 06:00
I am working on this issue with the Triplo team in our first Office Hours for folks on the other side of the globe.

**Comment by stpaultim** [comment] 2022-03-16 07:11
![image](https://user-images.githubusercontent.com/3144571/158535352-ba1e44ee-a6e1-4471-bb04-c3f4a6d97982.png)

The Triplo team was working on this issue tonight and we did an exploratory Pull Request to get additional feedback, because we're not sure about the best solution

1) We are not experienced with Hierarchical menu's and are not sure what the expected behavior is. Please check to see if this is working correctly.
2) We are not sure how this should interact with the breadcrumbs. Currently it is overlapping, which does not seem correct, but the only alternative we can think of is to push the breadcrumbs down, which also does not seem correct. 
3) Also, we are not sure if this kind of fix is even possible, in a backwards compatible way. 

We appreciate some feedback.

**Comment by BWPanda** [comment] 2022-03-16 07:47
@stpaultim I would recommend putting each level of the hierarchy on a line below its parent, with siblings sitting next to each other (rather than below each other like you currently have).

**Comment by BWPanda** [comment] 2022-03-16 09:43
Ah OK, thanks for the clarification.

Things should be pushed down, not covered. The only time I expect things to be covered is with a drop-down menu, and here we've specifically chosen otherwise.

**Comment by stpaultim** [comment] 2022-03-23 05:26
For the record, we looked at this same menu display in Basis and it does not behave as @BWPanda suggested, which means that we are going to hold off on this issue until we get further clarification.

We added this to the next Design/UX agenda.

**Comment by BWPanda** [comment] 2022-03-25 01:50
After listening to the Design/UX meeting discussion about this issue, I agree with @jenlampton's suggestion for just fixing the styling of sub-links in this issue, then open another issue for discussing the display of hierarchical menus in general.

I didn't realise there were two separate issues going on here.

So here's what it currently looks like when on a page that has sub-links:

![image](https://user-images.githubusercontent.com/2385329/160038394-4c831a12-fdd7-4498-b934-864698365893.png)

I think either removing the background of the sub-links:

![image](https://user-images.githubusercontent.com/2385329/160038480-5bbee582-dc01-4ac3-a0b8-b455c7efbb82.png)

Or adding padding to match to top-level links:

![image](https://user-images.githubusercontent.com/2385329/160038602-743795d0-4f76-4e15-986c-28064d20a59a.png)

Would be an improvement.

Now that I've done that, it seems like the last screenshot is what it's supposed to look like. I achieved that by simply adding `display: block;` to Bartik's `style.css` in this selector: `.l-header ul.menu li li a {}`

**Comment by stpaultim** [comment] 2022-03-25 02:18
@BWPanda - Thanks. Feel free to submit your own PR. Otherwise, I think we'll revisit this issue at our next office UTC5 office hours. We can at least make a little progress on this and your screenshots help.

**Comment by yorkshire-pudding** [comment] 2022-03-25 09:05
@BWPanda - your third option definitely looks right.

**Comment by irinaz** [comment] 2022-03-25 19:31
@BWPanda , third option looks correctly, thank you!
@stpaultim , to our conversation in UX meeting -  admin menu module provides standard design/UX for hierarchal menus 

<img width="502" alt="Hierarchical-menu" src="https://user-images.githubusercontent.com/2497005/160188767-aa16e63e-b455-4736-ae67-da82a6da3c82.png">

**Comment by stpaultim** [comment] 2022-03-30 07:15
@bdalomgir provided a PR that makes sense to me, but I'm still not certain it's what other people expect. He has indented 2nd level menu items as opposed to breaking them out by themselves as in the admin menu. 

I think this might be sufficient for this task, feedback wanted.

![image](https://user-images.githubusercontent.com/3144571/160773336-a692278f-d974-4a1b-93be-148fc2d35293.png)

**Comment by stpaultim** [comment] 2022-03-30 07:37
While we have been putting work into this issue, we do still have the problem of how to make changes like this without breaking existing sites. This problem might be obscure enough and broken enough, that fixing it is relatively safe. But, can we be sure that we are not breaking existing sites?

https://github.com/backdrop/backdrop-issues/issues/4167

**Comment by indigoxela** [comment] 2022-03-30 07:47
> I think this might be sufficient for this task, feedback wanted.

I think this is a slight improvement, but TBH it still looks broken. This is (yet another) topic where we should avoid possible side-effects on existing installs (which in the end prevents lots of improvements).

Personally, I never use Bartik. Not even with D7, and I'd never consider using it with Backdrop (after upgrading). It looks so ancient. So maybe in this special case we should really consider a bigger CSS change - this theme is only there to make upgrades from D7 easier, right? Or is anyone actually using it?

**Comment by yorkshire-pudding** [comment] 2022-03-30 07:58
@stpaultim - I changed the menu setting to dropdown (from hierarchical tree) and it works as you would expect.
![chrome_pS0RmMmNms](https://user-images.githubusercontent.com/20357797/160781430-2190e803-5ee4-4734-9a27-7691c1fb07f1.gif)

**Comment by yorkshire-pudding** [comment] 2022-03-30 07:59
So a significant improvement

**Comment by RakeshPotnuru** [comment] 2022-03-30 08:02
Just leaving a suggestion. Add a hover effect.

**Comment by stpaultim** [comment] 2022-03-30 09:52
> I changed the menu setting to dropdown (from hierarchical tree) and it works as you would expect.

@yorkshire-pudding - This was only intended to effect menus using the Hierarchical tree. To my knowledge the dropdown menu worked fine from the start. 

> I think this is a slight improvement, but TBH it still looks broken.

This is a good point and I should probably have been clear - this was discussed at the last design/UX meeting and no one had any idea what this SHOULD look like or if it would be possible to make that kind of change. The thought was that we should make it at least look less broken. Hence, the suggestions provided by @BWPanda here: 
https://github.com/backdrop/backdrop-issues/issues/726#issuecomment-1078574729

These were the best ideas we could come up, but I agree that all of them still look broken.

**Comment by yorkshire-pudding** [comment] 2022-03-30 09:56
@stpaultim - good point 
I can't think why anyone would use hierarchical tree menus in that location

**Comment by irinaz** [comment] 2022-03-30 15:05
> @stpaultim - I changed the menu setting to dropdown (from hierarchical tree) and it works as you would expect. ![chrome_pS0RmMmNms](https://user-images.githubusercontent.com/20357797/160781430-2190e803-5ee4-4734-9a27-7691c1fb07f1.gif)

This looks perfect.

**Comment by bugfolder** [comment] 2023-09-30 02:52
Tested this with the STR:

- Set Bartik as the default theme
- Choose 'Rounded tabs' as the Main Menu Tab Style in the theme settings
- Edit the Default layout and set the Primary Navigation block to use 'Hierarchical tree' as the Menu Style
- Add a new menu item as a child of 'About' (e.g. `posts/your-first-post`) (also added a second item for effect)
- View the About page (`about`) to see the issue with the child menu item:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/9293836e-aa46-437c-86c7-a4cdd36f0b87)

Applied the patch:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/d18fe7f3-51aa-4dec-8a33-2fc878c746f6)

Similar to @stpaultim's [comment above](https://github.com/backdrop/backdrop-issues/issues/726#issuecomment-1082713666), I think it's sufficient for the task, and does what is intended. So WFM.

Reviewed the CSS code. LGTM.

RTBC.

**Closed** 2023-10-06 18:31 UTC
Labels: type - bug report, type - task, status - has pull request, good first issue, design, pr - ready to be committed, pr - works for me

**Comment by quicksketch** [comment] 2023-10-06 18:33
Wow, this is an old issue. I'm happy to have merged https://github.com/backdrop/backdrop/pull/4027 to substantially improve the output of Bartik.

[0ebf474](https://github.com/backdrop/backdrop/commit/0ebf47467223f699fc6760f1d1d8897555941882) by @bdalomgir, @BWPanda, @stpaultim, @irinaz, @indigoxela, @yorkshire-pudding, @RakeshPotnuru, @bugfolder, @bd0bd, and @klonos.
