### ISSUE TITLE
Add link (field) module to core

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#240] opened 2014-05-17 06:55 UTC
Instead of leaving this as a stand-alone module, it should be added as a field type to field module.
(form field types should be updated to use the HTML5 url element too)

**Comment by quicksketch** [comment] 2015-06-25 19:52
@serundeputy has taken a stab at this and filed a PR at https://github.com/backdrop/backdrop/pull/971.

**Comment by klonos** [comment] 2015-06-25 23:07
I was wondering (not only for link, but also for the rest of the contrib modules that we are adding to core)... what happens during D7 website upgrades to Backdrop? I mean are the D7 contrib module settings upgraded/migrated by the respective Backdrop in-core module?

**Comment by serundeputy** [comment] 2015-06-26 01:33
@quicksketch has https://github.com/quicksketch/backdrop/commit/118e9006c930c7c63d890af8c33d1d83bae4e007

which lets us figure out if a contrib has been merged into core 

i believe the settings are migrated as well,  but it is a good point this upgrade functionality Will have to be written into these modules as well;  `link`, `date`, etc

**Comment by serundeputy** [comment] 2015-07-25 23:50
request for more eyeballs; @klonos, @docwilmot @Graham-72 and of course anyone else who is willing and able;
These tests are failing from `link.crud_browser.test`
```php
//_field_info_collate_fields(TRUE);
    $instances = field_info_instances('node', 'page');

    $instance = $instances['field_' . $name];
    $this->assertFalse($instance['required'], 'Make sure field is not required.');
    $this->assertEqual($instance['settings']['title'], 'optional', 'Title should be optional by default.');
```
but when I load up a variable `$my_var =     $instances = field_info_instances('node', 'page');` and dpm it has the value `optional` that the test is looking for so I'm perplexed on this one.  There  another 8 or 12 tests from the browser_crud file that are failing.

----
Then in link.entity_token.test it requires that the modules token, entity and entity_token be enabled, but when I search for those on `/admin/modules` they are not to be found.

```php
function setUp($modules = array()) {
    parent::setUp(array('token', 'entity', 'entity_token'));
  }
```

I'm trying to work my way through the rest of the tests as well, so more to come.

thanks,
~Geoff

**Comment by klonos** [comment] 2015-07-27 06:13
Unfortunately, I can't help with the failing tests but I might have an idea about the missing modules...

You see, according to #480, when token was moved to core, it was actually merged into system.module. So, if I got this right, there is no token.module in Backdrop core. All parts of the token module that are specific to other modules (I believe that these are the actual tokens for these modules), reside inside dedicated [module_name].tokens.inc files within the specific module folders.

So, I think that entity_token.module is pretty much entity.tokens.inc now.

As I said, far from a php expert or Drupal/Backdrop code expert for that matter, so could be totally wrong about all this.

**Comment by quicksketch** [comment] 2015-07-27 21:42
> Then in link.entity_token.test it requires that the modules token, entity and entity_token be enabled, but when I search for those on /admin/modules they are not to be found.

Yeah, all 3 of these should be able to be omitted. The core entity.module is required and cannot be disabled. Token is build into core as part of system and other modules. Entity token is *not* specifically included in core, so different entity types still need to expose their individual properties (e.g. Node NID, User name, etc.) but they do not need to expose their fields, as that is done for them by Field module's token integration now.

I always had a small beef with entity_token in D7 because it duplicated a bunch of tokens provided by Token module. In addition to token module's `[node:field_my_field]`, it would make another token `[node:field-my-field]`, resulting in two tokens that essentially did the same thing. For the purposes of testing, things should be similar enough to preserve the tests, but the names of the tokens may not line up if they were from Entity Token previously.

**Comment by docwilmot** [comment] 2015-07-28 18:38
@serundeputy, had a look, but not sure how to contribute my changes, submit a new PR? A patch? The GitHub process is still fuzzy sometimes. Anyway, meanwhile, I'm pushing a new PR with still some failing tests, but closer to green, and:
- I think the link entity_tokens tests dont really apply, since there is no exposure of token UI on the add field pages, which is what the test tests. Should that test be removed then?
- the misbehaving `$instances = field_info_instances('node', 'page');` is because of a static variable set in `_field_info_collate_fields`. If you replpace the `_field_info_collate_fields(TRUE);` lines with `backdrop_static_reset();` it works.
- fixed a few 'drupal' strings left over. 
- link.validate.test is failing on a `variable_get()` leftover which needs converting to config. I should have fixed that but havent, sorry.

**Comment by serundeputy** [comment] 2015-07-28 21:15
thanks @docwilmot and @quicksketch;
------
I'm taking @quicksketch 's sketches into my mind and going through the tests.

----
@docwilmot looks like your efforts are on your repo: https://github.com/docwilmot/backdrop/commits/link on the `link` branch.

I'll track your repo look at your branch and then I can merge them into my branch.

thanks,
~Geoff

**Comment by serundeputy** [comment] 2015-07-28 21:37
@docwilmot I apologize I had not pushed up my latest changes after asking for help :frowning: with it.

(1) I've pushed them up now; If you file a `PR` against my repo serundeputy/backdrop on branch: `240/add_link_field_to_core` that will be the easiest way to see the diff I think.

(2) otherwise I can go through your changes on your `PR` against the backdrop/backdrop repo; I've already seen some helpful things in there so thanks.

The thing I don't like about (2) is you won't get commit credit even though it is your work; so (1) would preserve your work and credit.

~Geoff

**Comment by docwilmot** [comment] 2015-07-28 21:47
Actually, I'd prefer you just picked out the changes; I'm a little short on time right now. Don't at all mind not getting credit. And my changes were essentially that one `backdrop_static_reset` and a find-and-replace for drupal strings and a couple little things. 
Thanks.

**Comment by serundeputy** [comment] 2015-07-28 21:48
ok cool;

**Comment by quicksketch** [comment] 2015-07-29 20:06
I've been testing this out. Here are the issues I've found:

- When setting up a new link field, if the field is required but no default is provided, you get this error trying to save the field configuration:

  > At least one title or URL must be entered.

  I shouldn't be required to provide a default.
- When editing a node that has a link with a title, there is an unnecessary description (IMO): "The link title is limited to 128 characters maximum." Do you think we can nix this?
- I once received a notice when saving the field configuration: 
```Notice: Undefined index: title in _link_validate() (line 446 of /media/nate/Mecury/Users/nate/Sites/backdrop/core/modules/link/link.module)."``` But reproducing it is a little tricky. Perhaps we just need to use an `empty()` check there to prevent notices.
- When allowing a user to enter a custom class *and* additional classes are specified in the field configuration, only the custom classes are printed. The additional classes are not printed. If the ability to have custom classes is disabled, then the additional classes are printed properly.

Overall, looking great! I'll take a look at the tests and see if I can help there.

**Comment by serundeputy** [comment] 2015-08-02 15:30
Implemented changes suggested in: https://github.com/backdrop/backdrop/pull/1007

> When setting up a new link field, if the field is required but no default is provided, you get this error trying to save the field configuration: `at least one URL ...`

this didn't happen to me after implementing the suggested changes in https://github.com/backdrop/backdrop/pull/1007 (sometimes problem?)

> When editing a node that has a link with a title, there is an unnecessary description (IMO): "The link title is limited to 128 characters maximum." Do you think we can nix this?

  I nixed it; we can put it back if others disagree.  If no one chimes in we will leave it nixed.

> I once received a notice when saving the field configuration: Notice: Undefined index: title in _link_validate() (line 446 of /media/nate/Mecury/Users/nate/Sites/backdrop/core/modules/link/link.module)." But reproducing it is a little tricky. Perhaps we just need to use an empty() check there to prevent notices.

- [ ]  TODO:
  I wasn't sure where to put the `empty()` check as line 446 is now different after the above refactor.

> notices.
When allowing a user to enter a custom class and additional classes are specified in the field configuration, only the custom classes are printed. The additional classes are not printed. If the ability to have custom classes is disabled, then the additional classes are printed properly.

 - [ ] TODO: I have not looked at this one yet

**Comment by quicksketch** [comment] 2015-08-02 19:28
Thanks @serundeputy! It's great to see the changes coming along!

As a general thought, I'm torn between maintaining the compatibility and
trying to simplify the module. IMO, the configuration of a link field is
crazy complicated. OTOH, I don't think we should remove any feature of the
module unless very carefully considered. With our primary selling point
being compatibility, we should keep as much as possible intact (and
upgradable).

However, if we can clean up the configuration of link fields, I think that
would be great. Moving all the settings for "rel", "target", and "class"
into an "Advanced" fieldset might help clear it up a bit. We're also
showing a bunch of settings that aren't applicable, like showing the
"Remove rel when link is external" option when there isn't a rel attribute
in the first place. It would be good if we could either use #states to hide
that when not applicable, or find a way of setting that configuration that
isn't so awkward.

**Comment by serundeputy** [comment] 2015-08-02 20:17
@quicksketch thanks so much for your direction, testing and comment on this! I find it very helpful in unsticking me and giving direction to the task.

> IMO, the configuration of a link field is
crazy complicated.
 
  it 'tis , but sensible defaults (usually I use the defaults and am happy with them)

> OTOH, I don't think we should remove any feature of the
module unless very carefully considered. With our primary selling point
being compatibility, we should keep as much as possible intact (and
upgradable).

  yes.  my inclination here is to leave in the functionality and try to clean up the UI on the field config page.  I think the defaults are sensible and probably make 80%+ of users happy. 

  I think fieldsets are a great idea here!

  I have on some occasions had clients ask for blah, blah on some specific link (or many fields) and in the case of link module I am always pleasantly surprised that they let us add a class!  I'm like oh; good add class, save and put some css; client and dev are happy :smile:

>  We're also
showing a bunch of settings that aren't applicable, like showing the
"Remove rel when link is external" option when there isn't a rel attribute
in the first place. It would be good if we could either use #states to hide
that when not applicable

  I for one am onboard with using `#states` for this.

All in all I think I'm in favor of keeping the functionality and cleaning up the UX of using `link` field.

The question becomes what is the scope for Sept 15th?  Do @jenlampton, @klonos, @wesruv @docwilmot  have opinions on this?

**Comment by klonos** [comment] 2015-08-02 22:12
> The question becomes what is the scope for Sept 15th? Do @jenlampton, @klonos, @wesruv @docwilmot or others have opinions on this?

Not sure what you're asking my opinion here for?

**Comment by serundeputy** [comment] 2015-08-02 22:17
@klonos the UX for adding a link field to an entity;

you can see/test that with either the cintrib module link our the PR here in #240

**Comment by klonos** [comment] 2015-08-02 22:49
Right, I will test as soon as I find why I cannot install Backdrop in my local environment.

**Comment by quicksketch** [comment] 2015-08-03 04:05
I think we should focus on fixing the tests, resolving the known issues
(especially that unable to save the link field if required), and ensuring
an upgrade from D7 and Backdrop 1.1 work. After that, regardless UI
improvements that *could* be made, let's put it in. Of course, if the
improvements are there beforehand, alls the better.

**Comment by serundeputy** [comment] 2015-08-06 23:07
Added fieldset for `Advanced Options` and some `#states` to only show fields when corresponding option is checked for use.  https://github.com/serundeputy/backdrop/commit/e9419d62b0d2938fe50594bb953f025a48642c2d

**Comment by quicksketch** [comment] 2015-08-15 01:56
Are the latest changes all in https://github.com/backdrop/backdrop/pull/1007? I'd like to give this another review this weekend.

**Comment by quicksketch** [comment] 2015-08-15 06:01
I'm working on cleaning up the current PR. There are a few Link-issues that I'm running across in testing that I'd like to get sorted out as well, e.g. https://www.drupal.org/node/2299657.

**Comment by serundeputy** [comment] 2015-08-17 13:07
sorry i was in the :ocean: , looks like you tested it though; yes this PR (backdrop/backdrop#1007) has the latest and greatest.

thanks!

**Comment by docwilmot** [comment] 2015-08-17 14:57
@quicksketch, incidentally, [this closed commit](https://github.com/docwilmot/backdrop/commit/b9e8bc015846ed2ba7fcb09fb23577062c39a039) was mainly for a persistent `field_XXXXX  not found` test fail (see line 301, replacing `_field_info_collate_fields(TRUE);` with `backdrop_static_reset();`, just so you dont waste as much time as I did trying to track it down. 

Although I suspect this wouldnt be difficult for you. :wink:

**Comment by quicksketch** [comment] 2015-08-26 06:00
Filed a new PR based on @serundeputy's work at https://github.com/backdrop/backdrop/pull/1026. Lots of updating, as this still had a lot of cleanup to do from the D7 version (and the D6 version for that matter):

- Removed D7 Entity module hook implementations.
- Removed abandoned Views integration (never fully ported in D7 from D6).
- Drastically simplified and optimized the tests. Link had been installing Backdrop once per URL checked, and 40-some URLs checked. This made for a really, really slow test suite. Now much faster using a single install for similar tests.
- Removed domain name checking entirely as it didn't work with the exploding array of new TLDs. I've been encouraging the same approach for the Drupal module over in https://www.drupal.org/node/2299657.
- Added ability to validate domains that contain UTF-8 characters.
- Removed the "Absolute URL" option, which supposedly "Makes links always display as absolute URLs", but it only affected the `href` property, not the actual display. I'm pretty sure removing this odd option is the right move. I would like to see options to limit URLs to only relative or absolute links, which seems like what I would have expected this option to do.
- Moved all theme functions to `link.theme.inc` to match our other modules.

**Comment by quicksketch** [comment] 2015-08-26 06:41
Woo! We're passing all tests now. Very exciting. :smile: Although I'm feeling pretty good about things, @serundeputy it would be great if you could give this another look as you've been instrumental in the work here. I wonder if @juanolalla might be able to take a look too, as he ported the module originally from D7. :wink;

**Comment by serundeputy** [comment] 2015-08-26 23:14
Wooot;
thanks @quicksketch 
I pulled down your branch today.
  * All tests pass locally; :fireworks: 
  * I added a content type with a link field
    * added instances of said content type and everything is working as I expect it to
  * I did not check every permutation of possible settings, but things are looking good from my perspective :+1: 

very exciting indeed;
~Geoff

**Comment by jenlampton** [comment] 2015-08-28 08:11
I've also added this patch to my client site. So far working like a charm with two fields on two content types, slightly different configurations.

**Comment by juanolalla** [comment] 2015-08-28 13:18
@quicksketch It wasn't me who ported this module, I think it was @herbdool. I ported email :wink: 

Sorry I can not help right now with that anyway. You're doing an amazing work, congrats!

**Comment by herbdool** [comment] 2015-08-28 14:52
Yup, I ported it originally. I was going to help get it into Backdrop core, but got stuck with confusing test suite and wasn't sure best direction for Backdropizing them. Plus! I've just been neck-deep into CiviCRM issues recently. So @quicksketch improvements sound on target -- there were some weird things in the module such as checking the TLDs.

Hopefully I can give it a go next week.

**Comment by quicksketch** [comment] 2015-08-28 23:51
Doh! Sorry for the confusion!

Yeah the test suite was a mess in this module. It's still not great, but its now using proper UnitTests for URL validation and a lot of duplicate code has been consolidated into fewer tests.

It's sort of nostalgic working back on this module. Fun trivia fact: Lullabot contracted me to write Link module as my first ever stand-alone module back in 2006! That was for CCK in Drupal 4.7. I handed the module off to John Fiala around the time that Drupal 6 was released.

The only thing I'd like to see changed at this point is the "optional" treatment of the protocol. Traditionally, you've been able to omit the "http://" from absolute URLs. e.g. "www.google.com" would be considered an absolute URL and be displayed as `http://www.google.com`. The trouble with this is that now that there are so many TLDs, it's possible that we'll end up with an overlap between file extensions and TLDs. For example, there could be a TLD for "rss" or "php" (the `.js` domain is actually a [real attempt](https://github.com/ozten/TLD.js/issues/8)). A relative URL such as "index.php" will currently be interpreted as an absolute URL, i.e. http://index.php/ We should remove the ability for the protocol to be optional IMO, as the current guessing is now unreliable.

**Comment by herbdool** [comment] 2015-08-29 17:48
ha! Part of the confusion is that I was trying to learn how to write proper tests at the same time so wasn't clear to me the best route.

Might be worth submitting an issue on the optional option to get that done at some point. Though that would break the upgrade path for some I suppose unless http:// is inserted in .install which is a bit intrusive for someone's content.

**Comment by quicksketch** [comment] 2015-09-07 03:20
I took at look at this again today and tried to remove the protocol assumption, but decided it would be too much effort (and change) for our release date. I think this is good enough for our initial inclusion. Unless there are any reasons to hold off, I would like to merge this ASAP so we could move onto the Date issue #1063.

**Comment by serundeputy** [comment] 2015-09-07 13:38
I have no objection.  Should I put in a message like:
`system.install`
````
function system_update_1040() {
  $path = backdrop_get_path('module', 'ckeditor');
  if ($path && strpos($path, 'core/modules/ckeditor') === FALSE) {
    backdrop_set_message(t('Backdrop core now provides a bundled CKEditor module. A different copy of CKEditor module has been located at %path. To use the new CKEditor module, disable and then uninstall the current module, remove it from your installation, and then enable the new CKEditor module from the modules page. For more information see the <a href="https://api.backdropcms.org/node/42827">CKEditor change notice</a>.', array('%path' => BACKDROP_ROOT . '/' . $path)), 'warning');
  }
}
```
?

**Comment by serundeputy** [comment] 2015-09-07 14:32
@quicksketch 
I put in a `PR` with the update notice in case it is desired:
https://github.com/quicksketch/backdrop/pull/2

<img width="840" alt="screen shot 2015-09-07 at 10 25 37 am" src="https://cloud.githubusercontent.com/assets/6763671/9718647/9833a30e-554b-11e5-954b-93b087a1a6ac.png">

I tested this on a fresh backdrop-1.1.3 + contrib/link 
of course the more testing we can get the better.
thanks,
~Geoff

**Comment by quicksketch** [comment] 2015-09-08 00:14
Oh of course; We should add message just like we've done for ckeditor and email. Let's merge email in first so our update numbers can get unconflicted, as they both need to be in system.install.

**Comment by serundeputy** [comment] 2015-09-08 01:09
sounds great!  :gem:

**Comment by quicksketch** [comment] 2015-09-08 03:22
Change notice for Link: https://api.backdropcms.org/node/42930

PR updated with @serundeputy's update hook and now links to the new change notice. I also added the same warning to `system_requirements()` as we did for Email. Let's see if it passes all tests.

**Comment by serundeputy** [comment] 2015-09-09 23:03
it passes! woooot; she passes the tests!
https://github.com/backdrop/backdrop/pull/1026
:evergreen_tree: wooot;

**Comment by quicksketch** [comment] 2015-09-10 03:12
Great, I think we're in a really great place here. I've tested this one up and down and given it 2 full code reviews. I think we're ready to merge here.

**Comment by quicksketch** [comment] 2015-09-10 03:13
Merged in https://github.com/backdrop/backdrop/pull/1026. Let's make new issues for any followups.

**Closed** 2015-09-10 03:13 UTC
Labels: pr - needs review, status - has pull request, type - feature request
