### ISSUE TITLE
Error: Call to undefined function tablesort_cell() in theme_table() (line 2219 

### ISSUE THREAD

**Issue by AlexL777** [backdrop/backdrop-issues#3089] opened 2018-05-07 18:14 UTC
This error message appears in the new Backdrop 1.9.5 version when updating under `/core/update.php`. How can you fix it? That came suddenly after the update to the last version.

Here is the error message.

`Error: Call to undefined function tablesort_cell() in theme_table() (line 2219 of /xxxxxxxxxxxxxxxxxxxxx/backdrop.cms-blogger.eu/core/includes/theme.inc).`

Thanks in advance.

**Comment by laryn** [comment] 2018-08-20 21:50
I'm going to close as a duplicate of https://github.com/backdrop/backdrop-issues/issues/3167

(Correct me if I'm wrong)

**Closed by laryn** 2018-08-20 21:50 UTC

**Comment by klonos** [comment] 2018-10-21 08:46
https://github.com/sindresorhus/refined-github is an open-source browser extension that shows you possible duplicate tickets:

![screen shot 2018-10-21 at 7 45 28 pm](https://user-images.githubusercontent.com/2423362/47264839-f2683c80-d569-11e8-9775-6fbfb97be6d5.png)
