### ISSUE TITLE
"Correct faulty and chopped off HTML" filter sometimes removes tags as a "correction"

### ISSUE THREAD

**Issue by pnmgman2** [backdrop/backdrop-issues#2869] opened 2017-10-02 18:18 UTC
Using some HTML tags outside `<p></p>` tags in content with the "Correct faulty and chopped off HTML" filter enabled results in unanticipated outcome.

**Steps to reproduce:**
1) Create a new content type and set Body section to "Full HTML". 
2) Enter a title and some text in the Body section like so...
```
<s>
  <p>Now is the time for all good men to come to the aid of their country..."</p> 
  <p>Now is the time for all good men to come to the ... second paragraph</p>
</s>
```
3) Save

**Expected result:** The following should create two paragraphs with strike-through text:
```
<p><s>Now is the time for all good men to come to the aid of their country..."</s></p> 
<p><s>Now is the time for all good men to come to the ... second paragraph</s></p>
```

**Actual result:** The S tag is removed:
```
<p>Now is the time for all good men to come to the aid of their country..."</p> 
<p>Now is the time for all good men to come to the ... second paragraph</p>
```

To make matters more confusing, without the "Correct faulty and chopped off HTML" filter enabled, the "incorrect" markup (with the S tags outside the P tags) is rendered correctly by most browsers.

Version 1.8.0 (LAMP, Ubuntu 14.04.1)

**Comment by jenlampton** [comment] 2017-10-02 20:02
Thanks for reporting this issue @pnmgman2.  I've taken a stab at updating the issue to make the steps to reproduce clearer, along with the expected and actual results. Please give it a read-over, and feel free to fix it if I've gotten anything wrong!

Since the `<strike>` and `<s>` tags were depercated in 1999, I wonder if this same thing would happen with the modern equivalent, `<del>`.

I've checked the code for the "Correct faulty and chopped off HTML" filter, and it looks like we are using [PHP's built-in DOM Object](https://api.backdropcms.org/api/backdrop/core%21modules%21filter%21filter.module/function/filter_dom_load/1) for these corrections: `The partial (X)HTML snippet to load. Invalid mark-up will be corrected on import.`

I wonder if that means we'd need to file a fix for this upstream?

**Comment by pnmgman2** [comment] 2017-10-02 22:15
Your changes are accurate - thanks for the wordsmithing, Jen. Also, I can confirm the same results occurred for us using `<del>` and `<strike>,` just as you have outlined.

**Comment by BWPanda** [comment] 2022-05-28 08:22
Yeah, the PHP code is what controls this. Considering no further activity since 2017, I'm marking this "works as designed".

**Closed by BWPanda** 2022-05-28 08:22 UTC
Labels: type - bug report
