### ISSUE TITLE
[D8][UX] Multi-value field items should offer some way for individual values to be removed

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2917] opened 2017-12-08 01:06 UTC
This is one of the many, tiny things that has been annoying me in the Drupal (and thus inherently Backdrop) UI for years:

>When working on a new Drupal 7 site I noticed a feature from the old D6 CCK days that allows you to remove a single item from a field that has unlimited values. Unfortunately, this is not built into Drupal 7's fields ... In a D7 unlimited field, you 'delete' an item by emptying all of its values and saving the form. This works fine in practice but is highly unintuitive for a standard Drupal user (ie: clients) ...

<img width="722" alt="screen shot 2017-12-08 at 2 33 12 am" src="https://user-images.githubusercontent.com/2423362/33745782-955336a0-dbc1-11e7-9097-5405482afea7.png">

There are currently two modules that address this issue:

[Multiple Fields Remove Button](https://www.drupal.org/project/multiple_fields_remove_button):

<img width="717" alt="screen shot 2017-12-08 at 2 41 12 am" src="https://user-images.githubusercontent.com/2423362/33745787-9adcbf38-dbc1-11e7-973e-bab60ed01321.png">

[Field Remove Item](https://www.drupal.org/project/field_remove_item):

<img width="718" alt="screen shot 2017-12-08 at 2 55 42 am" src="https://user-images.githubusercontent.com/2423362/33746065-5305d756-dbc3-11e7-8882-42d766942c97.png">

Both of these modules work the same, in that once the user clicks on either the button or the checkbox, the entry is removed in an AJAXy way. This action removes the item only from the form; there is no actual removal unless the user saves the form. I think that in our implementation, entries should be "marked" for removal, but still remain visible on the form, giving the user the option to change their mind and undo. Perhaps a list of checkboxes in a "remove" column would be more similar to other places in our UI, and thus a familiar UI pattern for the end user.

**Comment by klonos** [comment] 2017-12-08 01:09
There's also a ticket for including this functionality in D8.5 core: https://www.drupal.org/project/drupal/issues/1038316

...last comment there (a few days ago) is talking about using AJAX vs checkboxes too.

I would like to know what people think with regards to what would be the best solution UX-wise. I'm obviously voting for the checkbox, non-AJAX way, because I think that it would be the less complicated and less bug-prone one, plus it would be more straight forward to the user as to what is happening (compared to the removed-from-the-form-changes-not-actually-saved approach that is).

**Comment by klonos** [comment] 2017-12-08 02:39
...added this issue to the list in #378

**Comment by Graham-72** [comment] 2017-12-08 16:46
We seem to already have remove buttons for multi-value image fields. How do these work?

**Comment by klonos** [comment] 2018-04-22 23:00
...good catch @Graham-72 👍I have tested this with a link field:

<img width="1180" alt="screen shot 2018-04-23 at 8 57 55 am" src="https://user-images.githubusercontent.com/2423362/39100882-954d8a42-46d4-11e8-9bbe-03d9956eb13e.png">

We should adapt/abstract the code used in the image multi-value field, so to work with all multi-value fields.

**Comment by klonos** [comment] 2018-04-22 23:01
...I am classifying this as a UX bug.

**Comment by jenlampton** [comment] 2019-04-28 02:05
I use the Multiple Fields Remove Button module often, +1 for this idea from me.

**Comment by jenlampton** [comment] 2023-05-02 20:04
This looks like a duplicate of https://github.com/backdrop/backdrop-issues/issues/314

**Closed** 2023-05-02 20:05 UTC
Labels: type - bug report, needs - more feedback
