### ISSUE TITLE
PHP 7.4: Notice: Trying to access array offset on value of type <int, null>

### ISSUE THREAD

**Issue by hosef** [backdrop/backdrop-issues#4308] opened 2020-02-11 13:38 UTC
**Description of the bug**
There are a few places where we check the first character of a string or int using the array access syntax. As of PHP 7.4 this now gives an error notice. We should convert each of these to use substr() for checking the string.

**Steps To Reproduce**
To reproduce the behavior:
1. Upgrade to PHP 7.4
2. Try to use anything with AJAX or submit a form

---
PR by @hosef: https://github.com/backdrop/backdrop/pull/3079

**Comment by indigoxela** [comment] 2020-02-11 13:49
@hosef good reminder. We forgot to create the follow-up issue for #4263

For instance element_children() in common.inc is one of those functions. Did you find additional places?

**Comment by hosef** [comment] 2020-02-11 15:00
Yes, I've been running tests on my laptop which is running PHP 7.4 and fixing things as they fail. There are going to be a lot of changes in the PR

**Comment by indigoxela** [comment] 2020-02-11 15:22
One remark to the issue title: it's OK in PHP7.4 to access `strings` with array offset, only int/null are causing notices.

The problem is that Backdrop functions sometimes get integer/null and handle it like strings. Maybe the changes are smaller if you're able to sort out functions that _reliably_ get strings, or if you can cast some of those params. Not sure, what you prefer.

**Comment by hosef** [comment] 2020-02-11 15:51
Ahh, yes. You are correct about that.

I am evaluating each instance as I come across them, because of Backdrop's handling of cases where it allows array keys to be either strings or ints and cases where it does different things based on the type of the variable passed in.

**Comment by hosef** [comment] 2020-04-27 19:31
I believe that I have this complete. I was able to run the full test suite on PHP 7.4 with no exceptions being thrown.

**Comment by indigoxela** [comment] 2020-04-28 10:16
Hm... I get 4 fails and 3 exceptions. (Didn't run _all_ core tests, though)

I tested with apache 2.4 and php 7.4.5 on a virtual machine.

```
File upload wizard
Upload a file using the multi-step wizard.
210 passes, 0 fails, 3 exceptions, and 76 debug messages.
					
EXCEPTION: Trying to access array offset on value of type null	file.module	3392
```

```
Page cache test
Enable the page cache and test it with various HTTP requests.
150 passes, 4 fails, 0 exceptions, and 41 debug messages.

FAIL: Conditional request without If-None-Match returned 200 OK. bootstrap.test	142
FAIL: Page was cached. bootstrap.test	143
FAIL: Conditional request with new a If-Modified-Since date newer than Last-Modified returned 200 OK. bootstrap.test	146
FAIL: Page was cached. bootstrap.test	147
```

Before the test runs I logged in and clicked around, added a node, added a menu item, that all looked good. Nothing in dblog when doing trivial stuff on the site, so we really have progress here.

**Comment by hosef** [comment] 2020-04-29 18:05
Hmm, not sure how I missed that file test.
I think I have fixed it by changing the tests so they create default displays for custom file types now.

As far as the page cache tests, I think that is a random failure because it is checking that something is in the cache before it actually makes it into the cache.

**Comment by indigoxela** [comment] 2020-04-30 06:32
> I think I have fixed it by changing the tests so they create default displays for custom file types now.

Confirmed. With the latest commit FileUploadWizardTestCase passes on php 7.4.5.

Regarding the bootstrap test.... The backdropGet seems to get a _304 Not Modified_. Wouldn't that mean it should actually pass? In other words: isn't it wrong to expect a 200 there?

Maybe the test needs a closer look.
Funny that the test also failed with php7.0 on the latest zenci test run.

**Comment by indigoxela** [comment] 2020-04-30 07:04
Some digging and comparing:

On the same VM (same apache 2.4.25 and curl 7.52.1, different Backdrop install) with a different php version 7.2.30 and _without_ the changes from this PR this test fails too for me.
So the fact that this test fails seems unrelated to php 7.4 and your PR.

Out of curiosity I let the same bootstrap test run on a different server (apache 2.4.38, php 7.2.30, curl 7.64.0). And that install is a stable Backdrop 1.15.1.
On that server I get 136 passes, 20 fails, 0 exceptions. So even more checks fail.

**Comment by hosef** [comment] 2020-04-30 14:05
Yeah, those tests also gave me quite a bit of trouble when I was working on #4306. Backdrop was changed so that it sets the page cache after the page is returned, so if you want to test it, you have to wait after getting the page the first time. Annoyingly, any time we make Backdrop or Simpletest faster, it makes those tests fail more often. That test already has 50 seconds worth of sleep calls, and it seems like the only thing we can do to those tests is just make them sleep longer, unless we figure out some way to make saving of page cache data faster.

**Comment by indigoxela** [comment] 2020-04-30 14:09
> Annoyingly, any time we make Backdrop or Simpletest faster, it makes those tests fail more often.

Maybe a new issue for that?

The changes work fine, so "works for me".

**Comment by quicksketch** [comment] 2020-05-14 02:32
I code reviewed https://github.com/backdrop/backdrop/pull/3079 and found a number of small issues. @hosef could you take a look?

**Comment by docwilmot** [comment] 2020-05-15 16:28
So our tests currently run on PHP 7.0, and this is for 7.4. Am I to assume that everything between 7.0 and 7.4 will be supported after this PR?

**Comment by hosef** [comment] 2020-05-15 16:30
@quicksketch I made the changes that you requested.

@docwilmot Yes, that should be correct. I have been testing this on my laptop which is running PHP 7.4.

**Comment by quicksketch** [comment] 2020-05-15 19:15
Thanksk @hosef for updating the PR! I re-reviewed and it looks great. I also tried out most of the things that weren't obvious if there was any change in functionality, such as creating a taxonomy, uploading a profile picture, and rearranging views displays. Everything both worked and saved correctly, same as before.

I've merged into 1.x and 1.15.x, so this will be in 1.15.2 and 1.16.0.

**Closed by quicksketch** 2020-05-15 19:15 UTC
Labels: status - has pull request, status - fixed
