### ISSUE TITLE
Long time website upload / server response

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1137] opened 2015-09-01 08:52 UTC
Hi!

My site is very small (about 35 pages + 20 photos).
It has only Webform, CKEditor and Custom Meta as additional modules.

However the website upload time is extremely long — 3000-6000 ms for the first connection.
Then, for the second and next connections — it is enough good, about 300 ms.

My first idea was — it is my hoster's fault and/or the problem with the server.
But my hosting support told me that they are not to blame — all other websites located on this sever are working fast.

Please, may be somebody could indicate me what the problem is and how it might be solved?

Thank you!

**Comment by Graham-72** [comment] 2015-09-01 09:29
Hi @bd0bd 
Have you used a tool like the network monitor facility in Chrome's developer tools to see how the time is being spent? Which files are taking longer to arrive? There is usually quite a time for the first file to arrive from Backdrop and hence the need for setting cacheing in admin performance once production-ready.

**Comment by bd0bd** [comment] 2015-09-01 15:46
May be I am wrong but the upload/arrive time is normal, it is not a problem how I can understand.
The problem is a long time - 3000-6000 ms - it is waiting before the site begins (starts) to upload/arrive.

**Comment by quicksketch** [comment] 2015-09-01 22:02
Hi @bd0bd, that's certainly not expected behavior. Even after restarting my entire server and loading a logged-in page, the response time is very fast (<100ms) on my test site (though on a dedicated machine). I would suggest trying the following:

- Download the Devel module: https://backdropcms.org/project/devel
- Enable the module and visit the settings page for it `admin/config/development/devel`
- Turn on the "Display page timer" option (also make sure your account has "access devel information" permission).
- Now at the bottom of pages, it will report how long it took Backdrop to generate the individual page.

Wait a while and try one of your first-time requests. If the timer at the bottom of the page indicates that the page took 3000+ms, then the problem in first-time requests is likely in Backdrop's code. If the generation time is still small but the request takes a long time anyway, it's an issue on the host server software. It's also possible some issues are server-related that may be issues on a shared host, such as the PHP cache or filesystem cache being filled by other users on the same server.

Also, if you haven't done so already, be sure to turn on the anonymous page cache under admin/config/development/performance.

**Comment by bd0bd** [comment] 2015-09-02 15:56
Hi **quicksketch**, thank you!
I will install the site on another server and will test it too.
I know about the anonymous page cache option but I am avoiding to use it at the time I am building the site.

Hm, the results are shown twice at the same time, do not understand - why?
And it is shifted to the main body of the page.
I use Bartik with very minor changes and Seven 1.1.3 for admin panel.

![dev_1](https://cloud.githubusercontent.com/assets/13515302/9636272/3cbf8ed0-51a3-11e5-8c20-33fca35af1f4.gif)

![dev_2](https://cloud.githubusercontent.com/assets/13515302/9636280/4389ec56-51a3-11e5-986b-759b40af0021.gif)

![dev_3](https://cloud.githubusercontent.com/assets/13515302/9636288/49635c66-51a3-11e5-822c-b16af6b28035.gif)

**Comment by quicksketch** [comment] 2015-09-02 18:22
Hi @bd0bd, thanks this is useful information. So why you're seeing the number twice is because the admin bar is loaded via an AJAX request. If the page timer is on when generating the admin menu, the timer gets stuck on the admin bar as well. :stuck_out_tongue: 

So the first number here is the actual page (6755.44 ms) the second number is the time it took to generate the admin bar (730ms). The admin bar gets cached after the first request per-user.

It looks like indeed Backdrop is taking a long time to load then. This could still be server-related due to a lack of an op-code cache (e.g. APC or the PHP 5.5+ opcache), but it's likely that there is some expensive Backdrop-related process that is occurring on first-time requests.

So... solving the problem at this point gets a little trickier. The *best* way to figure out this problem is to get XHProf running on that server, then enabling the XHProf statistics in Devel module. This puts a link at the bottom of the page that gives you in-depth information about PHP's building of the page.
However, getting XHProf on your production server may not be possible. Instead, this could be done on your localhost installation, if you have one.

Easier but less-reliable ways of fixing this:

- Enable the SQL query log in Devel module and have it display at the bottom of the page. Similar to the page timer, this may cause some display issues but the information will all be there. Look for either SQL queries that are executing a bunch of times or a query that is running for a long time.

- Try disabling contrib modules until the problem seems to go away, then turning them back on one at a time.

Considering the nature of this problem disabling modules may not be very practical. The XHProf approach is most reliable but the most difficult to set up. I'd start with the SQL query log first and then we could try XHProf if that's possible.

**Comment by bd0bd** [comment] 2015-09-02 18:38
Thank you very much!
I will try it and report about the results tomorrow.

**Comment by bd0bd** [comment] 2015-09-03 17:47
Can not install a copy of the site on another server.
Please may be somebody could link me to the instructions how to do it?
I have uploaded all the files to the server (including "files" folder), created a mysql database and imported the database copy in there.
Thank you!

**Comment by MrHaroldA** [comment] 2015-09-03 20:42
> Solved!

You got it running, or running fast?

**Comment by bd0bd** [comment] 2015-09-03 21:03
I got it (the site) running on the new server.
But I will test it (with a help of the Devil module) a little bit later. Right now it is a night here. I need to test when the server is hard loaded with other websites located on the server - on a working day.

**Comment by bd0bd** [comment] 2015-09-04 11:28
The server is main reason.
The site is running (both - first-time and next requests) faster on another server (picture below - server # 2).
But I did not conduct a deep research described by **quicksketch** above (XHProf etc).
I have only tested it by the Devel modul:

First-time request, server # 1 (slow)
![slow_running](https://cloud.githubusercontent.com/assets/13515302/9682575/91fb3322-5310-11e5-842e-55d2e6bbe4a2.gif)

First-time request, server # 2 (fast)
![fast_running](https://cloud.githubusercontent.com/assets/13515302/9682580/9acdb83a-5310-11e5-9119-ffb699f8a354.gif)

**Comment by quicksketch** [comment] 2015-09-17 02:15
Another possible cause of first-time slowness may be the lack of a Cron job being set up to run regularly. If you haven't, try setting up cron to run and hit /core/cron.php every 5 minutes.

We may be able to fix this even if you're using the fallback cron over in https://github.com/backdrop/backdrop-issues/issues/1214.

**Comment by klonos** [comment] 2020-02-24 18:01
I will go ahead and close this one as outdated. Please feel free to either reopen, or file separate issues.

**Closed by klonos** 2020-02-24 18:01 UTC
