### ISSUE TITLE
Backdrop installer refers to profiles as "module"

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2015] opened 2016-07-13 07:21 UTC
One can only notice this in really slow machines because this is at the very last step of the installer and it usually takes a split second before it moves on to the "success" page:

![backdrop-standard_module_installed](https://cloud.githubusercontent.com/assets/2423362/16172192/5bf8944c-35c6-11e6-938e-2274dd184ece.png)

There's no Standard _module_ AFAIK. Only the Standard _profile_. Right?

**Comment by klonos** [comment] 2016-07-14 06:07
...I just saw this happen on a D7 installation, so it's not something new in Backdrop.

**Comment by BWPanda** [comment] 2019-11-07 17:07
Yes, install profiles are seen as modules in some ways I believe. Definitely no 'standard' module.

Going to close this question as answered, but feel free to reopen if there's anything more to this (like a feature request, etc.)

**Comment by klonos** [comment] 2019-11-07 22:57
Yeah, let's fix this so that things being enabled/installed are referred to as what they actually are.

**Comment by stpaultim** [comment] 2021-01-04 05:18
Closing this as duplicate of https://github.com/backdrop/backdrop-issues/issues/3796

**Closed by stpaultim** 2021-01-04 05:18 UTC
Labels: good first issue, type - bug report
