### ISSUE TITLE
Field labels showing even when there is no content

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4473] opened 2020-07-08 04:10 UTC
**Description of the bug**

I could have sworn there was an issue for this already (and that we fixed it in a recent release?) but I couldn't find one, open or closed. So here goes:

On Backdrop 1.16.2 field labels are displaying on nodes even when there is no value in the field.

So far I've noticed this happening for link fields, reference fields, and multifields. STR here are for Link since that is a core module.

I checked inside `theme_field()` and it looks like most of the render array is complete, even when the field values are empty, so the rendering continues even though there is no output. I don't remember what changed in Backdrop, but Field labels are properly hidden in Drupal 7. Maybe we need to revert back to handling them the same way?

**Steps To Reproduce**

To reproduce the behavior:
1. Add a link field to a content type
2. Set the label display to "inline"
3. Create a node of that type, leaving the link field empty
4. View the completed page, see the label

**Actual behavior**

Label displays :(

**Expected behavior**

Label should not display

**Comment by jenlampton** [comment] 2020-07-08 04:17
Here's the work-around I used for my site, though I'm not sure we want to change `theme_field()` in core. I think the problem is somewhere deeper in the render array, and would prefer to fix it there.

```php
/**
 * Overrides theme_field().
 * @see theme_field().
 */
function HOOK_field($variables) {
  $output = '';

  // Render all the items.
  foreach ($variables['items'] as $delta => $item) {
    $rendered_item = backdrop_render($item);
    if (!empty($rendered_item)) {
      $classes = 'field-item ' . ($delta % 2 ? 'odd' : 'even');
      $item_attributes = (isset($variables['item_attributes'][$delta])) ? backdrop_attributes($variables['item_attributes'][$delta]) : '';
      $output .= '<div class="' . $classes . '"' . $item_attributes . '>' . $rendered_item . '</div>';
    }
  }

  // Only if there  is output, add a wrapper div and a label.
  if (!empty($output)) {
    $wrapped_output = '';

    // Render the label, if it's not hidden.
    if (!$variables['label_hidden']) {
      $wrapped_output .= '<div class="field-label">' . $variables['label'] . ':&nbsp;</div>';
    }

    $content_attributes = (isset($variables['content_attributes'])) ? backdrop_attributes($variables['content_attributes']) : '';
    $wrapped_output .= '<div class="field-items"' . $content_attributes . '>';
    $wrapped_output .= $output;
    $wrapped_output .= '</div>';

    // Render the top-level DIV.
    return '<div class="' . implode(' ', $variables['classes']) . '"' . backdrop_attributes($variables['attributes']) . '>' . $output . '</div>';
  }
}
```

**Comment by indigoxela** [comment] 2020-07-08 06:43
> On Backdrop 1.16.2 field labels are displaying on nodes even when there is no value in the field.

I can't reproduce that on 1.16.2. Not with image, nor text/longtext nor taxonomy term reference. And I can't remember to ever having trouble with it in the previous versions.

@jenlampton Do you see field labels for empty fields on all or just a single of your sites? If there are several - what do they have in common? Could it be an interfering contrib module?

Are really all field types affected on your site(s)? If not - which one are?

**Comment by jenlampton** [comment] 2020-07-08 22:18
> I can't reproduce that on 1.16.2.

Hm, I just followed my STR on a fresh backdrop install, and was also unable to reproduce.

> @jenlampton Do you see field labels for empty fields on all or just a single of your sites?

I saw it on one site yesterday, but I'll check the others. I remember seeing visible field labels before one of the recent updates, but after the update thinking it was fixed. I wonder if that was the same site?

> Could it be an interfering contrib module?

I did have a custom override of `theme_field()` on this site, but I checked it against core and it looked nearly identical (except for my special handling to remove the field-items div when there is only a single item). I'll check the contrib modules and see if there's anything else that could affect fields.

> Are really all field types affected on your site(s)? If not - which one are?

From my original post:

> So far I've noticed this happening for link fields, reference fields, and multifields...

I'm going to add the cannot reproduce label until I can confirm this is happening on more than one site, and I can get some STR that will work on a clean backdrop install.

**Comment by quicksketch** [comment] 2020-07-09 19:50
Issues possibly related to this one:

#3873: Numeric fields throw fatal error when left blank - Fixed in 1.14.3
#4319: Empty large text fields are rendering markup - Fixed in 1.15.3

**Comment by jenlampton** [comment] 2020-07-10 02:53
Oh and this one: https://github.com/backdrop/backdrop-issues/issues/4152 Field label is sometimes displayed even when field is empty (for some fields including: Text)

**Comment by jenlampton** [comment] 2020-07-10 03:08
Actually, I'm pretty sure this issue is a duplicate of that one. I'm going to close this in favor of that one.

**Closed** 2020-07-11 01:48 UTC
Labels: status - duplicate
