### ISSUE TITLE
'Template' links on Layouts overview page are incorrect

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#2308] opened 2016-10-28 05:10 UTC
The 'Template' links on the Layouts overview page are incorrect and lead to a 'Page not found'. See below screenshots for the wrong link URL and what it should be instead.

![layout_template_link_wrong](https://cloud.githubusercontent.com/assets/2385329/19795612/e32faad0-9d28-11e6-8397-a8615f28bdd4.jpg)

![layout_template_link_right](https://cloud.githubusercontent.com/assets/2385329/19795615/e8e9044e-9d28-11e6-9a58-33af2caccfbc.jpg)

**Comment by klonos** [comment] 2016-10-28 08:41
@BWPanda I believe that this is a duplicate of #2298

**Comment by BWPanda** [comment] 2016-10-29 06:48
@klonos Indeed. Sorry about that. I did search for existing issues, but missed that somehow...

**Closed by BWPanda** 2016-10-29 06:48 UTC
Labels: status - duplicate

**Comment by klonos** [comment] 2016-10-29 09:54
No worries @BWPanda we can't follow and remember every single issue. That's what people like me are around for: helping triage the queue 😉

**Comment by BWPanda** [comment] 2016-10-29 10:54
@klonos And you're doing a great job! Thank you for your efforts! :+1:
