### ISSUE TITLE
Fixed: Update hook in 1.22.1 mistakenly recommends removing entity reference.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5694] opened 2022-07-21 20:10 UTC
## Description of the bug

There was a problem resolving a merge conflict that got into yesterday's release. The result is hat an update hook intened for 1.23.0 was accidentally included in 1.22.1. 

## Steps To Reproduce

To reproduce the behavior:
1. Install entity reference on 1.22.0
2. Update to 1.22.1
3. Run update.php, see mistaken recommendation.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.22.1

**Comment by jenlampton** [comment] 2022-07-21 20:14
I have a PR for the 1.22.2 release ready, here: 
* https://github.com/backdrop/backdrop/pull/4143

**Comment by jenlampton** [comment] 2022-07-21 20:31
I have a PR for the 1.23.0 release (this one includes the previous commit) https://github.com/backdrop/backdrop/pull/4144

**Comment by argiepiano** [comment] 2022-07-21 20:58
@jenlampton I don't know if you created your PR for 1.22.2 from an old version of Backdrop, but there are 587 files changed (?)

I'm referring to this PR:
https://github.com/backdrop/backdrop/pull/4143

**Comment by herbdool** [comment] 2022-07-21 21:11
It seems like https://github.com/backdrop/backdrop/pull/4144 removes and adds the deprecated message back, just in a different hook. Shouldn't it be only removed?

**Comment by jenlampton** [comment] 2022-07-21 21:39
@herbdool  we will need the message for 1.23.0.

**Comment by herbdool** [comment] 2022-07-21 21:47
I understand now. It's against the 1.x branch so I've changed the milestone to 1.23.0. Makes it clearer to me at least even if it gets merged soon.

Then we'll still need a second PR against the 1.22.x branch that only removes the hook.

**Comment by jenlampton** [comment] 2022-07-21 21:49
@herbdool  we need the [first PR](https://github.com/backdrop/backdrop/pull/4143) for today's release (1.22.2) but we can change the milestone after that one gets merged, for the [second PR](https://github.com/backdrop/backdrop/pull/4144).

**Comment by herbdool** [comment] 2022-07-21 21:57
The first pr looks fine https://github.com/backdrop/backdrop/pull/4143

**Comment by herbdool** [comment] 2022-07-21 21:59
I take that back. It likes it's on the 1.x branch but should be on the 1.22.x branch.

**Comment by jenlampton** [comment] 2022-07-21 22:02
> @argiepiano I tried to make that PR against the 1.22.x branch, but I don't think that's helpful. so, back to 1.x :)

Doh, okay I'll try that again.

**Comment by jenlampton** [comment] 2022-07-21 22:11
no dice, ignore that I'll try a #3.

**Comment by jenlampton** [comment] 2022-07-21 22:15
there we go!  The first PR is ready for review again, and properly against the 1.22.x branch this time :D 
I've also updated all the links above to the "first PR" to avoid any confusion.

**Comment by argiepiano** [comment] 2022-07-21 22:26
Strange. The fixed password reset flood control tests are failing in the 1.22.x patch https://github.com/backdrop/backdrop/pull/4146

I don't have time to look into this, but this doesn't look like a random failure. It failed on all 3 php versions

**Comment by argiepiano** [comment] 2022-07-21 22:39
OK, a quick look at the failing tests.

The problem is text incompatibility of two PRs that were merged into 1.22.x. 

- https://github.com/backdrop/backdrop-issues/issues/5659   (merged into 1.22.x)
- https://github.com/backdrop/backdrop-issues/issues/4521    (not merged into 1.22.x, but 1.x)

The second one changed "e-mail" to "email" everywhere. The problem is that the first issue used "email", making the test fail.

**Comment by quicksketch** [comment] 2022-07-21 23:09
I merged the PR for the 1.x branch: https://github.com/backdrop/backdrop/pull/4144

I made a small change to the code comments to clarify where the update hook got moved to (using the new function name, rather than saying the 1.23.0 version).

I'll take a look at updating @jenlampton's 1.22.x PR (https://github.com/backdrop/backdrop/pull/4146) to fix the failing test.

**Comment by quicksketch** [comment] 2022-07-21 23:30
I merged https://github.com/backdrop/backdrop/pull/4146 into 1.22.x after confirming reverting a few "email" into "e-mail" test checks fixes all tests on 1.22.x.

Thanks @jenlampton, @herbdool, @argiepiano, and @indigoxela for reporting and fixing this!

**Closed by quicksketch** 2022-07-21 23:30 UTC
Labels: type - bug report, status - has pull request, pr - needs testing, pr - needs code review
