### ISSUE TITLE
Tabledrag JS "sticks" to cursor

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2482] opened 2017-01-19 21:03 UTC
It looks like in 1.6.0, some users including @jenlampton and @YesCT have experienced a problem where when ordering items with tabledrag (for example menu items), the table row gets "stuck" to the cursor when clicking down and doesn't let go when releasing.

Confirm if this problem exists globally or in certain circumstances. ~~It does appear this happens in 1.6.0 only, not the 1.5.x branch.~~

---
~PR by @klonos: https://github.com/backdrop/backdrop/pull/1768~
PR by @quicksketch: https://github.com/backdrop/backdrop/pull/1787

**Comment by quicksketch** [comment] 2017-01-20 01:19
Hm, well in fact on trying to reproduce this, I can't reproduce it. @jenlampton will try to reproduce this and update.

**Comment by jenlampton** [comment] 2017-01-20 01:40
I've found the same problem on backdropcms.org (curently running 1.5.2) so it's not something we introduced recently.  Here's a video: https://www.screencast.com/t/SS97qqQdK

**Comment by klonos** [comment] 2017-01-20 05:52
I only saw this happening momentarily the first time I tried to reproduce this issue but then I refreshed the page and it didn't occur again - not even on other menus than the one I was initially playing around with.

Are there any people that are getting this behavior consistently? Any specific steps you need to take in order to reproduce it?

**Comment by klonos** [comment] 2017-01-20 05:53
...oops. Hadn't refreshed the page, so just saw the last two comments after I replied.

**Comment by klonos** [comment] 2017-01-20 05:53
I saw this happening on latest Firefox nightly x64 builds on Windows, so I doubt it is OS-specific.

**Comment by MrHaroldA** [comment] 2017-01-20 09:39
I have it too on Chrome / Linux, also on the 1.5 branch.

**Comment by klonos** [comment] 2017-01-23 19:05
As pointed out on Gitter by @MrHaroldA, this is an issue that got fixed in Drupal 7.53 ([Newer Chrome versions and IE11/Edge cannot drag and drop anymore on desktop after 7.51 update when jQuery is updated to 1.7-1.11.0 [#2821441]](https://www.drupal.org/node/2821441)). PR is the same as the respective D7 commit: http://cgit.drupalcode.org/drupal/commit/?id=f00cd29

**Comment by klonos** [comment] 2017-01-23 19:11
@jenlampton and @YesCT I could not reproduce this consistently so cannot test. Can you please test the PR and see if it actually fixes this issue?

**Comment by jenlampton** [comment] 2017-01-27 06:31
@klonos yes, this fixes the problem!!!  Thank you! :)

**Comment by jenlampton** [comment] 2017-01-27 06:57
Er, well I take it back.  I'm now using this patch on https://forum.backdropcms.org and I'm still running into the same tabledrag problem. I think it was a fluke that it worked on my local.

**Comment by klonos** [comment] 2017-01-27 11:33
FYI: I don't claim the PR to be fixing the issue (could not actually test this as I cannot reproduce it consistently); it's just getting the same fix that was committed in D7 core.

**Comment by MrHaroldA** [comment] 2017-01-27 12:09
I can confirm that this does not fix the issue; the row is still attached to the cursor on a single click.

Chrome 56 on Arch Linux.

**Comment by jenlampton** [comment] 2017-01-27 22:32
I don't think that commit to D7 fixes this problem. There are several other issues going on in D7 that appear to be related to the latest jQuery update:
* https://www.drupal.org/node/2838092
* https://www.drupal.org/node/2843240
* https://www.drupal.org/node/2544066

**Comment by quicksketch** [comment] 2017-02-10 03:27
I think I've identified the issue here. I'm now able to reproduce this issue after updating to the latest version of Chrome. And it's now clear why this is only affecting a few users (so far), it's because Chrome recently implemented this new feature to support "pointerdown" events in Chrome 55+ (apparently Chrome is the current version):

https://developer.mozilla.org/en-US/docs/Web/Events/pointerdown

We currently have this line in tabledrag.js:

```
  // Add event handler to start dragging when a handle is clicked or touched
  handle.on('mousedown touchstart pointerdown', function (event) {
    event.preventDefault();
    if (event.type == "touchstart") {
      event = event.originalEvent.touches[0];
    }
    self.dragStart(event, self, item);
  });
```

So up until the most recent version of Chrome, it ignored that "pointerdown" event. However, now that it listens to it, the call to `event.preventDefault()` apparently short-circuits the rest of the mouse events, including "mousemove". In Firefox this apparently is handled differently, and even if a "pointerdown" event fires, when the cursor moves, it fires both "pointermove" and "mousemove", while Chrome will only trigger "pointermove" events. Thus the row isn't getting moved when the cursor moves.

The apparently solution is to include "pointermove" events I believe. This apparently was included in the original Drupal patch at https://www.drupal.org/node/2177293#comment-10504420, but we missed it in the port we did for pointer events in #1550.

**Comment by quicksketch** [comment] 2017-02-10 04:39
New PR pushed up at https://github.com/backdrop/backdrop/pull/1787 that should fix this issue.

I don't think we need the previously filed PR, as Backdrop runs jQuery 1.12.4, which shouldn't be affected by the mentioned issue.

**Comment by MrHaroldA** [comment] 2017-02-10 08:33
A quick test shows that it fixes all my issues with drag ;)

**Comment by jenlampton** [comment] 2017-02-10 18:51
It's working for me as well, nice work @quicksketch !

**Comment by quicksketch** [comment] 2017-02-13 03:08
Merged https://github.com/backdrop/backdrop/pull/1787 for 1.6.1.

**Closed** 2017-02-13 03:08 UTC
Labels: pr - reviewed & tested by the community, status - has pull request, type - bug report
