### ISSUE TITLE
Manual self-update fails: Cannot determine type of project

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#3979] opened 2019-08-14 16:14 UTC
When I try to update Backdrop core using the user interface, I get the following error on the page `admin/update/ready`:

> UpdaterException: Cannot determine the type of project. in Updater::getUpdaterFromDirectory() (line 125 of /(...)/core/includes/updater.inc).

**Steps To Reproduce**

1. Log into a Backdrop 1.13.2. site, and make sure that *Manual self-updates* are enabled on `admin/reports/updates/settings`.
2. Go to `admin/modules/update`. There should be a 1.13.3 version available. Hit the checkbox, and click on "Download these updates".
3. Click the "Continue" button on the *Ready to update* page.

**Actual behavior**

You see an "unexpected error" message. In the DBlog you'll find the "UpdaterException" message mentioned above.

**Expected behavior**

The self update runs without problem.

---
PR by @indigoxela: https://github.com/backdrop/backdrop/pull/2828

**Comment by klonos** [comment] 2019-08-14 16:26
Hmm 🤔 ...I thought that we've addressed all such issues (they were being caused by some modules/profiles/tests not having a `type =` bit in their .info file).

@olafgrabienski are you getting this in a vanilla installation, or does this site include contrib and/or custom modules/themes/layouts?

**Comment by olafgrabienski** [comment] 2019-08-14 16:40
@klonos I thought also that we've fixed the `type` related things! Unfortunately, the message doesn't mention for which project there is a problem to determine the type.

To answer your question, one of the sites has a lot of contrib modules, the other one is a test site with only one module. I've disabled and uninstalled the only module of the latter site, removed the module code and cleared the cache, but the issue persists.

**Comment by klonos** [comment] 2019-08-14 16:49
> ...removed the module code and cleared the cache, but the issue persists.

Ok, it then sounds like a core bug. I will try to reproduce on a vanilla 1.13.2 test site on my local.

**Comment by indigoxela** [comment] 2019-08-15 07:58
I can confirm that manual self-update from1.13.2 to 1.13.3 fails on a vanilla install.

There are currently 32 .info files not containing "type", all of them are test files.

Here's a full list:

- ./core/modules/path/tests/path.tests.info
- ./core/modules/menu/tests/menu.tests.info
- ./core/modules/ckeditor/tests/ckeditor.tests.info
- ./core/modules/taxonomy/tests/taxonomy.tests.info
- ./core/modules/redirect/tests/redirect.tests.info
- ./core/modules/syslog/tests/syslog.tests.info
- ./core/modules/entity/tests/entity.tests.info
- ./core/modules/language/tests/language.tests.info
- ./core/modules/views/tests/views.tests.info
- ./core/modules/dashboard/tests/dashboard.tests.info
- ./core/modules/block/tests/block.tests.info
- ./core/modules/contact/tests/contact.tests.info
- ./core/modules/date/tests/date.tests.info
- ./core/modules/link/tests/link.tests.info
- ./core/modules/image/tests/image.tests.info
- ./core/modules/comment/tests/comment.tests.info
- ./core/modules/layout/tests/layout.tests.info
- ./core/modules/field_ui/tests/field_ui.tests.info
- ./core/modules/search/tests/search.tests.info
- ./core/modules/update/tests/update.tests.info
- ./core/modules/contextual/tests/contextual.tests.info
- ./core/modules/user/tests/user.tests.info
- ./core/modules/filter/tests/filter.tests.info
- ./core/modules/installer/tests/installer.tests.info
- ./core/modules/color/tests/color.tests.info
- ./core/modules/config/tests/config.tests.info
- ./core/modules/dblog/tests/dblog.tests.info
- ./core/modules/field/tests/field.tests.info
- ./core/modules/field/modules/field_sql_storage/tests/field_sql_storage.tests.info
- ./core/modules/translation/tests/translation.tests.info
- ./core/modules/book/tests/book.tests.info
- ./core/profiles/testing/modules/backdrop_system_listing_compatible_test/backdrop_system_listing_compatible_test.tests.info

I'm almost sure, this has been addressed in an existing issue, but I can't find it now.
There have been several issues regarding failed self-update because of missing type in info. All of them seem to be closed/fixed.

**Comment by indigoxela** [comment] 2019-08-15 08:07
I found the comment regarding tests: https://github.com/backdrop/backdrop-issues/issues/3821#issuecomment-496284479

Ah, the only .info file NOT contained in a tests directory is ./core/profiles/testing/modules/backdrop_system_listing_compatible_test/backdrop_system_listing_compatible_test.tests.info

There was an issue for that, but it was closed as duplicate: https://github.com/backdrop/backdrop-issues/issues/3821

**Comment by olafgrabienski** [comment] 2019-08-15 08:35
Good catch, @indigoxela! Should we reopen #3821 then?

Another question: After all the self update issues, it would be great to have the option to test an update to an upcoming release manually *before* it gets released? Can we create a sort of pre-release for update testing?

**Comment by klonos** [comment] 2019-08-15 09:26
@olafgrabienski we create pre-releases for minor versions (usually after feature freeze); creating pre-releases for each bug release would be quite an overhead for our core committers.

I think that the most future-proof solution here would be to require `type =` in the .info files of _all_ projects and also tests. At the moment, we are excluding tests ...or I should say "we are trying to exclude" ...we don't seem to be doing a great job 😅.

**Comment by klonos** [comment] 2019-08-15 09:32
Perhaps if we added the name of the `$directory` in the exception error in https://github.com/backdrop/backdrop/blob/1.x/core/includes/updater.inc#L125 ...that would at least help us determine which directory causes the exception.

**Comment by olafgrabienski** [comment] 2019-08-15 10:46
> creating pre-releases for each bug release would be quite an overhead for our core committers

I see! It would be however helpful to be able to test a release beforehand, not only regarding self updates but also regarding the installation process. Maybe provide a (hidden) option to simulate a new release, based on the 1.x branch?

**Comment by indigoxela** [comment] 2019-08-17 13:55
So what actually causes the problem?

Public static function findInfoFile() does a file_scan_directory() to pick up all files ending with .info. Then files ending with ".tests.info" get filtered out. The remaining info files are supposed to contain a "type", otherwise they're causing an exception.

Weird thing, this should pass for both, 1.13.2 and 1.13.3.

The Linux command line equivalent is:

`find core -type f -name '*.info' | grep -v '\.tests\.info$' | xargs grep -L '^type'`

Empty result, all seem OK. The problem must be caused by something else this time.


The exception is thrown in public static function getUpdaterFromDirectory(). It's possibly something with 'canUpdateDirectory'. Not sure. It would be extremely helpful to get the directory causing the exception.

**Comment by indigoxela** [comment] 2019-08-19 12:42
I just played around with the updater (I admit, I'm not familiar with it). Perhaps it could be an easy fix, though.

public static function getProjectType($directory) checks for ($directory == BACKDROP_ROOT) to return "core", but that's wrong because there the $directory is something like "temporary://update-extraction-577fc74f/backdrop".

Instead of 
```
    if ($directory == BACKDROP_ROOT) {
      return 'core';
    }
```
the check should rather be something like
```
    if (basename($directory) == 'backdrop') {
      return 'core';
    }
```
Please note: someone with a better understanding of the install/update process in Backdrop should create a pull request.

Maybe there's a more reliable check for the core updater.

Btw: the comment for getProjectType() needs to get updated - core has no '.info' file. ;)

**Comment by klonos** [comment] 2019-08-19 16:59
Hmmm, I finally got a chance to test this on my local, but I cannot reproduce the problem 🤔

**Comment by klonos** [comment] 2019-08-19 17:10
...steps I used:

- `git clone`'d fresh
- `git checkout 1.13.2`
- run the installation to get a fresh/vanilla 1.13.2 site (used latest ddev: MariaDB 10.2.25 / PHP 7.2.21 / nginx 1.16.0)
- head to `/admin/modules/update`
- select the available update for Backdrop 1.13.3
- follow the prompts as per usual

I got updated to 1.13.3 w/o any errors, and no errors in the log either.

Can you guys think of anything specific to your setup that might be causing this?

**Comment by klonos** [comment] 2019-08-19 17:13
...here's my file system settings:

![Screen Shot 2019-08-19 at 8 12 28 pm](https://user-images.githubusercontent.com/2423362/63285115-ba32a700-c2bd-11e9-91d0-8e6e50d6fff9.png)

**Comment by indigoxela** [comment] 2019-08-20 05:55
> git checkout 1.13.2

@klonos to reproduce the problem, please use the official release https://github.com/backdrop/backdrop/releases/tag/1.13.2 and update from that.

Regarding my local testing machine: there's nothing special about it, a Debian server.
I installed a fresh vanilla Backdrop using the official release. I then get notified immediately, that an update is available. If I try an update with self-update, it fails with the exception described by @olafgrabienski .

If I change core/includes/updater.inc in this 1.13.2 install like described in my [previous comment](https://github.com/backdrop/backdrop-issues/issues/3979#issuecomment-522555422), everything runs smoothly.

**Comment by olafgrabienski** [comment] 2019-08-20 08:11
> Can you guys think of anything specific to your setup that might be causing this?

Not that I would know. The sites in question are on different shared hosting services with quite current PHP versions. At least one of the servers is Nginx (others not).

I remember one of the sites (not on a Nginx server) where the update ran smoothly. So there might be certain circumstances where there is no issue, but it's even possible that I updated that site first from 1.12.x to 1.13.2 for testing purposes and then didn't clear caches before trying to update to 1.13.3.

It would however interesting to get more feedback, if people can reproduce the issue in different environments.

**Comment by indigoxela** [comment] 2019-08-24 12:10
I've added a pull request with a test (to reproduce) and a fix for "Cannot determine the type of project".

Please note: this needs a **close** inspection from an experienced Backdrop core developer.

_public static function getProjectType($directory)_ in core/includes/updater.inc was the problem, as "$directory" is the stream wrapper to the extracted directory, _not_ the backdrop install directory.
As this check didn't work, we had several issues with core and tests and missing .info files.

The test alone, without the fixing commit, fails with the UpdaterException, this issue is about.

I don't know, why the totally unrelated path_pattern test is failing for my pull request. It passes on my local.

**Comment by indigoxela** [comment] 2019-08-24 12:22
I don't think, this issue will get much attention from users out there. Self-update is probably broken for quite some time, so hardly anyone uses it. That's why I don't expect much feedback here anyway.

Regarding @olafgrabienski's suggestion to test self-updates beforehand: I've no idea, how this could be accomplished with Backdrop's existing infrastructure.

At least now there's another test to prevent a problem we found to reappear.

**Comment by klonos** [comment] 2019-08-24 12:31
Thanks for working on this @indigoxela 👍

> I don't think, this issue will get much attention from users out there. Self-update is probably broken for quite some time, so hardly anyone uses it. That's why I don't expect much feedback here anyway.

We need to get things right, so that people are more confident, and start using this feature more. So do expect feedback; at least from people actively working on Backdrop 🙂

I am still interested to test this (by downloading the .zip package instead of `git clone`'ing the latest version), and then confirm that your fix addresses the issue.

**Comment by klonos** [comment] 2019-08-24 12:46
...damn it! Even with the .zip from https://github.com/backdrop/backdrop/releases/download/1.13.2/backdrop.zip things worked fine for me. Still not able to reproduce this 😞

**Comment by indigoxela** [comment] 2019-08-24 13:00
> Still not able to reproduce this

This is so weird...

Just tried it again with 1.13.2 official release zip. Still an Exception. Is there anything special about your local testing machine?
Or: let's figure out, what is different compared to mine.

- OS: Debian stretch
- Webserver: apache 2.4
- PHP: php7.2-fpm and php7.0-fpm (Exception apprears with both versions here)

What else could be relevant?

**Comment by klonos** [comment] 2019-08-24 19:00
As mentioned earlier, I am testing using ddev on a Mac Mojave 10.14.6. My local has MariaDB 10.2.25 / PHP 7.2.21 / nginx 1.16.0

@olafgrabienski what is your setup?

**Comment by herbdool** [comment] 2019-08-25 12:09
I'll test this out later today.

**Comment by herbdool** [comment] 2019-08-25 21:15
I tested as well to see if I could recreate the error and couldn't. I used the official 1.13.2 version, and tested on Lando. This doesn't mean we can't make it more robust. So I'll test the PR as well, soon.

**Comment by klonos** [comment] 2019-08-25 21:16
@herbdool FTR, what was your AMP setup?

**Comment by indigoxela** [comment] 2019-08-26 06:42
Here's a screenshot of the code, which prevents running a self-update on my testing installs. With the values extracted via die(var_dump()) while trying to run the self-update. That's rude, but makes sure, what's the exact value of the variables at that point of the update procedure.

![screenshot-getProjectType-values](https://user-images.githubusercontent.com/842066/63670194-5556df80-c7dc-11e9-8dfc-50c25cfcb2de.png)

For the records: not that I expected a change, but I've also tested installing backdrop in a subdirectory instead of webspace root. Same behavior, UpdaterException.

As you can see, getProjectType can never succeed because the project type can't get determined. Hence Updater::getUpdaterFromDirectory() throws the Exception.

**Comment by olafgrabienski** [comment] 2019-08-26 08:49
> what is your setup? If you are also on apache, then maybe that's where the problem is.

@klonos Sorry for the delay. I've checked one of the testing sites, and it *is* on Apache. Here are the infos from the Status report page:

- Database: 5.5.5-10.1.39-MariaDB-1~jessie
- Web server: Apache/2.4.10 (Debian)
- PHP Version: 7.2.14

**Comment by klonos** [comment] 2019-08-26 10:16
Thanks @olafgrabienski ...if @herbdool is also on nginx, same as myself, then we can conclude that apache may have something to do with this (in addition perhaps to the other things that @indigoxela discovered). ...one thing I can think of is that any `.htaccess` file redirect or other rule we currently have in place may be interfering, since nginx does not support `.htaccess` files; so I assume it bypasses them entirely.

**Comment by klonos** [comment] 2019-08-26 10:26
> ...apache may have something to do with this

Nope; ddev allows you to switch to apache, so I just tested on Apache 2.4.25 (php still 7.2.21), and was able to update from 1.13.2 to 1.13.3 w/o any problems.

**Comment by indigoxela** [comment] 2019-08-26 11:11
I never assumed, apache / nginx is relevant here, but many thanks to @klonos for clarifying.

Another idea:

`$directory == BACKDROP_ROOT` can't be true even on those installs, where updates worked, BUT findInfoFile() could pull out a different .info file (from different subdirectory).

On php.net some comments warn that readdir() entry order can be unreliable.
file_scan_directory() uses readdir().

So possibly the working test instances simply get a different order, which results in something else getting returned as "the first or most important .info file".

Can anyone confirm or falsify that? What do you get as `$info['type']`?

**Comment by indigoxela** [comment] 2019-08-26 11:13
Oh, and if it is really about the directory content order, I'll have to rewrite my test.

**Comment by olafgrabienski** [comment] 2019-08-26 11:19
> What do you get as `$info['type']`?

How can I check for it?

**Comment by indigoxela** [comment] 2019-08-26 12:02
> How can I check for it?

That's a bit tricky. It's probably most reliable to actually run the updater.

So you would have to install 1.13.2 from zip, but _before_ you start a self-update, you open core/includes/updater.inc with an editor and add `die($info['type']);` right before the return in line 201.

The installer will stop right there, after downloading Backdrop 1.13.3, but before really doing something. This is at an early stage in the update process, your Backdrop won't break. But of course this should be done on a crash-and-burn (and fresh) install.

**Comment by olafgrabienski** [comment] 2019-08-26 12:47
Thanks for the instructions, @indigoxela ! Following them, I get a nearly blank page with the string `profile` on `admin/update/ready`.

**Comment by indigoxela** [comment] 2019-08-26 12:58
> I get a nearly blank page with the string profile on admin/update/ready

Exactly the same as I do, but that's not such a big surprise, as you are testing on Linux (Debian), too. And you initially reported the issue. ;)

Now I'm curious, what the people with the working updates report.

**Comment by klonos** [comment] 2019-08-26 16:19
> Now I'm curious, what the people with the working updates report.

For me `die($info['type']);` returns `theme`. As for the rest of the variables:

`$directory`: `temporary://update-extraction-0956944b/backdrop`

`$info_file`: `temporary://update-extraction-0956944b/backdrop/core/themes/bartik/bartik.info`

`$info`:

```
Array
(
    [name] => Bartik
    [description] => Legacy front-end theme.
    [version] => 1.13.3
    [type] => theme
    [backdrop] => 1.x
    [stylesheets] => Array
        (
            [all] => Array
                (
                    [0] => css/style.css
                    [1] => css/colors.css
                )
            [print] => Array
                (
                    [0] => css/print.css
                )
        )

    [ckeditor_stylesheets] => Array
        (
            [0] => css/editor.css
        )
    [settings] => Array
        (
            [color] => 1
            [main_menu_tabs] => no-tabs
        )
    [project] => backdrop
    [timestamp] => 1565217539
)
```

**Comment by olafgrabienski** [comment] 2019-08-26 16:36
>  I think this PR looks good. I've tested it locally.

Also tested, on the shared hosting site [mentioned above](https://github.com/backdrop/backdrop-issues/issues/3979#issuecomment-524778023), works for me, great!

**Comment by klonos** [comment] 2019-08-26 18:15
Thanks for confirming this works @olafgrabienski 👍 ...added this to the next bug fix release 😉

**Comment by klonos** [comment] 2019-08-27 00:26
If we want to be as future-proof as possible, we could add a regex pattern that accepts either plain `backdrop`, or versioned variations of it. Not fussed about it though.

**Comment by indigoxela** [comment] 2019-08-27 05:53
> The directory name is not always "backdrop" in the case that an archive is downloaded from GitHub

Good point. Although this is unlikely to happen in near future, I'd like to consider that when checking for the basename. Just in case...

I need to slightly adapt the test (and comment) anyway, now we know the root cause for the issue.

**Comment by indigoxela** [comment] 2019-08-27 07:06
I've updated my pull request to better catch possible updater class problems.

In function getProjectType the core directory is now checked to _start with_ backdrop, rather than for the full name. This should prevent errors, if we later on decide to add, for instance, dev releases with version numbers in directory names.

I also did a little cleanup and changed comments. Please review.

**Comment by klonos** [comment] 2019-08-27 19:35
I have added a comment in the PR. I think that it'd be better to use `preg_match()` instead.

**Comment by indigoxela** [comment] 2019-08-28 06:15
@klonos and @herbdool many thanks for having a look.

Regarding the check for "backdrop*": Sure, preg_match() might be a better option. But sticking to exactly "backdrop" might be even better. I'm not the one to decide. ;)

What I had in my mind, was an older issue, https://github.com/backdrop/backdrop-issues/issues/664. It isn't clear yet, what those nightlies could look like and what would be the directory naming pattern then. Drupal dev downloads don't have any version info in directory names, but maybe that's not feasible with Backdrop's infrastructure.

If it's not possible to decide that now, maybe we should stick with "starts with backdrop" (substr()).
Even if a theme is named like, for instance, "backdrop_supertheme" it won't contain a directory "core" then (is this true?). We could enhance the second check a bit, by verifying that a file exists in that directory, that will _always_ exist in backdrop core and _can't ever_ exist in a theme, layout or module (with is_file()). What about checking for "settings.php" or "core/authorize.php"? Does such an unambiguous file exist in core?

Regarding @herbdool's suggestion to throw an error if both checks, "backdrop*" and it contains "core": that's risky. I'd prefer to continue with searching for an info file. If nothing appropriate is found, an UpdaterException is thrown anyway.

**Comment by olafgrabienski** [comment] 2019-08-28 07:57
@indigoxela Good ideas! It's however difficult to find a file that will exixt forever, see e.g. #3208. (In case we take the approach, maybe mitigate the risk by making a code comment in the file we're referring to?)

**Comment by indigoxela** [comment] 2019-08-28 08:35
Hey, just a fancy idea: what if we create such an unambiguous file with solely the purpose to verify, this is a backdrop core project directory?

**Comment by indigoxela** [comment] 2019-08-28 13:37
> ...that the folder inside the zip file would still be just backdrop

Hey, then let's go back to `basename($directory) == 'backdrop'`

What do you think about my idea, to create a uniq indicator file for core? Overdone?

> ... it does not go to the else statement

Ooops, you're of course right, it's if/else, not if/if.
Yes, we should give the admin some hint, what went wrong, if it fails. Maybe an error message with a link to documentation, how to update manually is more helpful? Redirect somewhere? But what if core and some other projects get updated at the same time (in the same batch)?

**Comment by klonos** [comment] 2019-08-28 15:29
You beat me to it re authorize.php and #3208 @olafgrabienski 👍 

Agreed re going back to plain check for `backdrop` + then `core` within it. We can revise later, if the naming of folders within the .zip archives changes, and things do not work any more.

Good catch @herbdool re the if/else 👍 

@indigoxela perhaps add some inline comments explaining the logic? As for what to do, I believe that something like this would suffice:

`throw new UpdaterException(t('Unable to find <em>core</em> directory within the extracted <em>backdrop</em> directory.');`

**Comment by indigoxela** [comment] 2019-08-29 06:50
I've updated the PR. It turned out, that an UpdaterException is thrown anyway by getUpdaterFromDirectory(), but it makes sense to provide more specific info.

**Comment by quicksketch** [comment] 2019-08-29 18:12
Thanks everyone! Heh, as usual I accidentally derailed things a bit. Thanks for thinking on all sides of this.

> Re #664 even if there are additional zip files with something like 1.13.3+1-dev I gathered from Nate's previous comment that the folder inside the zip file would still be just `backdrop`.

Yes, that's right. We already make all downloads of packaged core and contrib modules be exactly the project name. If I recall, I think `drush` had some of the same expectations around the file names being exactly that of the module as well.

So I may have made much ado about nothing. 

Anyway, things look good and I've merged in https://github.com/backdrop/backdrop/pull/2828. Thanks @indigoxela, @olafgrabienski, @serundeputy, @klonos, and @herbdool!

**Closed by quicksketch** 2019-08-29 18:12 UTC
Labels: status - fixed, status - has pull request, type - bug report
