### ISSUE TITLE
CKEditor eats my P tags

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1197] opened 2015-09-16 03:49 UTC
I enabled ckeditor on my Filtered HTML input format, but any time I edit existing content all my P tags get eaten, and I'm forced to reformat the whole page.

**Comment by quicksketch** [comment] 2015-09-16 03:52
So to fix this, I think we may need to do the following:

- Have CKEditor detect if the auto-p filter is turned on.
- Create a "backdropautop" plugin that is loaded with the CKEditor configuration.
- Have the plugin add p tags upon loading.

It's also worth noting that WordPress actually *removes* P tags when you switch to the source code view (counting on both its JS and PHP filters to readd them when needed). I'm not sure if we want to take it that far. Should we just add P tags when used with CKEditor and leave them in the source when saved to the database?

**Comment by Dinornis** [comment] 2017-05-09 00:55
I believe this problem has been solved.  I was not able to reproduce this with 1.7.x-dev.
Closing and marking as fixed.  Please reopen if I misunderstood.

**Closed by Dinornis** 2017-05-09 00:55 UTC
Labels: type - bug report
