### ISSUE TITLE
Remove unused min_length_* variables

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4599] opened 2020-09-03 17:12 UTC
Fixes https://github.com/backdrop/backdrop-issues/issues/4265

**Description of the bug**

When adding a user and password:

> Uncaught TypeError: Cannot read property 'user_password_min_length_enabled' of undefined

This should be removed https://github.com/backdrop/backdrop/blob/464d385836ab0f05d9997aa6064f358679f0a128/core/modules/user/js/user.js#L186

I could have sworn I had removed this on @jenlampton PR before it got merged. But no biggie.

**Comment by herbdool** [comment] 2020-09-03 17:27
@jenlampton this should be an easy review. I had fixed your PR - and thought I had removed this too but was trying to do it on a phone so looks like it didn't save.

**Comment by indigoxela** [comment] 2020-09-04 09:38
Confirmed, currently the indicator is broken because of that missing variable. Removing these lines of code in user.js fixes the indicator.

@herbdool can you add the magic "Fixes" to your PR description, so the link shows up in the Issue header? It's easier to find then.

**Comment by herbdool** [comment] 2020-09-04 11:27
Thanks @indigoxela . I'm not 100% sure what you mean by magic "fixes" but I added a link to the original PR which this fixes.

**Comment by indigoxela** [comment] 2020-09-04 11:33
> I'm not 100% sure what you mean by magic "fixes"

It means to add `Fixes ...backdrop/backdrop-issues#4599` in the PR description - the word "Fixes" makes the link appear in the sticky header in the linked Issue and will also close the Issue when merged - that's the "magic". :wink:

**Comment by indigoxela** [comment] 2020-09-05 09:50
Can someone of the core team please merge this? We need a functioning indicator in other issues, and these are currently blocked by the regression.

**Comment by herbdool** [comment] 2020-09-05 11:28
@BWPanda can merge this one?

**Comment by stpaultim** [comment] 2020-09-06 03:21
I just want to confirm that the indicator was broken in the sandbox. Then @herbdool fixed something and then it was working in the sandbox, prior to being committed. So, something weird must have happened.

**Closed** 2020-09-07 00:29 UTC
Labels: pr - ready to be committed, status - has pull request, type - bug report

**Comment by BWPanda** [comment] 2020-09-07 00:30
@herbdool This is the 'magic' @indigoxela was referring to: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

I've merged https://github.com/backdrop/backdrop/pull/3286 into 1.x. It doesn't need to go into 1.16.x, right?

**Comment by klonos** [comment] 2020-09-07 02:13
> It doesn't need to go into 1.16.x, right?

Correct. This fixes a regression of a feature that was added in 1.x only.
