### ISSUE TITLE
Add date (field) module to core

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#478] opened 2014-12-18 20:13 UTC
Optionally, instead of leaving this as a stand-alone module, it could be added as a field type to field module.  Form element types will also need to be updated to use the new date form elements.

**Comment by quicksketch** [comment] 2015-06-25 19:42
As @Graham-72 has been doing a ton of work on the Date contrib module: https://github.com/backdrop-contrib/date, I'd love to hear his thoughts on which parts of Date we should bring in.

Date project includes a lot of various pieces, not all of which we'll probably want to include in core:

- Several different date field types (DateTime, Date, Timestamp).
- Date selector popup (we already have something similar in Backdrop but it needs work).
- Date views integration.
- Repeating events.
- All day events.
- Start and end dates.

**Comment by Graham-72** [comment] 2015-06-25 20:47
@quicksketch - my experience as a user of Date in Drupal 7 has made me think that most of it is useful, but I shall have to think more about how much should be in core. Repeating events, all day events and start and end dates may be largely related to providing calendar functionality, which I regard as an essential for many websites, but I guess I would now make use of Google Calendar, but as yet I have no idea how one links events in Google Calendar to Views in Backdrop. I would definitely want to use date fields in Views.

In my work on porting Date the main thing has been to integrate it with the config arrangements, using core's systems.date config, augmented by some settings in date_api.settings, more in date.settings and also date_views.settings, partitioned like this to retain the separation of the component modules (date_api, date, and date_views). Most of this now seems to be working but I am working my way through the various test modules to find any remaining problems.

I like the date selector popup and would hope that it, or an equivalent, will be in core.

One feature I have thought of omitting is the arrangement in Drupal's Date module to offer all sorts of variants of custom formats, which simplifies adding PHP date/time codes because you just choose from a drop-down list. This might still be a useful feature, and any formats added in this way would be added to the systems.date config, as already possible by entering them manually.

One feature I would like added is the capability of setting date formats to suit national preferences, though maybe there is something there that provides for this. My initial thought has been that this might be something core's locale module might do - all it need do is change some of the default formats in system.date.json, changing m-d to d-m etc to suit national preferences.

I hope these thoughts are helpful. There is a great deal in Date, much of which I have not yet fully understood.

**Comment by Graham-72** [comment] 2015-06-25 21:20
One aspect I haven't yet thought through is how to handle migration of Date on a Drupal site to a Backdrop site.

**Comment by klonos** [comment] 2015-06-25 22:16
Yep, I think Date in core would be the next big thing for Backdrop. Thanx for all your work on this @Graham-72

**Comment by wesruv** [comment] 2015-07-02 20:29
One thing that bit me in D7 Date module was the default value on a new field being set to 'Now'. I ended up not realizing that was the case until some poor content editor put in a TON of content and only some of it was valid and most was bogus and no clear way to tell which data was valid and which wasn't.

Seems to me the default value of *any* field would be 'empty' and you can change it to 'now'.

Otherwise I built 7 large sites and all of their content types for Highlights and never used a repeating date. If it ends up being contrib I don't think that'd be an issue.

**Comment by Graham-72** [comment] 2015-07-02 21:06
>One thing that bit me in D7 Date module was the default value on a new field being set to 'Now'

I agree. I look forward to some improvement here. In my port for Backdrop I have at the moment the form looking like this
![create basic page - www oliverweb net 2015-07-02 21-53-32](https://cloud.githubusercontent.com/assets/10559274/8487643/4f618198-2105-11e5-9b96-fd6aefa33289.png)
Note that under the text entry field (ISO Date) I have an example display of both the current local time and date, and the PHP format. The latter is chiefly to remind me in which order to put d and m (because for me it is the 'wrong' way in this case :wink: ).

I am still grappling with some problems in porting Date so it is not yet ready to issue formally.

**Comment by wesruv** [comment] 2015-07-02 21:12
@Graham-72++

**Comment by klonos** [comment] 2015-07-03 14:39
I think it is fair enough to have this issue assigned to you.

**Comment by Graham-72** [comment] 2015-07-11 14:43
I was running into increasing difficulty with my attempt to port Date (at https://github.com/backdrop-contrib/date) and so I have made a fresh start, omitting some of the most unlikely features for incorporation in core. I have named this new version 'Date Basic' and you can find it at https://github.com/backdrop-contrib/date_basic.

I shall continue with my testing of this; any comments, suggestions or issues found by others would be most welcome.

**Comment by docwilmot** [comment] 2015-07-11 23:17
Could you say which features are being excluded and included?

**Comment by Graham-72** [comment] 2015-07-12 06:26
Modules included in Date Basic: Date, Date API, Date Views, Date Popup, Date Tools (under review)

Modules not included: Date Migrate, Date Repeat, Date Repeat Field, Date All Day

Functionality:

In its current version, copied from the Drupal module, it provides for three types of date field: a Unix timestamp stored as an integer; an ISO format date stored as a text field; and a basic date stored as a MySQL datetime field.

Additionally it provides three different ways for a user to input a date: a text field using one of many PHP date-time formats; a drop-down select list for day, month and year; and a javascript pop-up calendar for day, month and year.

The module includes the possibility of a date-time pair, defining the start and finish times for an event.

An included Date Views module provides integration with Views.

The omitted modules Date Repeat, Date Repeat Field, Date All Day are, I believe, mainly needed to provide a Calendar, which if needed is probably best done in a contributed module.

Unknowns:

Date Migrate is something I have not considered. 

I am not sure how this module could handle migration from Date in Drupal 7.

There are parts that deal with databases other than MySQL and these could be removed for this Backdrop version.

**Comment by docwilmot** [comment] 2015-07-15 19:53
If in that case you're abandoning the date port to transition to a core module, why not just submit a PR against core rather than starting a new module which also will need to be abandoned in short course?

**Comment by Graham-72** [comment] 2015-07-16 14:07
@docwilmot I nearly did just that but sadly I am still finding the occasional bug and I would like to be confident that it all works correctly before submitting it to core.
Also, I would be glad of the view of @quicksketch (and others) of whether core should provide all three ways of storing dates in MySQL. So far I have been proceeding along the lines that Date in Backdrop should stick closely to the Drupal version but maybe it could be more of a subset than I have previously envisaged. Opinions welcome.

**Comment by docwilmot** [comment] 2015-07-16 14:32
I think a core PR would still be a better option. It keeps your work where
everyone's already working, you get Travis to help find bugs, and it saves
that extra step of having to try and merge into core again. And you'll
notice that others have often posted not-quite-ready PRs with the
declaration that it's an initial buggy start for Travis and @quicksketch to
evaluate.

**Comment by quicksketch** [comment] 2015-07-16 18:09
> So far I have been proceeding along the lines that Date in Backdrop should stick closely to the Drupal version but maybe it could be more of a subset than I have previously envisaged.

For the first pass, let's leave the 3 different formats intact (Date, DateTime, and Timestamp). We might consider doing something such as hiding the extra formats that are not necessary but allowing them to exist for compatibility with existing sites, but we can save that for later. If we flip the widget and field storage type as suggested in #80, that may alleviate some of the confusion as to which type of date field should be used, as we can make DateTime the first/default one for all date widgets.

**Comment by Graham-72** [comment] 2015-07-20 06:28
@quicksketch I have just tried to add the contents of contrib module Date Basic as new module 'date' in core with PR https://github.com/backdrop/backdrop/pull/999. Travis has identified several problems which may well be beyond my understanding.

Also, my PR just added the files and did not merge them as a repository with its history. I had tried to achieve this by following the procedure in https://help.github.com/articles/about-git-subtree-merges/ but hit a response that Github could not perform the merge.

**Comment by serundeputy** [comment] 2015-07-20 22:05
@Graham-72 maybe if we make a meta issue we can all chip in and fix failed tests one at a time?

just a thought.

~Geoff

**Comment by Graham-72** [comment] 2015-07-21 04:47
Travis report : Parse error: syntax error, unexpected '[' in /home/travis/build/backdrop/backdrop/core/modules/date/date_api/date_api.module on line 1733

Maybe we need to check that the value of $type is such that system_date_format_load($type) is an array. If not, use default 'medium'.

@serundeputy a meta issue sounds a great idea but I don't know how to set about it!

**Comment by klonos** [comment] 2015-07-21 12:49
> ...a meta issue sounds a great idea but I don't know how to set about it!

Just file a generic-title issue with a "[META]" at the front of the title. Start filing separate issues and refer to this "parent" issue. We can then edit the issue summary to add these "child" issues [as tasks](https://help.github.com/articles/writing-on-github/#task-lists) (adding a ```- [ ] ``` in front of each issue/task).

**Comment by klonos** [comment] 2015-07-22 20:19
@Graham-72: you nailed it! This is how a meta-issue is shown in the issue list (notice the x of y percent completed detail):

![github_meta_issue_progress](https://cloud.githubusercontent.com/assets/2423362/8836225/d1a1edac-3102-11e5-944d-61661b54c13f.png)

**Comment by Graham-72** [comment] 2015-07-24 20:28
Having had a further look at the Date Tools sub-module, I propose to remove it from Date Basic and not include it in core. This is because it seems to be mainly aimed at helping a user set up dates for a calendar and does not seem to be needed for date fields.

**Comment by serundeputy** [comment] 2015-08-26 23:27
@Graham-72 is there a branch we can check out to test this?

I'm tracking your repo as a remote `git@github.com:Graham-72/backdrop.git`
and I git fetch against it, but not seeing any 478/* branch.

Any ideas how to test this work?

**Comment by Graham-72** [comment] 2015-08-27 04:01
@serundeputy I am afraid I am not at all competent with my use of Github and have probably not done the right thing here. The repo Graham-72/backdrop.git is the one to use but perhaps I should have created a new branch? I have not been working on any other parts of core so there are no other changes from me in there.

**Comment by quicksketch** [comment] 2015-08-28 23:42
> The repo Graham-72/backdrop.git is the one to use but perhaps I should have created a new branch?

Yeah, if you're working on more than one thing, using a separate branch is a good idea before you get started. The video at https://backdropcms.org/develop/pull-requests walks through the whole thing. However, it doesn't really matter for the sake of making a single PR.

For testing this current PR, it can be done with:

```
# Starting from the 1.x branch, make a new branch for testing.
git checkout -b 478/date
# Pull from Graham's 1.x branch into this new branch.
git pull https://github.com/Graham-72/backdrop.git 1.x
```

I'm going to be giving this a go this weekend as well.

**Comment by serundeputy** [comment] 2015-08-31 01:08
thanks @Graham-72 and @quicksketch ;

  * I pulled this in enabled `Date`, `Date API`, `Date Popup` and `Date Views`.
  * Added and events content type with date field: `Popup Calendar` field widget and `Collect an end Date`
  * Added an instance of `event`; Everything worked swimmingly :smile: nice job!

--
Date API Tests
```
108 passes, 0 fails, and 1 exception
```
<img width="1199" alt="screen shot 2015-08-30 at 8 44 01 pm" src="https://cloud.githubusercontent.com/assets/6763671/9570382/fbdbc98a-4f57-11e5-845f-35fbbd72a77c.png">

--
Date Field Tests
```
230 passes, 0 fails, 0 exceptions, and 85 debug messages
```

--
Date Field UI Tests
```
193 passes, 0 fails, 0 exceptions, and 74 debug messages
```

--
Date Timezone & Granularity Tests
```
1025 passes, 0 fails, 0 exceptions, and 395 debug messages
```

--
Date Validation Tests
```
296 passes, 0 fails, 15 exceptions, and 103 debug messages
```
<img width="1233" alt="screen shot 2015-08-30 at 9 02 19 pm" src="https://cloud.githubusercontent.com/assets/6763671/9570454/778e8a8e-4f5a-11e5-97b2-c6ec501bba86.png">


--
Date Views - Popup Test
```
35 passes, 0 fails, 0 exceptions, and 11 debug messages
```

Looks like all these point to line 392 in `date_api.module` so maybe just one problem to fix!

nice job @Graham-72 looking really good.

**Comment by quicksketch** [comment] 2015-08-31 08:10
Indeed, great job @Graham-72 on taking on this big issue.

I worked this weekend on consolidating Date functionality. It doesn't make sense that we would have a separate module called "Date API" that you need to turn on (or ever see). Instead, Date API should just be part of core as a .inc file. Similarly, Date Views and Date Popup should just be part of Date module.

So I've been working this weekend on redistributing everything into new locations. I'm absolutely certain I've broken some things; this definitely still needs some work. But I wanted to post it up here for everyone before the work week starts.

I also removed a bunch of Contrib integrations which aren't appropriate for core. All changes:

- Moved most of Date API in a combination of /core/includes/date.inc (procedural functions) and /core/includes/date.class.inc (the BackdropDateTime object).
- Moved all of Date Views into Date module proper.
- Moved all theme functions into `date.theme.inc` per our standard.
- Reworked the markup/output of date elements. Eliminating ~12 theme functions for things like labels, separators, etc. These can be changed through element process, element pre_render, or form_alter functions. All elements have labels associated with them now for accessibility (no strays!)
- Removed date_api_ical.inc, move to a contrib module.
- Removed date.devel_generate.inc, move to Devel module.
- It looks like the settings form at admin/config/regional/date-time/date-views no configures any relevant settings. The code comment in hook_menu() indicates that it may be used in importing, which isn't part of the functionality going into core.
- Removed the deprecated functions, including:
  - date_field_all_day()
  - date_field_get_sql_handler()
- Removed Entity Metadata module integration.
- Remove Migrate module support (hook_content_migrate_field_alter()).
- Removed RDFa module support (could be readded with hook_date_formatter_pre_view())
- Removed Microdata module support (could be readded with hook_date_formatter_pre_view())
- Removed Diff module support (should be added into Diff module itself)

Date Popup is still a separate module but I've prepped it for merging it into Date module. I haven't looked at tests, which means I've probably borked them badly.

New PR is located at https://github.com/backdrop/backdrop/pull/1032.

**Comment by serundeputy** [comment] 2015-09-07 12:23
I've tested out the latest updates and all is working well :smile: 

here is a crack at the first two test groups: https://github.com/quicksketch/backdrop/pull/1

@quicksketch can you take a look and see if those are on the right path?

**Comment by quicksketch** [comment] 2015-09-08 06:39
Those changes all look good. I've made the changes manually as the PR was causing some conflicts for me. *Most* tests are now passing. The one area with which I've been having trouble is the configuring of a view to use the Date exposed filters. There's a rather worthless test in Date right now that just builds a view and then loads the view page, but doesn't make any assertions. :P
Anyway, lots more progress. I've merged Date Popup into Date proper so that we're only adding one new module total here.

**Comment by Graham-72** [comment] 2015-09-08 07:26
It is really good to see such progress and to watch a maestro at work. :+1: 
(Though I am wondering what :P means.)

**Comment by klonos** [comment] 2015-09-08 12:40
> Though I am wondering what :P means.

In case you were serious, it's short for :stuck_out_tongue:

**Comment by serundeputy** [comment] 2015-09-08 14:23
Thanks @quicksketch 

I'm still concerned about line (`date_api.test`, line 204):
```php
-    $expected = '1970-01-01T00:00:00+00:00';
+    $t_date = new DateTime("now", new DateTime('America/New_York'));
+    $expected = $t_date->format('c');//'1970-01-01T00:00:00+00:00';
```
Here it looks like the test is testing against unixtimestamp 0, but I'm speculating that backdrop's implementation is storing 0 as now; so I made the test against new DateTime("now", new DateTime('America/New_York')) so if that is the right thing to do we will have to get the test to detect the timezone for the backdrop install.

Is there a way to get that to detect the timezone of the backdrop site rather than hard coding 'America/New_York'?

~Geoff

**Comment by quicksketch** [comment] 2015-09-08 19:02
> Here it looks like the test is testing against unixtimestamp 0, but I'm speculating that backdrop's implementation is storing 0 as now;

This was caused by a change I had made to the BackdropDateTime class, it was indeed a regression because 0 was being interpreted as "now" instead of 1970-01-01 (which is correct, the Unix epoch). This should now be getting these dates correct.

> Is there a way to get that to detect the timezone of the backdrop site rather than hard coding 'America/New_York'?

Sure, it's `config_get('system.date', 'default_timezone')`. Another thing I've changed in this PR is that previously the default timezone was optional (in which case the server-timezone as set in PHP would be used). However it was pretty unusual for it to be empty because the timezone was part of the installation form. I've switched this to default to UTC on new installs if no timezone is specified, so a timezone should *always* be set, rather than being optional. This saves us from needing some of DateAPI's warning messages and hook_requirements() code, and it makes for more reliable timezone treatment across environments for users.

**Comment by serundeputy** [comment] 2015-09-08 21:45
:+1: sounds good!  thank you;

**Comment by quicksketch** [comment] 2015-09-09 22:04
Regarding our upgrade path. @jenlampton and I were talking about how we can manage this, because Date API is a special case that differs from our other modules we've merged into core.

In the case of Token and Path Auto, we were able to simply disable these modules upon upgrade because they were entirely merged.

In the case of CKEditor, Email, and Link, we moved them into core with modules of the same name. This means that contrib versions of these modules will still "win" when users upgrade their site. They'll need to remove the contrib versions of these modules before they use the new core modules. This makes for a safe upgrade where functionality doesn't suddenly disappear or change. The user needs to manually switch between the modules.

In the case of Date API, we have a particular problem with the current pull request in that we moved the contents of `date_api.module` into a `/core/includes/date.inc`. I think that's the most logical location for this API, but unfortunately this would cause a new set of problems for upgrading sites. Because `date.inc` and `date_api.module` would contain the same functions, you'd get a fatal error immediately upon upgrading to 1.2.0. We can't forcibly disable date_api.module though, because the contrib versions of Date, Date Popup, Calendar, etc. all explicitly depend upon `date_api.module`.

Therefore, I think the only way we can guarantee a safe upgrade for users is by moving the `date.inc` file back into Date module. This unfortunately means that modules wanting to use Date API will need to depend on Date module instead of the API always being available as you might expect. However, in the pursuit of compatibility I think this is our only option. We can move date.inc into /core/includes/ in Backdrop 2.x.

**Comment by serundeputy** [comment] 2015-09-09 22:46
> Therefore, I think the only way we can guarantee a safe upgrade for users is by moving the date.inc file back into Date module.

:disappointed: 

this is probably going to make me look silly, but is it possible to just ship with `date` core not enabled, but still give the strong warning message, change log, and publicity?  Maybe we can add to the warning that if you enable core `date` whilst contrib `date` is still enabled you will achieve maximum site blow up?

**Comment by docwilmot** [comment] 2015-09-09 22:48
> the contrib versions of Date, Date Popup, Calendar, etc.

But those don't exist (except for Date). Why not go ahead with moving date API, and let any *new* development modify the code to depend on the `date.inc` API? Then just disable Date as usual?

**Comment by quicksketch** [comment] 2015-09-09 23:23
> But those don't exist (except for Date).

Date Popup, Date All Day, Date Tools, Date Repeat, and Date Repeat Field all exist as sub-modules of the Date project. And even with Date module alone, the contrib version depends upon Date API in a way that would be difficult to emulate as .inc files in core.

If we forcibly disable Date API so that the date.inc file could be used, then the contrib Date module will have a dependency missing. We'd need to have core alter the info file registry to remove the dependencies, but we'd still have some trouble because some functionality of Date API really did belong in Date module (like the SQL object used by the Views integration). So date.inc and date.class.inc don't fully encompass what Date API used to provide.

> Why not go ahead with moving date API, and let any new development modify the code to depend on the date.inc API?

We do have that available as an option, but I'm worried that the setup would be fragile. I'd much rather that the contrib version of Date work independently of the core version of Date, and you just either use one or the other. The only way I can think of doing that is keeping the functionality from Date API in a module (whether that's Date module itself or a core version of Date API as a module).

**Comment by quicksketch** [comment] 2015-09-09 23:31
>  is it possible to just ship with date core not enabled, but still give the strong warning message, change log, and publicity? 

The trouble is that the `core/includes/date.inc` file would always be loaded. So if you have contrib Date API installed, your site would blow up immediately upon upgrading to 1.2.0 because the functions overlap with those in `date_api.module`. Selectively *not* loading the core date.inc file if Date API were present would cause problems, as we're likely to add new functions to date.inc in the future that Date API won't have. Likewise, we can't forcibly disable Date API module and have the contrib version of Date work with the core `date.inc` file, because they don't offer the exact same functionality.

Overall I don't think this is a bad situation, it's just not as clean as I'd hoped for. Modules that need the Date API will just have to depend upon Date module, which seems okay because all current date-related modules do that anyway, since they all need a field to store the dates. We can move date.inc and date.class.inc into the `/core/includes/` directory in 2.x.

**Comment by docwilmot** [comment] 2015-09-10 00:18
I had corrected my mistake re the submodules. 

But I see the issue; not much option, and not that bad a deal really I suppose.

**Comment by quicksketch** [comment] 2015-09-10 02:07
Updated PR: https://github.com/backdrop/backdrop/pull/1032

- Fixes all remaining tests.
- Moves Date API's `date.inc` and `date.class.inc` back into Date module (sad trombone).
- Fixed the Views integration #states usage.

This is looking really great. We still need to finish up the upgrade path and give users a warning as we do for CKEditor, Email, and Link.

**Comment by quicksketch** [comment] 2015-09-10 02:12
> Perhaps a unique collaboration between core/contrib to update Date/submodules to a new 1.2 version before the core port is committed?

I think it would be great if all these submodules were broken out into individual projects. There is a small amount of porting that needs to be done: `dateObject` is now `BackdropDateTime` and of course the Date API dependency will go away (but the dependency on Date remains).

We're really close on this project, but should we be considering pushing until 1.3? We've only got 6 days before release... I think core could be ready but the contrib projects will need some work at the time of release. Perhaps @Graham-72 would have time to split those out (pretty please)? Sort of the *opposite* of the Basic Date module.

**Comment by docwilmot** [comment] 2015-09-10 02:42
I'd lean towards 1.3. This module seems too big to try and push through in 6 days and there are other aspects of Backdrop that would benefit from your attention to get things refined before D8 launches.

But in the end if you feel you could get it done without major consequences, the rest of us can all pitch in to get the contrib sorted. If you want to go ahead, please clearly state ASAP what went in to core and what stayed contrib so we can start.

**Comment by Graham-72** [comment] 2015-09-10 04:12
> Perhaps @Graham-72 would have time to split those out (pretty please)?

Yes, I will gladly spend some time on this.

**Comment by quicksketch** [comment] 2015-09-10 04:31
> Yes, I will gladly spend some time on this.

Woot! I would group them all individually except Date Repeat and Date Repeat Field seem to be fairly bound together, no? I haven't used Date Repeat any time recently. Overall I think this will make for a better system. The lumping together of so much Date functionality seemed a bit excessive for one project.

**Comment by Graham-72** [comment] 2015-09-10 04:40
Am I understanding this correctly? We need a contrib module 'Date Extras' (or some such name) that has everything in it that was in the Drupal Date module except that which we will now have in core?

At the moment I have rather abandoned my port of the full Date. I doubt that anyone is trying to use it. Is there a mechanism for unpublishing a contrib module? Presumably Date Basic would have to be unpublished once it is in core?

That leaves the issue of those trying to upgrade an existing site from Drupal to Backdrop, and need all of Date.

Am I making any sense? It's early in the morning here :smile:

**Comment by Graham-72** [comment] 2015-09-10 12:21
Thinking about this some more, a lot of the extra parts of Date, i.e. those not in Date Basic, are to implement a Calendar. At this stage can we just focus on the things needed to make date fields suitable for a calendar (whatever those things may be) and not include all calendar functionality? So, for example, I could port date_all_day and date_repeat as separate contrib modules, omitting any parts that are specific to displaying on a calendar. Just thinking aloud here really.

**Comment by Graham-72** [comment] 2015-09-10 16:36
I have tried making a start by creating a fork of my port of Date ( https://github.com/backdrop-contrib/date ), renaming it to Date-all-day and deleting all files except those for the Date-all-day module. This new repo is at https://github.com/Graham-72/date-all-day. Unfortunately it seems I cannot change ownership to backdrop/contrib because Github tells me "backdrop-contrib already has a repository in the backdrop-contrib/date network"

So should I start again with a fork of the Drupal Date module? It won't take long to do.

**Comment by quicksketch** [comment] 2015-09-10 17:15
> I could port date_all_day and date_repeat as separate contrib modules, omitting any parts that are specific to displaying on a calendar. Just thinking aloud here really.

Yes, I think making a separate project for each, rather than lumping it all together in "Date Extras" would be a good idea.

> Github tells me "backdrop-contrib already has a repository in the backdrop-contrib/date network"

This is because GitHub tracks whether things are forked through its UI or not. To "disconnect" the tracking, keep your local checkout. Then delete the project in the GitHub UI. Now recreate a project with the same name. Then push up the branch again from local `git push origin date_all_day`. Now GitHub will treat them as individual projects instead of being forks of the same project.

For consistency, I also think it'd be a good idea to name the project "date_all_day" (with underscores) for consistency with our other projects.

**Comment by docwilmot** [comment] 2015-09-10 17:19
I'm probably a bit slow today, but I'm not getting it. 

In the end we will have date in core, and in contrib we will have ??? two separate modules called date_all_day and date_repeat? And would it be those two only or are there any other standalone date modules needing to be created?

**Comment by quicksketch** [comment] 2015-09-10 17:25
> in contrib we will have ?

Three separate projects:

- date_all_day
- date_repeat (which should also include date_repeat_field)
- date_tools(?)

There was also a separate module for date_migrate at one point. I'm not sure what that module does however. If it's integration with migrate module for continuous importing of dates, that might be nice in the future, but right now we don't have a migrate module for Backdrop.

**Comment by Graham-72** [comment] 2015-09-10 19:21
A port of date_all_day is now at https://github.com/backdrop-contrib/date_all_day.

**Comment by Graham-72** [comment] 2015-09-10 20:32
An initial port of date_repeat is now at https://github.com/backdrop-contrib/date_repeat. The project includes date_repeat_field submodule but integration of this has not yet been done.

**Comment by docwilmot** [comment] 2015-09-10 22:28
@Graham-72 I guess we need to test these against backdrop with the date PR applied to get them working. Are you doing that yet? If so do you need me to work on the other, or are you managing? And are you making a date tools repo too?

**Comment by quicksketch** [comment] 2015-09-10 23:49
I updated the PR to account for the inclusion of Link and Email modules. The system_update_xxxx hooks just had to be updated.

We haven't yet included an entry in `hook_requirments()` or in an update hook to notify users like we have done for Link and Email.

**Comment by serundeputy** [comment] 2015-09-11 01:23
* I pulled down the branch `quicksketch/478/date` verified all tests passing on my local.
* Added update hook 1044 in `system.install` to give warning to admins if contrib/date and core/date modules are both present

installed a fresh backdrop-1.1.3 w/ contrib/date contrib/link updated core to 1.x (rc 1.2)

* update.php
<img width="1359" alt="screen shot 2015-09-10 at 9 10 13 pm" src="https://cloud.githubusercontent.com/assets/6763671/9804911/c88b31e0-5800-11e5-8cf3-de5cfe8a00e9.png">

TODO: needs change notice on api.backdropcms.org ; needs update to the link in the notice in `PR`

not sure where/how to implement `hook_requirements()`?

`PR`: https://github.com/quicksketch/backdrop/pull/3

**Comment by Graham-72** [comment] 2015-09-11 04:17
@docwilmot 
>And are you making a date tools repo too?

I will go ahead and do that right now, because I previously did some work on porting this as part of the Date module. So best to reuse this work.

Then I plan to check through all three new repos and see if there is anything obvious I have missed in porting so far.

After that I will start testing. Thanks very much for your offer to help - that will be great. Perhaps after I have done the above?

**Comment by Graham-72** [comment] 2015-09-11 05:10
An initial port of date_tools is now available at https://github.com/backdrop-contrib/date_tools.

**Comment by quicksketch** [comment] 2015-09-11 05:36
> not sure where/how to implement hook_requirements()?

There are already a couple of examples in system.install (CKEditor, Link, and Email). Check the bottom of the `system_requirements()` function, I think that's where they all are.

Those screenshots really make it obvious that these messages might be pretty intimidating to someone updating their site. However, they'll only get a message if they've previously used one of these modules. At this point is it likely or worth worrying about a site that has had two or more of these modules installed, and so would be getting more than one of these (rather long) messages? Or perhaps we should shorten the messages so that they aren't so overwhelming individually and as a group?

> After that I will start testing. Thanks very much for your offer to help - that will be great. Perhaps after I have done the above?

Awesome work everyone! :heart_eyes:

**Comment by Graham-72** [comment] 2015-09-11 05:52
@quicksketch As you will have gathered I am very keen to see date (field) module make it into 1.2 and I am grateful for the work you are doing towards this.

If it doesn't I shall need to deal with remaining issues in date_basic so that can be used with more confidence. (I am using it myself without any significant problems).

My abandoned port of date ( https://github.com/backdrop-contrib/date ) has more serious issues and the fact that no one is reporting these makes me think that no one is trying to use it, and hopefully never will.

**Comment by Graham-72** [comment] 2015-09-11 08:20
Looking through date_tools to check on 'includes' I see this
`
module_load_include('inc', 'node', 'content_types');
`
and I also see it in date/tests/date_field.test, but I don't think there is a file content_types.inc in Backdrop's node module is there?

**Comment by Graham-72** [comment] 2015-09-11 13:03
I have installed the three modules (four if you count date_repeat _field) in a test site along with @quicksketch 's backdrop branch 478/date, and am now doing some testing, reporting problems as issues in the relevant project.

There are tests for date_tools and date_repeat but not date_all_day. @docwilmot if you can spare time to look at one or more of these tests that would be great.

**Comment by klonos** [comment] 2015-09-11 14:34
> At this point is it likely or worth worrying about a site that has had two or more of these modules installed, and so would be getting more than one of these (rather long) messages?

Please have a look at the issue I just filed for that.

**Comment by Graham-72** [comment] 2015-09-11 15:41
Change in CSS seems to have an adverse affect on select lists for entering a date. Where I used to get this
![create story - www oliverweb net 2015-09-11 16-32-34](https://cloud.githubusercontent.com/assets/10559274/9818999/4fe0baaa-58a3-11e5-9f45-df85e4e7e2f6.png)

I now get this
![create basic page - backdrop starter 2015-09-11 16-33-37](https://cloud.githubusercontent.com/assets/10559274/9819005/61860ae4-58a3-11e5-91ad-9b43ceed8d36.png)

I think because we no longer have float:left for .container-inline-date. Is this intended?

**Comment by Graham-72** [comment] 2015-09-11 19:02
I am getting a failure report 'page not found' for date/js/date_range_year.js
I think it is incorrectly named date-range-year.js in the repo?

**Comment by quicksketch** [comment] 2015-09-11 19:18
> I think because we no longer have float:left for .container-inline-date. Is this intended?

Hm, yeah I switched it to be `display: inline-block` for the elements instead of floating, as (usually) that makes for less CSS and no need for RTL styles. On all the pages I've checked, they're still displayed correctly (entering default values, node form, and in Views). Which location is it that you're seeing these displayed incorrectly?

> I am getting a failure report 'page not found' for date/js/date_year_range.js

Yes, I also renamed this to date-year-year.js for consistency with most other core JS files, which use hyphens instead of underscores. I'll update the addition of the JS to use the right name.

**Comment by docwilmot** [comment] 2015-09-11 19:43
> Change in CSS seems to have an adverse affect on select lists for entering a date. 

Getting the same as @Graham-72 
Also noted that `theme_date_combo` isn't being called. Maybe thats part of it?

**Comment by Graham-72** [comment] 2015-09-11 19:53
>Which location is it that you're seeing these displayed incorrectly?

@quicksketch I believe it is in the function theme_date_select_element($variables) in date.theme.inc and shows up when I go to add content at /node/add/page

**Comment by quicksketch** [comment] 2015-09-12 00:09
Thanks guys, sorry about that. I've updated the PR to fix this accidental regression. I re-added a wrapper to get the fields working with #states and accidentally removed that class in the process.

**Comment by quicksketch** [comment] 2015-09-12 01:02
I made a change notice at https://api.backdropcms.org/node/43066 in the event that this happens in 1.2.0. I'll update the PR with @serundeputy's suggestions.

After we decide whether this is go or no-go, we can implement the combined status message for all the merged modules as suggested in https://github.com/backdrop/backdrop-issues/issues/1163.

**Comment by Graham-72** [comment] 2015-09-12 03:09
>I made a change notice at https://api.backdropcms.org/node/43066 

The change notice is excellent thanks, but perhaps you meant to write "Date Repeat (includes Date Repeat Field)" rather than "Date All Day (includes Date All Day Field)" ?
![date date popup and date views modules now included in core - backdrop cms api 2015-09-12 04-01-53](https://cloud.githubusercontent.com/assets/10559274/9829621/e04d264a-5903-11e5-9f31-a2f09a0c17a1.png)

**Comment by quicksketch** [comment] 2015-09-12 03:38
LOL, yes I did.

**Comment by Graham-72** [comment] 2015-09-12 04:28
Sorry, but another situation where we used to have a float left, this time for date and time fields with pop-up.
I think it is in function theme_date_popup($variables)  in date.theme.inc line 440
![create basic page type 2 - backdrop starter 2015-09-12 05-28-05](https://cloud.githubusercontent.com/assets/10559274/9829865/1eb04ce0-590f-11e5-8cfa-bed1633da098.png)

**Comment by Graham-72** [comment] 2015-09-12 05:32
Good news. Project Date Tools now passes all tests in date_tools.test!

**Comment by Graham-72** [comment] 2015-09-12 11:37
Testing date_repeat is looking mostly good but 'stop repeating' on this screenshot doesn't look quite right.

![create basic page type 2 - backdrop starter 2015-09-12 12-35-44](https://cloud.githubusercontent.com/assets/10559274/9831343/f8cfea3a-594a-11e5-8246-b8224362408c.png)

**Comment by quicksketch** [comment] 2015-09-12 18:10
> Sorry, but another situation where we used to have a float left, this time for date and time fields with pop-up.

The date popup seems to display inline for me.

![screenshot16](https://cloud.githubusercontent.com/assets/100206/9833054/3b5e118c-5947-11e5-81bb-af881567fbb4.png)


> I think it is in function theme_date_popup($variables) in date.theme.inc line 440

It looks like `container-inline-date` is in there as it should be:

```
  // Wrap in a div with an ID for #states.
  if (isset($element['#children'])) {
    $element['#children'] = '<div id="' . $element['#id'] . '" class="container-inline-date">' . $element['#children'] . '</div>';
  }
```

**Comment by Graham-72** [comment] 2015-09-12 22:02
>The date popup seems to display inline for me.

Yes, apologies, it is fine now. I guess I should have cleared caches and tried again before thinking it was wrong.

**Comment by quicksketch** [comment] 2015-09-13 19:24
I'm definitely leaning towards putting this in (as soon as today). I think we've done a great job getting this to a core-appropriate state. I think we have more to gain from including this sooner rather than later.

Advantages: We have Date in core right away, making for better out-of-box experience. And honestly, makes Backdrop compare more favourably to D8. We solidify a target for contrib. And all @Graham-72's new modules will work immediately against 1.2.0 instead of working against nothing but a dev version of Backdrop that won't be out for 4 months.

Disadvantages: This is a bit rushed and we probably have some bugs that we have introduced. We will be committing to the API for a long time as it stands now.

However, regarding the disadvantage of the API being "frozen" after putting in core, I don't think that's any different from our current situation. Our commitment to compatibility from D7 has made it so that our Date API functions already cannot be changed significantly. So whether Date is in core or contrib, we already are committed to minimizing API changes. Leaving the only real disadvantage that we probably have bugs that we have not discovered. We can fix this in bug fix releases.

**Comment by Graham-72** [comment] 2015-09-13 19:32
I am strongly in favour!

People will be expecting to use date fields and, IMHO, what we now have ready for core is better than having to rely on Date Basic.

**Comment by docwilmot** [comment] 2015-09-13 20:05
Go for it.

**Comment by serundeputy** [comment] 2015-09-13 20:56
:+1: do it!

**Closed** 2015-09-13 21:15 UTC
Labels: status - has pull request, type - feature request

**Comment by quicksketch** [comment] 2015-09-13 21:17
Okay then! https://github.com/backdrop/backdrop/pull/1032 has been merged! Let's file followups separately for any fixes yet to be made.

Thanks again @Graham-72 for all the great work making this happen! And the reviews/PRs/collaboration from everyone. So proud of our community. :smile:

**Comment by serundeputy** [comment] 2015-09-13 21:19
woohoo! nice work @Graham-72 and everyone!  :hand:

**Comment by docwilmot** [comment] 2015-09-13 21:21
Yay! Well done all.

**Comment by klonos** [comment] 2015-09-13 23:30
Well done indeed :+1:

**Comment by wesruv** [comment] 2015-09-14 00:08
w00000t!

**Comment by Graham-72** [comment] 2015-09-14 04:34
It is a pleasure to be part of this team and does wonders for the grey cells. 1.2 is really exciting, so much has been achieved.

**Comment by sutibun** [comment] 2015-09-14 04:54
Yay, we did it.

**\*everybody stops and stares disapprovingly\***

Fine. i didn't do anything...

**\*slowly exits stage left\***

**Comment by jenlampton** [comment] 2015-09-28 07:47
@sutibun no, *we* did it, and *you* are a part of *we*

Go team!

**Comment by sutibun** [comment] 2015-09-28 08:10
__\*returns back and jumps in the air\*__ yay! \\(^\_^)/
