### ISSUE TITLE
Port and merge Entity API in core (feature parity with D8).

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1371] opened 2015-11-26 18:51 UTC
This is part of the #378 META.

[Entity API](https://www.drupal.org/project/entity) is reported to be used in [more than 575k sites](https://www.drupal.org/project/usage/entity) (that's more than 50% of [D7 installations](https://www.drupal.org/project/usage/drupal)) and has been merge in D8 core.

@docwilmot has started a rough port of it because it is a prerequisite of the RESTful Web Services module. Here's the related issue in contrib: https://github.com/backdrop-ops/contrib/issues/119

**Comment by mikemccaffrey** [comment] 2015-11-28 19:13
Isn't this not needed since the Entity API was integrated into core as part of #49? What functionality does RESTful need that isn't currently being supplied by core?

**Comment by Graham-72** [comment] 2015-11-28 22:07
When I was porting Rules (and it now needs some revision) I had to confront the absence of certain Entity functions in Backdrop. My assistance from @quicksketch is recorded at https://github.com/backdrop-ops/contrib/issues/71 . So I am not surprised to hear that RESTful needs more. Perhaps I should compare needs with @docwilmot ?

**Comment by docwilmot** [comment] 2015-11-28 22:23
RESTful needed the wrapper code.

That post was not about including entity module in core, since, add you note it's already there, but rather about how much of the residual entity code should remain if one ported the wrapper code to a new contrib module, as I've started. 

Thanks for that link though, @Graham-72, I note that there were in fact suggestions to bring those 'residual' functions into core in fact. So I'll keep them out of the emw module.

**Comment by mikemccaffrey** [comment] 2015-11-29 19:58
I think that part of the problem is that the Entity API module does quite a bit of different things, so we have no idea how much or what parts of the entity module are being used by the multitude of contributed modules that list it as a dependency.

Would it perhaps be helpful to list out all of the different functions provided by the Entity API, so we can decide how to handle each part? 

Here is a start:
- base entity class (already moved into core)
- entity controller class (already moved into core)
- entity wrapper classes
- entity ui to generate an admin page listing all the entity items
- entity property functions to make entities fieldable
- views integration
- features integration
- rules integration
- token integration
- internationalization

Am I missing things? Does anyone have a better way to divide the functionality into a list of features that entity provides?

**Comment by mikemccaffrey** [comment] 2015-11-29 20:10
Also, I'd have to say that I personally think that we should avoid the wrapper classes if possible. Drupal developers are used to accessing object properties directly, and forcing them to use functions to get and set values would create a huge burden on the community, and doesn't actually make anything simpler.

This post is a great example of how the reality of wrappers doesn't match up with the promises:
https://www.drupal.org/node/1388922

It says "The same result can be achieved with the contrib Entity API module but with fewer lines of code, better clarity, and less trouble from language / translation issues", but the version of the code that uses the Entity API is actually six lines of code longer and requires a ton of additional comments to explain what is happening.

**Comment by docwilmot** [comment] 2015-11-29 22:53
This may be an example of the difference between real developers and the amateur lot like me. I truly liked the EMW concept. 

I think at least it would be nice if it was available in contrib. And if it was, I wouldnt need to change the RESTful code. So I anxiously await more feedback from this. Thanks @mikemccaffrey.

As far as your list goes:
- base entity class (already moved into core)
- entity controller class (already moved into core)
- entity wrapper classes
- entity ui to generate an admin page listing all the entity items
- entity property functions to make entities fieldable (I thought entities were already fieldable?)
- views integration (I think this in in too?)
- features integration
- rules integration 
- token integration (entity tokens are in?)
- internationalization

**Comment by docwilmot** [comment] 2015-12-11 15:17
So it seems the only things left would be Entity UI and EMW, both of which could comfortably live in contrib I'd say. 
Closing this issue then; please re-open if you feel more work needs to be done here.

**Comment by klonos** [comment] 2015-12-21 05:19
Sorry to re-open, but I think I have found something that might have been left out. See #1440 that I have just filed.

**Comment by mikemccaffrey** [comment] 2016-02-22 19:20
@klonos Did you track down the cause of #1440? How do you know that it is something to do with missing features in the Entity API?

I'm going to close this ticket in favor of a new Entity API meta ticket.

**Closed by mikemccaffrey** 2016-02-22 19:20 UTC
