### ISSUE TITLE
Manual installation problem

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2080] opened 2016-08-19 16:23 UTC
I have wrote about this in May https://github.com/backdrop/backdrop-issues/issues/1920
Almost 3 months left and the problem still exist even in BD 4.4 I have installed an hour ago.
It is nice.

**Comment by BWPanda** [comment] 2019-10-30 04:18
Marking this as a duplicate of the linked issue, which has been fixed.

**Closed** 2019-10-30 04:19 UTC
Labels: status - duplicate
