### ISSUE TITLE
Home page layout shown as overridden on fresh installations.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2635] opened 2017-04-11 20:01 UTC
I think that this is a side-effect of the way we chose to update the existing layout when we've introduced the full bleed hero block (#2190). Is there a way to fix this? What happens when the user reverts the layout to its default?

**Comment by jenlampton** [comment] 2017-04-13 23:32
> What happens when the user reverts the layout to its default?

The site name reverts back to "Backdrop CMS". 

This is a duplicate of an issue I opened, I think with the same title.  IIRC we decided that this was the desired / intended behavior, and closed that issue :) Should we close this one too?

**Comment by klonos** [comment] 2017-04-15 00:13
Yes, I think it makes sense. Would be cool if we could use tokens in title fields and have the default (module-provided) value be `Welcome to [site:name]`. That way, we could leave the hero block as is during installation and reverting the block would only revert blocks and layout settings.

**Closed** 2017-04-15 00:14 UTC
