### ISSUE TITLE
Refer to "About us" page as "About" page and clean up page content type description to match.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2210] opened 2016-09-18 12:12 UTC
Is it "About" or "About us" page? ...I think plain "About" page, because we shouldn't be assuming a company or organization - it could be the "About **me**" page of a personal site.

The description for the `page` content type](https://github.com/backdrop/backdrop/blob/1.x/profiles/standard/standard.install#L120) is:

  `'description' => st("Add a page for static content, such as an 'About us' page."),`

  How about changing this to "Add a page **with** static content, **like the** 'About us' page." instead (emphasis on the changes)? ...reasoning: with the addition of actual out-of-the-box content in 1.5.0, it is not *an* "About us" page - it is *the* "About us" page. Also, if we go with "About" page instead of "About us", the final text should be "Add a page **with** static content, **like the** 'About' page."

---

PR by @klonos: https://github.com/backdrop/backdrop/pull/1590

**Comment by jenlampton** [comment] 2016-09-22 22:15
> Also, is it "About" or "About us" page?

I agree, it's an "About" page.

> How about changing this to "Add a page with static content, like the 'About us' page." instead 

Love it. I don't even mind the "us" in that example, but we can kill it to be consistent if you like. 

Also, this is not a bug and not urgent enough for 1.5.1. Removing tag/milestone.

**Comment by klonos** [comment] 2016-09-26 16:00
The "sibling" issue #2218 went in, so I filed a PR for this one:

![backdrop-issue2210-pull1590](https://cloud.githubusercontent.com/assets/2423362/18841804/3872dbca-8456-11e6-83e6-caa9c8c8a0ad.png)

**Comment by quicksketch** [comment] 2016-10-16 23:20
Thanks, merged https://github.com/backdrop/backdrop/pull/1590 for 1.5.1.

**Closed** 2016-10-16 23:20 UTC
Labels: pr - needs review, status - has pull request, type - documentation
