### ISSUE TITLE
Fix ordering issues in admin menu

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#2655] opened 2017-04-26 23:31 UTC
**Status update (8th Jan)**

The PR is passing all tests and seems to be working nicely. There have been multiple reviews (of different versions), but the latest version has been marked RTBC, so I think this is good to go!

---

In #2502 @olafgrabienski pointed out that the content type ordering is inconsistent in the admin bar:

> Looks good at first view. Then I've seen another place where the content types don't sort correctly: The *Add content* links in the Admin bar seem to not being ordered at all:

![screen-backdrop-pr-1809-sort-order-add-content-admin-bar](https://cloud.githubusercontent.com/assets/14188307/25426081/5037dd14-2a6e-11e7-81c6-1b219449c9a8.png)

Let's examine, identify weird or inconsistent ordering in admin menu and decide what to do about it in this issue.

---

PR by @BWPanda: https://github.com/backdrop/backdrop/pull/2851

**Comment by olafgrabienski** [comment] 2017-05-06 21:14
@jenlampton You mentioned in the other issue that you've noticed more places with strange sort order in the Admin bar. Do you remember which and where?

**Comment by jenlampton** [comment] 2017-05-06 23:11
* Configuration > Development (Configuration management at the bottom?)

**Comment by jenlampton** [comment] 2017-05-06 23:14
There should be custom orders in some places, but I don't think all these places call for them.

**Comment by olafgrabienski** [comment] 2017-05-09 20:25
Here's another strange order, as far as I remember, it's only on one of my sites: The sub-items of *Configuration* are sorted alphabetically, but *Media* is at the top:

![screen-backdrop-adminbar-configuration](https://cloud.githubusercontent.com/assets/14188307/25870960/349f06ca-3506-11e7-9ae3-9e34687651d9.png)

**Comment by olafgrabienski** [comment] 2017-05-09 20:33
... Speaking of which, on various sites with German localization, there is the item *Lokalisierung und Sprache* (*Regional and language*) at top of the *Konfiguration* (*Configuration*) sub-items:

![screen-backdrop-adminbar-konfiguration](https://cloud.githubusercontent.com/assets/14188307/25871288/45e78ece-3507-11e7-83f3-de3ba7c8bf1a.png)

**Comment by olafgrabienski** [comment] 2017-07-13 09:54
Another example for a strange sort order: I added three date fields to the *Post* content type, and that's the resulting sort order in the Admin bar:

```
Date
Body
Date 2
Tags
Image
Date 3
```
Screenshot:

![screen-backdrop-admin-menu-order-date-fields](https://user-images.githubusercontent.com/14188307/28160773-82cd1ccc-67c1-11e7-926e-7b4bb7e1bb74.png)

**Comment by BWPanda** [comment] 2019-09-05 05:50
I've since been having the same issue as https://github.com/backdrop/backdrop-issues/issues/2655#issuecomment-300290595 where Media appears first in the list. Marking this as a bug.

**Comment by BWPanda** [comment] 2019-09-06 10:31
I believe I have fixed this! Here's a [PR](https://github.com/backdrop/backdrop/pull/2851).

Explanation:

The problem lies with the custom `backdrop_sort()` function. This wasn't present in Drupal, and appears to have been written to cover various sorting needs. The function has 3 sections:

1. *Ensure all keys have a sort value.*
  This section deals with the `$keys` parameter and allows for variations thereof (fixing missing values, etc.).
2. *If sorting on a single value, optimize the sorting to sort only on that specific key without the overhead of recursive handling.*
  This section is for basic sorts that only have one sort key. It's meant to optimise sorting, preventing the unnecessary need for recursion here.
3. *If doing a multiple-key comparison, use a recursive callback.*
  This section is the recursive sort. It's what's used for this issue (sorting the admin menu). This is where my efforts were focused.

I had an array I was using for my testing - it's an array of the Configuration menu from one of my sites where this issue has cropped up (where the 'Media' link is displayed first). I was able to simplify the array down to just the necessary parts that meant when it was run through `backdrop_sort()` it was out-of-order ('Media' displayed first). Interestingly, making minute changes caused the bug to go away and the array to be sorted correctly. These changes didn't seem to be anything definite, meaning the bug seems somewhat random (as explained also by reports from others above experiencing it).

I initially tried re-writing parts of the sort function that I thought were causing the issue, however they didn't make any difference to my test array. I thought the issue was with comparing strings using `==` rather than proper string comparison functions, but my fixes just weren't working. In the end I couldn't figure it out as it seems to be a deeper issue with the Quicksort algorithm PHP uses under the hood (not that it's the problem (I'm sure it's very robust), but rather the way `backdrop_sort()` uses it). Anyway, very hard to figure out!

After spending hours with this, I finally decided that there must be a better way to sort arrays by various keys. I searched the web and came across this StackOverflow Q&A: https://stackoverflow.com/questions/3232965/sort-multidimensional-array-by-multiple-keys. The answer (using `array_multisort()`) is what I tried and ultimately worked. I re-wrote section 3 of `backdrop_sort()` to use `array_multisort()` instead, and to allow for any number of sorting keys. I then decided that I could remove section 2 and just have all sorts use the same bit of code. Might need performance testing here to make sure things haven't gotten worse as a result, but I don't think it should affect performance for simple or multi-key sorts...

So `backdrop_sort()` has been greatly simplified, and my test array now sorts correctly. Another array that was already sorting correctly before my PR still sorts correctly afterwards (so that's good!).
If you experienced weird sorting issues previously, please test and let me know if it's fixed now.

**Comment by BWPanda** [comment] 2019-09-06 10:34
Here's the simplified test array I was using (after sorting, 'Media' was being displayed at the top of the list, above 'Administration'). You can copy-and-paste this code into Devel's Execute PHP Code field to run.

```php
$array = array(
  '#title' => 'Configuration',
  '#href' => 'admin/config',
  '#options' => array(),
  '#weight' => '0',
  'admin/config/system' => array(
    '#title' => 'System',
  ),
  'admin/config/urls' => array(
    '#title' => 'URL handling',
  ),
  'admin/config/people' => array(
    '#title' => 'User accounts',
  ),
  'admin/config/development' => array(
    '#title' => 'Development',
  ),
  'admin/config/media' => array(
    '#title' => 'Media',
  ),
  'admin/config/search' => array(
    '#title' => 'Search',
  ),
  'admin/config/regional' => array(
    '#title' => 'Regional and language',
  ),
  'admin/config/administration' => array(
    '#title' => 'Administration',
  ),
  'admin/config/content' => array(
    '#title' => 'Content authoring',
  ),
  'admin/config/metadata' => array(
    '#title' => 'Metadata',
  ),
  'admin/config/user-interface' => array(
    '#title' => 'User interface',
  ),
  'admin/config/services' => array(
    '#title' => 'Web services',
  ),
  'admin/config/workflow' => array(
    '#title' => 'Workflow',
  ),
  '#is_category' => true,
  '#attributes' => array(),
);
backdrop_sort($array, array('#weight' => SORT_NUMERIC, '#title' => SORT_STRING));
dpm($array);
```

**Comment by BWPanda** [comment] 2019-09-06 13:14
Need help with fixing tests I think. Can't see why they're failing...

**Comment by BWPanda** [comment] 2019-09-06 13:16
Also, just gonna put this link here for future reference: https://git.drupalcode.org/project/admin_menu/blob/7.x-3.x/admin_menu.module#L840
That's how Drupal did the sorting. Could use that as a backup in case all else fails :wink:

**Comment by olafgrabienski** [comment] 2019-09-09 20:39
I've applied the PR to one of my test sites, and it fixed the issues I had:

- https://github.com/backdrop/backdrop-issues/issues/2655#issuecomment-300290595
  Sub-items of *Configuration* sorted alphabetically (as expected), but *Media* was at the top.
- https://github.com/backdrop/backdrop-issues/issues/2655#issuecomment-315031240
  Multiple date fields on *Post* content type, resulting in wrong sort order (Date / Body / Date 2 ...).

**Comment by klonos** [comment] 2019-12-22 20:14
I am in need to be able to sort objects by their `weight` (filter text format objects to be precise), and `backdrop_sort()` seems to be an almost perfect fit (in theory), because you can do this:

`backdrop_sort($my_array, array('weight'));`

...but I would like to be able to do this:

`backdrop_sort($my_array_of_objects, array('weight'));`

In other words, I would like to have `backdrop_sort()` extended to support arrays that hold objects with `weight` properties.

**Comment by klonos** [comment] 2019-12-22 20:56
> I am in need to be able to sort objects by their `weight`...

Never mind. It turns out that `backdrop_sort()` already supports that 🙂 ...still interested in this issue.

**Comment by BWPanda** [comment] 2019-12-27 19:18
I just spun up a demo site from B.org and the menu ordering issue is present there:

![image](https://user-images.githubusercontent.com/2385329/71529501-b0fdba80-28ed-11ea-85e1-0ef6b206359d.png)
(note the Media item at the top, above Administration, etc.)

This is a fresh site with no changes made since the install process finished. I therefore think this bug deserves more attention than it's been getting. Since it's a bug I can't advocate for it, so I guess the only option is to ask someone to second my milestone request and set an actual milestone for this so it can get more attention in the weekly meetings, etc.

Status is that the PR needs further testing (it seems that it fixes the bug, but need to make sure it doesn't break anything, and it's be good to get some performance stats on the new sorting method), and tests need fixing.

**Comment by olafgrabienski** [comment] 2019-12-27 22:20
I second the milestone request and have added the 1.14.3 milestone.

Have also added "pr - works for me" as of https://github.com/backdrop/backdrop-issues/issues/2655#issuecomment-529656693. @BWPanda Do you have something in mind to test to make sure the PR doesn't break anything?

**Comment by jenlampton** [comment] 2019-12-28 00:27
We'll need benchmarks if we are going to change `backdrop_sort()`. This function is used widely and IIRC previously optimized for speed. Since sorting things can be slow, we'll want to make sure we're not accidentally introducing a regression.

If it looks like this does change the site speed drastically, we could put a copy of this improved function directly into admin_bar so that we can get what we need for the menus.

**Comment by jenlampton** [comment] 2019-12-28 00:29
> set an actual milestone for this so it can get more attention in the weekly meetings

Most bug-fix issues don't make the weekly meetings, we'll need to add this one to the agenada...  doing that now.

**Comment by BWPanda** [comment] 2019-12-28 05:12
Thanks @olafgrabienski & @jenlampton

**Comment by BWPanda** [comment] 2019-12-28 05:41
I'd be interested to try the performance testing, but I don't know how. Can someone give instructions? Is a special program used for example?

**Comment by BWPanda** [comment] 2019-12-28 05:43
> Most bug-fix issues don't make the weekly meetings

Ah, I'm getting confused with feature requests/advocation I think. Sorry.

**Comment by quicksketch** [comment] 2020-01-02 21:02
The new version of `backdrop_sort()` seems as though it may be better. Usually PHP's internal functions operate more efficiently because they're written in C.

To benchmark this, we can set up a PHP script that does a large sort in a few different varieties, then use timer_start() and timer_stop() to measure how long it takes to execute the script before and after the changes. For more complicated profiling we can use Tideways or Blackfire.io, but since this is a single function, just explicitly timing it and then running the script a few times will be just as good and less hassle.

Unfortunately tests are failing on this though. We're getting a few PHP warnings and perhaps even some different (incorrect?) sorting results.

**Comment by BWPanda** [comment] 2020-01-03 08:36
No idea if this is the correct way to do it, but here's what I tried:

- `git checkout` `1.x` branch, cleared all caches
- Ran the below code in `/admin/devel/php` 5 times with the following results: 1468.73, 1.41, 1.11, 1.48, 1.49 (average: 294.844)
- `git checkoutl` `issue-2655` branch, cleared all caches
- Ran the below code in `/admin/devel/php` 5 times with the following results: 1343.97, 1.9, 1.02, 1.14, 0.94 (average: 269.794)

```php
module_load_include('inc', 'admin_bar');
timer_start('2655');
admin_bar_output();
timer_stop('2655');
dpm(timer_read('2655'));
```

**Comment by BWPanda** [comment] 2020-01-03 13:05
Woot! Latest commit fixes 42 of the 43 test failures!

Problem was that numeric keys were being re-indexed (as stated on PHP's [`array_multisort`](https://www.php.net/manual/en/function.array-multisort.php) page). Solution is to prefix each key, then sort, then remove the prefix again.

Now to fix that last failure...

**Comment by BWPanda** [comment] 2020-01-03 14:10
Fixed the last test failure! This was actually a bug in the test...

The test was checking if changes to the order of text filters in the interface were saved correctly to the database. It used to get the list of filters from the DB ordered by weight, then make sure they were in the correct order. However when filters were converted to config, there was never any code added to sort the filters after loading from config before checking the order (this can be seen here: https://github.com/backdrop/backdrop/commit/7d7cb66c80b310c6f453ce900a9868c3859ca7ab#diff-d5374d0f8c0269e7ab21ed07ef9f4fbcL294).

The test was previously working by sheer luck I think. In that after loading filters from config and checking the order of two of them, they were fine, but the rest weren't in order (though they were never checked).

The fix was to sort the filters by weight after loading from config.

**Comment by BWPanda** [comment] 2020-01-03 14:54
Now that tests are passing, trying performance testing again. Running this in `/admin/devel/php`:
```php
module_load_include('inc', 'admin_bar');
timer_start('2655');
for ($i = 0; $i < 1000; $i++) {
  admin_bar_output();
}
timer_stop('2655');
dpm(timer_read('2655'));
```

Result from `1.x` branch: 32,922.41
Result from `issue-2655` branch: 33,349.38

So... Maybe needs performance tuning?

**Comment by herbdool** [comment] 2020-01-03 16:03
I ran each branch a few times with your last example, and there seems to be a lot of variation in times. The variation is too high to know which is faster.

I upped it to looping 10000 and got this:

**1.x:**
8995
8333
8445
8365
8749
8672

**issue-2655:**
8192
8534
8917
8327
8579
8644

My numbers are lower, perhaps because I was running it locally.

**Comment by BWPanda** [comment] 2020-01-03 18:35
Thanks for that! I think it's not the numbers themselves that are important, but the comparison between the two.

**Comment by hosef** [comment] 2020-01-03 18:50
I think that `admin_bar_output()` is a bad function to use if you want to test the performance of `backdrop_sort()`.
First, the content is cached several times during the process of generating the menus, so it will only sort one time unless you put something like `cache('menu')->flush();` inside your loop.
Second, I ran the test with a profiler and compared to the amount of time spent on the database queries to load the menu the backdrop_sort function was barely noticeable.

I think this is a more accurate test to get the timing of just `backdrop_sort()`.
`
$tree = menu_tree_output(menu_tree_all_data('management'));
timer_start('2655');
for ($i = 0; $i < 50000; $i++) {
  $copy = $tree;
  backdrop_sort($copy, array('#weight' => SORT_NUMERIC, '#title' => SORT_STRING));
}
timer_stop('2655');
dpm(timer_read('2655'));
`

**Comment by hosef** [comment] 2020-01-03 18:59
As for the times I got with the test running 5 times on each branch:
1.x:
675
631
633
642
637

issue-2655:
212
193
206
201
206

**Comment by BWPanda** [comment] 2020-01-03 19:28
Thanks for the tips @hosef. That got me thinking: we don't actually need the admin menu per se, just any large array. So I checked the database to see what table had the most records, and it's the `menu_router` table (with 466 records). So I searched the API site and found the [`menu_get_router()`](https://api.backdropcms.org/api/backdrop/core%21includes%21menu.inc/function/menu_get_router/1) function that returns an array with all those records. So I tried this:
```php
$array = menu_get_router();
timer_start('2655');
for ($i = 0; $i < 10000; $i++) {
  $copy = $array;
  backdrop_sort($copy, array('weight' => SORT_NUMERIC, 'path' => SORT_STRING));
}
timer_stop('2655');
dpm(timer_read('2655'));
```

And here are results:

**1.x**
38705.17
38527.09
39459.39

**issue-2655**
6544.71
6553.77
6556.56

Unless I did something wrong, they seem quite telling...

**Comment by hosef** [comment] 2020-01-03 19:59
Yeah, I suspect that `array_multisort()` is much more efficient than the PHP based sorting we were doing before, and probably the performance improvement will grow as the arrays get larger.

**Comment by BWPanda** [comment] 2020-01-03 20:16
Same thing with a simple array:
```php
$array = array(
  array('name' => 'cat'),
  array('name' => 'dog'),
  array('name' => 'tiger'),
  array('name' => 'lion'),
  array('name' => 'bird'),
  array('name' => 'bat'),
  array('name' => 'dragon'),
  array('name' => 'panda'),
  array('name' => 'seagull'),
);
timer_start('2655');
for ($i = 0; $i < 100000; $i++) {
  $copy = $array;
  backdrop_sort($copy, array('name' => SORT_STRING));
}
timer_stop('2655');
dpm(timer_read('2655'));
```

**1.x**
869.13
864.62
864.68
857.35
859.1

**issue-2655**
787.45
772.85
764.02
756.8
759.67

**Comment by BWPanda** [comment] 2020-01-03 20:32
FTR, here's when the `backdrop_sort()` function was originally written and performance tested against the existing sorting functions: https://github.com/backdrop/backdrop-issues/issues/401 (just in case that's helpful...)

**Comment by indigoxela** [comment] 2020-01-04 11:13
I couldn't reproduce the problem with (un-)ordered content types or content type fields in admin menu or on overview page on any of my sites.

I can, however, reproduce the problem with _some_ weirdly ordered items in admin menu. ("Media" on top, "Lokalisierung ..." (de) on top).
And I can confirm that the PR fixes this odd behavior.
I compared with other testing/dev B1 instances.

As backdrop_sort() is widely used in Backdrop, I tried to find another sorting problem somewhere in core (token list, simpletest list...) - nothing suspicious so far.

One thing is strange, though: the status page ordering.
Without that patch sorting seems to be case insensitive (look for "jQuery" and "cUrl" positions), with that patch the sorting seems case sensitive (uppercase before lowercase). Can someone confirm this or am I missing something?

Cautious "works for me" from my side. (And a huge :+1: for @BWPanda )

**Comment by BWPanda** [comment] 2020-01-04 11:50
Thanks @indigoxela! I can confirm the case-sensitive sorting (the default scenario with the new PHP function we're using). Since Backdrop sorted case-insensitively before, I've made a new commit to the PR that does this.

**Comment by indigoxela** [comment] 2020-01-04 12:20
> I've made a new commit to the PR that does this.

@BWPanda yep, that does the trick. String sorting is case insensitive again.

**Comment by BWPanda** [comment] 2020-01-04 18:58
Oops, so the method I used for making the sort case-insensitive is only available in PHP v5.4+. Therefore the PHP v5.3 tests are failing all over the place. Need another way to do this (which I have an idea about), just leaving this note here as a reminder for myself of what I need to do when I get back to this.

**Comment by BWPanda** [comment] 2020-01-06 00:47
New commit changes method of doing case insensitive sorts. All tests passing!

**Comment by docwilmot** [comment] 2020-01-06 01:14
Hadnt really looked at this issue until now, wondering if this was the same problem I had while adding sort direction to that function and if this PR addresses that bug? Probably does, since we're ditching `uasort()`. Just curious @BWPanda, see https://github.com/backdrop/backdrop-issues/issues/2149#issuecomment-247859794.

**Comment by BWPanda** [comment] 2020-01-06 07:12
@docwilmot The [function](https://www.php.net/manual/en/function.array-multisort) we're now using says:

> If two members compare as equal, their relative order in the sorted array is undefined.

So I imagine it's the same situation as before - can't guarantee order of identically weighted items...

**Comment by BWPanda** [comment] 2020-01-06 11:35
If I run the performance test code from https://github.com/backdrop/backdrop-issues/issues/2655#issuecomment-570673669, I get the following:

**1.x:** 41111.9
**issue-2655:** 40503.75

The difference in results from when I originally ran the same code above is because the PR now uses `backdrop_strtolower()` (for case-insensitive sorting). If I change it to use PHP's `strtolower()` instead, I get this:

**issue-2655:** 7803.69

Which is much better (and closer to the previous results). So I'm wondering if we need to use Backdrop's version, or is PHP's version ok to use for better performance?

**Comment by indigoxela** [comment] 2020-01-06 12:28
Maybe off-topic, but just for the records: if you compare _mb_strtolower()_ in your performance test run - is it slower than strtolower()? Faster than backdrop_strtolower()?

I suspect, preg_replace_callback() is the slow part in backdrop_strtolower().

**Comment by herbdool** [comment] 2020-01-08 16:58
I've tested the latest PR. I tried the two different approaches that @hosef and @BWPanda pasted above. Each one gives quite different results. The first is roughly twice as slow with the PR. The second is almost an order of magnitude faster with the PR. Quite different.

1:

```
$tree = menu_tree_output(menu_tree_all_data('management'));
timer_start('2655');
for ($i = 0; $i < 50000; $i++) {
  $copy = $tree;
  backdrop_sort($copy, array('#weight' => SORT_NUMERIC, '#title' => SORT_STRING));
}
timer_stop('2655');
dpm(timer_read('2655'));
```

1.x:
• 399
• 450
• 467
• 435
• 448
• 436

issue-2655:
• 854
• 961
• 1076
• 1069
• 973
• 960

-----------
2:

```
$array = menu_get_router();
timer_start('2655');
for ($i = 0; $i < 10000; $i++) {
  $copy = $array;
  backdrop_sort($copy, array('weight' => SORT_NUMERIC, 'path' => SORT_STRING));
}
timer_stop('2655');
dpm(timer_read('2655'));
```

1.x:
• 37413
• 39795
• 40599
• 38317

issue-2655:
• 5173
• 5091
• 5215
• 5170

**Comment by herbdool** [comment] 2020-01-08 17:18
Just to be sure about the second test, I took the output of `menu_get_router()` and put it into a json string. Then each time the script decodes json and runs `backdrop_sort`. I got the same order of magnitude.

**Comment by BWPanda** [comment] 2020-01-08 18:54
Thanks for testing and reviewing @hosef! I'm confused by your performance results though... The only time I got similar results to your second case was when using `strtolower()`. When using `backdrop_strtolower()` then I got results that weren't much different from each other...

But hey, it's not a regression so I'm happy :smile:

**Comment by herbdool** [comment] 2020-01-08 22:24
@BWPanda did you mean to mention me? Maybe I should check `global $multibyte` since the fallback is `strtolower()`. Though I'm using stock Lando which is PHP 7.x and recent Mysql.

**Comment by BWPanda** [comment] 2020-01-09 04:37
> did you mean to mention me?

Oops, yes :smile: Edited.

**Comment by BWPanda** [comment] 2020-01-10 07:19
@klonos asked a question in the dev meeting about whether menu items that need to be sorted non-alphabetically (or otherwise out-of-order) are still able to do so with this PR. He gave the example of the Views menu and the Settings item being up the top. I've checked this with the PR version, and Settings is towards the bottom of the Views menu. But I also checked it with the `1.x` branch and it's the same there too, so this might be a bug elsewhere in core...?

**1.x:**
![image](https://user-images.githubusercontent.com/2385329/72133409-fad4af00-3389-11ea-9a46-c36785119288.png)

**This PR:**
![image](https://user-images.githubusercontent.com/2385329/72133442-1770e700-338a-11ea-8476-ba879a8d12e7.png)

So this PR seems to be ok in what's it's doing (changing what needs changing and not affecting what should stay the same). But the order of some sub-menus might be another issue.

**Closed** 2020-01-15 21:43 UTC
Labels: pr - ready to be committed, pr - works for me, status - has pull request, type - bug report

**Comment by quicksketch** [comment] 2020-01-15 21:46
Thanks everyone! I merged https://github.com/backdrop/backdrop/pull/2851 into 1.x and 1.14.x. Great work @BWPanda on figuring out a completely different way to accomplish the same thing. Thanks @hosef, @indigoxela, and @herbdool for doing those benchmarks, much appreciated! And thanks @serundeputy, @olafgrabienski, and @klonos for reporting and duplicating the issue.
