### ISSUE TITLE
Rename DISABLE to DELETE in Text editors and formats

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1768] opened 2016-03-31 05:22 UTC
If we add new text editor then then there is word DISABLE if we want to DELETE it.
It should be renamed to DELETE, right?
Because currently new text editor will be deleted and not disabled if we click DISABLE link.

![untitled-1](https://cloud.githubusercontent.com/assets/13515302/14166187/cf05bdfc-f719-11e5-82a6-f5203cd33175.png)

**Comment by quicksketch** [comment] 2016-03-31 08:41
This is a duplicate of #1575. Please see that issue as to why it's Disable and not Delete.

**Closed by quicksketch** 2016-03-31 08:41 UTC
Labels: status - duplicate

**Comment by klonos** [comment] 2016-03-31 08:44
I think you are right @bd0bd. The action will *remove* the text editor. As the warning message says:

> Disabled text formats are completely removed from the administrative interface, and any content stored with that format will not be displayed. This action cannot be undone.

I do not know why the decision was made to use the word "disable" when what is happening is clearly that the text format is completely removed. I think that the word "disable" implies that the action can be reverted by "enabling" the feature again. I'm sure there is some reasoning behind this. Lets wait for a reply from someone that has better knowledge on the matter.

**Comment by quicksketch** [comment] 2016-03-31 19:16
I think we may have posted at nearly the same time. There is an explanation in https://github.com/backdrop/backdrop-issues/issues/1575. Let's keep the conversation in that thread.
