### ISSUE TITLE
[DX] Place hook_block_* API Explanation In The Block Module

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop/backdrop-issues#3196] opened 2018-07-12 22:46 UTC
I was looking for the block API hooks, couldn't find them in the Block module, and then I saw them in the Layout module.

I think they should be placed back in the Block module's directory or renamed "hook_layout_*" with all of the other Layout hooks. 

I'm not aware of the impact of moving API files, but I thought they were just there for examples and there would be no impact, except for doc generator tools, maybe.

**Comment by docwilmot** [comment] 2018-07-12 22:51
Put them in both locations?

**Comment by alexfinnarn** [comment] 2018-07-12 22:53
My idea was just to move them to the block module. PR is attached.

**Comment by opi** [comment] 2018-07-13 13:38
> Put them in both locations?

Will be harder to maintain.

**Comment by docwilmot** [comment] 2018-07-13 13:51
Problem is the invocations of those hooks are now in Layout module, so the documentation should be there. Maybe then have a note in `block.api.php` saying where this documentation is?

**Comment by alexfinnarn** [comment] 2018-07-13 15:02
Okay. I just wanted some note since in Drupal 7 the API file is in the block module directory. 

You could add a `block.api.php` file with a note that the hooks are in the layout module directory, but I don't know if that breaks patterns. 

You could also have a `README.md` file with a note in it, but I don't see any readme files in modules at this point.

I don't really care either way, it's just something I found a bit confusing as I'm looking at Backdrop again coming from Drupal 7. I'll leave it to the seasoned Backdrop core developers to decide, and then I can modify my PR accordingly. Also, feel free to reject this if you don't think it is a good idea, but the only other way to find the hook examples would be to search through the codebase.

**Comment by jlfranklin** [comment] 2018-07-15 12:54
The `*.api.php` files are processed into documentation on api.backdrop.org.  A note in the block module would work fine, as long as whatever is written works well on the API site. 

A duplicate of the documentation would not work well. I’m not sure what would happen. Duplicate entries for the hooks? Weird indexing breakage?

**Comment by klonos** [comment] 2018-07-16 02:20
1. Add a file (README or .php) where people expect things to be, which points them to where they actually live.
2. Explain why things have been done that way.
3. Open an issue for moving them to "the right place". Slate that for 2.x.
4. If point 3 is decided to happen in 2.x, then state so in whatever is the product of point 2.
5. Ensure that api.b.org does not break and does not get confusing for people.

Right?

**Comment by opi** [comment] 2018-07-16 06:32
> Explain why things have been done that way.

Any clue ?

**Comment by klonos** [comment] 2018-07-16 23:14
@opi sorry nope :/ ...perhaps a question for @quicksketch or @serundeputy (?)

**Comment by alexfinnarn** [comment] 2018-07-17 17:08
I searched the change records and found https://api.backdropcms.org/change-records/new-layout-module-implements-drag-drop-model-building-layouts

I think that the notice explains a lot of the reasoning. It would be the place to add more notes if needed? Telling people to look at the change records is fair and good enough for me.

**Comment by klonos** [comment] 2018-07-18 14:18
@alexfinnarn are you suggesting that we have some "placeholder" files (like `block.api.php`) with docblocks that point people to the api.b.org change record? If so, then I find it a great idea.

**Comment by alexfinnarn** [comment] 2018-07-18 15:11
I think that sounds fine, but you could just try to point people to change records in other ways. If I had originally searched for "block" in the change records and found a list of them, maybe I wouldn't have even filed an issue...and I would have more contextual change records about blocks to look at. 

So, the main question is: are change records the precedent for notifying developers of changes like these? And I think the answer is yes, although I think a notice about moving the API hooks would solve that for me. Looking at change records is already mentioned in some developer docs.

I guess the real question is "RTFM" vs. placing notes for people who don't do that. More notes equals more cruft that can be handled by change notices, but less notes could lead to more head scratches. I'm in favor of the change records, but I can add a PR with the docblock pointing to the change record as well.

**Comment by klonos** [comment] 2018-07-18 15:22
I think that one of the great things we have been doing for the UX in Backdrop is to be placing things where people expect to find them. There is no reason to be treating DX any different. If a developer does not think of looking though the changelogs, and they start looking around the files, then having a note pointing them to the right direction is in order I believe.

**Comment by alexfinnarn** [comment] 2018-07-19 14:10
Makes sense. I updated my PR with a note in a comment docblock.

**Comment by quicksketch** [comment] 2018-08-30 19:25
Thanks, great suggestion. Merged https://github.com/backdrop/backdrop/pull/2243 into 1.x and 1.10.x.

**Comment by jenlampton** [comment] 2018-09-06 20:26
Can we close this then?

**Closed by jenlampton** 2018-09-06 20:26 UTC
Labels: status - has pull request, status - fixed
