### ISSUE TITLE
EntityStorageException: SQLSTATE[HY000]: Field 'language' doesn't have a default value in EntityDatabaseStorageController->save() (line 676 of entity.controller.inc).

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4716] opened 2020-10-23 22:43 UTC
This was reported by means of a forum post: https://forum.backdropcms.org/forum/field-language-doesnt-have-default-value

> I upgraded my site from Drupal 7 to Backdrop and I get the following error when I try to create a new user account.
>
> `EntityStorageException: SQLSTATE[HY000]: General error: 1364 Field 'language' doesn't have a default value in EntityDatabaseStorageController->save() (line 676 of /app/core/modules/entity/entity.controller.inc).`

**Comment by indigoxela** [comment] 2020-12-14 08:00
I think we can close this.

It turned out that the problem was caused by direct changes to the database structure in the past. Field 'language' does have a default value - an empty string.

**Closed by indigoxela** 2020-12-14 08:00 UTC
Labels: type - bug report
