### ISSUE TITLE
Search with language parameters doesn't give any results

### ISSUE THREAD

**Issue by jdanthinne** [backdrop/backdrop-issues#714] opened 2015-02-13 21:01 UTC
It seems that when you specify a language in the advanced search form, no results are found…

**Comment by quicksketch** [comment] 2015-02-13 21:50
Thanks for filing this @jdanthinne! I've confirmed this issue. Pre-fork there were a lot of changes to the handling of languages, but mostly it was switching `$language` to `$langcode` everywhere. Would you be up for making a pull request?

**Comment by jdanthinne** [comment] 2015-02-14 08:51
I can have a look at it next week, with pleasure.

**Comment by jdanthinne** [comment] 2015-02-15 12:44
Pull request made. See https://github.com/backdrop/backdrop/pull/742

**Comment by quicksketch** [comment] 2015-02-15 21:59
Thanks @jdanthinne! Looks like the search tests were broken by this change, although it's odd that they weren't failing previously. It'd be ideal if we could update the search tests to cover the situation that had been failing before.

Overall, the way the advanced search works seems really counter-intuitive. Instead of maintaining the values in the advanced search form, the options get transferred into the search query box as machine codes. I don't think that's a very friendly behavior for end-users... but let's not tackle that here.

**Comment by klonos** [comment] 2015-02-16 00:20
> ...but let's not tackle that here.

Filed that issue for you. Hope it saves you a few seconds to focus on other, more important things.

**Comment by quicksketch** [comment] 2015-02-16 02:27
Thanks! Although GitHub auto-links, I find explicit linking catches my eye better. The new issue is at https://github.com/backdrop/backdrop-issues/issues/720. Appreciated. :+1:

**Comment by jdanthinne** [comment] 2015-02-16 07:51
I've updated the pull request (test is fixed as well).

**Comment by quicksketch** [comment] 2015-02-16 08:13
The end commit looks good and isn't worth rerolling, so I've merged it in! In the future, it'd be better to squash the commits together into a single one (or just amend the last commit and force push). Thanks @jdanthinne!

**Closed by quicksketch** 2015-02-16 08:13 UTC
Labels: status - has pull request
