### ISSUE TITLE
[DX] Remove the "magic" that includes style.css automatically for themes

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#533] opened 2015-01-02 04:31 UTC
I would like to remove Drupal's "shortcut" that includes style.css automatically for themes . It adds error-prone "magic" that people can't see, and saves almost nothing (~31 characters of text).

It might also be worth looking at the other [improvements Drupal 8 has added](https://www.drupal.org/node/2349827) and see if we'd like to include anything else too.

**Comment by BWPanda** [comment] 2020-10-03 10:19
It seems Backdrop doesn't include this 'magic', in fact neither does Drupal 7...

From [Adding style sheets from .info files](https://www.drupal.org/docs/7/theming/working-with-css/adding-style-sheets-from-info-files):
> In Drupal 6, by default, a "style.css" file will be used from your theme when no other styles are defined inside the .info file. In Drupal 7, the style.css file will be used only if it is specified in the .info file.

I confirmed this by creating a simple 'theme' (basically just a bare-bones .info file) with a 'style.css' file in the same directory. When I enabled the theme and cleared caches, the CSS (making all text red) wasn't applied. When I added the 'stylesheets' line to the info file and cleared caches, the CSS was applied.

Closing as 'cannot reproduce'.

**Closed by BWPanda** 2020-10-03 10:19 UTC
Labels: needs - more feedback, status - cannot reproduce
