### ISSUE TITLE
[DX] Make File::access consistent with other entity classes.

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5480] opened 2022-01-29 13:10 UTC
## Description of the bug

The docblock of [that function in file.entity.inc](https://github.com/backdrop/backdrop/blob/1.x/core/modules/file/file.entity.inc#L163) states:

```
   * The "view" operation is not supported on the File Entity itself because it
   * has no page callback (yet), but there is separately file_download_access()
   * to check if a file is downloadable.
```
And accordingly the code only checks for create, update and delete operations.

However, that's not correct anymore. A few months after that code and comment was added, several additional permissions have been added, also "view" permissions.

So the comment is outdated and the access check is incomplete. Instead of trying to get File:access in sync with file_access, we decided to consolidate them to let one do the job and the other one is just a wrapper.

## Expected behavior

Function access() should be up to date with actual permissions. Otherwise entity_access() would lead to unexpected results.

## Additional information

- Backdrop CMS version: latest dev

Some communication happened in Zulip, so I'm posting initial concerns and findings re file_access() here. Yes, we had some trouble to understand the current code. :wink: This matters here (File::access()), because the logic gets consolidated.

1. This function does not actually handle $file = NULL, but claims to. After all it returns FALSE, anyway, if $file is neither an object nor a string. Why is it optional then?
2. `if (!$file && !in_array($op, array('view', 'download', 'update', 'delete', 'create'), TRUE)` what does this check try to achieve? Shouldn't that be two different checks, or, honestly be an OR instead of an AND?
3. `// Fall back to default behaviors on view.` why is "view" the only operation not handled in file_file_access? Means: no modules can hook in, no? Aren't they supposed to?
4. `@param $file` ... file object or file type. But that makes no sense, as actually the 'type' isn't considered when creating files: user_access('create files', $account). There's no create permission per file type.

---  

Minor release update:
- [ ] Add a conclusion suitable for blog post + release notes 
- [x] N/A Add Documentation label if the feature needs to be documented 
- [x] Add Needs change record label if the the issue contains an API change.
- [x] N/A Add Needs translation label if the the issue contains string translations.

## conclusion suitable for blog post

**Comment by klonos** [comment] 2022-02-06 09:58
Copy/pasting my comments from #5493...

This currently looks like so:

```php
  public function access($op, $account = NULL) {
    if ($op == 'create') {
      return self::createAccess(NULL, $account);
    }
    elseif (!in_array($op, array('update', 'delete'), TRUE)) {
      // If the $op was not one of the supported ones, we return access denied.
      return FALSE;
    }

    // If no user object is supplied, the access check is for the current user.
    if (empty($account)) {
      $account = $GLOBALS['user'];
    }

    if ($op == 'update') {
      return user_access('manage files', $account);
    }
    elseif ($op == 'delete') {
      return user_access('delete files', $account);
    }

    return FALSE;
  }
```

Was wondering why we're not doing this instead?:

```php
  public function access($op, $account = NULL) {
    // If no user object is supplied, the access check is for the current user.
    if (empty($account)) {
      $account = $GLOBALS['user'];
    }

    switch (condition) {
      case 'create':
        return self::createAccess(NULL, $account);
      case 'update':
        return user_access('manage files', $account);
      case 'delete':
        return user_access('delete files', $account);
      default:
        // If the $op was not one of the supported ones, we return access denied.
        return FALSE;
    }
  }
```

...I was also thinking that if the check for `$account` already happens in `File::createAccess()` and `user_access()`, then is it really needed at all here?

**Comment by klonos** [comment] 2022-02-06 10:04
It seems to me that we are stuck on "semantics" around the verbs "view" and "download" here ...doesn't one need to download the file in order to be able to view it? ...I guess what I'm saying is that view/download in the context of file entities seems one and the same to me.

**Comment by indigoxela** [comment] 2022-02-06 10:08
Let's gather some info:

Following perms currently are considered: 'manage files', 'delete files'.

Following perms are not considered yet:

- 'access file overview'
- 'bypass file access'
- 'administer file types'
- 'view own private files'
- 'view own files'
- 'view private files'
- 'view files'

> doesn't one need to download the file in order to be able to view it?

Not exactly, "viewing a file" in this case means "having access to the entity page (file/XX)". It's possible that a user has access to download a file, but can not access the entity page.

**Comment by klonos** [comment] 2022-02-06 10:14
> Not exactly, "viewing a file" in this case means "having access to the entity page (file/XX)". It's possible that a user has access to download a file, but can not access the entity page.

I'm having a really hard time correlating this to other entities like `Node` ...if a user doesn't have access to the node (say it is unpublished and they don't have permission to view unpublished nodes), then we don't allow them to access the "page" of the node and then say "hide" the content 🤔 🤷🏼

**Comment by indigoxela** [comment] 2022-02-06 10:21
Yes, that can be quite puzzling. The "File" and the "file" :laughing: - one is a classed Entity, the other is a ... (sigh) ...  a file like a pdf document or jpeg image or video, so something in the file system (:grin:) independently from the File Entity, which is some construct saved to the database, with an ID and several other properties.

I hope, my attempt to explain doesn't make things even worse. I don't have much trust in my skills to explain.

**Comment by klonos** [comment] 2022-02-06 10:22
Yes, I get all that, ...yet this still seems to me like we are trying to implement some sort of per-field access for file entities (unlike all other core entities). When people can access a node with a file field in it, they can access the node "page" and have access to all fields in it, right? Then why are we not doing the same for file entities?

**Comment by indigoxela** [comment] 2022-02-06 10:30
> node ... Then why are we not doing the same for file entities?

I'm probably the wrong person to answer why something has been implemented the way it has been. But I don't actually think that File and Node can get handled the same way. Handling access to the entities' page and the attached file separately makes sense IMO. 

But that's probably outside the scope of this issue, which suggests to update the existing access check to consider all relevant _existing_ permissions - which is currently not the case, yet.

**Comment by klonos** [comment] 2022-02-06 10:31
> But that's probably outside the scope of this issue...

Roger 👍🏼

**Comment by indigoxela** [comment] 2022-02-06 11:50
Some suggestions after taking a slightly closer look:

1. Use createAccess() in file_access() - after it has been merged (see  #5479)
2. Let file_access() do all the heavy lifting in function access() (instead of doing user_access() checks again, which wouldn't consider hooks)
3. ALTERNATIVE: switch that - let function access() do the heavy lifting including static cache and let file_access leverage that (more like the node module does)
4. Update the relevant docblocks

This should bring more consistency within the File module itself, and between File and Node.

**Comment by argiepiano** [comment] 2022-02-06 15:20
Another example of the inconsistencies and problems file access check:

1. As admin, go to Content -> Manage files and upload a document (e.g. a PDF) and an image
2. Give a user the global "View files" permission and none other
3. Log in as that user and visit example.com/file/1 or ...file/2

The user has the ability to view the image (shown in the browser) and download the PDF document. So in this case it seems that "View files" also means "Download files" , and this is a global permission for all types. Thus it may be good to rename this permission "View and download files"

BUT THEN:
1. Remove "View files" permission
2. Give the user all the permissions (including download) for Image and Document types. 
3. Then try accessing example.com/file/1 or ...file/2.  

You will still get Access Denied, which obviously is a bug, since the user has all the permissions for Image and Document

And a third example:
1. Attach a file field to Page that accepts, for example, txt files. 
2. As admin, create a new Page node and upload a file. This automatically creates a managed file of type "Document" which you can see by going to Content -> Manage files.  
3. Remove ALL file permissions for the user
4. Visit the node.  Click the file shown in the node

This user, without any permission, can still view and download this document.

But if you try to view the actual file entity by visiting example.com/file/3  (or whatever id) you'll get an access denied.

And there's more......

Try accessing

**Comment by herbdool** [comment] 2022-02-06 17:50
I prefer 3 over 2. Putting it into the access method also makes it more consistent with how `entity_view()` is a simple wrapper for `$entity->access()`.

**Comment by indigoxela** [comment] 2022-02-07 07:54
@argiepiano you're not the only one struggling with the File permission jungle :grin: #5493

I wonder, if we could simplify that a bit - currently it takes several loops of thinking and recherche (also me and probably other people, too), to figure out how it was actually *supposed* to be.

**Comment by indigoxela** [comment] 2022-02-12 13:48
Tests are passing.

The access method now takes over the job, file_access is a wrapper plus takes care of the optional $file param. It may still be a little early (I'll re-review my own code after a little pause, especially re the 'create' op), but an additional pair of eyes would be great.

**Comment by argiepiano** [comment] 2022-02-12 14:57
Thanks, @indigoxela. I can review and test probably tonight or tomorrow.

**Comment by indigoxela** [comment] 2022-02-13 09:37
> I can review and test probably tonight or tomorrow.

@argiepiano that's great!

The diff may be a little hard to understand, as I moved code around. Three functions are involved:

- [function file_access](https://github.com/indigoxela/backdrop/blob/7f8044853bc640db53746f8d28e348ed17dbf9ce/core/modules/file/file.module#L2797)
- [function file_file_access](https://github.com/indigoxela/backdrop/blob/7f8044853bc640db53746f8d28e348ed17dbf9ce/core/modules/file/file.module#L2863) (the hook implementation)
- [method File::access](https://github.com/indigoxela/backdrop/blob/7f8044853bc640db53746f8d28e348ed17dbf9ce/core/modules/file/file.entity.inc#L161) (which takes over most of the work now)

**Comment by argiepiano** [comment] 2022-02-14 01:46
@indigoxela thank you for providing this PR. It's looking great. I added a few comments (and questions) in the PR itself. Feel free to respond here so that others can also comment.

**Comment by argiepiano** [comment] 2022-02-14 01:51
Regarding your question in the PR whether we should use __METHOD__ or the name of the old function where the `backdrop_static()` was originally user: I don't know. I'm inclined to say __METHOD__. I don't see any instance of `backdrop_static_reset('file_access')` anywhere in core of the contrib modules in backdrop-contrib. I guess it's possible that someone's custom module may use it, in which case the static cache would not be reset for file_access... but I think that's unlikely.

**Comment by indigoxela** [comment] 2022-02-14 07:12
@argiepiano many thanks for taking a look. I answered your questions/concerns in PR comments.

> I'm inclined to say `__METHOD__`. I don't see any instance of backdrop_static_reset('file_access') anywhere in core...

There is one in core, although only in the functional test (file.test). However, there could be implementations in contrib or custom modules, so it doesn't seem safe to me to change the static cache name. I could get convinced that it's safe, but am rather cautious.

**Comment by indigoxela** [comment] 2022-02-14 16:08
I also had some questions and posted them on the PR next to the related code. Is anyone able to answer?

**Comment by indigoxela** [comment] 2022-02-20 10:07
Seems a little difficult to get feedback from core committers on this one.

Let's proceed with testing instead.

How to test:

- It should be possible to do testing via the Tugboat sandbox and the Devel module, hook_file_access needs an implementation, though
- Create a user or several users with different roles/permissions
- Create some files
- Check access via file_access *and* File::access - the latter requires an existing entity

**Comment by yorkshire-pudding** [comment] 2022-04-11 07:28
@indigoxela - I think I mostly understand the issue, and what the PR is aiming to fix, but what is stopping me going ahead with testing is that I don't know how to:
> Check access via file_access and File::access 

Also, would a tester need to do something with:
> (hook_file_access needs an implementation, though)

**Comment by indigoxela** [comment] 2022-04-11 07:51
@yorkshire-pudding that's great! Basic testing can be done in the PR sandbox.

- Log into the Tugboat sandbox
- Create some users / roles, set permissions
- Create some files
- Go to /admin/devel/php
- Check the output of file_access() and File::access()

**Comment by yorkshire-pudding** [comment] 2022-04-11 09:02
Ok - I must be doing something wrong.  I created two roles:
'AccessFiles' which had permission to 'view own files' and 'view files'
'AccessPages' which had no additional permissions

I created user `4` / ViewPages / viewpages with just AccessPages
I created user `5` / ViewFiles / viewfiles with both AccessPages and AccessFiles

I created some content with basic text files

I'm getting `FALSE` for:

`echo file_access('download','document',1) ? 'TRUE' : 'FALSE';`
`echo file_access('download','document',4) ? 'TRUE' : 'FALSE';`
`echo file_access('download','document',5) ? 'TRUE' : 'FALSE';`
`echo file_access('download',1,1) ? 'TRUE' : 'FALSE';`
`echo file_access('download',2,1) ? 'TRUE' : 'FALSE';`
That doesn't seem right. Am I using the function wrong? I'm passing the user system id though have tried with username in quotes.  Haven't even tried with the other function yet.  I have checked [the docs](https://docs.backdropcms.org/api/backdrop/core%21modules%21file%21file.module/function/file_access/1) but it doesn't help much with usage

**Comment by indigoxela** [comment] 2022-04-11 09:11
You need to pass the user object:

```
$user = user_load(4);
echo file_access('download','document',$user)...
```
Also: `view` and `download` are different permissions.

**Comment by yorkshire-pudding** [comment] 2022-04-11 10:43
Ok
worked out that type is only for create.
 here is what I get:
Code

<details>

```php
$users = array(1, 4, 5, 6);
$files = array(1, 2);

echo 'file_access()' . PHP_EOL;

foreach ($users as $user_id) {
  $user = user_load($user_id);
  foreach ($files as $file_id) {
    $file = file_load($file_id);
    echo 'user ' . $user->uid . ' view document ' . $file->fid . ':' . (file_access('view',$file,$user) ? 'TRUE' : 'FALSE') . PHP_EOL;
    echo 'user ' . $user->uid . ' download document ' . $file->fid . ':' . (file_access('download',$file,$user) ? 'TRUE' : 'FALSE') . PHP_EOL;
  }
  $user = NULL;
}

echo 'File::access()' . PHP_EOL;

foreach ($users as $user_id) {
  $user = user_load($user_id);
  foreach ($files as $file_id) {
    $file = file_load($file_id);
    echo 'user ' . $user->uid . ' view document ' . $file->fid . ':' . ($file->access('view',$user) ? 'TRUE' : 'FALSE') . PHP_EOL;
    echo 'user ' . $user->uid . ' download document ' . $file->fid . ':' . ($file->access('download',$user) ? 'TRUE' : 'FALSE') . PHP_EOL;
  }
  $user = NULL;
}
```

</details>


Results
<details>
file_access()  
user 1 view document 1:TRUE  
user 1 download document 1:TRUE  
user 1 view document 2:TRUE  
user 1 download document 2:TRUE  
user 4 view document 1:FALSE  
user 4 download document 1:FALSE  
user 4 view document 2:FALSE  
user 4 download document 2:FALSE  
user 5 view document 1:TRUE  
user 5 download document 1:FALSE  
user 5 view document 2:TRUE  
user 5 download document 2:FALSE  
user 6 view document 1:TRUE  
user 6 download document 1:TRUE  
user 6 view document 2:TRUE  
user 6 download document 2:TRUE  
File::access()  
user 1 view document 1:TRUE  
user 1 download document 1:TRUE  
user 1 view document 2:TRUE  
user 1 download document 2:TRUE  
user 4 view document 1:FALSE  
user 4 download document 1:FALSE  
user 4 view document 2:FALSE  
user 4 download document 2:FALSE  
user 5 view document 1:TRUE  
user 5 download document 1:FALSE  
user 5 view document 2:TRUE  
user 5 download document 2:FALSE  
user 6 view document 1:TRUE  
user 6 download document 1:TRUE  
user 6 view document 2:TRUE  
user 6 download document 2:TRUE  
</details>

All  have view published content
Role AccessViewPages has nothing extra
Role AccessViewFiles also has 'view own files', 'view files' 
Role AccessDownloadFile also has 'download any files' for each of the types.
The files uploaded were both text files
![chrome_LZve6xbAv1](https://user-images.githubusercontent.com/20357797/162723486-0fd0643a-318b-4f25-a619-287a07ed2628.png)

However, if I log into each account, I can see the pages and open the text files. (i.e. there is no difference in the user interface).

I've learned a bit more about php and the Backdrop object model here.  Thanks for the pointer.

**Comment by indigoxela** [comment] 2022-04-11 11:23
@yorkshire-pudding thank you so much for testing - die results are identical for both access functions.

One question:

> if I log into each account, I can see the pages and open the text files. (i.e. there is no difference in the user interface).

So the permissions are wrong? I struggle a bit to understand that. :wink:

**Comment by yorkshire-pudding** [comment] 2022-04-11 11:28
Sorry @indigoxela - I wasn't clear

I login as user 4 - can view and download the file via the page that it was added to (i would expect not to be able to see it, if I understand the permissions correctly - perhaps see page content but not see reference to file or not have a link to file)
Same for users 5 and 6 (though for user 5, not sure how they would view a txt file but not be able to download.)

**Comment by indigoxela** [comment] 2022-04-11 11:34
Ah, now I get it... :wink:

The permission to "view a file" is about the File entity page (`/file/FID`), not the attached file to nodes. This can be very confusing, you're not the first person struggling with it.

> not sure how they would view a txt file but not be able to download...

Yeah, that seems odd. No newly introduced oddness, though.

**Comment by yorkshire-pudding** [comment] 2022-04-11 11:41
That explains it.  Thanks.

**Comment by indigoxela** [comment] 2022-04-11 14:30
Inspired by the manual tests, I've now added a functional test.

**Comment by indigoxela** [comment] 2022-05-01 11:54
Rebased in case someone want's to review it.

**Comment by indigoxela** [comment] 2022-05-02 07:10
@herbdool thank you so much for having a look! :pray: 

I'll need your help with one of your comments - I don't understand yet, what you're after. :wink:

**Comment by indigoxela** [comment] 2022-06-03 07:33
Yet another rebase, hoping for some progress.

@herbdool I made the changes you suggested except for the ones I oppose to. :wink: Removing the ability to check basic access without a File entity would be a breaker.

**Comment by argiepiano** [comment] 2022-06-05 04:41
I've added a few comments to the code - I haven't looked at the tests, only the main workflow of the new code. In general I think it looks good, but I had a couple of questions.

**Comment by indigoxela** [comment] 2022-06-05 09:08
Seems like we're stuck a bit on the question, if we should provide access checks without entity given (for bundle string or no $file given).

@herbdool suggests to drop it all and only allow checks when an entity is given - did I summarize that correctly?

I don't think it's possible to completely drop support for checks without entity before B 2.x, as this is a much bigger change (and needs deprecation handling and a long process).

Why aren't Node and File doing it the same way?
Note the differences between them.

Node:
- In function node_access the $node param is not optional
- Neither in function node_node_access
- Node has only two generic permissions, that work without any additional info: "Bypass content access control" and "Administer nodes"

File:
- In function file_access $file currently IS optional
- In function file_file_access it's also optional - to also cover create access
- In public function access (class File) there's no param for $file
- File has several generic permissions, that work without additional info besides $op and $user:
- - Bypass file access control
- - Add and upload new files
- - View private files | View files (maybe do need additional check, though)
- - Manage or replace any file
- - Delete any file

Completely changing param handling for any of the access functions is beyond the scope of this issue and probably a 2.x task, anyway.

The purpose of THIS issue is to fix an urgent problem: File::access() is currently an equivalent of `array_rand([TRUE, FALSE])` - completely unusable. And I think we should fix that ASAP, before someone runs into trouble because they use that method.

I do get the request to completely overhaul (standardize) the whole Entity access system, but please let this be a follow-up. Otherwise we're stuck here for a long time. And have to live with the unusable method.

**Comment by argiepiano** [comment] 2022-06-05 14:20
> @herbdool suggests to drop it all and only allow checks when an entity is given - did I summarize that correctly 

I'm not sure that's what he proposed. I don't think completely dropping the ability to receive a string or null for $file in file_access is a good idea (or even possible).

**Comment by indigoxela** [comment] 2022-06-06 12:19
PR updated. Ready for more feedback.

**Comment by yorkshire-pudding** [comment] 2022-06-06 12:40
@indigoxela - I don't understand much of the code (yet) but if you need me to do more testing let me know

**Comment by indigoxela** [comment] 2022-09-05 07:36
Another rebase :wink: still ready for testing and review.

**Comment by yorkshire-pudding** [comment] 2022-09-06 14:11
@indigoxela 

I've re-created and then re-run the tests I did previously adjusting for user IDs and file IDs:

<details>
<summary>Code</summary>

```php
$users = array(1, 3, 4, 5);
$files = array(4, 5);

echo 'file_access()' . PHP_EOL;

foreach ($users as $user_id) {
  $user = user_load($user_id);
  foreach ($files as $file_id) {
    $file = file_load($file_id);
    echo 'user ' . $user->uid . ' view document ' . $file->fid . ':' . (file_access('view',$file,$user) ? 'TRUE' : 'FALSE') . PHP_EOL;
    echo 'user ' . $user->uid . ' download document ' . $file->fid . ':' . (file_access('download',$file,$user) ? 'TRUE' : 'FALSE') . PHP_EOL;
  }
  $user = NULL;
}

echo 'File::access()' . PHP_EOL;

foreach ($users as $user_id) {
  $user = user_load($user_id);
  foreach ($files as $file_id) {
    $file = file_load($file_id);
    echo 'user ' . $user->uid . ' view document ' . $file->fid . ':' . ($file->access('view',$user) ? 'TRUE' : 'FALSE') . PHP_EOL;
    echo 'user ' . $user->uid . ' download document ' . $file->fid . ':' . ($file->access('download',$user) ? 'TRUE' : 'FALSE') . PHP_EOL;
  }
  $user = NULL;
}
```

</details>

<details>
<summary>Results</summary>

```
file_access()
user 1 view document 4:TRUE
user 1 download document 4:TRUE
user 1 view document 5:TRUE
user 1 download document 5:TRUE
user 3 view document 4:FALSE
user 3 download document 4:FALSE
user 3 view document 5:FALSE
user 3 download document 5:FALSE
user 4 view document 4:TRUE
user 4 download document 4:FALSE
user 4 view document 5:TRUE
user 4 download document 5:FALSE
user 5 view document 4:TRUE
user 5 download document 4:TRUE
user 5 view document 5:TRUE
user 5 download document 5:TRUE
File::access()
user 1 view document 4:TRUE
user 1 download document 4:TRUE
user 1 view document 5:TRUE
user 1 download document 5:TRUE
user 3 view document 4:FALSE
user 3 download document 4:FALSE
user 3 view document 5:FALSE
user 3 download document 5:FALSE
user 4 view document 4:TRUE
user 4 download document 4:FALSE
user 4 view document 5:TRUE
user 4 download document 5:FALSE
user 5 view document 4:TRUE
user 5 download document 4:TRUE
user 5 view document 5:TRUE
user 5 download document 5:TRUE
```
</details>

Results are the same as previous and the same for both versions, so that should be good.  I don't understand much of the conversation above, so hopefully the same results is what you are still expecting.

**Comment by herbdool** [comment] 2022-09-06 14:22
I wasn't willing to RTBC the code when I reviewed it a few months ago. Instead of continuing the conversation over that PR, I decided it might be more efficient if I provide an alternative PR (at risk of confusing the labels). I took a different approach - I used the Node entity class as an example of the best way to re-arrange the code and ensure conformity between `file_access()` and `File::access()`. 

I actually don't think this issue counts as a bug - just because a comment is incorrect isn't enough. And I think the intro to this issue should be clearer on that. What we're doing is re-arranging the code so that it in effect creates a view permission on the entity and not just the procedural function. 

My approach means that static cache is hit sooner than in the first PR on this issue, which is also how it is done in Node class.

I included @indigoxela's test in my PR - seems to be passing them all.

**Comment by indigoxela** [comment] 2022-09-06 15:31
> I wasn't willing to RTBC the code when I reviewed it a few months ago

I was aware that you will block my approach, no worries. :wink:

> This issue ballooned quickly and I'm trying to just keep the PR focused on refactoring.

But in that case, I'd suggest to create an (completely new) META issue with clearly defined sub-tasks, just to not lose the overall picture.

I didn't take a closer look at your code, yet, so I'm not sure in how far it covers the initial issue description.

> I included @indigoxela's test in my PR - seems to be passing them all.

You never hesitated to take over other people's work, I know.

**Comment by herbdool** [comment] 2022-09-06 15:34
> You never hesitated to take over other people's work, I know.

Shrug. Such is open source. I can't tell if you're annoyed or just being sarcastic.

**Comment by indigoxela** [comment] 2022-09-06 15:37
> Such is open source.

Nowadays proper attribution has a high value.

> I can't tell if you're annoyed or just being sarcastic.

It wouldn't make any difference for this issue - whatever it is.

**Comment by herbdool** [comment] 2022-09-06 15:41
@indigoxela how would you like to be attributed? I can make changes. And whichever core committer merges either PR will include attribution of anyone who contributed in this issue.

**Comment by herbdool** [comment] 2022-09-06 22:09
@indigoxela to be clear, I didn't use any of your code other than the test. So it's a different take. I left this issue for months before deciding to do my own version, so I wouldn't call that "not hesitating". I didn't think I would make more progress in reviewing your PR. Given my limited capacity in doing free Backdrop work, providing my own PR seemed like a better use of my time. Now someone can critique my approach.

**Comment by indigoxela** [comment] 2022-09-07 06:19
@herbdool I closed my PR, good luck with yours.

**Comment by quicksketch** [comment] 2022-09-14 20:44
This is great. I love the consistency improvement. I just ran across an issue with the `download` permission being separate from `view`. I don't think this problem is covered by this PR, but I'd appreciate confirmation if that's the case:

- New Backdrop install
- Add public file field to any content type
- Enable the field in the full display mode, set formatter to "Download link"
- Upload a sample file and view the node as admin. The download link shows.
- Now log out and view as anonymous. The download link is hidden.
- Grant the "View files" permission. The download link is still hidden.

As far as I can tell, _nothing_ actually grants the "download" permission. The file download link shows only for users that have `bypass file access`. Note this only affects the "Download link" formatter. If the formatter is "Generic file" or "URL to file", both show and the file can be downloaded.

**Comment by quicksketch** [comment] 2022-09-14 21:11
I checked the sandbox and this problem still exists. I couldn't find any other similar issues so I filed https://github.com/backdrop/backdrop-issues/issues/5777.

**Comment by argiepiano** [comment] 2022-09-18 15:22
I can confirm this problem. The main difference between the "Download link" formatter and all other formatters, is that the Download link formatter presents a link to `file/FID/download` (this is the file entity download callback, not the direct URL to the file), while the other ones present the link to the file URL itself, as in `files/NAME.pdf`

So, to me, this is not a bug. Permissions to `file/FID/download` is handled by the permission  such as "Document: download any files", which seems correct to me.

In fact I would argue that the other formatters (with the exception of "URL to file")  should also present the file entity download link, rather than the direct URL. 

Side note: to me the "View files" permission means  "view the entity file page" - not necessarily "view the URL of the file". Perhaps we should open a new issue to decide exactly what each of these permissions mean. A semantics discussion...

**Comment by argiepiano** [comment] 2022-09-18 15:24
One more thing that got me at first: when you are testing access for anonymous **be sure to clear caches every time you change a permission**. Backdrop will serve the cached page otherwise.

**Comment by klonos** [comment] 2022-12-30 22:32
> Side note: to me the "View files" permission means "view the entity file page" - not necessarily "view the URL of the file". Perhaps we should open a new issue to decide exactly what each of these permissions mean. A semantics discussion...

Yes please. That ^^ 👍🏼 

This issue here was discussed a lot after my comments back in February (during my hiatus months), and now that I finally got through the entire thread, with each comment I finished reading I was constantly thinking "we won't be able to fix this properly before we clarify the terminology - people will not be able to test things properly if the same thing has a different meaning to different people" 🤔 

@indigoxela I've reassigned this issue based on this (so I hope you don't mind):
>@herbdool I closed my PR, good luck with yours.

I've asked a question in the PR, but might as well ask here: why are we caching access based on UID instead of role? Doesn't that have the potential of huge cache size in sites with lots of users? ...is it because we are caching that way elsewhere (saw something about mimicking Node access)?

**Comment by herbdool** [comment] 2023-01-03 02:48
@klonos I've updated the PR based on your comments. @quicksketch perhaps this is ready for 1.24.0?

I think we can merge this and create a new issue for clarifying the permission terminology. Just keep in mind what @argiepiano suggested: "So, to me, this is not a bug. Access to file/FID/download is handled by the permissions such as "Document: download any files", which seems correct to me."

**Comment by quicksketch** [comment] 2023-01-03 03:07
The PR at https://github.com/backdrop/backdrop/pull/4195 looks good to me. I made a few code syntax changes and committed them directly to the PR. With all existing tests passing and the new tests confirming `file_access()` and `$file->access()` behave the same, this seems like it should be backwards-compatible(?) Will this need a change record or will any `@since` docblocks be needed?

**Comment by quicksketch** [comment] 2023-01-03 03:12
Although I read through the code and tests pass, this could probably use a few manual checks to confirm file access works as expected.

**Comment by quicksketch** [comment] 2023-01-03 06:04
I merged https://github.com/backdrop/backdrop/pull/4195 into 1.x for 1.24.0. Thanks @herbdool!

@indigoxela If this new PR did not cover all the original objectives (I'm not sure it did) we can start again based on the new, cleaner/consistent code now in 1.x. I of course credited you on this issue even though the new PR took a different approach. Thanks for raising this issue and your several rounds of iteration on the original PR.

https://github.com/backdrop/backdrop/commit/1e5e47b0e2a25c9f0f9bbf204583e01a551712ad by @herbdool, @indigoxela, @klonos, @argiepiano, @yorkshire-pudding, and @quicksketch.

**Comment by klonos** [comment] 2023-01-15 04:02
Lets keep this open, to remember to create a change record for it.

**Comment by quicksketch** [comment] 2023-01-15 21:44
@herbdool Could you help draft a change record? If you have an account on the Docs site: https://docs.backdropcms.org/node/add/changenotice.

**Comment by herbdool** [comment] 2023-01-16 01:36
@quicksketch I started the draft https://docs.backdropcms.org/change-records/fileaccess-and-file_access-now-return-the-same-results but still need some more text.

**Comment by quicksketch** [comment] 2023-01-18 01:35
Thanks @herbdool. I updated it with a description that I believe describes the situation. The real short of it was: you couldn't rely on `File::access()` in previous versions. Fortunately, the worst-case scenario seems to be that access would be denied when it should have been granted (rather than the other way around).

**Comment by quicksketch** [comment] 2023-01-26 20:58
https://docs.backdropcms.org/change-records/file-access-and-file_access-now-return-the-same-results is now published.

**Closed by quicksketch** 2023-01-26 20:58 UTC
Labels: type - feature request, status - has pull request, needs - change record, status - fixed
