### ISSUE TITLE
CKEditor Link Continuously Adds Base URL

### ISSUE THREAD

**Issue by mikesoltis** [backdrop/backdrop-issues#5886] opened 2022-12-09 20:47 UTC
After editing a link using the CKEditor link icon, the Base URL string is added (/smbmc) - each time when it is saved.  After the second save this produces a broken link.

To reproduce the behavior:

1. Edit a Page with a working link using CKEditor - Full HTML
2. Click on the link to open the dialog box but make no changes
3. Click on "Save" in the dialog box
4. Click on "Save" in CKEditor
5. Clicking on the link on the page now gives an error

## Actual behavior

Link Dialog after 1 save:

![working_link](https://user-images.githubusercontent.com/78069725/206342405-0da544c5-52f8-43bd-b1f2-d5e6d58ebd8d.png)

Link Dialog after 2nd Save (no editing):

![broken_link](https://user-images.githubusercontent.com/78069725/206342559-bb0785f8-f204-4735-83ee-cf6afca74165.png)

## Expected behavior

Either 1) BASE URL is never added

or

2) no BASE URL added if it's already present

## Additional information

- Backdrop CMS version: 1.23.1 
- Web server/Operating: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.4.27 
- Browser(s) and their versions: Firefox 102.4.0esr (64-bit)

**Comment by argiepiano** [comment] 2022-12-10 02:21
I'm unable to reproduce this issue. 

1. I created a node with a body link that points at another node
<img width="414" alt="Screen Shot 2022-12-09 at 7 19 08 PM" src="https://user-images.githubusercontent.com/9938978/206824004-3df6953c-a335-40e3-b9e5-db72ede48859.png">

<img width="296" alt="Screen Shot 2022-12-09 at 7 19 35 PM" src="https://user-images.githubusercontent.com/9938978/206824020-406767a9-d536-4d9d-9bd2-40f52b40137e.png">

The link works as expected

2. I edited that node, put the cursor on top of the link, and clicked the link icon
3. Clicked Save to save the link without editing (as directed above)
4. Saved the node

The link still works as expted

5. I edited the node again to inspect the link. It still points to the correct place

Perhaps there is a missing step? I assume the link is to another node, correct?

**Comment by argiepiano** [comment] 2022-12-10 02:27
One strange thing I'm noticing in the image you posted is that the URL to edit the node is:

`XXX.stanford.edu/smbmc/node/930/edit`

It's strange that the `smbmc` is part of the URL. Usually the edit page of the node would look just like `stanford.edu/node/930/edit`, UNLESS your site is actually part of a multisite install with a subdirectory as the base url. If this is the case, perhaps there is a conflict between the subdirectory and the alias being used for the nodes?

**Comment by argiepiano** [comment] 2022-12-10 03:33
OK, I've been able to reproduce the issue. As suspected this happens when Backdrop is installed as multisite, using a URL with a subdirectory, as in `example.localhost/subsite`

1. Install a Backdrop multisite located under an address such as `example.localhost/subsite`. For example,  if your codebase is in www
  - In `sites` create a folder such as `sites/subsite`
  - Edit `sites/php` to add: `$sites['example.localhost.subsite'] = 'subsite';` to point it to the right subdirectory
  - Create a symlink in your root installation `ln -s . subsite`
  - Set up your `sites/subsite/settings.php` with the db information (create a db first) and the `trusted_host_pattern` as in `$settings['trusted_host_patterns'] = array( '^example\.localhost\:8888$');`
  - Visit `example.localhost/subsite/core/install.php` to install your site
2. After all the above, and after you have your site installed at `example.localhost/subsite` create some content and follow the steps outlined in this issue

As explained in the issue, the path is added again to the uri

<img width="500" alt="Screen Shot 2022-12-09 at 8 32 01 PM" src="https://user-images.githubusercontent.com/9938978/206827092-1bf4c84e-9e8f-457a-bb87-34150ec37e63.png">

**Comment by mikesoltis** [comment] 2022-12-10 03:58
You are correct - we have installed several instances of backdrop for each subdivision, smb, smbmc, smbxas, etc...

Thanks for looking into this issue.

**Comment by argiepiano** [comment] 2022-12-10 05:05
Even the first time the node with the link is saved, you end up with two base paths in the link (as in `/subsite/subsite/posts/vel-volutpat`).

This is happening because the form submission is first run through the element validation `_filter_format_editor_link_url_validate()` which adds the base path to the alias, resulting in `/subsite/posts/vel-volutpat` (specifically in the call to `url()` in line 598 of `_filter_cleanup_url()`), and then a SECOND base path is added in line 465 in the form submit handler `filter_format_editor_link_form_submit()` 

I believe these second one should not be added there. I don't know why that addition happens there. This is not a problem with the base path of the site is `/`, but it does become a problem when you have a subsite with another base path. 

Anyone, any thoughts on why that's added there?

**Comment by argiepiano** [comment] 2022-12-10 05:24
In fact the problem is solved if lines 466-467 of filter.pages.inc are changed to

```php
    // $url = (substr($uri, 0, 4) == 'http') ? $uri : substr(base_path(), 0, -1) . $uri;
    $form_state['values']['attributes']['href'] = $uri;
```

Commented out `// $uri = ... ` and changed `$form_state['values']['attributes']['href'] = $url;` to `$form_state['values']['attributes']['href'] = $uri;`

I have tested also in a "normal" Backdrop installation and this doesn't affect it's functioning of links. So, I believe this is the solution, but I'd like some thoughts on why that additional `base_path()` was added there after it had been added earlier in the element validation.

**Comment by argiepiano** [comment] 2022-12-10 05:44
Aha! I found it. 

16 months ago, in PR https://github.com/backdrop/backdrop/pull/3552, as part of issue https://github.com/backdrop/backdrop-issues/issues/4630  the element validation function  `_filter_format_editor_link_url_validate()` was changed to run `url()` on the link. This was not done in the previous version of the element validation function. Therefore we ended up with two `base_path` being added, one by `url()` in the element validation, and another one by the submit handler.

So, yes, it seems like getting rid of the second `base_path` addition is the correct fix. PR coming (probably tomorrow)

**Comment by argiepiano** [comment] 2022-12-10 23:00
PR submitted: https://github.com/backdrop/backdrop/pull/4274

@mikesoltis, would you please test, and if possible do a code review?

**Comment by klonos** [comment] 2022-12-11 02:24
Thanks @mikesoltis for taking the time to report this issue, and thank you @argiepiano for the investigation and PR 🙏🏼 

Yeah, I don't know why that check was there (need to further check the code and git blame/history to get a better understanding), but even `substr($uri, 0, 4) == 'http')` doesn't seem like a completely safe check to determine the presence of the scheme in a uri, since `http` without being followed by a `://` can possibly be in the non-scheme part of a uri - `parse_url()` would have been safer to use I believe.

**Comment by kiamlaluno** [comment] 2022-12-11 08:27
I guess `substr($uri, 0, 4) == 'http')` was used to check the URL scheme was either http:// or https://, but that is the wrong way to check the URL scheme, as it doesn't check the next characters. (It probably assumes the URL isn't malformed, but that is a bad assumption too.)

[`parse_url()`](https://www.php.net/manual/en/function.parse-url.php) is indeed the right way to get the URL scheme. Passing `PHP_URL_SCHEME` as second argument will return just that.

**Comment by argiepiano** [comment] 2022-12-11 14:58
> Yeah, I don't know why that check was there (

I discovered that above. This line added the base path to the link. It was needed before https://github.com/backdrop/backdrop/pull/3552 was merged 16 months ago. That PR did, among other things, run `url()` on the link as a way to validate it. `url` adds the base path. Se we end up with to base path before the fix I submitted here.

> I guess substr($uri, 0, 4) == 'http') was used to check the URL scheme

Perhaps it's not the correct way to do it, BUT keep in mind the link HAD already been validated (in the element validation callback), so this substr was used simply to check that we don't have an absolute URL (after validation). If the link was an absolute URL, then the base path wasn't added.

All of this is unnecessary after  https://github.com/backdrop/backdrop/pull/3552 was merged.

**Comment by kiamlaluno** [comment] 2022-12-11 16:38
(Nevermind... I cannot test it in a multi-site settings, or in a sub-site.)

**Comment by argiepiano** [comment] 2022-12-11 17:04
@kiamlaluno thanks for your willingness to test, but sorry you can't do a subsite test. What environment are you working with? I work with MAMP, and the directions on creating subsites I pasted above worked for me. Also look at [this page](https://www.drupal.org/docs/7/multisite-drupal/multi-site-in-subdirectories) that explains things re: subsites. 

Hopefully @mikesoltis will also be able to test.

**Comment by mikesoltis** [comment] 2022-12-12 00:49
My level of testing would be to run a new version of backdrop core!

**Comment by argiepiano** [comment] 2022-12-12 01:49
Yes, that would be helpful. If the fix works for you, you can mark this as "works for me". That'a a great first step in getting this fix merged. Thanks!

**Comment by mikesoltis** [comment] 2022-12-12 19:43
When can i expect a new version will become available? thanks -

**Comment by argiepiano** [comment] 2022-12-12 20:29
That will depend on the review/testing process. There are bug fix releases every couple of months usually. Things are looking slower recently, with fewer reviews and testing happening. Do you have the ability to test and mark this issue as "works for me"?

**Comment by mikesoltis** [comment] 2022-12-12 20:50
OK - I will mark the issue here once I test it - thanks

**Comment by argiepiano** [comment] 2023-01-02 14:37
@mikesoltis, have you tested this bug fix? This may be a good time to do so, as there is a lot of activity around the next release. Unless someone tests it and marks it as works for me, it won't be fixed.

**Comment by laryn** [comment] 2023-01-03 13:42
@argiepiano I'm hoping to test this today. (I was trying to get it tested before the kids woke up but setting up multisite in Lando was new to me and took me a little too long to figure out. I think I've got that working now -- just need to test this PR before and after).

**Comment by laryn** [comment] 2023-01-03 18:00
@argiepiano Do you see this after patching?

1. Add the link using autocomplete -- no subdirectory on the link.
2. Apply/close the link modal.
3. Open the link modal again -- the link now contains the subdirectory at the beginning.
4. Apply/close again and reopen -- only one subdirectory is ever added.

**Comment by argiepiano** [comment] 2023-01-03 20:23
@laryn, can you clarify whether your comment above is a "works fine" or "Uh-oh" comment?

Your point 4 seems to me like the expected behavior, no?

**Comment by argiepiano** [comment] 2023-01-03 20:24
@jenlampton I read your comment in the PR. Please refer to my comments above. The base path IS always added. The issue is that it was added twice because of a change in the API 16 months ago. 

It would be helpful if  you please tested and indicated what the issue is with the PR.

**Comment by argiepiano** [comment] 2023-01-03 20:28
Also, anyone testing this, please be sure you are testing this with a subsite installation of Backdrop - this is where the problem is detected. A "normal" installation of Backdrop doesn't have a base path (well, technically, yes: it's `/`).

**Comment by laryn** [comment] 2023-01-03 20:44
@argiepiano It's much better than it was but the fact that no base path was added for me in step 1 seemed inconsistent compared to step 3 and 4.

**Comment by argiepiano** [comment] 2023-01-04 01:00
@laryn, thanks for explaining.

The issue you are seeing is due to the difference between an "internal path" (e.g. `node/1` - notice the absence of an initial slash) and a "full path" (`/node/1`).  The internal path is basically what's stored in the `menu_links` table. 

When you are working with a single installation of Backdrop, that's no big deal (the slash is barely noticeable). But when you have a "subsite" in a multi-site installation, you have a big difference: `node/1` is still the internal path,  but the full path is now `/mysubsite/node/1`

What's happening has nothing to do with the fix here. It's related to what the autocomplete returns. Autocomplete returns **internal path**, but when the text field is saved, CKEditor takes care of converting that internal path to a full path (this is necessary because, when you are viewing the page, you need a link that will redirect you to the correct path).  So, when you reopen the text field in CKEditor, and you click the link icon, you will now be editing the FULL path, not the internal path.

Again, this discrepancy has nothing to do with this patch, and already existed in a regular single-site installation (nobody noticed it before because the difference between internal path and full path was so tiny).

To anyone else testing and reviewing: please focus on the RESULTING link when viewing the page/field. Before the patch, the base path was doubled. With this patch, it's not. The link is correct.

As I explained in previous comments, because  of the changes introduced in https://github.com/backdrop/backdrop/pull/3552 a year ago, the function I fixed here was adding the base path a second time. This bug was only noticeable when you have a subsite.

**Comment by laryn** [comment] 2023-01-04 02:09
@argiepiano Thanks for the patient explanation. That makes complete sense. I’m comfortable marking this as works for me.

**Comment by klonos** [comment] 2023-01-05 14:13
@argiepiano do we have an existing issue for the pre-existing problem/confusion because of that leading slash before/after editing the link? If not, can you please open one (would be mostly copy/pasting your previous comment and screenshots really).

**Comment by mikesoltis** [comment] 2023-01-05 23:48
> @mikesoltis, have you tested this bug fix? This may be a good time to do so, as there is a lot of activity around the next release. Unless someone tests it and marks it as works for me, it won't be fixed.

I meant I can test in an official core release...I'm not currently able to test a branch version.

**Comment by bugfolder** [comment] 2023-09-18 16:59
Code reviewed. LGTM.

**Closed** 2023-10-06 12:03 UTC
Labels: type - bug report, status - has pull request, pr - ready to be committed, pr - works for me

**Comment by laryn** [comment] 2023-10-06 12:05
Thanks  @mikesoltis for filing and sticking with this issue. Thanks @argiepiano for your working tracking down what was going on and fixing it. Thanks to @bugfolder, @klonos, and @kiamlaluno for reviews and feedback. Merged into `1.x` and `1.26.x`.
