### ISSUE TITLE
Fixed: Existing Image library popup does not show all images.

### ISSUE THREAD

**Issue by sudipto68** [backdrop/backdrop-issues#5835] opened 2022-10-17 11:48 UTC
## Description of the bug

When there are amount of images in the existing image library and I try to open the image library popup. It shows only part of the row of the images. But when I scroll down the pop-up resizes and shows all the images and the entire image library popup modal.

## Steps To Reproduce

To reproduce the behavior:
1. Add content "Post". 
2. Create “title” and then “Select existing file” for an image field.
3. Image library only shows part of one row.
4. When scrolling down or top it shows the entire image library Pop-up.

The existing Image library should have a number of images to reproduce this.

## Actual behavior
This is how it looks when the pop-up opens first.
![edit1](https://user-images.githubusercontent.com/53519888/196168090-a48855e2-64c9-473b-b028-3cf52318dcd7.png)

## Expected behavior

The existing image library should show the full window
![edit2](https://user-images.githubusercontent.com/53519888/196168938-1854ee2b-a017-4af6-8294-cef63252c37c.png)

## Additional information

- Backdrop CMS version: 1.23.0
- Web server and its version: Nginx/1.18.0
- Operating System and its version: Ubuntu 20.04 lts
- Browser(s) and their versions: Google Chrome V106.0

**Comment by indigoxela** [comment] 2022-10-17 12:14
Hi @sudipto68, many thanks for reporting and welcome to Backdrop!

I can reproduce it with Chromium 106.0 on Linux.

- Only with image fields, not with the inline image dialog
- Only on Chromium, not on Firefox
- Only when opening the dialog for the first time

This might be something with JS (race condition?) or possibly CSS (less likely).

But I'm confident, that you're able to figure it out, as I see "Front-end Developer | React JS Developer" on your profile. :wink:

Are you willing to dig a little deeper? Possibly provide a pull request, or share your findings?

**Comment by sudipto68** [comment] 2022-10-17 13:47
@indigoxela,  I have checked this and found that it is the backdrop dialog’s feature that on resizing the dialog modal resized its height and width. You can find that(Core > Misc > dialog.js). If we made the auto resizing(In the dialog.js file line no:  13) from ‘true' to 'false’ then the image library pop-up small height issue gets fixed. 

But I am not sure enough. I need more testing.

**Comment by indigoxela** [comment] 2022-10-17 14:07
> If we made the auto resizing(In the dialog.js file line no: 13) from ‘true' to 'false’ then the image library pop-up small height issue gets fixed.

Uh-oh, I don't think this is what we want... That would switch the default, which can break implementations of other dialogs, possibly also in contrib modules.

But there's something fishy in dialog.js. My suspicion is that something weird happens with maxHeight in resetPosition. Didn't dig deep enough, though (and I'm no JS/JQuery-UI expert).

**Comment by argiepiano** [comment] 2022-10-24 02:24
One more detail about this bug: it's only reproducible if you clear the browser or Backdrop's cache. If you close the dialog and reopen it, or even if you navigate away and then return to the page (without clearing caches) and reopen it, the modal opens correctly. 

This is the same behavior reported in [other issue like this one](https://github.com/backdrop-contrib/paragraphs/issues/140) in Paragraphs. In that case, a workaround was to load the Backdrop.dialog.ajax library in the first page request, rather than loading it through an ajax call. But the bug still exists... and it'd be good to fix it to avoid this issue.

**Comment by argiepiano** [comment] 2022-10-25 15:21
PR submitted https://github.com/backdrop/backdrop/pull/4241

**Comment by argiepiano** [comment] 2022-10-25 15:32
(There are other unrelated issues with the file browser. The view used in the dialog should display 10 items per row (it uses a mini pager with 20 items), but it's displaying only 9 per row, resulting on a third row with two items. I believe this is due to a miscalculation of the width of each image and the total width of the row, but is unrelated to this issue)

**Comment by indigoxela** [comment] 2022-10-26 09:25
@argiepiano brilliant analysis!

I can confirm that the CSS three-liner fixes the problem in Chrome.
Another thing to confirm the findings - after the very first load in Chrome, when resizing the browser window a bit (even minimally), the dialog "jumps" to the correct size.

> There is still a bit of "jumping" of the dialog when you scroll.

Yes, I'm also seeing that tiny jump up. Not too bad, though.

> Simply adding this class definition to core/themes/seven/css/styles.css solves this problem,

Yes, but only in Seven. Which assumes that all sites are using Seven as admin theme and only Seven has to handle dialogs. But for sure this workaround is a true improvement. :+1:

**Comment by sudipto68** [comment] 2022-10-27 09:47
@argiepiano Thanks for this workaround.
I have tested this. It fixes the problem in Chrome and yes I have not found this problem in Firefox.

**Comment by klonos** [comment] 2022-10-28 08:12
...added the "needs feedback" tag based on this:

> ...I'd love for someone fluent in http/ajax requests to share their wisdom on why these css classes are not applied.

**Comment by indigoxela** [comment] 2022-10-28 11:42
Some more digging: in both, Firefox and Chrome the dialog opening triggers resetPosition(), but Chrome miscalculates the height.

If I add a slight delay, it also works in Chrome, but gets "jumpy" in Firefox, so the trick is to only apply the delay to the browser that needs it.

That way the dialog height is correct *and* the slight jump up is also gone. But we need more testing in different Browsers and ideally on different OSes.

@argiepiano what do you think about my alternate approach?

**Comment by argiepiano** [comment] 2022-10-28 12:41
@indigoxela, thanks for providing an alternate approach. 

I don't know, but to me, this seems a more fragile way to approach the fix - in general, whenever I have worked with JS, setTimeOut approaches are highly dubious, and end up being very dependent on the environment; they are widely discouraged (usually in favor of promises or event handlers, but I don't know if this is possible here).  One thing I'd like to try is to check if injecting/loading the CSS file directly from inside the js code in `dialog.js` (perhaps with a browser check if needed) has any effect. 

Perhaps there is a way to fix this from the JS side instead of modifying the initial page css (which I'm also not crazy about). I had prettified the dialog plugin to trace it; it took hours, and I did not find anything wrong with the plugin itself. 


I wonder if this is a Chromium bug that will get fixed sometime? And is it really the case that the JS code here is being executed before the css has finished loading?

**Comment by indigoxela** [comment] 2022-10-28 14:40
> I don't know, but to me, this seems a more fragile way to approach the fix

That's why I asked for more feedback and testing. :wink: 

The appealing thing about my approach (for me): the jumping is gone and it works in all (admin) themes. But if we decide that setTimeout just isn't the way to go here, I'd support the CSS workaround.

**Comment by klonos** [comment] 2022-10-29 07:40
> I wonder if this is a Chromium bug that will get fixed sometime? ...

Yeah, I was wondering the same, but this might take time, so we can't leave such an obvious user-facing bug unsolved 🤔

**Comment by indigoxela** [comment] 2022-10-29 10:30
> is it really the case that the JS code here is being executed before the css has finished loading?

@argiepiano That's also something I tried to figure out - with no real conclusion. My current assumption is, that the CSS is _loaded_, but the height is calculated before the whole CSS is _applied_ in Chrome. (No real evidence, though)

I played locally with some bigger CSS changes, to get rid of `position: absolute` in filter.css and that fixes the problem. But that's a much bigger change. IMO it would take ages until we find consensus re a complete filter.css rewrite. :grin: So let's try to keep changes minimal.

**Comment by argiepiano** [comment] 2022-10-29 13:44
Hi @klonos. Before you assign @indigoxela to this, can we wait a bit for more feedback? We have two approaches, and it seems premature that you decided to go with one of them already.

@indigoxela, I know you may probably disagree with this, but the combination of and "if" browser testing and setTimeout seems more hacky to me than the css approach. If this is a Chrome bug and gets fixed, chances are that that setTimeout will remain there for a long time. The partial css "pre-loading" seems to be less intrusive (even though it doesn't completely fix the problem). 

Also, this bug is not too serious, so the fix can possibly wait for more feedback 🤞🏽 . After all it only happens once after you clear caches, it doesn't preclude the user from selecting a file (hey, you can always scroll), and it gets "fixed" automatically by itself and remains fixed until you clear cache again.

**Comment by indigoxela** [comment] 2022-10-30 08:59
@argiepiano I can see now, how my additional PR irritated you, so I closed it.

I'm not sure if there's a way to prevent the "jump" regression with only CSS, but it's worth a try. Any ideas?
And also: if the theme is the only option to prevent the miscalculation - could we fix it in all core themes?

**Comment by argiepiano** [comment] 2022-10-30 14:15
> I can see now, how my additional PR irritated you

Not at all. It's important that it's considered in the discussion. Please reopen.

**Comment by argiepiano** [comment] 2022-10-31 04:18
@indigoxela, after a lot of tests and research, I've found that the setTimeout approach you used has been actually recommended for cases like the one presented here. See for example [this post](https://stackoverflow.com/questions/45983893/detect-when-all-css-rules-have-been-applied-and-painted). So, thank you for suggesting it 🙏🏽

I've submitted a third PR that builds on your approach, in a different way. Rather than using an arbitrary number of milliseconds for setTimeout, I created a self-calling function that checks the value of a specific css property (`overflow`) for the element of class `.ui-dialog-content`   which is changed when `jquery.ui.dialog.css` is finally applied. It uses `getComputedStyle()`, which provides a live variable that changes as the style is applied. 

I've tested in Chrome, Safari and Firefox (this last one simply skips the new code). It seems to be working great. Typically, only 2 iterations of the function are needed before the style is applied.

Take a look and let me know what you think. Again, I did not mean to sound irritated by your PR - on the contrary. 

Thanks again.

**Comment by indigoxela** [comment] 2022-10-31 08:54
> Rather than using an arbitrary number of milliseconds for setTimeout, I created a self-calling function that checks the value of a specific css property

That works like a charm! :tada:  Tested in Firefox and Chrome, with all three core themes, with aggregation on and off.

> Firefox simply skips... Typically, only 2 iterations of the function are needed...

I can confirm both (tested locally with a console.log in waitForCss).

@sudipto68 are you interested in also testing this approach?

**Comment by indigoxela** [comment] 2022-11-01 08:30
Great! Seems like we settled on the second (nifty) approach, so the first PR (CSS only workaround) should get closed.
The second one is RTBC! :+1:

**Comment by quicksketch** [comment] 2022-11-26 18:40
Hi folks, sorry for the delay in final review here. This approach seems good to me but we can clean up the implementation a tiny bit. I couldn't get GitHub to file a PR against @argiepiano's PR for some reason so I made a new one here: https://github.com/backdrop/backdrop/pull/4258

It's the same concept, but I removed one set of variables and an if statement to simplify the logic. It should still behave in the same way. Could someone double-check I did not create any regressions?

**Comment by argiepiano** [comment] 2022-11-27 02:42
Thanks for the new PR. It looks better. WFM and RTBC

**Comment by quicksketch** [comment] 2022-11-27 03:09
@argiepiano Thanks for your suggestion in the PR. I separated out `computedStyle` into its own variable and more closely matches what you had before. Could you take one more look?

**Comment by argiepiano** [comment] 2022-11-29 23:50
Thanks @quicksketch. The PR still works for me after that change. RTBC again!

**Closed** 2022-11-30 02:12 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2022-11-30 02:14
Thanks @argiepiano! I merged https://github.com/backdrop/backdrop/pull/4258 into 1.x and 1.23.x. Special thanks to @sudipto68 for filing and helping resolve this issue. Thanks @indigoxela and @klonos for the ideas and reviewing!
