### ISSUE TITLE
"Is the home page" visibility condition does not show blocks unless path is empty

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5263] opened 2021-09-29 22:50 UTC
**Description of the bug**

The "Is the home page" visibility condition can't tell it's on the home page when a node (specified as front page) is accessed via its alias, instead of via the bare domain.

**Steps To Reproduce**

To reproduce the behavior:
1. Set the site home page to `node/2`
2. Add a block to the default layout, add vis condition "Is the front page".
3. Visit `/about` -- the block is not shown.
5. Visit `/` -- the block is shown on the same page.

**Actual behavior**

Blocks do not appear when alias used.

**Expected behavior**

Blocks should appear when alias used.

**Additional information**

Add any other information that could help, such as:
- Backdrop CMS version: 1.20.0

**Comment by klonos** [comment] 2021-10-05 18:41
@jenlampton I reviewed the PR, and the code change seems reasonable. I wasn't able to reproduce the issue in a demo sandbox 🤷🏼

**Comment by indigoxela** [comment] 2021-10-06 06:35
Same here, I simply can not reproduce the problem on a vanilla install (following the exact steps).

@jenlampton what else could interfere on your site? Is it a multilingual site? That could explain it.

@klonos isn't it a bit uncommon to mark a PR RTBC, although you can't reproduce the problem?

**Comment by klonos** [comment] 2021-10-06 10:35
> @klonos isn't it a bit uncommon to mark a PR RTBC, although you can't reproduce the problem?

I reviewed the code, and I was happy with it - no coding standard violations, and it seemed right. That's what the RTBC label is for, right? I think that:
- when it comes to code review, it's either:
  - needs code review
  - RTBC
- when it comes to testing, it can be either:
  - needs testing
  - works for me
  - cannot reproduce

Right?

**Comment by indigoxela** [comment] 2021-10-06 10:49
> ...Right?

I don't know, I don't make the rules, but it's the first time a saw a RTBC label before anyone tested or could even _reproduce_ the problem.

To my understanding RTBC is the last step before merge and marks it as "ready to merge" for core committers. I don't hope we merge stuff, nobody was able to reproduce yet. :wink:
And adding the label may confuse core committers.

**Comment by BWPanda** [comment] 2023-02-26 19:32
Also cannot reproduce. Closing therefore until @jenlampton (or anyone else) can provide updated steps and confirm this is still an issue.

**Closed by BWPanda** 2023-02-26 19:32 UTC
Labels: status - has pull request, status - cannot reproduce
