### ISSUE TITLE
[UX] The "Disable" action removes the text format instead of disabling

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3962] opened 2019-08-03 15:09 UTC
**Description of the bug / Steps To Reproduce**
1. Go to `admin/config/content/formats`
2. Select the "Disable" action for any text format...

**Actual behavior**
Despite the "Disabled text format xyz" message, the format gets completely removed, and there is no way to get it back:

<img width="1180" alt="Screen Shot 2019-08-03 at 6 02 03 pm" src="https://user-images.githubusercontent.com/2423362/62413592-48016780-b619-11e9-9e8d-7fa74a0fdbb4.png">

Even the confirmation message is confusing:

> Disabled text formats are completely removed from the administrative interface, and any content stored with that format will not be displayed. This action cannot be undone.

<img width="690" alt="Screen Shot 2019-08-03 at 6 06 33 pm" src="https://user-images.githubusercontent.com/2423362/62413614-85fe8b80-b619-11e9-88ed-2f4696e2ce46.png">

**Expected behavior**
Either call the action "Delete" or "Remove", or make it so that text formats can be disabled and re-enabled.

**Comment by olafgrabienski** [comment] 2019-08-08 15:07
> Expected behavior
> Either call the action "Delete" or "Remove", or make it so that text formats can be disabled and re-enabled.

I'm going to close this issue as a duplicate of #1575 which is older and contains already a lot of discussion about the topic.

**Closed by olafgrabienski** 2019-08-08 15:07 UTC
Labels: status - duplicate
