### ISSUE TITLE
[UX] Change the error message returned by file_validate_is_image()

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#5917] opened 2023-01-08 14:56 UTC
[`file_validate_is_image()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21file.inc/function/file_validate_is_image/1) uses the following code.

```php
$info = image_get_info($file->uri);
  if (!$info || empty($info['extension'])) {
    $errors[] = t('Only JPEG, PNG and GIF images are allowed.');
  }
```

The error message is wrong, as the image toolkit the site uses could return information and extension for other image formats. Even the GD toolkit implemented by Backdrop core returns information and extension for an extra image format: WebP.

The error message should either be *The image format is not recognized.* which avoids to list a format the form didn't show as acceptable, or *Only the following image types are allowed: %image_formats.*, but in this case the list of the allowed formats should not conflict with the allowed formats the form would eventually show.

This is what happens when I upload a user picture in the user edit form. First I tried with a .svg image, which isn't supported by the GD PHP extension (and from the image toolkit implemented by Backdrop core). The validation handlers reported these errors.

![screenshot](https://user-images.githubusercontent.com/29851/211269511-8b17a296-9f22-4d0c-b79d-e25948c01210.png)

> Only JPEG, PNG and GIF images are allowed.
> Only files with the following extensions are allowed: jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp docx docm pptx pptm xlsx xlsm.

Then I tried with a .webp image, supported by the GD PHP extension installed on the server. The validation error shown in this case is the following one.

![screenshot](https://user-images.githubusercontent.com/29851/211273247-08020d2d-ff1c-4bc2-98be-93a1f762ae63.png)

> The specified file dca0914322a08f0a0c639020e1e171af.webp could not be uploaded. Only files with the following extensions are allowed: jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp docx docm pptx pptm xlsx xlsm.

Reading the first validation error, I would not have tried to use a .webp image, which is instead accepted from `file_validate_is_image()`, the function that shows the *Only JPEG, PNG and GIF images are allowed.* message in the first case.

(Yes, .webp images are still rejected from the other validation code, since their extension is not allowed, but that is a different issue.)

Furthermore, [`image_get_info()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21image.inc/function/image_get_info/1) (the function called by `file_validate_is_image()`) returns `FALSE` when:

- The file has not been found
- The file has not been uploaded via HTTP POST
- The file does not contain an image the image toolkit recognizes (or doesn't contain an image at all)

Instead of giving a single error, `file_validate_is_image()` should return three different error messages.

**Comment by kiamlaluno** [comment] 2023-01-08 15:06
As for getting all the extensions for the supported images, the following code would work, which is the code used by [`image_field_widget_form()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21image%21image.field.inc/function/image_field_widget_form/1).

```php
$supported_extensions = array('png', 'gif', 'jpg', 'jpeg');
backdrop_alter('image_supported_extensions', $supported_extensions);
```

Backdrop core itself implements [`hook_image_supported_extensions_alter()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21image%21image.api.php/function/hook_image_supported_extensions_alter/1), with [`system_image_supported_extensions_alter()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.module/function/system_image_supported_extensions_alter/1), which returns *webp* as supported extension, when the used toolkit is GD and it supports .webp images.

**Comment by klonos** [comment] 2023-01-08 21:50
Thanks for reporting this @kiamlaluno ...do you have any rough steps to reproduce, or are you going by what's in the codebase?

Also, since you've done the investigation, are you going to be able to provide a PR to fix this?

**Comment by kiamlaluno** [comment] 2023-01-09 08:53
I didn't provide the steps to reproduce because this isn't a bug, but rather an "issue" with an error message that is not exact and that could be in contradiction with another error message given from other validation code. I also didn't want this report to be seen as a report about a specific form when it's not so.

I tried to upload a picture for an account after enabling them. Since the user edit form doesn't show which images I could use, I tried with a .svg image. When I submitted the form, I got this error messages.

![screenshot](https://user-images.githubusercontent.com/29851/211269511-8b17a296-9f22-4d0c-b79d-e25948c01210.png)

> Only JPEG, PNG and GIF images are allowed.
> Only files with the following extensions are allowed: jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp docx docm pptx pptm xlsx xlsm.

Those error messages are "in contradiction" with each other: The first message makes me think I can only use files whose extension is .jpg, .jpeg, .gif, or .png; the second message says I am allowed to upload files with more extensions.

If the error messages were the following, at least it would be clearer I tried to upload a file that doesn't contain an image. (I would still wonder why the second message says that .doc files are allowed, when that isn't an extension I would normally use for images.)

> The image format is not recognized.
> Only files with the following extensions are allowed: jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp docx docm pptx pptm xlsx xlsm.

**Comment by kiamlaluno** [comment] 2023-01-09 09:01
To make clearer why I think it's better to give an error message that shows the allowed image types, when the list of allowed images is not complete: Suppose that the allowed file extensions are changed, and the second error message becomes the following one.

> Only files with the following extensions are allowed: jpg jpeg gif png webp txt doc xls pdf ppt pps odt ods odp docx docm pptx pptm xlsx xlsm.

The first error message would tell me WebP images aren't allowed, but the second error message would tell me they are allowed.

**Comment by kiamlaluno** [comment] 2023-01-09 09:15
I also tried with a .webp image. These are the error messages I got.

![screenshot](https://user-images.githubusercontent.com/29851/211273247-08020d2d-ff1c-4bc2-98be-93a1f762ae63.png)

> The specified file dca0914322a08f0a0c639020e1e171af.webp could not be uploaded. Only files with the following extensions are allowed: jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp docx docm pptx pptm xlsx xlsm. 

`file_validate_is_image()` accepted the image, even though the image was not a JPEG, PNG, nor a GIF image. The fact *Only JPEG, PNG and GIF images are allowed.* is not shown for all the images that aren't one of those image formats is confusing. (It's also confusing the image is accepted by a validation handler but then rejected by another validation handler, but I would leave that for a different issue.)

If all this details should be added to the issue summary, I will add them.

**Comment by kiamlaluno** [comment] 2023-01-09 09:19
(Yes, another issue is that the error message is formatted in two different ways, whether the *Only JPEG, PNG and GIF images are allowed.* is present or not. That is probably a different issue that should be checked.)

**Comment by klonos** [comment] 2023-01-11 14:03
...been reading https://stackoverflow.com/questions/15408125/php-check-if-file-is-an-image and https://stackoverflow.com/questions/6755192/how-to-check-uploaded-file-type-in-php and thinking that we may need to look into the implementations of `file_validate_is_image()` and `image_get_info()` (upon which `file_validate_is_image()` relies) and tweak/improve them to account for these cases 🤔

**Comment by kiamlaluno** [comment] 2023-01-13 08:32
@klonos [`image_get_info()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21image.inc/function/image_get_info/1) returns `FALSE` even when the file hasn't been uploaded via HTTP POST. Probably the error message should account that too, since saying the file was not found when the user sees it could confuse users.

**Comment by kiamlaluno** [comment] 2023-01-13 09:00
*The file has not been found or it is not of the required type.* could be used for a file that does not contain an image recognized from the image toolkit and for a file that has not been uploaded via HTTP POST, but it would be probably understood only as *The file is not of the required type.*

I am still thinking to a error message that does not confuse users but it is not too long.  
I agree that saying the file does not contain an allowed image when the file has not been found could confuse users who want to understand why the image format has not been recognized. The first step they would probably take is to open that file, but they will not find it as it does not exist.

**Comment by jenlampton** [comment] 2023-01-13 20:18
I've reviewed the PR, but it does not include a list of all the allowed extensions (as stated by the issue title). It's not going to be very helpful if we tell people that something is wrong, without telling them how to fix it :) 

I think all we should add the code from the previous comment by @kiamlaluno, above:

```php
$supported_extensions = array('png', 'gif', 'jpg', 'jpeg');
backdrop_alter('image_supported_extensions', $supported_extensions);
```

**Comment by kiamlaluno** [comment] 2023-01-14 19:06
[`image_get_info()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21image.inc/function/image_get_info/1) returns `FALSE` when:

- The file has not been found
- The file has not been uploaded via HTTP POST
- The file does not contain an image the image toolkit recognizes (or doesn't contain an image at all)

I would show the list of the allowed image types only if:

- It is possible to make a distinction between those three cases
- Other validation handlers do not show a list that conflicts with that list of image types

At the current state, `file_validate_is_image()` can only understand if the file does not contain an image the image toolkit recognizes (or doesn't contain an image at all) because in that case `$info['extension']` is empty. In the first two cases, `image_get_info()` returns `FALSE`.  
As shown in the screenshot, the validation handlers give messages that conflict: For an image, the allowed extensions are reported to include .doc and .txt, which aren't used for images. (I hope we do not want to tell users they can store an image in a .txt file.)

Clearly, it would be possible to avoid the conflict between those two validation handlers by using a single validation handler. It would be sufficient to check the image toolkit recognizes the image, and show the file extensions for those images.

**Comment by kiamlaluno** [comment] 2023-01-14 19:10
As for the error message listing the file extensions for the allowed image types, there is still an "issue": The file could have the correct extension, but contain corrupted data. (It could be possible, since the files are uploaded.) In that case, telling users the file extension must be one in the list would not help them to understand what the problem is.

**Comment by herbdool** [comment] 2023-03-01 03:39
My PR on issue #4937 would solve this too https://github.com/backdrop/backdrop/pull/4366 I believe.

**Comment by kiamlaluno** [comment] 2023-03-01 09:05
It partially does. It does not report all the possible errors, listed on my previous comment.


- The file has not been found
- The file has not been uploaded via HTTP POST
- The file does not contain an image the image toolkit recognizes (or doesn't contain an image at all)

I should add that to the issue summary.

**Comment by kiamlaluno** [comment] 2023-07-21 16:48
I am closing this issue as per recent changes, including the changes in #4937. I will open a new issue for the changes left to do.

**Closed by kiamlaluno** 2023-07-21 16:48 UTC
Labels: status - duplicate

**Comment by klonos** [comment] 2023-07-22 22:34
I've filed #6176 as a follow-up (along with a PR for it).

This issue here should have been a bug, and I believe that we've addressed the initial concerns (as mentioned in the issue summary). What remains is this bit I believe:

> Furthermore, [`image_get_info()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21image.inc/function/image_get_info/1) (the function called by `file_validate_is_image()`) returns `FALSE` when:
> 
> - The file has not been found
> - The file has not been uploaded via HTTP POST
> - The file does not contain an image the image toolkit recognizes (or doesn't contain an image at all)
> 
> Instead of giving a single error, `file_validate_is_image()` should return three different error messages.

Is that correct @kiamlaluno, or have I missed something?

**Comment by kiamlaluno** [comment] 2023-07-23 07:37
@klonos The current Backdrop code does not show an error message that explains that those are the possible reasons for `file_validate_is_image()` to return `FALSE`. That seems quite what it is left to do.

**Comment by klonos** [comment] 2023-07-23 08:05
@kiamlaluno hmm 🤔 ...looking at both functions, I cannot see an easy way to have separate errors thrown for each scenario without considerably refactoring both functions. If you have any ideas, then please file a separate issue.

**Comment by kiamlaluno** [comment] 2023-07-23 08:44
I apologize for the confusion: I did not mean the error message should make a difference between those cases, but that *Only images with the following extensions are allowed: jpg, jpeg, gif, png.* (in the case WebP images are not supported) describes only one of three possible cases.

Imagine somebody uploads a PNG image for a user profile. That image is (for some reasons) deleted from the server before `file_validate_is_image()` is called for that file. When that person sees the error message, that person would check the image, notice the image is effectively one of the allowed images, and… get confused.

Truly, I am not clear why [`image_get_info()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21image.inc/function/image_get_info/1), which is called by [`file_validate_is_image()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21file.inc/function/file_validate_is_image/1) would verify the image has been uploaded via POST. That should be done only for uploaded images, but technically `file_validate_is_image()`'s purpose is checking any image.

**Comment by klonos** [comment] 2023-07-24 02:42
> Imagine somebody uploads a PNG image for a user profile. ...

Yes 👍🏼  ...and in order to catch that scenario (or any other valid scenario) and throw an appropriate/meaningful message, we'd need to refactor `file_validate_is_image()`. Can you please file a separate issue for it?

**Comment by kiamlaluno** [comment] 2023-07-24 09:11
I will do it, once I understand better which approach should be followed.
