### ISSUE TITLE
Porting Inline Form Errors

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2678] opened 2017-05-09 15:58 UTC
May be somebody would port [Inline Form Errors](https://www.drupal.org/project/ife).

:smile:

**Comment by laryn** [comment] 2017-05-09 16:40
Closing because I think this is a duplicate of https://github.com/backdrop/backdrop-issues/issues/1040

@bd0bd Check out the other issue and correct me if I'm wrong!

**Closed by laryn** 2017-05-09 16:40 UTC
Labels: status - duplicate

**Comment by bd0bd** [comment] 2017-05-09 16:53
**Jen** wrote me:

jenlampton commented 3 days ago • edited
@bd0bd Would you please create an issue in https://github.com/backdrop-ops/contrib/issues requesting that one of these modules be ported? Once there, please add the tag Port request and that way developers will know that you need it :)

**Comment by laryn** [comment] 2017-05-09 17:09
Ah ha, I see! Can you open it in the `backdrop-ops/contrib` queue (not the `backdrop-issues` queue) and maybe link back to the discussion you reference?

**Comment by bd0bd** [comment] 2017-05-09 17:27
Sorry, my mistake.

I did it https://github.com/backdrop-ops/contrib/issues/219
