### ISSUE TITLE
[UX] Layouts: blocks provided by deleted menus are not indicated as "Broken block".

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3346] opened 2018-10-27 00:45 UTC
### Steps to reproduce (if reporting a bug)

1. Enable the "Recent comments" view in `/admin/structure/views`.
2. Add a random new menu in `/admin/structure/menu/add` (no need to add menu items to it).
3. Choose any layout and add the block provided by the "Recent comments" view to any region.
4. In the same layout, also add the block provided by the menu you have added in step 2 above.
5. Save the layout.
6. Disable the "Recent comments" view.
7. Delete the menu added in step 2.
5. Back to the layout "Manage blocks" page...

### Actual behavior (if reporting a bug)

...the views block added in step 3 above is now shown as broken, but the menu block added in step 4 is not. It is rendered as an empty block instead (no title or content/description):

<img width="718" alt="screen shot 2018-10-27 at 11 44 10 am" src="https://user-images.githubusercontent.com/2423362/47597744-bd327300-d9dd-11e8-84f3-25d4b00773ed.png">

### Expected behavior (if reporting a bug)

Both broken block types should be similarly indicated as "Broken block".

**Comment by klonos** [comment] 2018-10-27 03:03
Huh... I cannot seem to be able to reproduce this any more.

**Comment by opi** [comment] 2019-02-10 14:42
Can't reproduce either. Closing this issue, it could be reopened if this bug come back.

**Closed by opi** 2019-02-10 14:42 UTC
Labels: needs - more feedback, type - bug report
