### ISSUE TITLE
[UX] Improve the aesthetic & usability of the place-blocks page.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1935] opened 2016-05-26 23:04 UTC
As I was working on Backdrop 1.4 and doing a lot of testing of layouts, I became bothered by the inconsistent colors and patterns on the place-blocks (configure layout) page. I love, love, love the new colors and design patterns we see on the modules page, cool blueish-grays and very few borders. I would love to see those colors and patterns applied to the layouts page. I made a few small color changes as part of Backdrop 1.4, but we can do better.  

Here's layouts in Backdrop 1.3: 
![1 3](https://cloud.githubusercontent.com/assets/397895/15592729/02c97968-235b-11e6-91be-ac4876e56929.png)

Here's the aesthetic I love about the modules page:
![modules](https://cloud.githubusercontent.com/assets/397895/15592795/7ce45344-235b-11e6-829d-bb901209e3ca.png)

**Comment by klonos** [comment] 2016-05-27 00:17
I know that we have intentionally removed the theme preview, but do you think that perhaps it's high time we re-introduced them?

You know what would be cool? ...a theme selector drop-down (top-right corner?) that would show the current layout in various themes. Then also a "edit selected theme" link that brings people to the page that @wesruv has designed in https://github.com/backdrop/backdrop-issues/issues/1905#issuecomment-222011318

**Comment by jenlampton** [comment] 2016-06-02 21:10
Here's an attempt to soften things up, using rounded corners and grays from the modules page.
![softer1](https://cloud.githubusercontent.com/assets/397895/15761206/c6c32c54-28cb-11e6-9339-2f77b59b1ad5.png)

**Comment by jenlampton** [comment] 2016-06-02 21:22
This one includes the draggable-handle so people know that blocks can be rearranged.
![softer2](https://cloud.githubusercontent.com/assets/397895/15761502/6bae62be-28cd-11e6-80be-f5dd2e649714.png)

**Comment by quicksketch** [comment] 2016-06-02 21:52
The addition of the Drag handles is great! That helps tremendously. Especially if you were on a touch device where you don't have the mouse-cursor to give indication.

**Comment by jenlampton** [comment] 2016-06-02 21:57
> The addition of the Drag handles is great! That helps tremendously. Especially if you were on a touch device where you don't have the mouse-cursor to give indication.

That's what I was thinking :)

I also tried one where the block content was gray instead of white for more contrast, but I'm not sure about this change:
 
![softer3](https://cloud.githubusercontent.com/assets/397895/15762384/51ad9ff6-28d2-11e6-9403-52c954711602.png)

**Comment by jenlampton** [comment] 2016-06-02 22:05
And here's another I wasn't sure about, an attempt to de-emphasize the region name by making it gray instead of black: 
![softer4](https://cloud.githubusercontent.com/assets/397895/15762592/7f3d7634-28d3-11e6-8f7b-021f34bd0c96.png)

**Comment by jenlampton** [comment] 2016-06-02 22:07
A PR with all the grays is over at https://github.com/backdrop/backdrop/pull/1434

**Comment by klonos** [comment] 2016-06-03 07:15
> I also tried one where the block content was gray instead of white for more contrast...

👍 looks much better IMO. Also 👍 on the rounded corners.

> ...an attempt to de-emphasize the region name by making it gray instead of black: 

Big 👍 from me on this one. It really bothered me when I was scanning the place block pages that the regions had the same style as the block headers.

...about the drag handle addition. Neither hot nor cold. It does indicate dragability, but on the other hand we use that handler in table rows as the single point that activates the dragging. In the blocks case though, one can use the entire header for that.

**Comment by jenlampton** [comment] 2016-06-03 21:31
> we use that handler in table rows as the single point that activates the dragging

I considered this too, but in this case if people try to drag by only the handle it will still work. I think better some indication (even if it's too little) than none at all. I think we're at least moving in the right direction!

I would love to hear what others think about 1) the gray background color for block content, and 2) the gray region name text.  @wesruv @dariusgarza @Graham-72 @docwilmot ?

**Comment by docwilmot** [comment] 2016-06-03 21:38
The last one is best, for sure. Grey bg and grey text.

**Comment by wesruv** [comment] 2016-06-05 16:51
> we use that handler in table rows as the single point that activates the dragging.

This is a-ok from a UX perspective, great addition @jenlampton 

I'm not a fan of the gray region text, wondering if stealing the fieldset title style would accomplish a similar purpose? It doesn't necessarily adjust it's visual hierarchy, but it will separate it visually. Which I think is what we need more than a change in visual dominance.

```
  text-transform: uppercase;
  font-size: (REM or EM that gets it to 14px or 16px);

```

**Comment by wesruv** [comment] 2016-06-05 16:58
I think removing the rounded corners on the regions (not the blocks) *might* work even better, again just to differentiate them visually a little bit.

Re: theme selector/theme preview
How would this work? Ideally you'd see the page with actual content, but that might require a content id to render properly. If we have the block admin stuff appear in the theme that would mean every theme has to make sure block admin UI has styles.

We could try to think up a system to preview the site that covers the theme/style/layout settings pages. I think they all have similar issues and could be covered by one module, assuming we can get the functionality right.

**Comment by jenlampton** [comment] 2016-06-05 22:20
We should create a separate issue for preview.

**Comment by wesruv** [comment] 2016-06-06 17:33
@jenlampton ^^ :smile:

**Comment by jenlampton** [comment] 2016-06-09 21:43
Thanks @wesruv :) I've squared off the corners of the drop-zones and it looks a lot bettter. I also added a drop-shadow behind each block, and made the region label text uppercase. 
![drop-shad](https://cloud.githubusercontent.com/assets/397895/15947476/8b359eda-2e50-11e6-8fe4-3cd4401e1804.png)

**Comment by klonos** [comment] 2016-06-10 20:51
Love it! ...although I think that a 4px `h-shadow` instead of 0 would look better.

**Comment by jenlampton** [comment] 2016-06-10 22:30
You are **so** right. updated.
![h](https://cloud.githubusercontent.com/assets/397895/15980412/3664d936-2f20-11e6-89d8-304a7089bf3e.png)

**Comment by olafgrabienski** [comment] 2016-06-10 22:46
Very nice! Just one suggestion for the moment: the _Sidebar_ region is very narrow, why not make it a little wider? I guess, _Content_ and _Sidebar_ could be displayed in a ratio of 2:1 or so.

**Comment by jenlampton** [comment] 2016-06-10 22:48
Thanks for your feedback @olafgrabienski! :) The layout seen here is just a reflection of the front-end layout, and this one happens to be a 25% 75% division. Other layouts will be different, or this can be overridden in the theme.

**Comment by olafgrabienski** [comment] 2016-06-10 22:57
Got it, thanks! As there is not so much horizontal space on the place-blocks page, might it be useful to define a min-width for the displayed regions?

**Comment by jenlampton** [comment] 2016-06-10 23:01
Interesting, so even if the page is 75/25 on the front, we could do a 60/40 split on the back, or something? I wonder if that would get confusing with the more complicated layouts, like Simmons. 

![simmons](https://cloud.githubusercontent.com/assets/397895/15980967/81b8644e-2f24-11e6-9e86-85a8bca37395.png)

**Comment by olafgrabienski** [comment] 2016-06-10 23:10
You're absolutely right! The motivation of my suggestion was the not so nice look of the **User Login** block title and it's _Configure_ link, but I ain't got no better idea yet ...

**Comment by jenlampton** [comment] 2016-06-10 23:13
Yeah, I've scowled at that block several times too. We could certainly override the sidebar width for a few of these layouts to make the most-common ones look better, but it would be ideal to find a solution that works for all of them. Would you please open a new issue about this problem so don't forget to come up with better ideas? :)

**Comment by olafgrabienski** [comment] 2016-06-10 23:21
Yes, I will think about it and open an issue in the next days.

**Comment by wesruv** [comment] 2016-06-11 20:43
@jenlampton if we took away flex-wrap and overrode some widths browsers *should* be able to handle slightly different widths on the admin side.

@jenlampton a small nitpick on the box-shadow, I like that it's 45deg now, but I would get rid of the blur on the dropshadow. The rest of @dariusgarza's designs have been with the 'flat' look, avoiding gradients, it'd be nice to keep that consistent here.

If a non-blurred shadow looks awful, I'd be cool with making an exception here, as I think the box-shadow is serving a function in this case of raising those elements up a bit, visually.

**Comment by klonos** [comment] 2016-06-11 23:12
If we take out blur/spread, then 4px is too much. Here's an animation that shows each alternative in order to compare:

![backdrop-better_blocks_placement_ui_aesthetics-full_page](https://cloud.githubusercontent.com/assets/2423362/15987872/d1a2a794-307d-11e6-8827-423af582b6b0.gif)

**Comment by klonos** [comment] 2016-06-11 23:18
...and a zoomed-in version:

![backdrop-better_blocks_placement_ui_aesthetics-zoomed](https://cloud.githubusercontent.com/assets/2423362/15987889/8a3c66be-307e-11e6-9765-eaed9be3c260.gif)

**Comment by jenlampton** [comment] 2016-06-12 04:15
I also think it's too dark.  @klonos what's the 3rd version in your close-up? Is that a color-change too or are we back to having the blur there?

**Comment by klonos** [comment] 2016-06-12 10:35
@jenlampton 1st frames are your version (with the blur), 2nd set of frames is again your version but with the blur removed and the shadow left at 4px, the last set of frames has no blur but also shadow reduced to 2px.

**Comment by wesruv** [comment] 2016-06-12 18:51
@klonos I would try lightening up the color. I'd make it the border color or a smidge darker than the border color.

**Comment by klonos** [comment] 2016-06-13 09:10
Here's my take with 2px, no blur and `#ccc`:

![backdrop-better_blocks_placement_ui_aesthetics-2px_shadow_no_blur_ccc](https://cloud.githubusercontent.com/assets/2423362/16002347/83d8d51a-319a-11e6-8f51-d325a68c72c5.png)

**Comment by olafgrabienski** [comment] 2016-06-13 10:14
@jenlampton regarding blocks like the **User Login** block in a narrow context. (Instead of opening a new issue) I'd like to propose a small adjustment:

If there is too less space because of layout definitions (or when the admin page is visited on narrower screens), let's remove the float and the right alignment of the _Configure_ link. To do that, I changed the CSS of my backdrop 1.4.2 site via Firebug as follows:

- removed `float: right;` from `.layout-editor-block-title .buttons`
- removed `right: 0;` from `.js .dropbutton-widget`

---

Further improvements for narrower screens could include (just some ideas):

- change the horizontal padding of `.layout-editor-block-title` to `0.5em`
- remove `text-transform: uppercase;` from `js .dropbutton a`
- add a `span` element to the _Configure_ link to save space:  
  - `<li class="configure"><a>Config<span>ure</span></a></li>`  
  - add `.js .dropbutton li.configure span { display: none; }`

Well, I guess the responsive design of the _place blocks page_ would indeed be a separate issue - have you discussed it already anywhere?

**Comment by klonos** [comment] 2016-06-13 12:06
@olafgrabienski there are better ways to chop text (https://www.paciellogroup.com/blog/2012/05/html5-accessibility-chops-hidden-and-aria-hidden) but no matter how much we chop button labels, we'll still have issues with them. Especially in languages that use long words. A much better option IMO would be to be replacing the text with icon fonts (#364) when the viewport gets narrow. Icons can still have text, which is a big + for people using screen readers.

**Comment by olafgrabienski** [comment] 2016-06-13 13:28
@klonos Yes, I imagined that there were better ways. (Thanks for the link!) Especially the 'span' suggestion wasn't intended as good practice but only to get an idea where to save space. The use of icon fonts seems a good approach.

**Comment by jenlampton** [comment] 2016-06-13 15:47
Can we open a new issue for making it better for small screens? These are
all great ideas but I don't want this discussion to delay these aesthetic
changes, which I hope to get in asap, before the newsletter goes out!

**Comment by klonos** [comment] 2016-06-14 08:24
> Can we open a new issue for making it better for small screens?

😉

**Comment by olafgrabienski** [comment] 2016-06-14 08:30
Thanks a lot, @klonos !

**Comment by jenlampton** [comment] 2016-06-16 20:57
This adjusts the box-shadow based on suggestions from @wesruv and @klonos but I used the color `#d0d0d0` because I felt `#cccccc` was a smidge too dark, and we were already using the former elsewhere (borders of form elements).

![final](https://cloud.githubusercontent.com/assets/397895/16132943/4482bade-33ca-11e6-831c-473655068cda.png)

**Comment by klonos** [comment] 2016-06-16 22:38
Yeah, about the color, I just picked something randomly. Not a designer or a very artistic person.

**Comment by wesruv** [comment] 2016-07-03 00:15
@jenlampton me gusta!

**Comment by jenlampton** [comment] 2016-07-05 21:48
Pushed a new PR that addresses @wesruv's feedback.

**Comment by jrearick** [comment] 2016-08-07 21:56
Looking good. I especially like how the drop targets are highlighted with blue. This helps re-enforce to the use they are dropping in the correct spot.

**Comment by quicksketch** [comment] 2016-08-15 03:47
Manually merged in https://github.com/backdrop/backdrop/pull/1434. Agreed this looks a lot better. Great job @jenlampton! This will be in 1.4.4.

**Closed by quicksketch** 2016-08-15 03:47 UTC
Labels: status - has pull request, design
