### ISSUE TITLE
Multi language demo site

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1574] opened 2016-01-24 18:55 UTC
Hi!

Sorry, may be you can link me to a demo multi language site where I can see how it is done (inside admin).

I do not understand a logic of Backdrop CMS, how to make a multi language site.

Thank you!

**Comment by klonos** [comment] 2016-01-25 19:45
Hi @bd0bd I think it would be easier to start a website and take it step by step. Each time you are stuck somewhere, just post a question here and I'm sure someone will help you...

1. First enable the "Content Translation", "Language" and "Locale" modules (from ```/admin/modules```)

2. Add the languages you need (```/admin/config/regional/language/add```)

3. Configure language detection (```/admin/config/regional/language/detection```)

4. For each content type (Page, Article) go to their respective configuration page and scroll down to the "Publishing settings" tab and enable the " Enabled, with translation" option under "Multilingual support".

5. Now, each time you create a page or article (or any other content type that you have enabled content translation), you will see a "Language" option with a drop-down menu that includes the languages you have enabled in step 2.

For translating other things like menus, it gets a bit tricky: You need to create one menu for each language and then place them all in the same region in your layout (```/admin/structure/layouts/manage/default```). In order to show only one menu instead of all, you will need to edit each menu and configure its visibility conditions. Add a "Site language" visibility condition for each menu and only select the language which corresponds to them individually.

**Comment by klonos** [comment] 2016-01-25 19:49
...for menu translation, we have this #225

**Comment by bd0bd** [comment] 2016-01-25 20:35
Hi @klonos, thank you!
I need time to think about :)

**Comment by klonos** [comment] 2016-01-25 20:49
Sure @bd0bd, as I said, take it step by step and should you need help, just post a comment here.

**Comment by steve65140** [comment] 2016-02-01 16:38
Hi,
I've just started to build a simple site in English and French to try out Backdrop. Whilst I can create and view translations of content OK I can't see how I can translate field names. Also, when I log in as a user who's default language is French and edit content the UI is in English. Have I done something wrong or have I missed something important with the site set-up? I've built numerous multi-lingual sites with D7 but have zero experience with Backdrop.
Cheers.

**Comment by bd0bd** [comment] 2016-02-16 07:32
Add a "Site language" visibility condition for each menu

Sorry, I do not see this option in the menu.
The only fields there are - Title and Description.

**Comment by klonos** [comment] 2016-02-16 09:46
In ```/admin/structure/layouts/manage/default```, click the "Configure" button for you menu block. Then in the dialog that comes up, click the "Visibility conditions" fieldset to expand it and then click on the "+ Add visibility condition" link. Then select "Site language" from the drop-down menu, then the "Add visibility condition" button, then select the language you want the menu to show up for. Finally click the "Add visibility condition" button one more time.

Repeat this procedure for every language-specific menu you have, each time selecting the respective language you want it to show up for.

Once done with setting language visibility conditions for all the menu blocks you have, hit the "Save layout" button at the bottom of the layout edit form.

**Comment by bd0bd** [comment] 2016-02-16 15:52
@klonos, thank you very much!
You have explained too much details I already know about but of cause this information will be helpful for less familiar Backdrop's users.
Thank you!

Well, in your initial post you have wrote me almost the same but I was complicated a little bit and careless. I am sorry.

**Comment by bd0bd** [comment] 2016-02-16 16:15
I have added 2 Primary navigation blocks and saved layout.
But it says "This form has unsaved changes ...".
Also I do not understand about Main page content block - why it ask me to add it if there was this block. Should I add 10 Main page content blocks if the site has 10 languages?
Thank you!

![navigation](https://cloud.githubusercontent.com/assets/13515302/13082244/b135fef8-d4f1-11e5-94b7-f8bf474edded.png)

**Comment by bd0bd** [comment] 2016-02-16 19:25
Hm, do not understand the logic how to make multilingual site with Backdrop.
This is why I ask for a demo to see it inside admin.
Problems arise from nothing.
I have done multilingual sites with other CMSs and there were no problems and the logic was simple.

I am complicated with menu. I do not understand how to make necessary things.
The best solution to understand - to see a demo site.

**Comment by bd0bd** [comment] 2016-02-16 19:57
For example, not clear why English menu displays on German and French versions of site. The English menu has permission only for English version.

**Comment by klonos** [comment] 2016-02-16 21:08
Hey there @bd0bd I think you either have discovered some bugs with the layout UI or you have done something wrong, so please be patient as I try to get us to the bottom of this...

1. Did you try to edit the default layout when you received the error message about the main content block? ...or did you try creating a new layout? I'm only asking because from the screenshot you provided, if you look in the "Content" region (the one below the "Page title" part), there is no block in it. The "Main page content" is indeed missing. So the error message you get is correct. But did you intentionally remove it, or did this happen when you added multiple menu blocks (per language)?

2. Each time you add a new block, or remove an existing block, or edit the settings of a block (visibility conditions for example) or move a block around either to a different region or just to change its order within the same region, in all these cases the layout page needs to be saved (the "Save layout" button at the bottom of the page). That's why you get the "This form has unsaved changes." warning. Are you saying that you got this warning **after** you have already saved the layout?

Anyways, I have tried the following in order to reproduce your issues:

- edited the default layout
- edited the already existing "Primary navigation" block to add a visibility condition of "Site language is Greek"
- added another "Primary navigation" block in the Header region and set its visibility condition to "Site language is English"

...at this point I only have the two "Primary navigation" blocks is place and my "Main page content" block is still in the "Content region":

![backdrop-issue1574](https://cloud.githubusercontent.com/assets/2423362/13091039/60206632-d54d-11e5-8481-0ebbd23bfd61.png)

IMPORTANT: You need to click the "Save layout" button in order for your changes to be saved!

**Comment by klonos** [comment] 2016-02-16 21:15
Anyways, **doing things this way will NOT achieve what you are after**. You need to create **separate menus for each language** (until we solve #225). What you are doing now is placing the **same menu block** multiple times. This will NOT work.

**Comment by bd0bd** [comment] 2016-02-16 22:27
But did you intentionally remove it, or did this happen when you added multiple menu blocks (per language)?
I did not removed this block. I do not know if the block was there before I have started to add additional menu blocks. Well now I have the same as on your picture.
I remember well about the "Save layout" button - I make websites from 1997-98.

    Are you saying that you got this warning after you have already saved the layout?

Yes! This happened after I have already saved the layout. The reason - there was no Main page content block. After adding a Main page content block the layout was saved successfully.

![lang](https://cloud.githubusercontent.com/assets/13515302/13093258/2244f368-d526-11e5-8108-f73b9c78a066.png)

Do not understand what to make next :)

**Comment by bd0bd** [comment] 2016-02-16 22:29
You need to create separate menus for each language
Not clear what do you mean.
How to do it?

**Comment by klonos** [comment] 2016-02-16 22:44
1. Go to ```/admin/structure/menu```.
2. Click the "+ Add menu" link at the top left.
3. Give the new menu a title of "German primary navigation" and save.
4. Add any menu items to this menu that lead to the German URLs of your site.

Now, repeat these steps to add a "French primary navigation" menu and add any French menu item URLs.

Now...

1. Head to the layout and **remove** the two "Primary navigation" blocks that you have added before.
2. Add the "German primary navigation" menu block and make it visible only when the language is German.
3. Add the "French primary navigation" menu block and make it visible only when the language is French.

I know that this is tedious and it would be easier it there was a single menu block that you could place in the layout, but as I already said, this feature is not implemented yet in Backdrop. It's #225

**Comment by bd0bd** [comment] 2016-02-16 23:01
> only when the language is French
But how to switch to another language?
Simply by directing to appropriate URL?: domain.com/fr

**Comment by bd0bd** [comment] 2016-02-16 23:15
Yes! Now it seems I did it.
@klonos, thank you very much for all your help! :)

**Comment by bd0bd** [comment] 2016-02-16 23:21
Another unclear thing: pages of all 10 languages will be messed up together on the same page?
In my case (another CMS) I have separate pages for each language.

![lg](https://cloud.githubusercontent.com/assets/13515302/13094597/8a13cfda-d52d-11e5-95db-43b9c4df66a0.png)

**Comment by bd0bd** [comment] 2016-02-16 23:54
Again misunderstand the logic.
I translate English menu item **About Us** into German **Uber uns** and it adds to English menu block.
In my logic it should be added to German menu block - no?
![1](https://cloud.githubusercontent.com/assets/13515302/13095275/82307cfa-d532-11e5-9556-df2c20e61a65.png)
![2](https://cloud.githubusercontent.com/assets/13515302/13095280/8cc453b2-d532-11e5-999a-560d7e123ffa.png)

**Comment by bd0bd** [comment] 2016-02-17 00:50
I have translated menu item into German but it does not appears in the German menu block.
![de](https://cloud.githubusercontent.com/assets/13515302/13096281/1ec565a6-d53a-11e5-87a0-546293c06a65.png)

**Comment by bd0bd** [comment] 2016-02-17 00:59
It seems I understand the problem.
We should go to de/admin/structure/types/manage/page and check French primary navigation and German primary navigation.
![menu](https://cloud.githubusercontent.com/assets/13515302/13096439/4f5ab45e-d53b-11e5-9ab8-0996abb03e48.png)

**Comment by klonos** [comment] 2016-02-17 01:17
...you are almost there. :clap:

Trust me, this is hard to do in Drupal, but we are doing our best to improve things in Backdrop. This will take some time and until then you'll have to be patient.

To the issue at hand though. What you need is to allow the "Basic page" content type to use the new menus you have created. To do this:

1. Go to your content type settings page (I am assuming this is a "Basic page" you are using): ```/admin/structure/types/manage/page```
2. Scroll down to the menu settings. You will see that only the original (English) "Primary navigation" menu is available for placing links. Enable the "German primary navigation" and the "French primary navigation" menus as well.
3. Save the content type.

Now edit the German "Uber uns" page and scroll down to the "Menu settings" section and switch the "Parent item" from "Primary navigation" to "German primary navigation".

Do the same for the French "À propos de nous" (I used Google translate) page but select the "French primary navigation" menu instead.

Repeat for each language and you're done!

**Comment by klonos** [comment] 2016-02-17 01:18
> ...What you need is to allow the "Basic page" content type to use the new menus you have created.....

Oh, it seems you have figured this out already! Great! :tada: :sparkles:

**Comment by bd0bd** [comment] 2016-02-17 12:18
@klonos, thank you very much for the help!

Drupal (and Backdrop) is a long time established **international** CMS and I wonder how difficult it is to make/configure a multi language website. About 6 years ago I have used a simple **national** CMS (targeted for local web-developers) created by a single PHP programmer and it was easy to configure/setup a multi language website.

**Comment by bd0bd** [comment] 2016-02-17 12:37
Well, how I can understand all pages will be displayed all-together - 10 Home, 10 About, 10 Contact etc. Of cause it is not good. Good - when displayed only the pages of appropriate language.
But may be is it possible to filter the pages? Please see the picture:
![filtering](https://cloud.githubusercontent.com/assets/13515302/13109684/bf7c8f80-d59c-11e5-8b77-d180ea8ac333.png)

**Comment by klonos** [comment] 2016-02-17 19:05
What you have in your screenshot is the "Find content" page. This page is created by a View. So if you go to ```/admin/structure/views```, you should be able to edit that specific view. It's called "Admin Content"...

By default, that view does not list or filter content language, but you can add that (and whatever other criteria you may need). For the language specifically, you'll need to...

a) add the "Content: Language" field to the "Fields" section (that will add a "Language" column in the "Find content" page)

b) add the "Content: Language" filter in the "Filter criteria" section (that will add a filtering option for language at the top). Just make sure you configure the filter as "exposed" (the "Expose this filter to visitors, to allow them to change it" checkbox), so that you can have a drop-down that people can use in order to filter by language.

That should do it.

**Comment by klonos** [comment] 2016-02-17 19:16
...oh, I forgot to mention that once you are happy with the view, you need to **remember to save it**! The view edit page works like the layout edit page: no change is saved until you hit the save button.

**Comment by bd0bd** [comment] 2016-02-17 19:27
Thank you very much!
This filtering option is a good solution.
This is an option I would expect for multi lang. site.
But I believe it should be setup and displayed automatically if any additional language is added to a website.

**Comment by bd0bd** [comment] 2016-02-17 19:52
Last selection problem.
If I select **English** then it switch again to **Any**.
![0](https://cloud.githubusercontent.com/assets/13515302/13122604/a4cbcf56-d5d9-11e5-8c97-7492f413b211.png)
![1](https://cloud.githubusercontent.com/assets/13515302/13122617/afcbaa48-d5d9-11e5-969f-3e00278da49e.png)
![2](https://cloud.githubusercontent.com/assets/13515302/13122644/d6e8af86-d5d9-11e5-9aa1-3a9046a0cb3a.png)

**Comment by klonos** [comment] 2016-02-17 21:04
> But I believe the switcher should be setup and displayed automatically if any additional language is added to a website.

That's why I filed #1625 for consideration :wink: 

I was able to verify the issue with the "Remember last selection" option, so I filed an issue for it too. I'm sure it will be fixed soon.

**Comment by bd0bd** [comment] 2016-02-17 22:04
Thank you!

**Comment by quicksketch** [comment] 2016-02-18 20:00
> I was able to verify the issue with the "Remember last selection" option, so I filed an issue for it too. I'm sure it will be fixed soon.

Thanks @klonos for filing this over in https://github.com/backdrop/backdrop-issues/issues/1626. :smile:

**Comment by BWPanda** [comment] 2019-11-07 16:53
Closing this old question that appears to have been answered now.

**Closed by BWPanda** 2019-11-07 16:53 UTC
