### ISSUE TITLE
Hero block file_usage always increments, never decrements

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4215] opened 2019-11-19 15:35 UTC
**Description of the bug**
When using a hero block and changing the image, the file usage count is recorded wrong.

**Steps To Reproduce**

1. Add an image to a hero block
2. Save that block again (without changing anything)

**Result:** The file usage count has incremented
Whenever the hero block form is saved, the file usage increments.

1. Add an image to the hero block
2. Remove that image from the hero block

**Result:** the file usage is still the same.

**Expected behavior**
We should add file_usage_delete() to function formSubmit to get correct file usage counts.

**Additional information**
- Backdrop CMS version: latest dev

I don't think that there's a related Drupal bug.

- - - - - - - - -

PR by @indigoxela = https://github.com/backdrop/backdrop/pull/2993

**Comment by indigoxela** [comment] 2019-11-19 16:08
A PR is available, please test and review.

**Comment by stpaultim** [comment] 2019-11-20 01:38
I confirmed the bug in a Tugboat site and then confirmed that the PR fixes the problem. 

As usual, I can report that this fix "works for me" but I can't say if it's the right fix or pass any judgement on the code. Hopefully, someone smarter than me can review the code.

**Comment by herbdool** [comment] 2019-11-20 05:26
The code looks good to me.

**Comment by quicksketch** [comment] 2019-12-20 05:25
Thanks folks! Merged https://github.com/backdrop/backdrop/pull/2993 into 1.xx and 1.14.x.

**Closed** 2019-12-20 05:25 UTC
Labels: status - has pull request, status - fixed
