### ISSUE TITLE
AJAX calls break CKEditor...

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1564] opened 2016-01-21 19:26 UTC
Steps to reproduce : 

Create a node Article, supply an image in the supplied field_image, Save.
Edit the article, click the Remove button near the image...
The body textarea has lost its CKEditor attachment !

I suspect an unbalanced set of 
`Backdrop.filterEditorAttach(field, Backdrop.settings.filter.formats[activeEditor]);`
and
`Backdrop.filterEditorDetach(field, Backdrop.settings.filter.formats[activeEditor]);`
in `core/modules/filter/js/filter.js` : commenting the detach at line 89 seems to solve the problem in most cases, but the root of the problem is obviously elsewhere...

**Comment by gifad** [comment] 2016-01-22 01:37
Reproduced on a 100% clean install of Backdrop v1.3.2
Actually, the editor is detached at the first click on the "Upload" button.
It can be re-attached by selecting another format, then selecting the original format.

**Comment by klonos** [comment] 2016-01-23 01:15
> Actually, the editor is detached at the first click on the "Upload" button.

Confirmed.

**Comment by serundeputy** [comment] 2016-07-08 10:38
from @Graham-72  https://www.drupal.org/node/2691101

**Comment by klonos** [comment] 2016-07-09 04:21
PR up for testing. Direct port from the RTBC patch in the respective d.org issue, so any credits should go to @tanius

Thanx @serundeputy & @Graham-72 for pointing to the issue.

**Comment by klonos** [comment] 2016-07-09 04:36
...seems to be working fine. Not sure if the change could potentially break other things, but all tests pass. So, I guess it's good.

**Comment by serundeputy** [comment] 2016-07-09 15:22
Thanks @klonos code looks good and works.  I don't think this can break anything else.  I've tested this against http://1459.backdrop.backdrop.qa.backdropcms.org/ and against my local and it is working as advertised.

I was looking into writing a test for this, but encountered this in `file.test` lines 482 and 483:

```php
// @todo This only tests a 'nojs' submission, because backdropPostAJAX()
//   does not yet support file uploads.
```

which I think means that we can not leverage file field uploads via AJAX in our tests ... is that right @quicksketch ?

Marking as reviewed and tested by the community.  Thanks @klonos !

**Comment by klonos** [comment] 2016-07-10 01:28
😉

**Comment by quicksketch** [comment] 2016-07-22 18:57
Nice one @klonos! Yes this looks good to me too. We don't have JS-level testing so manual is the best we can do for the time being. @serundeputy would you do the honors?

**Closed** 2016-07-22 19:29 UTC
Labels: pr - reviewed & tested by the community, status - has pull request, type - bug report

**Comment by serundeputy** [comment] 2016-07-22 19:34
Thanks @klonos this fixes a pretty ugly bug!
This is merged into `1.x` and `1.4.x` and will ship with `1.4.4`.

thanks everyone!

**Comment by klonos** [comment] 2016-07-22 20:06
Thanx, but all credits should go to @tanius as previously said.
