### ISSUE TITLE
[UX] Allow comments to be (truly, entirely) disabled on a per-content type basis.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1472] opened 2015-12-31 08:35 UTC
The way it currently is, when the comments for a content type are set to "closed", what actually happens is that a _default_ is set for _new_ nodes of that content type. There is still an option while creating/editing a node to open/allow comments. So, in reality comments cannot be _disabled_ on a per-content type basis.

There is at least one issue in the d.org queue about this: https://www.drupal.org/node/2085885 ...it was initially filed against D7, then switched to D8 (on the excuse of "things go against head first - then backported") until it was finally closed as "cannot reproduce" with this comment:

> In d8 comment settings are fields and page content type does not have comment field by default.

Typically dismissing too easy a long-standing, perfectly valid issue if you ask me.

There is also a discussion in the d.org support forum: [How to disable comments by default for specific content type?](https://www.drupal.org/node/958886)

It is clear from all the linked discussions above that this baffles people depending on what they expect from this setting and how they perceive the notion of open vs closed comments.

We have recently improved this a lot in #764, but there is still a thing that we have not addressed:

@quicksketch, in https://github.com/backdrop/backdrop-issues/issues/764#issuecomment-168096550

> ...comments can still be enabled per-node. The Open/Closed setting is only the _default_, so number of comments per page and other settings are still relevant if comments are opened on the node individually. However, I think this brings up a great point that you should be able to truly _disable_ comments entirely on a single type, rather than it only being a default.

...that is what this issue here is about...

There exists of course the "Post comments" permission that site admins can use to disallow comment posting, but this is a global and NOT a per-content type setting. So we could solve this if we split this into a more granular per-content-type permission, but then why not (in the spirit of "putting things where people expect to find them" - copyright by @jenlampton) have a "Disabled" setting in the content type edit form.

Since the most common use case is that site admins create and configure content types and they are the ones that would decide on this setting, why have them going to a separate (and admittedly complicated/cluttered) page such as the permissions page. So, lets add a "Disabled" checkbox in the content type edit form that truly disables comments on a per-content-type basis:
1. sets the comments for _all_ nodes of the content type to "hidden" (to account for possible past comments)
2. removes the entire "Comment settings" vtab in the node edit/create form for the content types where this setting is enabled
3. uses #states to hide all settings in the "Comment settings" vtab in the content type edit/create from (and updates the vtab summary to simply say "Disabled").

**Comment by klonos** [comment] 2015-12-31 09:06
...there's a contrib module that addresses this: [Comment Permissions](https://www.drupal.org/project/comment_perm)

> The Comment Permissions module enables control of commenting by user role and by node type. Additional user permissions for selected node types are added to the user access system so you can configure commenting with more control than Drupal core provides.

...not entirely sure about the per-user-role permissions. It might be complicating the permissions page even more. Perhaps leave that part for contrib. ...unless of course people think that having specific users comment on specific content types while others should not is a common use case.

**Comment by BWPanda** [comment] 2019-07-31 16:19
Going to close this as a duplicate of #3016 as that issue has a lot more (recent) discussion and seems to be addressing the same problem...

**Closed by BWPanda** 2019-07-31 16:20 UTC
Labels: status - duplicate
