### ISSUE TITLE
[UX] Text formats: provide a way to re-enable disabled formats via the admin UI

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1575] opened 2016-01-24 23:31 UTC
A 'Disabled' text format is different than every other 'Disabled' thing in the admin Ui. A text format, once disabled, can not be enabled again. Everything else can. This can be a pain-point for admins who think they know what to expect.

Possible solutions that have been considered:

1) Allow admins to re-enable disabled text formats, making the operation reversible.
2) Change the name from 'Disabled' to something more like 'Hidden'
3) Allow admins to completely 'Delete' a text format (possibly dangerous!)

The final approach taken in this issue was to keep disabled formats in the text formats list in `/admin/config/content/formats`, denote them as disabled, and allow for them to be re-enabled (via a newly-introduced "Enable" operation). See https://github.com/backdrop/backdrop-issues/issues/1575#issuecomment-527534721 for a screenshot of this implementation.

This fixes the actual UX issue here, which is that previously we were telling people that we are going to disable the text format, but what we were actually doing instead was to completely remove it from the UI, leaving the user wondering how to recover from this situation. Advanced users knew how to revert this, by manually editing the config files; the new implementation makes it so that even novice users can accomplish the same thing via the admin UI.

The actual "Remove" functionality, and whether we should implement that as complete removal of the text format config files, or simply hide them from the admin UI and keep the config files in place, was left as a follow-up task in #4013.

---

## Original Issue

Most site admins think that something "disabled" can be "enabled" again.
Ok, there is a confirm screen, but not everybody read them, especially if they are written in a foreign language (and drupal-7.41.##.po does not include text of `admin/config/content/formats/{format}/disable`)...

----

Advocate:  @klonos

----

Weekly update?

----

~~PR https://github.com/backdrop/backdrop/pull/2821~~ by @BWPanda
~~PR https://github.com/backdrop/backdrop/pull/2826~~ by @klonos (based on @BWPanda's original PR): 
~~PR https://github.com/backdrop/backdrop/pull/2845~~ by @quicksketch 
~~PR https://github.com/backdrop/backdrop/pull/2846 by @jenlampton~~
~~PR  https://github.com/backdrop/backdrop/pull/3024~~ by @klonos
PR https://github.com/backdrop/backdrop/pull/3071 by @docwilmot

**Comment by quicksketch** [comment] 2016-01-26 05:13
This might be a good idea, but I'll explain why it's "Disable" and not "Remove":

Text formats may contain sensitive information in them, such as executed PHP code or internal information that shouldn't be shown to a site visitor. If you "delete" a text format, it is *not removed* from configuration files or content in the database that currently uses that text format. The text format is removed from the admin interface, but it actually still exists and will be used on all existing content that had used that format previously.

So "disable" is definitely a more accurate word than "remove", but you're right that users expect that a format should be able to be re-enabled after it has been disabled. I could go either way on this one.

**Comment by klonos** [comment] 2016-01-26 10:51
...then it seems to me that instead of retitling, we should perhaps change the way this works and have formats be disabled (as in not available to be used with new content unless re-enabled).

**Comment by gifad** [comment] 2016-01-26 11:06
Thanks for the explanation, I was confused by the fact that it is not actually disabled until you manually flush caches...
If you keep on the concept of disable, it should stay in the list, with an "enable" option (like views)
If you don't, please remove the config file...

BTW, if the site is on a shared hosting with no ssh access, some admins will think that phpMyAdmin was not that bad to solve this kind of issue...

**Comment by klonos** [comment] 2016-01-26 11:19
> If you keep on the concept of disable, it should stay in the list, with an "enable" option (like views)

That would be the best way to go about it IMO.

**Comment by quicksketch** [comment] 2016-01-27 03:33
Sure, sounds good to me.

**Comment by mikemccaffrey** [comment] 2016-01-27 05:49
> The text format is removed from the admin interface, but it actually still exists and will be used on all existing content that had used that format previously.

Wait, so disabling a text format doesn't actually keep it from continuing to be used on content? That seems dangerous if you are trying to disable a format that executes php code, and expect that all the php code that has been inserted into your content will no longer be run.

**Comment by gifad** [comment] 2016-01-27 09:39
@mikemccaffrey : the content stays in the database, but it will not be rendered as soon as you flush caches.
a cache_clear_all() would be wellcome here...

**Comment by olafgrabienski** [comment] 2017-06-16 14:08
I stumbled about this issue and saw that it's open for a long time. As far as I understood, everyone agreed that disabled text formats should stay in the list and get an "enable" option.

Just as a reminder: If we do so (I agree as well), we should also change the following text on the disable confirmation page:

> Disabled text formats are completely removed from the administrative interface, and any content stored with that format will not be displayed. This action cannot be undone.

It could become something like: 

> Any content stored with the disabled text format will not be displayed.

**Comment by olafgrabienski** [comment] 2019-04-25 08:34
Not remembering this issue, I just 'disabled' a text format for test purposes. Now I don't see an option to re-enable it, that's not good!

(Changed the label from "feature request" to "bug report".)

**Comment by klonos** [comment] 2019-04-25 19:44
Until we actually support disabling (and re-enabling) text formats, I think that the "disable" action and any accompanying help text, page titles etc. should be renamed to "delete" or "remove".

`Disabled text formats are completely removed from the administrative interface, and any content stored with that format will not be displayed. This action cannot be undone.`

The above also reads data loss to me. Provide absolutely no way to recover content created using these formats is really bad.

**Comment by olafgrabienski** [comment] 2019-05-22 10:57
> Until we actually support disabling (and re-enabling) text formats, I think that the "disable" action and any accompanying help text, page titles etc. should be renamed to "delete" or "remove".

@klonos Why not allow disabling and re-enabling text formats straight away? I think, everyone agreed to it.

**Comment by klonos** [comment] 2019-05-22 17:59
> Why not allow disabling and re-enabling text formats straight away?

More work 😅

**Comment by klonos** [comment] 2019-08-10 04:31
...I have tried editing the issue summary (original report), but my changes do not get saved (I'm assuming because the original reporter has deleted their GitHub account). Here's the summary and screenshots from #3962, which was closed as a duplicate of this:

**Description of the bug / Steps To Reproduce**
1. Go to `admin/config/content/formats`
2. Select the "Disable" action for any text format...

**Actual behavior**
Despite the "Disabled text format xyz" message, the format gets completely removed, and there is no way to get it back:

<img width="1180" alt="Screen Shot 2019-08-03 at 6 02 03 pm" src="https://user-images.githubusercontent.com/2423362/62413592-48016780-b619-11e9-9e8d-7fa74a0fdbb4.png">

Even the confirmation message is confusing:

> Disabled text formats are completely removed from the administrative interface, and any content stored with that format will not be displayed. This action cannot be undone.

<img width="690" alt="Screen Shot 2019-08-03 at 6 06 33 pm" src="https://user-images.githubusercontent.com/2423362/62413614-85fe8b80-b619-11e9-88ed-2f4696e2ce46.png">

**Expected behavior**
Either call the action "Delete" or "Remove", or make it so that text formats can be disabled and re-enabled.

**Comment by olafgrabienski** [comment] 2019-08-14 15:17
> Why not allow disabling and re-enabling text formats straight away?

>> More work

@klonos Can you estimate how much work it would be? Unfortunately, I'm not able to provide any code, but I'll be happy to test.

(Tagging with "help wanted".)

**Comment by klonos** [comment] 2019-08-14 16:20
> Can you estimate how much work it would be?

I am notorious for not being able to estimate dev work 😓

Here's what I am thinking:

1. This issue here should remain a bug report, and fix the text bit of the current functionality, so that it either says "remove" or "delete" instead of the current "disable", which is misleading.

2. Follow-up issue, which will be a feature request, to allow for a status/state value to be saved for each text format config. I guess that would be a new `disabled` property, and have values of `1` or `0`. We then need to update the text format listing page to accomodate for that, showing if each format is enabled or disabled, and also allow to enable/disable them.

**Comment by olafgrabienski** [comment] 2019-08-14 16:50
> 1. This issue here should remain a bug report, to fix the UX/text bit of the current functionality, so that it either says "remove" or "delete" instead of the current "disable" ...
> 2. Follow-up issue, which will be a feature request ...

Hm, as @quicksketch says in https://github.com/backdrop/backdrop-issues/issues/1575#issuecomment-174835548, "remove" and "delete" are not appropriate. So the bugfix would be to allow re-enabling.

**Comment by klonos** [comment] 2019-08-14 16:55
...that was from back in Jan 2016 😅 ...I'll have to review the code to see what actually happens, and where we can improve, but it does sound that the bug is that we do not provide a way ro reenable disabled text formats.

Thanks for pointing out that comment @olafgrabienski 👍

**Comment by BWPanda** [comment] 2019-08-15 10:37
I've made an *initial* PR (needs works still) that allows disabled text formats to be enabled again. Please test and let me know what else needs to be done, but things I've noticed/didn't have time for/need advice on:

- Do we need a confirmation page to enable a disabled text format?
  - If so, what should the wording be on the confirmation page?
    - Confirm form 'Enable' button shouldn't be red
  - If not, how to activate it without a confirmation form...

**Comment by olafgrabienski** [comment] 2019-08-15 13:45
@BWPanda I've had a look at the sandbox page: I was able to disable and re-enable a text format, but without clear results:

- Added a custom text format.
- Created a page using the format.
- Disabled the format.
- Cleared cache and ran cron.
- Was still able to visit the page which uses the custom format. Was also able to edit the page, and the format was still there.

**Comment by BWPanda** [comment] 2019-08-15 13:56
@olafgrabienski That sounds like an issue with the current functionality. If you didn't get to re-enabling the format then my PR wouldn't have any effect I think...

**Comment by olafgrabienski** [comment] 2019-08-15 14:11
Yep, I was able to re-enable the format, so the PR has already an effect.

With my statement, I referred to the message `Any content stored with this format will not be displayed` (before disabling). It seems that the content continues to be displayed even if a format is disabled.

**Comment by olafgrabienski** [comment] 2019-08-15 14:30
I guess it's not fully clear to me what is expected to happen when a text format is disabled. From the comments in this issue:

> The text format is removed from the admin interface, but it actually still exists and will be used on all existing content that had used that format previously.

> I was confused by the fact that it is not actually disabled until you manually flush caches...

> the content stays in the database, but it will not be rendered as soon as you flush caches.

In the PR, with a disabled text format,

- the content of a disabled text format continues to be rendered, even after clearing caches several times, and
- the disabled format can still be chosen by an editor.

I've not tested so far if this happens also without the PR.

**Comment by klonos** [comment] 2019-08-15 14:50
Thanks @BWPanda ...I have taken a quick look at the code and the UI changes, and it looks good. Still needs some work as you said, but we're on a good path 👍

Some initial feedback (some may be follow-ups):

- I don't think that enabling a format needs a confirmation form.
- Rows of disabled formats should appear greyed-out, and also moved to the bottom of the table; same as in the Views listing and elsewhere.
- Add priority classes to the columns, so that the table displays properly on mobile. I am thinking that "Status" column should be low, and "Roles" medium.
- Roles should be rendered as a list, to improve readability/scannability, and to also render the column similarly on wide and narrow screens.
- Perhaps special-case the status text for the fallback format to something like "Always enabled".

I did not get to test this extensively, so cannot comment on @olafgrabienski's findings.

**Comment by BWPanda** [comment] 2019-08-15 15:07
@olafgrabienski Yeah, I think you'll find it acts the same without my PR. All it does is provide a UI to change a format's `status`. What happens when the status is 0 is up to the existing code.

**Comment by BWPanda** [comment] 2019-08-15 18:48
My apologies @olafgrabienski, it seems my PR does indeed cause the issues you're seeing. I had forgotten that I removed some code that prevents returning disabled formats, in order to display all formats on the overview form. However that same code is what's used in the Formatting Options dropdown. I'll have to find a better way to do this...

So sorry, but you were right. My bad.

**Comment by BWPanda** [comment] 2019-08-15 19:39
PR updated. Still yet to implement:

- Rows of disabled formats should appear greyed-out, and also moved to the bottom of the table; same as in the Views listing and elsewhere.
- Add priority classes to the columns, so that the table displays properly on mobile. I am thinking that "Status" column should be low, and "Roles" medium.
- Roles should be rendered as a list, to improve readability/scannability, and to also render the column similarly on wide and narrow screens.

**Comment by klonos** [comment] 2019-08-15 19:47
Thanks @BWPanda 👍 ...what do the parameters in `filter_formats(NULL, TRUE, TRUE)` do? https://api.backdropcms.org/api/backdrop/core%21modules%21filter%21filter.module/function/filter_formats/1 only mentions an `$account = NULL`.

**Comment by BWPanda** [comment] 2019-08-15 20:14
@klonos The 2nd parameter (`$include_disabled`) allows the caller to get disabled formats in addition to enabled ones (e.g. for the overview form), while the 3rd (`$reset`) allows bypassing the cache (there were issues otherwise).

**Comment by klonos** [comment] 2019-08-15 21:39
Oh OK, you are changing the function parameters as part of the PR. Sorry, I missed to notice that with your 2nd commit; I see it now 👍

I'm thinking that instead of changing the signature of the existing function, this might be a great opportunity to introduce a new function, with a proper name, like `filter_get_formats()`, or `filter_get_text_formats()` ...but not too fussed about it.

**Comment by olafgrabienski** [comment] 2019-08-15 21:52
> My apologies ...

No problem, @BWPanda! Looking forward to test the changed the PR when I find time!

**Comment by BWPanda** [comment] 2019-08-16 07:53
[PR](https://github.com/backdrop/backdrop/pull/2821) updated with latest requests. I think the Roles column is more important than Editor, so I've made it medium priority instead. I also don't think we need to change the name of the function @klonos, unless you want to file a separate issue for that?

![image](https://user-images.githubusercontent.com/2385329/63152030-8fbdc100-c013-11e9-8593-51f669a2ef2d.png)

Please test and let me know if I've missed anything.

**Comment by olafgrabienski** [comment] 2019-08-16 08:29
@BWPanda I've had a quick look at the PR, not at the UI but at the enabling/disabling actions. Works quite good now, I have observed caching issues though:

- When I disable a text format, content is still shown until I clear caches. Not ideal but acceptable, in my opinion.
- After disabling a text format, I can't re-enable or configure it otherwise, instead I get a "Page not found". Clearing caches seems to help here as well, but this should work immediately.

**Comment by klonos** [comment] 2019-08-18 03:24
> I also don't think we need to change the name of the function @klonos, unless you want to file a separate issue for that?

See how in my suggestion I said "not too fussed about it" @BWPanda? This can be a separate, DX follow-up 😉 

@olafgrabienski as far as I can see, @BWPanda's PR does not touch the code that handles disabling text formats. In fact all functions that enable/disable text formats (including the one that @BWPanda introduced), eventually end up calling either `filter_format_disable()`, which has the following bit of code:

```php
  // Clear the filter cache whenever a text format is disabled.
  filter_formats_reset();
  cache('filter')->deletePrefix($format->format . ':');
```

...or `filter_format_enable()`, which also has the same bit of code:

```php
  // Clear the filter cache whenever a text format is enabled.
  filter_formats_reset();
  cache('filter')->deletePrefix($format->format . ':');
```

...can you please check to see if you can reproduce the behaviour that requires cache clearing in a vanilla Backdrop installation (or on a Backdrop site other than the PR sandbox)?

In the meantime @BWPanda, I am curious why you have chosen to name the new function you have introduced `filter_enable()`, instead of naming it `filter_admin_enable()` (to match the respective `filter_admin_disable()`)? ...also, why place it in `filter.pages.inc`, instead of `filter.admin.inc`? Is there a convention that mandates any page callback to go in a `*.pages.inc` file?

**Comment by klonos** [comment] 2019-08-18 03:47
...general question: now that we have introduced a way to reinstate disabled text formats, should we introduce a function that *completely* removes them?

**Comment by klonos** [comment] 2019-08-18 04:00
New PR up for review: https://github.com/backdrop/backdrop/pull/2823 (based it off of @BWPanda's PR):

![Screen Shot 2019-08-18 at 6 53 39 am](https://user-images.githubusercontent.com/2423362/63219919-fadad500-c184-11e9-837f-e3b01a30b13b.png)

- Added help text above the table, to explain what the ordering does.
- Removed the "Status" column, and added a "Disabled formats" section.
- Added machine names, and made the human-readable names bolded (same as Views UI).
- Removed the drag handle and the weight select for disabled formats.

What still needs work:

- Naming and file of the new function that enables formats (pending feedback).
- Either disallow enabled formats from being dragged to the "disabled" section, or have them be disabled if moved there (also pending feedback).
- Confirm the caching issues reported by @olafgrabienski are not pre-existing.

**Comment by quicksketch** [comment] 2019-08-19 05:25
> ...general question: now that we have introduced a way to reinstate disabled text formats, should we introduce a function that completely removes them?

In my opinion, yes absolutely. And that would give us a place to put an adequate warning when fully deleting a text format.

(This looks great!)

**Comment by olafgrabienski** [comment] 2019-08-20 09:49
@klonos I just had a look at the PR's sandbox site:

- Cleared caches (before doing anything else).
- Set up a custom text format, and noticed other formats, amongst others two disabled ones, e.g. `aaa`.
- Created a page. Saw the disabled text formats as options in the *Formatting options > Editor* dropdown.
- Cleared caches again and edited the page: The disabled formats were still there.
- Re-enabled the `aaa` format, disabled it again, cleared caches multiple times.
- Edited the page again, and finally the disabled formats weren't anymore available in the dropdown.

Not sure what's going on here but caching seems to remain in issue.

**Comment by klonos** [comment] 2019-08-20 17:14
Thanks for testing this @olafgrabienski 👍 ...do you see the same behaviour on sites other than the PR sandbox?

I can add `cache_clear_all()` calls in, but this would be a "kill a mosquito with a cannon" solution. I first need to understand at which point things fail, in order to better deal with this.

**Comment by BWPanda** [comment] 2019-08-20 17:55
> In the meantime @BWPanda, I am curious why you have chosen to name the new function you have introduced filter_enable(), instead of naming it filter_admin_enable() (to match the respective filter_admin_disable())? ...also, why place it in filter.pages.inc, instead of filter.admin.inc? Is there a convention that mandates any page callback to go in a *.pages.inc file?

@klonos Honestly, I can't tell you... No idea why I chose that name (maybe copying from something else?), but as for the location of the function it seems all other `MENU_CALLBACKs` are located in `filter.pages.inc` (according to https://api.backdropcms.org/api/backdrop/core%21modules%21filter%21filter.module/function/filter_menu/1).

**Comment by klonos** [comment] 2019-08-20 18:19
Thanks @BWPanda 👍 ...I might ask on Gitter re best practice here.

On the one hand, for better novice DX, I would expect similar/matching function names for enabling/disabling a thing + for these functions to be in the same file.

On the other hand, if it is a common practice/convention to be adding callback functions to `*.pages.inc` files, I'd want to be adhering to that.

🤔

**Comment by klonos** [comment] 2019-08-20 18:38
...actually @olafgrabienski no need to confirm anything (unless you have time to do that anyway). The PR has failing field/text module tests, which lead to the `text.test` file, at a point where that test tries to disable all text formats, besides the plain text fallback format. The rest of the test fails, with mentions of unexpected HTML tags, and the format selector being shown where it shouldn't. Looking to fix that next.

**Comment by klonos** [comment] 2019-08-20 19:22
...noting this here, in case I don't manage to get to the bottom of it: On my local, I have replaced the specific cache clearing in `filter_format_enable()` and in `filter_format_disable()`, with `cache_clear_all()`. Now, each time that a text format is enabled or disabled, all text formats are being made available in the "Editor" selector; it takes a second, manual cache clear (via the admin menu) to get only the enabled formats to be shown in the drop-down selector. Looks like it might be a problem with the logic that populates the `#options` for that select 🤔

**Comment by klonos** [comment] 2019-08-20 19:56
...OK, simple fix after all: https://github.com/backdrop/backdrop/pull/2823/commits/f80466777b4dfbb0da8237868082165556c799b0

**Comment by klonos** [comment] 2019-08-20 21:48
OK, PR updated and ready for another round of review:

- Fixed the issues reported by @olafgrabienski re disabled formats still being available in the "Editor" selector, when creating content.
- Moved disabled text formats to a separate table, after the enabled formats table. Doing this prevents enabled formats from being able to be dragged to the "disabled" section.
- Fixed failing test.
- Added tests for enabling/disabling text formats.

Tasks remaining:

- Naming of the new function that enables formats, and which file it should be added to (pending feedback from core committers).
- Introduce a feature that completely removes formats from the admin UI (as opposed to disabling them)
- Introduce a function to clone a format (can be follow-up)

Any other feedback welcomed.

**Comment by klonos** [comment] 2019-08-21 13:22
...PR updated again, to allow text formats to be removed.

I have made it so that:

- status `1` is for enabled text formats (unchanged)
- status `-1` is for disabled ones (was previously `0`)
- status `0` is for removed

Since existing sites will have their disabled formats with status `0`, these will be now considered removed; so people will not have "random", previously-disabled formats suddenly reappear. Please let me know if we should have things be otherwise.

Also, I have noticed this for `filter_format_exists()`:

```php
/**
 * Determines if a text format exists.
 *
 * @param $format_id
 *   The ID of the text format to check.
 *
 * @return
 *   TRUE if the text format exists, FALSE otherwise. Note that for disabled
 *   formats filter_format_exists() will return TRUE while filter_format_load()
 *   will return FALSE.
 *
 * @see filter_format_load()
 */
```

So we need to decide what this function will now return for disabled formats, and what for removed ones.

Everything works on my local, but the PR sandbox is borked for some reason 😞

**Comment by klonos** [comment] 2019-08-21 17:17
So `filter_formats()` the way it was refactored by @BWPanda in the original PR accounted for disabled text formats, via a `$include_disabled` parameter passed to it. Things got tricky really quickly with the addition of removed formats, so I am thinking to revert all the changes in `filter_formats()`, and introduce a new `filter_get_formats()` function. This new function will be the home of all the newly-introduced "magic", including parameters to return filters by status (all/enabled/disabled/removed), and to reset caches. We can then make `filter_formats()` a wrapper function around the new `filter_get_formats()`, and mark it for deprecation in 2.0.

The bonus that I like with the above is that we'll end up with functions that have matching/consistent names 🙂:

- filter_get_filters()
- filter_get_editors()
- filter_get_formats()

**Comment by olafgrabienski** [comment] 2019-08-22 07:32
@klonos Thanks for your continuing work on disabling text formats! 👍  Didn't test the updated PR locally so far due to lack of time, and after your recent changes I'm not sure about the status: does it make sense to test the PR at the moment, or are you anyway planning to make more changes?

**Comment by klonos** [comment] 2019-08-22 19:06
Hey @olafgrabienski I could use some sanity check, so if you could pull my PR on your local and see if things are broken, it would help. I don't know why things work on my local, but then the entire PR sandbox is borked 😞

**Comment by olafgrabienski** [comment] 2019-08-23 15:24
Oh, In the meantime, in the PR's sandbox I get even a `HTTP Error 500` on `admin/config/content/formats`.

OK @klonos, so let's see how it works on my test site. (I've replaced the `core` directory of my test site with the one from your `issue-1575` branch.)

- Went to the *Text editors and formats* page on my test site. The UI looked as expected.
- Created a custom text format, and changed the order to put it further down in the list.
- Created a page with the custom format. Sort order of formats was as expected.
- Went back to the *Text editors and formats* page and disabled the custom format. The format showed up under *Disabled text formats*, as expected.
- Viewed the content page. Nothing special.
- Edited the content page. Format was still the custom one. :-/
  - Changed format to "Filtered HTML", and saved the page.
  - Cleared caches, edited page again. The custom format wasn't selected (as expected) but was still available.
- On the *Text editors and formats* page, I had a look at the disabled format.
  - In the *Configure* dropdown, there was still the "Disable" option available.
  - Disabled the format again via the dropdown, and cleared caches. No difference.
- Edited the content page again. Same result as before: Custom format was still available. (Expected result: Format isn't available anymore.)

So, locally the PR works partially but without the expected result regarding the disabling action.

**Comment by klonos** [comment] 2019-08-24 00:11
Thanks for testing this @olafgrabienski 👍 ...yeah, `admin/config/content/formats` works on my local as well; not sure why it would possible throw a 500 in the PR sandbox.

> Edited the content page. Format was still the custom one. :-/

Hmm 🤔 ...here's what we tell people in the warning we show in the confirmation dialog when disabling a text format:

...warning:
> Any existing content using this text format will stop being displayed.

I guess admin users are still able to edit that content though. Is that expected or not? Also, what should happen with non-admin users.

...plain text:
> The text format will no longer be available when creating new content; but it will be retained, so you can reenable it in the future.

Does the first bit of that text imply that the the text format **will** be available (in the "Editor" selector) when editing _existing_ content? Is that expected, or not?

Anyway, during the last dev meeting, I have asked for some technical/general direction from @quicksketch, and he suggested that we do not need to keep the format config around when (completely) removing a format. This means that I will have to work on the PR some more to revert certain things.

One question though: how this works currently, is that we disallow people to create new text formats with the same machine name as previously created formats (enabled or disabled). This I believe is meant to avoid causing data loss, when for example you create content with a certain format, then completely remove the format, then create a new format with the same machine name, then finally edit the piece of content that was using the previous format (assuming that the old and new formats with the same name have different filters enabled).

Thought on that last bit?

**Comment by olafgrabienski** [comment] 2019-08-26 09:41
>> Edited the content page. Format was still the custom one. :-/

> I guess admin users are still able to edit that content though. Is that expected or not? Also, what should happen with non-admin users

@klonos I've had another look at my testing site:

- User 1 is not only able to edit existing content using a disabled text format but also to create new content.
- The same -- edit existing content and creating new content with disabled text format -- is true for an authenticated user with typical editor permissions.

**Comment by klonos** [comment] 2019-09-03 02:28
...new PR here: https://github.com/backdrop/backdrop/pull/2826

**Comment by klonos** [comment] 2019-09-03 04:35
FTR, after extensive discussion on Gitter, between @jenlampton, @quicksketch, @docwilmot, and myself, we have decided to remove the "Remove" functionality, and work on introducing that as a follow-up.

Config files of "disabled" text formats was never actually deleted anyway, and the main UX problem here (telling people that we are disabling a text format, without giving them an option to re-enable it) is being addressed.

PR updated accordingly.

**Comment by quicksketch** [comment] 2019-09-03 07:38
After getting this so close but not quite finishing it, we're going to give this one another 24 hours to get wrapped up for the 1.14.0 code freeze.

**Comment by BWPanda** [comment] 2019-09-03 10:14
The aforementioned 'remove' functionality follow-up: #4013

**Comment by klonos** [comment] 2019-09-03 16:26
<img width="1187" alt="Screen Shot 2019-09-03 at 7 00 14 pm" src="https://user-images.githubusercontent.com/2423362/64189629-52fc2180-ce7d-11e9-8049-07e41806d4bf.png">

**Comment by jenlampton** [comment] 2019-09-04 02:00
The message: `Any content stored with this format will not be displayed.` I just tested it and all content with the disabled format is still displayed. Is this a bug, or is the message incorrect?

Other minor design things:
* Name column should match approved name / machine name format (can be follow up).
* Column widths are weird between the two tables, keeping everything in the same table would solve this (see views or file types for an example - can be follow up).

**Comment by quicksketch** [comment] 2019-09-04 02:35
New PR filed at https://github.com/backdrop/backdrop/pull/2845 that addresses the concerns @docwilmot pointed out, where the results from `filter_formats()` could end up cached and serve the wrong contents when called multiple times per page.

**Comment by jenlampton** [comment] 2019-09-04 02:39
Alternate PR that doesn't change anything other than enabling disabled formats at https://github.com/backdrop/backdrop/pull/2846 (copy/pasted from @klonos's PR) will look at @quicksketch's to see if I need any of that too.

**Comment by jenlampton** [comment] 2019-09-04 03:06
Okay, I merged in the tests from @klonos's PR, and the fixes from @quicksketch's PR. Testing now!

**Comment by klonos** [comment] 2019-09-04 04:50
...there were a few things to polish, and bug to address, so we decided to push this to 1.15. Great teamwork everyone 👍 ...thanks for helping bring it so close!

**Comment by olafgrabienski** [comment] 2019-09-04 07:50
> ... so we decided to push this to 1.15

As this issue is a bug report, I'd suggest to not wait until 1.15. Let's put the fix, when things are polished, in one of the next bugfix releases.

**Comment by klonos** [comment] 2019-09-04 20:41
It is a bug report, but there were some API changes required (mainly in the `filter_formats()` function, in order to allow retrieving disabled text formats). Perhaps we can replace that function with a new `filter_load_formats()` or `filter_get_formats()` one, which introduces the new functionality, and retain the old `filter_formats()` function as is 🤷‍♂ 

Anyway, it was those API changes that lead us to have this slatted for 1.14 instead of a bug release too.

**Comment by docwilmot** [comment] 2019-09-10 04:14
As far as I can see, we only need to check *all* formats when doing operations on `filter_admin_overview()`, so we can either just directly get all formats from config there, or create a `filter_get_all_formats()` just for that form and its submit. Everything else can keep using `filter_formats()` as usual.

**Comment by docwilmot** [comment] 2019-09-14 02:48
is this still a bug fix, to go in 1.14?

**Comment by klonos** [comment] 2019-09-16 02:59
@docwilmot the removing instead of disabling is the UX bug. We can fix that in a 1.14.x bug release by changing the UI text. The bit where we introduce a way to (re)enable disabled formats sounds like a feature request, so that one may need to wait till 1.15.

**Comment by jenlampton** [comment] 2019-10-24 20:28
@klonos should we split the bug-fix text-change into a separate issue, ad keep this one, along with all it's discussion, for 1.15?

**Comment by klonos** [comment] 2019-12-23 01:19
OK, I have reworked this in this new PR: https://github.com/backdrop/backdrop/pull/3024

I have done the following:

- Moved all the code/logic from `filter_formats()` into a new `filter_get_all_text_formats()` function. No new parameters added - just the pre-existing optional `$account` parameter (which helps get formats allowed for a specific user account).
- Added a new `filter_get_enabled_text_formats()` function (along with a `filter_text_format_is_enabled()` function).
- Added a new `filter_get_disabled_text_formats()` function (along with a `filter_text_format_is_disabled()` function).
- Made `filter_formats()` a wrapper function for the newly-introduced `filter_get_enabled_text_formats()` function, so that we **retain the functionality of `filter_formats()` returning only enabled formats**.
- Kept wording and certain other improvements from @jenlampton's PR (like using weight to reorder the links in the dropbuttons, and using single quotes + concatenation where links included variables in them, etc.).
- Used a single table to hold both enabled and disabled text formats. This resulted in cleaner/less code, and more consistent styling/alignment of the table cells in general.
- I have tweaked `tabledrag.js`, so to be adding a `tabledrag-handles-on` class to help with styling rows that are disabled (and while at it, I've fixed an issue where clicking the show/hide weights toggle would leave behind empty `style=""` entries in the DOM).

I want feedback in general, but on the following things specifically:

1. Should the new function names be `filter_get_*_text_formats()` or `filter_get_*_formats()` (so basically, should they include the word "text" or just plain "formats")?

2. Should we now deprecate `filter_formats()` in favor of `filter_get_enabled_text_formats()`?

3. Should we allow disabled formats to be dragged too? We'd have to replicate the UI used in the "Manage displays" pages, where field rows can be dragged below the "Hidden" section to be hidden, and above it to be shown - but that's kinda complicated (uses a `'#type' => 'field_ui_table'` custom field type), and I may need some help with the JS to accomplish that.

4. The docblock of the `filter_format_exists()` function mentions the following:

```php
 * @return
 *   TRUE if the text format exists, FALSE otherwise. Note that for disabled
 *   formats filter_format_exists() will return TRUE while filter_format_load()
 *   will return FALSE.
```

Wondering if I should refactor to retain this, or if both `filter_format_exists()` and `filter_format_load()` should return `TRUE` now (since we allow disabled formats to be reenabled). Asking, because with the changes in my PR, people can use either `filter_get_disabled_text_formats()` or `filter_text_format_is_disabled` if they want to figure out if a text format is disabled.

**Comment by docwilmot** [comment] 2019-12-25 18:04
I really dont think all of this is necessary TBH. As I mentioned at https://github.com/backdrop/backdrop-issues/issues/1575#issuecomment-529761426 we only ever need to load all formats in one place; if we just did that it would be a much simpler PR. 

In either case we should add another parameter to `filter_format_load(format_id, $all = FALSE)` with a `load arguments` in `filter_menu()` so we maintain the previous functionality.

**Comment by jenlampton** [comment] 2019-12-26 18:51
I agree, this PR has a lot of change. Let's stick with the previously
agreed upon approach @docwilmot mentioned.

**Comment by jenlampton** [comment] 2020-01-01 23:18
We discussed this issue in last week's meeting and agreed that the changes needed are 

* the additional parameter in `filter_format_load(format_id , $enabled = TRUE)` as @docwilmot mentioned (though we recommended `$enabled = TRUE` as opposed to `$all = FALSE`) 
* as well as the additional parameter added to `filter_formats($account = NULL, $enabled = TRUE)` as is done already in the most recent PR.

**Comment by alanmels** [comment] 2020-01-19 18:31
The issue was first created back in 2016 and it has not been addressed in 2020. I really do hope Backdrop won't follow Drupal in some of its worst practices of hanging important issues without resolution for many years.

**Comment by docwilmot** [comment] 2020-01-20 00:48
The difficulty we have, and my greatest frustration with working on Backdrop, is that we have no way of deciding if this is an "important issue" nor any way to mark it as such if were did decide it was important. Tons of comparatively trivial stuff would have been committed since this issue was just posted, because of that.

I've tried to raise this concern about our lack of direction multiple times, the latest here: https://github.com/backdrop-ops/backdropcms.org/issues/630

Part of my problem of course is that I dont attend the Thursday meetings, so I dont know if these concerns are addressed, but we havent so far had any good ideas come forward on how to prioritize things.

**Comment by docwilmot** [comment] 2020-02-12 21:18
I've added the load arguments in a new PR based of @jenlampton's. This returns previous functionality to `filter_format_load()`, allowing by default only enabled filters to load. This was important especially where the load function is called in `check_markup()` to prevent content with disabled formats from being accessed.

**Comment by jenlampton** [comment] 2020-04-02 21:23
I've tested the PR and it works great! Thanks @docwilmot for getting that change in.

**Comment by docwilmot** [comment] 2020-04-02 21:32
RTBC?

**Comment by jenlampton** [comment] 2020-04-02 21:52
still looking over code, but....

**Closed** 2020-04-15 20:50 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2020-04-15 20:52
Merged https://github.com/backdrop/backdrop/pull/3071 into 1.x for 1.16.0. Thanks for carrying this one home @docwilmot and @jenlampton! Thanks @klonos for advocating for this issue and being there for all those meetings. Thanks @BWPanda for the several iterations you put together.  Thanks @olafgrabienski for your persistent testing and suggestions!
