### ISSUE TITLE
[UX] Provide responsive drop-down menus out of the box.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2107] opened 2016-08-30 09:00 UTC
The Primary navigation menu should be responsive (by default) and drop-down (by default) and when any menu block is placed anywhere it should also have options to do the same.  

This is an alternative approach to to https://github.com/backdrop/backdrop-issues/issues/1457 (Add a menu styles API), which would also accomplish this goal but with a more ambitious feature set.

I'm worried we may not be able to add a whole new menu styles API in core in time for 1.5.  Here's an alternate approach.

- [x] Add a checkbox to the menu settings on each block to make the menu a drop-down (https://github.com/backdrop/backdrop-issues/issues/1457#issuecomment-168081376)

- [x] Add necessary JS to turn the menu into a hamburger (and the word "Menu") when it runs out of room. Maybe http://www.smartmenus.org (https://github.com/vadikom/smartmenus)?

- [x] Add necessary CSS to make sure it's pretty for mobile.

===

Latest PR: https://github.com/backdrop/backdrop/pull/1542

**Comment by quicksketch** [comment] 2016-08-30 09:37
> can we get away with using the same code we used for admin_menu?

This would have two challenges: 1) The JS code for admin_bar is not generic currently (afaik), so some work would go into separating it into a library and 2) I don't think the markup for admin_bar is not the same as menus (though it's probably pretty close).

Admin Bar also isn't at all written as a library, so there aren't any options for things like animations, hover delay, etc. Everything in it is just hard-coded and that's the way it is. This might actually be appropriate for a simple default, but it will definitely limit its customization ability.

**Comment by jenlampton** [comment] 2016-08-30 09:39
> Admin Bar also isn't at all written as a library, so there aren't any options for things like animations, hover delay, etc. Everything in it is just hard-coded and that's the way it is. This might actually be appropriate for a simple default, but it will definitely limit its customization ability.

That sounds good to me, I wouldn't want those settings cluttering up core anyway. If people want settings they'll probably also want to choose a different menu style entirely, so more like what we're discussing over in https://github.com/backdrop/backdrop-issues/issues/1457.

**Comment by jenlampton** [comment] 2016-08-30 09:43
I've pushed a PR that simply adds the setting for drop-down menus. From here we need to add CSS and JS as notes above. Perhaps @wesruv you could take it from here since you had some ideas about which libraries we should be using over in https://github.com/backdrop/backdrop-issues/issues/1457. This one saves it's settings :)

**Comment by klonos** [comment] 2016-08-30 10:53
@jahaimon duplicate issue mentioned in the issue summary:

>  This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/1457,  and https://github.com/backdrop/backdrop-issues/issues/1457.

**Comment by wesruv** [comment] 2016-09-01 23:32
I'll take a look soon

**Comment by quicksketch** [comment] 2016-09-06 06:45
I took a look at Admin Bar and checked what CSS/JS is necessary to create the dropdowns there. The overall code is not all that substantial: https://gist.github.com/quicksketch/1d62a37923dab6116b74b1d1afaa16c6

Some CSS could be reduced and is admin-bar specific, but we'd need to come up with a new "generic style" (e.g. gray backgrounds and borders) that could be overridden by themes. Something probably similar to what Nice Menus provided in D7. (Speaking of Nice Menus, it uses Suckerfish for dropdowns, which are also fairly simple, but is not touch friendly or responsive AFAIK.)

**Comment by jenlampton** [comment] 2016-09-06 07:06
> Speaking of Nice Menus 

I thought we decided on smartmenus? https://github.com/vadikom/smartmenus We should take a look at the default CSS used there.

**Comment by klonos** [comment] 2016-09-06 13:03
> I thought we decided on smartmenus?

Well, we have not *officially* decided, but it's feature-rich:

> Mobile first, responsive and accessible list-based website menus **that work on all devices**.

...plus:

- free
- jQuery-based
- includes themes
- highly customizable:
  - full width with a choice to justify it across the screen
  - render horizontally with options for aligning left/right/center
  - render vertically with RTL/LTR options

It sounds ideal.

**Comment by klonos** [comment] 2016-09-06 13:04
...also supports mega-menus:

> This is a mega drop down test. Just set the "mega-menu" class to the parent UL element to inform the SmartMenus script. It can contain **any HTML**

**Comment by klonos** [comment] 2016-09-06 13:22
I don't know if we could (or should) make that a generic core library and use it for admin bar too (will make themable too). Perhaps the admin bar JS is too specific for its use case, but one thing that we can take advantage is the solution smartmenus has for issues like #520

**Comment by olafgrabienski** [comment] 2016-09-06 14:27
> Add necessary JS to turn the menu into a hamburger (and the word "Menu") when it runs out of room. Maybe http://www.smartmenus.org (https://github.com/vadikom/smartmenus)?

I just had a look at the SmartMenus demo page and saw that it doesn't show a collapsed menu and a hamburger icon on a smartphone screen by default. (On the product page the menu is collapsed and shows the hamburger. Compare the screenshots:

**Product page**
![screen-smartmenu-product-page-with-hamburger](https://cloud.githubusercontent.com/assets/14188307/18277415/b7fb70ae-744e-11e6-92e3-fbb21a0cb224.png)

**Demo page**
![screen-smartmenu-demo-page-without-hamburger](https://cloud.githubusercontent.com/assets/14188307/18277433/c640a7e2-744e-11e6-8a19-8f97e46aea76.png)

Has someone already tested if SmartMenus actually provides the automatic hamburger icon related functionality?

**Comment by docwilmot** [comment] 2016-09-06 14:35
Its a bit late to be undecided about this actually. Will this make it in? Would be great to see some code attached to an install soon.

> Has someone already tested if SmartMenus actually provides the automatic hamburger icon related functionality?

It doesn't actually. See http://www.smartmenus.org/docs/#menu-toggle-button. But it seems easy enough to set up. This is the reason why I chose Slimmenu instead for building the demo; it does eevrything we needed out of the box. Although I do understand the limitations.

**Comment by quicksketch** [comment] 2016-09-07 03:36
I'm going to take a pass at reviewing https://github.com/backdrop/backdrop-issues/issues/1457, where the PR has a library integrated a bit further. As I said in that issue, I'm not particular about the library we use (if any) as long as it can fit some basic requirements (responsive, accessible, touch-friendly). We can write this in a way where the library isn't accessible as a stand-alone library, leaving the door open to replacing it at a later time (as long as we have consistent markup and classes).

**Comment by jenlampton** [comment] 2016-09-07 03:38
@quicksketch the library used in  #1457 doesn't pass those requirements, so it's not a candidate for core inclusion. I would be interested in your feedback on that approach. But, after 1.5, perhaps?

**Comment by quicksketch** [comment] 2016-09-07 03:51
Hm, yeah mobile friendly-ish but not at all keyboard accessible: https://github.com/adnantopal/slimmenu/issues/40 :stuck_out_tongue:  Gar. Well... maybe back to SmartMenus? Definitely keyboard accessible. We'll need to write our own hamburger portion with this one... but yeah. Still in the same position, the really hard part here is the front-end integration and styling.

**Comment by jenlampton** [comment] 2016-09-07 03:52
> We'll need to write our own hamburger portion with this one... but yeah

No, it has a setting for that!  But yea, styling will be trixy whichever way we go.

**Comment by jenlampton** [comment] 2016-09-09 06:40
I just pushed a new PR that attaches the smart menus library to the main menu when the box is checked.  it's not initialized yet, we still need to add `$('ul.sm').smartmenus();`

**Comment by quicksketch** [comment] 2016-09-10 05:58
Okay, well I know I said in the last meeting I don't think this will make it... maybe it will?

I updated @jenlampton's PR to tie this into the front-end. Overall I think it works pretty well. Here's the rundown:

- All dropdown default theming lives in the new `menu-dropdown.theme.css` file, with the intention that theme's like Basis would override this file.
- Bartik does *not* override the file but inherits from it. Same with Stark of course.
- Bartik did not have *any* mobile styling previously, so I put in a little leg work to make the nav mobile friendly-ish whether you have the drop-downs turned on or not.
- Added styling for the mobile and desktop versions of the dropdowns in Bartik.
- There is NO hamburger menu that is automatic. Even on SmartMenus website, they implemented that separately. My thought is to have Basis implement a hamburger but exclude that from Bartik. Basis would likely do this through a combination of JS, theme_menu_tree(), and additional CSS.

Here are some GIFs, everybody loves GIFs. :wink:

Desktop Bartik:
![desktop-bartik](https://cloud.githubusercontent.com/assets/100206/18408289/7a08845a-76e0-11e6-8031-d3ad9eba73cc.gif)

Desktop Bartik No tabs:
![desktop-bartik-no-tabs](https://cloud.githubusercontent.com/assets/100206/18408291/82a6539e-76e0-11e6-978e-4b2c8f1c7d4b.gif)

Desktop Bartik No Dropdowns:
![screenshot from 2016-09-09 22-43-52](https://cloud.githubusercontent.com/assets/100206/18408302/b001eed4-76e0-11e6-8316-636cf1f79446.png)


Mobile Bartik:
![mobile-bartik](https://cloud.githubusercontent.com/assets/100206/18408294/8c22477a-76e0-11e6-8a6f-dba40eb62fe1.gif)

Mobile Bartik No Dropdowns:
![screenshot from 2016-09-09 22-43-29](https://cloud.githubusercontent.com/assets/100206/18408304/b94ad14a-76e0-11e6-86f5-7b23e2243ce8.png)

Stark Desktop:
![desktop-stark](https://cloud.githubusercontent.com/assets/100206/18408310/c8cab252-76e0-11e6-98cf-4c1ff6ca6ad9.gif)

Stark Mobile:
![mobile-stark](https://cloud.githubusercontent.com/assets/100206/18408315/d0d76a26-76e0-11e6-937e-8e7ad43ee125.gif)

PR for testing: https://github.com/backdrop/backdrop/issues/1530.

**Comment by klonos** [comment] 2016-09-10 16:47
...just tried giving the PR sandbox a spin, but drop-down menus don't seem to be working. Maybe something I'm missing?

**Comment by jenlampton** [comment] 2016-09-10 16:57
Did you turn them on?

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by quicksketch** [comment] 2016-09-10 21:12
> ...just tried giving the PR sandbox a spin, but drop-down menus don't seem to be working. Maybe something I'm missing?

Yes almost certainly! There is the stupid stupid stupid requirement that after you make menu items you have to go and edit the menu links, and mark each one as "expanded". Very annoying! Of course then you also have to edit the block and check the box to turn on the drop down option.

I'm going to see if it's possible to either ignore the "expanded" options entirely with certain menu styles or worse-come-to-worse, make an option for "Expand only active menu tree" (which is the default Backdrop behavior) that if you don't check it, the entire tree will be expanded, which is what you'd want for dropdowns.

**Comment by quicksketch** [comment] 2016-09-10 22:33
Marking this needs work. IMO the need to expand menu links manually is so UX-breaking we can't put this in until it's fixed.

**Comment by klonos** [comment] 2016-09-11 01:26
> Did you turn them on?

> ...Of course then you also have to edit the block and check the box to turn on the drop down option.

DOH! ...what confused me there was that I expected this to work "out of the box" as advertised. I initially looked for a setting under menu configuration, but saw nothing there. I then thought that through and (because I am a long-time Drupal/Backdrop user and know my way around the system and how it works) had an AHAH! moment: of course, this needs to be a per menu **instance** setting ...so it will be in the menu block settings for that specific layout. Went to the default layout, hit the configure button for the primary navigation menu... nothing. That's where I gave up and came back here with "Doesn't work". I then realized (after a good night 💤 ) that there is another final setting that needs to be set "_Maximum depth_" for the menu needs to be some value other than **the default of 1** (UX WTF issue there).

> Marking this needs work. IMO the need to expand menu links manually is so UX-breaking we can't put this in until it's fixed.

Fully agree @quicksketch

**Comment by klonos** [comment] 2016-09-11 02:16
Here's a thought: how about for the default layout, for the primary nav block, we **set the max depth to unlimited by default out of the box**? If people only create menu items that are one level deep, they will notice no change 😉 

...in fact I think that we should make "unlimited" the default depth in general for all menu blocks and revert the logic to be more or less the same as we did for the limited/unlimited values of fields (in #1459). So, instead of this:

![backdrop-issue2107-default_menu_depth_1](https://cloud.githubusercontent.com/assets/2423362/18414735/28ac1ccc-7819-11e6-8665-d42ff1fa09f8.gif)

...we have this:

![backdrop-issue2107-default_menu_unlimited](https://cloud.githubusercontent.com/assets/2423362/18414736/2fd8abf0-7819-11e6-96f6-116862ca207a.gif)

**Comment by klonos** [comment] 2016-09-11 21:16
...some styling thoughts:

1. The `.menu-dropdown a span.sub-arrow` when rendering the top-level links without any tabs should be set to `#fefeff` (same as menu links) instead of `#555555`, otherwise it's hard to distinct (especially in color schemes with darker header colors).

  This can easily be sorted by adding the following code in `/core/themes/bartik/css/styles.css`

  ```css
  .l-header .no-tabs .menu-dropdown > li > a > span.sub-arrow {
    border-color: #fefeff transparent transparent transparent;
  }
  ```

 This specifically targets the first drop-down arrow (top-level menu items) *only* when the "No tabs" style is selected and leaves the default for the rest of the child menu items with the default `#555555` color. Before/after:
  
  ![backdrop-issue2107-drop-menu_arrow_color](https://cloud.githubusercontent.com/assets/2423362/18420110/73512520-78ae-11e6-987c-60cca16b8924.png)

2. Perhaps in this case (no tabs) we should render the drop-menu items in the same color as the header background? It feels kinda off having white menus expanding from colored parent items. This will require some work (defining new color labels for the drop-down menu items, adjusting the preview to actually display the drop-down menus etc.), but eventually we will need to support customizing the newly-introduced drop-down menus anyways. This can be a follow-up as we are short on time for the release of 1.5.0.

**Comment by quicksketch** [comment] 2016-09-12 01:08
Great feedback @klonos. Yeah truth be told I was just getting tired of futzing with Bartik's colors. We could definitely improve this further. I'm going to work more on simplifying the enabling of dropdowns. And you're right this should be enabled out-of-box rather than needing to be turned on.

**Comment by quicksketch** [comment] 2016-09-12 05:31
I closed the previous PR and made a new one at https://github.com/backdrop/backdrop/pull/1542.

Changes:

- The Bartik dropdowns now match the background color if using the "no-tabs" version (the default) of the header.
- I switched the configuration of the dropdown option from a checkbox to a select list. It now looks like this:
  ![peek 2016-09-11 22-18](https://cloud.githubusercontent.com/assets/100206/18425374/cce6e73c-786d-11e6-93fb-2a011a04f5a4.gif)
  Note the options for depth and hierarchy showing only where applicable. Right now these are just #states. When/if we add full Menu Styles (#1457), these settings would be shown/hidden via AJAX just like we do for the block styles.
- The addition of "top_only" option means that we can now specifically target a difference between a hierarchical tree and just a list of links. This means that `system.theme.css` no longer is going to add triangles and dots for "expanded" and "leaf" elements *unless* you specify the block to show as a hierarchical list. The bane of themers everywhere fixed as a side-effect! Yay! This change leaves the same level-specificity as before, so themes' current behavior theming menus is unaffected (though existing themes will probably want to rework their menu CSS anyway to support the dropdowns).
- If the menu style is set to anything other than "Hierarchical tree" all menu items are expanded up to the specified depth, regardless of the "Expanded" setting on each individual menu item. We probably need to update the description text on that option anywhere it is mentioned in the UI to clarify it's purpose.
- The dropdown style is set out-of-box on the default layout. Combined with above that means that nested links will "just work" and turn into a drop down out-of-the-box.
- However, the default for *new* menu blocks still defaults to "Hierarchical tree", matching the legacy behavior when menu blocks were added. This is because new layouts will clone the default, which uses a dropdown in the most likely place, but other placed blocks are likely to be trees or top-only links.

There is still no "real" menu style API in here, but this sets up our UI and a lot of the underlying code to support it later.

**Comment by klonos** [comment] 2016-09-12 06:11
HOW COOL IS BACKDROP?!? Huh? 👍 ❤️

**Comment by klonos** [comment] 2016-09-12 06:16
I mean...

> - The addition of "top_only" option means that we can now specifically target a difference between a hierarchical tree and just a list of links. This means that system.theme.css no longer is going to add triangles and dots for "expanded" and "leaf" elements *unless* you specify the block to show as a hierarchical list. The bane of themers everywhere fixed as a side-effect! Yay! This change leaves the same level-specificity as before, so themes' current behavior theming menus is unaffected...
> - If the menu style is set to anything other than "Hierarchical tree" all menu items are expanded up to the specified depth, regardless of the "Expanded" setting on each individual menu item. ...

...and of course:

> - The dropdown style is set out-of-box on the default layout. Combined with above that means that nested links will "just work" and turn into a drop down out-of-the-box.

That was the whole point of this issue! 👍 

...and of course (although likely of small interest to the end user):

> There is still no "real" menu style API in here, but this sets up our UI and a lot of the underlying code to support it later.

Yay for laying the path for even greater things!

**Comment by klonos** [comment] 2016-09-12 06:19
I still would like it better though if we changed the max depth drop-drown to have the two unlimited/limited values sames + the number field to set the specific depth (as we did for the field values).

**Comment by klonos** [comment] 2016-09-12 06:51
@quicksketch also, the menus now look so much better with the same background color as the header instead of white when the "No tabs" style is selected! 👍 ...they would be even better if they had some opacity on `:hover` (behaving more or less like the admin bar). This can of course wait for a follow-up if too hard to implement now.

**Comment by klonos** [comment] 2016-09-12 07:12
...and a minor bug (but could be smartmenus, so need to be reported/fixed upstream): I tried the keyboard navigation with multiple levels of menus and it works just fine with the exception of going back to the top-level menus. Can someone else also test that please (I tested on Windows x64 with latest Firefox and Chrome)?

Steps to reproduce:

0. Create or generate some menu items for the primary nav menu with enough complexity and menu depths.
1. Start tapping the tab keyboard key until the primary menu has focus.
2. Navigate with the left/right keys of the keyboard through the top-level menu items (do not go deeper yet). This should work fine.
3. Select one of the of the top-level menu items that has a drop-down and press the down key.
4. Start navigating using the up/down/left/right keys. This should work fine too.
5. Try to move back to the top-level menu items. When you reach the first child before the top-level menu item, the up key does nothing. <- BUG

There are some other minor annoyances. I will document these here, but only for reference. These need to be checked in case they are smartmenus bugs (or features?):

- Reaching the last child of a series of submenus and hitting the right key should do nothing (that's what I personally expect?), but it jumps to the next top-level menu item instead.
- When a series of submenus reaches the end of the screen, smartmenus is smart enough to start unfolding the menus to the left ( 👍  this prevents the menus going outside the viewport), but navigating to them works by the right arrow key (I'd expect this to switch to left instead).
- I would expect that hovering over the menu with the mouse makes the item active and I can then continue navigation via the keyboard. This does not happen though.
- Need to test RTL.

**Comment by quicksketch** [comment] 2016-09-12 07:31
> they would be even better if they had some opacity on :hover (behaving more or less like the admin bar). This can of course wait for a follow-up if too hard to implement now.

Yeah, the styling of the dropdowns (both in Bartik and Basis) are a real time drain. I could probably futz with them for hours, so I stopped with what we now have. Definitely follow-up worthy.

> Try to move back to the top-level menu items. When you reach the first child before the top-level menu item, the up key does nothing :bug:

Confirmed. We should log this bug with SmartMenus. Actually, all your additional feedback would be great in the SmartMenus queue. They have a really quiet issue tracker: https://github.com/vadikom/smartmenus/issues

> Need to test long menus that go bellow the viewport.

I think SmartMenus has some handling for this, but I don't know for sure. If nothing else it probably just requires you to scroll down to reach the bottom of the menu, this is what happens now with admin menu. It was a common problem back in D6 days I know because there was no hierarchy under Admin -> Settings, so you'd have 20-80 items in there that could easily cause a page scroll.

So it sounds like so far our issues are all upstream problems... we'll need to work with SmartMenus to get them fixed, but I don't think they are blockers. What IS a blocker though is we've expanded the API-level abilities of menus with the always-expanded menu items. We'll need new tests covering this expanded functionality.

Thanks for reviewing @klonos!

**Comment by klonos** [comment] 2016-09-12 08:03
I think I'm gonna start filing follow-ups...

**Comment by klonos** [comment] 2016-09-12 08:07
> > they would be even better if they had some opacity on :hover (behaving more or less like the admin bar). This can of course wait for a follow-up if too hard to implement now.

> Yeah, the styling of the dropdowns (both in Bartik and Basis) are a real time drain. I could probably futz with them for hours, so I stopped with what we now have. Definitely follow-up worthy.

Done 😉

**Comment by klonos** [comment] 2016-09-12 08:22
>> Need to test long menus that go bellow the viewport.

> I think SmartMenus has some handling for this, but I don't know for sure. If nothing else it probably just requires you to scroll down to reach the bottom of the menu, this is what happens now with admin menu. It was a common problem back in D6 days I know because there was no hierarchy under Admin -> Settings, so you'd have 20-80 items in there that could easily cause a page scroll.

It handles it pretty well actually. You can use the "Longus menus" item that I've created in the PR sandbox to test 😉 ...I've filed a follow-up for that too. Check it out for a screencast of how it behaves.

**Comment by klonos** [comment] 2016-09-12 08:25
YAY for another Drupal annoyance that we solved (minus the small side-effect) by adopting a PFE library 😉

**Comment by klonos** [comment] 2016-09-12 08:27
> ...Actually, all your additional feedback would be great in the SmartMenus queue. They have a really quiet issue tracker: https://github.com/vadikom/smartmenus/issues

Let me tell you it's about to get loud 😄 ...you know me and the issue queues. ...with screenshots and the lot 😆

**Comment by klonos** [comment] 2016-09-12 08:29
> So it sounds like so far our issues are all upstream problems... we'll need to work with SmartMenus to get them fixed, but I don't think they are blockers

Nope, not blockers. This PR is RTBC from me from an end-user and site-builder UX point of view. All we need is perhaps a code review and lets get it in. Did I mention today how much I ❤️ Backdrop!?

**Comment by klonos** [comment] 2016-09-12 09:07
Sounds like a plan to me. I think that @wesruv has already requested to merge Basis as a feature branch.

**Comment by jenlampton** [comment] 2016-09-12 09:10
> I think that @wesruv has already requested to merge Basis as a feature branch.

Yep, [here](https://github.com/backdrop/backdrop-issues/issues/1361#issuecomment-246252724)

**Comment by klonos** [comment] 2016-09-12 09:17
>> Try to move back to the top-level menu items. When you reach the first child before the top-level menu item, the up key does nothing :bug:

>Confirmed. We should log this bug with SmartMenus. Actually, all your additional feedback would be great in the SmartMenus queue. They have a really quiet issue tracker: https://github.com/vadikom/smartmenus/issues

It's not a bug - it's a feature after all (I hope with an option that can somehow be overridden because it doesn't feel "natural"):

![smartmenus-up-down_keys_circle_trhough_the_menu](https://cloud.githubusercontent.com/assets/2423362/18430776/537db83e-791d-11e6-8037-c04123d25e55.gif)

...so what happens is that the up/down keys circle through the menus. When the last item is reached, the next key tap moves the active menu back to the first one (and the reverse). In our case, this was not obvious because we need #2160

**Comment by klonos** [comment] 2016-09-12 09:19
...the Esc key works in getting you to the top-level menu 😉

**Comment by quicksketch** [comment] 2016-09-12 09:23
> . When the last item is reached, the next key tap moves the active menu back to the first one (and the reverse). In our case, this was not obvious because we need #2160

Ah, funny. Nice find.

I've made a feature branch at https://github.com/backdrop/backdrop/tree/1.x-basis. The Basis PR is currently failing tests however, we should at least get them working before merging, otherwise we won't have a good idea of if further changes are breaking things more or not.

**Comment by klonos** [comment] 2016-09-12 09:31
Filed and issue against the smartmenus queue to see if there is an option to change this behavior (or intention to add one).

**Comment by quicksketch** [comment] 2016-09-15 06:00
New tests are added in https://github.com/backdrop/backdrop/pull/1542, and everything is passing (Zen CI issues aside). This has been merged into 1.x for 1.5.0! Very exciting.

We have a number of follow-ups already.

- [Drop-down menus: add opacity on :hover.](https://github.com/backdrop/backdrop-issues/issues/2160)
- [Drop-down menus: 1st item in long menus is hidden under the admin bar.](https://github.com/backdrop/backdrop-issues/issues/2161)

Plus this could fix a number of issues in Admin Bar if we switch from the existing library to use the more comprehensive SmartMenus.

Very exciting!

**Closed** 2016-09-15 06:00 UTC
Labels: status - fixed, type - feature request

**Comment by klonos** [comment] 2016-09-15 19:52
Yeah, I don't know if you followed that issue, but @vadikom (SmartMenus dev) [has replied](https://github.com/vadikom/smartmenus/issues/50#issuecomment-247040565) explaining things. It seems that most of the things I've noticed are by design in order to mimic the behavior of app menus on Windows and Mac. As for the issue with the keyboard navigation...

> Like you've found out already:

>>  . When the last item is reached, the next key tap moves the active menu back to the first one (and the reverse). In our case, this was not obvious because we need #2160

> the up/down keys cycle through the current menu's items (actually the same goes for the left/right keys for a horizontal main menu). This is indeed a feature (desktop menus on Windows and to some extend macOS function similarly) and currently there is no way to disable it but I will consider providing an option in the next release of the keyboard add-on.
