### ISSUE TITLE
ob_end_flush notices in log again

### ISSUE THREAD

**Issue by vtad** [backdrop/backdrop-issues#1883] opened 2016-05-17 19:20 UTC
After updating from 1.3.5 to 1.4.0 I get:
Notice: ob_end_flush(): failed to delete and flush buffer. No buffer to delete or flush in backdrop_page_footer() (Zeile 2951 von /home/www/backdrop/core/includes/common.inc).

This was issue #1541 resolved with 
replacing line 2951 ob_end_flush(); with @ob_end_flush(); works,

**Comment by Gormartsen** [comment] 2016-05-17 20:26
@vtad can you let me know your PHP version please?

@quicksketch looks like you removed this one here:backdrop/backdrop#1218  related to backdrop/backdrop-issues#1541
but without ob_end_flush we have the issue with BootstrapPageCacheTestCase on php3 backdrop/backdrop#1378

There is 2 solutions:
put @ob_end_flush(); or check PHP version and do so if PHPv5.3 only.

**Comment by quicksketch** [comment] 2016-05-17 20:54
I think silencing the message would be the easiest and most effective. Let's get this in for the 1.4.1 release. Let's add a code comment to the effect of what purpose it serves, which versions require it and which cause a notice.

The error message is correct in that we shouldn't have any active buffers at the time that it is called. It might actually be just the "flush" part that sends information to the browser that is doing work.

In the original issue @vtad noted he was running PHP 5.5.

**Comment by quicksketch** [comment] 2016-05-17 20:57
This regression also means we should make a new 1.3.x release to fix the problem we made in 1.3.6. As this was backported in https://github.com/backdrop/backdrop/pull/1378.

**Comment by quicksketch** [comment] 2016-05-17 21:01
PR filed at https://github.com/backdrop/backdrop/pull/1399.

I really apologize @vtad for introducing this regression. It was only a few months ago that we *removed* this call. I should have done research as to why it was removed before adding it again.

**Comment by quicksketch** [comment] 2016-05-17 22:07
Merged into 1.x and 1.3.x. We'll make a new 1.3.7 release to fix this regression in 1.3.x. And of course 1.4.1 will also fix this issue.

**Comment by Gormartsen** [comment] 2016-05-18 02:08
@vtad Can you share phpinfo(); output from your host, please?

It will help me to reproduce environment where this issue happen to make it possible to test it in future.

thank you!

**Comment by vtad** [comment] 2016-05-18 07:35
The php info output

[phpinfo_htm.txt](https://github.com/backdrop/backdrop-issues/files/269847/phpinfo_htm.txt)

**Comment by Gormartsen** [comment] 2016-05-18 13:49
@vtad thank you. You helped to figure it out.
If you interested with process how we are going to cover and test it, you can follow #1888 

This issue is closed as resolved.

**Comment by quicksketch** [comment] 2016-05-18 22:40
For some reason my commit didn't actually show up in the 1.x history.

It's very clearly made right here: https://github.com/backdrop/backdrop/commit/0096913ebf86c6ee98c0e2cf173a8c814ab08398

And it supposedly is in the 1.x branch (I can see it in the `git log` as well as in the web interface on GitHub). But for whatever reason, when checking out the code, it's not in 1.x (or in 1.4.1). I'll make another release...

**Comment by quicksketch** [comment] 2016-05-18 23:01
Cut a new release, 1.4.2 that includes this fix for real this time. :hammer:

**Closed by quicksketch** 2016-05-18 23:01 UTC
Labels: type - bug report
