### ISSUE TITLE
Simple decimals fail to pass validation

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3792] opened 2019-05-17 15:09 UTC
**Description of the bug**
I am running into a problem where a number/decimal field is not allowing values that should pass the validation.

It is possibly related to [this Drupal 8 issue](https://www.drupal.org/project/drupal/issues/2230909)? Not certain but sounds similar, and the steps to reproduce listed here also reproduce the error on a Backdrop install: 

> **Problem/Motivation**
> 
> - Create decimal field, set precision to 10 (minimum in the UI and scale to 4
> - Saving new node with value 19999.0000 succeeds (precision is 5+4 = 9).
> - Saving new node with value 99999.0000 fails (same precision as above).
> 
> or
> 
> - Create decimal field, set scale to anything over 6 (need 8 to store bitcoin values for example). I used 16 as precission.
> - Saving new node with value 20.12345678 fails validation while 0.1234567 succeeds.
> 
> This is because Drupal\Component\Utility\Number::validStep() returns false. Detailed investigation on this function (which is only used once in Drupal), reveals that the first argument ($value) is received as a string, but $step and $offset are floats. PHP seems to slightly mangle the $step value on the first case above from 0.0001 to 0.00010000000000000001438. Passing the step parameter as a string in the case of decimal numbers maintains the correct precision, and allows a correct approximation calculation.
>
> **Proposed resolution**
> 
> Bypass weak PHP floating-point handling by passing the step as a string.
> 

**Update**

After some experiments with a much simpler, then the D8 approach, it turned out that neither of these works properly.

It needs a small change in function number_field_widget_form() and a complete rewrite of function valid_number_step().

Also note that several of the existing tests were wrong and needed switching, see [this comment](https://github.com/backdrop/backdrop-issues/issues/3792#issuecomment-724819508) for details and explanation.

Several additional automated tests have been added to verify the new approach.

---
There are currently two PR, which might be confusing.

- by @indigoxela https://github.com/backdrop/backdrop/pull/3392
- by @BWPanda outdated, just fixes a few false negatives

**Comment by klonos** [comment] 2020-11-03 21:00
Been working on #4732 and was able to confirm this bug here. The d.org issue is still marked as "needs work".

**Comment by indigoxela** [comment] 2020-11-04 08:51
> The d.org issue is still marked as "needs work".

The field settings are also base for the database column setting (table structure). If changing something about the validation logic results in different settings, that should get applied to the database, too. It might impact existing data. But that's only a problem when someone made "impossible settings".

I could also confirm that decimal validation is pretty unreliable:

- precision 12
- scale 6

- 119.200005 passes
- 219.200005 fails

It's clear that [function valid_number_step()](https://github.com/backdrop/backdrop/blob/e084bb8137dcbb76b1fbd627ece68a822077ca1b/core/includes/common.inc#L1456) needs to get fixed.

**Comment by indigoxela** [comment] 2020-11-07 15:20
It turned out that the problem has its root cause in the Number module and how the `#step` value gets created.

Example:
precision 12, scale 6 (correct step 1.0E-6)

In function number_field_widget_form() the value gets mangled, because php calculates `pow(0.1, $field['settings']['scale']);` to 1.0000000000000004E-6. Hence the validation fails.

My [PR](https://github.com/backdrop/backdrop/pull/3392) rounds the outcome of pow to the same scale value, which seems to give better results.

Astounded? Read more about the [PHP floating point precision](https://www.leaseweb.com/labs/2013/06/the-php-floating-point-precision-is-wrong-by-default/)

Fun fact: php on command line and php via apache calculate differently.

And yeah, this needs a bunch of functional tests. :wink:

But please test and report.

**Comment by klonos** [comment] 2020-11-08 01:21
Hmm 🤔 ... https://www.drupal.org/project/drupal/issues/2230909 has been open since 2014, and there is a great deal of feedback, testing, and various approaches. Although you approach is simplistic @indigoxela, I think that we should go with backporting the Drupal solution. At the moment, they seem to be going with this instead of rounding:

> Bypass weak PHP floating-point handling by passing the step as a string.

**Comment by indigoxela** [comment] 2020-11-08 08:12
@klonos Many thanks for having a look.

> I think that we should go with backporting the Drupal solution.

I disagree on that. My PR is not (only) "simplistic", but catches the problem _at the right point_ - where it arises. Whereas the D approach does a lot of weird math to solve a problem in a function that does not have a problem.

Why I think that? My first approach was to extend the existing tests with the examples we have here in our issue. But... they didn't fail. The output of function valid_number_step() was correct for all the examples. That's why I had to dig deeper and discovered, that the actual miscalculation happens in function number_field_widget_form().

Anyway, provide an alternative PR if you're convinced of their approach. :wink:

**Comment by indigoxela** [comment] 2020-11-08 13:56
A test has been added. Still failing, maybe because of the higher scale value.

Note, my simpler approach still fixes *many* faulty validation failures, but not all of them.

So we either do need to port the Drupal solution, or the problem is somewhere else.

**Comment by indigoxela** [comment] 2020-11-10 16:36
Wohoo, test passing... bigger change than I thought, but my PR is stuffed with comments.

Some might wonder, why I also changed "unrelated" tests. Here's why.

Following tests in functions testNumberStep() and testNumberStepOffset() have been moved to the proper section, results verified by `bc`:

**Is NOT divisble:**

```
$this->assertTrue(valid_number_step(1, 1/3));

echo 'scale=14; 1 % (1 / 3)' | bc
.0000000000000000000000000001
```

```
$this->assertTrue(valid_number_step(-100, 100/7));

echo 'scale=14; -100 % (100 / 7)' | bc
-.0000000000000400000000000000
```

```
$this->assertTrue(valid_number_step(-100, 90/7, -10));

echo 'scale=14; (-100 - -10) % (90 / 7)' | bc
-.0000000000000500000000000000
```

**IS divisible:**

```
$this->assertFalse(valid_number_step(1936.5, 3e-8));

echo 'scale=20; 1936.5 % 0.00000003' | bc
0
```

The PR function max scale is 13, we'd need at least a scale of 20 (!) to get this working, removed.

`$this->assertTrue(valid_number_step(2/7 + 5/9, 1/7, 5/9));`


Re test form test with following float 0.00392156863712 in form_test_number (core/modules/simpletest/tests/form_test.module)

A scale of 14 for the number widget, which has a UI limit of 10? Ambitious... Changed to scale 13.

I'm aware that my rewrite contains compromises, but so does the D8 solution (which actually doesn't fully work - even against a test with a scale of 8).
The previous solution was also a compromise, but one with way too much false negatives.

So, please test and review.

**Comment by klonos** [comment] 2020-11-10 20:06
> Anyway, provide an alternative PR if you're convinced of their approach.

**Comment by klonos** [comment] 2020-11-10 20:11
> ...but my PR is stuffed with comments.

That's a good thing though 😉 

I'll need some time to review/grok all this 😅

**Comment by klonos** [comment] 2020-11-10 20:25
...I know that @BWPanda has a great love for math, so he'll enjoy this a lot 🙂

**Comment by BWPanda** [comment] 2020-11-10 22:57
Ok, so I *do* enjoy maths, but this is getting over my head...

With that in mind, maybe I'm taking a simplistic approach, but based on the docblock comment for the `valid_number_step()` function ("Verifies that a number is a multiple of a given step."), couldn't that whole function be replaced with something like this:

```php
// Convert exponention notation to string.
$step_string = rtrim(sprintf('%.15F', $step), '0');

// Get integer and fraction parts of the step.
$step_parts = explode('.', $step_string);

if ($step_parts[1] > 0) {
  // Count the number of decimal places in the step.
  $decimal_places = strlen($step_parts[1]);

  // Convert the value by the same amount.
  $multiplied_value = $value * pow(10, $decimal_places);

  // Number is valid if mod == 0.
  $valid = $multiplied_value % (integer) $step_parts[1];
}
```

That's not final working code, but just wanted to get my idea across. I've run out of time to work on this now, so maybe it'll help someone else (or maybe it's rubbish).

**Comment by BWPanda** [comment] 2020-11-11 00:46
Looked at this again and I noticed something interesting (which @indigoxela touched on above):

(BTW, I'm using precision=10, scale=8 and entering the number: 20.05050505)

In `form_validate_number()` it calls `valid_number_step()` which fails. If I `dpm()` the variables it's sending to `valid_number_step()` then I get the expected `20.05050505` and `1.0E-8`. But if I go to `/admin/devel/php` and enter this:

```php
if (valid_number_step(20.05050505, 1.0E-8)) {
  dpm('Pass!');
}
else {
  dpm('Fail');
}
```

I see 'Pass!'. So `valid_number_step()`actally works (as @indigoxela said).

I tried working out what the different was between `form_validate_number()` and `/admin/devel/php`, and I finally thought to test the *type* of variables `form_validate_number()` was sending. Turns out that `$element['#step']` is a `double`...

Since passing strings works for both parameters in `/admin/devel/php`, I deciced to convert `$element['#step']` to a string instead, and after doing that, it validates! Here's a PR: https://github.com/backdrop/backdrop/pull/3396

**Comment by klonos** [comment] 2020-11-11 04:27
I like the idea of @BWPanda's 1-line PR 😅 ...what I would like us to do is this:

- add all tests from D8 (all seem to involve numbers/calculations)
- add all the tests from @indigoxela's PR
- confirm that all tests that are meant to be failing are indeed failing with current 1.x
- add the 1-liner fix, and confirm that all tests pass

**Comment by indigoxela** [comment] 2020-11-11 07:14
Hehe, very exciting discussion...

If a one-liner fixes it, that would of course be a much better solution. But to verify that, we need tests.

@BWPanda just grab my test from core/modules/field/modules/number/tests/number.test

One thing seems important to me: the existing but wrong tests I corrected like described in [my previous comment](https://github.com/backdrop/backdrop-issues/issues/3792#issuecomment-724819508).
Tests that do wrong math aren't useful.

I did consider the D8 approach, BTW, small parts of it went into my PR. But while playing with it, I realized that it's not really fixing as much as expected.

Again: we can not be 100% precise, there will always have to be compromises when it comes to very small floats or ones with high scale or numbers that exceed `ini_get('precision')` (14 by default in php).

**Comment by BWPanda** [comment] 2020-11-11 08:50
You guys seem to be more knowledgeable about the tests and what's needed here, so feel free to update/steal my PR.

**Comment by indigoxela** [comment] 2020-11-11 09:10
@BWPanda I did a quick check with your one-liner change with manual tests (decimal field).

Precision 14, scale 10:

- 20.123456789 - fail
- 9999.1933172003 - fail
- 219.200005 - pass
- 199.200001 - fail

It fixes one out of four.

**Comment by BWPanda** [comment] 2020-11-11 09:15
One down, three to go :wink:

**Comment by BWPanda** [comment] 2020-11-11 09:18
Ok, on a more serious note, the basis of my PR was the fact that `valid_number_step()` worked when I called it directly, but not when called from the form validation. So we need to work out if, in all other cases, calling `valid_number_step()` directly works (and therefore the issue is elsewhere), or if that was a random fluke and `valid_number_step()` actually needs work...

**Comment by indigoxela** [comment] 2020-11-11 09:24
> ... the basis of my PR was the fact that valid_number_step() worked when I called it directly, but not when called from the form validation...

That's what I fixed with `$element['#step'] = 1 / pow(10, $scale);` in function number_field_widget_form(). That fixed many, but by far not all problems. I think, the rest has to get fixed in function valid_number_step().

**Comment by indigoxela** [comment] 2020-11-12 13:41
**How to test:**

1. Attach a decimal field to a content type (sandbox)
2. Add content of that type with valid (but problematic) or with invalid values and verify the validation works correctly
3. If you get an unexpected result, post _precision + scale + decimal value_ here

**For people willing to review code:**

As function valid_number_step() is a complete rewrite, it might be easier to understand the logic if you view [the file without diff](https://github.com/indigoxela/backdrop/blob/31f3a49055408c1bcf1cb9181ba68a736bb54da4/core/includes/common.inc#L1452) - just a suggestion

**Comment by laryn** [comment] 2020-11-30 16:23
Error "Please select a value that is not more than 1000000" on:

- Precision 10
- Scale 2
- Decimal value:  12345678.91

This is a built-in error interface in Firefox (ie. not form validation, in case that matters) and seems to be due to a "max" value on the field itself:
![Screen Shot 2020-11-30 at 10 21 51 AM](https://user-images.githubusercontent.com/871421/100635335-04df0380-32f6-11eb-8eff-93481295c191.jpg)

**Comment by indigoxela** [comment] 2020-11-30 16:26
> Error "Please select a value that is not more than 1000000":

Yep, please ignore that - there's another Issue for that: #4751

To insert higher values, you need to set it in the field settings, but keep an eye on that other issue.

**Comment by laryn** [comment] 2020-11-30 16:36
@indigoxela Got it. When I change the field's maximum, Firefox allows me to input the value `12345678.12` for Prec 10, Sc 2 but then the form validation kicks in and gives me the "not a valid number." error.

**Comment by indigoxela** [comment] 2020-12-01 07:37
> Firefox allows me to input the value 12345678.12 for Prec 10, Sc 2 but then the form validation kicks in and gives me the "not a valid number." error.

@laryn many thanks for testing. Hm... `12345678.12 for Prec 10, Sc 2` passes here (gets saved without any problems).

What's your php setting for "precision" (admin/reports/status/php)? Which php version?

To make sure: there are two PR linked to this issue, which one did you pick? @BWPanda mind to close yours to prevent confusion?

**Comment by indigoxela** [comment] 2020-12-01 07:52
To verify the result I added 12345678.12 to the automated tests. It also passes in the Tugboat sandbox.

**Comment by stpaultim** [comment] 2020-12-16 23:44
I tested the following numbers that DID NOT work in existing Tugboat DEMO site, but did work with the PR.

333333.43
99999.0000
123456.78
55555.0000
35555.0000
292929.292

I was not able to cause it to fail with the PR.

Works for me!

**Comment by laryn** [comment] 2020-12-17 17:18
I did some testing as well and besides the separate `#max` issue it's looking good -- great job @indigoxela !

**Comment by indigoxela** [comment] 2021-01-01 15:20
Does anyone of the testers feel like this issue can get a milestone set?

**Comment by jenlampton** [comment] 2021-01-14 21:46
PR looks great, nice mew tests!!

**Closed** 2021-01-15 20:27 UTC
Labels: pr - ready to be committed, pr - works for me, status - has pull request, type - bug report

**Comment by quicksketch** [comment] 2021-01-15 20:30
The PR at https://github.com/backdrop/backdrop/pull/3392 looks great to me, though I admit I did not take the time to understand the more complex math portions. The new tests and the user testing validating the new use-cases are sufficient for me to believe that these problems are solved. I merged it into 1.x and 1.17.x. Thanks @indigoxela, @BWPanda, et al for the work on getting this gnarly problem figured out.
