### ISSUE TITLE
Fix CKEditor "Maximize" mode: form should save successfully after closing

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#4933] opened 2021-02-03 13:06 UTC
**Description of the bug**

Sometimes I'm not able to save a page after editing the body text in CKEditor. After hitting the "Save" button of the page edit form, the editor area changes: buttons disappear,  text is in source code, and the whole area seems frozen. To continue editing, I have to reload the edit form, and my edits of before are lost!

The issue doesn't happen all the times but quite often. I've experienced it on many different sites over a long time. (Didn't report it before, because I'm not sure how to exactly reproduce it reliably.)

**Steps To Reproduce**

To reproduce the behavior:
1. Add a page with some content, and save it.
2. Edit the page again. Maximize the CKEditor area (the "Maximize" button stays usually at the right of the toolbar).
3. Do some editing within the textarea. Insert also an image.
4. Minimize the CKEditor area again. (Everything fine so far.)
5. Hit the Save button of the content form.

**Actual behavior**

*Sometimes* the CKEditor area looses its buttons and seems frozen. Within the area, you see the source code of your content. The content isn't editable, and the content form doesn't seem to react in any way. The content doesn't get saved, and you just stay in the form. To continue, you have to hit the "Edit" tab at the top of the form and make your content changes again.

**Expected behavior**

The page is saved, and you are directed to where you came from.

**Additional information**

- Backdrop CMS version: various (not only the latest)
- Web server: various
- Operating System and Browsers: *most* of the times, I use Firefox on Mac OS

**Comment by indigoxela** [comment] 2021-02-03 13:34
I could just reproduce it (with Firefox ESR), but only when _adding an image from the image library_.
When adding no image or uploading a fresh one, no problem occurs. When selecting from library, the problem is reliably reproducible.

Nothing in the browser console log.

Maybe important: when closing the maximized editor, nothing happens yet, the toolbar is still there. The problem happens, when hitting the node's Save button.

**Comment by indigoxela** [comment] 2021-02-03 13:45
Update! In Chromium the situation is worse: it's reproducible with both, images from library and images that just got uploaded.

Editor + dialog + ajax... will be hard to find someone, who can solve this :sweat:

**Comment by olafgrabienski** [comment] 2021-02-04 20:49
> Editor + dialog + ajax... will be hard to find someone, who can solve this

Maybe @quicksketch who managed to fix the similar tricky issue https://github.com/backdrop/backdrop-issues/issues/1259?

**Comment by indigoxela** [comment] 2021-03-15 13:40
I can't help out with a solution here, but I did some analysis and found the reason.

Basically I did a recursive grep for "preventDefault" and blindly commented them out to see, which one's the "killer".
And then again and again opened a node form, did a maximize on the editor, opened and closed any dialog, un-maximized and tried to save the node form.

It's that line: https://github.com/backdrop/backdrop/blob/72b071a1842d9b745fc0fa28c069b20c6260984b/core/misc/form.js#L109

This came in with #2595 (a cross port):
```
163d73eceb core/misc/form.js (Jonathan Daggerhart 2019-04-27 16:22:14 -0400 109)

Author: Jonathan Daggerhart <jonathan daggerhart.com>
Date:   Sat Apr 27 16:22:14 2019 -0400

    Issue #2595: JavaScript double-click protection on form submit buttons.
  
    Cross-port of https://www.drupal.org/node/1705618
```
Code snippet from my debug session:
```
      var previousValues = $form.attr('data-backdrop-form-submit-last');
      if (previousValues === formValues) {
        console.log('you came here ... bad luck');
        e.preventDefault();// THIS is the killer...
      }
```
We probably have to make this check smarter. We still need someone with better js skills. :wink:

**Comment by indigoxela** [comment] 2021-03-16 07:19
Based on the suggestion by @docwilmot I created a [PR](https://github.com/backdrop/backdrop/pull/3566).

**How to test:**

Of course, repeat the steps from issue description.

But also check that there's no regression re double-click prevention. Example: on admin/config/administration/admin-bar double- or triple click on the submit button and verify, that one *one* message appears.

Do this in different browsers. Firefox has its own built-in double click prevention, but Chrome hasn't, so test in Chrome or Chromium - and other browsers.

**Comment by olafgrabienski** [comment] 2021-03-16 15:07
Thanks for the PR! Works for me, tested on Mac OS 10.14 in the following browsers:

- Chrome 88.0
- Firefox 86.0
- Opera 74.0
- Safari 12.1

**Comment by klonos** [comment] 2021-03-16 15:50
I've tested the PR sandbox against all STR reported in the d.org issue: https://www.drupal.org/node/1705618

First test:
- head to the module listing page
- open the network inspector
- scroll all the way down (do not select any module to be enabled/disabled)
- triple-click the submit button -> only a single POST event triggered 👍 
- select the Contact module to be enabled
- scroll all the way down and triple-click the submit button -> only a single POST event triggered 👍 
- select the Contact module to be disabled
- scroll all the way down and triple-click the submit button -> only a single POST event triggered 👍 

Second test:
- head to `admin/config/people/settings`
- set the "Who can register accounts?" setting to "Visitors, but administrator approval is required" and save
- log out
- head to `/user/register`
- enter a username and email address
- triple-click the submit button -> no errors whatsoever 👍

**Comment by indigoxela** [comment] 2021-03-19 07:00
> thank you @indigoxela for finding such an elegant fix!

It was actually teamwork. I found the cause, but @docwilmot found the solution (posted in zulip). :wink:

**Closed** 2021-03-24 00:45 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2021-03-24 00:48
I am not 100% certain how the PR fixes the problem, but I believe by the event handler being bound to the body element makes it fairly unlikely to affect other JavaScript behaviors negatively, since it's the last element that receives "bubbled-up" events. With the testing by several people, I have merged in https://github.com/backdrop/backdrop/pull/3566 into 1.x and 1.18.x. Thanks @indigoxela, @docwilmot, @olafgrabienski, @jenlampton, and @klonos for your work on this issue.
