### ISSUE TITLE
[A11Y] Provide an API for aria-live region update announcements for accessibility improvements

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#4985] opened 2021-03-07 04:27 UTC
**Description of the need**
Sister issue on D7: https://www.drupal.org/project/drupal/issues/1915302
Triggering issue on Backdrop: https://github.com/backdrop/backdrop-issues/issues/4941
Read about aria-live here: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

Specifically, we are looking for ways to make the Layout block add page accessible.

**Proposed solution**

An API to allow devs to trigger announcements on certain screen events and interactions
PR upcoming; ported from D7.

---
PR by @docwilmot https://github.com/backdrop/backdrop/pull/3557

**Comment by indigoxela** [comment] 2021-03-07 08:29
@docwilmot many thanks for porting this important change.

There currently seems to be a problem, though: the div with id "backdrop-live-announce" gets duplicated on events instead of updating it:

![duplicate-ids](https://user-images.githubusercontent.com/842066/110233862-384db180-7f27-11eb-9b2d-9f3aad196b3c.png)

What seems to be missing is: `if (!liveElement) {...}` - only guessing, my js foo is limited. :wink:

**Comment by docwilmot** [comment] 2021-03-07 14:19
Very true, thanks, fixed.
> my js foo is limited

No less than mine I'm sure. My "PRs" are officially considered suggestions for @quicksketch to do the real work.

**Comment by MustafaDogan78** [comment] 2021-03-07 21:56
I don't know English. I'm building a dialect with translation. It's a Problem, but there's no other way. There is another problem with accessibility. Setting permissions. Problem reading roles first, then checkboxes. When using Drupal, the cue box and the roles would be read simultaneously. I figure out what role to allow by counting the tick boxes.

**Comment by quicksketch** [comment] 2021-03-07 22:34
Thanks @docwilmot for filing this issue! And thank you @MustafaDogan78 for providing more reports on accessibility problems. Let's use this issue to discuss the new feature for `aria-live` announcements. I made a new issue at https://github.com/backdrop/backdrop-issues/issues/4987 that we can use to discuss this new problem that you have described regarding the permissions page.

**Comment by docwilmot** [comment] 2021-03-08 22:30
The final Drupal version of this includes a debounce to allow multiple consecutive announcements to be queued up and read. I added the denounce function to Backdrop.js instead of a separate debounce file, since there's only one usage of this so far..

Also removed the tabledrag changes, so that we could commit this as a standalone API. We can add implementations as we go along later.

To test then will require pulling to local. Recommend adding a few lines of
```
    Backdrop.announce('hello world');
    Backdrop.announce('hello another world');
    Backdrop.announce('goodbye world');
```
to a JS file that listens for some user action (pasting the above in `Backdrop.behaviors.layoutDisplayEditor.updateLayout()` would fire anytime you drag a block in layout editor, for example) and listen with a screen reader.

Needs milestone and a review then please.

**Comment by MustafaDogan78** [comment] 2021-03-08 23:37
I can not speak English. I could not understand with translation. I sent the article to my friend who speaks English. He will translate it into Turkish and send it to me. As soon as the answer comes, I will quickly do what you said. I will write to you as soon as possible.

**Comment by indigoxela** [comment] 2021-03-09 07:13
@docwilmot I'll definitely need more detailed instructions on how to test the new API. As I already stated, my js foo is limited.

**Comment by MustafaDogan78** [comment] 2021-03-09 07:49
I made a mistake. I am very sorry. after the misunderstanding, I got this 
mixed up.
http://3531.backdrop.backdrop.qa.backdropcms.org/admin/structure/layouts/update
Everything's gone. I hope he has a backup. again, I'm sorry.

**Comment by indigoxela** [comment] 2021-03-09 07:56
@MustafaDogan78 No problem, no need to excuse. It's currently a bit confusing (also for me), because we have several issues that partly depend on each other. We'll hopefully sort out things soon, so it gets easier for testers to catch up.

**Comment by MustafaDogan78** [comment] 2021-03-09 08:09
I made unintentional changes to the site. I've updated the layouts. There was a flashback. The developments there are gone. I'm talking about the Test site. the language problem caused it. I am very sorry. I hope he has a backup. I may have ruined your friends ' work.

**Comment by indigoxela** [comment] 2021-03-09 08:17
> I've updated the layouts. There was a flashback. The developments there are gone. 

@MustafaDogan78 don't worry. Every time a pull request gets updated, the test box gets flushed. The developer reverted some of the initial changes, so this pull request only provides the API without any actual implementation. This means, that you can't test the new functionality here anymore. Nothing's broken. We'll inform you and other testers, as soon as there's some actual functionality to test on the issues, that will actually use this API.

**Comment by docwilmot** [comment] 2021-03-09 17:19
I forgot to mention one important thing for testing: announce library has to be loaded. Add backdrop_add_library('system', 'announce'); in layout_content_form().

It may be reasonable to just add the `Backdrop.announce` function to `Backdrop.js` to prevent this requirement. I'll have to see what @quicksketch suggests as I'm not sure of the implications. 

Reading the issue, D8/9 initially did have announce in `Drupal.js` but moved it out when they recognized it needed debounce, as debounce was already in its own file and it wouldn't do to have `Drupal.js` dependent on `debounce.js`. But if we're starting off creating both files, we could just add both to `Backdrop.js` from the start, I'd think.

**Comment by indigoxela** [comment] 2021-03-10 06:27
> I forgot to mention one important thing for testing: announce library has to be loaded.

@docwilmot I was aware of that. My testing setup is as such (I used Seven for a quick check):

- In template.php in hook seven_preprocess_page I added `backdrop_add_library('system', 'announce', TRUE);`
- In seven.info I added `scripts[] = js/helper.js`
- Verified that both files are loaded

The content of helper.js:

```
(function ($) {

  $(document).ready(function() {
      $('.form-type-checkbox input').on('change', function () {
        var notifytext = $(this).next('label').text() + ' has changed.';
        if ($(this).prop('checked') == true) {
          notifytext += ' New value is "checked".';
        }
        else {
          notifytext += ' New value is "unchecked".';
        }
        Backdrop.announce(notifytext);
      });
  });

})(jQuery);
```
This is not supposed to be a real-life example, but I expected it to work. But...

I opened /node/1/edit and checked/unchecked one of the checkboxes. And in the browser console I got:

```
Uncaught TypeError: Backdrop.behaviors is undefined
Uncaught TypeError: Backdrop.announce is not a function
```
Only if I edit announce.js and add on top:
`Backdrop.behaviors = {};`
These errors go away and the div with id "backdrop-live-announce" finally gets added, but then when I check/uncheck a checkbox I get:
`Uncaught TypeError: debounce is not a function`
After changing `return debounce(announce, 300)();` to `return Backdrop.debounce(announce, 300)();`, the announcements work.

What am I missing?

**Comment by indigoxela** [comment] 2021-03-10 15:08
> What am I missing?

Now I know - it's the _order_ in which the js files get loaded. The trouble I had was caused by the fact, that the file "announce.js" has been loaded even before "backdrop.js".

My sample code from above works without console nagging, if I slightly adapt the library definition to add the announce library to a different group (JS_DEFAULT) - which is loaded later. Not sure, if that's a valid solution.

Some other thoughts:

- I'm not sure, if the Drupal9 js namespaces should be uses as-is (`})(Backdrop, Backdrop.debounce);`)
- I'm not sure, if the library version should be `1.0.0` - I'd rather assume `BACKDROP_VERSION`

**Comment by docwilmot** [comment] 2021-03-10 16:53
Wow, you certainly found a thorough way to test this. 
I've implemented your suggestions.

**Comment by indigoxela** [comment] 2021-03-11 06:21
One last question:
In function announce() the "aria-busy" attribute gets set to true and instantly to false again.

```
      liveElement.setAttribute('aria-busy', 'true');
      liveElement.setAttribute('aria-live', priority);
      liveElement.innerHTML = text.join('\n');
      liveElement.setAttribute('aria-busy', 'false');
```
Will screen readers pick this up quickly enough? I'm asking, because I can't properly test that yet (I didn't manage yet to get Orca working on my Linux and don't have Windows, so can't use NVDA.)

**Comment by MustafaDogan78** [comment] 2021-03-11 12:03
We can test it together. Send me the draft and I'll set up a yee. I'm also looking at the code you wrote. E-mail: ***@***.***

**Comment by indigoxela** [comment] 2021-03-11 13:37
> We can test it together. Send me the draft and I'll set up a yee. I'm also looking at the code you wrote.

@MustafaDogan78 many thanks for your offer, but I'm afraid there's not much to actually test here. My example code, which I used locally, was only meant to verify that the new API will be working. That seems to be the case.

If you want to test locally, you could adapt my code example. Make sure that you have the latest code changes from the pull request on https://github.com/backdrop/backdrop/pull/3557.

Then you can load the library in a theme or module with, for instance, `backdrop_add_library('system', 'backdrop.announce')`.
And then you should be able to use `Backdrop.announce('Your announce text');` in your custom Javascript code.
Does this help in any way?

**Comment by MustafaDogan78** [comment] 2021-03-11 16:50
it'll be as you say. Screen reader works well with Aria. if a screen reader cannot work with aria, the problem is with the screen reader.

**Comment by indigoxela** [comment] 2021-03-12 07:59
In the meantime I've been able to get Orca on my Linux (more or less) working. I could verify, that it properly picks up changes.

I'd say: works for me. I've left a suggestion to add some info to the doc block, about how to include the library.
What should be our next steps?

**Comment by quicksketch** [comment] 2021-03-12 20:33
@docwilmot has suggested that we include this in the next bugfix release (1.18.2 if possible) because it will help resolve the accessibility problems with Layout module (see https://github.com/backdrop/backdrop-issues/issues/4941).

Although this is a new API and feature, we make exceptions for UX improvements that they can be made at any time (as long as they don't have compatibility impacts). I think this falls under that umbrella of exceptions.

I think the next step here is to merge this issue, so that #4941 can utilize it. What do you folks think?

**Comment by quicksketch** [comment] 2021-03-24 22:45
I added docblocks to both Backdrop.debounce() and Backdrop.announce(), and added @since 1.18.2 indicators to clarify when this API became available.

We're not yet using this functionality but it is now in place for further enhancements.

I have merged https://github.com/backdrop/backdrop/pull/3557 into 1.x and 1.18.x. Thanks @docwilmot, @indigoxela, and @MustafaDogan78!

**Comment by quicksketch** [comment] 2021-03-24 22:49
I have made a follow-up to integrate this new feature with the block UI: https://github.com/backdrop/backdrop-issues/issues/5021

**Comment by klonos** [comment] 2021-03-25 01:27
I'm re-opening this issue and adding the label for a change record, so that it's within our radar to do - but still keeping the "status - fixed" label 😉

**Comment by herbdool** [comment] 2024-01-04 22:50
Change record https://docs.backdropcms.org/change-records/new-api-to-allow-for-aria-live-regions-for-announcing-ui-changes-aurally

**Closed by herbdool** 2024-01-04 22:50 UTC
Labels: type - task, needs - change record, status - fixed
