### ISSUE TITLE
Project installer: Modules sort by "Most installed" are displayed in wrong order

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#2227] opened 2016-09-22 21:24 UTC
When you order on the "Install modules" page by "Most installed" (admin/modules/install?order=usage&sort=desc), the order seems to be in confusion:

![screen-backdrop-1-5-project-installer-sort-most-installed](https://cloud.githubusercontent.com/assets/14188307/18766611/602a3188-811b-11e6-80fd-7b5b9bb77003.png)

Below in the list (not on the screenshot), I see even more deviating examples.

Can anyone confirm this?

**Comment by olafgrabienski** [comment] 2016-09-22 21:26
Forgot to mention: Backdrop 1.5 (no fresh install, updated a 1.34 version in Kalabox)

**Comment by klonos** [comment] 2016-09-23 08:54
> Can anyone confirm this?

Yes, I've noticed this before.

**Comment by quicksketch** [comment] 2016-10-17 04:38
Thanks @olafgrabienski for reporting this issue. This is likely a server-side problem on backdropcms.org, as it's responsible for returning the results in the right order. Relevant code should be in the `borg_project_browser_server.module` in the BackdropCMS.org repository (http://github.com/backdrop-ops/backdropcms.org).

**Comment by olafgrabienski** [comment] 2016-10-17 10:06
So, should I post an issue there?

**Comment by quicksketch** [comment] 2016-10-18 03:19
Eh, nah I think that's fine. I think I found the source of the problem.

Here's the current query:

```
mysql> SELECT n.*, (SELECT SUM(w.count) FROM project_usage_week_project w WHERE w.nid = n.nid) AS usage_query FROM node n INNER JOIN project_release p ON n.nid = p.project_nid WHERE (n.type = 'project_module') GROUP BY n.nid ORDER BY usage_query DESC LIMIT 12 OFFSET 0;
+-----+------+----------------+----------+--------------------+-----+--------+------------+------------+---------+---------+--------+------+-----------+-------------+
| nid | vid  | type           | langcode | title              | uid | status | created    | changed    | comment | promote | sticky | tnid | translate | usage_query |
+-----+------+----------------+----------+--------------------+-----+--------+------------+------------+---------+---------+--------+------+-----------+-------------+
| 182 |  217 | project_module | und      | Backup and Migrate |   1 |      1 | 1432646903 | 1472104777 |       0 |       0 |      0 |    0 |         0 |        1366 |
| 167 |  201 | project_module | und      | Devel              |   1 |      1 | 1431651411 | 1472104777 |       0 |       0 |      0 |    0 |         0 |        1241 |
| 130 |  164 | project_module | und      | Honeypot           |   1 |      1 | 1430146403 | 1472104777 |       0 |       0 |      0 |    0 |         0 |         821 |
| 416 |  484 | project_module | und      | Google Analytics   |   1 |      1 | 1450315512 | 1472104777 |       0 |       0 |      0 |    0 |         0 |         756 |
| 149 |  183 | project_module | und      | Webform            |   1 |      1 | 1430177546 | 1472104777 |       0 |       0 |      0 |    0 |         0 |         681 |
| 163 |  197 | project_module | und      | Libraries          |   1 |      1 | 1431288395 | 1472104777 |       0 |       0 |      0 |    0 |         0 |         555 |
| 120 |  154 | project_module | und      | On The Web         |   1 |      1 | 1429827928 | 1472104777 |       0 |       0 |      0 |    0 |         0 |         456 |
| 118 |  152 | project_module | und      | Redirect           |   1 |      1 | 1429823008 | 1472104777 |       0 |       0 |      0 |    0 |         0 |         454 |
| 463 |  553 | project_module | und      | IMCE               |   1 |      1 | 1453739379 | 1472104777 |       0 |       0 |      0 |    0 |         0 |         401 |
| 192 |  227 | project_module | und      | Google Fonts       |   1 |      1 | 1433954737 | 1472104777 |       0 |       0 |      0 |    0 |         0 |         387 |
| 430 |  499 | project_module | und      | FlexSlider         |   1 |      1 | 1451532451 | 1472104777 |       0 |       0 |      0 |    0 |         0 |         382 |
| 114 |  147 | project_module | und      | Global Redirect    |   1 |      1 | 1429673649 | 1472104777 |       0 |       0 |      0 |    0 |         0 |         378 |
+-----+------+----------------+----------+--------------------+-----+--------+------------+------------+---------+---------+--------+------+-----------+-------------+
12 rows in set (0.01 sec)
```

The problem is we're sorting based on the SUM() of usages, so Backup Migrate might be the "most popular module in the existence of Backdrop", but not the "most popular module right now". :smile:

Looks like we just need to sort on the latest usage, not the sum of all usage ever.

**Comment by quicksketch** [comment] 2016-10-18 03:22
Here's what the fixed query looks like: 

```
mysql> SELECT n.*, (SELECT w.count FROM project_usage_week_project w WHERE w.nid = n.nid ORDER BY timestamp DESC LIMIT 1) AS usage_query FROM node n INNER JOIN project_release p ON n.nid = p.project_nid WHERE (n.type = 'project_module') GROUP BY n.nid ORDER BY usage_query DESC LIMIT 12 OFFSET 0;
+-----+------+----------------+----------+--------------------+-----+--------+------------+------------+---------+---------+--------+------+-----------+-------------+
| nid | vid  | type           | langcode | title              | uid | status | created    | changed    | comment | promote | sticky | tnid | translate | usage_query |
+-----+------+----------------+----------+--------------------+-----+--------+------------+------------+---------+---------+--------+------+-----------+-------------+
| 167 |  201 | project_module | und      | Devel              |   1 |      1 | 1431651411 | 1472104777 |       0 |       0 |      0 |    0 |         0 |          42 |
| 130 |  164 | project_module | und      | Honeypot           |   1 |      1 | 1430146403 | 1472104777 |       0 |       0 |      0 |    0 |         0 |          39 |
| 416 |  484 | project_module | und      | Google Analytics   |   1 |      1 | 1450315512 | 1472104777 |       0 |       0 |      0 |    0 |         0 |          36 |
| 182 |  217 | project_module | und      | Backup and Migrate |   1 |      1 | 1432646903 | 1472104777 |       0 |       0 |      0 |    0 |         0 |          35 |
| 149 |  183 | project_module | und      | Webform            |   1 |      1 | 1430177546 | 1472104777 |       0 |       0 |      0 |    0 |         0 |          33 |
| 163 |  197 | project_module | und      | Libraries          |   1 |      1 | 1431288395 | 1472104777 |       0 |       0 |      0 |    0 |         0 |          29 |
| 430 |  499 | project_module | und      | FlexSlider         |   1 |      1 | 1451532451 | 1472104777 |       0 |       0 |      0 |    0 |         0 |          26 |
| 463 |  553 | project_module | und      | IMCE               |   1 |      1 | 1453739379 | 1472104777 |       0 |       0 |      0 |    0 |         0 |          25 |
| 120 |  154 | project_module | und      | On The Web         |   1 |      1 | 1429827928 | 1472104777 |       0 |       0 |      0 |    0 |         0 |          20 |
| 192 |  227 | project_module | und      | Google Fonts       |   1 |      1 | 1433954737 | 1472104777 |       0 |       0 |      0 |    0 |         0 |          17 |
| 449 |  530 | project_module | und      | References         |   1 |      1 | 1453244810 | 1472104777 |       0 |       0 |      0 |    0 |         0 |          17 |
| 135 |  169 | project_module | und      | Colorbox           |   1 |      1 | 1430170609 | 1472104777 |       0 |       0 |      0 |    0 |         0 |          15 |
+-----+------+----------------+----------+--------------------+-----+--------+------------+------------+---------+---------+--------+------+-----------+-------------+
12 rows in set (0.01 sec)
```

Much better and reflects the counts you see on the project pages.

**Comment by quicksketch** [comment] 2016-10-18 03:28
Fixed in https://github.com/backdrop-ops/backdropcms.org/commit/f1511ffd967a14ddc1b50a7ade2415e2d394e327. Thanks for reporting this @olafgrabienski!

**Closed** 2016-10-18 03:28 UTC
Labels: status - fixed
