### ISSUE TITLE
Don't count markup characters as part of the text length

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#309] opened 2014-08-22 21:54 UTC
Problem: People are often frustrated when they expect 600 characters of text, and get far fewer because their post contained an image, or other HTML.

Solution: We should strip the HTML tags out of a post before we count the characters. 

Link on [d.o](https://www.drupal.org/node/221257)
[D7 module](https://www.drupal.org/project/field_html_trim) which attempts to solve this problem

**Comment by BWPanda** [comment] 2015-01-18 04:16
Can we also add in this functionality: [Field Word Boundary](https://www.drupal.org/project/field_word_boundary)? This module allows trimming to word boundaries, not just sentences or paragraphs. Seems like a logical addition to core...

(I think the problem this solves is most often seen when the trim length is quite short (e.g. 100 characters) and the first sentence is longer than this - this means that nothing gets output).

**Comment by jenlampton** [comment] 2015-01-18 04:38
Yes. But can we make a separate issue for that?

**Comment by BWPanda** [comment] 2015-01-18 04:49
There you go :)

**Comment by jenlampton** [comment] 2015-01-18 06:51
woot!  thanks :)

**Comment by Dinornis** [comment] 2017-05-02 22:34
👍 for removing markup from content before counting characters to determine text length.

**Comment by BWPanda** [comment] 2020-08-17 06:08
I looked at @jenlampton's PR and it seems to have some code that's unnecessary or incomplete... E.g. defining variables that aren't really used, adding a new parameter to the function that's never used, etc.

So definitely 'needs work', and not just for tests...

**Comment by BWPanda** [comment] 2021-12-24 04:21
I've been trying to work on this, but I'm coming up against two problems:

1. The main part of the [Field HTML Trim](https://www.drupal.org/project/field_html_trim) module is a function they copied from CakePHP: https://git.drupalcode.org/project/field_html_trim/-/blob/7.x-1.x/field_html_trim.module#L202 This is what does the HTML-trimming magic. However, it includes code for adding an ellipsis and for trimming to a word or to an exact number of characters (even if that's within a word). Both of these things are outside the scopeof this issue (which is just for excluding the HTML tags when calculating the trim count)...

2. I'm not sure how to integrate this magic function with Backdrop's existing system of trimming to a paragraph, or to a line-break, or to a sentence (in that order).

So not sure how best to proceed...

**Comment by BWPanda** [comment] 2021-12-24 04:25
I'm changing this from a bug report to a feature request, since if we implement this it should be a checkbox to exclude HTML tags in the trim count (disabled by default, for backwards compatibility). Also removing the PR labels since that PR is so old (and the original branch deleted) that we basically need to start from scratch anyway.

**Comment by jenlampton** [comment] 2021-12-24 16:57
It might also be worth reviewing the Drupal issue and seeing if there's a
new patch. But this is definitely a huge bug since it can break your site
if you get only an opening HTML take in the summary.

**Comment by klonos** [comment] 2021-12-28 09:11
Yeah, I also see this as a bug.

**Comment by klonos** [comment] 2021-12-28 09:12
> It might also be worth reviewing the Drupal issue and seeing if there's a new patch.

Nope, no new patch. But it seems that this is also tormenting our Drupal brethren, and the issue is marked as "Backport to D7", so that's good news I think.

**Comment by klonos** [comment] 2021-12-28 09:17
I'm wondering if we should follow a simplistic approach, using `strip_tags()`, and then basing our word/character count on that. I'll need to think more about this.

**Comment by klonos** [comment] 2021-12-30 21:36
@BWPanda during today's dev meeting, @jenlampton mentioned that she's been having better results with https://github.com/backdrop-contrib/smart_trim, so it might be worth checking the implementation they are using.

**Comment by BWPanda** [comment] 2022-01-01 10:39
@klonos See https://github.com/backdrop/backdrop-issues/issues/599#issuecomment-1003539213 where I suggest avoiding that approach...

**Comment by BWPanda** [comment] 2022-01-24 05:19
See https://github.com/backdrop/backdrop-issues/issues/599#issuecomment-1019730627 for my proposal for this issue.

**Comment by BWPanda** [comment] 2023-02-27 06:04
I'm closing this issue in favour of https://github.com/backdrop/backdrop-issues/issues/6001

**Closed by BWPanda** 2023-02-27 06:04 UTC
Labels: status - duplicate
