### ISSUE TITLE
[DX] move system_admin_bar_cache_info() into update.module

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#804] opened 2015-03-06 02:16 UTC
left-over cleanup from moving admin_menu/admin_bar into core.  `update_admin_bar_cache_info()` is in `admin_bar.inc` instead of in `update.module`. 

Let's move this function.

---
PR by @docwilmot: https://github.com/backdrop/backdrop/pull/2212

**Comment by klonos** [comment] 2018-09-03 21:58
I have approved the PR since it just verbatim moved two functions to their respectively appropriate places. The PR sandbox takes you to the installation wizard though. Not sure if this is a fail of the sandbox or caused by the PR somehow. @docwilmot can you please close and reopen the PR to refresh the sandbox? Thanks

**Comment by docwilmot** [comment] 2018-09-03 22:09
Rebooted, all is well. Feel free to RTBC.

**Comment by herbdool** [comment] 2018-09-07 02:18
I checked too on test box. Looks good.

**Comment by quicksketch** [comment] 2018-09-09 21:35
Looks great. Merged https://github.com/backdrop/backdrop/pull/2212 into 1.x for 1.11.0.

**Closed** 2018-09-09 21:35 UTC
Labels: status - has pull request, status - fixed
