### ISSUE TITLE
Language names not translated to their native names

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4511] opened 2020-07-31 15:45 UTC
One thing baffles me: the language names themselves are not translated.

With one notable exception: the installer uses the native name.
Everywhere else the English names appear (language select list, language switcher block, language overview list, translation page...)

<strike>I wonder what the reason for this is.</strike>

The reason for this is a breaking change in early Drupal 8:

- Breaking commit 879b5357cd6c8cb9a62ee63e5b06e72b82fa05ae
- Drupal Issue: https://www.drupal.org/project/drupal/issues/1301148
- Drupal patch: https://www.drupal.org/files/kill-fake-locale-config-translation-13.patch
- Drupal changelog: https://www.drupal.org/node/1323146

----
Will also address this bug (moved from https://github.com/backdrop/backdrop-issues/issues/4838):

1. Enable locale, language modules
2. Create a view of type "Locale source"
3. Add a field "Locale target: Language", set display to "Native language", save and refresh preview

You get a bunch of:

> Notice: Undefined property: stdClass::$native in views_language_list() (line 752 of .../core/modules/views/views.module).

Reason: The "native" property has been removed from the $language object

**Comment by klonos** [comment] 2020-07-31 17:10
No good reason 😅 ...the only thing I can think of is that we'd need to decide how these are sorted (alphabetically?), and also whether the English version of the language name will be listed next to it.

There are some issues that would come up with trying to properly represent certain languages in the same dropdown select, such as the default being RTL (can you have both LTR and RTL in the same select?), or being a vertical language:

![image](https://user-images.githubusercontent.com/2423362/89059412-cc401500-d369-11ea-9fbc-6ebeea7e7cf3.png)

**Comment by indigoxela** [comment] 2020-08-02 12:07
@klonos many thanks for taking the time to do some recherche on this. This doesn't, however, seem plausible to me.

**Comment by indigoxela** [comment] 2020-08-02 12:20
Looks like this is a regression that Backdrop inherited from early D8:

- https://www.drupal.org/project/drupal/issues/2107427
- https://www.drupal.org/project/drupal/issues/1879930

Proposed solution: implement a "native" property for language objects. Other ideas?

**Comment by klonos** [comment] 2020-08-03 15:57
Nice find those 2 d.org issues @indigoxela 👍 

I wouldn't mid going with whichever solution fixed things for D8 (if possible).

**Comment by indigoxela** [comment] 2020-08-04 05:39
> I wouldn't mind going with whichever solution fixed things for D8 (if possible).

The D8 solution is, of course, not applicable for Backdrop.

**Comment by indigoxela** [comment] 2020-08-04 06:15
Views does translate the language name in [views_language_list()](https://api.backdropcms.org/api/backdrop/core%21modules%21views%21views.module/function/views_language_list/1)

Via t().

**Comment by herbdool** [comment] 2020-10-27 11:37
Those are really long issues! I didn't read enough to understand how it was a regression. I'm ok with resurrecting how d7 did it (if that was core) with the native name.

**Comment by indigoxela** [comment] 2020-12-29 12:26
Coming back to this issue after some time. With more detailed information:

- Breaking Drupal commit 879b5357cd6c8cb9a62ee63e5b06e72b82fa05ae
- Drupal Issue: https://www.drupal.org/project/drupal/issues/1301148
- Drupal patch: https://www.drupal.org/files/kill-fake-locale-config-translation-13.patch
- Drupal changelog: https://www.drupal.org/node/1323146

The regressions caused by this change have already been linked in one of my previous comments.

My proposed solution for this problem is still to restore the "native" property for language. Not sure, how exactly this could be accomplished.

**Comment by indigoxela** [comment] 2020-12-29 13:46
A [PR](https://github.com/backdrop/backdrop/pull/3463) is available for curious testers.

It (sort of) restores parts of the breaking D8 commit - without the use of t(), BTW.

When installing a new predefined language, the native name is pulled from core/includes/standard.inc, but the native name is also a form item when editing installed languages.

The native names show up in different locations.

1. When translating nodes (in the language dropdown)
2. When viewing node translations (links to translations below node content)
3. In the language overview (admin/config/regional/language)
4. In the language switcher block

Although the PR still needs work, testing and feedback is welcome. For instance, where else should the native language name used instead of the English name?

(I suppose, this will be a 1.19.0 task :grin:)

**Comment by findlabnet** [comment] 2020-12-29 14:30
>where else the native language name is preferred over the English name?

Menu item add/edit form.

Can't test right now, sorry. One question: what should be done with this new(restored) feature upgrade on existing site where language(s) renamed already by hand?

**Comment by indigoxela** [comment] 2020-12-29 14:41
> One question: what should be done with this new(restored) feature upgrade on existing site where language(s) renamed already by hand?

Ah, that's what you used as workaround. The language form provides two different fields, so it's easy to override (again), if needed:
![language-form](https://user-images.githubusercontent.com/842066/103291249-94f29480-49eb-11eb-875b-6997dfbe336d.png)

In an update hook (to be done) existing sites get the native values added either from core/includes/standard.inc, which has a long language list available, or if nothing found in that list, the original language name would get copied. The original name works as a fallback anyway. So IMO this change doesn't break anything.

**Comment by klonos** [comment] 2020-12-30 07:56
@indigoxela the code looks good so far, but I've done some quick testing and found certain things not working as expected:

- Customizing any native language name does not work (the custom value does not get saved):
  - edit any language (even English)
  - change the native language name (lets say "my Français" or "Français 123")
  - save -> you are redirected to the language list, and there's a "The configuration options have been saved." success message shown, but the label is still "English" 👎 
  - edit the language again -> the value of the "Native language name" field is reverted to "English" or "Français" (the default native name instead of the custom one) 👎 
- When adding a language, the language selection dropdown in `admin/config/regional/language/add` only shows the English names of the languages.
- Should the labels of languages be `$native . `(` . $language_name . `)`` or `$native . `(` . $langcode . `)``? It would help non-native speakers identify the language.

**Comment by indigoxela** [comment] 2020-12-30 10:25
@klonos many thanks for having a look.

> Customizing any native language name does not work

You're right, I forgot to update the edit form. Done now.

> When adding a language, the language selection dropdown in admin/config/regional/language/add only shows the English names

That's right. Would this be a place where native names are preferred?

Regarding the labels and which value should be in parentheses ... `name (native)` or the other way round - I don't know.
Where should it be used? I suppose you refer to function locale_language_selector_form() - which I didn't touch yet. That's the user's language selection form.
I wouldn't use it for dropdown lists, though.

**Comment by klonos** [comment] 2020-12-30 11:53
> I forgot to update the _edit_ form submit function. Done now.

Thanks ...works as expected now 👍 

> That's right. Would this be a place where native names are preferred?

Yup, I think so. IMO there + the installer language selector should be showing native language names.

> Regarding the labels and which value should be in parentheses ... `name (native)` or the other way round - I don't know.

I don't have any specific preference, so lets bikeshed based on user feedback 😅 ...in the meantime, I'll do some research to see what is considered best practice.

I like how the language switcher looks with https://www.drupal.org/project/lang_dropdown + http://drupal.org/project/languageicons:

![image](https://user-images.githubusercontent.com/2423362/103349747-5a99fd80-4aa6-11eb-85c3-55bad948ce06.png)

**Comment by klonos** [comment] 2020-12-30 12:02
...well, turns that flag icons aren't a good idea (and there's a dedicated domain for it too 😅): http://www.flagsarenotlanguages.com/blog/language-menus-flags-symbolize-nations-not-languages. I think I agree:

![image](https://user-images.githubusercontent.com/2423362/103350111-8ec1ee00-4aa7-11eb-993c-5a53e4e0e566.png)

**Comment by indigoxela** [comment] 2020-12-30 12:02
>>    That's right. Would this be a place where native names are preferred?

> Yup, I think so. IMO there + the installer language selector should be showing native language names.

Let's see what people recommend.
Personally, I'd prefer the English names here. I wouldn't be able to add Arabic or Hindi to a site then, because I wouldn't be able to reliably recognize it. 
The installer shows the native name out of the box, BTW - nothing to do regarding that.

> I like how the language switcher looks with https://www.drupal.org/project/lang_dropdown + http://drupal.org/project/languageicons

Hm... Country flags for languages - I'd not recommend it. There are plenty of related discussions out there. TLDR: there are many countries with more than one language, there are many languages spoken in different countries.
Ah, you found it while I was writing. :laughing:

**Comment by klonos** [comment] 2020-12-30 12:10
> The installer shows the native name out of the box, BTW - nothing to do regarding that.

👍 

> Ah, you found it while I was writing. 😆

😆

**Comment by klonos** [comment] 2020-12-30 12:10
Interesting read:

- https://uxdesign.cc/my-take-on-language-selectors-945caceb58f7
- https://uxdesign.cc/designing-language-selectors-that-work-well-with-assistive-technology-c645a16e73e7

**Comment by indigoxela** [comment] 2020-12-30 14:12
Tests are passing now, an update hook has been added, too. So my PR is ready for more testing and review.

We should now figure out, where the native language name makes more sense and where the English name.

I think, on the admin language overview page (admin/config/regional/language) the combination `name (native)` would really make sense.
And in the form where the user selects his/her preferred language, the native name seems appropriate.

I'm looking forward for more feedback.

**Comment by klonos** [comment] 2020-12-31 01:06
> I think, on the admin language overview page (admin/config/regional/language) the combination `name (native)` (with parentheses) would really make sense.
>And in the form where the user selects his/her preferred language, the native name seems appropriate.

I agree 👍

**Comment by olafgrabienski** [comment] 2020-12-31 09:59
I also agree and would suggest to generalize the differentiation between 'admin' pages (display both names) and pages for visitors (display native name).

Admin examples:
- Installer
- Languages page (admin/config/regional/language)

Visitor examples:
- Language switcher block
- Language switcher links below content

Hm, forgot a 3rd category: editors. Examples:
- Language dropdown in node form
- Translation overview page of a node (node/NID/translate)

I'd prefer the display of both names here as well. An editor isn't necessarily able to recognize all native language names of a site.

Another reason for displaying both names where possible: language names are sorted by the native name. If the native name isn't visible, sort order seems to be arbitrary.

**Comment by indigoxela** [comment] 2020-12-31 10:30
@olafgrabienski Many thanks for your feedback. Totally makes sense.

> ...language names are sorted by the native name

Are you sure? Function language_list() returns the list sorted by 1. weight (as on admin/config/regional/language), 2. name. I'll have a closer look, though, when updating to the proposed name/native usage. There might be some inconsistency.

**Comment by olafgrabienski** [comment] 2020-12-31 10:47
> Are you sure? Function language_list() returns the list sorted by 1. weight (as on admin/config/regional/language), 2. name.

No, not at all! Wanted to say "name", not "native name". In the sandbox website, I've set all weights on `admin/config/regional/language` to `0`. As a result, the language switcher displays this order:
- English
- Français
- Deutsch
- Ελληνικά
- Italiano

Yep, looks to me as if it's not sorted by native name but by name. So, if the **name** isn't visible, sort order seems to be arbitrary.

There seems to be a default order on `admin/config/regional/language` btw, showing English first. (Don't remember the default order of the other languages.)

**Comment by indigoxela** [comment] 2020-12-31 12:15
**New / updated:**

- Use the native name for account's preferred language setting (user/X/edit)
- Use a combination of name and native name in node_form (e.g. node/add/page)
- Use a combination of name and native name on language overview (admin/config/regional/language)

**Tricky: node/XX/translate**

There's already parentheses in use - for the `(source)` of the translation. Adding another one might look awkward.

@olafgrabienski re the language link sort order: there really is some randomness - the links below node content are displayed in the order the translations have been added. This behavior isn't new.

Re the (switcher block) list sorted by name when languages have no weight set yet. I hesitate to change that (sort by native name if that's used as complete label), as I suspect this might cause even more confusion.

**Comment by olafgrabienski** [comment] 2020-12-31 16:05
> **Tricky: node/XX/translate**
> There's already parentheses in use - for the `(source)` of the translation. Adding another one might look awkward.

Agreed! And I'm fine with the current state (non-native name). Not seeing the native name on that page is mitigated by the node title which will usually be the same language as the native name would be.

Re sort order I agree as well. Let's have a closer look in a follow-up maybe.

**Comment by klonos** [comment] 2021-01-01 01:26
> Yep, looks to me as if it's not sorted by native name but by name. So, if the name isn't visible, sort order seems to be arbitrary.

Yeah, I've seen this happen in language selectors in other software, and I don't have any good answer. If you leave the sorting by the latin name of the language, then the sorting does indeed seem random. In that case, unless you are a developer, and able to figure out the correlation between the latin and the native name, and then mentally try to visualize the correct sorting, things seem odd and the UX is not great when trying to locate your language in a long list.

Perhaps `latin_name (native name)` makes sense then? 🤷 

> Re sort order I agree as well. Let's have a closer look in a follow-up maybe.

Agreed 👍 ...bay steps: lets fix all the easy things that make sense here, and then follow-up for the more complicated ones.

**Comment by indigoxela** [comment] 2021-01-01 15:11
Looks like we made some great progress here in short time. :smile:

Does anyone feel adventurous enough to set a milestone?

Note that this issue will need a change record, as function language_list() gets a third optional parameter `$native_names`.

**Comment by herbdool** [comment] 2021-01-04 05:26
I'd prefer this to be in a minor release and not bug fix given that it requires adding function parameters.

**Comment by indigoxela** [comment] 2021-01-04 08:13
> I'd prefer this to be in a minor release and not bug fix given that it requires adding function parameters.

I'm fine with 1.18, too. As long as it gets fixed. :wink: Feel free to change the milestone accordingly.

**Comment by indigoxela** [comment] 2021-01-09 09:02
If the change record, or more precisely the additional parameter in function language_list(), turns out to be a show-stopper here, I could adapt my PR to work without it.

But is it really a show-stopper? I'm not familiar with the procedures regarding changes in API functions.

**Comment by herbdool** [comment] 2021-01-10 18:30
I don't think it's a deal breaker so long as it's backwards compatible.

**Comment by herbdool** [comment] 2021-01-11 15:01
Another thing: do we know this will work when upgrading from d7? I'm guessing that most of the languages will be fine since they're being pulled in from the code, but might need to ensure that it uses the one set in the d7 database, in case the native name was customized (I guess that was in locale_source?) Or maybe that's a nice to have since right now users lose this functionality altogether.

**Comment by indigoxela** [comment] 2021-01-11 15:12
> do we know this will work when upgrading from d7

Yep, that will work. In D7 languages are stored in the "languages" db table, and there's a column "native". And even if a native name were missing, my PR always uses the name as fallback.

FTR: in Backdrop languages are in config (language.settings.json).

@herbdool but you bring up a good point. I should test that everything works smoothly, when upgrading from D7 (re language_update_1002(), which turns db data into config).

**Comment by indigoxela** [comment] 2021-01-24 10:43
I've rebased my PR and additionally checked an upgrade from D7 - works like a charm, native names are available as expected.

**Comment by herbdool** [comment] 2021-01-26 15:43
I've tested, including a D7 upgrade and reviewed the code. Looks good!

**Comment by klonos** [comment] 2021-01-26 20:41
Does anyone else feel that this help text leaves room for ambiguity/confusion?:

> Name of the language in the language being added.

Would something like this work better?:

- Change the label of the field to "Language name in English"
- Change the help text of the "Native language name" field to something like:
  > Language name as it is written in the language itself.

**Comment by indigoxela** [comment] 2021-01-27 06:53
> Does anyone else feel that this help text leaves room for ambiguity/confusion?

I agree, there's room for improvement. @klonos mind to open a follow-up for proper labels and help text?

**Comment by klonos** [comment] 2021-01-27 08:49
> mind to open a follow-up

No problem 👍

**Comment by indigoxela** [comment] 2021-01-27 09:34
> No problem +1 ...but the help text is being introduced with this PR here

I see. I have to admit, I blindly added it back when reverting the breaking change from early D8. I suppose, the other field's labels and help text might need some loving care, too.

Do you suggest to cover them in this issue here? We currently have the milestone set to 1.18.2, so there's probably no need to rush anyway.

**Comment by klonos** [comment] 2021-01-27 12:40
> Do you suggest to cover them in this issue here?

Yes please, if possible and we don't drag the decision around the proper/best string for too long. I see no point to add a string with this PR here, and then create a new issue to change that string 😅

**Comment by indigoxela** [comment] 2021-01-27 13:04
> Yes please, if possible and we don't drag the decision around the proper/best string for too long.

So, let's do it! :wink: Suggestions are welcome.

**Comment by indigoxela** [comment] 2021-01-27 13:21
A screenshot of the form in current state:
![language-form](https://user-images.githubusercontent.com/842066/105996673-f53c2b00-60aa-11eb-830f-cb5a1b0cf77b.png)

**Comment by olafgrabienski** [comment] 2021-01-27 13:53
"Language name in English" instead of "Language name" is good, in my opinion. And in this case, we don't need the description of the "Native language name".

Following two screenshots to see how it looks:

![screen-backdrop-language-names-farsi](https://user-images.githubusercontent.com/14188307/106000630-5534d080-60af-11eb-8cd6-7d601a4e7013.png)

---

![screen-backdrop-language-names-german](https://user-images.githubusercontent.com/14188307/106000636-5665fd80-60af-11eb-89d8-6b39dc642597.png)

**Comment by indigoxela** [comment] 2021-01-27 15:25
Let's give it a try, I updated the form items accordingly. Feedback is welcome.

**Comment by olafgrabienski** [comment] 2021-01-27 15:48
Hm, I don't find the PR anymore.

**Comment by indigoxela** [comment] 2021-01-27 16:05
> Hm, I don't find the PR anymore.

Sorry, I had the usual "discussion" with Zen.CI (random test failures) and tried to turn in off and on again. The tests are still running, but the Tugboat sandbox is ready again.

**Comment by olafgrabienski** [comment] 2021-01-27 16:11
Looks good, still works for me, and the different meaning of the labels is easy to understand.

**Comment by herbdool** [comment] 2021-02-11 16:19
Reviewed. I didn't realize it needed another review - just a couple text changes.

**Comment by quicksketch** [comment] 2021-03-04 03:21
I merged https://github.com/backdrop/backdrop/pull/3463 into 1.x and 1.18.x (as a UX improvement), per the current milestone assignment.

I made a tiny follow-up commit to add a `@since` docblock to `language_list()` in https://github.com/backdrop/backdrop/commit/091b7e06702575d15536126858192682cc4e0972

This issue is technically not closed because we need a changelog describing the change. @indigoxela would you be willing to write a description of how this changes calls to `language_list()` and where native names should be used?

**Comment by indigoxela** [comment] 2021-03-04 07:10
> ...would you be willing to write a description of how this changes calls to language_list().

I'm willing, but ... wording. :smile: Here's a rough suggestion, please adapt as required:


New optional parameter `$native_names` in function language_list().

Before:
```
$language_list = language_list(TRUE, TRUE);
```
After:
```
$language_list = language_list(TRUE, TRUE, TRUE);
```
Whether the labels in the select list should use the native name instead of the English language name. Only applies if the second parameter $option_list is TRUE.

Introduced in branch: 
1.18.x
Introduced in version: 
1.18.2
Impacts: 
Module developers
Related Github Issues:
https://github.com/backdrop/backdrop-issues/issues/4511

Should we also document the global $language property "native"? As far as I know, the language object has no documentation - as most globals in Backdrop. The property defaults to the same string as the "name".

**Comment by jenlampton** [comment] 2021-03-24 23:01
I've started on a change record, here: https://docs.backdropcms.org/change-records/new-optional-parameter-native_names-in-function-language_list

**Closed by jenlampton** 2021-03-24 23:01 UTC
Labels: needs - change record, status - fixed, status - has pull request, type - bug report
