### ISSUE TITLE
Visibility condition for node ID does not throw error when non-integer

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5262] opened 2021-09-29 18:10 UTC
**Description of the bug**

I just watched someone enter node/4 into the ID box, and was able to save the block, and then save the layout. 

**Steps To Reproduce**

To reproduce the behavior:
1. Create a new layout at node/%
2. Add a new block to the right sidebar
3. Add a visibility condition 
4. Enter `node/1` into the ID box (instead of 1)
5. Save the block configuration
6. Save the layout configuration
7. Configure the block again -- the Node ID visibility condition has been changed to `0`

**Expected behavior**

The visibility conditions box should validate (or be a number field) so that non-integer values cannot be entered.

**Additional information**

Add any other information that could help, such as:
- Backdrop CMS version: 1.20.0

**Comment by olafgrabienski** [comment] 2021-09-29 19:13
Sounds familiar ... I guess this is a duplicate of #2668 😃

**Comment by bugfolder** [comment] 2021-09-29 19:28
PR submitted. Since it affects EntityIDLayoutAccess, this also fixes the same issue with respect to User IDs.

**Closed** 2021-09-29 23:39 UTC
Labels: type - bug report, status - has pull request, pr - needs testing, pr - needs code review
