### ISSUE TITLE
CKEditor <a> text selection logic: select any subset at the end of the link text, start typing, only the first typed character is part of the link text

### ISSUE THREAD

**Issue by wimleers** [backdrop/backdrop-issues#1631] opened 2016-02-19 14:43 UTC
Reported at https://www.drupal.org/node/2671896.

For color, see that issue.

The essence of the problem is this:
- Start: `<a href="foobar">One Two Three</a>`
- Edit: Select Three, and type Four.
- Expected: `<a href="foobar">One Two Four</a>`
- Actual: `<a href="foobar">One Two F</a>our``

It's not yet clear whether this is a bug in CKEditor core, or whether it's a bug in the `drupallink` plugin that also exists in CKEditor's official `link` plugin that Drupal (and backdrop) simply inherited due to similar code. In any case, it can be reproduced at http://ckeditor.com/demo as well.

**Comment by BWPanda** [comment] 2019-09-06 17:22
I can confirm this. However, as per the linked Drupal issue, this is an upstream bug in the browser engine thing. As there's not much Backdrop can do about it (and likely won't need to do once its fixed upstream) I'll close this issue.

**Closed by BWPanda** 2019-09-06 17:22 UTC

**Comment by BWPanda** [comment] 2019-09-06 17:24
Marking as documentation since its not actually a bug in Backdrop, but good to leave for others to come across if they experience it.
