### ISSUE TITLE
Port and merge Administration Language in core (feature parity with D8).

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1381] opened 2015-11-29 08:28 UTC
Another module that's merged in D8 core: https://www.drupal.org/project/admin_language

Part of #378

Note: I run a quick check of the recently released Drupal 8.0.0, but even after enabling all language-related modules, I could not find where/how this feature was added in core. Anyone using this feature shade some light please?

**Comment by olafgrabienski** [comment] 2016-09-18 21:25
Hi @klonos , I just skimmed throug some multilingual Backdrop issues and saw your question from last year. I'm currently building a multilingual website with D8, so I'm able to answer:

- Create a Drupal 8 site, enable the relevant language and translation related modules.
- Choose or add languages, e.g.: Finnish (default), English, German.
- Enable the translation for a content type, e.g. Basic page.
- Enable the **detection method "Account administration pages"** (in addition to "URL" or an equivalent other method).
- Choose English as **"Administration pages language" on your user profile**.

At the moment, there is a confusing bug using this configuration not letting you edit translated content anymore (patch available: http://drupal.org/node/2189267#comment-11049517). Of course, there are some more issues with the D8 approach, but generally it works.

Btw, see also https://github.com/backdrop/backdrop-issues/issues/282#issuecomment-67721480 where @jenlampton suggests not to implement the D8 approach but the one of the D7 module.

Anyway, I'd be happy if there was whatever solution to choose an admin language different from the site's default language in Backdrop as well. Constellations where the admin doesn't understand the default site language might be rare, but if they occur you're literally lost.

**Comment by klonos** [comment] 2016-09-19 12:47
Thanx @olafgrabienski. It all makes sense now. I don't currently have any use for such functionality myself, but I'm all for D7/D8 feature parity for various reasons.

**Comment by jenlampton** [comment] 2016-09-19 18:13
Looks like this issue is a duplicate of https://github.com/backdrop/backdrop-issues/issues/282

**Closed by jenlampton** 2016-09-19 18:13 UTC
Labels: status - duplicate
