### ISSUE TITLE
CKEditor - custom blocks have no image upload option

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#2219] opened 2016-09-21 05:30 UTC
The option to browse for and upload an image has disappeared in release 1.5.

![add custom block image](https://cloud.githubusercontent.com/assets/10559274/18698779/bddda75e-7fc4-11e6-9664-9e768f61bc99.png)

---

PR https://github.com/backdrop/backdrop/pull/1594

**Comment by olafgrabienski** [comment] 2016-09-22 15:00
@Graham-72 - Couldn't reproduce the issue in a fresh 1.5 installation. I was able to browse for and upload an image using CKEditor in the "Bottom" region of the "Home page" layout (see screenshots below). Did you try that at another place? @all: Could another one try to reproduce the issue?

**Image in editor:**
![screen-backdrop-1-5-custom-block-ckeditor-image-1](https://cloud.githubusercontent.com/assets/14188307/18753376/649e8c22-80e5-11e6-96cb-4dc1bf0e254d.png)

**Edit image dialog:**
![screen-backdrop-1-5-custom-block-ckeditor-image-2](https://cloud.githubusercontent.com/assets/14188307/18753374/649d24fe-80e5-11e6-9583-db3fddfe56c1.png)

**Result:**
![screen-backdrop-1-5-custom-block-ckeditor-image-result](https://cloud.githubusercontent.com/assets/14188307/18753375/649dd188-80e5-11e6-9942-b211c370d81d.png)

**Comment by Graham-72** [comment] 2016-09-22 16:28
@olafgrabienski I have tried again and still cannot get the option to browse for an image, with what is a fresh install.

**Comment by olafgrabienski** [comment] 2016-09-22 21:29
@Graham-72 - Could you describe the exact steps to reproduce the bug? I'd like to givr it another try.

**Comment by Graham-72** [comment] 2016-09-23 05:19
@olafgrabienski, in admin try structure > content blocks > add content block, then in the 'block content' field menu click on the image icon to bring up the 'insert image' form.

**Comment by olafgrabienski** [comment] 2016-09-23 10:38
@Graham-72 - I agree: following **Structure > Custom blocks > Add custom block** there is no option to browse for an image via CKEditor.

In contrast, everything works fine, if you follow **Structure > Layouts > (Choose a layout) > Manage Blocks > (Choose a region) > Add Block > Add a custom block**.

Interesting side notes:
- Looking at the source code of my working example, I wonder why there is an absolute image URL: `<img alt="Dummy image" data-caption="Dummy image" data-file-id="1" height="933" src="http://backdrop.dev/files/inline-images/dummy-1400-933-grau.png" width="1400" />`. @jenlampton or anyone who knows Backdrop better than me: is an absolute URL the expected behaviour? If not, I'd write an issue.
- When I copy the (relative) image URL of my working example in the CKEditor "Edit image" dialog of the example that didn't work so far, it is accepted, and I'm able to use the saved block in the layouts. (I guess, this observation concerns https://github.com/backdrop/backdrop-issues/issues/2220.)

**Comment by Graham-72** [comment] 2016-09-23 11:42
> In contrast, everything works fine, if you follow ....

Interesting, I tried this previously and it would not work. I will try again soon.

**Comment by quicksketch** [comment] 2016-09-29 19:58
Thanks guys for identifying this so clearly! I think this is because we now have a property to disable uploads if they are not supported on that form. Looks like we've marked it supported in the Layout UI but not in the stand-alone blocks UI! We can fix this very easily. I'll take a stab at this today.

**Comment by quicksketch** [comment] 2016-09-30 01:56
PR filed at https://github.com/backdrop/backdrop/pull/1594 that should fix this.

**Comment by olafgrabienski** [comment] 2016-09-30 08:15
Nice PR, was able to upload an image following **Structure > Custom blocks > Add custom block**, using the image button of CKEditor. (I saw as well, that one test failed, no idea why.)

But I noticed another issue which I mentioned already as a side note in https://github.com/backdrop/backdrop-issues/issues/2219#issuecomment-249158882. The image URL is an absolute one:

`<img alt="Dummy image" data-file-id="1" height="200" src="http://1594.backdrop.backdrop.qa.backdropcms.org/files/inline-images/dummy_300.png" width="300">`

Is that intended behaviour?

**Comment by jenlampton** [comment] 2016-10-01 17:55
It sounds like it is. But we should open another issue to fix it.

**Comment by laryn** [comment] 2016-10-05 19:59
Came across this issue on a site I was working on and @serundeputy pointed me here. Tested @quicksketch 's patch and it solved it for me.

**Comment by quicksketch** [comment] 2016-10-06 18:43
Great, I've merged https://github.com/backdrop/backdrop/pull/1594 for 1.5.1. Thanks!

**Closed** 2016-10-06 18:43 UTC
Labels: pr - needs review, pr - reviewed & tested by the community, status - has pull request, type - bug report
