### ISSUE TITLE
[UX] Layouts by Parts (mini layouts, like mini panels)

### ISSUE THREAD

**Issue by Scoppettuolo** [backdrop/backdrop-issues#2119] opened 2016-09-02 01:53 UTC
I don´t know if this is possible, but I think that can be a good implementation, and make more easy construct a site without edit a layout.

The idea is that you can choice a layout for specific region, and not just predefinited layout with all regions.

Example...:

Region 1 - Header. - \* Choice the Layout Style.
Region 2 - Top. - \* Choice the Layout Style.
Region 3 - Content and SideBar. - \* Choice the Layout Style.
Region 4 - Bottom. - \* Choice the Layout Style.
Region 5 - Footer. - \* Choice the Layout Style.

...the Layouts can be for example just like now, but individualy for choice...: 1/1, 1/2, 1/3, 1/4, etc.

**Comment by mikemccaffrey** [comment] 2016-09-02 02:00
Perhaps the way to phrase this request is to "allow a layout to be inserted inside of another layout"?

Personally, I'm thinking this would be best tried as a contrib module before we discuss including it in core.

**Comment by quicksketch** [comment] 2016-09-02 03:43
> Perhaps the way to phrase this request is to "allow a layout to be inserted inside of another layout"?

We discussed something like this (eventually) in https://github.com/backdrop/backdrop-issues/issues/1886. You could have a single-column layout and then fill it with "Mini Layouts" that are preconfigured collections of blocks.

However, I think what's being requested here is something that would just allow you to build your own dynamic layout. There was a prototype module for Drupal that has the right idea that we could leverage for Backdrop: https://www.drupal.org/project/layout

We'd need to rename this layout_builder or something though, as we obviously already have a module named layout.

With our grid-system based layouts, this would be much easier to implement than previously, as the "Layout builder" would just assembled the needed markup, without any need to generate CSS.

Individual layout configurations right now do not have support for settings, so right now any attempt at doing this would need to make reusable dynamic layouts. You'd assemble one layout and then it would be shown as an option side-by-side the hard-coded ones. But I think this is possible already a contrib module. I think this would make a great contrib module but I'm not so certain about it being a core feature.

**Comment by Scoppettuolo** [comment] 2016-09-02 05:58
mikemccaffrey: Not, not is Layout in Layout.

quicksketch: That is more for the Blocks, and sound how Mini-Panels.

That I Try to Say...:

For Example...: If you Make a New layout Name "Portal" in this case, you need choice predefinited Template.
So...
- Choise "Moscone"
...but you Want, or Need, or just Like for the Header the Style in the part of the Content of "sutro" (...1/2...)., You Need Make a New Layout for This.
- For the Part of Top 1/1 Style is Ok.
- For the Content, and SideBar is Ok, Well, but Now you Want pas the SideBar to the Right., What? You Need Make again other Layout just for this.
- For the Bottom You Want Three Columns Like Geary, You Need add the Code to the Layout, but What Happen, if You Want Change Just this part in the Future? Again Change the Code.
- The Footer is Ok? Well, But if You Want to Change, for Example Style Taylor, or Rolph?

...is That That I Try to Say.

- No Layout in Layout.
- No Mini-Panels.
- Not Block Change, is Fine How is Now.

I Try to Say About the Templates of Layouts Himself., If Was by Parts, "Sutro", "Taylor", "Boxton", etc, Can Not Exist, and be Replaced Just by more Simple Templates Predefinited (...1/1, 1/2, 1/3, 1/4, etc...) for Choice in the Settings of Layout.

Sorry my English.

**Comment by klonos** [comment] 2016-09-03 11:30
@Scoppettuolo I too believe that what you are asking is to be able to define how various horizontal sections of your layout (header/main/footer) are divided vertically. For example:

- Header: you like to occupy the full width.
- Main, you want to either have 1-1-1 (two sidebars + main) or 1-2 (sidebar to the left) or 2-1  (sidebar to the right)
- Footer you want to split in 2 or 3 columns

The above is a simple example with only 3 horizontal sections, but you could have as many as you want.

The Drupal module that @quicksketch has linked to does all that and I think that it would be a great addition to out blocks and layouts system as a layout builder.

I particularly like the ability to define different layouts per device size (breakpoints) and would absolutely love it if you were able to customize breakpoints (edit the existing or add/remove).

**Comment by klonos** [comment] 2016-09-03 11:48
It would also be nice to be able to define the "grid size" per breakpoint. For example:

- a grid size of 3 would allow combinations of:
  1-1-1 (3 columns)
  1-2 (sidebar on the left)
  2-1 (sidebar on the right)
  3 (full width)
- a grid size of 3 would allow combinations of:
  1-1-1-1 (4 columns)
  2-2 (2 columns)
  1-2-1 (both left and right sidebars)
  1-3 (sidebar on the left)
  3-1 (sidebar on the right)
  4 (full width)
- ...

So, if I have this right, we currently have the notion of:

- layouts (configuration)
  - that have pre-defined regions depending on layout template (code) chosen
    - where we can place blocks.

If we were to implement a Layout Builder, we'd then have:

- layouts (configuration)
  - that would have breakpoints (each one with its own grid size)
    - where regions could be dragged around, resized on the grid, or even be hidden/removed
      - where blocks could then be placed

We'd basically give site builders the ability to create their own layout templates without having to code. That would be A-M-A-Z-I-N-G!!! ...*plus* each layout could have a different customized layout template *per breakpoint*. A-M-A-Z-I-N-G-E-R!!!

**Comment by klonos** [comment] 2016-09-03 11:53
When is 2.0 planned for again 😄 😞

**Comment by klonos** [comment] 2016-09-03 13:17
Related (implemented as a stater theme): https://www.drupal.org/project/layoutstudio

**Comment by Scoppettuolo** [comment] 2016-09-05 07:55
@klonos Is exactly that., A "grid system / Layout by parts".

**Comment by jenlampton** [comment] 2018-11-20 21:36
This issue may be a duplicate of https://github.com/backdrop/backdrop-issues/issues/2119 But

**Comment by stpaultim** [comment] 2019-06-28 00:02
How is this issue affected by the work being done here: 
https://github.com/backdrop/backdrop-issues/issues/3755

**Comment by klonos** [comment] 2019-08-23 23:39
With the exception of @jenlampton's last comment, I find this issue to have become redundant with #3755. I think that i'd be OK to close as either outdated, or duplicate.

Nevertheless, I would like allow some time for the person that initially raised this feature request to chime in. So @Scoppettuolo, can you please take a look at the layout template builder we are implementing in #3755, and provide some feedback as to whether that feature would address all/most of the needs you initially had that lead you to file this issue here?

**Comment by klonos** [comment] 2019-09-26 15:24
Lets close this one then. We have #3755 since Backdrop 1.14.0 + #4046 for a series of improvements for it.

**Closed by klonos** 2019-09-26 15:24 UTC
Labels: status - duplicate, status - outdated, type - feature request
