### ISSUE TITLE
[PS][D8]  BigPipe module add in backdrop core

### ISSUE THREAD

**Issue by domaingood** [backdrop/backdrop-issues#5216] opened 2021-09-13 16:05 UTC
**The BigPipe technique was invented at Facebook.**
How it works
During rendering, the personalized parts are turned into placeholders.
By default, Drupal 8 uses the Single Flush strategy (aka "traditional") for replacing the placeholders. i.e. we don't send a response until we've replaced all placeholders.
The BigPipe module introduces a new strategy, that allows us to flush the initial page first, and then stream the replacements for the placeholders.
This results in hugely improved front-end/perceived performance (watch the 40-second screencast above).
Features
Faster with zero configuration! BigPipe is able to make things faster automatically thanks to Drupal 8's improved render pipeline & render API, and in particular thanks to the cacheability metadata and auto-placeholdering.

Ensuring a smooth visual page load experience
Because BigPipe lazily loads certain parts of the page, it could result in a jarring page load experience. Whether it does depends on your theme and the location of the lazily loaded content: in the demonstration screencast above, there is no jarring experience at all because the streamed/lazily loaded blocks appear one after the other, appending to an otherwise empty space.
The BigPipe module is included in Drupal 8 core since Drupal 8.1

**Proposed solution**
Need to add in core backdrop CMS
https://www.drupal.org/docs/8/core/modules/big-pipe/overview

**Comment by klonos** [comment] 2021-09-13 16:38
@domaingood this is a duplicate of #1716. I've added your comment from above to that issue, so let's close this one here. Feel free to re-open #1716, but I don't think that much has changed since we decided not to do this, back in 2016 (I could be wrong about it though).

**Closed by klonos** 2021-09-13 16:38 UTC
Labels: type - feature request
