### ISSUE TITLE
Language switcher should retain URL query

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#5342] opened 2021-11-03 15:42 UTC
**Description of the bug**

When using URL query parameters (for example a view block with an exposed filter on a translated page) in combination with the language switcher, the results are not as convenient as they should be. The URL query parameters are all completely lost when clicking the language switch links. 

Instead, it seems to me that the query parameters should be passed along to the new page.

**Comment by laryn** [comment] 2021-11-03 16:00
Locally this seems to be working in the meantime:

```
/*
  * Implements hook_language_switch_links_alter().
  */
function custommodule_language_switch_links_alter(array &$links, $type, $path) {
  $query = backdrop_get_query_parameters();
  foreach ($links as $langcode => $link) {
    $links[$langcode]['query'] = $query;
  }
}
```

If people agree this is expected functionality I can make a PR for core.

**Comment by klonos** [comment] 2021-11-04 16:30
I agree that the expected behavior is for the parameters to be retained 👍🏼

**Comment by indigoxela** [comment] 2022-01-05 13:28
There may be situations, when the query parameters aren't so helpful (with pagers, when switching between languages gives less items...), but I also agree: they shouldn't get dropped when switching language.

Works for me. IMO the parameters are in more cases useful, than not useful.

**Comment by laryn** [comment] 2022-03-04 19:22
Milestone?

**Comment by laryn** [comment] 2022-05-09 18:05
@klonos Are you willing to put a milestone here?

**Comment by quicksketch** [comment] 2023-10-10 02:47
Thanks folks! Merged https://github.com/backdrop/backdrop/pull/3814 into 1.x and 1.26.x.

**Closed** 2023-10-10 02:46 UTC
Labels: status - has pull request, status - fixed
