### ISSUE TITLE
[UX] Decide what to call a `URL alias` and do it consistently

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1250] opened 2015-09-24 04:13 UTC
Here is the current state of things:
- On the node form, label for the vertical tab: `URL path settings`
- On the node form, inside the fieldset (vertical tab): `Generate automatic URL alias`
- On the content listing, the bulk operation: `Update node alias`
- On the path page (admin/config/search/path): `URL aliases` and `Add Alias` and `Filter Aliases`
-  On the patterns page: Mostly `Path` and `Paths` but also `Path patterns automatically alias new content...` WUT?
-  Bulk generate page: `URL aliases`
- Delete aliases page: `Aliases`, `aliases`, `paths`, `paths`, `paths`

Recommended:
- URL alias (to add the thing)
- URL alias pattern (to configure the thing)

**Comment by docwilmot** [comment] 2015-10-30 15:44
> Aliases, aliases, paths, paths, paths

:smile: 

But what are the options? I vote for sticking with "URL alias" everywhere, unless there are other good suggestions.

**Comment by sutibun** [comment] 2015-10-31 01:44
Just call it [URL](https://github.com/backdrop/backdrop-issues/issues/1286#issuecomment-149406423)

**Comment by klonos** [comment] 2015-10-31 13:43
> Just call it [URL](https://github.com/backdrop/backdrop-issues/issues/1286#issuecomment-149406423)

https://github.com/backdrop/backdrop-issues/issues/1286#issuecomment-145199564:

> We cannot simply call them "URLs" because the sentence "Create a URL" would not be 100% accurate since *technically* a URL is actually created no matter what (```/node/1```). It's just not... well, not friendly or pretty.

**Comment by jenlampton** [comment] 2016-01-14 21:45
> I vote for sticking with "URL alias"

I like this idea too!

**Comment by jenlampton** [comment] 2016-01-15 01:37
PR now passing tests, ready for a final review: https://github.com/backdrop/backdrop/issues/1205

**Comment by quicksketch** [comment] 2016-01-15 04:38
I posted some feedback to https://github.com/backdrop/backdrop/pull/1205. As we're just changing strings here, I wanted to make sure that we're doing them correctly. There are a number of places where we're not using sentence-casing as is our standard.

**Comment by jenlampton** [comment] 2016-01-15 04:52
I pushed a new PR that fixes all the case issues. 

One of the problems I fixed in the PR was an issue with two different UI's (one for path aliases and one for path patterns) both needing to use the label provided by `hook_path_info`. 

I had solved this by removing the noun from the label, and instead adding it in the two UIs, since each needed UI a different noun.

I thought this was the cleanest way to handle the problem without an API change, but we could change what's returned from `hook_path_info` instead, and require one thing have 'URL aliases' while the other has 'URL patterns'.  I just thought that seemed unnecessary since the path module knows the nouns, all we need to know from the other module is the **type** of noun.

**Comment by quicksketch** [comment] 2016-01-15 06:32
> I had solved this by removing the noun from the label, and instead adding the noun in the two UIs, since each needed UI a different noun. Example: Content URL aliases vs Content URL patterns.

Gotcha. Thanks for the explanation. The PR looks good! I've merged in https://github.com/backdrop/backdrop/pull/1205 into 1.x for 1.3.0. Thanks!!

**Comment by BWPanda** [comment] 2016-05-20 01:48
Reopening this as the bulk operation seems to have been forgotten and is still called 'Update node alias'...

**Comment by klonos** [comment] 2016-05-20 15:39
I think I got them all now. If not, there will be a part 3 :wink:

**Comment by quicksketch** [comment] 2016-05-31 19:57
PR at https://github.com/backdrop/backdrop/pull/1412 looks pretty good. We have a few legit failing tests though caused by the string changes.

**Comment by klonos** [comment] 2016-05-31 23:07
Disclaimer: first time I'm trying to delve into SimpleTesting (notice how I use D6 terminology? ...that's how far back I last [encountered the beast](https://www.drupal.org/simpletest-tutorial) ...and instantly gave up ...I was a Drupal newbie). So, used common sense + search and replace tools to figure out what needed changing for the failing tests to pass. Seems I've missed changing the string in https://github.com/backdrop/backdrop/blob/1.x/core/modules/path/path.admin.inc#L492

...new failing tests seem to be unrelated/random because they mention layouts and I'm 100% sure I haven't touched any of that. @Gormartsen is on to it.

**Comment by Gormartsen** [comment] 2016-05-31 23:22
backdrop/backdrop#1412 is clean. All tests passed
```
continuous-integration/travis-ci/pr — The Travis CI build passed
Details gitlc/test/php53/pr-1412 — 549 tests passed.
Details gitlc/test/php70/pr-1412 — 549 tests passed.
```
Looks like it was random fail again.

**Comment by klonos** [comment] 2016-05-31 23:39
...I guess we're all good then :smile:

**Comment by quicksketch** [comment] 2016-06-01 01:37
Merged https://github.com/backdrop/backdrop/pull/1412 for 1.4.3, thanks!

**Comment by klonos** [comment] 2016-06-03 22:43
...3rd round of changes coming up 😄

**Comment by klonos** [comment] 2016-06-04 11:44
PR ready for review 😄

**Comment by jenlampton** [comment] 2016-08-08 00:10
Nice work @klonos!  I just rebased your older PR (and updated another instance of 'URL path' we missed). Hopefully we'll get it in soon :)

**Comment by klonos** [comment] 2016-08-08 06:15
Hopefully 😄

**Comment by quicksketch** [comment] 2016-08-15 01:34
I think the PR at https://github.com/backdrop/backdrop/issues/1478 looks good but got into trying to rewrite the help text instead of just updating the terminology. I find the new text to be more confusing than it was previously. See comment at https://github.com/backdrop/backdrop/pull/1478/files#r74713411

Otherwise looks pretty good to me. "URL alias pattern" is quite a mouthful but at least it's accurate and consistent after these changes.

**Comment by jenlampton** [comment] 2016-08-15 01:59
Pushed a new PR that reverted the text change: https://github.com/backdrop/backdrop/pull/1478

**Comment by quicksketch** [comment] 2016-08-15 02:09
Merged https://github.com/backdrop/backdrop/pull/1478 for 1.5.0 and 1.4.4 thanks @jenlampton and @klonos!

**Closed by quicksketch** 2016-08-15 02:09 UTC
Labels: status - has pull request
