### ISSUE TITLE
Fail to install due to missing tablesort.inc file

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop/backdrop-issues#2693] opened 2017-05-15 18:35 UTC
### Steps to reproduce

git clone backdrop and install

### Actual behavior

got error

`Error: Call to undefined function tablesort_cell() in theme_table() (line 2200 of /.../core/includes/theme.inc).`

### Any additional version/system information

I found this error today and @Gormartsen, on gitter, pointed to this issue (https://github.com/backdrop/backdrop-issues/issues/485) and PR (https://github.com/backdrop/backdrop/pull/1836) as the origin of this issue here by adding the sorting of the status report table.

---

PR by @jlfranklin and @quicksketch: https://github.com/backdrop/backdrop/issues/1894
Follow-up PR: https://github.com/backdrop/backdrop/pull/2573

**Comment by Gormartsen** [comment] 2017-05-15 20:44
To fix this issue:
in file https://github.com/backdrop/backdrop/blob/1.x/core/includes/install.core.inc#L249
need to be added:
```
require_once BACKDROP_ROOT . '/core/includes/tablesort.inc’;
```

**Comment by Gormartsen** [comment] 2017-05-15 20:45
PS: update.php need to be tested as well.
I am not sure that issue is repetable on update stage.

**Comment by Gormartsen** [comment] 2017-05-15 20:46
https://github.com/backdrop/backdrop/pull/1892 contain fix for this issue

**Comment by robertgarrigos** [comment] 2017-05-15 20:47
I tried update.php with no problem, although there was nothing to update, so provably not good enough test

**Comment by quicksketch** [comment] 2017-05-15 20:47
Thanks, this was also noted in https://github.com/backdrop/backdrop-issues/issues/2683. You're right it's caused by the redesign of the status report. I actually prefer we solve these two problems separately, so let's keep this issue open to track this problem.

**Comment by quicksketch** [comment] 2017-05-15 20:48
And while including tablesort.inc in the installer is one way to fix this problem, I would like to see if we could make it so that theme_table() doesn't depend on tablesort in the first place unless the table actually uses it.

**Comment by quicksketch** [comment] 2017-05-15 21:26
After looking at `theme_table()` a bit, I don't think my suggestion is easily implemented. So let's just go with including the file as in @jlfranklin's PR in https://github.com/backdrop/backdrop/pull/1892. I'll split that out and make it stand-alone.

**Comment by jenlampton** [comment] 2017-05-15 21:28
I'm trying to help test this, but I can't get the installer to fail. I tried changing permissions on files or settings.php, but Backdrop fixes them for me. I tried setting the PHP memory limit too low, but I get an out of memory error before I get a requirements error.

**Comment by quicksketch** [comment] 2017-05-15 21:36
I pulled out the fix from the previous PR to fix this problem specifically. PR is at https://github.com/backdrop/backdrop/issues/1894.

I was able to reproduce the problem by doing `chmod 600 settings.php`. The installer shouldn't attempt to "fix" permissions on settings.php. I believe we removed all of that magic chmod'ing from Backdrop's installer.

**Comment by jenlampton** [comment] 2017-05-15 21:44
> I was able to reproduce the problem by doing `chmod 600 settings.php`.

Backdrop installs cleanly for me with `chmod 600 settings.php`. Permissions remain unchanged, but site still happily installed.

**Comment by jenlampton** [comment] 2017-05-15 21:59
The PR in https://github.com/backdrop/backdrop/pull/1894 fixes the problem for me. I now see the table on the installer when there are requirements problems instead of the error.

**Comment by jenlampton** [comment] 2017-05-15 22:04
I also tested the available updates page, project installer, and automatic updater via the module update process. All worked seamlessly.

**Comment by quicksketch** [comment] 2017-05-15 22:17
I've merged in https://github.com/backdrop/backdrop/pull/1894 into 1.x only. The status report redesign (https://github.com/backdrop/backdrop-issues/issues/485) was the source of this regression, so this shouldn't be needed in 1.6.x.

**Comment by robertgarrigos** [comment] 2017-05-16 15:43
Why I fetch core 1.x and still have this error?

**Comment by jenlampton** [comment] 2017-05-16 17:17
@robertgarrigos did you fetch core or pull core?  You'll need to pull to get the latest updates.

**Comment by robertgarrigos** [comment] 2017-05-17 01:30
thanks @jenlampton I had an error in my .git/config

**Comment by docwilmot** [comment] 2019-02-14 17:54
This is back https://forum.backdropcms.org/forum/cannot-run-updatephp-after-upgrading-webform-1x-4191

**Comment by quicksketch** [comment] 2019-04-11 22:22
I've confirmed this problem is solved for install.php but not update.php. I've filed a PR at https://github.com/backdrop/backdrop/pull/2573 that fixes the reporting of errors on update.php.

To reproduce this I caused a fake error by modifying system_requirements() and adding a new `$required_extensions` value like `'foo'` that will never exist and always throw a status report error. Though the display of the requirements table is still terrible, at least it doesn't throw a fatal error:

![image](https://user-images.githubusercontent.com/100206/55996876-96a38400-5c6d-11e9-92c4-34f280194460.png)

**Comment by pnmgman2** [comment] 2019-04-12 14:38
Thanks Quicksketch! 
I implemented your fix and update.php is working on my site. It showed a dependency error for Webform layout:
![image](https://user-images.githubusercontent.com/3721737/56044792-30664200-5cfd-11e9-9f97-96707c6fe129.png)
I removed the module Webform layout as I wasn't using it, and all is fine.

On a side note, I don't remember where Webform Layout came from. . . did I port if for myself from D7? Was it included with BD Webform?

Anyway, the error message is interesting, but I don't know if it is relevant to this issue, or another. The error states it is incompatible with **version 4.19.2** instead of **1.x-4.19.2** - this is what I believe was causing the dependency error when running update.php.

**Comment by laryn** [comment] 2019-08-09 17:23
WFM

**Comment by klonos** [comment] 2019-08-10 02:05
I did not test this, but the code change is simple, and it makes sense.

**Comment by quicksketch** [comment] 2019-08-18 22:07
Thanks! Merged in the follow-up at https://github.com/backdrop/backdrop/pull/2573.

**Closed by quicksketch** 2019-08-18 22:07 UTC
Labels: status - has pull request, status - fixed
