### ISSUE TITLE
[UX] Auto-fill the site email address and clarify what site email vs admin email are used for.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2362] opened 2016-11-26 21:49 UTC
This is a counter-issue to #2117 where instead of removing the site email address field I suggest auto-filing it with a default email address from the domain the site is being installed on. Pre-filling the site email address with something like `no-reply@%auto-detected-domain%` will address the issue where people don't bother reading the help text by giving them a hint as to what form of email is expected (still giving them the option to personalize the part before the `@domain`).

The issue here is that people misinterpret the use of the site email and enter either a personal email address or one that is hosted in an external domain. Trying to send notification emails FROM this email address will either fail or result to mail flagged as spam. So, I suggest to clarify things a bit more in the existing help text.

Lets also add help to the site admin email address to state that this email will be used to *receive* notifications about site updates (and possibly other site issues in the future).

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1653

**Comment by klonos** [comment] 2016-11-26 22:02
I will explore making the `@%auto-detected-domain%` part of the site email address a filed suffix instead of having it be editable. This will make it so that there is a default `no-reply` part added to the email address that users can still customize, while at the same time ensuring that the end email will be from the domain Backdrop is being installed on.

**Comment by jenlampton** [comment] 2016-11-26 22:36
> Lets also add help to the site admin email address to state that this email will be used to receive notifications about site updates (and possibly other site issues in the future).

This is not the case in Backdrop. As stated previously, no emails will be sent to this email address about anything of the sort.

**Comment by jenlampton** [comment] 2016-11-26 22:38
If we remove that part of this issue, it becomes a duplicate of https://github.com/backdrop/backdrop-issues/issues/2117.  Can we please close this issue so that we don't duplicate the conversation? (And please update your PR to point to that issue instead!)

**Closed by jenlampton** 2016-11-26 22:38 UTC
Labels: status - has pull request, pr - needs work

**Comment by jenlampton** [comment] 2016-11-26 22:42
In terms of process @klonos, we don't need a separate issue for each PR. The point of separate issues is to have separate conversations about separate tasks. In this case we have competing PRs that should point to the same issue, so that e can have a single conversation, and review different approaches with code. We don't want to split the conversation unless the tasks are unrelated, for example, 1) clean up the install form vs 2) dream up reasons to email administrator-type people.

**Comment by klonos** [comment] 2016-11-26 22:44
Sure @jenlampton. It's just that the title of #2117 is "**remove** the site email from the installer" while my PR keeps it there. That's why I filed a separate issue.

**Comment by jenlampton** [comment] 2016-11-26 22:56
How's this? https://github.com/backdrop/backdrop-issues/issues/2117

**Comment by quicksketch** [comment] 2017-01-01 22:43
As we discussed further in #2117, the premise of *this* issue is incorrect.

> Lets also add help to the site admin email address to state that this email will be used to receive notifications about site updates (and possibly other site issues in the future).

This is the oh-so-common misconception about what the "site_mail" setting is for. It's not a TO address. No email should ever be sent to it. It's the site FROM address. And in order to work with almost every mail system out there, the site mail must be the same as the domain of the site. Otherwise it will get flagged as spam.

As such, I think we should continue with #2117 to remove this setting from the installer, because it's not a question that people expect to be asked.

@jenlampton made a new issue for making a site-wide TO address at https://github.com/backdrop/backdrop-issues/issues/2365. If added, that might make a reasonable question to ask in the installer again.
