### ISSUE TITLE
Why aren't we using 4 byte UTF-8 database tables out of the box?

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2783] opened 2017-08-06 02:50 UTC
## Describe your issue or idea

I have just installed a fresh copy of Backdrop, only to be greeted with an error notification in the admin bar. Turned out that this was the convert db to UTF-8 thing. Why aren't we using that by default again? Why does one have to install and then convert on a fresh installation (instead of installing and converting during the installation process I mean)?

### Steps to reproduce (if reporting a bug)

Just install a vanilla Backdrop instance.

### Actual behavior (if reporting a bug)

There's an error badge in the admin bar right after installation that leads you to the site status page where you are given the option to convert the tables to use 4 byte UTF-8.

### Expected behavior (if reporting a bug)

Either install using 4 byte UTF-8 by default if the system supports it, or expose that as an option in the database setup step of the installer. That way, we'd save the user an additional step after installation.

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2130

**Comment by quicksketch** [comment] 2017-08-06 19:52
What should happen is the following:

- If installing Backdrop and the settings.php file is in the default state, Backdrop will ask for your database credentials during the install. When Backdrop updates the settings.php file to save the values, it should automatically detect 4-byte character support and enable it if available.

- If installing Backdrop and the settings.php has a database connection string specified, Backdrop assumes that connection is the final configuration. It skips any rewriting of the database connection information, including 4-byte character support.

If the first scenario is not working properly we need to fix it. It's likely you installed with the second scenario. In which case perhaps we should evaluate if we want to change how that behavior works.

**Comment by klonos** [comment] 2017-08-06 22:19
...this was a fresh `git clone` and I have provided the db details and credentials via the web installer. So definitely 1st scenario ...unless I'm missing something. I'll repeat with another fresh installation to verify.

**Comment by BWPanda** [comment] 2018-01-19 03:19
Marked as a bug report based on @quicksketch's comment:

    If the first scenario is not working properly we need to fix it.

**Comment by quicksketch** [comment] 2018-04-14 00:39
I've run across this now too as well. It looks like the problem is quite simple: Backdrop actually detects and installs with UTF8MB4 support correctly, but then it forgets to set the flag indicating that support is enabled. Thus it shows the notification badge and asks you to "update" your tables, even though they all already support UTF8MB4.

**Comment by quicksketch** [comment] 2018-04-18 22:28
Merged https://github.com/backdrop/backdrop/pull/2130 into 1.x and 1.9.x. This will be in 1.9.4.

**Closed** 2018-04-18 22:27 UTC
Labels: pr - needs review, status - has pull request, type - bug report

**Comment by klonos** [comment] 2019-06-23 23:07
FTR, this may have been because of #3858 ...in which case, good catch @oadaeh 👍
