### ISSUE TITLE
Visiting /admin/config/development/configuration/sync/diff gives error

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5559] opened 2022-03-20 19:11 UTC
## Description of the bug

Visiting the page  at `admin/config/development/configuration/sync/diff` results in an error.

## Steps To Reproduce

To reproduce the behavior:
1. Go to `admin/config/development/configuration/sync/diff`2, which is here in the admin menu:

![diff](https://user-images.githubusercontent.com/29214084/159178343-c435065a-da75-4f81-ba3b-fd9ca549f943.jpg)

## Actual behavior

![error](https://user-images.githubusercontent.com/29214084/159178307-114b2efa-b7f1-4d76-ba86-31462b822d60.jpg)

## Expected behavior

It's not fully clear what was intended. The path is declared with no page arguments:

```
  $items['admin/config/development/configuration/sync/diff'] = array(
    'title' => 'Configuration diff',
    'page callback' => 'config_diff_page',
    'access arguments' => array('synchronize configuration'),
    'file' => 'config.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
```

But the function `config_diff_page()` is expecting the name of a single config file:

```
/**
 * Shows diff of specified configuration file.
 *
 * @param string $config_file
 *   The name of the configuration file.
 *
 * @return string
 *   Table showing a two-way diff between the active and staged configuration.
 */
function config_diff_page($config_file) {
  $diff = config_diff($config_file);
...
```

Perhaps this path was never intended to be exposed without additional arguments? The path `admin/config/development/configuration/sync/diff/%` is used to create the dialog that displays a diff for an individual file when you click "View differences" on the main Synchronize page (or it opens a standalone page, if you right-click and open in a new tab).

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.x branch as of 2022-03-20.

**Comment by indigoxela** [comment] 2022-03-21 07:01
> Visiting the page at admin/config/development/configuration/sync/diff results in an error.

Confirmed. How could we miss that?

> Perhaps this path was never intended to be exposed without additional arguments?

That sounds plausible.

**Comment by indigoxela** [comment] 2022-03-21 07:52
A possible solution (if our guess, that it shouldn't have been a tab anyway) could be to set that page to `'type' => MENU_CALLBACK,`.

**Comment by bugfolder** [comment] 2022-03-24 22:30
That removes the problematic menu item, but it wipes out the breadcrumb trail for the standalone diff page:

as `MENU_LOCAL_TASK`:

![menu_local_task](https://user-images.githubusercontent.com/29214084/160020519-5866d56e-3db8-4d32-b19d-cb9af6a9757b.jpg)

as `MENU_CALLBACK`:

![menu_callback](https://user-images.githubusercontent.com/29214084/160020542-f7de7b3d-2b89-45b7-9fb6-145552b66bf0.jpg)

Maybe a gentler solution will be to keep that menu item as is, but if the argument is missing, redirect to the main synchronize page.

**Comment by indigoxela** [comment] 2022-03-25 11:47
> That removes the problematic menu item, but it wipes out the breadcrumb trail for the standalone diff page

Oh, I see.

The current workaround is an improvement, but... the menu item is still there, which doesn't seem right.

If the page always needs an argument, shouldn't we be able to fix it with `'page arguments' => array(6),` and a placeholder in hook_menu?
I didn't try that yet, but I feel like there must be a more elegant solution.

**Comment by indigoxela** [comment] 2022-03-25 12:08
> shouldn't we be able to fix it with 'page arguments' => array(6), and a placeholder ...

That seems to do the trick:

```
  $items['admin/config/development/configuration/sync/diff/%'] = array(
    'title' => 'Configuration diff',
    'page callback' => 'config_diff_page',
    'access arguments' => array('synchronize configuration'),
    'page arguments' => array(6),
    'file' => 'config.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
```
The pointless menu item is gone, the dialog works, and the standalone page has the right breadcrumb.

@bugfolder want to give it a try and do some additional testing? Personally, I'm not using config sync often, so I might have missed something.

**Comment by indigoxela** [comment] 2022-03-26 08:56
> Perhaps this is what was originally intended.

I think so, yes. Works for me! (But I'm now too involved to do the review.)

**Comment by BWPanda** [comment] 2022-06-02 12:15
Wow, I just noticed this bug myself then found this issue for it. How did we miss that indeed... Especially since the code in question was committed 9 years ago! Surely there must have been a more recent, unrelated change in Backdrop that allowed this menu item to be displayed. It can't have been there all this time...

In any case, PR looks good to me and does the trick.

**Comment by quicksketch** [comment] 2022-06-21 00:18
Thanks folks! Great solution here. I've merged https://github.com/backdrop/backdrop/pull/4019 into 1.x and 1.22.x. Thanks!

**Closed** 2022-06-21 00:17 UTC
Labels: type - bug report, status - has pull request, pr - ready to be committed, pr - works for me
