### ISSUE TITLE
Fix install.sh with PHP 8.1 causes deprecation notices

### ISSUE THREAD

**Issue by Wylbur** [backdrop/backdrop-issues#6087] opened 2023-04-29 18:17 UTC
## Description of the bug

When installing a new Backdrop CMS site using PHP 8.1, the install.sh generates Deprecated Notices:

```
PHP Deprecated:  urldecode(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/docroot/core/scripts/install.sh on line 134
PHP Deprecated:  urldecode(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/docroot/core/scripts/install.sh on line 134
PHP Deprecated:  urldecode(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/docroot/core/scripts/install.sh on line 134
```

## Steps To Reproduce

To reproduce the behavior:
1. Install a new instance of a Backdrop CMS site.  I used the Docksal Boilerplate template that runs this command:
```
bee.php si \--db-name=default --db-user=user \
	  --db-host=db --db-pass=user --url="${VIRTUAL_HOST}" \
		--site-name='My Backdrop Site' \
		--username="admin" --password="admin" --auto
```
3. The script /core/scripts/install.sh calls `array_map` which passes empty values to the `urldecode` function.   

## Actual behavior

Deprecation notice is generated, but the script continues executing, and finishes the site install.

## Expected behavior

No notices should be generated.  

## Additional information

On line 125 the empty value that trigger the error are added to the array.  Moving these lines below will rectify this error, and only add null values.

**Comment by Wylbur** [comment] 2023-04-29 18:34
This pull request replaces the function that creates and assigns null values for all variables required for the db connection in the settings file.  
https://github.com/backdrop/backdrop/pull/4415

**Comment by argiepiano** [comment] 2023-04-29 21:50
Thanks, @Wylbur. Please see suggested change in the PR.

**Comment by Wylbur** [comment] 2023-05-01 17:25
The pull request has been updated, thanks for the suggesting @argiepiano !

**Comment by klonos** [comment] 2023-05-05 22:41
Well, if this gets into 1.24.3, it will also be in 1.25.0, but I get the addition of the minor milestone as well. ...in any case, if we don't make it now, it will be in 1.25.1 I guess 😉 

Code looks good to me 👍🏼

**Comment by stpaultim** [comment] 2023-05-06 00:29
I'm confused when I see "RTBC" and "Needs Testing". Does this still need testing?

Does testing require Docksal?

@Wylbur ??

**Comment by klonos** [comment] 2023-05-06 01:22
FTR, I have a script that runs the following:

```
lando bee si --db-name=backdrop --db-user=root --db-pass=backdrop --password=password --site-name=${ISSUE} --auto
```

This command installs the site w/o any errors in php 8.1, but I am not using the `--url` parameter at all. Running `lando bee help si` doesn't mention that parameter at all either, and since the cause for this issue is `urldecode ()`, I'm assuming that it _may_ have something to do with that. So can someone please explain what is the purpose of this parameter?

**Closed** 2023-06-06 19:29 UTC
Labels: status - has pull request, status - fixed

**Comment by quicksketch** [comment] 2023-06-06 19:31
I tested an install and didn't see any regressions. I merged https://github.com/backdrop/backdrop/pull/4415 into 1.x and 1.25.x for 1.25.1. Thanks @Wylbur, @klonos, and @kiamlaluno for the work on this!
