### ISSUE TITLE
[UX] Admin content listing does not remember last exposed filter selection

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#634] opened 2015-01-21 09:03 UTC
In Drupal when you navigated to the admin page, made a selection (say, for node type) navigated away, and then returned later, Drupal would remember your selection.  Backdrop forgets.  Let's fix this.

The default admin/content view needs to have the "Remember the last selection" option added for each exposed filter for the role "Authenticated".

**Comment by quicksketch** [comment] 2015-01-21 09:51
> In Drupal when you navigated to the admin page, made a selection (say, for node type) navigated away, and then returned later, Drupal would remember your selection. Backdrop forgets.

Backdrop remembers your last suggestion as long as you use the Back button, but doesn't remember if you revisit that page later. It also should remember your selection if you use the edit, delete, or bulk operations on the page.

Personally, I think that is the preferred behavior. I don't want the admin listing to remember my listing the last time I tried to find a piece of content, because I'm usually looking for a different piece of content the next time I visit that page.

**Comment by docwilmot** [comment] 2015-01-21 16:54
+1 for not remembering.

**Comment by jenlampton** [comment] 2015-01-22 00:22
Well I just had a UX fail last night with it not remembering...  Made me miss Drupal 7. I'll leave this open for further discussion and we can see how others feel (and myself, too) after more use.

**Comment by Dinornis** [comment] 2017-01-08 03:24
Drupal 6 does remember and sometimes I find this useful, but most of the time I click on the reset filter button. Maybe a check box `Remember filter setting` would make all camps happy.  Not sure about the priority for such feature versus the 100s of other open issues.

**Comment by jenlampton** [comment] 2017-01-08 04:00
There's already a setting in views, we just forgot to set it when we converted the admin listing to a view.

**Comment by Dinornis** [comment] 2017-01-08 18:26
So, no matter what you change the default for the `Remember the last selection` option to it will satisfy only some users.  Seems like the only way to address this would be to include a `Remember ...` check box on the `Admin Content` page and let the user decide.
OR
Enable the `Remember the last selection` option for each Filter Criteria as Jen suggested, but also include the `Reset` button.

**Comment by BWPanda** [comment] 2020-02-14 10:42
I just noticed this in a D7 site (after reading through this issue a few days ago, so it stood out to me), and I don't like that it remembers. I have to keep clicking 'Reset' to then filter by what I want. So I vote for no remembering.

**Comment by jenlampton** [comment] 2020-09-24 00:15
Okay, closing this issue as wontfix since most people prefer re-entering search terms with every visit to the content listing. I've since trained myself never to leave the content listing (yay, more tabs) to get around this problem with Backdrop :)

**Comment by stpaultim** [comment] 2021-03-16 03:38
A friend just pinged me with this example:

> I have a usability issue regarding backdrop. Suppose that I want to delete all nodes of a certain type. I go to “Manage content”, filter on the node type, select all rows, and click Delete. But this only deletes the first 50 nodes of that type.
> 
> What I expect is that the filter will still be in effect, so I can once again select all rows and click Delete.
> 
> What actually happens is that the filter was cleared after clicking delete, and I accidentally deleted a whole bunch of content of the wrong type (and had to restore from backup).
> 
> It was my fault for not paying attention. But I think that Drupal does not clear the filter in this situation.

I remembered that in fact, I was often frustrated by the fact that Drupal would remember my last search when I didn't want it to and that I was pleased to find that Backdrop doesn't do that. But, I heard this story and thought - in this use case I can why a user would expect that. 

I found this issue and this comment from @quicksketch.

> Backdrop remembers your last suggestion as long as you use the Back button, but doesn't remember if you revisit that page later through the navigation. It also remembers your selection if you use the edit/delete links or bulk operations on the page.

I tested the scenario mentioned by my friend because that sounds like the scenario that @quicksketch is referring to, but in that case Backdrop did NOT remember the search. 

Personally, I like the scenario mentioned by @quicksketch as the best option. But, I don't think that is working. ALSO - I tried checking the "Remember the last selection" option for the "Content Type" filter on the default manage content view and that does not seem to work. 

So, this issue that originally seemed like a simple UI discussion now seems like it might in fact be a bug?

**Comment by jenlampton** [comment] 2021-03-16 04:06
@stpaultim I think the views "remember the last selection" option not working needs a separate issue. That's definitely a bug. It worked sometime in the past because I've been using that on some of my sites where I expected the D7 behavior and was frustrated when I didn't have it. (I believe I found the setting in the exposed form settings area -- not with the filters)

The other issue, the one with the filter being reset when bulk operations are used is currently "works as designed" since that form submit action simply returns people to the default content listing -- but I agree it's not an ideal design. 

Right now the only way to get back to the listing with the filters preserved is via the back button, or by using one of the links in the drop-buttons, as @quicksketch described previously. I think it would be reasonable to retain the filters when bulk operations are used, too. 

I would prefer that be done in a separate issue specifically describing the problem and desired effect as it relates to views bulk operations globally, rather than focusing on this one `admin/content` view.

**Comment by stpaultim** [comment] 2021-03-16 05:53
@jenlampton - Thanks. I marked this as a bug mostly because I read the comment by @quicksketch to say that Backdrop currently should remember your settings if you are using bulk operations.

> It also remembers your selection if you use the edit/delete links or bulk operations on the page.

Maybe that second part was a mistake, because that does not appear to be the case and your comments suggest that behavior would be desirable, but is not current expected. As long as we know that this does not work, then it is not a bug but a feature request and I agree belongs in it's own ticket. 

Regarding the "remember last selection" I agree that is a different issue. I'm not yet prepared to open a ticket, because that portion might still be user error on my part. This view has multiple filters and I might not have been setting it correctly. I try to test some more when I have time.

**Closed** 2021-03-16 05:55 UTC
Labels: type - bug report

**Comment by jenlampton** [comment] 2021-03-16 05:59
For the record, I still think you're right that these are both bugs (and not feature requests) :)

> or bulk operations

Ah, I missed this bit.

**Comment by stpaultim** [comment] 2021-03-16 06:12
Well, I opened one new ticket (https://github.com/backdrop/backdrop-issues/issues/5001), because that issue is more clear to me. But I think I would need to do more testing on the "remember last selection" option before I open a ticket.

**Comment by oriolroger** [comment] 2023-06-13 15:22
I had the same problem. When deleting some nodes from the Admin content view, I was expecting that the selected content type was still filtered after deleting, but is not, once you delete a node and are redirected to the Admin content view, all filters are reset, and is quite dangerous in case you don't realize that and continue deleting stuff.

To avoid this, go to the Administer content view (/admin/structure/views/view/node_admin_content/configure/page), and in the Page display, click on the filter "Content: Type (exposed)" and enable the option "Remember the last selection". That will remember the filter selected after submitting a bulk operation.

Hope this helps.
