### ISSUE TITLE
Layouts: The page title configure button is broken in latest 1.x

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2170] opened 2016-09-13 11:46 UTC
I just downloaded a fresh copy of 1.x to test some things locally, but when I click the newly-added "Configure" button on the title "pseudo-region, nothing happens(??). The respective buttons for all other regions seem to work fine though. Can someone please confirm?

**Comment by jenlampton** [comment] 2016-09-15 02:57
I'm also unable to reproduce this issue. The only thing that's a bit funny is that when you hit "Save configuration" the text in the menu doesn't update to show the changes you just made (until you hit save).  Did that ever work? Maybe not...

**Comment by quicksketch** [comment] 2016-09-15 06:15
I'm going to close this as unreproducible. Though I would hate see this cropping up on launch day (tomorrow!)

Please let us know if you're still seeing this on the latest 1.x @klonos.

**Closed by quicksketch** 2016-09-15 06:15 UTC
Labels: type - bug report
