### ISSUE TITLE
Fix default classes in header region for Flexible Layouts

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#4066] opened 2019-09-17 20:18 UTC
**Description of the bug**
The display of the header block is pretty horrible if you move it into a flexible layout template.

**Steps To Reproduce**
To reproduce the behavior:
1. Create a flexible layout template.
2. Assign the new template to an existing layout.
3. Move the "Header block" into the flexible template's "Header region"
4. Save

**Actual behavior**
There's a big mess at the top of the page.

**Expected behavior**
It should look at least similar/respectable since we haven't changed the theme.

---------
~~PR by @stpaultim = https://github.com/backdrop/backdrop/pull/2887~~
PR by @stpaultim = https://github.com/backdrop/backdrop/pull/2912

**Comment by stpaultim** [comment] 2019-09-17 20:59
Here is a screen shot of what @laryn is describing. 

![Home___Test](https://user-images.githubusercontent.com/3144571/65078693-2a872380-d963-11e9-85d4-1a75e53cc928.png)

The problem is the lack of '.l-header' class on the header row. If you add that class to the row, it looks like this.

![Home___Test](https://user-images.githubusercontent.com/3144571/65078843-7cc84480-d963-11e9-8cd9-268025af2ddb.png)

If set the header row "Row width behavior" to "Maximum width" AND add a container class to the header block, it looks like this.

![Home___Test](https://user-images.githubusercontent.com/3144571/65078959-cc0e7500-d963-11e9-875d-0fb73ae07f4c.png)

**Comment by olafgrabienski** [comment] 2019-09-17 21:49
Good catch! The header looks good when the *Header-Block* is part of the *Header* region and you assign the `container` class to the block.

(Same for the *Primary navigation* block.)

**Comment by stpaultim** [comment] 2019-09-18 09:11
I have a proposed fix. Will try to create PR tomorrow.

**Comment by stpaultim** [comment] 2019-09-19 05:29
The problem is that almost every other template has a l-header class in the header and l-footer in the footer. Our flexible layouts have neither. My PR adds a class to every row that is .l-[element]. This works great for headers and footers, but I don't know if the .l-div or .l-section classes that this will also create are necessary. 

This PR might break any site that already has flexible layouts and has created custom css based upon it?

- - - - - - - - - 

If you take a fresh 1.14 site and create a new flexible layout without ANY change. Then, change the homepage to use your new flexible layout and put the following blocks in the following regions:

HEADER
- Header block
- Primary navigation
CONTENT
- Welcome to __________
- Promoted content
FOOTER
- Powered by Backdrop

This is what you get.


![Home___Flexible](https://user-images.githubusercontent.com/3144571/65215386-f1d66f80-da72-11e9-8027-07578fa163ef.png)

In the test sandbox with this PR you do the same thing and you get:

![Home___PR_2887_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/65215545-7f19c400-da73-11e9-8ab8-793bde4dc1bb.png)

**Comment by olafgrabienski** [comment] 2019-09-19 10:19
@stpaultim I've had a look at the sandbox site, and it looks good. There's one issue, though, regarding the Hero block: Out of the box, in the Boxton layout, the Hero is full-width because it's above `l-wrapper-inner` in the `l-top` region which has no `container` class. In your *Minneapolis* template, the Hero is in `Content`which has a `container` class.

I've simulated the Boxton behavior in *Minneapolis* (created a `Top` region without row classes) and put another Hero block in this region. Here's the result:

![screen-backdrop-pr-2887-hero-top](https://user-images.githubusercontent.com/14188307/65235434-e1f07700-dad6-11e9-9de8-19e67f549a74.png)

Possible fix: provide a `Top` region (without `container` class) for every new Flexible layout template, so that every Flexible layout would start with four regions.

**Comment by stpaultim** [comment] 2019-09-19 20:24
@olafgrabienski - I tested moving the front page into other existing core layout templates and the hero block breaks in many of them as well. The footer and header generally work across layout templates, but the hero does not.

I would support making the hero block compatible with a default flexible layout, but I don't think it's as critical as the header and footer.

**Comment by olafgrabienski** [comment] 2019-09-20 08:10
> I would support making the hero block compatible with a default flexible layout, but I don't think it's as critical as the header and footer.

Agreed, the hero block doesn't look really broken. We can make a separate issue for it anytime.

**Comment by olafgrabienski** [comment] 2019-09-20 08:11
I've added "works for me" but would be happy for another pair of eyes.

**Comment by klonos** [comment] 2019-09-20 19:38
Thanks @stpaultim 👍 

I have reviewed the code, and it LTM; but I am hesitant to mark RTBC, as I would like a person with more layout/theming experience to have a look.

**Comment by klonos** [comment] 2019-09-20 19:41
...I'm also in support of adding a `Top` region for new flexible templates OOTB. It's easier for novice users to remove pre-configured rows they don't need, rather than figuring out how to add new and configure them to work as expected. UX++

**Comment by stpaultim** [comment] 2019-09-24 02:52
https://github.com/backdrop/backdrop-issues/issues/4081

**Comment by jenlampton** [comment] 2019-09-26 19:50
As discussed in the design/ux meeting today, we are going to try adding the `l-header` and `l-footer` classes as defaults in the region config.

**Comment by stpaultim** [comment] 2019-09-29 02:37
Just tested and unfortunately, in most layouts the l-header and l-footer class is on the header and footer element. The config adds classes to the inner-wrapper, a div immediately inside of the header or footer. I think we need to either stick with my original approach which was to add a l-[element] class to every row or to specifically add them for header and footer rows.

**Comment by stpaultim** [comment] 2019-09-29 03:33
New PR ONLY creates a new class on any header or footer element. I believe that it works, but someone should look at the code to see if there is a better way to write the conditional class. 
https://github.com/backdrop/backdrop/pull/2912/files

I ended up with this:

`    <<?php print $row['element']; ?> data-row-id="<?php print $name; ?>" class="flexible-row <?php print 'l-' . $name;
    if ($row['element'] == 'header' || $row['element'] == 'footer'){print ' l-' . $row['element'];} ?>" <?php print $row['row_id']; ?>>`

**Comment by stpaultim** [comment] 2019-10-03 20:25
@klonos - Just to be sure, did you check/look at the most recent PR. I just noticed that the issue summary was still referencing PR backdrop/backdrop#2887 when the most current PR is backdrop/backdrop#2912

Again, this PR is different from what we discussed in DEV meeting last week for reasons I mentioned in my comments 5 days ago.

**Comment by quicksketch** [comment] 2019-10-06 19:22
Thanks @stpaultim! I think this new approach is a fine compromise. It fixes the immediate problem and it doesn't add weird `l-div` classes. This is subjective, but could we try to make the code look a little cleaner? Maybe something like this:

```
  <?php foreach ($row_data as $name => $row): ?>
    <?php
      $classes = array('flexible-row', 'l-' . $name);
      if ($row['element'] == 'header' || $row['element'] == 'footer') {
        $classes[] = 'l-' . $row['element'];
      }
    ?>
    <<?php print $row['element']; ?> data-row-id="<?php print $name; ?>" class="<?php print implode(' ', $classes); ?>" <?php print $row['row_id']; ?>>
```

**Comment by stpaultim** [comment] 2019-10-06 20:09
I welcome suggestions for my code/php. This looks good, working on it now.

**Comment by stpaultim** [comment] 2019-10-06 20:53
Ready for another look!

**Comment by quicksketch** [comment] 2019-10-06 21:02
Code looks great to me! Could we get a manual visual testing on this to confirm it fixes the issue?

**Comment by quicksketch** [comment] 2019-10-06 22:49
I tested out https://github.com/backdrop/backdrop/pull/2912 manually one more time and it works great. Thanks @stpaultim for your work! Thanks @laryn for reporting. And thanks to  @olafgrabienski
and @klonos for your feedback. :smile: 

I've merged it into 1.x and 1.14.x. Thanks folks!

**Closed by quicksketch** 2019-10-06 22:49 UTC
Labels: status - fixed, status - has pull request, type - bug report
