### ISSUE TITLE
Undefined variable: footer in maintenance-page.tpl.php

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2187] opened 2016-09-15 18:46 UTC
PHP throws the following notice when running update.php:

```
Notice: Undefined variable: footer in include() (line 31 of backdrop/core/themes/seven/templates/maintenance-page.tpl.php).
```

**Comment by quicksketch** [comment] 2016-09-15 21:01
This seems to be an issue caused by switching between 1.x and 1.4.x branches. In 1.4.x, there isn't a `$footer` variable at all in any of the maintenance pages; so I don't think this error could actually occur in 1.4.x.

The PR at https://github.com/backdrop/backdrop/pull/1558, is actually against 1.x, where the `$footer` variable *does* exist, so we shouldn't take it out there. So overall I don't think this is needed. Please reopen if I've misunderstood.

**Comment by jenlampton** [comment] 2017-01-27 00:52
I'm still getting this error on all updates. On a closer inspection of `core/themes/seven/templates/maintenance-page.tpl.php` it does look like there is still a footer in there. Let's kill it.

**Comment by quicksketch** [comment] 2017-02-10 01:20
> On a closer inspection of core/themes/seven/templates/maintenance-page.tpl.php it does look like there is still a footer in there.

There is supposed to be a `$footer` variable in there. We don't want to remove it, we want to make it so that it is always defined. It's worth noting that $footer is also in system/templates/maintenance-page.tpl.php.

I can't reproduce the problem where a notice is thrown. There should always be a variable defined... unless perhaps you're updating from an older version of Backdrop where this variable didn't exist? e.g. a 1.4.0 to 1.6.0 update?

**Comment by quicksketch** [comment] 2017-02-10 01:21
A note instead of killing the variable (which is supposed to be there), we could wrap in a check to match system.module's implementation:

```php
    <?php if (!empty($footer)): ?>
      <footer role="contentinfo">
        <?php print $footer; ?>
      </footer>
    <?php endif; ?>
```

**Comment by quicksketch** [comment] 2017-02-10 01:26
You can see in `backdrop_common_theme()` that a 'footer' variable is supposed to exist:

```php
    // From theme.maintenance.inc.
    'maintenance_page' => array(
      'variables' => array('content' => NULL, 'sidebar' => NULL, 'footer' => NULL, 'show_messages' => TRUE),
      'template' => 'templates/maintenance-page',
    ),
    'update_page' => array(
      'variables' => array('content' => NULL, 'sidebar' => NULL, 'footer' => NULL, 'show_messages' => TRUE),
    ),
    'install_page' => array(
      'variables' => array('content' => NULL, 'sidebar' => NULL, 'footer' => NULL),
    ),
```

But my guess is that if you are upgrading from a version prior to issue #450 being fixed, the theme registry cache doesn't include the default values, so you get the PHP notices the first time update.php is run on those older versions.

**Comment by jenlampton** [comment] 2017-02-13 03:47
If it's supposed to be there, then I like the recommendation to wrap it in a check, like system does. I've updated the PR as recommended:

```php
<?php if (!empty($footer)): ?>
      <footer role="contentinfo">
        <?php print $footer; ?>
      </footer>
    <?php endif; ?>
```

**Comment by quicksketch** [comment] 2017-02-13 03:55
Thanks, merged https://github.com/backdrop/backdrop/pull/1772 for 1.6.1.

**Closed** 2017-02-13 03:55 UTC
Labels: status - has pull request, status - fixed
