### ISSUE TITLE
Upgrade jQuery to 1.12.4

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1362] opened 2015-11-22 23:09 UTC
We are still on [1.11.1](https://github.com/backdrop/backdrop/blob/1.x/core/misc/jquery.js)

[1.11.2 release notes/changelog](https://blog.jquery.com/2014/12/18/jquery-1-11-2-and-2-1-3-released-safari-fail-safe-edition)
[1.11.3 release notes/changelog](https://blog.jquery.com/2015/04/28/jquery-1-11-3-and-2-1-4-released-ios-fail-safe-edition)
[1.12.0 release notes/changelog](https://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released)
[1.12.1 release notes/changelog](https://blog.jquery.com/2016/02/22/jquery-1-12-1-and-2-2-1-released)
[1.12.2 release notes/changelog](https://blog.jquery.com/2016/03/17/jquery-1-12-2-and-2-2-2-released)
[1.12.3 release notes/changelog](https://blog.jquery.com/2016/04/05/jquery-1-12-3-and-2-2-3-released)
[1.12.4 release notes/changelog](https://blog.jquery.com/2016/05/20/jquery-1-12-4-and-2-2-4-released)

**Comment by MrHaroldA** [comment] 2016-03-24 09:06
What about upgrading to v2.x? Or are we still keen on IE7/8/9 support?

On a related note; I get deprecation warnings with 1.11 in Google Chrome:

```
'SVGElement.offsetWidth' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/5724912467574784 for more details.
'SVGElement.offsetHeight' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/5724912467574784 for more details.
```

**Comment by klonos** [comment] 2016-03-24 16:08
>What about upgrading to v2.x?

[FYI](http://blog.jquery.com/2016/03/17/jquery-1-12-2-and-2-2-2-released/): 

> We’ll have a release candidate of jQuery 3.0 very soon.

**Comment by MrHaroldA** [comment] 2016-03-25 11:13
3.0 also doesn't support the ancient IE6/7/8.

**Comment by klonos** [comment] 2016-03-25 12:00
Yeah, I'm not sure where we stand on IE8 support and below. Usage stats all over the internet show a 2% or even less.

**Comment by klonos** [comment] 2016-06-19 00:18
Forgot to post this here, but again FYI: [jQuery 3.0 was released](https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/) on June 9.

**Comment by klonos** [comment] 2016-06-19 00:36
...I'll give this a go once I have some time.

**Comment by klonos** [comment] 2016-06-19 00:37
...lets set a realistic milestone 😄

**Comment by quicksketch** [comment] 2016-09-07 05:08
Let's get ourselves upgraded to the latest 1.x branch at least. That's trivial. I'd like to have more agreements on Dropping IE 8 (#214); I think it's time too but we should have a period for feedback, not last minute before releasing 1.5.0.

**Comment by quicksketch** [comment] 2016-09-07 05:27
PR at https://github.com/backdrop/backdrop/issues/1522

I gave this some basic testing, including posting content, uploading files, CKEditor, admin bar, dialogs, etc. jQuery has been a lot better about API compatibility in recent years so I would be surprised if anything actually broke by this change. However, more user testing would definitely be appreciated:

Website: http://1522.backdrop.backdrop.qa.backdropcms.org
Username: admin
Password: ArNYPaxr

I also found that this version of jQuery must prevent calling a bunch of deprecated methods, because the JavaScript console in Firefox is much quieter now, which is great.

**Comment by olafgrabienski** [comment] 2016-09-07 09:54
Did some basic testing as well: created a custom block and a simple content view and saw no problems so far.

Actually, there were some "Trying to get property of non-object in template_preprocess_node ..." notices, but that's not jQuery related. (Origin of the notices: After I deleted a custom content type, the relevant content was not deleted but missing some information. Is that the expected behaviour in Backdrop?)

**Comment by jenlampton** [comment] 2016-09-09 07:48
Thanks for testing @olafgrabienski ! :) Feel free to change the "Labels" in the right sidebar too. If you think this is good to go, you can add the label for "pr - Reviewed and tested by community" and remove "pr - Needs review".

I also gave this a test, I tested tabledrag in menus, the auto-fills for vertical tabs, the drag-and-drop of layouts, Views Ui, the date picker, and a bunch of other places I thought jQuery might have been in use. This looks good to me, nice work as usual @quicksketch  :)

**Comment by quicksketch** [comment] 2016-09-11 02:11
> Actually, there were some "Trying to get property of non-object in template_preprocess_node ..." notices, but that's not jQuery related.

If this happens on new installs it may be something that changed recently. If this can be reproduced on new installations we should open an issue to get it fixed.

But not jQuery related, so it sounds like this is good for 1.5.0. I'll merge shortly.

**Comment by quicksketch** [comment] 2016-09-11 02:12
Thanks @olafgrabienski and @jenlampton for testing. https://github.com/backdrop/backdrop/pull/1522 has been merged into 1.x for 1.5.0.

**Closed** 2016-09-11 02:11 UTC
Labels: status - fixed
