### ISSUE TITLE
Move page-level contextual menus (e.g. "Edit view") to the "Main content" block

### ISSUE THREAD

**Issue by jdanthinne** [backdrop/backdrop-issues#841] opened 2015-04-01 13:41 UTC
That was very handy, when hovering a Views page/block, to go directly the Views UI and make changes.

**Comment by quicksketch** [comment] 2015-04-01 23:07
These links are still there, though the edit view contextual menu might be further away from the listing than you might expect on pages.

Blocks:
![view-block](https://cloud.githubusercontent.com/assets/100206/6954638/df60afe6-d888-11e4-9bcf-8ee3c88d1f8f.png)

Pages:
![view-page](https://cloud.githubusercontent.com/assets/100206/6954658/0900a59a-d889-11e4-9505-0a5e7bb6225c.png)

Perhaps the problem is the link just isn't where you expected? If so, I think it'd be a good idea to make this issue be about moving the page contextual menu for views away from page level, and instead attempting to put the contextual menu on the "Main content" block, which is where you would probably expect it.

**Comment by jdanthinne** [comment] 2015-04-02 06:44
Damn, you're right, the links were so far from the View itself I didn't notice it! I'll try to see if I can move that closer.

**Comment by quicksketch** [comment] 2015-04-02 06:46
Great. :smile: I updated the title to reflect the issue at hand. I have no idea how difficult this will end up being. Contextual links are notoriously difficult to understand and control.

**Comment by jdanthinne** [comment] 2015-04-02 07:30
Just checked that, and in fact, the contextual is at the right place in the HTML. But as it has a CSS positioning of *absolute*, and as my theme has no parent element with a positioning of *relative* or *fixed* or *absolute*, the positioning is done page-wise.
So, unfortunately, I think this issue depends on the theme you're using. Or we can change the CSS of each provided layout, but I don't if it's a good idea…

**Comment by quicksketch** [comment] 2015-04-02 07:37
That may be good thing. What contextual module expects is to put a "contextual-links-region" class on the area to be affected. I think what's happening here is that contextual module isn't able to add a class to the main content block because it's specifically overridden in system.module. See [block--system--main.tpl.php](https://api.backdropcms.org/api/backdrop/core!modules!system!templates!block--system--main.tpl.php/1) (click View source). I think perhaps we could check if any classes are needed there (such as the contexual class) and add the wrapping div if necessary. We removed it to prevent the unnecessary divitis around content that usually would provide its own wrapper if needed.

**Comment by jdanthinne** [comment] 2015-04-07 08:24
What about https://github.com/jdanthinne/backdrop/commit/8ca2a4ddb4d7210a182c771df531617fbb84ebc6 ? Working for me.

**Comment by quicksketch** [comment] 2015-04-07 22:02
I think that would work in most situations, but you don't necessarily need to put the main content block in the `<main>` area of the page. There's nothing preventing a user from moving the main content into the sidebar region for example, in which case the contextual link will float up to the top right again.

**Comment by jdanthinne** [comment] 2015-04-08 07:17
Then that seems impossible with CSS without a wrapping div around the system-main block. Was there a special reason for removing it in Backdrop, apart from removing unnecessary code and divs?
But Instead of reverting that, could we just do
```html
<div class="<?php print implode(' ', $classes); ?>">
  <?php print render($content); ?>
</div>
```
instead of the current
```html
<?php print render($content); ?>
```
?

**Comment by quicksketch** [comment] 2015-04-10 03:13
I think the suggested code would work. I had thought about making that `<div>` conditional as well:

```php
<?php if ($classes): ?><div class="<?php print implode(' ', $classes); ?>"><?php endif; ?>
  <?php print render($content); ?>
<?php if ($classes): ?></div><?php endif; ?>
```

The general expectation was that this div was almost always going to be redundant/unnecessary, so we removed it to help divitis, but yeah... looks like we need it for contextual links. What do you think about making it conditional like this? Unfortunately it probably won't be quite this easy, we'd need a preprocess function as well to remove default classes like `block--system--main`.

**Comment by jdanthinne** [comment] 2015-04-10 09:54
Conditional approach is good I think. But one thing I don't understand is that the contextual-links-region class is added to the main page wrapper (ie. div class="layout--one-column layout contextual-links-region") and not to this block--system-main…

**Comment by klonos** [comment] 2019-03-24 10:20
Not 100% sure, but this issue might have become moot wit #3615 and/or #2690

**Comment by klonos** [comment] 2019-10-05 09:37
So, with #2690 fixed, the contextual links to edit views have now been moved closer to where it makes sense:

<img width="1219" alt="Screen Shot 2019-10-05 at 7 31 47 pm" src="https://user-images.githubusercontent.com/2423362/66253165-23577680-e7a7-11e9-987e-04de6a783e1a.png">

The contextual links for editing views-provided blocks do still have an issue, but that is discussed in more detail over in #3615. IOW, one down, one left to be fixed.

So, I'm gonna go ahead and close this issue here as duplicate of those two other issues. If I am missing something, please feel free to reopen.

**Closed by klonos** 2019-10-05 09:37 UTC
Labels: status - duplicate
