### ISSUE TITLE
[PS] Add `webp` to default extensions on new image fields (if supported)

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#4998] opened 2021-03-14 13:32 UTC
**Description of the need**

We've added core support for `webp` but when adding a new image field it is not in the list of available extensions by default.

**Proposed solution**

Can we expand this issue to include `webp` extension on new image fields by default (if `webp` is supported on the server)?

**Comment by jenlampton** [comment] 2023-01-19 21:59
This may be a duplicate of (or perhaps related to) https://github.com/backdrop/backdrop-issues/issues/4998 where we are discussing adding a global set of allowed image types.

**Comment by jenlampton** [comment] 2023-01-19 22:29
I just learned that there is no `image` form api element 🤯 so a quick fix is going to need to add better image type support to every image upload field we have in core, individually. :) fun times!

**Comment by herbdool** [comment] 2023-03-01 03:43
My PR on issue #4937 would solve this too https://github.com/backdrop/backdrop/pull/4366 I believe.

**Comment by herbdool** [comment] 2023-05-02 17:04
Closing. This has been addressed by https://github.com/backdrop/backdrop-issues/issues/4937. (Feel free to reopen if you disagree)

**Closed by herbdool** 2023-05-02 17:04 UTC
