### ISSUE TITLE
Admin bar goes off screen on smaller displays

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1404] opened 2015-12-11 19:28 UTC
![flyout](https://cloud.githubusercontent.com/assets/1042283/11753488/5a0e78a2-a013-11e5-85d3-0ca21d2e073e.png)

Related is https://github.com/backdrop/backdrop-issues/issues/1368, figuring out how to let the menu fly to the left.

**Comment by Dinornis** [comment] 2017-05-12 06:39
This is still a problem in 1.7.x-dev

**Comment by BWPanda** [comment] 2022-01-25 08:33
I know this issue is older, and I apologise for not finding it originally before opening my own issue, but I'm going to close this as a duplicate of https://github.com/backdrop/backdrop-issues/issues/4549 as this one hasn't had much recent activity...

**Closed by BWPanda** 2022-01-25 08:33 UTC
Labels: type - bug report, design
